build.gradle

iceberg-core should declare an api dependency on avro. For example, the public class `org.apache.iceberg.PartitionData` extends avro-specific types. In addition, there are public methods that deal with avro types, see `org.apache.iceberg.avro.AvroSchemaUtil`

Build: Declare avro as an api dependency of iceberg-core

---

docs/docs/spark-queries.md

The entries headline was not a headline but the last line of the table in the snapshots output above

[DOCS] Fix header for entries metadata table

---

spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/SparkReadConf.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/SparkSQLProperties.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/source/ColStats.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/source/SparkChangelogScan.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/source/SparkColumnStatistics.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/source/SparkScan.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/source/Stats.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkScan.java

Co-authored-by: Huaxin Gao
Co-authored-by: Karuppayya Rajendran
This PR adds the column stats support, so Iceberg can report column stats to Spark engine for CBO.

Support Spark Column Stats

---

.github/ISSUE_TEMPLATE/iceberg_improvement.yml

similar to #10708 this adds an addtional contributing section to the improvement/feature template

Infra: Improve feature request template

---

core/src/test/java/org/apache/iceberg/TestMetadataTableFilters.java

- Found 2 `MetadataTableType.ALL_DATA_FILES` from the `AGG_FILE_TABLES` set. One of them should be `ALL_DELETE_FILES`.
- Fix unit test as `ALL_DATA_FILES ` and `ALL_DELETE_FILES` should return data/delete manifests in DELETED and ADDED states.
cc @szehon-ho

Core: (unit test) Replace the duplicated ALL_DATA_FILES with ALL_DELETE_FILES

---

flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/sink/shuffle/AggregatedStatisticsTracker.java
flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/sink/shuffle/CompletedStatistics.java
flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/sink/shuffle/DataStatisticsCoordinator.java
flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/sink/shuffle/RangePartitioner.java
flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/sink/shuffle/SketchRangePartitioner.java
flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/sink/shuffle/SketchUtil.java
flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/sink/shuffle/SortKeyUtil.java
flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/sink/shuffle/Fixtures.java
flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/sink/shuffle/TestRangePartitioner.java
flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/sink/shuffle/TestSketchRangePartitioner.java
flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/sink/shuffle/TestSketchUtil.java
flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/sink/shuffle/TestSortKeyUtil.java

- handle empty stats (like no traffic)
- use struct comparator with transformed schema for SortKey
- also added more unit tests.
The next PR after this would be putting everything together in `FlinkSink` and document update.

Flink: a few small fixes or tuning for range partitioner

---

.github/workflows/delta-conversion-ci.yml
.github/workflows/flink-ci.yml
.github/workflows/hive-ci.yml
.github/workflows/java-ci.yml
.github/workflows/publish-snapshot.yml
.github/workflows/spark-ci.yml
README.md
build.gradle
deploy.gradle
hive-runtime/build.gradle
jmh.gradle
site/docs/contribute.md
tasks.gradle

Relates to: https://github.com/apache/iceberg/pull/10474

Core: Drop support for Java 8

---

build.gradle
core/src/test/java/org/apache/iceberg/rest/RESTCatalogServlet.java
gradle/libs.versions.toml

Now that we're on JDK11 we can bump Jetty and the underlying Servlet API being used. Note that this is the latest Jetty version that runs with JDK11

Core: Upgrade Jetty and Servlet API

---

baseline.gradle
build.gradle

Configures the `JavaCompile` tasks to use `options.release = 11` and remove the [no longer necessary](https://github.com/palantir/gradle-baseline?tab=readme-ov-file#compalantirbaseline-release-compatibility) `com.palantir.baseline-release-compatibility` plugin

Build for Java 11

---

core/src/main/java/org/apache/iceberg/util/ParallelIterable.java
core/src/test/java/org/apache/iceberg/util/TestParallelIterable.java

This is a unit test, so can leverage package-private access.

Core: Remove reflection from TestParallelIterable

---

format/spec.md

In the [discuss thread on the dev list](https://lists.apache.org/thread/oohcjfp1vpo005h2r0f6gfpsp6op0qps), there was agreement to deprecate the "File System Tables" scheme for committing metadata. This also updates the spec to note where the scheme is unsafe (object stores and local file systems).

Spec: Deprecate the file system table scheme.

---

api/src/main/java/org/apache/iceberg/UpdatePartitionSpec.java
core/src/main/java/org/apache/iceberg/BaseUpdatePartitionSpec.java
core/src/main/java/org/apache/iceberg/TableMetadata.java
core/src/test/java/org/apache/iceberg/TestTableUpdatePartitionSpec.java

This may be used in cases where we want to add a partition spec but not set the new partition spec as default.
For example, if I want to make sure that there's an unpartitioned spec since I might want to commit specific data to it in some cases, I would first validate that there's an unpartition spec in the table, and if there isn't, I would try to add the unpartitioned spec but not set it as the new default partition spec

Core, API: Add addNonDefaultSpec to UpdatePartitionSpec to not set the new partition spec as default

---

build.gradle

`ScalaCompile` does not respect `options.release` and `-release:11` in the aruments is not enough. Re-adding `sourceCompatibility` + `targetCompatibility` for 11.
Otherwise Java code compiled with ScalaCompile will be generated using the "current" Java version running the Gradle build.

Build: Fix Scala compilation

---

core/src/main/java/org/apache/iceberg/rest/RESTSessionCatalog.java
core/src/main/java/org/apache/iceberg/rest/RESTUtil.java
core/src/test/java/org/apache/iceberg/rest/RESTCatalogAdapter.java

We want to eventually make the namespace separator configurable. In order to do that, all the encoding / decoding should go through `RestUtil.encodeNamespace` and `RestUtil.decodeNamespace`rather than using the Splitter / Joiner

Core: Use encoding/decoding methods for namespaces and deprecate Splitter/Joiner

---

api/src/main/java/org/apache/iceberg/types/Comparators.java
core/src/main/java/org/apache/iceberg/deletes/Deletes.java

extracts DataFileFilter#charSeqEquals logic into Comparators#filePath()

Core: Extract filePath comparator into it's own class

---

api/src/main/java/org/apache/iceberg/io/SupportsRecoveryOperations.java

This change adds a SupportsRecoveryOperations mixin for FileIO which offers a `boolean recoverFile(String path)` API. The purpose of this interface is to enable FileIO implementations to attempt a best effort recovery of a given file in case of corruption cases. This could be used as a primitive in repair functions such as https://github.com/apache/iceberg/pull/10445.
This change also implements this mixin for S3FileIO which will get object versions for the specific object and take the latest non-deleted version. If one is not found, the recoverFile API returns false since this mixin is meant for FileIO to perform a best effort recovery, not neccessarily guarantee recovery since that depends on a lot of factors of the underlying storage configuration.

API: Add SupportsRecoveryOperations mixin for FileIO

---

format/spec.md

Discussion on mailing list: https://lists.apache.org/thread/hss83r1605r8932b94xv9y2wfb9o0yns.

Spec: Clarify identity partition edge cases. 

---

format/spec.md

The angle brackets were without any escapes so docs renderer treated them as HTML. The resulting text on the website looked like an unfinished sentence:
The unified partition type looks like Struct.
Putting the angle brackets in backticks prevent them from being interpreted as HTML. Surrounding names like spec#0, field#1 are also put inside backticks for consistence.

Spec: Fix rendering of unified partition struct

---

docs/docs/aws.md

The following document specifies `my_catalog` as Glue Catalog, but the catalog name for S3 MRAP is set to `test` and they should be `my_catalog` here. 
https://iceberg.apache.org/docs/nightly/aws/#s3-access-points
```
spark-sql --conf spark.sql.catalog.my_catalog=org.apache.iceberg.spark.SparkCatalog \
--conf spark.sql.catalog.my_catalog.warehouse=s3://my-bucket2/my/key/prefix \
--conf spark.sql.catalog.my_catalog.type=glue \
--conf spark.sql.catalog.my_catalog.io-impl=org.apache.iceberg.aws.s3.S3FileIO \
--conf spark.sql.catalog.my_catalog.s3.use-arn-region-enabled=false \
--conf spark.sql.catalog.test.s3.access-points.my-bucket1=arn:aws:s3::123456789012:accesspoint:mfzwi23gnjvgw.mrap \  <= HERE
--conf spark.sql.catalog.test.s3.access-points.my-bucket2=arn:aws:s3::123456789012:accesspoint …
```

Docs: Nit Fix catalog name for S3 MRAP

---

flink/v1.18/flink/src/main/java/org/apache/iceberg/flink/data/RowDataUtil.java
flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/data/RowDataUtil.java
flink/v1.20/flink/src/main/java/org/apache/iceberg/flink/data/RowDataUtil.java

Scheduled for removal in 1.7.0.

Flink: Remove deprecated RowDataUtil.clone method

---

aws/src/integration/java/org/apache/iceberg/aws/AwsIntegTestUtil.java
aws/src/integration/java/org/apache/iceberg/aws/s3/TestS3FileIOIntegration.java
aws/src/main/java/org/apache/iceberg/aws/s3/S3FileIO.java

This change implements the SupportsRecoveryOperations mixin for S3FileIO. The implementation is a best effort recovery which first determines the latest object version, and if that is found, then performs the actual recovery by performing an s3#copy operation.
This can be used as a primitive in repair procedures that the community is working on or even simply work standalone in someone's own logic if they want to correct their table state by recovering files which may have accidentally removed (assuming their bucket has versioning enabled)

AWS: Implement SupportsRecoveryOperations for S3FileIO

---

site/README.md
site/dev/common.sh

The versioned docs are pulled from the remote 'iceberg_docs' repo. When making local changes to versioned docs it seems reasonable to mount some local git branch instead of the remote one so that we can test the changes.
This patch add support for setting a local branch to be mounted for the versioned docs using environment variables.

[Docs, Infra] Mount local versioned doc branch for testing

---

api/src/main/java/org/apache/iceberg/Transaction.java

This PR aims to make the comment content of interface methods in `Transaction` more accurate.

API: Fix JavaDoc typos in `Transaction` API

---

core/src/test/java/org/apache/iceberg/TestMetadataTableFilters.java
core/src/test/java/org/apache/iceberg/TestMetadataTableScans.java

- Found a few minor typos where the right partition key is not set. Coincidentally, they don't break unit tests so it is a bit tricky to detect.
- Fix comments on partition values
cc @szehon-ho @RussellSpitzer Please take a look for me, thanks!

Core: (unit test) Set partition to the right PartitionKey

---

.palantir/revapi.yml
core/src/main/java/org/apache/iceberg/AllManifestsTable.java
core/src/main/java/org/apache/iceberg/AllManifestsTableTaskParser.java
core/src/main/java/org/apache/iceberg/BaseEntriesTable.java
core/src/main/java/org/apache/iceberg/BaseFilesTable.java
core/src/main/java/org/apache/iceberg/FilesTableTaskParser.java
core/src/main/java/org/apache/iceberg/GenericManifestFile.java
core/src/main/java/org/apache/iceberg/ManifestEntriesTableTaskParser.java
core/src/main/java/org/apache/iceberg/ManifestFileParser.java
core/src/main/java/org/apache/iceberg/ScanTaskParser.java
core/src/main/java/org/apache/iceberg/TableMetadata.java
core/src/main/java/org/apache/iceberg/hadoop/HadoopFileIO.java
core/src/main/java/org/apache/iceberg/io/FileIOParser.java
core/src/main/java/org/apache/iceberg/util/PartitionUtil.java
core/src/test/java/org/apache/iceberg/TestAllManifestsTableTaskParser.java
core/src/test/java/org/apache/iceberg/TestFilesTableTaskParser.java
core/src/test/java/org/apache/iceberg/TestManifestFileParser.java

This completes the JSON parser for scan task. These scan tasks are for metadata tables.
This would unblock Flink to switch to FLIP-27 source as the default. Flink unit tests pass  with FLIP-27 as default, except for one test with limit clause (which I would follow up separately).
close issue #9597 .

 Core: add JSON serialization for BaseFilesTable.ManifestReadTask, AllManifestsTable.ManifestListReadTask, and BaseEntriesTable.ManifestReadTask

---

core/src/main/java/org/apache/iceberg/TableMetadata.java
core/src/test/java/org/apache/iceberg/TestFormatVersions.java
core/src/test/java/org/apache/iceberg/TestTableMetadata.java
core/src/test/java/org/apache/iceberg/TestUpdateRequirements.java

Fixes https://github.com/apache/iceberg/issues/10763.
Validates metadata format upgrade paths:
- (OK) V1 -> V2
- (OK) V2 -> V3
- (OK) V1 -> V3
- internally represented as V1->V2->V3
Adds logic for multi-version upgrades to internally execute as a stepwise upgrade so that non-incremental upgrade paths do not need to be explicitly maintained

Core: V3 Metadata Upgrade Validation and Testing

---

open-api/rest-catalog-open-api.yaml

This change clarifies in the REST Spec that server implementations for commit endpoints should fail with 400
for any unknown requirements/updates. This ensures that server implementations should *not* ignore table change or requirement to ensure correctness guarantees for implementations.
The default implementation already fails for unknown [updates](https://github.com/apache/iceberg/blob/main/core/src/main/java/org/apache/iceberg/MetadataUpdateParser.java#L316-L317) and [requirements](https://github.com/apache/iceberg/blob/main/core/src/main/java/org/apache/iceberg/UpdateRequirementParser.java#L182-L183).

OpenAPI: Clarify in REST spec that server implementations of commit endpoints must fail with 400 for unknown requirements/updates

---

aws/src/main/java/org/apache/iceberg/aws/s3/S3OutputStream.java

If a user didn't call close on the stream the file shouldn't be uploaded.
This means that if the user forgets to call `close()` on a completed file it will no longer be uploaded. However, this is preferred to having files which were intentionally not closed being uploaded and creating garbage.

AWS: Don't complete multipart upload on finalize for S3OutputStream

---

core/src/main/java/org/apache/iceberg/util/ParallelIterable.java

As part of the change in commit
7831a8dfc3a2de546ca069f4fc1e7afd03777554, queue low water mark was introduced. However, it resulted in increased number of manifests being read when planning LIMIT queries in Trino Iceberg connector. To avoid increased I/O, back out the change for now.

Core: Drop ParallelIterable's queue low water mark

---

core/src/main/java/org/apache/iceberg/util/ParallelIterable.java

As part of the change in commit
7831a8dfc3a2de546ca069f4fc1e7afd03777554, queue low water mark was introduced. However, it resulted in increased number of manifests being read when planning LIMIT queries in Trino Iceberg connector. To avoid increased I/O, back out the change for now.
This is cherry pick of https://github.com/apache/iceberg/pull/10978 into 1.6.x branch

[1.6] Core: Drop ParallelIterable's queue low water mark

---

aws/src/test/java/org/apache/iceberg/aws/s3/TestS3FileIO.java
core/src/main/java/org/apache/iceberg/io/ResolvingFileIO.java

When `ResolvingFileIo` is invoked without conf set (which can happen when catalog or fileIo is explicitly created), it throws NPE. 
```
at org.apache.iceberg.io.ResolvingFileIO.lambda$io$1(ResolvingFileIO.java:179)
at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
at org.apache.iceberg.io.ResolvingFileIO.io(ResolvingFileIO.java:176)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at …
```

Core,AWS: Fix NPE in ResolvingFileIO when HadoopConf is not set

---

spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/actions/TestCreateActions.java

Before this fix, `HiveCatalog` is loaded instead of `HadoopCatalog` due to spark sql config is not cleared up after each test in `TestCreateActions`.
After the correct catalog is loaded, more migrate tests need to be skipped for `HadoopCatalog`.
cc @chinmay-bhat @nastra

Spark 3.5: Fix incorrect catalog loaded in TestCreateActions

---

flink/v1.18/flink/src/main/java/org/apache/iceberg/flink/source/IcebergSource.java
flink/v1.18/flink/src/main/java/org/apache/iceberg/flink/source/reader/AvroGenericRecordConverter.java
flink/v1.18/flink/src/main/java/org/apache/iceberg/flink/source/reader/AvroGenericRecordReaderFunction.java
flink/v1.18/flink/src/main/java/org/apache/iceberg/flink/source/reader/ConverterReaderFunction.java
flink/v1.18/flink/src/main/java/org/apache/iceberg/flink/source/reader/IcebergSourceSplitReader.java
flink/v1.18/flink/src/main/java/org/apache/iceberg/flink/source/reader/RowDataConverter.java
flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/source/TestIcebergSourceBoundedGenericRecord.java
flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/source/IcebergSource.java
flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/source/reader/AvroGenericRecordConverter.java
flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/source/reader/AvroGenericRecordReaderFunction.java
flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/source/reader/ConverterReaderFunction.java
flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/source/reader/IcebergSourceSplitReader.java
flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/source/reader/RowDataConverter.java
flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/source/TestIcebergSourceBoundedGenericRecord.java

Flink: backport PR #10956 for converter interface that deprecates ReaderFunction

---

flink/v1.18/flink/src/main/java/org/apache/iceberg/flink/FlinkCatalogFactory.java
flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/CatalogTestBase.java
flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/SqlBase.java
flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/TestFlinkTableSink.java
flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/TestFlinkTableSinkExtended.java
flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/TestIcebergConnector.java
flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSink.java
flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkBase.java
flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkDistributionMode.java
flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkExtended.java
flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/source/TestIcebergSpeculativeExecutionSupport.java

1.20 porting is not needed as the 1.20 code was based on the hash that already included PR #10777.
This is a clean port except for two places (called out in comments) that are changed when 1.19 was introduced. with the refactoring and porting, now they are needed for 1.18

Flink: backport PR #10777 from 1.19 to 1.18 for sink test refactoring.

---

flink/v1.18/flink/src/main/java/org/apache/iceberg/flink/FlinkConfParser.java
flink/v1.18/flink/src/main/java/org/apache/iceberg/flink/FlinkWriteConf.java
flink/v1.18/flink/src/main/java/org/apache/iceberg/flink/FlinkWriteOptions.java
flink/v1.18/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java
flink/v1.18/flink/src/main/java/org/apache/iceberg/flink/sink/shuffle/DataStatisticsOperatorFactory.java
flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkDistributionMode.java
flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkV2.java
flink/v1.20/flink/src/main/java/org/apache/iceberg/flink/FlinkConfParser.java
flink/v1.20/flink/src/main/java/org/apache/iceberg/flink/FlinkWriteConf.java
flink/v1.20/flink/src/main/java/org/apache/iceberg/flink/FlinkWriteOptions.java
flink/v1.20/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java
flink/v1.20/flink/src/main/java/org/apache/iceberg/flink/sink/shuffle/DataStatisticsOperatorFactory.java
flink/v1.20/flink/src/test/java/org/apache/iceberg/flink/TestFlinkTableSinkExtended.java
flink/v1.20/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkDistributionMode.java
flink/v1.20/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkV2.java

it is a clean back port of PR #10859  except that change in `TestFlinkTableSinkExtended` has been included in another back port PR #10965

Flink: backport PR #10859 for range distribution

---

spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/SparkTableUtil.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/actions/NDVSketchUtil.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/actions/TestComputeTableStatsAction.java

While reviewing #10288, I realized we don't have a reliable way to load Iceberg table state as `Dataset` in Spark. We shouldn't use `load(table.name())` as it is not clear if the name already includes the catalog name. This PR extends what we currently do for metadata tables to regular tables.

Spark 3.5: Add utility to load table state reliably

---

aws-bundle/LICENSE
aws-bundle/NOTICE
aws-bundle/build.gradle
aws/src/integration/java/org/apache/iceberg/aws/AwsIntegTestUtil.java
aws/src/integration/java/org/apache/iceberg/aws/s3/TestS3FileIOIntegration.java
build.gradle
kafka-connect/build.gradle

Include `software.amazon.awssdk:http-auth-aws-crt` into iceberg-aws-bundle to enable access to S3 multi-region access points.
Closes #10967

AWS: Include http-auth-aws-crt module into iceberg-aws-bundle

---

docs/mkdocs.yml

ClickHouse is the right name (H should be uppercase): https://clickhouse.com/

Docs: Rename Clickhouse to ClickHouse

---

flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java
flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkWriteResult.java
flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/sink/IcebergFilesCommitter.java
flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/sink/IcebergStreamWriter.java
flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/SimpleDataUtil.java
flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/sink/TestCompressionSettings.java
flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/sink/TestIcebergFilesCommitter.java
flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/sink/TestIcebergStreamWriter.java

Flink: Fix duplicate data with upsert writer in case of aborted checkpoints

---

flink/v1.20/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkManifestUtil.java
flink/v1.20/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java
flink/v1.20/flink/src/main/java/org/apache/iceberg/flink/sink/IcebergCommittable.java
flink/v1.20/flink/src/main/java/org/apache/iceberg/flink/sink/IcebergCommittableSerializer.java
flink/v1.20/flink/src/main/java/org/apache/iceberg/flink/sink/IcebergCommitter.java
flink/v1.20/flink/src/main/java/org/apache/iceberg/flink/sink/IcebergFilesCommitter.java
flink/v1.20/flink/src/main/java/org/apache/iceberg/flink/sink/IcebergSink.java
flink/v1.20/flink/src/main/java/org/apache/iceberg/flink/sink/IcebergSinkWriter.java
flink/v1.20/flink/src/main/java/org/apache/iceberg/flink/sink/IcebergStreamWriter.java
flink/v1.20/flink/src/main/java/org/apache/iceberg/flink/sink/IcebergWriteAggregator.java
flink/v1.20/flink/src/main/java/org/apache/iceberg/flink/sink/ManifestOutputFileFactory.java
flink/v1.20/flink/src/main/java/org/apache/iceberg/flink/sink/SinkUtil.java
flink/v1.20/flink/src/main/java/org/apache/iceberg/flink/sink/WriteResultSerializer.java
flink/v1.20/flink/src/test/java/org/apache/iceberg/flink/sink/SinkTestUtil.java
flink/v1.20/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkV2Base.java
flink/v1.20/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkManifest.java
flink/v1.20/flink/src/test/java/org/apache/iceberg/flink/sink/TestIcebergCommitter.java
flink/v1.20/flink/src/test/java/org/apache/iceberg/flink/sink/TestIcebergFilesCommitter.java
flink/v1.20/flink/src/test/java/org/apache/iceberg/flink/sink/TestIcebergSink.java
flink/v1.20/flink/src/test/java/org/apache/iceberg/flink/sink/TestIcebergSinkBranch.java
flink/v1.20/flink/src/test/java/org/apache/iceberg/flink/sink/TestIcebergSinkV2.java
flink/v1.20/flink/src/test/java/org/apache/iceberg/flink/sink/TestIcebergSinkV2Branch.java

Steps:
```bash
git diff HEAD^ HEAD > /tmp/v1.19.patch
cat /tmp/v1.19.patch | sed "s/v1.19/v1.20/g" > /tmp/v1.20.patch
git apply -3 /tmp/v1.20.patch
```
all files came out `cleanly`

Flink: Backport PR #10179  to Flink 1.20 for v2 sink

---

core/src/main/java/org/apache/iceberg/DeleteFileIndex.java
core/src/main/java/org/apache/iceberg/ManifestGroup.java
core/src/test/java/org/apache/iceberg/DeleteFileIndexTestBase.java

This PR optimizes `ManifestGroup` to only project data file stats if equality deletes are present. Such stats are useless for position deletes as position deletes are either assigned via path lookup or by partition. This is similar to an optimization we performed in distributed planning.

Core: Project data file stats only if there are equality deletes

---

docs/mkdocs.yml

Add entry to the sidebar linking to the official Druid Iceberg tables support.

Docs: Add Druid docs url to sidebar

---

flink/v1.18/flink/src/main/java/org/apache/iceberg/flink/source/IcebergSource.java
flink/v1.18/flink/src/main/java/org/apache/iceberg/flink/source/IcebergTableSource.java
flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/source/TestIcebergSourceBounded.java
flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/source/TestIcebergSourceBoundedSql.java
flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/source/TestIcebergSourceInferParallelism.java
flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/source/TestIcebergSourceSql.java
flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/source/TestIcebergSpeculativeExecutionSupport.java
flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/source/IcebergSource.java
flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/source/IcebergTableSource.java
flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/source/TestIcebergSourceBounded.java
flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/source/TestIcebergSourceBoundedSql.java
flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/source/TestIcebergSourceInferParallelism.java
flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/source/TestIcebergSourceSql.java
flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/source/TestIcebergSpeculativeExecutionSupport.java

This is a clean back port except for `TestIcebergSpeculativeExecutionSupport` due minor differences of Flink APIs  among 1.18, 1.19, 1.20.

Flink: backport PR #10832 of inferring parallelism in FLIP-27 source

---

build.gradle
deploy.gradle
gradle/libs.versions.toml
open-api/README.md
open-api/src/test/java/org/apache/iceberg/rest/RESTCompatibilityKitCatalogTests.java
open-api/src/test/java/org/apache/iceberg/rest/RESTCompatibilityKitSuite.java
open-api/src/test/java/org/apache/iceberg/rest/RESTCompatibilityKitViewCatalogTests.java
open-api/src/testFixtures/java/org/apache/iceberg/rest/RCKUtils.java
open-api/src/testFixtures/java/org/apache/iceberg/rest/RESTCatalogServer.java
open-api/src/testFixtures/java/org/apache/iceberg/rest/RESTServerCatalogAdapter.java
open-api/src/testFixtures/java/org/apache/iceberg/rest/RESTServerExtension.java

This PR adds the ability to run the Catalog Table and View tests against a REST Catalog implementation.  By default, it will run the tests against a local server using the catalog adaptor to proxy to a JDBC backend catalog.
Catalog configurations can be overridden to point to a different catalog implementation or service running externally.

Add REST Compatibility Kit

---

core/src/test/java/org/apache/iceberg/FileGenerationUtil.java
core/src/test/java/org/apache/iceberg/TestFileGenerationUtil.java

This PR makes `FileGenerationUtil`, which is used in benchmarks, generate realistic bounds.
Our current logic always generates 16 random bytes, which causes problems:
- The metrics mode is not respected (none, count, full).
- Bounds may be invalid values (int/long).
- Lower bounds may be actually be greater than upper bounds.
```
byte[] lower = new byte[16];
random().nextBytes(lower);
lowerBounds.put(fieldId, ByteBuffer.wrap(lower));
byte[] upper = new byte[16];
random().nextBytes(upper);
upperBounds.put(fieldId, ByteBuffer.wrap(upper));
```
I ran a few benchmarks that depend on `FileGenerationUtil ` after this change and they seem to run fine. I also added tests.

Core: Generate realistic bounds in benchmarks

---

baseline.gradle
open-api/src/testFixtures/java/org/apache/iceberg/rest/RESTCatalogServer.java
open-api/src/testFixtures/java/org/apache/iceberg/rest/RESTServerExtension.java

The `testFixtures` directories were not included in spotless, this PR adds them to the source targets.

OpenAPI, Build: Apply spotless to testFixtures source code

---

.github/ISSUE_TEMPLATE/iceberg_bug_report.yml
doap.rdf
site/mkdocs.yml
site/nav.yml

Update latest release version to 1.6.1 in the doap and iceberg_bug_report.yml.

Docs: bump latest version to 1.6.1

---

open-api/rest-catalog-open-api.py
open-api/rest-catalog-open-api.yaml

See https://github.com/apache/iceberg/pull/10755
A new update type is required to be able to enable removing inactive partition specs.

OpenAPI: Add RemovePartitionSpecsUpdate REST update type

---

.gitignore

This PR modifies `.gitignore` to include benchmark output folders across all modules, not just `data`. We already have benchmarks in other modules like `core` and it is easy to accidentally commit benchmark output files.

Build: Ignore benchmark output folders across all modules

---

core/src/jmh/java/org/apache/iceberg/AppendBenchmark.java

This PR adds a benchmark for appending data. As shown below, Iceberg is currently very slow when an operation contains many new data files. I'll follow up with a fix separately.
```
Benchmark                    (fast)  (numFiles)  Mode  Cnt   Score   Error  Units
AppendBenchmark.appendFiles    true      500000    ss    5   7.451 ± 0.184   s/op
AppendBenchmark.appendFiles    true     1000000    ss    5  14.646 ± 0.371   s/op
AppendBenchmark.appendFiles    true     2500000    ss    5  36.853 ± 0.798   s/op
AppendBenchmark.appendFiles   false      500000    ss    5   7.556 ± 0.627   s/op
AppendBenchmark.appendFiles   false     1000000    ss    5  14.869 ± 0.286   s/op
AppendBenchmark.appendFiles   false     2500000    ss    5  37.495 ± 1.247   s/op
```

Core: Add benchmark for adding files

---

flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkRangeDistributionBucketing.java
flink/v1.20/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkRangeDistributionBucketing.java

Also started to use the new `DataGeneratorSource` which is only available in 1.19 and after. hence, didn't add the unit test to 1.18.

Flink: add unit tests for range distribution on bucket partition column

---

kafka-connect/build.gradle

This PR disables the build publishing tasks for the `kafka-connect-runtime` project. This project doesn't have any libraries to publish. This should resolve https://github.com/apache/iceberg/issues/11026.

Kafka Connect: Disable publish tasks in runtime project

---

flink/v1.18/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java
flink/v1.18/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkWriteResult.java
flink/v1.18/flink/src/main/java/org/apache/iceberg/flink/sink/IcebergFilesCommitter.java
flink/v1.18/flink/src/main/java/org/apache/iceberg/flink/sink/IcebergStreamWriter.java
flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/sink/TestCompressionSettings.java
flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/sink/TestIcebergFilesCommitter.java
flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/sink/TestIcebergStreamWriter.java
flink/v1.20/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java
flink/v1.20/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkWriteResult.java
flink/v1.20/flink/src/main/java/org/apache/iceberg/flink/sink/IcebergFilesCommitter.java
flink/v1.20/flink/src/main/java/org/apache/iceberg/flink/sink/IcebergStreamWriter.java
flink/v1.20/flink/src/test/java/org/apache/iceberg/flink/sink/TestCompressionSettings.java
flink/v1.20/flink/src/test/java/org/apache/iceberg/flink/sink/TestIcebergFilesCommitter.java
flink/v1.20/flink/src/test/java/org/apache/iceberg/flink/sink/TestIcebergStreamWriter.java

Flink: Backport PR #10526 to v1.18 and v1.20

---

core/src/main/java/org/apache/iceberg/util/ZOrderByteUtils.java

Follow up from https://github.com/apache/iceberg/pull/10583#discussion_r1660623439
Addressing my own comment. 
- Fix the java docs
- Update `intToOrderedBytes` to use `longToOrderedBytes` as it is the same code.
- Use `longToOrderedBytes` for `shortToOrderedBytes` and `tinyintToOrderedBytes` to avoid double casting. 
- Extract common function to new public methods.

Core: Refactor ZOrderByteUtils

---

flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/maintenance/operator/TableChange.java
flink/v1.20/flink/src/main/java/org/apache/iceberg/flink/maintenance/operator/TableChange.java

`./gradlew clean build -x test -x integrationTest --no-build-cache` results in compile warnings on the newly added code.
`iceberg/flink/v1.20/flink/src/main/java/org/apache/iceberg/flink/maintenance/operator/TableChange.java:186: warning: [ImplicitPublicBuilderConstructor] A Builder with a static factory method on the encapsulating class must have a private constructor. Minimizing unnecessary public API prevents future API breaks from impacting consumers. `

Flink: Fix compile warning

---

site/docs/multi-engine-support.md

Since support of Flink 1.20 is not **released** yet, I update the multi-engine-support doc accordingly to avoid confusions.
cc @snazy @pvary @stevenzwu @nastra

Docs: Fix Flink 1.20 support versions

---

build.gradle
gradle/libs.versions.toml

`./gradlew clean build -x test -x integrationTest --no-build-cache` results in compile warnings for open-api module. 
The reason is that new dependencies that are added in https://github.com/apache/iceberg/pull/10908 requires `apigurdian` during `testFixtureCompilation`.
```
+--- org.junit.jupiter:junit-jupiter:5.10.1 -> 5.10.3
|    +--- org.junit:junit-bom:5.10.3
|    |    +--- org.junit.jupiter:junit-jupiter:5.10.3 (c)
|    |    +--- org.junit.jupiter:junit-jupiter-engine:5.10.3 (c)
|    |    +--- org.junit.platform:junit-platform-commons:1.10.3 (c)
|    |    +--- org.junit.platform:junit-platform-engine:1.10.3 (c)
|    |    +--- org.junit.platform:junit-platform-suite-api:1.10.3 (c)
|    |    +--- org.junit.platform:junit-platform-suite-engine:1.10.3 (c)
|    |    +--- …
```

open-api: Fix compile warnings for testFixtures

---

spark/v3.3/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestAddFilesProcedure.java
spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/SparkTableUtil.java
spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/actions/MigrateTableSparkAction.java
spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/actions/SnapshotTableSparkAction.java
spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/procedures/AddFilesProcedure.java
spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/procedures/MigrateTableProcedure.java
spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/procedures/ProcedureInput.java
spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/procedures/SnapshotTableProcedure.java
spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/actions/TestMigrateTableAction.java
spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/actions/TestSnapshotTableAction.java
spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestAddFilesProcedure.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/SparkTableUtil.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/actions/MigrateTableSparkAction.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/actions/SnapshotTableSparkAction.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/procedures/AddFilesProcedure.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/procedures/MigrateTableProcedure.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/procedures/ProcedureInput.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/procedures/SnapshotTableProcedure.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/actions/TestMigrateTableAction.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/actions/TestSnapshotTableAction.java

This back-ports #9274 and #10037
cc @amogh-jahagirdar @nastra

Spark 3.3, 3.4: Parallelize reading files in migrate procedures

---

spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestCreateChangelogViewProcedure.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/procedures/CreateChangelogViewProcedure.java

Throw validation exception in create_changelog_view procedure when table contains unsortable columns and identifier columns are not provided
```
org.apache.spark.sql.AnalysisException: [DATATYPE_MISMATCH.INVALID_ORDERING_TYPE] Cannot resolve "tokens ASC NULLS FIRST" due to data type mismatch: The `sortorder` does not support ordering on type "MAP<STRING, STRING>"
org.apache.spark.sql.catalyst.analysis.package$AnalysisErrorAt.dataTypeMismatch(package.scala:73)
org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis0$5(CheckAnalysis.scala:269)
org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis0$5$adapted(CheckAnalysis.scala:256)
org.apache.spark.sql.catalyst.trees.TreeNode.foreachUp(TreeNode.scala:295) …
```

Spark 3.5: Mandate identifier fields when create_changelog_view for table contain unsortable columns

---

core/src/main/java/org/apache/iceberg/MergingSnapshotProducer.java

After the support for adding data files that belong to multiple specs in #9860, we have to fix resetting `hasNewDataFile`.

Core: Fix setting hasNewDataFile flag in MergingSnapshotProducer

---

site/docs/contribute.md

This PR documents our recommendations for accessing instance variables to improve consistency of the code. This rule is not new and was frequently mentioned by committers during reviews. Documenting it to bring more attention.

Docs: Document accessing instance variables

---

format/spec.md

Even though the indentation in `.md` file was correct,
for website (mkdocs), need to use required syntax for rendering. 
Hence, adjusted it accordingly. 
before:
After:

Spec: Fix rendering of partition stats file spec

---

spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/actions/TestCreateActions.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/actions/TestCreateActions.java

Back-port of #10952
cc @nastra

Spark 3.3, 3.4: Fix incorrect catalog loaded in TestCreateActions

---

open-api/rest-catalog-open-api.py
open-api/rest-catalog-open-api.yaml

Dev list discussion thread for this change: https://lists.apache.org/thread/flmw1qts0hv8n0k4pd9n1nfry322633y
cc @jackye1995 @rdblue @danielcweeks @nastra @amogh-jahagirdar 
ran make install, make lint, make generate, and python3 rest-catalog-open-api.py

Add Scan Planning Endpoints to open api spec

---

kafka-connect/kafka-connect/src/main/java/org/apache/iceberg/connect/channel/Coordinator.java
kafka-connect/kafka-connect/src/main/java/org/apache/iceberg/connect/channel/CoordinatorThread.java
kafka-connect/kafka-connect/src/main/java/org/apache/iceberg/connect/data/RecordConverter.java

This PR aims to improve the handling of coordinator shutdown during sink rebalances, to better ensure only one coordinator is active at a given time. The sink was designed with the assumption that only one coordinator and its tasks are active, to achieve exactly once semantics.
When a rebalance is triggered and `close()` is called on the sink task, here we immediately flag the coordinator as terminated, shut down the commit executor, and await termination from the main sink task thread (instead of from the coordinator thread). Any new table commits attempted by this coordinator will check the terminated flag and fail if set. This doesn't solve all edge cases but should be an improvement to fencing out zombie coordinators.
This PR also updates some exceptions thrown from `RuntimeException` …

Kafka Connect: Stop commits on terminated coordinator

---

site/nav.yml

Add the `Contributing` page to the top level project nav (this was previously hidden under community and difficult to find).
Add a link to the REST Spec, which links the swagger editor using the current baselined REST spec url from github.

Docs: Update Project links to include contributing and REST spec

---

open-api/rest-catalog-open-api.yaml

__NOTE:  this is a formatting change only__
The current open API document has some minor formatting issues related to embedded json examples.  It appears that some formatter regard this indentation as incorrect including:
- https://editor-next.swagger.io/
- https://yamlchecker.com/
Other checkers like https://www.yamllint.com/, do not appear to consider this invalid.
Making these indentation changes works with all the validators.  I would generally not make this change except that the [swagger editor](https://editor-next.swagger.io/?url=https://raw.githubusercontent.com/apache/iceberg/main/open-api/rest-catalog-open-api.yaml) is very useful for reviewing and understanding the rest protocol.

OpenAPI: Fix YAML example and value json formatting

---

core/src/jmh/java/org/apache/iceberg/AppendBenchmark.java
core/src/main/java/org/apache/iceberg/FastAppend.java
core/src/main/java/org/apache/iceberg/MergingSnapshotProducer.java
core/src/main/java/org/apache/iceberg/SnapshotProducer.java
core/src/test/java/org/apache/iceberg/TestBase.java
core/src/test/java/org/apache/iceberg/TestFastAppend.java
core/src/test/java/org/apache/iceberg/TestMergeAppend.java
core/src/test/java/org/apache/iceberg/TestSnapshotProducer.java

This PR optimizes writing metadata for many new files, which is helpful during initial table creation and row-level operations that modify many files.
Benchmark results prior to the changes:
```
Benchmark                    (fast)  (numFiles)  Mode  Cnt   Score   Error  Units
AppendBenchmark.appendFiles    true       50000    ss    5   1.111 ± 0.035   s/op
AppendBenchmark.appendFiles    true      100000    ss    5   2.114 ± 0.049   s/op
AppendBenchmark.appendFiles    true      500000    ss    5  10.144 ± 0.182   s/op
AppendBenchmark.appendFiles    true     1000000    ss    5  20.205 ± 0.388   s/op
AppendBenchmark.appendFiles    true     2500000    ss    5  51.280 ± 3.610   s/op
AppendBenchmark.appendFiles   false       50000    ss    5   1.125 ± 0.084   s/op
AppendBenchmark.appendFiles …
```

Core: Parallelize manifest writing for many new files

---

spark/v3.4/build.gradle
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/actions/ComputeTableStatsSparkAction.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/actions/NDVSketchUtil.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/actions/SparkActions.java
spark/v3.4/spark/src/main/scala/org/apache/spark/sql/stats/ThetaSketchAgg.scala
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/actions/TestComputeTableStatsAction.java

Backport of https://github.com/apache/iceberg/pull/10288
cc: @aokolnychyi @szehon-ho

Spark 3.4: Action to compute table stats

---

flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkRangeDistributionBucketing.java
flink/v1.20/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkRangeDistributionBucketing.java

6 checkpoionts cycles seem to be more stable based on the existing TestFlinkIcebergSinkDistributionMode test.

Flink: Increase the number of checkpoints from 4 to 6 to fix flakiness.

---

spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/SparkTableUtil.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/actions/NDVSketchUtil.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/actions/TestComputeTableStatsAction.java

backport of #10984
@aokolnychyi @karuppayya

Spark 3.4: Add utility to load table state reliably

---

core/src/main/java/org/apache/iceberg/TableMetadata.java
core/src/test/java/org/apache/iceberg/TestTableMetadata.java

Using `TableMetadata.buildFrom(metadata).withMetadataLocation(metadataLocation).build()` would do the following things:
- update `lastUpdatedMillis`
- write a new `metadata-log` entry
However, in `LoadTableResponse` the goal is to only update the metadata location without updating the two mentioned things above.

Core: Update metadata location without updating lastUpdatedMillis

---

.github/workflows/delta-conversion-ci.yml
.github/workflows/flink-ci.yml
.github/workflows/hive-ci.yml
.github/workflows/kafka-connect-ci.yml
.github/workflows/publish-snapshot.yml
.github/workflows/spark-ci.yml
dev/stage-binaries.sh
gradle.properties
kafka-connect/kafka-connect-runtime/src/integration/java/org/apache/iceberg/connect/IntegrationTestBase.java
kafka-connect/kafka-connect-runtime/src/integration/java/org/apache/iceberg/connect/TestContext.java
settings.gradle

This PR creates a separate Kafka Connect CI workflow that runs the Kafka Connect tests, and prevents the Kafka Connect tests from running in other CI workflows.
This PR also  increases the timeout for initializing the Docker containers from the default of 1 minute to 2 minutes in the integration tests, to hopefully alleviate https://github.com/apache/iceberg/issues/11046.

Kafka Connect: separate CI workflow

---

core/src/main/java/org/apache/iceberg/BaseFile.java
core/src/main/java/org/apache/iceberg/GenericDataFile.java
core/src/main/java/org/apache/iceberg/GenericDeleteFile.java
core/src/main/java/org/apache/iceberg/GenericManifestEntry.java
core/src/main/java/org/apache/iceberg/GenericManifestFile.java
core/src/main/java/org/apache/iceberg/ManifestWriter.java
core/src/main/java/org/apache/iceberg/avro/SupportsIndexProjection.java
core/src/test/java/org/apache/iceberg/TestBase.java

This makes projection more generic and reusable for internal types.

Core: Move internal struct projection to SupportsIndexProjection

---

core/src/main/java/org/apache/iceberg/rest/RESTSerializers.java
core/src/main/java/org/apache/iceberg/rest/responses/LoadTableResponse.java
core/src/main/java/org/apache/iceberg/rest/responses/LoadTableResponseParser.java
core/src/test/java/org/apache/iceberg/rest/responses/TestLoadTableResponseParser.java

This introduces an explicit JSON parser for `LoadTableResponse` as a preparation step for standardizing credentials as proposed in https://github.com/apache/iceberg/pull/10722.
Currently, `LoadTableResponse` is relying on reflection to properly do JSON <--> `LoadTableResponse`.
Having an explicit JSON parser has the advantage that the underlying `credentials` can be parsed in a way that gives us more flexiblity and allows to be fully forward/backward compatible when new credentials are being added. 
This currently depends on #11151

Core: Add explicit JSON parser for LoadTableResponse

---

.gitignore

Add the .java-version file to .gitignore, so users can customize their preferred JDK version locally without affecting the project. This can help users who manage multiple JDK versions using Jenv avoid manually switching JDK versions.
@findepi @szehon-ho can you please help review this?I found your commits #3651 and #8300 related to this in the git history. Thanks.

Build: Add .java-version to gitignore.

---

docs/docs/partitioning.md

As an Iceberg newbie, I was very confused by the difference between the partitioning overview and the partition transform spec documentation.  The partitioning overview page seemed to reference a transform named "date".  However, this transform does not actually exist.  Instead "date" was intended to be a pseudo transform demonstrating the possibilities of Iceberg's partition transforms.
This use of "date" pseudo transform resulted in confusion for me as I could not find any such partition transform.  After digging into the spec docs more, I realized the "day" partition transform is the same as this "date" pseudo transform.
This commit updates the doc to use the actual "day" transform and includes a brief explanation.

Docs: Clarified Partition Transform

---

api/src/main/java/org/apache/iceberg/RowDelta.java
core/src/jmh/java/org/apache/iceberg/ReplaceDeleteFilesBenchmark.java
core/src/main/java/org/apache/iceberg/BaseRowDelta.java
core/src/test/java/org/apache/iceberg/TestRowDelta.java

This PR enables query engines to drop rewritten historical deletes in `RowDelta` if they choose to support sync maintenance.
```
Benchmark                                             (numFiles)  Mode  Cnt  Score   Error  Units
ReplaceDeleteFilesBenchmark.replaceDeleteFiles             50000    ss    5  0.823 ± 1.783   s/op
ReplaceDeleteFilesBenchmark.replaceDeleteFiles            100000    ss    5  1.430 ± 0.081   s/op
ReplaceDeleteFilesBenchmark.replaceDeleteFiles            500000    ss    5  2.314 ± 0.396   s/op
ReplaceDeleteFilesBenchmark.replaceDeleteFiles           1000000    ss    5  2.557 ± 1.134   s/op
ReplaceDeleteFilesBenchmark.replaceDeleteFiles           2500000    ss    5  6.141 ± 1.685   s/op
```

API, Core: Enable dropping rewritten delete files in RowDelta

---

format/spec.md

Docs: `field_id` in name serialisation spec should read `field-id`

---

api/src/main/java/org/apache/iceberg/ContentFile.java

ContentFile#path returns CharSequence instead of String. The original intention of this API returning CharSequence was to directly surface Avro UTF8 without any conversion, however for distributed cases the CharSequence needs to be converted into String since CharSequence itself isn't serializable. Furthermore, in terms of naming we tend to use location in other places like manifestListLocation or metadataLocation, also in FileIO. This change performs the following:
1. Deprecate path on ContentFile since callers need to convert the CharSequence to String for the majority of cases. This would be removed from the interface in 2.0
2. Add a String location() API to ContentFile which logically returns the same filePath but it will return String instead. An initial default implementation of …

API: Deprecate ContentFile#path API and add location API which returns String

---

docs/docs/aws.md
docs/mkdocs.yml

AWS have added the support of Iceberg across more engine, Having this in our docs with existing lists, would certainly help in navigation and support.
cc @jackye1995 @amogh-jahagirdar

[Docs] Update AWS docs to add more AWS engines that supports iceberg

---

aws/src/main/java/org/apache/iceberg/aws/s3/S3InputStream.java
aws/src/test/java/org/apache/iceberg/aws/s3/TestFlakyS3InputStream.java
aws/src/test/java/org/apache/iceberg/aws/s3/TestS3InputStream.java
build.gradle
gradle/libs.versions.toml

Fixes #10340 
This is an alternative approach to https://github.com/apache/iceberg/pull/4912/files and https://github.com/apache/iceberg/pull/8221/files#diff-0b632866a3b10fac55c442b08178ec0ac72b3b600878243e15d788a8bd031054
for retrying failures encountered when retrying on the reading of input streams.
This approach defines a `RetryableInputStream` class which will wrap underlying input streams returned by object store APIs.
Upon failures a new stream will be created. Custom exceptions can be passed in, but the default retries are on SocketTimeoutException and SSLException. This change integrates this input stream implementation with S3InputStream, but RetryableINputStream should be able to be used for the other input streams implementations that are provided by Iceberg.
This change …

API, AWS: Retry S3InputStream reads

---

aws/src/main/java/org/apache/iceberg/aws/s3/S3FileIOProperties.java

Fix AWS doc URL in S3FileIOProperties to point to the international version instead of the Chinese version.

AWS: Fix AWS doc URL

---

core/src/main/java/org/apache/iceberg/deletes/BitmapPositionDeleteIndex.java
core/src/main/java/org/apache/iceberg/deletes/PositionDeleteIndex.java
core/src/test/java/org/apache/iceberg/deletes/TestBitmapPositionDeleteIndex.java

This PR adds support for iterating over positions in `PositionDeleteIndex`.

Core: Support iterating over positions in PositionDeleteIndex

---

core/src/main/java/org/apache/iceberg/deletes/BitmapPositionDeleteIndex.java
core/src/main/java/org/apache/iceberg/deletes/PositionDeleteIndex.java
core/src/main/java/org/apache/iceberg/deletes/PositionDeleteIndexUtil.java
core/src/test/java/org/apache/iceberg/deletes/TestBitmapPositionDeleteIndex.java

This PR adds support for merging `PositionDeleteIndex` objects in place without extra objects.

Core: Support merging in PositionDeleteIndex

---

.palantir/revapi.yml
core/src/main/java/org/apache/iceberg/deletes/Deletes.java
core/src/test/java/org/apache/iceberg/deletes/TestPositionFilter.java

Follow up to https://github.com/apache/iceberg/pull/9117.
Prior to that PR, there were two code paths in `DeleteFilter` for applying position deletes: if the number of position deletes were below a certain number, we use the `PositionDeleteIndex` bitmap and otherwise we use a streaming filter. That PR makes it so that we always use the first code path, but did not remove the now unused code for the second code path.
This PR is to remove most of the unused code. It includes removing tests which were only added to test that second code path as well as bugs found in that code path (https://github.com/apache/iceberg/pull/8132). The `streamingFilter` and `streamingMarker` public methods in `Deletes` are not removed but are deprecated; they can be removed in the version after 1.7. However, the …

Core: Remove unused code for streaming position deletes

---

core/src/jmh/java/org/apache/iceberg/PartitionStatsUtilBenchmark.java
core/src/main/java/org/apache/iceberg/BaseScan.java
core/src/main/java/org/apache/iceberg/PartitionStats.java
core/src/main/java/org/apache/iceberg/PartitionStatsUtil.java
core/src/main/java/org/apache/iceberg/Partitioning.java
core/src/main/java/org/apache/iceberg/PartitionsTable.java
core/src/main/java/org/apache/iceberg/util/PartitionUtil.java
core/src/test/java/org/apache/iceberg/FileGenerationUtil.java
core/src/test/java/org/apache/iceberg/TestPartitionStatsUtil.java

Introduced two API's to compute and sort partition stats as per spec. 
- `Iterable<PartitionStats> partitionStats = PartitionStatsUtil.computeStats(table, table.currentSnapshot());`
- `PartitionStatsUtil.sortStats(partitionStats, Partitioning.partitionType(table));`
These will be used by engines integrated with writer to compute and write the partition stats.

Core: Add a util to compute partition stats

---

parquet/src/main/java/org/apache/iceberg/parquet/ParquetSchemaUtil.java
parquet/src/main/java/org/apache/iceberg/parquet/PruneColumns.java

Currently PruneColumns inherits from ParquetTypeVisitor which will only pass Parquet types. Later when we add the support for Variant type, we need to know the column is a Variant type during column pruning. Before logical Variant type is added to Parquet, we can change to inherit from TypeWithSchemaVisitor to have the Iceberg type. #11178 
Existing tests in TestPruneColumns should provide the test coverage so no tests are added.

Parquet: update PruneColumns to inherit from TypeWithSchemaVisitor to have Iceberg type

---

core/src/test/java/org/apache/iceberg/TestFastAppend.java

This test was added in https://github.com/apache/iceberg/pull/11086/. It should use `FastAppend` instead of `MergeAppend`.

[Minor][Test] Fix TestFastAppend.testAddManyFiles()

---

spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/SparkAppenderFactory.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/source/SparkAppenderFactory.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/source/SparkAppenderFactory.java

It is unused currently and Spark integration uses `SparkFileWriterFactory` instead of this.

Spark: Deprecate SparkAppenderFactory

---

core/src/main/java/org/apache/iceberg/rest/CatalogHandlers.java
core/src/test/java/org/apache/iceberg/rest/TestRESTCatalog.java
core/src/test/java/org/apache/iceberg/rest/TestRESTViewCatalog.java

When requesting a pagesize that exceeds the number of namespaces/views/tables from the REST Catalog, it throws an `IndexOutOfBoundsException`. This is due to using `List.subList` with the end-index being set to the page-size. Java's `sublist` doesn't appreciate an end-index bigger than the size of the list.
See https://github.com/apache/iceberg/issues/11142

REST: Handle Requests with Page Sizes Exceeding Available Number of  Namespaces /Tables/Views

---

core/src/main/java/org/apache/iceberg/deletes/BitmapPositionDeleteIndex.java
core/src/main/java/org/apache/iceberg/deletes/Deletes.java
core/src/main/java/org/apache/iceberg/deletes/PositionDelete.java
core/src/main/java/org/apache/iceberg/deletes/PositionDeleteIndex.java
core/src/main/java/org/apache/iceberg/deletes/SortingPositionOnlyDeleteWriter.java
core/src/main/java/org/apache/iceberg/io/FanoutPositionOnlyDeleteWriter.java
core/src/test/java/org/apache/iceberg/TestBase.java
data/src/main/java/org/apache/iceberg/data/BaseDeleteLoader.java
data/src/test/java/org/apache/iceberg/io/TestPartitioningWriters.java

This PR adds support for combing historical position deletes in writers, enabling sync maintenance.

Core: Support combining position deletes during writes

---

aws/src/main/java/org/apache/iceberg/aws/s3/S3FileIO.java
core/src/jmh/java/org/apache/iceberg/metrics/CountersBenchmark.java
core/src/main/java/org/apache/iceberg/BaseDistributedDataScan.java
core/src/main/java/org/apache/iceberg/hadoop/HadoopFileIO.java
core/src/main/java/org/apache/iceberg/util/ThreadPools.java
data/src/main/java/org/apache/iceberg/data/TableMigrationUtil.java
flink/v1.20/flink/src/main/java/org/apache/iceberg/flink/sink/IcebergCommitter.java
flink/v1.20/flink/src/main/java/org/apache/iceberg/flink/sink/IcebergFilesCommitter.java
flink/v1.20/flink/src/main/java/org/apache/iceberg/flink/source/FlinkInputFormat.java
flink/v1.20/flink/src/main/java/org/apache/iceberg/flink/source/IcebergSource.java
flink/v1.20/flink/src/main/java/org/apache/iceberg/flink/source/StreamingMonitorFunction.java
flink/v1.20/flink/src/main/java/org/apache/iceberg/flink/source/enumerator/ContinuousSplitPlannerImpl.java
kafka-connect/kafka-connect/src/main/java/org/apache/iceberg/connect/channel/Coordinator.java
mr/src/main/java/org/apache/iceberg/mr/mapreduce/IcebergInputFormat.java
mr/src/test/java/org/apache/iceberg/mr/TestIcebergInputFormats.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/SparkTableUtil.java

We are currently using Flink's Local Env mode (executing Flink tasks within the local JVM). We are starting many "Flink query Iceberg tasks" sequentially within the lifecycle of a single JVM (which can be considered a long-running service).
After the JVM runs for a while, we can observe a metaspace memory leak. By examining the leaking ClassLoaders, we found that Iceberg's ExecutorService is registered to the ShutdownHook (GC root).
I noticed that these ExecutorServices are actively shut down. Theoretically, they don't need to be registered to the ShutdownHook.

ThreadPools introduce newExitingWorkerPool and newFixedThreadPool for clearer semantics

---

core/src/main/java/org/apache/iceberg/deletes/Deletes.java

This PR deprecates older ways for loading position deletes. Engines should migrate to `DeleteLoader`s that handle concurrency and caching.

Core: Deprecate legacy ways for loading position deletes

---

aws/src/main/java/org/apache/iceberg/aws/AssumeRoleAwsClientFactory.java
aws/src/main/java/org/apache/iceberg/aws/AwsClientFactories.java
aws/src/main/java/org/apache/iceberg/aws/lakeformation/LakeFormationAwsClientFactory.java
aws/src/main/java/org/apache/iceberg/aws/s3/DefaultS3FileIOAwsClientFactory.java
aws/src/main/java/org/apache/iceberg/aws/s3/S3FileIOProperties.java
aws/src/test/java/org/apache/iceberg/aws/s3/TestS3FileIOProperties.java
docs/docs/aws.md

Iceberg workloads which exceed S3's prefix limits will see HTTP 503 (SlowDown) error responses. The ideal customer experience is for Iceberg to retry these 503 errors persistently, such that the workload is able to make progress, and eventually trigger S3 autoscaling.
Customers using Iceberg OSS with S3FileIO leverage the SDK's default retry mechanism, which is limited to 3 retries. We observe in our load tests that 3 retries is insufficient, and these workloads fail almost immediately. This change aims to improve the customer experience by providing configuration parameters for S3 retries and also introduces better defaults to prevent fast failures.
This change is also addressing some of the concerns that were mentioned in a previous pull …

AWS: Set better defaults for S3 retry behaviour

---

format/puffin-spec.md

Follows discussion https://github.com/apache/iceberg/pull/10288#discussion_r1691077522

Puffin: Document stats `ndv` value representation

---

baseline.gradle

In ordinary switch statement, case branches implicitly fall-through to the next one. This is Java's C legacy. Forbid this unless intent is indicated in the code with a comment like `// fall through`.

Build: Forbid implicit case fall-through without a comment and enable couple more recommendable error-prone checks

---

aws/src/main/java/org/apache/iceberg/aws/s3/S3FileIOProperties.java
aws/src/test/java/org/apache/iceberg/aws/TestS3FileIOProperties.java

- In the `iceberg-aws` module, the community has added the following S3 configurations over time:
| S3 configuration | Pull Request |
| ---------------- | ------------- |
| `Signer` configuration | https://github.com/apache/iceberg/pull/7562 |
| `UserAgent` configuration | https://github.com/apache/iceberg/pull/9963 |
| `Retry` configuration | https://github.com/apache/iceberg/pull/11052 |
- As PR https://github.com/apache/iceberg/pull/10198 suggested, calling `builder.overrideConfiguration()` will return a new `ClientOverrideConfiguration` instance and ignore existing overridden configurations.
- However, the previous PR didn't take care of the `Retry` configuration b/c it was introduced only a few days ago.
- Make sure we can apply the following configurations without losing conf …

AWS: Make sure overridden configurations are applied

---

api/src/main/java/org/apache/iceberg/types/Comparators.java
api/src/main/java/org/apache/iceberg/util/UnicodeUtil.java
core/src/test/java/org/apache/iceberg/TestMetricsTruncation.java

Core: Fix UnicodeUtil#truncateStringMax returns malformed string.

---

core/src/main/java/org/apache/iceberg/ManifestReader.java
core/src/main/java/org/apache/iceberg/avro/InternalReader.java
core/src/main/java/org/apache/iceberg/avro/InternalReaders.java
core/src/main/java/org/apache/iceberg/avro/ValueReaders.java
core/src/test/java/org/apache/iceberg/TestManifestReader.java

This adds an Avro reader that produces Iceberg's internal object model and uses `StructLike` rather than Avro's `IndexedRecord`.

Core: Add internal Avro reader

---

format/spec.md

This PR includes the changes to v3 for type promotion. It also includes some changes to introduce `unknown` and `variant` types to show what the type promotion language will be for those types.
I'll remove the type additions before merging. We probably want those in separate commits.

Spec: Add v3 types and type promotion

---

arrow/src/main/java/org/apache/iceberg/arrow/vectorized/parquet/VectorizedColumnIterator.java
arrow/src/main/java/org/apache/iceberg/arrow/vectorized/parquet/VectorizedDictionaryEncodedParquetValuesReader.java
arrow/src/main/java/org/apache/iceberg/arrow/vectorized/parquet/VectorizedPageIterator.java
arrow/src/main/java/org/apache/iceberg/arrow/vectorized/parquet/VectorizedParquetDefinitionLevelReader.java

For fixed width binary, the FixedSizeBinaryXXX readers are actually used.
In `VectorizedArrowReader::read`:
```
case UUID:
case FIXED_WIDTH_BINARY:
case FIXED_LENGTH_DECIMAL:
vectorizedColumnIterator
.fixedSizeBinaryBatchReader()
.nextBatch(vec, typeWidth, nullabilityHolder);
break;
```
This is a follow-up to https://github.com/apache/iceberg/pull/11276.

Arrow: Deprecate unused fixed width binary reader classes

---

api/src/main/java/org/apache/iceberg/expressions/StrictMetricsEvaluator.java
api/src/test/java/org/apache/iceberg/expressions/TestStrictMetricsEvaluator.java
spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestDelete.java

Currently, the `StrictMetricsEvaluator` fails when evaluating expressions with nested columns, causing Spark's `DELETE FROM` statement to throw an exception if the `WHERE` condition uses nested columns as predicates.
The `StrictMetricsEvaluator` requires null count data for columns during evaluation, but the null count data for nested columns collected in the current metadata might be incorrect (see #8611). Therefore, the `StrictMetricsEvaluator` cannot support the evaluation of filters on nested columns.
However, I think we can at least return `ROWS_MIGHT_NOT_MATCH` when encountering filters with nested columns instead of directly throwing exceptions and causing job failures. We are currently alreadt doing this in the evaluation of `startsWith`: …

Api, Spark: Make StrictMetricsEvaluator not fail on nested column predicates

---

aws-bundle/build.gradle
azure-bundle/build.gradle
build.gradle
flink/v1.18/build.gradle
flink/v1.19/build.gradle
flink/v1.20/build.gradle
gcp-bundle/build.gradle
hive-runtime/build.gradle
hive3-orc-bundle/build.gradle
spark/v3.3/build.gradle
spark/v3.4/build.gradle
spark/v3.5/build.gradle

The Iceberg project uses `io.github.goooler.shadow` project which is archived. 
https://github.com/Goooler/shadow?tab=readme-ov-file#gradle-shadow
The old `com.github.johnrengelman.shadow` is now maintained under `com.gradleup.shadow` 
https://github.com/GradleUp/shadow?tab=readme-ov-file#gradle-shadow
So, updating the project to use https://plugins.gradle.org/plugin/com.gradleup.shadow

Build: Use the active shadow plugin

---

core/src/main/java/org/apache/iceberg/BaseOverwriteFiles.java
core/src/main/java/org/apache/iceberg/BaseRewriteFiles.java
core/src/main/java/org/apache/iceberg/FastAppend.java
core/src/main/java/org/apache/iceberg/ManifestFilterManager.java
core/src/main/java/org/apache/iceberg/MergingSnapshotProducer.java
core/src/main/java/org/apache/iceberg/SnapshotProducer.java
core/src/main/java/org/apache/iceberg/actions/RewriteDataFilesCommitManager.java
core/src/main/java/org/apache/iceberg/actions/RewriteFileGroup.java
core/src/main/java/org/apache/iceberg/actions/RewritePositionDeletesGroup.java
core/src/test/java/org/apache/iceberg/TestDeleteFiles.java
hive-metastore/src/test/java/org/apache/iceberg/hive/HiveTableTest.java
nessie/src/test/java/org/apache/iceberg/nessie/TestNessieTable.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/source/SparkPositionDeletesRewrite.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/source/SparkWrite.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/TestFileRewriteCoordinator.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/data/TestHelpers.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestPositionDeletesTable.java

```
Usage of DataFileSet / DeleteFileSet
====================================
Benchmark                                       (numFiles)  Mode  Cnt  Score   Error  Units
ReplaceDeleteFilesBenchmark.replaceDeleteFiles       50000    ss    5  0.892 ± 1.837   s/op
ReplaceDeleteFilesBenchmark.replaceDeleteFiles      100000    ss    5  1.544 ± 0.139   s/op
ReplaceDeleteFilesBenchmark.replaceDeleteFiles      500000    ss    5  2.487 ± 0.542   s/op
ReplaceDeleteFilesBenchmark.replaceDeleteFiles     1000000    ss    5  2.534 ± 1.214   s/op
ReplaceDeleteFilesBenchmark.replaceDeleteFiles     2500000    ss    5  6.490 ± 2.507   s/op
main
=====
Benchmark                                       (numFiles)  Mode  Cnt  Score   Error  Units
ReplaceDeleteFilesBenchmark.replaceDeleteFiles       50000    ss …
```

Core: Switch usage to DataFileSet / DeleteFileSet

---

core/src/main/java/org/apache/iceberg/io/ContentCache.java

This method does only best-effort invalidation and is susceptible to a
race condition. If the caller changed the state that could be cached
(perhaps files on the storage) and calls this method, there is no
guarantee that the cache will not contain stale entries some time after
this method returns. This is a similar problem as the one described at
https://github.com/google/guava/issues/1881. `ContentCache` doesn't use
a Guava Cache, it uses Caffeine. Caffeine offers partial solution to
this issue, but not for `invalidateAll` call.  To avoid accidental
incorrect use of ContentCache, deprecate the `invalidateAll` method,
which can be deceptive for the caller and remove it later.

Core: Deprecate ContentCache.invalidateAll

---

core/src/main/java/org/apache/iceberg/ManifestFilterManager.java
core/src/main/java/org/apache/iceberg/MergingSnapshotProducer.java
core/src/main/java/org/apache/iceberg/SnapshotProducer.java

Core: Rename DeleteFileHolder to PendingDeleteFile / Optimize duplicate data/delete file detection

---

azure/src/main/java/org/apache/iceberg/azure/adlsv2/ADLSFileIO.java
azure/src/main/java/org/apache/iceberg/azure/adlsv2/ADLSLocation.java
azure/src/test/java/org/apache/iceberg/azure/adlsv2/ADLSLocationTest.java
core/src/main/java/org/apache/iceberg/io/ResolvingFileIO.java

Resolves https://github.com/apache/iceberg/issues/10127 by delegating wasb[s] paths to the ADLSFileIO via ResolvingFileIO.
Additionally, I refactored the parsing logic to use java.net.URI because I believe it's clearer.  This also led me to change the invalid URI exception to `IllegalArgumentException` instead of a `ValidationException` b/c this seems more appropriate.

Support wasb[s] paths in ADLSFileIO

---

kafka-connect/kafka-connect/src/main/resources/META-INF/services/org.apache.kafka.connect.sink.SinkConnector

What is [Plugin Discovery](https://kafka.apache.org/documentation.html#connect_plugindiscovery).
When connector is used with kafka version above 3.6 with default plugin.discovery worker configuration there would be a warning
```
org.apache.kafka.connect.runtime.isolation.Plugins","message":"One or more plugins are missing ServiceLoader manifests may not be usable with plugin.discovery=service_load: [
...
Read the documentation at https://kafka.apache.org/documentation.html#connect_plugindiscovery for instructions on migrating your plugins to take advantage of the performance improvements of service_load mode. To silence this warning, set plugin.discovery=only_scan in the worker config.
```

Make connect compatable with kafka plugin.discovery

---

core/src/main/java/org/apache/iceberg/puffin/StandardBlobTypes.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/source/SparkScan.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkScan.java

Updating SparkScan to only read Apache DataSketches

---

kafka-connect/kafka-connect/src/main/java/org/apache/iceberg/connect/IcebergSinkConfig.java
kafka-connect/kafka-connect/src/test/java/org/apache/iceberg/connect/IcebergSinkConfigTest.java

We have a custom wrapper on the ConnectDistributed class which does not match the regex check here. This PR expands the regex to be more generous but is still reasonable, especially considering the properties check afterwards.
Closes an issue in [tabular.io/iceberg-kafka-connect](https://github.com/tabular-io/iceberg-kafka-connect/issues/301)

add checkClassName regex func

---

aws/src/main/java/org/apache/iceberg/aws/s3/S3InputStream.java
aws/src/test/java/org/apache/iceberg/aws/s3/TestFlakyS3InputStream.java
aws/src/test/java/org/apache/iceberg/aws/s3/TestS3InputStream.java

The retry policy for `S3InputStream` reads introduced in https://github.com/apache/iceberg/commit/c0d73f4ef5c16401bdfd62e1745faf2fbbf62177 (https://github.com/apache/iceberg/pull/10433) is not actually re-opening the stream on each retry attempt given that it uses `onFailure` which, as per the [documentation](https://failsafe.dev/javadoc/core/dev/failsafe/PolicyBuilder.html#onFailure-dev.failsafe.event.EventListener-), it is triggered after the whole (retry) policy has failed completely and was unable to produce a successful result, i.e. all retries have been exhausted and failed. With the existing implementation, once a stream fails with something like `SSLException` due to a socket connection reset, the retries will keep failing (due to not actually reopening the stream) and therefore …

AWS: Fix S3InputStream retry policy

---

core/src/main/java/org/apache/iceberg/hadoop/HadoopFileIO.java
core/src/test/java/org/apache/iceberg/hadoop/HadoopFileIOTest.java

This can happen in the FileIOParser serialization and deserialization scenario. FileIOParser doesn't serialize and deserialize the Hadoop configuration. the deserialized io object is not valid because hadoopConf is null. NPE would be throw if newInputFile is called on deserialized object.
This is a blocker for Flink to switch to JSON parser for scan tasks of metadata tables (like manifest etc.)

Core: fix NPE with HadoopFileIO because FileIOParser doesn't serialize Hadoop configuration

---

azure/src/main/java/org/apache/iceberg/azure/adlsv2/ADLSFileIO.java
azure/src/main/java/org/apache/iceberg/azure/adlsv2/ADLSLocation.java
azure/src/test/java/org/apache/iceberg/azure/adlsv2/ADLSLocationTest.java
core/src/main/java/org/apache/iceberg/io/ResolvingFileIO.java

There is a worry that certain Azure file location will not be parsed correctly by the Java URI methods so we are reverting this PR pending more test cases. WASB Support can occur with a different implementation while we wait
Reverts apache/iceberg#11294

Revert "Support wasb[s] paths in ADLSFileIO"

---

docs/docs/flink-queries.md
flink/v1.18/flink/src/main/java/org/apache/iceberg/flink/source/FlinkSource.java
flink/v1.18/flink/src/main/java/org/apache/iceberg/flink/source/IcebergSource.java
flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/source/FlinkSource.java
flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/source/IcebergSource.java
flink/v1.20/flink/src/main/java/org/apache/iceberg/flink/FlinkConfigOptions.java
flink/v1.20/flink/src/main/java/org/apache/iceberg/flink/source/FlinkSource.java
flink/v1.20/flink/src/main/java/org/apache/iceberg/flink/source/IcebergSource.java

SQL config default change is only applied to 1.20.
See the dev ML discussion [here](https://lists.apache.org/api/plain?thread=2r34z5drgkn1fqbvktwfzhr0fj39p3th).

Flink: make FLIP-27 default in SQL and mark the old FlinkSource as deprecated

---

flink/v1.20/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java
flink/v1.20/flink/src/main/java/org/apache/iceberg/flink/sink/IcebergSink.java
flink/v1.20/flink/src/main/java/org/apache/iceberg/flink/sink/IcebergSinkBuilder.java

This PR extracts the concept of `IcebergSinkBuilder` interface from the #11219. This interface will be used to avoid code duplication in tests and to keep the interface of both implemenations of sinks similar for easier transition between them.

Flink: Add IcebergSinkBuilder interface allowed unification of most of operations on FlinkSink and IcebergSink Builders

---

core/src/main/java/org/apache/iceberg/avro/AvroWithPartnerVisitor.java
core/src/main/java/org/apache/iceberg/avro/ValueReaders.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/data/SparkAvroReader.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/data/SparkPlannedAvroReader.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/data/SparkValueReaders.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/source/BaseRowReader.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/data/TestSparkAvroEnums.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/data/TestSparkAvroReader.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestDataFrameWrites.java

Moving to the planned reader adds default value support. This is the same basic change as in #9366 and #11108.

Spark 3.5: Update Spark to use planned Avro reads

---

spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestViews.java

We already randomize some of the view names for testing but not all of them. This is in preparation for adding view support to `SparkSessionCatalog` and running `TestViews` against that catalog

Spark: Randomize view/function names in testing

---

spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/SparkContentFile.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/actions/RemoveDanglingDeletesSparkAction.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/actions/RewriteDataFilesSparkAction.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/actions/SparkActions.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/actions/TestRemoveDanglingDeleteAction.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteDataFilesAction.java

backport of #9724 to spark 3.4

Spark 3.4: Action to remove dangling deletes

---

spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestCompressionSettings.java

When running `TestCompressionSettings#testWriteDataWithDifferentSetting()`, we want to reset the Spark configuration between tests to ensure that previous settings do not influence subsequent ones. For instance, consider the following scenarios:
The first configuration uses:
```
ImmutableMap.of(COMPRESSION_CODEC, "zstd", COMPRESSION_LEVEL, "1")
```
The second configuration uses:
```
ImmutableMap.of(COMPRESSION_CODEC, "gzip")
```
Currently, the configuration does not reset, so the second setting unexpectedly retains the `COMPRESSION_LEVEL` from the first setting, resulting in `COMPRESSION_CODEC, "gzip", COMPRESSION_LEVEL, "1"`. This can lead to unexpected behavior.

Reset Spark Conf for each test in TestCompressionSettings

---

aws/src/integration/java/org/apache/iceberg/aws/AwsIntegTestUtil.java
aws/src/integration/java/org/apache/iceberg/aws/glue/GlueTestBase.java
aws/src/integration/java/org/apache/iceberg/aws/s3/TestS3FileIOIntegration.java
aws/src/integration/java/org/apache/iceberg/aws/s3/TestS3MultipartUpload.java
aws/src/main/java/org/apache/iceberg/aws/s3/S3FileIO.java
aws/src/main/java/org/apache/iceberg/aws/s3/S3FileIOProperties.java
aws/src/main/java/org/apache/iceberg/aws/s3/S3URI.java
aws/src/test/java/org/apache/iceberg/aws/TestS3FileIOProperties.java
aws/src/test/java/org/apache/iceberg/aws/s3/TestS3FileIO.java
aws/src/test/java/org/apache/iceberg/aws/s3/TestS3URI.java

The following cases exist that will cause the integration tests to fail when pointed at an s3 express bucket:
- S3 Express needs a delimiter at the end of the prefix so updating the
tests to cater for that
- File ACLs aren’t supported by S3 Express
- S3 Express doesn't have versioning support
- KMS/custom encryption isn’t supported by S3 Express.
- Multi-part uploads fail with ‘This bucket does not support Content
Md5 header.’ error.
- updated the prefix to have a "/" this cater for s3 general and
express
- disabled the tests that fail for s3 express that test features
currently not supported
- used the suffix "x-s3 to detect express buckets
- added method to clean s3 express buckets
- Ran s3 integration tests targeting general s3 bucket on my account
- Ran s3 integration tests targeting …

AWS: Support S3 directory bucket listing

---

core/src/main/java/org/apache/iceberg/rest/RESTSerializers.java
core/src/main/java/org/apache/iceberg/rest/responses/LoadCredentialsResponse.java
core/src/main/java/org/apache/iceberg/rest/responses/LoadCredentialsResponseParser.java
core/src/main/java/org/apache/iceberg/rest/responses/LoadTableResponseParser.java
core/src/main/java/org/apache/iceberg/rest/responses/LoadViewResponseParser.java
core/src/test/java/org/apache/iceberg/rest/responses/TestLoadCredentialsResponseParser.java

This implements the spec changes from https://github.com/apache/iceberg/pull/11281

Core: Add LoadCredentialsResponse class/parser

---

kafka-connect/build.gradle
kafka-connect/kafka-connect-runtime/LICENSE
kafka-connect/kafka-connect-runtime/NOTICE

This PR includes third party licenses and notices in the Kafka Connect sink distribution archives.
The third party licenses and notices were generated using the Gradle License Report [plugin](https://github.com/jk1/Gradle-License-Report), along with a custom report renderer. This is the same plugin used to generate the license and notice files for the AWS, GCP, and Azure bundles. The plugin scans jar and pom file dependencies for license and notice information.
(We might want to consider adding this plugin to the build so we can regenerate the license and notice files more easily.)

Kafka Connect: Include third party licenses and notices in distribution

---

pig/src/main/java/org/apache/iceberg/pig/IcebergPigInputFormat.java
pig/src/main/java/org/apache/iceberg/pig/IcebergStorage.java
pig/src/main/java/org/apache/iceberg/pig/PigParquetReader.java
pig/src/main/java/org/apache/iceberg/pig/SchemaUtil.java

As discussed on the dev mailing list (https://lists.apache.org/thread/mw0v24nj9h7b0wyrbw7gn0ldd4m3c8kw), this PR logs a warning to inform the users about deprecation.

Deprecate iceberg-pig

---

spark/v3.5/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/parser/extensions/IcebergSqlExtensionsAstBuilder.scala
spark/v3.5/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/SetWriteDistributionAndOrderingExec.scala
spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestSetWriteDistributionAndOrdering.java
spark/v3.5/spark/src/main/scala/org/apache/spark/sql/catalyst/plans/logical/SetWriteDistributionAndOrdering.scala

As discussed with @aokolnychyi @szehon-ho and @RussellSpitzer in https://github.com/apache/iceberg/pull/10647#issuecomment-2237793353

Spark 3.5: Don't change table distribution when only altering local order

---

format/spec.md

Table of contents in the [spec web page](https://iceberg.apache.org/spec/) is not generated for `spec` and its subsection after https://github.com/apache/iceberg/pull/10948. It is super hard to navigate the spec without the table of contents. 
The reason is mkdocs only consider first H1 for TOC generation. 
More info: https://github.com/squidfunk/mkdocs-material/issues/818
So, keeping spec as H2 and adjusted its sub topics. 
Note that the double # removal is not fully reverted, only added back one # . It is still kept at the same level as expected in the PR#10948
Also locally verified the new table of contents by building it in the `site` directory using `make serve` and hosted at `http://localhost:8000/spec`

Spec: Fix table of content generation

---

core/src/main/java/org/apache/iceberg/SnapshotParser.java
core/src/test/java/org/apache/iceberg/TestSnapshotJson.java

This PR adds additional constraints in the `SnapshotParser` and also includes tests to verify the behaviors.
`Snapshot`'s `summary` field is optional in V1 but required in V2. See https://iceberg.apache.org/spec/#snapshots
When serializing `Snapshot` to `JSON`, if the `summary` field exists, the `operation` key must also exist ([code](https://github.com/apache/iceberg/blob/main/core/src/main/java/org/apache/iceberg/SnapshotParser.java#L63-L66)). In other words, the `summary` field without the `operation` key is considered invalid. 
Note that `operation` is a top-level field in the `Snapshot` class. But when serialized to JSON, the `operation` field is stored in the `summary` map. 
Devlist discussion https://lists.apache.org/thread/h9qmrmlgxh91ol0y2v8olt90b9q6p9xr
Relates to …

Core: Snapshot `summary` map must have `operation` key

---

core/src/main/java/org/apache/iceberg/TableMetadataParser.java

Minor try-with-resources tweak to fix an unclosed stream memory leak I encountered.
More specifically, this occurs when the file is Gzipped and file.newStream().read() throws an exception.
The `GZIPInputStream` constructor calls read on it's input to load the header.
see: https://stackoverflow.com/questions/12552863/correct-idiom-for-managing-multiple-chained-resources-in-try-with-resources-bloc

Core: Update TableMetadataParser to ensure all streams closed

---

core/src/main/java/org/apache/iceberg/FastAppend.java
core/src/main/java/org/apache/iceberg/MergeAppend.java
core/src/main/java/org/apache/iceberg/SnapshotProducer.java
core/src/main/java/org/apache/iceberg/StreamingDelete.java
core/src/test/java/org/apache/iceberg/TestFastAppend.java

There is a comment for FastAppend that mentions the number of commit retries done by the class. I removed it for 2 reasons:
1) Not the FastAppend class does the commit so the commit retries shouldn't be commented there.
2) The number of commit retries is configurable via a table property so mentioning a hard-coded
value in the comment is incorrect.
Added a new test that adjusts the COMMIT_NUM_RETRIES table property. Adjusted existing tests to exercise the boundaries of the number of commit retries.

Core: Remove one comment from FastAppend

---

flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkRangeDistributionBucketing.java
flink/v1.20/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkRangeDistributionBucketing.java

This fixes #11397. cc @stevenzwu

Flink: Fix disabling flaky range distribution bucketing tests

---

spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestDataFrameWrites.java

Spark 3.5: Fix flaky test due to deleting temp directory failure

---

build.gradle

Importing 
`testFixturesImplementation project(':iceberg-core').sourceSets.test.runtimeClasspath`
brings everything to class path and creates problem for shadow jar. 
Need to depend only on required classes.

open-api: Fix testFixtures dependencies

---

core/src/main/java/org/apache/iceberg/BaseFilesTable.java

walking through my old discarded PR and found somewhere we can improve
If you want to take a look ? @szehon-ho @RussellSpitzer

Core: use ManifestFiles.open when possible

---

core/src/main/java/org/apache/iceberg/rest/responses/LoadViewResponse.java
core/src/main/java/org/apache/iceberg/rest/responses/LoadViewResponseParser.java
core/src/test/java/org/apache/iceberg/rest/responses/TestLoadViewResponseParser.java

The original idea why credentials were added to `LoadViewResponse` was to pass back the credentials to the table that the view is referencing. However, we actually want to wait with this until we have the use case fully defined on how this will work and want to remove the functionality for now, as otherwise we'd have to maintain reading/writing credentials in `LoadViewResponse` forever.
We'll we sharing a separate proposal on how to realize this shortly on the mailing list.

Core: Remove credentials from LoadViewResponse

---

open-api/rest-catalog-open-api.py
open-api/rest-catalog-open-api.yaml

The original idea why credentials were added to `LoadViewResponse` was to pass back the credentials to the table that the view is referencing. However, we actually want to wait with this until we have the use case fully defined on how this will work and want to remove the functionality for now, as otherwise we'd have to maintain reading/writing credentials in `LoadViewResponse` forever.
We'll we sharing a separate proposal on how to realize this shortly on the mailing list.

OpenAPI: Remove credentials from LoadViewResult

---

docs/docs/spark-procedures.md

Include documentation update for rewrite_data_files procedure for
#9803 
#9611 
#9724 
@manuzhang @himadripal @singhpk234 @szehon-ho if you are interested

Doc: Update rewrite data files spark procedure

---

core/src/main/java/org/apache/iceberg/deletes/BitmapPositionDeleteIndex.java

This PR migrates `BitmapPositionDeleteIndex` to use `RoaringPositionBitmap` in preparation for DVs. The original PR that added the bitmap had elaborate tests and benchmarks.

Core: Use RoaringPositionBitmap in position index

---

core/src/main/java/org/apache/iceberg/PropertiesUpdate.java
core/src/main/java/org/apache/iceberg/TableMetadata.java
core/src/main/java/org/apache/iceberg/TableProperties.java
core/src/main/java/org/apache/iceberg/util/PropertyUtil.java
core/src/test/java/org/apache/iceberg/TestTransaction.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/sql/TestCreateTable.java

close #11435 
Total of 2 Changes proposed here
1. Add validation for creating new table where commit related table properties need to have value type checked (as integer) and value is non-negative. This apply to following 4 table properties as those are common set of properties to be used on commit for metadata changes
1. commit.retry.num-retries
1. commit.retry.min-wait-ms
1. commit.retry.max-wait-ms
1. commit.retry.total-timeout-ms
1. Relax the constrain of [PendingUpdate](https://github.com/apache/iceberg/blob/main/core/src/main/java/org/apache/iceberg/PropertiesUpdate.java#L100-L114) so that existing table with such corrupted table properties can proceed with correction (see example below)
- ~~achieved by using [NumberUtils::toInt](https://commons.apache.org/proper/commons-lang/apidocs …

Core: Add validation for table commit properties

---

core/src/main/java/org/apache/iceberg/deletes/BitmapPositionDeleteIndex.java
core/src/main/java/org/apache/iceberg/deletes/PositionDeleteIndex.java

This PR adds `cardinality` to `PositionDeleteIndex`.

Core: Add cardinality to PositionDeleteIndex

---

format/puffin-spec.md

This adds a blob type to the Puffin spec that can store a Roaring bitmap delete vector. This is in support of the row-level delete improvements proposed for Iceberg v3.

Puffin: Add delete-vector-v1 blob type

---

api/src/main/java/org/apache/iceberg/DataFile.java
api/src/main/java/org/apache/iceberg/DeleteFile.java
core/src/main/java/org/apache/iceberg/BaseFile.java
core/src/main/java/org/apache/iceberg/BaseScan.java
core/src/main/java/org/apache/iceberg/ContentFileParser.java
core/src/main/java/org/apache/iceberg/FileMetadata.java
core/src/main/java/org/apache/iceberg/GenericDataFile.java
core/src/main/java/org/apache/iceberg/GenericDeleteFile.java
core/src/main/java/org/apache/iceberg/SnapshotProducer.java
core/src/main/java/org/apache/iceberg/V2Metadata.java
core/src/main/java/org/apache/iceberg/V3Metadata.java
core/src/main/java/org/apache/iceberg/util/ContentFileUtil.java
core/src/test/java/org/apache/iceberg/TestBase.java
core/src/test/java/org/apache/iceberg/TestContentFileParser.java
core/src/test/java/org/apache/iceberg/TestManifestEncryption.java
core/src/test/java/org/apache/iceberg/TestManifestReader.java
core/src/test/java/org/apache/iceberg/TestManifestWriterVersions.java

This PR adds `referenced_data_file` to our delete metadata as per the design doc for improving position deletes.
This PR cannot be merged until the vote is closed.

API, Core: Add data file reference to DeleteFile

---

core/src/test/java/org/apache/iceberg/FileGenerationUtil.java

This PR fixes generated position delete file spec. The current logic relies on the current table spec instead of the spec that the referenced data file belongs to.

Core: Fix generated position delete file spec

---

spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/SparkContentFile.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteManifestsAction.java

This PR preserves content offset and size during manifest rewrites.

Spark 3.5: Preserve content offset and size during manifest rewrites

---

spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestDataFrameWrites.java

Follow-up of #10811 to ignore other types of `FileSystemException` like `DirectoryNotEmptyException` as well
```
TestDataFrameWrites > testFaultToleranceOnWrite() > format = parquet FAILED
java.nio.file.DirectoryNotEmptyException: /tmp/junit-7768099913831474039/parquet/test
at java.base/sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:289)
at java.base/sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:104)
at java.base/java.nio.file.Files.delete(Files.java:1152)
at org.apache.commons.io.FileUtils.delete(FileUtils.java:1222)
at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1242)
at org.apache.iceberg.spark.source.TestDataFrameWrites.testFaultToleranceOnWrite(TestDataFrameWrites.java:427)
```
cc @Fokko @nastra

Spark 3.5: Fix flaky test due to temp directory not empty during delete

---

core/src/main/java/org/apache/iceberg/DeleteFileIndex.java
core/src/main/java/org/apache/iceberg/util/ContentFileUtil.java
core/src/test/java/org/apache/iceberg/DeleteFileIndexTestBase.java

This PR adds supports for DVs in `DeleteFileIndex`.

Core: Support DVs in DeleteFileIndex

---

core/src/main/java/org/apache/iceberg/SnapshotSummary.java
core/src/main/java/org/apache/iceberg/metrics/CommitMetricsResult.java
core/src/main/java/org/apache/iceberg/metrics/CommitMetricsResultParser.java
core/src/main/java/org/apache/iceberg/metrics/ScanMetrics.java
core/src/main/java/org/apache/iceberg/metrics/ScanMetricsResult.java
core/src/main/java/org/apache/iceberg/metrics/ScanMetricsResultParser.java
core/src/main/java/org/apache/iceberg/metrics/ScanMetricsUtil.java
core/src/test/java/org/apache/iceberg/TestSnapshotSummary.java
core/src/test/java/org/apache/iceberg/metrics/TestCommitMetricsResultParser.java
core/src/test/java/org/apache/iceberg/metrics/TestScanMetricsResultParser.java
core/src/test/java/org/apache/iceberg/metrics/TestScanReportParser.java

This PR adapts commit, scan, and snapshot stats for DVs.

Core: Adapt commit, scan, and snapshot stats for DVs

---

core/src/main/java/org/apache/iceberg/deletes/SortingPositionOnlyDeleteWriter.java
core/src/main/java/org/apache/iceberg/util/ContentFileUtil.java
spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMergeOnReadDelete.java
spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMergeOnReadUpdate.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/source/SparkBatchQueryScan.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/source/SparkPositionDeltaWrite.java

This change consumes the updated fanout position delete writers in https://github.com/apache/iceberg/pull/11222 to maintain position deletes during writes (_minor compaction_). The mapping of data files to file scoped deletes is broadcasted to executors, where delete file writers merge the historical position deletes with new position deletes. This behavior is behind a Spark conf `maintain-position-deletes` and can also be controlled via the `write.delete.maintain-during-write` table property.
By default this maintenance during write is enabled.
ToDo: UpdateProjectionBenchmark may need to include some changes to use file granularity for MoR cases, so that we can look at the impact of this change before/after. The benchmark should probably be run after …

Spark: Merge new position deletes with old deletes during writing

---

build.gradle
deploy.gradle
open-api/LICENSE
open-api/NOTICE

Since the REST catalog TCK is merged (https://github.com/apache/iceberg/pull/10908), 
we can have a runtime jar from the test fixture which can be used for building the docker image of rest catalog adapter. 
PR for docker image will be raised in the follow up (already working on it)

open-api: Build runtime jar for test fixture

---

flink/v1.18/flink/src/main/java/org/apache/iceberg/flink/source/split/SplitComparators.java
flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/source/assigner/TestFileSequenceNumberBasedSplitAssigner.java
flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/source/split/SplitComparators.java
flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/source/assigner/TestFileSequenceNumberBasedSplitAssigner.java
flink/v1.20/flink/src/main/java/org/apache/iceberg/flink/source/split/SplitComparators.java
flink/v1.20/flink/src/test/java/org/apache/iceberg/flink/source/assigner/TestFileSequenceNumberBasedSplitAssigner.java

`split-open-file-cost` should be `split-file-open-cost`. Or simply use the const variable for constructing the error message. Also updated the test that asserts error message.

Flink: Fix config key typo in error message of SplitComparators

---

api/src/main/java/org/apache/iceberg/Schema.java
api/src/test/java/org/apache/iceberg/TestHelpers.java
api/src/test/java/org/apache/iceberg/TestSchema.java

A lot of our tests are currently very specific but are going to be reused for various other types as they get added. We also currently hard code in the versions we are testing. This makes it a little more difficult whenever we add a new format version to correctly update all of the corresponding tests. 
I'm updating TestSchema to show what I think should be our general pattern for version specific testing where the versions tested are defined in a single location rather than each time per test. 
For the "type" tests, rather than making a named test per type, we parameterize over the type itself so that new types (Geo and Variant) can be added without duplicating code.

API: Removes Explicit Parameterization of Schema Tests

---

core/src/main/java/org/apache/iceberg/util/ContentFileUtil.java
data/src/main/java/org/apache/iceberg/data/BaseDeleteLoader.java
data/src/main/java/org/apache/iceberg/data/DeleteLoader.java
data/src/test/java/org/apache/iceberg/io/TestDVWriters.java

This PR adds support for reading DVs in `BaseDeleteLoader`, the only loader implementation we have.

Core: Support DVs in DeleteLoader

---

docs/docs/spark-ddl.md

This PR simply fix a typo in spark ddl document, the sort order key words should be `ASC/DESC` rather than `ASC/DEC`.

Spark: Fix typo in spark ddl document

---

core/src/main/java/org/apache/iceberg/BaseRowDelta.java
core/src/main/java/org/apache/iceberg/MergingSnapshotProducer.java
core/src/test/java/org/apache/iceberg/DeleteFileIndexTestBase.java
core/src/test/java/org/apache/iceberg/ScanPlanningAndReportingTestBase.java
core/src/test/java/org/apache/iceberg/TestBase.java
core/src/test/java/org/apache/iceberg/TestBatchScans.java
core/src/test/java/org/apache/iceberg/TestCommitReporting.java
core/src/test/java/org/apache/iceberg/TestEntriesMetadataTable.java
core/src/test/java/org/apache/iceberg/TestMetadataTableScans.java
core/src/test/java/org/apache/iceberg/TestMetadataTableScansWithPartitionEvolution.java
core/src/test/java/org/apache/iceberg/TestRewriteFiles.java
core/src/test/java/org/apache/iceberg/TestRewriteManifests.java
core/src/test/java/org/apache/iceberg/TestRowDelta.java
core/src/test/java/org/apache/iceberg/TestSnapshot.java
core/src/test/java/org/apache/iceberg/TestSnapshotSummary.java
data/src/test/java/org/apache/iceberg/io/TestDVWriters.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/TestSparkDistributedDataScanDeletes.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/TestSparkDistributedDataScanReporting.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteManifestsAction.java

This PR adds supports for committing operations with DVs.

Core: Support commits with DVs

---

kafka-connect/build.gradle

This PR removes the exclusion of the woodstox libraries from the Hadoop transitive dependencies when building the Kafka Connect distribution, as they are needed to load Hadoop's `Configuration`.  Previously the required libraries were brought in by the Azure dependencies until that was upgraded in [this commit](https://github.com/apache/iceberg/commit/7ac617a5a8b0dedbaaa6e19caedfd846968c7cac), so the connector did not have any issues.
This addresses https://github.com/apache/iceberg/issues/11489.

Kafka Connect: fix Hadoop dependency exclusion

---

dev/source-release.sh
site/docs/how-to-release.md

Deprecate the use of 
- https://dist.apache.org/repos/dist/dev/iceberg/KEYS
in favor of 
- https://downloads.apache.org/iceberg/KEYS which is an alias for https://dist.apache.org/repos/dist/release/iceberg/KEYS
devlist discussion: https://lists.apache.org/thread/8j41w4y2jx6r3ybj0o82bfyn0npmhgx2

use `dist/release` KEYS

---

core/src/main/java/org/apache/iceberg/BaseContentScanTask.java
core/src/main/java/org/apache/iceberg/BaseFileScanTask.java
core/src/test/java/org/apache/iceberg/TestMetadataTableFilters.java
core/src/test/java/org/apache/iceberg/TestMetadataTableScans.java
data/src/test/java/org/apache/iceberg/data/FileHelpers.java
flink/v1.20/flink/src/test/java/org/apache/iceberg/flink/actions/TestRewriteDataFilesAction.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/actions/TestDeleteReachableFilesAction.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/actions/TestExpireSnapshotsAction.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/actions/TestRemoveDanglingDeleteAction.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/actions/TestRemoveOrphanFilesAction.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/actions/TestRemoveOrphanFilesAction3.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteDataFilesAction.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteManifestsAction.java

This verifies that existing maintenance actions work with format-version=3 and DVs. There are still a few tests like `TestPositionDeletesTable`/ `TestRewritePositionDeleteFiles` that need some additional work, which will be done in a separate PR

Core, Flink, Spark: Verify maintenance actions with DVs

---

spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/SparkReadConf.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/SparkSQLProperties.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/source/SparkChangelogScan.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/source/SparkColumnStatistics.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/source/SparkScan.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/source/Stats.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkScan.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkScan.java

Backport of #10659 & #11035
Currently only Spark Action to Analyze table(#11106) is backported to 3.4, this PR backports changes related to reporting back Column Stats to Spark 3.4 
@huaxingao @karuppayya @szehon-ho can u help review this

Spark 3.4: Support Spark Column Stats

---

azure/src/main/java/org/apache/iceberg/azure/AzureProperties.java
azure/src/main/java/org/apache/iceberg/azure/adlsv2/ADLSLocation.java
azure/src/test/java/org/apache/iceberg/azure/AzurePropertiesTest.java
azure/src/test/java/org/apache/iceberg/azure/adlsv2/ADLSLocationTest.java
core/src/main/java/org/apache/iceberg/io/ResolvingFileIO.java

This is a second attempt to resolve https://github.com/apache/iceberg/issues/10127 but avoids using `java.net.URI` for parsing, which was found to be problematic after the first attempt was merged.
Additionally I've refactored to minimize the number of lines changed and clarify the usage of the `storageAccount` variable, which was previously storing the endpoint host and now will only store the [storage account name](https://learn.microsoft.com/en-us/azure/storage/common/storage-account-overview#standard-endpoints) as the subdomain.

Support WASB scheme in ADLSFileIO

---

site/docs/releases.md

Although the github markdown render works correctly with 2 spaces, mkdocs does not.

Docs: 4 Spaces are Required for Sublists

---

spark/v3.5/spark-extensions/src/jmh/java/org/apache/iceberg/DeleteFileIndexBenchmark.java

This PR adapts our `DeleteFileIndexBenchmark` for DVs.
```
Benchmark                                                           (type)  Mode  Cnt            Score         Error   Units
DeleteFileIndexBenchmark.buildIndexAndLookup                     partition    ss   10            0.475 ±       0.031    s/op
DeleteFileIndexBenchmark.buildIndexAndLookup                          file    ss   10            5.381 ±       0.224    s/op
DeleteFileIndexBenchmark.buildIndexAndLookup                            dv    ss   10            3.612 ±       0.201    s/op
```
The reason partition-scoped deletes are fastest is because the benchmark sets up a table with a small number of deep partitions (50K data files per partition) and only 100 delete files per partition. Therefore, the number of delete …

Spark 3.5: Adapt DeleteFileIndexBenchmark for DVs

---

spark/v3.5/spark/src/jmh/java/org/apache/iceberg/spark/source/DVReaderBenchmark.java

This PR adds `DVReaderBenchmark` that compares the performance of DV and position delete readers.
```
Benchmark                                        (deletedRowsRatio)  (referencedDataFileCount)  Mode  Cnt  Score    Error  Units
DVReaderBenchmark.dv                                           0.01                          5    ss   15  0.001 ±  0.001   s/op
DVReaderBenchmark.dv                                           0.01                         10    ss   15  0.001 ±  0.001   s/op
DVReaderBenchmark.dv                                           0.03                          5    ss   15  0.001 ±  0.001   s/op
DVReaderBenchmark.dv                                           0.03                         10    ss   15  0.001 ±  0.001   s/op
DVReaderBenchmark.dv …
```

Spark 3.5: Add DVReaderBenchmark

---

core/src/main/java/org/apache/iceberg/rest/RESTSessionCatalog.java
core/src/main/java/org/apache/iceberg/rest/RESTUtil.java
core/src/test/java/org/apache/iceberg/rest/RESTCatalogAdapter.java

Reverts apache/iceberg#10858
I'll revert this one for now and do a proper fix for 1.8.0

Revert "Core: Use encoding/decoding methods for namespaces and deprecate Splitter/Joiner"

---

azure/src/main/java/org/apache/iceberg/azure/AzureProperties.java
azure/src/main/java/org/apache/iceberg/azure/adlsv2/ADLSLocation.java
azure/src/test/java/org/apache/iceberg/azure/AzurePropertiesTest.java
azure/src/test/java/org/apache/iceberg/azure/adlsv2/ADLSLocationTest.java
core/src/main/java/org/apache/iceberg/io/ResolvingFileIO.java
core/src/main/java/org/apache/iceberg/rest/RESTSessionCatalog.java
core/src/main/java/org/apache/iceberg/rest/RESTUtil.java
core/src/test/java/org/apache/iceberg/rest/RESTCatalogAdapter.java
kafka-connect/build.gradle

This PR picks the following PRs to the 1.7.x branch, in preparation for the 1.7.1 release:
https://github.com/apache/iceberg/pull/11516
https://github.com/apache/iceberg/pull/11395
https://github.com/apache/iceberg/pull/11504
https://github.com/apache/iceberg/pull/11574

1.7.1rc0 cherry picks

---

core/src/main/java/org/apache/iceberg/hadoop/HadoopTableOperations.java
core/src/test/java/org/apache/iceberg/hadoop/TestHadoopCommits.java

When using HadoopCatalog, renameToFinal would fail with version already exists exception, we should also delete the temp metadata file in this case.

Core: delete temp metadata file when version already exists

---

data/src/main/java/org/apache/iceberg/data/TableMigrationUtil.java
spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestAddFilesProcedure.java
spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMigrateTableProcedure.java
spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestSnapshotTableProcedure.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/SparkTableUtil.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/procedures/MigrateTableProcedure.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/procedures/SnapshotTableProcedure.java

This fixes #11147
cc @nastra @aokolnychyi @zzeekk

Spark 3.5: Fix NotSerializableException when migrating Spark tables

---

azure/src/main/java/org/apache/iceberg/azure/AzureProperties.java
azure/src/main/java/org/apache/iceberg/azure/adlsv2/ADLSLocation.java
azure/src/test/java/org/apache/iceberg/azure/AzurePropertiesTest.java
azure/src/test/java/org/apache/iceberg/azure/adlsv2/ADLSLocationTest.java
core/src/main/java/org/apache/iceberg/io/ResolvingFileIO.java
core/src/main/java/org/apache/iceberg/rest/RESTSessionCatalog.java
core/src/main/java/org/apache/iceberg/rest/RESTUtil.java
core/src/test/java/org/apache/iceberg/rest/RESTCatalogAdapter.java
kafka-connect/build.gradle

This PR picks the following PRs to the 1.7.x branch, in preparation for the 1.7.1 release:
https://github.com/apache/iceberg/pull/11516
https://github.com/apache/iceberg/pull/11395
https://github.com/apache/iceberg/pull/11504
https://github.com/apache/iceberg/pull/11574
This is the same as https://github.com/apache/iceberg/pull/11593 which was squash merged, which we don't want for this.

1.7.0rc0 cherry picks #2

---

hive-metastore/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java
hive-metastore/src/main/java/org/apache/iceberg/hive/HiveViewOperations.java
hive-metastore/src/test/java/org/apache/iceberg/hive/TestHiveCommits.java
hive-metastore/src/test/java/org/apache/iceberg/hive/TestHiveViewCommits.java

bugfix for #11575 
Fixed the problem of mistakenly deleting table snapshot metadata file in the event of unexpected errors, like OutOfMemoryError, during the checkCommitStatus method execution.
While the org.apache.iceberg.hive.HiveViewOperations.checkCurrentMetadataLocation method performs a refresh operation to download and update the current table metadata, this action consumes memory. 
To address this, we now set the commit status to UNKNOWN before checking the commit status, thus preventing inadvertent deletion of snapshot metadata files.

Bugfix for incorrect Deletion of Snapshot Metadata Due to OutOfMemoryError

---

docs/mkdocs.yml

Add a link to the Documentation for the Golang implementation of Iceberg for the iceberg.apache.org website.

Docs: add iceberg-go to doc site

---

spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestChangelogTable.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/source/SparkScanBuilder.java

After upgrading to Iceberg 1.5 and Spark 3.5.1, the `create_changelog_view` procedure occasionally returns records that were inserted outside (before) the specified time range. Specifically:
- When querying for recent changes (e.g. last 10 minutes)
- The view sometimes includes records from 3-5 hours ago
- Re-running the same query returns the expected 0 records
- This inconsistency wasn't present in Iceberg 1.3
Added a unit test `testChangelogViewOutsideTimeRange` to `TestChangelogTable` that:
1. Inserts test records into the table
2. Waits for a time period to ensure those records are "old"
3. Creates a changelog view with a time range that starts *after* the inserts
4. Verifies the view returns 0 records (expected behavior)
5. The test helps validate that records outside the specified …

Spark: Fix changelog table bug for start time older than current snapshot

---

open-api/src/testFixtures/java/org/apache/iceberg/rest/RCKUtils.java
open-api/src/testFixtures/java/org/apache/iceberg/rest/RESTCatalogServer.java
open-api/src/testFixtures/java/org/apache/iceberg/rest/RESTServerExtension.java
spark/v3.5/build.gradle
spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMetadataTables.java
spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRemoveOrphanFilesProcedure.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/CatalogTestBase.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/SparkCatalogConfig.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/TestBaseWithCatalog.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/actions/TestComputeTableStatsAction.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/sql/TestAlterTable.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/sql/TestCreateTable.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/sql/TestRefreshTable.java

For issue: https://github.com/apache/iceberg/issues/11079

Add REST Catalog tests to Spark 3.5 integration test

---

spark/v3.5/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/parser/extensions/IcebergSparkSqlExtensionsParser.scala
spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestBranchDDL.java
spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestTagDDL.java

https://github.com/apache/iceberg/pull/7734 for Spark 3.5

Spark 3.5: Correct the two-stage parsing strategy of antlr parser

---

spark/v3.4/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/parser/extensions/IcebergSparkSqlExtensionsParser.scala
spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestBranchDDL.java
spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestTagDDL.java

As mentioned in https://github.com/antlr/antlr4/issues/192#issuecomment-15238595
> You can save a great deal of time on correct inputs by using a two-stage parsing strategy.
>
> 1. Attempt to parse the input using BailErrorStrategy and PredictionMode.SLL.
>    If no exception is thrown, you know the answer is correct.
> 2. If a ParseCancellationException is thrown, retry the parse using the default
>    settings (DefaultErrorStrategy and PredictionMode.LL).
Iceberg's antlr parser code is derived from Spark, and Spark's one is derived from Presto, the original implementation in Presto is wrong.
It was identified on Spark and got fixed in SPARK-42552 https://github.com/apache/spark/pull/40835
The Iceberg extended syntax is not complicated enough, I suppose this fix does not have …

Spark 3.4: Correct the two-stage parsing strategy of antlr parser

---

dev/source-release.sh
site/docs/how-to-release.md

This cherry-picks https://github.com/apache/iceberg/pull/11526 to the 1.7.x branch.

1.7.x cherry pick #11526

---

docs/docs/configuration.md

In short, HIVE-26882 works for PostgreSQL-based HMS but has correctness issues for MySQL/MariaDB-based HMS, we should emphasize this in Iceberg docs to avoid corrupting users' data. For more tech details, please see conversations in https://issues.apache.org/jira/browse/HIVE-26882

Docs: Mention look-free requires HIVE-28121 for MySQL/MariaDB-based HMS 

---

docs/docs/spark-configuration.md
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/source/IcebergSource.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSourceTablesBase.java

This PR aims to make `IcebergSource extends SessionConfigSupport` to improve the Spark DataSource v2 API coverage.
```
/**
* A mix-in interface for {@link TableProvider}. Data sources can implement this interface to
* propagate session configs with the specified key-prefix to all data source operations in this
* session.
*
* @since 3.0.0
*/
@Evolving
public interface SessionConfigSupport extends TableProvider {
/**
* Key prefix of the session configs to propagate, which is usually the data source name. Spark
* will extract all session configs that starts with `spark.datasource.$keyPrefix`, turn
* `spark.datasource.$keyPrefix.xxx -&gt; yyy` into `xxx -&gt; yyy`, and propagate them to all
* data source operations in this session.
*/
String keyPrefix();
}
```
It allows to set read/write …

Spark 3.4: IcebergSource extends SessionConfigSupport

---

spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/source/IcebergSource.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSourceTablesBase.java

Port https://github.com/apache/iceberg/pull/7732 to Spark 3.5

Spark 3.5: IcebergSource extends SessionConfigSupport

---

spark/v3.3/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/parser/extensions/IcebergSparkSqlExtensionsParser.scala
spark/v3.3/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestBranchDDL.java
spark/v3.3/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestTagDDL.java

https://github.com/apache/iceberg/pull/7734 for Spark 3.3

Spark 3.3: Correct the two-stage parsing strategy of antlr parser

---

docs/docs/flink-writes.md
flink/v1.20/flink/src/main/java/org/apache/iceberg/flink/FlinkConfigOptions.java
flink/v1.20/flink/src/main/java/org/apache/iceberg/flink/IcebergTableSink.java
flink/v1.20/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java
flink/v1.20/flink/src/test/java/org/apache/iceberg/flink/TestFlinkTableSink.java
flink/v1.20/flink/src/test/java/org/apache/iceberg/flink/TestFlinkTableSinkExtended.java

This PR adds a `table.exec.iceberg.use-v2-sink` configuration option allowing to use Flink's Sink v2 API described in the [FLIP-143](https://cwiki.apache.org/confluence/display/FLINK/FLIP-143%3A+Unified+Sink+API) document.
The configuration option is by default set to `false`.
This PR is the follow-up of discussion in #10179 and in #11219

Flink: Add table.exec.iceberg.use-v2-sink option

---

docs/docs/spark-configuration.md

Replace the example with `DataFrameWriterV2` because
https://github.com/apache/iceberg/blob/319f29ea860e42e7cc21cda8c05d882134e6431f/docs/docs/spark-writes.md#L264
This is consistent with other places.

Docs: Use DataFrameWriterV2 in Spark's example

---

docs/docs/spark-writes.md

`WHEN NOT MATCHED BY SOURCE` has been supported in Spark 3.5+ since [1.4.0](https://iceberg.apache.org/releases/#140-release), but most Iceberg users don't know that it is possible because it is not present in the documentation.
This PR adds an example of its usage to Spark writes documentation.

Docs: add `WHEN NOT MATCHED BY SOURCE` to Spark `MERGE INTO` doc

---

.asf.yaml

This PR enables the GitHub feature that automatically deleting the head branch on PR merge.

Build: Delete branch automatically on PR merge

---

flink/v1.20/flink/src/test/java/org/apache/iceberg/flink/data/AbstractTestFlinkAvroReaderWriter.java
flink/v1.20/flink/src/test/java/org/apache/iceberg/flink/data/TestFlinkAvroDeprecatedReaderWriter.java
flink/v1.20/flink/src/test/java/org/apache/iceberg/flink/data/TestFlinkAvroPlannedReaderWriter.java
flink/v1.20/flink/src/test/java/org/apache/iceberg/flink/data/TestRowProjection.java

Following #11386, this PR adds test coverage on both the "new" `FlinkAvroPlannedReader` and the "deprecated" `FlinkAvroReader`.

Flink: Test both "new" Flink Avro planned reader and "deprecated" Avro reader

---

spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestComputeTableStatsProcedure.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/procedures/ComputeTableStatsProcedure.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/procedures/SparkProcedures.java

Backporting the procedure to Spark 3.4 @karuppayya , so that the procedure can be executed in Spark 3.4 too as other changes for Compute Statistics have already been back ported to Spark 3.4.
This is with reference to this PR
https://github.com/apache/iceberg/pull/10986
Kindly review this PR.

Adding ComputeTableStats Procedure to Spark 3.4 

---

flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/FlinkConfigOptions.java
flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/IcebergTableSink.java
flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java
flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/TestFlinkTableSink.java
flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/TestFlinkTableSinkExtended.java

Steps:
```
git diff cb1ad79ca..fa47f3141 flink/v1.20 > /tmp/v1.20.patch
cat /tmp/v1.20.patch | sed "s/v1.20/v1.19/g" > /tmp/v1.19.patch
git apply -3 /tmp/v1.19.patch
```
all files came out cleanly

Flink: Backport #11244 to Flink 1.19 (Add table.exec.iceberg.use-v2-sink option)

---

format/spec.md

Currently, clicking on Javadoc links in the [doc](https://iceberg.apache.org/spec/#metastore-tables) does not navigate to the class page; instead, it remains on the index page. 
For example: https://iceberg.apache.org/javadoc/1.7.0/index.html?org/apache/iceberg/BaseMetastoreTableOperations.html

Doc: Fix some Javadoc URLs.

---

site/docs/blogs.md

Added a blog post that I've written in September. Blog post shows integration with an open source tool, [Nussknacker](https://github.com/TouK/nussknacker) that I'm working on

Docs: Add blog post showing Nussknacker with Iceberg integration

---

docs/docs/kafka-connect.md
kafka-connect/kafka-connect/src/main/java/org/apache/iceberg/connect/IcebergSinkConfig.java
kafka-connect/kafka-connect/src/main/java/org/apache/iceberg/connect/channel/Worker.java

I would like to control the name of the control consumer group to have more fine grained accesses when deploying the Iceberg Sink connector on my infrastructure. 
This PR aims to replace the DEFAULT_CONTROL_GROUP_PREFIX by a configurable variable

Kafka Connect: Add config to prefix the control consumer group

---

flink/v1.18/flink/src/main/java/org/apache/iceberg/flink/data/FlinkPlannedAvroReader.java
flink/v1.18/flink/src/main/java/org/apache/iceberg/flink/data/FlinkValueReaders.java
flink/v1.18/flink/src/main/java/org/apache/iceberg/flink/source/RowDataFileScanTaskReader.java
flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/data/AbstractTestFlinkAvroReaderWriter.java
flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/data/TestFlinkAvroDeprecatedReaderWriter.java
flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/data/TestFlinkAvroPlannedReaderWriter.java
flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/data/TestRowProjection.java
flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/data/FlinkAvroReader.java
flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/data/FlinkPlannedAvroReader.java
flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/data/FlinkValueReaders.java
flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/source/RowDataFileScanTaskReader.java
flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/data/AbstractTestFlinkAvroReaderWriter.java
flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/data/TestFlinkAvroDeprecatedReaderWriter.java
flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/data/TestFlinkAvroPlannedReaderWriter.java
flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/data/TestRowProjection.java

This PR backports the Avro planned reader (and corresponding tests).

Backport Avro planned reader (and corresponding tests) on Flink v1.18 and v1.19

---

docs/docs/risingwave.md
docs/mkdocs.yml

Adds an overview page about RisingWave's support for Iceberg to help developers get started with the RisingWave Iceberg integration.

Docs: Add RisingWave

---

build.gradle
docker/iceberg-rest-adapter-image/Dockerfile
docker/iceberg-rest-adapter-image/README.md
open-api/LICENSE
open-api/NOTICE
open-api/src/testFixtures/resources/log4j.properties

REST: Docker file for REST Fixture

---

core/src/main/java/org/apache/iceberg/BaseMetastoreCatalog.java
core/src/main/java/org/apache/iceberg/Transactions.java
core/src/main/java/org/apache/iceberg/inmemory/InMemoryCatalog.java
core/src/test/java/org/apache/iceberg/catalog/CatalogTests.java
core/src/test/java/org/apache/iceberg/inmemory/TestInMemoryCatalog.java
core/src/test/java/org/apache/iceberg/jdbc/TestJdbcCatalog.java
core/src/test/java/org/apache/iceberg/jdbc/TestJdbcCatalogWithV1Schema.java
core/src/test/java/org/apache/iceberg/rest/TestRESTCatalog.java
hive-metastore/src/test/java/org/apache/iceberg/hive/TestHiveCatalog.java
nessie/src/test/java/org/apache/iceberg/nessie/TestNessieCatalog.java
open-api/src/test/java/org/apache/iceberg/rest/RESTCompatibilityKitCatalogTests.java

fixes https://github.com/apache/iceberg/issues/11664

Core: Propagate custom metrics reporter when table is created/replaced through Transaction

---

spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/BaseBatchReader.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/source/BaseBatchReader.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/source/BaseBatchReader.java

Originally, we have `ReadConfig#generateOffsetToStartPos(Schema schema)` to compute the row offsets of the row groups. This method needs to check if the schema contains ROW_POSITION. https://github.com/apache/iceberg/pull/11520 uses native getRowIndexOffset so we don't need `generateOffsetToStartPos` any more. As a result, we don't need to add ROW_POSITION to the schema any more.

Spark: remove ROW_POSITION from project schema

---

data/src/main/java/org/apache/iceberg/data/DeleteFilter.java
data/src/test/java/org/apache/iceberg/data/DeleteReadTests.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/data/vectorized/ColumnarBatchReader.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/data/vectorized/VectorizedSparkParquetReaders.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkReaderDeletes.java

In Equality Delete, we build `ColumnarBatchReader` for the equality delete filter columns to read their values and determine which rows are deleted. If these filter columns are not among the requested columns, they are considered extra and should be removed before returning the `ColumnBatch` to Spark.
Suppose the table schema includes C1, C2, C3, C4, C5. If the query is: `SELECT C5 FROM table`, and the equality delete filter is on C3 and C4,
We read the values of C3 and C4 to identify which rows are deleted. However, we do not want to include these values in the `ColumnBatch` that we return to Spark.

Spark: Remove extra columns for ColumnBatch

---

core/src/main/java/org/apache/iceberg/rest/RESTSessionCatalog.java

The previous message reported the wrong URI example when the value of `props.get(CatalogProperties.URI)` doesn't end with `/` likes `https://example.com/wsv1/oauth/tokens` (`/` should exist between `ws` and `v1`).

REST: Fix warning message for deprecated OAuth2 server URI

---

.palantir/revapi.yml
core/src/main/java/org/apache/iceberg/hadoop/Util.java

The Apache Hive community is trying to implement optimizations, such as Bucket Map Join, using partition transform specs. We presume `Util::blockLocations` should accept not `CombinedScanTask` but `ScanTaskGroup<FileScanTask>`, which is a more general expression.
See also https://github.com/apache/hive/pull/5409

Core: Generalize Util::blockLocations

---

core/src/main/java/org/apache/iceberg/io/PartitioningDVWriter.java
spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/SparkRowLevelOperationsTestBase.java
spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestDelete.java
spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMerge.java
spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMergeOnReadDelete.java
spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMergeOnReadMerge.java
spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMergeOnReadUpdate.java
spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestUpdate.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/SparkWriteConf.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/source/SparkBatchQueryScan.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/source/SparkPositionDeltaWrite.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/data/TestHelpers.java

This change adds support for writing DVs in SparkPositionDeltaWrite for V3 tables.

Spark: Write DVs for V3 MoR tables

---

docker/iceberg-rest-fixture/Dockerfile

Closes #11688
I have added curl to the docker image. If you want me to adjust the contribution in any way, e.g to also clean up the package cache to save space, let me know.

Added curl to the iceberg rest fixture Docker image #11688

---

.github/workflows/publish-iceberg-rest-fixture-docker.yml

We should also publish the `arm64` arch next to `amd64`. I bumped into this when doing some checks on Iceberg-rust.
Successful run on my fork: https://github.com/Fokko/iceberg/actions/runs/12278801894

docker: Build for `arm64` architecture

---

spark/v3.4/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/analysis/ResolveViews.scala
spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestViews.java
spark/v3.5/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/analysis/ResolveViews.scala
spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestViews.java

This PR Fixed the BUG of iceberg views when resolved "group by ordinals".

Spark3.4,3.5: Fix the BUG of iceberg views when resolved  "group by ordinals"

---

core/src/main/java/org/apache/iceberg/hadoop/HadoopTableOperations.java
core/src/test/java/org/apache/iceberg/hadoop/TestHadoopCatalog.java

Currently, in `HadoopTableOperations` when the metadata file is missing, we can't know where it's located. This PR adds metadata location to the exception message. Besides, a UT is added for metedata file missing.
cc @pvary

Hadoop: Log where the missing metadata file is located

---

gcp/src/main/java/org/apache/iceberg/gcp/gcs/OAuth2RefreshCredentialsHandler.java

The following line uses `java.util.Date`. 
https://github.com/apache/iceberg/blob/a3dcfd19fd1b2a709f7bdf013b83836953d49c6f/gcp/src/main/java/org/apache/iceberg/gcp/gcs/OAuth2RefreshCredentialsHandler.java#L80

GCS: Suppress JavaUtilDate in OAuth2RefreshCredentialsHandler

---

flink/v1.20/flink/src/main/java/org/apache/iceberg/flink/source/reader/RowConverter.java
flink/v1.20/flink/src/test/java/org/apache/iceberg/flink/source/TestIcebergSourceBoundedConverterBase.java
flink/v1.20/flink/src/test/java/org/apache/iceberg/flink/source/TestIcebergSourceBoundedGenericRecord.java
flink/v1.20/flink/src/test/java/org/apache/iceberg/flink/source/TestIcebergSourceBoundedRow.java

Currently we can't create views on top of IcebergSource DataStreams directly. We need to convert the RowData to Row explicitly using map function. I thought creating a RowConverter to convert RowData to Row and return IcebergSource<Row> would be a good idea. This approach enables the use of the Iceberg schema to create a DataStream<Row> and further create a view on top of it. What are your thoughts?

Flink: Add RowConverter for Iceberg Source

---

spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewritePositionDeleteFilesAction.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/sql/PartitionedWritesTestBase.java

Spark 3.5: Fix comment and assertion mismatch in PartitionedWritesTestBase/TestRewritePositionDeleteFilesAction

---

core/src/main/java/org/apache/iceberg/rest/Endpoint.java
core/src/main/java/org/apache/iceberg/rest/RESTSessionCatalog.java
core/src/main/java/org/apache/iceberg/rest/ResourcePaths.java

Noticed there were some definitions missing in the REST Endpoint class (most notably entries for tableExists and the new loadCredentials endpoints).
Added the following definitions in that class:
- tableExists (HEAD 
- loadCredentials
- namespaceExists
- viewExists
- scan plan endpoints (can remove these if don't want to add them yet)
Added the tableExists endpoint to the list of default endpoints.
- should the loadCredentials and namespaceExists endpoints be added as well?
- should the viewExists endpoint be added to the view endpoints list?
It doesn't appear that the REST catalog impl actually uses the namespaceExists or viewExists endpoints and instead falls back to the session and view session catalog impls which loads the namespace/view to check if exists -- is there a reason the …

Core: Add missing REST endpoint definitions

---

core/src/main/java/org/apache/iceberg/SerializableTable.java
core/src/main/java/org/apache/iceberg/TableUtil.java
core/src/test/java/org/apache/iceberg/TestTableUtil.java
core/src/test/java/org/apache/iceberg/catalog/CatalogTests.java
core/src/test/java/org/apache/iceberg/hadoop/TestTableSerialization.java

This is an alternative impl to https://github.com/apache/iceberg/pull/11587

Core: Add TableUtil to provide access to a table's format version

---

spark/v3.4/build.gradle
spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMetadataTables.java
spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRemoveOrphanFilesProcedure.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/rest/RESTServerRule.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/SparkCatalogConfig.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/SparkCatalogTestBase.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/SparkTestBaseWithCatalog.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/actions/TestComputeTableStatsAction.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/sql/TestAlterTable.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/sql/TestCreateTableAsSelect.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/sql/TestNamespaceSQL.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/sql/TestRefreshTable.java

This backports https://github.com/apache/iceberg/pull/11093 to Spark 3.4 as this is required in order to be able to backport the tests to Spark 3.4 of https://github.com/apache/iceberg/pull/11388

Spark 3.4: Add REST catalog to Spark integration tests

---

data/src/test/java/org/apache/iceberg/data/DataTestHelpers.java
data/src/test/java/org/apache/iceberg/data/parquet/TestGenericData.java
parquet/src/main/java/org/apache/iceberg/data/parquet/BaseParquetReaders.java

This adds default value support when reading Parquet files into Iceberg's generic data model.

Parquet: Implement defaults for generic data

---

api/src/main/java/org/apache/iceberg/transforms/Bucket.java
api/src/main/java/org/apache/iceberg/transforms/Dates.java
api/src/main/java/org/apache/iceberg/transforms/Identity.java
api/src/main/java/org/apache/iceberg/transforms/Timestamps.java
api/src/main/java/org/apache/iceberg/transforms/UnknownTransform.java
api/src/main/java/org/apache/iceberg/transforms/VoidTransform.java

Adds some missing deprecations as based in https://github.com/apache/iceberg/pull/11691
Also, copied some deprecations from the interface to the implementations to make it more explicit.

API: Add missing deprecations

---

core/src/test/java/org/apache/iceberg/hadoop/TestHadoopCommits.java
spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestDelete.java
spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMerge.java

This PR attempts to fix following tests failure due to timeout.
#11047
#11066 
#11651

Core, Spark3.5: Fix tests failure due to timeout

---

core/src/main/java/org/apache/iceberg/avro/ValueReaders.java
core/src/main/java/org/apache/iceberg/data/GenericDataUtil.java
core/src/main/java/org/apache/iceberg/data/avro/PlannedDataReader.java
data/src/test/java/org/apache/iceberg/data/DataTest.java
data/src/test/java/org/apache/iceberg/data/DataTestHelpers.java
data/src/test/java/org/apache/iceberg/data/avro/TestGenericData.java
data/src/test/java/org/apache/iceberg/data/parquet/TestGenericData.java
parquet/src/main/java/org/apache/iceberg/data/parquet/BaseParquetReaders.java
parquet/src/main/java/org/apache/iceberg/data/parquet/GenericParquetReaders.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/SparkUtil.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/data/SparkParquetReaders.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/data/SparkPlannedAvroReader.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/source/BaseReader.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/data/AvroDataTest.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/data/TestHelpers.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/data/TestSparkAvroReader.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/data/TestSparkParquetReader.java

This updates the Avro and Parquet readers for Spark and Iceberg's generic data model to produce the expected date/time classes. It also adds a test for primitive type defaults.

Data: Fix Parquet and Avro defaults date/time representation

---

azure/src/main/java/org/apache/iceberg/azure/AzureProperties.java
azure/src/main/java/org/apache/iceberg/azure/adlsv2/ADLSLocation.java
azure/src/test/java/org/apache/iceberg/azure/AzurePropertiesTest.java
azure/src/test/java/org/apache/iceberg/azure/adlsv2/ADLSLocationTest.java
core/src/main/java/org/apache/iceberg/io/ResolvingFileIO.java

There was a breaking change introduced in 1.7.1 when using ADLSFileIO SAS tokens so this reverts apache/iceberg#11504
For more info see this mailing list thread
https://lists.apache.org/thread/xc0ddyjkwdl8rhp072fcydl4rondogx6

Revert "Support WASB scheme in ADLSFileIO"

---

azure/src/main/java/org/apache/iceberg/azure/AzureProperties.java
azure/src/main/java/org/apache/iceberg/azure/adlsv2/ADLSLocation.java
azure/src/test/java/org/apache/iceberg/azure/AzurePropertiesTest.java
azure/src/test/java/org/apache/iceberg/azure/adlsv2/ADLSLocationTest.java
core/src/main/java/org/apache/iceberg/io/ResolvingFileIO.java

This cherry picks the revert PR https://github.com/apache/iceberg/pull/11812 into the 1.7.x branch to fix a breaking change introduced in 1.7.1

[1.7] Revert "Support WASB scheme in ADLSFileIO" 

---

build.gradle
flink/v1.18/flink-runtime/LICENSE
flink/v1.19/flink-runtime/LICENSE
flink/v1.20/flink-runtime/LICENSE
hive-runtime/LICENSE
kafka-connect/kafka-connect-runtime/LICENSE
spark/v3.3/spark-runtime/LICENSE
spark/v3.4/spark-runtime/LICENSE
spark/v3.5/spark-runtime/LICENSE

This change removes unused failsafe from core (it was an oversight to include it in core as part of https://github.com/apache/iceberg/commit/c0d73f4ef5c16401bdfd62e1745faf2fbbf62177#diff-49a96e7eea8a94af862798a45174e6ac43eb4f8b4bd40759b5da63ba31ec3ef7 , we ended up isolating the retry behavior just to AWS). 
For clarity this change also adds Failsafe to the Runtime LICENSE(s) for the runtime artifacts which depend on iceberg-aws just to fall in line with our practice of including dependencies (although it's not required as per https://infra.apache.org/licensing-howto.html#alv2-dep since Failsafe is Apache 2.0 Licensed). 
Note Failsafe has no Notice of its own.

Core, Spark, Flink, Hive: Remove unused failsafe dependency from core and add Failsafe to runtime LICENSE(s)

---

docs/docs/flink.md

All following commands assumes the directory is in flink-${FLINK_VERSION}. Let's update the instructions to make that clear.

Docs: Change to Flink directory for instructions

---

arrow/src/main/java/org/apache/iceberg/arrow/vectorized/VectorizedReaderBuilder.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/data/vectorized/VectorizedSparkParquetReaders.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/data/AvroDataTest.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/data/TestHelpers.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/data/parquet/vectorized/TestParquetVectorizedReads.java

This follows on #11803 and adds default value support to vectorized reads.

Spark 3.5: Support default values in vectorized reads

---

spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewritePositionDeleteFilesAction.java

This follows the suggestions in: https://github.com/apache/iceberg/pull/11748/files/36d953f359e58d4f01f45a7783cf3ae01d52c59b#r1880821876

Remove number from assert description

---

core/src/main/java/org/apache/iceberg/rest/HTTPHeaders.java
core/src/main/java/org/apache/iceberg/rest/auth/AuthManager.java
core/src/main/java/org/apache/iceberg/rest/auth/AuthManagers.java
core/src/main/java/org/apache/iceberg/rest/auth/AuthProperties.java
core/src/main/java/org/apache/iceberg/rest/auth/AuthSession.java
core/src/main/java/org/apache/iceberg/rest/auth/BasicAuthManager.java
core/src/main/java/org/apache/iceberg/rest/auth/DefaultAuthSession.java
core/src/main/java/org/apache/iceberg/rest/auth/NoopAuthManager.java
core/src/test/java/org/apache/iceberg/rest/TestHTTPHeaders.java
core/src/test/java/org/apache/iceberg/rest/auth/TestAuthManagers.java
core/src/test/java/org/apache/iceberg/rest/auth/TestBasicAuthManager.java
core/src/test/java/org/apache/iceberg/rest/auth/TestDefaultAuthSession.java

Second PR for the Auth Manager API.
This PR introduces the `AuthManager` itself, along with 2 simple implementations: Basic and Noop. This PR does _not_ turn the manager on yet.
\cc @nastra @danielcweeks

Auth Manager API part 2: AuthManager

---

core/src/main/java/org/apache/iceberg/TableMetadata.java
core/src/test/java/org/apache/iceberg/TestTableMetadata.java
core/src/test/java/org/apache/iceberg/catalog/CatalogTests.java
core/src/test/java/org/apache/iceberg/rest/TestRESTCatalog.java

Core: Don't reset snapshotLog in `TableMetadata.removeRef` method

---

core/src/test/java/org/apache/iceberg/avro/TestSchemaConversions.java

The method is deprecated: https://avro.apache.org/docs/1.12.0/api/java/org/apache/avro/Schema.html#toString(boolean)
> Deprecated. Use SchemaFormatter.format(Schema) instead, using the format json/pretty or json/inline

Core: Replace deprecated Schema.toString with SchemaFormatter

---

api/src/test/java/org/apache/iceberg/util/TestExceptionUtil.java

`asList` method is deprecated: https://www.javadoc.io/doc/org.assertj/assertj-core/latest/org/assertj/core/api/AbstractAssert.html#asList()

API: Replace deprecated asList with asInstanceOf in TestExceptionUtil

---

flink/v1.20/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java
flink/v1.20/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkDistributionMode.java

Detailed： #11543
This fix will modify the data processing process in RANGE mode, set the filter link of `StatisticsOrRecord` and actively set it to `writeParallelism` to avoid the shuffle mode changing to rebalance due to changes in parallelism in subsequent write operators.

Flink: Avoid RANGE mode broken chain when write parallelism changes

---

core/src/main/java/org/apache/iceberg/hadoop/HadoopTableOperations.java

`version-hint.txt` is incorrect and confusing as `version-hint.text` is the valid file name.

Core: Fix typo in HadoopTableOperations

---

hive-metastore/src/main/java/org/apache/iceberg/hive/HiveCatalog.java

This reverts commit 7e2920af400e5d559f8f1742b1043787b0477d74 from #10771.
Issue reported in https://github.com/apache/iceberg/issues/11783, https://github.com/apache/iceberg/issues/11633 and https://github.com/apache/iceberg/issues/11582. 
I was able to reproduce this on PyIceberg https://github.com/apache/iceberg-python/pull/1323, and while doing a `git bisect`, this led me to this PR:
```
➜  iceberg git:(7e2920af4) git bisect bad       
7e2920af400e5d559f8f1742b1043787b0477d74 is the first bad commit
commit 7e2920af400e5d559f8f1742b1043787b0477d74
Author: Hussein Awala <hussein@awala.fr>
Date:   Thu Jul 25 19:50:19 2024 +0200
Hive: close the fileIO client when closing the hive catalog (#10771)
Co-authored-by: Amogh Jahagirdar <amoghj@apache.org>
Co-authored-by: Eduard Tudenhoefner …
```

Revert "Hive: close the fileIO client when closing the hive catalog"

---

docs/docs/hive.md

Hive supports the `history` table.
https://github.com/apache/hive/blob/master/iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/IcebergMetadataTables.java
I verified it would work with the latest version, 4.0.1.
```
0: jdbc:hive2://localhost:10000/> CREATE TABLE test (id INT) STORED BY ICEBERG;
...
0: jdbc:hive2://localhost:10000/> INSERT INTO test VALUES (1);
...
0: jdbc:hive2://localhost:10000/> INSERT INTO test VALUES (2);
...
0: jdbc:hive2://localhost:10000/> SELECT * FROM default.test.history;
...
+----------------------------------+----------------------+----------------------+---------------------------+
|       test.made_current_at       |   test.snapshot_id   |    test.parent_id    | test.is_current_ancestor  | …
```

Docs: Add history to Hive's metadata tables

---

docs/docs/hive.md

The original format is broken:
https://iceberg.apache.org/docs/nightly/hive/#partitioned-tables

Doc: Fix format of Hive

---

kafka-connect/kafka-connect-runtime/src/integration/java/org/apache/iceberg/connect/IntegrationDynamicTableTest.java
kafka-connect/kafka-connect-runtime/src/integration/java/org/apache/iceberg/connect/IntegrationMultiTableTest.java
kafka-connect/kafka-connect-runtime/src/integration/java/org/apache/iceberg/connect/IntegrationTest.java
kafka-connect/kafka-connect-runtime/src/integration/java/org/apache/iceberg/connect/IntegrationTestBase.java

I've found a lot of code duplicates in integration tests of module `iceberg-kafka-connect-runtime`. I propose to avoid such code duplication by making parent class `IntegrationTestBase` abstract and move all common logic (beforeEach, afterEach, creating kafka common config, running test,  asserting snapshot is added) from `IntegrationTest`, `IntegrationMultiTableTest` and `IntegrationDynamicTableTest` to `IntegrationTestBase`.

Kafka-connect-runtime: remove code duplications in integration tests

---

flink/v1.20/flink/src/main/java/org/apache/iceberg/flink/source/reader/RowConverter.java

- I just discovered that the LegacyTypeInfoDataTypeConverter(used by tableSchema.getFieldTypes()) doesn't support Instant datatypes. 
- To work for Instant datatypes, we either change LegacyTypeInfoDataTypeConverter or use a different method. But the LegacyTypeInfoDataTypeConverter has been tagged deprecated.
- So I found another way to convert DataType to TypeInfo and made changes. Please review. 
Sorry, I should have dug a little more into this code earlier.

Use ExternalTypeInfo in Rowconverter code instead of deprecated TableSchema.getFieldTypes

---

hive-metastore/src/main/java/org/apache/iceberg/hive/HiveCatalog.java
hive-metastore/src/test/java/org/apache/iceberg/hive/TestHiveViewCatalog.java

Similar to #11597 but apply same optimization for checking hive view existence check without instantiate the hive view operations based on the comment from https://github.com/apache/iceberg/pull/11597#issuecomment-2491144010

Hive: Optimize viewExists API in hive catalog

---

docs/docs/spark-queries.md

```
spark-sql (default)> DESC default.test.manifests;
content             	int
path                	string
length              	bigint
partition_spec_id   	int
added_snapshot_id   	bigint
added_data_files_count	int
existing_data_files_count	int
deleted_data_files_count	int
added_delete_files_count	int
existing_delete_files_count	int
deleted_delete_files_count	int
partition_summaries 	array<struct<contains_null:boolean,contains_nan:boolean,lower_bound:string,upper_bound:string>>
Time taken: 0.107 seconds, Fetched 12 row(s)
```
```
spark-sql (default)> DESC default.test.position_deletes;
file_path           	string              	Path of a file in which a deleted row is stored
pos                 	bigint              	Ordinal position of a deleted row in the data file
row …
```

Doc: Add missing fields to metadata tables in Spark page

---

core/src/main/java/org/apache/iceberg/FastAppend.java
core/src/test/java/org/apache/iceberg/TestFastAppend.java
core/src/test/java/org/apache/iceberg/catalog/CatalogTests.java

This PR adds ability to add files to multiple partition specs in FastAppend. Inspired by MergeAppend code.

Core: Allow adding files to multiple partition specs in FastAppend

---

core/src/main/java/org/apache/iceberg/util/ParallelIterable.java
core/src/test/java/org/apache/iceberg/util/TestParallelIterable.java

It was observed that with high concurrency/high workload scenario cluster deadlocks due to manifest readers waiting for connection from S3 pool.
Specifically, ManifestGroup#plan will create ManifestReader per every ParallelIterable.Task. These readers will effectively hold onto S3 connection from the pool. When ParallelIterable queue is full, Task will be tabled for later use.
Consider scenario:
S3 connection pool size=1
approximateMaxQueueSize=1
workerPoolSize=1
ParallelIterable1: starts TaskP1
ParallelIterable1: TaskP1 produces result, queue gets full, TaskP1 is put on hold (holds S3 connection)
ParallelIterable2: starts TaskP2, TaskP2 is scheduled on workerPool but is blocked on S3 connection pool
ParallelIterable1: result gets consumed, TaskP1 is scheduled again
ParallelIterable1: …

Core: Fix possible deadlock in ParallelIterable

---

core/src/main/java/org/apache/iceberg/inmemory/InMemoryCatalog.java
core/src/main/java/org/apache/iceberg/jdbc/JdbcUtil.java
core/src/test/java/org/apache/iceberg/catalog/CatalogTests.java
core/src/test/java/org/apache/iceberg/inmemory/TestInMemoryCatalog.java
core/src/test/java/org/apache/iceberg/inmemory/TestInMemoryViewCatalog.java
core/src/test/java/org/apache/iceberg/jdbc/TestJdbcCatalog.java
core/src/test/java/org/apache/iceberg/jdbc/TestJdbcUtil.java
core/src/test/java/org/apache/iceberg/jdbc/TestJdbcViewCatalog.java
core/src/test/java/org/apache/iceberg/view/ViewCatalogTests.java
spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestViews.java
spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestViews.java

From all the catalogs that extend `CatalogTests`, only Hive + REST don't support creating a table/view and also listing tables/views in an empty namespace.
JDBC + InMemory do support that and therefore override the `supportsEmptyNamespace()` feature in their tests.
Additionally, this PR also fixes listing tables/views for InMemory as previously this would list all available tables/views, instead of just the ones in that namespace.
I've decided to not adjust the Nessie tests, since the behavior deviates from the current behavior that can be found for JDBC + InMemory. While Nessie doesn't support creation/removal of empty namespaces, it does support creating a table/view in an empty namespace. Listing tables/views in an empty namespace returns all available tables/views.

Core: Add tests for catalogs supporting empty namespaces

---

core/src/main/java/org/apache/iceberg/rest/RESTSessionCatalog.java

This PR fix the failure test `RESTCompatibilityKitCatalogTests.listNamespacesWithEmptyNamespace()` running based on `RESTSessionCatalog`.
In the original implementation, for empty namespaces, `RESTSessionCatalog.namespaceExists()` would directly throw an `NoSuchNamespaceException` rather than returning false. This will lead to the failure of the test.

Core: Fix test failure caused by check empty namespace on REST session catalog

---

docs/mkdocs.yml
site/docs/vendors.md

1. The Doris website has been upgraded so the link to Doris Iceberg Catalog is missing. Update to the new link.
2. Add VeloDB in vendors list.

[docs] Update docs link about Apache Doris and update vendors list

---

core/src/main/java/org/apache/iceberg/CachingCatalog.java
core/src/test/java/org/apache/iceberg/hadoop/TestCachingCatalog.java

If a regular table had a metadata table name then CachingCatalog throws a NoSuchTableException when loading that table.

Core: Fix loading a table in CachingCatalog with metadata table name

---

open-api/rest-catalog-open-api.py
open-api/rest-catalog-open-api.yaml

The `const` has been added in Open API 3.1:
https://www.speakeasy.com/openapi/schemas/enums#constants-for-single-value-enums
This fixes the compilation issue reported in https://github.com/apache/iceberg/pull/11806 as well.
cc @VladimirYushkevich @jbonofre @amogh-jahagirdar @nastra @ajantha-bhat

Open-API: Bump to OpenAPI 3.1

---

.github/workflows/java-ci.yml

To avoid situations like https://github.com/apache/iceberg/pull/11970

Run `java-ci` on changes in `open-api/**`

---

aws/src/main/java/org/apache/iceberg/aws/AwsClientProperties.java
aws/src/test/java/org/apache/iceberg/aws/AwsClientPropertiesTest.java
core/src/main/java/org/apache/iceberg/rest/RESTUtil.java
core/src/test/java/org/apache/iceberg/rest/TestRESTUtil.java
gcp/src/main/java/org/apache/iceberg/gcp/GCPProperties.java

The goal of this PR is to improve the credential URI / token handling when a server sends back properties to a client in order to indicate that refreshing vended credentials is supported. In detail, the following things are improved here:
* currently only a full URI can be passed as the `credentials.uri`. However, the catalog URI itself is already passed via the properties and so having support for a relative credential path can make things easier for servers. This is being changed for S3 + GCP in this PR.
* The `VendedCredentialsProvider` (specific to S3) currently requires the OAuth2 token to be passed via `client.credentials-provider.token` in order to be properly passed down from `AwsClientProperties` to the `VendedCredentialsProvider`. This is being simplified in this PR so that the …

AWS, Core, GCP: Support relative credential endpoint / pass OAuth2 token to credential provider

---

aws/src/main/java/org/apache/iceberg/aws/AwsClientProperties.java
aws/src/test/java/org/apache/iceberg/aws/AwsClientPropertiesTest.java
core/src/main/java/org/apache/iceberg/rest/RESTUtil.java
core/src/test/java/org/apache/iceberg/rest/TestRESTUtil.java
gcp/src/main/java/org/apache/iceberg/gcp/GCPProperties.java

this backports https://github.com/apache/iceberg/pull/11954 to 1.7.x

[1.7.x] AWS, Core, GCP: Support relative credential endpoint / pass OAuth2 token to credential provider

---

docs/docs/hive.md

Relates to https://github.com/apache/hive/pull/4897
Tested with `apache/hive:4.0.1`:
```
0: jdbc:hive2://localhost:10000/> ALTER TABLE employee EXECUTE DELETE ORPHAN-FILES;
INFO  : Compiling command(queryId=hive_20250101074601_ee489833-e643-4cc9-9c0d-338192d5270f): ALTER TABLE employee EXECUTE DELETE ORPHAN-FILES
INFO  : Semantic Analysis Completed (retrial = false)
INFO  : Created Hive schema: Schema(fieldSchemas:null, properties:null)
INFO  : Completed compiling command(queryId=hive_20250101074601_ee489833-e643-4cc9-9c0d-338192d5270f); Time taken: 0.03 seconds
INFO  : Concurrency mode is disabled, not creating a lock manager
INFO  : Executing command(queryId=hive_20250101074601_ee489833-e643-4cc9-9c0d-338192d5270f): ALTER TABLE employee EXECUTE DELETE ORPHAN-FILES
INFO  : Starting task …
```

Doc: Add DELETE ORPHAN-FILES example to Hive page

---

spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestViews.java
spark/v3.4/spark-runtime/src/integration/java/org/apache/iceberg/spark/SmokeTest.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/BaseCatalog.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/SparkCatalog.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/SparkSessionCatalog.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/SparkCatalogConfig.java
spark/v3.5/spark-runtime/src/integration/java/org/apache/iceberg/spark/SmokeTest.java

Spark 3.4: Add view support to SparkSessionCatalog

---

spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMergeOnReadDelete.java
spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMergeOnReadUpdate.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/source/SparkBatchQueryScan.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/source/SparkPositionDeltaWrite.java

Spark 3.4: Backport rewriting historical file-scoped deletes (#11273) to 3.4

---

api/src/main/java/org/apache/iceberg/expressions/ExpressionUtil.java
api/src/test/java/org/apache/iceberg/expressions/TestExpressionUtil.java

This is the fixed code that corrected the casting error that occurred in the issue below.
I have also added one TestCode.
#11932

Support sanitizing a `Literal<?>`

---

core/src/main/java/org/apache/iceberg/rest/auth/AuthConfig.java
core/src/main/java/org/apache/iceberg/rest/auth/AuthManagers.java
core/src/main/java/org/apache/iceberg/rest/auth/AuthProperties.java
core/src/main/java/org/apache/iceberg/rest/auth/AuthSessionCache.java
core/src/main/java/org/apache/iceberg/rest/auth/OAuth2Manager.java
core/src/main/java/org/apache/iceberg/rest/auth/OAuth2Util.java
core/src/main/java/org/apache/iceberg/rest/auth/RefreshingAuthManager.java
core/src/test/java/org/apache/iceberg/rest/auth/TestAuthManagers.java
core/src/test/java/org/apache/iceberg/rest/auth/TestAuthSessionCache.java
core/src/test/java/org/apache/iceberg/rest/auth/TestOAuth2Manager.java

3rd PR for the Auth Manager API. Previous ones:
* #11809
* #11769 
This PR introduces the `OAuth2Manager` along with session caching and credentials refreshing. It is still "unplugged" though. Most of the `OAuth2Manager` code reflects one-to-one what's currently hard-coded in `RESTSessionCatalog` (and it's still there).
\cc @nastra @danielcweeks

Auth Manager API part 3: OAuth2 Manager

---

spark/v3.3/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestCreateChangelogViewProcedure.java
spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/SparkScanBuilder.java
spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestCreateChangelogViewProcedure.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/source/SparkScanBuilder.java
spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestCreateChangelogViewProcedure.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/source/SparkScanBuilder.java

The issue occurs when the start timestamp resolves to the root snapshot, and no end timestamp is provided. In this case, the change log scan will be flagged to do an empty scan. The expected scenario is a full table scan.
```
if (table.currentSnapshot() == null
|| table.currentSnapshot().timestampMillis() < startTimestamp) {
emptyScan = true;
}
```
This code block ensures that there is at least some snapshots exist in the table and is after the input startTimestamp, otherwise we do an empty scan. As a result, even if getStartSnapshotId(startTimestamp) resolves to null, we will know that there is a snapshot with no parent and should scan the table.
```testOnlyStartTimestampInput``` is an added test that reproduces the issue and is passing after the change.
* ```./gradlew spotlessApply …
```

Spark: Fix empty scan issue when start timestamp retrieves root snapshot and end timestamp is missing

---

spark/v3.3/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestCreateChangelogViewProcedure.java
spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/SparkScanBuilder.java
spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestCreateChangelogViewProcedure.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/source/SparkScanBuilder.java
spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestCreateChangelogViewProcedure.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/source/SparkScanBuilder.java

Backport to 1.7.2 of https://github.com/apache/iceberg/pull/11967

Spark: Fix empty scan issue when start timestamp retrieves root snapshot and end timestamp is missing (#11967)

---

docs/docs/spark-queries.md

I missed adding the value in https://github.com/apache/iceberg/pull/11897

Doc: Add missing content value to manifests table

---

spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMergeOnReadDelete.java
spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMergeOnReadMerge.java
spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMergeOnReadUpdate.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/SparkWriteConf.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/source/SparkPositionDeltaWrite.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/TestSparkWriteConf.java

Fixes #11968 
Currently, when writing DVs in Spark, the incorrect file suffix is being used. This is because the file format passed to the output file factory which produces the actual filename is not correct and uses the default conf delete file format (typically the same as the data file format).
Note, the actual Puffin DVs were always being written when the table format is V3, it just had the wrong suffix so users see "delete-foo.parquet" even though the file is really a Puffin file with DVs.

Spark: Fix Puffin suffix for DV files

---

format/spec.md

Split out from #11948 
Working on the row-lineage implementation made it clear that we needed a way to get information from the Snapshot object propagated into the Metadata layer. Specifically we need to know the count of all newly added rows in that Snapshot to change the `last-row-id` of the TableMetadata. While we can potentially read this from Snapshot Summary, it would be a bit odd to have a requirement on key value pair within Snapshot summary. We could also potentially re-read and calculate the number of added rows, but this would require re-opening the manifest list itself. 
I believe it makes more sense to formally have added-rows as an optional field within the Snapshot itself so we can make it clear in the spec this value is expected to be stored within the Snapshot metadata if …

Spec: Add added-rows field to Snapshot

---

api/src/main/java/org/apache/iceberg/types/Types.java

API: add hashcode cache in StructType

---

api/src/main/java/org/apache/iceberg/types/Types.java

It looks like it breaks some tests on the Flink side wrt serialization.
This reverts commit bed7c33174ca97809fc4a9657d39b1d09ae38b72.

Revert "API: add hashcode cache in StructType (#11764)"

---

azure/src/main/java/org/apache/iceberg/azure/AzureProperties.java
azure/src/main/java/org/apache/iceberg/azure/adlsv2/ADLSFileIO.java
azure/src/main/java/org/apache/iceberg/azure/adlsv2/ADLSLocation.java
azure/src/test/java/org/apache/iceberg/azure/AzurePropertiesTest.java
azure/src/test/java/org/apache/iceberg/azure/adlsv2/ADLSFileIOTest.java
azure/src/test/java/org/apache/iceberg/azure/adlsv2/ADLSLocationTest.java
core/src/main/java/org/apache/iceberg/io/ResolvingFileIO.java

This is my third attempt to resolve https://github.com/apache/iceberg/issues/10127 (...third time's the charm 😉)
We needed to revert https://github.com/apache/iceberg/pull/11504 since it introduced [a breaking change for ADLSFileIO clients that were using SAS tokens](https://github.com/apache/iceberg/pull/11504#issuecomment-2547124997).  This PR fixes the issue by introducing a new  `host()` method to ADLSLocation and [uses it in ADLSFileIO when calling applyClientConfiguration](https://github.com/apache/iceberg/compare/main...mrcnc:iceberg:support-wasb-for-adlsfileio?expand=1#diff-b6b966659def85b3107d8db1f7c3e23ca7c84b9139123114b21dd4df85942664R114).

Support WASB scheme in ADLSFileIO 

---

flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/util/TestFlinkPackage.java
gradle/libs.versions.toml
site/mkdocs.yml

If users run a Flink job on Flink 1.19.1 with IcebergSink compiled against 1.19.0, as is the case prior this change, they will get the following exception on commit:
```
java.lang.NoSuchMethodError: 'void org.apache.flink.streaming.api.connector.sink2.CommittableSummary.<init>(int, int, java.lang.Long, int, int, int)'
at org.apache.iceberg.flink.sink.IcebergWriteAggregator.prepareSnapshotPreBarrier(IcebergWriteAggregator.java:91)
```
The reason is that from 1.19.0 to 1.19.1, Flink changed the signature of the constructor for `CommittableSummary` from
```
CommittableSummary(int, int, Long, int, int, int)
```
to
```
CommittableSummary(int, int, long, int, int, int)
```
Note the `Long` to `long` change. Since Flink 1.19.1 is the latest supported version and 1.19.0 is no longer supported, it …

Flink: Upgrade Flink version 1.19.0 => 1.19.1 to mitigate NoSuchMethodError on commit

---

spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/SparkRowLevelOperationsTestBase.java
spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestCopyOnWriteDelete.java
spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestCopyOnWriteMerge.java
spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestCopyOnWriteUpdate.java
spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestDelete.java
spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMerge.java
spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMergeOnReadDelete.java
spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMergeOnReadMerge.java
spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMergeOnReadUpdate.java
spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestUpdate.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/SparkWriteConf.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/source/SparkBatchQueryScan.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/source/SparkPositionDeltaWrite.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/data/TestHelpers.java

Backports the combination of https://github.com/apache/iceberg/pull/11561+ https://github.com/apache/iceberg/pull/11986 to Spark 3.4.

Spark 3.4: Backport writing DVs to Spark 3.4

---

orc/src/main/java/org/apache/iceberg/orc/ORCSchemaUtil.java
orc/src/test/java/org/apache/iceberg/orc/TestBuildOrcProjection.java

Updates ORC's `buildOrcProjection` to fail with a good error message when a default value would be used, rather than failing with `ArrayIndexOutOfBoundsException`.
ORC readers are not built the same way that Parquet and Avro readers are built. ORC uses `buildOrcProjection` to create a requested ORC schema that matches the fields in the expected Iceberg schema. This schema is used for ORC projection, but is also used to produce ORC readers. As a result, ORC cannot currently detect missing columns when building readers, which is necessary for using a constant reader for the initial default.
Refactoring how ORC builds readers is a large task, so in the meantime this PR provides better error messages.

ORC: Fail when initial default support is required

---

core/src/main/java/org/apache/iceberg/rest/RESTSessionCatalog.java
open-api/rest-catalog-open-api.yaml

`HEAD /v1/{prefix}/namespaces/{namespace}` and `HEAD /v1/{prefix}/namespaces/{namespace}/tables/{table}` look missing in default endpoints in open-api/rest-catalog-open-api.yaml. 
`POST /v1/{prefix}/transactions/commit` is mentioned in the above yaml, but `DEFAULT_ENDPOINTS` constant doesn't contain `Endpoint.V1_COMMIT_TRANSACTION`.

REST: Add missing default HEAD endpoints and V1_COMMIT_TRANSACTION

---

spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/data/vectorized/ColumnVectorBuilder.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/data/vectorized/ColumnarBatchReader.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/data/vectorized/ColumnarBatchUtil.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/data/vectorized/DeletedColumnVector.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/data/vectorized/IcebergArrowColumnVector.java

Address the comments in https://github.com/apache/iceberg/pull/9841#discussion_r1906083743

Spark 3.5: Refactor delete logic in batch reading

---

aws-bundle/LICENSE
azure-bundle/LICENSE
gcp-bundle/LICENSE

https://github.com/apache/iceberg/pull/10665 updated the bundle jar files by removing slf4j-api.
However, the `LICENSE` file in these bundle jar files has not been updated and still contain reference to `slf4j-api`.

Remove slf4j-api reference in LICENSE as it's now excluded from the distributed jar files

---

aws-bundle/LICENSE
azure-bundle/LICENSE
gcp-bundle/LICENSE

Work by @jbonofre, let's include this in 1.7.2 as well:
I've checked out the branch, and it is also excluded from the JAR on the `1.7.x` branch:
```
➜  azure find . | grep -i slf4j
./org/apache/iceberg/azure/shaded/io/netty/util/internal/logging/LocationAwareSlf4JLogger.class
./org/apache/iceberg/azure/shaded/io/netty/util/internal/logging/Slf4JLoggerFactory$NopInstanceHolder.class
./org/apache/iceberg/azure/shaded/io/netty/util/internal/logging/Slf4JLoggerFactory.class
./org/apache/iceberg/azure/shaded/io/netty/util/internal/logging/Slf4JLogger.class
./reactor/util/Loggers$Slf4JLoggerFactory.class
./reactor/util/Loggers$Slf4JLogger.class
```
```
➜  gcp find . | grep -i slf4j …
```

Remove `slf4j-api` reference in `LICENSE` (#12052)

---

baseline.gradle
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/data/vectorized/ColumnarBatchUtil.java

https://github.com/apache/iceberg/issues/12053

Spark 3.5: Fix Javadoc in ColumnarBatchUtil

---

core/src/main/java/org/apache/iceberg/view/ViewMetadata.java
core/src/test/java/org/apache/iceberg/view/TestViewMetadata.java

This fixes the issue reported by https://github.com/apache/iceberg/pull/12051
/cc @c-thiel 
Fixes https://github.com/apache/iceberg/pull/12051

Core: Retain current view version during expiration

---

spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRewriteTablePathProcedure.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/actions/RewriteTablePathSparkAction.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/procedures/RewriteTablePathProcedure.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/procedures/SparkProcedures.java

Add spark procedure for rewrite table path

Spark 3.5: Procedure to rewrite table path

---

api/src/main/java/org/apache/iceberg/Schema.java
api/src/main/java/org/apache/iceberg/expressions/ExpressionUtil.java
api/src/main/java/org/apache/iceberg/transforms/Identity.java
api/src/main/java/org/apache/iceberg/types/Type.java
api/src/main/java/org/apache/iceberg/types/TypeUtil.java
api/src/main/java/org/apache/iceberg/types/Types.java
api/src/test/java/org/apache/iceberg/TestPartitionSpecValidation.java
api/src/test/java/org/apache/iceberg/TestSchema.java
api/src/test/java/org/apache/iceberg/transforms/TestBucketing.java
api/src/test/java/org/apache/iceberg/transforms/TestDates.java
api/src/test/java/org/apache/iceberg/transforms/TestIdentity.java
api/src/test/java/org/apache/iceberg/transforms/TestTimestamps.java
api/src/test/java/org/apache/iceberg/transforms/TestTruncate.java
api/src/test/java/org/apache/iceberg/transforms/TestVoid.java
api/src/test/java/org/apache/iceberg/types/TestSerializableTypes.java
api/src/test/java/org/apache/iceberg/types/TestTypes.java
core/src/test/java/org/apache/iceberg/TestSortOrder.java

Fixes https://github.com/apache/iceberg/issues/11732

API: Add `UnknownType`

---

spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/actions/RewriteTablePathSparkAction.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteTablePathsAction.java

This PR fixes following exception when running `rewrite_table_path` action with Spark
```
java.lang.UnsupportedOperationException
at org.apache.iceberg.spark.actions.RewriteTablePathSparkAction.writeDataManifest(RewriteTablePathSparkAction.java:535)
at org.apache.iceberg.spark.actions.RewriteTablePathSparkAction.lambda$toManifests$fbc8fb31$1(RewriteTablePathSparkAction.java:491)
at org.apache.spark.sql.execution.MapElementsExec.$anonfun$doExecute$9(objects.scala:302)
at org.apache.spark.sql.execution.MapElementsExec.$anonfun$doExecute$11(objects.scala:309)
at scala.collection.Iterator$$anon$10.next(Iterator.scala:461)
at scala.collection.Iterator$$anon$10.next(Iterator.scala:461)
at scala.collection.Iterator.foreach(Iterator.scala:943)
at …
```

Spark 3.5: Fix broadcasting specs in RewriteTablePath

---

spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRewriteTablePathProcedure.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/actions/BaseSparkAction.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/actions/RewriteTablePathSparkAction.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/actions/SparkActions.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/procedures/RewriteTablePathProcedure.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/procedures/SparkProcedures.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteTablePathsAction.java

Minor unit test modification to accommodate for difference between junit4 and junit5
Can you take a look? @amogh-jahagirdar

Spark 3.4: Backport Spark actions and procedures for RewriteTablePath

---

core/src/main/java/org/apache/iceberg/SerializableTable.java
core/src/main/java/org/apache/iceberg/TableUtil.java
core/src/test/java/org/apache/iceberg/TestTableUtil.java
core/src/test/java/org/apache/iceberg/hadoop/TestTableSerialization.java
spark/v3.3/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRegisterTableProcedure.java
spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRegisterTableProcedure.java
spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRegisterTableProcedure.java
spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRewriteTablePathProcedure.java

Context: https://github.com/apache/iceberg/pull/11931#discussion_r1927795585
- Add a new static helper method in TableUtil to expose metadata file location for a given table
- also added a public method in serializableTable to expose metadata file location
- leverage EnumSource in unit tests to help with execute in oarameterized fashion for all metadata tables
@amogh-jahagirdar @nastra if you want to take a look

Core: Add metadataFileLocation in TableUtil

---

.palantir/revapi.yml
api/src/main/java/org/apache/iceberg/UpdateStatistics.java
core/src/main/java/org/apache/iceberg/MetadataUpdate.java
core/src/main/java/org/apache/iceberg/MetadataUpdateParser.java
core/src/main/java/org/apache/iceberg/SetStatistics.java
core/src/main/java/org/apache/iceberg/TableMetadata.java
core/src/test/java/org/apache/iceberg/TestMetadataUpdateParser.java
open-api/rest-catalog-open-api.py
open-api/rest-catalog-open-api.yaml

Following the discussion on the Mailing List:
https://lists.apache.org/thread/phxjz196zbzg0fjpfkmnj0fpkshgh9z0
I would appreciate a more thorough look at the Java code changes, it's my first deprecation in iceberg and java is not my primary language.

OpenAPI: Deprecate snapshot-id of SetStatisticsUpdate

---

core/src/main/java/org/apache/iceberg/FileMetadata.java
core/src/test/java/org/apache/iceberg/TestDeleteFiles.java

This field is required for DV. I missed setting this field when preparing deletion vector's changes in Trino, and it resulted in incorrect results even though DELETE statement succeeded. It would be nice to fail early. 
https://github.com/apache/iceberg/blob/a04220a198a03f4116d3012330f99b787dabc8e1/api/src/main/java/org/apache/iceberg/DeleteFile.java#L35-L44

Core: Check referencedDataFile existence for DV

---

core/src/main/java/org/apache/iceberg/variants/PrimitiveWrapper.java
core/src/main/java/org/apache/iceberg/variants/SerializedArray.java
core/src/main/java/org/apache/iceberg/variants/SerializedMetadata.java
core/src/main/java/org/apache/iceberg/variants/SerializedObject.java
core/src/main/java/org/apache/iceberg/variants/ShreddedObject.java
core/src/main/java/org/apache/iceberg/variants/VariantArray.java
core/src/main/java/org/apache/iceberg/variants/VariantMetadata.java
core/src/main/java/org/apache/iceberg/variants/VariantObject.java
core/src/main/java/org/apache/iceberg/variants/Variants.java
core/src/test/java/org/apache/iceberg/variants/TestPrimitiveWrapper.java
core/src/test/java/org/apache/iceberg/variants/TestSerializedArray.java
core/src/test/java/org/apache/iceberg/variants/TestSerializedMetadata.java
core/src/test/java/org/apache/iceberg/variants/TestSerializedObject.java
core/src/test/java/org/apache/iceberg/variants/TestShreddedObject.java
core/src/test/java/org/apache/iceberg/variants/VariantTestUtil.java

This updates variants with changes needed for Parquet readers.
* Add `numFields` to objects, `numElements` to arrays, and `dictionarySize` to metadata
* Use `VariantMetadata` instead of direct references to `SerializedMetadata`
* Support any `VariantObject` for unshredded fields in `ShreddedObject` to avoid leaking `SerializedObject`
* Support suppressing fields in `ShreddedObject` to handle shredded fields that are missing, not overridden
* For boolean variants, alter the type based on the value to simplify creating booleans
* Rename `Variants.from`

Core: Update variant class visibility

---

flink/v1.20/flink/src/main/java/org/apache/iceberg/flink/data/FlinkParquetReaders.java
parquet/src/main/java/org/apache/iceberg/data/parquet/BaseParquetReaders.java
parquet/src/main/java/org/apache/iceberg/data/parquet/GenericParquetReaders.java
parquet/src/main/java/org/apache/iceberg/data/parquet/InternalReader.java
parquet/src/main/java/org/apache/iceberg/parquet/ParquetAvroValueReaders.java
parquet/src/main/java/org/apache/iceberg/parquet/ParquetValueReader.java
parquet/src/main/java/org/apache/iceberg/parquet/ParquetValueReaders.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/data/SparkParquetReaders.java

This is a refactor that cleans up a few issues I noticed while reviewing #11904 and while working on Parquet variant readers.
- Updates INT and UINT handling to reject unsupported unsigned types (like UINT64)
- Adds more factory methods to `ParquetValueReaders` to keep implementations private
- Removes unused `types` argument from `ParquetValueReader.StructReader` subclasses. Some accessible uses had to be left, but most are removed. This allowed removing types from the reader builders as well.
- Removes unnecessary `TimeUnit` param from factory methods added in #11904
- Removes unnecessary implementations of `setPageSource`
- Adds imports for `LogicalTypeAnnotation` classes to cut down on multi-line method signatures
Changes are grouped into separate commits for easier review.

Parquet: Clean up Parquet generic and internal readers

---

site/docs/how-to-release.md

Fix spacing issue in the "how to release" voting section, this was [already fixed in pyiceberg
](https://github.com/apache/iceberg-python/blob/985029042199d870f25b6fbec0e80907d4440f41/mkdocs/docs/verify-release.md#cast-the-vote)
Old:
https://iceberg.apache.org/how-to-release/#voting
New:

[docs] add spacing to "how to release"'s voting section

---

format/spec.md

The docs for `_row_id` has "see Row Lineage" but `_last_updated_sequence_number` has "Row Lineage" by itself, which reads like a small typo.

Spec: Fix minor typo in `_last_updated_sequence_number` docs

---

core/src/main/java/org/apache/iceberg/view/BaseViewOperations.java
core/src/main/java/org/apache/iceberg/view/ViewProperties.java
core/src/test/java/org/apache/iceberg/view/ViewCatalogTests.java
docs/docs/view-configuration.md
spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestViews.java
spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestViews.java

This commit makes the View's metadata file location configurable by `write.metadata.path` as the table configuration, it and provides more flexible way to configure the metadata file path for Iceberg Views.
Currently, View's metadata file location respects its relevant database location first. If the database doesn't have the location, the View's metadata location is set to a warehouse location. 
For now, when you customize the View's metadata location, you need to set the `warehouse` parameter. However, if your database has the configured location in its property such as `location: /db/table/path`, you need to change the database location (this is not always easy).
```sql
-- SparkSQL
CREATE VIEW db.view TBLPROPERTIES('write.metadata.path'='s3://bucket/path/new-metadata-loc') 
AS SELECT …
```

Make view metadata path configurable by `write.metadata.path`

---

core/src/main/java/org/apache/iceberg/EnvironmentContext.java
core/src/test/java/org/apache/iceberg/TestEnvironmentContext.java

Tiny change to support removing keys from `EnvironmentContext`.
Useful when a JVM is shared by multiple jobs and jobs want to express different environment properties.

Core: Support removing keys from EnvironmentContext

---

core/src/test/java/org/apache/iceberg/rest/requests/TestCreateTableRequest.java
core/src/test/java/org/apache/iceberg/rest/responses/TestLoadTableResponse.java
core/src/test/resources/TableMetadataV3ValidMinimal.json
open-api/rest-catalog-open-api.py
open-api/rest-catalog-open-api.yaml

Adds `inital-default` and `write-default` to the REST API spec.
Includes updates to a couple small round-trip request/response serde tests.

OpenAPI: add initial/write defaults to schema

---

aws-bundle/LICENSE
aws-bundle/NOTICE

This fixes:
- Update versions in both `LICENSE` and `NOTICE`
- Add/update `NOTICE` with `netty`

Fix NOTICE and LICENSE in the aws-bundle jar

---

azure-bundle/LICENSE
azure-bundle/NOTICE

This fixes `LICENSE` and `NOTICE` in the azure-bundle jar with:
- Update the versions
- Remove `jackson-dataformat-xml` as it's not in the runtime classpath and the jar
- Remove `woodstox-core` as it's not in the runtime classpath and the jar
- Add Netty `NOTICE` content in azure-bundle `NOTICE`

Fix NOTICE and LICENSE in the azure-bundle jar

---

format/view-spec.md

The example given [in the View Spec](https://iceberg.apache.org/view-spec/#appendix-a-an-example) demonstrates creation of a new version of a View. The new metadata file should list the `current-version-id` as `2` but currently lists `1`. This PR is intended to fix that discrepancy and prevent potential confusion around the behavior of `current-version-id` in View metadata files.

Spec: Fix current-version-id in View Spec example

---

data/src/main/java/org/apache/iceberg/data/GenericReader.java

When using `GenericReader`, e.g. via `IcebergGenerics`, to scan data in a table, the data file is opened using the location only. This PR passes in the `DataFile` object instead, so that the file length stat can be used. In `S3FileIO`, for example, if you don't pass in the file length then it will make an S3 head request to get the file length.

Data: open file using stats in scan

---

core/src/main/java/org/apache/iceberg/TableMetadata.java

The private method `TableMetadata::Builder::resetMainBranch` used once is equivalent to `TableMetadata::Builder::removeRef(SnapshotRef.MAIN_BRANCH)`, so this PR removes it.

Core: Remove `TableMetadata::Builder::resetMainBranch`

---

core/src/main/java/org/apache/iceberg/variants/PrimitiveWrapper.java
core/src/main/java/org/apache/iceberg/variants/SerializedMetadata.java
core/src/main/java/org/apache/iceberg/variants/SerializedObject.java
core/src/main/java/org/apache/iceberg/variants/SerializedPrimitive.java
core/src/main/java/org/apache/iceberg/variants/SerializedShortString.java
core/src/main/java/org/apache/iceberg/variants/ShreddedObject.java
core/src/main/java/org/apache/iceberg/variants/VariantMetadata.java
core/src/main/java/org/apache/iceberg/variants/VariantObject.java
core/src/main/java/org/apache/iceberg/variants/VariantPrimitive.java

This implements `toString` for Variant classes, which is more friendly when reading parameterized test cases.

Variants: Implement toString

---

core/src/main/java/org/apache/iceberg/variants/LogicalType.java
core/src/main/java/org/apache/iceberg/variants/PhysicalType.java
core/src/main/java/org/apache/iceberg/variants/PrimitiveWrapper.java
core/src/main/java/org/apache/iceberg/variants/Primitives.java
core/src/main/java/org/apache/iceberg/variants/SerializedMetadata.java
core/src/main/java/org/apache/iceberg/variants/SerializedPrimitive.java
core/src/main/java/org/apache/iceberg/variants/SerializedShortString.java
core/src/main/java/org/apache/iceberg/variants/VariantMetadata.java
core/src/main/java/org/apache/iceberg/variants/VariantObject.java
core/src/main/java/org/apache/iceberg/variants/VariantUtil.java
core/src/main/java/org/apache/iceberg/variants/VariantValue.java
core/src/main/java/org/apache/iceberg/variants/Variants.java
core/src/test/java/org/apache/iceberg/variants/TestSerializedArray.java
core/src/test/java/org/apache/iceberg/variants/TestSerializedObject.java
core/src/test/java/org/apache/iceberg/variants/TestSerializedPrimitives.java
core/src/test/java/org/apache/iceberg/variants/TestShreddedObject.java

This refactors the existing Variant class structure to avoid breaking changes when the Variant interfaces are moved to `iceberg-api`. This requires:
* `PhysicalType` should not be a static class in `Variants`, which will not move
* `VariantMetadata` should not extend `Variants.Serialized`, which should not be exposed
This also adds `writeTo` and `sizeInBytes` to `VariantMetadata` to be able to serialize back to a `ByteBuffer` without `Serialized`.

Core: Refactor variants to enable moving interfaces to API module

---

site/mkdocs.yml

This brings them in line with 1.7.1:
https://github.com/apache/iceberg/blob/apache-iceberg-1.7.1/gradle/libs.versions.toml

Bump the versions of `site/mkdocs.yml`

---

api/src/main/java/org/apache/iceberg/types/Types.java
api/src/test/java/org/apache/iceberg/types/TestTypes.java

The NestedField builder relies on the NestedField constructor to validate values, but the builder uses `Integer` for the id value whereas the constructor uses `int`.  
This results in a confusing auto-unboxing related NPE if a field id is not provided to the builder.  This PR adds a check prior to the auto-unboxing to provide a reasonable message that the field id is required.

API: Null check for auto-unboxed field id in builder

---

hive-metastore/src/test/java/org/apache/iceberg/hive/TestHiveMetastore.java

Fix https://github.com/apache/iceberg/issues/12131 
SystemClassLoader swap to getClassLoader
add try-resources for connection in derby db

Test Hive: Fix TestHiveMetastore

---

aws/src/main/java/org/apache/iceberg/aws/s3/VendedCredentialsProvider.java
aws/src/main/java/org/apache/iceberg/aws/s3/signer/S3V4RestSignerClient.java
aws/src/test/java/org/apache/iceberg/aws/TestRESTSigV4Signer.java
core/src/main/java/org/apache/iceberg/rest/BaseHTTPClient.java
core/src/main/java/org/apache/iceberg/rest/HTTPClient.java
core/src/main/java/org/apache/iceberg/rest/RESTClient.java
core/src/main/java/org/apache/iceberg/rest/RESTSessionCatalog.java
core/src/test/java/org/apache/iceberg/rest/RESTCatalogAdapter.java
core/src/test/java/org/apache/iceberg/rest/RESTCatalogServlet.java
core/src/test/java/org/apache/iceberg/rest/TestHTTPClient.java
core/src/test/java/org/apache/iceberg/rest/TestRESTCatalog.java
core/src/test/java/org/apache/iceberg/rest/TestRESTViewCatalog.java
gcp/src/main/java/org/apache/iceberg/gcp/gcs/OAuth2RefreshCredentialsHandler.java

4th PR for the Auth Manager API. Previous ones:
* #11844
* #11809
* #11769 
This PR introduces the required changes to `RESTClient` and `HTTPClient`. It also introduces a `BaseHTTPClient` abstract class to facilitate the creation and execution of `HTTPRequest`s in a consistent way.
The biggest change in actually in `TestRESTCatalog`, because almost every `Mockito.verify()` call needs to be adapted.
The AuthManager API is still "unplugged" at this point.
\cc @nastra @danielcweeks

Auth Manager API part 4: RESTClient, HTTPClient

---

flink/v1.20/flink-runtime/LICENSE
flink/v1.20/flink-runtime/NOTICE

This is a proposal including:
- cleanup ASF projects references
- remove animal sniffer annotations from `LICENSE` as it's not in the jar or the runtime classpath
- remove yetus from `LICENSE` as it's not in the jar or the runtime classpath
- fix Nessie in `LICENSE` (`NOTICE` should go in `NOTICE`)
- add Codahale Metrics in `LICENSE` (it's in the jar)
- add RoaringBitmap in `LICENSE` (it's in the jar)
- add Eclipse Microprofile OpenAPI in `LICENSE` (it's in the jar)
- add Zstd in `LICENSE` (it's in the jar)
- update Nessie `NOTICE` (with the correct Nessie version)
- add Eclipse Microprofile OpenAPI `NOTICE`

Fix NOTICE and LICENSE in the flink-runtime jar

---

flink/v1.18/flink-runtime/LICENSE
flink/v1.18/flink-runtime/NOTICE
flink/v1.19/flink-runtime/LICENSE
flink/v1.19/flink-runtime/NOTICE
flink/v1.20/flink-runtime/LICENSE

This PR:
- remove airlift slice from `LICENSE` (I don't see it in any flink-runtime jar)
- add Codahale Metrics (present in all flink-runtime jars)
- I check flink-runtime 1.18 and 1.19 and the `LICENSE` and `NOTICE` from 1.20 also apply

Update LICENSE/NOTICE in flink-runtime jar files

---

spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/actions/RewriteTablePathSparkAction.java

 Spark 3.4: Remove use of File.Separator in RewriteTablePath

---

core/src/main/java/org/apache/iceberg/RewriteTablePathUtil.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/actions/RewriteTablePathSparkAction.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteTablePathsAction.java

Statistics files are helpful to determine the NDV for each columns in a table and can be collected via engines like [trino](https://trino.io/docs/current/connector/iceberg.html#updating-table-statistics) or [spark ](https://iceberg.apache.org/docs/nightly/spark-procedures/#compute_table_stats)
This patch help support table statistics files as part of rewrite table path spark action. 
@szehon-ho @flyrain if you want to take a look

Spark: support statistics files in RewriteTablePath

---

format/spec.md

This is the spec change for https://github.com/apache/iceberg/issues/10260.
Also this is based closely on the decisions taken in the Parquet proposal for the same :  https://github.com/apache/parquet-format/pull/240

Spec: Support geo type

---

format/spec.md

variant and geospatial types are recently added to the v3 spec but the summary is not updated in sync.

Docs: Add missing types to the spec v3 summary

---

format/spec.md

I was looking at adding support for `source-ids` in PyIceberg, but noticed that it was also still lacking for Java.
I've noticed that `source-ids` are also backported to V1 and V2 tables, which surprised me since this might break existing V2 implementations that are unaware of the `source-ids`.
This PR reconsiders https://github.com/apache/iceberg/pull/9661
And more specifically: https://lists.apache.org/thread/9opgkrpqhzp3nl8hdohgnk1m1zxnxmq0
It would be good to only allow multi-arg transforms from V3 onwards, and avoid having some implementations support this by setting a flag. Other implementations might not be aware of this implementation and drop the 2nd argument onward:
```json
{
"source-id": 19,
"source-ids": [19, 25],
"field-id": 1000,
"name": "ts_bucket",
"transform": "bucket"
} …
```

spec: Remove `source-ids` for `V{1,2}` tables

---

site/docs/releases.md

Fix formatting for 1.8.0 release notes, was missing a newline and it messed up the list structure below.
Before:
After:

Docs: Fix formatting of 1.8.0 release notes

---

core/src/main/java/org/apache/iceberg/rest/RESTObjectMapper.java
core/src/main/java/org/apache/iceberg/util/JsonUtil.java
mr/build.gradle

With very large table metadata json, for example, those with many snapshots with partition summaries, we sometimes encounter errors involving hash collisions when loading the metadata. This PR disables that hash collision check so the metadata can be parsed without error. We have had this set in our internal fork for a while.
In addition, this PR disable string interning of field names which has lead to performance problems for us when parsing metadata. Given partition summary field names and other snapshot properties are often not reused across different metadata, the interning causes more harm than good. This is especially true when using Iceberg in a server which is loading metadata for many tables.
This also fixes a test classpath issue. The Avatica driver is a shadow jar that bundles …

Core: Adjust Jackson settings to handle large metadata json

---

core/src/main/java/org/apache/iceberg/InternalData.java
core/src/main/java/org/apache/iceberg/ManifestListWriter.java
core/src/main/java/org/apache/iceberg/ManifestReader.java
core/src/main/java/org/apache/iceberg/ManifestWriter.java
core/src/main/java/org/apache/iceberg/V1Metadata.java
core/src/main/java/org/apache/iceberg/V2Metadata.java
core/src/main/java/org/apache/iceberg/V3Metadata.java
core/src/main/java/org/apache/iceberg/avro/Avro.java
core/src/main/java/org/apache/iceberg/avro/InternalReader.java
core/src/main/java/org/apache/iceberg/avro/SupportsCustomRecords.java
core/src/main/java/org/apache/iceberg/avro/SupportsCustomTypes.java
parquet/src/main/java/org/apache/iceberg/InternalParquet.java
parquet/src/main/java/org/apache/iceberg/parquet/Parquet.java

This adds `InternalData` with read and write builder interfaces that can be used with Avro and Parquet by passing a `FileFormat`. Formats are registered by calling `InternalData.register` with callbacks to create format-specific builders.
The class is `InternalData` because registered builders are expected to use the internal object model that is used for Iceberg metadata files. Using a specific object model avoids needing to register callbacks to create value readers and writers that produce the format needed by the caller.
To demonstrate the new interfaces, this PR implements them using both Avro and Parquet. Parquet can't be used because it would fail at runtime until #11904 is committed (it is also missing custom type support).
Avro is working. To demonstrate that the builders can be …

Core: Add InternalData read and write builders

---

api/src/main/java/org/apache/iceberg/UpdateSchema.java
api/src/main/java/org/apache/iceberg/expressions/Expressions.java
api/src/main/java/org/apache/iceberg/types/Types.java
core/src/main/java/org/apache/iceberg/SchemaParser.java
core/src/main/java/org/apache/iceberg/SchemaUpdate.java
core/src/main/java/org/apache/iceberg/mapping/MappingUtil.java
core/src/main/java/org/apache/iceberg/schema/UnionByNameVisitor.java
core/src/test/java/org/apache/iceberg/TestSchemaUnionByFieldName.java
core/src/test/java/org/apache/iceberg/TestSchemaUpdate.java
flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/TestFlinkCatalogTable.java
flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/TestFlinkCatalogTable.java
flink/v1.20/flink/src/test/java/org/apache/iceberg/flink/TestFlinkCatalogTable.java

This adds default value support to `UpdateSchema` and the implementation of it in core.
The API has new methods that accept a default value:
* `addColumn(String name, Type type, String doc, Object defaultValue)`
* `addRequiredColumn(String name, Type type, String doc, Object defaultValue)`
* `updateColumnDefault(String name, Object defaultValue)`
* `updateColumn(String name, Type type, String doc, Object defaultValue)`
The new methods always require supplying a doc string, which can be `null`. However, callers should not need to know to pass `null` when there is no doc string. Because the type of a default value is `Object`, adding additional method signatures that omit the doc string would conflict (for instance `addColumn("a", StringType.get(), "default or description?")`).
To make the …

API, Core: Support default values in UpdateSchema

---

site/overrides/home.html

Removed Call for Papers CTA and added link to icebergsummit2025.com with 'Register Now!' CTA.

update site to include iceberg summit link

---

core/src/main/java/org/apache/iceberg/util/TableScanUtil.java
core/src/test/java/org/apache/iceberg/util/TestTableScanUtil.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/sql/TestSelect.java

Currently, `TableScanUtil.adjustSplitSize(...)` would handle the situations where parameter `splitSize` is negative, however, it doesn't consider the situation where `splitSize` equals 0. That is to say, in a calculation engine like Spark, if we query a table after set it's property `read.split.target-size` to a negative value like `-1`, we will succeed and get  the result, since the default `read.split.adaptive-size.enabled` is true. Meanwhile, if we query a table after set it's property `read.split.target-size` to 0, we will fail with the error message `/ by zero`.
This PR add validation for the parameter `splitSize` in `TableScanUtil.adjustSplitSize(...)` to ensure that errors can be uniformly thrown when it's less than or equal to 0.

Core: Fix divide by zero when adjust split size

---

api/src/main/java/org/apache/iceberg/types/Types.java
api/src/test/java/org/apache/iceberg/TestSchema.java
api/src/test/java/org/apache/iceberg/types/TestTypeUtil.java
arrow/src/main/java/org/apache/iceberg/arrow/vectorized/VectorizedArrowReader.java
core/src/main/java/org/apache/iceberg/MetricsUtil.java
core/src/test/java/org/apache/iceberg/TestDeleteFiles.java
core/src/test/java/org/apache/iceberg/TestSchemaParser.java
core/src/test/java/org/apache/iceberg/avro/TestReadDefaultValues.java
core/src/test/java/org/apache/iceberg/rest/requests/TestCreateTableRequest.java
data/src/test/java/org/apache/iceberg/data/DataTest.java
flink/v1.20/flink/src/main/java/org/apache/iceberg/flink/sink/shuffle/SortKeySerializer.java
flink/v1.20/flink/src/main/java/org/apache/iceberg/flink/sink/shuffle/SortKeyUtil.java
kafka-connect/kafka-connect/src/main/java/org/apache/iceberg/connect/data/SchemaUtils.java
orc/src/main/java/org/apache/iceberg/orc/OrcToIcebergVisitor.java
orc/src/test/java/org/apache/iceberg/orc/TestBuildOrcProjection.java
spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/data/AvroDataTest.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/data/AvroDataTest.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/data/AvroDataTest.java

This is a follow up to #12211. While adding support for default values in `UpdateSchema`, many of the changes were to use the `NestedField` builder's copy constructor, `from(NestedField)`, so that field defaults are not dropped. Dropping defaults is easy to do when using the `of` factory method that was previously used to copy fields.
This PR deprecates that factory method and removes deprecated uses of `NestedField` methods.

API: Deprecate NestedType.of in favor of builder

---

.github/workflows/publish-iceberg-rest-fixture-docker.yml

https://github.com/apache/iceberg/actions/workflows/publish-iceberg-rest-fixture-docker.yml has failed since 2 days ago due to qemu version change (https://github.com/docker/setup-qemu-action/issues/198).

Docker: Pin QEMU version temporarily

---

site/docs/about.md

Fixes #12265 
Button now points to /spark-quickstart (same as 'Learn More' on the homepage).

Minor: update Learn More to point to spark quickstart

---

open-api/Makefile
open-api/requirements.txt

Build: Bump datamodel-code-generator from 0.27.2 to 0.28.1

---

spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/actions/RewriteTablePathSparkAction.java

The original message returns "... from version 'null' to ..."

Spark 3.5: Fix job description of RewriteTablePathSparkAction

---

open-api/rest-catalog-open-api.py
open-api/rest-catalog-open-api.yaml

dev list discussion: https://lists.apache.org/thread/kkj1f98v035p2k25jpcb5mboc9bpsk58
dev list voting: https://lists.apache.org/thread/bm9x6f9lxh2901j2scwoqs2gf6mlm6yt

OpenAPI: Add overwrite option when registering an iceberg table

---

api/src/main/java/org/apache/iceberg/types/Types.java
api/src/test/java/org/apache/iceberg/TestPartitionSpecValidation.java
api/src/test/java/org/apache/iceberg/TestSchema.java
core/src/test/java/org/apache/iceberg/TestSchemaUpdate.java

This updates `NestedField` to check that `UnknownType` is not used in a required field, which is [not permitted by the spec](https://github.com/apache/iceberg/blob/main/format/spec.md#primitive-types). It also checks that default values are cast to the correct type or are rejected.

API: Reject unknown type for required fields and validate defaults

---

api/src/test/java/org/apache/iceberg/expressions/TestInclusiveMetricsEvaluator.java

While working on expressions for variant, I found that all of the test assertions for `notStartsWith` were short-circuiting because of a `mayContainNull` check that was always true. If a file may contain null, `notStartsWith` will always select the file because null does not start with the prefix. Because all of the test files reported at least one non-null value, this was used for every assertion.
This PR updates the test `DataFile` instances to report 0 null values, fixes the value count to match the number of rows (for correctness), and adds a positive case where `notStartsWith` will skip a file because all rows must start with the prefix.

API: Fix TestInclusiveMetricsEvaluator notStartsWith tests

---

api/src/test/java/org/apache/iceberg/types/TestTypeUtil.java
core/src/test/java/org/apache/iceberg/TestSchemaUnionByFieldName.java

Collision between https://github.com/apache/iceberg/commit/93ef86112a238b584e2171b11c40cfefcdd8731d and https://github.com/apache/iceberg/commit/0b47faaada2aafa42c118be78445f6c40fc0ead6

Fix CI: Update tests with `UnknownType` from `Required` to `Optional`

---

core/src/main/java/org/apache/iceberg/variants/Variants.java
core/src/test/java/org/apache/iceberg/variants/VariantTestUtil.java
parquet/src/main/java/org/apache/iceberg/data/parquet/BaseParquetReaders.java
parquet/src/main/java/org/apache/iceberg/parquet/ParquetSchemaUtil.java
parquet/src/main/java/org/apache/iceberg/parquet/ParquetValueReaders.java
parquet/src/main/java/org/apache/iceberg/parquet/ParquetVariantReaders.java
parquet/src/main/java/org/apache/iceberg/parquet/ParquetVariantVisitor.java
parquet/src/main/java/org/apache/iceberg/parquet/PruneColumns.java
parquet/src/main/java/org/apache/iceberg/parquet/TypeToMessageType.java
parquet/src/main/java/org/apache/iceberg/parquet/TypeWithSchemaVisitor.java
parquet/src/main/java/org/apache/iceberg/parquet/VariantReaderBuilder.java
parquet/src/test/java/org/apache/iceberg/parquet/TestVariantReaders.java

This adds Parquet readers for Variant data, including for shredded fields.
The readers are built using a new Variant visitor that is plugged into the existing Parquet type visitor by returning a Variant visitor class. When a Variant visitor is present, it is called to produce a result to pass into the Parquet `variant` visitor method. This PR adds a Variant visitor that produces Parquet readers that handle metadata, serialized values, and shredded values.
Tests are in `TestVariantReaders`.
This does not support Variant arrays. I intend to follow up with support after this is reviewed.

Parquet: Implement Variant readers

---

docs/docs/spark-procedures.md

Documentation for #11931 #11555 
I took wording and docs with original author of @flyrain and @szehon-ho 
Also @manuzhang is interested in this and wondering if @amogh-jahagirdar is ready to take this as part of 1.8

Docs: Add rewrite-table-path in spark procedure

---

docs/docs/amoro.md
docs/mkdocs.yml

add [apache amoro(incubating)](https://amoro.apache.org) describe with iceberg (#11965)

Docs: add apache amoro(incubating) with iceberg (#11965)

---

core/src/main/java/org/apache/iceberg/rest/RESTSessionCatalog.java
core/src/test/java/org/apache/iceberg/rest/TestRESTCatalog.java
core/src/test/java/org/apache/iceberg/rest/TestRESTViewCatalog.java

This backports #12314 to 1.8.x

[1.8.x] Core: Fallback to GET requests for namespace/table/view exists checks

---

parquet/src/main/java/org/apache/iceberg/parquet/Parquet.java

This backports #12305 to 1.8.x

[1.8.x] Parquet: Fix performance regression in reader init (#12305)

---

core/src/main/java/org/apache/iceberg/rest/RESTObjectMapper.java
core/src/main/java/org/apache/iceberg/util/JsonUtil.java
mr/build.gradle

this backports #12224 to 1.8.x

[1.8.x] Core: Adjust Jackson settings to handle large metadata json (#12224)

---

.baseline/checkstyle/checkstyle.xml

The rule already exists for class type parameters:
```
<module name="ClassTypeParameterName"> 
<property name="format" value="(^[A-Z][0-9]?)$|([A-Z][a-zA-Z0-9]*[T]$)"/>
</module>
```
but it is missing for interfaces.

Checkstyle: Apply the same generic type naming rules to interfaces and classes

---

docs/docs/spark-configuration.md

revives PR: https://github.com/apache/iceberg/pull/8044
Request for adding this in docs : 
Past occurrence : 
[1] https://apache-iceberg.slack.com/archives/C025PH0G1D4/p1716740209929429
[2] https://apache-iceberg.slack.com/archives/C03LG1D563F/p1689071538157539?thread_ts=1688648903.712169&cid=C03LG1D563F
Recent occurrence (2/10): 
[1] https://apache-iceberg.slack.com/archives/C025PH0G1D4/p1739229168225159?thread_ts=1739220861.061949&cid=C025PH0G1D4

Docs: Add documentation for Rate limiting in Spark Structured Streaming

---

spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestAddFilesProcedure.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/SparkTableUtil.java

Fixes #12273 
I wrote a full overview of the behavior on the above ticket but the fix here is relatively simple. Instead of attempting to intuit what the Partition Spec should be and blindly using "0" as the given specId for any added files, we look in the table to see if there currently exists a Spec which contains a partitioning identical to the one in the Spark table.
We should extend this in the future to potentially handle V1 Tables (with null partitions being ignored) and cases where the Iceberg table partitioning ordering is different than the source table. For now I wanted to fix this as cleanly as possible while preserving the old behavior.

Spark 3.5: Fix Incorrect Spec Used With AddFiles Procedure

---

core/src/main/java/org/apache/iceberg/PartitionStatsUtil.java
core/src/test/java/org/apache/iceberg/TestPartitionStatsUtil.java

**Description**:
`PartitionMap` creates internal wrappers based on table specs `partitionType`, however, we are passing coercedPartition with `unified partition type` considering all specs as a `KEY`, leading to wrong evaluation. 
https://github.com/apache/iceberg/issues/12168
**Repro**:
https://github.com/apache/hive/blob/master/iceberg/iceberg-handler/src/test/queries/positive/iceberg_bucket_map_join_4.q
**Testing**:
- TestPartitionStatsUtil#testPartitionStatsWithSchemaEvolution2

Core: Handle partition evolution case in PartitionStatsUtil#computeStats

---

core/src/main/java/org/apache/iceberg/deletes/BaseDVFileWriter.java

Nit: Remove additional 'Iceberg' in Puffin footer payload

---

core/src/main/java/org/apache/iceberg/rest/RESTSessionCatalog.java
core/src/test/java/org/apache/iceberg/rest/TestRESTCatalog.java
core/src/test/java/org/apache/iceberg/rest/TestRESTViewCatalog.java
open-api/rest-catalog-open-api.yaml

this backports #12351 to 1.8.x

[1.8.x] Core: Remove namespace/table/view HEAD endpoints from defaults (#12351)

---

flink/v1.18/flink/src/main/java/org/apache/iceberg/flink/sink/shuffle/SketchDataStatistics.java
flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/sink/shuffle/SketchDataStatistics.java
flink/v1.20/flink/src/main/java/org/apache/iceberg/flink/sink/shuffle/SketchDataStatistics.java

The comment for SketchDataStatistics is incorrectly written as the comment information for MapDataStatistics. This PR mainly aims to correct the comments for SketchDataStatistics.

Flink: Fix the comment error in SketchDataStatistics

---

core/src/main/java/org/apache/iceberg/hadoop/HadoopFileIO.java

This PR follows a warning message on a compilation.
https://errorprone.info/bugpattern/DoubleCheckedLocking
```
/.../iceberg/core/src/main/java/org/apache/iceberg/hadoop/HadoopFileIO.java:125: warning: [DoubleCheckedLocking] Double-checked locking on non-volatile fields is unsafe
if (hadoopConf == null) {
^
(see https://errorprone.info/bugpattern/DoubleCheckedLocking)
Did you mean 'private volatile SerializableSupplier<Configuration> hadoopConf;'?
```

Core: Add "volatile" to HadoopFileIO#hadoopConf

---

aliyun/src/test/java/org/apache/iceberg/aliyun/oss/mock/AliyunOSSMockLocalStore.java
build.gradle
flink/v1.18/build.gradle
flink/v1.19/build.gradle
flink/v1.20/build.gradle
gradle/libs.versions.toml
mr/build.gradle
spark/v3.4/build.gradle
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/source/TestCompressionSettings.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/source/TestStructuredStreaming.java
spark/v3.5/build.gradle
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestStructuredStreaming.java

This is the continuation of https://github.com/apache/iceberg/pull/10932
The removal of Hadoop 2 was blocked by hive2 before. Now we have hive runtime removed from the source tree since https://github.com/apache/iceberg/pull/11801, Hadoop 2 removal should have been unblocked.
Removing Hadoop 2 is also required for upgrading parquet packages to the next version, as described in https://github.com/apache/iceberg/pull/12347#issuecomment-2670709563, latest parquet-hadoop code uses new FileSystem APIs introduced in Hadoop 3.
Related issue: https://github.com/apache/iceberg/issues/10940

Build: remove Hadoop 2 dependency

---

docs/docs/hive.md

iceberg/docs/docs/hive.md In the document Hive table creation statement word error, 
STORED BY written as STORED AS.
**Incorrect  statement**
**Correct statement**

[hive]:Fix Hive table creation syntax errors

---

gradle/libs.versions.toml
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/data/TestHelpers.java

Fixes https://github.com/apache/iceberg/issues/11945

Spark: Bump Spark 3.5 to 3.5.5

---

site/docs/releases.md

hive runtime has been removed since 1.8.0

Docs: Remove Hive runtime jar link from latest release

---

api/src/main/java/org/apache/iceberg/FileFormat.java
api/src/test/java/org/apache/iceberg/FileFormatTest.java
api/src/test/java/org/apache/iceberg/TestFileFormat.java

Closes #12300.
`FileFormat#fromFileName` should account for file names that are shorter than a file format extension.

Fix IndexOutOfBounds exception in FileFormat#fromFileName

---

core/src/test/java/org/apache/iceberg/TestTables.java

1: TestTableOperations already contains a member for the table name. It's redundant to have the same as a separate constuctor parameter for TestTable.
2: The 2 constructors for TestTableOperations have redundant code.

Core: Code cleanup around TestTable and TestTableOperations

---

api/src/main/java/org/apache/iceberg/UpdatePartitionStatistics.java
core/src/main/java/org/apache/iceberg/PartitionStatsUtil.java
core/src/main/java/org/apache/iceberg/SetPartitionStatistics.java
core/src/test/java/org/apache/iceberg/TestRowLineageMetadata.java
core/src/test/java/org/apache/iceberg/TestTables.java
data/src/main/java/org/apache/iceberg/data/PartitionStatsHandler.java
data/src/test/java/org/apache/iceberg/data/TestPartitionStatsHandler.java

Introduce APIs to write the partition stats into files in table default format using Iceberg internal writers and readers.
```
PartitionStatisticsFile partitionStatisticsFile =
PartitionStatsHandler.computeAndWriteStatsFile(testTable, "b1");
testTable.updatePartitionStatistics().setPartitionStatistics(partitionStatisticsFile).commit();
```

Data: Add partition stats writer and reader

---

format/spec.md

According to the Iceberg Geo types spec, the CRS format follows `type:identifier` and the only allowed types are `srid` or `projjson`, no `ogc`.
Whenever the spec says `OGC:CRS84`, it always refers to the following projjson object. It is pretty much the `srid:4326` but with axis order in `lon/lat`.
```
{
"$schema": "https://proj.org/schemas/v0.5/projjson.schema.json",
"type": "GeographicCRS",
"name": "WGS 84 longitude-latitude",
"datum": {
"type": "GeodeticReferenceFrame",
"name": "World Geodetic System 1984",
"ellipsoid": {
"name": "WGS 84",
"semi_major_axis": 6378137,
"inverse_flattening": 298.257223563
}
},
"coordinate_system": {
"subtype": "ellipsoidal",
"axis": [
{
"name": "Geodetic longitude",
"abbreviation": "Lon",
"direction": "east",
"unit": "degree"
},
{
"name": "Geodetic …
```

spec: fix the wrong example in Geo Types

---

docs/docs/spark-writes.md

Fix typo in delete statement: change database name from `dbl` to `db` in spark-writes.md

Fix typo in delete statement: change database name from "dbl"  to "db"  in spark-writes.md

---

core/src/main/java/org/apache/iceberg/MetadataUpdate.java
core/src/main/java/org/apache/iceberg/MetadataUpdateParser.java
core/src/main/java/org/apache/iceberg/RemoveSnapshots.java
core/src/main/java/org/apache/iceberg/TableMetadata.java
core/src/main/java/org/apache/iceberg/UpdateRequirements.java
core/src/test/java/org/apache/iceberg/TestMetadataUpdateParser.java
core/src/test/java/org/apache/iceberg/TestRemoveSnapshots.java
core/src/test/java/org/apache/iceberg/TestTableMetadata.java
core/src/test/java/org/apache/iceberg/TestTables.java
core/src/test/java/org/apache/iceberg/TestUpdateRequirements.java
core/src/test/java/org/apache/iceberg/catalog/CatalogTests.java

Similarly to removing partition specs, this PR improves RemoveSnapshots to also remove unused schemas.

Core: Change RemoveSnapshots to remove unused schemas

---

spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestAddFilesProcedure.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/Spark3Util.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/SparkTableUtil.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/procedures/AddFilesProcedure.java

Also renaming `validatePartitionSpec` method to `validatePartitionFilter` as it's actually validating the filters
Closes #12325

Spark: Infer partition spec in ADD_FILES procedure for FileTables than taking latest table spec

---

api/src/main/java/org/apache/iceberg/types/PrimitiveHolder.java
api/src/main/java/org/apache/iceberg/types/PrimitiveLikeHolder.java
api/src/main/java/org/apache/iceberg/types/Type.java
api/src/main/java/org/apache/iceberg/types/Types.java
api/src/test/java/org/apache/iceberg/types/TestSerializableTypes.java

Simple change to wrap variant in PrimitiveHolder similar to primitive type so when it's deserialized, it's returning the same instance.

Wrap variant in PrimitiveHoder so serialization can result same instance

---

flink/v1.20/flink/src/main/java/org/apache/iceberg/flink/FlinkCatalog.java
flink/v1.20/flink/src/main/java/org/apache/iceberg/flink/FlinkCatalogFactory.java
flink/v1.20/flink/src/main/java/org/apache/iceberg/flink/FlinkCreateTableOptions.java
flink/v1.20/flink/src/main/java/org/apache/iceberg/flink/FlinkDynamicTableFactory.java
flink/v1.20/flink/src/test/java/org/apache/iceberg/flink/TestFlinkCatalogTable.java
flink/v1.20/flink/src/test/java/org/apache/iceberg/flink/TestIcebergConnector.java
flink/v1.20/flink/src/test/java/org/apache/iceberg/flink/source/TestIcebergSourceSql.java

Creation of dynamic Iceberg table in Flink Catalog using the underlying physical Iceberg table using LIKE clause.
Currently (without the changes in PR),  create table in flink catalog works by configuring flink connector as described in,
[flink-connector](https://iceberg.apache.org/docs/nightly/flink-connector/#flink-connector )
But that needs user to provide the schema for the table. A way to tackle that is to do create table LIKE using below DDL.
```
CREATE TABLE table_wm (
eventTS AS CAST(t1 AS TIMESTAMP(3)),
WATERMARK FOR eventTS AS SOURCE_WATERMARK()
) WITH (
'connector'='iceberg',
'catalog-name'='iceberg_catalog',
'catalog-database'='testdb',
'catalog-table'='t'
) LIKE iceberg_catalog.testdb.t;
```
Options like connector, catalog-name, catalog-database, catalog-table need to be …

support create table like in flink catalog

---

api/src/main/java/org/apache/iceberg/variants/VariantData.java
core/src/main/java/org/apache/iceberg/variants/ShreddedObject.java
core/src/main/java/org/apache/iceberg/variants/VariantVisitor.java
core/src/main/java/org/apache/iceberg/variants/Variants.java
core/src/test/java/org/apache/iceberg/InternalTestHelpers.java
parquet/src/main/java/org/apache/iceberg/data/parquet/BaseParquetWriter.java
parquet/src/main/java/org/apache/iceberg/data/parquet/InternalWriter.java
parquet/src/main/java/org/apache/iceberg/parquet/Parquet.java
parquet/src/main/java/org/apache/iceberg/parquet/ParquetSchemaUtil.java
parquet/src/main/java/org/apache/iceberg/parquet/ParquetValueWriters.java
parquet/src/main/java/org/apache/iceberg/parquet/ParquetVariantReaders.java
parquet/src/main/java/org/apache/iceberg/parquet/ParquetVariantWriters.java
parquet/src/main/java/org/apache/iceberg/parquet/ParquetWriter.java
parquet/src/main/java/org/apache/iceberg/parquet/TypeToMessageType.java
parquet/src/main/java/org/apache/iceberg/parquet/VariantShreddingFunction.java
parquet/src/main/java/org/apache/iceberg/parquet/VariantWriterBuilder.java
parquet/src/test/java/org/apache/iceberg/parquet/TestVariantWriters.java

This PR implements Variant writers for Parquet based on a Parquet schema passed into the writer builder. It works basically the same as #12139.

Parquet: Implement Variant writers

---

format/spec.md

See for context: https://lists.apache.org/thread/gqqsnww6nqc50pddwn29blzghmb0m0h3

Spec: Add implementation note on `current-snapshot-id`

---

data/src/main/java/org/apache/iceberg/data/PartitionStatsHandler.java
data/src/test/java/org/apache/iceberg/data/TestPartitionStatsHandler.java

While adding the spark procedure, observed that puffin stats procedure exposes snapshot-id and partition stats procedure exposes branch name. 
https://github.com/apache/iceberg/pull/12451#discussion_r1980150585
There is no standard in Iceberg about which one to expose. 
But keeping both the interface same will be useful for users. Hence, updating the partition stats interface to use snapshot id instead of branch name. This is not a breaking change as this API is added in the same version (unreleased).

Data: Expose snapshot-id instead of branch for computing partition stats

---

data/src/test/java/org/apache/iceberg/data/parquet/TestGenericData.java
parquet/src/main/java/org/apache/iceberg/data/parquet/BaseParquetReaders.java
parquet/src/main/java/org/apache/iceberg/data/parquet/BaseParquetWriter.java
parquet/src/main/java/org/apache/iceberg/data/parquet/GenericParquetReaders.java
parquet/src/main/java/org/apache/iceberg/data/parquet/GenericParquetWriter.java
parquet/src/main/java/org/apache/iceberg/parquet/ParquetValueReaders.java
parquet/src/main/java/org/apache/iceberg/parquet/TypeToMessageType.java
parquet/src/test/java/org/apache/iceberg/parquet/TestInternalParquet.java

This adds Parquet readers and writers for unknown and nanosecond timestamp types. It supports Iceberg generics and the internal object model. Spark and Flink support will be added in following PRs.

Parquet: Support unknown and timestamp(9) in generics and internal model

---

open-api/rest-catalog-open-api.yaml

Docs: fix typo in rest-catalog-open-api.yaml.

Docs: fix typo in rest-catalog-open-api.yaml.

---

data/src/main/java/org/apache/iceberg/data/GenericAppenderFactory.java
data/src/test/java/org/apache/iceberg/TestGenericAppenderFactory.java

The **DataWriter** created using **GenericAppenderFactory** in the application does not configure metric writing behavior according to the table's properties. 
Based on previous modifications, such as **FlinkAppenderFactory**, this class should also invoke the correct API to configure the relevant properties

Core: Apply correct metric configs in GenericAppenderFactory

---

site/docs/talks.md

The Iceberg talks page hasn't been updated in a long time.  https://iceberg.apache.org/talks/ This PR updates it with recent ~20 brilliant talks from official Iceberg meetups from 2024-2025

Docs: Update Iceberg talks with recent Iceberg meetup sessions

---

aws/src/main/java/org/apache/iceberg/aws/s3/VendedCredentialsProvider.java
aws/src/test/java/org/apache/iceberg/aws/s3/TestVendedCredentialsProvider.java

When the `VendedCredentialProvider` is created, the `properties` typically already contain a valid credential from the first time a table is loaded. This PR uses the credential from the properties and otherwise falls back to loading a valid credential from the refresh endpoint in case the credential in `properties` is incomplete or expired.

AWS: Don't fetch credential from endpoint if properties contain a valid credential

---

aws/src/main/java/org/apache/iceberg/aws/s3/VendedCredentialsProvider.java
aws/src/test/java/org/apache/iceberg/aws/s3/TestVendedCredentialsProvider.java

This backports #12504 to 1.7.x

[1.7.x] AWS: Don't fetch credential from endpoint if properties contain a valid credential (#12504)

---

aws/src/main/java/org/apache/iceberg/aws/AssumeRoleAwsClientFactory.java
aws/src/main/java/org/apache/iceberg/aws/AwsClientFactories.java
aws/src/main/java/org/apache/iceberg/aws/AwsClientProperties.java
aws/src/main/java/org/apache/iceberg/aws/s3/DefaultS3FileIOAwsClientFactory.java
aws/src/main/java/org/apache/iceberg/aws/s3/S3FileIOProperties.java
aws/src/test/java/org/apache/iceberg/aws/s3/TestS3FileIOProperties.java
docs/docs/aws.md

This is a followup PR for #12299 to:
- Configure `max-concurrency` for CRT based async clients.
- Extend client region and credentials configuration mutations for async clients.
- Add docs for the `analytics-accelerator-s3` integration.

AWS: Update S3 async client configurations and docs for analytics-accelerator-s3

---

core/src/main/java/org/apache/iceberg/BaseTable.java

This PR implements:
* https://github.com/apache/iceberg/issues/12513
To unblock the next step of fixing:
* https://github.com/trinodb/trino/issues/25303

Make reporter() method public so that it can be accessed by Trino for BaseTable creation

---

spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/CatalogTestBase.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/TestBase.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/TestBaseWithCatalog.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/TestFunctionCatalog.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/source/TestPathIdentifier.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/sql/TestAlterTable.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestPathIdentifier.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/sql/TestAlterTable.java

Migrate Spark 3.4 tests based on JUnit 4 to Junit5 with AssertJ style. This is related to https://github.com/apache/iceberg/issues/7160
This PR includes the replacement of TestBases related to Spark tests, and a relevant test related to each TestBase for test purpose. Specifically the following TestBases and relevant tests are included:
* `CatalogTestBase` (replacing `SparkCatalogTestBase`)
* `TestAlterTable` (the relevant test)
* `TestBase` (replacing `SparkTestBase`)
* `TestPathIdentifier` (the relevant test)
* `TestBaseWithCatalog` (replacing `SparkTestBaseWithCatalog`)
* `TestFunctionCatalog` (the relevant test)

Migrate Spark 3.4 test base to JUnit5

---

core/src/main/java/org/apache/iceberg/GenericManifestFile.java
core/src/test/java/org/apache/iceberg/TestTableMetadata.java

This PR adds the proper constructor to allow use of the `SupportsIndexProjection` with `GenericManifestFile`.

Core: Fix support for GenericManifestFile index projection

---

core/src/main/java/org/apache/iceberg/rest/RESTSessionCatalog.java
core/src/test/java/org/apache/iceberg/catalog/CatalogTests.java
core/src/test/java/org/apache/iceberg/inmemory/TestInMemoryCatalog.java
core/src/test/java/org/apache/iceberg/jdbc/TestJdbcCatalog.java
core/src/test/java/org/apache/iceberg/jdbc/TestJdbcCatalogWithV1Schema.java
core/src/test/java/org/apache/iceberg/rest/TestRESTCatalog.java
hive-metastore/src/test/java/org/apache/iceberg/hive/TestHiveCatalog.java
nessie/src/test/java/org/apache/iceberg/nessie/TestNessieCatalog.java
open-api/src/testFixtures/java/org/apache/iceberg/rest/RCKUtils.java

Similar to #11064, but for table properties.

Core: Set missing table-default property in RESTSessionCatalog

---

api/src/main/java/org/apache/iceberg/types/AssignFreshIds.java
api/src/main/java/org/apache/iceberg/types/AssignIds.java
api/src/main/java/org/apache/iceberg/types/ReassignDoc.java
api/src/test/java/org/apache/iceberg/types/TestTypeUtil.java
core/src/test/java/org/apache/iceberg/catalog/CatalogTests.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/source/ScanTestBase.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/ScanTestBase.java

Fix for #12495
During table creation the schema is updated and new fieldIds are assigned based on the original schema. The new field data is copied from the original one, but the default and the initial values were not copied.

Core: Fix default and initial value handling on table creation

---

docs/docs/kafka-connect.md
kafka-connect/kafka-connect/src/main/java/org/apache/iceberg/connect/IcebergSinkConfig.java
kafka-connect/kafka-connect/src/main/java/org/apache/iceberg/connect/channel/Channel.java

In a Kafka setup where strict ACLs are applied, e.g. based on a certain `PREFIX` for [Transactional IDs](https://docs.confluent.io/platform/current/security/authorization/acls/overview.html#transactional-id-resource-type-operations), it is important to have the prefix configurable.
Currently, it is the name of the "Channel" (e.g. `"worker"` or `"coordinator"` for the 2 extending subclasses):
https://github.com/apache/iceberg/blob/540d6a6251e31b232fe6ed2413680621454d107a/kafka-connect/kafka-connect/src/main/java/org/apache/iceberg/connect/channel/Channel.java#L57-L67
This PR introduces an optional prefix to add - which by default is empty so that the behaviour is not changed to the current behaviour.

Kafka Connect: Add the configuration option to provide a transactional id prefix to use

---

spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/ScanTestBase.java

Seems like `configureTable` is not currently in use. This PR explicitly calls `configureTable` to configure the table.

Spark: Call configureTable in ScanTestBase to ensure proper table configuration

---

core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java

See https://github.com/apache/iceberg/issues/12539
I am adding the `io` to the `closeableGroup` with this PR. Any FileIO that is opened should ideally be closed and not left to linger for the garbage collector to pick up.
The `io` variable is passed to `JdbcViewOperations` and `JdbcTableOperations` outside this class, but those already get the `connections` variable passed in as well that gets closed. This makes me not super worried about a usages outside this class (this might be worth revisting?).

Core: fix "Unclosed S3FileIO" warning in JdbcCatalog

---

spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/TestSpark3Util.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/TestSparkSessionCatalog.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/actions/TestDeleteReachableFilesAction.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/actions/TestExpireSnapshotsAction.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/actions/TestRemoveDanglingDeleteAction.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteTablePathsAction.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/actions/TestSparkFileRewriter.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/TestSparkSessionCatalog.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/actions/TestDeleteReachableFilesAction.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/actions/TestExpireSnapshotsAction.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/actions/TestSparkFileRewriter.java

This PR migrates `SparkTestBase` related tests in Spark 3.4 into JUnit 5 with AssertJ. The following classes are included in this PR:
* In `spark` package:
* `TestSparkSessionCatalog` 
* `TestSpark3Util`
* In `spark.actions` package:
*  `TestDeleteReachableFilesAction`
* `TestExpireSnapshotsAction`
* `TestRemoveDanglingDeleteAction`
* `TestRewriteTablePathsAction` 
* `TestSparkFileRewriter`

Migrate Spark 3.4 TestBase related tests in spark and actions

---

api/src/main/java/org/apache/iceberg/variants/Serialized.java
api/src/main/java/org/apache/iceberg/variants/VariantMetadata.java
core/src/main/java/org/apache/iceberg/avro/Avro.java
core/src/main/java/org/apache/iceberg/avro/AvroWithPartnerVisitor.java
core/src/main/java/org/apache/iceberg/avro/BaseWriteBuilder.java
core/src/main/java/org/apache/iceberg/avro/GenericAvroReader.java
core/src/main/java/org/apache/iceberg/avro/InternalReader.java
core/src/main/java/org/apache/iceberg/avro/ValueReaders.java
core/src/main/java/org/apache/iceberg/avro/ValueWriters.java
core/src/main/java/org/apache/iceberg/avro/VariantConversion.java
core/src/main/java/org/apache/iceberg/data/avro/DataWriter.java
core/src/main/java/org/apache/iceberg/data/avro/PlannedDataReader.java
core/src/main/java/org/apache/iceberg/io/IOUtil.java
core/src/test/java/org/apache/iceberg/InternalTestHelpers.java
core/src/test/java/org/apache/iceberg/RandomInternalData.java
core/src/test/java/org/apache/iceberg/RandomVariants.java
core/src/test/java/org/apache/iceberg/avro/AvroTestHelpers.java
core/src/test/java/org/apache/iceberg/avro/RandomAvroData.java
core/src/test/java/org/apache/iceberg/avro/TestGenericAvro.java
core/src/test/java/org/apache/iceberg/avro/TestInternalAvro.java
data/src/test/java/org/apache/iceberg/data/DataTestHelpers.java
data/src/test/java/org/apache/iceberg/data/RandomGenericData.java
data/src/test/java/org/apache/iceberg/data/avro/TestGenericData.java
parquet/src/main/java/org/apache/iceberg/parquet/ParquetSchemaUtil.java
parquet/src/main/java/org/apache/iceberg/parquet/ParquetVariantWriters.java

This adds readers and writers for Variants in Avro. Avro generics, Iceberg generics, and the internal data model are supported.
Variant values are tested using `RandomVariants` to extend random data generation.

Avro: Add variant readers and writers

---

core/src/main/java/org/apache/iceberg/rest/HTTPRequest.java
core/src/test/java/org/apache/iceberg/rest/TestHTTPRequest.java

Before the introduction of `HTTPRequest`, it was technically possible, although unlikely, to create an `HTTPClient` without base URI. In such cases, all requests must have an absolute path.
This is currently not possible anymore, because `HTTPRequest.baseUri()` cannot be null.
This PR fixes this small behavioral regression by allowing `HTTPRequest.baseUri()` to return null, when the request path is absolute.

REST: HTTPRequest.baseUri() should be nullable

---

core/src/test/java/org/apache/iceberg/avro/TestAvroEncoderUtil.java
data/src/test/java/org/apache/iceberg/data/parquet/TestParquetEncryptionWithWriteSupport.java
parquet/src/main/java/org/apache/iceberg/data/parquet/GenericParquetWriter.java
parquet/src/main/java/org/apache/iceberg/data/parquet/InternalWriter.java
parquet/src/test/java/org/apache/iceberg/parquet/TestInternalParquet.java

This enables `supportsVariant()` in `DataTest` suites where the support exists and works.

Parquet, Core: Enable passing Variant tests

---

core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java
core/src/test/java/org/apache/iceberg/jdbc/TestJdbcViewCatalog.java

- `HiveCatalog` implemented `dropView` in https://github.com/apache/iceberg/pull/9852 and the view metadata will be purged from storage if `TableProperties.GC_ENABLED` is `true`(default)
- I think `JdbcCatalog` should also purge view metadata in the same way.
- Tests are borrowed from https://github.com/apache/iceberg/pull/9852/files

Core: JDBCCatalog's dropView() should purge metadata files if GC is enabled

---

core/src/main/java/org/apache/iceberg/DeleteFileIndex.java
core/src/main/java/org/apache/iceberg/ManifestGroup.java
data/src/test/java/org/apache/iceberg/data/FileHelpers.java
data/src/test/java/org/apache/iceberg/data/TestDataFileIndexStatsFilters.java
spark/v3.5/build.gradle
spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestCopyOnWriteDelete.java

The original issue here is that a user noted that Equality deletes were essentially being ignored on COW operations. I tracked this down to the fact that the data filter being used during COW was essentially being used to remove Equality Deletes that don't fit the COW operation.
This shouldn't have been an issue because "ignoreResiduals" essentially tells ManifestGroups to throw out data file level filters when it gets applied *BUT* this doesn't get passed through to the DeleteFileIndex. _This means while the filter won't be used to ignore data files, it will be used to ignore delete files for those data files_.|
To fix this I add an interface to the DeleteFileIndex Builder to actually take in the arg for ignoringResiduals and pass that through from the Manifest Group. Then within the …

Core, Spark 3.5: Apply Ignore Residuals to Delete Filtering

---

core/src/main/java/org/apache/iceberg/PartitionStats.java
core/src/test/java/org/apache/iceberg/TestPartitionStats.java
core/src/test/java/org/apache/iceberg/TestPartitionStatsUtil.java
data/src/test/java/org/apache/iceberg/data/TestPartitionStatsHandler.java

Spec was already optional for totalRecordCount.
https://iceberg.apache.org/spec/#partition-statistics-file
During the implementation, we decided to make all the counters to be initialized to zero. 
Recently, we concluded that total record count counter can still be optional. 
Based on the discussions from https://github.com/apache/iceberg/pull/12098#discussion_r1940551771
and https://lists.apache.org/thread/1dzcv7989q0hchjytyb8g219wo7nc1xm

Core: Make totalRecordCount optional in PartitionStats

---

docs/docs/hive.md

Our doc mentions 4.0.0-alpha-1, 4.0.0-alpha-2, and 4.0.0-beta-1, maybe because the Hive community had struggled to release 4.0.0. Now that it's been approximately 1 year since we released 4.0.0, I think we don't need to mention all the RC versions in our document.
https://hive.apache.org/general/downloads/

Docs: Update statements mentioning Hive's alpha/beta versions

---

flink/v1.20/flink/src/main/java/org/apache/iceberg/flink/source/IcebergTableSource.java
flink/v1.20/flink/src/test/java/org/apache/iceberg/flink/SqlBase.java
flink/v1.20/flink/src/test/java/org/apache/iceberg/flink/source/TestIcebergSourceSql.java
flink/v1.20/flink/src/test/java/org/apache/iceberg/flink/source/TestSqlBase.java

Iceberg Source to support Source Watermark, so it can be used in Flink WINDOW functions. https://github.com/apache/flink/blob/release-1.18/flink-table/flink-table-common/src/main/java/org/apache/flink/table/connector/source/abilities/SupportsSourceWatermark.java enables Flink to rely on the watermark strategy provided by the ScanTableSource itself.
```
CREATE TABLE table_wm (
eventTS AS CAST(t1 AS TIMESTAMP(3)),
WATERMARK FOR eventTS AS SOURCE_WATERMARK()
) WITH (
'watermark-column'='t1'
) LIKE iceberg_catalog.db.table;
```
**Reference:**
https://github.com/apache/iceberg/issues/10219
https://github.com/apache/iceberg/pull/9346
Previous discussion in PR, https://github.com/apache/iceberg/pull/12116 . Split into separate PR for easy review.

Flink: Support source watermark for flink sql windows

---

spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/source/SparkScan.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkScan.java

This fixes a bug in `SparkScan::estimateStatistics(Snapshot)`.
`Table::statisticsFiles()` returns a `List<StatisticsFile>`. We need to get the `StatisticsFile` with the `snapshotId` of the `Snapshot` for use in estimating the statistics.
I modified an existing test so that it fails without the fix and passes with it.

Spark: Use correct statistics file in SparkScan::estimateStatistics(Snapshot)

---

flink/v1.20/flink/src/main/java/org/apache/iceberg/flink/source/ScanContext.java

In the current code, the assignment of connector.iceberg.max-allowed-planning-failures uses FlinkReadOptions.MAX_ALLOWED_PLANNING_FAILURES_OPTION.defaultValue() instead of retrieving it from flinkReadConf. 
As a result, this configuration always remains at its default value of 3 and cannot be modified. 
This PR primarily aims to resolve this issue by ensuring that the configuration can be correctly assigned from the Flink config.

Flink: fix read config of connector.iceberg.max-allowed-planning-failures

---

flink/v1.18/flink/src/main/java/org/apache/iceberg/flink/source/ScanContext.java
flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/source/ScanContext.java

backport #12585 to the 1.19, and 1.18 branches

Flink: backport for fix read config of connector.iceberg.max-allowed-planning-failures to 1.18 and 1.19

---

api/src/main/java/org/apache/iceberg/ManifestFile.java
core/src/main/java/org/apache/iceberg/AllManifestsTable.java
core/src/main/java/org/apache/iceberg/ManifestLists.java
core/src/main/java/org/apache/iceberg/ManifestReader.java

This PR expands the use of InternalData for metadata reads to `ManifestsLists` and `AllManifestsTable` and uses a common iterable that exposes access to file metadata like Avro previously supported.  Implements the new metadata read path for both Avro and Parquet.

Core: Use InternalData with avro for readers.

---

core/src/main/java/org/apache/iceberg/rest/ErrorHandlers.java
core/src/main/java/org/apache/iceberg/rest/RESTSessionCatalog.java
core/src/test/java/org/apache/iceberg/catalog/CatalogTests.java
core/src/test/java/org/apache/iceberg/rest/RESTCatalogAdapter.java

Spec changes have been handled in https://github.com/apache/iceberg/pull/12518

Core: Handle NamespaceNotEmptyException in NamespaceErrorHandler

---

spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/actions/TestRemoveOrphanFilesAction.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/actions/TestRemoveOrphanFilesAction3.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteDataFilesAction.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteManifestsAction.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/actions/TestRemoveOrphanFilesAction.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/actions/TestRemoveOrphanFilesAction3.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteDataFilesAction.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteManifestsAction.java

This PR migrates the other tests in the `spark.actions` package in Spark 3.4 into JUnit 5 with AssertJ. The following classes are included in this PR:
* `TestRewriteDataFilesAction`
* `TestRewriteManifestsAction` 
* ~~`TestRewriteTablePathsAction` (backporting from https://github.com/apache/iceberg/pull/12569)~~
* `TestRemoveOrphanFilesAction` and `TestRemoveOrphanFilesAction3`

Migrate Spark 3.4 TestBase-related remaining tests in actions

---

spark/v3.4/build.gradle
spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/ExtensionsTestBase.java
spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMergeOnReadUpdate.java
spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMetadataTables.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/source/DVIterator.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/CatalogTestBase.java

this backports #12135 to Spark 3.4 and also includes changes around switching from JUnit4 to JUnit5

Spark 3.4: Test metadata tables with format-version=v3 / add ExtensionsTestBase

---

core/src/main/java/org/apache/iceberg/FileCleanupStrategy.java
core/src/main/java/org/apache/iceberg/RemoveSnapshots.java
core/src/test/java/org/apache/iceberg/TestRemoveSnapshots.java

The current implementation uses the deleteFile() of the FileIO even if it supports bulk operations. Even though the user of the RemoveSnapshots API can provide a custom Consumer to perform bulk deletion, Iceberg can be clever enough itself to find out if bulk deletion is possible on the FileIO.

Core: Bulk deletion in RemoveSnapshots

---

spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/SparkContentFile.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/actions/RewritePositionDeleteFilesSparkAction.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/actions/TestDeleteReachableFilesAction.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/actions/TestExpireSnapshotsAction.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteManifestsAction.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewritePositionDeleteFilesAction.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewritePositionDeleteFilesAction.java

This PR backports the Spark 3.5 Deletion Vectors related part including tests into Spark 3.4, to reflect the changes in https://github.com/apache/iceberg/pull/12048 and https://github.com/apache/iceberg/pull/11485 to Spark 3.4 as well . The following classes in the  `actions` package are mainly included:
* `RewritePositionDeleteFilesSparkAction` and `TestRewritePositionDeleteFilesAction.java` (backporting https://github.com/apache/iceberg/pull/12048)
* `TestRewriteManifest` (backporting https://github.com/apache/iceberg/pull/11457)
* The others tests are from https://github.com/apache/iceberg/pull/11485

Spark: Backport Spark 3.5 DVs related part to Spark 3.4

---

.palantir/revapi.yml
api/src/main/java/org/apache/iceberg/Metrics.java
api/src/main/java/org/apache/iceberg/util/BinaryUtil.java
api/src/main/java/org/apache/iceberg/util/UnicodeUtil.java
api/src/main/java/org/apache/iceberg/variants/SerializedObject.java
api/src/main/java/org/apache/iceberg/variants/SerializedPrimitive.java
api/src/main/java/org/apache/iceberg/variants/SerializedShortString.java
api/src/main/java/org/apache/iceberg/variants/VariantObject.java
api/src/main/java/org/apache/iceberg/variants/VariantPrimitive.java
api/src/main/java/org/apache/iceberg/variants/VariantUtil.java
core/src/main/java/org/apache/iceberg/FieldMetrics.java
core/src/main/java/org/apache/iceberg/MetricsUtil.java
core/src/main/java/org/apache/iceberg/variants/PrimitiveWrapper.java
core/src/main/java/org/apache/iceberg/variants/Variants.java
core/src/test/java/org/apache/iceberg/TestMetrics.java
data/src/test/java/org/apache/iceberg/TestMergingMetrics.java
orc/src/main/java/org/apache/iceberg/orc/OrcMetrics.java
parquet/src/main/java/org/apache/iceberg/data/parquet/BaseParquetReaders.java
parquet/src/main/java/org/apache/iceberg/data/parquet/BaseParquetWriter.java
parquet/src/main/java/org/apache/iceberg/parquet/ParquetConversions.java
parquet/src/main/java/org/apache/iceberg/parquet/ParquetMetrics.java
parquet/src/main/java/org/apache/iceberg/parquet/ParquetUtil.java
parquet/src/main/java/org/apache/iceberg/parquet/ParquetVariantUtil.java
parquet/src/main/java/org/apache/iceberg/parquet/ParquetWriteAdapter.java
parquet/src/main/java/org/apache/iceberg/parquet/ParquetWriter.java
parquet/src/main/java/org/apache/iceberg/parquet/PruneColumns.java
parquet/src/main/java/org/apache/iceberg/parquet/TypeWithSchemaVisitor.java
parquet/src/test/java/org/apache/iceberg/parquet/TestVariantMetrics.java
parquet/src/test/java/org/apache/iceberg/parquet/TestVariantWriters.java

This implements metrics for Variant types stored in Parquet files, using new visitors to produce the metrics.
This also refactors the existing metrics code to use a visitor. If I remember correctly, the metrics code predates the Parquet visitor. I think the visitor version is cleaner.

Parquet: Implement Variant metrics

---

spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/actions/RemoveDanglingDeletesSparkAction.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/actions/RewritePositionDeleteFilesSparkAction.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/source/PositionDeletesRowReader.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/source/SparkPositionDeletesRewrite.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/source/SparkWrite.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewritePositionDeleteFilesAction.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/data/TestHelpers.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/source/TestPositionDeletesTable.java

this backports #12250 and #12270 to Spark 3.4

Spark 3.4: Rewrite V2 deletes to V3 DVs / Detect dangling DVs properly

---

format/spec.md

Minor simplifications to the geo spec, noticed while doing the reference implementation.
1. Specify null as only valid default value for geo type (eliminate need for WKB in most implementation): 
2. Simplify json representation of the type 
Refs:
- [1] https://github.com/apache/iceberg/pull/12346#discussion_r1995896505)
- [2] https://github.com/apache/iceberg/pull/12346#discussion_r1995898210)

Spec: Geo spec simplifications

---

spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/source/SparkPositionDeltaWrite.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/source/SparkWrite.java

I see repeated logs as follows from `SparkWrite` in Spark driver.
```
25/02/26 01:48:56 INFO SparkWrite: Requesting 0 bytes advisory partition size for table ***
25/02/26 01:48:56 INFO SparkWrite: Requesting 0 bytes advisory partition size for table ***
25/02/26 01:48:56 INFO SparkWrite: Requesting 0 bytes advisory partition size for table ***
25/02/26 01:48:56 INFO SparkWrite: Requesting UnspecifiedDistribution as write distribution for table ***
25/02/26 01:48:56 INFO SparkWrite: Requesting UnspecifiedDistribution as write distribution for table ***
25/02/26 01:48:56 INFO SparkWrite: Requesting [] as write ordering for table ***
25/02/26 01:48:56 INFO SparkWrite: Requesting [] as write ordering for table ***
25/02/26 01:48:56 INFO SparkWrite: Requesting [] as write ordering for table …
```

Spark 3.5: Adjust repeated INFO logs to DEBUG in SparkWrite and SparkPositionDeltaWrite

---

spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/actions/RewriteTablePathSparkAction.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteTablePathsAction.java

backport #12006 #12172 #11929 #12282 #12569

Spark 3.4: Backport Spark actions changes in Spark rewrite_table_path procedure (#12006 #12172 #11929 #12282 #12569)

---

core/src/main/java/org/apache/iceberg/BaseRewriteManifests.java
core/src/main/java/org/apache/iceberg/BaseTable.java
core/src/main/java/org/apache/iceberg/BaseTransaction.java
core/src/test/java/org/apache/iceberg/TestCommitReporting.java

The rewrite manifests snapshot producer is the only one that does not generate an update event, thus listeners are not notified when a rewrite manifest occurs. This PR adds an update event for rewrite manifests.

Core: Add update event for rewrite manifests

---

data/src/main/java/org/apache/iceberg/data/PartitionStatsHandler.java
data/src/test/java/org/apache/iceberg/data/TestPartitionStatsHandler.java

Replaced Enum with Nested field because Iceberg follows this pattern in other files (Example: DataFile.java)
More info: https://github.com/apache/iceberg/pull/11216#discussion_r1992481276

Data: Refactor PartitionStatsHandler

---

aws/src/main/java/org/apache/iceberg/aws/RESTSigV4AuthManager.java
aws/src/main/java/org/apache/iceberg/aws/RESTSigV4AuthSession.java
aws/src/test/java/org/apache/iceberg/aws/TestRESTSigV4AuthManager.java

Also fixes a potential issue with context credentials, and improves unit tests.

AWS: fix incorrect parent session when calling delegate auth manager

---

spark/v3.4/build.gradle
spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/SparkRowLevelOperationsTestBase.java
spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestCopyOnWriteDelete.java
spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestCopyOnWriteMerge.java
spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestCopyOnWriteUpdate.java
spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestDelete.java
spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMerge.java
spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMergeOnReadDelete.java
spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMergeOnReadMerge.java
spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMergeOnReadUpdate.java
spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestUpdate.java
spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestCopyOnWriteDelete.java
spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestCopyOnWriteMerge.java
spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestCopyOnWriteUpdate.java
spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMerge.java
spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMergeOnReadMerge.java

This PR migrates `SparkRowLevelOperationsTestBase` related tests in Spark 3.4 into JUnit 5 with AssertJ. The following classes are included in this PR:
- `SparkRowLevelOperationsTestBase`
- `TestDelete`, and `TestCopyOnWriteDelete`/`TestMergeOnReadDelete`
- `TestMerge`,  and `TestCopyOnWriteMerge`/`TestMergeOnReadMerge`
- `TestUpdate`, and  `TestCopyOnWriteUpdate`/`TestMergeOnReadUpdate`

Spark 3.4: Migrate SparkRowLevelOperationsTestBase related tests to JUnit 5

---

core/src/test/java/org/apache/iceberg/TestRemoveSnapshots.java

1. Replace duplicate codes with `waitUntilAfter`
2. Remove unused variables
3. Remove redundant `toString`

Core: Enhance TestRemoveSnapshots

---

flink/v1.18/flink/src/main/java/org/apache/iceberg/flink/FlinkCatalog.java
flink/v1.18/flink/src/main/java/org/apache/iceberg/flink/FlinkCatalogFactory.java
flink/v1.18/flink/src/main/java/org/apache/iceberg/flink/FlinkCreateTableOptions.java
flink/v1.18/flink/src/main/java/org/apache/iceberg/flink/FlinkDynamicTableFactory.java
flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/TestFlinkCatalogTable.java
flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/source/TestIcebergSourceSql.java
flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/FlinkCatalog.java
flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/FlinkCatalogFactory.java
flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/FlinkCreateTableOptions.java
flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/FlinkDynamicTableFactory.java
flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/TestFlinkCatalogTable.java
flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/source/TestIcebergSourceSql.java

Backporting support create table like changes from Flink-1.20 to Flink-1.18/Flink-1.19.
https://github.com/apache/iceberg/pull/12199
High level changes:
Creation of dynamic Iceberg table in Flink Catalog using the underlying physical Iceberg table using LIKE clause.
Currently (without the changes in PR), create table in flink catalog works by configuring flink connector as described in,
[flink-connector](https://iceberg.apache.org/docs/nightly/flink-connector/#flink-connector)
But that needs user to provide the schema for the table. A way to tackle that is to do create table LIKE using below DDL.
CREATE TABLE table_wm (
eventTS AS CAST(t1 AS TIMESTAMP(3)),
WATERMARK FOR eventTS AS SOURCE_WATERMARK()
) WITH (
'connector'='iceberg',
'catalog-name'='iceberg_catalog', …

Flink: backport support create table like in flink catalog

---

docs/docs/spark-procedures.md

Doc: Update Instructions for rewrite_table_path.
We have recently been using rewrite_table_path and noticed an issue with the use of quotes in the examples provided in the documentation. While other procedures use single quotes for variables, this stored procedure uses double quotes.

Doc: Update Instructions for rewrite_table_path.

---

api/src/main/java/org/apache/iceberg/util/BucketUtil.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/functions/BucketFunction.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/sql/TestSparkBucketFunction.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/functions/BucketFunction.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/sql/TestSparkBucketFunction.java

This change removes unnecessary `toString()` conversions by directly processing UTF-8 bytes, improving efficiency and reducing memory allocations.

Spark, API: Enhance hashing efficiency by operating on raw UTF-8 bytes

---

spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/actions/RewriteDataFilesSparkAction.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteDataFilesAction.java

Spark 3.5: Fix RewriteDataFiles with partial progress enabled and max-failed-commits larger than total-file-group

---

flink/v1.18/flink/src/main/java/org/apache/iceberg/flink/source/IcebergTableSource.java
flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/source/TestIcebergSourceSql.java
flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/source/TestSqlBase.java
flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/source/IcebergTableSource.java
flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/source/TestIcebergSourceSql.java
flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/source/TestSqlBase.java

Backport changes in https://github.com/apache/iceberg/pull/12191 to 1.18,1.19 
Iceberg Source to support Source Watermark, so it can be used in Flink WINDOW functions. https://github.com/apache/flink/blob/release-1.18/flink-table/flink-table-common/src/main/java/org/apache/flink/table/connector/source/abilities/SupportsSourceWatermark.java enables Flink to rely on the watermark strategy provided by the ScanTableSource itself.
```
CREATE TABLE table_wm (
eventTS AS CAST(t1 AS TIMESTAMP(3)),
WATERMARK FOR eventTS AS SOURCE_WATERMARK()
) WITH (
'watermark-column'='t1'
) LIKE iceberg_catalog.db.table;
```
**Reference:**
https://github.com/apache/iceberg/issues/10219
https://github.com/apache/iceberg/pull/9346

Flink: Backport support source watermark for flink sql windows

---

spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/actions/RewriteDataFilesSparkAction.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteDataFilesAction.java

Spark 3.4: Fix RewriteDataFiles with partial progress enabled and max-failed-commits larger than total-file-group

---

aws-bundle/LICENSE
aws-bundle/NOTICE
aws-bundle/build.gradle
gradle/libs.versions.toml
kafka-connect/kafka-connect-runtime/hive/LICENSE
kafka-connect/kafka-connect-runtime/hive/NOTICE
kafka-connect/kafka-connect-runtime/main/LICENSE
kafka-connect/kafka-connect-runtime/main/NOTICE

This PR adds the dependencies from #12299 to `aws-bundle`. It also adds some missing `aws` dependencies and updates the corresponding `LICENSE`  and `NOTICE` files.

AWS: Update the aws-bundle with latest dependencies

---

docs/docs/spark-procedures.md

Doc: Remove Warning for resolved issue #11147 .
Reference: Spark 3.5: Fix NotSerializableException when migrating Spark tables #11157.

Doc: Remove Warning for resolved issue #11147.

---

flink/v1.18/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java
flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkDistributionMode.java
flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java
flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkDistributionMode.java

Backport for https://github.com/apache/iceberg/pull/11702
This PR a clean backport.

Backport #11702 to FLink1.19 and 1.18

---

format/spec.md

Now that equality deletes can co-exist with row lineage, update the spec to require lineage for v3.
This PR includes:
- removal of the flag to enable row lineage
- adjust language to remove reference of lineage being optional in v3
- clarify spec based language around what should/must be handled by writers

Spec: update to reflect lineage is required

---

.palantir/revapi.yml
core/src/main/java/org/apache/iceberg/MetadataUpdate.java
core/src/main/java/org/apache/iceberg/MetadataUpdateParser.java
core/src/main/java/org/apache/iceberg/TableMetadata.java
core/src/test/java/org/apache/iceberg/TestMetadataUpdateParser.java
core/src/test/java/org/apache/iceberg/TestUpdateRequirements.java
core/src/test/java/org/apache/iceberg/rest/requests/TestCommitTransactionRequestParser.java

This PR changes the `remove-snapshots` operation to run in bulk instead of single operations on the Rest Catalog server.
The remove-snapshots operation signature already accepts a list of snapshots IDs. However, each snapshot ID is stored in a dedicated `Metadata` object. This makes the operations not very efficient, causing performance issues, mentioned on: https://github.com/apache/iceberg/issues/12642.
The PR changes:
- Rename `MetadataUpdate` class `RemoveSnapshot` to `RemoveSnapshots`.
- Compute the entire snapshots IDs list and store them on the `RemoveSnapshots` instead of an individual snapshot ID.

Core: Enhance remove snapshots efficiency by executing them in bulk

---

core/src/main/java/org/apache/iceberg/MetadataColumns.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/source/SparkTable.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkMetadataColumns.java

This change adds
1. Row id and last updated sequence number metadata columns with field IDs as defined per the spec https://iceberg.apache.org/spec/#reserved-field-ids
2. Exposes these metadata columns in SparkTable for V3 tables. Added a test which ensures that the columns are resolved for V3+ tables, and fail for tables prior to V3.

Core, Spark: Add row lineage metadata columns, and surface them in SparkTable metadata columns

---

flink/v1.18/flink/src/main/java/org/apache/iceberg/flink/source/reader/RowConverter.java
flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/source/TestIcebergSourceBoundedConverterBase.java
flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/source/TestIcebergSourceBoundedGenericRecord.java
flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/source/TestIcebergSourceBoundedRow.java
flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/source/reader/RowConverter.java
flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/source/TestIcebergSourceBoundedConverterBase.java
flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/source/TestIcebergSourceBoundedGenericRecord.java
flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/source/TestIcebergSourceBoundedRow.java

This PR backports https://github.com/apache/iceberg/pull/11301

Flink: Backport RowConverter to Flink 1.19 and 1.18

---

flink/v1.20/flink/src/main/java/org/apache/iceberg/flink/sink/shuffle/SketchUtil.java
flink/v1.20/flink/src/test/java/org/apache/iceberg/flink/sink/shuffle/TestSketchUtil.java

When we enable range mode and set range-distribution-statistics-type=Sketch, a NullPointerException occurs if the number of sort keys is less than the downstream parallelism. In the SketchUtil.rangeBounds method, the SortKey[] array is initialized with null values. If the number of sort keys during a checkpoint duration is less than the downstream parallelism, this method will pass a SortKey[] array containing null values, which leads to a NullPointerException during serialization.
the error log like this:
```
org.apache.flink.util.FlinkException: Global failure triggered by OperatorCoordinator for 'Source: source -> flat -> deliver -> *anonymous_datastream_source$1*[1] -> Calc[2] -> range-shuffle' (operator 7016fb5b1ab54e21d55257a88ab9a39e).
at …
```

Flink: Fix npe in SketchUtil when numPartitions bigger than length of samples

---

core/src/main/java/org/apache/iceberg/RemoveSnapshots.java
core/src/main/java/org/apache/iceberg/SnapshotProducer.java
core/src/test/java/org/apache/iceberg/TestRemoveSnapshots.java

For code paths where an ExecutorService can be provided, the default call to ThreadPools.getWorkerPool() can be deferred until the point of actual usage.

Core: Lazy init workerPool in RemoveSnapshots and SnapshotProducer

---

flink/v1.18/flink/src/main/java/org/apache/iceberg/flink/source/reader/RowConverter.java
flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/source/reader/RowConverter.java

This PR backports https://github.com/apache/iceberg/pull/11838

Flink: Backport Typeinfo in RowConverter to Flink 1.19 and 1.18

---

hive-metastore/src/main/java/org/apache/iceberg/hive/HMSTablePropertyHelper.java
hive-metastore/src/main/java/org/apache/iceberg/hive/HiveOperationsBase.java
hive-metastore/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java
hive-metastore/src/main/java/org/apache/iceberg/hive/HiveViewOperations.java
hive-metastore/src/test/java/org/apache/iceberg/hive/TestHiveCatalog.java

HIVE-28801 Iceberg: Refactor HMS table parameter setting to be able to reuse

HIVE-28801 Iceberg: Refactor HMS table parameter setting to be able to reuse

---

docs/docs/hive.md
site/docs/multi-engine-support.md

Since we removed hive-runtime and discontinued support for Hive 2.x/3.x in version 1.8.0, we can now safely remove the Hive 2.x/3.x-related documentation from hive.md.

Doc: Remove Hive 2.x/3.x related docs in hive.md

---

core/src/main/java/org/apache/iceberg/TableMetadata.java

See my other comment on this in https://github.com/apache/iceberg/pull/12593#pullrequestreview-2742015722 where we should be returning `this` instead of `null`. 
@rdblue I'm not sure if https://github.com/apache/iceberg/pull/12672 makes it into 1.9.0, so we should probably just fix this separately so that we can do a 1.9.0 RC

Core: Return this instead of null in enableRowLineage()

---

api/src/main/java/org/apache/iceberg/io/CredentialSupplier.java

This API isn't used anywhere and we should deprecate it now and eventually remove it with 2.0.0

API: Deprecate CredentialSupplier

---

flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/sink/TestIcebergCommitter.java
flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/util/TestFlinkPackage.java
flink/v1.20/flink/src/test/java/org/apache/iceberg/flink/sink/TestIcebergCommitter.java
flink/v1.20/flink/src/test/java/org/apache/iceberg/flink/util/TestFlinkPackage.java
gradle/libs.versions.toml

This code also updates `testRecoveryFromSnapshotWithoutCompletedNotification` unit test, by removing the second assertion when we check that `harness.initializeState` is actually committing pending transactions. 
The reason we need to remove it, is because the flink test harness has a known limitation, where for recovery the lastCompleted checkpoint is always reset to 0, which makes it impossible to correctly commit the pending commits when the checkpointId > 0.
see: https://issues.apache.org/jira/browse/FLINK-36058
and: https://github.com/apache/flink/blob/master/flink-streaming-java/src/test/java/org/apache/flink/streaming/runtime/operators/sink/CommitterOperatorTestBase.java#L184

Upgrades Flink Version to 1.19.2 and 1.20.1

---

flink/v1.20/flink/src/main/java/org/apache/iceberg/flink/maintenance/api/TableMaintenance.java

This PR fixes two things:
1. Use checkArgument with `newRateLimit`, not rateLimit, as expected.
2. Add checkNotNull before checking `newRateLimit.toMillis() > 0`.

Flink: fix rateLimit argument check in TableMaintenance

---

spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestAlterTablePartitionFields.java
spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestAlterTableSchema.java
spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestBranchDDL.java
spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestComputeTableStatsProcedure.java
spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestFastForwardBranchProcedure.java
spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestPublishChangesProcedure.java
spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRegisterTableProcedure.java
spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestReplaceBranch.java
spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestTagDDL.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/procedures/FastForwardBranchProcedure.java
spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestAlterTablePartitionFields.java
spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestAlterTableSchema.java
spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestBranchDDL.java
spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestFastForwardBranchProcedure.java
spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestPublishChangesProcedure.java
spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRegisterTableProcedure.java
spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRewriteTablePathProcedure.java
spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestTagDDL.java

This PR migrates the below tests, which are related to extensions test base in Spark 3.4, into JUnit 5 with AssertJ. The following classes are included in this PR:
* Partition and schema changes:
* `TestAlterTablePartitionFields`
* `TestAlterTableSchema`
* Branching and Tagging:
* `TestBranchDDL` including refactoring
* `TestFastForwardBranchProcedure` (including the backport from https://github.com/apache/iceberg/pull/9196)
* `TestReplaceBranch`
* `TestPublishChangesProcedure` 
* `org.assertj.core.api.AssertionsForClassTypes.assertThat;` was used, but this is only for Java 8 which has been deprecated in recent Iceberg verions. So replace it with …

Migrate Spark 3.4 ExtensionsTestBase-related tests  for Partition, Schema and Branch/Tag

---

core/src/main/java/org/apache/iceberg/ManifestListWriter.java
core/src/main/java/org/apache/iceberg/ManifestReader.java
core/src/main/java/org/apache/iceberg/ManifestWriter.java
core/src/main/java/org/apache/iceberg/TableMetadataParser.java
core/src/main/java/org/apache/iceberg/avro/AvroIterable.java
core/src/main/java/org/apache/iceberg/view/ViewMetadataParser.java
orc/src/main/java/org/apache/iceberg/orc/OrcIterable.java
parquet/src/main/java/org/apache/iceberg/parquet/ParquetIO.java
parquet/src/main/java/org/apache/iceberg/parquet/ParquetUtil.java

Object Instances of the OutputFile & InputFile Interface are occasionally referenced directly in error messages. [Example](https://github.com/apache/iceberg/blob/0152075268851d397b60bcb66e5a7c346271dfd9/core/src/main/java/org/apache/iceberg/view/ViewMetadataParser.java#L194).
In order for the error message to print the path of the OutputFile/ InputFile, each implementation must have a toString() method overridden (typically with .location()).
However, if the Implementation does not override the toString, the result is:
`Failed to open file: com.random.folder.exec.store.iceberg.RandomOutputFileImplementation@5e3d9f12`
instead of leaving it up to the implementation to properly override the toString() method, it would be best to print the OutputFile.location() & InputFile.location(). There …

Core: Use OutputFile.location(), InputFile.location() in Error Messages

---

flink/v1.20/flink/src/test/java/org/apache/iceberg/flink/maintenance/operator/OperatorTestBase.java
flink/v1.20/flink/src/test/java/org/apache/iceberg/flink/maintenance/operator/TestTriggerManager.java

Since OperatorTestBase.MemoryLockFactory.open cleans the lock automatically, so it doesn't test when there is an existing lock.
This pr is aim to move the unlock to the TestCase before

Flink: Move unlock from MemoryLock open to TestCase Before

---

flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/maintenance/operator/OperatorTestBase.java
flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/maintenance/operator/TestTriggerManager.java

This pr is backport https://github.com/apache/iceberg/pull/12793 to Flink 1.19

Flink: backport #12793 to Flink 1.19

---

build.gradle
gradle/libs.versions.toml
spark/v3.5/build.gradle

Closes #12378
Closes #12381
Closes #12537
Closes #12538
As of Gradle 8, not explicitly depending upon `junit-platform-launcher` is [deprecated](https://docs.gradle.org/8.12/userguide/upgrading_version_8.html#test_framework_implementation_dependencies) (and will be required in Gradle 9)
~~Also adds `junit-bom` as per their [recommendation](https://junit.org/junit5/docs/current/user-guide/#running-tests-build-gradle-bom)~~

Build: Bump junit to 5.12.2

---

flink/v1.20/flink/src/main/java/org/apache/iceberg/flink/maintenance/operator/TriggerManager.java
flink/v1.20/flink/src/test/java/org/apache/iceberg/flink/maintenance/operator/TestTriggerManager.java

In the following scenario, the performance of TableMaintenance may not meet expectations:
1. The previous job stopped but left a lock that was not released.
2. A new job starts directly instead of recovering from state (when there is an existing lock, but no state).
3. TableMaintenance keeps failing to try to acquire the lock and cannot execute new tasks.
This PR aims to release the lock when the job starts without state to avoid the issue of failing to acquire the lock indefinitely.

Flink: fix unlock when previous job orphaned lock

---

flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/maintenance/operator/TriggerManager.java
flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/maintenance/operator/TestTriggerManager.java

This pr is aim to backport https://github.com/apache/iceberg/pull/12794 for Flink 1.19

Flink: backport fix TriggerManager to unlock task execution when previous job left an orphaned lock for Flink 1.19

---

flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/maintenance/operator/TestTriggerManager.java
flink/v1.20/flink/src/test/java/org/apache/iceberg/flink/maintenance/operator/TestTriggerManager.java

This pr aim to fix paramters for test recovery . It's a trivial change so I put changes in all Flink versions.

Flink: fix parameters for test recovery

---

core/src/test/java/org/apache/iceberg/catalog/CatalogTests.java
core/src/test/java/org/apache/iceberg/rest/TestRESTCatalog.java

Hi all,
This PR addresses several improvements to the `CatalogTests` class:
1.  **`listNamespacesWithEmptyNamespace` Fix:** It corrects a bug where the `listNamespacesWithEmptyNamespace` test doesn't properly check for `supportsEmptyNamespace` on catalogs. This ensures the test is only executed for catalogs that support empty namespaces, preventing potential errors or misleading test results.
2.  **Reserved Keyword Avoidance:** The tests were using `TABLE` as a table identifier, which is a reserved keyword in ANSI SQL and various database systems (e.g., [Spark](https://docs.databricks.com/aws/en/sql/language-manual/sql-ref-reserved-words)). This PR renames the identifier to `newtable` to avoid conflicts and improve compatibility with a wider range of catalogs. 
3.  **Configurable Table …

CatalogTests: Fix listNamespaces Check, Avoid Reserved Keyword, Allow Configurable Location

---

docs/docs/flink-connector.md
docs/docs/flink.md

Updating the doc as REST catalog type was introduced a while ago in https://github.com/apache/iceberg/pull/7044

Update the docs for working with Flink and REST catalog

---

spark/v3.4/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/parser/extensions/IcebergSqlExtensionsAstBuilder.scala
spark/v3.4/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/SetWriteDistributionAndOrderingExec.scala
spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestAncestorsOfProcedure.java
spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestCallStatementParser.java
spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestChangelogTable.java
spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestCherrypickSnapshotProcedure.java
spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestConflictValidation.java
spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestCreateChangelogViewProcedure.java
spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMetaColumnProjectionWithStageScan.java
spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRequiredDistributionAndOrdering.java
spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRollbackToSnapshotProcedure.java
spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRollbackToTimestampProcedure.java
spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestSetCurrentSnapshotProcedure.java
spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestSetWriteDistributionAndOrdering.java
spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestStoragePartitionedJoinsInRowLevelOperations.java
spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestSystemFunctionPushDownDQL.java
spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestSystemFunctionPushDownInRowLevelOperations.java
spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestWriteAborts.java
spark/v3.4/spark/src/main/scala/org/apache/spark/sql/catalyst/plans/logical/SetWriteDistributionAndOrdering.scala
spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestCallStatementParser.java
spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestChangelogTable.java
spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestCherrypickSnapshotProcedure.java
spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRollbackToSnapshotProcedure.java
spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRollbackToTimestampProcedure.java
spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestSetCurrentSnapshotProcedure.java
spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestSetWriteDistributionAndOrdering.java

This PR migrates the below tests, which are related to extensions test base in Spark 3.4, into JUnit 5 with AssertJ. The following classes are included in this PR:
* Snapshot Manipulation: 
* `TestAncestorsOfProcedure` 
* `TestCherrypickSnapshotProcedure` (Replace `import static org.assertj.core.api.AssertionsForClassTypes.assertThat;` with `Assertions.assertThat` because the previous one is only for Java 8 which has been deprecated in recent Iceberg verions)
* `TestSetCurrentSnapshotProcedure` (Replace `AssertionsForClassTypes.assertThat` with `Assertions.assertThat` as well)
* `TestRollbackToSnapshotProcedure` (Replace …

Migrate Spark 3.4 ExtensionsTestBase-related tests for Snapshot manipulation, ChangeLogView and Distribution/Ordering

---

aws/src/main/java/org/apache/iceberg/aws/s3/VendedCredentialsProvider.java
aws/src/test/java/org/apache/iceberg/aws/s3/TestVendedCredentialsProvider.java

This backports #12504 to 1.8.x

[1.8.x] AWS: Don't fetch credential from endpoint if properties contain a valid credential (#12504)

---

site/docs/contribute.md

This PR tries to add the test guideline for ArrayAsssertions to the AssertJ section (https://iceberg.apache.org/contribute/#assertj) in addition to the other data types such as map.

Docs: Add the recommended style for ArrayAssertions

---

spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/procedures/SnapshotTableProcedure.java

Spark 3.5: Use ProcedureInput for SnapshotTableProcedure.

Spark 3.5: Use ProcedureInput for SnapshotTableProcedure.

---

spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/procedures/MigrateTableProcedure.java

Spark 3.5: Use ProcedureInput for MigrateTableProcedure.

Spark 3.5: Use ProcedureInput for MigrateTableProcedure.

---

aws-bundle/LICENSE
aws-bundle/NOTICE
azure-bundle/LICENSE
azure-bundle/NOTICE
kafka-connect/kafka-connect-runtime/hive/LICENSE
kafka-connect/kafka-connect-runtime/hive/NOTICE
kafka-connect/kafka-connect-runtime/main/LICENSE
kafka-connect/kafka-connect-runtime/main/NOTICE

I will share my script soon.
Basically:
* for `aws-bundle`, `azure-bundle`, and `gcp-bundle`, it uses gradle module `dependencies` to get the correct versions (bundled in the artifact)
* for `karaf-connect-runtime` distributions (`main` and `hive`), it uses the content of the `lib` folder in distributions to get the correct versions (bundled in the zip)
This PR fixes the versions in the bundled artifacts and the distributions.

Fix versions in LICENSE and NOTICE

---

spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/procedures/MigrateTableProcedure.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/procedures/SnapshotTableProcedure.java

Spark3.4: Backport ProcedureInput for MigrateTableProcedure And SnapshotTableProcedure (#12782 #12783)

Spark3.4: Backport ProcedureInput for MigrateTableProcedure And SnapshotTableProcedure (#12782 #12783)

---

core/src/main/java/org/apache/iceberg/ManifestReader.java
core/src/main/java/org/apache/iceberg/util/PartitionUtil.java
core/src/test/java/org/apache/iceberg/TestRowLineageAssignment.java
core/src/test/java/org/apache/iceberg/data/DataTest.java
data/src/test/java/org/apache/iceberg/data/DataTestHelpers.java
data/src/test/java/org/apache/iceberg/data/parquet/TestGenericData.java
parquet/src/main/java/org/apache/iceberg/data/parquet/BaseParquetReaders.java
parquet/src/main/java/org/apache/iceberg/data/parquet/GenericParquetReaders.java
parquet/src/main/java/org/apache/iceberg/data/parquet/InternalReader.java
parquet/src/main/java/org/apache/iceberg/parquet/ParquetValueReaders.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/data/SparkParquetReaders.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/source/SparkBatch.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/SparkTestHelperBase.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/data/AvroDataTest.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/data/GenericsHelpers.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/data/TestSparkParquetReader.java

This adds readers for `_row_id` and `_last_updated_sequence_number` in Spark and the generic data model.

Spark: Add _row_id and _last_updated_sequence_number readers

---

api/src/main/java/org/apache/iceberg/expressions/BoundExtract.java
api/src/main/java/org/apache/iceberg/expressions/InclusiveMetricsEvaluator.java
api/src/main/java/org/apache/iceberg/expressions/PathUtil.java
api/src/test/java/org/apache/iceberg/expressions/TestExpressionBinding.java
api/src/test/java/org/apache/iceberg/expressions/TestPathUtil.java
core/src/test/java/org/apache/iceberg/expressions/TestInclusiveMetricsEvaluatorWithExtract.java
parquet/src/main/java/org/apache/iceberg/parquet/ParquetVariantUtil.java
parquet/src/test/java/org/apache/iceberg/parquet/TestVariantMetrics.java

This updates the Parquet metrics conversion to use normalized JSON paths instead of joining field names using `.`. A normalized path is a more reliable representation that preserves the distinction between `[a.b][c]`, `[a][b][c]` and `[a.b.c]`.
This implements the changes from #12658. Currently, the spec does not cover how bounds should be stored for variants, but I think we are in agreement about using normalized paths, so I would like to get this in to avoid writing incorrect bounds in the 1.9.0 release.

API: Use normalized JSON path to identify Variant fields

---

spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestAddFilesProcedure.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/procedures/AddFilesProcedure.java

Spark 3.5: Add Parallelism Parameter Validation to AddFilesProcedure.

Spark 3.5: Add Parallelism Parameter Validation to AddFilesProcedure.

---

spark/v3.4/spark/src/test/java/org/apache/iceberg/TaskCheckHelper.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/TestDataFileSerialization.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/TestFileIOSerialization.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/TestHadoopMetricsContextSerialization.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/TestManifestFileSerialization.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/TestScanTaskSerialization.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/TestTableSerialization.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/actions/TestComputeTableStatsAction.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/actions/TestCreateActions.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/actions/TestSnapshotTableAction.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/functions/TestSparkFunctions.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/TaskCheckHelper.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/TestFileIOSerialization.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/TestScanTaskSerialization.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/actions/TestComputeTableStatsAction.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/actions/TestCreateActions.java

This PR migrates the following Spark 3.4 tests to JUnit 5 with AssertJ:
* In the`extensions` package:
* `TestComputeTableStatsAction` including refactoring
* `TestCreateActions` including refactoring
* `TestSnapshotTableAction`
* In the `functions` package: `TestFunctions`
* Under the `spark`:
* `TestTableSerialization`
* `TestScanTaskSerialization`
* `TestManifestFileSerialization`
* `TestFileIOSerialization`
* `TestDataFileSerialization`
* `TaskCheckHelper`

Spark3.4: Migrate tests in spark, extensions and functions

---

api/src/test/java/org/apache/iceberg/variants/TestSerializedMetadata.java

The error msg might be missing when the tests are executed with different JDK versions, so it's better to skip checking the underlying error msg to avoid flakiness in test executions

API: Don't check underlying error msg on AIOOBE

---

.github/workflows/site-ci.yml

I merged a [spec-change earlier today](https://github.com/apache/iceberg/pull/12644), but noticed that it was not live on the website. I think it would be good to get these changes out right away.

Add `format/` to site-ci

---

docs/docs/daft.md

We did a major refresh of Daft docs on our end, so want to make sure the links are also updated on your end!
One thing to note:
On our docs, we renamed the below fields, let me know if it makes sense to update these as well: 
| Iceberg | Daft |
| ------- | ---- |
| STRUCT<[field_name: field_type,]> | [daft.DataType.struct(fields)](https://www.getdaft.io/projects/docs/en/latest/api/datatypes/#daft.datatype.DataType.struct) | 
| LIST<element_type> | [daft.DataType.list(element_type)](https://www.getdaft.io/projects/docs/en/latest/api/datatypes/#daft.datatype.DataType.list)| 
| MAP<key_type, value_type> | [daft.DataType.map(key_type, value_type)](https://www.getdaft.io/projects/docs/en/latest/api/datatypes/#daft.datatype.DataType.map) |
Here's our page for reference: …

update links to daft docs

---

core/src/main/java/org/apache/iceberg/variants/ShreddedObject.java
format/spec.md

This makes a slight change to the spec for v3 default values.
Previously, the spec allowed default values for struct fields in the struct default and in fields. For example, this was valid:
```sql
ALTER TABLE t ADD COLUMN point struct<x int NOT NULL DEFAULT 0, y int NOT NULL DEFAULT 0> DEFAULT struct(-1, -1)
```
This would result in a different write default depending on whether a field (default to 0) or the struct itself (default fields to -1) was missing. This behavior is difficult to implement correctly and unnecessary. It is also confusing what will happen when attempting to modify the struct's default, which should not change field defaults, and what will be used for a field's initial default.
The proposed change is to always track field defaults in the struct fields. This results in …

Spec: Avoid struct field conflicts in default values

---

core/src/main/java/org/apache/iceberg/view/ViewMetadata.java
core/src/test/java/org/apache/iceberg/view/TestViewMetadata.java
core/src/test/java/org/apache/iceberg/view/TestViewMetadataParser.java

* Fixes #12809
* Apply the fixes from https://github.com/apache/iceberg-rust/pull/1218 by @c-thiel

Core: Ensure reactivated view version uses correct timestamp

---

spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/actions/NDVSketchUtil.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/actions/NDVSketchUtil.java

We renamed the method from `newArrayList` to `newArrayListWithExpectedSize` because some user tables may contain hundreds or even thousands of columns. If the expected capacity (size) of the collection is not specified in advance, dynamic resizing operations will trigger multiple memory copy operations.

Spark: Use newArrayListWithExpectedSize instead of newArrayList for NDVSketchUtil

---

flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/source/StreamingStartingStrategy.java
flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/source/enumerator/ContinuousSplitPlannerImpl.java
flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/source/enumerator/TestContinuousSplitPlannerImpl.java
flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/source/enumerator/TestContinuousSplitPlannerImplStartStrategy.java

backports [#12839](https://github.com/apache/iceberg/pull/12839)

Flink: Backport add StreamingStartingStrategy.INCREMENTAL_FROM_LATEST_SNAPSHOT_EXCLUSIVE to Flink 1.19

---

flink/v2.0/flink/src/main/java/org/apache/iceberg/flink/maintenance/operator/LockRemover.java
flink/v2.0/flink/src/test/java/org/apache/iceberg/flink/maintenance/operator/TestLockRemover.java

In LockRemover, I noticed we missed `lockFactory.open()` before `this.lock = lockFactory.createLock()`. This could lead to an NPE since the factory isn't initialized and we have to close lock after (similar to the pool in jdbcFactory).
This pr is aim to add the init of lockFactory when LockRemover init.

Flink: Add lockFactory open in LockRemover

---

api/src/main/java/org/apache/iceberg/variants/SerializedArray.java
api/src/main/java/org/apache/iceberg/variants/VariantArray.java
api/src/test/java/org/apache/iceberg/variants/VariantTestUtil.java
core/src/main/java/org/apache/iceberg/variants/ValueArray.java
core/src/test/java/org/apache/iceberg/RandomVariants.java
parquet/src/main/java/org/apache/iceberg/parquet/ParquetVariantUtil.java
parquet/src/main/java/org/apache/iceberg/parquet/ParquetVariantWriters.java
parquet/src/main/java/org/apache/iceberg/parquet/VariantWriterBuilder.java
parquet/src/test/java/org/apache/iceberg/parquet/TestVariantWriters.java

Implement Variant array write for Parquet.
https://github.com/apache/iceberg/pull/12512 has implemented the Variant readers for array. This PR is to implement the Variant writer for arrays. We are adding writing non-shredded and shredded arrays.

Parquet variant array write

---

spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/sql/TestAggregatePushDown.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/sql/TestCreateTable.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/sql/TestCreateTableAsSelect.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/sql/TestDeleteFrom.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/sql/TestDropTable.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/sql/TestFilterPushDown.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/sql/TestNamespaceSQL.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/sql/TestRefreshTable.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/sql/TestSelect.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/sql/TestAggregatePushDown.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/sql/TestCreateTable.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/sql/TestCreateTableAsSelect.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/sql/TestDeleteFrom.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/sql/TestDropTable.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/sql/TestNamespaceSQL.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/sql/TestRefreshTable.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/sql/TestSelect.java

This PR migrates the following Spark 3.4 tests in the `spark.sql` package to JUnit 5 with AssertJ:
* `TestAggregatePushDown`
* `TestCreateTable`
* `TestCreateTableAsSelect`
* `TestDeleteFrom`
* `TestDropTable`
* `TestFilterPushDown`
* `TestNamespaceSQL`
* `TestRefreshTable`
* `TestSelect`

Spark 3.4: Migrate tests in sql

---

flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/maintenance/operator/LockRemover.java
flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/maintenance/operator/TestLockRemover.java
flink/v1.20/flink/src/main/java/org/apache/iceberg/flink/maintenance/operator/LockRemover.java
flink/v1.20/flink/src/test/java/org/apache/iceberg/flink/maintenance/operator/TestLockRemover.java

This pr is backport https://github.com/apache/iceberg/pull/12900 to  Flink 1.20 and 1.19.

Flink: Backport Add lockFactory open in LockRemover for table maintenance to Flink 1.20 and 1.19

---

docs/mkdocs.yml

This PR adds DuckDB in the menu among the systems supporting Iceberg. The link points to DuckDB's [`iceberg` extension](https://duckdb.org/docs/preview/core_extensions/iceberg/overview).

Docs: Add DuckDB

---

spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/sql/TestSparkBucketFunction.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/sql/TestSparkDaysFunction.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/sql/TestSparkHoursFunction.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/sql/TestSparkMonthsFunction.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/sql/TestSparkTruncateFunction.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/sql/TestSparkYearsFunction.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/sql/TestStoragePartitionedJoins.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/sql/TestTimestampWithoutZone.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/sql/TestSparkBucketFunction.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/sql/TestSparkDaysFunction.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/sql/TestSparkHoursFunction.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/sql/TestSparkMonthsFunction.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/sql/TestSparkTruncateFunction.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/sql/TestSparkYearsFunction.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/sql/TestTimestampWithoutZone.java

This PR migrates the following Spark 3.4 partition transform tests (and some additional tests) in the `spark.sql` package to JUnit 5 with AssertJ:
Partition transform:
* `TestSparkBucketFunction`
* `TestSparkDaysFunction`
* `TestSparkHoursFunction`
* `TestSparkMonthsFunction`
* `TestSparkTruncateFunction`
* `TestSparkYearsFunction`
Others:
* `TestTimestampWithoutZone`
* `TestStoragePartitionedJoins`

Spark 3.4: Migrate Spark Partition Transform tests

---

open-api/rest-catalog-open-api.yaml

The existence of the 419 AuthenticationTimeoutResponse status code caused confusion in the Iceberg community on the following two questions:
- whether the error response should be issued by a REST catalog on token expiry over 401 UnauthorizedResponse
- and how the client should respond on 419 response (vs a 401 response)
The updated description follows the RFC language of using SHOULD and MAY to be make these more clear for the REST catalog as well as the client responding to the status response.

OpenAPI: Use more clear language in recommending error responses

---

format/spec.md

In https://github.com/apache/iceberg/pull/12644, the spec was clarified that for a partition field, `source-id` should always be written if has a single-argument transform, and `source-ids` should be written instead if it has a multi-argument transform.
There is a statement left over that conflicts with the above. In this PR, we remove that statement.

Spec: Remove misleading statement about source-ids

---

api/src/test/java/org/apache/iceberg/TestIcebergBuild.java
build.gradle

Fixes #12926
The underlying issue is that we automatically bumped the Git Properties plugin which now uses a slightly different mechanism for determining what the version of the project is from before. To avoid any issues in the future, I decided to just explicitly pass in our custom version function to the plugin. 
I then added a few tests to check that we don't have an undefined value and if a version.txt file is present make sure it matches.

API, Build: Explicitly pass version into Git Properties Plugin

---

spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/sql/PartitionedWritesTestBase.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/sql/TestPartitionedWrites.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/sql/TestPartitionedWritesAsSelect.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/sql/TestPartitionedWritesToBranch.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/sql/TestPartitionedWritesToWapBranch.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/sql/TestUnpartitionedWrites.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/sql/TestUnpartitionedWritesToBranch.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/sql/UnpartitionedWritesTestBase.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/sql/PartitionedWritesTestBase.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/sql/TestPartitionedWritesAsSelect.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/sql/TestPartitionedWritesToBranch.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/sql/TestPartitionedWritesToWapBranch.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/sql/TestUnpartitionedWritesToBranch.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/sql/UnpartitionedWritesTestBase.java

This PR migrates the following Spark 3.4 other remaining tests (and some additional tests) in the `spark.sql` package to JUnit 5 with AssertJ:
* `PartitionedWritesTestBase`
* `TestPartitionedWrites`
* `TestPartitionedWritesToBranch`
* `TestPartitionedWritesToWapBranch`
* `UnpartitionedWritesTestBase`
* `TestUnPartitionedWrites`
* `TestUnPartitionedWritesToBranch`
* `TestPartitionedWritesAsSelect`

Spark 3.4: Migrate other sql tests

---

format/spec.md

This PR adapts our partition stats spec to accommodate DVs:
- `position_delete_record_count` includes a sum of position deletes across position delete files and DVs
- `position_delete_file_count` still counts only position delete files (ignoring deletion vectors)
- `dv_count` counts the number of deletion vectors

Spec: Update partition stats for V3

---

api/src/main/java/org/apache/iceberg/Snapshot.java
api/src/main/java/org/apache/iceberg/encryption/EncryptedKey.java
core/src/main/java/org/apache/iceberg/BaseSnapshot.java
core/src/main/java/org/apache/iceberg/EncryptedKeyParser.java
core/src/main/java/org/apache/iceberg/MetadataUpdate.java
core/src/main/java/org/apache/iceberg/MetadataUpdateParser.java
core/src/main/java/org/apache/iceberg/RewriteTablePathUtil.java
core/src/main/java/org/apache/iceberg/SnapshotParser.java
core/src/main/java/org/apache/iceberg/SnapshotProducer.java
core/src/main/java/org/apache/iceberg/TableMetadata.java
core/src/main/java/org/apache/iceberg/TableMetadataParser.java
core/src/main/java/org/apache/iceberg/encryption/BaseEncryptedKey.java
core/src/main/java/org/apache/iceberg/encryption/EncryptionUtil.java
core/src/main/java/org/apache/iceberg/util/JsonUtil.java
core/src/test/java/org/apache/iceberg/TestDataTaskParser.java
core/src/test/java/org/apache/iceberg/TestEncryptedKeyParser.java
core/src/test/java/org/apache/iceberg/TestMetadataUpdateParser.java
core/src/test/java/org/apache/iceberg/TestRowLineageMetadata.java
core/src/test/java/org/apache/iceberg/TestSnapshotJson.java
core/src/test/java/org/apache/iceberg/TestTableMetadata.java
core/src/test/java/org/apache/iceberg/util/TestJsonUtil.java

This implements the spec changes from #12162.
It adds the `encryption-keys` list to `TableMetadata` that stores an `EncryptedKey`. The `TableMetadata.Builder` is updated with `addEncryptionKey` and `removeEncryptionKey` methods, along with corresponding REST protocol metadata updates. This also adds `key-id` to snapshot metadata.

API, Core: Add table metadata keys for encryption

---

core/src/main/java/org/apache/iceberg/rest/HTTPClient.java
core/src/test/java/org/apache/iceberg/rest/TestHTTPClient.java

This PR Fixes the following issues
https://github.com/apache/iceberg/issues/12059
https://github.com/apache/iceberg/issues/9174
```
conf.set("spark.sql.catalog.demo.rest.client.proxy.hostname", "127.0.0.1")
conf.set("spark.sql.catalog.demo.rest.client.proxy.port", "8080")
conf.set("spark.sql.catalog.demo.rest.client.proxy.username", "admin")
conf.set("spark.sql.catalog.demo.rest.client.proxy.password", "admin")
```
Notes:
* Changes are tested using [mitmproxy](https://mitmproxy.org/)

Enable HTTP proxy support for the client used by REST Catalog 

---

gradle/libs.versions.toml
spark/v3.4/build.gradle
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/data/vectorized/CometColumnReader.java
spark/v3.5/build.gradle
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/data/vectorized/CometColumnReader.java

Update Comet version to the latest 0.8.1.
https://github.com/apache/datafusion-comet/compare/0.5.0...0.8.1
The older version of Comet accidentally shaded `org.apache.comet.shaded.arrow.c.CometSchemaImporter`. This has been fixed in the new version.

Build: Bump Comet from 0.5.0 to 0.8.1

---

api/src/main/java/org/apache/iceberg/PartitionSpec.java
api/src/test/java/org/apache/iceberg/TestPartitionSpecValidation.java

Core: Disallow creation of invalid PartitionSpec

---

open-api/rest-catalog-open-api.py
open-api/rest-catalog-open-api.yaml

This PR removes the table action to enable row lineage because it is always on for v3 tables.

REST spec: Remove update to enable row lineage

---

build.gradle
core/src/main/java/org/apache/iceberg/io/ImmutableStorageCredential.java
core/src/main/java/org/apache/iceberg/io/StorageCredential.java

https://github.com/apache/iceberg/pull/12882 went in right in between voting on 1.9.0 happened, which means that the API breakage wasn't detected as a breakage when it was merged. After upgrading RevAPI to compare against 1.9.0, the API breakage around Map -> SerializableMap was flagged. 
The underlying issue is that Immutables will always create an unmodifiable Map (which isn't configurable and is generally what you want) when the API definition is `Map`, which Kryo can't deal with, since Kryo adds back elements to the collection after deserialization. There is some hope that Kryo will eventually be able to deal with unmodifiable collections without having to use a separate kryo-serializers lib (https://github.com/EsotericSoftware/kryo/pull/1154) but we're not there yet and maybe the …

Build, Core: Let RevAPI compare against 1.9.0 / Fix API breakage around StorageCredential

---

spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/TestFileRewriteCoordinator.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/TestSparkCachedTableCatalog.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/TestSparkCatalogOperations.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/TestSparkWriteConf.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/actions/TestMigrateTableAction.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/source/TestDataSourceOptions.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSourceHadoopTables.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSourceHiveTables.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSourceTablesBase.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/source/TestMetadataTableReadableMetrics.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/source/TestMetadataTablesWithPartitionEvolution.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/TestFileRewriteCoordinator.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/TestSparkCachedTableCatalog.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/TestSparkCatalogOperations.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/TestSparkExecutorCache.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/TestSparkWriteConf.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestDataSourceOptions.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSourceHadoopTables.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSourceTablesBase.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestMetadataTableReadableMetrics.java

This PR migrates the following Spark 3.4 tests in the `spark` and `spark.source` packages to JUnit 5 with AssertJ:
`spark`:
* `TestFileRewriteCoordinator`
* `TestSparkCatalogOperations`
* `TestSparkWriteConf`
* `TestSparkCachedTableCatalog`
`spark.source`:
* `TestDataSourceOptions`
* `TestIcebergSourceTablesBase`
* `TestIcebergSourceHadoopTables`
* `TestIcebergSourceHiveTables`
* `TestMetadataTableReadableMetrics`
* `TestMetadataTablesWithPartitionEvolution`
And, additiona one such as `TestMigrateTableAction` which is only left in the `actions` package.

Spark 3.4: Migrate source and spark tests

---

docs/mkdocs.yml

Hi, this pr adds how Databend(Cloud warehouse like Snowflake) works with iceberg.
Please let me know if you have any clarification. Thanks!

Add databend & iceberg docuement url

---

parquet/src/main/java/org/apache/iceberg/parquet/ParquetValueReaders.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkMetadataColumns.java

Currently, there's a bug in the Parquet reader where when creating the last updated sequence reader, the passed in baseRowId is actually the sequence number as well. 
Note that this issue doesn't impact V3+ tables which actually support row lineage, but rather just leads to odd results when projecting these columns from V2 tables where row lineage isn't even supported. It should still be possible to project these columns in older tables but they should always just be null since lineage isn't tracked for those.
This baseRowId is used to determine if we should project nulls or not for the sequence number. Since we always inherit the sequence number regardless of the format version, the current implementation leads to non-null sequence numbers being read instead of the null parquet reader …

Parquet: Fix to ensure that last updated sequence numbers for V2 and earlier tables are null

---

spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/data/GenericsHelpers.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/data/TestHelpers.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/data/TestOrcWrite.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/data/TestParquetAvroReader.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/data/TestParquetAvroWriter.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/data/TestSparkAvroEnums.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/data/TestSparkDateTimes.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/data/TestSparkOrcReadMetadataColumns.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/data/TestSparkParquetReadMetadataColumns.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/data/TestSparkParquetWriter.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/data/parquet/vectorized/TestParquetDictionaryFallbackToPlainEncodingVectorizedReads.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/data/parquet/vectorized/TestParquetVectorizedReads.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/data/GenericsHelpers.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/data/TestHelpers.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/data/TestOrcWrite.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/data/TestSparkDateTimes.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/data/TestSparkParquetWriter.java

This PR migrates the following tests in `spark.data` to JUnit 5 with AssertJ:
`data.parquet.vectorized`
* `TestParquetDictionaryFallbackToPlainEncodingVectorizedReads`
* `TestParquetVectorizedReads`
`data`
* `GenericsHelpers` including refactoring Spark 3.5 tests
* `TestHelpers` including refectoring Spark 3.5 tests
* `TestOrcWrite` 
* `TestParquetAvroReader`
* `TestParquetAvroWriter`
* `TestSparkAvroEnums`
* `TestSparkDateTimes`
* `TestSparkOrcReadMetadataColumns`
* `TestSparkParquetReadMetadataColumns`
* `TestSparkParquetWriter` including the backport from https://github.com/apache/iceberg/pull/10149

Spark 3.4: Migrate tests in spark.data including refactoring Spark 3.5 tests

---

spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/actions/TestExpireSnapshotsAction.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/source/TestBaseReader.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/source/TestFilteredScan.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/source/TestForwardCompatibility.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSpark.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/source/TestInternalRowWrapper.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/source/TestPartitionPruning.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/source/TestPartitionValues.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkAggregates.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkDataFile.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkReaderWithBloomFilter.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/source/TestStreamingOffset.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/source/TestStructuredStreaming.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/source/TestWriteMetricsConfig.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestFilteredScan.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestForwardCompatibility.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSpark.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestPartitionPruning.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestPartitionValues.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkAggregates.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkDataFile.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestStructuredStreaming.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestWriteMetricsConfig.java

This PR migrates the following tests in `spark.source` to JUnit 5 with AssertJ:
* `TestBaseReader` 
* `TestFilteredScan`
* `TestForwardCompatibility`
* `TestIcebergSpark` including refactoring Spark 3.5 tests
* `TestInternalRowWrapper`
* `TestPartitionPruning` including refactoring Spark 3.5 tests
* `TestPartitionValues` including refactoring Spark 3.5 tests
* `TestSparkAggregates` including refactoring Spark 3.5 tests
* `TestSparkDataFile`
* `TestSparkReaderWithBloomFilter`
* `TestStreamingOffset`
* `TestStructuredStreaming` including refactoring Spark 3.5 tests
* `TestWriteMetricsConfig` including refactoring Spark 3.5 tests
Plus, add …

Spark 3.4: Migrate tests in spark.source including refactoring Spark 3.5 tests

---

docs/docs/configuration.md
docs/docs/spark-configuration.md

Currently there's no the "Delete Granularity" option in the documentation for the Iceberg's table properties and Spark write configuation. This documentation adds the description of that granularity option.

Docs: Add Delete Granularity option to write configuration

---

spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/SparkTestHelperBase.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/TestChangelogIterator.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/TestSparkFilters.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/TestSparkSchemaUtil.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/TestSparkTableUtil.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/TestSparkV2Filters.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/TestSparkValueConverter.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/source/TestReadProjection.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/source/TestSnapshotSelection.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkDataWrite.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkReadProjection.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkTable.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/SparkTestHelperBase.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/TestSparkFilters.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/TestSparkSchemaUtil.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/TestSparkTableUtil.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/TestSparkV2Filters.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestReadProjection.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestSnapshotSelection.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkDataWrite.java

This PR migrate the other JUnit 4 tests to JUnit 5 and complete the Spark migration. The following classes are included in this PR:
`source`
* `TestReadProjection` including refactoring Spark 3.5 tests
* `TestSnapshotSelection`
* `TestSparkDataWrite` including refactoring Spark 3.5 tests
* `TestSparkReadProjection`
Others:
* `SparkTestHelperBase`
* `TestChangelogIterator`
* `TestSparkTableUtil` including refactoring Spark 3.5 tests
* `TestSparkSchemaUtil`
* `TestSparkTable`
* `TestSparkFilters` including refactoring Spark 3.5 tests
* `TestSparkV2Filters` including refactoring Spark 3.5 tests
* `TestSparkValueConverter`

Spark 3.4: Migrate other JUnit 4 dependant tests to JUnit 5

---

arrow/src/main/java/org/apache/iceberg/arrow/ArrowSchemaUtil.java
arrow/src/test/java/org/apache/iceberg/arrow/vectorized/ArrowReaderTest.java

`Decimal(int precision, int scale)` constructor is deprecated.
https://github.com/apache/arrow-java/blob/b459647910a6a373fb9f3d9cd0eb8cc717932bed/vector/src/main/codegen/templates/ArrowType.java#L180-L191

Arrow: Avoid deprecated ArrowType.Decimal constructor

---

flink/v2.0/build.gradle
flink/v2.0/flink/src/main/java/org/apache/iceberg/flink/sink/dynamic/DynamicRecord.java
flink/v2.0/flink/src/main/java/org/apache/iceberg/flink/sink/dynamic/DynamicRecordInternal.java
flink/v2.0/flink/src/main/java/org/apache/iceberg/flink/sink/dynamic/DynamicRecordInternalSerializer.java
flink/v2.0/flink/src/main/java/org/apache/iceberg/flink/sink/dynamic/DynamicRecordInternalType.java
flink/v2.0/flink/src/main/java/org/apache/iceberg/flink/sink/dynamic/TableSerializerCache.java
flink/v2.0/flink/src/test/java/org/apache/iceberg/flink/sink/dynamic/DynamicRecordInternalSerializerTestBase.java
flink/v2.0/flink/src/test/java/org/apache/iceberg/flink/sink/dynamic/TestDynamicRecordInternalSerializerWriteSchema.java
flink/v2.0/flink/src/test/java/org/apache/iceberg/flink/sink/dynamic/TestDynamicRecordInternalSerializerWriteSchemaId.java
flink/v2.0/flink/src/test/java/org/apache/iceberg/flink/sink/dynamic/TestTableSerializerCache.java

This adds the user-facing type DynamicRecord, alongside with its internal representation DynamicRecordInternal and its type information and serializer.
Broken out of https://github.com/apache/iceberg/pull/12424.
The original PR is based on Flink 1.20. This version is based on Flink 2.0.

Flink: Add DynamicRecord / DynamicRecordInternal / DynamicRecordInternalSerializer

---

.baseline/checkstyle/checkstyle-suppressions.xml
flink/v1.20/flink/src/main/java/org/apache/iceberg/flink/maintenance/api/ZkLockFactory.java
flink/v1.20/flink/src/test/java/org/apache/iceberg/flink/maintenance/api/TestZkLockFactory.java

In TableMaintenance, we have already implemented JdbcLock. I believe we will have a need for ZookeeperLock. This PR aims to support ZkLockFactory to implement ZkLock.

Flink: Support zookeeper lock in TableMaintenance

---

flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/maintenance/api/ZkLockFactory.java
flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/maintenance/api/TestZkLockFactory.java
flink/v2.0/flink/src/main/java/org/apache/iceberg/flink/maintenance/api/ZkLockFactory.java
flink/v2.0/flink/src/test/java/org/apache/iceberg/flink/maintenance/api/TestZkLockFactory.java

This pr is backport https://github.com/apache/iceberg/pull/12810 to Flink 1.19 and 2.0

Flink: Backport support zookeeper lock in TableMaintenance to Flink 1.19 and 2.0

---

docs/docs/kafka-connect.md
kafka-connect/build.gradle

As the BigQuery Metastore catalog was introduced in https://github.com/apache/iceberg/pull/12808, this PR aims to make it available in the Kafka Connect.

Kafka Connect: Add BigQuery Metastore catalog

---

flink/v2.0/flink/src/main/java/org/apache/iceberg/flink/maintenance/operator/TaskResultAggregator.java
flink/v2.0/flink/src/test/java/org/apache/iceberg/flink/maintenance/operator/TestTaskResultAggregator.java

`TaskResultAggregator` is connected to `LockRemover`, and `LockRemover` only releases the `recoveryLock` when `processWatermark()` is called. 
Currently, `TaskResultAggregator` misses calling the `processWatermark` method and not passing watermark to `LockRemover`, which causes the lock to not be released if the job recovers from failure, thereby preventing the maintenance job from being triggered.
This pr is aim to fix watermark not passing in TaskResultAggregator.

Flink: Fix watermark not passing in TaskResultAggregator

---

spark/v4.0/spark/src/test/java/org/apache/iceberg/spark/source/TestRequiredDistributionAndOrdering.java
spark/v4.0/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkCatalogHadoopOverrides.java
spark/v4.0/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkStagedScan.java
spark/v4.0/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkTable.java

This PR reapplies the Spark 4.0 changes in https://github.com/apache/iceberg/pull/13007 based on the comment in https://github.com/apache/iceberg/pull/13022#issuecomment-2869004899

Spark 4.0: Reapply changes removed during the Spark 4.0 reversion

---

spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/source/SparkMicroBatchStream.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestStructuredStreamingRead3.java

This fixes the TODO in https://github.com/apache/iceberg/pull/4479.
Use the ReadLimit passed in to `SparkMicroBatchStream::latestOffset(Offset, ReadLimit)`. In testing this, a bug was found in `SparkMicroBatchStream::getDefaultReadLimit()` and fixed.

Spark 3.5: Structured Streaming read limit support follow-up

---

parquet/src/main/java/org/apache/iceberg/parquet/TypeToMessageType.java

The `field(field)` method is unnecessarily called twice, once to check for null, and again to add the result. This leads to redundant computation. Might be an oversight.

Parquet: Fix redundant type conversion in parquet schema

---

spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/source/SparkMicroBatchStream.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/source/TestStructuredStreamingRead3.java

Use the `ReadLimit` passed in to `SparkMicroBatchStream::latestOffset(Offset, ReadLimit)`. In testing this, a bug was found in `SparkMicroBatchStream::getDefaultReadLimit()` and fixed.
This is a backport of https://github.com/apache/iceberg/pull/12260.

Spark 3.4: Structured Streaming read limit support follow-up

---

core/src/main/java/org/apache/iceberg/TableMetadata.java

https://github.com/apache/iceberg/pull/12670 introduces a behavior change that requires the REST catalog server to upgrade to 1.9.x as well, otherwise, the client with 1.9.x cannot talk to the existing server.
This PR is to revert back to the 1.8.x behavior in core that the client will send single snapshot to remove that the existing server can understand.
This PR is only fixing in 1.9.x branch.

core: Send single snapshot to remove rather than in bulk

---

gradle.properties

Twice, I have ran into OOMError with gradle build
https://github.com/apache/iceberg/actions/runs/15146709248/job/42584083395
https://github.com/apache/iceberg/actions/runs/15146709248/job/42590212786
```
Unexpected exception thrown.
org.gradle.internal.remote.internal.MessageIOException: Could not read message from '/127.0.0.1:40376'.
at org.gradle.internal.remote.internal.inet.SocketConnection.receive(SocketConnection.java:96)
at org.gradle.internal.remote.internal.hub.MessageHub$ConnectionReceive.run(MessageHub.java:270)
at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
at org.gradle.internal.concurrent.AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:48)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Threa …
```

Build: increase gradle jvm heap size from 1 GB to 1.5 GB.

---

spark/v4.0/spark/src/main/java/org/apache/iceberg/spark/source/SparkMicroBatchStream.java
spark/v4.0/spark/src/test/java/org/apache/iceberg/spark/source/TestStructuredStreamingRead3.java

Use the `ReadLimit` passed in to `SparkMicroBatchStream::latestOffset(Offset, ReadLimit)`. In testing this, a bug was found in `SparkMicroBatchStream::getDefaultReadLimit()` and fixed.
This is a forward port of https://github.com/apache/iceberg/pull/12260.

Spark 4.0: Structured Streaming read limit support follow-up

---

parquet/src/main/java/org/apache/iceberg/parquet/ParquetReader.java

We should intercept the `ParquetDecodingException` and log the corrupted parquet file to make this easily discoverable. Knowing the exact parquet file that the executor failed on is essential for identifying bad nodes in a cluster that could be producing corrupt data, and eventually take them out.
```
23/12/10 13:28:04 WARN task-result-getter-0 TaskSetManager: Lost task 55.0 in stage 0.0 (TID 55) (ip-100-74-15-132.ec2.internal executor 28): org.apache.iceberg.bdp.shaded.org.apache.parquet.io.ParquetDecodingException: could not decompress page
```

CORE: [PARQUET] Log corrupted parquet filenames to trace bad nodes that may have written them.

---

format/spec.md

This is a PR documenting current behavior and is not intended to introduce functionality but rather document functionality that has already been implemented for quite some time and has not made it into the specification.
There are two aspects:
1.  File name conventions for GZIP files.  Both python and Java reference implementation have expectations for how these files are named and will not work without this naming convention.  Additionally the naming convention is required for filesystem commits but this is on the path to deprecation.
2. Document the simple fact that GZIP compression is supported for metadata.
The logic documented is reverse engineered from [TableMetadataParser.Codec](http://github.com/apache/iceberg/blob/main/core/src/main/java/org/apache/iceberg/TableMetadataParser.java …

Spec: Add details on GZIP compressed metadata files

---

flink/v2.0/flink/src/main/java/org/apache/iceberg/flink/maintenance/operator/TaskResultAggregator.java
flink/v2.0/flink/src/test/java/org/apache/iceberg/flink/maintenance/operator/OperatorTestBase.java
flink/v2.0/flink/src/test/java/org/apache/iceberg/flink/maintenance/operator/TestTaskResultAggregator.java

Now the `startTime` in `TaskResultAggregator` is a transient `Long` that is initialized when the object is created, not in the `open` method. When the job recovers from a failure, it becomes null and causes a NPE when `processWatermark` is call before `processElement1` constructing the required `long` for `TaskResult`.
https://github.com/apache/iceberg/blob/c2478968e65368c61799d8ca4b89506a61ca3e7c/flink/v2.0/flink/src/main/java/org/apache/iceberg/flink/maintenance/operator/TaskResultAggregator.java#L64
This PR aims to change the initialization of `startTime` to the `open` method. If `startTime` is 0, the `TaskResult` will not be propagated downstream; instead, it will rely on the advancement of the watermark to reach downstream operators.

Flink: Fix npe in TaskResultAggregator when job recovery

---

flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/maintenance/operator/TaskResultAggregator.java
flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/maintenance/operator/OperatorTestBase.java
flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/maintenance/operator/TestTaskResultAggregator.java
flink/v1.20/flink/src/main/java/org/apache/iceberg/flink/maintenance/operator/TaskResultAggregator.java
flink/v1.20/flink/src/test/java/org/apache/iceberg/flink/maintenance/operator/OperatorTestBase.java
flink/v1.20/flink/src/test/java/org/apache/iceberg/flink/maintenance/operator/TestTaskResultAggregator.java

This is a backport to Flink 1.19 and 1.20 
https://github.com/apache/iceberg/pull/13086

Flink: Backport fix npe in TaskResultAggregator when job recovery to Flink 1.19 and 1.20

---

aws/src/main/java/org/apache/iceberg/aws/s3/AnalyticsAcceleratorUtil.java

Current integration with the S3 Analytics Accelerator Library ( #12299 ) is not closing the `S3SeekableInputStreamFactory` on `S3FileIO` close.  This PR incorporates that logic by closing it before removing from cache.

AWS: Close the S3SeekableInputStreamFactory before removing from cache

---

docs/mkdocs.yml
site/docs/blogs.md
site/docs/vendors.md

Based on [12764](https://github.com/apache/iceberg/pull/12764), this PR includes Tinybird in the list of vendors who support Iceberg, as well as it includes a link to a recent blog post on how to integrate Iceberg with Tinybird.

Docs: add Tinybird to the list of vendors and blog posts

---

spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/source/SparkMicroBatchStream.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/source/TestStructuredStreamingRead3.java

This is a backport of https://github.com/apache/iceberg/pull/8980, authored by @cccs-jc.

Spark 3.4: streaming-skip-overwrite-snapshots fix

---

core/src/main/java/org/apache/iceberg/PartitionStatsHandler.java
core/src/test/java/org/apache/iceberg/PartitionStatsHandlerTestBase.java
orc/src/test/java/org/apache/iceberg/TestOrcPartitionStatsHandler.java

Fixes an edge case where deleted entires information is not carried to next snapshot. So, incremental stats compute was wrong for this copy on write case. Fix is to apply incremental stats compute snapshot by snapshot for its added manifest.
Also fallback when stats file exist for table but not for current snapshot chain, instead of throwing exception.  
Fixes: #13155

Core: Fix incremental compute of partition stats with COW deletes

---

api/src/main/java/org/apache/iceberg/variants/VariantPrimitive.java

This implements toString for time/nano-timestamp types in Variant to show friendly time string in test cases instead of long value.

Add Variant toString for time/nano-timestamps type

---

api/src/main/java/org/apache/iceberg/RowDelta.java
core/src/main/java/org/apache/iceberg/BaseRowDelta.java
core/src/test/java/org/apache/iceberg/TestRowDelta.java

@rdblue Pointed out that while I matched the method name from OverwriteFiles, I had not matched the other methods within RowDelta. I've changed the method deleteFiles to removeRows to match the "addRows" method that already exists.

API, Core: Rename RowDelta deleteFile to removeRows

---

docs/docs/spark-procedures.md
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/actions/DeleteOrphanFilesSparkAction.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/procedures/RemoveOrphanFilesProcedure.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/actions/TestRemoveOrphanFilesAction.java

Closes #11541  
RemoveOrphanFiles Using FileIO when it implements SupportPrefixOperations to list files. And it will fall back using Hadoop Class when it does not.
Some concerns:
1. All list file operations are performed on the driver, which may cause performance pressure in scenarios involving massive files.
2. Currently, it has only been implemented in Spark 3.5. Should it be implemented in other Spark versions as well?
3. Tests are running on this FileIO branch. Should tests be added for the original Hadoop Class based branch?

SPARK: Remove dependency on hadoop's filesystem class from remove orphan files

---

core/src/main/java/org/apache/iceberg/rest/CatalogHandlers.java

Allow listing tables, views and namespaces in rest catalog without `pageToken` query parameter when `pageSize` query parameter is included. Closes #13119
Examples:
- http://localhost:8181/v1/namespaces?pageSize=1
- http://localhost:8181/v1/namespaces/default/tables?pageSize=1
- http://localhost:8181/v1/namespaces/default/views?pageSize=1

Core: Improve pagination logic to handle null pageToken

---

flink/v1.20/flink/src/main/java/org/apache/iceberg/flink/sink/IcebergSink.java
flink/v1.20/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkV2DistributionMode.java
flink/v1.20/flink/src/test/java/org/apache/iceberg/flink/sink/TestIcebergSink.java

This PR ports the RANGE distribution mode on the `FlinkSink` to the new `IcebergSink` based on the Flink V2 sink interface.
cc: @stevenzwu @mxm @pvary @Guosmilesmile

Flink: port range distribution to v2 iceberg sink

---

flink/v2.0/flink/src/main/java/org/apache/iceberg/flink/sink/CommitSummary.java
flink/v2.0/flink/src/main/java/org/apache/iceberg/flink/sink/DeltaManifests.java
flink/v2.0/flink/src/main/java/org/apache/iceberg/flink/sink/DeltaManifestsSerializer.java
flink/v2.0/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkManifestUtil.java
flink/v2.0/flink/src/main/java/org/apache/iceberg/flink/sink/IcebergCommittable.java
flink/v2.0/flink/src/main/java/org/apache/iceberg/flink/sink/IcebergFilesCommitterMetrics.java
flink/v2.0/flink/src/main/java/org/apache/iceberg/flink/sink/IcebergStreamWriterMetrics.java
flink/v2.0/flink/src/main/java/org/apache/iceberg/flink/sink/ManifestOutputFileFactory.java
flink/v2.0/flink/src/main/java/org/apache/iceberg/flink/sink/RowDataTaskWriterFactory.java
flink/v2.0/flink/src/main/java/org/apache/iceberg/flink/sink/WriteResultSerializer.java
flink/v2.0/flink/src/main/java/org/apache/iceberg/flink/sink/dynamic/DynamicCommittable.java
flink/v2.0/flink/src/main/java/org/apache/iceberg/flink/sink/dynamic/DynamicCommittableSerializer.java
flink/v2.0/flink/src/main/java/org/apache/iceberg/flink/sink/dynamic/DynamicCommitter.java
flink/v2.0/flink/src/main/java/org/apache/iceberg/flink/sink/dynamic/DynamicCommitterMetrics.java
flink/v2.0/flink/src/main/java/org/apache/iceberg/flink/sink/dynamic/DynamicWriteResult.java
flink/v2.0/flink/src/main/java/org/apache/iceberg/flink/sink/dynamic/DynamicWriteResultAggregator.java
flink/v2.0/flink/src/main/java/org/apache/iceberg/flink/sink/dynamic/DynamicWriteResultSerializer.java
flink/v2.0/flink/src/main/java/org/apache/iceberg/flink/sink/dynamic/DynamicWriter.java
flink/v2.0/flink/src/main/java/org/apache/iceberg/flink/sink/dynamic/DynamicWriterMetrics.java
flink/v2.0/flink/src/main/java/org/apache/iceberg/flink/sink/dynamic/WriteTarget.java
flink/v2.0/flink/src/test/java/org/apache/iceberg/flink/sink/dynamic/TestDynamicCommittableSerializer.java
flink/v2.0/flink/src/test/java/org/apache/iceberg/flink/sink/dynamic/TestDynamicCommitter.java
flink/v2.0/flink/src/test/java/org/apache/iceberg/flink/sink/dynamic/TestDynamicWriteResultAggregator.java
flink/v2.0/flink/src/test/java/org/apache/iceberg/flink/sink/dynamic/TestDynamicWriteResultSerializer.java
flink/v2.0/flink/src/test/java/org/apache/iceberg/flink/sink/dynamic/TestDynamicWriter.java
flink/v2.0/flink/src/test/java/org/apache/iceberg/flink/sink/dynamic/TestTableSerializerCache.java

This adds the dynamic version of the writer and committer for the Flink Dynamic Iceberg Sink. Conceptually, they work similar to the IcebergSink, but they support writing to multiple tables. Write results from each table are aggregated from the DynamicWriter in the DynamicWriteResultAggregator, from where they are sent to the DynamicCommitter.
Broken out of https://github.com/apache/iceberg/pull/12424.

Flink: Dynamic Iceberg Sink: Add dynamic writer and committer

---

core/src/main/java/org/apache/iceberg/rest/HTTPClient.java
core/src/main/java/org/apache/iceberg/rest/auth/TLSConfigurer.java
core/src/test/java/org/apache/iceberg/rest/TestHTTPClient.java

This PR adds an option to the REST client to configure TLS settings via a pluggable configurer class. Java supports setting some TLS parameters via System properties, but doing so will affect all connections, and causes issues with clients such as the S3 client.
Also, while some basic parameters could be set via catalog properties, using a plugin approach allows the most flexibility when configuring mutual authentication, which can involve custom logic for certificate and host name verification. This aligns with the pluggable model currently used for AuthManagers.
If useful, we could follow this PR up with an implementation that is driven off of catalog properties, for cases that don't need special logic. This would allow setting the keystore and the truststore sepcifically for the REST …

[REST] Add option to configure TLS settings in REST client

---

docs/mkdocs.yml
site/docs/blogs.md
site/docs/vendors.md

Redpanda is a streaming software company that offers the "Iceberg Topics" feature for converting Kafka messages into Iceberg tables, usable by many standard vendor Iceberg offerings.
This PR is to add us to your list of vendors.
You can reach me at lea.fester@redpanda.com if you have any questions.  
Thank you,
Lea Fester

Docs: Add Redpanda to vendor-related documentation

---

spark/v4.0/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMerge.java

Since Spark 4.0 added support in DataFrameWriterV2 for MERGE INTO ([SPARK-46207](https://issues.apache.org/jira/browse/SPARK-46207)), it would be useful to have a test for that support.

Spark 4.0: Add a test for DataFrame API support for MERGE INTO

---

site/docs/spark-quickstart.md

Hi team,
This PR updates the `spark-quickstart` documentation to use the latest MinIO client configuration command. The previous `config host` command appears to be deprecated.

Docs: use latest minio client command configuration parameters

---

docs/docs/aws.md
docs/docs/flink-writes.md
docs/docs/hive.md
docs/docs/spark-queries.md
site/README.md

Fixes #13075
The issue with rendering list is related to a missing blank line between paragraphs and lists. I found more similar issues and fixed them in this PR as well.
Here are the screenshots of the fixed lists from the local instance:
1. Integrations / AWS:
2. Flink / Flink Writes
3. Hive
4. Spark / Queries (**original example of the issue**)

Docs: Fix list rendering and typos (#13075)

---

core/src/main/java/org/apache/iceberg/rest/HTTPClient.java
core/src/test/java/org/apache/iceberg/rest/TestHTTPClient.java

This change attempts to add UA so that clients can set this at their end and it can supplement the server for audit and debugging purpose, we do have `X-Client-Version` which helps solve most of the cases as this helps server understand that  what version of the client the server is interacted, but in a world where we want to see the logs at server end and identify what happened to a client will be very hard. 
Putting this change out to see if folks are interested in this !
Added a new UT

REST: Add property for configuring user agent in http client

---

docs/docs/spark-procedures.md

Update typo in `rewrite_manifests` spark procedure docs

docs: Fix typo in `rewrite_manifests` output table in spark-procedures.md

---

flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/sink/IcebergSink.java
flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/sink/TestIcebergSink.java
flink/v1.20/flink/src/main/java/org/apache/iceberg/flink/sink/IcebergSink.java
flink/v1.20/flink/src/test/java/org/apache/iceberg/flink/sink/TestIcebergSink.java

This PR backports https://github.com/apache/iceberg/pull/13260 to Flink 1.19 and 1.20
The backport patch came out cleanly.

Flink: Backports #13260 to Flink 1.19 and 1.20

---

flink/v2.0/flink/src/jmh/java/org/apache/iceberg/flink/sink/dynamic/DynamicRecordSerializerDeserializerBenchmark.java
flink/v2.0/flink/src/main/java/org/apache/iceberg/flink/FlinkConfParser.java
flink/v2.0/flink/src/main/java/org/apache/iceberg/flink/FlinkWriteConf.java
flink/v2.0/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java
flink/v2.0/flink/src/main/java/org/apache/iceberg/flink/sink/IcebergSink.java
flink/v2.0/flink/src/main/java/org/apache/iceberg/flink/sink/SinkUtil.java
flink/v2.0/flink/src/main/java/org/apache/iceberg/flink/sink/dynamic/DynamicCommitter.java
flink/v2.0/flink/src/main/java/org/apache/iceberg/flink/sink/dynamic/DynamicIcebergSink.java
flink/v2.0/flink/src/main/java/org/apache/iceberg/flink/sink/dynamic/DynamicRecordConverter.java
flink/v2.0/flink/src/main/java/org/apache/iceberg/flink/sink/dynamic/DynamicRecordGenerator.java
flink/v2.0/flink/src/main/java/org/apache/iceberg/flink/sink/dynamic/DynamicRecordProcessor.java
flink/v2.0/flink/src/main/java/org/apache/iceberg/flink/sink/dynamic/HashKeyGenerator.java
flink/v2.0/flink/src/test/java/org/apache/iceberg/flink/SimpleDataUtil.java
flink/v2.0/flink/src/test/java/org/apache/iceberg/flink/TestFlinkFilters.java
flink/v2.0/flink/src/test/java/org/apache/iceberg/flink/TestHelpers.java
flink/v2.0/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkBase.java
flink/v2.0/flink/src/test/java/org/apache/iceberg/flink/sink/dynamic/TestDynamicIcebergSink.java
flink/v2.0/flink/src/test/java/org/apache/iceberg/flink/sink/dynamic/TestDynamicIcebergSinkPerf.java

This completes the breakdown of #12424. Most importantly, it adds the following missing components:
The actual Flink sink which ties together the previously merged components. The sink will be instantiated by the user like this:
```java
DynamicIcebergSink
.forInput(inputStream)
.withConverter(new MyConverter())
.catalogLoader(..)
.append();  
```
An example for a converter implementation would be:
```java
class MyConverter implements DynamicRecordConverter<MyInput> {
final RuntimeParams params;
MyConverter(RuntimeParams params) {
this.params = params;
}
@Override
public void convert(MyInput inputRecord, Collector<DynamicRecord> out) {
DynamicRecord record = new DynamicRecord(
inputRecord.getTable(),
inputRecord.getBranch(),
inputRecord.buildSchema(),
inputRecord.convertData(), …
```

Flink: Dynamic Iceberg Sink: Add sink / core processing logic / benchmarking

---

.palantir/revapi.yml
core/src/main/java/org/apache/iceberg/rest/BaseHTTPClient.java
core/src/main/java/org/apache/iceberg/rest/HTTPClient.java
core/src/main/java/org/apache/iceberg/rest/ParserContext.java
core/src/main/java/org/apache/iceberg/rest/RESTClient.java
core/src/test/java/org/apache/iceberg/rest/RESTCatalogAdapter.java

Presently the REST parsers are stateless aka static, this makes hard to inject a state which can help the parser to construct the response object if it needs some prior info. Addding injectable values to the mapper and using a reader with injectable value passed during making the request will make sure that during deserialization we will get back the value injected from the DeserializationContext 
https://github.com/apache/iceberg/blob/3469cf30f2d839763813596e3f0c66ed16189c9a/core/src/main/java/org/apache/iceberg/rest/RESTSerializers.java#L450
essentially something like this is possible now : 
```
// Retrieve injectable values
@SuppressWarnings("unchecked")
Map<Integer, PartitionSpec> specsById =
(Map<Integer, PartitionSpec>) context.findInjectableValue("specsById", null, null);
boolean …
```

[CORE][REST]: Add context aware response parsing

---

flink/v2.0/flink/src/main/java/org/apache/iceberg/flink/sink/dynamic/DynamicRecordGenerator.java
flink/v2.0/flink/src/main/java/org/apache/iceberg/flink/sink/dynamic/DynamicRecordProcessor.java
flink/v2.0/flink/src/test/java/org/apache/iceberg/flink/sink/dynamic/TestDynamicIcebergSink.java
flink/v2.0/flink/src/test/java/org/apache/iceberg/flink/sink/dynamic/TestDynamicIcebergSinkPerf.java

The decided to change the terminology from converter to generator. The interface method still had the old name, despite the class already gotten renamed.

Flink: Dynamic Iceberg Sink: Rename method in DynamicRecordGenerator

---

core/src/main/java/org/apache/iceberg/RemoveSnapshots.java
core/src/test/java/org/apache/iceberg/TestRemoveSnapshots.java

Core: Clean expired metadata even if there is no snapshot to expire

---

docs/mkdocs.yml
site/docs/blogs.md
site/docs/vendors.md

Adds Firebolt to the list of vendors that support Iceberg, with links to Firebolt's documentation and Iceberg blog post.

Docs: Add Firebolt to list of vendors and blog posts

---

build.gradle
gcp/src/main/java/org/apache/iceberg/gcp/GCPProperties.java
gcp/src/main/java/org/apache/iceberg/gcp/auth/GoogleAuthManager.java
gcp/src/main/java/org/apache/iceberg/gcp/auth/GoogleAuthSession.java
gcp/src/test/java/org/apache/iceberg/gcp/auth/TestGoogleAuthManager.java
gcp/src/test/java/org/apache/iceberg/gcp/auth/TestGoogleAuthSession.java

This PR introduces a dedicated GoogleAuthManager for the Iceberg REST client, enabling robust and streamlined authentication with Google Cloud Platform (GCP) services by delegating authentication to GCP's auth library.
***Why add a specific GoogleAuthManager?***
Currently, Iceberg's AuthManager and the generic OAuth2Manager provide a good baseline for authentication. However, connecting to services on Google Cloud often uses specific patterns that a generic manager doesn't fully simplify. This new GoogleAuthManager makes life easier for folks using Iceberg REST catalogs behind GCP Auth Service 
The existing OAuth2Manager is great for standard OAuth2 flows (like client credentials) but it does not support [authorization code workflow](https://datatracker.ietf.org/doc/html/rfc6749#section-6) …

GCP: Add Google Authentication Support

---

build.gradle

These classes are not shaded and cause duplicate class conflicts.

Remove JSpecify annotations from bundled-guava

---

.github/workflows/publish-snapshot.yml

Use the higher supported JDK version to publish snapshot to Maven, to fix https://github.com/apache/iceberg/actions/runs/15812361048/job/44565434608.
Both Java and Scala are configured with `-release:11`, it means even use a higher version of JDK to build, the output jars still compatible with Java 11.
```
tasks.withType(JavaCompile.class).configureEach {
options.encoding = "UTF-8"
options.release = 11
}
```
```
tasks.withType(ScalaCompile.class) {
scalaCompileOptions.keepAliveMode.set(KeepAliveMode.DAEMON)
// `options.release` doesn't seem to work for ScalaCompile :(
sourceCompatibility = "11"
targetCompatibility = "11"
scalaCompileOptions.additionalParameters.add("-release:11")
}
```

Build: Use Java 17 to publish snapshot to Maven

---

spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/SparkRowLevelOperationsTestBase.java
spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRowLevelOperationsWithLineage.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/actions/ManifestFileBean.java

For Spark Distributed planning we use a `ManifestFileBean` implementation of ManifestFile which is serializable and encodes the minimal amount of manifest fields required during distributed planning. This was missing firstRowId and as a result null values would be propogated for the inherited firstRowId. This fixes the issue by simply adding the firstRowId field to the bean which will be set correctly and as a result be inherited correctly during Spark distributed planning.
I discovered this when going through the DML row lineage tests and noticed we weren't exercising a distributed planning case and after enabling, debugged. I added another test parameter set for distributed planning.

Spark: Fix row lineage inheritance for distributed planning

---

docs/docs/spark-queries.md
format/spec.md

Introduce explicit Markdown headings for the `manifest_entry` and `data_file` structs so other documentation sections (for example, the *Entries* metadata-table page from #13104) can deep-link to them.
These headings automatically generate the anchors #manifest-entry-fields and #data-file-fields.
During review of #13104 it became clear that we cannot currently link to individual struct definitions because the headings (and therefore anchors) are missing. Adding them here resolves the issue in a docs-only change.

Docs: improve structure for manifest entry fields

---

docs/docs/spark-configuration.md
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/source/SparkMicroBatchStream.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestStructuredStreamingRead3.java

Make _maxRecordsPerMicrobatch_ a soft limit, as the cases like for ex max number of records is less than the totalRecords of a file, would expect us to read the file partially (current behavior), this can't be just a row group boundary or something which we can incorporate in our scan tasks as if like splitting it at the record count cutoff, hence its very difficult to define the boundary, it would be better if we make the make this a soft limit as if and when including a file if it can be contained within the limit its fine, otherwise include the whole file and be done with that particular micro-batch stream.
This change is motivated by two major factors : 
1. stream being stuck presently leading to poor UX https://github.com/apache/iceberg/pull/12217#discussion_r1962211721
2. Softlimit …

Spark: Make maxRecordPerMicrobatch a soft limit

---

build.gradle
core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java
core/src/main/java/org/apache/iceberg/jdbc/JdbcUtil.java
core/src/test/java/org/apache/iceberg/jdbc/TestJdbcTableConcurrency.java
gradle/libs.versions.toml

Fix for ICEBERG-13343
Closes #13343

ICEBERG-13343: fix race condition in JdbcCatalog

---

api/src/main/java/org/apache/iceberg/util/DateTimeUtil.java
api/src/test/java/org/apache/iceberg/util/TestDateTimeUtil.java
spark/v4.0/spark/src/main/java/org/apache/iceberg/spark/functions/DaysFunction.java
spark/v4.0/spark/src/main/java/org/apache/iceberg/spark/functions/HoursFunction.java
spark/v4.0/spark/src/test/java/org/apache/iceberg/spark/sql/TestStoragePartitionedJoins.java

This PR introduces a reducer function to support Storage Partition Join (SPJ) for two iceberg tables one partitioned by day and another one partitioned by hour and join key contains the partitioned column.  At spark level, when SPJ finds the compatible partition transformation is involved on both side of the table, SPJ then uses this iceberg reducer function (hourToDays) to group hour partitions to day level and performs join.

spark 4.0 : SPJ : add hour to day reducer

---

spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRowLevelOperationsWithLineage.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/actions/ManifestFileBean.java

Backport #13061 fix for row lineage inheritance in distributed planning to 3.4
This backport is a clean backport

Spark 3.4: Backport #13061 fix for row lineage inheritance in distributed planning

---

gcp/src/main/java/org/apache/iceberg/gcp/gcs/PrefixedStorage.java
gcp/src/test/java/org/apache/iceberg/gcp/gcs/TestPrefixedStorage.java

Currently the user-agent for traffic from GCSFileIO to GCS is unknown, having an user-agent will help in analyzing and prioritizing the performance improvements for Iceberg FileIO integration with GCS.
Fixes #13393

GCS: Add Iceberg version to UserAgent in GCS requests

---

spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/source/SparkMicroBatchStream.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/source/TestStructuredStreamingRead3.java
spark/v4.0/spark/src/main/java/org/apache/iceberg/spark/source/SparkMicroBatchStream.java
spark/v4.0/spark/src/test/java/org/apache/iceberg/spark/source/TestStructuredStreamingRead3.java

Cherry pick https://github.com/apache/iceberg/pull/12988/files to spark 4.0 and 3.4 
Existing UTs

CheeryPick 12988 to all Spark version

---

api/src/main/java/org/apache/iceberg/OverwriteFiles.java
api/src/main/java/org/apache/iceberg/actions/RewriteDataFiles.java
core/src/main/java/org/apache/iceberg/BaseOverwriteFiles.java
core/src/main/java/org/apache/iceberg/actions/BaseRewriteDataFiles.java
core/src/main/java/org/apache/iceberg/actions/RewriteDataFilesCommitManager.java
core/src/main/java/org/apache/iceberg/actions/RewriteFileGroup.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/actions/RewriteDataFilesSparkAction.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/source/SparkWrite.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteDataFilesAction.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/actions/RewriteDataFilesSparkAction.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/source/SparkWrite.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteDataFilesAction.java
spark/v4.0/spark/src/main/java/org/apache/iceberg/spark/actions/RewriteDataFilesSparkAction.java
spark/v4.0/spark/src/main/java/org/apache/iceberg/spark/source/SparkWrite.java
spark/v4.0/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteDataFilesAction.java

To conform to the v3 spec we're propagating orphaned DVs down to the actual APIs that rewrite/overwrite data files. That way we can ensure that there are no orphaned DVs left in delete manifests

Core, Spark: Propagate orphaned delete files when rewriting data files

---

api/src/main/java/org/apache/iceberg/actions/ActionsProvider.java
api/src/main/java/org/apache/iceberg/actions/ComputePartitionStats.java
core/src/main/java/org/apache/iceberg/PartitionStatsHandler.java
core/src/main/java/org/apache/iceberg/actions/BaseComputePartitionStats.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/actions/ComputePartitionStatsSparkAction.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/actions/SparkActions.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/actions/TestComputePartitionStatsAction.java

This is a Spark wrapper for `PartitionStatsHandler.computeAndWriteStatsFile()`. This is a foundation for spark users to compute stats using just a SQL (call procedure). 
Even though Spark may not have plans to use it for CBO at the moment[1],
Partition stats can be useful for Spark users to
a) List all the partitions of the table without reading all the manifest file 
b) To figure out which partition is affected by the latest snapshot, so users can refresh their pipelines. 
[1] IMO, Spark CBO is not matured yet.
They don't have an interface to keep partition level statistics. Only exposed interface is to keep table level statistics as can be seen here
[https://github.com/apache/iceberg/blob/6c98a9e470d44f77e1939a1a333bf197a57949a6/sp[…]rk/src/main/java/org/apache/iceberg/spark/source/Spark …

Spark-3.5: Add spark action to compute partition stats

---

docs/docs/daft.md

We recently changed our site domain so want to update all Daft documentation links
(I think my last PR https://github.com/apache/iceberg/pull/12860 didn't make it into release so all the links in the "Type Compatibility" table go to 404)

site: update daft docs

---

aws/src/integration/java/org/apache/iceberg/aws/s3/MinioUtil.java
aws/src/integration/java/org/apache/iceberg/aws/s3/TestS3FileIO.java
aws/src/integration/java/org/apache/iceberg/aws/s3/TestS3FileIOWithLegacyMinIO.java
aws/src/integration/java/org/apache/iceberg/aws/s3/signer/TestS3RestSigner.java
aws/src/main/java/org/apache/iceberg/aws/AssumeRoleAwsClientFactory.java
aws/src/main/java/org/apache/iceberg/aws/AwsClientFactories.java
aws/src/main/java/org/apache/iceberg/aws/AwsClientProperties.java
aws/src/main/java/org/apache/iceberg/aws/lakeformation/LakeFormationAwsClientFactory.java
aws/src/main/java/org/apache/iceberg/aws/s3/DefaultS3FileIOAwsClientFactory.java

The recent AWS SDK bump introduced strong integrity checksums, and broke compatibility with many S3-compatible object storages (pre-2025 Minio, Vast, Dell EC etc). 
In Trino project, we received the error report (Missing required header for this request: Content-Md5) from several users and had to disable the check temporarily. We recommend disabling it in Iceberg as well. I faced this issue when I tried upgrading Iceberg library to 1.8.0 in Trino. 
Relates to https://github.com/trinodb/trino/pull/24954 & https://github.com/trinodb/trino/pull/24713

S3: Add LegacyMd5Plugin to S3 client builder

---

spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/Spark3Util.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/CatalogTestBase.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/sql/TestAlterTable.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/Spark3Util.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/CatalogTestBase.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/sql/TestAlterTable.java
spark/v4.0/spark/src/main/java/org/apache/iceberg/spark/Spark3Util.java
spark/v4.0/spark/src/test/java/org/apache/iceberg/spark/sql/TestAlterTable.java

Currently, ALTER TABLE ADD COLUMN with default values is unsupported, however the DDL will succeed and silently ignore setting the default value in Iceberg metadata.  There is an ongoing PR for [supporting](https://github.com/apache/iceberg/pull/13107)  this but there's still more work to be done on that.  
It'd be ideal at least in the interim if we can explicitly surface an unsupported operation exception to users when the default value is specified . 
Note:
1. Create table with default values will already fail in Spark since the SparkCatalog/SparkSessionCatalog already don't surface default values as a capability 
2. SparkSessionCatalog with alter table add column will also already fail in Spark 3.4/3.5 because the analyzer tries to set …

Spark: Throw unsupported for ADD COLUMN with default value

---

core/src/jmh/java/org/apache/iceberg/RewriteDataFilesBenchmark.java
core/src/main/java/org/apache/iceberg/ManifestFilterManager.java
core/src/main/java/org/apache/iceberg/MergingSnapshotProducer.java
core/src/test/java/org/apache/iceberg/TestDeleteFiles.java
core/src/test/java/org/apache/iceberg/TestReplacePartitions.java
core/src/test/java/org/apache/iceberg/TestRewriteFiles.java
core/src/test/java/org/apache/iceberg/TestRowDelta.java
flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/maintenance/api/TestRewriteDataFiles.java
flink/v1.20/flink/src/test/java/org/apache/iceberg/flink/maintenance/api/TestRewriteDataFiles.java
flink/v2.0/flink/src/test/java/org/apache/iceberg/flink/maintenance/api/TestRewriteDataFiles.java

This keeps track of all data files to be removed/rewritten in **MergingSnapshotProducer** and passes those to the **ManifestFilterManager** for deletes. Once **ManifestFilterManager** goes through delete manifests, it also checks whether a DV references any of the data files to be removed. 
This is needed in addition to https://github.com/apache/iceberg/pull/13245 so that we can properly remove orphaned DVs when e.g. a metadata-only delete is performed.
The below benchmark shows that tracking data files to be removed and then detecting orphaned DVs when delete manifests are looked at is only adding a small fraction to the throughput.
without tracking data files to be removed
=========================================
```
Benchmark                                   (numFiles) …
```

Core: Keep track of data files to be removed for orphaned DV detection

---

spark/v4.0/spark/src/test/java/org/apache/iceberg/spark/data/TestSparkAvroReader.java

This change ports the TestSparkAvroReader changes from #13070 to Spark 4.0, I'm breaking this away from #13310

Spark 4.0: Port Avro lineage reader test changes from #13070

---

spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/actions/RewriteTablePathSparkAction.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/actions/RewriteTablePathSparkAction.java
spark/v4.0/spark/src/main/java/org/apache/iceberg/spark/actions/RewriteTablePathSparkAction.java

RewriteTablePath leverages iceberg native table IO for everything except for writing a "file list" file. For this task it currently leverages a Spark writer, which in turn uses Hadoop. This might become a limitation in some cloud environments: for instance, Hadoop does not support [modern auth strategies](https://learn.microsoft.com/en-us/entra/identity/managed-identities-azure-resources/overview) of Azure, and thus enforces unwanted auth paths where it is not required by the cloud provider itself. Also it requires the user to manage 2 configurations for table IO and for spark IO. We suggest to use native table io instead.
See corresponding issue here:
https://github.com/apache/iceberg/issues/13458

Spark: Use native table FileIO instead of Hadoop to save file list in RewriteTablePath

---

api/src/main/java/org/apache/iceberg/catalog/Catalog.java
flink/v1.20/flink/src/main/java/org/apache/iceberg/flink/source/FlinkSource.java
flink/v2.0/flink/src/main/java/org/apache/iceberg/flink/source/FlinkSource.java

Remove superfluous `/**` string inside javadoc section

API, Flink: fix typos in javadoc

---

site/docs/blogs.md
site/docs/vendors.md

Added Ryft to the list of vendors, as well as links to the Iceberg blog posts.

Docs: Add Ryft to list of vendors and blog posts

---

spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestComputePartitionStatsProcedure.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/procedures/ComputePartitionStatsProcedure.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/procedures/SparkProcedures.java

Wrapper on the Spark action PR that got merged: https://github.com/apache/iceberg/pull/12450
Just a 
`CALL catalog_name.system.compute_partition_stats('db.sample'); `
And observe the stats files registered to table
`table.partitionStatisticsFiles()
`
Fixes: https://github.com/apache/iceberg/issues/10106

Spark-3.5: Add procedure to compute partition stats

---

site/dev/common.sh

Fixes #13499 
At the moment the [script checks for MacOS](https://github.com/apache/iceberg/blob/9faf4311d71ce313e81dea07290b3aea9298422c/site/dev/common.sh#L178) and uses a different syntax for `sed`, assuming that it will be BSD sed. This assumption is invalid if the user has changed their default `sed` to be GNU sed.
This PR hardcodes the script to, if on the MacOS, use the built-in BSD sed.

Docs: Hardcode BSD sed if running on MacOS (Closes #13499)

---

site/docs/vendors.md

Tabular were acquired by DataBricks, and so as such it doesn't make sense for them to be listed as a Vendor.

[docs] Remove Tabular from Vendors page

---

docs/docs/spark-procedures.md

Follow up from https://github.com/apache/iceberg/pull/13523

Docs: Document compute_partition_stats procedure

---

api/src/main/java/org/apache/iceberg/variants/VariantUtil.java
api/src/test/java/org/apache/iceberg/variants/TestSerializedArray.java
api/src/test/java/org/apache/iceberg/variants/TestSerializedObject.java
api/src/test/java/org/apache/iceberg/variants/TestSerializedPrimitives.java
api/src/test/java/org/apache/iceberg/variants/VariantTestUtil.java
core/src/main/java/org/apache/iceberg/variants/PrimitiveWrapper.java
core/src/test/java/org/apache/iceberg/variants/TestPrimitiveWrapper.java
core/src/test/java/org/apache/iceberg/variants/TestShreddedObject.java
core/src/test/java/org/apache/iceberg/variants/TestValueArray.java

PR for https://github.com/apache/iceberg/issues/13282.
Save 4 bytes for short strings stored in Variant by reserving first byte only for header. Regular strings continue to use 1 (header) + 4 (offset sizes) bytes.

Use short string in Variant when possible

---

format/spec.md

Fix spelling errors in Iceberg v3 `spec.md`
- Corrected spelling mistakes in the document, such as changing "algoritm" to "algorithm" and "occured" to "occurred".
- Remove the repeated spelling of the word 'the'.

Docs: Fix spelling errors in Iceberg v3 spec.md.

---

api/src/main/java/org/apache/iceberg/SnapshotRefType.java

Hi!
It seems that this enum should be `public` to be able to create instance for this update: https://github.com/apache/iceberg/blob/378479bd21ddc5de7c08dcfec1595196dd8f4a78/core/src/main/java/org/apache/iceberg/MetadataUpdate.java#L378-L390 otherwise it requires to use some kind of reflection / shadowing to be able to create instance of SnapshotRefType.
Or maybe there is another way to create MetadataUpdate.SetSnapshotRef?

Core: make SnapshotRefType public

---

spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/SparkTableUtil.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/SparkTableUtil.java
spark/v4.0/spark/src/main/java/org/apache/iceberg/spark/SparkTableUtil.java

Leverage bulk deletion if IO supports, helpful to speed up the table import with many files. 
Existing `TestAddFilesProcedure` have many unit tests cover this code path for both hive and hadoop catalog (hadoop fileIO) in  
- addFilteredPartitionsToPartitionedWithNullValueFilteringOnDept
- addPartitionsWithNullValueShouldAddFilesToNullPartition
- addAllPartitionsToPartitionedWithNullValue
- addFilteredPartitionsToPartitioned2
- addDataUnpartitioned
- addPartitionToPartitionedHive
- testAddFilesToTableWithManySpecs

Spark: use Bulk deletion for manifests when import files to an iceberg table

---

build.gradle
flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/TestFlinkUpsert.java
flink/v1.20/flink/src/test/java/org/apache/iceberg/flink/TestFlinkUpsert.java
flink/v2.0/flink/src/test/java/org/apache/iceberg/flink/TestFlinkUpsert.java

I often face a situation where the Flink test is stuck in an infinite loop.
Last time it happened with `TestFlinkUpsert`.
This PR adds the timeout to the test, and also adds stop/start logs to the CI output, so it is easier to find the stuck tests.

Build, Flink: Add timeout and print more logs

---

spark/v3.5/build.gradle
spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRewriteDataFilesProcedure.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/SparkCachedTableCatalog.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/SparkCatalog.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/source/IcebergSource.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/source/SparkTable.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/source/SparkWriteBuilder.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteDataFilesAction.java

Backport of #13555 with the following differences:
1.  SparkWriteBuilder in 3.5 used to not need additional logic to add the lineage fields to the spark write schema since every case prior to compaction (e.g. DML) already had this due to the custom rules. However, now with compaction going through a different path where the write schema won't be modified by some external rule, we need to have similar logic as to what exists in 4.0 for adding the lineage fields if they don't exist.

Spark 3.5: Backport #13555 for preserving row lineage on compaction

---

spark/v3.4/build.gradle
spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRewriteDataFilesProcedure.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/SparkCachedTableCatalog.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/SparkCatalog.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/source/IcebergSource.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/source/SparkTable.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/source/SparkWriteBuilder.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteDataFilesAction.java

Backport #13555 for preserving row lineage on compaction, same exact change as https://github.com/apache/iceberg/pull/13637/files for 3.5

Spark 3.4: Backport #13555 for preserving row lineage on compaction

---

spark/v4.0/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRowLevelOperationsWithLineage.java
spark/v4.0/spark/src/test/java/org/apache/iceberg/spark/data/GenericsHelpers.java
spark/v4.0/spark/src/test/java/org/apache/iceberg/spark/data/TestHelpers.java
spark/v4.0/spark/src/test/java/org/apache/iceberg/spark/data/vectorized/parquet/TestParquetVectorizedReads.java

Add v3.5 tests from https://github.com/apache/iceberg/pull/12928 to v4.0

spark 4: add tests to verify Arrow Support for Row lineage when using the Parquet Vectorized reader

---

spark/v4.0/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestAlterTablePartitionFields.java

Add v3.5 tests from https://github.com/apache/iceberg/pull/11868 to v4.0

spark 4: add test to verify ignore partition fields that are dropped from the current-schema

---

flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/sink/dynamic/EvolveSchemaVisitor.java
flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/sink/dynamic/TestEvolveSchemaVisitor.java
flink/v1.20/flink/src/main/java/org/apache/iceberg/flink/sink/dynamic/EvolveSchemaVisitor.java
flink/v1.20/flink/src/test/java/org/apache/iceberg/flink/sink/dynamic/TestEvolveSchemaVisitor.java

This is a clean backport of #13639  to Flink 1.19 and Flink 1.20.

Backport #13639: Flink: Dynamic Sink: Ensure parent for newly added struct is resolved from current schema

---

flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/sink/dynamic/CompareSchemasVisitor.java
flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/sink/dynamic/TestCompareSchemasVisitor.java
flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/sink/dynamic/TestDynamicIcebergSink.java
flink/v1.20/flink/src/main/java/org/apache/iceberg/flink/sink/dynamic/CompareSchemasVisitor.java
flink/v1.20/flink/src/test/java/org/apache/iceberg/flink/sink/dynamic/TestCompareSchemasVisitor.java
flink/v1.20/flink/src/test/java/org/apache/iceberg/flink/sink/dynamic/TestDynamicIcebergSink.java

This is a clean backport of #13659 to Flink 1.20 and 1.19.

Backport: Flink: DynamicSink: Convert existing required fields to optional

---

docker/iceberg-rest-fixture/Dockerfile

When adding common catalog [integration tests in pyiceberg](https://github.com/apache/iceberg-python/pull/2090), we noticed that the rest catalog test, which tests against the rest fixture was failing to throw a `NoSuchNamespaceError` when attempting to create a table in a namespace that does not exist.  @kevinjqliu spotted the issue and we are able to resolve downstream by setting `CATALOG_JDBC_STRICT__MODE=true` in the `docker-compose-integration.yml`, but I think it makes sense to set that variable here to ensure we have consistent behavior wherever this fixture is used.
Tests are now passing downstream with the environment variable set, and the rest catalog is behaving in line with other catalog implementations in the integration tests, which I believe is proof enough that it is safe …

REST-Fixture: Ensure strict mode on jdbc catalog for rest fixture

---

site/docs/rest-catalog-spec.md
site/nav.yml

I always access the irc spec through the left pane of https://iceberg.apache.org/spec/  which brings me to the swagger view. 
The swagger view is great but wont allow me to reference and hyperlink a specific section. 
So I end up navigating to the `rest-catalog-open-api.yaml` file manually. 
This PR adds a dedicated page for REST spec
I also took a few paragraphs from https://www.tabular.io/apache-iceberg-cookbook/getting-started-catalog-background/

docs: add subpage for REST Catalog Spec in "Specification"

---

core/src/main/java/org/apache/iceberg/BaseTransaction.java
core/src/test/java/org/apache/iceberg/TestRemoveSnapshots.java
core/src/test/java/org/apache/iceberg/TestTables.java
core/src/test/java/org/apache/iceberg/TestTransaction.java

Leverage the bulk deletion in FileIO to clean up uncommitted files in BaseTransactions

[Core] Use Bulk deletion for cleaning up uncommitted files in BaseTransaction

---

core/src/main/java/org/apache/iceberg/rest/ExponentialHttpRequestRetryStrategy.java
core/src/main/java/org/apache/iceberg/rest/HTTPClient.java
core/src/test/java/org/apache/iceberg/rest/TestExponentialHttpRequestRetryStrategy.java
core/src/test/java/org/apache/iceberg/rest/TestHTTPClient.java

Was thinking that we should allow for retries for Idempotent Requests from the HTTP Client for 50X issues.

Core: Allow retries for Idempotent Requests with Certain Codes

---

spark/v4.0/spark/src/test/java/org/apache/iceberg/spark/source/DataFrameWriteTestBase.java

Revert back to use hasSameSizeAs instead of isEqualTo in the test since when the number doesn't match, hasSameSizeAs will show the records for debug.
```
Actual and expected should have same size but actual size is:
100
while expected size is:
99
Actual was:
[[-1853403699951111791,keys: [djhnOE!Q8EcmpHvCXKdCGT1bKPynyUGZ57,MJtC!VHkgou8p!H1!10?RdQBc1e69Os-F
TMEx7tg6cF4Kvk2D3PcPGZUspTDtS9wK?p!qqERhkj?DT3A=CottFHuHPVAGRPlOwVpSWdNbP})]
...
at org.apache.iceberg.spark.source.DataFrameWriteTestBase.createDataset(DataFrameWriteTestBase.java:104)
at org.apache.iceberg.spark.source.DataFrameWriteTestBase.writeRecords(DataFrameWriteTestBase.java:69)
at org.apache.iceberg.spark.source.ScanTestBase.writeAndValidate(ScanTestBase.java:105)
at org.apache.iceberg.spark.source.ScanTestBase.writeAndValidate( …
```

Minor: Use hasSameSizeAs to show more debug info

---

flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkDistributionMode.java
flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkV2DistributionMode.java
flink/v1.20/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkDistributionMode.java
flink/v1.20/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkV2DistributionMode.java
flink/v2.0/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkDistributionMode.java
flink/v2.0/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkV2DistributionMode.java

it was a flaky test as reported by issue #11835 . but [recently it starts to fail consistently](https://github.com/apache/iceberg/pull/13645#discussion_r2237722782) and cause a lot of CI failures. disable it for now while we can continue to investigate.

Flink: disable flaky testRangeDistributionStatisticsMigration()

---

api/src/test/java/org/apache/iceberg/variants/TestSerializedPrimitives.java
core/src/main/java/org/apache/iceberg/variants/Variants.java
core/src/test/java/org/apache/iceberg/variants/TestPrimitiveWrapper.java
parquet/src/test/java/org/apache/iceberg/parquet/TestVariantReaders.java

**Updated decimal encoding to follow Variant spec**
Aligned the decimal encoding logic with the [Variant spec](https://github.com/apache/parquet-format/blob/master/VariantEncoding.md), selecting the appropriate decimal type based on precision rather than unscaled value range. Updated corresponding tests to reflect the change.

Use decimal precision to determine variant decimal type

---

core/src/main/java/org/apache/iceberg/SchemaUpdate.java
core/src/test/java/org/apache/iceberg/TestSchemaUpdate.java

Closes #13696 
The case sensitivity settings are ignored during the final validation step when committing the `UpdateSchema`.

Core: Fix case-insensitive validation of fields in schema evolution

---

core/src/main/java/org/apache/iceberg/MetricsUtil.java
core/src/test/java/org/apache/iceberg/TestMetrics.java

Spark expects all StringType fields to be castable to CharSequence, but Iceberg's
readable_metrics lower_bound/upper_bound may decode to java.util.UUID for UUID-typed
columns. This causes a runtime ClassCastException when Spark tries to read those
metrics as UTF8String.
This commit fixes the issue by converting UUID values to string when generating
readable metric values for Spark metadata tables.
Closes: https://github.com/apache/iceberg/issues/13077#issuecomment-2886403713

fix: coerce UUID to String in readable_metrics to avoid ClassCastException in Spark

---

flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/maintenance/api/ExpireSnapshots.java
flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/maintenance/operator/ExpireSnapshotsProcessor.java
flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/maintenance/operator/OperatorTestBase.java
flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/maintenance/operator/TestExpireSnapshotsProcessor.java
flink/v1.20/flink/src/main/java/org/apache/iceberg/flink/maintenance/api/ExpireSnapshots.java
flink/v1.20/flink/src/main/java/org/apache/iceberg/flink/maintenance/operator/ExpireSnapshotsProcessor.java
flink/v1.20/flink/src/test/java/org/apache/iceberg/flink/maintenance/operator/OperatorTestBase.java
flink/v1.20/flink/src/test/java/org/apache/iceberg/flink/maintenance/operator/TestExpireSnapshotsProcessor.java

Flink 1.19, 1.20: Expose cleanExpiredMetadata for snapshot expiration

---

core/src/main/java/org/apache/iceberg/BaseRowDelta.java

Similar to other base class extends MergingSnapshotProducer
- https://github.com/apache/iceberg/blob/main/core/src/main/java/org/apache/iceberg/BaseOverwriteFiles.java
- https://github.com/apache/iceberg/blob/main/core/src/main/java/org/apache/iceberg/BaseReplacePartitions.java
- https://github.com/apache/iceberg/blob/main/core/src/main/java/org/apache/iceberg/StreamingDelete.java
we want to make BaseRowDelta public to allow for customization in validation logic and reuse the rest of the logic in the base class.

Core: make BaseRowDelta public

---

api/src/main/java/org/apache/iceberg/Metrics.java
api/src/test/java/org/apache/iceberg/TestMetricsSerialization.java
core/src/main/java/org/apache/iceberg/DataFiles.java
core/src/main/java/org/apache/iceberg/DoubleFieldMetrics.java
core/src/main/java/org/apache/iceberg/FieldMetrics.java
core/src/main/java/org/apache/iceberg/FileMetadata.java
core/src/main/java/org/apache/iceberg/FloatFieldMetrics.java
core/src/main/java/org/apache/iceberg/MetricsUtil.java
core/src/test/java/org/apache/iceberg/FileGenerationUtil.java
core/src/test/java/org/apache/iceberg/TestMetrics.java
orc/src/main/java/org/apache/iceberg/data/orc/GenericOrcWriters.java
orc/src/main/java/org/apache/iceberg/orc/OrcMetrics.java
parquet/src/main/java/org/apache/iceberg/parquet/ParquetMetrics.java
parquet/src/main/java/org/apache/iceberg/parquet/ParquetValueWriters.java
parquet/src/test/java/org/apache/iceberg/parquet/TestVariantMetrics.java

This preserves the original type of the upper/lower bound of a particular field metric. 
This will be later used to convert from `Metrics` to the new content stats

API, Core: Preserve original Type for upper/lower bounds in Metrics

---

kafka-connect/kafka-connect/src/main/java/org/apache/iceberg/connect/IcebergSinkConfig.java
kafka-connect/kafka-connect/src/main/java/org/apache/iceberg/connect/IcebergSinkConnector.java
kafka-connect/kafka-connect/src/main/java/org/apache/iceberg/connect/channel/CommitterImpl.java
kafka-connect/kafka-connect/src/main/java/org/apache/iceberg/connect/channel/Coordinator.java
kafka-connect/kafka-connect/src/main/java/org/apache/iceberg/connect/channel/CoordinatorThread.java

Clearing resources and seeking offset only if the resources have been initialised.
Addresses -> [https://github.com/apache/iceberg/issues/13593](url)

Close resources only if initialised to avoid rare case NPE

---

docs/docs/flink.md

Per https://issues.apache.org/jira/browse/FLINK-21634, these features are now available.
e.g.
```sql
Flink SQL> SET 'execution.checkpointing.interval' = '30s';
[INFO] Execute statement succeeded.
Flink SQL> CREATE TABLE test01 (col1 INT)
>     WITH (
>         'connector' = 'iceberg',
>         'catalog-name' = 'foo',
>         'catalog-database' = 'my_glue_db',
>         'warehouse' = 's3://rmoff-lakehouse/00/',
>         'catalog-impl' = 'org.apache.iceberg.aws.glue.GlueCatalog',
>         'ioImpl' = 'org.apache.iceberg.aws.s3.S3FileIO');
[INFO] Execute statement succeeded.
-- Add a column
Flink SQL> ALTER TABLE test01 ADD test_col INT;
[INFO] Execute statement succeeded.
Flink SQL> DESCRIBE test01;
+----------+------+------+-----+--------+-----------+
|     name | type | null | key | …
```

[docs] Flink can now add/drop/modify columns

---

azure/src/main/java/org/apache/iceberg/azure/adlsv2/VendedAdlsCredentialProvider.java
azure/src/main/java/org/apache/iceberg/azure/adlsv2/VendedAzureSasCredentialPolicy.java
azure/src/test/java/org/apache/iceberg/azure/adlsv2/TestVendedAdlsCredentialProvider.java
azure/src/test/java/org/apache/iceberg/azure/adlsv2/TestVendedAzureSasCredentialPolicy.java

Fixes #13733
The first commit fixes a crash when trying to use the pipeline async on a parallel Reactor thread:
```
Caused by: java.lang.IllegalStateException: block()/blockFirst()/blockLast() are blocking, which is not supported in thread parallel-1
at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:83)
at reactor.core.publisher.Mono.block(Mono.java:1742)
at org.apache.iceberg.azure.adlsv2.VendedAdlsCredentialProvider.credentialForAccount(VendedAdlsCredentialProvider.java:78)
at org.apache.iceberg.azure.adlsv2.VendedAzureSasCredentialPolicy.maybeUpdateCredential(VendedAzureSasCredentialPolicy.java:58)
at org.apache.iceberg.azure.adlsv2.VendedAzureSasCredentialPolicy.process(VendedAzureSasCredentialPolicy.java:46)
at …
```

Fix concurrency issues in Azure credential refresh.

---

core/src/main/java/org/apache/iceberg/MetricsUtil.java
core/src/test/java/org/apache/iceberg/TestMetrics.java

This reverts commit 7fefc46e95040e96f199d1c8e4d025047ac1bbc6 which caused downstream issues in Trino, see https://github.com/apache/iceberg/pull/13087

Revert "Coerce UUID to String in `readable-metrics` (#13087)"

---

api/src/main/java/org/apache/iceberg/expressions/Expressions.java
api/src/main/java/org/apache/iceberg/expressions/Literals.java
api/src/test/java/org/apache/iceberg/expressions/TestExpressionHelpers.java

This adds factory methods to Expressions that create timestamp literals. This enables creating predicates with the right timestamp precision:
```java
Expressions.equals("ts", nanos(1754434662952357612L));
Expressions.in("ts", nanos(1754434662952357612L), micros(1754434662952357L));
```
This addresses the concerns from #11775.

API: Add expression factory methods for timestamp literals.

---

aliyun/src/main/java/org/apache/iceberg/aliyun/oss/OSSOutputStream.java
aws/src/main/java/org/apache/iceberg/aws/s3/S3OutputStream.java

- fix #13738
Remove unnecessary `File.deleteOnExit()` calls from `S3OutputStream` and `OSSOutputStream` that were causing memory leaks in long-running servers. These calls registered files in the global `DeleteOnExitHook` set which never gets cleared during normal operation, leading to unbounded heap growth. The explicit cleanup logic already handles temporary file deletion properly.

AWS, Aliyun: Fix memory leak by removing deleteOnExit() calls

---

kafka-connect/kafka-connect-transforms/src/main/resources/META-INF/services/org.apache.kafka.connect.transforms.Transformation

Iceberg has a service loader manifest for `IcebergSinkConnector` but does not have a manifest for the Kafka Connect transformations.
Transformations also need a manifest, otherwise by default, with `plugin.discovery=hybrid_warn` you get a warning at startup. Without a manifest, if the `plugin.discovery` configuration is set to `service_load` in the Kafka Connect cluster, then the transformations are not loaded.

Kafka Connect: Add manifests for the transformations

---

core/src/main/java/org/apache/iceberg/actions/FileURI.java
core/src/main/java/org/apache/iceberg/util/FileSystemWalker.java
core/src/test/java/org/apache/iceberg/actions/TestFileURI.java
core/src/test/java/org/apache/iceberg/util/TestFileSystemWalker.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/actions/DeleteOrphanFilesSparkAction.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/actions/TestRemoveOrphanFilesAction.java

Currently, Flink may support DeleteOrphans (https://github.com/apache/iceberg/pull/13302), and some of the code can be reused from Spark.  
The main goal of this PR is to refactor the commonly used code out of the Spark code into the core, so that Flink can reuse it.

Spark,Core: Refactor Delete OrphanFiles by moving common code from Spark to core

---

parquet/src/main/java/org/apache/iceberg/parquet/TripleWriter.java

This PR fixes incorrect JavaDoc `@param` descriptions in the
`TripleWriter` interface that have been present since the initial
commit in 2018.
The issue was caused by copy-paste errors where all type-specific
write methods incorrectly described their `value` parameter as "the
boolean value", which was only correct for the `writeBoolean()`
method. This inconsistency could confuse developers implementing or
using the `TripleWriter` interface.
The `TripleWriter` interface is used internally in Parquet column
writers to handle different data types. Each write method accepts a
repetition level and a value of a specific type, but the JavaDoc
incorrectly described all values as boolean.
Fixed JavaDoc `@param` descriptions for the following methods in `p …

Parquet: Fix incorrect JavaDoc parameter descriptions in TripleWriter

---

core/src/main/java/org/apache/iceberg/CherryPickOperation.java
core/src/main/java/org/apache/iceberg/util/SnapshotUtil.java

These changes ensures that data files are not loaded all into memory at once when validating replaced partitions. Instead it uses `ParallelIterable` to load new files in batches with a hard limit of 30k files in memory at a time.
This PR deprecates `SnapshotUtil.newFiles` in favor of `SnapshotUtil.newFilesBetween`

Core: Batch load new files when validating replaced partitions

---

.baseline/checkstyle/checkstyle.xml
flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/sink/dynamic/TestRowDataConverter.java
flink/v1.20/flink/src/test/java/org/apache/iceberg/flink/sink/dynamic/TestRowDataConverter.java
flink/v2.0/flink/src/test/java/org/apache/iceberg/flink/sink/dynamic/TestRowDataConverter.java

While reviewing the Flink code in the Iceberg project, I noticed the use of JUnit 5's assertThrows. Since the Iceberg project uses AssertJ for unit tests consistently, I have replaced this with AssertJ's assertThatThrownBy to maintain consistency.

Replace `assertThrows` with `assertThatThrownBy` for better readability.

---

site/docs/community.md

Show Apache Iceberg Community Calendar first

docs: reorder so "Apache Iceberg Community Calendar" is first

---

spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/data/SparkParquetWriters.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/data/SparkParquetWriters.java
spark/v4.0/spark/src/main/java/org/apache/iceberg/spark/data/SparkParquetWriters.java

Above we have:
```
if (logicalTypeAnnotation != null) {
return logicalTypeAnnotation(...)
}
```
So, the branch wil never be `true`.

Spark: Prune dead branch

---

spark/v4.0/spark/src/main/java/org/apache/iceberg/spark/actions/RewriteDataFilesSparkAction.java
spark/v4.0/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteDataFilesAction.java

Fixes: https://github.com/apache/iceberg/issues/11648
Disables executor cache for delete files in RewriteDataFilesSparkAction.

Spark 4.0: Disable executor cache for delete files in RewriteDataFilesSparkAction

---

flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/sink/shuffle/DataStatisticsCoordinator.java
flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/sink/shuffle/TestDataStatisticsCoordinator.java
flink/v1.20/flink/src/main/java/org/apache/iceberg/flink/sink/shuffle/DataStatisticsCoordinator.java
flink/v1.20/flink/src/test/java/org/apache/iceberg/flink/sink/shuffle/TestDataStatisticsCoordinator.java

This pr is a backport https://github.com/apache/iceberg/pull/13827 to Flink 1.20 and 1.19. It is a clearn backport.

Flink: Backport #13827 to flink 1.20 and 1.19

---

core/src/main/java/org/apache/iceberg/BaseMetastoreCatalog.java
core/src/main/java/org/apache/iceberg/TableMetadataParser.java
core/src/test/java/org/apache/iceberg/TestTableMetadataParser.java
core/src/test/java/org/apache/iceberg/hadoop/HadoopTableTestBase.java

The file io parameter is never used in  `TableMetadataParser#read(org.apache.iceberg.io.FileIO, org.apache.iceberg.io.InputFile)` and can be removed.

Core: Deprecate TableMetadataParser.read with unused file io parameter

---

spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/actions/RewriteDataFilesSparkAction.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteDataFilesAction.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/actions/RewriteDataFilesSparkAction.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteDataFilesAction.java
spark/v4.0/spark/src/main/java/org/apache/iceberg/spark/actions/RewriteDataFilesSparkAction.java

Backport of https://github.com/apache/iceberg/pull/13820 to Spark 3.4 and 3.5 since it was originally reported in Spark 3.5 https://github.com/apache/iceberg/issues/11648

Spark 3.5, 3.4: Disable executor cache for delete files in RewriteDataFilesSparkAction

---

spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/actions/RewriteManifestsSparkAction.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteManifestsAction.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/actions/RewriteManifestsSparkAction.java
spark/v4.0/spark/src/main/java/org/apache/iceberg/spark/actions/RewriteManifestsSparkAction.java
spark/v4.0/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteManifestsAction.java

This is a follow on to https://github.com/apache/iceberg/pull/12840. Related to https://github.com/apache/iceberg/issues/9615. Ported the exact same functionality and tests to spark 3.4 and 4.0.

Porting custom spark manifest rewrite order to spark 3.4 and 4.0

---

core/src/main/java/org/apache/iceberg/rest/ErrorHandlers.java
core/src/main/java/org/apache/iceberg/rest/ExponentialHttpRequestRetryStrategy.java
core/src/test/java/org/apache/iceberg/rest/TestExponentialHttpRequestRetryStrategy.java
open-api/rest-catalog-open-api.yaml

Mark 503 as non retryable in update table, as pointed some of the very common services like Envoy 
details : https://lists.apache.org/thread/oqonscy1b4qlmovnjtbcohz38kgprgmq
There seems to be a general alignment on the direction to treat 503 as commit state unknown as the outcomes are severe as if leading to table corruption.

Spec, Core: mark 503 as non retryable error code for Update Table

---

aws/src/main/java/org/apache/iceberg/aws/s3/S3InputStream.java
aws/src/test/java/org/apache/iceberg/aws/s3/TestS3InputStream.java

When S3InputStreamReadFully is called it does not expose the underlying InputStream to the caller and does not close it on its own. This leads to connection leak in S3Client since the underlying connection is not returned to connection pool in Apace HTTP client.

Fix S3InputStream.readFully connection leak

---

open-api/rest-catalog-open-api.yaml

mention may be null in description but not encoded in the openapi spec
https://stackoverflow.com/questions/45575493/what-does-required-in-openapi-really-mean

spec: be explict about nullability of  `LoadTableResult`'s `metadata-location` 

---

open-api/rest-catalog-open-api.py
open-api/rest-catalog-open-api.yaml

Closes #13901
this is the only case of required but null/missing in the REST spec

update REST spec to clarify `AssertRefSnapshotId`'s `snapshot-id` field as required

---

spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkDataWrite.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/sql/TestStoragePartitionedJoins.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkDataWrite.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/sql/TestStoragePartitionedJoins.java
spark/v4.0/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkDataWrite.java
spark/v4.0/spark/src/test/java/org/apache/iceberg/spark/sql/TestStoragePartitionedJoins.java

- In `TestStoragePartitionedJoins.java`, most of the query order projected columns except one. That leads to indeterministic result.
- In `TestSparkDataWrite.java`, also order by all projected columns especially when the value of the `id` column in `SimpleRecord` are identical.

Spark: (unit test) Order query result deterministically

---

docs/mkdocs.yml

Adding "Memiiso Debezium Iceberg Consumer" project to third party integrations
link: https://memiiso.github.io/debezium-server-iceberg/
There are end user use-cases but the project is not widely known by end users. This could help to get more visibility and reach to correct users. 
The project is not official Debezium repository, however its  known by the debezium project team. I know it might not be ideal(since the project is not official debezoim.io) but opening PR in case its acceptable.

Docs: Add Memiiso Debezium to third party integrations

---

flink/v2.0/flink/src/main/java/org/apache/iceberg/flink/maintenance/api/FlinkMaintenanceConfig.java
flink/v2.0/flink/src/main/java/org/apache/iceberg/flink/maintenance/api/LockConfig.java
flink/v2.0/flink/src/main/java/org/apache/iceberg/flink/maintenance/api/RewriteDataFilesConfig.java

This pull request improves the readability and maintainability of the following configuration classes by enhancing the descriptions for ConfigOptions and adding necessary comments:
- FlinkMaintenanceConfig:
Added clear descriptions for configuration options such as `LOCK_CHECK_DELAY_OPTION`, `PARALLELISM_OPTION`, `RATE_LIMIT_OPTION`, and `SLOT_SHARING_GROUP_OPTION`.
Added comments explaining the purpose and function of each configuration option.
- LockConfig:
Added detailed descriptions for configuration options like `LOCK_TYPE_OPTION`, `LOCK_ID_OPTION`, `JdbcLockConfig`, and `ZkLockConfig` related to different locking mechanisms.
Improved code clarity by explaining the role of each configuration option for locking (e.g., `JDBC_URI_OPTION`, `ZK_URI_OPTION`, etc.).
- …

Flink: Improve ConfigOption Descriptions for Flink Table Maintenance Configs.

---

site/docs/vendors.md

Adding OLake to the list of vendors that support Apache Iceberg™

Docs: Add OLake to list of vendors

---

flink/v1.19/flink/src/jmh/java/org/apache/iceberg/flink/sink/shuffle/SketchRangePartitionerBenchmark.java
flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/sink/shuffle/DataDistributionUtil.java
flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/sink/shuffle/TestDataDistributionUtil.java
flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/sink/shuffle/TestRangePartitionerSkew.java
flink/v1.20/flink/src/jmh/java/org/apache/iceberg/flink/sink/shuffle/MapRangePartitionerBenchmark.java
flink/v1.20/flink/src/jmh/java/org/apache/iceberg/flink/sink/shuffle/SketchRangePartitionerBenchmark.java
flink/v1.20/flink/src/test/java/org/apache/iceberg/flink/sink/shuffle/DataDistributionUtil.java
flink/v1.20/flink/src/test/java/org/apache/iceberg/flink/sink/shuffle/TestDataDistributionUtil.java
flink/v1.20/flink/src/test/java/org/apache/iceberg/flink/sink/shuffle/TestRangePartitionerSkew.java

It is **almost** a clean backport
```
git diff HEAD~1 HEAD flink/v2.0 |sed "s/v2.0/v1.20/g">/tmp/1.20.patch
git apply -3 /tmp/1.20.patch
git diff HEAD~1 HEAD flink/v2.0 |sed "s/v2.0/v1.19/g">/tmp/1.19.patch
git apply -3 /tmp/1.19.patch
git co --theirs flink/v1.19/flink/src/jmh/java/org/apache/iceberg/flink/sink/shuffle/MapRangePartitionerBenchmark.java
```
There was a diff btw 1.19 and other versions before the backport
```
➜  iceberg git:(main) ✗ diff flink/v1.19/flink/src/jmh/java/org/apache/iceberg/flink/sink/shuffle/MapRangePartitionerBenchmark.java flink/v1.20/flink/src/jmh/java/org/apache/iceberg/flink/sink/shuffle/MapRangePartitionerBenchmark.java
143c143
<     return prefix + new String(buffer, StandardCharsets.US_ASCII);
---
>     return prefix + new String(buffer, …
```

Flink: backport PR #13900 for adding unit test of skewness for range partitioner

---

open-api/rest-catalog-open-api.py
open-api/rest-catalog-open-api.yaml

Should we not update `format-version` in REST spec to deal with V3 and anticipate V4 ?

OpenAPI: Update the range in format-version (for v3)

---

deploy.gradle

Spark requires JDK 17 or 21, so let's bump the JDK needed to release to 17.
Since we set the target at 11 it works with JDK11 and higher:
https://github.com/apache/iceberg/blob/522de0fe839df2f22f4472241bce632995adc01d/build.gradle#L192
https://github.com/apache/iceberg/blob/522de0fe839df2f22f4472241bce632995adc01d/build.gradle#L245-L247

Build: Release with JDK17

---

dev/stage-binaries.sh

found that Spark 4.0 module wasn't publish during staging binaries.

Build: add spark 4.0 to stage-binaries.sh

---

dev/stage-binaries.sh
site/docs/how-to-release.md

--no-parallel: allow us not to manually modify the gradle.properties file before running the release script. updated the `how-to-release.md` doc accordingly.
--no-configuration-cache: initially, I couldn't get parallel run disabled via modifying the `gradle.propertes` file or cmd-line arg. It turns out that gradle daemon can cache the config. With this option, parallel build and staging to Maven repo are disabled correctly.

Build: add gradle options --no-parallel and --no-configuration-cache to stage-binaries.sh

---

site/mkdocs.yml

closes #13968
Based on the version in gradle/libs.versions.toml: https://github.com/apache/iceberg/blob/d8767f1b56a4de379d3d49a5c2f02bab4b0e330f/gradle/libs.versions.toml#L76

Docs: Update nessie version

---

format/spec.md

Based on [mailing list discussion](https://lists.apache.org/thread/p94gobths7b92jkk1c6td1gz22jxf3ld) try to capture semantics of type promotion/schema evolution and old writers.

[SPEC] Add implementation note about schema evolution

---

spark/v4.0/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/ExtensionsTestBase.java
spark/v4.0/spark/src/test/java/org/apache/iceberg/spark/source/TestFilteredScan.java
spark/v4.0/spark/src/test/java/org/apache/iceberg/spark/source/TestForwardCompatibility.java
spark/v4.0/spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSpark.java
spark/v4.0/spark/src/test/java/org/apache/iceberg/spark/source/TestPartitionPruning.java
spark/v4.0/spark/src/test/java/org/apache/iceberg/spark/source/TestPartitionValues.java
spark/v4.0/spark/src/test/java/org/apache/iceberg/spark/source/TestSnapshotSelection.java
spark/v4.0/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkDataFile.java
spark/v4.0/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkDataWrite.java
spark/v4.0/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkReadProjection.java
spark/v4.0/spark/src/test/java/org/apache/iceberg/spark/source/TestStructuredStreaming.java
spark/v4.0/spark/src/test/java/org/apache/iceberg/spark/source/TestWriteMetricsConfig.java

Previous PR #13101  for issue #13097 focused on REST server tests. Didn't completely resolve the issue for Spark tests. 
After this fix, the spark tests passed in my local env (without /etc/hosts workaround).
```
./gradlew -DsparkVersions=4.0 :iceberg-spark:iceberg-spark-4.0_2.13:test
```
Will create a separate PR for backport to 3.4 and 3.5. Hopefully, it will be a clean backport.

Spark: use lookback address for spark session in tests to work with more restrictive firewall env on dev machines

---

spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/ExtensionsTestBase.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/source/TestFilteredScan.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/source/TestForwardCompatibility.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSpark.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/source/TestPartitionPruning.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/source/TestPartitionValues.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/source/TestSnapshotSelection.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkDataFile.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkDataWrite.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkReadProjection.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/source/TestStructuredStreaming.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/source/TestWriteMetricsConfig.java
spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/ExtensionsTestBase.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestFilteredScan.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestForwardCompatibility.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSpark.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestPartitionPruning.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestPartitionValues.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestSnapshotSelection.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkDataFile.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkDataWrite.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkReadProjection.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestStructuredStreaming.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestWriteMetricsConfig.java

This is a clean backport except for the only conflict that I called out in one comment.

Spark: backport PR #13993 to use loopback address for spark driver in tests

---

aws/src/test/java/org/apache/iceberg/aws/s3/TestS3FileIOProperties.java

Looks like during the migration to AssertJ the assertions were not properly adjusted - AssertJ expects actual value to be the argument of assertThat.

Fixing AssertJ assertions in TestS3FileIOProperties

---

site/requirements.txt

https://github.com/bitsondatadev/mkdocs-monorepo-plugin/commit/6cef2431f99f8b68ca472376d3ada79ec912958c has been [committed in upstream](https://github.com/backstage/mkdocs-monorepo-plugin/pull/140/files#diff-a4e8ad01beb5a9b33f939926810cf6d661132f85e1c4f4ec9882222cfa45281c), so the forked mkdocs-monorepo-plugin is no longer needed.
cc @bitsondatadev @Fokko

Site: Bump up mkdocs-monorepo-plugin to 1.1.2

---

core/src/main/java/org/apache/iceberg/RewriteTablePathUtil.java
spark/v4.0/spark/src/main/java/org/apache/iceberg/spark/actions/RewriteTablePathSparkAction.java
spark/v4.0/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteTablePathsAction.java

- #TODO: update partition statistics file paths (completes the table path rewrite functionality).

Spark 4.0: Add Support for PartitionStatistics Files in RewriteTablePath.

---

docs/docs/flink.md

`flink-actions.md` got renamed to `flink-maintenance.md` in https://github.com/apache/iceberg/commit/2df7dc760a63622c0ecd884155e471b27989191d
https://github.com/apache/iceberg/blob/main/docs/docs/flink-maintenance.md
cc @manuzhang

docs: flink: Fix updated link

---

spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/source/SparkMicroBatchStream.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/source/TestStructuredStreamingRead3.java
spark/v4.0/spark/src/main/java/org/apache/iceberg/spark/source/SparkMicroBatchStream.java
spark/v4.0/spark/src/test/java/org/apache/iceberg/spark/source/TestStructuredStreamingRead3.java

Backport #13824 to Spark versions 4.0 & 3.4

Spark 4.0, 3.4: Backport #13824 to Support Trigger AvailableNow in SS

---

spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestComputePartitionStatsProcedure.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/actions/ComputePartitionStatsSparkAction.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/actions/SparkActions.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/procedures/ComputePartitionStatsProcedure.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/procedures/SparkProcedures.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/actions/TestComputePartitionStatsAction.java

backport #12450, #13480 to Spark3.4

Spark 3.4: Backport: Add procedure and action to compute partition stats.

---

core/src/main/java/org/apache/iceberg/BaseMetadataTable.java
core/src/test/java/org/apache/iceberg/TestMetadataTableScansWithPartitionEvolution.java

To replicate this issue run the following spark queries:
```sql
CREATE TABLE ns.barfoo (dateint INT,hour INT, data STRING) USING iceberg PARTITIONED BY (dateint, hour);
INSERT INTO ns.barfoo (dateint, hour, data) VALUES (20250101, 1, 'a'), (20250102, 1, 'a'), (20250102, 2, 'a');
ALTER TABLE ns.barfoo DROP PARTITION FIELD dateint;
ALTER TABLE ns.barfoo DROP COLUMN dateint;
SELECT * FROM ns.barfoo.files;
```

Core: Allow reading metadata table when scanning table with dropped partition source field

---

site/docs/vendors.md

Adding StreamNative to the vendors.md file

Add StreamNative to the vendor list

---

api/src/main/java/org/apache/iceberg/Snapshot.java
format/spec.md

Relevant dev-list thread: https://lists.apache.org/thread/29n4t7xfzx4g2pcgt3yzzwn1oqcot0nn
Closes #14067

Spec: bring back added-rows in snapshot fields

---

.github/ISSUE_TEMPLATE/iceberg_bug_report.yml
.github/ISSUE_TEMPLATE/iceberg_improvement.yml
.github/ISSUE_TEMPLATE/iceberg_proposal.yml
.github/ISSUE_TEMPLATE/iceberg_question.yml

External contributors are usually not very familiar with all the procedures and rules and such at Apache.
Important "stop signs" should be added to the issue templates, highlighting to not share sensitive information and particularly to report potential vulnerabilities and security issues via security@apache.org.

Add "stop signs" for sensitive information/issues to all issue templates

---

bigquery/src/main/java/org/apache/iceberg/gcp/bigquery/BigQueryMetastoreCatalog.java
bigquery/src/test/java/org/apache/iceberg/gcp/bigquery/TestBigQueryCatalog.java

This PR fixes a table validity check for the BigQueryMetastoreCatalog introduced in https://github.com/apache/iceberg/pull/12808. We need this validity check in order to access metadata tables using the syntax documented in: https://iceberg.apache.org/docs/1.10.0/docs/hive/?h=metadata#querying-metadata-tables. For example [inspecting metadata tables](https://iceberg.apache.org/docs/1.10.0/docs/spark-queries/?h=partitions#inspecting-with-dataframes). This is similar to the HiveCatalog [implementation](https://github.com/apache/iceberg/blob/345140e9f7d428fcc3b4fcc639a690084a698b76/hive-metastore/src/main/java/org/apache/iceberg/hive/HiveCatalog.java#L663-L665). Without this check Iceberg will attempt to load a regular table and fail in the BigQueryMetastoreCatalog implementation because the …

BigQuery: Add table validity check for BigQueryMetastoreCatalog

---

gradle/libs.versions.toml

Hadoop 3.4.2 has been released, and we can consider upgrading to this version.

Build: Bump hadoop from 3.4.1 to 3.4.2.

---

docs/docs/spark-procedures.md

In the RewriteTablePath procedure, we added the `create_file_list` parameter to control whether a list of rewritten files is generated. We also introduced two new output fields: `rewritten_manifest_file_paths_count` and `rewritten_delete_file_paths_count`. 
These details have been added to the documentation.

Doc: Enhance RewriteTablePath procedure documentation with parameter details.

---

spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestCherrypickSnapshotProcedure.java
spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestExpireSnapshotsProcedure.java
spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestFastForwardBranchProcedure.java
spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestPublishChangesProcedure.java
spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRemoveOrphanFilesProcedure.java
spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRewriteManifestsProcedure.java
spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRollbackToSnapshotProcedure.java
spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestSetCurrentSnapshotProcedure.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/procedures/BaseProcedure.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/procedures/CherrypickSnapshotProcedure.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/procedures/ExpireSnapshotsProcedure.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/procedures/FastForwardBranchProcedure.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/procedures/ProcedureInput.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/procedures/PublishChangesProcedure.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/procedures/RegisterTableProcedure.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/procedures/RemoveOrphanFilesProcedure.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/procedures/RewriteManifestsProcedure.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/procedures/RollbackToSnapshotProcedure.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/procedures/RollbackToTimestampProcedure.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/procedures/SetCurrentSnapshotProcedure.java

Backport https://github.com/apache/iceberg/pull/14179

Spark 3.4: Refactor Spark procedures to consistently use ProcedureInput for parameter handling.

---

docs/docs/flink-configuration.md
flink/v2.0/flink/src/main/java/org/apache/iceberg/flink/FlinkWriteConf.java
flink/v2.0/flink/src/main/java/org/apache/iceberg/flink/FlinkWriteOptions.java
flink/v2.0/flink/src/main/java/org/apache/iceberg/flink/sink/IcebergSink.java
flink/v2.0/flink/src/test/java/org/apache/iceberg/flink/TestFlinkTableSink.java

Introduces a new 'uid-suffix' Flink write option that allows customizing the IcebergSink operator UID suffix.
This is particularly useful for statement sets with multiple INSERT operations targeting the same table. In the `IcebergSink` implementation, we were currently specifying a default UID suffix using the table's name, which led to hash collisions when multiple instances of IcebergSink attempted to register themselves in different DAGs.

Flink: Adds uid-suffix write option to prevent operator UID hash collisions

---

site/nav.yml

Add reference in the documentation about the Starburst connector.
The Starburst Iceberg connector is the product of intensive focus on providing state of the art connector for the Iceberg workloads on its Query Engine.
https://docs.starburst.io/latest/connector/iceberg.html

Add reference to the Starburst connector

---

flink/v2.1/flink/src/main/java/org/apache/iceberg/flink/sink/dynamic/DynamicCommitter.java
flink/v2.1/flink/src/test/java/org/apache/iceberg/flink/sink/dynamic/TestDynamicCommitter.java
flink/v2.1/flink/src/test/java/org/apache/iceberg/flink/sink/dynamic/TestDynamicIcebergSink.java

Previously, the DynamicCommitter could commit duplicate WriteResults when recovering from failures, leading to incorrect data in tables. This change gets rid of the unnecessary commits for each WriteResult, which caused the problems in the first place, and instead commits all the WriteResults for each Flink checkpoint / table / branch together. 
The WriteResults for each checkpoint / table / branch can safely be committed together, even in the presence of delete files. Since we now commit once per Flink checkpoint and table / branch, we can use the already existing max Flink checkpoint id in the snapshot table properties for the table / branch to detect whether we have already committed.
We intentionally chose not to combine WriteResults across Flink checkpoints, which would be possible …

Flink: Ensure DynamicCommitter idempotence in the presence of failures

---

aws-bundle/build.gradle

A recent AWS SDK version update introduced Log4j version that are incompatible with some environments (like Spark 4.x).  This results in class conflicts if the bundle jar is resolved before other logging jars.
The bom should not include the logging libraries and the existing exclusions don't cover all of the artifacts.  This PR expands the exclusions to remove the conflicting dependencies.

AWS: exclude logging dependencies from bundle

---

build.gradle
flink/v1.20/build.gradle
flink/v2.0/build.gradle
flink/v2.1/build.gradle
spark/v3.4/build.gradle
spark/v3.5/build.gradle
spark/v4.0/build.gradle

BigQuery: Add iceberg-bigquery dependency to spark and flink build scripts

---

.github/workflows/api-binary-compatibility.yml
.github/workflows/delta-conversion-ci.yml
.github/workflows/flink-ci.yml
.github/workflows/hive-ci.yml
.github/workflows/java-ci.yml
.github/workflows/jmh-benchmarks.yml
.github/workflows/kafka-connect-ci.yml
.github/workflows/labeler.yml
.github/workflows/license-check.yml
.github/workflows/open-api.yml
.github/workflows/publish-snapshot.yml
.github/workflows/recurring-jmh-benchmarks.yml
.github/workflows/spark-ci.yml
.github/workflows/stale.yml

Build: Bump runner image from Ubuntu 22.04 to 24.04.
The Ubuntu 24.04 image for Actions is now generally available since Sep 2024 : 
https://github.blog/changelog/2024-09-25-actions-new-images-and-ubuntu-latest-changes/

Build: Bump runner image from Ubuntu 22.04 to 24.04.

---

gradle/libs.versions.toml

`jackson-annotations` has been decoupled according to https://github.com/FasterXML/jackson-annotations/issues/307#issuecomment-3238744290
Supersedes #13954

Build: Bump jackson-bom from 2.19.2 to 2.20.0 and jackson-annotations to 2.20

---

core/src/main/java/org/apache/iceberg/view/ViewProperties.java
docs/docs/spark-ddl.md
docs/docs/view-configuration.md
spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestViews.java
spark/v4.0/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestViews.java

The context of this PR is https://github.com/apache/iceberg/pull/12017#issuecomment-3238253488.
This PR tries to deprecate the `write.metadata.path` property which was added in [PR#12017](https://github.com/apache/iceberg/pull/12017), and use `location` instead to for the view location configuration.
That PR#12017 added `write.metadata.path` to customize the View location. However, the [Iceberg View Spec](https://iceberg.apache.org/view-spec/#view-metadata) defines `location` as its view location. Using `write.metadata.path` is confusing because it specifies two view locations in its view properties, along with `location`. 
Both properties can configure the view location, however, 
* if `write.metadata.path` is specified, the view metadata is put in the path defined `write.metadata.path` …

Core, Spark: Deprecate `write.metadata.path` and use `location` to customize view location
