apache/iceberg

core/src/main/java/org/apache/iceberg/TableMetadata.java, core/src/main/java/org/apache/iceberg/TableMetadataParser.java, core/src/test/java/org/apache/iceberg/TestTableMetadata.java
=> Add a tolerance check of 1 minute to prevent small clock skews to break commits

api/src/main/java/org/apache/iceberg/RowDelta.java, api/src/main/java/org/apache/iceberg/Table.java, api/src/main/java/org/apache/iceberg/Transaction.java, core/src/main/java/org/apache/iceberg/BaseMetadataTable.java, core/src/main/java/org/apache/iceberg/BaseRowDelta.java, core/src/main/java/org/apache/iceberg/BaseTable.java, core/src/main/java/org/apache/iceberg/BaseTransaction.java, core/src/main/java/org/apache/iceberg/CommitCallbackTransaction.java, core/src/main/java/org/apache/iceberg/DataFiles.java, core/src/main/java/org/apache/iceberg/FileMetadata.java, core/src/main/java/org/apache/iceberg/ManifestFilterManager.java, core/src/main/java/org/apache/iceberg/ManifestReader.java, core/src/main/java/org/apache/iceberg/MergingSnapshotProducer.java, core/src/main/java/org/apache/iceberg/SnapshotProducer.java, core/src/main/java/org/apache/iceberg/SnapshotSummary.java, core/src/test/java/org/apache/iceberg/TableTestBase.java, core/src/test/java/org/apache/iceberg/TestRowDelta.java, core/src/test/java/org/apache/iceberg/V2TableTestBase.java
This adds support for `DeleteFile` to `MergingSnapshotProducer`, which is the base class used to implement most operations that update Iceberg table data.
To test the updates, this adds a new `RowDelta` operation to `Table` and `Transaction` that adds `DeleteFile` and `DataFile` instances to the table. The tests are in `TestRowDelta` and mainly test the behavior of operations when there are delete files in table metadata. This doesn't add new tests for `DeleteFile` compaction or cleanup because the same code is used for delete and data files. There is no need to duplicate the testing done for data files.
=> Support DeleteFile in MergingSnapshotProducer

core/src/main/java/org/apache/iceberg/AllDataFilesTable.java, core/src/main/java/org/apache/iceberg/AllEntriesTable.java, core/src/main/java/org/apache/iceberg/AllManifestsTable.java, core/src/main/java/org/apache/iceberg/BaseAllMetadataTableScan.java, core/src/main/java/org/apache/iceberg/BaseTableScan.java, core/src/main/java/org/apache/iceberg/DataFilesTable.java, core/src/main/java/org/apache/iceberg/DataTableScan.java, core/src/main/java/org/apache/iceberg/IncrementalDataTableScan.java, core/src/main/java/org/apache/iceberg/ManifestEntriesTable.java, core/src/main/java/org/apache/iceberg/StaticTableScan.java, core/src/main/java/org/apache/iceberg/TableScanContext.java
This PR is a refactor of `TableScan` implementations to use a `TableScanContext` object for the optional arguments used.
As discussed in https://github.com/apache/iceberg/pull/1094#discussion_r435532764, when new arguments are added to a `TableScan` the number of changes needed is really large only to pass down the arguments through the refinement calls. 
This change will make such changes more straightforward minimizing the number of changes required to add an argument, which would only be required now in the context object and in the specific `TableScan` that would use it, leading to more maintainable code.
PTAL @aokolnychyi @rdblue
=> Refactor TableScan optional arguments into an immutable context object

site/docs/api-quickstart.md, site/docs/java-api-quickstart.md
This PR propose to add HadoopCatalog example to create/load tables in the Iceberg User docs.
=> Add HadoopCatalog example to create/load tables in the Iceberg User docs

core/src/main/java/org/apache/iceberg/avro/PruneColumns.java, core/src/test/java/org/apache/iceberg/avro/TestAvroOptionsWithNonNullDefaults.java
Avro files written by non-Iceberg writers can contain optional schemas where the NULL schema is second in the options list. If there is a default value associated with the field, we need to ensure that our visitors preserve this ordering else it can lead to issues like `org.apache.avro.AvroTypeException: Invalid default for field field: [] not a ["null",{"type":"array","items":"long"}]`. This is because the Avro [spec requires](https://avro.apache.org/docs/current/spec.html#Unions) the type of the default value to match the first option in the schema.
The changes should be limited to the codepaths which interact with non-Iceberg Avro files so I believe the visitors used in `ProjectionDatumReader` are the only ones affected.
Error stacktraces:
```
org.apache.avro.AvroTypeException: Invalid …
```
=> Fix errors when reading options in Avro files with non-null defaults

data/src/test/java/org/apache/iceberg/data/TestLocalScan.java, data/src/test/java/org/apache/iceberg/data/orc/TestGenericData.java, orc/src/main/java/org/apache/iceberg/orc/OrcMetrics.java, orc/src/test/java/org/apache/iceberg/orc/TestExpressionToSearchArgument.java
This PR attempts to solve issues #1116 and #1113 when running in different Time Zones.
I've added a test to check for local scan on different timezones which surfaced an issue with the pushdown predicates with DATE columns, which seem to use incorrect incorrect TZ to read the metrics within the ORC reader. Due to this, disabling ORC lower/upper bound metrics for Date in Iceberg as well.
I've tested by changing system TZ to other timezones and running the tests and they pass.
PTAL @shardulm94 @chenjunjiedada if you have a chance, please pull this branch and run the test suite locally just to double check the build. Thanks!
@rdblue
=> ORC: fix date metrics to adjust milliseconds to local timezone

parquet/src/main/java/org/apache/iceberg/parquet/ParquetDictionaryRowGroupFilter.java
Spark executors use a new thread for each task, and Iceberg reuses a thread-local evaluator when running row group filters. The combination of new threads and thread-local prevents those evaluators from being garbage collected.
The evaluator holds state for the current row group, which can be large for the dictionary row group filter. This PR avoids a large memory leak by cleaning up references to the row group's dictionaries and other state after each evaluation.
=> Fix executor memory leak in Parquet row group filter

api/src/main/java/org/apache/iceberg/exceptions/NoSuchIcebergTableException.java, core/src/main/java/org/apache/iceberg/BaseMetastoreCatalog.java, core/src/main/java/org/apache/iceberg/hadoop/HadoopCatalog.java, hive/src/main/java/org/apache/iceberg/hive/HiveCatalog.java, hive/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java, spark3/src/main/java/org/apache/iceberg/spark/Spark3Util.java, spark3/src/main/java/org/apache/iceberg/spark/SparkCatalog.java, spark3/src/main/java/org/apache/iceberg/spark/source/IcebergSource.java, spark3/src/main/java/org/apache/iceberg/spark/source/SparkBatchWrite.java, spark3/src/main/java/org/apache/iceberg/spark/source/SparkTable.java
This is the last set of changes from the spark-3 branch.
* Add name to catalog implementations
* Add `NoSuchIcebergTableException` to Hive when a table is found, but is not Iceberg
* Return `false` from `dropTable` if the identifier is invalid and cannot be a table
* Fix table create properties; provider must always be `iceberg`
=> Spark: Fix remaining differences from spark-3 branch

core/src/main/java/org/apache/iceberg/hadoop/HadoopCatalog.java, core/src/test/java/org/apache/iceberg/hadoop/TestHadoopCatalog.java, hive/src/main/java/org/apache/iceberg/hive/HiveCatalog.java, spark/src/test/java/org/apache/iceberg/spark/SparkTestBase.java, spark3/src/main/java/org/apache/iceberg/spark/SparkCatalog.java, spark3/src/test/java/org/apache/iceberg/spark/SparkCatalogTestBase.java, spark3/src/test/java/org/apache/iceberg/spark/sql/TestNamespaceSQL.java
This adds `SupportsNamespaces` to `SparkCatalog` and adds tests in `TestNamespaceSQL`.
This also adds a couple of new base classes for Spark tests that will be used for other SQL test suites.
=> Support namespaces in SparkCatalog

mr/src/test/java/org/apache/iceberg/mr/mapred/serde/objectinspector/TestIcebergObjectInspector.java
Use fixed IDs in TestIcebergObjectInspector. Follow-up PR for a comment left on apache/iceberg#1103.
=> Use fixed IDs in TestIcebergObjectInspector

orc/src/main/java/org/apache/iceberg/orc/ORCSchemaUtil.java, orc/src/main/java/org/apache/iceberg/orc/OrcSchemaVisitor.java, orc/src/main/java/org/apache/iceberg/orc/OrcSchemaWithTypeVisitor.java, orc/src/main/java/org/apache/iceberg/orc/OrcToIcebergVisitor.java, orc/src/test/java/org/apache/iceberg/orc/TestORCSchemaUtil.java
As mentioned in https://github.com/apache/iceberg/pull/989#discussion_r420996718 and referenced in #1055 ORC previously assigned an ID based on an `AtomicCounter` to assign Iceberg IDs if they were not found in ORC type attributes.
This PR changes the implementation to use the ORC type visitor and skips types that do not have an Iceberg ID in the type attribute as follows:
* Primitives: if the type does not have an Iceberg ID it is skipped
* Lists: only included if element and the list type itself have an Iceberg ID, otherwise it is skipped
* Maps: only included if key, value and the map type itself have an Iceberg ID, otherwise it is skipped
* Structs: included as long as any of the fields in the struct has an Iceberg ID, otherwise it is skipped 
If the schema as a whole does not have …
=> ORC: skip non-iceberg columns when converting schema to Iceberg

orc/src/main/java/org/apache/iceberg/orc/OrcMetrics.java
This simplifies the visitor used to determine which ORC columns should have stats stored in table metadata. It uses the new visitor introduced in #1140. This is an alternative implementation to #1112.
=> ORC: Simplify logic to determine which columns have stats

.travis.yml, build.gradle, deploy.gradle, settings.gradle
Fixes #577.
Co-authored-by: Fokko Driesprong <fokko@apache.org>
=> Add JDK 11 to CI build, disable Spark 2.4 with JDK 11

data/src/main/java/org/apache/iceberg/data/parquet/BaseParquetReaders.java, data/src/test/java/org/apache/iceberg/data/TestReadProjection.java
The visitor that builds Parquet value readers for Iceberg generics did not handle cases where the expected type was null because a field was is not projected. This was not a problem for most primitive types that did not use the expected type, but cases that did would throw a `NullPointerException`.
Fixes #1117.
=> Parquet: Fix NPE in value reader building for projections

api/src/main/java/org/apache/iceberg/expressions/Evaluator.java, api/src/main/java/org/apache/iceberg/expressions/InclusiveMetricsEvaluator.java, api/src/main/java/org/apache/iceberg/expressions/ManifestEvaluator.java, api/src/main/java/org/apache/iceberg/expressions/ResidualEvaluator.java, api/src/main/java/org/apache/iceberg/expressions/StrictMetricsEvaluator.java, parquet/src/main/java/org/apache/iceberg/parquet/ParquetDictionaryRowGroupFilter.java, parquet/src/main/java/org/apache/iceberg/parquet/ParquetMetricsRowGroupFilter.java
Follow up the discussion in #1139, this change remove thread local objects and use new visitors to keep the code straightforward.
=> Remove thread local objects and use new visitors

api/src/main/java/org/apache/iceberg/util/CharSequenceSet.java
`MergingSnapshotProducer` was recently refactored to separate out manifest filtering and merging so it could be reused for delete files. That refactor also updated the filter to use a `CharSequenceSet` instead of a `HashSet` and `CharSequenceWrapper`. The `CharSequenceSet` embeds the wrapper and is easier to use, but this introduced a bug where multiple threads using the same `CharSequenceSet` would use the same seq wrapper in `contains`. This was causing deletes of specific files to miss data files if the wrapper was reused while testing a file that should be deleted was in the delete set.
The solution is to make `CharSequenceSet` thread safe by using a thread-local wrapper.
This only affects operations that delete specific files, which are mostly in tests. Spark deletes using an …
=> Make CharSequenceSet thread safe

site/docs/spark.md
This adds documentation for most of the supported Spark 3 SQL commands. It does not exhaustively cover Spark SQL. Instead, this attempts to demonstrate how Spark SQL uses Iceberg features.
=> Docs: Update spark.md for Spark 3

.gitignore, core/src/main/java/org/apache/iceberg/BaseSnapshot.java
Add a few items in gitignore;
For BaseSnapshot::cacheManifests, it code implies that deleteManifests will always be set. This change is just to explicitly set deleteManifests if it is null to increase code readability.
Tests: Existing UTs in Core. No need for new UTs.
=>  improve code readability

core/src/main/java/org/apache/iceberg/BaseMetastoreCatalog.java, core/src/main/java/org/apache/iceberg/TableMetadata.java, core/src/test/java/org/apache/iceberg/TestTables.java, hive/src/main/java/org/apache/iceberg/hive/HiveCatalog.java, hive/src/test/java/org/apache/iceberg/hive/HiveCreateReplaceTableTest.java, spark/src/test/java/org/apache/iceberg/spark/SparkTestBase.java, spark/src/test/java/org/apache/iceberg/spark/source/SimpleRecord.java, spark3/src/main/java/org/apache/iceberg/spark/source/SparkWriteBuilder.java, spark3/src/test/java/org/apache/iceberg/spark/SparkCatalogTestBase.java, spark3/src/test/java/org/apache/iceberg/spark/sql/TestAlterTable.java, spark3/src/test/java/org/apache/iceberg/spark/sql/TestCreateTable.java, spark3/src/test/java/org/apache/iceberg/spark/sql/TestCreateTableAsSelect.java, spark3/src/test/java/org/apache/iceberg/spark/sql/TestDeleteFrom.java, spark3/src/test/java/org/apache/iceberg/spark/sql/TestNamespaceSQL.java, spark3/src/test/java/org/apache/iceberg/spark/sql/TestPartitionedWrites.java, spark3/src/test/java/org/apache/iceberg/spark/sql/TestSelect.java, spark3/src/test/java/org/apache/iceberg/spark/sql/TestUnpartitionedWrites.java
This adds tests for Spark SQL operations.
The tests primarily focus on the way that query info is passed to Iceberg. This is not intended to be exhaustive for either ways to express changes as SQL or for what Iceberg supports. For example, this only tests updating an int column to long to validate that `TableChange.UpdateColumnType` is handled.
These tests have exposed a few bugs:
* The Spark session catalog doesn't support metadata tables because Spark validates the namespace independent of the catalog. We could add a suffix convention to make the metadata tables accessible, since many people will want to use this catalog. (The session catalog can delegate to Spark's v1 catalog, so this catalog can load any existing table as well as Iceberg from the same Hive namespace.)
* Spark has a …
=> Add Spark 3 SQL tests

spark/src/test/java/org/apache/iceberg/actions/TestRemoveOrphanFilesAction.java, spark/src/test/java/org/apache/iceberg/actions/TestRewriteDataFilesAction.java, spark/src/test/java/org/apache/iceberg/actions/TestRewriteManifestsAction.java, spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSourceHadoopTables.java, spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSourceHiveTables.java, spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSourceTablesBase.java, spark2/src/test/java/org/apache/iceberg/actions/TestRemoveOrphanFilesAction24.java, spark2/src/test/java/org/apache/iceberg/actions/TestRewriteDataFilesAction24.java, spark2/src/test/java/org/apache/iceberg/actions/TestRewriteManifestsAction24.java, spark2/src/test/java/org/apache/iceberg/spark/source/TestIcebergSourceHadoopTables24.java, spark2/src/test/java/org/apache/iceberg/spark/source/TestIcebergSourceHiveTables24.java, spark3/src/test/java/org/apache/iceberg/spark/actions/TestRemoveOrphanFilesAction3.java, spark3/src/test/java/org/apache/iceberg/spark/actions/TestRewriteDataFilesAction3.java, spark3/src/test/java/org/apache/iceberg/spark/actions/TestRewriteManifestsAction3.java, spark3/src/test/java/org/apache/iceberg/spark/source/TestIcebergSourceHadoopTables3.java, spark3/src/test/java/org/apache/iceberg/spark/source/TestIcebergSourceHiveTables3.java
When refactoring Spark support into modules for 2.4 and 3.0, any tests that used `SparkTableUtil` were moved to iceberg-spark2 to avoid needing Scala in the iceberg-spark3 module. Now that #1126 is finished, the tests need to be moved back to the common module and applied in both version-specific modules.
This makes the tests abstract and creates concrete test classes for both Spark versions.
=> Apply table import test suites to Spark 3

spark3/src/main/java/org/apache/iceberg/spark/RollbackStagedTable.java, spark3/src/main/java/org/apache/iceberg/spark/SparkSessionCatalog.java, spark3/src/test/java/org/apache/iceberg/spark/sql/TestCreateTableAsSelect.java
This adds support for atomic CTAS and RTAS commands when using SparkSessionCatalog in Spark 3.
If a TableCatalog in Spark 3 implements StagingTableCatalog, then all CTAS/RTAS operations will use the staging table methods, assuming that all tables in the catalog support the same capabilities. Iceberg tables support atomic operations, but tables loaded by the wrapped session catalog do not. The work-around is to mimic Spark's non-atomic behavior by creating a table immediately, using it for the write, and rolling back by dropping the table.
This PR doesn't contain new tests because the session catalog in Spark 3 does not work with v2 tables. It will always return a [`V1Table`](https://github.com/apache/spark/blob/v3.0.0/sql/core/src/main/scala/org/apache/spark/sql/execution/datasources/v2/V2 …
=> Support atomic CTAS and RTAS with SparkSessionCatalog

api/src/main/java/org/apache/iceberg/types/TypeUtil.java
This adds implementations of `select` and `selectNot` for structs. It also refactors `getProjectedIds` to return an immutable collection.
=> Add select and selectNot to TypeUtil for structs

build.gradle, spark-runtime/LICENSE, spark3-runtime/LICENSE
This adds a spark3 runtime Jar.
The LICENSE change is needed because ORC 1.6.3 added this dependency, which is now pulled into runtime Jars.
=> Add spark3-runtime config, fix LICENSE files in runtime Jars

site/docs/spark.md
This fixes the issues raised on #1172.
=> Fix typos in Spark docs

data/src/main/java/org/apache/iceberg/data/TableScanIterable.java, mr/src/main/java/org/apache/iceberg/mr/mapreduce/IcebergInputFormat.java, orc/src/main/java/org/apache/iceberg/orc/OrcValueReaders.java, spark/src/main/java/org/apache/iceberg/spark/data/SparkOrcValueReaders.java, spark/src/main/java/org/apache/iceberg/spark/source/RowDataReader.java
Fixes #1056 
cc: @rdsr Since you had worked on this initially
=> ORC: Use ConstantReader for identity partition columns

.gitignore
Spark tests run under `spark2` and `spark3` modules sometimes create the `spark-warehouse` directory. Previously we had a `.gitignore` rule for the `spark` module. This PR adds the same for `spark2` and `spark3` modules.
=> Add spark-warehouse directories under spark2 and spark3 modules to .gitignore

.gitignore, api/src/main/java/org/apache/iceberg/io/CloseableIterator.java, orc/src/main/java/org/apache/iceberg/orc/ORC.java, orc/src/main/java/org/apache/iceberg/orc/OrcBatchReader.java, orc/src/main/java/org/apache/iceberg/orc/OrcIterable.java, orc/src/main/java/org/apache/iceberg/orc/VectorizedRowBatchIterator.java, spark/src/main/java/org/apache/iceberg/spark/data/SparkOrcReader.java, spark/src/main/java/org/apache/iceberg/spark/data/SparkOrcValueReaders.java, spark/src/main/java/org/apache/iceberg/spark/data/vectorized/ConstantColumnVector.java, spark/src/main/java/org/apache/iceberg/spark/data/vectorized/IcebergArrowColumnVector.java, spark/src/main/java/org/apache/iceberg/spark/data/vectorized/VectorizedSparkOrcReaders.java, spark/src/main/java/org/apache/iceberg/spark/source/BaseDataReader.java, spark/src/main/java/org/apache/iceberg/spark/source/BatchDataReader.java, spark/src/main/java/org/apache/iceberg/spark/source/RowDataReader.java, spark/src/test/java/org/apache/iceberg/spark/data/TestHelpers.java, spark/src/test/java/org/apache/iceberg/spark/data/TestSparkOrcReader.java, spark/src/test/java/org/apache/iceberg/spark/source/TestIdentityPartitionData.java, spark/src/test/java/org/apache/iceberg/spark/source/TestPartitionValues.java, spark/src/test/java/org/apache/iceberg/spark/source/TestSparkReadProjection.java, spark2/src/jmh/java/org/apache/iceberg/spark/source/orc/IcebergSourceFlatORCDataReadBenchmark.java, spark2/src/jmh/java/org/apache/iceberg/spark/source/orc/IcebergSourceNestedORCDataReadBenchmark.java, spark2/src/main/java/org/apache/iceberg/spark/source/Reader.java, spark2/src/test/java/org/apache/iceberg/spark/source/TestFilteredScan.java, spark2/src/test/java/org/apache/iceberg/spark/source/TestIdentityPartitionData24.java, spark2/src/test/java/org/apache/iceberg/spark/source/TestPartitionValues24.java, spark3/src/main/java/org/apache/iceberg/spark/source/SparkBatchScan.java, spark3/src/test/java/org/apache/iceberg/spark/source/TestFilteredScan.java, spark3/src/test/java/org/apache/iceberg/spark/source/TestPartitionValues3.java
- Most of the new code is added in `VectorizedSparkOrcReaders`
- Replaced `NullValuesColumnVector` with `ConstantColumnVector` which can support any constant (including nulls)
- Moved the Iceberg to Spark constant conversion logic from `RowDataReader` into `BaseDataReader` so that it can be reused in `BatchDataReader`
- Modified many of the Spark read test cases to test for both vectorized and non vectorized codepaths
- Modified `TestFilteredScan` in Spark3 to use IcebergGenerics instead of Avro just like in Spark2. This enables use to test ORC reads/writes which do not have Avro GenericRecord writer.
Benchmark results:
Tests reads of 10 files with 5M records each
```
Benchmark                                                                          Mode  Cnt    Score    Error  Units …
```
=> Spark: Support ORC vectorized reads

spark3/src/main/java/org/apache/iceberg/spark/SparkCatalog.java
When testing 0.9.0 RC5, I found that when a table is created using CTAS and a USING clause to set a non-Parquet format, the format is ignored because unlike CREATE TABLE, the catalog method used by CTAS doesn't call `Spark3Util.rebuildCreateProperties` to set the table's default format from the USING clause.
=> Spark: Fix USING format with CTAS

flink/src/main/java/org/apache/iceberg/flink/FlinkSchemaUtil.java, flink/src/main/java/org/apache/iceberg/flink/FlinkTypeToType.java, flink/src/main/java/org/apache/iceberg/flink/FlinkTypeVisitor.java, flink/src/test/java/org/apache/iceberg/flink/TestFlinkSchemaUtil.java
This PR wants to improve https://github.com/apache/iceberg/pull/1096
Flink has `LogicalTypeVisitor` and `DataTypeVisitor`, they are very useful for visiting types. We don't implement a custom visitor based on `instanceOf`, it's error prone and not very elegant.
And for FieldsDataType, it not has a good design in 1.9 and 1.10, so in Flink 1.11, it has been refactored to be removed getFieldDataTypes. So I think maybe a LogicalTypeVisitor is enough, since we never touch the physical information in the DataTypes.
A `CollectionDataType` may be `MultisetType` too. We can map it to Map<T, Integer>.
=> FlinkTypeVisitor: Use LogicalTypeVisitor and supports MultisetType

core/src/main/java/org/apache/iceberg/hadoop/HadoopCatalog.java, core/src/test/java/org/apache/iceberg/hadoop/TestHadoopCatalog.java
In `HadoopCatalog.dropNamespace`, throws `RuntimeIOException("Namespace delete failed")` when Namespace is not empty, but according to `SupportsNamespaces.dropNamespace`, should throw `NamespaceNotEmptyException`.
Before delete, check `listStatus` first.
=> HadoopCatalog.dropNamespace throw NamespaceNotEmptyException when Namespace is not empty

.gitignore, spark/src/main/java/org/apache/iceberg/spark/data/vectorized/ConstantColumnVector.java, spark/src/main/java/org/apache/iceberg/spark/data/vectorized/VectorizedSparkOrcReaders.java, spark/src/test/java/org/apache/iceberg/spark/data/TestHelpers.java
Followup for https://github.com/apache/iceberg/pull/1189#discussion_r453125375
=> Spark: Remove unnecessary null checks from ORC vectorized readers

build.gradle
This implements option 4 from #1198. Each passing test case will be logged so that Travis CI gets updates that tests are still running.
=> Fix test timeout by logging tests that pass

flink/src/main/java/org/apache/iceberg/flink/FlinkSchemaUtil.java, flink/src/main/java/org/apache/iceberg/flink/TypeToFlinkType.java, flink/src/test/java/org/apache/iceberg/flink/TestFlinkSchemaUtil.java
Converter between Flink types and Iceberg type.
The conversion is not a 1:1 mapping that not allows back-and-forth conversion. So some information might get lost during the back-and-forth conversion.
(background: FlinkCatalog need convert iceberg tables to Flink tables)
=> Add TypeToFlinkType: convert iceberg types to Flink types

flink/src/main/java/org/apache/iceberg/flink/RowWrapper.java, flink/src/test/java/org/apache/iceberg/flink/TestPartitionKey.java, flink/src/test/java/org/apache/iceberg/flink/data/RandomData.java
This patch abstract the common codes of PartitionKey to the newly introduced class `BasePartitionKey`, and both spark `PartitionKey` and flink `PartitionKey` will extend this base class.  I also provide the unit tests for flink `PartitionKey`.
=> Flink: Add wrapper to adapt Row to StructLike

build.gradle
This is a followup on #1210
This change avoids printing the test name in non-CI environments to reduce noise in local builds
=> Gradle: Do not print test names in non-CI environments

core/src/main/java/org/apache/iceberg/CachingCatalog.java
This removes table expiration from cache in `CachingCatalog`. As long as a reference to a table exists, the cache should continue to use that reference so that writes update the table for all queries. The cache still uses soft values, so once other references are removed it can be garbage collected if memory is needed.
=> Remove table cache expiration

versions.props
This solve #1179
It is better to merge https://github.com/apache/iceberg/pull/1173 first. There are some conflicts.
=> Bump Flink to 1.11

core/src/main/java/org/apache/iceberg/MetadataColumns.java, data/src/main/java/org/apache/iceberg/data/TableScanIterable.java, data/src/main/java/org/apache/iceberg/data/orc/GenericOrcReader.java, data/src/main/java/org/apache/iceberg/data/orc/GenericOrcReaders.java, mr/src/main/java/org/apache/iceberg/mr/mapreduce/IcebergInputFormat.java, orc/src/main/java/org/apache/iceberg/orc/OrcBatchReader.java, orc/src/main/java/org/apache/iceberg/orc/OrcIterable.java, orc/src/main/java/org/apache/iceberg/orc/OrcRowReader.java, orc/src/main/java/org/apache/iceberg/orc/OrcValueReader.java, orc/src/main/java/org/apache/iceberg/orc/OrcValueReaders.java, orc/src/main/java/org/apache/iceberg/orc/VectorizedRowBatchIterator.java, spark/src/main/java/org/apache/iceberg/spark/data/SparkOrcReader.java, spark/src/main/java/org/apache/iceberg/spark/data/SparkOrcValueReaders.java, spark/src/main/java/org/apache/iceberg/spark/data/vectorized/RowPostitionColumnVector.java, spark/src/main/java/org/apache/iceberg/spark/data/vectorized/VectorizedSparkOrcReaders.java, spark/src/main/java/org/apache/iceberg/spark/source/RowDataReader.java, spark/src/test/java/org/apache/iceberg/spark/data/TestSparkOrcReadMetadataColumns.java
Completes a part of #1021
Adds support to output the row position within the file as a `_pos` column in the data record through ORC readers when the metadata column is provided in the expected schema 
Main changes:
- Add a `MetadataColumns` class to `iceberg-core` which will define the metadata columns supported by Iceberg
- Expose row batch offset in the file to `OrcValueReader`s so that the we can create a new ValueReader which returns the row position
- Add logic in the `StructReader` to check if a field is a metadata field and provide the correct reader for it
=> ORC: Support row position as a metadata column

api/src/test/java/org/apache/iceberg/AssertHelpers.java, build.gradle, flink/src/main/java/org/apache/iceberg/flink/FlinkCatalog.java, flink/src/main/java/org/apache/iceberg/flink/FlinkCatalogFactory.java, flink/src/main/resources/META-INF/services/org.apache.flink.table.factories.TableFactory, flink/src/test/java/org/apache/iceberg/flink/FlinkCatalogTestBase.java, flink/src/test/java/org/apache/iceberg/flink/FlinkTestBase.java, flink/src/test/java/org/apache/iceberg/flink/TestFlinkCatalogDatabase.java, flink/src/test/java/org/apache/iceberg/flink/TestFlinkCatalogTable.java, gradle/wrapper/gradle-wrapper.properties, versions.props
Like Spark 3, Flink also has Catalog interface, we can integrate Iceberg catalog to Flink catalog, iceberg as a Flink catalog, users can use Flink DDLs to manipulate iceberg metadata. And query iceberg tables directly.
The mapping between Flink database and Iceberg namespace:
- Supplying a base namespace for a given catalog, so if you have a catalog that supports a 2-level namespace, you would supply the first level in the catalog configuration and the second level would be exposed as Flink databases.
- The Iceberg table manages its partitions by itself. The partition of the Iceberg table is independent of the partition of Flink.
This PR solve https://github.com/apache/iceberg/issues/1170
This PR depends on:
- https://github.com/apache/iceberg/pull/1174
- …
=> Flink: Integrate Iceberg catalog to Flink catalog

site/docs/api.md, site/docs/javadoc/0.9.0/search.js, site/docs/reliability.md, tasks.gradle
This PR includes some minor fixes to the documentation site:
- Javadoc bug which makes the search form unusable - 
When using JDK 11 the Javadoc is generated using HTML 5 and has a search bar, due to a bug some of the links redirect to invalid locations, for example:
```
https://iceberg.apache.org/javadoc/0.9.0/undefined/org/apache/iceberg/Transaction.html
```
instead of:
```
https://iceberg.apache.org/javadoc/0.9.0/org/apache/iceberg/Transaction.html
```
The bug was fixed manually for version 0.9.0 and for future release I have modified the gradle task to make the necessary changes according to the solution suggested [here](https://stackoverflow.com/questions/52326318/maven-javadoc-search-redirects-to-undefined-url/52603413#52603413).
- Java API page changes:
- Adding documentation for …
=> Site: Fixes

python/iceberg/api/partition_spec.py, python/iceberg/api/types/type_util.py, python/iceberg/core/filesystem/local_filesystem.py, python/iceberg/core/table_metadata.py, python/tests/api/expressions/conftest.py, python/tests/api/test_helpers.py, python/tests/core/conftest.py, python/tests/hive/test_hive_tables.py
In the course of implementing create table I came across minor issues:
* rename test fixtures to suppress warnings and prevent pytest from treating them as tests
* test partition code path & fix incorrect signature when creating metadata
* handle `file:` as well as `file://` as it seems both schemas are used
* add mypy annotations in areas where I fixed code
* fix tox/mypy
=> [Python] Minor fixes for tests

hive/src/test/java/org/apache/iceberg/hive/TestHiveTableConcurrency.java
In my local env, this test testConcurrentConnections fails with a timeout.   
```
org.apache.iceberg.hive.TestHiveTableConcurrency > testConcurrentConnections FAILED
java.lang.AssertionError: Timeout
at org.junit.Assert.fail(Assert.java:88)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.apache.iceberg.hive.TestHiveTableConcurrency.testConcurrentConnections(TestHiveTableConcurrency.java:106)
```
Increasing the timeout to 3 min fixes this.   
Fixes #1225
=> Fix TestHiveTableConcurrency test failure: Increase the timeout to 3min

core/src/main/java/org/apache/iceberg/hadoop/Util.java, spark/src/main/java/org/apache/iceberg/spark/SparkTableUtil.java, spark2/src/test/java/org/apache/iceberg/spark/source/TestSparkTableUtil.java
More info at apache/iceberg#1224 
Previously the listPartition method would use a string representation
of the Partition's URI when creating the Hadoop Path. This constructor would
handle the string as the literal input for the path and ignore any encoded
characters. This casues an issue if the directory or filename has whitespace
or some other special character being reported as it's encoded version
resulting in FNF exceptions. By switching to passing a URI as
the SparkPartition's location uri, the escaped characters are correctly handled
by the Hadoop Path class..
=> Fix Handling of SparkPartitions with Whitepsace in Location

core/src/main/java/org/apache/iceberg/avro/AvroIO.java, core/src/main/java/org/apache/iceberg/avro/AvroIterable.java, core/src/main/java/org/apache/iceberg/avro/BuildAvroProjection.java, core/src/main/java/org/apache/iceberg/avro/ProjectionDatumReader.java, core/src/main/java/org/apache/iceberg/avro/SupportsRowPosition.java, core/src/main/java/org/apache/iceberg/avro/ValueReaders.java, core/src/main/java/org/apache/iceberg/data/avro/DataReader.java, core/src/test/java/org/apache/iceberg/avro/TestAvroFileSplit.java
This adds an Avro `ValueReader` that returns the position of a row within a file.
The position reader's initial position is set from a callback that returns the starting row position of the split that is being read. The callback is passed to classes that implement a new interface, `SupportsRowPosition`. This uses a callback so that if there is no position reader, the starting row position does not need to be calculated, which is expensive.
Finding the row position at the start of a split requires scanning through an Avro file stream. `AvroIO` now includes a utility method that keeps track of the number of rows in each Avro block and seeks past the block content until the next block is after the given split starting point. This validates Avro sync bytes to ensure the count is accurate. …
=> Add Avro row position reader

mr/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergInputFormat.java
Fix typo in `TestHiveIcebergInputFormat.testScanTable`, which was spotted by @HotSushi in #1192.
=> Fix TestHiveIcebergInputFormat.testScanTable

core/src/main/java/org/apache/iceberg/SnapshotSummary.java, site/docs/configuration.md, spark/src/test/java/org/apache/iceberg/spark/source/TestDataSourceOptions.java, spark2/src/main/java/org/apache/iceberg/spark/source/Writer.java, spark3/src/main/java/org/apache/iceberg/spark/source/SparkBatchWrite.java
Plumbing to add extra custom metadata to snapshot summary via write options https://github.com/apache/iceberg/issues/1242
Context: At Stripe we make use of airflow to run spark jobs, and want to pass a separate external ID and some versioning information linking an airflow run for each snapshot created. Currently to do this, we have to fork the Writer just to override the commitOperation. 
The changes in this PR would allow custom metadata via write options which start with a particular prefix (`extra-metadata.`). 
cc? @rdblue
=> Plumbing to add extra custom metadata to snapshot summary

core/src/main/java/org/apache/iceberg/BaseFile.java
When building the project for the first time, the compiler warns that there are several places that are missing overrides.
I've discussed the issue here: https://github.com/apache/iceberg/issues/1248
I have taken a shot at removing these warnings and adding the `@Override` annotation to non-abstract methods in `BaseFile` from the `iceberg-core` module. There are more warnings than just this one file, but I wanted to keep the workload light in this first PR in case the missing Overrides were intentional (in which case we might consider the use of `@SuppressWarnings`).
As I'm relatively new to the project, I'd love any feedback possible. I'm tagging @openinx as I've recently commented on their PR's.
=> Fix missing Override warnings in org.apache.iceberg.BaseFile

mr/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergOutputFormat.java, mr/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
As suggested by @massdosage and @pvary, add HiveIcebergOutputFormat placeholder that throws `UnsupportedOperationException` when `getRecordWriter` is called.
@massdosage @pvary @rdsr
=> Add HiveIcebergOutputFormat placeholder

mr/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergInputFormat.java, mr/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergSerDe.java, mr/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java, mr/src/main/java/org/apache/iceberg/mr/hive/TableResolver.java, mr/src/main/java/org/apache/iceberg/mr/hive/serde/objectinspector/IcebergBinaryObjectInspector.java, mr/src/main/java/org/apache/iceberg/mr/hive/serde/objectinspector/IcebergDateObjectInspector.java, mr/src/main/java/org/apache/iceberg/mr/hive/serde/objectinspector/IcebergDecimalObjectInspector.java, mr/src/main/java/org/apache/iceberg/mr/hive/serde/objectinspector/IcebergObjectInspector.java, mr/src/main/java/org/apache/iceberg/mr/hive/serde/objectinspector/IcebergRecordObjectInspector.java, mr/src/main/java/org/apache/iceberg/mr/hive/serde/objectinspector/IcebergTimestampObjectInspector.java, mr/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergSerDe.java, mr/src/test/java/org/apache/iceberg/mr/hive/TestTableResolver.java, mr/src/test/java/org/apache/iceberg/mr/hive/serde/objectinspector/TestIcebergBinaryObjectInspector.java, mr/src/test/java/org/apache/iceberg/mr/hive/serde/objectinspector/TestIcebergDateObjectInspector.java, mr/src/test/java/org/apache/iceberg/mr/hive/serde/objectinspector/TestIcebergDecimalObjectInspector.java, mr/src/test/java/org/apache/iceberg/mr/hive/serde/objectinspector/TestIcebergObjectInspector.java, mr/src/test/java/org/apache/iceberg/mr/hive/serde/objectinspector/TestIcebergRecordObjectInspector.java, mr/src/test/java/org/apache/iceberg/mr/hive/serde/objectinspector/TestIcebergTimestampObjectInspector.java
This PR moves Hive-related classes to the `*.mr.hive` package and renames the `IcebergSerDe` class to `HiveIcebergSerDe` for consistency.
@massdosage @rdsr
=> Move Hive-related classes to mr.hive package

site/docs/spark.md
Spark has different approaches to handle multi-part name, between default catalog (spark_catalog) and custom catalog. While the metadata table format for inspection (catalog.database.table.metadata) works for custom catalog, it does not work for default catalog, as of Spark 3.0.0.
This patch documents the limitation so that end users can understand and take a workaround.
Screenshot (change emphasized by red box):
=> Spark: mention the limitation of "default catalog" on Spark 3.0 for inspecting table

hive/src/main/java/org/apache/iceberg/hive/HiveCatalog.java, hive/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java, hive/src/test/java/org/apache/iceberg/hive/HiveTableBaseTest.java, hive/src/test/java/org/apache/iceberg/hive/HiveTableTest.java
Pull request for issue for issue #954 
- Fixes HiveCatalog.defaultWarehouseLocation method
- Creates a test for it
- A simple formatting fix
- Moves an unnecessary SD conversion
=> Default warehouse location of a table should be a subdirectory in database location

core/src/main/java/org/apache/iceberg/GenericDataFile.java, core/src/main/java/org/apache/iceberg/GenericDeleteFile.java, parquet/src/main/java/org/apache/iceberg/parquet/PageIterator.java, spark/src/main/java/org/apache/iceberg/spark/source/BaseDataReader.java, spark3/src/main/java/org/apache/iceberg/spark/source/SparkBatchWrite.java
This adds in the missing Override annotations according to Error Prone when running `./gradlew clean && ./gradlew build`. It also closes out https://github.com/apache/iceberg/issues/1248 for the time being, until somebody merges in something that's missing an Override annotation 🙃. 
There are still a few Error Prone warnings that I'd like to fix, but I'm wondering if we'd like to possibly add an additional blocking check on PRs for specific error prone warnings / errors. These missing override annotations are relatively benign, but some of the other warnings that I'm going through to clean up include potentially lossy conversions, e.g. [NarrowingCompoundAssignment](https://errorprone.info/bugpattern/NarrowingCompoundAssignment), on what appear to be relatively important fields as well as …
=> Add in missing Override annotations according to Error Prone

api/src/main/java/org/apache/iceberg/ExpireSnapshots.java, core/src/main/java/org/apache/iceberg/RemoveSnapshots.java, core/src/test/java/org/apache/iceberg/TestRemoveSnapshots.java
This PR aims to support https://github.com/apache/iceberg/issues/1178
By default execution of delete tasks of metadata and data files is single threaded.
=> Add support to parallelise the execution of tasks of metadata and data files delete operations

core/src/main/java/org/apache/iceberg/MicroBatches.java, core/src/test/java/org/apache/iceberg/TestMicroBatchBuilder.java
This PR is separated out from #796 to support streaming read of Iceberg table. The main purpose of adding `MicroBatch` is to get the size limited batch in `Snapshot`, which can be used by streaming read either for Spark or Flink.
=> Add MicroBatch support in Iceberg Core

site/docs/getting-started.md
Minor typo fix to the conf property name in the getting started guide. 
Change spark.sql.catalog.local.uri to spark.sql.catalog.local.warehouse
=> Fix the conf property name in docs

spark/src/main/java/org/apache/iceberg/spark/SparkSchemaUtil.java, spark/src/test/java/org/apache/iceberg/spark/TestSparkSchemaUtil.java, spark2/src/main/java/org/apache/iceberg/spark/source/Reader.java, spark3/src/main/java/org/apache/iceberg/spark/source/SparkBatchScan.java
…tistics call
https://github.com/apache/iceberg/issues/1220
this commits add support for table property "read.spark.use-approximate-statistics"
which returns table statistics based on table rows and approximate row size and avoid reading manifest and data files
to get table size and row count.
this feature is useful for spark2 as spark2 does not perform predicate pushdown before calling
estimateStatistics which ends up scanning entire table.
this feature may be useful for spark3 if table manifest list is large even after predicate pushdown.
=> Spark: Fix estimateStatistics when called without filters

api/src/main/java/org/apache/iceberg/ExpireSnapshots.java, core/src/main/java/org/apache/iceberg/RemoveSnapshots.java, core/src/test/java/org/apache/iceberg/TestRemoveSnapshots.java
Previously ExpireSnapshots would always follow the expiration of Snapshots
with a deletion of local DataFiles and Manifests which were no longer relevant
to the Table. This patch introduces an API to skip this deletion phase, which
was always run locally, and instead just expire the snapshots. This allows for
future implementations which can read and remove unused files in parallel or
on distributed frameworks.
=> Allow ExpireSnapshots to run without Deleting Files

data/src/main/java/org/apache/iceberg/data/IcebergGenerics.java, data/src/test/java/org/apache/iceberg/data/TestLocalScan.java
Currently, `IcebergGenerics.ScanBuilder` doesn't support incremental scan,  this adds the incremental scan support to the iceberg generic scan builder.
=> Add incremental scan for iceberg generics scan builder

core/src/main/java/org/apache/iceberg/avro/ValueWriters.java, core/src/main/java/org/apache/iceberg/util/DecimalUtil.java, parquet/src/main/java/org/apache/iceberg/parquet/ParquetValueWriters.java, spark/src/main/java/org/apache/iceberg/spark/data/SparkParquetWriters.java, spark/src/main/java/org/apache/iceberg/spark/data/SparkValueWriters.java
Introduce DecimalUtil to convert BigDecimal to reused fix length bytes for:
- `ValueWriters`
- `ParquetValueWriters`
- `SparkValueWriters`
- `SparkParqueWriters`
=> Introduce DecimalUtil to convert BigDecimal to reused fix length bytes

data/src/main/java/org/apache/iceberg/data/parquet/BaseParquetReaders.java, parquet/src/main/java/org/apache/iceberg/parquet/BaseColumnIterator.java, parquet/src/main/java/org/apache/iceberg/parquet/ParquetReader.java, parquet/src/main/java/org/apache/iceberg/parquet/ParquetValueReader.java, parquet/src/main/java/org/apache/iceberg/parquet/ParquetValueReaders.java, parquet/src/main/java/org/apache/iceberg/parquet/ReadConf.java, spark/src/main/java/org/apache/iceberg/spark/data/SparkParquetReaders.java, spark/src/test/java/org/apache/iceberg/spark/data/TestSparkParquetReadMetadataColumns.java
This adds position reader for parquet readers. 
TODO:
1. Add row position reader for the vectorized reader.
=> Parquet: Add row position reader

build.gradle, mr/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergSerDe.java, mr/src/main/java/org/apache/iceberg/mr/hive/TableResolver.java
I was receiving the following exception when running Hive MR tests from my IDE
```
java.lang.NoSuchMethodError: org.apache.parquet.schema.Types$PrimitiveBuilder.as(Lorg/apache/parquet/schema/LogicalTypeAnnotation;)Lorg/apache/parquet/schema/Types$Builder;
at org.apache.iceberg.parquet.TypeToMessageType.primitive(TypeToMessageType.java:145)
at org.apache.iceberg.parquet.TypeToMessageType.field(TypeToMessageType.java:88)
at org.apache.iceberg.parquet.TypeToMessageType.convert(TypeToMessageType.java:65)
at org.apache.iceberg.parquet.ParquetSchemaUtil.convert(ParquetSchemaUtil.java:41)
at org.apache.iceberg.parquet.Parquet$WriteBuilder.build(Parquet.java:210)
at org.apache.iceberg.mr.TestHelper.writeFile(TestHelper.java:163)
at org.apache.iceberg.mr.TestHelper.writeFile(TestHelper.java:140) …
```
=> Remove conflicting dependency and unnecessary checked exception

.baseline/checkstyle/checkstyle.xml, core/src/main/java/org/apache/iceberg/hadoop/HadoopInputFile.java
This can cause the Spark 3 runtime Jar to fail because the Lists class is missing.
Closes #1274, which has the same fix but not the checkstyle update.
Co-authored-by: Chen, Junjie <chenjunjiedada@gmail.com>
=> Ban imports from org.apache.commons.compress.utils

api/src/main/java/org/apache/iceberg/expressions/BoundLiteralPredicate.java, api/src/main/java/org/apache/iceberg/expressions/BoundUnaryPredicate.java, api/src/test/java/org/apache/iceberg/expressions/TestExpressionHelpers.java
When `in` and `notIn` predicates were added, the `negate` method was left out of the refactor that split `BoundPredicate` into `BoundLiteralPredicate`, `BoundUnaryPredicate` and `BoundSetPredicate`. This prevents operations that call `rewriteNot` from rewriting most expressions that contain not.
This doesn't affect simple scans, but will cause moderately complicated workflows to fail in query planning.
=> Implement negate in bound predicates

spark3/src/main/java/org/apache/iceberg/spark/Spark3Util.java
Building query plans will fail when IN predicates are present.
=> Fix Spark 3 describe with IN predicates

spark3/src/main/java/org/apache/iceberg/spark/SparkSessionCatalog.java
If end users provide SparkSessionCatalog when defining non-default catalog (other than `spark_catalog`), Iceberg will throw NPE in runtime without proper message explaining what is misconfigured. This patch provides better error message on such case.
=> Spark: Provide better error message on using SparkSessionCatalog without replacing default spark catalog

arrow/src/main/java/org/apache/iceberg/arrow/vectorized/VectorHolder.java, arrow/src/main/java/org/apache/iceberg/arrow/vectorized/VectorizedArrowReader.java, spark/src/main/java/org/apache/iceberg/spark/data/vectorized/IcebergArrowColumnVector.java, spark/src/main/java/org/apache/iceberg/spark/data/vectorized/VectorizedSparkParquetReaders.java, spark/src/main/java/org/apache/iceberg/spark/source/BatchDataReader.java, spark/src/test/java/org/apache/iceberg/spark/source/TestIdentityPartitionData.java, spark2/src/main/java/org/apache/iceberg/spark/source/Reader.java
Previously vectorization would be disabled whenever an underlying iceberg table
was using Parquet files and also used Identity transforms in it's partitioning.
To fix this we extend the DummyVectorReader to be a ConstantVectorReader which is
used when a column's value can be determined from the PartitionSpec. Then when
constructing the reader we use a ConstantColumnVector to fill in the missing
column.
=> Vectorized Reads of Parquet with Identity Partitions

api/src/main/java/org/apache/iceberg/FileScanTask.java, api/src/main/java/org/apache/iceberg/PartitionSpec.java, core/src/main/java/org/apache/iceberg/AllManifestsTable.java, core/src/main/java/org/apache/iceberg/BaseFileScanTask.java, core/src/main/java/org/apache/iceberg/DataFilesTable.java, core/src/main/java/org/apache/iceberg/DataTableScan.java, core/src/main/java/org/apache/iceberg/DeleteFileIndex.java, core/src/main/java/org/apache/iceberg/GenericManifestEntry.java, core/src/main/java/org/apache/iceberg/ManifestEntriesTable.java, core/src/main/java/org/apache/iceberg/ManifestGroup.java, core/src/main/java/org/apache/iceberg/StaticDataTask.java, core/src/test/java/org/apache/iceberg/MockFileScanTask.java, core/src/test/java/org/apache/iceberg/TestDeleteFileIndex.java
This adds `DeleteFileIndex` to scan delete manifests and index delete files, updates `ManifestGroup` to use the index when planning tasks, and adds delete files to `FileScanTask`.
The `DeleteFileIndex` uses a map keyed by partition spec ID and partition tuple. Values of the map are sorted list of sequence numbers and corresponding `DeleteFile` instances. When looking up a `DataFile`, the potentially matching delete files are fetched using its partition tuple, then the sequence numbers are binary searched to find the matching set of delete files with sequence numbers higher than the data file.
The index also supports global equality delete files. If an equality delete file is added to the table with an unpartitioned spec, it will be returned for all data files with a lower sequence number, …
=> Update scan planning with DeleteFiles in each task

flink/src/main/java/org/apache/iceberg/flink/FlinkTypeVisitor.java, flink/src/main/java/org/apache/iceberg/flink/TaskWriterFactory.java, flink/src/main/java/org/apache/iceberg/flink/data/AvroWithFlinkSchemaVisitor.java, flink/src/main/java/org/apache/iceberg/flink/data/FlinkAvroReader.java, flink/src/main/java/org/apache/iceberg/flink/data/FlinkAvroWriter.java, flink/src/main/java/org/apache/iceberg/flink/data/FlinkValueReaders.java, flink/src/main/java/org/apache/iceberg/flink/data/FlinkValueWriters.java, flink/src/test/java/org/apache/iceberg/flink/FlinkTestBase.java, flink/src/test/java/org/apache/iceberg/flink/TestTaskWriters.java, flink/src/test/java/org/apache/iceberg/flink/data/TestFlinkAvroReaderWriter.java, flink/src/test/java/org/apache/iceberg/flink/data/TestRowProjection.java
=> Flink: Using RowData to avro reader and writer

core/src/main/java/org/apache/iceberg/deletes/Deletes.java, core/src/main/java/org/apache/iceberg/util/Filter.java, core/src/main/java/org/apache/iceberg/util/FilterIterator.java, core/src/main/java/org/apache/iceberg/util/SortedMerge.java, core/src/test/java/org/apache/iceberg/deletes/TestPositionFilter.java
This adds a position delete row filter and helpers for constructing a row filter that will filter deletes to a specific data file and merge deletes from multiple delete files. These utilities are written using `CloseableIterable` and handle file closing.
=> Add position delete filter and utils

spark/src/main/java/org/apache/iceberg/spark/data/SparkOrcValueWriter.java, spark/src/main/java/org/apache/iceberg/spark/data/SparkOrcValueWriters.java, spark/src/main/java/org/apache/iceberg/spark/data/SparkOrcWriter.java, spark/src/main/java/org/apache/iceberg/spark/source/SparkAppenderFactory.java, spark/src/test/java/org/apache/iceberg/spark/data/TestOrcWrite.java, spark/src/test/java/org/apache/iceberg/spark/data/TestSparkOrcReadMetadataColumns.java, spark/src/test/java/org/apache/iceberg/spark/data/TestSparkOrcReader.java
This patch addressed the issues from https://github.com/apache/iceberg/issues/1236.  Once patch ~~https://github.com/apache/iceberg/pull/1197~~  get merged, I will do a git-rebase and it will only remain the spark orc writer changes.
=> Refactor the SparkOrcWriter by using OrcSchemaWithTypeVisitor#visit

build.gradle, data/src/main/java/org/apache/iceberg/data/orc/GenericOrcWriter.java, data/src/main/java/org/apache/iceberg/data/orc/GenericOrcWriters.java, spark/src/main/java/org/apache/iceberg/spark/data/SparkOrcValueReaders.java, spark/src/main/java/org/apache/iceberg/spark/data/SparkOrcValueWriters.java, spark/src/test/java/org/apache/iceberg/spark/data/GenericsHelpers.java, spark/src/test/java/org/apache/iceberg/spark/data/TestSparkRecordOrcReaderWriter.java
This PR addressed the bug in https://github.com/apache/iceberg/issues/1269,  it mainly fixed the two sub-issues: 
1.  when writing a Decimal (precision<=18) into hive orc file,  the orc writer will scale down the decimal. for example,  we have a value  10.100  for type `Decimal(10, 3)`,  the hive orc will remove all the trailing zero and store it as 101*10^(-1), mean precision is 3 and scale is 1.  Here the scale of decimal read from hive orc file, is not strictly equal to 3.  so for both spark orc reader and generic orc reader we need to transform it to the given scale =3 .  Otherwise, the unit test will be broken. 
2. The long value of zoned timestamp can be negative,  while we spark orc reader/writer did not consider this case, and just use the  `/`  and `%` to do the arithmetic …
=> Align the records written by GenericOrcWriter and SparkOrcWriter

.baseline/checkstyle/checkstyle.xml, spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSourceHiveTables.java, spark2/src/main/java/org/apache/iceberg/spark/source/Reader.java, spark2/src/test/java/org/apache/iceberg/examples/ConcurrencyTest.java, spark2/src/test/java/org/apache/iceberg/examples/ReadAndWriteTablesTest.java, spark2/src/test/java/org/apache/iceberg/examples/SchemaEvolutionTest.java, spark2/src/test/java/org/apache/iceberg/examples/SnapshotFunctionalityTest.java, spark3/src/main/java/org/apache/iceberg/spark/SparkCatalog.java, spark3/src/main/java/org/apache/iceberg/spark/source/IcebergSource.java
We have to use `SessionState` to get a complete Hadoop conf. It is legal to set Hadoop properties directly without the `spark.hadoop` prefix. If we use `SparkContext` directly, we will miss such properties.
=> Spark: Use SessionState to load Hadoop config

spark3/src/main/java/org/apache/iceberg/spark/source/SparkBatchScan.java
Support for Parquet vectorized reads with identity partition values was added in https://github.com/apache/iceberg/pull/1287 but the Spark3 read path was missed. This PR also enables vectorized reads for such tables in Spark3. The test case added in #1287 also runs for Spark3 and should test this change.
cc: @RussellSpitzer
=> Spark3: Enable Parquet vectorized reads with identity partition values

core/src/main/java/org/apache/iceberg/PartitionsTable.java, spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSourceTablesBase.java
Querying the partitions table in Spark when a table is unpartitioned causes Spark to fail because the partition struct is empty.
=> Fix partitions metadata table for unpartitioned tables

spark/src/test/java/org/apache/iceberg/SerializationCheckHelper.java, spark/src/test/java/org/apache/iceberg/TaskCheckHelper.java, spark/src/test/java/org/apache/iceberg/TestDataFileSerialization.java, spark/src/test/java/org/apache/iceberg/TestScanTaskSerialization.java
This patch refactors to deduplicate the code:
* Comparing BaseCombinedScanTask needs compare of DataFile, which we already have the method for this, but in other test suite. I created a new helper class to move out comparison methods so that they can be co-used.
=> Spark: refactor serialization test suites

api/src/main/java/org/apache/iceberg/types/Comparators.java, api/src/main/java/org/apache/iceberg/types/JavaHash.java, api/src/main/java/org/apache/iceberg/types/JavaHashes.java, api/src/main/java/org/apache/iceberg/util/CharSequenceWrapper.java, core/src/main/java/org/apache/iceberg/PartitionsTable.java, core/src/main/java/org/apache/iceberg/util/PartitionSet.java, core/src/main/java/org/apache/iceberg/util/StructLikeSet.java, core/src/main/java/org/apache/iceberg/util/StructLikeWrapper.java, spark/src/main/java/org/apache/iceberg/actions/RewriteDataFilesAction.java
`StructLikeWrapper` is used to provide `equals` and `hashCode` methods that are consistent across all `StructLike` implementations. But, the implementation did not handle different implementations of `CharSequence` correctly. This fixes the implementations by adding a `Comparator` implementation for structs, and adding classes to implement Java's `hashCode`. These implementations depend on the Iceberg type of an object.
The type of a struct is not always passed to `StructLikeWrapper`, so this includes a temporary work-around to use the existing implementation for code paths that do not currently have a struct's type.
This also adds two helper classes, `StructLikeSet` and `PartitionSet`. The struct set hides `StructLikeWrapper` from callers and is based on `CharSequenceSet`. `PartitionSet` …
=> Fix struct comparison and add struct and partition set implementations

api/src/main/java/org/apache/iceberg/ExpireSnapshots.java, core/src/main/java/org/apache/iceberg/RemoveSnapshots.java, core/src/test/java/org/apache/iceberg/TestRemoveSnapshots.java
The executor passed in executeWith is only used for deletes so we will rename it
to executeDeleteWith. The JavaDoc already states it will only effect deletes and
the implementation already match this name so no other changes are needed.
cc @rdblue  + @aokolnychyi  Just a rename refactor as we discussed in https://github.com/apache/iceberg/pull/1264
=> ExpireSnapshots executeWith renamed executeDeleteWith

api/src/main/java/org/apache/iceberg/ContentFile.java, api/src/test/java/org/apache/iceberg/TestHelpers.java, core/src/main/java/org/apache/iceberg/AllManifestsTable.java, core/src/main/java/org/apache/iceberg/BaseFile.java, core/src/main/java/org/apache/iceberg/DataFiles.java, core/src/main/java/org/apache/iceberg/FileMetadata.java, core/src/main/java/org/apache/iceberg/GenericDataFile.java, core/src/main/java/org/apache/iceberg/GenericDeleteFile.java, core/src/main/java/org/apache/iceberg/InheritableMetadataFactory.java, core/src/main/java/org/apache/iceberg/StaticDataTask.java, core/src/main/java/org/apache/iceberg/V1Metadata.java, core/src/main/java/org/apache/iceberg/V2Metadata.java, core/src/test/java/org/apache/iceberg/TestManifestWriterVersions.java, core/src/test/java/org/apache/iceberg/TestMergeAppend.java, core/src/test/java/org/apache/iceberg/TestRewriteManifests.java, data/src/test/java/org/apache/iceberg/data/TestLocalScan.java, spark/src/main/java/org/apache/iceberg/spark/SparkDataFile.java, spark/src/test/java/org/apache/iceberg/spark/source/TestPartitionValues.java
Utilities that compare partitions need to also track the partition spec that a partition tuple belongs to because the same set of partition values can be valid for multiple specs, but identify different partitions. Many classes track the partitions of data and delete files, and the easiest way to update those utilities is to pass the spec ID along with the `DataFile` instance. Otherwise, getting the correct spec ID would require updating several public APIs to add a spec ID argument.
This PR adds spec ID to `DataFile` and `DeleteFile`, and adds it to metadata that is inherited from `ManifestFile`, where the spec ID of a manifest is tracked.
This also cleans up unnecessary factory methods in `DataFile` that were used only in tests and were missing spec ID. Now, all data file creation uses …
=> Add specId to DataFile

api/src/main/java/org/apache/iceberg/types/Comparators.java, api/src/test/java/org/apache/iceberg/TestHelpers.java, core/src/main/java/org/apache/iceberg/deletes/Deletes.java, core/src/test/java/org/apache/iceberg/deletes/TestEqualityFilter.java, core/src/test/java/org/apache/iceberg/deletes/TestPositionFilter.java
This adds set-based filter implementations for equality and position deletes. Equality deletes use the `StructLikeSet` added in #1307.
=> Add set-based equality and position filters

data/src/main/java/org/apache/iceberg/data/parquet/BaseParquetReaders.java, parquet/src/main/java/org/apache/iceberg/parquet/MessageTypeToType.java, spark/src/test/java/org/apache/iceberg/spark/data/TestSparkParquetReader.java
Fixes https://github.com/apache/iceberg/issues/1138#issuecomment-670717050 by making sure that we can convert from `org.apache.parquet.schema.MessageType` to `org.apache.iceberg.types.Type`.
The issue was occurring due to Iceberg not being able to map the `int96` type to an Iceberg Timestamp. Also added an end to end test to verify that we can read through Iceberg API the imported parquet file.
While doing this, I noticed that the Iceberg generic parquet reader was reading the timestamp as timestamp without timezone instead of a timestamp with timezone.
Improved our current unit-test to handle this issue
to: @rdblue 
cc: @thesquelched @aokolnychyi
=> End to end read support for int96 parquet timestamps

core/src/main/java/org/apache/iceberg/BaseReplacePartitions.java, core/src/main/java/org/apache/iceberg/DeleteFileIndex.java, core/src/main/java/org/apache/iceberg/ManifestFilterManager.java, core/src/main/java/org/apache/iceberg/ManifestGroup.java, core/src/main/java/org/apache/iceberg/MergingSnapshotProducer.java, core/src/main/java/org/apache/iceberg/SnapshotManager.java, core/src/main/java/org/apache/iceberg/util/ManifestFileUtil.java, core/src/main/java/org/apache/iceberg/util/StructLikeWrapper.java, core/src/test/java/org/apache/iceberg/TestDeleteFileIndex.java
This PR updates classes that use `StructLikeWrapper` to correctly track partitions using both ID and tuple, using `DataFile.specId` from #1317 and `PartitionSet` added by #1307.
This is needed to correctly track partitions because tuples can be valid for more than one spec. For example, `(12974)` is a valid partition for both `hours(ts)` and `days(ts)` partition specs, but does not represent the same logical partition in both.
=> Fix partition sets

api/src/main/java/org/apache/iceberg/ContentFile.java, api/src/main/java/org/apache/iceberg/DataFile.java, core/src/main/java/org/apache/iceberg/BaseFile.java, core/src/main/java/org/apache/iceberg/FileMetadata.java, core/src/main/java/org/apache/iceberg/GenericDataFile.java, core/src/main/java/org/apache/iceberg/GenericDeleteFile.java, core/src/main/java/org/apache/iceberg/V2Metadata.java, core/src/main/java/org/apache/iceberg/util/ArrayUtil.java, core/src/test/java/org/apache/iceberg/TestManifestWriterVersions.java, core/src/test/java/org/apache/iceberg/TestMergeAppend.java
This adds a list of equality field IDs to `DeleteFile` metadata that is tracked in manifests.
The equality field ID list identifies the subset of a delete file's fields (by ID) that should be used when comparing rows against the rows deleted in an equality delete file. The remaining fields are informational and store the values that were deleted by an equality delete. These may be used, for example, to reconstruct CDC events that contained deleted row values.
Additional fields will also be used for min/max stats filtering and are required to be accurate. When finding files for a table scan, the min/max values for non-comparison columns can still be used to filter delete files, even if the delete file applies to a data file that will be read.
For example, if a table contains columns `id` …
=> Add equality field IDs to DeleteFile

spark3/src/main/java/org/apache/iceberg/spark/Spark3Util.java, spark3/src/test/java/org/apache/iceberg/spark/sql/TestAlterTable.java
Fixes https://github.com/apache/iceberg/issues/1324
- Throw error when adding a required column using the Alter table DDL 
- Added a new unit test to verify this scenario
With the fix, 
```
scala> spark.sql("CREATE TABLE local.t1 (id int COMMENT 'unique id', data string not null) USING iceberg")
res0: org.apache.spark.sql.DataFrame = []
scala> spark.sql("ALTER TABLE local.t1 ADD COLUMN time int NOT NULL")
org.apache.spark.SparkException: Unsupported table change: Incompatible change: cannot add required column: time
at org.apache.spark.sql.execution.datasources.v2.AlterTableExec.run(AlterTableExec.scala:40)
at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.result$lzycompute(V2CommandExec.scala:39)
at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.result(V2CommandE …
```
=> Throw error when adding non-null columns using the alter table ddl

core/src/main/java/org/apache/iceberg/avro/PruneColumns.java, core/src/test/java/org/apache/iceberg/avro/TestAvroNameMapping.java, core/src/test/java/org/apache/iceberg/avro/TestAvroReadProjection.java
Added a unit test which fails without the change
-----
Consider type `map(long, list<long>)` (a logical-map array in Iceberg-Avro) and a full projection.
In `GetProjectedIds::map`, the key id and value id won't be added if the value type is nested.
```java
public Set<Integer> map(Types.MapType map, Set<Integer> keyResult, Set<Integer> valueResult) {
if (valueResult == null) {
for (Types.NestedField field : map.fields()) {
fieldIds.add(field.fieldId());
}
}
return fieldIds;
}
```
Missing the key id can pose a problem in `PruneColumns::array`, since the array's child record's key field will be omitted.
=> Avro: Fix pruning columns when a logical-map array's value type is nested

orc/src/main/java/org/apache/iceberg/orc/ApplyNameMapping.java, orc/src/main/java/org/apache/iceberg/orc/HasIds.java, orc/src/main/java/org/apache/iceberg/orc/ORC.java, orc/src/main/java/org/apache/iceberg/orc/ORCSchemaUtil.java, orc/src/main/java/org/apache/iceberg/orc/OrcIterable.java, orc/src/main/java/org/apache/iceberg/orc/OrcSchemaVisitor.java, orc/src/main/java/org/apache/iceberg/orc/OrcToIcebergVisitor.java, orc/src/main/java/org/apache/iceberg/orc/RemoveIds.java, orc/src/test/java/org/apache/iceberg/orc/TestExpressionToSearchArgument.java, orc/src/test/java/org/apache/iceberg/orc/TestORCSchemaUtil.java, spark/src/main/java/org/apache/iceberg/spark/source/BatchDataReader.java, spark/src/main/java/org/apache/iceberg/spark/source/RowDataReader.java, spark2/src/test/java/org/apache/iceberg/spark/source/TestNameMappingProjection.java
This PR fixes #1204 implementing name mapping for ORC.
=> ORC: Add name mapping support

api/src/main/java/org/apache/iceberg/data/Record.java, core/src/main/java/org/apache/iceberg/BaseFile.java, core/src/main/java/org/apache/iceberg/DeleteFileIndex.java, core/src/main/java/org/apache/iceberg/ManifestGroup.java, core/src/main/java/org/apache/iceberg/ManifestReader.java, core/src/main/java/org/apache/iceberg/avro/Avro.java, core/src/main/java/org/apache/iceberg/deletes/Deletes.java, core/src/main/java/org/apache/iceberg/util/FilterIterator.java, core/src/test/java/org/apache/iceberg/TestDeleteFileIndex.java, core/src/test/java/org/apache/iceberg/TestTables.java, data/src/test/java/org/apache/iceberg/data/TestDataFileIndexStatsFilters.java, parquet/src/main/java/org/apache/iceberg/parquet/Parquet.java
This adds two optimizations for `DeleteFileIndex`:
* For position deletes, if the data file path is not in the range of values for a delete file's `file_path` column, ignore the delete file
* For equality deletes, if the data file and delete file value ranges for any equality column do not overlap, ignore the delete file
=> Add file stats range optimizations for DeleteFileIndex

build.gradle
Skip building the empty jars that we don't need.
Verified the shadow jars still built and no empty jars.
=> Skip building empty jars

api/src/main/java/org/apache/iceberg/PartitionSpec.java
This PR fixes `hashCode` in `PartitionSpec` and makes it consistent with `equals`.
=> API: Fix PartitionSpec hashCode

core/src/main/java/org/apache/iceberg/StaticTableOperations.java, core/src/main/java/org/apache/iceberg/hadoop/HadoopTables.java, core/src/test/java/org/apache/iceberg/hadoop/TestStaticTable.java
Allows for a Table Operations which references a specfic metadata version
file. This operation will not change even if the base table it was derived
from is changed. This enables it to act like a ReadOnly view of the table's
state at a given time.
=> Static Table Operations

api/src/main/java/org/apache/iceberg/types/Conversions.java, api/src/main/java/org/apache/iceberg/util/UUIDUtil.java, core/src/main/java/org/apache/iceberg/avro/UUIDConversion.java, core/src/main/java/org/apache/iceberg/avro/ValueReaders.java, data/src/main/java/org/apache/iceberg/data/orc/GenericOrcReaders.java, flink/src/main/java/org/apache/iceberg/flink/RowDataWrapper.java, parquet/src/main/java/org/apache/iceberg/parquet/ParquetAvroValueReaders.java, spark/src/main/java/org/apache/iceberg/spark/data/SparkValueReaders.java
This patch address the minor comment from [here](https://github.com/apache/iceberg/pull/1320#discussion_r469509967), we abstracted a common `UUIDUtil` to convert between bytes and UUID.
=> Refactor to use a common UUIDUtil to convert between bytes and UUID

data/src/main/java/org/apache/iceberg/data/GenericAppenderFactory.java, data/src/test/java/org/apache/iceberg/TestSplitScan.java, data/src/test/java/org/apache/iceberg/data/GenericAppenderHelper.java, data/src/test/java/org/apache/iceberg/data/TestLocalScan.java, mr/src/test/java/org/apache/iceberg/mr/TestHelper.java, spark/src/test/java/org/apache/iceberg/spark/source/TestSparkReadProjection.java, spark2/src/test/java/org/apache/iceberg/spark/source/TestFilteredScan.java, spark3/src/test/java/org/apache/iceberg/spark/source/TestFilteredScan.java
In #1293, we found lot of places use `switch case avro orc parquet` to create appender, these logicals can be extract to `GenericAppenderFactory`.
=> Introduce GenericAppenderFactory and GenericAppenderHelper

spark/src/main/java/org/apache/iceberg/actions/BaseAction.java, spark/src/main/java/org/apache/iceberg/actions/ExpireSnapshotsAction.java
Requires #1342
Removes the necessity of a Cache from ExpireSnapshotsAction. Instead uses a Static view of the TableMetadata enabled by #1342 to preserve a listing of all metadata/data files from a previous point in time.
=> Expire snapshots action without cache

flink/src/main/java/org/apache/iceberg/flink/CatalogLoader.java, flink/src/main/java/org/apache/iceberg/flink/FlinkCatalog.java, flink/src/main/java/org/apache/iceberg/flink/FlinkCatalogFactory.java, flink/src/main/java/org/apache/iceberg/flink/TableLoader.java, flink/src/test/java/org/apache/iceberg/flink/FlinkCatalogTestBase.java
Fixes #1303
Unlike Spark catalog table (Table is only required on the client/driver side), Flink needs obtain `Table` object in Job Manager or Task.
- For writer (https://github.com/apache/iceberg/pull/1185): Flink needs obtain `Table` in committer task for appending files.
- For reader (https://github.com/apache/iceberg/pull/1293): Flink needs obtain `Table` in Job Manager for planing tasks.
So we can introduce a `CatalogLoader` for reader and writer, users can define a custom catalog loader in `FlinkCatalogFactory`.
```
public interface CatalogLoader extends Serializable {
Catalog loadCatalog(Configuration hadoopConf);
}
```
For support hadoop table based on location. Introduce `TableLoader` for both catalog table and hadoop location table.
Q: Can/Should we introduce `CatalogLoader` and …
=> Flink: Introduce CatalogLoader and TableLoader

build.gradle
See the comment here https://github.com/apache/iceberg/pull/1357#issuecomment-677263670,  After I applied this patch, the relocated package could be imported again.
=> Build: Fix the intellij issue that could not import the relocated classes

spark/src/test/java/org/apache/iceberg/actions/TestExpireSnapshotsAction.java
Because we use LocalIterator in ExpireSnapshotAction, every partition
runs it's own spark job, almost all of which are completely empty. This
leads to a lot of overhead which we don't need in the Test Suite. Setting
shuffle parallelism to 1 (from 200) greatly reduces the test runtime.
=> Speed up ExpireSnapshotAction Test by Reducing Shuffle Paralleism

core/src/test/java/org/apache/iceberg/TestMetrics.java, data/src/test/java/org/apache/iceberg/orc/TestOrcMetrics.java, data/src/test/java/org/apache/iceberg/parquet/TestParquetMetrics.java, orc/src/main/java/org/apache/iceberg/orc/ORC.java, orc/src/main/java/org/apache/iceberg/orc/OrcFileAppender.java, orc/src/main/java/org/apache/iceberg/orc/OrcMetrics.java, spark/src/main/java/org/apache/iceberg/spark/SparkTableUtil.java, spark/src/main/java/org/apache/iceberg/spark/source/SparkAppenderFactory.java
Unlike Parquet metrics, ORC was not using `MetricsConfig` to let the user configure which metrics to collect or truncate string column metrics.
This PR fixes #1268 by adding `MetricsConfig` support in ORC metrics. I've also added unit tests to `TestMetrics`, which runs for both Parquet and ORC, to check the different `MetricsModes` and the truncation of string and binary (not supported in ORC) columns.
PTAL @aokolnychyi @rdsr @shardulm94 Thanks!
=> ORC: Use MetricsConfig

spark/src/test/java/org/apache/iceberg/actions/TestExpireSnapshotsAction.java, spark2/src/main/java/org/apache/iceberg/spark/source/Reader.java, spark3/src/main/java/org/apache/iceberg/spark/source/SparkBatchScan.java
Encountered this NPE issue, while running ExpireSnapshots Action on an empty table ( no data is pushed yet ).
Added a test for ExpireSnapshotAction with empty table.
=> Fix NPE while estimating statistics on empty table

flink/src/main/java/org/apache/iceberg/flink/data/FlinkParquetWriters.java
This is a follow up for #1272.
=> Flink: optimize the parquet writer getter method

spark2/src/main/java/org/apache/iceberg/spark/source/Reader.java, spark3/src/main/java/org/apache/iceberg/spark/source/SparkBatchScan.java
This PR disables stats estimation for metadata tables using snapshot summary.
=> Spark: Estimate statistics using snapshot summary only for partitioned tables

core/src/test/java/org/apache/iceberg/TestRemoveSnapshots.java, spark/src/test/java/org/apache/iceberg/actions/TestExpireSnapshotsAction.java
This fixes the new snapshot expiration with rollback tests. The tests were not waiting enough time before running expire because the wait was based on the current snapshot, not the newer snapshot that was committed and rolled back.
=> Fix new snapshot expiration with rollback tests

api/src/main/java/org/apache/iceberg/io/ClosingIterator.java, core/src/main/java/org/apache/iceberg/ManifestFiles.java, spark/src/main/java/org/apache/iceberg/actions/BaseAction.java, spark/src/main/java/org/apache/iceberg/actions/ExpireSnapshotsAction.java, spark/src/main/java/org/apache/iceberg/actions/ManifestFileBean.java
This replaces use of the `all_data_files` metadata table in RemoveOrphanFilesAction and ExpireSnapshotsAction with a call to read data file paths from manifest files in parallel. This avoids reading all of the manifest lists in the Spark driver to plan the `all_data_files` scan.
On large tables, this runs much faster with adaptive execution and broadcast joins disabled. Both optimizations use size estimates that are incorrect because the number of data files is much larger than the number of manifests in a table, and Spark does not account for a single row (manifest file) producing thousands or millions of result rows (data files) in a stage.
=> Actions: Speed up expire snapshots action

spark/src/main/java/org/apache/iceberg/actions/ExpireSnapshotsAction.java, spark/src/test/java/org/apache/iceberg/actions/TestExpireSnapshotsAction.java
Previously ExpireSnapshotAction would always use toLocalIterator which
ends up costing significantly more time on smaller data sets. Since even
the largest lists of files are expected to fit in memory we are changing
the default to Collect. Collect will bring back the results more quickly
at the cost of additional memory. An option to streamDeleteResults will still
be available for extremely large expire operations.
=> Changes default collect behavior of ExpireSnapshotActions

arrow/src/main/java/org/apache/iceberg/arrow/vectorized/VectorizedArrowReader.java, parquet/src/main/java/org/apache/iceberg/parquet/Parquet.java, parquet/src/main/java/org/apache/iceberg/parquet/ParquetIO.java, spark/src/test/java/org/apache/iceberg/spark/data/parquet/vectorized/TestParquetDictionaryEncodedVectorizedReads.java, spark/src/test/java/org/apache/iceberg/spark/data/parquet/vectorized/TestParquetVectorizedReads.java
=> [Parquet Vectorized Reads] Fix reading of files with mix of dictionary and non-dictionary encoded row groups

.gitignore
Currently, we ignore directories named `spark-warehouse` only if they're underneath one of the various `spark*` repo root directories.
As a messy developer, I tend to start things like `spark-shell` etc from almost anywhere. I imagine I'm not the only one. 
This updates the .gitignore to ignore any folder named `spark-warehouse` or `tmp` (which was also underneath spark, but I can't for the life of me see why we'd check in a directory named tmp - the rule can be updated if such a use case exists).
=> Gitignore - ignore all directories named spark-warehouse or tmp

NOTICE, bundled-guava/NOTICE, spark-runtime/LICENSE, spark-runtime/NOTICE, spark3-runtime/LICENSE, spark3-runtime/NOTICE
While working on https://github.com/apache/iceberg/pull/1267 I noticed a few small things in the `NOTICE` and `LICENSE` files that I thought were worth fixing.
=> Small fixes to LICENSE and NOTICE files

flink/src/main/java/org/apache/iceberg/flink/FlinkCatalog.java, flink/src/test/java/org/apache/iceberg/flink/TestFlinkCatalogTable.java
Fixes #1392 
1. Create table: Only support identity partition, wait for Flink SQL support hidden partition, but can load all Iceberg tables.
2. Alter table: 
- Currently, Flink SQL only support altering table properties, not support altering schema and partition.
- Also support `location`, `current-snapshot-id` and `cherry-pick-snapshot-id` like Spark.
=> Flink: Support creating table and altering table in Flink SQL

api/src/main/java/org/apache/iceberg/Schema.java, api/src/main/java/org/apache/iceberg/types/IndexByName.java, api/src/main/java/org/apache/iceberg/types/TypeUtil.java
Iceberg indexes schemas by name to look up fields, but uses short names by omitting "element" and "value" names when a list or map has a struct element or value. For example, a list, `locations`, of structs `struct<lat: double, long: double>` will use names `locations.lat` instead of `locations.element.lat`.
This works most of the time, but can lead to conflicts when a map value contains a field name `key`. In that case, the schema is rejected with a failure message like this: `ValidationException: Invalid schema: multiple fields for name some_map.key: 146 and 144`
In addition, Spark passes names through `alterTable` that include the `value` and `element` names that are omitted.
This PR fixes the problem by keeping track of two names, the full name with `element` and `value`, and …
=> Fix schema name conflicts

core/src/main/java/org/apache/iceberg/BaseTransaction.java, core/src/main/java/org/apache/iceberg/RemoveSnapshots.java, core/src/test/java/org/apache/iceberg/TestRemoveSnapshots.java
Related to issue: https://github.com/apache/iceberg/issues/1370
I think this is check is just to reduce the commit times, but it may cause some other problems.
=> Remove a wrong check for commit operation

api/src/main/java/org/apache/iceberg/catalog/Catalog.java, core/src/main/java/org/apache/iceberg/BaseMetastoreCatalog.java, core/src/main/java/org/apache/iceberg/hadoop/HadoopCatalog.java, core/src/test/java/org/apache/iceberg/hadoop/TestHadoopCatalog.java, hive-metastore/src/test/java/org/apache/iceberg/hive/TestHiveCatalog.java
This PR introduces a builder in `Catalog` to avoid duplicating the number of methods each time we introduce a new param.
=> API: Introduce a builder in Catalog

.baseline/checkstyle/checkstyle.xml, api/src/main/java/org/apache/iceberg/NullOrder.java, api/src/main/java/org/apache/iceberg/SortDirection.java, api/src/main/java/org/apache/iceberg/SortField.java, api/src/main/java/org/apache/iceberg/SortOrder.java, api/src/main/java/org/apache/iceberg/Table.java, api/src/main/java/org/apache/iceberg/Tables.java, api/src/main/java/org/apache/iceberg/catalog/Catalog.java, api/src/main/java/org/apache/iceberg/expressions/Expressions.java, core/src/main/java/org/apache/iceberg/BaseMetadataTable.java, core/src/main/java/org/apache/iceberg/BaseMetastoreCatalog.java, core/src/main/java/org/apache/iceberg/BaseTable.java, core/src/main/java/org/apache/iceberg/BaseTransaction.java, core/src/main/java/org/apache/iceberg/SortOrderParser.java, core/src/main/java/org/apache/iceberg/TableMetadata.java, core/src/main/java/org/apache/iceberg/TableMetadataParser.java, core/src/main/java/org/apache/iceberg/hadoop/HadoopTables.java, core/src/test/java/org/apache/iceberg/TestReplaceTransaction.java, core/src/test/java/org/apache/iceberg/TestSortOrder.java, core/src/test/java/org/apache/iceberg/TestSortOrderParser.java, core/src/test/java/org/apache/iceberg/TestTableMetadata.java, core/src/test/java/org/apache/iceberg/TestTables.java, core/src/test/java/org/apache/iceberg/hadoop/TestHadoopCatalog.java, core/src/test/java/org/apache/iceberg/hadoop/TestHadoopTablesSortOrder.java, hive-metastore/src/test/java/org/apache/iceberg/hive/TestHiveCatalog.java, mr/src/test/java/org/apache/iceberg/mr/hive/TestTables.java, parquet/src/main/java/org/apache/iceberg/parquet/Parquet.java
This PR extends Iceberg metadata with a sort order and is supposed to replace the work in #589.
The API currently looks like this:
```
SortOrder.builderFor(schema)
.withOrderId(3)
.asc("y", NullOrder.NULLS_FIRST)
.desc(Expressions.bucket("z", 4), NullOrder.NULLS_LAST)
.build();
```
The underlying representation looks like this:
```
"default-sort-order-id": 3,
"sort-orders": [
{
"order-id": 3,
"fields": [
{
"transform": "identity",
"source-id": 2,
"direction": "asc",
"null-order": "nulls-first"
},
{
"transform": "bucket[4]",
"source-id": 3,
"direction": "desc",
"null-order": "nulls-last"
}
]
}
],
```
**Open items**
- Consider switching to a builder patter in `Catalog`.
- Whether to reserve id 0 for the unsorted order.
- Case sensitivity when binding `Term`s in `Builder`.
**Follow-up …
=> API: Implement SortOrder

hive-metastore/src/main/java/org/apache/iceberg/hive/ClientPool.java, hive-metastore/src/test/java/org/apache/iceberg/hive/TestClientPool.java
When preparing demo for flink + hive metastore,   I created a hive catalog with a random port for metastore, for example: 
```sql
create catalog hive_catalog with(
'type'='iceberg',
'catalog-type'='hive',
'uri'='thrift://localhost:3234',
'clients'='1',
'property-version'='1'
);
```
Then I switch to use the `hive_catalog` and execute sql command `show databases` to show all the databases,  I found that the sql command was blocked. 
After digging into the code, I find that it's a bug in `ClientPool`, saying if encountering an exception when `newClient`,  the upper layer (Flink SQL client) will try to close all the resources from `ClientPool` by calling `ClientPool#close`, finally it will be blocked in close method like following: 
```
"main" #1 prio=5 os_prio=31 tid=0x00007fc853802800 …
```
=> Fix the bug that clientPool#close will block forever when newClient encountered an exception.

core/src/main/java/org/apache/iceberg/BaseMetastoreTableOperations.java
Closes #1428 
This patch adjusts the log level on NoSuchTableException in refresh() with HiveCatalog, specific to the NoSuchIcebergTableException, which can be occurred in the "normal" case, like below:
1. Use default spark catalog with type=hive
2. Read non-iceberg table
=> Core: Lower the log level of warning message on refresh() for NoSuchIcebergTableException

flink/src/main/java/org/apache/iceberg/flink/FlinkCatalog.java, flink/src/test/java/org/apache/iceberg/flink/TestFlinkCatalogDatabase.java
This fix the issue https://github.com/apache/iceberg/issues/1434. 
It's necessary to create the default database if it does not exist in the newly created catalog.
=> Create the default database if it does not exist when opening the catalog

.github/autolabeler.yml
As noticed in this PR, https://github.com/apache/iceberg/pull/1423, changes to the `build.gradle` file were not properly handled by the autolabeler.
I have updated the autolabeler config to handle this case. I've also merged this into my local repo in order to test for this.
I validated the change on a top level file named `gradle.properties` (to check both top level files as well as files with only the substing gradle) in [this PR in my local repo](https://github.com/kbendick/iceberg/pull/12).
I also tested against [the build.gradle file](https://github.com/kbendick/iceberg/pull/13), as that was the original file and it differed from the previous one in that `gradle` is now the ending substring (checking padding on either side).
I also performed two checks for files in the `gradle` …
=> Update autolabeler config to match any file with gradle in it

.github/autolabeler.yml
This adds the upcoming `flink-runtime` module, and associated top level directory, to be tagged under `flink` like the current `spark-runtime` and associated top level spark directories / different spark modules are all tagged as `spark`.
The pending PR which adds the `flink-runtime` module is here: https://github.com/apache/iceberg/pull/1423
This closes this issue: https://github.com/apache/iceberg/issues/1448
=> Add top level flink-runtime directory to flink autolabeler config

site/docs/java-api-quickstart.md, site/docs/maintenance.md, site/docs/spark-structured-streaming.md
Appendix in SSS page was actually to deduplicate code in maintenance page, but it didn't move to maintenance page once we extract the content from SSS page.
I also add a link for compacting data files in SSS page.
=> DOC: Remove unnecessary appendix in SSS doc, add missing links

core/src/main/java/org/apache/iceberg/hadoop/HadoopTableOperations.java, core/src/test/java/org/apache/iceberg/hadoop/TestHadoopCatalog.java
During my testing I have noticed that if the version-hint.text file content is empty then we can not read the table anymore.
Based on @rdblue's comment on the mail list this is not the expected behavior. We should try to recover from it.
This patch starts to read the metadata files from version 1 if the version-hint.text content can not be parsed, or there is an error reading the file. The only remaining failure situation is if the file itself does not exists - I use this case to double-check that we have really manipulated the correct file, and not just reading the old file again and again 😄
=> Core: Fix table load error on corrupted version-hint.text file

.gitattributes
We are working on updating the release script to make it easier to pick up all current files, except for the few sets of directories or files that we would like to ignore from the release. The current PR (which has a large number of added shell commands) is https://github.com/apache/iceberg/issues/1453.
`.gitattributes` provides an easy, industry-standard way of doing this which will greatly simplify the release scripts.
In order to see the changes in any PR to update the release script, the `.gitattributes` file needs to be added first.
This closes https://github.com/apache/iceberg/issues/1453 and then makes way for a much simplified release script, using industry standards, beyond the work done in https://github.com/apache/iceberg/issues/1453.
I have merged this into my local repository …
=> Add .gitattributes file for simplifying excludes/includes in release script

.gitattributes, dev/source-release.sh
This PR replaces https://github.com/apache/iceberg/pull/1227, as @rdblue and I spent quite some time on it yesterday trying to get it to work and it wound up becoming one of those somewhat overly complex shell scripts (mostly due to my suggestions).
As it turns out, git already has a feature to explicitly ignore certain files, directories, and the contents of those directories from the `git archive` process. This can be achieved via the `.gitattributes` file and the `export-ignore` label.
In order to achieve the same behavior of `git ls-tree --name-only -r HEAD`, which Ryan suggested as an alternative to automatically keeping the archives "includes" up to date, I've gone ahead and used HEAD as the tag that is passed to the `git archive` script. It still uses the `release_hash`, but it …
=> Use gitattributes file to detect archive list automatically and simplify release script

core/src/main/java/org/apache/iceberg/DeleteFileIndex.java, core/src/main/java/org/apache/iceberg/util/ParallelIterable.java
This fixes the tests that have been flaky in Java 11.
The problem was that the `DeleteFileIndex` uses a map from partition spec ID to thread-local `StructLikeWrapper` for working with partition tuples. The map was being updated with concurrent calls to `computeIfAbsent`, resulting in a `ConcurrentModificationException`.
That exception was causing a planning task to fail inside of `ParallelIterator`, which was not correctly checking for failed tasks. When a task failed, the files from the task were not added to the iterator's queue, which caused the flaky behavior. This PR also updates `ParallelIterator` to check for exceptions held by task futures when it checks task status to ensure that future issues will result in failures.
The bug does not affect any released version of Iceberg …
=> Fix ConcurrentModificationException in DeleteFileIndex

core/src/main/java/org/apache/iceberg/BaseCombinedScanTask.java
I was looking at another PR and checking for nullability concerns, when I noticed that there are two constructors for BaseCombineTask. There's one constructor that takes in a List<FileScanTask> and one that uses varargs FileScanTask.... The List constructor specifically checks for null, however, the varargs one does not.
However, because arrays are objects in java, the FileScanTask... when passed in null does not give new FileScanTask[]{null} or new FileScanTask[0], it simply passes null.
Therefore, it doesn't seem overly cautious to add a precondition check for null here since we have it already.
This closes issue: https://github.com/apache/iceberg/issues/1451
=> Add a null precondition check to the varargs BaseCombinedTask constructor

site/docs/maintenance.md
@rdblue here is the warning we discussed in the ASF Slack
=> Warning about RemoveOrphanFiles

flink/src/main/java/org/apache/iceberg/flink/sink/IcebergFilesCommitter.java, flink/src/test/java/org/apache/iceberg/flink/sink/TestIcebergFilesCommitter.java
This patch will address the comment from the [discussion](https://github.com/apache/iceberg/pull/1185/files#r479545979).  FYI @stevenzwu @rdblue @JingsongLi .
=> Flink: Add flink job id to state backend for handling flink job redeployment

site/docs/spark.md
#1463 Led me to see that our examples were hitting a Spark issue of discarding options when using "table" in a DataFrameReader command.
=> Fix Time Travel Examples and Docs

api/src/main/java/org/apache/iceberg/Accessors.java, build.gradle, core/src/main/java/org/apache/iceberg/util/TableScanUtil.java, data/src/main/java/org/apache/iceberg/data/DeleteFilter.java, data/src/main/java/org/apache/iceberg/data/GenericDeleteFilter.java, data/src/main/java/org/apache/iceberg/data/GenericReader.java, spark/src/main/java/org/apache/iceberg/spark/source/BaseDataReader.java, spark/src/main/java/org/apache/iceberg/spark/source/RowDataReader.java, spark/src/test/java/org/apache/iceberg/spark/SparkTestBase.java, spark/src/test/java/org/apache/iceberg/spark/source/TestSparkReaderDeletes.java, spark2/src/main/java/org/apache/iceberg/spark/source/Reader.java, spark2/src/test/java/org/apache/iceberg/spark/source/TestSparkReaderDeletes24.java, spark3/src/main/java/org/apache/iceberg/spark/source/SparkBatchScan.java, spark3/src/test/java/org/apache/iceberg/spark/source/TestSparkReaderDeletes3.java
This applies row-level delete files while reading in Spark, and refactors the generic read code to share the filter code between Spark and generics.
* Moves filter methods from `GenericReader` to `DeleteFilter`
* Adds `SparkDeleteFilter` to adapt `InternalRow` to `StructLike` for deletes
* Adds `GenericDeleteFilter` for generic rows, which can be reused for `IcebergInputFormat`
* Updates Spark to also decrypt delete files
* Adds tests for deletes in Spark based on generics tests
=> Spark: Apply row-level delete files when reading

parquet/src/main/java/org/apache/iceberg/parquet/ReadConf.java
this lead to s3a connection pool timeout
=> FIX: fix reader not getting closed.

core/src/main/java/org/apache/iceberg/hadoop/HadoopTableOperations.java, core/src/main/java/org/apache/iceberg/hadoop/HadoopTables.java, core/src/test/java/org/apache/iceberg/hadoop/TestHadoopCatalog.java
The patch enhances the recovery introduced in #1443 for missing/corrupted version-hint.txt by listing the files in the metadata directory and returning the highest possible version.
=> Core: Enhance version-hint.txt recovery with file listing

spark/src/test/java/org/apache/iceberg/spark/source/TestDataFrameWrites.java
The functionality is obvious as the concept of Iceberg, but it would be still nice to have a simple test on auditing fault-tolerance situation.
=> Spark: add test on fault tolerance during write (transactional write)

api/src/main/java/org/apache/iceberg/types/AssignFreshIds.java, api/src/main/java/org/apache/iceberg/types/TypeUtil.java, core/src/main/java/org/apache/iceberg/TableMetadata.java, core/src/test/java/org/apache/iceberg/TestReplaceTransaction.java
`REPLACE TABLE` replaces the table schema and partition spec in addition to the table data. When the new schema is passed to Iceberg, its field IDs are reassigned to ensure they are consistent (for example, no duplicate IDs), just like when a table is created. This updates how the IDs are reassigned to fix time travel and partition specs.
Iceberg doesn't currently track what the table schema was at the time a snapshot was written. The current table schema is always used to read older snapshots. When a table is replaced and the ids are reassigned, this can lead to incompatible ID conflicts between an older schema and the current schema.
To fix incompatible IDs, this updates reassignment to use the current table schema's ids if possible. If the current schema is `1: id bigint, 2: data …
=> Fix REPLACE TABLE by preserving existing field IDs

README.md
We have `iceberg-spark2` and `iceberg-spark3` listed in the readme which direct people to use the corresponding `iceberg-spark*-runtime` for a shaded version. Now that @openinx has added the `iceberg-flink-runtime` shaded module, I've updated the README to reflect that users should use that.
=> Update README to reference shaded flink-runtime

core/src/main/java/org/apache/iceberg/BaseMetastoreCatalog.java
The method BaseMetastoreCatalog#deleteFiles keeps track of deleted files in a Map<String, Boolean> using a Guava MapMaker with weak keys.
We intern the file path represented as a string that is going to be placed into this weak key map, as the Guava MapMaker weak key map uses identity (==) instead of equals. Thus, interning the strings is the only way to ensure that when two possible keys p1 and p2 are placed into the map, where p1.equals(p2), it will be correctly overwritten (i.e. the intern is necessary to force the strings to share the same memory address and thus have identity comparison work as that's what is used).
=> Suppress warning for DangerousStringInternUsage in BaseMetastoreCatalog

flink/src/main/java/org/apache/iceberg/flink/FlinkFixupTypes.java, flink/src/main/java/org/apache/iceberg/flink/FlinkSchemaUtil.java, flink/src/main/java/org/apache/iceberg/flink/data/FlinkOrcReader.java, flink/src/main/java/org/apache/iceberg/flink/data/FlinkOrcReaders.java, flink/src/main/java/org/apache/iceberg/flink/data/FlinkParquetReaders.java, flink/src/main/java/org/apache/iceberg/flink/source/DataIterator.java, flink/src/main/java/org/apache/iceberg/flink/source/FlinkInputFormat.java, flink/src/main/java/org/apache/iceberg/flink/source/FlinkInputSplit.java, flink/src/main/java/org/apache/iceberg/flink/source/FlinkSource.java, flink/src/main/java/org/apache/iceberg/flink/source/FlinkSplitGenerator.java, flink/src/main/java/org/apache/iceberg/flink/source/RowDataIterator.java, flink/src/main/java/org/apache/iceberg/flink/source/ScanOptions.java, flink/src/test/java/org/apache/iceberg/flink/data/TestFlinkOrcReaderWriter.java, flink/src/test/java/org/apache/iceberg/flink/source/TestFlinkInputFormat.java, flink/src/test/java/org/apache/iceberg/flink/source/TestFlinkScan.java
This is subtask of #1293
Introduce `FlinkInputFormat` to read records from Iceberg table by Flink engine. The `FlinkInputFormat` is the foundation of SQL reader and streaming reader.
Implemented by:
- Introduce `RowDataIterator` and `DataIterator`, just like Spark `BaseDataReader` and `RowDataReader`.
- The `DataIterator` provides a union iterator to union `FileScanTask` iterators.
- Introduce `FlinkSplitGenerator`, this generator just wrap Iceberg `CombinedScanTask` to `FlinkInputSplit`.
- Introduce `FlinkInputFormat`, it provides a simple API: `FlinkInputFormat.builder().tableLoader(..).build()`.
This PR is based on:
- Introduce CatalogLoader. ~~#1332~~
- Introduce GenericAppenderFactory and GenericAppenderHelper for reusing and testing. ~~#1340~~
=> Flink: Introduce Flink InputFormat

core/src/main/java/org/apache/iceberg/BaseMetastoreCatalog.java, core/src/main/java/org/apache/iceberg/CatalogUtil.java, core/src/main/java/org/apache/iceberg/hadoop/HadoopCatalog.java, core/src/main/java/org/apache/iceberg/hadoop/HadoopTables.java, core/src/test/java/org/apache/iceberg/hadoop/TestHadoopTables.java, hive-metastore/src/main/java/org/apache/iceberg/hive/HiveCatalog.java, mr/src/main/java/org/apache/iceberg/mr/Catalogs.java, mr/src/main/java/org/apache/iceberg/mr/InputFormatConfig.java, mr/src/test/java/org/apache/iceberg/mr/TestCatalogs.java
If tools want to implement drop and create table operations using the Catalogs they need a common interface to accessing the functionality.
For example these methods will be used by HiveMetaHook to allow Iceberg table creation through Hive SQL commands
The patch includes 2 commits:
1. HadoopTables did not have the dropTable functionality. Refactored the code out from BaseCatalog to be accessible by HadoopTables, and implemented the method. Added some tests around the new function.
2. Created the corresponding Catalogs methods and added tests around that.
=> Core: Implement Catalogs.createTable and Catalogs.dropTable

orc/src/main/java/org/apache/iceberg/orc/OrcMetrics.java, spark/src/main/java/org/apache/iceberg/spark/SparkTableUtil.java, spark2/src/test/java/org/apache/iceberg/spark/source/TestSparkTableUtil.java
This PR fixes #1345 and #1206 - the main changes included are:
1. Refactor `TestSparkTableUtil` to run tests in multiple file formats.
2. Use name mapping when importing ORC tables.
Note that I changed to use a name mapping by default of the target table, as mentioned in https://github.com/apache/iceberg/issues/1345#issuecomment-679417869.
PTAL @rdsr @shardulm94 @aokolnychyi - Thanks!
=> Spark: Follow name mapping when importing ORC tables

core/src/main/java/org/apache/iceberg/CatalogUtil.java
When cleaning up valid uses of java.lang.String.intern (on weak-keyed maps which use identity comparison instead of equality comparison), I missed one instance. Here's a previous PR: https://github.com/apache/iceberg/pull/1489
This suppresses that final warning as well.
I tried to enforce this type of warning as a bug, but I was unable to do so in a way that emitted a readable error (admittedly I didn't spend too much time on it). 
I can open an issue if this is something we'd like to enforce as either suppressed or not done. Depends on your thoughts @rdblue @RussellSpitzer.
=> Suppress the last remaining invalid DangerousStringInternUsage warning

build.gradle
The PR set the `javadoc` task encoding option since the build task fails on the system that uses ascii. For example, we can reproduce the issue when setting `javadoc` encoding to `ASCII`.
```
> Task :iceberg-orc:javadoc FAILED                                                                                                                         
/home/cjj/iceberg/orc/src/main/java/org/apache/iceberg/orc/ORCSchemaUtil.java:233: error: unmappable character for encoding ASCII                          
* which would then use its schema evolution to map that to the writer??????s schema.                                                                       
^ …
```
=> Fix javadoc encoding

core/src/main/java/org/apache/iceberg/RemoveSnapshots.java, core/src/main/java/org/apache/iceberg/SnapshotProducer.java, spark/src/main/java/org/apache/iceberg/actions/ExpireSnapshotsAction.java
Several classes have a private named field `defaultDelete`, which is a `Consumer<String>` and is used as a functional interface for removing files etc.
We use a functional interface so that users may pass in their own implementation of the functional interface. It is a common pattern in the code base.
I tried out the method suggested as a fix, by defining the function as a method `void defaultDelete(String file)` and it got really messy. I suggest we suppress these warnings and move on with it so as to clean up the clutter in the build phase.
=> Suppress UnnecessaryAnonymousClass warnings for classes with defaultDelete as a Consumer

mr/src/main/java/org/apache/iceberg/mr/mapreduce/IcebergInputFormat.java
There was a TODO saying to switch to FileIO from directly accessing the HadoopInputFile class.
=> [MINOR] Switch to FileIO for InputFormat

api/src/main/java/org/apache/iceberg/types/PruneColumns.java, core/src/main/java/org/apache/iceberg/avro/PruneColumns.java, parquet/src/main/java/org/apache/iceberg/parquet/PruneColumns.java
The class PruneColumns has a single constructor, which takes in a Set<Integer>, `PruneColumns(Set<Integer> selected)`.
Later on in this class, there are no null checks before calling methods on the value `selected` such as `contains`, etc.
Admittedly, the only place that PruneColumns is _currently_ used, `org.apache.iceberg.types.TypeUtils#select(Types.StructType struct, Set<Integer> fieldIds)`, has a precondition check for null on `fieldIds` - which is passed into PruneColumns. Thus, it is arguably not necessary to add this additional check with the code as is.
However, because the class `PruneColumns` is part of `api` and might get used elsewhere, it seems sane to add this precondition check given that we do no null checking before accessing it and so it would be up to the caller to add …
=> [API][Core - Types/Avro][Parquet] Add a precondition null check for the constructor arg of PruneColumns

core/src/main/java/org/apache/iceberg/DataFilesTable.java
We refer to the field value by literal integer rather than the field's constant ID
@rdblue Quick fix extracted to it's own PR
=> Replace Literal Integer with Constant Reference

data/src/test/java/org/apache/iceberg/data/TestMetricsRowGroupFilter.java, orc/src/main/java/org/apache/iceberg/orc/ExpressionToSearchArgument.java, orc/src/test/java/org/apache/iceberg/orc/TestExpressionToSearchArgument.java
ORC uses SQL semantics for Search Arguments, so an expression like `col != 1` will exclude rows where col is NULL along with rows where `col = 1`. In contrast, Iceberg's Expressions will keep rows with NULL values, so the equivalent ORC Search Argument for an Iceberg Expression `col != x` is `col IS NULL OR col != x`.
This PR fixes the issue of the ORC pushdown returning less rows than what Iceberg expects. https://github.com/apache/iceberg/blob/78e80d2a35c4c93e68776c31c24cc8ccb06fed4b/data/src/test/java/org/apache/iceberg/data/TestMetricsRowGroupFilter.java#L741-L742 mentions that this might be a bug in ORC, but in fact its just a case of mismatched semantics. During conversion of Iceberg expression to ORC Search Arguments, we now take care of this semantic difference.
The wider …
=> ORC: Fix predicate pushdown for Not In and Not Equals

spark/src/test/java/org/apache/iceberg/spark/SparkTestBase.java
As pointed out by @RussellSpitzer in his PR https://github.com/apache/iceberg/pull/1525/files, there is the possibility that the catalog is null when the tests are running. This error likely come from killing tests early while debugging, but that's something that probably a good handful of us do in our workflow and this will make the output less verbose.
I've cherry picked this change from his PR, as that PR will likely take much more time to merge in due to its scope and the community can benefit from this fix now.
=> Add null check when calling catalog.close in SparkTestBase

site/docs/flink.md, site/mkdocs.yml
It's the document for flink sink connector, pls apply this patch after applied the PR https://github.com/apache/iceberg/pull/1423.
=> Flink: Add flink sink document

api/src/main/java/org/apache/iceberg/Table.java, api/src/main/java/org/apache/iceberg/catalog/Catalog.java, core/src/main/java/org/apache/iceberg/AllDataFilesTable.java, core/src/main/java/org/apache/iceberg/AllEntriesTable.java, core/src/main/java/org/apache/iceberg/AllManifestsTable.java, core/src/main/java/org/apache/iceberg/BaseMetadataTable.java, core/src/main/java/org/apache/iceberg/BaseMetastoreCatalog.java, core/src/main/java/org/apache/iceberg/BaseTable.java, core/src/main/java/org/apache/iceberg/BaseTransaction.java, core/src/main/java/org/apache/iceberg/CachingCatalog.java, core/src/main/java/org/apache/iceberg/DataFilesTable.java, core/src/main/java/org/apache/iceberg/HistoryTable.java, core/src/main/java/org/apache/iceberg/ManifestEntriesTable.java, core/src/main/java/org/apache/iceberg/ManifestsTable.java, core/src/main/java/org/apache/iceberg/MetadataTableUtils.java, core/src/main/java/org/apache/iceberg/PartitionsTable.java, core/src/main/java/org/apache/iceberg/SnapshotsTable.java, core/src/main/java/org/apache/iceberg/hadoop/HadoopCatalog.java, core/src/main/java/org/apache/iceberg/hadoop/HadoopTables.java, core/src/test/java/org/apache/iceberg/hadoop/TestCachingCatalog.java, core/src/test/java/org/apache/iceberg/hadoop/TestHadoopCatalog.java, core/src/test/java/org/apache/iceberg/hadoop/TestHadoopTables.java, hive-metastore/src/main/java/org/apache/iceberg/hive/HiveCatalog.java, hive-metastore/src/test/java/org/apache/iceberg/hive/TestHiveCatalog.java
This PR adds `name` methods to the `Table` and `Catalog` APIs.
Resolves #658.
=> API: Add name to Table and Catalog APIs

mr/src/main/java/org/apache/iceberg/mr/mapreduce/IcebergInputFormat.java, mr/src/main/java/org/apache/iceberg/mr/mapreduce/IcebergSplit.java
This along with #1526 fixes https://github.com/apache/iceberg/issues/865.
=> MR: use encryption manager for input files

spark3/src/main/java/org/apache/iceberg/spark/source/SparkTable.java, spark3/src/test/java/org/apache/iceberg/spark/source/TestSparkTable.java
This PR implements `equals` and `hashCode` in `SparkTable` and `BaseTable` so that we can refresh Spark cache correctly in our stored procedures.
See more details in #1485.
=> Spark: Implement equals and hashCode in SparkTable

.baseline/checkstyle/checkstyle.xml, core/src/main/java/org/apache/iceberg/BaseTableScan.java, core/src/main/java/org/apache/iceberg/deletes/PositionDelete.java, data/src/main/java/org/apache/iceberg/data/InternalRecordWrapper.java, spark/src/test/java/org/apache/iceberg/spark/data/TestHelpers.java
This PR removes `OverloadMethodsDeclarationOrder` from the list of enforced rules.
=> Build: Ignore OverloadMethodsDeclarationOrder rule

spark/src/test/java/org/apache/iceberg/spark/source/LogMessage.java, spark/src/test/java/org/apache/iceberg/spark/source/TestPartitionPruning.java, spark2/src/test/java/org/apache/iceberg/spark/source/TestPartitionPruning24.java, spark3/src/test/java/org/apache/iceberg/spark/source/TestPartitionPruning3.java
This PR proposes to add E2E tests on partition pruning for both Spark 2.4 and Spark 3. 
This PR tests below queries:
* identity with String type
* bucket with Integer type
* truncate with String type
* hour with Timestamp type
which the table has all of them in partition spec.
=> Spark: add E2E test on partition pruning for filter pushdown

core/src/main/java/org/apache/iceberg/BaseRewriteManifests.java, core/src/main/java/org/apache/iceberg/FastAppend.java, core/src/main/java/org/apache/iceberg/MergingSnapshotProducer.java, core/src/main/java/org/apache/iceberg/SnapshotSummary.java, core/src/main/java/org/apache/iceberg/TableProperties.java, core/src/test/java/org/apache/iceberg/TestFastAppend.java, core/src/test/java/org/apache/iceberg/TestMergeAppend.java, site/docs/configuration.md
This adds partition-level summaries to snapshot summaries.
Summary counters are refactored into a private `UpdateMetrics` class that is used to track both partition and snapshot metrics. Metrics for changed partitions are added to snapshot summaries by merging the metrics into a string that can be parsed back into a map.
If manifests are appended in a snapshot, some of the summary information is not valid. This keeps track of when the summary metrics are valid and only adds valid metrics.
=> Add partition summaries in SnapshotSummary builder

spark/src/test/java/org/apache/iceberg/spark/source/TestSparkDataWrite.java, spark3/src/main/java/org/apache/iceberg/spark/SparkCatalog.java, spark3/src/main/java/org/apache/iceberg/spark/source/IcebergSource.java, spark3/src/main/java/org/apache/iceberg/spark/source/SparkTable.java, spark3/src/main/java/org/apache/iceberg/spark/source/StagedSparkTable.java, spark3/src/test/java/org/apache/iceberg/spark/sql/TestPartitionedWrites.java
This PR makes views that reference Iceberg tables show up-to-date data with and without catalog cache.
See #1485 for more info.
=> Spark3: Make views that reference Iceberg tables show current data

core/src/main/java/org/apache/iceberg/AllDataFilesTable.java, core/src/main/java/org/apache/iceberg/AllEntriesTable.java
The all_data_files and all_entries tables were not correctly passing iterables to `ParallelIterable`. Instead of passing an iterable that would read a manifest list, the tables were reading the manifest list in the calling thread and passing the iterable `List<ManifestFile>` to `ParallelIterable`. This fixes the problem, which speeds up planning for those metadata tables.
=> Core: Parallelize manifest list reads in metadata tables

api/src/main/java/org/apache/iceberg/OverwriteFiles.java, api/src/main/java/org/apache/iceberg/RowDelta.java, core/src/main/java/org/apache/iceberg/BaseOverwriteFiles.java, core/src/main/java/org/apache/iceberg/BaseRowDelta.java, core/src/main/java/org/apache/iceberg/MergingSnapshotProducer.java, core/src/main/java/org/apache/iceberg/SnapshotManager.java, core/src/main/java/org/apache/iceberg/SnapshotProducer.java, core/src/main/java/org/apache/iceberg/deletes/PositionDeleteWriter.java, core/src/main/java/org/apache/iceberg/util/SnapshotUtil.java, core/src/test/java/org/apache/iceberg/TestOverwriteWithValidation.java, core/src/test/java/org/apache/iceberg/TestRowDelta.java, data/src/test/java/org/apache/iceberg/data/DeleteReadTests.java, data/src/test/java/org/apache/iceberg/data/FileHelpers.java, data/src/test/java/org/apache/iceberg/data/TestDataFileIndexStatsFilters.java
This adds a new validations to the `RowDelta` operation.
This includes some small cleanup by adding a `validate` method to `SnapshotProducer` to run validations and updating existing operations to use it.
One new validation for `RowDelta` finds data files that have been deleted since a starting "from" snapshot and validates that the set of referenced data files does not intersect the deleted data file set. Configuration uses 3 methods:
* `RowDelta.validateFromSnapshot(id)` to set the starting snapshot ID for accumulating deleted files
* `RowDelta.validateDataFilesExist(Iterable)` to add required data files to the validation
* `RowDelta.validateDeletedFiles()` to validate data files were not deleted by concurrent deletes (rewrite/overwrite is the default)
The second new validation tests …
=> Add position delete validation that data files have not been deleted

mr/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
Hive queries which spawn map reduce jobs are currently failing on live yarn clusters with the following stack trace:
```
2020-10-02 23:37:01,507 WARN [main] org.apache.hadoop.mapred.YarnChild: Exception running child : java.io.IOException: java.lang.NullPointerException
at org.apache.hadoop.hive.io.HiveIOExceptionHandlerChain.handleRecordReaderCreationException(HiveIOExceptionHandlerChain.java:97)
at org.apache.hadoop.hive.io.HiveIOExceptionHandlerUtil.handleRecordReaderCreationException(HiveIOExceptionHandlerUtil.java:57)
at org.apache.hadoop.hive.ql.io.HiveInputFormat.getRecordReader(HiveInputFormat.java:258)
at org.apache.hadoop.hive.ql.io.CombineHiveInputFormat.getRecordReader(CombineHiveInputFormat.java:705)
at org.apache.hadoop.mapred.MapTask$TrackedRecordReader.<init>(MapTask.java:1 …
```
=> Hive: Fix for missing table schema in map reduce job configurations

site/docs/spark.md
As a new user going through the documentation and testing features, I got stuck at this third line of config to load tables from a Hive metastore. After some help from Russell and scrolling down further, I found out that URI can be ignored for hive to follow the default. 
Very simply, if this line for omitting the uri was in this first section for 'Configuring catalogs" as opposed to later in the documentation, I wouldn't have been stuck here and understood this. This note could either be placed up in the 'Configuring catalogs' section as I did here, or repeated in both places, but I think this would help.
=> Rearranging some starter documentation in Spark Catalogs

mr/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergSerDe.java
Hive when it spawns Map Reduce jobs, needs to initialize `HiveIcebergSerDe` on mappers. When HiveIcebergSerDe is initialized, [a catalog instance](https://github.com/apache/iceberg/blob/master/mr/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergSerDe.java#L41)  is created and queried for table schema. This doesn't seem like a good behavior, considering that there can be 1000s of mappers, and that can overload the catalog, for example a hive metastore. 
I accidentally came across this behavior while trying to run it on a yarn cluster, the mappers didn't have access to HiveMetaStore classes ([see the error](https://gist.github.com/HotSushi/fe86bdfe576138aa53d1b6cf4b12a24b)). The reason this is not reproducible in HiveRunner unit tests, is because the classpath already contains …
=> Hive: Don't use catalog to initialize serde on mappers

spark/src/main/java/org/apache/iceberg/spark/source/BaseDataReader.java, spark/src/test/java/org/apache/iceberg/spark/source/TestSparkBaseDataReader.java, spark/src/test/java/org/apache/iceberg/spark/source/TestSparkReadProjection.java, spark2/src/test/java/org/apache/iceberg/spark/source/TestSparkBaseDataReader24.java, spark3/src/test/java/org/apache/iceberg/spark/source/TestSparkBaseDataReader3.java
- This PR closes data iterator when it is exhausted in Spark base data reader.
- **Observation**: Using S3 store, _coalesced_ read sees timeout on http pool connections from S3A. Using our internal metrics, we do see constant number of pending http pool connections. By contrast, reading directly to the underlying S3 data path with parquet read (not iceberg) has zero pending connections.
- **Cause**: Base reader for Spark does not close data iterator when it is exhausted
- **Question**: Why does this not happen more commonly iceberg read (non-coaleseced)?
- In Spark, the data reader will be closed after Spark _task_ is finished as it is registered in task completion callback: https://git.corp.stripe.com/stripe-private-oss-forks/spark/blob/stripe-2.4.4/sql/core/src/main/scala/org/apache/spar …
=> Close source data iterator for Spark data reader: fixing timeout due to S3A connection pool

mr/src/test/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandlerBaseTest.java
It would be great to increase our Hive test coverage for ORC as well. One way to make progress on that is to run the same StorageHandler tests for both file formats (Parquet and ORC). 
This would be ideally done by using the JUnit `Parameterized` test runner, however, we're already using the `StandaloneHiveRunner` test runner, so can't use both on the same class. @massdosage are you aware of any easy ways to use HiveRunner without this test runner? Couldn't find any Rules-based implementation for it, and pulling out the logic of the HiveShell initialization from the Runner seemed complicated enough to make it not worth it. Similarly, I didn't find any Rules-based implementation for `Parameterized` either, therefore I had to resort to simply writing new test methods for ORC.
It's not …
=> Run hive storage handler tests for both Parquet and ORC

.github/autolabeler.yml
The autolabeler is currently configured mostly off of top level names, either directories or files, with an exception for some infra and build related things.
The iceberg-hive module was split into multiple modules. This updates the `/hive3` and `/hive-runtime` to be labeled as hive. It also closes https://github.com/apache/iceberg/issues/1574
I've chosen to add a new label, METASTORE, for the newer `hive-metastore` because it is of importance to several other projects. That's handled in this PR: https://github.com/apache/iceberg/pull/1576
=> Add split up hive modules to the autolabeler configuration

flink/src/main/java/org/apache/iceberg/flink/data/FlinkOrcWriters.java
This patch fixes the following warning for `IntLongMath`
```
/iceberg/flink/src/main/java/org/apache/iceberg/flink/data/FlinkOrcWriters.java:135: warning: [IntLongMath] Expression of type int may overflow before being assigned to a long
((LongColumnVector) output).vector[rowId] = millis * 1000;
^
(see https://errorprone.info/bugpattern/IntLongMath)
Did you mean '((LongColumnVector) output).vector[rowId] = millis * 1000L;'?
```
=> Fix IntLongMath warnings

core/src/main/java/org/apache/iceberg/BaseAllMetadataTableScan.java, core/src/main/java/org/apache/iceberg/BaseTableScan.java, core/src/test/java/org/apache/iceberg/hadoop/TestHadoopCatalog.java, flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java, spark/src/main/java/org/apache/iceberg/actions/BaseAction.java, spark3/src/main/java/org/apache/iceberg/spark/source/SparkBatchScan.java
In many places we rely on `table.toString()` when we're really looking for the table's name, which is available in another method `table.name()`. Although at the moment, at least when looking at the interface, the two are semantically equivalent, it makes it much more difficult to read the code when seeing so many calls to `table.toString()` when what we're really looking for is the table's name.
This assists with, but does not  necessarily close, issue https://github.com/apache/iceberg/issues/1544. I'm not sure if this has captured all instances where `table.toString` is used when logically `table.name` is what should be requested.
I chose not to update any calls where the table is logged as a parameter, which implicitly uses `toString`, as that's standard behavior. I only updated calls …
=> Replace calls to table.toString with table.name

api/src/main/java/org/apache/iceberg/transforms/Bucket.java, api/src/main/java/org/apache/iceberg/transforms/Truncate.java, api/src/test/java/org/apache/iceberg/transforms/TestBucketing.java, api/src/test/java/org/apache/iceberg/transforms/TestTruncate.java
There was no exception output,when create a partition table with `bucket(colName, 0)` or `bucket(colName, -1)`.
However, when writing data, the following two exceptions occur.
1) Exception in thread "main" java.lang.UnsupportedOperationException: Cannot write using unsupported transforms: bucket[-1]
2) java.lang.ArithmeticException: / by zero
Link: #1543
=> API: add some validation when create bucket/truncate partition

mr/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergFilterFactory.java, mr/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergFilterFactory.java
For me, the test `TestHiveIcebergFilterFactory#testDateType` is failing locally, though it doesnt fail in the CI. So whether or not this needs to be changed is debatable, but this test fails for me when I run it locally.
I've changed the test to use `Date.valueOf("2015-11-12")`, which matches the `Literal.of("2015-11-12")` more closely anyway.
I've also made the string literal for the date its own named argument, under the hopes that possibly these tests could be parameterized some day.
When  I test this on my local, the output of the failing test is 
```
expected:<16751> but was:<16750>
Expected :16751
Actual   :16750
...
org.apache.iceberg.mr.hive.TestHiveIcebergFilterFactory > testDateType FAILED
java.lang.AssertionError: expected:<16751> but was:<16750>
```
=> Remove time-zone dependent call when casting a date via toLocalDate in HiveIcebergFilterFactory

data/src/test/java/org/apache/iceberg/data/TestMetricsRowGroupFilter.java, orc/src/main/java/org/apache/iceberg/orc/OrcMetrics.java
A couple of fixes went into ORC 1.6.4 which allows us to remove workarounds and ignored tests
[ORC-623](https://issues.apache.org/jira/browse/ORC-623): ORC will now correctly skip row groups for notNull predicates
[ORC-661](https://issues.apache.org/jira/browse/ORC-661): ORC now provides timezone agnostic daysFromEpoch, so we no longer need to use reflection
PS: We also have a workaround for [ORC-611](https://issues.apache.org/jira/browse/ORC-611), but I will raise a separate PR for that
=> ORC: Remove workarounds after 1.6.5 upgrade

flink/src/main/java/org/apache/iceberg/flink/source/RowDataIterator.java, spark/src/main/java/org/apache/iceberg/spark/source/RowDataReader.java
This is for discussion [here](https://github.com/apache/iceberg/pull/1517#discussion_r495701495). I don't add the unit test here since the existing end to end unit tests should cover.
=> reuse container when reading parquet records

spark3/src/test/java/org/apache/iceberg/actions/TestExpireSnapshotsAction3.java, spark3/src/test/java/org/apache/iceberg/actions/TestRemoveOrphanFilesAction3.java, spark3/src/test/java/org/apache/iceberg/actions/TestRewriteDataFilesAction3.java, spark3/src/test/java/org/apache/iceberg/actions/TestRewriteManifestsAction3.java
Previously these files lived in o.a.iceberg.spark.actions when they
should be in o.a.iceberg.actions
=> Move Spark3 Action tests to the Correct Package

hive-metastore/src/test/java/org/apache/iceberg/hive/TestHiveMetastore.java, mr/src/test/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandlerBaseTest.java
Last night I was able to reproduce these failures for a while:
```
org.apache.iceberg.mr.hive.TestHiveIcebergStorageHandlerWithHiveCatalog > testJoinTablesParquet FAILED
java.lang.IllegalArgumentException: Failed to executeQuery Hive query SHOW TABLES: Error while compiling statement: FAILED: SemanticException org.apache.thrift.transport.TTransportException: java.net.SocketException: Broken pipe (Write failed)
Caused by:
org.apache.hive.service.cli.HiveSQLException: Error while compiling statement: FAILED: SemanticException org.apache.thrift.transport.TTransportException: java.net.SocketException: Broken pipe (Write failed)
Caused by:
org.apache.hadoop.hive.ql.parse.SemanticException: org.apache.thrift.transport.TTransportException: java.net.SocketException: Broken pipe (Write failed) …
```
=> Hive: Fix TestHiveMetastore worker exhaustion

hive-metastore/src/test/java/org/apache/iceberg/hive/TestHiveMetastore.java, mr/src/test/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandlerBaseTest.java
As discussed in #1620 we should make the pool size configurable
=> Hive: Make the TestHiveMetastore connection pool size configurable

mr/src/main/java/org/apache/iceberg/mr/hive/serde/objectinspector/IcebergObjectInspector.java
To fix https://github.com/apache/iceberg/issues/1630, the ObjectInspector selection logic needs to depend on checking the presence of Hive3 classes on the classpath.
cc @rdblue @massdosage @pvary - thanks for checking!
=> Select correct ObjectInspector based on Hive version on classpath

flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java, flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSink.java
Adding a method in `FlinkSink` to configure write parallelism for iceberg stream writer. It's a comment from here https://github.com/apache/iceberg/issues/1403
=> Flink: Support configuring write parallelims for iceberg stream writer.

parquet/src/main/java/org/apache/iceberg/parquet/ParquetMetricsRowGroupFilter.java, parquet/src/test/java/org/apache/iceberg/parquet/TestCDHParquetStatistics.java
The behvaior of hasNonNull in parquet statistics chagnes based on the
version of the file that the statistics are read from. For binary columns
generated by CDH 1.5.0 to 1.7.0, the function returns hasNonNull as false
even if there are nonNull values in the column. This not an issue for files
written by OSS Parquet because of a seperate bug which prohibts reading these
statistics from Parquet earlier than 1.8.0. The fix for that bug (PARQUET-251)
was backported in to the CDH distribution so it correctly can return statistics
but not in a format that Iceberg is able to handle correctly.
=> Fix Reading of Statistics from old Parquet CDH Versions

spark/src/main/java/org/apache/iceberg/actions/Actions.java, spark2/src/main/java/org/apache/iceberg/actions/SparkActions.java, spark3/src/main/java/org/apache/iceberg/actions/SparkActions.java
Uses reflection in the base Actions class to determine the actual
implementation on the classloader to use. This allows both Spark2
and Spark3 to use different implementations of Actions while not
changing the location of the original Actions class.
=> Seperate Action Implementations into Spark Specific Modules - With Reflection

core/src/main/java/org/apache/iceberg/BaseOverwriteFiles.java, core/src/main/java/org/apache/iceberg/types/FixupTypes.java, data/src/main/java/org/apache/iceberg/data/DeleteFilter.java, spark/src/main/java/org/apache/iceberg/spark/data/SparkOrcValueReaders.java, spark/src/main/java/org/apache/iceberg/spark/data/SparkOrcValueWriters.java
Some small stuff that I found when working on https://github.com/apache/iceberg/pull/1648
=> Fix small issues

site/docs/spark.md, spark3/src/test/java/org/apache/iceberg/spark/sql/TestCreateTableAsSelect.java
Fixes #1410 
- New table properties in replace are merged with existing table properties. Add this behavior to the spark.md doc. 
- Modify an existing RTAS testcase to also test the table properties behavior.
=> Document behavior of table properties in replace table command

spark/src/test/java/org/apache/iceberg/spark/data/TestHelpers.java, spark/src/test/java/org/apache/iceberg/spark/data/parquet/vectorized/TestParquetDictionaryEncodedVectorizedReads.java, spark/src/test/java/org/apache/iceberg/spark/data/parquet/vectorized/TestParquetDictionaryFallbackToPlainEncodingVectorizedReads.java, spark/src/test/java/org/apache/iceberg/spark/data/parquet/vectorized/TestParquetVectorizedReads.java
=> Parquet Vectorized Reads - Test case for exercising reallocation of Arrow buffers to accommodate larger values

build.gradle, mr/src/test/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandlerBaseTest.java, mr/src/test/java/org/apache/iceberg/mr/hive/TestHiveShell.java, versions.props
Had a discussion earlier with @massdosage and @pvary on this topic, and I think it makes sense to introduce a new `TestHiveShell` test class, which basically does the same things as our current HiveRunner/HiveShell. 
The biggest difference is that the new test class can be instantiated once per test suite and does not require its own runner. This leads to a few important advantages over HiveRunner:
- Quicker: due to not having to restart HS2 after each test method, I've noticed a ~20% speed up when using the `TestHiveShell`. This is expected improve further as we're adding more and more test cases to the StorageHandler tests
- Flakyness: not having to recreate the HS2 every time also means fewer chances of something going wrong with the metastore connections (i.e. Broken Pipe intermittent …
=> Use TestHiveShell to run StorageHandler tests. Use Parameterized runner.

parquet/src/main/java/org/apache/iceberg/parquet/ParquetDictionaryRowGroupFilter.java
This PR optimizes the evaluation of IN predicates on dictionary encoded columns in Parquet.
The previous solution relied on `isEmpty` on top of `Sets$intersection`. That, in turn, used `Collections$disjoint(set2, set1)`. The latter checks whether the first argument is a set or not. If yes, it would simply iterate over the second argument ignoring the fact that the second argument can be also a set and may be even bigger. All of that led to the fact that we iterated through all dictionary values to evaluate IN predicates.
=> Parquet: Optimize IN predicates in ParquetDictionaryRowGroupFilter

site/docs/spec.md
This updates the Iceberg spec with requirements for row-level deletes, as implemented in Java.
=> Update the Iceberg spec for row-level deletes

hive-metastore/src/main/java/org/apache/iceberg/hive/HiveCatalogs.java
This removes the time limit that expires cache entries in `HiveCatalogs`. When a catalog is evicted from the cache it is closed, which closes the client pool used by all of the tables loaded by the catalog. Any table still referenced can no longer be used, which breaks some Spark uses that keep DataFrames around.
=> Remove cache expiration in HiveCatalogs cache

build.gradle
This PR wraps the application of the `git-version` plugin into a try-catch block so that we won't fail the build without having the `.git` folder.
=> Build: Support builds without .git directory

core/src/main/java/org/apache/iceberg/hadoop/HadoopTableOperations.java
Under issue #1496 it was already discussed that we should find a way to update version-hint.txt atomically. At the moment, there is no know operation that would support atomic updates. Based on this I think our best solution would be:
1. Create a new file
2. Delete old version-hint.txt
3. Move the new file to version-hint.txt
=> Core: Update version-hint.txt atomically

.github/workflows/labeler.yml
The labeler worked in my fork, but not when I pushed a change to this repo. On further inspection, it seems that the target of the workflow needs to be on `pull_request_target`, so that people who don't have push / write access to the repo can still trigger the workflow.
I found this here: https://github.com/actions/labeler/issues/12
I also need to verify the permissions with ASF infra for `Fork Pull Request Workflows` to ensure that nobody can gain easy access to our secrets (I assume they likely have it set up correctly already, but since this is our first foray into the land of official github workflows, it's possibly best to double check).
=> Change labeler to run on the more secure pull_request_target

spark3/src/test/java/org/apache/iceberg/spark/sql/TestPartitionedWrites.java
This enables a test that was disabled in Spark 3 due to [SPARK-32168](https://issues.apache.org/jira/browse/SPARK-32168).
=> Enable testInsertOverwrite, passing with Spark 3.0.1

core/src/main/java/org/apache/iceberg/ManifestsTable.java
This fixes a small bug in the manifest table for tables that have a current partition spec with more fields than previously used spec.
=> Fix ArrayIndexOutOfBounds for tables with migrated partition specs

core/src/main/java/org/apache/iceberg/SnapshotManager.java
Fixes a minor bug in SnapshotManager validation when the table has no current snapshot.
=> Fix replaced partitions validation in SnapshotManager

core/src/main/java/org/apache/iceberg/AllEntriesTable.java, core/src/main/java/org/apache/iceberg/ManifestEntriesTable.java, core/src/test/java/org/apache/iceberg/TestEntriesMetadataTable.java
Previously the entries metadatat tables would throw an exception if a table
had been modified with a rowDelta and had a delete manifest. To fix this we
switch the reader based on the type of manifest that is being read by the
metadata table so that both type of manifest can be displayed.
=> Entries Tables Working with Delete Manifests

orc/src/main/java/org/apache/iceberg/orc/OrcFileAppender.java
Fixes #1666
There doesn't seem to be a way to get physical file size from the ORC writer itself, so we can do an FS call to get the length. 
cc: @rdblue @zhangjun0x01
=> ORC: OrcFileAppender#length should return file size on disk

core/src/test/java/org/apache/iceberg/TestMetrics.java, data/src/test/java/org/apache/iceberg/data/TestMetricsRowGroupFilterTypes.java, orc/src/main/java/org/apache/iceberg/orc/ExpressionToSearchArgument.java, orc/src/main/java/org/apache/iceberg/orc/OrcMetrics.java, orc/src/test/java/org/apache/iceberg/orc/TestExpressionToSearchArgument.java
Now that [ORC-611](https://issues.apache.org/jira/browse/ORC-611#) is fixed, ORC will store statistics for Timestamp types with nanosecond precision. So we can push down predicates and also rely on timestamp statistics reported back by ORC.
For older ORC files which only contain millisecond precision stats, ORC will subtract/add 1 millisecond to the min/max so that the lower/upper bounds are valid and correctly represent the values in the data.
=> ORC: Enable predicate pushdown and remove metrics workaround for Timestamps

mr/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
This reverts commit 13d94bc2e4e2dcae3d964b98dbb3aaeee19b46c2.
See issue: https://github.com/apache/iceberg/issues/1708
=> Revert "Hive: Fix missing table schema in Hive 1.1 query (#1557)"

data/src/test/java/org/apache/iceberg/data/orc/TestOrcRowIterator.java, orc/src/main/java/org/apache/iceberg/orc/OrcIterable.java, orc/src/main/java/org/apache/iceberg/orc/VectorizedRowBatchIterator.java
ORC non-vectorized code path uses the following condition in `OrcRowIterator#next()` to determine if a new batch should be read and row batch counter should be reset.
`if (batch == null || nextRow >= batch.size)` (Note: the code uses `current` as the variable name instead of `batch`)
Since the batch object is reused, `#hasNext()` can cause a new batch to be loaded in case the existing batch was consumed. In such a case, the condition in `#next()` will cause the row batch counter to be reset. However, if `#hasNext()` was called prior to this, the `batch` variable will already have data loaded for the next batch and so `batch.size` will give size of the newly loaded batch.
In some cases, the batch sizes across batches will remain the same and so the current condition works fine. However, …
=> ORC: Fix non-vectorized reader incorrectly skipping rows

build.gradle, mr/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergSerDe.java, mr/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java, mr/src/test/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandlerBaseTest.java, mr/src/test/java/org/apache/iceberg/mr/hive/TestHiveShell.java, versions.props
Use the execution engine as a test parameter to run all hive storage handler tests with both MR and Tez.
Note: setting the table schema in the global job conf (see https://github.com/apache/iceberg/pull/1557) in `HiveIcebergStorageHandler#configureJobConf()` meant that whichever table called this function last, ended up having its schema stored in the global conf. Then in `HiveIcebergSerde#initialize()`, the schema was taken from the conf when present, but that led to failures since all tables were now using the schema of the table that was the "winner" (setting its schema last in the previous step). To keep the caching nonetheless, I'm now storing and retrieving the schemas of each table separately with no risk of overwriting.
I can't rule out that there are other issues with how job …
=> Run all StorageHandler tests with both MR and Tez

site/docs/spark.md
I've found the type compatibility being asymmetric among the cases, and it required me to look into the code to find the conversions (TypeToSparkType, SparkTypeToType).
Given the conversions won't change frequently, it'd be nice to document the conversions so that end users don't feel surprised. This would be also helpful if end users consider using same Iceberg table across components - end users will have a clear view of the types when they create an Iceberg table from Spark, when they read an Iceberg table from Spark, when they write to the Iceberg table via Spark.
Probably it might be ideal to have such type compatibility matrixes for all supported components, so that end users can look into these matrixes and check type issues on interop.
=> DOCS: describe type compatibility between Spark and Iceberg

api/src/main/java/org/apache/iceberg/SortField.java, api/src/main/java/org/apache/iceberg/SortOrder.java, api/src/main/java/org/apache/iceberg/expressions/Expressions.java, api/src/main/java/org/apache/iceberg/transforms/Dates.java, api/src/main/java/org/apache/iceberg/transforms/Identity.java, api/src/main/java/org/apache/iceberg/transforms/PartitionSpecVisitor.java, api/src/main/java/org/apache/iceberg/transforms/SortOrderVisitor.java, api/src/main/java/org/apache/iceberg/transforms/Timestamps.java, api/src/main/java/org/apache/iceberg/transforms/Transform.java, api/src/main/java/org/apache/iceberg/transforms/Truncate.java, core/src/main/java/org/apache/iceberg/CopySortOrderFields.java, core/src/main/java/org/apache/iceberg/Partitioning.java, core/src/test/java/org/apache/iceberg/TestSortOrder.java, spark3/src/main/java/org/apache/iceberg/spark/Spark3Util.java
This updates the partitioning and sort order API with utilities needed for required distribution and ordering.
* Adds `Expressions.transform` to create an `UnboundTransform` term from an existing `Transform` and a field name
* Adds `SortField.satisfies` and `Transform.satisfiesOrderOf` to implement satisfies between compatible fields, like days and hours. Hours satisfies the ordering of days
* Updates `PartitionSpecVisitor` to pass partition field IDs and adds `unknown` and `alwaysNull` visitor methods.
* Adds `SortOrderVisitor` to visit a sort order
* Adds `Partitioning` helper methods `hasBucketField(PartitionSpec)` and `sortOrderFor(PartitionSpec)`
* Adds `CopySortOrderFields` visitor to copy a sort order fields to a sort order builder
=> API: Extend partitioning and sort order

api/src/main/java/org/apache/iceberg/catalog/Catalog.java, core/src/main/java/org/apache/iceberg/CatalogProperties.java, core/src/main/java/org/apache/iceberg/CatalogUtil.java, core/src/test/java/org/apache/iceberg/TestCatalogUtil.java, flink/src/main/java/org/apache/iceberg/flink/CatalogLoader.java, flink/src/main/java/org/apache/iceberg/flink/FlinkCatalogFactory.java, spark3/src/main/java/org/apache/iceberg/spark/SparkCatalog.java
As we are having multiple new Catalog implementations added to Iceberg, we need a way to load those Catalogs in Spark and Flink easily. Currently there is a simple switch branch that chooses between `hive` and `hadoop` catalogs. This approach requires the `iceberg-spark` and `iceberg-flink` module to take a dependency on the catalog implementation modules. This would potentially bring in many unnecessary dependencies as more and more cloud providers try to add support for Iceberg.
This PR proposes the following way to load custom Catalog implementations:
1. the `type` of a catalog can be `hive` or `hadoop` to keep existing behaviors
2. if `catalog-impl` is set, `type` is ignored and we will load catalog based on the class value
3. A catalog must have a no-arg constructor be initialized by …
=> Allow loading custom Catalog implementation in Spark and Flink

api/src/main/java/org/apache/iceberg/io/FileIO.java, core/src/main/java/org/apache/iceberg/CatalogProperties.java, core/src/main/java/org/apache/iceberg/CatalogUtil.java, core/src/main/java/org/apache/iceberg/hadoop/HadoopCatalog.java, core/src/main/java/org/apache/iceberg/hadoop/HadoopTableOperations.java, core/src/main/java/org/apache/iceberg/hadoop/HadoopTables.java, core/src/test/java/org/apache/iceberg/TestCatalogUtil.java, flink/src/main/java/org/apache/iceberg/flink/CatalogLoader.java, flink/src/main/java/org/apache/iceberg/flink/FlinkCatalogFactory.java, flink/src/test/java/org/apache/iceberg/flink/FlinkCatalogTestBase.java, flink/src/test/java/org/apache/iceberg/flink/TestCatalogTableLoader.java, flink/src/test/java/org/apache/iceberg/flink/TestFlinkHiveCatalog.java, flink/src/test/java/org/apache/iceberg/flink/source/TestFlinkInputFormatReaderDeletes.java, hive-metastore/src/main/java/org/apache/iceberg/hive/HiveCatalog.java, hive-metastore/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java, spark3/src/main/java/org/apache/iceberg/spark/SparkCatalog.java
- refactor the class loader logic in `LocationProviders` to a util class
- add functionality to dynamically load FileIO in Hadoop and Hive table operations
- introduce a catalog property `io-impl`
=> dynamically load custom FileIO implementation

.github/workflows/license_check.yml
The workflow is currently failing because `dev/check-license` is not present.
=> Add checkout step to rat check action

core/src/main/java/org/apache/iceberg/ManifestReader.java, core/src/test/java/org/apache/iceberg/TestManifestReader.java, spark/src/test/java/org/apache/iceberg/spark/source/TestSparkReaderDeletes.java
This fixes a `NullPointerException` that is thrown by a `ManifestReader` for delete files when there is a query filter. The `DeleteFileIndex` projects all fields of a delete manifest, so it doesn't call `select` to select specific columns, unlike `ManifestGroup`, which selects `*` by default. When select is not called, methods that check whether to add stats columns fail, but only if there is a row filter because stats columns are not needed if there is no row filter.
Existing tests either called `select` to configure the reader, or didn't pass a row filter and projected all rows. This adds a test that uses `DeleteFileIndex` and a test for `ManifestReader`. This also fixes `dropStats` in addition to `requireStatsProjection`.
Closes #1726, #1724.
Co-authored-by: 钟保罗 …
=> Fix NullPointerException in ManifestReader

api/src/main/java/org/apache/iceberg/expressions/Expressions.java, api/src/test/java/org/apache/iceberg/expressions/TestEvaluator.java
Noticed this copy paste issue while updating `Expressions`. Verified that no code is actually using it, so updating it shouldn't impact any test.
=> API: one line fix in Expressions with tests

site/docs/configuration.md, site/docs/custom-catalog.md, site/docs/flink.md, site/docs/spark.md
- added new sections in `custom catalog` about implementing custom `FileIO` and `LocationProvider`, with some more details around how to load the custom classes.
- added a new section in `Configuration` about catalog properties
- added a new section in `Spark` about loading a custom catalog
- added a new section in `Flink` about creating a custom catalog
=> Docs: add documentation related to dynamic class loading

parquet/src/main/java/org/apache/iceberg/parquet/ParquetReader.java, parquet/src/main/java/org/apache/iceberg/parquet/ReadConf.java
This is used to avoid reading all row group metadata if the position metadata column is not projected.
=> Read all row group metadata only when position column is projected

site/docs/presto.md
Current and relatively complete documentation for the Iceberg Presto
connector was added to Presto in July.  This PR removes the pointer
to the obsolete Presto README.md file, and changes the link to point
to the Iceberg Presto connector documentation.
=> Update Presto documentation link

versions.props
Apache Arrow 2.0 has been released. For Java nothing big has changed.
Changelog: http://arrow.apache.org/blog/2020/10/22/2.0.0-release/
=> Bump to Apache Arrow 2.0

api/src/main/java/org/apache/iceberg/ContentFile.java, api/src/test/java/org/apache/iceberg/TestHelpers.java, core/src/main/java/org/apache/iceberg/BaseFile.java, core/src/main/java/org/apache/iceberg/ManifestReader.java, core/src/main/java/org/apache/iceberg/V1Metadata.java, core/src/main/java/org/apache/iceberg/V2Metadata.java, core/src/main/java/org/apache/iceberg/avro/GenericAvroReader.java, core/src/main/java/org/apache/iceberg/avro/ValueReaders.java, core/src/test/java/org/apache/iceberg/TestManifestReader.java, spark/src/main/java/org/apache/iceberg/spark/SparkDataFile.java
This updates `ManifestReader` to project the file position metadata column so that `DataFile` and `DeleteFile` objects read from manifests include the position within the manifest. This is in support of streaming reads, where the data in a table is turned into a stream of snapshots, then new manifests, then data files. The position of each file in a manifest can be encoded as a recoverable offset.
=> Add position in manifest to DataFile and DeleteFile

hive3/src/main/java/org/apache/iceberg/mr/hive/serde/objectinspector/IcebergDateObjectInspectorHive3.java, hive3/src/main/java/org/apache/iceberg/mr/hive/serde/objectinspector/IcebergTimestampObjectInspectorHive3.java, mr/src/main/java/org/apache/iceberg/mr/hive/serde/objectinspector/IcebergBinaryObjectInspector.java, mr/src/main/java/org/apache/iceberg/mr/hive/serde/objectinspector/IcebergDateObjectInspector.java, mr/src/main/java/org/apache/iceberg/mr/hive/serde/objectinspector/IcebergDecimalObjectInspector.java, mr/src/main/java/org/apache/iceberg/mr/hive/serde/objectinspector/IcebergTimestampObjectInspector.java, mr/src/test/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandlerBaseTest.java
The following casting exceptions were observed when joining two Iceberg tables on Tez:
- java.math.BigDecimal cannot be cast to org.apache.hadoop.hive.common.type.HiveDecimal
- java.time.OffsetDateTime cannot be cast to org.apache.hadoop.hive.common.type.Timestamp
- java.nio.HeapByteBuffer cannot be cast to [B
- java.time.LocalDate cannot be cast to org.apache.hadoop.hive.common.type.Date
Doesn't happen with Iceberg table - non-Iceberg table joins, or with order by queries on a single table.
=> Fix casting issues when joining two Iceberg tables together on Tez

aws/src/main/java/org/apache/iceberg/aws/AwsClientUtil.java, aws/src/main/java/org/apache/iceberg/aws/s3/S3FileIO.java, aws/src/main/java/org/apache/iceberg/aws/s3/S3OutputStream.java, aws/src/test/java/org/apache/iceberg/aws/s3/S3OutputStreamTest.java, aws/src/test/java/org/apache/iceberg/aws/s3/S3URITest.java, build.gradle, versions.props
When used in `BaseMetastoreTableOperations`, in `TableMetadataParser.internalWrite()`, an output stream is closed twice because of the closure of the output stream and its writer:
```
try (OutputStream ou = isGzip ? new GZIPOutputStream(stream) : stream;
OutputStreamWriter writer = new OutputStreamWriter(ou, StandardCharsets.UTF_8)) {
...
}
```
This causes issue in `S3OutputStream` because the stream uploads the file from local to S3 during the call to close.
Also, `S3FileIO` cannot be properly initialized when there are multiple HTTP client builders available in the Java class path at runtime, so `AwsClientUtil` is used to provide a stable default client for `S3FileIO` to use.
=> AWS: fix bugs around using S3FileIO for table operations

LICENSE, project/scalastyle_config.xml, spark3-extensions/src/main/scala/org/apache/iceberg/spark/extensions/IcebergSparkSessionExtensions.scala, spark3-extensions/src/main/scala/org/apache/spark/sql/catalyst/analysis/ResolveProcedures.scala, spark3-extensions/src/main/scala/org/apache/spark/sql/catalyst/plans/logical/Call.scala, spark3-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/CallExec.scala, spark3-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/ExtendedDataSourceV2Strategy.scala, spark3/src/main/java/org/apache/spark/sql/catalyst/analysis/NoSuchProcedureException.java, spark3/src/main/java/org/apache/spark/sql/connector/catalog/Procedure.java, spark3/src/main/java/org/apache/spark/sql/connector/catalog/ProcedureCatalog.java, spark3/src/main/java/org/apache/spark/sql/connector/catalog/ProcedureParameter.java, spark3/src/main/java/org/apache/spark/sql/connector/catalog/ProcedureParameterImpl.java
This PR adds the stored procedure API.
The actual implementation in Iceberg and tests will come in a separate PR.
Resolves #1593.
=> Spark: Add stored procedure API

hive-metastore/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java, hive-metastore/src/test/java/org/apache/iceberg/hive/HiveTableTest.java
Some engines (e.g. Impala) depend on the Input/Output format classes
being set in the HMS storage descriptor.
=> Set Input/Output formats for the HMS storage descriptor

site/mkdocs.yml
At @blue's suggestion, this PR changes site/mkdocs.yml to link directly
to the Presto connector documentation.  On @electrum's advice,  it leaves
docs/presto.md in place, in case folks link to it directly.
=> Link directly to Presto connector  doc

flink/src/main/java/org/apache/iceberg/flink/actions/RewriteDataFilesAction.java
We should add the `maxParallelism` method to the method chain so that users can set some Action parameters easily.
=> Flink: add maxParallelism method to method chain in flink RewriteDataFilesAction

spark3-extensions/src/main/scala/org/apache/spark/sql/catalyst/analysis/ResolveProcedures.scala, spark3-extensions/src/main/scala/org/apache/spark/sql/catalyst/plans/logical/Call.scala, spark3-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/CallExec.scala, spark3/src/main/java/org/apache/spark/sql/connector/iceberg/catalog/Procedure.java, spark3/src/main/java/org/apache/spark/sql/connector/iceberg/catalog/ProcedureCatalog.java, spark3/src/main/java/org/apache/spark/sql/connector/iceberg/catalog/ProcedureParameter.java, spark3/src/main/java/org/apache/spark/sql/connector/iceberg/catalog/ProcedureParameterImpl.java
This PR moves connector interfaces to avoid conflicts when these interfaces appear in Spark.
=> Spark: Move connector classes to avoid conflicts

baseline.gradle
After `iceberg-spark3-extensions` module is added, there are a ton of warnings emitted during build because of the generated files by antlr. This change avoids running errorprone for generated files in any `generated-src` directory.
=> Ignore generated-src directory in errorprone

flink/src/test/java/org/apache/iceberg/flink/TestFlinkCatalogTable.java
I think we should add `super.clean();` for TestFlinkCatalogTable#After method
=> add clean for TestFlinkCatalogTable

spark3-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestCherrypickSnapshotProcedure.java, spark3/src/main/java/org/apache/iceberg/spark/procedures/CherrypickSnapshotProcedure.java, spark3/src/main/java/org/apache/iceberg/spark/procedures/SparkProcedures.java
This PR adds a procedure to cherry-pick a snapshot.
Resolves #1595.
=> Spark: Add CherrypickSnapshotProcedure

spark3-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestSetCurrentSnapshotProcedure.java, spark3/src/main/java/org/apache/iceberg/spark/procedures/SetCurrentSnapshotProcedure.java, spark3/src/main/java/org/apache/iceberg/spark/procedures/SparkProcedures.java
This PR adds a procedure to set the current snapshot in a table.
Resolves #1596.
=> Spark: Add SetCurrentSnapshotProcedure

spark/src/test/java/org/apache/iceberg/spark/SparkTestBase.java, spark3-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRollbackToTimestampProcedure.java, spark3/src/main/java/org/apache/iceberg/spark/procedures/RollbackToTimestampProcedure.java, spark3/src/main/java/org/apache/iceberg/spark/procedures/SparkProcedures.java
This PR adds a procedure to rollback a table to a given point in time.
Resolves #1594.
=> Spark: Add RollbackToTimestampProcedure

aws/src/integration/java/org/apache/iceberg/aws/AwsIntegTestUtil.java, aws/src/integration/java/org/apache/iceberg/aws/s3/S3FileIOTest.java, aws/src/main/java/org/apache/iceberg/aws/AwsClientUtil.java, aws/src/main/java/org/apache/iceberg/aws/AwsProperties.java, aws/src/main/java/org/apache/iceberg/aws/s3/BaseS3File.java, aws/src/main/java/org/apache/iceberg/aws/s3/S3FileIO.java, aws/src/main/java/org/apache/iceberg/aws/s3/S3InputFile.java, aws/src/main/java/org/apache/iceberg/aws/s3/S3InputStream.java, aws/src/main/java/org/apache/iceberg/aws/s3/S3OutputFile.java, aws/src/main/java/org/apache/iceberg/aws/s3/S3OutputStream.java, build.gradle
- add support for server side encryption (3 types: S3, KMS, Custom) for `S3FileIO`
- add corresponding integration tests
- add `AwsCatalogProperties` as the centralized place to put all AWS related catalog properties
- also fix warnings in `S3URI`
=> AWS: support Server Side Encryption for S3FileIO

api/src/main/java/org/apache/iceberg/events/IncrementalScanEvent.java, core/src/main/java/org/apache/iceberg/IncrementalDataTableScan.java, core/src/test/java/org/apache/iceberg/TestIncrementalDataTableScan.java
Fixes #1711 
Changes include: 
- Create a new `IncrementalScanEvent` to keep track of the `from` and `to` snapshot id
- Publish the `IncrementalScanEvent` in` IncrementalDataTableScan` and remove the todo
Tests:
- Modify an existing test to check that the event is being published.
=> Publish incremental scan event during planning

hive3/src/test/resources/log4j2.properties, mr/src/test/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandlerBaseTest.java, mr/src/test/resources/log4j.properties, mr/src/test/resources/log4j2.properties
- Current log4j properties is only used by Hive2 and DataNucleus but not Hive3 -> adding a log4j2 props file to drive logging configuration for Hive3
- Changing root log level to warn to remove log noise (e.g. datanucleus debug logs), this can be tuned back to lower levels whenever debugging is needed
- Enabling a flag to print execution summary and counter values for Tez queries (DAG stages, execution times, number of records/bytes read/written, etc.)
cc @rdblue @pvary
=> Improve log settings in Hive unit tests

.baseline/checkstyle/checkstyle.xml, spark/src/main/java/org/apache/iceberg/actions/BaseSparkAction.java, spark/src/main/java/org/apache/iceberg/actions/RewriteManifestsAction.java, spark/src/test/java/org/apache/iceberg/actions/TestRemoveOrphanFilesAction.java, spark3/src/test/java/org/apache/iceberg/actions/TestRemoveOrphanFilesAction3.java
Previously the Action code would use the table name when attempting to look
up MetadataTable names. This is an issue in Spark3 with V2 catalogs because
we strip off the catalog information if the catalog is named "hadoop" or "hive"
and include it in all other cases. When we include the catalog name this breaks
the lookup code which uses the DataSourceRegistry pathway and not the V2 Table
pathway. To fix this we introduce a method for using the V2 pathway when a catalog
name is present.
=> Fix Actions to be Compatible with V2 Catalogs

flink/src/test/java/org/apache/iceberg/flink/SimpleDataUtil.java
if the parameter `List<Record>` contains repeated data, the `Set` will remove the duplicates, which is different from our expected value,we should compare the original list
=> Flink: Refactor SimpleDataUtil#assertTableRecords method

aws/src/integration/java/org/apache/iceberg/aws/AwsIntegTestUtil.java, aws/src/integration/java/org/apache/iceberg/aws/glue/GlueCatalogNamespaceTest.java, aws/src/integration/java/org/apache/iceberg/aws/glue/GlueCatalogTableTest.java, aws/src/integration/java/org/apache/iceberg/aws/glue/GlueTestBase.java, aws/src/main/java/org/apache/iceberg/aws/AwsClientUtil.java, aws/src/main/java/org/apache/iceberg/aws/AwsProperties.java, aws/src/main/java/org/apache/iceberg/aws/glue/GlueCatalog.java, aws/src/main/java/org/apache/iceberg/aws/glue/GlueTableOperations.java, aws/src/main/java/org/apache/iceberg/aws/glue/GlueToIcebergConverter.java, aws/src/main/java/org/apache/iceberg/aws/glue/IcebergToGlueConverter.java, aws/src/test/java/org/apache/iceberg/aws/glue/GlueCatalogTest.java, aws/src/test/java/org/apache/iceberg/aws/glue/GlueToIcebergConverterTest.java, aws/src/test/java/org/apache/iceberg/aws/glue/IcebergToGlueConverterTest.java, build.gradle
- Add `GlueCatalog` and `GlueTableOperations` implementations
- Fix bugs found in `S3FileIO` and add more tests
- add `:integrationTest` task to run integration tests for the `aws` module.
=> AWS Glue catalog and table operations

spark/src/main/java/org/apache/iceberg/actions/BaseSparkAction.java, spark3/src/main/java/org/apache/iceberg/spark/Spark3Util.java, spark3/src/test/java/org/apache/iceberg/actions/TestRemoveOrphanFilesAction3.java
Do to an issue within Spark's Resolution rules we cannot acces a table in the session
catalog with a multipart identifier. Because we also cannot determine whether the underlying
Iceberg table is Hadoop or Hive based we also cannot know the right method for reading the
table. To work around this for now we attempt to first load the table as a HiveTable, if
the table isn't found we fall back and attempt to load it as a Hadoop table.
=> Fix Resolving of SparkSession Table's Metadata Tables

aws/src/main/java/org/apache/iceberg/aws/s3/S3URI.java
fix errorprone warnings in S3URI：
```
/iceberg/aws/src/main/java/org/apache/iceberg/aws/s3/S3URI.java:60: warning: [StringSplitter] String.split(String) has surprising behavior
String [] schemeSplit = location.split(SCHEME_DELIM);
^
(see https://errorprone.info/bugpattern/StringSplitter)
Did you mean 'List<String> schemeSplit = Splitter.onPattern(SCHEME_DELIM).splitToList(location);'?
/iceberg/aws/src/main/java/org/apache/iceberg/aws/s3/S3URI.java:73: warning: [StringSplitter] String.split(String) has surprising behavior
path = path.split(QUERY_DELIM)[0];
^
(see https://errorprone.info/bugpattern/StringSplitter)
Did you mean 'path = Iterables.get(Splitter.onPattern(QUERY_DELIM).split(path), 0);'?
/iceberg/aws/src/main/java/org/apache/iceberg/aws/s3/S3URI.java:74: warning: [StringSplitter] …
```
=> AWS: fix errorprone warnings in S3URI

aws/src/main/java/org/apache/iceberg/aws/AwsProperties.java, aws/src/main/java/org/apache/iceberg/aws/s3/S3FileIO.java, aws/src/main/java/org/apache/iceberg/aws/s3/S3InputStream.java, aws/src/main/java/org/apache/iceberg/aws/s3/S3OutputStream.java, aws/src/main/java/org/apache/iceberg/aws/s3/S3RequestUtil.java, aws/src/test/java/org/apache/iceberg/aws/s3/S3OutputStreamTest.java, bundled-guava/src/main/java/org/apache/iceberg/GuavaClasses.java, core/src/main/java/org/apache/iceberg/util/PropertyUtil.java
Add progressive upload to S3OutputStream using multipart upload.
A few key changes are:
1. The output stream will switch from single PUT based upload to multipart when the multipart size * threshold is reached.
2. Staging files will be rotated and uploaded async as output written
3. Staging files will be deleted when the upload completes to reduce local disk requirements
4. An attempt will be made to abort the upload upon failure, but this is not guaranteed (Bucket lifecycle rules should be implemented to ensure data is cleaned up.)
=> AWS: Add progressive multipart upload to S3FileIO

core/src/main/java/org/apache/iceberg/util/StructLikeSet.java
When I prepare the patch for flink cdc write flow (https://github.com/apache/iceberg/pull/1663/files),  I found the `StructLikeSet` had the following issues: 
1.  It does not provide several common methods, such as `toString()`, `equals`, `hashCode`  etc.   It's useful for testing.  So I make it extend the `AbstractSet`. 
2. In the `remove` method,  we did the instanceof incorrectly.
=> Core: Improve the utility StructLikeSet.

mr/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
We can reduce the number of HMS calls by caching the table schema in the table properties during query execution. 
In `HiveIcebergSerDe.initialize()`, this results in skipping the HMS calls in all Tez workers as well as during the query optimisation steps. In the `testJoinTable()` unit test, this results in a 40% reduction in schema-related HMS calls (10 -> 6).
@shardulm94 @pvary - could you please take a look when you get the chance? Thanks!
=> Reduce number of calls to fetch table schema from HMS

spark3/src/main/java/org/apache/iceberg/spark/procedures/BaseProcedure.java, spark3/src/main/java/org/apache/iceberg/spark/procedures/CherrypickSnapshotProcedure.java, spark3/src/main/java/org/apache/iceberg/spark/procedures/RollbackToSnapshotProcedure.java, spark3/src/main/java/org/apache/iceberg/spark/procedures/RollbackToTimestampProcedure.java, spark3/src/main/java/org/apache/iceberg/spark/procedures/SetCurrentSnapshotProcedure.java
This PR adds `newInternalRow` to `BaseProcedure` to unify construction of `InternalRow`s in procedures.
=> Spark: Add newInternalRow to BaseProcedure

spark3-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRewriteManifestsProcedure.java, spark3/src/main/java/org/apache/iceberg/spark/procedures/RewriteManifestsProcedure.java, spark3/src/main/java/org/apache/iceberg/spark/procedures/SparkProcedures.java
This PR adds a procedure to rewrite manifests.
This is a temporary solution that rewrites all metadata until we figure out how to determine the clustering ratio of metadata.
=> Spark: Add RewriteManifestsProcedure

aws/src/main/java/org/apache/iceberg/aws/s3/BaseS3File.java, aws/src/main/java/org/apache/iceberg/aws/s3/S3RequestUtil.java, aws/src/test/java/org/apache/iceberg/aws/s3/S3RequestUtilTest.java
Try to address issue in #1767 for different request types to set encryption information.
=> AWS: centralize logic for setting encryption info

aws/src/integration/java/org/apache/iceberg/aws/s3/S3FileIOTest.java, aws/src/main/java/org/apache/iceberg/aws/AwsProperties.java, aws/src/main/java/org/apache/iceberg/aws/s3/S3OutputStream.java, aws/src/main/java/org/apache/iceberg/aws/s3/S3RequestUtil.java, aws/src/test/java/org/apache/iceberg/aws/AwsPropertiesTest.java
As discussed in #1767 with @danielcweeks and @johnclara, add ACL support for `S3FileIO`
=> AWS: add ACL support for S3FileIO

api/src/main/java/org/apache/iceberg/ContentFile.java, api/src/main/java/org/apache/iceberg/DataFile.java, api/src/test/java/org/apache/iceberg/TestHelpers.java, core/src/main/java/org/apache/iceberg/BaseFile.java, core/src/main/java/org/apache/iceberg/DataFiles.java, core/src/main/java/org/apache/iceberg/DataTableScan.java, core/src/main/java/org/apache/iceberg/FileMetadata.java, core/src/main/java/org/apache/iceberg/GenericDataFile.java, core/src/main/java/org/apache/iceberg/GenericDeleteFile.java, core/src/main/java/org/apache/iceberg/ManifestReader.java, core/src/main/java/org/apache/iceberg/MetricsModes.java, core/src/main/java/org/apache/iceberg/V1Metadata.java, core/src/main/java/org/apache/iceberg/V2Metadata.java, core/src/test/java/org/apache/iceberg/TestManifestReaderStats.java, core/src/test/java/org/apache/iceberg/TestManifestWriterVersions.java, core/src/test/java/org/apache/iceberg/TestMetrics.java, spark/src/main/java/org/apache/iceberg/spark/SparkDataFile.java, spark/src/test/java/org/apache/iceberg/TestDataFileSerialization.java, spark/src/test/java/org/apache/iceberg/spark/source/TestSparkDataFile.java
- counterpart of https://github.com/apache/iceberg/pull/1747
- will only add the new count in V2 table
- also added some tests for stats handling in manifest reader
=> Add NaN value count to content file

spark3/src/main/java/org/apache/iceberg/spark/procedures/BaseProcedure.java
This PR makes refresh of Spark cache optional in procedures for procedures like remove orphan files.
=> Spark: Make refresh of Spark cache optional in procedures

data/src/test/java/org/apache/iceberg/data/orc/TestGenericData.java, orc/src/main/java/org/apache/iceberg/orc/ORCSchemaUtil.java
In the Iceberg spec we mention
> ORC tinyint and smallint would also map to int
> ORC varchar and char would also map to string
However, trying to read such data currently throws errors
```
java.lang.IllegalArgumentException: Can not promote VARCHAR type to STRING
at org.apache.iceberg.relocated.com.google.common.base.Preconditions.checkArgument(Preconditions.java:441)
at org.apache.iceberg.orc.ORCSchemaUtil.buildOrcProjection(ORCSchemaUtil.java:302)
```
Iceberg does not write CHAR and VARCHAR, but this data may exist in files written by non-Iceberg writers imported into Iceberg. This PR adds support in `buildOrcProjection` for such types.
=> ORC: Allow reads of tinyint, smallint, char, varchar types

python/tests/api/expressions/test_inclusive_manifest_evaluator.py
There is a missing `assert` in the test, rendering the comparison pointless.
=> Make the CI happy

core/src/main/java/org/apache/iceberg/TableProperties.java, core/src/main/java/org/apache/iceberg/io/PartitionedFanoutWriter.java, flink/src/main/java/org/apache/iceberg/flink/sink/RowDataTaskWriterFactory.java, site/docs/configuration.md, spark/src/main/java/org/apache/iceberg/spark/source/RowDataRewriter.java, spark/src/main/java/org/apache/iceberg/spark/source/SparkPartitionedFanoutWriter.java, spark/src/test/java/org/apache/iceberg/spark/source/TestSparkDataWrite.java, spark2/src/main/java/org/apache/iceberg/spark/source/Writer.java, spark3/src/main/java/org/apache/iceberg/spark/source/SparkWrite.java
Changes involved in this PR:
1. Move the `PartitionedFanoutWriter` of flink to `core/src/main/java/org/apache/iceberg/io` package.
2. Implement immobile writers for spark2 and spark3 modules respectively.
3. User can turn it on according to the parameter `write.partitioned.fanout.enabled= true` in the setting table. The default is false and can also set spark option `partitioned.fanout.enabled` to override it.
=> [iceberg-1746] Implement spark fanout writer

core/src/main/java/org/apache/iceberg/BaseMetastoreCatalog.java
As discussed we should deprecate this in 0.11.0:
--------------
Because this was `protected`, I think we should keep it and just delegate to where the method moved. We can also deprecated it and set a version when it will be removed:
```
/**
* ...
* @deprecated will be removed in 0.11.0; use CatalogUtil.dropTableData instead.
*/
```
--------------
_Originally posted by @rdblue in https://github.com/apache/iceberg/pull/1481#discussion_r493965672_
=> Remove deprecated BaseMetastoreCatalog.dropTableData

core/src/main/java/org/apache/iceberg/avro/AvroSchemaUtil.java, core/src/main/java/org/apache/iceberg/avro/SchemaToType.java, core/src/test/java/org/apache/iceberg/avro/TestSchemaConversions.java
Currently trying to convert avro schemas to iceberg schemas fails for avro schemas containing timestamps but without the `adjust-to-utc` annotations. 
```
val icebergSchema = AvroSchemaUtil.toIceberg(avroSchema)
Exception in thread "main" java.lang.IllegalArgumentException: Invalid value for adjust-to-utc: null
at org.apache.iceberg.relocated.com.google.common.base.Preconditions.checkArgument(Preconditions.java:217)
at org.apache.iceberg.avro.SchemaToType.primitive(SchemaToType.java:185)
```
The [avro spec](https://avro.apache.org/docs/current/spec.html#Timestamp+%28microsecond+precision%29) says the `timestamp-millis` and `timestamp-micros` types represent an instant on the global timeline, and this aligns with the [timestamp iceberg …
=> Add support for converting avro schemas containing timestamps without the adjust-to-utc annotations

site/docs/api.md
- Fix typos and minor wording change in api.md
=> Docs: Fix typos in api.md 

spark3-extensions/src/main/scala/org/apache/iceberg/spark/extensions/IcebergSparkSessionExtensions.scala, spark3-extensions/src/main/scala/org/apache/spark/sql/catalyst/analysis/DeleteFromTablePredicateCheck.scala, spark3-extensions/src/main/scala/org/apache/spark/sql/catalyst/optimizer/OptimizeConditionsInRowLevelOperations.scala, spark3-extensions/src/main/scala/org/apache/spark/sql/catalyst/optimizer/PullupCorrelatedPredicatesInRowLevelOperations.scala, spark3-extensions/src/main/scala/org/apache/spark/sql/catalyst/optimizer/RewriteDelete.scala, spark3-extensions/src/main/scala/org/apache/spark/sql/catalyst/plans/logical/DynamicFileFilter.scala, spark3-extensions/src/main/scala/org/apache/spark/sql/catalyst/plans/logical/ReplaceData.scala, spark3-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/DynamicFileFilterExec.scala, spark3-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/ExtendedBatchScanExec.scala, spark3-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/ExtendedDataSourceV2Implicits.scala, spark3-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/ExtendedDataSourceV2Strategy.scala, spark3-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/ReplaceDataExec.scala
This PR adds the core logic for executing DELETE statements in Spark.
=> Spark: Add plans & rules for DELETE

spark3-extensions/src/main/scala/org/apache/iceberg/spark/extensions/IcebergSparkSessionExtensions.scala, spark3-extensions/src/main/scala/org/apache/spark/sql/catalyst/analysis/ProcedureArgumentCoercion.scala, spark3-extensions/src/main/scala/org/apache/spark/sql/catalyst/analysis/ResolveProcedures.scala, spark3-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestCherrypickSnapshotProcedure.java, spark3-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRollbackToSnapshotProcedure.java, spark3-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRollbackToTimestampProcedure.java, spark3-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestSetCurrentSnapshotProcedure.java
This PR fixes the resolution of procedures that contain expressions as arguments.
=> Spark: Fix resolution of procedures with expressions

spark3-extensions/src/main/antlr/org.apache.spark.sql.catalyst.parser.extensions/IcebergSqlExtensions.g4, spark3-extensions/src/main/scala/org/apache/spark/sql/catalyst/parser/extensions/IcebergSparkSqlExtensionsParser.scala, spark3-extensions/src/main/scala/org/apache/spark/sql/catalyst/parser/extensions/IcebergSqlExtensionsAstBuilder.scala, spark3-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestCallStatementParser.java
Previously we would always delegate to the Spark parser, even when a
CALL request could not be parsed. This leads to confusing errors which
would state that "CALL" was not a good first token. This change has us
only using the custom parser for "CALL" commands and delegating for
everything else.
Fixes #1855
=> #1855 : When we fail to parse a "CALL" command provide a better error message

aws/src/integration/java/org/apache/iceberg/aws/s3/S3FileIOTest.java, aws/src/main/java/org/apache/iceberg/aws/s3/BaseS3File.java, aws/src/main/java/org/apache/iceberg/aws/s3/S3InputFile.java, aws/src/main/java/org/apache/iceberg/aws/s3/S3RequestUtil.java, aws/src/test/java/org/apache/iceberg/aws/s3/S3FileIOTest.java
AWS released S3 strong consistency, and now all LIST and GET are strongly consistent. So we can use a LIST to force strong consistency before performing a HEAD for `exists()` check.
More details: https://aws.amazon.com/blogs/aws/amazon-s3-update-strong-read-after-write-consistency/
=> AWS: support S3 strong consistency

spark2/src/main/java/org/apache/iceberg/spark/source/Reader.java, spark3/src/main/java/org/apache/iceberg/spark/Spark3Util.java
Since enabling vectorized reads internally, we have come across a couple of issues listed below that provide motivation for adding a session level control for enabling/disabling vectorized reads:
1) For some pyspark jobs we have noticed that certain libraries like Pandas were not able to handle ColumnarBatch being returned by Iceberg correctly. 
For example in Spark 2.4.4, the below call failed:
```
spark_df.toPandas() 
```
with
```
java.lang.ClassCastException: org.apache.spark.sql.vectorized.ColumnarBatch cannot be cast to org.apache.spark.sql.catalyst.InternalRow
at org.apache.spark.sql.execution.datasources.v2.DataSourceV2ScanExecBase$$anonfun$doExecute$1.apply(DataSourceV2ScanExecBase.scala:71)
at scala.collection.Iterator$$anon$11.next(Iterator.scala:410)
at …
```
=> Parquet - Add a spark session configuration for controlling enabling vectorized reads

spark3-extensions/src/test/java/org/apache/iceberg/spark/extensions/SparkExtensionsTestBase.java, spark3-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRemoveOrphanFilesProcedure.java, spark3/src/main/java/org/apache/iceberg/spark/procedures/RemoveOrphanFilesProcedure.java, spark3/src/main/java/org/apache/iceberg/spark/procedures/SparkProcedures.java
This PR adds a stored procedure for removing orphan files.
This change was originally authored by @liukun4515 against my internal fork before we got the stored procedures in. I kept @liukun4515 as the lead author and added more changes based on the current API for stored procedures.
Tests to be done.
=> Spark: Add RemoveOrphanFilesProcedure

spark3/src/main/java/org/apache/iceberg/spark/procedures/RewriteManifestsProcedure.java
This PR renames output columns in `RewriteManifestsProcedure` for consistency.
=> Spark: Rename output columns in RewriteManifestsProcedure

gradle.properties
Set gradle build heap size to avoid build failure because JVM heap space is exhausted.
For https://github.com/apache/iceberg/issues/1846.
=> Set gradle build heap size to avoid build failure

python/iceberg/api/expressions/expression.py, python/iceberg/api/types/type.py, python/iceberg/api/types/types.py, python/iceberg/core/filesystem/__init__.py, python/iceberg/core/util/profile.py, python/iceberg/exceptions/__init__.py, python/iceberg/exceptions/exceptions.py, python/iceberg/parquet/__init__.py, python/iceberg/parquet/dataset_utils.py, python/iceberg/parquet/parquet_reader.py, python/iceberg/parquet/parquet_schema_utils.py, python/iceberg/parquet/parquet_to_iceberg.py, python/setup.py, python/tests/parquet/__init__.py, python/tests/parquet/conftest.py, python/tests/parquet/test_dataset_utils.py, python/tests/parquet/test_parquet_reader.py, python/tests/parquet/test_parquet_to_iceberg.py
This adds a parquet reader class that leverages pyarrow.datasets to read parquet files and apply row-level filters.  Additionally, there are some helper classes to convert between arrow schemas and iceberg schemas, so that we can apply any necessary schema evolution.
cc @danielcweeks @rymurr
=> [python] Adding parquet package and the classes for reading parquet

core/src/main/java/org/apache/iceberg/TableProperties.java, site/docs/configuration.md, spark/src/main/java/org/apache/iceberg/spark/SparkWriteOptions.java, spark/src/main/java/org/apache/iceberg/spark/source/RowDataRewriter.java, spark/src/test/java/org/apache/iceberg/spark/source/TestSparkDataWrite.java, spark2/src/main/java/org/apache/iceberg/spark/source/Writer.java, spark3/src/main/java/org/apache/iceberg/spark/source/SparkWrite.java
Renaming the fanout configs.
1. Renamed DF write option from `partitioned.fanout.enabled` to `fanout-enabled`(similar to other Spark options)
2. Renamed TableProperty `write.partitioned.fanout.enabled` to `write.spark.partitioned.fanout.enabled`, as it applies to only Spark.
=> Rename fanout configs

core/src/main/java/org/apache/iceberg/CachingCatalog.java
The TableBuilder makes it easier to use catalogs from Spark, but the CachingCatalog doesn't currently support the builder so tests fail. This implements the builder for the CachingCatalog and uses it for the existing transaction methods. The existing tests should now exercise the builder.
=> Core: Support TableBuilder in CachingCatalog

core/src/main/java/org/apache/iceberg/deletes/EqualityDeleteWriter.java, core/src/main/java/org/apache/iceberg/io/BaseTaskWriter.java, core/src/main/java/org/apache/iceberg/io/PartitionedFanoutWriter.java, core/src/main/java/org/apache/iceberg/io/PartitionedWriter.java, core/src/main/java/org/apache/iceberg/io/TaskWriter.java, core/src/main/java/org/apache/iceberg/io/UnpartitionedWriter.java, core/src/main/java/org/apache/iceberg/io/WriteResult.java, data/src/test/java/org/apache/iceberg/io/TestBaseTaskWriter.java, flink/src/main/java/org/apache/iceberg/flink/sink/IcebergStreamWriter.java, flink/src/main/java/org/apache/iceberg/flink/source/RowDataRewriter.java, flink/src/test/java/org/apache/iceberg/flink/sink/TestTaskWriters.java, spark/src/main/java/org/apache/iceberg/spark/source/RowDataRewriter.java, spark2/src/main/java/org/apache/iceberg/spark/source/Writer.java, spark3/src/main/java/org/apache/iceberg/spark/source/SparkWrite.java
This is a sub-PR for this issue: https://github.com/apache/iceberg/pull/1818/files#diff-fc9a9fd84d24c607fd85e053b08a559f56dd2dd2a46f1341c528e7a0269f873cR183.   It's mainly used for abstracting the BaseRollingWriter.  We've provided the `RollingFileWriter` to write data records and `RollingEqDeleteWriter` to write equality-delete records in this patch, and provide complete unit tests to cover those.
=> Core: Add RollingEqDeleteWriter.

core/src/main/java/org/apache/iceberg/avro/Avro.java, core/src/main/java/org/apache/iceberg/io/SortedPosDeleteWriter.java, data/src/test/java/org/apache/iceberg/io/TestGenericSortedPosDeleteWriter.java
This is a separate issue (from [here](https://github.com/apache/iceberg/pull/1818/files#diff-179b5fea5d3aef7c16dd6104c17e1dc53ac9067f13695f3469d21e96c323eb97R39)) to implement the writer to write the sorted pos-deletes.
=> Core: Add SortedPosDeleteWriter

mr/src/main/java/org/apache/iceberg/mr/hive/Deserializer.java, mr/src/main/java/org/apache/iceberg/mr/hive/serde/objectinspector/IcebergBinaryObjectInspector.java, mr/src/main/java/org/apache/iceberg/mr/hive/serde/objectinspector/IcebergDateObjectInspector.java, mr/src/main/java/org/apache/iceberg/mr/hive/serde/objectinspector/IcebergDecimalObjectInspector.java, mr/src/main/java/org/apache/iceberg/mr/hive/serde/objectinspector/IcebergObjectInspector.java, mr/src/main/java/org/apache/iceberg/mr/hive/serde/objectinspector/IcebergTimestampObjectInspector.java, mr/src/main/java/org/apache/iceberg/mr/hive/serde/objectinspector/IcebergWriteObjectInspector.java, mr/src/main/java/org/apache/iceberg/mr/hive/serde/objectinspector/WriteObjectInspector.java, mr/src/test/java/org/apache/iceberg/mr/hive/HiveIcebergTestUtils.java, mr/src/test/java/org/apache/iceberg/mr/hive/TestDeserializer.java
Implements the Deserializer for Hive writes, and creates the corresponding test suite
=> Hive: Implement Deserializer for Hive writes

api/src/main/java/org/apache/iceberg/expressions/Expressions.java, api/src/main/java/org/apache/iceberg/expressions/Literals.java, api/src/test/java/org/apache/iceberg/expressions/TestExpressionHelpers.java
Follow up item from #1747 to clean up `Expressions` a bit. No behavior change.
=> API: move NaN validation from Expressions to Literals

flink/src/main/java/org/apache/iceberg/flink/IcebergTableSource.java, flink/src/main/java/org/apache/iceberg/flink/source/FlinkInputFormat.java, flink/src/main/java/org/apache/iceberg/flink/source/FlinkSource.java, flink/src/main/java/org/apache/iceberg/flink/source/ScanContext.java, flink/src/test/java/org/apache/iceberg/flink/TestFlinkTableSource.java
related to #1816 
now the source implement the interface `LimitableTableSource`,
after flink 1.12 ,implement the `SupportsLimitPushDown`
=> Flink: add limit pushdown for IcebergTableSource

api/src/main/java/org/apache/iceberg/ReplaceSortOrder.java, api/src/main/java/org/apache/iceberg/SortOrder.java, api/src/main/java/org/apache/iceberg/SortOrderBuilder.java, api/src/main/java/org/apache/iceberg/Table.java, api/src/main/java/org/apache/iceberg/Transaction.java, core/src/main/java/org/apache/iceberg/BaseMetadataTable.java, core/src/main/java/org/apache/iceberg/BaseReplaceSortOrder.java, core/src/main/java/org/apache/iceberg/BaseTable.java, core/src/main/java/org/apache/iceberg/BaseTransaction.java, core/src/main/java/org/apache/iceberg/CommitCallbackTransaction.java, core/src/main/java/org/apache/iceberg/ReplaceOrder.java, core/src/main/java/org/apache/iceberg/TableMetadata.java, core/src/test/java/org/apache/iceberg/TestTableMetadata.java
This adds a table API operation to replace the sort order with a newly constructed order, and abstracts the configuration methods into an API shared between `SortOrder.Builder` and `ReplaceSortOrder`.
=> Add Table.replaceSortOrder operation

spark3-extensions/src/test/java/org/apache/iceberg/spark/extensions/SparkExtensionsTestBase.java
There are quite some tests that perform shuffles so it makes sense to reduce the number of shuffle partitions.
=> Spark: Speed up tests for extensions

hive-metastore/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java, hive-metastore/src/test/java/org/apache/iceberg/hive/TestHiveCommitLocks.java, hive-metastore/src/test/java/org/apache/iceberg/hive/TestHiveMetastore.java, site/docs/configuration.md
50 milliseconds (constant) sleep time between "checking lock status" thrashes hive metastore databases when multiple jobs try to commit to the same Iceberg table. This fix allows the frequency of "checking the WAITING lock status" configurable and makes use of Tasks to backoff exponentially.
Every time a check on the lock is made, the HMS performs heartbeats on the lock record and the transaction record. It eventually ends up with the below errors if the number of jobs on the same table grew and commit at the same time. Ability to configure the delay between retries and slowing down retries further exponentially would help. Thanks.
```
MetaException(message:Unable to update transaction database org.postgresql.util.PSQLException: ERROR: could not serialize access due to read/write …
```
=> Hive: Make lock check retries backoff exponentially

site/docs/hive.md
Based on #1850 we need to enhance the documentation to mention that everyone modifying the table should use the `iceberg.engine.hive.enabled` config so the Hive parameters are not removed from the table
=> Hive: Enhance iceberg.hive.engine.enabled documentation

api/src/main/java/org/apache/iceberg/expressions/Literals.java, api/src/test/java/org/apache/iceberg/expressions/TestExpressionHelpers.java, mr/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergFilterFactory.java, mr/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergFilterFactory.java, pig/src/main/java/org/apache/iceberg/pig/IcebergStorage.java, spark2/src/main/java/org/apache/iceberg/spark/SparkFilters.java, spark2/src/test/java/org/apache/iceberg/spark/source/TestSelect.java, spark3/src/main/java/org/apache/iceberg/spark/Spark3Util.java, spark3/src/main/java/org/apache/iceberg/spark/SparkFilters.java, spark3/src/test/java/org/apache/iceberg/spark/sql/TestSelect.java
This PR is based on #1747. Currently it couldn't compile but I have confirmed locally that the project could build and all tests passed after rebasing it on top of #1747. This is because there are a few files required from #1747 to let the tests work. I will rebase the change and mark as ready for review once 1747 is merged.
=> rewrite equals filters

aws/src/integration/java/org/apache/iceberg/aws/s3/S3MultipartUploadTest.java, aws/src/main/java/org/apache/iceberg/aws/AwsProperties.java, aws/src/main/java/org/apache/iceberg/aws/s3/S3FileIO.java, aws/src/main/java/org/apache/iceberg/aws/s3/S3OutputStream.java, aws/src/main/java/org/apache/iceberg/aws/s3/S3RequestUtil.java, aws/src/test/java/org/apache/iceberg/aws/AwsPropertiesTest.java
@danielcweeks made the following updates to `S3FileIO` related code:
1. added integration tests that verifies upload behaviors against S3
2. updated variable names and documentations in `AwsProperties` to be consistent with others, added corresponding tests
3. fixed invalid reference to private variable `S3URI#VALID_SCHEMES` in doc of `S3FileIO`
4. muted errorprone warnings:
```
/iceberg/aws/src/main/java/org/apache/iceberg/aws/s3/S3RequestUtil.java:35: warning: [UnnecessaryLambda] Returning a lambda from a helper method or saving it in a constant is unnecessary; prefer to implement the functional interface method directly and use a method reference instead.
private static final Function<ServerSideEncryption, S3Request.Builder> NULL_SSE_SETTER = sse -> null;
^
(see …
```
=> AWS: add more S3FileIO tests, cleanup related codebase

build.gradle
Noticed some weird `java.lang.AbstractMethodError` exceptions while using Iceberg/Hive and REST clients. This completely removes rather old versions of Jersey from all modules so we only have v2 of `javax.ws.rs` in our dependency graph
=> Remove sun's jersey

aws/src/integration/java/org/apache/iceberg/aws/glue/GlueCatalogTableTest.java, aws/src/main/java/org/apache/iceberg/aws/glue/GlueTableOperations.java
fix bug in `GlueCatalog` that table type is removed after update
=> AWS: fix Glue bug table type removed after update

build.gradle, hive-metastore/src/main/java/org/apache/iceberg/hive/HiveSchemaConverter.java, hive-metastore/src/main/java/org/apache/iceberg/hive/HiveSchemaUtil.java, hive3/src/main/java/org/apache/iceberg/mr/hive/serde/objectinspector/IcebergTimestampObjectInspectorHive3.java, hive3/src/main/java/org/apache/iceberg/mr/hive/serde/objectinspector/IcebergTimestampWithZoneObjectInspectorHive3.java, hive3/src/test/java/org/apache/iceberg/mr/hive/TestHiveSchemaUtilHive3.java, hive3/src/test/java/org/apache/iceberg/mr/hive/serde/objectinspector/TestIcebergTimestampObjectInspectorHive3.java, hive3/src/test/java/org/apache/iceberg/mr/hive/serde/objectinspector/TestIcebergTimestampWithZoneObjectInspectorHive3.java, mr/src/main/java/org/apache/iceberg/mr/hive/serde/objectinspector/IcebergObjectInspector.java, mr/src/main/java/org/apache/iceberg/mr/hive/serde/objectinspector/IcebergTimestampObjectInspector.java, mr/src/main/java/org/apache/iceberg/mr/hive/serde/objectinspector/IcebergTimestampWithZoneObjectInspector.java, mr/src/test/java/org/apache/iceberg/mr/hive/serde/objectinspector/TestIcebergObjectInspector.java, mr/src/test/java/org/apache/iceberg/mr/hive/serde/objectinspector/TestIcebergTimestampObjectInspector.java, mr/src/test/java/org/apache/iceberg/mr/hive/serde/objectinspector/TestIcebergTimestampWithZoneObjectInspector.java
- Break up `TimestampObjectInspector` classes into two separate classes for (i) normal timestamps and (ii) timestamps with zone (instead of using inner classes)
- For Hive3, take advantage of its TimestampWithLocalTimeZone type (which Hive2 doesn't have) instead of just converting timestampTz into normal timestamps
=> Add support for timestamp with local zone in Hive3

build.gradle
Small one. While working on a Beam sink, I've noticed that the Arrow dependency was referenced twice. It is also reference two lines above.
=> Remove duplicate Arrow dependency

core/src/main/java/org/apache/iceberg/io/BaseTaskWriter.java, flink/src/main/java/org/apache/iceberg/flink/RowDataWrapper.java, flink/src/main/java/org/apache/iceberg/flink/sink/BaseDeltaTaskWriter.java, flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java, flink/src/main/java/org/apache/iceberg/flink/sink/PartitionedDeltaWriter.java, flink/src/main/java/org/apache/iceberg/flink/sink/RowDataTaskWriterFactory.java, flink/src/main/java/org/apache/iceberg/flink/sink/UnpartitionedDeltaWriter.java, flink/src/main/java/org/apache/iceberg/flink/source/RowDataRewriter.java, flink/src/test/java/org/apache/iceberg/flink/SimpleDataUtil.java, flink/src/test/java/org/apache/iceberg/flink/sink/TestDeltaTaskWriter.java, flink/src/test/java/org/apache/iceberg/flink/sink/TestTaskWriters.java
Introduced an new flink  delta task writer to write cdc events into iceberg table,  this PR is currently built on top of PR https://github.com/apache/iceberg/pull/1888.
=> Flink: Add PartitionedDeltaTaskWriter and UnpartitionedDeltaTaskWriter to write both insert and equality-deletes

api/src/main/java/org/apache/iceberg/Table.java, api/src/main/java/org/apache/iceberg/Transaction.java, api/src/main/java/org/apache/iceberg/UpdatePartitionSpec.java, core/src/main/java/org/apache/iceberg/BaseMetadataTable.java, core/src/main/java/org/apache/iceberg/BaseTable.java, core/src/main/java/org/apache/iceberg/BaseTransaction.java, core/src/main/java/org/apache/iceberg/BaseUpdatePartitionSpec.java, core/src/main/java/org/apache/iceberg/CommitCallbackTransaction.java, core/src/main/java/org/apache/iceberg/TableMetadata.java, core/src/test/java/org/apache/iceberg/TestTableMetadata.java
This adds `UpdatePartitionSpec` to ` Table` and `Transaction`.
These changes are extracted from #922 and @jun-he is the primary author.
=> Add UpdatePartitionSpec operation for tables.

aws/src/integration/java/org/apache/iceberg/aws/s3/S3FileIOTest.java, aws/src/main/java/org/apache/iceberg/aws/s3/BaseS3File.java, aws/src/main/java/org/apache/iceberg/aws/s3/S3InputFile.java, aws/src/main/java/org/apache/iceberg/aws/s3/S3RequestUtil.java, aws/src/test/java/org/apache/iceberg/aws/s3/S3FileIOTest.java
This reverts commit c882ac9249229078bf89caf48de688c399e858f9.
@jackye1995 I wanted to propose reverting #1863 and going back to the HEAD operation for `exists()` and `contentLength()` FileIO operations.  There was some discussion on the dev list and apparently there's some level of confirmation that negative caching with HEAD operations is covered (and possibly strong consistency?) in the recent announcement around S3 consistency.
Iceberg isn't using this operation for consistency and the major concern I have is that the LIST operation cost appears to be 10X (or more) than the HEAD operation, which could really add up depending on usage.
I just wanted to put this up for discussion and see if there's any real advantage at this point to using LIST.  
(cc @giovannifumarola, @kbendick, …
=> Revert "AWS: support S3 strong consistency (#1863)"

spark3-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestDelete.java
This PR fixes the test case with IN and NOT IN condition. It is currently ignored due to a limitation in Spark.
=> Spark: Fix delete test with IN and NOT IN condition

spark/src/main/java/org/apache/iceberg/spark/source/StructInternalRow.java
I noticed this when I was working on avro metrics support #1935, that [this test case](https://github.com/apache/iceberg/pull/1935/files#diff-81688a1556370355eceb1e39ea9babd927c8ae4a2e6b1ae56743548e0ac833f5R259) will fail with cast exception (unable to cast int to collection). Before this change, I think when `elementType` is of type list, this line result in a second call to `collectionToArrayData` with `elementType` as list when it iterates through each element in the list (within `fillArray` L300), and the cast exception occurs when it tries to cast the element's type to collection for applying `setter.accept`. 
I think this would occur when there's a list in a nested structure (e.g. list within map, etc), and I think this doesn't cause problem now since this class is only used for …
=> Spark: update list array copy behavior in StructInternalRow

build.gradle
Remove unused hadoop test dependencies
- basic sanity done by running tests of the affected projects/modules
cc: @RussellSpitzer
=> Remove unused hadoop test dependencies

core/src/main/java/org/apache/iceberg/util/ExceptionUtil.java, core/src/test/java/org/apache/iceberg/util/TestExceptionUtil.java
This adds a utility method that accepts blocks as lambdas and correctly handles exceptions. Catch and finally blocks are always run and any exceptions thrown in those blocks are added to the main block's exception as suppressed exceptions. If the main block does not throw an exception, but finally does then the finally exception is thrown.
This currently supports up to 3 checked exception classes.
=> Add ExceptionUtil.runSafely

arrow/src/main/java/org/apache/iceberg/arrow/vectorized/VectorHolder.java, arrow/src/main/java/org/apache/iceberg/arrow/vectorized/VectorizedArrowReader.java, parquet/src/main/java/org/apache/iceberg/parquet/VectorizedParquetReader.java, parquet/src/main/java/org/apache/iceberg/parquet/VectorizedReader.java, spark/src/main/java/org/apache/iceberg/spark/data/vectorized/ArrowVectorAccessors.java, spark/src/main/java/org/apache/iceberg/spark/data/vectorized/ColumnarBatchReader.java, spark/src/main/java/org/apache/iceberg/spark/data/vectorized/VectorizedSparkParquetReaders.java, spark/src/test/java/org/apache/iceberg/spark/data/TestSparkParquetReadMetadataColumns.java
This adds parquet position reader for the vectorized case.
=> Parquet: Add vectorized position reader

mr/src/main/java/org/apache/iceberg/mr/hive/serde/objectinspector/IcebergTimestampWithZoneObjectInspector.java, mr/src/test/java/org/apache/iceberg/mr/hive/serde/objectinspector/TestIcebergTimestampWithZoneObjectInspector.java
For https://github.com/apache/iceberg/issues/1964, update IcebergTimestampWithZoneObjectInspector to fix test failures in local build.
=> Update IcebergTimestampWithZoneObjectInspector to fix test failures

spark3-extensions/src/main/antlr/org.apache.spark.sql.catalyst.parser.extensions/IcebergSqlExtensions.g4, spark3-extensions/src/main/scala/org/apache/spark/sql/catalyst/parser/extensions/IcebergSparkSqlExtensionsParser.scala, spark3-extensions/src/main/scala/org/apache/spark/sql/catalyst/parser/extensions/IcebergSqlExtensionsAstBuilder.scala, spark3-extensions/src/main/scala/org/apache/spark/sql/catalyst/plans/logical/SetWriteOrder.scala, spark3-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/ExtendedDataSourceV2Strategy.scala, spark3-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/SetWriteOrderExec.scala, spark3-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestSetWriteOrder.java
This adds `ALTER TABLE ... WRITE ORDERED BY ...` to set the table order in Spark.
=> Spark: Add WRITE ORDERED BY command to set table order

parquet/src/main/java/org/apache/iceberg/parquet/ParquetUtil.java
Explicit type argument Encoding can be replaced with <>
=> explicit type argument Encoding can be replaced with <>

core/src/main/java/org/apache/iceberg/TableProperties.java, spark3/src/main/java/org/apache/iceberg/spark/source/SparkMergeBuilder.java, spark3/src/main/java/org/apache/iceberg/spark/source/SparkTable.java
This PR adds table properties to control UPDATE mode and isolation level.
=> Spark: Add table properties to control UPDATE mode and isolation level

core/src/main/java/org/apache/iceberg/TableProperties.java, spark3/src/main/java/org/apache/iceberg/spark/source/SparkMergeBuilder.java, spark3/src/main/java/org/apache/iceberg/spark/source/SparkTable.java
This PR adds table properties to control MERGE mode and isolation level.
=> Spark: Add table properties to control MERGE mode and isolation level

hive-metastore/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java
wrap `io().deleteFile(metadataLocation)` in try catch block so that `unlock(lockId)` must be called in the finally block.
=> Hive: ensure unlock is called when new metadata cannot be deleted

core/src/main/java/org/apache/iceberg/avro/SchemaToType.java, core/src/main/java/org/apache/iceberg/avro/TypeToSchema.java, core/src/test/java/org/apache/iceberg/TestMergeAppend.java, core/src/test/java/org/apache/iceberg/avro/TestSchemaConversions.java, spark/src/test/java/org/apache/iceberg/spark/data/AvroDataTest.java
This addresses issue https://github.com/apache/iceberg/issues/1954
=> Avro: Schema conversions should preserve field docs

aws/src/main/java/org/apache/iceberg/aws/AwsClientFactories.java, aws/src/main/java/org/apache/iceberg/aws/AwsProperties.java, aws/src/main/java/org/apache/iceberg/aws/s3/S3OutputStream.java, aws/src/test/java/org/apache/iceberg/aws/AwsClientFactoriesTest.java
1. remove `get` from get method `getS3fileIoStagingDirectory`
2. move client factory config key to `AwsProperties`, so all configs are in a single place.
3. fix bug in `AwsClientFactories.loadClientFactory`, no error was thrown because of the use of reflection.
=> AWS: cleanup AwsProperties styles

build.gradle
As discussed in #1887 , put AWS dependencies into provided scope and add to Spark and Flink runtime jar. The produced artifact will not contain AWS packages, please let me know if I still need to update the license and notice files in this case. 
I will post logs for executing the updated Spark and Flink runtime jar in comments later.
=> AWS: add aws to spark and flink runtime

core/src/test/java/org/apache/iceberg/TestMergeAppend.java
The goal of this patch is to help future proof this test against any future increases in the manifest file size (additional fields, longer or additional doc strings, etc).
This is a follow up to when the value was increased in this PR https://github.com/apache/iceberg/pull/1991, as suggested by @rdblue.
This PR and the original PR are originally related to this issue: https://github.com/apache/iceberg/issues/1954
=> [Core] Minor test config value increase for manifest target size in testManifestMergeMinCount

core/src/test/java/org/apache/iceberg/TestTableUpdatePartitionSpec.java
Add some of additional tests (from https://github.com/apache/iceberg/pull/922) for partition spec updates.
=> Add additional partition spec update tests

site/docs/trino.md, site/mkdocs.yml
PrestoSQL was rebranded as Trino: https://trino.io/blog/2020/12/27/announcing-trino.html
=> Rename Presto SQL to Trino

README.md, core/src/main/java/org/apache/iceberg/hadoop/HadoopTables.java
fix issue in #1843 which failed to pick up correct sort order when executing transactions from `HadoopTables`
Thanks @openinx !
=> Use supplied sort order in HadoopTables replace transactions

core/src/main/java/org/apache/iceberg/actions/BaseRewriteDataFilesAction.java, flink/src/test/java/org/apache/iceberg/flink/actions/TestRewriteDataFilesAction.java
the pr fix #1661 
If DataFile cannot be  combined to CombinedScanTask with other DataFiles, the size of CombinedScanTask list size is 1, so we remove these CombinedScanTasks to avoid compressed repeatedly.
=> Flink : Fix Repeated Rewrite for RewriteDataFilesAction

.github/workflows/java-ci.yml, .github/workflows/python-ci.yml
This updates Java and Python CI actions to run only when certain files are modified. Python matches any file in the `python` folder or its CI config, and Java matches any file except those in the `python` or `site` folders.
=> Build: Add path config to control github actions

build.gradle, nessie/src/main/java/org/apache/iceberg/nessie/NessieCatalog.java, versions.props
This bumps nessie to [0.3.0 ](https://github.com/projectnessie/nessie/releases/tag/nessie-0.3.0). The new release removes the JAX-RS client in favour of `HttpUrlConnection`.
We have simplified the gradle build accordingly and bumped the version of Nessie
=> Bump Nessie version to 0.3.0

api/src/main/java/org/apache/iceberg/PartitionSpec.java, core/src/test/java/org/apache/iceberg/TestTableUpdatePartitionSpec.java
Fix update partition spec with only rename changes by treating the new spec as incompatible one.
=> Fix update partition spec with only rename changes

.github/workflows/java-ci.yml
This is a first step toward breaking the tests up into smaller jobs that can be run in parallel. This creates a job for running errorprone and checkstyle (extra-checks) and a job for javadoc, so that the test jobs don't need to duplicate that work and the analysis feedback is faster because it isn't delayed by testing.
=> Build: Add separate CI jobs for javadoc and errorprone/checkstyle

build.gradle
This removes additional logging added in #1210 and #1212 to avoid timeouts in Travis CI. Now that the project uses github actions, it shouldn't be needed any longer.
=> Build: Remove additional logging for Travis CI

spark3/src/main/java/org/apache/iceberg/spark/source/IcebergSource.java
This fixes the [failing Javadoc check](https://github.com/apache/iceberg/pull/2011/checks?check_run_id=1633744225#step:4:1084).
=> Spark: Fix Javadoc in IcebergSource

core/src/main/java/org/apache/iceberg/BaseSnapshot.java
For the Beam runner, we emit the Snapshots after they are made. This can be done to notify downstream consumers of the data. Because the snapshots will be serialized, Beam needs to have the ability to compare them. This is done by the native Java equals function. Because we implement equals, we also need to implement the hashcode function.
```
[direct-runner-worker] WARN org.apache.beam.sdk.util.MutationDetectors - Coder of type class org.apache.beam.sdk.coders.SerializableCoder has a #structuralValue method which does not return true when the encoding of the elements is equal. Element BaseSnapshot{id=8584070983395915429, timestamp_ms=1609329789570, operation=append, summary={added-data-files=3, added-records=300, added-files-size=3072, changed-partition-count=1, total-records=300, …
```
=> Add equals and hashcode to BaseSnapshot

core/src/main/java/org/apache/iceberg/BaseSnapshot.java
Using the Objects.equal, we're safe against NPE's. Others are primitives, so that should be fine.
=> The this.parentId can be null

mr/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java, mr/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandler.java
Impala retrieves the Input and OutputFormat classes directly from the HMS properties, and not from the StorageHandler. Therefore, we need to explicitly set these values during the Hive metahook operations, so that we have those present even when the table was created using Hive DDL. The analogous change in the Iceberg API has been added in this commit: https://github.com/apache/iceberg/commit/45caac4927fedc8313aba79d49f5911eccee2474
@rdblue, @pvary could you please take a look? Thank you
=> Set Input and OutputFormat in the hive meta hook

aws/src/integration/java/org/apache/iceberg/aws/glue/GlueTestBase.java, aws/src/integration/java/org/apache/iceberg/aws/s3/S3FileIOTest.java, aws/src/main/java/org/apache/iceberg/aws/glue/GlueCatalog.java, aws/src/main/java/org/apache/iceberg/aws/glue/GlueTableOperations.java, aws/src/main/java/org/apache/iceberg/aws/glue/LockManager.java, aws/src/main/java/org/apache/iceberg/aws/glue/LockManagers.java, aws/src/test/java/org/apache/iceberg/aws/glue/GlueCatalogTest.java, aws/src/test/java/org/apache/iceberg/aws/glue/InMemoryLockManagerTest.java, aws/src/test/java/org/apache/iceberg/aws/glue/LockManagersTest.java, core/src/main/java/org/apache/iceberg/CatalogProperties.java
Allow Glue catalog to use an external DynamoDB table to enforce serializable isolation during commit.
=> AWS: Glue catalog lock interface

parquet/src/main/java/org/apache/iceberg/parquet/ParquetWriter.java, parquet/src/test/java/org/apache/iceberg/parquet/ParquetWritingTestUtils.java, parquet/src/test/java/org/apache/iceberg/parquet/TestParquet.java
a fix for [iss1980](https://github.com/apache/iceberg/issues/1980)
=> iss1980 a special close flag added to indicate that the writer is closed

aws/src/integration/java/org/apache/iceberg/aws/AssumeRoleAwsClientFactoryTest.java, aws/src/integration/java/org/apache/iceberg/aws/AwsIntegTestUtil.java, aws/src/main/java/org/apache/iceberg/aws/AssumeRoleAwsClientFactory.java, aws/src/main/java/org/apache/iceberg/aws/AwsProperties.java, build.gradle
@danielcweeks  as discussed in #1844 , separated PR for assume role client factory support.
=> AWS: add client factory for assume role use case

core/src/main/java/org/apache/iceberg/util/ExceptionUtil.java
The interfaces `Block`, `CatchBlock` and `FinallyBlock` need to be public so that callers can use `runSafely` in other package paths.
=> Core: fix bug that interfaces in ExceptionUtil are not public

aws/src/main/java/org/apache/iceberg/aws/s3/S3OutputStream.java
`ExecutorService` should be created with synchronized static variable guard.
=> AWS: fix S3FileIO executor service creation synchronization

LICENSE, project/scalastyle_config.xml, spark/src/test/java/org/apache/iceberg/spark/SparkTestBase.java, spark3-extensions/src/main/scala/org/apache/iceberg/spark/extensions/IcebergSparkSessionExtensions.scala, spark3-extensions/src/main/scala/org/apache/spark/sql/catalyst/analysis/AlignMergeIntoTable.scala, spark3-extensions/src/main/scala/org/apache/spark/sql/catalyst/analysis/AssignmentAlignmentSupport.scala, spark3-extensions/src/test/java/org/apache/iceberg/spark/extensions/SparkRowLevelOperationsTestBase.java, spark3-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestCopyOnWriteMerge.java, spark3-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestDelete.java, spark3-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMerge.java
This PR adds a rule that aligns assignments in MERGE operations with target table columns.
=> Spark: Add a rule to align updates in MERGE operations

aws/src/integration/java/org/apache/iceberg/aws/glue/DynamoLockManagerTest.java, aws/src/integration/java/org/apache/iceberg/aws/glue/GlueCatalogLockTest.java, aws/src/main/java/org/apache/iceberg/aws/AssumeRoleAwsClientFactory.java, aws/src/main/java/org/apache/iceberg/aws/AwsClientFactories.java, aws/src/main/java/org/apache/iceberg/aws/AwsClientFactory.java, aws/src/main/java/org/apache/iceberg/aws/glue/DynamoLockManager.java, aws/src/main/java/org/apache/iceberg/aws/glue/LockManager.java, aws/src/test/java/org/apache/iceberg/aws/AwsClientFactoriesTest.java, build.gradle
As discussed, the DynamoDB part of #1823 
Also updates the documentation for `LockManager.release()`.
=> AWS: add DynamoDB implementation of Glue lock manager

data/src/main/java/org/apache/iceberg/data/GenericAppenderFactory.java, flink/src/main/java/org/apache/iceberg/flink/sink/FlinkAppenderFactory.java
Looks like we didn't plug in the metrics config for generating ORC file appenders in Flink and Generic appender factory as we do in Parquet
=> add missing metrics config to ORC appenders

site/mkdocs.yml
Tested locally with `mkdocs serve`.
=> Docs: Add redirect from presto/ to trino/

aws/src/main/java/org/apache/iceberg/aws/AwsProperties.java, core/src/main/java/org/apache/iceberg/CatalogProperties.java
As discussed in #1891 with @rdblue , shorten AWS config keys and change the following names:
- `gluecatalog.*` to `glue.*`
- `s3fileio.*` to `s3.*`
- `staging.dir` to `staging-dir`
- `lock.impl` to `lock-impl`
- `part-size` to `part-size-bytes`
@danielcweeks are you okay with these changes?
=> AWS: consolidate config key names before release

site/docs/aws.md, site/docs/configuration.md, site/docs/css/extra.css, site/mkdocs.yml
Initial draft for documentation page of the AWS module, I will mark this as draft until #1823 and #1844 are merged.
Also, I am currently placing it under `Tables` tab, which is clearly wrong. I was thinking about adding a new tab `Integrations` for all integrations including AWS and Nessie, but the navbar becomes too long. I am thinking about moving Flink, Hive and Presto all to a single `Engines` tab, any thoughts on that?
=> AWS: documentation page for AWS module

api/src/main/java/org/apache/iceberg/Tables.java, core/src/main/java/org/apache/iceberg/hadoop/HadoopTables.java, core/src/test/java/org/apache/iceberg/hadoop/TestHadoopTables.java, mr/src/test/java/org/apache/iceberg/mr/hive/TestTables.java
currently we do not have a straightforward way to check the existence of HadoopTables.
instead of capturing exception when calling load/create and then justify whether the table is in the path, this PR provides a new API exists()
=> Core: provide new api of table exists for HadoopTables

spark3-extensions/src/main/scala/org/apache/spark/sql/catalyst/plans/logical/DynamicFileFilter.scala, spark3-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/DynamicFileFilterExec.scala
This PR overrides `simpleString` in dynamic file filter nodes to limit their output.
After this PR:
```
+- DynamicFileFilter[id#20, dep#21, _file#28, _pos#29L]
:- RelationV2[id#20, dep#21, _file#28, _pos#29L] testhive.default.table
+- Aggregate [_file#28], [_file#28]
+- Project [_file#28]
+- Filter (id#20 <=> 1)
+- RelationV2[id#20, dep#21, _file#28, _pos#29L] testhive.default.table
+- DynamicFileFilterExec[id#20, dep#21, _file#28, _pos#29L]
:- *(1) Project [id#20, dep#21, _file#28, _pos#29L]
:  +- ExtendedBatchScan[id#20, dep#21, _file#28, _pos#29L] testhive.default.table [filters=id = 1]
+- *(2) HashAggregate(keys=[_file#28], functions=[], output=[_file#28])
+- *(2) HashAggregate(keys=[_file#28], functions=[], output=[_file#28])
+- *(2) Project [_file#28]
+- *(2) Filter (id#20 <=> 1)
+- …
```
=> Spark: Override simpleString in dynamic file filter nodes

core/src/main/java/org/apache/iceberg/BaseUpdatePartitionSpec.java, core/src/test/java/org/apache/iceberg/TestTableUpdatePartitionSpec.java
The field ID in the new spec should start with the largest last assigned partition id among all table specs.
=> Fix the partition field id when appending a field to the V2 spec.

data/src/test/java/org/apache/iceberg/data/GenericAppenderHelper.java, flink/src/main/java/org/apache/iceberg/flink/source/FlinkInputFormat.java, flink/src/main/java/org/apache/iceberg/flink/source/FlinkInputSplit.java, flink/src/main/java/org/apache/iceberg/flink/source/FlinkSource.java, flink/src/main/java/org/apache/iceberg/flink/source/FlinkSplitGenerator.java, flink/src/main/java/org/apache/iceberg/flink/source/ScanContext.java, flink/src/main/java/org/apache/iceberg/flink/source/StreamingMonitorFunction.java, flink/src/main/java/org/apache/iceberg/flink/source/StreamingReaderOperator.java, flink/src/test/java/org/apache/iceberg/flink/FlinkTestBase.java, flink/src/test/java/org/apache/iceberg/flink/TestTableLoader.java, flink/src/test/java/org/apache/iceberg/flink/source/TestStreamScanSql.java, flink/src/test/java/org/apache/iceberg/flink/source/TestStreamingMonitorFunction.java, flink/src/test/java/org/apache/iceberg/flink/source/TestStreamingReaderOperator.java
This patch port the flink streaming reader from here. https://github.com/generic-datalake/iceberg-poc/pull/3
=> Flink: Support streaming reader.

flink/src/main/java/org/apache/iceberg/flink/FlinkCatalogFactory.java
When testing Nessie as a custom catalog I came across Flink (1.11.3) not accepting custom catalog properties or `catalog-impl`. This PR adds `catalog-impl` as a property and a wildcard suffix for custom catalog properties, The result is:
```
CREATE CATALOG nessie_catalog WITH (
'type'='iceberg',
'catalog-impl'='org.apache.iceberg.nessie.NessieCatalog',
'custom-catalog.url'='http://localhost:19120/api/v1',
'custom-catalog.warehouse'='/home/ryan/warehouse');
```
I am wondering if the community thinks this is the best pattern or if a better way is preferred? If this is good I will update the docs accordingly.
=> Fix properties for custom catalogs in Flink

hive3/src/main/java/org/apache/iceberg/mr/hive/serde/objectinspector/IcebergTimestampObjectInspectorHive3.java, hive3/src/main/java/org/apache/iceberg/mr/hive/serde/objectinspector/IcebergTimestampWithZoneObjectInspectorHive3.java, hive3/src/test/java/org/apache/iceberg/mr/hive/serde/objectinspector/TestIcebergTimestampObjectInspectorHive3.java, hive3/src/test/java/org/apache/iceberg/mr/hive/serde/objectinspector/TestIcebergTimestampWithZoneObjectInspectorHive3.java, mr/src/main/java/org/apache/iceberg/mr/hive/Deserializer.java, mr/src/main/java/org/apache/iceberg/mr/hive/serde/objectinspector/IcebergBinaryObjectInspector.java, mr/src/main/java/org/apache/iceberg/mr/hive/serde/objectinspector/IcebergDateObjectInspector.java, mr/src/main/java/org/apache/iceberg/mr/hive/serde/objectinspector/IcebergDecimalObjectInspector.java, mr/src/main/java/org/apache/iceberg/mr/hive/serde/objectinspector/IcebergTimestampObjectInspector.java, mr/src/main/java/org/apache/iceberg/mr/hive/serde/objectinspector/IcebergTimestampWithZoneObjectInspector.java, mr/src/main/java/org/apache/iceberg/mr/hive/serde/objectinspector/WriteObjectInspector.java, mr/src/test/java/org/apache/iceberg/mr/hive/HiveIcebergTestUtils.java, mr/src/test/java/org/apache/iceberg/mr/hive/TestDeserializer.java, mr/src/test/java/org/apache/iceberg/mr/hive/serde/objectinspector/TestIcebergTimestampObjectInspector.java, mr/src/test/java/org/apache/iceberg/mr/hive/serde/objectinspector/TestIcebergTimestampWithZoneObjectInspector.java
During the testing of the write path @lcspinter run more extensive tests and identified an issue that fields which are supposed to use the WriteObjectInspector does not work.
The root cause was that the we both have to use the Hive generated ObjectInspectors to get the primitive object data from the Hive data model, and then use the IcebergObjectInspectors to convert them to the Iceberg data model.
The proposed solution creates an ObjectInspectorPair for every field which contains both the Hive and the Iceberg ObjectInspectors, and uses them when the conversion is needed.
Testing is done with the original code with changing the ObjectInspectors used. Also we hit #2053 so I had to disable the case sensitivity tests until #2053 is committed.
=> Hive: Fix Deserializer to use source deserializer instead of the Iceberg ones

spark3-extensions/src/main/scala/org/apache/iceberg/spark/extensions/IcebergSparkSessionExtensions.scala, spark3-extensions/src/main/scala/org/apache/spark/sql/catalyst/optimizer/RewriteDelete.scala, spark3-extensions/src/main/scala/org/apache/spark/sql/utils/RewriteRowLevelOperationHelper.scala
- Creates a base trait ```RewriteRowLevelOperationHelper``` that all the rewrite rules for row level operations will make use of.
- Its a basic refactor PR which refactors the method from `RewriteDelete` rule.
=> Create a base trait for row level operations - Foundational work for MERGE INTO

spark3-extensions/src/main/scala/org/apache/spark/sql/catalyst/optimizer/RewriteDelete.scala, spark3-extensions/src/main/scala/org/apache/spark/sql/catalyst/utils/RewriteRowLevelOperationHelper.scala
This PR refactors `RewriteRowLevelOperationHelper` to support MERGE operations.
=> Spark: Refactor RewriteRowLevelOperationHelper to support MERGE operations

api/src/main/java/org/apache/iceberg/util/BinaryUtil.java, api/src/test/java/org/apache/iceberg/expressions/TestInclusiveMetricsEvaluator.java, core/src/test/java/org/apache/iceberg/TestMetricsTruncation.java, spark2/src/test/java/org/apache/iceberg/spark/source/TestFilteredScan.java, spark3/src/test/java/org/apache/iceberg/spark/source/TestFilteredScan.java
This PR closes https://github.com/apache/iceberg/issues/2065
This allows for the `BinaryUtil.truncateBinary` function to allow for a zero length truncation. This is necessary for handling
scans where STARTS_WITH filters are applied to the table (or any filter that uses  `truncateBinary`) when a (possibly non-partition) column has an empty string value in it.
It would be more efficient to return early in each of the given metrics evaluators if the length is zero, but I did not want to introduce too many changes that conflict with this PR: https://github.com/apache/iceberg/pull/2062. If we'd like, we can go in and update all of those functions individually, but this is the minimum possible change set (to the non-test code) to fix the issue now and is likely cleaner. Additionally, since …
=> Allow binary truncation length to be zero to handle evaluators that encounter empty string values

mr/src/main/java/org/apache/iceberg/mr/hive/serde/objectinspector/IcebergBinaryObjectInspector.java, mr/src/main/java/org/apache/iceberg/mr/hive/serde/objectinspector/IcebergFixedObjectInspector.java, mr/src/main/java/org/apache/iceberg/mr/hive/serde/objectinspector/IcebergObjectInspector.java, mr/src/main/java/org/apache/iceberg/mr/hive/serde/objectinspector/IcebergTimeObjectInspector.java, mr/src/main/java/org/apache/iceberg/mr/hive/serde/objectinspector/IcebergUUIDObjectInspector.java, mr/src/test/java/org/apache/iceberg/mr/hive/HiveIcebergTestUtils.java, mr/src/test/java/org/apache/iceberg/mr/hive/TestDeserializer.java, mr/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerWithEngine.java, mr/src/test/java/org/apache/iceberg/mr/hive/serde/objectinspector/TestIcebergFixedObjectInspector.java, mr/src/test/java/org/apache/iceberg/mr/hive/serde/objectinspector/TestIcebergObjectInspector.java, mr/src/test/java/org/apache/iceberg/mr/hive/serde/objectinspector/TestIcebergTimeObjectInspector.java, mr/src/test/java/org/apache/iceberg/mr/hive/serde/objectinspector/TestIcebergUUIDObjectInspector.java
This PR covers the schema conversion for UUID, Fixed and Time types between Iceberg and Hive.
The following mapping is used:
- UUID -> String
- Fixed -> Binary
- Time -> String
=> Hive: Add ObjectInspector implementations for UUID, Fixed and Time type

hive-metastore/src/test/java/org/apache/iceberg/hive/HiveMetastoreTest.java, hive-metastore/src/test/java/org/apache/iceberg/hive/TestHiveMetastore.java, mr/src/test/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandlerTestUtils.java, mr/src/test/java/org/apache/iceberg/mr/hive/TestHiveShell.java, orc/src/main/java/org/apache/iceberg/orc/ORC.java
After this change (_[HIVE-20129](https://issues.apache.org/jira/browse/HIVE-20129) Revert to position based schema evolution for orc tables_) in Hive the Iceberg ORC column projection is not working as expected.
The effect:
- If the table has 3 columns (customer_id, first_name, last_name)
- And the query requests the last 2 columns (first_name, last_name)
- We will read the first 2 (customer_id, first_name) instead of the requested ones
I think it would be good to turn off this config for our Iceberg ORC readers as we expect it to be false anyway and other systems using Iceberg might need it to be set differently.
The patch contains 3 groups of changes:
- Test infra changes so we can change HMS configuration (this is used for HiveCatalog FileIO creation)
- Actually setting the …
=> ORC, Hive: Fix column projection when reading ORC files and `orc.force.positional.evolution` is set to `true` on the default configuration

site/docs/api.md
I noticed the list of modules in the API documentation is missing a number of published modules.
I've updated the list with descriptions that I came up with. As I am by no means an expert on various aspects of the modules that make up this project, please feel free to recommend changes or alternative language. 🙂
=> [Docs] update list of modules in API docs

arrow/src/main/java/org/apache/iceberg/arrow/vectorized/VectorizedArrowReader.java, spark/src/main/java/org/apache/iceberg/spark/data/vectorized/ArrowVectorAccessors.java, spark/src/test/java/org/apache/iceberg/spark/data/TestHelpers.java, spark/src/test/java/org/apache/iceberg/spark/data/parquet/vectorized/TestParquetVectorizedReads.java
When the type of a column in iceberg-parquet table is promoted from int->long, or float->double, vectorized reads fail with a ClassCastException. 
```
java.lang.ClassCastException: org.apache.iceberg.bdp.shaded.org.apache.arrow.vector.BigIntVector cannot be cast to org.apache.iceberg.bdp.shaded.org.apache.arrow.vector.IntVector
at org.apache.iceberg.arrow.vectorized.VectorizedArrowReader.allocateFieldVector(VectorizedArrowReader.java:280)
at org.apache.iceberg.arrow.vectorized.VectorizedArrowReader.read(VectorizedArrowReader.java:120)
at org.apache.iceberg.spark.data.vectorized.ColumnarBatchReader.read(ColumnarBatchReader.java:69)
at org.apache.iceberg.spark.data.vectorized.ColumnarBatchReader.read(ColumnarBatchReader.java:39)
at …
```
=> Spark - Fix parquet vectorized reads when column types are promoted

NOTICE, bundled-guava/NOTICE, flink-runtime/NOTICE, hive-runtime/NOTICE, spark-runtime/NOTICE, spark3-runtime/NOTICE
This is a follow up to this PR: https://github.com/apache/iceberg/pull/2106
Updates the NOTICE files to include 2021 in the copyright years for Iceberg.
cc @rdblue
=> Update NOTICE files to include 2021 in copyright years

.gitignore
I was checking to see if we had any scripts or automation to automatically update our NOTICE files to the current year.
I didn't find any. But I did notice that when I ran the `dev/check-license` bash script that it downloads `apache-rat-0.xx.jar` into `/lib`, which then made my git working tree dirty.
To prevent users from accidentally checking in the rat jar or any future libraries, I've added `/lib` to the `.gitignore` file.
=> [MISC] Add rat library install location from dev/check-license to gitignore

api/src/main/java/org/apache/iceberg/SortOrder.java
When going back over fixing some NarrowingCompoundAssignment warnings, I caught these two left over instances of missing overrides.
=> [MISC] Fix missing override warnings in SortOrder

hive-metastore/src/main/java/org/apache/iceberg/hive/HiveSchemaConverter.java, hive-metastore/src/main/java/org/apache/iceberg/hive/HiveSchemaUtil.java, mr/src/main/java/org/apache/iceberg/mr/InputFormatConfig.java, mr/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java, mr/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergSerDe.java, mr/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerNoScan.java
To allow existing Hive workloads to easily move to Iceberg tables we should make it easier to migrate the scripts.
Currently the following types are not allowed in Hive `CREATE TABLE` statements since they do not have an exact match in Iceberg types:
- TINYINT
- SMALLINT
- VARCHAR
- CHAR
We still want to keep the 1-on-1 schema mapping between Hive and Iceberg, but for the table creation we can convert unsupported types to supported ones:
- TINYINT - INTEGER
- SMALLINT - INTERER
- VARCHAR - STRING
- CHAR - STRING
So this PR introduces a new configuration key: `iceberg.mr.schema.auto.conversion` which if it set to `true` then the `CREATE TABLE` query will not throw an exception, but will convert the columns instead.
For example:
```
CREATE EXTERNAL TABLE not_supported_types (not_supported …
```
=> Hive: Allow auto conversion of Hive types when the CREATE TABLE statement contains a not supported type

spark3-extensions/src/main/scala/org/apache/spark/sql/catalyst/optimizer/RewriteDelete.scala, spark3-extensions/src/main/scala/org/apache/spark/sql/catalyst/optimizer/RewriteMergeInto.scala, spark3-extensions/src/main/scala/org/apache/spark/sql/catalyst/plans/logical/MergeInto.scala, spark3-extensions/src/main/scala/org/apache/spark/sql/catalyst/utils/RewriteRowLevelOperationHelper.scala, spark3-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/MergeIntoExec.scala
This updates MERGE INTO to avoid using a full outer join if it is not needed.
* If there are no "matched" conditions, then all of the actions must be inserts and the merge can be rewritten to append rows instead of rewriting existing data files. In this case, the join used is a left anti join to remove any source row that has a matching target row.
* If there are no "not matched" conditions, then all actions must have a target row. In this case, the join used is a right outer join to discard any source rows that do not match a target row.
* Otherwise, the original full outer join is used.
This commit also updates how rows are handled in `MergeIntoExec`. These changes are needed because target columns are not available if the join is a left anti join. To avoid a failure when building a …
=> Optimize join types for MERGE INTO

api/src/main/java/org/apache/iceberg/DistributionMode.java, core/src/main/java/org/apache/iceberg/TableProperties.java, flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java, flink/src/main/java/org/apache/iceberg/flink/sink/PartitionKeySelector.java, flink/src/test/java/org/apache/iceberg/flink/FlinkCatalogTestBase.java, flink/src/test/java/org/apache/iceberg/flink/TestFlinkTableSink.java, flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSink.java, flink/src/test/java/org/apache/iceberg/flink/sink/TestIcebergStreamWriter.java
Provides a switch in org.apache.flink.sink.FlinkSink to shuffle by partition key, so that each partition/bucket will be wrote by only one task. That will reduce lots of small files in partitioned fanout write policy for flink sink.
=> Flink: Support write.distribution-mode.

api/src/main/java/org/apache/iceberg/expressions/InclusiveMetricsEvaluator.java, api/src/main/java/org/apache/iceberg/expressions/StrictMetricsEvaluator.java, api/src/test/java/org/apache/iceberg/expressions/TestMetricsEvaluatorsNaNHandling.java
This PR is based on the behavior we observed in [here](https://github.com/apache/iceberg/blob/master/core/src/test/java/org/apache/iceberg/TestMetrics.java#L362-L417):
- NaN is always populated as max when present in Parquet, and both max and min for ORC if the first row of the file is NaN
- when lower bound is NaN, upper bound will also always be NaN
- in Java, NaN is considered to be greater than all numbers in comparison
This fixes #1761.
=> API: handle NaN as min/max stats in evaluators

LICENSE, core/src/main/java/org/apache/iceberg/TableProperties.java, spark3-extensions/src/main/scala/org/apache/iceberg/spark/extensions/IcebergSparkSessionExtensions.scala, spark3-extensions/src/main/scala/org/apache/spark/sql/catalyst/expressions/AccumulateFiles.scala, spark3-extensions/src/main/scala/org/apache/spark/sql/catalyst/optimizer/RewriteDelete.scala, spark3-extensions/src/main/scala/org/apache/spark/sql/catalyst/optimizer/RewriteMergeInto.scala, spark3-extensions/src/main/scala/org/apache/spark/sql/catalyst/plans/logical/DynamicFileFilter.scala, spark3-extensions/src/main/scala/org/apache/spark/sql/catalyst/utils/RewriteRowLevelOperationHelper.scala, spark3-extensions/src/main/scala/org/apache/spark/sql/catalyst/utils/SetAccumulator.scala, spark3-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/DynamicFileFilterExec.scala, spark3-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/ExtendedDataSourceV2Strategy.scala, spark3-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMergeIntoTable.java
SQL standard requires an exception to be thrown if the ON clause in MERGE is such that more than 1 row in source matches a row in target
Implements suggestion 1 from Anton in [comment](https://github.com/apache/iceberg/pull/1947#issuecomment-747450897)
```
1. append _row_id and _file columns to the target table
2. do an inner join on the merge condition
3. define an udf that accepts the file name, adds it to the accumulator and retuns 1 => Changed it to an expression to stay in catalyst world.
4. group by _row_id, perform the cardinality check
5. access the accumulator to get the matching files
```
=> Add the cardinality check to detect ambiguous target row for MERGE INTO

core/src/main/java/org/apache/iceberg/CatalogProperties.java, flink/src/main/java/org/apache/iceberg/flink/CatalogLoader.java, flink/src/test/java/org/apache/iceberg/flink/FlinkCatalogTestBase.java, flink/src/test/java/org/apache/iceberg/flink/TestFlinkHiveCatalog.java, flink/src/test/java/org/apache/iceberg/flink/source/TestFlinkInputFormatReaderDeletes.java, hive-metastore/src/main/java/org/apache/iceberg/hive/HiveCatalog.java, site/docs/configuration.md, spark2/src/test/java/org/apache/iceberg/spark/source/TestCatalog.java, spark2/src/test/java/org/apache/iceberg/spark/source/TestCustomCatalog.java
the ongoing work in JDBC catalog #1870 also uses the Hive catalog properties. So it does not make sense to have HIVE prefix for them. Remove those prefix before the initial release for `CatalogProperties`, it will be difficult to change it after released.
=> Core: rename HIVE related catalog properties before release

spark3-extensions/src/main/scala/org/apache/iceberg/spark/extensions/IcebergSparkSessionExtensions.scala, spark3-extensions/src/main/scala/org/apache/spark/sql/catalyst/analysis/MergeIntoTablePredicateCheck.scala, spark3-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMerge.java
This PR disables subqueries in conditions of MERGE operations until we figure out the best way to support them.
=> Spark: Prohibit subqueries in conditions of MERGE operations

build.gradle, site/docs/spark.md, spark3-runtime/LICENSE
tested with AWS EMR:
```
spark-sql> ALTER TABLE prod.db8.sample3 ADD PARTITION FIELD bucket(id,16);
21/01/21 01:06:46 INFO BaseMetastoreTableOperations: Refreshing table metadata from new version: s3://iceberg-test-yzhaoqin/db8.db/sample3/metadata/00001-60f23197-414e-49a8-97e3-00ea40297412.metadata.json
21/01/21 01:06:58 INFO BaseMetastoreTableOperations: Successfully committed to table prod.db8.sample3 in 11492 ms
Time taken: 11.693 seconds
21/01/21 01:06:58 INFO SparkSQLCLIDriver: Time taken: 11.693 seconds
```
=> Spark: add extension to spark 3 runtime

LICENSE, core/src/main/java/org/apache/iceberg/TableProperties.java, spark3-extensions/src/main/scala/org/apache/spark/sql/catalyst/expressions/TransformExpressions.scala, spark3-extensions/src/main/scala/org/apache/spark/sql/catalyst/optimizer/RewriteMergeInto.scala, spark3-extensions/src/main/scala/org/apache/spark/sql/catalyst/plans/logical/MergeInto.scala, spark3-extensions/src/main/scala/org/apache/spark/sql/catalyst/utils/RewriteRowLevelOperationHelper.scala, spark3-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/ExtendedDataSourceV2Strategy.scala, spark3-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/MergeIntoExec.scala, spark3-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMergeIntoTable.java, spark3/src/main/java/org/apache/iceberg/spark/CopySortOrderFields.java, spark3/src/main/java/org/apache/iceberg/spark/OrderField.java, spark3/src/main/java/org/apache/iceberg/spark/SortOrderToSpark.java, spark3/src/main/java/org/apache/iceberg/spark/Spark3Util.java, spark3/src/main/java/org/apache/spark/sql/connector/iceberg/distributions/ClusteredDistribution.java, spark3/src/main/java/org/apache/spark/sql/connector/iceberg/distributions/Distribution.java, spark3/src/main/java/org/apache/spark/sql/connector/iceberg/distributions/Distributions.java, spark3/src/main/java/org/apache/spark/sql/connector/iceberg/distributions/OrderedDistribution.java, spark3/src/main/java/org/apache/spark/sql/connector/iceberg/distributions/UnspecifiedDistribution.java, spark3/src/main/java/org/apache/spark/sql/connector/iceberg/distributions/impl/ClusterDistributionImpl.java, spark3/src/main/java/org/apache/spark/sql/connector/iceberg/distributions/impl/OrderedDistributionImpl.java, spark3/src/main/java/org/apache/spark/sql/connector/iceberg/distributions/impl/UnspecifiedDistributionImpl.java, spark3/src/main/java/org/apache/spark/sql/connector/iceberg/expressions/NullOrdering.java, spark3/src/main/java/org/apache/spark/sql/connector/iceberg/expressions/SortDirection.java, spark3/src/main/java/org/apache/spark/sql/connector/iceberg/expressions/SortOrder.java
- Group and sort the rows based on partition spec and sort order of target table.
- If the above is not available, then group and sort rows based on columns from join condition.
**Note:**
There is proposal from Anton to group and sort rows based on `_file` and `_pos` for unchanged rows and partition spec and sort order for unchanged rows. This can be added in a follow-up.
=> Implement logic to group and sort rows before writing rows for MERGE INTO.

api/src/main/java/org/apache/iceberg/transforms/Dates.java, api/src/main/java/org/apache/iceberg/transforms/ProjectionUtil.java, api/src/main/java/org/apache/iceberg/transforms/Timestamps.java, api/src/main/java/org/apache/iceberg/transforms/TransformUtil.java, api/src/test/java/org/apache/iceberg/expressions/TestStringLiteralConversions.java, api/src/test/java/org/apache/iceberg/transforms/TestDates.java, api/src/test/java/org/apache/iceberg/transforms/TestDatesProjection.java, api/src/test/java/org/apache/iceberg/transforms/TestTimestamps.java, api/src/test/java/org/apache/iceberg/transforms/TestTimestampsProjection.java
This fixes incorrect values produced by date and time transforms and adds tests.
This also updates date and timestamp transform projection methods to include incorrectly transformed values.
Fixes #1680.
=> Fix date and timestamp transforms

LICENSE, build.gradle, core/src/main/java/org/apache/iceberg/util/ArrayUtil.java, core/src/main/java/org/apache/iceberg/util/SerializationUtil.java, flink-runtime/LICENSE, flink/src/main/java/org/apache/iceberg/flink/data/FlinkParquetReaders.java, hive-runtime/LICENSE, mr/src/main/java/org/apache/iceberg/mr/InputFormatConfig.java, mr/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergInputFormat.java, mr/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergSplit.java, mr/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java, mr/src/main/java/org/apache/iceberg/mr/mapreduce/IcebergInputFormat.java, mr/src/main/java/org/apache/iceberg/mr/mapreduce/IcebergSplit.java, pig/src/main/java/org/apache/iceberg/pig/IcebergPigInputFormat.java, spark-runtime/LICENSE, spark3-runtime/LICENSE, spark3/src/main/java/org/apache/iceberg/spark/Spark3Util.java, versions.props
=> [Misc] Remove non-test uses of commons-lang3

flink/src/main/java/org/apache/iceberg/flink/FlinkTableFactory.java, flink/src/main/java/org/apache/iceberg/flink/FlinkTableOptions.java, flink/src/main/java/org/apache/iceberg/flink/IcebergTableSource.java, flink/src/main/java/org/apache/iceberg/flink/source/FlinkSource.java, flink/src/test/java/org/apache/iceberg/flink/FlinkTestBase.java, flink/src/test/java/org/apache/iceberg/flink/TestFlinkTableSource.java, flink/src/test/java/org/apache/iceberg/flink/source/TestFlinkScanSql.java
When using flink to query the iceberg table, the parallelism is the default parallelism of flink, but the number of datafiles on  iceberg table is different. The user do not know how much parallelism should be used, and setting a too large parallelism will cause  resource waste, setting the parallelism too small will cause the query to be slow, so we can add  parallelism infer.
The function is enabled by default. the parallelism is equal to the number of read splits. Of course, the user can manually turn off the infer function. In order to prevent too many datafiles from causing excessive parallelism, we also set a max infer parallelism.  When the infer parallelism exceeds the setting, use the max  parallelism.
In addition, we also need to compare with the limit in the `select` query …
=> Flink: Support inferring parallelism for batch read.

data/src/main/java/org/apache/iceberg/data/orc/GenericOrcWriters.java, flink/src/main/java/org/apache/iceberg/flink/data/FlinkOrcWriters.java, spark/src/main/java/org/apache/iceberg/spark/data/SparkOrcValueWriters.java
This fixes all current instances of `NarrowingCompoundAssignment` warnings when running `./gradlew check --continue`.
This does not handle the possibility of overflow when adding the current elements size or number of elements to the existing `cv.childCount`, but the old code did not handle that either.
I chose to continue to use the addition of `cv.lengths[rowId]`, which could have typically been substituted for `value.size()`  / `data.size()` / `value.numElements()`, in the off chance that the input `ColumnVector` computes the `size` / `numElements` lazily each time that the method is called. I don't personally think that's likely, but we get the same result either way and this avoids unnecessary repeated work if that is ever the case.
This closes issue …
=> [MISC] Fix NarrowingCompoundAssignment warnings

site/docs/aws.md
Client package is not a part of the default AWS bundle and need to be added separately.
=> AWS: fix bug in doc that HTTP client package is not included in bundle

spark3-extensions/src/main/scala/org/apache/spark/sql/catalyst/expressions/TransformExpressions.scala
This PR fixes the bucketed transform in Spark.
=> Spark: Fix bucketed transform expression

spark3-extensions/src/main/scala/org/apache/spark/sql/catalyst/analysis/AlignMergeIntoTable.scala, spark3-extensions/src/main/scala/org/apache/spark/sql/catalyst/analysis/DeleteFromTablePredicateCheck.scala, spark3-extensions/src/main/scala/org/apache/spark/sql/catalyst/analysis/MergeIntoTablePredicateCheck.scala, spark3-extensions/src/main/scala/org/apache/spark/sql/catalyst/optimizer/OptimizeConditionsInRowLevelOperations.scala, spark3-extensions/src/main/scala/org/apache/spark/sql/catalyst/optimizer/PullupCorrelatedPredicatesInRowLevelOperations.scala, spark3-extensions/src/main/scala/org/apache/spark/sql/catalyst/optimizer/RewriteDelete.scala, spark3-extensions/src/main/scala/org/apache/spark/sql/catalyst/optimizer/RewriteMergeInto.scala, spark3-extensions/src/main/scala/org/apache/spark/sql/catalyst/utils/IcebergTable.scala, spark3-extensions/src/main/scala/org/apache/spark/sql/catalyst/utils/PlanUtils.scala, spark3-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestDelete.java, spark3-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMerge.java
- Currently the rules in the extension do not check for target table type.
- This pr makes sure the rules are applied only for iceberg table.
=> Apply iceberg extensions for MERGE INTO and DELETE only for target iceberg table.

spark3-extensions/src/main/scala/org/apache/spark/sql/catalyst/optimizer/RewriteMergeInto.scala
This changes the distribution mode used by default to write the output of MERGE INTO to `none` if the table is unsorted, rather than `range`. Range distribution is expensive because it uses an extra round-robin exchange and has an extra stage to estimate skew. If the sort order of the table is not set, then it is not worth adding the extra stages for the inferred sort order.
=> Do not redistribute MERGE INTO rows unless the table is sorted

core/src/main/java/org/apache/iceberg/TableProperties.java
This PR adds a constant to table properties for the `none` distribution mode.
=> API: Add a constant for none distribution mode

hive-metastore/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java, hive-metastore/src/test/java/org/apache/iceberg/hive/TestHiveMetastore.java, mr/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java, mr/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerNoScan.java
As agreed with the community:
- Iceberg table properties are the canonical source of truth
- HMS table properties should be maintained as much as possible to be in sync with the Iceberg table, but it can only happen on a best effort basis
This PR makes the following changes:
- Ensures that all Iceberg table properties are propagated to the HMS table during `HiveTableOperations` commit
- All HMS table properties are pushed down to Iceberg as well during table creation (except for metadata location and spec props)
- Refactors the various property check assertions scattered throughout various test cases into a single property-focused unit test case
What is left out and should be done in the future:
-  Push property changes occurring via Hive DDL (`ALTER TABLE SET TBLPROPERTIES`) down to …
=> Hive: Push Iceberg table property values to HMS table properties

spark3-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/ExtendedDataSourceV2Strategy.scala, spark3-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/ReplaceDataExec.scala, spark3-extensions/src/test/java/org/apache/iceberg/spark/extensions/SparkRowLevelOperationsTestBase.java, spark3-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestDelete.java, spark3-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMerge.java
This PR invalidates the relation cache after DELETE and MERGE operations.
=> Spark: Refresh relation cache in DELETE and MERGE

spark3-extensions/src/main/scala/org/apache/spark/sql/catalyst/optimizer/RewriteDelete.scala, spark3-extensions/src/main/scala/org/apache/spark/sql/catalyst/optimizer/RewriteMergeInto.scala, spark3-extensions/src/main/scala/org/apache/spark/sql/catalyst/utils/RewriteRowLevelOperationHelper.scala
This PR introduces companion objects for DELETE and MERGE rewrite rules and moves constants there.
=> Spark: Introduce companion objects for DELETE and MERGE rewrite rules

mr/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergOutputFormat.java, mr/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerWithEngine.java
The OutputFormatFactory always got FileFormat.PARQUET as an input parameter. The result is that the extension of the target files were always `.parquet`.
=> Hive: Fix file extensions for written files

mr/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergOutputFormat.java, mr/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerWithEngine.java, mr/src/test/java/org/apache/iceberg/mr/hive/TestTables.java
If we write to the identity partitioned table, then the partition values are store in the manifest file.
Since we failed the provide the partition specification to the `GenericAppenderFactory`, the values are not handled correctly and the returned rows contain `null` for the partition keys.
Fixed the writer creation, and also added a test case.
=> Hive: Fix identity partitioned writes

api/src/main/java/org/apache/iceberg/SortOrder.java, core/src/test/java/org/apache/iceberg/TestSortOrder.java
This PR allows building empty sort orders. Before that, it was failing with a validation exception.
=> Core: Allow building unsorted orders

spark3-extensions/src/main/scala/org/apache/spark/sql/catalyst/optimizer/RewriteDelete.scala, spark3/src/main/java/org/apache/iceberg/spark/Spark3Util.java
This PR makes DELETE respect the distribution mode set in table properties.
=> Spark: Don't distribute records in DELETE if mode is none

core/src/main/java/org/apache/iceberg/hadoop/HadoopCatalog.java, core/src/test/java/org/apache/iceberg/hadoop/TestHadoopCatalog.java
Move to RemoteIterator for scanning directories.
It's not as elegant as using the java8 streaming, but it works with
the prefetching that the s3a and (soon) abfs connectors do, as well
as bailing out more efficiently.
Because each directory is probed with its own getFileStatus and list calls, the overhead of the outer list could be entirely swallowed by those inner probes -at least if there is >1 page of results in the listing *and* the implementation is prefetching. 
Also added check for access errors to also look for AccessDeniedException; that's to support other filesystems and to prepare for HADOOP-15710
=> Improve HadoopCatalog performance/scalability #2124

spark3-extensions/src/main/scala/org/apache/spark/sql/catalyst/utils/RewriteRowLevelOperationHelper.scala, spark3-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/ExtendedDataSourceV2Implicits.scala, spark3/src/main/java/org/apache/iceberg/spark/source/SparkScanBuilder.java
This updates how metadata columns are requested for merge plans. Previously, the merge builder automatically added `_file` and `_pos` metadata columns. But but the left anti join case of `MERGE INTO` uses a non-merge scan. To make the metadata columns available in a more reliable way, this adds `withMetadataColumns` to the Iceberg `ScanBuilder`.
It also adds `ScanBuilderHelper.asIceberg` to get an Iceberg `ScanBuilder` when needed.
=> Refactor metadata column projection in merge plans

spark/src/test/java/org/apache/iceberg/spark/SparkTestBase.java, spark3-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMerge.java
This PR adds a test for modifying a null struct in MERGE.
=> Spark: Add a test for MERGE modifying a null struct

site/docs/aws.md, site/docs/flink.md, site/docs/releases.md, site/docs/spark.md
@rdblue as we discussed in slack, add more details for bug fixes in 0.11. Also fix some typos and add more details in Flink as suggested by #2168
=> Doc: fix miscellaneous comments and add more details in release note for 0.11

hive-metastore/src/main/java/org/apache/iceberg/hive/HiveCatalog.java
I think this should fix the Hive metastore errors that have made `TestCopyOnWriteDelete` flaky. I think this was accidentally caused by https://github.com/apache/iceberg/commit/6731211eaf746c6a4abfe71386ef53172a3fc137. That commit stopped using the constructors for the Hive and Hadoop catalogs and started loading them dynamically. It also didn't use the same default pool size, 2, and added a hard-coded 5.
I think the test is flaky because the first Hive catalog test runs with 5 clients and shares the same metastore instance with the later catalog test for `spark_catalog`.
=> Fix flaky delete test

spark/src/test/java/org/apache/iceberg/spark/SparkTestBase.java, spark3-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMerge.java
This PR adds more tests for `AssignmentAlignmentSupport` that previously required an actual implementation of MERGE.
=> Spark: Add more tests for action alignment in MERGE

project/scalastyle_config.xml, spark3-extensions/src/main/scala/org/apache/spark/sql/catalyst/optimizer/RewriteMergeInto.scala, spark3-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMerge.java
This PR optimizes the insert only case with a single not matched action (the only case supported by Spark 3.0).
=> Spark: Optimize insert only case in MERGE

mr/src/main/java/org/apache/iceberg/mr/hive/serde/objectinspector/IcebergRecordObjectInspector.java, mr/src/test/java/org/apache/iceberg/mr/hive/HiveIcebergTestUtils.java, mr/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerWithEngine.java, mr/src/test/java/org/apache/iceberg/mr/hive/TestHiveShell.java
During the test found several issues with vectorization for which I raised #2120 
There are no issues with vectorization turned off, but having a test case for it helps finding possible issues later
=> Hive: New test case for writing to the table with projection and column specification

core/src/main/java/org/apache/iceberg/BaseFile.java, core/src/main/java/org/apache/iceberg/ManifestGroup.java, core/src/main/java/org/apache/iceberg/ManifestReader.java, core/src/test/java/org/apache/iceberg/TestManifestReaderStats.java
- Please see [this comment](https://github.com/apache/iceberg/pull/1803#discussion_r528061128_) for the reason to have this change
- Please note that this changes the behavior of `recordCount` in `BaseFile`; originally if `BaseFile` was created by avro schema reflection without populating `recordCount`, calling `recordCount()` will throw NPE because its return type is primitive. I'm currently following the same style as `fileSizeInBytes` to return -1 when it is not populated. 
- One implication of this is that the NPE problem described in the original comment will no longer exist, instead metrics evaluators will not filter out anything. 
- Alternatively I can refrain from changing this and accept that `data.recordCount()` could throw NPE in tests, or change the return type of …
=> Core: update record_count behavior, include in manifest reader

core/src/test/java/org/apache/iceberg/TestMetrics.java, data/src/main/java/org/apache/iceberg/data/orc/GenericOrcWriter.java, data/src/main/java/org/apache/iceberg/data/orc/GenericOrcWriters.java, data/src/test/java/org/apache/iceberg/TestMergingMetrics.java, data/src/test/java/org/apache/iceberg/parquet/TestGenericMergingMetrics.java, flink/src/main/java/org/apache/iceberg/flink/data/FlinkOrcWriter.java, flink/src/main/java/org/apache/iceberg/flink/data/FlinkOrcWriters.java, flink/src/main/java/org/apache/iceberg/flink/data/FlinkSchemaVisitor.java, orc/src/main/java/org/apache/iceberg/orc/ORCSchemaUtil.java, orc/src/main/java/org/apache/iceberg/orc/OrcFileAppender.java, orc/src/main/java/org/apache/iceberg/orc/OrcMetrics.java, orc/src/main/java/org/apache/iceberg/orc/OrcRowWriter.java, orc/src/main/java/org/apache/iceberg/orc/OrcValueWriter.java, parquet/src/main/java/org/apache/iceberg/parquet/ParquetValueWriter.java, spark/src/main/java/org/apache/iceberg/spark/data/SparkOrcValueWriter.java, spark/src/main/java/org/apache/iceberg/spark/data/SparkOrcValueWriters.java, spark/src/main/java/org/apache/iceberg/spark/data/SparkOrcWriter.java
- Similar to #1641 
- Renamed a few classes to be shared between Parquet and ORC
- Also noticed an issue where the Spark implementation of `TestMergingMetrics ` didn't handle `Date`/`Timestamp` types as expected: they don't have matching type in `StructInternalRow.get` and the logic default the value to null, and this didn't trigger issue earlier since in the test case they were declared as optional fields. ORC Spark writer handles null values differently and revealed this problem. 
Edit: To reduce the size of this PR I separated some of the changes to #1829, and will rebase this on top of #1829 once that is merged. This PR still contains some of the changes in #1829 to ensure the code can compile and tests can run.
=> Core: Implement NaN counts in ORC

api/src/main/java/org/apache/iceberg/ContentFile.java, api/src/main/java/org/apache/iceberg/DataFile.java, core/src/main/java/org/apache/iceberg/BaseFile.java, core/src/main/java/org/apache/iceberg/DataFiles.java, core/src/main/java/org/apache/iceberg/FileMetadata.java, core/src/main/java/org/apache/iceberg/GenericDataFile.java, core/src/main/java/org/apache/iceberg/GenericDeleteFile.java, core/src/main/java/org/apache/iceberg/V1Metadata.java, core/src/main/java/org/apache/iceberg/V2Metadata.java, core/src/test/java/org/apache/iceberg/TestManifestWriterVersions.java, spark/src/main/java/org/apache/iceberg/spark/SparkDataFile.java, spark/src/test/java/org/apache/iceberg/TestDataFileSerialization.java, spark/src/test/java/org/apache/iceberg/spark/source/TestSparkDataFile.java
This change adds sort_order_id to content file, and allow read and write of this attribute in manifest entry. The logic of populating sort order id in writers from table attribute is not included here and will be the main focus for the next PR, as doing so will likely requires a lot of signature changes. 
**Questions**
- Not sure if sort order should be nullable by default or  0 (from`unsorted_order`): decided as nullable for now, as I think positional delete files shouldn't have sort order (since they should be sorted by file_path and position per spec)
- Do we want only sort order id, or actual sort order struct? Id itself is good for comparison but when merging data/delete files I think we do need the actual sort order struct. Without including it in manifest entries, I think we may …
=> Core: add sort order id to content file

api/src/main/java/org/apache/iceberg/types/Comparators.java, core/src/main/java/org/apache/iceberg/avro/Avro.java, core/src/main/java/org/apache/iceberg/avro/AvroFileAppender.java, core/src/main/java/org/apache/iceberg/avro/AvroMetrics.java, core/src/main/java/org/apache/iceberg/avro/GenericAvroWriter.java, core/src/main/java/org/apache/iceberg/avro/MetricsAwareDatumWriter.java, core/src/main/java/org/apache/iceberg/data/avro/DataWriter.java, data/src/main/java/org/apache/iceberg/data/GenericAppenderFactory.java, flink/src/main/java/org/apache/iceberg/flink/data/FlinkAvroWriter.java, flink/src/main/java/org/apache/iceberg/flink/sink/FlinkAppenderFactory.java, spark/src/main/java/org/apache/iceberg/spark/data/SparkAvroWriter.java
This change is a smaller PR broken down from #1935. There is no change in behavior from this PR. It covers the following:
- add comparator for byte array
- updated field metrics bound type to allow object to byte buffer translation to occur later
- add `metrics()` method to `ValueWriter` for Avro, currently default to empty stream
- create `MetricsAwareDatumWriter` that exposes writer metrics, and replace `DatumWriter` with it in various classes
- add metrics config to avro writer and builder
- create a `AvroMetrics` class that resembles current behavior for producing metrics for avro writer
=> Avro metrics support: create MetricsAwareDatumWriter and some refactors for Avro

spark3-extensions/src/main/scala/org/apache/iceberg/spark/extensions/IcebergSparkSessionExtensions.scala, spark3-extensions/src/main/scala/org/apache/spark/sql/catalyst/analysis/AlignRowLevelOperations.scala, spark3-extensions/src/main/scala/org/apache/spark/sql/catalyst/optimizer/OptimizeConditionsInRowLevelOperations.scala, spark3-extensions/src/main/scala/org/apache/spark/sql/catalyst/optimizer/RewriteDelete.scala, spark3-extensions/src/main/scala/org/apache/spark/sql/catalyst/optimizer/RewriteMergeInto.scala, spark3-extensions/src/main/scala/org/apache/spark/sql/catalyst/optimizer/RewriteUpdate.scala, spark3-extensions/src/main/scala/org/apache/spark/sql/catalyst/utils/RewriteRowLevelOperationHelper.scala, spark3-extensions/src/test/java/org/apache/iceberg/spark/extensions/SparkRowLevelOperationsTestBase.java, spark3-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestCopyOnWriteUpdate.java, spark3-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestDelete.java, spark3-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestUpdate.java
This PR introduces support for UPDATE statements in Spark. Support for subqueries will come in a follow-up PR.
=> Spark: Support UPDATE statements without subqueries

spark3-extensions/src/main/scala/org/apache/iceberg/spark/extensions/IcebergSparkSessionExtensions.scala, spark3-extensions/src/main/scala/org/apache/spark/sql/catalyst/optimizer/RewriteDelete.scala
Since we hope to move our rewrites to the analyzer, this PR removes TODO items that no longer valid.
=> Spark: Remove irrelevant TODO items for row-level ops

flink/src/main/java/org/apache/iceberg/flink/actions/RewriteDataFilesAction.java, flink/src/main/java/org/apache/iceberg/flink/source/RowDataRewriter.java
Now, all the job name of the rewrite data file job is `Data Stream Collect`, and it can not be set. 
So we can’t distinguish the running jobs，the purpose of this PR is to set a different  job name for each job
=> Flink : update rewrite data file job name

spark/src/main/java/org/apache/iceberg/spark/data/SparkAvroReader.java
This PR fixes the `_pos` metadata column in `SparkAvroReader`. Previously, we always returned 0 as `_pos`.
=> Spark: Fix _pos metadata column in SparkAvroReader

api/src/main/java/org/apache/iceberg/ManifestFile.java, api/src/main/java/org/apache/iceberg/expressions/ManifestEvaluator.java, api/src/test/java/org/apache/iceberg/TestHelpers.java, api/src/test/java/org/apache/iceberg/expressions/TestInclusiveManifestEvaluator.java, core/src/main/java/org/apache/iceberg/AllManifestsTable.java, core/src/main/java/org/apache/iceberg/GenericPartitionFieldSummary.java, core/src/main/java/org/apache/iceberg/ManifestsTable.java, core/src/main/java/org/apache/iceberg/PartitionSummary.java, core/src/main/java/org/apache/iceberg/util/ManifestFileUtil.java, core/src/test/java/org/apache/iceberg/TestManifestListVersions.java, core/src/test/java/org/apache/iceberg/TestManifestWriter.java, spark/src/test/java/org/apache/iceberg/TestManifestFileSerialization.java, spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSourceTablesBase.java
Will update manifest evaluator to use this new field after either this or #1747 is merged.
=> Core: add contains_nan to field_summary

data/src/main/java/org/apache/iceberg/data/orc/GenericOrcWriters.java, flink/src/main/java/org/apache/iceberg/flink/data/FlinkOrcWriters.java, spark/src/main/java/org/apache/iceberg/spark/data/SparkOrcValueWriters.java, spark2/src/jmh/java/org/apache/iceberg/spark/source/IcebergSourceNestedListDataBenchmark.java, spark2/src/jmh/java/org/apache/iceberg/spark/source/orc/IcebergSourceNestedListORCDataWriteBenchmark.java, spark2/src/jmh/java/org/apache/iceberg/spark/source/parquet/IcebergSourceNestedListParquetDataWriteBenchmark.java
A performance issue was reported in [Iceberg Slack](https://the-asf.slack.com/archives/CF01LKV9S/p1612381780127800) where ORC writer performed about 400x worse than the Parquet writer for a schema with a list having a large number of elements.
On profiling I found that the majority of time was spent in growing child element vectors for list and map types. Currently we only grow these vectors by the size required to fit the current row. However this causes growth to be triggered for every non-empty row, subsequently resulting in an array copy underneath.
We now increase the vectors by a growth factor of 3 to avoid frequent array allocations and copies. The growth factor 3 was taken from [ORC's Mapreduce writer](https://github.com/apache/orc/blob/2981629a13b9d262570c73974bc09dabcad0184d/java …
=> ORC: Grow list and map child vectors with a growth factor of 3

core/src/main/java/org/apache/iceberg/SchemaUpdate.java, core/src/test/java/org/apache/iceberg/TestSchemaUpdate.java
This PR allows for a `UpdateSchema` sequence to permit adding of a deleted column. 
```java
Schema updatedNested = new SchemaUpdate(SCHEMA, SCHEMA_LAST_COLUMN_ID)
.deleteColumn("preferences.feature1")
.addColumn("preferences", "feature1", Types.BooleanType.get())
.apply();
```
where previously, this was not allowed.
Note this does change the struct ordering of the column, but that's expected.
=> Allow adding of deleted columns

site/docs/spec.md, spark2/src/test/java/org/apache/iceberg/examples/README.md
Follow up of https://github.com/apache/iceberg/pull/2089
=> add the descriptions for last-partition-id in docs

core/src/main/java/org/apache/iceberg/TableProperties.java
Hello, we are thinking to change for default "write.target-file-size-bytes" to 512 MB
-- The current default (unbound file sizes) will never take advantage of any predicate push down
-- This number corresponds well with the Parquet default row-group size (4 row groups/file)
-- This will have no impact on ORC file (BaseTaskWriter#shouldRollToNewFile() makes an exception for ORC files)
This will result in different behaviors, so would be good to see what the community thinks, cc @aokolnychyi  
Thank you
=> Change default write.target-file-size-bytes to 512 MB.

data/src/test/java/org/apache/iceberg/data/TestMetricsRowGroupFilter.java, parquet/src/main/java/org/apache/iceberg/parquet/ParquetConversions.java, parquet/src/main/java/org/apache/iceberg/parquet/ParquetDictionaryRowGroupFilter.java, parquet/src/main/java/org/apache/iceberg/parquet/ParquetMetricsRowGroupFilter.java, parquet/src/test/java/org/apache/iceberg/parquet/TestDictionaryRowGroupFilter.java
This fixes Parquet row group filters when types have been promoted from int to long or from float to double.
The filters are passed the file schema after ids are added, which is used to convert dictionary values or lower/upper bounds. That conversion currently uses the file's types to deserialize, but the filter expression is bound to the table types. If the types differ, then comparison in the evaluator fails.
This updates the conversion to first deserialize the Parquet value and then promote it if the table's type has changed. Only int to long and float to double are needed because those are the only type promotions that use a different representation.
=> Parquet: Fix row group filters with promoted types

hive-metastore/src/test/java/org/apache/iceberg/hive/TestHiveMetastore.java, mr/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergSerDe.java, mr/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java, mr/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerWithEngine.java
When inserting data into an Iceberg table from a Hive table, where the source table has the same columns as the target table, the query fails. This is due to the fact that after the SELECT query completes on the source table, the read column values from the source table will be stuck in the config under `hive.io.file.readcolumn.names`, and will be read by the Serde when writing out the data into the target table and therefore will create the wrong objectinspector. To solve this issue, we should skip column projection pushdown for output tables that we write to.
=> Hive: skip projection pushdown for output tables

mr/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java, mr/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerWithEngine.java
- Adding a test for inserting from joining two other tables
- Enabling inserts from joins on Tez by putting the output committer into the map in `HiveIcebergStorageHandler#configureOutputJobProperties`.
=> Hive: enable inserting data from joins

hive-metastore/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java, mr/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerNoScan.java
Addressing https://github.com/apache/iceberg/issues/2249
=> Hive: removed Iceberg props should be removed from HMS table props too

spark3-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestUpdate.java
This PR makes ignored UPDATE tests deterministic.
=> Spark: Make ignored UPDATE tests deterministic

spark3-extensions/src/main/scala/org/apache/spark/sql/catalyst/optimizer/RewriteDelete.scala, spark3-extensions/src/main/scala/org/apache/spark/sql/catalyst/optimizer/RewriteMergeInto.scala, spark3-extensions/src/main/scala/org/apache/spark/sql/catalyst/optimizer/RewriteUpdate.scala
This PR moves our optimizer rules to use `transform` instead of `resolveOperators`.
=> Spark: Don't use resolveOperators in optimizer rules

core/src/main/java/org/apache/iceberg/util/SortOrderUtil.java, core/src/test/java/org/apache/iceberg/util/TestSortOrderUtil.java
This PR avoid using the schema from `PartitionSpec` in `SortOrderUtil` since unpartitioned specs have an empty schema.
=> Core: Support unpartitioned specs in SortOrderUtil

mr/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergFilterFactory.java
#2254 modified how the Timestamp type is handled in `HiveIcebergFilterFactory.microsFromTimestamp` but forgot to update the tests for filter conversion.
The original change (#2254) fixed the Timestamp / Date filters to work not only in UTC timezone but other timezones as well. The change was verified by adding new tests which were testing with multiple timezones, but the original `TestHiveIcebergFilterFactory.testTimestampType` test was checking the base behavior which were originally wrong and fixed in #2254, so we need to change the test too.
=> Hive: Quick fix for broken TestHiveIcebergFilterFactory.testTimestampType test

aws/src/integration/java/org/apache/iceberg/aws/glue/GlueCatalogNamespaceTest.java, aws/src/main/java/org/apache/iceberg/aws/glue/GlueCatalog.java, aws/src/test/java/org/apache/iceberg/aws/glue/GlueCatalogTest.java
People might store non-Iceberg table in the same Glue database, and `listTables` should list non-Iceberg tables.
=> AWS: do not list non-iceberg table in Glue

flink/src/main/java/org/apache/iceberg/flink/data/RowDataUtil.java, flink/src/test/java/org/apache/iceberg/flink/TestFixtures.java, flink/src/test/java/org/apache/iceberg/flink/TestHelpers.java, flink/src/test/java/org/apache/iceberg/flink/source/TestFlinkInputFormat.java, flink/src/test/java/org/apache/iceberg/flink/source/TestFlinkInputFormatReaderDeletes.java, flink/src/test/java/org/apache/iceberg/flink/source/TestFlinkReaderDeletesBase.java, flink/src/test/java/org/apache/iceberg/flink/source/TestFlinkScan.java, flink/src/test/java/org/apache/iceberg/flink/source/TestFlinkScanSql.java, flink/src/test/java/org/apache/iceberg/flink/source/TestFlinkSource.java, flink/src/test/java/org/apache/iceberg/flink/source/TestStreamingMonitorFunction.java, flink/src/test/java/org/apache/iceberg/flink/source/TestStreamingReaderOperator.java
=> Flink: Refactor flink source tests for FLIP-27 unified source.

spark2/src/main/java/org/apache/iceberg/spark/source/Reader.java, spark3/src/main/java/org/apache/iceberg/spark/Spark3Util.java, spark3/src/main/java/org/apache/iceberg/spark/source/SparkBatchScan.java
This PR fixes `isVectorizationEnabled` in `Spark3Util`. Previously, we would not enable vectorized reads in ORC if Parquet is disabled. That seems a bit odd as the configs should be independent.
=> Spark: Fix vectorization flags

flink/src/main/java/org/apache/iceberg/flink/FlinkCatalog.java
In some cases, I need to get the iceberg table to do some work, such as `RewriteDataFiles`, or modify table schema. When we use the iceberg table of `HiveCatalog`, we may need to construct the `CatalogLoader` first, then construct the `TableLoader`, and then load the iceberg table. The code is relatively complicated, I personally prefer to use sql as much as possible, so I want to change the `org.apache.iceberg.flink.FlinkCatalog#loadIcebergTable` method to public so that we can easily get the iceberg table through the following code .
```
StreamTableEnvironment tenv = StreamTableEnvironment.create(env);
tenv.executeSql(
"CREATE CATALOG iceberg WITH (\n"
+ "  'type'='iceberg',\n"
+ "  'catalog-type'='hive',"
+ "   'warehouse'='hdfs://localhost/user/hive2/warehouse',\n"
+ " …
```
=> Flink: add a catalog() method for FlinkCatalog to exposing iceberg catalog

core/src/main/java/org/apache/iceberg/io/BaseTaskWriter.java, core/src/main/java/org/apache/iceberg/io/OutputFileFactory.java, core/src/main/java/org/apache/iceberg/io/SortedPosDeleteWriter.java
This changes the writers' constructor to accept `StructLike` instead of `PartitionKey`, so that writers could create files using `PartitionData`.
=> Core: change writers constructor to use StructLike

data/src/test/java/org/apache/iceberg/data/DeleteReadTests.java, spark/src/test/java/org/apache/iceberg/spark/source/TestSparkReaderDeletes.java
The unit test `testEqualityDeleteWithFilter` create the table by itself but not create test data. Looks like the idea is to use the same test data from its base class.
=> Spark: Improve the test case testEqualityDeleteWithFilter

core/src/main/java/org/apache/iceberg/hadoop/HadoopCatalog.java, flink/src/main/java/org/apache/iceberg/flink/CatalogLoader.java, flink/src/test/java/org/apache/iceberg/flink/FlinkTestBase.java, flink/src/test/java/org/apache/iceberg/flink/source/TestFlinkReaderDeletesBase.java, hive-metastore/src/main/java/org/apache/iceberg/hive/HiveCatalog.java, hive-metastore/src/main/java/org/apache/iceberg/hive/HiveCatalogs.java, hive-metastore/src/main/java/org/apache/iceberg/hive/HiveClientPool.java, hive-metastore/src/test/java/org/apache/iceberg/hive/HiveMetastoreTest.java, hive-metastore/src/test/java/org/apache/iceberg/hive/HiveTableTest.java, spark/src/test/java/org/apache/iceberg/spark/SparkTestBase.java, spark/src/test/java/org/apache/iceberg/spark/source/TestSparkReaderDeletes.java, spark3-extensions/src/test/java/org/apache/iceberg/spark/extensions/SparkExtensionsTestBase.java
* remove option to create pool w/o a defined size
* deprecate last no-arg constructor in HiveCatalog
* move tests to use no-arg constructor
**NOTE:** the `HiveCatalog` copies a new Hadoop Configuration which is a breaking change from how the constructor used to work. See `HiveMetastoreTest` changes for ramifications.
As discussed in https://github.com/apache/iceberg/pull/2180#issuecomment-770062242
=> HiveCatalog and HiveClientPool fixes

build.gradle, nessie/src/main/java/org/apache/iceberg/nessie/NessieCatalog.java, nessie/src/main/java/org/apache/iceberg/nessie/NessieTableOperations.java, nessie/src/main/java/org/apache/iceberg/nessie/NessieUtil.java, nessie/src/main/java/org/apache/iceberg/nessie/UpdateableReference.java, nessie/src/test/java/org/apache/iceberg/nessie/BaseTestIceberg.java, nessie/src/test/java/org/apache/iceberg/nessie/TestBranchVisibility.java, nessie/src/test/java/org/apache/iceberg/nessie/TestNessieTable.java, versions.props
Contains some "noise" due to the renamed package `com.dremio.nessie` -> `org.projectnessie`.
Implicitly bumps Quarkus to 1.12.1.Final
Quarkus image building requires us to set the system property `quarkus.build.native-image`, which is not particularly
great and should be changed in the future on the Nessie-Quarkus-Gradle-Plugin side. It is a change in the behavior
since Quarkus 1.10 (Nessie 0.3.0 used Quarkus 1.9.1.Final) regarding how the Quarkus platform properties are applied,
which sadly also affects Quarkus builds that do not build a native image. Playing around with applying the Quarkus
bom, as suggested by Quarkus project, in various places (Gradle configs) didn't help here. I suspect, that's some
transitive dependency resolving issue.
=> Bump Nessie to version 0.4.0

build.gradle
As per: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/
I tested this on a new VM w/ no gradle cache. It looks like the only dependencies on JCenter are gradle plugins. Gradle plugins will be automatically moved off jcenter: https://blog.gradle.org/jcenter-shutdown
=> JCenter is shutting down

build.gradle
As [suggested](https://github.com/apache/iceberg/pull/2296#issuecomment-797085585) by @aokolnychyi , we need to shade the runtime antlr4 dep and be independent from Spark.
=> [BUILD] Relocate Antlr4 in spark3 runtime module

core/src/main/java/org/apache/iceberg/actions/BaseExpireSnapshotsActionResult.java, spark/src/main/java/org/apache/iceberg/actions/Actions.java, spark/src/main/java/org/apache/iceberg/actions/BaseSparkAction.java, spark/src/main/java/org/apache/iceberg/actions/ExpireSnapshotsAction.java, spark/src/main/java/org/apache/iceberg/actions/ExpireSnapshotsActionResult.java, spark/src/main/java/org/apache/iceberg/actions/RemoveOrphanFilesAction.java, spark/src/main/java/org/apache/iceberg/spark/actions/BaseExpireSnapshotsSparkAction.java
This PR refactors the action for expiring snapshots and moves it to the new API.
=> Spark: Refactor action for expiring snapshots

core/src/main/java/org/apache/iceberg/SnapshotProducer.java, core/src/main/java/org/apache/iceberg/SnapshotSummary.java, core/src/test/java/org/apache/iceberg/TestSnapshotSummary.java, hive-metastore/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java, mr/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerNoScan.java
This patch:
- Introduces a new snapshot summary metric for `total-files-size`. It was somehow missing up till now, even though it has its companion metrics `added-files-size` and `removed-files-size`. Introducing this total metric makes it consistent with the other 'metric groups'.
- On HiveTableOperations commit, we should populate the HMS statistics using these snapshot metrics. Having these stats populated makes the Hive read query planning significantly faster. In some cases, @pvary's research showed that it led to 10x+ improvement on query compilation times, since in the absence of HMS stats the Hive query planner will recursively list the data files to gather their sizes first before execution.
=> Core/Hive: Introduce total-files-size snapshot metric and populate HMS

core/src/main/java/org/apache/iceberg/TableMetadataParser.java, core/src/test/java/org/apache/iceberg/TestTableMetadata.java
Add missing tests and comments in the table metadata parser related to sort order
@yyanyy
=> Core: add missing tests and comments for sort order

spark2/src/main/java/org/apache/iceberg/spark/source/CustomCatalogs.java
As discussed in https://github.com/apache/iceberg/issues/1502, it's possible for a catalog to be prematurely GC'd in Spark 2. The lifecycle of the catalog should match that of the Spark session, and removing `softValues` from the cache should enforce that.
=> Spark: Remove softValues for spark2 catalog cache

core/src/main/java/org/apache/iceberg/CatalogUtil.java, spark3-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestSnapshotTableProcedure.java
This PR prohibits removal of data files if GC is disabled. Fixes #2366.
=> Core: Don't delete data files on DROP if GC is disabled

api/src/main/java/org/apache/iceberg/TableScan.java, core/src/main/java/org/apache/iceberg/AllDataFilesTable.java, core/src/main/java/org/apache/iceberg/AllEntriesTable.java, core/src/main/java/org/apache/iceberg/AllManifestsTable.java, core/src/main/java/org/apache/iceberg/BaseTableScan.java, core/src/main/java/org/apache/iceberg/DataFilesTable.java, core/src/main/java/org/apache/iceberg/DataTableScan.java, core/src/main/java/org/apache/iceberg/ManifestEntriesTable.java, core/src/main/java/org/apache/iceberg/StaticTableScan.java
Currently `targetSplitSize` is a private method in `BaseTableScan`. However, currently both `SparkBatchQueryScan` (from #2276) and `SparkMergeScan` need to know the scan-specific split size when planning tasks. Therefore, this PR moves it to `TableScan` and makes it public. In addition, this removes the parameter `TableOperations` from the method and replaces it with `tableOps()`.
=> Core: move targetSplitSize() to TableScan interface

core/src/main/java/org/apache/iceberg/hadoop/HadoopFileIO.java, core/src/test/java/org/apache/iceberg/TestCatalogUtil.java
@aokolnychyi this should probably go to 0.11.1
HadoopFileIO currently does not have a no-arg constructor and could not be loaded by the dynamic FileIO loader. But our documentation claims it can be loaded, so we need to fix it asap. There are 2 ways to fix it,
1. add a no-arg constructor to HadoopFileIO, let it implement Configurable, and set configuration in `setConf` method.
2. (current approach in PR) allow the loader to load an implementation that has a constructor taking Hadoop configuration.
To do approach 1, we need to change HadoopFileIO class variable to be not final, and I am a bit hesitated to do that for performance concerns, so I went with approach 2 for now.
=> Core: fix bug that HadoopFileIO cannot be dynamically loaded

api/src/main/java/org/apache/iceberg/RewriteFiles.java, core/src/main/java/org/apache/iceberg/BaseRewriteFiles.java, core/src/test/java/org/apache/iceberg/TableTestBase.java, core/src/test/java/org/apache/iceberg/TestRewriteFiles.java
In iceberg format v2,  we've introduced the row-level delete feature,  which would introduce many delete files ( include positional delete files and insert data files).   Currently the **batch** RewriteAction only works for iceberg format v2, say compacting data files only.  Before expose the format v2 to end users, we need to check whether the common features are OK,   we should provide the ability to rewrite both data files and delete files. 
In this PR,  I'm trying to extend the **RewriteFiles** API to work for both data files and delete files, so that we could implement the format v2's  RewriteFiles Action.
=> Core: Support rewriting delete files.

site/docs/configuration.md
https://iceberg.apache.org/configuration/ still shows default value of write.target-file-size-bytes is Long.MAX_VALUE, which has been changed to 512M after the change "Core: Change default write.target-file-size-bytes to 512 MB (#2220)".
=> Docs: Show the correct default value of write.target-file-size-bytes.

spark3/src/main/java/org/apache/iceberg/spark/source/SparkTable.java, spark3/src/test/java/org/apache/iceberg/actions/TestCreateActions.java
https://github.com/apache/iceberg/issues/2309
A unit test is added. Besides here is the integration test with Apache Spark 3.0.2:
```
spark-sql> describe table extended local.db.table;
21/03/13 00:22:33 INFO BaseMetastoreCatalog: Table loaded by catalog: local.db.table
21/03/13 00:22:35 INFO CodeGenerator: Code generated in 242.060932 ms
21/03/13 00:22:35 INFO CodeGenerator: Code generated in 11.30419 ms
id	bigint
data	string
Not partitioned
Name	local.db.table
Location	/Users/yufei/Downloads/spark-3.0.2-bin-hadoop2.7/warehouse/db/table
Provider	iceberg
Owner	yufei
Table Properties	[current-snapshot-id=none,format=iceberg/parquet]
Time taken: 3.503 seconds, Fetched 12 row(s)
21/03/13 00:22:35 INFO SparkSQLCLIDriver: Time taken: 3.503 seconds, Fetched 12 row(s)
```
=> Spark: Add table location to reserved properties so that the table location shows in Spark SQL Properties.

core/src/main/java/org/apache/iceberg/BaseFile.java, core/src/main/java/org/apache/iceberg/LazyImmutableMap.java, core/src/main/java/org/apache/iceberg/SerializableMap.java, flink/src/test/java/org/apache/iceberg/flink/TestDataFileSerialization.java, flink/src/test/java/org/apache/iceberg/flink/TestHelpers.java
This PR is resolving this comment : https://github.com/apache/iceberg/pull/2258#discussion_r588809379
=> Core: Fix the kryo serialization issue in BaseFile.

flink/src/main/java/org/apache/iceberg/flink/FlinkCatalog.java, flink/src/main/java/org/apache/iceberg/flink/FlinkCatalogFactory.java
This address the [comment](https://github.com/apache/iceberg/blob/master/flink/src/main/java/org/apache/iceberg/flink/FlinkCatalog.java#L99) in [FlinkCatalog](https://github.com/apache/iceberg/blob/master/flink/src/main/java/org/apache/iceberg/flink/FlinkCatalog.java)
=> Flink: Use Namespace in FlinkCatalog.

site/docs/hive.md
As discussed in #2228 we should document that the Hive multi-table inserts are only atomic on table level.
@massdosage, @rdblue, @RussellSpitzer, @jackye1995 could one of you please check my English?
Thanks,
Peter
=> Doc: Document non-atomicity of Hive multi-table inserts

spark/src/main/java/org/apache/iceberg/spark/actions/BaseRewriteManifestsSparkAction.java
This PR adds missing override annotations to the rewrite manifests action in Spark.
=> Spark: Add missing override annotations to rewrite manifests action

spark/src/main/java/org/apache/iceberg/spark/actions/BaseRemoveOrphanFilesSparkAction.java, spark/src/main/java/org/apache/iceberg/spark/actions/BaseRewriteManifestsSparkAction.java
This PR removes redundant casts in refactored actions.
=> Spark: Remove redundant casts in actions

core/src/main/java/org/apache/iceberg/AllDataFilesTable.java, core/src/main/java/org/apache/iceberg/AllEntriesTable.java, core/src/main/java/org/apache/iceberg/AllManifestsTable.java, core/src/main/java/org/apache/iceberg/BaseMetadataTable.java, core/src/main/java/org/apache/iceberg/BaseTransaction.java, core/src/main/java/org/apache/iceberg/DataFilesTable.java, core/src/main/java/org/apache/iceberg/HistoryTable.java, core/src/main/java/org/apache/iceberg/ManifestEntriesTable.java, core/src/main/java/org/apache/iceberg/ManifestsTable.java, core/src/main/java/org/apache/iceberg/PartitionsTable.java, core/src/main/java/org/apache/iceberg/SnapshotsTable.java
This PR implements `HasTableOperations` in metadata and txn tables so that we can leverage it in `SerializedTable` later on.
=> Core: Implement HasTableOperations in metadata and txn tables

flink/src/test/java/org/apache/iceberg/flink/FlinkTestBase.java, flink/src/test/java/org/apache/iceberg/flink/TestFlinkCatalogDatabase.java, flink/src/test/java/org/apache/iceberg/flink/TestFlinkTableSource.java
Currently,  the  FlinkTestBase#sql will returns a `List<Object[]>`,  which is not friendly to assert the results of flink SQL query because for a record,  we have to build a `Object` array , and then use the `Assert.assertArrayEquals((Object[])result,  expected)` to check the equality.   It's hard to assert the record that read from a table with nested column.
So I recommend to return a `List<Row>`  for the `FlinkTestBase#sql` because the flink's  row have considered the equal logic for nested columns, pls see the [equals](https://github.com/apache/flink/blob/master/flink-core/src/main/java/org/apache/flink/types/Row.java#L405) method.
=> Tests: Get row collection from flink sql query.

aws/src/integration/java/org/apache/iceberg/aws/glue/GlueCatalogCommitFailureTest.java, aws/src/main/java/org/apache/iceberg/aws/glue/GlueTableOperations.java, core/src/main/java/org/apache/iceberg/BaseMetastoreTableOperations.java, hive-metastore/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java
- same fix as in #2328 for glue catalog. This case in theory should happen less often for Glue comparing to HMS unless there's internet connectivity issue with the current host at the time the commit is in progress, but still want to handle regardless. 
- in theory, certain exception types from glue may not worth catalog recheck, e.g. client side exception due to invalid input. Personally I think an extra glue check may be cheap enough comparing to the risk of missing a valid case handling and code complexity of listing all kinds of exception type, but I don't really feel strongly either way and comments are welcome. 
- moved `checkCommitStatus()` from `HiveTableOperations` to `BaseMetastoreTableOperations` to allow code reuse.
- tests in `GlueCatalogCommitFailureTest` are heavily based …
=> AWS: handle uncertain catalog state for glue

site/docs/flink.md
Small hotfix for a typo I found when looking through the docs today
=> [DOCS]: Fix typo in Flink docs

spark3/src/main/java/org/apache/iceberg/actions/Spark3SnapshotAction.java
This PR moves `ensureNameMappingPresent` into the try-catch block to ensure we will call abort in case of any errors.
=> Spark: Handle name mapping assignment errors in snapshot action

spark3-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMigrateTableProcedure.java, spark3/src/main/java/org/apache/iceberg/actions/Spark3MigrateAction.java
This PR makes sure we don't call `abortStagedChanges` if `stagedTable` is null.
=> Spark: Abort changes in migrate action only if staging was successful 

spark3/src/main/java/org/apache/iceberg/spark/Spark3Util.java, spark3/src/main/java/org/apache/iceberg/spark/source/SparkTable.java, spark3/src/test/java/org/apache/iceberg/actions/TestCreateActions.java, spark3/src/test/java/org/apache/iceberg/spark/TestSpark3Util.java
Unit test is added. The integration test is blocked by https://github.com/apache/iceberg/issues/2382.
=> Spark: Add table sort-order to reserved table properties

spark3-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMigrateTableProcedure.java, spark3-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestSnapshotTableProcedure.java, spark3/src/main/java/org/apache/iceberg/actions/Spark3MigrateAction.java, spark3/src/main/java/org/apache/iceberg/actions/Spark3SnapshotAction.java
This PR makes sure we always set the snapshot and migrate specific table properties irrespectively of additional properties provided by the user in the command.
=> Spark: Override provided props in snapshot and migrate actions

hive-metastore/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java, mr/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java, mr/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerNoScan.java
This is a PR for the proposal outlined in: https://github.com/apache/iceberg/pull/2367#issuecomment-806687999
Note: The other direction of synchronization (HMS -> Iceberg, via `ALTER TABLE SET TBLPROPERTIES`) will be enabled by https://issues.apache.org/jira/browse/HIVE-24665 at a later point.
=> Hive: Synchronize equivalent HMS and Iceberg properties

python/iceberg/api/expressions/__init__.py, python/iceberg/api/expressions/expression.py, python/iceberg/api/expressions/expressions.py, python/iceberg/api/expressions/inclusive_metrics_evaluator.py, python/iceberg/api/expressions/predicate.py, python/iceberg/api/expressions/projections.py, python/iceberg/api/expressions/reference.py, python/iceberg/api/expressions/strict_metrics_evaluator.py, python/iceberg/api/expressions/term.py, python/iceberg/api/expressions/transform.py, python/iceberg/api/schema.py, python/tests/api/expressions/test_evaluator.py, python/tests/api/expressions/test_expression_binding.py, python/tests/api/expressions/test_predicate_binding.py
Part 1 of N(?) updating python expressions to move it closer to the current state of the java implementation.  This was motivated following review of some of the changes when I started working on some issues in the ResidualEvaluator and on non-identity partition columns.  
The implementation in java has diverged a lot since the initial python implementation, this and the following commits should help move it back in line.  I expect there may be some back and forth on this because I was a little unsure about how to approach this.  cc: @rymurr Let me know what your thoughts are on it.
=> [python] Updating Expressions with the Term object used in Predicates

.github/workflows/java-ci.yml
https://github.com/apache/spark/pull/32096
=> [BUILD] Fix the java.net.BindException when testing with Github Action

nessie/src/main/java/org/apache/iceberg/nessie/NessieTableOperations.java
This minor fix changes how the Nessie Table ops commits a table. Instead of using the single table commit endpoint, it will now use the multi-table endpoint. This is more stable long-term as the single table commit may be deprecated.
=> Nessie: change commit operation type

spark3/src/main/java/org/apache/iceberg/spark/SparkCatalog.java, spark3/src/test/java/org/apache/iceberg/spark/sql/TestAlterTable.java
=> Spark: Prevent setting sort-order by using "ALTER TABLE ... SET TBLPROPERTIES"

core/src/main/java/org/apache/iceberg/actions/BaseMigrateTableActionResult.java, core/src/main/java/org/apache/iceberg/actions/BaseSnapshotTableActionResult.java, spark/src/main/java/org/apache/iceberg/actions/CreateAction.java, spark3/src/main/java/org/apache/iceberg/actions/Spark3MigrateAction.java, spark3/src/main/java/org/apache/iceberg/actions/Spark3SnapshotAction.java, spark3/src/main/java/org/apache/iceberg/spark/actions/BaseMigrateTableSparkAction.java, spark3/src/main/java/org/apache/iceberg/spark/actions/BaseSnapshotTableSparkAction.java, spark3/src/main/java/org/apache/iceberg/spark/actions/BaseTableCreationSparkAction.java, spark3/src/main/java/org/apache/iceberg/spark/actions/BaseTableMigrationSparkAction.java
This PR moves our snapshot and migrate actions to use the new API.
=> Spark: Refactor snapshot and migrate actions

site/docs/flink.md
The snippets in Flink section are a bit outdated with some compile errors. This PR fixes the problem.
=> Doc: Fix broken Flink DataStream snippets

hive-metastore/src/test/java/org/apache/iceberg/hive/TestHiveMetastore.java, mr/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerWithEngine.java, mr/src/test/java/org/apache/iceberg/mr/hive/TestHiveShell.java
In #2437 we seem to hit an issue where the tests are failing because of resource problems.
Github infra handles the timeouts in this case, but when there is a timeout the logs are not collected.
We should handle the timeouts on the tests itself. This is a good practice and in this case we might be able to squeeze out more information about the problems from the logs.
Used a 40s timeout in most tests (usually they run around 5-10 s on my local machine), and used 100s for longer tests (they run around 20-30 s on my local machine). Let's see how they behave on the CI infra.
=> Hive: Add timeout for TestHiveIcebergStorageHandlerWithEngine tests

.github/workflows/java-ci.yml
See https://github.com/apache/iceberg/pull/2451#issuecomment-819674109
See https://lists.apache.org/thread.html/r40b2da182952f21a3b94696e6f1bf8594e7ff16e1c5979fe8b2d51c8%40%3Cbuilds.apache.org%3E
Fixes #2475
=> Try reverse DNS lookup workaround for Ubunut GitHub runners

build.gradle, nessie/src/main/java/org/apache/iceberg/nessie/NessieCatalog.java, nessie/src/main/java/org/apache/iceberg/nessie/NessieTableOperations.java, versions.props
* Bump Nessie version to 0.5.1
* Support incremental builds w/ the Nessie-Gradle-Plugin
* Simplify the `:iceberg-nessie` code in `build.gradle`
=> Bump Nessie version to 0.5.1

site/README.md, site/docs/aws.md, site/docs/getting-started.md, site/docs/nessie.md, site/docs/releases.md, site/docs/spark-configuration.md, site/mkdocs.yml, site/requirements.txt
This uses `mkdocs-markdownextradata-plugin` to template things like versions. Hopefully this will simplify updating docs on releases
cc @aokolnychyi I saw #2427 and thought this might save a bit of time in the future.
=> Simplify Docs release by adding a version template

spark3/src/main/java/org/apache/iceberg/spark/procedures/BaseProcedure.java, spark3/src/main/java/org/apache/iceberg/spark/procedures/ExpireSnapshotsProcedure.java, spark3/src/main/java/org/apache/iceberg/spark/procedures/RemoveOrphanFilesProcedure.java, spark3/src/main/java/org/apache/iceberg/spark/procedures/RewriteManifestsProcedure.java
This PR migrates our procedures to use `SparkActions`, the new entry point for interacting with actions.
=> Spark: Use new actions entry point in procedures

build.gradle
Iceberg uses the Parquet 1.11.x. Parquet removed all shading of `org.codehaus.jackson` after version 1.3.3 as the following commits show.
1. https://github.com/apache/parquet-mr/commit/9652d97f63a05d410fae941f14d684b8dfcedd44
2. https://github.com/apache/parquet-mr/commit/7def49cdd57d670a87abdf264aef5a461de9610a
3. https://github.com/apache/parquet-mr/commit/5ffaba99e7b10e55df9b49e3401396660e3262a7
Iceberg still assumes `org.codehaus.jackson` is shaded in Parquet, then double shades it. This is not only unnecessary, but also causes problem. Integration with Parquet 1.12 may fail due to this.
=> Spark: Remove the shading of org.codehaus.jackson.

core/src/main/java/org/apache/iceberg/io/OutputFileFactory.java, spark/src/main/java/org/apache/iceberg/actions/RewriteDataFilesAction.java, spark/src/main/java/org/apache/iceberg/spark/source/BatchDataReader.java, spark/src/main/java/org/apache/iceberg/spark/source/EqualityDeleteRowReader.java, spark/src/main/java/org/apache/iceberg/spark/source/RowDataReader.java, spark/src/main/java/org/apache/iceberg/spark/source/RowDataRewriter.java, spark/src/main/java/org/apache/iceberg/spark/source/SparkAppenderFactory.java, spark/src/test/java/org/apache/iceberg/spark/source/TestSparkReaderDeletes.java, spark2/src/main/java/org/apache/iceberg/spark/source/IcebergSource.java, spark2/src/main/java/org/apache/iceberg/spark/source/Reader.java, spark2/src/main/java/org/apache/iceberg/spark/source/StreamingWriter.java, spark2/src/main/java/org/apache/iceberg/spark/source/Writer.java, spark3/src/main/java/org/apache/iceberg/spark/source/SparkBatchQueryScan.java, spark3/src/main/java/org/apache/iceberg/spark/source/SparkBatchScan.java, spark3/src/main/java/org/apache/iceberg/spark/source/SparkMergeScan.java, spark3/src/main/java/org/apache/iceberg/spark/source/SparkScanBuilder.java, spark3/src/main/java/org/apache/iceberg/spark/source/SparkWrite.java, spark3/src/main/java/org/apache/iceberg/spark/source/SparkWriteBuilder.java
This PR refactors our code to pass around `Table` object instead of individual things like spec, sort order, etc.
Originally, we used to separately pass `FileIO`, `LocationProvider`, properties as our `Table` objects were not serializable. We have to modify a lot of places each time we need add one more item to pass (e.g. sort order). That’s why passing `Table` instances to executors should simplify the configuration and make APIs easier.
=> Spark: Pass Table object to executors

spark3-extensions/src/main/scala/org/apache/spark/sql/catalyst/parser/extensions/IcebergSparkSqlExtensionsParser.scala
The https://github.com/antlr/antlr4/commit/ac9f7530 has been fixed in upstream, so remove the workaround to simplify code, see also https://github.com/apache/spark/pull/32238
=> Spark: Remove antlr workaround

spark/src/main/java/org/apache/iceberg/spark/SparkReadOptions.java, spark3/src/main/java/org/apache/iceberg/spark/FileScanTaskSetManager.java, spark3/src/main/java/org/apache/iceberg/spark/source/SparkFilesScan.java, spark3/src/main/java/org/apache/iceberg/spark/source/SparkFilesScanBuilder.java, spark3/src/main/java/org/apache/iceberg/spark/source/SparkTable.java, spark3/src/test/java/org/apache/iceberg/spark/source/TestSparkFilesScan.java
This PR adds `SparkFilesScan` that can be used to load a list of file scan tasks.
=> Spark: Add SparkFilesScan

core/src/main/java/org/apache/iceberg/util/ManifestFileUtil.java
Previously the boxed value of contains NaN would be null if the table
was made before NaN stats were implemented. This leads to an NPE when
being unboxed. To fix this we use the Boxed boolean and on null report
"true" since we do not know if the partition contains any NaN values. In
addition we move this below the "allValuesNull" check just in case that
would have allowed us to ignore the manifest since the values are all null.
Fixes (#2492 )
=> Core: Fix NPE caused by Unboxing a Null in ManifestFileUtil (#2492)

aws/src/integration/java/org/apache/iceberg/aws/glue/GlueCatalogCommitFailureTest.java, hive-metastore/src/test/java/org/apache/iceberg/hive/TestHiveCommits.java, versions.props
Current mockito version (1.x) used by Iceberg is 6+ years old, so upgrading to a newer version (3.x) to take advantage of the latest feature set and any bugfixes.
=> Upgrade mockito version

nessie/src/main/java/org/apache/iceberg/nessie/NessieTableOperations.java
In case the Nessie endpoint did not respond or some other network error that makes it impossible
to detect whether the Nessie server got the request and, more importantly, get the response.
This PR adds a `catch (org.projectnessie.client.http.HttpClientException)` and re-throws it as
the new `CommitStateUnknownException`.
Related to #2328
=> Use `CommitStatusUnknownException` for Nessie

core/src/main/java/org/apache/iceberg/TableOperations.java
Per description of https://github.com/apache/iceberg/pull/57, the
snapshot ID is expected to be positive.  In the very unlikely edge case
`Math.abs` can return a negative result, i.e. when argument is
`Long.MIN_VALUE`.
=> Ensure snapshot ID is positive

spark/src/main/java/org/apache/iceberg/spark/source/RowDataRewriter.java, spark/src/main/java/org/apache/iceberg/spark/source/SparkAppenderFactory.java, spark/src/test/java/org/apache/iceberg/spark/source/TestSparkAppenderFactory.java, spark/src/test/java/org/apache/iceberg/spark/source/TestSparkMergingMetrics.java, spark2/src/main/java/org/apache/iceberg/spark/source/Writer.java, spark3/src/main/java/org/apache/iceberg/spark/source/SparkWrite.java
As discussed in : https://github.com/apache/iceberg/pull/2362, rebased and submit part of my PR: https://github.com/apache/iceberg/pull/2240 about the SparkAppenderFactoryBuilder
=> Spark: Add builder pattern to SparkAppenderFactory to handle increasing number of arguments

aws/src/main/java/org/apache/iceberg/aws/s3/S3FileIO.java, aws/src/main/java/org/apache/iceberg/aws/s3/S3InputFile.java, aws/src/main/java/org/apache/iceberg/aws/s3/S3OutputFile.java, aws/src/main/java/org/apache/iceberg/aws/s3/S3URI.java
While `S3InputFile` and `S3OutputFile` are public, in order to build a custom `FileIO` using them, `S3URI` needs to be public like the rest of the arguments in their public constructors.
PTAL @danielcweeks @jackye1995 - Thanks!
=> AWS: Remove S3URI usage from public constructors

api/src/main/java/org/apache/iceberg/Schema.java, api/src/main/java/org/apache/iceberg/UpdateSchema.java, core/src/main/java/org/apache/iceberg/SchemaParser.java, core/src/main/java/org/apache/iceberg/SchemaUpdate.java, core/src/main/java/org/apache/iceberg/TableMetadata.java, core/src/main/java/org/apache/iceberg/util/JsonUtil.java, core/src/test/java/org/apache/iceberg/TestSchemaUpdate.java, core/src/test/java/org/apache/iceberg/TestTableMetadata.java, core/src/test/resources/TableMetadataV2Valid.json
Continuation of #2354
@yyanyy @rdblue @openinx @aokolnychyi 
Spec with row identifier:
```
{
"type": "struct",
"schema-id": 1,
"row-identifiers": [
1,
2
],
"fields": [
{
"id": 1,
"name": "x",
"required": true,
"type": "long"
},
{
"id": 2,
"name": "y",
"required": true,
"type": "long",
"doc": "comment"
},
{
"id": 3,
"name": "z",
"required": true,
"type": "long"
}
]
}
```
New Schema toString:
```
table {
fields {
1: x: required long
2: y: required long (comment)
3: z: required long
}
row identifiers { 1,2 }
}
```
Update row identifier rules:
1. row identifier should be added through `UpdateSchema.addRowIdentifier(columnName)`
2. the column added should exist in schema or a part of the newly added columns (to make adding a new primary key a single atomic update)
3. rename, move column should …
=> Core: add row identifier to schema

spark3/src/main/java/org/apache/iceberg/spark/SparkFilters.java, spark3/src/test/java/org/apache/iceberg/spark/TestSparkFilters.java
Before this patch if Spark passes through a filter on an Instant the
comparison will fail in Iceberg due to our lack of handling of Instant
literals. To fix this we convert Instants and LocalDates like we do for Timestamp and
Date in the filter conversion code.
=> Spark: Handle Instant and LocalDate in filter expressions (#2530)

build.gradle
bintray is being sunset. The Palantir plugins can now be found at https://plugins.gradle.org/m2/. Therefore we can remove http://palantir.bintray.com/releases from the repositories.
This relates to https://github.com/apache/iceberg/issues/2462.
=> Build: Remove bintray from repositories.

build.gradle, site/docs/aws.md
@pvary @yyanyy adding the AWS module to the Hive runtime jar. Verified with EMR 6.3.0 (Hive 3.1.2) that I can create external Glue type table and query successfully:
```
0: jdbc:hive2://localhost:10000> CREATE EXTERNAL TABLE db10.sample234
. . . . . . . . . . . . . . . .> STORED BY 'org.apache.iceberg.mr.hive.HiveIcebergStorageHandler'
. . . . . . . . . . . . . . . .> TBLPROPERTIES ('iceberg.catalog'='glue');
INFO  : Compiling command(queryId=hive_20210503024236_8bdfc3e3-6b80-4731-a5d8-0e7f15026254): CREATE EXTERNAL TABLE db10.sample234
STORED BY 'org.apache.iceberg.mr.hive.HiveIcebergStorageHandler'
TBLPROPERTIES ('iceberg.catalog'='glue')
INFO  : Concurrency mode is disabled, not creating a lock manager
INFO  : Semantic Analysis Completed (retrial = false)
INFO  : Returning Hive schema: …
```
=> Hive: add iceberg-aws to Hive runtime

api/src/main/java/org/apache/iceberg/UpdateSchema.java, core/src/main/java/org/apache/iceberg/SchemaUpdate.java
@rdblue thank you for merging the PR, here is the fix for Collection as input type.
=> Core: use Collection for input of UpdateSchema.setIdentifierFields

site/docs/javadoc/index.html, site/docs/releases.md
This PR adds already deployed release notes for 0.11.1 and updates references to refer to 0.11.1 instead of 0.11.0.
=> Docs: Add release notes for 0.11.1 and update references

hive-metastore/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java, hive-metastore/src/test/java/org/apache/iceberg/hive/TestHiveCommitLocks.java
Following up on https://github.com/apache/iceberg/issues/2540. 
This commit introduces table-level JVM locks for commit operations to avoid requesting HMS locks unnecessarily when multiple threads are trying to commit to the same table concurrently. The implementation uses a lock cache in order to instantiate any new locks in a thread-safe manner and evict table keys over time to avoid caching table keys indefinitely.
@RussellSpitzer @raptond @pvary @aokolnychyi
=> Hive: add table level JVM lock on HiveCatalog commit operation

mr/src/main/java/org/apache/iceberg/mr/Catalogs.java, mr/src/main/java/org/apache/iceberg/mr/InputFormatConfig.java, site/docs/hive.md
@pvary, @marton-bod, @lcspinter, @rdblue
As @openinx suggested in #2535, we lack documentation for Hive catalog loading after #2129 is merged. This PR adds examples of loading the catalog and creating tables with custom catalogs. I also reorganized the doc to follow the same structure as Spark and Flink, and added more details for each section.
Also there are some documentations in the code that were not updated so I also fixed those.
The doc changes are quite messy, using the split view to read the updated content might be easier, thanks!
=> Doc: refactor Hive documentation with catalog loading examples

api/src/main/java/org/apache/iceberg/actions/RewriteDataFiles.java, core/src/main/java/org/apache/iceberg/actions/BinPackStrategy.java, core/src/test/java/org/apache/iceberg/actions/TestBinPackStrategy.java
Remove explicit staregy api in Rewrite Data Files APi so that we can more easily add strategies with custom arguements, such as "sort(SortOrder ...)
Change BinPack Defaults and organization to better handle small and large files
Removes the output size parameter and replaces it with a constant check clause to see if the output of the rewrite would produce a target size file or the input exceeds the MIN_INPUT_FILES param
=> Refactor of RewriteDataFiles and BinPackStrategy

api/src/main/java/org/apache/iceberg/Schema.java, flink/src/main/java/org/apache/iceberg/flink/FlinkCatalog.java, flink/src/main/java/org/apache/iceberg/flink/FlinkSchemaUtil.java, flink/src/main/java/org/apache/iceberg/flink/IcebergTableSink.java, flink/src/test/java/org/apache/iceberg/flink/SimpleDataUtil.java, flink/src/test/java/org/apache/iceberg/flink/TestChangeLogTable.java, flink/src/test/java/org/apache/iceberg/flink/TestFlinkCatalogTable.java, flink/src/test/java/org/apache/iceberg/flink/TestFlinkSchemaUtil.java, flink/src/test/java/org/apache/iceberg/flink/source/BoundedTableFactory.java, flink/src/test/java/org/apache/iceberg/flink/source/BoundedTestSource.java, flink/src/test/java/org/apache/iceberg/flink/source/ChangeLogTableTestBase.java, flink/src/test/java/org/apache/iceberg/flink/source/TestBoundedTableFactory.java, flink/src/test/resources/META-INF/services/org.apache.flink.table.factories.Factory
This is built on top of https://github.com/apache/iceberg/pull/2354 
As we will define an apache iceberg sink table in flink+hive catalog, so you will need to follow all those steps in [here](https://iceberg.apache.org/flink/#preparation).
Another side, we will define an mysql CDC table in catalog, so we will need to download the flink-sql-connector-mysql-cdc-1.2.0.jar from [here](https://github.com/ververica/flink-cdc-connectors/wiki/Downloads) and put it under the `$FLINK_HOME/lib` directory:
```bash
wget https://repo1.maven.org/maven2/com/alibaba/ververica/flink-sql-connector-mysql-cdc/1.2.0/flink-sql-connector-mysql-cdc-1.2.0.jar
cp flink-sql-connector-mysql-cdc-1.2.0.jar $FLINK_HOME/lib/
```
You need to start a local mysql server and then enable the binlog (Pls follow the …
=> Flink: Support SQL primary key

core/src/main/java/org/apache/iceberg/CatalogUtil.java, mr/src/main/java/org/apache/iceberg/mr/Catalogs.java, mr/src/main/java/org/apache/iceberg/mr/InputFormatConfig.java, mr/src/test/java/org/apache/iceberg/mr/TestCatalogs.java, mr/src/test/java/org/apache/iceberg/mr/TestIcebergInputFormats.java, mr/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerLocalScan.java, mr/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerNoScan.java, mr/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerWithMultipleCatalogs.java, mr/src/test/java/org/apache/iceberg/mr/hive/TestTables.java, site/docs/aws.md, site/docs/hive.md
As discussed in #2544, make Hive catalog experience consistent with Spark and Flink, specifically:
1. when `type` is `null`, look at `catalog-impl`, if that is also `null` then use `HiveCatalog` as default.
2. there is also no need to have templates `CATALOG_WAREHOUSE_TEMPLATE` and `CATALOG_CLASS_TEMPLATE`, because they are unified in `CatalogProperties`.
I also rewrote all the tests to make each test case clear in separated tests instead of a single giant test, please take a look if I missed any edge case in testing.
@pvary @marton-bod @lcspinter @aokolnychyi @rdblue
=> Hive: unify catalog experience across engines

hive-metastore/src/test/java/org/apache/iceberg/hive/TestHiveMetastore.java, mr/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java, mr/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerNoScan.java
Following up on https://github.com/apache/iceberg/issues/2554.
We should enable dropping HMS tables even if the metadata files have been corrupted/deleted in the meantime.
@RussellSpitzer @rdblue @pvary
=> Hive: enable dropping HMS tables despite metadata problems

core/src/main/java/org/apache/iceberg/MetricsConfig.java, core/src/main/java/org/apache/iceberg/SchemaUpdate.java, core/src/main/java/org/apache/iceberg/TableProperties.java, core/src/test/java/org/apache/iceberg/TestSchemaAndMappingUpdate.java
This is for #2079, when we transform the schema we should update the metrics as well automatically.
Longer term we may wish to consider also migrating the metrics to column references, but either way for backwards compatibility we should preserve the name based fields.
=> Handle metrics during schema transformation

.gitignore
I have a number of `.out` folders that are getting in the way of my tab completion when I move around between different folders.
These are generated by gradle, and so I've added them to the .gitignore.
There is an existing entry, `out`, which does not catch these but is listed under the `gradle` section. I've removed it. It was added in a PR that also added some automation for the site, so I built the site locally and clicked around to se if an `out` log was generated but it was not.
=> [INFRA] Add .out folders to gitignore

deploy.gradle
=> Build: Support overwrite maven repo by gradle properties

core/src/main/java/org/apache/iceberg/BaseSnapshot.java, core/src/main/java/org/apache/iceberg/MergingSnapshotProducer.java, core/src/main/java/org/apache/iceberg/TableMetadata.java
We need the same thing as [here](https://github.com/apache/iceberg/blob/83886c87f516afed7e625bed7f5749838217138c/core/src/main/java/org/apache/iceberg/SnapshotProducer.java#L315) in the context of eventual consistency. Otherwise, we hits a NPE like this. We need a fix even though it is a WARN. 
```
timestamp="2021-04-23T22:35:23,938+0000",level="WARN",threadName="pool-1-thread-1",appName="spark-driver",logger="org.apache.iceberg.SnapshotProducer",message="Failed to notify listeners",exception="java.lang.NullPointerException
at org.apache.iceberg.MergingSnapshotProducer.updateEvent(MergingSnapshotProducer.java:377)
at org.apache.iceberg.SnapshotProducer.notifyListeners(SnapshotProducer.java:329)
at org.apache.iceberg.SnapshotProducer.commit(SnapshotProducer.java:324)
at …
```
=> Core: Fix the NPE while updating event in the context of eventual consistency.

core/src/main/java/org/apache/iceberg/BaseMetastoreTableOperations.java, core/src/main/java/org/apache/iceberg/TableProperties.java
Currently, the minWaitMs and maxWaitMs are 1000 by default, we should add the configs of check-status to TableProperties.
I don't know if the default values I configured are appropriate.
=> Core: Add check-status config to TableProperties.

core/src/main/java/org/apache/iceberg/BaseMetastoreTableOperations.java, nessie/src/main/java/org/apache/iceberg/nessie/NessieTableOperations.java
Fix null tableName when logging in checkCommitStatus for Nessie tables and enforce tableName is implemented at compile time.
Arguably, `tableName` _might_ be something that we want to make part of the interface for `TableOperations`, but that's a larger discussion.
This will fix the [currently `null` tableName](https://github.com/apache/iceberg/blob/32ce969218b75915cb7396c541bdc19f4ac8bd9f/core/src/main/java/org/apache/iceberg/BaseMetastoreTableOperations.java#L72-L74) logs in [`checkCommitStatus`](https://github.com/apache/iceberg/blob/32ce969218b75915cb7396c541bdc19f4ac8bd9f/core/src/main/java/org/apache/iceberg/BaseMetastoreTableOperations.java#L274-L311) for Nessie tables, as well as enforce this issue doesn't occur when new catalogs are added if they derive their operations from …
=> [CORE] Enforce tableName is implemented in BaseMetastoreTableOperations for logging

core/src/main/java/org/apache/iceberg/MicroBatches.java
1.  `StreamingOffset` stores file index as `long` - so changing `MicroBatches.startFileIndex` from `int` to `long`.
2. renaming `MicroBatches.isStarting` to `MicroBatches.scanAllFiles` - as `isStarting` is **when** it is used, in terms of the callers state - whereas, `scanAllFiles` is the actual **what** `MicroBatches.generate` should do.
this is part of effort #2611 & is copied from #2272.
=> minor refactoring in MicroBatches class to prep for Spark3 streaming change

nessie/src/main/java/org/apache/iceberg/nessie/NessieCatalog.java
Explicitly log a warning when the mandatory `warehouse` option is missing, otherwise the thrown exception can get missed in the "silent-ish catch". in `o.a.i.spark.Spark3Util.catalogAndIdentifier(o.a.s.sql.SparkSession, List<String>, o.a.s.sql.connector.catalog.CatalogPlugin)`
in the code block
```
Pair<CatalogPlugin, Identifier> catalogIdentifier = SparkUtil.catalogAndIdentifier(nameParts,
catalogName ->  {
try {
return catalogManager.catalog(catalogName);
} catch (Exception e) {
return null;
}
},
Identifier::of,
defaultCatalog,
currentNamespace
);
```
=> Nessie: Explicitly log warning, when mandatory `warehouse` option is missing

hive-metastore/src/main/java/org/apache/iceberg/hive/HiveSchemaUtil.java, mr/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java, mr/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergOutputCommitter.java, mr/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergOutputFormat.java
This pr improved some code style.
=> Hive: Improve code style

nessie/src/main/java/org/apache/iceberg/nessie/TableReference.java
This code part shouldn't be affected by
https://errorprone.info/bugpattern/StringSplitter as we're checking
explicitly whether the string contains a `@` before splitting:
`if (path.contains("@"))`.
=> Use Guava Splitter to fix StringSplitter warning

.asf.yaml
This patch enables the Wiki and Project Board features for the Iceberg
repository.
Please consult the following links for more information about these
features:
- [Project Boards](https://docs.github.com/en/issues/organizing-your-work-with-project-boards)
- [Wikis](https://docs.github.com/en/communities/documenting-your-project-with-wikis/about-wikis)
=> Enable Github Wiki and Project Board features

core/src/main/java/org/apache/iceberg/ReachableFileUtil.java, core/src/test/java/org/apache/iceberg/util/TestReachableFileUtil.java
This PR adds support for retrieving version hint location for static tables to unblock PR #2415.
=> Core: Support retrieving version hint location for static tables

spark2/src/test/java/org/apache/iceberg/spark/source/TestCatalog.java, spark2/src/test/java/org/apache/iceberg/spark/source/TestCustomCatalog.java
I came across this minor typo working on a separate issue.
I'd include it in that work to reduce commits, but ultimately I won't need to touch this file in that other PR.
After discussing with Ryan Murr, we've decided to rewrite some of the precondition error messages to be of the standard form `cannot do X, reason. Optionally how to fix`, to be more consistent with the projects guidelines.
=> Clarify preconditions in spark 2 TestCatalog initialization

build.gradle, hive3/src/main/java/org/apache/iceberg/mr/hive/vector/CompatibilityHiveVectorUtils.java, hive3/src/main/java/org/apache/iceberg/mr/hive/vector/HiveIcebergVectorizedRecordReader.java, hive3/src/main/java/org/apache/iceberg/mr/hive/vector/HiveVectorizedReader.java, hive3/src/main/java/org/apache/iceberg/mr/hive/vector/VectorizedRowBatchIterator.java, mr/src/main/java/org/apache/hadoop/hive/ql/exec/vector/VectorizedSupport.java, mr/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergInputFormat.java, mr/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergSerDe.java, mr/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java, mr/src/main/java/org/apache/iceberg/mr/mapred/AbstractMapredIcebergRecordReader.java, mr/src/main/java/org/apache/iceberg/mr/mapred/MapredIcebergInputFormat.java, mr/src/main/java/org/apache/iceberg/mr/mapreduce/IcebergInputFormat.java, mr/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerWithEngine.java, settings.gradle
Currently Hive relies on org.apache.iceberg.mr.mapreduce.IcebergInputFormat for reading data from Iceberg. This in turn relies on the internal reader implementations for the various file formats, such as GenericOrcReader(s). Unfortunately for Hive, the whole read pipeline is record based, whereas GenericRecord instances hold the information on which Hive has to use the Iceberg object inspectors to retrieve the encoded data from.
From a design point of view I see 3 layers where during reading data flows upwards:
- Execution engine: Hive
- Table format: Iceberg
- File format: ORC/Parquet/Avro
The current design however combines the two bottom layers, and although Hive already has support for vectorized execution, and already has implementations for vectorized reading from various file …
=> Hive: Vectorized ORC reads for Hive

api/src/main/java/org/apache/iceberg/ManifestFile.java, api/src/test/java/org/apache/iceberg/TestHelpers.java, api/src/test/java/org/apache/iceberg/expressions/TestInclusiveManifestEvaluator.java, core/src/main/java/org/apache/iceberg/GenericManifestFile.java, core/src/main/java/org/apache/iceberg/ManifestWriter.java, core/src/main/java/org/apache/iceberg/SnapshotProducer.java, core/src/main/java/org/apache/iceberg/V2Metadata.java, core/src/test/java/org/apache/iceberg/TestManifestListVersions.java, flink/src/test/java/org/apache/iceberg/flink/sink/TestIcebergFilesCommitter.java, spark/src/main/java/org/apache/iceberg/actions/ManifestFileBean.java
@flyrain @rdblue @ggershinsky 
first step based on draft #2520, simply add `keyMetadata` to the interface and implementations, pass in `null` for any caller.
=> Core: add key_metadata to ManifestFile spec

flink/src/main/java/org/apache/iceberg/flink/FlinkCatalogFactory.java, site/docs/flink.md, site/docs/spark-configuration.md, spark3/src/main/java/org/apache/iceberg/spark/SparkCatalog.java
By default the catalog cache is enabled. **In one spark-sql session**, same sql over a changing iceberg table will return the same result even if the table has changed. The reason is that `loadTable` method is cached and we couldn't get latest snapshots of the table. If we turn off the cache, we can always get the latest result within one session.
So I think the `cache-enabled` property should be in the docs as it is an important configuration.
=> Docs: Add cache-enabled to catalog property list

aws/src/main/java/org/apache/iceberg/aws/s3/S3OutputFile.java
Small hot fix for a typo I noticed from a user's support request in Slack.
=> [AWS][Minor] Fix typo in S3OutputFile.createOrOverwrite exception message

site/docs/spec.md
This updates the spec for v2 changes that are in master or pull requests:
* Adds `identifier-field-ids` to schema (#2354)
* Adds partition evolution section (#1025)
* Adds `schemas` and `current-schema-id` to table metadata (#1029, #2096)
* Adds `key_metadata` to manifest lists (#2520)
* Adds `schema-id` to snapshot metadata (#2275)
Closes #1141.
=> Update spec for v2 changes

python/tox.ini
Adds mypy ignores for `pytz` and `dateutil`
=> [python] Adding type ignores for dependencies without type support

api/src/test/java/org/apache/iceberg/AssertHelpers.java
`.withFailMessage(..)` was mistakenly used and was therefore overriding
the actual error reporting, making debugging difficult.
=> Use .as() when describing an Assertion

site/docs/blogs.md
Adds link to Adobe's blog on migrating to Apache Iceberg
=> Docs: Adobe Apache Iceberg Migration

api/src/main/java/org/apache/iceberg/Schema.java, core/src/main/java/org/apache/iceberg/SchemaUpdate.java, core/src/test/java/org/apache/iceberg/TestCreateTransaction.java, core/src/test/java/org/apache/iceberg/TestSchemaUpdate.java
=> Core: do not allow optional, double and float identifier fields

python/iceberg/api/partition_spec.py, python/iceberg/api/transforms/dates.py, python/iceberg/api/transforms/timestamps.py, python/iceberg/api/transforms/transform.py, python/tests/api/test_partition_spec.py
Support custom target name in partition spec builder and also fix some other issues. Additionally, add unit tests for partition spec.
=> [Python] support custom target name in partition spec builder

README.md
Small PR to address #2708 just changes a single link in the top-level README.md
=> Docs: updating README to link to travis-ci.com instead of travis-ci.org

parquet/src/main/java/org/apache/iceberg/parquet/ParquetAvro.java, parquet/src/main/java/org/apache/iceberg/parquet/PruneColumns.java
See also https://errorprone.info/bugpattern/ReferenceEquality
=> Use equals() instead of Ref. equality

data/src/main/java/org/apache/iceberg/data/InternalRecordWrapper.java, data/src/test/java/org/apache/iceberg/RecordWrapperTest.java, flink/src/test/java/org/apache/iceberg/flink/TestRowDataWrapper.java, spark/src/test/java/org/apache/iceberg/spark/source/TestInternalRowWrapper.java
Add unit tests to address the introduced `InternalRecordWrapper`, `RowDataWrapper`, `InternalRowWrapper`.  The intention of writing this test is :  I find that the `InternalRecordWrapper` did not handle the nullable value correct ( I mean we will cast a `null` to the target value, that is incorrect), so I think preparing an unit tests for this is necessary.
=> Tests: Add unit tests for InternalRecordWrapper, RowDataWrapper, InternalRowWrapper

core/src/main/java/org/apache/iceberg/MicroBatches.java
Param scanAllFiles Used to check whether all the data files should be processed, or only added files.Here we should replace  scanAllFiles to  !scanAllFiles.
=> Update context conditions  

site/docs/configuration.md
Add  configures to doc: `commit.status-check.num-retries`, `commit.status-check.min-wait-ms`,`commit.status-check.max-wait-ms `,`commit.status-check.total-timeout-ms`.
=> Docs: Add commit.status-check on doc.

python/iceberg/api/transforms/transforms.py, python/iceberg/api/transforms/unknown_transform.py, python/iceberg/api/transforms/void_transform.py
This adds the Void and Unknown transforms that already exists in the java implementation.  It's relevant to @jun-he 's open PR.
=> [python] Adding Unknown and Void transforms

core/src/main/java/org/apache/iceberg/SchemaUpdate.java, parquet/src/main/java/org/apache/iceberg/parquet/TypeWithSchemaVisitor.java
See also https://errorprone.info/bugpattern/JdkObsolete
This also suppresses the same warning for `SchemaUpdate.moveField` as we can't move to an `ArrayDeque` there.
=> Replace LinkedList usage with ArrayDeque for better performance

core/src/main/java/org/apache/iceberg/AllDataFilesTable.java, core/src/main/java/org/apache/iceberg/AllEntriesTable.java, core/src/main/java/org/apache/iceberg/AllManifestsTable.java, core/src/main/java/org/apache/iceberg/BaseAllMetadataTableScan.java, core/src/main/java/org/apache/iceberg/DataFilesTable.java, core/src/main/java/org/apache/iceberg/HistoryTable.java, core/src/main/java/org/apache/iceberg/ManifestEntriesTable.java, core/src/main/java/org/apache/iceberg/ManifestsTable.java, core/src/main/java/org/apache/iceberg/PartitionsTable.java, core/src/main/java/org/apache/iceberg/SnapshotsTable.java, core/src/main/java/org/apache/iceberg/StaticTableScan.java, core/src/test/java/org/apache/iceberg/hadoop/TestStaticTable.java
Refines the error message given when a user attempts an incremental scan against any of the metadata table scans to include the name of the name of the metadata table that's being scanned.
This also makes it trivial to correct the bug in https://github.com/apache/iceberg/issues/2635
This is to assist users who are testing incremental scans on a table `foo`, and might switch back and forth between querying `foo` and for example `foo.history` (to debug their development). Currently, the error message is just `Incremental scan is not supported`, which is not very clear when switching back and forth during development.
This closes https://github.com/apache/iceberg/issues/2599
cc @RussellSpitzer @aokolnychyi
=> Refine error message when performing incremental scans on metadata tables

spark3-extensions/src/main/antlr/org.apache.spark.sql.catalyst.parser.extensions/IcebergSqlExtensions.g4, spark3-extensions/src/main/scala/org/apache/spark/sql/catalyst/parser/extensions/IcebergSparkSqlExtensionsParser.scala, spark3-extensions/src/main/scala/org/apache/spark/sql/catalyst/parser/extensions/IcebergSqlExtensionsAstBuilder.scala, spark3-extensions/src/main/scala/org/apache/spark/sql/catalyst/plans/logical/DropIdentifierFields.scala, spark3-extensions/src/main/scala/org/apache/spark/sql/catalyst/plans/logical/SetIdentifierFields.scala, spark3-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/DropIdentifierFieldsExec.scala, spark3-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/ExtendedDataSourceV2Strategy.scala, spark3-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/SetIdentifierFieldsExec.scala, spark3-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestAlterTableSchema.java
continuation of #2556 , will need to rebase after that is merged.
Here I propose the following syntax:
```sql
ALTER TABLE table REPLACE IDENTIFIER FIELDS (field1, field2, ...)
-- drop all
ALTER TABLE table DROP IDENTIFIER FIELDS
```
`IDENTIFIER` and `FIELDS` are new keywords. Because we already have `FIELD` as a keyword, I think adding `FIELDS` can be beneficial for other batch operations in the future. It also makes the statement more clear instead of saying `ALTER TABLE table REPLACE IDENTIFIER`.
The reason for having another drop statement to drop all is because typically in SQL statements a `( ... )` clause always has at least one element. We can do `ALTER TABLE table REPLACE IDENTIFIER FIELDS ()` instead, but it just feels awkward to me, not sure how other people think about this.
=> Spark: add spark extension for identifier fields

core/src/main/java/org/apache/iceberg/SerializableTable.java, core/src/main/java/org/apache/iceberg/hadoop/HadoopConfigurable.java, core/src/main/java/org/apache/iceberg/hadoop/HadoopFileIO.java, core/src/main/java/org/apache/iceberg/util/SerializationUtil.java, mr/src/main/java/org/apache/iceberg/mr/mapreduce/IcebergSplit.java, spark/src/main/java/org/apache/iceberg/spark/SparkUtil.java, spark2/src/main/java/org/apache/iceberg/spark/source/Reader.java
Currently we have special handling for `HadoopFileIO` in different code paths to make sure Hadoop configuration can be serialized and deserialized properly. This PR introduces `HadoopConfigurable` interface to make it more generic for other custom Hadoop configurable `FileIO` implementations to leverage the same code path.
=> Core: add HadoopConfigurable interface to serialize custom FileIO

aws/src/integration/java/org/apache/iceberg/aws/dynamodb/DynamoDbCatalogTest.java, aws/src/main/java/org/apache/iceberg/aws/AwsProperties.java, aws/src/main/java/org/apache/iceberg/aws/dynamodb/DynamoDbCatalog.java, aws/src/main/java/org/apache/iceberg/aws/dynamodb/DynamoDbTableOperations.java
Add DynamoDB catalog implementation, with the following specifications:
1. identifier column (partition key): table identifier string, or `NAMESPACE` for namespaces
2. namespace column (sort key): namespace string
3. a global secondary index (GSI) with namespace as partition key, identifier as sort key, no other projected columns
4. version column : UUID string, used for optimistic locking
5. updated_at column : timestamp long, used to record latest update time
6. created_at column : timestamp long, used to record initial create time
7. p.[property_key] column : string, used to store properties (namespace property or Iceberg-defined table properties including `table_type`, `metadata_location` and `previous_metadata_location`)
This design has the following benefits:
1. table name is used …
=> AWS: add DynamoDb catalog

core/src/main/java/org/apache/iceberg/DoubleFieldMetrics.java, core/src/main/java/org/apache/iceberg/FieldMetrics.java, core/src/main/java/org/apache/iceberg/FloatFieldMetrics.java, core/src/main/java/org/apache/iceberg/MetricsUtil.java, core/src/test/java/org/apache/iceberg/TestMetrics.java, data/src/main/java/org/apache/iceberg/data/orc/GenericOrcWriter.java, data/src/main/java/org/apache/iceberg/data/orc/GenericOrcWriters.java, data/src/test/java/org/apache/iceberg/TestMergingMetrics.java, flink/src/main/java/org/apache/iceberg/flink/data/FlinkOrcWriter.java, flink/src/main/java/org/apache/iceberg/flink/data/FlinkOrcWriters.java, orc/src/main/java/org/apache/iceberg/orc/OrcMetrics.java, orc/src/main/java/org/apache/iceberg/orc/OrcRowWriter.java, orc/src/main/java/org/apache/iceberg/orc/OrcValueWriter.java, parquet/src/main/java/org/apache/iceberg/parquet/ParquetUtil.java, parquet/src/main/java/org/apache/iceberg/parquet/ParquetValueWriter.java, parquet/src/main/java/org/apache/iceberg/parquet/ParquetValueWriters.java, spark/src/main/java/org/apache/iceberg/spark/data/SparkOrcValueWriter.java, spark/src/main/java/org/apache/iceberg/spark/data/SparkOrcValueWriters.java, spark/src/main/java/org/apache/iceberg/spark/data/SparkOrcWriter.java
- This PR implements the behavior described in #348, to exclude NaN from upper/lower bound of double/float type columns in parquet/orc. 
- Support for Avro metrics can be found in #1963, and has some overlap with this PR (especially on `FieldMetrics` related classes)
=> Core: exclude NaN from upper/lower bound of floating columns in Parquet/ORC

spark3-extensions/src/main/scala/org/apache/spark/sql/catalyst/parser/extensions/IcebergSparkSqlExtensionsParser.scala, spark3-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestAlterTablePartitionFields.java
Currently, iceberg sql command recognition is strict: extra white spaces between some of the keywords are not allowed. 
This fix looses this restriction and make it more user friendly as well as more aligned with general sql syntax.
=> make iceberg sql command recognition more whitespace tolerant

flink/src/main/java/org/apache/iceberg/flink/FlinkConfigOptions.java, flink/src/main/java/org/apache/iceberg/flink/source/FlinkSource.java, flink/src/test/java/org/apache/iceberg/flink/FlinkTestBase.java, flink/src/test/java/org/apache/iceberg/flink/source/TestFlinkScanSql.java
…e can centralize all configs (table, source, sink etc.) in this single class
This is to address this comment: https://github.com/apache/iceberg/pull/2305#discussion_r591421143
The config class is not user facing even though it is a public class. To users, what matters are the config keys. They are the public contract and weren't changed. So it shouldn't cause any compatibility issue. 
cc @holdenk @openinx
=> Flink: Rename FlinkTableOptions to more generic FlinkConfigOptions.

arrow/src/main/java/org/apache/iceberg/arrow/ArrowSchemaUtil.java, arrow/src/main/java/org/apache/iceberg/arrow/vectorized/ArrowReader.java, arrow/src/main/java/org/apache/iceberg/arrow/vectorized/GenericArrowVectorAccessorFactory.java, arrow/src/main/java/org/apache/iceberg/arrow/vectorized/VectorizedArrowReader.java, arrow/src/main/java/org/apache/iceberg/arrow/vectorized/parquet/VectorizedColumnIterator.java, arrow/src/main/java/org/apache/iceberg/arrow/vectorized/parquet/VectorizedDictionaryEncodedParquetValuesReader.java, arrow/src/main/java/org/apache/iceberg/arrow/vectorized/parquet/VectorizedPageIterator.java, arrow/src/main/java/org/apache/iceberg/arrow/vectorized/parquet/VectorizedParquetDefinitionLevelReader.java, arrow/src/test/java/org/apache/iceberg/arrow/ArrowSchemaUtilTest.java, arrow/src/test/java/org/apache/iceberg/arrow/vectorized/ArrowReaderTest.java
This is partly fixing https://github.com/apache/iceberg/issues/2486 and https://github.com/apache/iceberg/issues/2485. I didn't want to include all types as otherwise the PR would become too large. It's been a bit of a pain adding new type support. So I'm planning to refactor the code after this PR is merged in the `arrow` project in order to reduce code duplication and complexity before adding support for more types.
=> Arrow: Add support for TimeType / UUIDType

spark3/src/main/java/org/apache/iceberg/spark/source/SparkMicroBatchStream.java
=> MicroBatchStream read impl doesn't read the spark read option - FILE_OPEN_COST correctly

api/src/main/java/org/apache/iceberg/Snapshot.java, api/src/main/java/org/apache/iceberg/Table.java, api/src/test/java/org/apache/iceberg/TestHelpers.java, core/src/main/java/org/apache/iceberg/BaseMetadataTable.java, core/src/main/java/org/apache/iceberg/BaseSnapshot.java, core/src/main/java/org/apache/iceberg/BaseTable.java, core/src/main/java/org/apache/iceberg/BaseTransaction.java, core/src/main/java/org/apache/iceberg/SerializableTable.java, core/src/main/java/org/apache/iceberg/SnapshotParser.java, core/src/main/java/org/apache/iceberg/SnapshotProducer.java, core/src/test/java/org/apache/iceberg/TableTestBase.java, core/src/test/java/org/apache/iceberg/TestSchemaID.java, core/src/test/java/org/apache/iceberg/TestSnapshotJson.java, core/src/test/java/org/apache/iceberg/TestTableMetadata.java, core/src/test/resources/TableMetadataV2Valid.json
- Followup of #2096 to add schema id to snapshot. 
- Also addressed the remaining comments in #2096 in this commit
- Will added some util methods for easier retrieving of snapshot/schema information in follow up PRs.
=> Core: add schema id to snapshot

site/docs/css/extra.css, site/docs/spec.md
@rdblue looks like the new spec diagram from #2622 was a larger image than the old one so when I only replaced the image, it took up a lot of the space on the page. this is to fix the alignment and size and alignment of it on the spec page
I tested it via mkdocs locally and it now looks good on both desktop and mobile
=> Docs: fix alignment of new spec diagram on page

site/docs/spec.md
The previous spec update didn't include changes in manifest file properties or in the JSON serialization section.
=> Spec: Update for v2 schemas in remaining sections

core/src/main/java/org/apache/iceberg/util/TableScanUtil.java, core/src/test/java/org/apache/iceberg/TestSplitPlanning.java
Previously these values were not validated which could lead to a huge
runtime issues or OOMs. To prevent errors we validate the parameters
for these methods and prevent these issues from occuring.
=> Core: Validate planTasks and splitFiles in TableScanUtil

arrow/src/main/java/org/apache/iceberg/arrow/vectorized/parquet/BaseVectorizedParquetValuesReader.java, arrow/src/main/java/org/apache/iceberg/arrow/vectorized/parquet/VectorizedPageIterator.java, arrow/src/main/java/org/apache/iceberg/arrow/vectorized/parquet/VectorizedParquetDefinitionLevelReader.java, parquet/src/main/java/org/apache/iceberg/parquet/BasePageIterator.java, parquet/src/main/java/org/apache/iceberg/parquet/Parquet.java, spark/src/test/java/org/apache/iceberg/spark/data/parquet/vectorized/TestParquetVectorizedReads.java
With this change, we have added support for Parquet data written in V2 format.
The only data encodings we support are dictionary and plain.
Vectorized reads against data written using Delta/RLE and other encodings are
not supported. As of this commit, note that the Spark Parquet vectorized reads also don't
support vectorized reads for such encodings.
=> [Spark] Add limited support for vectorized reads for Parquet V2

site/docs/flink.md, site/docs/java-api-quickstart.md, site/docs/maintenance.md, site/docs/spark-procedures.md, site/mkdocs.yml
I recently reinstalled mkdocs and deployed the ASF site, which broke directory URLs (like iceberg.apache.org/spec). The problem is that the behavior of `use_directory_urls` changed when `site_url` is not specified because [`site_url` is now requred](https://www.mkdocs.org/about/release-notes/#backward-incompatible-changes-in-12).
This also fixes the redirect plugin config warning and all broken link warnings.
Fixes #2587.
=> Docs: Update for mkdocs 1.2

nessie/src/main/java/org/apache/iceberg/nessie/NessieCatalog.java, nessie/src/main/java/org/apache/iceberg/nessie/TableReference.java, nessie/src/test/java/org/apache/iceberg/nessie/BaseTestIceberg.java, nessie/src/test/java/org/apache/iceberg/nessie/NessieUtilTest.java, nessie/src/test/java/org/apache/iceberg/nessie/TestBranchVisibility.java
These are all purely whitespace changes that properly format the code (according to `intellij-java-palantir-style.xml`) in the `nessie` project
=> Properly format code in nessie project

build.gradle
We are using a version of spotless plugin that is vulnerable to attack https://nvd.nist.gov/vuln/detail/CVE-2019-9843, thus bumping up the version to 3.20
=> Build: bump up DiffPlug Spotless version

build.gradle, versions.props
Upgrading to JUnit 5 using `junit-vintage-engine` is fairly straightforward as `junit-vintage-engine` makes sure that JUnit 4 tests work as usual.
`junit-vintage-engine` brings junit **4.13** as can be seen below:
```
+--- org.junit.vintage:junit-vintage-engine -> 5.7.2
|    +--- org.junit.platform:junit-platform-engine:1.7.2
|    |    \--- org.junit.platform:junit-platform-commons:1.7.2
|    \--- junit:junit:4.13
```
I also analyzed the dependencies of all projects and made sure that those projects don't pull in older junit versions.
The reason for upgrading to JUnit5 is that we'd like to make use of the new [Extension model](https://junit.org/junit5/docs/current/user-guide/#extensions) that comes with it.
/cc @snazy @rymurr
=> Upgrade to JUnit 5

spark2/src/main/java/org/apache/iceberg/spark/source/Reader.java, spark3/src/main/java/org/apache/iceberg/spark/source/SparkBatchScan.java, spark3/src/main/java/org/apache/iceberg/spark/source/SparkMicroBatchStream.java
Follows #2577, use thread pool to initialize readTasks if Spark locality is preferred.
Before this, the Spark plan phase could be slow as it uses single thread to obtain block locations of all files for this scan.
More information could be found in [this comment](https://github.com/apache/iceberg/pull/2577#issue-637698205)
=> Spark: Parallelize initializing readTasks when localityPreferred is true

api/src/main/java/org/apache/iceberg/actions/ActionsProvider.java, api/src/main/java/org/apache/iceberg/actions/DeleteOrphanFiles.java, api/src/main/java/org/apache/iceberg/actions/DeleteReachableFiles.java, core/src/main/java/org/apache/iceberg/actions/BaseDeleteOrphanFilesActionResult.java, core/src/main/java/org/apache/iceberg/actions/BaseDeleteReachableFilesActionResult.java, spark/src/main/java/org/apache/iceberg/actions/Actions.java, spark/src/main/java/org/apache/iceberg/actions/RemoveOrphanFilesAction.java, spark/src/main/java/org/apache/iceberg/spark/actions/BaseDeleteOrphanFilesSparkAction.java, spark/src/main/java/org/apache/iceberg/spark/actions/BaseDeleteReachableFilesSparkAction.java, spark/src/main/java/org/apache/iceberg/spark/actions/BaseSparkActions.java, spark/src/test/java/org/apache/iceberg/actions/TestDeleteReachableFilesAction.java, spark/src/test/java/org/apache/iceberg/spark/actions/TestNewRewriteDataFilesAction.java, spark2/src/test/java/org/apache/iceberg/actions/TestDeleteReachableFilesAction24.java, spark3/src/main/java/org/apache/iceberg/spark/procedures/RemoveOrphanFilesProcedure.java, spark3/src/test/java/org/apache/iceberg/actions/TestRemoveFilesAction3.java
This PR switches our new actions to use `delete` instead of `remove` as I think `delete` makes more sense given the naming of methods in these actions.
This is NOT a breaking change as we modify only the unreleased Actions API.
=> API: Use delete instead of remove in actions for clarity

.baseline/checkstyle/checkstyle.xml, spark/src/main/java/org/apache/iceberg/actions/RewriteDataFilesAction.java, spark/src/main/java/org/apache/iceberg/spark/actions/BaseSparkAction.java, spark/src/test/java/org/apache/iceberg/spark/source/TestDataFrameWrites.java, spark/src/test/java/org/apache/iceberg/spark/source/TestPartitionPruning.java, spark/src/test/java/org/apache/iceberg/spark/source/TestSparkDataFile.java, spark/src/test/java/org/apache/iceberg/spark/source/TestWriteMetricsConfig.java
As @RussellSpitzer pointed out during reviews, it is better avoid calling `new` to construct `JavaSparkContext` not to mislead people as we are not actually creating a new context. Instead, we create a wrapper.
This PR updates places that were committed before that.
=> Spark: Use JavaSparkContext.fromSparkContext instead of constructor

spark/src/main/java/org/apache/iceberg/actions/Actions.java, spark/src/main/java/org/apache/iceberg/actions/CreateAction.java, spark/src/main/java/org/apache/iceberg/actions/RewriteDataFilesAction.java, spark/src/main/java/org/apache/iceberg/actions/SnapshotAction.java, spark2/src/main/java/org/apache/iceberg/actions/SparkActions.java, spark3/src/main/java/org/apache/iceberg/actions/SparkActions.java
This PR adds missing deprecation annotations for old Spark actions.
=> Spark: Add missing deprecation annotations for old actions

spark3/src/main/java/org/apache/iceberg/spark/FileRewriteCoordinator.java, spark3/src/main/java/org/apache/iceberg/spark/actions/Spark3BinPackStrategy.java, spark3/src/test/java/org/apache/iceberg/spark/TestFileRewriteCoordinator.java
Since we changed our implementation of Spark3BinPackStrategy we no longer need some
of the functionality that was previously in FileRewriteCoordinator. Here we remove
those functions and related test code.
=> Spark: Remove Unused FileRewriteCoordinator Functions

build.gradle, nessie/src/main/java/org/apache/iceberg/nessie/NessieCatalog.java, nessie/src/main/java/org/apache/iceberg/nessie/NessieTableOperations.java, nessie/src/main/java/org/apache/iceberg/nessie/UpdateableReference.java, nessie/src/test/java/org/apache/iceberg/nessie/BaseTestIceberg.java, nessie/src/test/java/org/apache/iceberg/nessie/NessieUtilTest.java, nessie/src/test/java/org/apache/iceberg/nessie/TestBranchVisibility.java, nessie/src/test/java/org/apache/iceberg/nessie/TestNamespace.java, nessie/src/test/java/org/apache/iceberg/nessie/TestNessieTable.java, nessie/src/test/java/org/apache/iceberg/nessie/TestTableReference.java, versions.props
* Bump Nessie to 0.8.2 + replace Gradle plugin with new JUnit extension
* Replace Gradle plugin with new JUnit extension.
See [Add JAX-RS tests and add JUnit/Jupyter extension](https://github.com/projectnessie/nessie/pull/1566)
* Apply changes to Iceberg required by API changes in Nessie:
* [Re-introduce wrapper classes for query params of CommitLog/Entries](https://github.com/projectnessie/nessie/pull/1595)
* [Server-side commit range filtering](https://github.com/projectnessie/nessie/pull/1596)
* [Add hashOnRef query param to support time travel on a named ref](https://github.com/projectnessie/nessie/pull/1589)
* [Only accept NamedRefs in REST API](https://github.com/projectnessie/nessie/pull/1583)
* Bugfix: must send the Contents.id of the existing table
Nessie's `Contents.id` is a …
=> Bump Nessie to 0.8.2 + related changes

api/src/test/java/org/apache/iceberg/expressions/TestExpressionBinding.java, api/src/test/java/org/apache/iceberg/transforms/TestProjection.java, api/src/test/java/org/apache/iceberg/transforms/TestStartsWith.java, aws/src/test/java/org/apache/iceberg/aws/glue/LockManagersTest.java, core/src/test/java/org/apache/iceberg/TestCatalogUtil.java, core/src/test/java/org/apache/iceberg/TestSortOrderParser.java, core/src/test/java/org/apache/iceberg/avro/AvroTestHelpers.java, core/src/test/java/org/apache/iceberg/util/TestExceptionUtil.java, data/src/test/java/org/apache/iceberg/data/DataTestHelpers.java, flink/src/test/java/org/apache/iceberg/flink/TestCatalogTableLoader.java, flink/src/test/java/org/apache/iceberg/flink/TestDataFileSerialization.java, flink/src/test/java/org/apache/iceberg/flink/TestFlinkFilters.java, flink/src/test/java/org/apache/iceberg/flink/TestHelpers.java, flink/src/test/java/org/apache/iceberg/flink/TestManifestFileSerialization.java, flink/src/test/java/org/apache/iceberg/flink/sink/TestIcebergStreamWriter.java, mr/src/test/java/org/apache/iceberg/mr/TestCatalogs.java, parquet/src/test/java/org/apache/iceberg/TestHelpers.java, spark/src/test/java/org/apache/iceberg/TestDataFileSerialization.java, spark/src/test/java/org/apache/iceberg/TestManifestFileSerialization.java, spark/src/test/java/org/apache/iceberg/TestScanTaskSerialization.java, spark/src/test/java/org/apache/iceberg/spark/data/GenericsHelpers.java, spark/src/test/java/org/apache/iceberg/spark/data/TestHelpers.java, spark2/src/test/java/org/apache/iceberg/spark/source/TestFilteredScan.java, spark3/src/test/java/org/apache/iceberg/spark/source/TestFilteredScan.java, spark3/src/test/java/org/apache/iceberg/spark/source/TestPathIdentifier.java
While working on some other code where I was debugging an issue that resulted in failing checks in `TestHelpers`. Those failing checks were essentially of the form `Should be XYZ` without actually knowing what the actual value was, thus requiring to add some additional context to the failure message.
For example, the check `Assert.assertTrue("Should be a long", actual instanceof Long)` could fail either if `actual` is `null` or of a different type. Yet one doesn't know and has to add some additional context to understand what `actual`'s value is.
Therefore it seems better to move to AssertJ checks, where the actual value will be reported.
Note that I didn't touch all the other `Assert.assertEquals` checks in order to keep the change set to an absolute minimum but still improve the …
=> Move Assert.assertTrue(..) instance checks to AssertJ assertions

api/src/main/java/org/apache/iceberg/transforms/Bucket.java, api/src/test/java/org/apache/iceberg/transforms/TestBucketing.java
Fixes https://github.com/apache/iceberg/issues/2837
=> Fix bucketing of strings with non-BMP characters

core/src/main/java/org/apache/iceberg/TableProperties.java, core/src/main/java/org/apache/iceberg/avro/Avro.java, parquet/src/main/java/org/apache/iceberg/parquet/Parquet.java
This PR adds table properties to configure delete Avro and Parquet writers independently of data writers.
It is a subset of the changes in #2827.
=> Core: Add delete table properties for Avro and Parquet

core/src/main/java/org/apache/iceberg/avro/Avro.java, core/src/test/java/org/apache/iceberg/avro/TestAvroDataWriter.java, data/src/test/java/org/apache/iceberg/data/orc/TestOrcDataWriter.java, orc/src/main/java/org/apache/iceberg/orc/ORC.java, parquet/src/main/java/org/apache/iceberg/parquet/Parquet.java, parquet/src/test/java/org/apache/iceberg/parquet/TestParquetDataWriter.java
This PR adds `DataWriter` builders to our `Avro`, `Parquet`, `ORC` classes. This functionality is needed to introduce a writer factory in subsequent PRs.
=> Avro, Parquet, ORC: Add DataWriter builders

core/src/main/java/org/apache/iceberg/io/OutputFileFactory.java, core/src/test/java/org/apache/iceberg/io/TestOutputFileFactory.java, data/src/test/java/org/apache/iceberg/io/TestAppenderFactory.java, data/src/test/java/org/apache/iceberg/io/TestBaseTaskWriter.java, data/src/test/java/org/apache/iceberg/io/TestGenericSortedPosDeleteWriter.java, data/src/test/java/org/apache/iceberg/io/TestTaskEqualityDeltaWriter.java, mr/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergOutputFormat.java, mr/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergOutputCommitter.java, spark/src/main/java/org/apache/iceberg/spark/source/RowDataRewriter.java, spark2/src/main/java/org/apache/iceberg/spark/source/Writer.java, spark3/src/main/java/org/apache/iceberg/spark/source/SparkWrite.java
This PR extends `OutputFileFactory` to support multiple specs. When we write delete files, we should write them using the the same partition spec as data files they reference. This means we will need to write to multiple specs in a single transaction. Instead of having an output factory per spec, I think it is better to support multiple specs in a single factory.
=> Core: Support multiple specs in OutputFileFactory

site/docs/security.md, site/mkdocs.yml
This patch adds a page to the site docs which describes the process for
reporting security vulnerabilites found in Apache Iceberg.
=> Add security page to site docs

site/docs/spec.md
This removes undeprecates `distinct_counts` in the `data_file` struct stored in manifests. While these counts are difficult to use, discussion from the dev list indicates that having them is better than having no data at all. This also tightens the description to clarify that the distinct counts must be produced from values in the file and not by merging distinct counts from other sources of metadata.
=> Spec: Add back distinct_counts in data_file metadata

site/docs/spec.md
This was caught by the v2 discussion on the dev list. Because v1 manifests are valid in v2 and a manifest list is written for each snapshot, a writer may not know whether a v1 manifest contains a NaN value in one of its partitions. As a result, the `contains_nan` field of the manifest list's partition summary should not be required.
=> Spec: Make contains_nan partition summary field optional in v2

build.gradle
Due to an issue with the build.gradle both the spark test and test31 modules were both running with Spark 3.1. Removing the inter dependency fixes the issue and both grade tasks now run with the correct respective spark versions.
@cwsteinbach
=> Build: Run tests against Spark 3.0 and Spark 3.1

api/src/main/java/org/apache/iceberg/RewriteFiles.java, core/src/main/java/org/apache/iceberg/BaseRewriteFiles.java, core/src/main/java/org/apache/iceberg/BaseRowDelta.java, core/src/main/java/org/apache/iceberg/DeleteFileIndex.java, core/src/main/java/org/apache/iceberg/MergingSnapshotProducer.java, core/src/main/java/org/apache/iceberg/actions/BaseRewriteDataFilesAction.java, core/src/main/java/org/apache/iceberg/actions/RewriteDataFilesCommitManager.java, core/src/test/java/org/apache/iceberg/TestRewriteFiles.java, spark/src/main/java/org/apache/iceberg/spark/actions/BaseRewriteDataFilesSparkAction.java, spark/src/test/java/org/apache/iceberg/spark/actions/TestNewRewriteDataFilesAction.java
This adds a new validation for `RewriteFiles` that checks whether delete files have been added for any of the files that are being rewritten. The check constructs a delete file index for all the delete files in snapshots written since a starting snapshot and filters the delete file entries using the sequence number of the starting snapshot to ensure that only delete files that were added after the starting snapshot are indexed. Next, if any data file being replaced matches a delete file in the index, a validation exception is thrown.
This also updates actions to correctly set the starting snapshot ID for validation.
This fixes #2308.
=> Core: Add validation for row-level deletes with rewrites

python/iceberg/api/transforms/bucket.py, python/tests/api/test_partition_spec.py, python/tests/api/transforms/test_bucket.py
Follow up https://github.com/apache/iceberg/pull/2689#discussion_r650597195
=> [Python] support BucketByteBuffer and BucketUUID

python/setup.py
The dependencies were pulling in pyarrow 5.0.0, which just released today, and it was breaking the current python build.
=> [python] Updating pyarrow dependencies

core/src/main/java/org/apache/iceberg/DataFiles.java, spark/src/test/java/org/apache/iceberg/spark/source/TestSparkDataFile.java
There's a minor bug that was introduced from this [PR](https://github.com/apache/iceberg/pull/1975/files#diff-ac5b4d1edab36f13fd929683cad0f56951ac019353354ac886e84d099d5dd219R179). 
The DataFiles which were deserialized from manifests have a null sortOrderId, that means it will encounter an Exception when we convert the `null` Integer to a primitive int.
=> Core: Fix the NPE in DataFiles.Builder#copy

core/src/main/java/org/apache/iceberg/FindFiles.java, core/src/test/java/org/apache/iceberg/TableTestBase.java, core/src/test/java/org/apache/iceberg/TestFindFiles.java
This PR  added includeColumnStats option in FindFiles API so that we can choose to remain column stat when select data files and commit them to other iceberg table.
Reference #2870  
@openinx
=> Core: added includeColumnStats option in FindFiles API

.baseline/checkstyle/checkstyle.xml, core/src/main/java/org/apache/iceberg/MetadataColumns.java, core/src/main/java/org/apache/iceberg/avro/Avro.java, core/src/main/java/org/apache/iceberg/io/WriterFactory.java, data/src/main/java/org/apache/iceberg/data/BaseWriterFactory.java, data/src/test/java/org/apache/iceberg/io/TestWriterFactory.java, orc/src/main/java/org/apache/iceberg/orc/ORC.java, parquet/src/main/java/org/apache/iceberg/parquet/Parquet.java, spark/src/main/java/org/apache/iceberg/spark/source/SparkWriterFactory.java, spark/src/test/java/org/apache/iceberg/spark/source/TestSparkWriterFactory.java
This PR adds a new interface called `WriterFactory` for creating data and delete writers.
This change also includes `BaseWriterFactory` to be shared by query engine integrations and a Spark writer factory.
=> Core: Add WriterFactory

site/docs/community.md
Update the Slack link to one for apache-iceberg.slack.com that will not expire.
=> Docs: Update Slack invite link

parquet/src/main/java/org/apache/iceberg/parquet/TypeToMessageType.java
The spec mandates that UUID fields in Parquet have logical type "UUID"
(https://iceberg.apache.org/spec/#parquet). This is possible to fulfill
after 236615497bdc2c6fbedbd3acc41a4ed85c4a8bfd, as
`LogicalTypeAnnotation.uuidType` was added in Parquet 1.12.0.
=> Annotate UUID fields in Parquet

flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java, flink/src/main/java/org/apache/iceberg/flink/sink/RowDataTaskWriterFactory.java, flink/src/main/java/org/apache/iceberg/flink/source/RowDataRewriter.java, flink/src/test/java/org/apache/iceberg/flink/sink/TestDeltaTaskWriter.java, flink/src/test/java/org/apache/iceberg/flink/sink/TestTaskWriters.java
This PR switches Flink sink to use `SerializableTable` to avoid using deprecated methods in `OutputFileFactory`.
=> Flink: Switch to using SerializableTable

api/src/main/java/org/apache/iceberg/types/JavaHashes.java, core/src/main/java/org/apache/iceberg/util/StructLikeMap.java, core/src/main/java/org/apache/iceberg/util/StructLikeSet.java, core/src/test/java/org/apache/iceberg/util/TestStructLikeMap.java, core/src/test/java/org/apache/iceberg/util/TestStructLikeSet.java
Our `JavaHashes` are inconsistent in handling nulls. Specifically, only `CharSequenceHash` currently handles nulls correctly and all others fail with a NPE. In addition, our `StructLike` collections don't handle nulls too. It is possible to add a null object but never retrieve it.
=> Core: Support nulls in StructLike collections

core/src/main/java/org/apache/iceberg/TableMetadata.java, core/src/main/java/org/apache/iceberg/TableProperties.java, core/src/test/java/org/apache/iceberg/TestTableMetadata.java, flink/src/test/java/org/apache/iceberg/flink/TestFlinkCatalogTable.java, mr/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerNoScan.java, spark3/src/test/java/org/apache/iceberg/spark/sql/TestCreateTable.java
Based on the discussion on dev list, it would be good to have a way to directly create experimental v2 tables. This is my current proposal:
When `format-version` is specified in the table properties section of a CREATE TABLE DDL, we use the specific format version, otherwise use default version
Some considerations I had:
1. `format-version` is not a part of `TableProperties`, but just a property used at table creation time. The value is never stored as actual table property, and updating this property has no effect on table version.
2. Because of 1, we do not use a traditional property syntax like `format.version` but instead use `table-format` to distinguish it from other actual table properties.
3. I am trying to make this a long-term solution for future format versions, so I made the …
=> Core: allow creating v2 tables through table property

flink/src/main/java/org/apache/iceberg/flink/sink/FlinkWriterFactory.java, flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkWriterFactory.java
This PR adds `FlinkWriterFactory` that extends `BaseWriterFactory` introduced in #2873.
=> Flink: Add FlinkWriterFactory

.asf.yaml
This patch adds a subset of non-committer project contributors to the list of collaborators defined in asf.yaml. Please note the following:
1. The documentation for asf.yaml states that the maximum number of collaborators is 20. However, the actual limit is 10.
2. The list of people to add was previously approved on a privtate@iceberg thread.
3. Since I was able to add only a subset of the people who were approved in the aforementioned private@iceberg thread, I based my selection on the total number of commits and the tempo of recent contributions.
=> Add list of Github collaborators to asf.yaml

core/src/main/java/org/apache/iceberg/AllDataFilesTable.java
Fix for nested projection missed doing the same change in AllDataFiles table.
Spotted in #2936 by @aokolnychyi
=> Core: Missed Nested Schema Projection in AllDataFiles Table

site/docs/spark-configuration.md
Adds a section to the Spark documentation on the website about how to override hadoop configuration values per catalog.
This is a very simple explanation and I'm open to discussion on what should be added.
This closes issue https://github.com/apache/iceberg/issues/2907
cc @rdblue
=> [DOCS] Document how to add per-catalog hadoop conf values with Spark

api/src/test/java/org/apache/iceberg/AssertHelpers.java, aws/src/integration/java/org/apache/iceberg/aws/glue/GlueCatalogCommitFailureTest.java
@kbendick @yyanyy 
Integration test fails when running 0.12.0 build verification, due to the change in #2721. We never merged this internally so did not get a chance to test it.
=> AWS: fix integration test after assert library refactor

spark3-extensions/src/main/scala/org/apache/spark/sql/catalyst/optimizer/RewriteDelete.scala, spark3-extensions/src/main/scala/org/apache/spark/sql/catalyst/utils/DistributionAndOrderingUtils.scala, spark3-extensions/src/main/scala/org/apache/spark/sql/catalyst/utils/PlanUtils.scala
The constructor of RepartitionByExpression changed between Spark 3.0 and 3.1.
There was an instance of constructing RepartitionByExpression that was missed in the original commit (#2512).
=> [Spark] Support building against both Spark 3.0 and Spark 3.1: follow-up

spark/src/test/java/org/apache/iceberg/actions/TestDeleteReachableFilesAction.java
-- Sometimes fails with exception (reported also on Slack)
```
org.apache.iceberg.actions.TestRemoveFilesAction3 > dataFilesCleanupWithParallelTasks FAILED
java.lang.AssertionError: FILE_A should be deleted
```
-- Fixed by making Set used for the assertion and update by async thread, a concurrent set
-- Validated by running 50 times (some exceptions seen before, did not see after)
=> Spark: Fix random test failures in TestDeleteReachableFilesAction

core/src/main/java/org/apache/iceberg/BaseMetadataTable.java, core/src/main/java/org/apache/iceberg/DataFilesTable.java, core/src/main/java/org/apache/iceberg/PartitionsTable.java, core/src/test/java/org/apache/iceberg/TestMetadataTableScans.java
* This re-uses the logic of https://github.com/apache/iceberg/pull/2358 (partitions metadata table)
=> Core: Predicate pushdown for files metadata table

spark/src/test/java/org/apache/iceberg/spark/source/TestSparkDataWrite.java, spark2/src/main/java/org/apache/iceberg/spark/source/Writer.java, spark3/src/main/java/org/apache/iceberg/spark/source/SparkWrite.java
When attempting to insert overwrite with an empty dataset
we would previously throw an error. This patch causes spark
to skip any no-op partition replacement operations.
=> Spark: Don't create empty partition replace operations

core/src/main/java/org/apache/iceberg/LocationProviders.java, core/src/test/java/org/apache/iceberg/TestLocationProvider.java
when table property `write.object-storage.path` is not set, use the default table data path which is `tableLocation/data`
@yyanyy
=> Core: allow default data location for ObjectStorageLocationProvider

core/src/main/java/org/apache/iceberg/SerializableTable.java
This PR makes our `SerializableTable` to capture all specs. This is needed to avoid reading the JSON file while writing deltas as deletes may be written to historical specs.
The downside of the new approach is that we always capture all specs even if we actually need only the current spec. I considered offering a builder that would let us customize what to include but I did some quick benchmarks and capturing 4 specs adds less than 2% overhead in terms of size. We are still heavily dominated by the size of the serialized `FileIO`. That's why I went with the simple option and captured all specs.
=> Core: Serialize all specs in SerializableTable

api/src/main/java/org/apache/iceberg/PartitionField.java, core/src/main/java/org/apache/iceberg/AllDataFilesTable.java, core/src/main/java/org/apache/iceberg/AllEntriesTable.java, core/src/main/java/org/apache/iceberg/DataFilesTable.java, core/src/main/java/org/apache/iceberg/ManifestEntriesTable.java, core/src/main/java/org/apache/iceberg/Partitioning.java, core/src/test/java/org/apache/iceberg/TestPartitioning.java, spark3/src/test/java/org/apache/iceberg/spark/source/TestMetadataTablesWithPartitionEvolution.java
This PR adds a utility method to derive a common type for all partition specs.
Prior to this change, querying metadata tables in v2 format with evolved partitioning failed with runtime exceptions.
=> Core: Fix querying metadata tables with multiple specs

site/docs/aws.md
Clarified the description on ObjectStoreLocationProvider on that it generates a deterministic hash based on the filename, and that the hash is placed after `write.object-storage.path`.
=> Docs: Clarify ObjectStoreLocationProvider

site/docs/python-feature-support.md
ARROW-1644 was resolved as of version 2.0 it looks like at least version 3 is required in setup.py
=> Remove feature gap comment about nested types.

site/docs/flink.md, site/docs/hive.md, site/docs/maintenance.md, site/docs/nessie.md, site/docs/releases.md, site/docs/spark-procedures.md, site/mkdocs.yml
=> Add release notes for 0.12.0

mr/src/main/java/org/apache/iceberg/mr/mapreduce/IcebergInputFormat.java, mr/src/main/java/org/apache/iceberg/mr/mapreduce/IcebergSplit.java
This PR migrates `IcebergSplit` to use `SerializableTable` to support changes in #2984.
=> MR: Use SerializableTable in IcebergSplit

site/docs/getting-started.md, site/docs/index.md, site/docs/trino-prestodb.md, site/mkdocs.yml
continuation of #2832 
Based on the discussion, proposing a way to refactor engines pages to accommodate more Iceberg support in the future.
@rdblue @electrum please see if this version is better.
=> Doc: refactor engines pages and add link to PrestoDB

core/src/main/java/org/apache/iceberg/Partitioning.java, spark3/src/test/java/org/apache/iceberg/spark/source/TestMetadataTablesWithPartitionEvolution.java
Until we store the output type of transforms, we should fail building the partition type if we hit `UnknownTransform`.
=> Core: Validate transforms while building partition type

core/src/test/java/org/apache/iceberg/TestMetrics.java, orc/src/main/java/org/apache/iceberg/orc/OrcMetrics.java
This is not a new PR, but one I was trying to fix along with https://github.com/apache/iceberg/pull/2240, found at the time when writing unit tests for configured metrics modes for nested structs.
To be clearer, breaking this fix out to separate PR and adding a specific unit test to reproduce problem.
=> Orc: Correct Metrics Modes for nested fields

spark3/src/main/java/org/apache/iceberg/spark/Spark3Util.java, spark3/src/test/java/org/apache/iceberg/spark/TestSpark3Util.java
This is useful for any user or developer who want to get an Iceberg table by its name.
=> Spark: Add a method to load an Iceberg table by its name in Spark3.

.github/workflows/labeler.yml
According to [the docs on Permissions for the GITHUB_TOKEN](https://docs.github.com/en/actions/reference/authentication-in-a-workflow#permissions-for-the-github_token), the GITHUB_TOKEN that's generated for each run of a workflow has a specific set of permissions associated to it.
These permissions can be defined more granularly, to reduce the scope of the things the workflow can touch.
The full docs on `permissions` is located [here](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#permissions).
To test this out, I'm using the permissions given in the example provided on the same page.
This partially closes the following issue issue https://github.com/apache/iceberg/issues/3006, though we should consider adding this to all workflows that use GITHUB_TOKEN. …
=> [INFRA] Reduce permissions for Github tokens generated for labeler action

core/src/main/java/org/apache/iceberg/LocationProviders.java, core/src/main/java/org/apache/iceberg/TableProperties.java, core/src/test/java/org/apache/iceberg/TestLocationProvider.java, spark/src/jmh/java/org/apache/iceberg/spark/source/IcebergSourceBenchmark.java, spark/src/test/java/org/apache/iceberg/actions/TestRemoveOrphanFilesAction.java, spark/src/test/java/org/apache/iceberg/spark/source/TestDataFrameWrites.java, spark3/src/main/java/org/apache/iceberg/spark/actions/BaseSnapshotTableSparkAction.java
closes #2964 
@cobookman, @kbendick and @openinx brought up the issue during #2845 that the variable name `WRITE_NEW_DATA_LOCATION` is inconsistent with the actual value `write.folder-storage.path`.  This PR deprecates the old variable name to use a name that is consistent with the actual value.
I looked into the original PR that introduced this which is #6, I think @rdblue suggested using the value `write.folder-storage.path`, but the author @mccheah did not update the variable name.
Please let me know if there is any concern about this deprecation.
=> Core: rename WRITE_NEW_DATA_LOCATION to WRITE_FOLDER_STORAGE_LOCATION

hive-metastore/src/main/java/org/apache/iceberg/hive/HiveCatalog.java
Noticed a lot of these errors while trying to debug timeouted Hive tests
=> Hive: Fix some message typos in HiveCatalog: Matastore => Metastore

hive-metastore/src/main/java/org/apache/iceberg/hive/HiveCatalog.java
Small fix.  
When running the Spark shell or other Scala REPL  , the new no-arg constructor, replacing the deprecated one, hits this NPE which prevents it from being constructed
```
scala> val catalog = new HiveCatalog()
at org.apache.iceberg.hive.HiveCatalog.toString(HiveCatalog.java:523)
at scala.runtime.ScalaRunTime$.inner$1(ScalaRunTime.scala:254)
```
=> Hive: Fix toString NPE with recommended constructor

core/src/main/java/org/apache/iceberg/PropertiesUpdate.java
The current iceberg table properties by design do not support any other value than non-null string values. However, due to a typo in the code, it allows a null value for a table property. Due to this we can store the value as null but breaks the read/load of iceberg table back due to non-null property values checks as part of metadata parsers.
This PR just updates the typo to ensure we cannot populate non-null values.
@rdblue @jackye1995 @aokolnychyi @RussellSpitzer
=> Core : Fixing allowed null values for iceberg table properties

flink/src/main/java/org/apache/iceberg/flink/FlinkCatalog.java, flink/src/main/java/org/apache/iceberg/flink/FlinkCatalogFactory.java, flink/src/main/java/org/apache/iceberg/flink/FlinkDynamicTableFactory.java, flink/src/main/resources/META-INF/services/org.apache.flink.table.factories.Factory, flink/src/test/java/org/apache/iceberg/flink/TestIcebergConnector.java
This PR is trying to address the issue : https://github.com/apache/iceberg/issues/2572
For people who want to create an iceberg table under hadoop catalog, could use the following sql:
```sql
CREATE TABLE hadoop_table (
id        BIGINT,
data   STRING
) WITH (
'connector' = 'iceberg',
'catalog-name' = 'hadoop-catalog',
'catalog-type' = 'hadoop',
'catalog-database' = 'local_db',
'warehouse' = 'hdfs://nn:9090/path/to/warehouse'
);
```
If want to create an iceberg table under hive catalog,  we could use the following SQL:
```sql
CREATE TABLE hive_table (
id      BIGINT,
data STRING
) WITH (
'connector' = 'iceberg',
'catalog-name' = 'hive-catalog',
'catalog-type' = 'hive',
'catalog-database' = 'default',
'uri' = 'thrift://localhost:9093',
'warehouse' = 'hdfs://nn:9090/path/to/warehouse'
); …
```
=> Flink: Support create iceberg table with 'connector'='iceberg'

api/src/main/java/org/apache/iceberg/types/PruneColumns.java, api/src/main/java/org/apache/iceberg/types/TypeUtil.java, api/src/test/java/org/apache/iceberg/types/TestTypeUtil.java
Previously we only had TypeUtil.select which would select all nested
elements of selected structs. This made it difficult to project empty
structs since they would have no selected leaf elements. The new
TypeUtil.project instead takes only the elements which are specifically
requested with no automatic selection of nested elements.
=> Core: Add TypeUtil.project() for Explicit Projection

flink/src/test/java/org/apache/iceberg/flink/SimpleDataUtil.java, flink/src/test/java/org/apache/iceberg/flink/TestFlinkTableSink.java
* In my observation, new files may be added if pass checkpoint interval (set to 400)
=> Flink: Fix flaky test TestFlinkTableSink

site/docs/flink.md
about https://github.com/apache/iceberg/issues/3075
the **default** keyword is used in the SQL statement in the Flink document, but the example does not add escape, so the statement cannot be run directly.
such as：
```
CREATE TABLE hive_catalog.default.sample (
id BIGINT COMMENT 'unique id',
data STRING
);
```
An error will be reported when the statement is executed：
```
[ERROR] Could not execute SQL statement. Reason:
org.apache.flink.sql.parser.impl.ParseException: Encountered ". default" at line 1, column 27.
```
modify the SQL：
```
CREATE TABLE hive_catalog.`default`.sample (
id BIGINT COMMENT 'unique id',
data STRING
);
```
the above statements can be executed normally.
=> Doc:Add escape in the SQL statement in the flink engine document

spark3-extensions/src/test/java/org/apache/iceberg/spark/extensions/SparkExtensionsTestBase.java
The (non-Iceberg) tables generated during testing in `TestAddFiles` procedure are partitioned on date columns that are not casts to strings.
Most metastores will handle this just fine, but Derby and some others will throw an exception. MySQL and Postgres backed metastores will handle this fine and won't need to fall back or generate an exception.
Without setting this, many of the tests in `TestAddFiles` fail with `MetaException(message:Filtering is supported only on partition keys of type string)`
This is related to https://issues.apache.org/jira/browse/SPARK-36128. The consensus in the community was that `false` is the best value for this in production environments as this can in theory have impact on performance, to let users know and adjust their data accordingly.
For tests though, it …
=> [SPARK] Add in config value needed in tests once Spark 3.2 is supported

build.gradle
`spark-core` already has the dependency `zstd-jni`, it should be exclude from `iceberg-spark3-runtime`.
=> Build: Exclude zstd-jni from iceberg-spark3-runtime

core/src/main/java/org/apache/iceberg/MetadataTableUtils.java, spark/src/main/java/org/apache/iceberg/spark/SparkTableUtil.java, spark3/src/main/java/org/apache/iceberg/spark/Spark3Util.java
This updates Spark 3 to create metadata tables directly inside of actions, instead of loading them through a SparkCatalog.
This avoids a problem where metadata tables used by the expire snapshots action were using `HadoopFileIO` instead of a custom `FileIO` implementation. The problem happened in the expire snapshots action, where metadata tables are used for file reachability datasets, but are based on a `StaticTableOperations` that points directly to a metadata file path. `SparkTableUtil` would create the metadata table by translating the table back to an identifier and loading it. For static tables, the identifier is the location of the metadata file. This causes Spark to load the metadata table using HadoopTables instead of a catalog, which then uses `HadoopFileIO`.
The solution is to …
=> Spark: Create metadata tables directly to preserve custom FileIO

.github/workflows/java-ci.yml
Adding info level logs to the JVM CI suite to help debug occasional timeouts that occur when the CI suite is trying to run the Spark 3 tests (happens occasionally for both Java 8 and Java 11).
We can revert this after we have the chance to review logs with timeouts.
From there, we'll either be able to fix our situation or need to run with `-d` (debug logs). Then there are additional GitHub Actions logs we can get too after that.
Related to this issue https://github.com/apache/iceberg/issues/3091
=> [BUILD] Add gradle info level logs to JVM CI suite to debug irregular timeouts during CI

spark/src/main/java/org/apache/iceberg/spark/SparkSchemaUtil.java, spark3/src/main/java/org/apache/iceberg/spark/source/SparkBatchScan.java
When estimating statistics, we should take the read schema into account.
As explained in the [PR](https://github.com/apache/spark/pull/33825) for [SPARK-36568](https://issues.apache.org/jira/browse/SPARK-36568):
`V2ScanRelationPushDown` can column prune `DataSourceV2ScanRelation`s and change read schema of `Scan` operations. 
In `SparkBatchScan.estimateStatistics()`, before this change, for unpartitioned tables or partitioned tables with no filter expressions, we sum the file sizes of the files to be scanned and use that as the estimate for the size in bytes. With this change, we adjust that by the ratio of the size of the columns to be read to the size of all the columns; we also adjust that by the compression factor in case it is set (the default is 1.0). With this change, some joins …
=> Spark: Better SparkBatchScan statistics estimation

aws/src/integration/java/org/apache/iceberg/aws/dynamodb/DynamoDbCatalogTest.java, aws/src/main/java/org/apache/iceberg/aws/dynamodb/DynamoDbCatalog.java
This PR is intended to resolve an issue with `DynamoDbCatalog.dropNamespace()` --  the dynamoDB delete fails as the conditionExpression evaluates to e.g. `attribute_exists(my_db)`, rather than `attribute_exists(namespace)`.  
Example namespace record in dynamo:
```json
{
"identifier": "NAMESPACE",
"namespace": "my_db",
"updated_at": 1628190933466,
"created_at": 1628190933466,
"v": "0203ec48-317b-4197-9712-4a7c91b5c91a",
"p.owner": "bijan"
}
```
@jackye1995 - can you confirm this change makes sense  / is what was intended?
@danielcweeks
=> AWS: update DynamoDbCatalog.dropNamespace attr check

core/src/main/java/org/apache/iceberg/hadoop/HadoopCatalog.java, core/src/test/java/org/apache/iceberg/hadoop/TestHadoopCatalog.java
=> Hadoop drop table to return false if table does not exist

core/src/main/java/org/apache/iceberg/BaseRowDelta.java, core/src/main/java/org/apache/iceberg/MergingSnapshotProducer.java, core/src/test/java/org/apache/iceberg/TestRowDelta.java
This PR optimizes our check for referenced data files in `BaseRowDelta` by pushing down the conflict detection filter. Previously, we would open manifests even though they belonged to partitions out of our interest.
=> Core: Optimize check for referenced data files in BaseRowDelta

flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSink.java
This test has a race condition, where one of the two disjointed DAGs can finish and close its tasks before the other has finished.
When the task(s) belonging to the disjoint DAG which terminated aren't present to participate in checkpointing, it leads to an infinite loop of attempting to re-checkpoint.
Here are some of the logs (visible when passing `-i` for info level logs to gradle.
```
2021-09-13T08:19:47.7896411Z > Task :iceberg-flink:test
2021-09-13T08:19:47.7899950Z     [Checkpoint Timer] INFO org.apache.flink.runtime.checkpoint.CheckpointCoordinator - Checkpoint triggering task Source: rightCustomSource -> rightIcebergSink-rightIcebergSink -> rightIcebergSink-IcebergStreamWriter (1/1) of job 437e46445e777ca2231677f60f87496a is not in state RUNNING but FINISHED instead. Aborting …
```
=> Flink - Ignore test that leads to infinite checkpoint loop and CI timeouts

spark3-extensions/src/test/java/org/apache/iceberg/spark/extensions/SparkRowLevelOperationsTestBase.java, spark3-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestCopyOnWriteDelete.java, spark3-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestCopyOnWriteMerge.java, spark3-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestCopyOnWriteUpdate.java, spark3-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestDelete.java, spark3-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMerge.java, spark3-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestUpdate.java
When `MERGE INTO` works in `distribution-mode=hash` and `distribution-mode=range`,  we should check there are no duplicate commits. https://github.com/apache/iceberg/blob/master/spark3-extensions/src/main/scala/org/apache/spark/sql/catalyst/utils/RewriteRowLevelOperationHelper.scala#L217
=> Spark3: Add validation for merge into/update/delete  on different distribution-mode

.github/workflows/java-ci.yml
As part of investigating timeouts in CI (https://github.com/apache/iceberg/issues/3091), we added additional logging.
This reverts that logging as we've located the source of the timeouts and are ignoring the one test for now in this PR: https://github.com/apache/iceberg/pull/3110
=> INFRA - Remove additional logs added to Java CI for debugging timeouts

arrow/src/main/java/org/apache/iceberg/arrow/vectorized/ArrowReader.java, arrow/src/main/java/org/apache/iceberg/arrow/vectorized/ColumnVector.java
Changes to the ArrowReader:
1. Add assertions for reader support
2. Don't process delete files since they are not supported in the reader
3. Fix an error message
4. Fix the code style
=> [ARROW] Vectorized Parquet Reads - Assertions + Correctness Checks for Deletion Files

spark2/src/main/java/org/apache/iceberg/spark/source/Reader.java
Follow-up to #3038.
Use (estimated) row size * number of rows to estimate the size instead of adding up file sizes.
The row size is estimated from the pruned schema if we prune columns.
=> Spark: Better statistics estimation for spark2 Reader.

site/docs/nessie.md
There was a broken Nessie link in the documentation, should be fixed with this PR.
=> Doc: Fix Nessie Spark broken link

core/src/main/java/org/apache/iceberg/TableProperties.java, spark2/src/main/java/org/apache/iceberg/spark/source/Reader.java, spark3/src/main/java/org/apache/iceberg/spark/Spark3Util.java, spark3/src/main/java/org/apache/iceberg/spark/source/SparkBatchScan.java
This PR adds a new table property to control the ORC batch size. Previously, we used the Parquet batch size for ORC reads.
=> Core: Add table property for ORC batch size

jmh.gradle
This started to happen after the Gradle 7 upgrade
```
> Task :iceberg-spark3:jmhJar FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':iceberg-spark3:jmhJar'.
> archive contains more than 65535 entries.
To build this archive, please enable the zip64 extension.
See: https://docs.gradle.org/7.2/dsl/org.gradle.api.tasks.bundling.Zip.html#org.gradle.api.tasks.bundling.Zip:zip64
```
=> Build: Enable zip64 to allow > 65535 files for JMH

spark3/src/main/java/org/apache/iceberg/spark/SparkSessionCatalog.java, spark3/src/test/java/org/apache/iceberg/spark/sql/TestRefreshTable.java
Previously this was not implemented making it impossible for users to
refresh Iceberg or Session tables. Here we implement the method by
calling invalidate on the Iceberg catalog if the table exists, and
on the Session catalog if it does not.
Solves #2972
=> Spark: Implement InvalidateTable for SparkSessionCatalog

core/src/main/java/org/apache/iceberg/deletes/EqualityDeleteWriter.java, core/src/main/java/org/apache/iceberg/deletes/PositionDeleteWriter.java, core/src/main/java/org/apache/iceberg/io/DataWriteResult.java, core/src/main/java/org/apache/iceberg/io/DataWriter.java, core/src/main/java/org/apache/iceberg/io/DeleteWriteResult.java, core/src/main/java/org/apache/iceberg/io/FileWriter.java, core/src/main/java/org/apache/iceberg/io/FileWriterFactory.java, core/src/main/java/org/apache/iceberg/io/SortedPosDeleteWriter.java, data/src/main/java/org/apache/iceberg/data/BaseFileWriterFactory.java, data/src/test/java/org/apache/iceberg/io/TestFileWriterFactory.java, data/src/test/java/org/apache/iceberg/io/TestWriterMetrics.java, flink/src/main/java/org/apache/iceberg/flink/sink/FlinkFileWriterFactory.java, flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkFileWriterFactory.java, flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkWriterMetrics.java, spark/src/main/java/org/apache/iceberg/spark/source/SparkFileWriterFactory.java, spark/src/test/java/org/apache/iceberg/spark/source/TestSparkFileWriterFactory.java, spark/src/test/java/org/apache/iceberg/spark/source/TestSparkWriterMetrics.java
This PR adds the `FileWriter` interface that defines a contract for writing a number of files of a single type within one spec/partition.
=> Core: Add FileWriter interface

mr/src/main/java/org/apache/iceberg/mr/mapreduce/IcebergInputFormat.java
I assume we already support ORC MR in Hive and thus, I have changed the exception wording to reflect this.
=> Fix ORC exception typo in IcebergInputFormat

api/src/main/java/org/apache/iceberg/types/Comparators.java
This adds identity cases for comparators. If the arguments to `compare` are the same object, return that the two are equal without more expensive checks.
=> API: Test for identity in comparators

core/src/main/java/org/apache/iceberg/io/DeleteWriteResult.java, core/src/main/java/org/apache/iceberg/io/RollingDataWriter.java, core/src/main/java/org/apache/iceberg/io/RollingEqualityDeleteWriter.java, core/src/main/java/org/apache/iceberg/io/RollingFileWriter.java, core/src/main/java/org/apache/iceberg/io/RollingPositionDeleteWriter.java, data/src/test/java/org/apache/iceberg/io/TestRollingFileWriters.java, flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkRollingFileWriters.java, spark/src/test/java/org/apache/iceberg/spark/source/TestSparkRollingFileWriters.java
This PR adds new rolling writers and contains a subset of changes in PR #2945.
=> Core: Add new rolling file writers

core/src/main/java/org/apache/iceberg/BaseOverwriteFiles.java, core/src/main/java/org/apache/iceberg/BaseReplacePartitions.java, core/src/main/java/org/apache/iceberg/MergingSnapshotProducer.java, core/src/test/java/org/apache/iceberg/TableTestBase.java, core/src/test/java/org/apache/iceberg/TestRowDelta.java
This PR enables committing delete files that belong to different specs in a single operation. Previously, we only supported row deltas where all delete and data files were part of the same spec.
=> Core: Support committing delete files with multiple specs

site/docs/flink-connector.md, site/mkdocs.yml
Add document for the PR #2666 .  I decided to prepare a document for this because I've seen people were asking how to use the flink `'connector'='iceberg'` to create iceberg table in https://github.com/apache/iceberg/issues/3079
=> Docs: Add flink iceberg connector

core/src/main/java/org/apache/iceberg/LocationProviders.java, core/src/main/java/org/apache/iceberg/TableProperties.java, core/src/test/java/org/apache/iceberg/TestLocationProvider.java, site/docs/aws.md, spark/src/jmh/java/org/apache/iceberg/spark/source/IcebergSourceBenchmark.java, spark/src/test/java/org/apache/iceberg/actions/TestRemoveOrphanFilesAction.java, spark/src/test/java/org/apache/iceberg/spark/source/TestDataFrameWrites.java, spark3/src/main/java/org/apache/iceberg/spark/actions/BaseSnapshotTableSparkAction.java
Per discussion in #2965, we deprecate both `write.folder-storage.path` and `write.object-storage.path`, and use `write.data.path` instead. 
Created a new method `LocationProviders::dataLocation` to get the data location and to be compatible with deprecated configs.
cc @rdblue @jackye1995 @aokolnychyi @RussellSpitzer @kbendick @karuppayya
=> Core: Consolidate write.folder-storage.path and write.object-storage.path to write.data.path

build.gradle, core/src/main/java/org/apache/iceberg/deletes/PositionDelete.java, core/src/main/java/org/apache/iceberg/io/ClusteredDataWriter.java, core/src/main/java/org/apache/iceberg/io/ClusteredEqualityDeleteWriter.java, core/src/main/java/org/apache/iceberg/io/ClusteredPositionDeleteWriter.java, core/src/main/java/org/apache/iceberg/io/ClusteredWriter.java, core/src/main/java/org/apache/iceberg/io/FanoutDataWriter.java, core/src/main/java/org/apache/iceberg/io/FanoutWriter.java, core/src/main/java/org/apache/iceberg/io/PartitioningWriter.java, core/src/main/java/org/apache/iceberg/io/StructCopy.java, core/src/test/java/org/apache/iceberg/TableTestBase.java, data/src/test/java/org/apache/iceberg/io/TestAppenderFactory.java, data/src/test/java/org/apache/iceberg/io/TestFileWriterFactory.java, data/src/test/java/org/apache/iceberg/io/TestPartitioningWriters.java, data/src/test/java/org/apache/iceberg/io/TestRollingFileWriters.java, data/src/test/java/org/apache/iceberg/io/WriterTestBase.java, flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkPartitioningWriters.java, jmh.gradle, spark/src/jmh/java/org/apache/iceberg/spark/source/WritersBenchmark.java, spark/src/jmh/java/org/apache/iceberg/spark/source/avro/AvroWritersBenchmark.java, spark/src/jmh/java/org/apache/iceberg/spark/source/parquet/ParquetWritersBenchmark.java, spark/src/test/java/org/apache/iceberg/spark/source/TestSparkPartitioningWriters.java
This PR adds the `PartitioningWriter` interface and two implementations:
- `ClusteredWriter`
- `FanoutWriter`
It is a subset of changes in PR #2945.
=> Core: Add PartitioningWriter

core/src/main/java/org/apache/iceberg/deletes/EqualityDeleteWriter.java, core/src/main/java/org/apache/iceberg/deletes/PositionDeleteWriter.java, core/src/main/java/org/apache/iceberg/io/ClusteredWriter.java, core/src/main/java/org/apache/iceberg/io/FanoutWriter.java, core/src/main/java/org/apache/iceberg/io/FileWriter.java, core/src/main/java/org/apache/iceberg/io/PartitioningWriter.java, core/src/main/java/org/apache/iceberg/io/RollingFileWriter.java, core/src/main/java/org/apache/iceberg/io/SortedPosDeleteWriter.java, data/src/test/java/org/apache/iceberg/io/TestPartitioningWriters.java
This method removes `IOException` from `write` methods in new writers.
This is a follow-up to address [this](https://github.com/apache/iceberg/pull/3164#discussion_r715166505) comment and make using the new APIs easier. This also aligns new classes with existing writers and appenders.
=> Core: Avoid throwing IOException in new write methods

spark3/src/main/java/org/apache/iceberg/spark/source/SparkWrite.java
This PR migrates `SparkWrite` to use new data writers.
=> Spark: Migrate to new data writers in SparkWrite

core/src/main/java/org/apache/iceberg/MetricsConfig.java, core/src/main/java/org/apache/iceberg/avro/Avro.java, data/src/main/java/org/apache/iceberg/data/BaseFileWriterFactory.java, data/src/test/java/org/apache/iceberg/io/TestWriterMetrics.java, flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkWriterMetrics.java, parquet/src/main/java/org/apache/iceberg/parquet/Parquet.java, spark/src/test/java/org/apache/iceberg/spark/source/TestSparkWriterMetrics.java
This PR propagates a correct metrics config for Avro equality deletes and position deletes in Parquet and Avro.
=> Core: Use correct metrics config for delete files

core/src/main/java/org/apache/iceberg/jdbc/JdbcClientPool.java, core/src/main/java/org/apache/iceberg/jdbc/JdbcUtil.java, core/src/test/java/org/apache/iceberg/jdbc/TestJdbcUtil.java
I just try JDBC Catalog in my local machine following [this guide](https://iceberg.apache.org/jdbc/), but I got the following exception:
```bash
$ spark-sql --packages org.apache.iceberg:iceberg-spark3-runtime:0.12.0,org.postgresql:postgresql:42.2.23 \
--conf spark.sql.extensions=org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions \
--conf spark.sql.catalog.iceberg=org.apache.iceberg.spark.SparkCatalog \
--conf spark.sql.catalog.iceberg.warehouse=/tmp/warehouse \
--conf spark.sql.catalog.iceberg.catalog-impl=org.apache.iceberg.jdbc.JdbcCatalog \
--conf spark.sql.catalog.iceberg.uri=jdbc:postgresql://postgres:5432/iceberg \
--conf spark.sql.catalog.iceberg.jdbc.user=postgres \
--conf spark.sql.catalog.iceberg.jdbc.password=SuperSecr3t
spark-sql> CREATE TABLE …
```
=> fix: JdbcCatalog jdbc.user is overwrite by user property

core/src/main/java/org/apache/iceberg/io/BasePositionDeltaWriter.java, core/src/main/java/org/apache/iceberg/io/EqualityDeltaWriter.java, core/src/main/java/org/apache/iceberg/io/PositionDeltaWriter.java, data/src/test/java/org/apache/iceberg/io/TestPositionDeltaWriters.java, flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkPositionDeltaWriters.java, spark/src/test/java/org/apache/iceberg/spark/source/TestSparkPositionDeltaWriters.java
This PR adds position and equality delta writer interfaces and contains a subset of changes in PR #2945.
=> Core: Add position and equality delta writer interfaces

api/src/main/java/org/apache/iceberg/util/StructProjection.java, core/src/main/java/org/apache/iceberg/MetadataColumns.java, core/src/main/java/org/apache/iceberg/util/PartitionUtil.java, spark/src/main/java/org/apache/iceberg/spark/source/BaseDataReader.java, spark/src/main/java/org/apache/iceberg/spark/source/BatchDataReader.java, spark/src/main/java/org/apache/iceberg/spark/source/EqualityDeleteRowReader.java, spark/src/main/java/org/apache/iceberg/spark/source/RowDataReader.java, spark/src/test/java/org/apache/iceberg/spark/source/TestSparkBaseDataReader.java, spark3/src/main/java/org/apache/iceberg/spark/source/SparkScanBuilder.java, spark3/src/test/java/org/apache/iceberg/spark/source/SparkTestTable.java, spark3/src/test/java/org/apache/iceberg/spark/source/TestSparkCatalog.java, spark3/src/test/java/org/apache/iceberg/spark/source/TestSparkMetadataColumns.java
This WIP PR adds support for `_spec` and `_partition` metadata columns so that we can project them for writing deltas.
=> Spark: Support spec ID and partition metadata columns

site/docs/spec.md
This PR updates the spec to include recently added metadata columns.
=> Spec: Add _deleted, _spec_id, _partition metadata columns

spark/src/main/java/org/apache/iceberg/spark/actions/BaseRewriteDataFilesSparkAction.java
It should be checked whether there is no need to rewrite before calling the `toGroupStream()` method, so as to reduce the code logic that does not need to be rewritten.
cc @RussellSpitzer @rdblue @aokolnychyi
=> Spark: Rewrite adjust check group count before to group stream

.asf.yaml
This should opt in the Iceberg project to participate in Hacktoberfest 2021
=> Build: Opt in to hacktoberfest

api/src/main/java/org/apache/iceberg/RowDelta.java, core/src/main/java/org/apache/iceberg/BaseRowDelta.java, core/src/main/java/org/apache/iceberg/DeleteFileIndex.java, core/src/main/java/org/apache/iceberg/MergingSnapshotProducer.java, core/src/test/java/org/apache/iceberg/TableTestBase.java, core/src/test/java/org/apache/iceberg/TestRowDelta.java
This PR validates concurrently added delete files in `BaseRowDelta`.
=> Core: Validate concurrently added delete files in RowDelta

api/src/main/java/org/apache/iceberg/io/OutputFile.java, aws/src/main/java/org/apache/iceberg/aws/s3/S3OutputFile.java, aws/src/main/java/org/apache/iceberg/aws/s3/S3OutputStream.java, aws/src/test/java/org/apache/iceberg/aws/s3/S3OutputStreamTest.java
Fix for #2991 
Seems like for EMR 6.x (Spark 3.x) Iceberg attempts to write the temp files ([S3FileIO Reference](https://iceberg.apache.org/aws/#progressive-multipart-upload)) before the `tmp` directory is created in some cases. This results in `java.io.IOException: No such file or directory` exception. 
The `tmp` files look something like this by default (here `System.getProperty("java.io.tmpdir")` is `/mnt1/yarn/usercache/hadoop/appcache/application_1632368478936_0042/container_1632368478936_0042_01_000001/tmp`):
```
/mnt1/yarn/usercache/hadoop/appcache/application_1632368478936_0042/container_1632368478936_0042_01_000001/tmp/s3fileio-2279038237918274355.tmp
/mnt1/yarn/usercache/hadoop/appcache/application_1632368478936_0042/container_1632368478936_0042_01_000001/tmp/s3fileio-22790382379 …
```
=> AWS: Add check to create staging directory if not exists for S3OutputStream

api/src/main/java/org/apache/iceberg/OverwriteFiles.java, core/src/main/java/org/apache/iceberg/BaseOverwriteFiles.java, core/src/test/java/org/apache/iceberg/TestOverwriteWithValidation.java, spark3/src/main/java/org/apache/iceberg/spark/source/SparkWrite.java
This PR validates concurrently added delete files in `BaseOvewriteFiles`.
=> Core: Validate concurrently added delete files in OvewriteFiles

baseline.gradle
When we recently upgraded the error prone library (I believe as part of the Gradle upgrade), a new ErrorProne rule that's unique to the palantir repo has been added, `ConsistentLoggerName`.
As we typically use `LOG` for the logger name, but the warning wants it to be `log`, I have chosen to turn it off.
I only found about 5-6 instances where it wasn't called `LOG` (a handful of `log` and one or two `logger`).
While this is a nice goal, the palantir fork of error-prone doesn't seem to allow us to configure the expected name [as it's hard coded.](https://github.com/palantir/gradle-baseline/blob/779c6db14689b312bbdb2f4bc705cdfe2f61f078/baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/ConsistentLoggerName.java#L64)
@nastra if you know of a way that we can change this to be …
=> Disable ErrorProne ConsistentLoggerName as we use alternative name

api/src/main/java/org/apache/iceberg/types/GetProjectedIds.java, api/src/main/java/org/apache/iceberg/types/TypeUtil.java, api/src/main/java/org/apache/iceberg/util/StructProjection.java, api/src/test/java/org/apache/iceberg/types/TestTypeUtil.java, core/src/main/java/org/apache/iceberg/BaseTableScan.java, core/src/main/java/org/apache/iceberg/avro/PruneColumns.java, core/src/test/java/org/apache/iceberg/TestSchemaUpdate.java, core/src/test/java/org/apache/iceberg/avro/TestReadProjection.java, parquet/src/main/java/org/apache/iceberg/parquet/PruneColumns.java, spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSourceTablesBase.java
Previously getProjectedIds would only return leaf nodes and primitives that
were selected. This made it impossible to return empty structs. To fix this
we change the behavior to return all id's of required fields including structs.
This in turn requires fixing the alternate PruneColumn methods for Avro
and Parquet to respect that they will now have selected field ID's for non
primitive nodes. Previous use cases of TypeUtil.select are converted to
TypeUtil.project, which inverses this new getProjecetedIds code.
=> API: Change GetProjectedIds to Return all Ids

spark3/src/main/scala/org/apache/spark/sql/catalyst/utils/PlanUtils.scala
Leverage SPARK-32056 to coalesce partitions for repartition by expressions when AQE is enabled in Spark 3.1
Because that `RequiresDistributionAndOrdering` is introduced in SPARK-33779, which is part of Spark 3.2, https://github.com/apache/iceberg/pull/2512#discussion_r658040759 is not suitable for Spark 3.1
This PR pick the idea of https://github.com/apache/iceberg/pull/2512#discussion_r657095040
=> Spark: Leverage SPARK-32056 in Spark 3.1

tasks.gradle
The problem is that `./gradlew printVersion` is currently showing the
branch name instead of the actual Iceberg version, because the version
is being overwritten here.
=> Build: ./gradlew printVersion should print correct Iceberg version

.gitignore
When run tests using Intellij idea, it will create many output files list as follow
```
api/out/
common/out/
core/out/
data/out/
flink/out/
hive-metastore/out/
orc/out/
parquet/out/
```
Those output files will be traced by git
1. add `out` into `.gitignore` to filter those output files.
=> filter idea test outputs from the source code

spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSpark.java
While working on the cherry-picking for creating the initial release candidate for 1.12.1, while trying to cherry-pick this PR, https://github.com/apache/iceberg/pull/3368, a checkstyle error fails the build.
```
> Task :iceberg-spark:checkstyleTest
[ant:checkstyle] [ERROR] /Users/kylebendickson/repos/iceberg-kyle/spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSpark.java:150:36: Unnecessary parentheses around expression. [UnnecessaryParentheses]
```
For some reason, this doesn't come up during the current build / CI, but I need to apply this hotfix to be able to cherry-pick the above PR as cleanly as possible into the 1.12.x branch (and I have a feeling that this might be hinting at some underlying CI tests that aren't being run entirely, for example the Spark v3.2 tests …
=> Hotfix - Remove additional parens to satisfy checkstyle for 1.12.1 cherry-picking

python/setup.py, python/src/iceberg/types.py, python/src/iceberg/utils/bin_packing.py, python/tests/test_types.py, python/tests/utils/test_bin_packing.py, python/tox.ini
This adds black and isort as well as an auto format command `tox -e format` that formats the entire project. The only direct changes I made here is to the `tox.ini` file and the rest of the diff is from running the auto-formatter.
=> Add black and isort as well as tox -e format command

gradle.properties
This updates the default versions included in the build for Spark, Flink, and Hive to only build one version by default: Spark 3.2, Flink 1.13, and Hive 2.
This does not affect CI workflows, which already control versions explicitly and test each version individually.
=> Build: Only build one Spark, Flink, and Hive version by default

spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/SparkMetadataColumn.java, spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/SparkTable.java, spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkCatalog.java, spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkMetadataColumns.java
This PR adds proper support for metadata columns in Spark 3.2.
=> Spark: Support metadata columns in 3.2

hive-metastore/src/main/java/org/apache/iceberg/hive/HiveClientPool.java
Fixes : https://github.com/apache/iceberg/issues/3363, RetryingMetaStoreClient broken for Hive 2.1.
The root cause is this commit: https://issues.apache.org/jira/browse/HIVE-12918, fixed in Hive 2.3 (the version we build against) by https://issues.apache.org/jira/browse/HIVE-15081
Change to use this more stable method in RetryingMetaStoreClient: https://github.com/apache/hive/blob/rel/release-2.3.8/metastore/src/java/org/apache/hadoop/hive/metastore/RetryingMetaStoreClient.java#L95.  
I'm usually hesitant to use @VisibleForTesting methods, but as @sunchao pointed out offline to me, for Hive it means the method is at least tested :), unlike the non marked one.
=> Hive: Fix RetryingMetaStoreClient for Hive 2.1

core/src/main/java/org/apache/iceberg/TableMetadata.java, spark/v3.0/spark/src/test/java/org/apache/iceberg/spark/sql/TestCreateTableAsSelect.java, spark/v3.1/spark/src/test/java/org/apache/iceberg/spark/sql/TestCreateTableAsSelect.java, spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/sql/TestCreateTableAsSelect.java
Originally when we rebuild the partition spec for V1 tables we automatically
include void transforms for and source column which is not be transformed
identically in the new replacement table. This has issues if the column's
partitioning transform has changed leading to errors because a spec can
only transform a given column a single time. To fix this we instead replace
any transform in the previous spec that was modifying the same source column
as the new spec. Voids are still propagated for source columns which are
untransformed in the new spec.
=> Core: Fix Replace Table with Changing Partition Spec

api/src/main/java/org/apache/iceberg/OverwriteFiles.java, api/src/main/java/org/apache/iceberg/RowDelta.java, core/src/main/java/org/apache/iceberg/BaseOverwriteFiles.java, core/src/main/java/org/apache/iceberg/BaseRowDelta.java, core/src/main/java/org/apache/iceberg/DeleteFileIndex.java, core/src/main/java/org/apache/iceberg/MergingSnapshotProducer.java, core/src/test/java/org/apache/iceberg/TableTestBase.java, core/src/test/java/org/apache/iceberg/TestOverwriteWithValidation.java, core/src/test/java/org/apache/iceberg/TestRowDelta.java, hive-metastore/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java, spark3/src/main/java/org/apache/iceberg/spark/source/SparkWrite.java
This PR is to get the following two PRs, slated for release in 0.12.1, to be able to merge.
Neither of them cherry-pick cleanly, though I do know the set of PRs that would be needed to do so (as mentioned in another PR).
- https://github.com/apache/iceberg/pull/3195
- https://github.com/apache/iceberg/pull/3199
** Merge first - After a decision is made about #3264
=> 0.12.1 Cherry-Picks: Part 2

api/src/main/java/org/apache/iceberg/Metrics.java, build.gradle, core/src/main/java/org/apache/iceberg/avro/Avro.java, data/src/main/java/org/apache/iceberg/data/TableMigrationUtil.java, hive-metastore/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java, mr/src/main/java/org/apache/iceberg/mr/Catalogs.java, mr/src/main/java/org/apache/iceberg/mr/hive/Deserializer.java, mr/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergSerDe.java, mr/src/test/java/org/apache/iceberg/mr/TestCatalogs.java, orc/src/main/java/org/apache/iceberg/orc/OrcMetrics.java, spark/src/main/java/org/apache/iceberg/spark/IcebergSpark.java, spark/src/main/java/org/apache/iceberg/spark/SparkValueConverter.java, spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSpark.java, spark3-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestAddFilesProcedure.java
This includes the last round of cherry-picks for the 0.12.1 rc0.
It is a continuation of https://github.com/apache/iceberg/pull/3402 and https://github.com/apache/iceberg/pull/3429.
I will marked the things I needed to change, but mostly it was just updating files as we did not backport the project structural reorganization for multiple spark versions by path.
The only PR cherry-picked that wasn't 100% clean was #3338 `Hive: Fix Catalogs.hiveCatalog method for default catalogs`. But even that one, the differences between the two were exactly the same, it just wasn't considered clean as there were PRs prior to it that weren't grabbed but they didn't affect the parts we care about (just the line numbers).
Otherwise, everything cherry-picked cleanly, except for PRs that came after the …
=> 0.12.1 Cherry-Picks: Part 3

build.gradle, spark/v3.2/build.gradle, versions.props
To fix #3405. 
According to https://github.com/apache/iceberg/blob/d08a1f7dcf878bae5e96eef8510c34ff644a7f79/spark/v3.2/build.gradle#L235, the netty buffer should only come from project(':iceberg-arrow'). So we need to exclude any other libs which depend on netty buffer.
hadoop-minicluster depends on netty buffer, but we don't need to exclude Netty buffer here since it is only for test, it won't come across with relocation of Netty buffer
```
testImplementation("org.apache.hadoop:hadoop-minicluster") {
exclude group: 'org.apache.avro', module: 'avro'
}
```
cc @rdblue @aokolnychyi @RussellSpitzer @karuppayya @szehon-ho
=> Spark: Enforce the netty buffer version to fix jmh test failures in Spark 3.2

dev/source-release.sh
The `sha512sum` doesn't exist on my relatively new macbook out of the box.
I've updated it to something equivalent that exists on both a linux computer and my macbook.
=> Build: Make source-release script macOS compatible

.github/workflows/java-ci-bechmarks.yml, .github/workflows/jmh-bechmarks.yml, site/docs/benchmarks.md
@rdblue this is a proposal that allows running the existing Benchmarks via GH actions by manually triggering the `JMH Benchmarks` action.
I have been doing some experiments on my own fork and the benchmark results can be seen in https://github.com/nastra/iceberg/actions/workflows/jmh-bechmarks.yml (note the **benchmark-results** artifact at the bottom with the uploaded results)
=> Run Benchmarks via GH actions

python/src/iceberg/types.py, python/tox.ini
* This PR adds tox commands to automate code formatting and type checking.
* tox uses following 
> - black for code formatting
> - isort for import ordering
> - autoflake for removing unused imports
> - mypy for static type checking
* Core tox commands
> - `tox` will run tests and linters (code format and type checks). This is the central command that'll be most used.
> - `tox -e linters` will check if the code adheres to the standard and passes type checking
>- `tox -e format` automates code reformatting
* Future enhancements
>- Add tox commands for documentation creation
>- Perhaps add git pre-recommit hooks to make it more seamless?
* We'll need a follow PR to run these commands over the codebase.
=> Python: Add tox commands for code format and type checking #3282

site/README.md, site/deploy.sh, tasks.gradle
Only the last command in the gradle `deploySite` task was being run, which resulted in some stale pages in the site after the style update. This moves the deployment logic into `site/deploy.sh`.
=> Build: Fix deploySite task
