core/src/main/java/com/netflix/iceberg/avro/Avro.java

Avro.Writer.build() now returns FileAppender instead of package private AvroFileAppender

---

parquet/src/main/java/com/netflix/iceberg/parquet/ColumnIterator.java
parquet/src/main/java/com/netflix/iceberg/parquet/ColumnWriter.java
parquet/src/main/java/com/netflix/iceberg/parquet/PageIterator.java
parquet/src/main/java/com/netflix/iceberg/parquet/ParquetDictionaryRowGroupFilter.java

Remove calls to deprecated ColumnDescriptor.getType method.

---

parquet/src/main/java/com/netflix/iceberg/parquet/Parquet.java

(cherry picked from commit a33a217dd063c76e95b272206bacc0ca503f297d)

Parquet write should use Hadoop conf from HadoopOutputFile

---

api/src/main/java/com/netflix/iceberg/Table.java
api/src/main/java/com/netflix/iceberg/io/FileIO.java
api/src/main/java/com/netflix/iceberg/io/LocationProvider.java
core/src/main/java/com/netflix/iceberg/BaseMetastoreTableOperations.java
core/src/main/java/com/netflix/iceberg/BaseTable.java
core/src/main/java/com/netflix/iceberg/BaseTransaction.java
core/src/main/java/com/netflix/iceberg/LocationProviders.java
core/src/main/java/com/netflix/iceberg/TableMetadata.java
core/src/main/java/com/netflix/iceberg/TableOperations.java
core/src/main/java/com/netflix/iceberg/hadoop/HadoopTableOperations.java
core/src/main/java/com/netflix/iceberg/util/PropertyUtil.java
core/src/test/java/com/netflix/iceberg/LocalTableOperations.java
core/src/test/java/com/netflix/iceberg/TestTables.java
spark/src/main/java/com/netflix/iceberg/spark/source/Writer.java
spark/src/test/java/com/netflix/iceberg/spark/source/TestTables.java

This is a different approach to the same problem that #73 addresses.

Add LocationProvider to determine data file locations.

---

core/src/main/java/com/netflix/iceberg/hadoop/HadoopStreams.java

This adds a finalizer that closes open streams when they are garbage collected. It also logs the stack that opened the stream to catch leaks.

Add finalizer for Hadoop streams to catch paths that don't call close.

---

README.md

As per #30, updating README file.

Minor: Update README to state Spark 2.4.0 support.

---

core/src/test/java/com/netflix/iceberg/hadoop/TestHadoopCommits.java

**This PR:**
- Adds a unit test to update table schema with a complex (nested) struct
- Makes assertions on schema correctness

[Minor] Add UT: UpdateSchemaWithComplexStruct

---

core/src/main/java/org/apache/iceberg/avro/AvroIterable.java

Fix missing close call for Avro with container reuse.

---

api/src/main/java/org/apache/iceberg/expressions/ExpressionVisitors.java
api/src/main/java/org/apache/iceberg/expressions/SerializationProxies.java
api/src/main/java/org/apache/iceberg/transforms/Bucket.java
api/src/main/java/org/apache/iceberg/types/Type.java
common/src/main/java/org/apache/iceberg/common/DynFields.java
common/src/main/java/org/apache/iceberg/common/DynMethods.java
core/src/main/java/org/apache/iceberg/BaseTableScan.java
core/src/main/java/org/apache/iceberg/PartitionData.java
core/src/main/java/org/apache/iceberg/hadoop/HadoopTableOperations.java
core/src/main/java/org/apache/iceberg/util/BinPacking.java
parquet/src/main/java/org/apache/iceberg/parquet/ParquetFilters.java
spark/src/main/java/org/apache/iceberg/spark/data/SparkParquetReaders.java
spark/src/main/java/org/apache/iceberg/spark/source/Writer.java

Add override annotations for HadoopTableOperations
Signed-off-by: Yishuang Lu <luystu@gmail.com>

Add override annotations for HadoopTableOperations

---

core/src/main/java/org/apache/iceberg/util/Tasks.java

trivial improvement when reviewing PR #142: https://github.com/apache/incubator-iceberg/pull/142#issuecomment-476057486

Break the loop early if exception matches onlyRetryExceptions.

---

core/src/main/java/org/apache/iceberg/GenericDataFile.java

Required since ByteBuffer itself isn't serializable. Override Java serialization to convert to byte array first before pushing to object streams.
Closes #169

Properly serialize key metadata in GenericDataFile.

---

api/src/main/java/org/apache/iceberg/DataFile.java
api/src/test/java/org/apache/iceberg/TestHelpers.java
core/src/main/java/org/apache/iceberg/DataFiles.java
core/src/main/java/org/apache/iceberg/GenericDataFile.java
spark/src/main/scala/org/apache/iceberg/spark/SparkTableUtil.scala

Remove block_size_in_bytes from API. Make the corresponding avro field optional.

---

python/iceberg/core/util/bin_packing.py
python/tests/core/utils/test_bin_packing.py

This is used in BaseScanTask to combine scan tasks into a BaseCombinedScanTask up to the split size

Adding Bin Packing util for Combining scan tasks

---

spark/src/main/java/org/apache/iceberg/spark/data/SparkOrcReader.java

* Make converters reusable by avoiding storing the `UnsafeWriter` in the converters

SparkORCReader should create converters only once and not per record (#195)

---

build.gradle
common/src/main/java/org/apache/iceberg/common/DynFields.java
core/src/main/java/org/apache/iceberg/BaseFileScanTask.java
core/src/main/java/org/apache/iceberg/BaseSnapshot.java
core/src/main/java/org/apache/iceberg/BaseTableScan.java
core/src/main/java/org/apache/iceberg/GenericDataFile.java
core/src/main/java/org/apache/iceberg/GenericManifestFile.java
core/src/main/java/org/apache/iceberg/GenericPartitionFieldSummary.java
core/src/main/java/org/apache/iceberg/ManifestEntry.java
core/src/main/java/org/apache/iceberg/TableMetadata.java

Trying to fix #162 
Test Plan: ./gradlew build (it runs unit tests)

guava: upgrade it to latest

---

core/src/main/java/org/apache/iceberg/BaseTableScan.java

SimpleDateFormat is not thread safe.

Fix thread safety of date formatting in BaseTableScan

---

core/src/main/java/org/apache/iceberg/BaseMetastoreTables.java
core/src/main/java/org/apache/iceberg/BaseTable.java
core/src/main/java/org/apache/iceberg/BaseTransaction.java
core/src/main/java/org/apache/iceberg/Transactions.java
core/src/test/java/org/apache/iceberg/TestTables.java

This allows using it outside of BaseMetastoreTables.

Move BaseTransaction factory methods to Transaction

---

api/src/main/java/org/apache/iceberg/transforms/Bucket.java

The primary motivation of this change is to simplify the code. As a bonus, a simple JMH benchmark shows that the new code is twice as fast:
```
Benchmark                          Mode  Cnt         Score        Error  Units
BenchmarkBucketUuid.bucketBuffer  thrpt    5  14548998.313 ± 209390.443  ops/s
BenchmarkBucketUuid.bucketDirect  thrpt    5  30708144.423 ± 522965.940  ops/s
```

Simplify BucketUUID to remove thread local

---

api/src/main/java/org/apache/iceberg/transforms/Bucket.java
site/docs/spec.md

Use doubleToLongBits instead of doubleToRawLongBits. 

---

site/docs/spec.md

This pull request fixes some minor typos and grammatical issues, along with some incongruent formatting in lists/tables.

Fix some spelling/grammar issues and some incongruent formatting

---

build.gradle

Install source JAR when running install target

---

site/docs/spark.md

Tested locally with:
```
mkdocs serve
```
@rdblue

[site] Fix broken link to Iceberg API

---

python/setup.py
python/tox.ini

python: Remove unused deps

---

core/src/main/java/org/apache/iceberg/mapping/NameMapping.java

Add public factory methods for NameMapping

---

core/src/main/java/org/apache/iceberg/BaseTransaction.java

Hit a null pointer exception after deploying the recent transaction cleanup fixes.

Minor update to BaseTransaction snapshot ID handling

---

core/src/test/java/org/apache/iceberg/TestScanSummary.java
spark/src/test/java/org/apache/iceberg/spark/data/AvroDataTest.java

This adds a couple of test cases that have been left out of other PRs.

Add test cases

---

python/iceberg/api/types/conversions.py
python/iceberg/api/types/type.py
python/iceberg/api/types/type_util.py
python/iceberg/api/types/types.py

Some minor code refactors and fixing some bugs uncovered during read path implementation. 
@danielcweeks

[python]Bringing type module into sync

---

python/iceberg/api/expressions/evaluator.py
python/iceberg/api/expressions/inclusive_manifest_evaluator.py
python/iceberg/api/expressions/inclusive_metrics_evaluator.py
python/iceberg/api/expressions/literals.py
python/iceberg/api/expressions/residual_evaluator.py
python/iceberg/api/expressions/strict_metrics_evaluator.py

Some of the files in expressions modules have diverged between our internal project and the open source. This commit has some minor changes to bring the two back into sync
@danielcweeks

[python]Bringing expression implementations back into synchronization

---

core/src/test/java/org/apache/iceberg/TestScanSummary.java

This fixes the flaky test identified here: https://github.com/apache/incubator-iceberg/pull/389#pullrequestreview-276110033

Fix flaky TestScanSummary test

---

core/src/main/java/org/apache/iceberg/BaseOverwriteFiles.java
core/src/main/java/org/apache/iceberg/BaseReplacePartitions.java
core/src/main/java/org/apache/iceberg/BaseRewriteFiles.java
core/src/main/java/org/apache/iceberg/BaseRewriteManifests.java
core/src/main/java/org/apache/iceberg/BaseTable.java
core/src/main/java/org/apache/iceberg/BaseTransaction.java
core/src/test/java/org/apache/iceberg/TestRewriteFiles.java
core/src/test/java/org/apache/iceberg/TestRewriteManifests.java

This PR renames some classes to be consistent with the rest of the codebase.

Rename some implementations for consistency

---

api/src/main/java/org/apache/iceberg/PartitionSpec.java

It is about a typo in comment, no change on any logic.
(1) 100 should be 1000
(2) Add link to point to the declaration of PARTITION_DATA_ID_START

Correct typo about PARTITION_DATA_ID_START

---

api/src/main/java/org/apache/iceberg/Files.java
api/src/main/java/org/apache/iceberg/exceptions/NotFoundException.java
api/src/main/java/org/apache/iceberg/io/InputFile.java
core/src/main/java/org/apache/iceberg/hadoop/HadoopInputFile.java

Add a new NotFoundException for callers to act upon this scenario.

InputFile.newStream should throw NotFoundException when the file does not exist

---

parquet/src/main/java/org/apache/iceberg/parquet/ParquetMetricsRowGroupFilter.java

This PR adds optimizations to ParquetMetricsRowGroupFilter by using ByteBuffer, and  resolves #423.

Optimize ParquetMetricsRowGroupFilter by using ByteBuffer

---

core/src/main/java/org/apache/iceberg/BaseMetastoreCatalog.java
core/src/main/java/org/apache/iceberg/DataFilesTable.java
core/src/main/java/org/apache/iceberg/HistoryTable.java
core/src/main/java/org/apache/iceberg/ManifestEntriesTable.java
core/src/main/java/org/apache/iceberg/ManifestsTable.java
core/src/main/java/org/apache/iceberg/MetadataTableType.java
core/src/main/java/org/apache/iceberg/SnapshotsTable.java
core/src/main/java/org/apache/iceberg/hadoop/HadoopTables.java
spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSourceHadoopTables.java

Fixes #404. Based heavily on #252.

Add metadata tables for path-based tables

---

README.md

Fixes https://github.com/apache/incubator-iceberg/issues/167
```
MacBook-Pro-van-Fokko:incubator-iceberg fokkodriesprong$ ./gradlew 
> Task :help
Welcome to Gradle 5.4.1.
```

Update docs to Gradle 5.4.1

---

core/src/main/java/org/apache/iceberg/FindFiles.java
core/src/test/java/org/apache/iceberg/TestFindFiles.java

Avoid NullPointerException in FindFiles when there is no snapshot

---

NOTICE

This was caught on the IPMC vote thread for the 0.7.0-incubating release.

Update copyright dates in NOTICE

---

baseline.gradle
build.gradle
deploy.gradle
jmh.gradle
tasks.gradle

This also adds suppressions for errorprone checks that are noisy.

Refactor the build into multiple gradle scripts.

---

jmh.gradle

Disable ErrorProne during compilation of JMH generated classes

---

api/src/main/java/org/apache/iceberg/catalog/TableIdentifier.java
core/src/main/java/org/apache/iceberg/DataTableScan.java
core/src/main/java/org/apache/iceberg/ManifestReader.java
hive/src/main/java/org/apache/iceberg/hive/HiveCatalog.java
spark/src/main/java/org/apache/iceberg/spark/data/SparkOrcWriter.java

Fix MissingOverride error

---

core/src/main/java/org/apache/iceberg/hadoop/SerializableConfiguration.java

Fix InconsistentCapitalization error

---

core/src/main/java/org/apache/iceberg/avro/Avro.java

Fix ImmutableEnumChecker error

---

api/src/main/java/org/apache/iceberg/PartitionSpec.java

Fix ObjectsHashCodePrimitive error

---

api/src/main/java/org/apache/iceberg/PartitionSpec.java
core/src/main/java/org/apache/iceberg/TableMetadataParser.java

Fix PreconditionsInvalidPlaceholder error

---

core/src/main/java/org/apache/iceberg/avro/GenericAvroReader.java
core/src/main/java/org/apache/iceberg/avro/ValueReaders.java
core/src/test/java/org/apache/iceberg/avro/TestAvroEnums.java
spark/src/main/java/org/apache/iceberg/spark/data/SparkAvroReader.java
spark/src/main/java/org/apache/iceberg/spark/data/SparkValueReaders.java
spark/src/test/java/org/apache/iceberg/spark/data/TestSparkAvroEnums.java

Support reading Avro enums as strings

---

spark/src/main/scala/org/apache/iceberg/spark/SparkTableUtil.scala
spark/src/test/java/org/apache/iceberg/spark/source/TestSparkTableUtilWithInMemoryCatalog.java

I think we should support importing certain partitions to Iceberg tables in `SparkTableUtil` as we already have `getPartitionsByFilter`. That way, users don't have to import all partitions to try Iceberg.

Extend SparkTableUtil to import only certain partitions

---

core/src/main/java/org/apache/iceberg/MergingSnapshotProducer.java
core/src/test/java/org/apache/iceberg/TableTestBase.java
core/src/test/java/org/apache/iceberg/TestMergeAppend.java

related to issue #490 
@aokolnychyi can you please review. thanks !

respect commit.manifest.min.count

---

api/src/main/java/org/apache/iceberg/catalog/Catalog.java
api/src/main/java/org/apache/iceberg/catalog/Namespace.java
api/src/main/java/org/apache/iceberg/catalog/TableIdentifier.java
core/src/main/java/org/apache/iceberg/CachingCatalog.java
core/src/main/java/org/apache/iceberg/CommitCallbackTransaction.java

This is a catalog implementation that wraps another catalog and adds table caching.

Add CachingCatalog

---

api/src/main/java/org/apache/iceberg/expressions/InclusiveMetricsEvaluator.java
core/src/main/java/org/apache/iceberg/BaseMetastoreTableOperations.java
hive/src/main/java/org/apache/iceberg/hive/ClientPool.java
spark/src/main/java/org/apache/iceberg/spark/data/SparkParquetWriters.java
spark/src/main/java/org/apache/iceberg/spark/source/Writer.java

There are a lot of unused variables and a lot of warnings in the console. I've removed some of them,  that didn't make any sense.

Remove some of the unused variables

---

site/docs/configuration.md

This PR adds missing table properties to our docs.

Add missing table properties to configuration.md

---

core/src/main/java/org/apache/iceberg/hadoop/HadoopCatalog.java
core/src/test/java/org/apache/iceberg/hadoop/TestHadoopCatalog.java

Check the metadata directory is an iceberg table directory, use the file `.metadata.json` .

[ISSUE #680] Fix the listTable in HadoopCatalog

---

api/src/main/java/org/apache/iceberg/expressions/BoundReference.java
api/src/main/java/org/apache/iceberg/expressions/NamedReference.java
api/src/main/java/org/apache/iceberg/expressions/UnboundPredicate.java
api/src/main/java/org/apache/iceberg/expressions/UnboundTransform.java

While debugging the Avro stuff, I've noticed that there were a lot of warnings :-)

Add missing overrides

---

hive/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java

The PR is trying to address issue #399

Add timeout for acquiring locks in HiveTableOperations

---

spark/src/main/java/org/apache/iceberg/spark/source/Reader.java

This addresses the issue of #697 to add PreferredLocations support for Iceberg Spark ReadTask. This PR is against master branch, I will backport to spark-3 branch once ready. 
This patch is verified manually under Spark 2.4 and Hadoop 2.7 (I didn't add an UT since it is a little complicated to mock FileSystem and others).

Add PreferredLocations support for Iceberg Spark Source

---

core/src/main/java/org/apache/iceberg/CachingCatalog.java

trying to address the discussion [here,](https://github.com/apache/incubator-iceberg/pull/653/files#r369126444)
by passing "purge" option further

Pass purge option in dropTable of CachingCatalog

---

site/docs/configuration.md

This PR adds docs for our Hadoop properties.

Document Hadoop config options

---

api/src/main/java/org/apache/iceberg/expressions/ResidualEvaluator.java
api/src/test/java/org/apache/iceberg/transforms/TestResiduals.java

Address https://github.com/apache/incubator-iceberg/issues/760.

Support in and notIn in ResidualVisitor

---

core/src/main/java/org/apache/iceberg/IncrementalDataTableScan.java

Fixes: #765: This addresses the following follow-ups from #315
Use a single manifestgroup for doing planning in a single run

Incremental scan followups

---

api/src/main/java/org/apache/iceberg/Metrics.java
core/src/test/java/org/apache/iceberg/TestMetrics.java

Adding javadoc to `Metrics` following `Parquet` metrics implementation as proposal.

Metrics javadoc fixes #767

---

core/src/main/java/org/apache/iceberg/SnapshotManager.java
core/src/test/java/org/apache/iceberg/TestWapWorkflow.java

This updates the `SnapshotManger` cherrypick operation to allow picking any commit if its parent is still the current version. This adds a new validation for the current snapshot ID.

Allow cherry-picking any commit as long as it is a fast-forward

---

api/src/main/java/org/apache/iceberg/types/TypeUtil.java
core/src/main/java/org/apache/iceberg/avro/TypeToSchema.java

This fixes #831 by removing the linked list that is accidentally shared between threads when `SchemaVisitor` implementations are singletons. Now, `SchemaVisitor` exposes `beforeField` and `afterField` callbacks so the visitor that uses field IDs can track them itself.

Fix SchemaVisitor thread safety

---

.travis.yml

Updating travis to use bionic instead of trusty. @chyzzqo2 do you think I should be updating this to use python 3.7 too?
cc: @rdblue @danielcweeks

Updating travis to use bionic

---

data/src/main/java/org/apache/iceberg/data/TableScanIterable.java
data/src/test/java/org/apache/iceberg/data/TestLocalScan.java

For issue [https://github.com/apache/incubator-iceberg/issues/848](https://github.com/apache/incubator-iceberg/issues/848)
@rdsr  please help to review, thanks

IcebergGenerics should support ORC format

---

api/src/main/java/org/apache/iceberg/Schema.java
api/src/main/java/org/apache/iceberg/catalog/TableIdentifier.java

While reading source code, I found a few comments can be improved/fixed.

[Doc][Minor]: Fix comments

---

core/src/main/java/org/apache/iceberg/AllDataFilesTable.java
core/src/main/java/org/apache/iceberg/AllEntriesTable.java
core/src/main/java/org/apache/iceberg/AllManifestsTable.java
core/src/main/java/org/apache/iceberg/BaseTableScan.java
core/src/main/java/org/apache/iceberg/DataFilesTable.java
core/src/main/java/org/apache/iceberg/ManifestEntriesTable.java
core/src/main/java/org/apache/iceberg/StaticTableScan.java
core/src/main/java/org/apache/iceberg/TableProperties.java
core/src/test/java/org/apache/iceberg/TestEntriesMetadataTable.java
core/src/test/java/org/apache/iceberg/TestSplitPlanning.java
spark/src/test/java/org/apache/iceberg/spark/source/TestDataSourceOptions.java

Related issue https://github.com/apache/incubator-iceberg/issues/817

Support configurable split size for metadata tables

---

api/src/main/java/org/apache/iceberg/types/TypeUtil.java
api/src/test/java/org/apache/iceberg/transforms/TestBucketing.java
api/src/test/java/org/apache/iceberg/transforms/TestTruncatesResiduals.java
api/src/test/java/org/apache/iceberg/types/TestSerializableTypes.java
core/src/main/java/org/apache/iceberg/avro/TypeToSchema.java
core/src/main/java/org/apache/iceberg/avro/ValueWriters.java
parquet/src/main/java/org/apache/iceberg/parquet/ParquetAvro.java
parquet/src/main/java/org/apache/iceberg/parquet/ParquetValueWriters.java
parquet/src/main/java/org/apache/iceberg/parquet/TypeToMessageType.java
spark/src/main/java/org/apache/iceberg/spark/data/SparkParquetWriters.java
spark/src/main/java/org/apache/iceberg/spark/data/SparkValueWriters.java

Fixed a few typos found in the code.

fix typos in api

---

core/src/main/java/org/apache/iceberg/RemoveSnapshots.java

Replaced it with ConcurrentHashMap.newKeySet

Fixes #874 Remove Netty's ConcurrentSet

---

site/docs/spec.md

This is for https://github.com/apache/incubator-iceberg/issues/359

Define file and position based deletion file in spec

---

core/src/main/java/org/apache/iceberg/AllDataFilesTable.java
core/src/main/java/org/apache/iceberg/AllEntriesTable.java
core/src/main/java/org/apache/iceberg/AllManifestsTable.java
core/src/main/java/org/apache/iceberg/BaseMetadataTable.java
core/src/main/java/org/apache/iceberg/DataFilesTable.java
core/src/main/java/org/apache/iceberg/HistoryTable.java
core/src/main/java/org/apache/iceberg/ManifestEntriesTable.java
core/src/main/java/org/apache/iceberg/ManifestsTable.java
core/src/main/java/org/apache/iceberg/PartitionsTable.java
core/src/main/java/org/apache/iceberg/SnapshotsTable.java

Refactor` location()` method for different metadata tables

[ISSUE #904] Refactor the metadata table `location()`

---

data/src/main/java/org/apache/iceberg/data/orc/GenericOrcWriter.java
parquet/src/main/java/org/apache/iceberg/parquet/PageIterator.java

Reduces the number of errors in the build

Add missing `@Override` annotations

---

core/src/main/java/org/apache/iceberg/ManifestLists.java
core/src/test/java/org/apache/iceberg/TestSnapshotJson.java

This method is only used in one test.

Remove unused ManifestLists.write method

---

mr/src/main/java/org/apache/iceberg/mr/mapreduce/IcebergInputFormat.java
mr/src/test/java/org/apache/iceberg/mr/mapreduce/TestIcebergInputFormat.java

This is for https://github.com/apache/incubator-iceberg/issues/866.

Add residual evaluation for MR reader

---

build.gradle

Configuration based on [these recommendations](https://stackoverflow.com/questions/28614865/how-to-read-test-result-reports-on-travis-ci).

Log test failure exceptions in Travis CI

---

api/src/main/java/org/apache/iceberg/events/Listeners.java

The thread safety in `Listeners` was incorrect. It was locking on a concurrent map, then updating the resulting value list outside the lock unsafely.
This updates to delegate lookup and initialization to the concurrent map using `computeIfAbsent`, and changes the map values to concurrent queues.

Fix thread safety in listeners and simplify implementation

---

README.md

Document Java version should be exact 1.8

---

site/docs/presto.md

The connector is already part of the master branch of Presto SQL, although many features are still missing.

Update documentation for Presto SQL

---

spark-runtime/DISCLAIMER

This was added to the build in #966.

Add DISCLAIMER to spark-runtime

---

core/src/main/java/org/apache/iceberg/ManifestFiles.java
core/src/test/java/org/apache/iceberg/TableTestBase.java
spark/src/main/java/org/apache/iceberg/actions/RewriteManifestsAction.java

This PR ensures that we use the correct manifest version while rewriting them.

Use correct manifest versions while rewriting manifests

---

core/src/test/java/org/apache/iceberg/TestWapWorkflow.java

* remove unsued vars
* remove commented code
* fix comments

TestWapWorkflow cleanup

---

core/src/main/java/org/apache/iceberg/hadoop/HadoopTableOperations.java

This fixes #970. The problem happens when a table is updated concurrently in two processes and one process has multiple threads accessing the same `Table` instance. The multi-threaded process starts to commit and validates that its base `TableMetadata` is correct (e.g., version 8), the other process completes a commit to the table (version 9). In the process that is still committing, another thread refreshes the table causing the `version` to be updated (version 9). When committer writes its new `TableMetadata`, it will commit the wrong version (version 10) and the commit will succeed.
The solution here is to ensure that version and metadata are accessed together using synchronized private methods, so there is no way to get metadata that doesn't correspond to the version, and so there is …

Fix Hadoop commit race condition

---

data/src/main/java/org/apache/iceberg/data/DateTimeUtil.java

Add reverse functions:
From LocalDate / LocalTime / LocalDateTime / OffsetDateTime
To long / int

Add reverse functions to DateTimeUtil

---

spark/src/test/java/org/apache/iceberg/spark/source/TestSparkTableUtil.java

allow managed table creation even if location exists in Test

---

python/iceberg/api/expressions/expression_parser.py
python/iceberg/api/expressions/expressions.py
python/setup.py
python/tests/api/expressions/test_str_to_expr.py

Cleaning up the dependency on moz_sql_parser and instead relying on pyparsing directly.
cc: @danielcweeks @rdblue

Removing dependency on moz_sql_parser

---

.travis.yml
python/README.md
python/iceberg/api/io/closeable_iterable.py
python/iceberg/api/partition_spec.py
python/iceberg/api/types/type_util.py
python/iceberg/core/avro/avro_to_iceberg.py
python/iceberg/core/base_metastore_tables.py
python/iceberg/core/data_files.py
python/iceberg/core/filesystem/s3_filesystem.py
python/iceberg/core/scan_summary.py
python/setup.py
python/tests/api/expressions/conftest.py
python/tox.ini

- Rename `next` to `__next__`
- Fix indentation
- Fix faulty string formatting

Add Flake8 to the CI

---

parquet/src/main/java/org/apache/iceberg/parquet/RemoveIds.java
parquet/src/test/java/org/apache/iceberg/parquet/TestParquetSchemaUtil.java

This is a follow-up for https://github.com/apache/iceberg/pull/830#issuecomment-645495768.

Fix parquet name mapping unit test

---

core/src/main/java/org/apache/iceberg/data/avro/DataReader.java
core/src/main/java/org/apache/iceberg/data/avro/DataWriter.java
flink/src/main/java/org/apache/iceberg/flink/data/FlinkAvroReader.java
flink/src/main/java/org/apache/iceberg/flink/data/FlinkAvroWriter.java
flink/src/test/java/org/apache/iceberg/flink/data/RandomData.java
flink/src/test/java/org/apache/iceberg/flink/data/TestFlinkAvroReaderWriter.java
flink/src/test/java/org/apache/iceberg/flink/data/TestRowProjection.java

I implemented the flink avro reader writer, also raise the issue https://github.com/apache/iceberg/issues/1152. Please take a look, @rdblue . 
Thanks in advance.

Flink: Add Avro value reader, writer implementations

---

site/docs/spark.md

Add some sample code for how to inspect tables by HDFS path.

Add Inspecting tables example by HDFS path in the Iceberg User docs

---

spark/src/main/java/org/apache/iceberg/actions/BaseAction.java
spark2/src/test/java/org/apache/iceberg/actions/TestRemoveOrphanFilesAction.java

I fixed the problem by doing some debugging and modifying some of the code.
Isuues url:[1160](https://github.com/apache/iceberg/issues/1160)

Fix errors when use removeOrphanFiles By HadoopCatalog

---

.gitignore

Per suggestion, open a new PR to add gitignore items

add git ignore items

---

core/src/test/java/org/apache/iceberg/TestRemoveSnapshots.java

This is an easy PR, no Prod code changes, just improves test coverage :)
Previously none of the tests in TestRemoveSnapshots used the code path for
valid snapshots which contained references to manifests which were created
in a snapshot that had previously expired. Although there are no bugs in that
logic, we add two tests which check this pathway to protect against future
breakage.

Adds Tests for Untested RemoveSnapshot Pathway

---

core/src/main/java/org/apache/iceberg/avro/GenericAvroReader.java
core/src/main/java/org/apache/iceberg/avro/ValueReaders.java
core/src/main/java/org/apache/iceberg/data/avro/DataReader.java
spark/src/main/java/org/apache/iceberg/spark/data/SparkAvroReader.java

Extract `ValueReaders.decimalBytesReader` for reusing code.

avro: Extract ValueReaders.decimalBytesReader

---

.baseline/checkstyle/checkstyle.xml
build.gradle
spark3/src/main/java/org/apache/iceberg/spark/Spark3Util.java
spark3/src/main/java/org/apache/iceberg/spark/SparkCatalog.java

Fixes accidental Guava imports and adds new relocations to the checkstyle ban.

Fix Guava imports

---

core/src/main/java/org/apache/iceberg/BaseCombinedScanTask.java
spark/src/test/java/org/apache/iceberg/TestScanTaskSerialization.java
spark/src/test/java/org/apache/iceberg/actions/TestRewriteDataFilesAction.java
spark2/src/test/java/org/apache/iceberg/TestScanTaskSerialization24.java
spark3/src/test/java/org/apache/iceberg/TestScanTaskSerialization3.java

This patch is spin-off version of #1280 which excludes refactoring, to be included in bugfix version release.

Core: fix serialization issue in BaseCombinedScanTask with Kyro (No refactor)

---

data/src/test/java/org/apache/iceberg/data/TestLocalScan.java

This fixes #https://github.com/apache/iceberg/issues/1262.

Generics: Refactor TestLocalScan

---

parquet/src/main/java/org/apache/iceberg/parquet/ParquetUtil.java
spark2/src/test/java/org/apache/iceberg/spark/source/TestSparkTableUtilWithInMemoryCatalog.java

We fail while importing existing Parquet tables with INT96 timestamps as `ParquetConversions.fromParquetPrimitive` assumes the value is long. Since INT96 metrics are unreliable, I propose to ignore them.
```
java.lang.ClassCastException: org.apache.iceberg.shaded.org.apache.parquet.io.api.Binary$ByteArrayBackedBinary cannot be cast to java.lang.Long
at org.apache.iceberg.parquet.ParquetConversions.fromParquetPrimitive(ParquetConversions.java:48)
at org.apache.iceberg.parquet.ParquetUtil.footerMetrics(ParquetUtil.java:133)
at org.apache.iceberg.spark.SparkTableUtil.lambda$listParquetPartition$8(SparkTableUtil.java:426)
at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
at …
```

Parquet: Ignore INT96 metrics while importing tables

---

python/iceberg/api/tables.py
python/iceberg/api/types/type.py
python/iceberg/core/__init__.py
python/iceberg/core/base_metastore_tables.py
python/iceberg/core/base_transaction.py
python/iceberg/core/filesystem/filesystem_tables.py
python/iceberg/core/filesystem/local_filesystem.py
python/iceberg/core/table_metadata.py
python/iceberg/hive/hive_table_operations.py
python/iceberg/hive/hive_tables.py
python/iceberg/hive/hive_types.py
python/tests/core/conftest.py
python/tests/core/test_filesystem_tables.py
python/tests/hive/test_hive_tables.py

First step in write support for python.
Adds support & tests for create on:
* `HiveTables`
* `FilesystemTables`

[Python] create table support

---

build.gradle
versions.props

There aren't any Joda references in the code.

Remove Joda test dependency

---

api/src/main/java/org/apache/iceberg/UpdateSchema.java
core/src/main/java/org/apache/iceberg/SchemaUpdate.java
core/src/main/java/org/apache/iceberg/schema/SchemaWithPartnerVisitor.java
core/src/main/java/org/apache/iceberg/schema/UnionByNameVisitor.java
core/src/test/java/org/apache/iceberg/TestSchemaUnionByFieldName.java

Continues on (most) the work done by @rdsr on https://github.com/apache/iceberg/pull/759

Add schema upsert API for adding new fields and updating type (where applicable) using an input schema

---

mr/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergFilterFactory.java

fix TestHiveIcebergFilterFactory.testDateType failed due to timezone dependent

---

site/docs/spark.md
spark/src/main/java/org/apache/iceberg/spark/IcebergSpark.java
spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSpark.java
spark2/src/test/java/org/apache/iceberg/spark/source/TestIcebergSpark24.java
spark3/src/test/java/org/apache/iceberg/spark/source/TestIcebergSpark3.java

Closes #1520 
This PR documents how to write against partitioned table in Spark, as there doesn't look to be documented somewhere, and it's not a no-brainer thing to deal with.
Screenshot of 230650d is follow:

ISSUE-1520 Document writing against partitioned table in Spark

---

spark3/src/main/java/org/apache/iceberg/spark/source/SparkBatchScan.java

Spark creates a "canonicalized" plan to determine whether two plan trees produce the same result. If two trees produce the same result, then Spark will reuse shuffle data to reduce the number of stages. In DSv2, the equality of Spark's `BatchScanExec` depends on the equality of the `Scan` produced by sources.
This implements `equals` and `hashCode` in `SparkBatchScan` so that the canonicalized plan is equal when scans are equivalent.

Spark: Implement equals and hashCode in SparkBatchScan

---

mr/src/test/java/org/apache/iceberg/mr/TestCatalogs.java

Issue: https://github.com/apache/iceberg/issues/1534

Hive: fix temporary folder location and cleanup in TestCatalogs

---

data/src/test/java/org/apache/iceberg/data/DeleteReadTests.java
spark/src/main/java/org/apache/iceberg/spark/source/BaseDataReader.java

This dedups the DeleteFiles in ReadTask, because a single DeleteFile can be referred by multiple DataFile for filtering. Fixes issue https://github.com/apache/iceberg/issues/1511
cc: @rdblue

Issue-1511: Read errors out with multiple DeleteFile entries after UPSERT

---

core/src/main/java/org/apache/iceberg/TableMetadata.java
core/src/test/java/org/apache/iceberg/TestTableMetadata.java

This adds a method to update a `TableMetadata` with a new `SortOrder`. There is no operation that uses this, but it can be used directly for testing.

Add TableMetadata.updateSortOrder

---

build.gradle
mr/src/test/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandlerBaseTest.java

Similar in spirit to: https://github.com/apache/iceberg/pull/1570

Run Hive StorageHandler tests for Avro as well

---

spark2/src/jmh/java/org/apache/iceberg/spark/data/parquet/SparkParquetReadersFlatDataBenchmark.java
spark2/src/jmh/java/org/apache/iceberg/spark/data/parquet/SparkParquetReadersNestedDataBenchmark.java
spark2/src/jmh/java/org/apache/iceberg/spark/data/parquet/SparkParquetWritersFlatDataBenchmark.java
spark2/src/jmh/java/org/apache/iceberg/spark/data/parquet/SparkParquetWritersNestedDataBenchmark.java
spark2/src/jmh/java/org/apache/iceberg/spark/source/avro/IcebergSourceFlatAvroDataReadBenchmark.java
spark2/src/jmh/java/org/apache/iceberg/spark/source/avro/IcebergSourceNestedAvroDataReadBenchmark.java
spark2/src/jmh/java/org/apache/iceberg/spark/source/orc/IcebergSourceFlatORCDataReadBenchmark.java
spark2/src/jmh/java/org/apache/iceberg/spark/source/orc/IcebergSourceNestedORCDataReadBenchmark.java
spark2/src/jmh/java/org/apache/iceberg/spark/source/parquet/IcebergSourceFlatParquetDataFilterBenchmark.java
spark2/src/jmh/java/org/apache/iceberg/spark/source/parquet/IcebergSourceFlatParquetDataReadBenchmark.java
spark2/src/jmh/java/org/apache/iceberg/spark/source/parquet/IcebergSourceFlatParquetDataWriteBenchmark.java
spark2/src/jmh/java/org/apache/iceberg/spark/source/parquet/IcebergSourceNestedParquetDataFilterBenchmark.java
spark2/src/jmh/java/org/apache/iceberg/spark/source/parquet/IcebergSourceNestedParquetDataReadBenchmark.java
spark2/src/jmh/java/org/apache/iceberg/spark/source/parquet/IcebergSourceNestedParquetDataWriteBenchmark.java
spark2/src/jmh/java/org/apache/iceberg/spark/source/parquet/vectorized/VectorizedReadDictionaryEncodedFlatParquetDataBenchmark.java
spark2/src/jmh/java/org/apache/iceberg/spark/source/parquet/vectorized/VectorizedReadFlatParquetDataBenchmark.java

This addresses the issue in https://github.com/apache/iceberg/pull/1522#issuecomment-707164336.

fix jmh benchmark issue and update doc

---

flink/src/main/java/org/apache/iceberg/flink/CatalogLoader.java
flink/src/main/java/org/apache/iceberg/flink/FlinkCatalogFactory.java
flink/src/test/java/org/apache/iceberg/flink/FlinkCatalogTestBase.java
flink/src/test/java/org/apache/iceberg/flink/FlinkTestBase.java
flink/src/test/java/org/apache/iceberg/flink/TestCatalogTableLoader.java
flink/src/test/java/org/apache/iceberg/flink/TestFlinkCatalogDatabase.java
flink/src/test/java/org/apache/iceberg/flink/TestFlinkCatalogTable.java
flink/src/test/java/org/apache/iceberg/flink/TestFlinkHiveCatalog.java
flink/src/test/java/org/apache/iceberg/flink/TestFlinkTableSink.java
flink/src/test/java/org/apache/iceberg/flink/source/TestFlinkInputFormatReaderDeletes.java
hive-metastore/src/main/java/org/apache/iceberg/hive/HiveCatalog.java
site/docs/flink.md

This patch will address the comment: https://github.com/apache/iceberg/pull/1558#issuecomment-707097927.

Flink: support specifying user-provided hive-site.xml for hive catalog.

---

api/src/main/java/org/apache/iceberg/expressions/InclusiveMetricsEvaluator.java
api/src/main/java/org/apache/iceberg/expressions/ManifestEvaluator.java
api/src/test/java/org/apache/iceberg/expressions/TestInclusiveMetricsEvaluator.java
data/src/test/java/org/apache/iceberg/data/TestMetricsRowGroupFilter.java
parquet/src/main/java/org/apache/iceberg/parquet/ParquetMetricsRowGroupFilter.java

This PR fixes the IN predicate performance using hard-coded values.
Resolves #1588.

Fix IN predicate performance

---

dev/source-release.sh

This PR fixes `source-release.sh`.

Build: Fix source-release.sh

---

site/docs/api.md
site/docs/configuration.md
site/docs/evolution.md
site/docs/flink.md
site/docs/getting-started.md
site/docs/hive.md
site/docs/java-api-quickstart.md
site/docs/maintenance.md
site/docs/reliability.md
site/docs/schemas.md
site/docs/spark-structured-streaming.md
site/docs/spark.md
site/docs/spec.md
site/docs/terms.md

update configuration.md link

---

core/src/main/java/org/apache/iceberg/SnapshotManager.java

Fixes #1693
See https://github.com/apache/iceberg/pull/1677#discussion_r514097825 for details.

Core: Fix possible NPE issue in SnapshotManager.validateCurrentSnapshot

---

spark3/src/main/java/org/apache/iceberg/spark/source/SparkTable.java
spark3/src/test/java/org/apache/iceberg/spark/sql/TestDeleteFrom.java

This PR optimizes the case when the delete condition evaluates to false.

Spark: Skip DELETE if the condition is false

---

core/src/main/java/org/apache/iceberg/CachingCatalog.java
core/src/test/java/org/apache/iceberg/hadoop/TestCachingCatalog.java

This PR fixes the invalidation of metadata tables when the main table is dropped from the catalog.

Core: Fix invalidation of metadata tables in CachingCatalog

---

core/src/main/java/org/apache/iceberg/RemoveSnapshots.java
core/src/main/java/org/apache/iceberg/TableProperties.java
core/src/test/java/org/apache/iceberg/TestRemoveSnapshots.java
spark/src/main/java/org/apache/iceberg/actions/ExpireSnapshotsAction.java
spark/src/main/java/org/apache/iceberg/actions/RemoveOrphanFilesAction.java
spark/src/test/java/org/apache/iceberg/actions/TestExpireSnapshotsAction.java
spark/src/test/java/org/apache/iceberg/actions/TestRemoveOrphanFilesAction.java

This PR adds a table property to disable garbage collection.

Core: Add table property to disable garbage collection

---

spark3/src/main/java/org/apache/iceberg/spark/source/SparkBatchQueryScan.java
spark3/src/main/java/org/apache/iceberg/spark/source/SparkBatchScan.java
spark3/src/main/java/org/apache/iceberg/spark/source/SparkMergeScan.java
spark3/src/main/java/org/apache/iceberg/spark/source/SparkScanBuilder.java

This PR adds a Spark scan for DELETE/UPDATE/MERGE operations.

Spark: Add SparkMergeScan

---

mr/src/test/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandlerBaseTest.java

Introduce additional testcases to cover scenarios involving complex types and embedded complex types.

Test out complex stuctures: MAP/LIST/STRUCT

---

spark3/src/main/java/org/apache/spark/sql/connector/iceberg/catalog/ExtendedSupportsDelete.java
spark3/src/main/java/org/apache/spark/sql/connector/iceberg/catalog/SupportsMerge.java
spark3/src/main/java/org/apache/spark/sql/connector/iceberg/read/SupportsFileFilter.java
spark3/src/main/java/org/apache/spark/sql/connector/iceberg/write/MergeBuilder.java

This PR adds APIs to support DELETE/UPDATE/MERGE operations in Spark.

Spark: Add connector APIs for DELETE/UPDATE/MERGE

---

site/docs/hive.md

This pull request fixes some minor typos and grammatical issues in hive.md.

Fix some spelling/grammar issues in hive.md

---

spark3-extensions/src/main/scala/org/apache/spark/sql/catalyst/analysis/ResolveProcedures.scala
spark3/src/main/java/org/apache/spark/sql/connector/iceberg/catalog/ProcedureParameterImpl.java

This PR fixes validation of optional args in procedures.

Spark: Fix optional argument validation in procedures

---

spark3-extensions/src/main/scala/org/apache/spark/sql/catalyst/parser/extensions/IcebergSqlExtensionsAstBuilder.scala
spark3-extensions/src/main/scala/org/apache/spark/sql/catalyst/plans/logical/statements.scala
spark3/src/main/java/org/apache/iceberg/spark/procedures/CherrypickSnapshotProcedure.java
spark3/src/main/java/org/apache/iceberg/spark/procedures/RewriteManifestsProcedure.java
spark3/src/main/java/org/apache/iceberg/spark/procedures/RollbackToSnapshotProcedure.java
spark3/src/main/java/org/apache/iceberg/spark/procedures/RollbackToTimestampProcedure.java
spark3/src/main/java/org/apache/iceberg/spark/procedures/SetCurrentSnapshotProcedure.java
spark3/src/main/java/org/apache/spark/sql/connector/iceberg/catalog/Procedure.java
spark3/src/main/java/org/apache/spark/sql/connector/iceberg/catalog/ProcedureCatalog.java
spark3/src/main/java/org/apache/spark/sql/connector/iceberg/catalog/ProcedureParameter.java
spark3/src/main/java/org/apache/spark/sql/connector/iceberg/catalog/ProcedureParameterImpl.java

This PR adds Javadoc for stored procedure API.

Spark: Add Javadoc for stored procedure API

---

core/src/main/java/org/apache/iceberg/PartitionData.java
flink/src/main/java/org/apache/iceberg/flink/FlinkCatalog.java
flink/src/main/java/org/apache/iceberg/flink/FlinkCatalogFactory.java
flink/src/test/java/org/apache/iceberg/flink/FlinkCatalogTestBase.java
flink/src/test/java/org/apache/iceberg/flink/TestFlinkCatalogTablePartitions.java

Flink : add list partitions for FlinkCatalog

---

mr/src/test/java/org/apache/iceberg/mr/hive/TestHiveShell.java

Hive: Flaky test testScanTable org.apache.iceberg.mr.hive.TestHiveIcebergStorageHandlerWithCustomCatalog (#1817)

---

core/src/main/java/org/apache/iceberg/util/StructLikeMap.java
core/src/test/java/org/apache/iceberg/util/TestStructLikeMap.java

This is a separate PR for https://github.com/apache/iceberg/pull/1818/files#diff-0d33a480c6c61ed9b4adaf5715a2ef66ca2eb7d3c999328166e7870851e35589R31

Core: Add utility StructLikeMap.

---

hive-metastore/src/main/java/org/apache/iceberg/hive/HiveCatalog.java
hive-metastore/src/test/java/org/apache/iceberg/hive/HiveTableTest.java

only list iceberg tables for HiveCatalog listTables method

---

core/src/main/java/org/apache/iceberg/RemoveSnapshots.java
core/src/main/java/org/apache/iceberg/TableProperties.java
core/src/test/java/org/apache/iceberg/TestRemoveSnapshots.java
site/docs/configuration.md

This PR adds table properties for snapshot retention.

Core: Add table properties for snapshot retention

---

flink/src/main/java/org/apache/iceberg/flink/data/FlinkParquetReaders.java
flink/src/test/java/org/apache/iceberg/flink/source/TestFlinkInputFormat.java

This fixes an NPE that when projecting out the timestamp type.

Flink: fix projection NPE caused by timestamp type

---

spark2/src/test/java/org/apache/iceberg/examples/SchemaEvolutionTest.java

Refactor Spark schema evolution tests
- Avoid init of Sparksession for every tests
- Data correctness check
- Refactors

Refactor Spark schema evolution tests 

---

spark/src/main/java/org/apache/iceberg/spark/source/BaseDataReader.java

Make it easier to find out exactly which file was being read when we encountered an error either opening the task or when reading rows from the task
Heres an example of how it looks now
```
Exception: Error reading file: hdfs://namenode/table/path/part-r-00001.orc
at org.apache.iceberg.spark.source.BaseDataReader.next(BaseDataReader.java:97)
at org.apache.spark.sql.execution.datasources.v2.DataSourceRDD$$anon$1.hasNext(DataSourceRDD.scala:49)
at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
at …
```

Spark: Print file location in case of error during reads

---

arrow/src/main/java/org/apache/iceberg/arrow/vectorized/VectorizedArrowReader.java
spark/src/test/java/org/apache/iceberg/spark/data/TestSparkParquetReadMetadataColumns.java

This was caught by Ryan, here is to update the unit test to expose the bug.

Parquet: fix vectorized position reader

---

site/docs/hive.md

This pull request fixes some minor typos in hive.md.

Fix some spelling issues in hive.md

---

flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSink.java

The apache flink's build-in testing utility [FiniteTestSource](https://github.com/apache/flink/blob/master/flink-test-utils-parent/flink-test-utils/src/main/java/org/apache/flink/streaming/util/FiniteTestSource.java#L85)  will emit the row list twice by default,  that means the expected results will occur twice.  Thought it works but increase a bit complexity. 
After  https://github.com/apache/iceberg/pull/1974/files,  we've introduced a simple [BoundedTestSource](https://github.com/apache/iceberg/pull/1974/files#diff-44b67dbf8c1de58ea2453b4aa026560ae400c15f4f1bf6668c9dc608e03b4f86R39),  it's better to replace `FiniteTestSource` with `BoundedTestSource` .

Flink: Replace FiniteTestSource with BoundedTestSource.

---

flink/src/test/java/org/apache/iceberg/flink/FlinkCatalogTestBase.java
flink/src/test/java/org/apache/iceberg/flink/TestFlinkCatalogDatabase.java
flink/src/test/java/org/apache/iceberg/flink/TestFlinkCatalogTable.java
flink/src/test/java/org/apache/iceberg/flink/TestFlinkCatalogTablePartitions.java
flink/src/test/java/org/apache/iceberg/flink/TestFlinkTableSink.java
flink/src/test/java/org/apache/iceberg/flink/TestFlinkTableSource.java
flink/src/test/java/org/apache/iceberg/flink/actions/TestRewriteDataFilesAction.java

Address the issue https://github.com/apache/iceberg/issues/1541.

Flink: Use Namespace in the parameterized args.

---

flink/src/test/java/org/apache/iceberg/flink/TestFlinkCatalogTable.java
site/docs/flink.md

add create table like test case for flink

Flink : add create table like test case for flink

---

site/docs/configuration.md
site/docs/spark.md
spark/src/main/java/org/apache/iceberg/spark/SparkReadOptions.java
spark/src/main/java/org/apache/iceberg/spark/SparkWriteOptions.java
spark/src/test/java/org/apache/iceberg/spark/source/TestDataFrameWrites.java
spark/src/test/java/org/apache/iceberg/spark/source/TestDataSourceOptions.java
spark/src/test/java/org/apache/iceberg/spark/source/TestIdentityPartitionData.java
spark/src/test/java/org/apache/iceberg/spark/source/TestPartitionPruning.java
spark/src/test/java/org/apache/iceberg/spark/source/TestPartitionValues.java
spark/src/test/java/org/apache/iceberg/spark/source/TestSnapshotSelection.java
spark/src/test/java/org/apache/iceberg/spark/source/TestSparkDataWrite.java
spark/src/test/java/org/apache/iceberg/spark/source/TestSparkReadProjection.java
spark/src/test/java/org/apache/iceberg/spark/source/TestWriteMetricsConfig.java
spark2/src/jmh/java/org/apache/iceberg/spark/source/orc/IcebergSourceFlatORCDataReadBenchmark.java
spark2/src/jmh/java/org/apache/iceberg/spark/source/orc/IcebergSourceNestedORCDataReadBenchmark.java
spark2/src/main/java/org/apache/iceberg/spark/source/IcebergSource.java
spark2/src/main/java/org/apache/iceberg/spark/source/Reader.java
spark2/src/main/java/org/apache/iceberg/spark/source/Writer.java
spark2/src/test/java/org/apache/iceberg/spark/source/TestFilteredScan.java
spark3/src/main/java/org/apache/iceberg/spark/Spark3Util.java
spark3/src/main/java/org/apache/iceberg/spark/source/SparkBatchQueryScan.java
spark3/src/main/java/org/apache/iceberg/spark/source/SparkMergeScan.java
spark3/src/main/java/org/apache/iceberg/spark/source/SparkWrite.java
spark3/src/main/java/org/apache/iceberg/spark/source/SparkWriteBuilder.java
spark3/src/test/java/org/apache/iceberg/spark/source/TestFilteredScan.java

Refactor Spark DF read and Write options

Refactor Spark DF read and Write options

---

core/src/main/java/org/apache/iceberg/BaseTable.java
core/src/main/java/org/apache/iceberg/BaseTableScan.java
core/src/main/java/org/apache/iceberg/ScanSummary.java
core/src/main/java/org/apache/iceberg/actions/BaseRewriteDataFilesAction.java
core/src/main/java/org/apache/iceberg/io/BaseTaskWriter.java
core/src/main/java/org/apache/iceberg/io/PartitionedWriter.java
spark3/src/main/java/org/apache/iceberg/spark/source/IcebergSource.java
spark3/src/main/java/org/apache/iceberg/spark/source/SparkBatchScan.java
spark3/src/main/java/org/apache/iceberg/spark/source/SparkMergeBuilder.java

While working on https://github.com/apache/iceberg/pull/1972 I've noticed that there are a lot of warnings in the output. This PR fixes the low hanging fruit to reduce the noise.

Fix small issues

---

mr/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java

There were some remaining small issues during the review of #1917.
The fixes are here.

Fixes for remaining issues in #1917

---

build.gradle
hive-runtime/LICENSE
hive-runtime/NOTICE

This PR adds Nessie to the Flink runtime. Compliments #1895

add Nessie to flink runtime

---

api/src/main/java/org/apache/iceberg/Accessors.java

We need some comments to explain the purpose here. otherwise it's a bit hard to understand.

Add comments for Position2Accessor and Position3Accessor

---

mr/src/main/java/org/apache/iceberg/mr/InputFormatConfig.java
mr/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergOutputFormat.java
mr/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergSerDe.java
mr/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
mr/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergOutputCommitter.java
mr/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerWithEngine.java
mr/src/test/java/org/apache/iceberg/mr/hive/TestTables.java

The PR contains the final changes for the first implementation of Hive writes. Also contains some tests for checking the functionality.

Hive: Implementation for INSERT INTO Iceberg backed Hive tables using the new HiveIcebergRecordWriter

---

api/src/main/java/org/apache/iceberg/PartitionSpec.java
api/src/main/java/org/apache/iceberg/transforms/Dates.java
api/src/main/java/org/apache/iceberg/transforms/Timestamps.java
api/src/main/java/org/apache/iceberg/transforms/Transform.java
api/src/test/java/org/apache/iceberg/TestPartitionSpecValidation.java

Improve partition spec builder to prevent adding duplicate identity partition fields.

Improve partition spec builder

---

site/mkdocs.yml

New year, new copyright footer.

[DOCS] Update copyright years in doc footers to include 2021

---

core/src/main/java/org/apache/iceberg/TableProperties.java
spark3-extensions/src/main/scala/org/apache/spark/sql/catalyst/expressions/AccumulateFiles.scala
spark3-extensions/src/main/scala/org/apache/spark/sql/catalyst/optimizer/RewriteMergeInto.scala
spark3-extensions/src/main/scala/org/apache/spark/sql/catalyst/plans/logical/DynamicFileFilter.scala
spark3-extensions/src/main/scala/org/apache/spark/sql/catalyst/utils/RewriteRowLevelOperationHelper.scala
spark3-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/DynamicFileFilterExec.scala
spark3-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/ExtendedDataSourceV2Strategy.scala
spark3-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMergeIntoTable.java

This PR updates some minor places in the cardinality check for MERGE.

Spark: Minor refactoring for the cardinality check in MERGE

---

site/docs/evolution.md
site/docs/partitioning.md
site/docs/spark.md

1. add spark SQL for partition and sort order update
2. add a section for sort order evolution

Doc: add partition spec and sort order evolution doc

---

flink/src/main/java/org/apache/iceberg/flink/FlinkCatalog.java
flink/src/test/java/org/apache/iceberg/flink/TestFlinkCatalogDatabase.java
flink/src/test/java/org/apache/iceberg/flink/TestFlinkCatalogTable.java

This will address bug from here: https://github.com/apache/iceberg/issues/2133

Flink: Support SQL 'IF EXISTS' and 'IF NOT EXISTS'

---

README.md
site/docs/index.md

Update README and documentation references for Trino

---

site/docs/configuration.md
site/docs/flink.md

This address the issue: https://github.com/apache/iceberg/issues/2136

Docs: Add new flink features for release 0.11.0

---

spark3-extensions/src/main/scala/org/apache/spark/sql/catalyst/expressions/TransformExpressions.scala
spark3-extensions/src/main/scala/org/apache/spark/sql/catalyst/utils/DistributionAndOrderingUtils.scala
spark3-extensions/src/main/scala/org/apache/spark/sql/catalyst/utils/RewriteRowLevelOperationHelper.scala
spark3-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMergeIntoTable.java

Truncate transform support was missing in the first cut. This PR adds the support.

Add truncate transform support for MERGE INTO 

---

core/src/main/java/org/apache/iceberg/CatalogUtil.java
core/src/test/java/org/apache/iceberg/TestCatalogErrorConstructor.java
core/src/test/java/org/apache/iceberg/TestCatalogUtil.java

Improved error messages in CatalogUtil.loadCatalog

---

site/docs/blogs.md
site/mkdocs.yml

@cwsteinbach as discussed in slack, here is the blog page, please let me know if I missed anything. There are also some old ones, and talks from Ryan and Anton that I did not include here, not sure if they should be included or not.

Doc: add blog page

---

spark3/src/test/java/org/apache/iceberg/actions/TestCreateActions.java

- Adding more tests for migrate action

More tests for migrate action

---

spark3-extensions/src/main/scala/org/apache/spark/sql/catalyst/optimizer/RewriteMergeInto.scala
spark3-extensions/src/main/scala/org/apache/spark/sql/catalyst/plans/logical/MergeInto.scala
spark3-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/MergeIntoExec.scala

This is a minor PR that tries to address [comment](https://github.com/apache/iceberg/pull/2116#discussion_r560426572)

[MINOR] Negate sourceRow and targetRow presence conditions for readability

---

spark3-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestDelete.java

This PR adds more tests with multiple subqueries in DELETE. Previously, some tests defined two views but used only one.

Spark: Add more tests with multiple subqueries in DELETE

---

spark3-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMerge.java

This PR brings more tests for MERGE operations in Spark. In particular, tests with self subqueries, isolation level tests, null handling, updating a single row group in a file with multiple row groups.

Spark: Add more tests for MERGE

---

spark/src/test/java/org/apache/iceberg/spark/source/TestDataSourceOptions.java

Previously this test assumed that a record would always be 611 bytes and the
file created by the test would have roughly twice that many bytes. When parquet
versions are changed this test will be broken (We tested this with an internal build of Parquet).
Instead we now write a single file and divide that file size in two to guarantee only 2 partitions will exist if the
test property is correctly applied.

Change Datasource Option Test to not Rely on Hardcoded File Size

---

spark/src/main/java/org/apache/iceberg/spark/source/BatchDataReader.java
spark3-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestUpdate.java

This PR fixes vectorized reads with metadata columns in ORC. Previously, we tried to read `_pos` column from files and could not build a correct projection as `_pos` was not in the file.

ORC: Fix vectorized reads with metadata columns

---

spark3-extensions/src/main/scala/org/apache/spark/sql/catalyst/expressions/TransformExpressions.scala

This PR moves our transform expressions to use `UnaryExpression` and `nullSafeEval`.

Spark: Use nullSafeEval in transform expressions

---

core/src/main/java/org/apache/iceberg/ManifestFiles.java
core/src/test/java/org/apache/iceberg/TableTestBase.java
core/src/test/java/org/apache/iceberg/TestManifestReader.java

Add position in manifest to DeleteFile's unit test.

Core: Add DeleteManifest position unit test.

---

site/docs/python-api-intro.md
site/docs/python-feature-support.md

Update python docs

---

spark/src/main/java/org/apache/iceberg/actions/BaseSnapshotUpdateSparkAction.java
spark/src/main/java/org/apache/iceberg/actions/BaseSparkAction.java
spark/src/main/java/org/apache/iceberg/actions/ExpireSnapshotsAction.java
spark/src/main/java/org/apache/iceberg/actions/RemoveOrphanFilesAction.java
spark/src/main/java/org/apache/iceberg/actions/RewriteManifestsAction.java

This PR refactors `BaseSparkAction` and prepares it for upcoming changes.

Spark: Refactor BaseSparkAction

---

core/src/main/java/org/apache/iceberg/hadoop/HadoopCatalog.java
flink/src/main/java/org/apache/iceberg/flink/CatalogLoader.java

Follow on from #2203
cc @aokolnychyi

Deprecate and remove uses of hadoop catalog constructors

---

hive-metastore/src/test/java/org/apache/iceberg/hive/TestHiveClientPool.java

#2075 Introduced a new test which broke the master codeline.

Fix broken TestHiveClientPool

---

core/src/main/java/org/apache/iceberg/actions/BaseRemoveOrphanFilesActionResult.java
spark/src/main/java/org/apache/iceberg/actions/Actions.java
spark/src/main/java/org/apache/iceberg/actions/RemoveOrphanFilesAction.java
spark/src/main/java/org/apache/iceberg/spark/actions/BaseRemoveOrphanFilesSparkAction.java

This PR moves the action for removing orphan files to use the V2 interface.

Spark: Refactor action for removing orphan files

---

spark/src/main/java/org/apache/iceberg/spark/actions/BaseExpireSnapshotsSparkAction.java
spark/src/main/java/org/apache/iceberg/spark/actions/BaseRemoveOrphanFilesSparkAction.java
spark/src/main/java/org/apache/iceberg/spark/actions/BaseRewriteManifestsSparkAction.java
spark/src/main/java/org/apache/iceberg/spark/actions/BaseSnapshotUpdateSparkAction.java
spark/src/main/java/org/apache/iceberg/spark/actions/BaseSparkAction.java

This PR moves base Spark actions to the correct new package.

Spark: Move base actions to new package

---

core/src/main/java/org/apache/iceberg/GenericManifestFile.java
flink/src/test/java/org/apache/iceberg/flink/TestHelpers.java
flink/src/test/java/org/apache/iceberg/flink/TestManifestFileSerialization.java
flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkManifest.java
flink/src/test/java/org/apache/iceberg/flink/sink/TestIcebergFilesCommitter.java

This fix the issue: https://github.com/apache/iceberg/issues/2346

Flink: Fix the manifest kryo serialization issue.

---

site/docs/nessie.md
site/mkdocs.yml

Add a page to explain the Nessie Catalog

Add nessie documentation

---

flink/src/test/java/org/apache/iceberg/flink/SimpleDataUtil.java
flink/src/test/java/org/apache/iceberg/flink/TestFlinkTableSink.java
flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSink.java

This address the issue https://github.com/apache/iceberg/issues/2384.

Tests: Fix the flaky testHashDistributeMode

---

core/src/main/java/org/apache/iceberg/BaseMetastoreCatalog.java

Core: Fix circular call in BaseMetastoreCatalog

---

site/docs/aws.md

Because of many asks such as #2168 I got recently for using AWS module with Flink, I am adding a section for Flink integration. I also made the scripts more generic for Spark and Flink.

Doc: add AWS Flink usage details

---

spark3/src/main/java/org/apache/iceberg/actions/Spark3MigrateAction.java

This PR moves the backing up and restoring logic in the migrate action into separate methods to simplify `doExecute`.

Spark: Refactor backing up and restoring logic in migrate action

---

hive-metastore/src/main/java/org/apache/iceberg/hive/HiveCatalog.java

Remove literal false boolean value

Remove literal false boolean value

---

spark3/src/main/java/org/apache/iceberg/spark/source/IcebergSource.java

fixes #2423
cc @aokolnychyi @rdblue

Remove createParquetAsIceberg as default in IcebergSource

---

spark3/src/main/java/org/apache/iceberg/actions/Spark3MigrateAction.java
spark3/src/main/java/org/apache/iceberg/actions/Spark3SnapshotAction.java

This PR adds more logging to the snapshot and migrate actions. These actions are usually tricky operations and having as much logs as possible helped us in the past.

Spark: Refine logging in snapshot and migrate actions

---

core/src/main/java/org/apache/iceberg/io/WriteResult.java
flink/src/main/java/org/apache/iceberg/flink/sink/IcebergFilesCommitter.java
flink/src/test/java/org/apache/iceberg/flink/sink/TestIcebergFilesCommitter.java

a draft for adding a  commit idle time config

[FLINK]add max idle time  config to prevent too frequent for empty commit

---

mr/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergOutputFormat.java
mr/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerWithEngine.java

Following up on https://github.com/apache/iceberg/issues/2440

Hive: Capitalize write format value when creating writer

---

mr/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerNoScan.java
mr/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerWithEngine.java

Hive: Fix compilation failure in TestHiveIcebergStorageHandlerNoScan and TestHiveIcebergStorageHandlerWithEngine

---

.github/workflows/java-ci.yml
build.gradle
spark3-extensions/src/main/scala/org/apache/spark/sql/catalyst/parser/extensions/IcebergSparkSqlExtensionsParser.scala
spark3-extensions/src/main/scala/org/apache/spark/sql/catalyst/parser/extensions/IcebergSqlExtensionsAstBuilder.scala
spark3-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestCallStatementParser.java
spark3-runtime/src/integration/java/org/apache/iceberg/spark/SmokeTest.java

Fix our issue with Antlr Shadowing and add an integration test which checks to make sure that the Spark3 Runtime Jar works. 
Addresses #2382

Fix Antlr Shadowing and add Integration Tests

---

site/docs/performance.md

fix #2476 
update accessible pdf url

[Site][Doc] fix performance pdf url

---

spark/src/main/java/org/apache/iceberg/spark/actions/BaseSparkActions.java
spark2/src/main/java/org/apache/iceberg/spark/actions/SparkActions.java
spark3/src/main/java/org/apache/iceberg/spark/actions/SparkActions.java

This PR adds new entry points for the redesigned actions API in Spark.

Spark: Add new entry point for actions

---

spark/src/main/java/org/apache/iceberg/spark/SparkWriteOptions.java
spark3/src/main/java/org/apache/iceberg/spark/FileRewriteCoordinator.java
spark3/src/main/java/org/apache/iceberg/spark/source/SparkRewriteBuilder.java
spark3/src/main/java/org/apache/iceberg/spark/source/SparkTable.java
spark3/src/main/java/org/apache/iceberg/spark/source/SparkWrite.java
spark3/src/test/java/org/apache/iceberg/spark/TestFileRewriteCoordinator.java

This PR adds `SparkRewriteBuilder` for rewriting a set of files.

Spark: Add SparkRewriteBuilder for rewriting a set of files

---

build.gradle
flink-runtime/LICENSE
flink-runtime/NOTICE

Note: updates the flink notice+license files, as #2032 updated the hive notice-license files ;)

add Nessie to Hive runtime

---

spark/src/main/java/org/apache/iceberg/spark/actions/BaseExpireSnapshotsSparkAction.java
spark/src/main/java/org/apache/iceberg/spark/actions/BaseRemoveOrphanFilesSparkAction.java
spark/src/main/java/org/apache/iceberg/spark/actions/BaseRewriteManifestsSparkAction.java
spark3/src/main/java/org/apache/iceberg/spark/actions/BaseMigrateTableSparkAction.java
spark3/src/main/java/org/apache/iceberg/spark/actions/BaseSnapshotTableSparkAction.java

Add Spark UI description to Iceberg jobs

---

spark3/src/main/java/org/apache/iceberg/spark/Spark3Util.java
spark3/src/test/java/org/apache/iceberg/spark/TestSpark3Util.java

For https://github.com/apache/iceberg/issues/2526

Fix the typo in the list method of DescribeSchemaVisitor in Spark3Util

---

api/src/main/java/org/apache/iceberg/transforms/ProjectionUtil.java

@rdblue Hi, I read the code and found the comment in ProjectionUtil#fixInclusiveTimeProjection might be incorrect. Would you have a look please?

API: Fix typo in ProjectionUtil

---

api/src/main/java/org/apache/iceberg/transforms/PartitionSpecVisitor.java
spark3-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestAlterTablePartitionFields.java
spark3/src/main/java/org/apache/iceberg/spark/Spark3Util.java

A quick fix for the issue https://github.com/apache/iceberg/issues/2453

Fix describing v1 table with void transform partitions.

---

parquet/src/main/java/org/apache/iceberg/parquet/Parquet.java
parquet/src/main/java/org/apache/iceberg/parquet/ParquetDictionaryRowGroupFilter.java
parquet/src/test/java/org/apache/iceberg/parquet/TestDictionaryRowGroupFilter.java

Filtering dictionary encoded FIX_LEN_BYTE_ARRAY

---

nessie/src/main/java/org/apache/iceberg/nessie/NessieCatalog.java

Adds `Tasks.onFailure((c, exception) -> refresh())` to `NessieCatalog.dropTable` +
`renameTable`.
Also refactors the use of the deprecated Nessie `ContentsApi.deleteContents()` to
`TreeAPi.commitMultipleOperations`.

Let NessieCatalog handle HttpClientException and clean up retry-handling

---

core/src/main/java/org/apache/iceberg/actions/BaseAction.java

Use the the ReachableUtil methods in BaseAction

Clean-up base action

---

python/iceberg/api/types/conversions.py
python/tests/api/test_conversions.py

Update to_byte_buff_mapping and from_byte_buff_mapping to be consistent and add additional tests.

[Python] Update to_byte_buff_mapping and from_byte_buff_mapping

---

site/docs/flink.md

Modify the Flink variable name from the doc

Docs: Modify the Flink variable name from the doc

---

data/src/main/java/org/apache/iceberg/data/orc/GenericOrcReaders.java

Constant variable EPOCH and EPOCH_DAY are never used, we should remove them

[Data][Minor] remove useless code

---

api/src/main/java/org/apache/iceberg/util/CharSequenceSet.java
api/src/test/java/org/apache/iceberg/util/TestCharSequenceSet.java
core/src/main/java/org/apache/iceberg/BaseRowDelta.java
core/src/main/java/org/apache/iceberg/ManifestFilterManager.java
core/src/main/java/org/apache/iceberg/MergingSnapshotProducer.java
core/src/main/java/org/apache/iceberg/deletes/PositionDeleteWriter.java
core/src/main/java/org/apache/iceberg/io/BaseTaskWriter.java
core/src/main/java/org/apache/iceberg/io/SortedPosDeleteWriter.java
core/src/main/java/org/apache/iceberg/io/WriteResult.java
data/src/test/java/org/apache/iceberg/data/DeleteReadTests.java
data/src/test/java/org/apache/iceberg/data/FileHelpers.java
data/src/test/java/org/apache/iceberg/data/TestDataFileIndexStatsFilters.java

This should fix the ErrorProne issue https://errorprone.info/bugpattern/CollectionUndefinedEquality

Use CharSequenceSet instead of Set<CharSequence> to avoid undefined equality check behavior

---

arrow/src/main/java/org/apache/iceberg/arrow/vectorized/ArrowReader.java
flink/src/main/java/org/apache/iceberg/flink/source/DataIterator.java
spark/src/main/java/org/apache/iceberg/spark/source/BaseDataReader.java

This is a follow-up from https://github.com/apache/iceberg/pull/2286/files#r638280456
/cc @rdblue since you reviewed the original code, maybe you could review this one as well?

Use bulk decryption interface in ArrowReader

---

flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java

Flink: Add an optional uidPrefix to FlinkSink#Builder to explicitly set operator uid.

---

api/src/main/java/org/apache/iceberg/actions/RewriteDataFiles.java
api/src/main/java/org/apache/iceberg/actions/RewriteStrategy.java
core/src/main/java/org/apache/iceberg/actions/BinPackStrategy.java
core/src/test/java/org/apache/iceberg/actions/TestBinPackStrategy.java

Changes to support the implementation of the Spark RewriteDatafileAciton. Fixes JavaDoc links,
adds in BinPackStrategy comments to better binpack real world usecases.

Bin pack strategy cosmetic changes

---

site/docs/flink.md

alter 'fromHadooptable'  to 'fromHadoopTable'

Docs: Fix typo in flink.md

---

hive-metastore/src/main/java/org/apache/iceberg/hive/CachedClientPool.java

Delete blank line  of CachedClientPool.java

---

site/docs/spec.md

This updates the change summary for format v2 at the end of the spec.

Update v2 change summary

---

core/src/main/java/org/apache/iceberg/jdbc/JdbcUtil.java

look https://github.com/apache/iceberg/issues/2744

Core: Fix JdbcCatalog CATALOG_TABLE_NAME to lowercase

---

site/docs/aws.md
site/docs/evolution.md
site/docs/spark-structured-streaming.md

Docs: Fixes broken links to old spark doc page

---

site/docs/blogs.md

Apache Iceberg - An Architectural Look Under the Covers

Docs:  Add new blog - Apache Iceberg: An Architectural Look Under the Covers

---

site/docs/blogs.md

Add blog from 6/8/21 by Tencent to the blog page.

Add Tencent blog

---

README.md

Doc: update README local build instructions

---

api/src/main/java/org/apache/iceberg/Schema.java
core/src/main/java/org/apache/iceberg/SchemaUpdate.java
core/src/test/java/org/apache/iceberg/TestSchemaUpdate.java
flink/src/test/java/org/apache/iceberg/flink/TestFlinkSchemaUtil.java

moved validateIdentifierField to Schema and do validation inside constructor
Closes https://github.com/apache/iceberg/issues/2940
cc: @jackye1995

Move Identifier field validation to Schema class

---

dev/source-release.sh

Add command line options for the following:
* Specifying the keyId of the key to use for signing
* Setting the name of the Git remote for staging the release
* Enabling DEBUG output
Improve the progress messages printed to STDOUT.

Miscellaneous improvements to source-release.sh

---

site/docs/blogs.md

(CC @bitsondatadev)
Great blogs, Brian!

Add Starburst blog series

---

site/docs/flink.md

for flink document, enhance the package info in shell script

Flink: shell enhancement

---

flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java

Flink: Fix the warning in FlinkSink

---

site/docs/releases.md

I found a misspelling of a word and corrected it

Fix spelling mistakes in releases.md

---

core/src/test/java/org/apache/iceberg/hadoop/TestHadoopCatalog.java

Core: Fix comment in TestHadoopCatalog

---

site/docs/spark-writes.md

I found the doc's lack of `UPDATE` queries on spark3. And I added it.

Docs: Add UPDATE describtion for spark3.

---

python_legacy/README.md

Update README in python_legacy module to have renamed folder name

---

spark3/src/main/java/org/apache/iceberg/spark/source/SparkWrite.java

This PR changes `SparkWrite` to directly use `FileWriter` for unpartitioned writes.

Spark: Use FileWriter for unpartitioned writes

---

README.md

Just went to the old slack space.  Update the link to the latest.

Infra: update slack address

---

README.md
site/docs/spec.md

updated gradle version in ReadMe and version details in spec.

Doc: Update ReadMe and Spec

---

aliyun/src/test/java/org/apache/iceberg/aliyun/oss/AliyunOSSTestUtility.java
aliyun/src/test/java/org/apache/iceberg/aliyun/oss/mock/TestLocalAliyunOSS.java

make configurable testrule  to implement both local and remote aliyun oss test

Aliyun: Add configurable TestRule.

---

arrow/src/main/java/org/apache/iceberg/arrow/vectorized/ArrowReader.java
arrow/src/test/java/org/apache/iceberg/arrow/vectorized/ArrowReaderTest.java

Follow-up on https://github.com/apache/iceberg/pull/2933.
+ @nastra

[ARROW] Vectorized Parquet Reads - Make ArrowReader's iterator idempotent

---

site/docs/maintenance.md

I'm not sure if this is the _correct_ fix though 🤷

Typo in the docs - or at least I think it is

---

api/src/main/java/org/apache/iceberg/TableScan.java
api/src/main/java/org/apache/iceberg/types/IndexByName.java
api/src/main/java/org/apache/iceberg/types/TypeUtil.java
core/src/main/java/org/apache/iceberg/AllDataFilesTable.java
core/src/main/java/org/apache/iceberg/AllEntriesTable.java
core/src/main/java/org/apache/iceberg/AllManifestsTable.java
core/src/main/java/org/apache/iceberg/BaseAllMetadataTableScan.java
core/src/main/java/org/apache/iceberg/BaseMetadataTable.java
core/src/main/java/org/apache/iceberg/BaseMetadataTableScan.java
core/src/main/java/org/apache/iceberg/BaseTableScan.java
core/src/main/java/org/apache/iceberg/DataFilesTable.java
core/src/main/java/org/apache/iceberg/DataTableScan.java
core/src/main/java/org/apache/iceberg/ManifestEntriesTable.java
core/src/main/java/org/apache/iceberg/StaticTableScan.java
spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/Spark3Util.java
spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/SparkConfParser.java
spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/SparkFilters.java
spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/SparkReadConf.java
spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/SparkSchemaUtil.java
spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/SparkBatchQueryScan.java
spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/TestSparkFilters.java
spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/source/TestRuntimeFiltering.java

This PR adds support for dynamic partition filtering in 3.2.

Spark: Support dynamic partition filtering in 3.2

---

spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/SparkWriteConf.java
spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/SparkWriteOptions.java

add overwrite-mode to SparkWriteOptions as a constant

Add overwrite-mode to SparkWriteOptions as a constant

---

nessie/src/main/java/org/apache/iceberg/nessie/NessieCatalog.java
nessie/src/main/java/org/apache/iceberg/nessie/NessieTableOperations.java
nessie/src/test/java/org/apache/iceberg/nessie/TestNessieTable.java

NessieCatalog: Improve Commit Messages

---

arrow/src/main/java/org/apache/iceberg/arrow/vectorized/NullabilityHolder.java
arrow/src/main/java/org/apache/iceberg/arrow/vectorized/VectorizedArrowReader.java
arrow/src/main/java/org/apache/iceberg/arrow/vectorized/VectorizedReaderBuilder.java
spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkMetadataColumns.java

This PR fixes the vectorized position reader. Previously, it would give wrong results if multiple batches were read.

Arrow: Fix vectorized position reader

---

core/src/main/java/org/apache/iceberg/deletes/Deletes.java

CharSeqComparator is a bit of overkill to know whether two file paths are different. It also performances not well. The PR introduces a new method for the use case with better perf.
Perf tests have been done for the new method comparing to class `CharSeqComparator`. 
1. Compare two identical paths. The new method is about 18 times faster than `CharSeqComparator.compare`
2. Compare two paths with different lengths. The new method is about 17 times faster.
3. Compare two path with the same length but different chars inside. The new method is about 13 times faster.
FYI, here is the code I used for perf tests.
```
@Test
public void testCharSeqEqualsVsComparatorWithSamePath() {
// the same CharSeq
String suffix = "parquet"; // to prevent generating the same object.
CharSequence s5 = …
```

Core: Introduce a CharSeq equals method for faster file path filtering

---

spark/v3.0/spark/src/main/java/org/apache/iceberg/spark/IcebergSpark.java
spark/v3.0/spark/src/main/java/org/apache/iceberg/spark/SparkValueConverter.java
spark/v3.0/spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSpark.java

Port of #3368 to Spark 3.0.
Fix is due to Chen Zhang (@izchen).

Spark 3.0: Fix ClassCastException when using bucket UDF

---

spark/v2.4/spark/src/main/java/org/apache/iceberg/spark/IcebergSpark.java
spark/v2.4/spark/src/main/java/org/apache/iceberg/spark/SparkValueConverter.java
spark/v2.4/spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSpark.java

Port of #3368 to Spark 2.4.
Fix is due to Chen Zhang (@izchen).

Spark 2.4: Fix ClassCastException when using bucket UDF

---

api/src/main/java/org/apache/iceberg/io/FileIO.java
core/src/test/java/org/apache/iceberg/TestIncrementalDataTableScan.java
core/src/test/java/org/apache/iceberg/TestSplitPlanning.java
data/src/test/java/org/apache/iceberg/io/TestAppenderFactory.java
data/src/test/java/org/apache/iceberg/io/TestBaseTaskWriter.java
data/src/test/java/org/apache/iceberg/io/TestFileWriterFactory.java
data/src/test/java/org/apache/iceberg/io/TestGenericSortedPosDeleteWriter.java
data/src/test/java/org/apache/iceberg/io/TestPartitioningWriters.java
data/src/test/java/org/apache/iceberg/io/TestPositionDeltaWriters.java
data/src/test/java/org/apache/iceberg/io/TestRollingFileWriters.java
data/src/test/java/org/apache/iceberg/io/TestTaskEqualityDeltaWriter.java
flink/v1.13/flink/src/test/java/org/apache/iceberg/flink/TestFlinkCatalogTable.java
flink/v1.13/flink/src/test/java/org/apache/iceberg/flink/TestFlinkCatalogTablePartitions.java
flink/v1.13/flink/src/test/java/org/apache/iceberg/flink/TestFlinkTableSink.java
flink/v1.13/flink/src/test/java/org/apache/iceberg/flink/actions/TestRewriteDataFilesAction.java
flink/v1.13/flink/src/test/java/org/apache/iceberg/flink/sink/TestDeltaTaskWriter.java
flink/v1.13/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkV2.java
flink/v1.13/flink/src/test/java/org/apache/iceberg/flink/sink/TestIcebergFilesCommitter.java
flink/v1.13/flink/src/test/java/org/apache/iceberg/flink/source/TestStreamScanSql.java
mr/src/test/java/org/apache/iceberg/mr/hive/TestTables.java
nessie/src/test/java/org/apache/iceberg/nessie/TestNessieTable.java
spark/v3.2/spark/src/jmh/java/org/apache/iceberg/spark/source/WritersBenchmark.java
spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/data/parquet/vectorized/TestParquetVectorizedReads.java

Just to reduce warnings output from the build.

Add missing @Override annotations

---

CONTRIBUTING.md

These are the guidelines that I repeat the most.

Docs: Update contributing with some additional Java style guidelines

---

api/src/main/java/org/apache/iceberg/DeleteFiles.java
api/src/main/java/org/apache/iceberg/expressions/StrictMetricsEvaluator.java
core/src/main/java/org/apache/iceberg/BaseOverwriteFiles.java
core/src/main/java/org/apache/iceberg/BaseRowDelta.java
core/src/main/java/org/apache/iceberg/ManifestFilterManager.java
core/src/main/java/org/apache/iceberg/MergingSnapshotProducer.java
core/src/main/java/org/apache/iceberg/StreamingDelete.java
core/src/test/java/org/apache/iceberg/TestDeleteFiles.java
core/src/test/java/org/apache/iceberg/TestOverwriteWithValidation.java
core/src/test/java/org/apache/iceberg/TestRowDelta.java

This PR adds support for case sensitivity in `MergingSnapshotProducer`.

Core: Support case sensitivity in MergingSnapshotProducer

---

spark/v3.1/spark/src/test/java/org/apache/iceberg/spark/sql/TestAlterTable.java

This PR is just for backporting #3683 to spark-3.1

Spark-3.1: Add test cases for alter column with complex types

---

spark/v3.0/spark/src/test/java/org/apache/iceberg/spark/sql/TestAlterTable.java

This PR is just for backporting #3683 to spark-3.0

Spark-3.0: Add test cases for alter column with complex types

---

spark/v3.2/spark-extensions/src/main/scala/org/apache/iceberg/spark/extensions/IcebergSparkSessionExtensions.scala
spark/v3.2/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/analysis/AlignRowLevelCommandAssignments.scala
spark/v3.2/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/analysis/AssignmentAlignmentSupport.scala
spark/v3.2/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/analysis/RewriteDeleteFromTable.scala
spark/v3.2/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/analysis/RewriteRowLevelCommand.scala
spark/v3.2/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/analysis/RewriteUpdateTable.scala
spark/v3.2/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/expressions/AssignmentUtils.scala
spark/v3.2/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/optimizer/ExtendedReplaceNullWithFalseInPredicate.scala
spark/v3.2/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/optimizer/ExtendedSimplifyConditionalsInPredicate.scala
spark/v3.2/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/parser/extensions/IcebergSparkSqlExtensionsParser.scala
spark/v3.2/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/planning/RewrittenRowLevelCommand.scala
spark/v3.2/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/plans/logical/UpdateIcebergTable.scala
spark/v3.2/spark-extensions/src/main/scala/org/apache/spark/sql/execution/dynamicpruning/RowLevelCommandDynamicPruning.scala
spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestUpdate.java
spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/SparkWriteConf.java
spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/SparkWriteBuilder.java

This PR implements copy-on-write UPDATE in Spark.

Spark: Implement copy-on-write UPDATE

---

CONTRIBUTING.md

Closes #3678
Added documentation about Iceberg config naming convention.

Docs: Added config naming

---

NOTICE
bundled-guava/NOTICE
flink/v1.12/flink-runtime/NOTICE
flink/v1.13/flink-runtime/NOTICE
flink/v1.14/flink-runtime/NOTICE
hive-runtime/NOTICE
python/NOTICE
spark/v2.4/spark-runtime/NOTICE
spark/v3.0/spark-runtime/NOTICE
spark/v3.1/spark-runtime/NOTICE
spark/v3.2/spark-runtime/NOTICE

Build: Update NOTICE to include copyright for 2022

---

baseline.gradle
spark/v3.0/build.gradle
spark/v3.1/build.gradle
spark/v3.2/build.gradle

Only apply scalastyle plugin for projects using the scala plugin

---

spark/v3.0/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/DynamicFileFilterExec.scala
spark/v3.0/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMerge.java
spark/v3.0/spark/src/main/java/org/apache/iceberg/spark/source/SparkMergeScan.java
spark/v3.0/spark/src/main/java/org/apache/spark/sql/connector/iceberg/read/SupportsFileFilter.java
spark/v3.0/spark/src/test/java/org/apache/iceberg/spark/SparkTestBase.java

**Add Spark UI metrics for merge into DynamicFileFilterExec:**
1. total number of files
2. number of files hit
3. file hit rate %
**Spark UI:**

Spark 3.0: Add Spark UI metrics for merge into DynamicFileFilterExec

---

spark/v3.1/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/DynamicFileFilterExec.scala
spark/v3.1/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMerge.java
spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/source/SparkMergeScan.java
spark/v3.1/spark/src/main/java/org/apache/spark/sql/connector/iceberg/read/SupportsFileFilter.java
spark/v3.1/spark/src/test/java/org/apache/iceberg/spark/SparkTestBase.java

Spark 3.1: Add Spark UI metrics for merge into DynamicFileFilterExec

---

spark/v3.2/spark-extensions/src/main/scala/org/apache/iceberg/spark/extensions/IcebergSparkSessionExtensions.scala
spark/v3.2/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/analysis/AlignRowLevelCommandAssignments.scala
spark/v3.2/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/analysis/CheckMergeIntoTableConditions.scala
spark/v3.2/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/analysis/MergeIntoIcebergTableResolutionCheck.scala
spark/v3.2/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/analysis/ResolveMergeIntoTableReferences.scala
spark/v3.2/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/analysis/RewriteMergeIntoTable.scala
spark/v3.2/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/optimizer/ExtendedReplaceNullWithFalseInPredicate.scala
spark/v3.2/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/optimizer/ExtendedSimplifyConditionalsInPredicate.scala
spark/v3.2/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/parser/extensions/IcebergSparkSqlExtensionsParser.scala
spark/v3.2/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/plans/logical/MergeIntoIcebergTable.scala
spark/v3.2/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/plans/logical/MergeRows.scala
spark/v3.2/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/plans/logical/UnresolvedMergeIntoIcebergTable.scala
spark/v3.2/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/ExtendedDataSourceV2Strategy.scala
spark/v3.2/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/MergeRowsExec.scala
spark/v3.2/spark-extensions/src/main/scala/org/apache/spark/sql/execution/dynamicpruning/RowLevelCommandDynamicPruning.scala
spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestCopyOnWriteMerge.java
spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMerge.java
spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/SparkWriteConf.java
spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/SparkWriteBuilder.java

This PR implements copy-on-write MERGE in Spark.

Spark: Implement copy-on-write MERGE

---

spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMerge.java

This PR adds missing tests for multiple NOT MATCHED clauses that are supported since Spark 3.1.

Spark 3.2: Add tests for multiple NOT MATCHED clauses

---

core/src/main/java/org/apache/iceberg/ManifestReader.java

Fix context classloader usage for avro reader

---

flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/TestHelpers.java
flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/TestTableSerialization.java

Port PR: https://github.com/apache/iceberg/pull/3857 to flink 1.14.

Flink 1.14: Fix SerializableTable with Kryo

---

flink/v1.12/flink/src/test/java/org/apache/iceberg/flink/TestHelpers.java
flink/v1.12/flink/src/test/java/org/apache/iceberg/flink/TestTableSerialization.java

Flink 1.12: Fix SerializableTable with Kryo

---

python_legacy/iceberg/api/partition_spec.py
python_legacy/iceberg/api/transforms/truncate.py

Resolving issue #3939 .  See issue for details.

Python: Fix type for partition_type struct fields (#3939)

---

spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/TestSparkDistributionAndOrderingUtil.java

This PR adds tests for copy-on-write MERGE distribution and ordering.

Spark 3.2: Add tests for copy-on-write MERGE distribution and ordering

---

spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/SparkBatchQueryScan.java
spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/source/TestRuntimeFiltering.java

Spark: Handle CaseSenstivity in runtimeFiltering of Spark

---

rest_docs/rest-catalog-open-api.yaml

This adds a 403 response to all of the REST API routes.

Spec: Add 403 response to REST API

---

spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/source/SparkWrite.java

Spark 3.1: Reports bytesWritten and recordsWritten to metrics

---

spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/SparkWrite.java

Spark 3.2: Reports bytesWritten and recordsWritten to metrics

---

spark/v3.0/spark/src/main/java/org/apache/iceberg/spark/source/SparkWrite.java

Spark 3.0: Reports bytesWritten and recordsWritten to metrics

---

python/tests/test_types.py

Follow-up PR to PR #4025 to auto-format another PR that was merged. @rdblue

Autoformat test_types.py with new line-length

---

core/src/main/java/org/apache/iceberg/io/BasePositionDeltaWriter.java
core/src/main/java/org/apache/iceberg/io/PositionDeltaWriter.java
data/src/test/java/org/apache/iceberg/io/TestPositionDeltaWriters.java
spark/v3.2/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/analysis/RewriteUpdateTable.scala
spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMergeOnReadUpdate.java
spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestUpdate.java
spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/SparkDistributionAndOrderingUtil.java
spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/SparkWriteConf.java
spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/SparkPositionDeltaWrite.java
spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/SparkPositionDeltaWriteBuilder.java
spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/SparkWriteBuilder.java
spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/TestSparkDistributionAndOrderingUtil.java

This PR implements merge-on-read UPDATE in Spark 3.2.

Spark 3.2: Implement merge-on-read UPDATE

---

CONTRIBUTING.md

Makes the code sample's intent embarrassingly clear.

Docs: Fix sample code in CONTRIBUTING.md

---

spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/SparkRowLevelOperationsTestBase.java
spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestUpdate.java

To demonstrate test fix idea for https://github.com/apache/iceberg/issues/4031

Fix random failure of TestCopyOnWriteUpdate::testUpdateWithoutCondition

---

CONTRIBUTING.md

Docs: update documentation contribution instructions

---

.github/labeler.yml
.github/workflows/flink-ci.yml
.github/workflows/hive-ci.yml
.github/workflows/java-ci.yml
.github/workflows/spark-ci.yml

Infra: exclude readme, contributing and gitattributes from CI

---

docs/common/project/multi-engine-support.md

Docs: add engine support start version and Flink 1.11 information

---

docs/common/project/how-to-release.md

@amogh-jahagirdar @samredai 
I've not tested the steps fully, I am just writing this based on what should be done, @amogh-jahagirdar can verify if anything here is not accurate.

Docs: add website release instruction

---

data/src/main/java/org/apache/iceberg/data/TableMigrationUtil.java

Previously, the executor service created for parallel reading of partitions in
TableMigrationUtil would only be claused when the finalizer was called. Instead in this
patch we close the service as soon as the method has completed.

Data: Close Migration ExecutorService if Started

---

docs/common/releases/release-notes.md
docs/versioned/releases/0.13.1/_index.md

Add 0.13.1 release notes (Note: Vote still in progress, this is just a PR to make sure the release notes are clear. Won't merge until vote is confirmed).
@pan3793 @coolderli @aokolnychyi let me know your thoughts on the release notes for the fixes!
@jackye1995 @rdblue

Docs: Add 0.13.1 release notes

---

core/src/main/java/org/apache/iceberg/SetSnapshotOperation.java

fixes the current build failure in master CI

Core: use setBranchSnapshot to commit SetSnapshotOperation

---

docs/versioned/spark/spark-procedures.md

Hoping that  the change of my commit is correct, Please take a look, Thanks
Edit by Russ: Closes #4134

Docs: Broken JavaDoc Links on Spark Procedures Page (#4134)

---

flink/v1.13/flink/src/main/java/org/apache/iceberg/flink/FlinkConfigOptions.java
flink/v1.13/flink/src/main/java/org/apache/iceberg/flink/source/FlinkInputFormat.java
flink/v1.13/flink/src/main/java/org/apache/iceberg/flink/source/FlinkInputSplit.java
flink/v1.13/flink/src/main/java/org/apache/iceberg/flink/source/FlinkSource.java
flink/v1.13/flink/src/main/java/org/apache/iceberg/flink/source/FlinkSplitGenerator.java
flink/v1.13/flink/src/main/java/org/apache/iceberg/flink/source/ScanContext.java
flink/v1.13/flink/src/test/java/org/apache/iceberg/flink/source/TestFlinkScanSql.java

port https://github.com/apache/iceberg/pull/3817 to Flink 1.13

Flink 1.13: Support HDFS locality with LocatableInputSplit

---

spark/v3.2/build.gradle

Spark 3.2.1 released few days ago, https://spark.apache.org/releases/spark-release-3-2-1.html

Build: Bump Spark 3.2.1

---

api/src/main/java/org/apache/iceberg/TableScan.java
core/src/main/java/org/apache/iceberg/AllDataFilesTable.java
core/src/main/java/org/apache/iceberg/AllEntriesTable.java
core/src/main/java/org/apache/iceberg/BaseTableScan.java
core/src/main/java/org/apache/iceberg/DataTableScan.java
core/src/main/java/org/apache/iceberg/IncrementalDataTableScan.java
core/src/main/java/org/apache/iceberg/PartitionsTable.java
core/src/main/java/org/apache/iceberg/TableScanContext.java
core/src/test/java/org/apache/iceberg/TestDataTableScan.java
core/src/test/java/org/apache/iceberg/TestIncrementalDataTableScan.java
core/src/test/java/org/apache/iceberg/TestMetadataTableScans.java

Support planning with particular executor for table scan

---

docs/common/format/spec.md

Lines 218 and 220 are duplicates.

Doc: Delete duplicate contents in spec

---

docs/versioned/tables/configuration.md

Modify configuration.md doc with read and write properties

Docs: modify the configuration.md

---

spark/v3.2/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/OptimizeMetadataOnlyDeleteFromTable.scala

It's not easy for users to know whether they are writing deletes that can be performed with just metadata, so adding this log line.
Example output from a unit test:
```
org.apache.spark.sql.execution.datasources.v2.OptimizeMetadataOnlyDeleteFromTable - Optimizing delete expression: IsNull(dep) as metadata delete
```

Add logging when optimizing delete to metadata-only-delete

---

api/src/main/java/org/apache/iceberg/SnapshotUpdate.java
core/src/main/java/org/apache/iceberg/BaseRewriteManifests.java
core/src/main/java/org/apache/iceberg/ManifestFilterManager.java
core/src/main/java/org/apache/iceberg/ManifestMergeManager.java
core/src/main/java/org/apache/iceberg/MergingSnapshotProducer.java
core/src/main/java/org/apache/iceberg/SnapshotProducer.java
core/src/test/java/org/apache/iceberg/TestMergeAppend.java
core/src/test/java/org/apache/iceberg/TestRewriteManifests.java

Support planning with particular executor for snapshots update

---

docs/versioned/api/python-api-intro.md

Docs: update python-api-intro.md

---

flink/v1.12/flink/src/test/java/org/apache/iceberg/flink/SimpleDataUtil.java
flink/v1.13/flink/src/test/java/org/apache/iceberg/flink/SimpleDataUtil.java
flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/SimpleDataUtil.java

Flink: Fix the testing utility SimpleDataUtil#snapshotToDataFiles

---

core/src/main/java/org/apache/iceberg/TableProperties.java

This PR removes deprecated table properties.

Core: Remove deprecated table properties

---

gradle/wrapper/gradle-wrapper.properties

docs:
https://docs.gradle.org/current/userguide/gradle_wrapper.html#configuring_checksum_verification
official checksums:
https://gradle.org/release-checksums/
other projects that also do this:
https://github.com/apache/kafka/blob/d8cf47bf28af0b5eb5be8382883e6a331b788e01/gradle/wrapper/gradle-wrapper.properties
https://github.com/apache/calcite/blob/cbbe5701b7f61d7f8df12d314ba5aabf898c1cae/gradle/wrapper/gradle-wrapper.properties

Build: verify integrity of gradle distribution

---

spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/actions/Spark3BinPackStrategy.java
spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteDataFilesAction.java

Previously, a rewrite between partition specs would fail as the rows from files in one spec
may actually belong to a different partition in the current spec. In this PR the partitioning
is updated via a range repartition if the destination spec does not match the origin spec.

Spark: Allow Bin-Pack Rewrite between Partition Specs

---

gradle/wrapper/gradle-wrapper.properties
gradlew

https://docs.gradle.org/7.4.1/release-notes.html

Build: Upgrade to Gradle 7.4.1

---

api/src/main/java/org/apache/iceberg/exceptions/ValidationException.java

I add the usage in javadoc of ValidationException.
Can you give me some suggestion if my description is not accurate.
thanks! @jackye1995

API:Add the usage in javadoc of ValidationException(#3895)

---

core/src/main/java/org/apache/iceberg/rest/ErrorHandlers.java

This adds a table error handler to the REST catalog `ErrorHandlers`.

Core: Add REST catalog table error handler

---

spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteDataFilesAction.java

Previously the overlap function would not correctly find overlaps when the bounds for
overlapping files were equivelent, or if a single file was returned. The new function
correctly only ignores files that are exactly the same (path and bounds) and throws an
error if overlaps are being checked for on a single file.

Spark: Fix Rewrite Overlap Test Function

---

format/spec.md

Docs: missing word: 'read-' to 'read-optimized'

---

orc/src/main/java/org/apache/iceberg/orc/ORC.java

A probable fix to 
Close https://github.com/apache/iceberg/issues/4383

ORC : Avoid modifying existing conf of HadoopOutputFile rather create new one

---

format/spec.md

This is based on a [mailing list thread](https://lists.apache.org/thread/n63h22y1zpg85wsxjf48o4mmjvc5c378) about file uniqueness

Docs: Clarify contract for file uniqueness

---

hive-metastore/src/main/java/org/apache/iceberg/hive/HiveCatalog.java
hive-metastore/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java
hive-metastore/src/main/java/org/apache/iceberg/hive/MetastoreUtil.java

Attempts to avoid recursive listing in HiveCatalog#renameTable
ref : https://github.com/apache/iceberg/pull/734#issuecomment-574062407
--- 
Closes https://github.com/apache/iceberg/issues/4406

Hive: Avoid recursive listing in HiveCatalog#renameTable

---

aliyun/src/main/java/org/apache/iceberg/aliyun/oss/BaseOSSFile.java
aliyun/src/main/java/org/apache/iceberg/aliyun/oss/OSSFileIO.java
aliyun/src/main/java/org/apache/iceberg/aliyun/oss/OSSInputFile.java
aliyun/src/main/java/org/apache/iceberg/aliyun/oss/OSSInputStream.java
aliyun/src/main/java/org/apache/iceberg/aliyun/oss/OSSOutputFile.java
aliyun/src/main/java/org/apache/iceberg/aliyun/oss/OSSOutputStream.java
aliyun/src/test/java/org/apache/iceberg/aliyun/oss/TestOSSInputFile.java
aliyun/src/test/java/org/apache/iceberg/aliyun/oss/TestOSSOutputFile.java
aliyun/src/test/java/org/apache/iceberg/aliyun/oss/TestOSSOutputStream.java

This PR adds metrics tracking for `OSSFileIO`. This would help reporting IO metrics via the Hadoop `FileSystem.Statistics`.
---
cc: @danielcweeks @rdblue @kbendick

Aliyun: Add metrics tracking for OSSFileIO

---

flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/TestHelpers.java
flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/source/TestFlinkScan.java

as @openinx metioned in https://github.com/apache/iceberg/pull/4432#issuecomment-1084003848

Flink: add test case for ReusableMapData

---

nessie/src/main/java/org/apache/iceberg/nessie/NessieCatalog.java
nessie/src/main/java/org/apache/iceberg/nessie/NessieUtil.java
nessie/src/test/java/org/apache/iceberg/nessie/TestCustomNessieClient.java

Nessie: Use config constants from public Nessie API

---

build.gradle
nessie/src/main/java/org/apache/iceberg/nessie/NessieTableOperations.java
nessie/src/test/java/org/apache/iceberg/nessie/TestNessieCatalog.java
nessie/src/test/java/org/apache/iceberg/nessie/TestNessieTable.java

currently depends on #4385 and #4333

Nessie: Add Catalog tests for NessieCatalog

---

gradle/wrapper/gradle-wrapper.properties
gradlew

https://docs.gradle.org/7.4.2/release-notes.html

Build: Upgrade to Gradle 7.4.2

---

spark/v2.4/spark/src/main/java/org/apache/iceberg/spark/source/Reader.java

Backports 
- https://github.com/apache/iceberg/pull/4446
to spark 2.4
---- 
cc @rdblue

Spark 2.x: Improve stats estimation for spark scan (backport #4446)

---

python/src/iceberg/io/pyarrow.py
python/src/iceberg/schema.py
python/tests/test_schema.py

This adds the logic for the `Schema.find_column_name` method as well as adds a few tests.

Add Schema.find_column_name method

---

docs/tables/evolution.md

fix typo in docs/tables/evolution.md.

fix typo in docs/tables/evolution.md

---

mr/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergFilterFactory.java

Delete Blank line in HiveIcebergFilterFactory

---

python/src/iceberg/expressions/base.py
python/tests/conftest.py
python/tests/expressions/test_expressions_base.py

This adds a generic accessor class and adds tests that use a test `FooStruct` and `FooAccessor`.

Add a generic Accessor class

---

nessie/src/main/java/org/apache/iceberg/nessie/NessieCatalog.java
nessie/src/main/java/org/apache/iceberg/nessie/UpdateableReference.java
spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/actions/TestCreateActions.java

Per project code style, Preconditions.checkNotNull should be used
instead.

Fix Objects.requireNonNull usages

---

python/src/iceberg/transforms.py
python/tests/test_transforms.py

To split the PR https://github.com/apache/iceberg/pull/3450, open a new PR for unknown transform here.

add UnknownTransform

---

nessie/src/main/java/org/apache/iceberg/nessie/NessieCatalog.java
nessie/src/main/java/org/apache/iceberg/nessie/NessieIcebergClient.java
nessie/src/test/java/org/apache/iceberg/nessie/TestNamespace.java
nessie/src/test/java/org/apache/iceberg/nessie/TestNessieCatalog.java

This requires https://github.com/apache/iceberg/pull/4594 in order for the failing tests to pass, thus I'll rebase the PR once #4595 is in

Nessie: Support Namespace properties

---

spark/v2.4/spark/src/main/java/org/apache/iceberg/spark/source/Writer.java
spark/v2.4/spark/src/test/java/org/apache/iceberg/spark/source/ManualSource.java
spark/v2.4/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkDataWrite.java
spark/v3.0/spark/src/main/java/org/apache/iceberg/spark/source/SparkWrite.java
spark/v3.0/spark/src/test/java/org/apache/iceberg/spark/source/ManualSource.java
spark/v3.0/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkDataWrite.java
spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/source/SparkWrite.java
spark/v3.1/spark/src/test/java/org/apache/iceberg/spark/source/ManualSource.java
spark/v3.1/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkDataWrite.java

Spark 3.X: Backport Fix CommitStateUnknown Handling (#4687)

---

flink/v1.13/flink/src/test/java/org/apache/iceberg/flink/TestFlinkTableSource.java
flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/TestFlinkTableSource.java

This backports https://github.com/apache/iceberg/pull/4697 to Flink 1.14 and 1.13.
Let me know if we'd prefer to use 2 PRs instead.

Flink: Backport flaky, order-dependent test for limit 1 query in TestFlinkTableSource

---

core/src/main/java/org/apache/iceberg/SnapshotProducer.java

`refresh()` updates `this.base`.

Remove redundant assignment

---

flink/v1.13/flink/src/main/java/org/apache/iceberg/flink/sink/BaseDeltaTaskWriter.java
flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/BaseDeltaTaskWriter.java
flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/sink/BaseDeltaTaskWriter.java

There seems to be an error in the comment of BaseDeltaTaskWriter.java

Flink: fix comment error in BaseDeltaTaskWriter.java

---

core/src/main/java/org/apache/iceberg/BaseTransaction.java
core/src/test/java/org/apache/iceberg/TestTransaction.java

This backports #4464 to the 0.13.x branch

[0.13] Core: Fix transaction retry logic (#4464)

---

api/src/main/java/org/apache/iceberg/PendingUpdate.java
spark/v2.4/spark/src/main/java/org/apache/iceberg/spark/source/Writer.java
spark/v2.4/spark/src/test/java/org/apache/iceberg/spark/source/ManualSource.java
spark/v2.4/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkDataWrite.java
spark/v3.0/spark/src/main/java/org/apache/iceberg/spark/source/SparkWrite.java
spark/v3.0/spark/src/test/java/org/apache/iceberg/spark/source/ManualSource.java
spark/v3.0/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkDataWrite.java
spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/source/SparkWrite.java
spark/v3.1/spark/src/test/java/org/apache/iceberg/spark/source/ManualSource.java
spark/v3.1/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkDataWrite.java
spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/SparkWrite.java
spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/source/ManualSource.java
spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkDataWrite.java

This backports #4687 and #4719 to the 0.13.x branch

[0.13] Spark commit unknown handling backports

---

.palantir/revapi.yml
api/src/main/java/org/apache/iceberg/Scan.java
api/src/main/java/org/apache/iceberg/TableScan.java
api/src/main/java/org/apache/iceberg/events/IncrementalScanEvent.java
api/src/test/java/org/apache/iceberg/TestHelpers.java
core/src/main/java/org/apache/iceberg/BaseIncrementalAppendScan.java
core/src/main/java/org/apache/iceberg/BaseScan.java
core/src/main/java/org/apache/iceberg/BaseTable.java
core/src/main/java/org/apache/iceberg/BaseTableScan.java
core/src/main/java/org/apache/iceberg/IncrementalDataTableScan.java
core/src/main/java/org/apache/iceberg/TableScanContext.java
core/src/main/java/org/apache/iceberg/util/SnapshotUtil.java
core/src/test/java/org/apache/iceberg/ScanTestBase.java
core/src/test/java/org/apache/iceberg/TestBaseIncrementalAppendScan.java
core/src/test/java/org/apache/iceberg/TestDataTableScan.java

this is a follow-up to PR #4580. will need to rebase this branch when 4580 is merged

Core: Incremental append scan impl

---

core/src/main/java/org/apache/iceberg/rest/HTTPClient.java
core/src/main/java/org/apache/iceberg/rest/RESTClient.java
core/src/main/java/org/apache/iceberg/rest/RESTSessionCatalog.java
core/src/test/java/org/apache/iceberg/catalog/CatalogTests.java
core/src/test/java/org/apache/iceberg/jdbc/TestJdbcCatalog.java
core/src/test/java/org/apache/iceberg/rest/RESTCatalogAdapter.java
core/src/test/java/org/apache/iceberg/rest/TestRESTCatalog.java

This implements support for passing a parent namespace to list.

Core: Implement namespace listing with a parent in REST catalog

---

orc/src/main/java/org/apache/iceberg/orc/OrcFileAppender.java

Because ORC has been updated, we can call method `estimateMemory` directly instead of reflection.
1. Use  memory evaluation methods in `Writer`

ORC: Upgrade orc version to use the built-in estimate memory method

---

dev/source-release.sh

Default is wrong on remote
Key values are not used

Dev: Release Script Fix

---

python/src/iceberg/conversions.py

Also add an annotation for mypy :)

Python: Decimal is actually DecimalType

---

python/CONTRIBUTING.md

Some instructions to get everyone up to speed with Poetry.

Python: Add Poetry IDEA instructions

---

python/src/iceberg/schema.py
python/src/iceberg/types.py
python/src/iceberg/utils/schema_conversion.py
python/tests/conftest.py
python/tests/expressions/test_expressions_base.py
python/tests/test_schema.py
python/tests/test_types.py
python/tests/utils/test_schema_conversion.py

See https://github.com/apache/iceberg/issues/4985

Python: Change Python API naming closer to the spec

---

README.md

https://github.com/masseguillaume/iceberg/tree/restore-logo#readme

Restore iceberg logo from previous commit

---

core/src/main/java/org/apache/iceberg/puffin/PuffinWriter.java

Call IOUtil.writeFully directly
Follow up to https://github.com/apache/iceberg/pull/4537#discussion_r898264496

Inline PuffinWriter.writeFully

---

format/puffin-spec.md

Follow up to https://github.com/apache/iceberg/pull/4537#discussion_r897618171

Fix type of fields list in Puffin

---

flink/v1.14/build.gradle
flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/source/enumerator/AbstractIcebergEnumerator.java
flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/source/enumerator/ContinuousIcebergEnumerator.java
flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/source/enumerator/IcebergEnumeratorPositionSerializer.java
flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/source/enumerator/IcebergEnumeratorState.java
flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/source/enumerator/IcebergEnumeratorStateSerializer.java
flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/source/enumerator/StaticIcebergEnumerator.java
flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/source/enumerator/TestContinuousIcebergEnumerator.java
flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/source/enumerator/TestIcebergEnumeratorStateSerializer.java
flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/source/enumerator/AbstractIcebergEnumerator.java
flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/source/enumerator/StaticIcebergEnumerator.java

also fixed a couple of style and comment in 1.15 code that was merged in PR #4986

Flink: Port PR #4986 (part 2 of FLIP-27 source enumerator) to 1.14 module

---

docs/hive.md

Original PR -> PR #4915
Co-authored-by: pvary pvary@cloudera.com

Docs: Update Hive doc page with the 4.0.0-alpha-1 features

---

python/pyiceberg/transforms.py
python/tests/test_transforms.py

This is being used by the partition-spec.

Python: Move Transforms to Pydantic

---

flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/source/IcebergSource.java
flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/source/ScanContext.java
flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/source/assigner/SimpleSplitAssigner.java
flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/source/enumerator/ContinuousSplitPlannerImpl.java
flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/SimpleDataUtil.java
flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/TestFixtures.java
flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/data/RowDataToRowMapper.java
flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/source/TestIcebergSourceBounded.java
flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/source/TestIcebergSourceContinuous.java
flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/source/TestIcebergSourceFailover.java
flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/source/TestIcebergSourceReaderDeletes.java

port #5109, FLIP-27 Iceberg source and builder to 1.14 module.

Flink: port #5109, FLIP-27 Iceberg source and builder to 1.14 module

---

docs/spark-queries.md

Document time travel introduced in spark 3.3
- spark jira : https://issues.apache.org/jira/browse/SPARK-37219
cc @samredai @pvary

Docs: Add time travel examples via SPARK-SQL

---

spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/actions/BaseDeleteOrphanFilesSparkAction.java
spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/actions/BaseDeleteReachableFilesSparkAction.java
spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/actions/BaseExpireSnapshotsSparkAction.java
spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/actions/BaseMigrateTableSparkAction.java
spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/actions/BaseRewriteDataFilesSparkAction.java
spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/actions/BaseRewriteManifestsSparkAction.java
spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/actions/BaseSnapshotTableSparkAction.java
spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/actions/BaseSnapshotUpdateSparkAction.java
spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/actions/BaseSparkAction.java
spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/actions/BaseTableCreationSparkAction.java
spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/actions/DeleteOrphanFilesSparkAction.java
spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/actions/DeleteReachableFilesSparkAction.java
spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/actions/ExpireSnapshotsSparkAction.java
spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/actions/MigrateTableSparkAction.java
spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/actions/RewriteDataFilesSparkAction.java
spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/actions/RewriteManifestsSparkAction.java
spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/actions/SnapshotTableSparkAction.java
spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/actions/SparkActions.java
spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/procedures/ExpireSnapshotsProcedure.java
spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/procedures/RemoveOrphanFilesProcedure.java
spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/procedures/RewriteManifestsProcedure.java
spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/actions/TestExpireSnapshotsAction.java
spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/actions/TestRemoveOrphanFilesAction.java
spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteDataFilesAction.java

A change similar to #5257 but for Spark 3.2.

Spark 3.2: Expose action classes in SparkActions

---

spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/SparkScanBuilder.java
spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/SparkScanBuilder.java

Log a warning when filter conversion/bind expression fail to address this comment https://github.com/apache/iceberg/pull/5227#discussion_r917098256

log warning when filter conversion/bind expression fail

---

mr/src/main/java/org/apache/iceberg/mr/Catalogs.java

typos depracated to deprecated

typos depracated to deprecated

---

spark/v3.0/spark/src/main/java/org/apache/iceberg/spark/SparkCatalog.java
spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/SparkCatalog.java
spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/SparkCatalog.java
spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/SparkCatalog.java

Spark: Correct SparkCatalog javadoc for supplying custom catalog

---

python/poetry.lock

Pin downstream dependencies to the latest version.

Python: Bump dependencies to the latest version

---

python/.pre-commit-config.yaml

Python: Bump pre-commit plugins to the latest version

---

python/pyiceberg/schema.py

Python: Remove unused function

---

aws/src/main/java/org/apache/iceberg/aws/s3/S3OutputStream.java

This PR fixes [issue #2796](https://github.com/apache/iceberg/issues/2796). It avoids invalid mark reset on retries by providing the input stream factory instead of original input stream to S3 API.
Root cause:
Currently, the underlying InputStream created from staging files is passed to S3 RequestBody and is reused by S3 client for every retry attempts; and S3 `mark` the underlying input stream with hard-coded of `read limit` of 128K at the beginning for once and `reset` it on every retry. In the case of a first attempt failed after reading more than 128K, the `mark` was invalidated because more than `read limit` amount of data has been read, and when then second attempt try to `reset` the invalidated mark, it breaks the mark/reset contract and throws exception with "Resetting to invalid …

AWS: Fix #2796 - avoid S3 error of "Resetting to invalid mark" by re-creating input stream on retries

---

aws/src/integration/java/org/apache/iceberg/aws/TestDefaultAwsClientFactory.java
aws/src/main/java/org/apache/iceberg/aws/AwsClientFactories.java
aws/src/main/java/org/apache/iceberg/aws/AwsProperties.java

Make glue endpoint configurable #5095

---

spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/SparkTableUtil.java

typo mulitple -> multiple

---

api/src/main/java/org/apache/iceberg/actions/DeleteOrphanFiles.java
spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRemoveOrphanFilesProcedure.java
spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/actions/DeleteOrphanFilesSparkAction.java
spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/actions/SetAccumulator.java
spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/procedures/RemoveOrphanFilesProcedure.java
spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/actions/TestRemoveOrphanFilesAction.java
spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/actions/TestRemoveOrphanFilesAction3.java

ICEBERG-4346: Better handling of Orphan files

---

format/spec.md

minor edit to fix the broken link.

Update spec.md to fix broken link to parquet-format/blob/master/LogicalTypes

---

python/pyiceberg/catalog/rest.py
python/tests/avro/test_resolver.py

Python: Add and cleanup tests

---

.palantir/revapi.yml
api/src/main/java/org/apache/iceberg/Scan.java
api/src/main/java/org/apache/iceberg/TableScan.java
core/src/main/java/org/apache/iceberg/BaseIncrementalAppendScan.java
core/src/main/java/org/apache/iceberg/BaseIncrementalChangelogScan.java
core/src/main/java/org/apache/iceberg/BaseIncrementalScan.java
core/src/main/java/org/apache/iceberg/BaseScan.java
core/src/main/java/org/apache/iceberg/BaseTable.java
core/src/main/java/org/apache/iceberg/BaseTableScan.java
core/src/main/java/org/apache/iceberg/DataTableScan.java
core/src/main/java/org/apache/iceberg/IncrementalDataTableScan.java
core/src/main/java/org/apache/iceberg/PartitionsTable.java
core/src/main/java/org/apache/iceberg/util/SnapshotUtil.java
core/src/test/java/org/apache/iceberg/ScanTestBase.java
core/src/test/java/org/apache/iceberg/TableTestBase.java
core/src/test/java/org/apache/iceberg/TestBaseIncrementalAppendScan.java
core/src/test/java/org/apache/iceberg/TestBaseIncrementalChangelogScan.java
core/src/test/java/org/apache/iceberg/TestDataTableScan.java

This PR implements `IncrementalChangelogScan` without support for delete files.

Core: Implement IncrementalChangelogScan without deletes

---

flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/source/IcebergSource.java
flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/source/reader/IcebergSourceReader.java
flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/source/reader/IcebergSourceSplitReader.java
flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/source/IcebergSource.java
flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/source/reader/IcebergSourceReader.java
flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/source/reader/IcebergSourceSplitReader.java

Flink: missed IcebergSourceReader group in PR #5393 for FLIP-27 source reader metrics

---

docs/flink-getting-started.md

update the address of Flink unit test in flink-getting-started.md.
--
sorry for creating another pr to solve this issue instead of  #5481, because it's my first pr of other project and I close pr of #5481 by force push, I will learn the process of modifying pr code now.

Doc: Update web page of Flink unit test (apache#5480)

---

python/pyiceberg/catalog/__init__.py
python/pyiceberg/catalog/hive.py

Follow up of https://github.com/apache/iceberg/pull/5465

Python: Fix docstring

---

spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/actions/BaseSparkAction.java
spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/actions/DeleteReachableFilesSparkAction.java
spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/actions/ExpireSnapshotsSparkAction.java
spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/actions/TestDeleteReachableFilesAction.java

This PR cherry-picks #5451 to Spark 3.2.

Spark 3.2: Count delete files in DeleteReachableFiles

---

python/pyiceberg/table/sorting.py
python/tests/table/test_sorting.py

This way it shows nicely in the CLI

Python: Add __str__ implementation to SortOrder and SortField

---

spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/SparkConfParser.java
spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/SparkWriteConf.java
spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/source/SparkWrite.java

Spark 3.1:Port #3721 to Spark 3.1
Split from #5479

Spark 3.1:Port #3721 to Spark 3.1

---

spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/actions/BaseDeleteOrphanFilesSparkAction.java
spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/actions/BaseDeleteReachableFilesSparkAction.java
spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/actions/BaseExpireSnapshotsSparkAction.java
spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/actions/BaseSparkAction.java

Spark 3.1:Port #4198 to Spark 3.1
Split from #5479

Spark 3.1:Port #4198 to Spark 3.1

---

spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/SparkWriteConf.java
spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/SparkWriteOptions.java

Spark 3.1:Port #3491 to Spark 3.1
Split from #5479

Spark 3.1:Port #3491 to Spark 3.1

---

spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/SparkSchemaUtil.java
spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/source/SparkBatchScan.java
spark/v3.1/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkMetadataColumns.java

Spark 3.1:Port #3456 to Spark 3.1
Split from #5479, after #5500.

Spark 3.1:Port #3456 to Spark 3.1

---

flink/v1.13/flink/src/main/java/org/apache/iceberg/flink/FlinkDynamicTableFactory.java
flink/v1.13/flink/src/main/java/org/apache/iceberg/flink/IcebergTableSink.java
flink/v1.13/flink/src/test/java/org/apache/iceberg/flink/TestFlinkUpsert.java
flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/FlinkDynamicTableFactory.java
flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/IcebergTableSink.java
flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/TestFlinkUpsert.java

Flink 1.13&1.14: Port #5050 to Flink 1.13&1.14

Flink 1.13&1.14: Port #5050 to Flink 1.13&1.14

---

python/.pre-commit-config.yaml

Python: Bump pre-commit to the latest version

---

python/pyiceberg/cli/output.py
python/tests/cli/test_console.py

Python: Write the column docs as well

---

api/src/main/java/org/apache/iceberg/metrics/Counter.java
api/src/main/java/org/apache/iceberg/metrics/DefaultCounter.java
api/src/main/java/org/apache/iceberg/metrics/DefaultMetricsContext.java
api/src/main/java/org/apache/iceberg/metrics/DefaultTimer.java
api/src/main/java/org/apache/iceberg/metrics/MetricsContext.java
api/src/main/java/org/apache/iceberg/metrics/ScanReport.java
api/src/main/java/org/apache/iceberg/metrics/Timer.java
api/src/test/java/org/apache/iceberg/metrics/TestDefaultCounter.java
api/src/test/java/org/apache/iceberg/metrics/TestDefaultMetricsContext.java
api/src/test/java/org/apache/iceberg/metrics/TestDefaultTimer.java
core/src/main/java/org/apache/iceberg/hadoop/HadoopMetricsContext.java
core/src/main/java/org/apache/iceberg/metrics/CounterResultParser.java
core/src/main/java/org/apache/iceberg/metrics/ScanMetricsResultParser.java
core/src/main/java/org/apache/iceberg/metrics/TimerResultParser.java
core/src/test/java/org/apache/iceberg/metrics/TestCounterResultParser.java
core/src/test/java/org/apache/iceberg/metrics/TestScanMetricsResultParser.java
core/src/test/java/org/apache/iceberg/metrics/TestTimerResultParser.java

This aligns the NOOP Timer's behavior with how the NOOP Counter behaves
(aka throwing an exception on value methods)

API: Remove counter name

---

spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/functions/BucketFunction.java
spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/functions/TruncateFunction.java

This PR aligns formatting in `TruncateFunction` and `BucketFunction` in Spark 3.3.

Spark 3.3: Align formatting in bucket and truncate functions

---

docs/flink-getting-started.md

Add upsert content to Flink doc.

Docs: Flink `Streaming upsert write`

---

python/pyiceberg/utils/bin_packing.py
python/tests/utils/test_bin_packing.py

Everyone loves types 👍🏻 
One class a day, so we can enable mypy `--strict` one day.

Python: Add types to bin packing

---

aws/src/integration/java/org/apache/iceberg/aws/glue/GlueTestBase.java
aws/src/integration/java/org/apache/iceberg/aws/glue/TestGlueCatalogTable.java
core/src/main/java/org/apache/iceberg/CatalogUtil.java

This change updates the implementation of dropping table data and metadata to use bulk delete if applicable.

Core: Use Bulk Delete when dropping table data and metadata

---

aliyun/src/main/java/org/apache/iceberg/aliyun/oss/OSSInputFile.java
aliyun/src/main/java/org/apache/iceberg/aliyun/oss/OSSInputStream.java

Moves public input/output streams to package visibility

Deprecations for 1.0 release: Aliyun OSS

---

python/poetry.lock
python/pyproject.toml

Currently it is missing:
```
root@88de3a02961f:/# pip install "git+https://github.com/apache/iceberg.git#subdirectory=python"
root@88de3a02961f:/# pyiceberg
Traceback (most recent call last):
File "/usr/local/bin/pyiceberg", line 5, in <module>
from pyiceberg.cli.console import run
File "/usr/local/lib/python3.9/site-packages/pyiceberg/cli/console.py", line 30, in <module>
from pyiceberg.catalog import Catalog, load_catalog
File "/usr/local/lib/python3.9/site-packages/pyiceberg/catalog/__init__.py", line 37, in <module>
from pyiceberg.utils.config import Config, merge_config
File "/usr/local/lib/python3.9/site-packages/pyiceberg/utils/config.py", line 21, in <module>
import yaml
ModuleNotFoundError: No module named 'yaml'
```

Python: Install PyYaml

---

spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/ChangelogRowReader.java
spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/source/TestChangelogReader.java

Cherry-pick #5578 to Spark3.2. cc @aokolnychyi

Spark 3.2: Add row-based changelog reader

---

gradle/wrapper/gradle-wrapper.properties
gradlew

See https://docs.gradle.org/7.5.1/release-notes.html
Upgraded by running the following command twice and manually
re-applying iceberg customizations:
./gradlew wrapper --gradle-version 7.5.1 --distribution-type bin

Build: Upgrade to Gradle 7.5.1

---

python/pyiceberg/catalog/hive.py

This way we can determine to load the correct FileIO

Python: Pass through the location for the FileIO

---

python/pyiceberg/io/__init__.py
python/pyiceberg/io/fsspec.py

Thanks for @fokko for identifying the fix :)

Python: fix FileIO fallback to pyarrow when s3fs not present.

---

docs/spark-queries.md

Add docs for snapshot references metadata table https://github.com/apache/iceberg/pull/4807
Proposal doc: [Link](https://docs.google.com/document/d/1tbATFPrKF3vNlzkgZQdaW8CAJmbjvryfrlg6C2Ci_aA/edit#heading=h.yxi0c6l48qw0)
---
cc: @rdblue @jackye1995 @amogh-jahagirdar

Docs: Add snapshot references metadata table

---

flink/v1.13/flink/src/main/java/org/apache/iceberg/flink/sink/IcebergStreamWriter.java
flink/v1.13/flink/src/test/java/org/apache/iceberg/flink/sink/TestIcebergStreamWriter.java

cc : @pvary @stevenzwu @kbendick

Flink: Fixed an issue where Flink1.13 batch entry was not accurate

---

aws/src/main/java/org/apache/iceberg/aws/glue/GlueCatalog.java
aws/src/main/java/org/apache/iceberg/aws/glue/GlueTableOperations.java

Preload S3 client in GlueCatalog when glueLakeFormationEnabled

AWS: Preload S3 client in GlueCatalog For LakeFormation enabled tables

---

python/pyiceberg/io/pyarrow.py
python/tests/io/test_io.py
python/tests/io/test_pyarrow.py

Open for feedback on the approach I'm taking here to make PyArrow parameterized with Properties similarly to FSSpec version.
@samredai @Fokko -- lots of issues with tests, but I think a big question I have is that many of the tests are directly constructing an InputFile or OutputFile instead of using the FileIO abstraction with new_input() and new_output()
Two main changes:
1) Allow pyarrow to interpret "s3a"
2) Pass through the properties object when creating the S3FileSystem

PyArrow support for S3/S3A with properties

---

api/src/main/java/org/apache/iceberg/expressions/ManifestEvaluator.java

API: Remove unneeded class variable
