apache/iceberg

- site/docs/spark-procedures.md
It doesn`t work when I use 'date_sub(current_date(), 10)' in 'spark_catalog.system.expire_snapshots'.
because we use a parser extension, the procedures do not allow arbitrary expressions.
I think that we'd better modify the document first to prevent users from encountering errors.
environment: 
|  Spark   | Iceberg |
|  ----  | ----  |
| 3.0  | 0.12|
```shell
scala> spark.sql("CALL spark_catalog.system.expire_snapshots('db.table', date_sub(current_date(), 10), 5)")
```
```shell
org.apache.spark.sql.catalyst.parser.extensions.IcebergParseException:
no viable alternative at input 'date_sub('(line 1, pos 81)
== SQL ==
CALL spark_catalog.system.expire_snapshots('db.table', date_sub(current_date(), 10), 5)
---------------------------------------------------------------------------------^^^
at …
```
> Docs: Fix date function in spark procedures docs

- .baseline/checkstyle/checkstyle.xml
- arrow/src/main/java/org/apache/iceberg/arrow/vectorized/VectorHolder.java
- spark/v3.0/spark/src/main/java/org/apache/iceberg/spark/procedures/BaseProcedure.java
- spark/v3.0/spark/src/main/java/org/apache/iceberg/spark/source/SparkMergeBuilder.java
- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/procedures/BaseProcedure.java
- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/source/SparkMergeBuilder.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/procedures/BaseProcedure.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/SparkMergeBuilder.java
add new checkstyle rules for unshaded Guava classes for recently introduced libraries. @kbendick
> Checkstyle: prevent using unshaded Guava classes in Arrow and AssertJ

- aws/src/main/java/org/apache/iceberg/aws/glue/GlueCatalog.java
- aws/src/test/java/org/apache/iceberg/aws/glue/GlueCatalogTest.java
Adding the StroageDescriptor parameter to a renamed table in the Glue Data Catalog by ALTER TABLE RENAME TO with Iceberg.
The ALTER TABLE RENAME TO supported in Iceberg operates CREATE A NEW TABLE and DROP TABLE because the Glue Data Catalog doesn’t support renaming tables.
Currently, the StorageDescriptor part is not copied when running ALTER TABLE RENAME TO with Iceberg as the following example.
**Before the table is renamed**:
```json
➜  ~ aws glue get-table --database-name db --name iceberg_1636000905
{
"Table": {
"Name": "iceberg_1636000905",
"DatabaseName": "db",
"CreateTime": 1636000913.0,
"UpdateTime": 1636000913.0,
"Retention": 0,
"StorageDescriptor": {
"Columns": [
{
"Name": "id",
"Type": "bigint",
"Parameters": {
"iceberg.field.id": "1",
"iceberg.field.optional": "true", …
```
> AWS: Fix the missing StorageDescriptor parameter after ALTER TABLE RENAME TO by iceberg.

- aws/src/integration/java/org/apache/iceberg/aws/glue/GlueCatalogNamespaceTest.java
- aws/src/main/java/org/apache/iceberg/aws/glue/GlueCatalog.java
- aws/src/main/java/org/apache/iceberg/aws/glue/IcebergToGlueConverter.java
- aws/src/test/java/org/apache/iceberg/aws/glue/GlueToIcebergConverterTest.java
> AWS: support setting location and description for Glue database

- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/SparkSchemaUtil.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/SparkBatchScan.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkMetadataColumns.java
This PR is a follow-up to #3373 and throws an exception when table columns conflict with metadata columns during reads.
> Spark: Validate table columns don't conflict with metadata columns

- core/src/main/java/org/apache/iceberg/actions/BinPackStrategy.java
- core/src/test/java/org/apache/iceberg/MockFileScanTask.java
- core/src/test/java/org/apache/iceberg/actions/TestBinPackStrategy.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/actions/TestNewRewriteDataFilesAction.java
Add an option `min-deletes-per-file` to allow rewriting files with certain number of deletes. This does not remove the deletes. It is used to solve the situation that a file is already of optimized size and never included in for bin packing, but deletes are associated with it so the deletes cannot be expired.
> Core: add delete option for bin-packing

- spark/v3.0/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestAddFilesProcedure.java
- spark/v3.0/spark/src/main/java/org/apache/iceberg/spark/procedures/AddFilesProcedure.java
- spark/v3.1/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestAddFilesProcedure.java
- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/procedures/AddFilesProcedure.java
- spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestAddFilesProcedure.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/procedures/AddFilesProcedure.java
This fixes https://github.com/apache/iceberg/issues/3453
However, we should probably return earlier if a user passes a path that has no files, but for now at least we can be more helpful than throwing an NPE which could kill a running job.
> Spark - Fix AddFilesProcedure throws NumberFormatException when no files are imported

- .github/workflows/cancel-duplicate-workflow-runs.yml
Small nit but in case Python Legacy CI gets run, it's not in the Cancel Duplicates Workflow so we could wind up with a lot of unnecessary runs.
> Infra - Add Python Legacy CI to Cancel Duplicate Action

- .gitignore
Adds the spark/v3.1/benchmarks directory to the .gitignore file.
Eventually we should see if we can have a single-level glob so we can ignore spark/v*/spark/benchmarks, but for now I just wanted to bring this up to parity with the others.
> Infra - Add Spark v3.1 JMH benchmarks to gitignore

- data/src/test/java/org/apache/iceberg/io/TestPartitioningWriters.java
Following up on the conversation https://github.com/apache/iceberg/pull/3377#discussion_r741387388.
Enabling running tests on ORC as well since https://github.com/apache/iceberg/pull/3250 has gone in.
cc @aokolnychyi
> Data: run tests for ORC too in TestPartitioningWriters deleteWriter tests

- .github/workflows/publish-snapshot.yml
The `Publish Snapshot to Maven` Github Action has been scheduled automatically in my forked repo and failing due to permission issues. 
Log: 
```
* What went wrong:
120
Execution failed for task ':iceberg-spark:publishApachePublicationToMavenRepository'.
121
> Failed to publish publication 'apache' to repository 'maven'
122
> Could not PUT 'https://repository.apache.org/content/repositories/snapshots/org/apache/iceberg/iceberg-spark/0.13.0-SNAPSHOT/maven-metadata.xml'. Received status code 401 from server: Unauthorized
123
```
[Example GH Action run](https://github.com/kevinjqliu/iceberg/runs/4133664776?check_suite_focus=true) 
The GH Action retries automatically (every day?) and will also generate a failure email report. I had to manually disable it on my forked repo.
This PR limits the …
> Only run publish GH action for apache repo, not forked

- core/src/main/java/org/apache/iceberg/actions/BinPackStrategy.java
- core/src/test/java/org/apache/iceberg/actions/TestBinPackStrategy.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/actions/TestNewRewriteDataFilesAction.java
based on conversation in https://github.com/apache/iceberg/pull/3454#issuecomment-962681328, use a different name for `min-deletes-per-file` to avoid confusion. Currently my idea is to use `delete-file-threshold`. Any thoughts? @rdblue @RussellSpitzer
> Core: rename min-deletes-per-file in BinPackStrategy

- core/src/main/java/org/apache/iceberg/TableProperties.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/SparkWriteConf.java
This PR adds table properties for controlling DELETE/UPDATE/MERGE distribution mode. Right now, Spark uses only one distribution mode per table. In some cases, regular writes and row-level commands have very different characteristics and would benefit from a different distribution.
> Core: Add DELETE/UPDATE/MERGE distribution mode properties

- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/Spark3Util.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/SparkReadConf.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/SparkReadOptions.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/SparkBatchQueryScan.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/SparkBatchScan.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/SparkFilesScan.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/SparkFilesScanBuilder.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/SparkMergeScan.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/SparkMicroBatchStream.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/SparkScanBuilder.java
This PR moves more read configs to `SparkReadConf`.
> Spark: Move more read configs to SparkReadConf

- core/src/main/java/org/apache/iceberg/TableProperties.java
- flink/v1.12/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java
- flink/v1.13/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java
This PR renames the upsert table property for consistency with other table props.
> Flink: Rename upsert table property

- core/src/main/java/org/apache/iceberg/PartitionsTable.java
- core/src/test/java/org/apache/iceberg/TestMetadataTableScans.java
Partitions table should read stats column from manifests only if requested on the scan (not enabled by default). 
This allows reading partitions from large tables without having to allocate a large amount of memory. We were hitting OOM on the Spark driver side when scanning the partitions table.
> Partitions table only reads stats if needed

- site/docs/releases.md
- site/mkdocs.yml
Adds 0.12.1 Release Notes to the Site Docs.
For javadoc updates, see https://github.com/apache/iceberg/pull/3503
> Docs - Add 0.12.1 to the release notes

- site/docs/blogs.md
Adds Tabular's blog post on [Iceberg metadata indexing](https://tabular.io/blog/iceberg-metadata-indexing/) to the blogs page.
> Docs: Add Iceberg indexing blog post

- data/src/test/java/org/apache/iceberg/data/FileHelpers.java
- flink/v1.12/flink/src/main/java/org/apache/iceberg/flink/data/FlinkAvroReader.java
- flink/v1.13/flink/src/main/java/org/apache/iceberg/flink/data/FlinkAvroReader.java
This is trying to fix the flink's v2 avro reader bug  https://github.com/apache/iceberg/pull/3477#discussion_r744576384
The problem is that the Flink Avro readers do not implement `SupportsRowPosition` so the position is always null.
> Flink: Fix the avro reader issue when reading v2 position deletes.

- README.md
- gradle/wrapper/gradle-wrapper.properties
- gradlew
Gradle 7.3 has just been released, which brings support for building Java 17 projects (not relevant for Iceberg (yet)) and other improvements. This upgrade should be fairly straight-forward and not as complicated as #2826 was.
Full release notes can be seen at https://docs.gradle.org/current/release-notes.html
> Build: Upgrade Gradle to 7.3

- spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRequiredDistributionAndOrdering.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/SortOrderToSpark.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/Spark3Util.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/SparkDistributionAndOrderingUtil.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/source/TestRequiredDistributionAndOrdering.java
This PR fixes our Spark references in required distribution and ordering. Previously, if a column had a special char in its name, Iceberg would request unquoted references that would break the resolution in Spark.
> Spark: Use quoted names in required distribution and ordering

- hive-metastore/src/main/java/org/apache/iceberg/hive/HiveSchemaConverter.java
- hive-metastore/src/test/java/org/apache/iceberg/hive/TestHiveSchemaUtil.java
- mr/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerNoScan.java
This PR backport https://issues.apache.org/jira/browse/HIVE-25377 for user still using Hive 2 ou 3.
> Hive : BACKPORT Hive-25377 :  Creating Iceberg table where some columns has omments but the last one does not fails

- .github/workflows/java-ci.yml
In this PR, we've just enabled the checkstyles check for the default engines.  As @rdblue suggested, it's better to enable checkstyles for all the engines.
> Build: Enable checkstyle for all engine versions

- site/docs/spec.md
While we have a significant amount of code relying on the `NameMapping` of a table, we don't actually include any information on this table property in the Spec. This PR aims to codify what we already do in most implementations of Iceberg.
> Spec: Document NameMapping

- core/src/main/java/org/apache/iceberg/BaseFile.java
- core/src/test/java/org/apache/iceberg/TestManifestReader.java
Fixes: https://github.com/apache/iceberg/issues/3167
From: https://github.com/apache/iceberg/pull/3015#discussion_r705780942
> Core: BaseFile returns wrong field when accessing position via index

- CONTRIBUTING.md
I noticed that the community profile (displayed on the Insights tab) is not all nice and green so I thought we could tackle these items (read more here: [About community profiles for public repositories](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/about-community-profiles-for-public-repositories)). This PR adds a simple contributing guideline doc, everyone please chime in with things that should be added/removed! :)
As for the Issue template and PR template, I'd like to suggest some variation of these templates created by Steven Mao: https://github.com/stevemao/github-issue-templates
1.
2.
3.
- Version of Iceberg:
- Platform:
Fixes #
-
-
-
As for the last item, a repo admin should be able to enable reported content from the settings page. …
> Adding a contributing doc

- api/src/main/java/org/apache/iceberg/RewriteFiles.java
- api/src/main/java/org/apache/iceberg/actions/RewriteDataFiles.java
- core/src/main/java/org/apache/iceberg/BaseRewriteFiles.java
- core/src/main/java/org/apache/iceberg/GenericManifestEntry.java
- core/src/main/java/org/apache/iceberg/ManifestWriter.java
- core/src/main/java/org/apache/iceberg/MergingSnapshotProducer.java
- core/src/main/java/org/apache/iceberg/actions/RewriteDataFilesCommitManager.java
- core/src/test/java/org/apache/iceberg/TableTestBase.java
- core/src/test/java/org/apache/iceberg/TestManifestWriter.java
- core/src/test/java/org/apache/iceberg/TestRewriteFiles.java
- core/src/test/java/org/apache/iceberg/TestRowDelta.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/actions/BaseRewriteDataFilesSparkAction.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/actions/TestNewRewriteDataFilesAction.java
Add new hook in `RewriteFiles` snapshot update to allow accepting a sequence number that is used for all new data files. That will force the manifest writer to produce `ManifestFile` with the provided sequence number instead of `-1`.
Also add a new property in `RewriteDataFiles` to use this feature through config `use-starting-sequence-number`. When enabled, the sequence number when compaction starts will be used for commit.
This whole mechanism solves the issue today in CDC where compaction has conflicts with new equality delete files. With this change, `RewriteFiles` can go through as long as the newly added data files don't have new position deletes.
> Core: support rewrite data files with starting sequence number

- site/docs/theme_customization/nav-item.html
solves [#3483](https://github.com/apache/iceberg/issues/3483)
Added `target="_blank" rel="noopener noreferrer"` to the anchor tag of presto / trino. 
Manually tested in local.
------
Additional resources : [how-to-use-html-to-open-link-in-new-tab](https://www.freecodecamp.org/news/how-to-use-html-to-open-link-in-new-tab/)
> Website: PrestoDB and Trino links should open in a new tab

- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/IcebergSpark.java
- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/SparkValueConverter.java
- spark/v3.1/spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSpark.java
Port of #3368 to Spark 3.1.
Fix is due to Chen Zhang (@izchen).
> Spark 3.1: Fix ClassCastException when using bucket UDF

- hive3/build.gradle
Small fix following up on https://github.com/apache/iceberg/pull/3510
> Build: add missing hive version variable in hive3 build file

- core/src/main/java/org/apache/iceberg/HistoryTable.java
- core/src/main/java/org/apache/iceberg/IncrementalDataTableScan.java
- core/src/main/java/org/apache/iceberg/MergingSnapshotProducer.java
- core/src/main/java/org/apache/iceberg/util/SnapshotUtil.java
- flink/v1.12/flink/src/main/java/org/apache/iceberg/flink/source/StreamingMonitorFunction.java
- flink/v1.12/flink/src/test/java/org/apache/iceberg/flink/source/TestStreamingReaderOperator.java
- flink/v1.13/flink/src/main/java/org/apache/iceberg/flink/source/StreamingMonitorFunction.java
- flink/v1.13/flink/src/test/java/org/apache/iceberg/flink/source/TestStreamingReaderOperator.java
- spark/v2.4/spark/src/main/java/org/apache/iceberg/actions/SparkActions.java
- spark/v2.4/spark/src/test/java/org/apache/iceberg/spark/source/TestDataSourceOptions.java
- spark/v3.0/spark/src/main/java/org/apache/iceberg/spark/procedures/AncestorsOfProcedure.java
- spark/v3.0/spark/src/main/java/org/apache/iceberg/spark/source/SparkMicroBatchStream.java
- spark/v3.0/spark/src/test/java/org/apache/iceberg/spark/source/TestDataSourceOptions.java
- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/procedures/AncestorsOfProcedure.java
- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/source/SparkMicroBatchStream.java
- spark/v3.1/spark/src/test/java/org/apache/iceberg/spark/source/TestDataSourceOptions.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/procedures/AncestorsOfProcedure.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/SparkMicroBatchStream.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/source/TestDataSourceOptions.java
There are many places that traverse snapshot history by looping over ancestors. Instead of rebuilding this logic everywhere, `SnapshotUtil` should provide an iterable to traverse ancestors. This adds that iterable and uses it to simplify code in other places that don't need to use the `parentId` logic.
> Core: Refactor SnapshotUtil using an Iterable

- core/src/main/java/org/apache/iceberg/ManifestFilterManager.java
- core/src/test/java/org/apache/iceberg/TestDeleteFiles.java
This PR fixes the logic for checking whether manifests have new files to delete. Specifically, we should ignore files that were previously deleted.
> Core: Fix check for new deleted files in manifests

- core/src/main/java/org/apache/iceberg/BaseSnapshot.java
- core/src/main/java/org/apache/iceberg/TableMetadata.java
- core/src/main/java/org/apache/iceberg/TableMetadataParser.java
- core/src/test/java/org/apache/iceberg/TestTableMetadata.java
This adds methods to parse `TableMetadata` from JSON strings, not just from `InputFile`. This is in support of the REST catalog.
> Core: Add methods to parse TableMetadata from JSON strings

- core/src/main/java/org/apache/iceberg/actions/BinPackStrategy.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteDataFilesAction.java
the `delete-file-threshold` should mean "a data file will be rewritten if it has this number of deletes or more", fix the javadoc and also improve the tests to refactor duplicated code that generates delete files.
> Core: fix javadoc for delete-file-threshold and improve test

- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/SparkCatalog.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/TestSparkCatalogOperations.java
closes: #3281 
The `alterTable()` method on the SparkCatalog class always returns null. This violates the [API contract](https://spark.apache.org/docs/latest/api/java/org/apache/spark/sql/connector/catalog/TableCatalog.html#alterTable-org.apache.spark.sql.connector.catalog.Identifier-org.apache.spark.sql.connector.catalog.TableChange...-) for the `TableCatalog` interface - this method must return the updated `Table` instance.
This PR fixes this by returning an updated `SparkTable` (which implements the `Table` interface) instance.
cc: @RussellSpitzer @netvl 
I have two questions when implementing this
- Why do we have multiple versions of Spark in the repo. Do I need to copy the same code to different versions of Spark?
- What's the difference between the `SparkCatalog` and …
> Conform .alterTable to the standard interface

- site/docs/blogs.md
There is a blog written by ververica.com's  flink-cdc-connector authors.  I think it's good to add this to apache iceberg blog list.
https://ververica.github.io/flink-cdc-connectors/master/content/quickstart/build-real-time-data-lake-tutorial.html
> Docs: Add ververica blog - Using Flink CDC to synchronize data from MySQL sharding tables and build real-time data lake

- aws/src/main/java/org/apache/iceberg/aws/glue/GlueCatalog.java
- core/src/main/java/org/apache/iceberg/CatalogUtil.java
- core/src/main/java/org/apache/iceberg/hadoop/Configurable.java
- core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java
This removes needing to have Hadoop `Configurable` or `Configuration` in the classpath to use `CatalogUtil`. It also adds a new `Configurable<C>` interface that can be implemented by pass-through catalogs that dynamically instantiate `FileIO` so there is no need for those catalogs to implement Hadoop's `Configurable` interface.
> Make Configurable.setConf call dynamic in CatalogUtil

- core/src/main/java/org/apache/iceberg/io/ResolvingFileIO.java
While testing Spark streaming reads with `S3FileIO`, I found that `FileIO` is used for checkpoint state but the checkpoint location may not match the expected `FileIO` implementation. This adds a new `FileIO` that dynamically loads and uses `S3FileIO` or falls back to `HadoopFileIO` depending on the scheme of each location.
> Initial implementation of ResolvingFileIO

- core/src/main/java/org/apache/iceberg/BaseMetadataTable.java
This PR :metadataTableSchena variable name's Schena is wrong，update to Schema.
> Core: Fix typo form metadataTableSchena to metadataTableSchema

- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/SparkFilters.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/TestSparkFilters.java
This PR is an attempt to fix NOT IN predicates in `SparkFilters`.
> Spark: Fix NOT IN predicates in SparkFilters

- .github/workflows/spark-ci.yml
- jmh.gradle
- settings.gradle
- spark/v3.1/build.gradle
- spark/v3.2/build.gradle
The Spark 3.1 and 3.2 artifacts currently don't have the scala version in them.
As Spark 3.2 adds experimental support for Scala 2.13, we should likely include our scala version in our project names.
I've added `_2.12` to the end of all of the Spark 3.1 and 3.2 projects.
This generates artifacts as follows, which seems a bit off (I'd prefer `3.2_2.12`), but does match sbt builds.
```
:iceberg-spark:iceberg-spark-3.2_2.12
:iceberg-spark:iceberg-spark-3.2-extensions_2.12
:iceberg-spark:iceberg-spark-3.2-runtime_2.12
```
Please feel free to suggest a better way to go about this than manually updating all references if you know one.
> Build: Append _2.12 (scala version) to Spark 3.1 and 3.2 module names

- spark/v3.2/spark/src/main/java/org/apache/spark/sql/connector/iceberg/write/DeltaBatchWrite.java
- spark/v3.2/spark/src/main/java/org/apache/spark/sql/connector/iceberg/write/DeltaWrite.java
- spark/v3.2/spark/src/main/java/org/apache/spark/sql/connector/iceberg/write/DeltaWriteBuilder.java
- spark/v3.2/spark/src/main/java/org/apache/spark/sql/connector/iceberg/write/DeltaWriter.java
- spark/v3.2/spark/src/main/java/org/apache/spark/sql/connector/iceberg/write/DeltaWriterFactory.java
- spark/v3.2/spark/src/main/java/org/apache/spark/sql/connector/iceberg/write/ExtendedLogicalWriteInfo.java
- spark/v3.2/spark/src/main/java/org/apache/spark/sql/connector/iceberg/write/RowLevelOperation.java
- spark/v3.2/spark/src/main/java/org/apache/spark/sql/connector/iceberg/write/RowLevelOperationBuilder.java
- spark/v3.2/spark/src/main/java/org/apache/spark/sql/connector/iceberg/write/RowLevelOperationInfo.java
- spark/v3.2/spark/src/main/java/org/apache/spark/sql/connector/iceberg/write/SupportsDelta.java
This PR adds new connector APIs for row-level commands in Spark 3.2 based on the voted [Spark SPIP](https://docs.google.com/document/d/12Ywmc47j3l2WF4anG5vL4qlrhT2OKigb7_EbIKhxg60).
Resolves #3628.
> Spark: Add connector APIs for row-level commands

- core/src/main/java/org/apache/iceberg/CatalogUtil.java
- core/src/test/java/org/apache/iceberg/hadoop/TestCatalogUtilDropTable.java
This change deletes the old metadata.json files in `dropTableData` which will be invoked by drop table with `purge=true`. Today only the latest metadata.json file will be deleted. Please see email thread https://lists.apache.org/thread/p59hn1dqoqs4r3z90tvlxx2wmv01g6fs for details. 
I don't think we have any existing unit test around this, but I have tested the change locally and also added unit tests for the same method.
> Core: delete previous metadata locations in dropping table with purge enabled

- .github/workflows/spark-ci.yml
- settings.gradle
- spark/v3.1/build.gradle
- spark/v3.2/build.gradle
With this rename, the modules for Spark 3.1 and 3.2 will be:
iceberg-spark-3.1_2.12
iceberg-spark-extensions-3.1_2.12
iceberg-spark-runtime-3.1_2.12
iceberg-spark-3.2_2.12
iceberg-spark-extensions-3.2_2.12
iceberg-spark-runtime-3.2_2.12
The 1st and 4th are current names as a result of #3624. Here we are renaming the rest. The new names are, in my opinion, more rational and still conform to sbt convention.
> Build: Rename Spark 3.1 and 3.2 module names

- core/src/main/java/org/apache/iceberg/MetricsConfig.java
- core/src/main/java/org/apache/iceberg/MetricsModes.java
`MetricsConfig` was effectively immutable from user perspective, because
all mutations were done in factory methods. Still, making the class
declare & enforce immutability helps the class users determine whether
it can be safety kept.
> Ensure MetricsConfig is immutable

- aws/src/main/java/org/apache/iceberg/aws/s3/S3URI.java
- aws/src/test/java/org/apache/iceberg/aws/s3/TestS3URI.java
As discussed in the mailing list: https://mail-archives.apache.org/mod_mbox/iceberg-dev/202112.mbox/%3CCAMwmD1_P2PCMpzUai5RV%2B4a9Bv62ZFqrrDdxCtLcTSvPnUxk6g%40mail.gmail.com%3E
Based on what Piotr said, 
> There are storages which are primarily used as "s3 compatible" and they need these settings to make them work.
We've seen these being used to access MinIO, Ceph and even S3 with some gateway
It seems to make more sense to just remove the restriction entirely instead of extending the list of allowed schemes.
@rdblue @danielcweeks @findepi @mayursrivastava
> AWS: remove S3URI scheme restrictions

- core/src/main/java/org/apache/iceberg/CatalogUtil.java
Raising a small change to change the variable name from `list` to `metadataFile` as `metadata.metadataFileLocation()` would give the current metadata file (and not a list). 
This change is also consistent with the previous lines where the previous metadata files are deleted: https://github.com/apache/iceberg/blob/master/core/src/main/java/org/apache/iceberg/CatalogUtil.java#L114-L117
> Core: Change variable name to metadataFile in CatalogUtil's dropTableData

- jmh.gradle
Noticed we don't have Spark 3.1 as a JMH option.
> [Spark] Add missing Spark 3.1 to JMH configuration

- core/src/main/java/org/apache/iceberg/BaseFileScanTask.java
- core/src/main/java/org/apache/iceberg/DataTableScan.java
- core/src/test/java/org/apache/iceberg/TestSplitPlanning.java
- spark/v2.4/spark/src/test/java/org/apache/iceberg/spark/source/TestDataSourceOptions.java
- spark/v3.0/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteDataFilesAction.java
- spark/v3.0/spark/src/test/java/org/apache/iceberg/spark/source/TestDataSourceOptions.java
- spark/v3.1/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteDataFilesAction.java
- spark/v3.1/spark/src/test/java/org/apache/iceberg/spark/source/TestDataSourceOptions.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteDataFilesAction.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/source/TestDataSourceOptions.java
Previously we didn't explicitly request the split_offsets column from
manifest files when planning Scan Tasks. This meant that the datafiles
would be split aware when they were divided. To fix this we request the
split_offset information when we do the Manifest read. In addition tests
are added to make sure this isn't missed again in the future.
Closes #3662
> Core: Request Split_Offsets when Planning Scans

- spark/v2.4/spark/src/main/java/org/apache/iceberg/spark/SparkTableUtil.java
- spark/v2.4/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkTableUtil.java
- spark/v3.0/spark/src/main/java/org/apache/iceberg/spark/SparkTableUtil.java
- spark/v3.0/spark/src/test/java/org/apache/iceberg/spark/TestSparkTableUtil.java
- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/SparkTableUtil.java
- spark/v3.1/spark/src/test/java/org/apache/iceberg/spark/TestSparkTableUtil.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/SparkTableUtil.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/TestSparkPartitionSerialization.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/TestSparkTableUtil.java
This PR replaces https://github.com/apache/iceberg/pull/3597, as @dubeme has not responded about some minor changes and we need this patch prior to the upcoming 0.13.0 release.
I have added them as a co-author on this PR so that they still get credit for their contribution 😄 
Issue #3586 shows situation where Kyro is unable to serialize the SparkPartition object (@rdblue points it out from the stack trace). This commit replaces the ImmutableMap with HashMap and adds a test for round trip Kryo serialization and Java serialization for `SparkPartition` objects.
I also tested this by running the `add_files` test suite with Kryo serialization enabled. The tests failed until this patch was applied. Unfortunately, I couldn't add a test there as the usual `withSQLConf` method did not pick up the …
> Spark: Remove ImmutableMap from SparkPartition for Kryo SerDe

- core/src/main/java/org/apache/iceberg/hadoop/ConfigProperties.java
- hive-metastore/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java
- mr/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerWithEngine.java
- mr/src/test/java/org/apache/iceberg/mr/hive/TestTables.java
The Hive engine keeps the HMS stats updated after each write to a table, provided that hive.stats.autogather is turned on. If other engines are interacting with the same table however, e.g. Spark writing to the same table, they might not update the HMS stats but also not invalidate the stats within HMS either, leaving it stale but HMS believing that it's up-to-date. This PR introduces a config which can enable/disable HMS stats invalidation in HiveCatalog for each engine.
cc @pvary
> Hive: HiveCatalog should remove HMS stats for certain engines based on config

- hive-metastore/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java
Leaving the serdeInfo.parameters as null can lead to NPE for consumers. We have encountered such an [error](https://github.com/apache/hive/commit/2431fd16aedbb857356cef3e15f20e91185e4039#diff-b1bce663288d98098d8aaa474ad0694d43484b0cd1977a788dc9f6c6f7fae4d0R206) in Hive before - this should guard against such scenarios.
> Hive: initialize serde parameters when committing table in HiveCatalog

- spark/v3.0/spark/src/main/java/org/apache/iceberg/spark/SparkCatalog.java
- spark/v3.0/spark/src/test/java/org/apache/iceberg/spark/TestSparkCatalogOperations.java
Port of #3548 to 3.0.
Fix is due to Xinbin Huang (@xinbinhuang).
> Spark 3.0: Make SparkCatalog#alterTable conform to TableCatalog interface

- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/SparkCatalog.java
- spark/v3.1/spark/src/test/java/org/apache/iceberg/spark/TestSparkCatalogOperations.java
Port of #3548 to 3.1.
Fix is due to Xinbin Huang (@xinbinhuang).
> Spark 3.1: Make SparkCatalog#alterTable conform to TableCatalog interface

- api/src/main/java/org/apache/iceberg/catalog/SupportsNamespaces.java
Minor typo in the javadoc summary of `NamespaceNotEmptyException` for `dropNamespace`.
> API: Fix typo in dropNamespace javadoc

- data/src/test/java/org/apache/iceberg/data/parquet/TestGenericData.java
- parquet/src/main/java/org/apache/iceberg/parquet/ParquetValueReaders.java
This is trying to address issue: [#3575](https://github.com/apache/iceberg/issues/3575)
> Parquet: fix the `limit` setting of ParquetValueReaders#BytesReader

- aliyun/src/main/java/org/apache/iceberg/aliyun/AliyunClientFactories.java
- aliyun/src/main/java/org/apache/iceberg/aliyun/AliyunProperties.java
- aliyun/src/main/java/org/apache/iceberg/aliyun/oss/OSSFileIO.java
- aliyun/src/test/java/org/apache/iceberg/aliyun/TestAliyunClientFactories.java
@openinx @xingbowu
I was writing #3658 and I noticed that there is some inconsistency between Aliyun and AWS module. I suggest making the following changes:
1. use `client.access-key-id` and `client.secret-access-key` as property names, 
`.` is used to build hierarchy to config names, but `access.key.id` does not have any hierarchy in it. Also I checked Aliyun doc, the name is secret access key, not access key secret, as shown in the builder method:
```
public class OSSClientBuilder implements OSSBuilder {
@Override
public OSS build(String endpoint, String accessKeyId, String secretAccessKey) {
return new OSSClient(endpoint, getDefaultCredentialProvider(accessKeyId, secretAccessKey),
getClientConfiguration());
}
```
I made `client` as the prefix because it seems like your credentials …
> Aliyun: align property names with AWS module

- spark/v2.4/build.gradle
- spark/v3.0/build.gradle
- spark/v3.1/build.gradle
- spark/v3.2/build.gradle
icebeg-hive-metastore dependency is not needed at compile time (and should not be needed). Spark and spark extension modules should not depend on HiveCatalog being on the classpath.
That said the dependency needed for running the tests, and also needed to be put into the fat runtime jar.
The PR modifies these dependencies accordingly.
> Spark: Remove iceberg-hive-metastore compile time dependency

- core/src/main/java/org/apache/iceberg/MetricsConfig.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/TestSparkTableUtil.java
In #3638 , we improved `MetricsConfig` construction and marked it as immutable. As @aokolnychyi pointed out the class was used for serialization before we introduced `SerializableTable`. Although it is not likely that people are still serializing the metrics config, because it implements the `Serializable` interface, it's still safer to use `SerializableMap` instead of `ImmutableMap` for this to avoid any potential trouble.
> Core: ensure Kryo serializability of MetricsConfig

- aws/src/integration/java/org/apache/iceberg/aws/TestDefaultAwsClientFactory.java
- aws/src/main/java/org/apache/iceberg/aws/AssumeRoleAwsClientFactory.java
- aws/src/main/java/org/apache/iceberg/aws/AwsClientFactories.java
- aws/src/main/java/org/apache/iceberg/aws/AwsProperties.java
- aws/src/test/java/org/apache/iceberg/aws/TestAwsClientFactories.java
As discussed in the mailing list: https://mail-archives.apache.org/mod_mbox/iceberg-dev/202112.mbox/%3CCAMwmD1_P2PCMpzUai5RV%2B4a9Bv62ZFqrrDdxCtLcTSvPnUxk6g%40mail.gmail.com%3E
For `DefaultClientFactory`, we allow configuration of S3 static credentials and endpoint.
For `AssumeRoleClientFactory`, we only allow configuration of S3 endpoint, because credential is always assume role credential.
@rdblue @danielcweeks @findepi @mayursrivastava
> AWS: support S3FileIO alternative endpoint and credentials

- flink/src/test/java/org/apache/iceberg/flink/source/TestProjectMetaColumn.java
- flink/v1.12/flink/src/test/java/org/apache/iceberg/flink/TestHelpers.java
- flink/v1.12/flink/src/test/java/org/apache/iceberg/flink/source/TestProjectMetaColumn.java
- flink/v1.13/flink/src/test/java/org/apache/iceberg/flink/TestHelpers.java
- flink/v1.13/flink/src/test/java/org/apache/iceberg/flink/source/TestProjectMetaColumn.java
This is trying to address issue: https://github.com/apache/iceberg/issues/3431
> Flink: Add tests to check whether should remove meta columns in source reader

- site/docs/spark-ddl.md
Adds an example for specifying create clauses in a spark CTAS/RTAS DDL
> Docs: add spark create clause CTAS/RTAS example

- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/SparkConfParser.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/SparkWriteConf.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/SparkWrite.java
This PR moves the logic for checking whether WAP is enabled to `SparkWriteConf`.
> Spark: Move WAP conf to SparkWriteConf

- .github/workflows/flink-ci.yml
- flink/v1.12/build.gradle
- flink/v1.13/build.gradle
- flink/v1.14/build.gradle
- settings.gradle
This PR changes the JAR / task names for different Flink versions, to have the version number at the very end.
This makes the jars alphabetically ordered and also places all words before version numbers.
This also is consistent with how we version our Spark runtime jars as of this PR: https://github.com/apache/iceberg/pull/3655
Current:    `iceberg-1.14-runtime`, `iceberg-1.13-runtime` and `iceberg-1.13`, etc.
Proposed: `iceberg-runtime-1.14`, `iceberg-runtime-1.13` and `iceberg-1.13`, etc.
cc @rdblue @stevenzwu @aokolnychyi @RussellSpitzer @openinx and I believe @wypoon handled the first version change for Spark.
> [Flink] Update flink-runtime jar naming with flink version at the end (like we do with Spark)

- site/docs/flink.md
modify description for flink streaming job
> Site Docs - Fix Flink batch job incorrectly labeled as streaming

- core/src/main/java/org/apache/iceberg/BaseMetastoreTableOperations.java
- hive-metastore/src/test/java/org/apache/iceberg/hive/TestHiveCommits.java
This PR fixes an issue where a commit succeeds but its metadata file is deleted and table is corrupted.
Currently when there's an exception during commit, we refresh table and check commit state by looking at if the new metadata location matches current or in history, and commit state is Failure if not, and the current metadata file is deleted.
There's a possibility that when the check happens, the metadata remote server (e.g. Hive metastore) is still processing the commit and eventually succeed later, in this case, the commit(atomic location swap) succeeds but metadata file is deleted, and the table is in bad state.
The commit state should be considered as unknown to avoid metadata being deleted, also the error propagated to user is more accurate.
> Core: Commit state should be unknown even when new location is not in history

- core/src/main/java/org/apache/iceberg/CachingCatalog.java
- core/src/main/java/org/apache/iceberg/CatalogProperties.java
- core/src/test/java/org/apache/iceberg/TestableCachingCatalog.java
- core/src/test/java/org/apache/iceberg/hadoop/TestCachingCatalog.java
- core/src/test/java/org/apache/iceberg/util/FakeTicker.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/SparkCatalog.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkCatalogCacheExpiration.java
Occasionally, users have reported issues that they have very specific problems with table caching.
Namely, if they're trying to read from a table, and others have written to it from another program, the cache won't be refreshed and users need to manually call `.refresh` on the table. This can be a source of confusion.
In general, the cache makes things more efficient.
But for things like long-lived session clusters or scenarios as described above, it would be desirable to expire the tables in the cache and then have them be reloaded if they're accessed via the catalog again after some period of time.
This allows for the catalog to still benefit from caching, but to discard cached entries after a configurable period of time.
Details:
- Adds a new catalog property, …
> Add configurable cache expiry to caching catalog 

- build.gradle
- gcp/src/main/java/org/apache/iceberg/gcp/GCPProperties.java
- gcp/src/main/java/org/apache/iceberg/gcp/gcs/BaseGCSFile.java
- gcp/src/main/java/org/apache/iceberg/gcp/gcs/GCSFileIO.java
- gcp/src/main/java/org/apache/iceberg/gcp/gcs/GCSInputFile.java
- gcp/src/main/java/org/apache/iceberg/gcp/gcs/GCSInputStream.java
- gcp/src/main/java/org/apache/iceberg/gcp/gcs/GCSOutputFile.java
- gcp/src/main/java/org/apache/iceberg/gcp/gcs/GCSOutputStream.java
- gcp/src/test/java/org/apache/iceberg/gcp/gcs/GCSFileIOTest.java
- gcp/src/test/java/org/apache/iceberg/gcp/gcs/GCSInputStreamTest.java
- gcp/src/test/java/org/apache/iceberg/gcp/gcs/GCSOutputStreamTest.java
- settings.gradle
- versions.props
This PR adds native FileIO support for GCS using the google storage apis directly.
The read/write paths leverage the streaming transfers and allow for full configuration of the storage provider via custom storage supplier.  By default, a number of common configuration properties are provided via GCPProperties and can be used with a dynamically loaded configuration.
> Add FileIO implementation for Google Cloud Storage

- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/SparkReadConf.java
- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/SparkReadOptions.java
- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/source/SparkBatchScan.java
- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/source/SparkMicroBatchStream.java
- spark/v3.1/spark/src/test/java/org/apache/iceberg/spark/source/TestStructuredStreamingRead3.java
Backport the following changes to Spark 3.1 runtime module:
- `SparkReadConf.streamingSkipDeleteSnapshots`.
- Read from timestamp changes (https://github.com/apache/iceberg/pull/3039).
> Spark 3.1: Backport SparkReadConf.streamingSkipDeleteSnapshots and read from timestamp changes

- spark/v3.0/spark/src/main/java/org/apache/iceberg/spark/SparkReadConf.java
- spark/v3.0/spark/src/main/java/org/apache/iceberg/spark/SparkReadOptions.java
- spark/v3.0/spark/src/main/java/org/apache/iceberg/spark/source/SparkBatchScan.java
- spark/v3.0/spark/src/main/java/org/apache/iceberg/spark/source/SparkMicroBatchStream.java
- spark/v3.0/spark/src/test/java/org/apache/iceberg/spark/source/TestStructuredStreamingRead3.java
Backport the following changes to Spark 3.0 runtime module:
- `SparkReadConf.streamingSkipDeleteSnapshots`.
- Read from timestamp changes (https://github.com/apache/iceberg/pull/3039).
> Spark 3.0: Backport SparkReadConf.streamingSkipDeleteSnapshots and read from timestamp changes

- flink/v1.12/build.gradle
- flink/v1.13/build.gradle
- flink/v1.14/build.gradle
- hive-runtime/build.gradle
- spark/v2.4/build.gradle
- spark/v3.0/build.gradle
- spark/v3.1/build.gradle
- spark/v3.2/build.gradle
* Start the Flink SQL cilent: 
```bash
wget https://gosspublic.alicdn.com/sdks/java/aliyun_java_sdk_3.10.2.zip
unzip aliyun_java_sdk_3.10.2.zip
FLINK_HOME=/path/to/flink-release
FLINK_RUNTIME_LIB=/path/to/iceberg-flink-runtime-1.14-0.13.0-SNAPSHOT.jar
HIVE_METASTORE_LIB=/path/to/flink-sql-connector-hive-2.3.6_2.12-1.13.2.jar
DEPS="-j $FLINK_RUNTIME_LIB -j $HIVE_METASTORE_LIB"
for dep in `find aliyun_java_sdk_3.10.2 -type f -name '*.jar'`; do
DEPS="$DEPS -j $dep"
done
eval "$FLINK_HOME/bin/sql-client.sh embedded $DEPS shell"
```
* Execute the flink SQL:
```sql
CREATE CATALOG hive WITH (
'type' = 'iceberg',
'uri' = 'thrift://localhost:9083',
'warehouse' = 'oss://iceberg-test/warehouse',
'io-impl' = 'org.apache.iceberg.aliyun.oss.OSSFileIO',
'oss.endpoint' = 'oss-cn-hangzhou.aliyuncs.com', …
```
> Aliyun: Add iceberg-aliyun to engines runtime

- deploy.gradle
Since we refactored the spark projects to have separate folders/projects
per spark version (in 811af43), gradle was evaluating the maven publish
plugin config (in `deploy.gradle`) before it applied the `shadowJar`
configs required for spark runtime projects, causing the generated POM
to include dependencies when it shouldn't (as we're publishing a shadow
jar).
This fixes it by delaying the maven publishing config to
`afterEvaluate`, when gradle has already applied the shadowJar plugin
for projects.
Closes #3620
> build: apply publishing config after project evaluation

- spark/v3.0/spark/src/main/java/org/apache/iceberg/spark/SparkCatalog.java
- spark/v3.0/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkCatalogCacheExpiration.java
* Backports https://github.com/apache/iceberg/pull/3543 to Spark 3.0
> [SPARK] Backport cache.expiration-interval-ms config to Spark 3.0

- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/SparkCatalog.java
- spark/v3.1/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkCatalogCacheExpiration.java
Backporting https://github.com/apache/iceberg/pull/3543 to Spark 3.1.
> [SPARK] Backport cache.expiration-interval-ms config to Spark 3.1

- core/src/main/java/org/apache/iceberg/TableProperties.java
- flink/v1.12/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java
- flink/v1.13/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java
- flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java
- spark/v3.0/spark/src/main/java/org/apache/iceberg/spark/Spark3Util.java
- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/Spark3Util.java
This PR deprecates `WRITE_DISTRIBUTION_MODE_DEFAULT` in `TableProperties` as discussed [here](https://github.com/apache/iceberg/pull/3720#discussion_r767310772).
> Core: Deprecate default distribution constant in TableProperties

- core/src/main/java/org/apache/iceberg/TableProperties.java
This PR unifies the definition style of our constants in `TableProperties`.
> Core: Use consistent literal definition in TableProperties

- data/src/test/java/org/apache/iceberg/data/GenericAppenderHelper.java
- hive3/build.gradle
- hive3/src/main/java/org/apache/iceberg/mr/hive/vector/HiveVectorizedReader.java
- hive3/src/main/java/org/apache/iceberg/orc/VectorizedReadUtils.java
- mr/src/test/java/org/apache/iceberg/mr/TestHelper.java
- mr/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerWithEngine.java
The Hive ORC vectorization code path considered the ORC file start/end positions as per given by the task.
In reality it should always read the OrcTail (metadata) parts from the end of the actual file,
irrespective of the task offset/length information.
This problem has come out after #3666 corrected that the split offsets provided by native file format appenders
should be considered in split generation. Unfortunately the unit tests were not populating split_offsets either earlier...
> Hive: ORC vectorization fails when split offsets are considered during split generation

- core/src/main/java/org/apache/iceberg/util/SnapshotUtil.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/SparkCatalog.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/IcebergSource.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/SparkScanBuilder.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/SparkTable.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSourceTablesBase.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/sql/TestDeleteFrom.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/sql/TestSelect.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/sql/TestUnpartitionedWrites.java
This has been implemented for Spark 2 in #1508. For Spark 3, Ryan Blue proposed a syntax for adding the snapshot id or timestamp to the table identifier in #3269. Here we implement the Spark 3 support for using the snapshot schema by using the proposed table identifier syntax. This is until a new version of Spark 3 is released with support for `AS OF` in Spark SQL.
Note: The table identifier syntax is for internal use only (as in this implementation) and not meant to be exposed as a publicly supported syntax in SQL. However, for testing, we do test its use from SQL.
> Spark: Use snapshot schema when reading snapshot

- site/docs/spark-procedures.md
Update table migration doc with notes consistent with other parts of the documentation.
> Update table migration doc with notes consistent with other parts of the documentation.

- core/src/main/java/org/apache/iceberg/util/PropertyUtil.java
I happen to notice that in `PropertyUtil`, we define a variable to hold the value of `properties.get(property)` and then we call the `get` again. We can just use the variable.
> [Minor] Core: dedup call to properties.get(property) in PropertyUtil

- .github/workflows/publish-snapshot.yml
Currently, only the default versions are being published to the
snapshots repo (e.g only spark 3.2). In order to allow testing of other
versions, we should publish packages all supported versions of spark,
flink and hive.
> Build: publish snapshot packages for all known versions

- spark/v3.0/spark/src/main/java/org/apache/iceberg/spark/SparkCatalog.java
- spark/v3.0/spark/src/main/java/org/apache/iceberg/spark/source/IcebergSource.java
- spark/v3.0/spark/src/main/java/org/apache/iceberg/spark/source/SparkScanBuilder.java
- spark/v3.0/spark/src/main/java/org/apache/iceberg/spark/source/SparkTable.java
- spark/v3.0/spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSourceTablesBase.java
- spark/v3.0/spark/src/test/java/org/apache/iceberg/spark/sql/TestDeleteFrom.java
- spark/v3.0/spark/src/test/java/org/apache/iceberg/spark/sql/TestSelect.java
- spark/v3.0/spark/src/test/java/org/apache/iceberg/spark/sql/TestUnpartitionedWrites.java
Port of #3722 to v3.0.
Notes:
Similar to #3768, except that `TestDeleteFrom` in v3.0 does have `testDeleteFromUnpartitionedTable` and `testDeleteFromPartitionedTable` (which are not present in v3.1).
> Spark 3.0: Use snapshot schema for time travel queries

- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/SparkCatalog.java
- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/source/IcebergSource.java
- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/source/SparkScanBuilder.java
- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/source/SparkTable.java
- spark/v3.1/spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSourceTablesBase.java
- spark/v3.1/spark/src/test/java/org/apache/iceberg/spark/sql/TestDeleteFrom.java
- spark/v3.1/spark/src/test/java/org/apache/iceberg/spark/sql/TestSelect.java
- spark/v3.1/spark/src/test/java/org/apache/iceberg/spark/sql/TestUnpartitionedWrites.java
Port of #3722 to v3.1.
Notes:
I took the diff from #3722, edited it to change v3.2 to v3.1 in the paths, and tried to `git apply 3722.diff`. That did not apply, so I did `git am -3 < 3722.diff`, which left conflicts in SparkTable.java and TestDeleteFrom.java.
The conflicts in SparkTable.java were straightforward to resolve.
`TestDeleteFrom` in v3.2 has `testDeleteFromUnpartitionedTable` and `testDeleteFromPartitionedTable` which are note present in v3.1; I had based the new test, `testDeleteFromTableAtSnapshot` on `testDeleteFromUnpartitionedTable`, and it is still usable because we don't actually delete anything, just check that an exception is thrown.
Also, for the negative test cases added in `TestDeleteFrom` and `TestUnpartitionedWrites`, I had to exclude the `SparkSessionCatalog` …
> Spark 3.1: Use snapshot schema for time travel queries

- spark/v3.0/spark/src/test/java/org/apache/iceberg/spark/actions/TestCreateActions.java
- spark/v3.1/spark/src/test/java/org/apache/iceberg/spark/actions/TestCreateActions.java
Add spark's legacy mode write tests to spark3.0 and 3.1 versions.
> Add spark's legacy mode write tests to spark3.0 and 3.1 versions.

- gradle/wrapper/gradle-wrapper.properties
- gradlew
According to https://docs.gradle.org/7.3.2/release-notes.html, this version contains mitigations for log4j vulnerability
> Build: Upgrade Gradle to 7.3.2

- core/src/main/java/org/apache/iceberg/BaseTransaction.java
- core/src/test/java/org/apache/iceberg/TableTestBase.java
- core/src/test/java/org/apache/iceberg/TestReplaceTransaction.java
- core/src/test/java/org/apache/iceberg/TestTables.java
- core/src/test/java/org/apache/iceberg/TestTransaction.java
Deleting files when commit state is unknown can leave table in bad state, similar fixes have been there in some places some places like "SnapshotProducer.commit".
> Core: Don't delete files during transaction commit when commit state is unknown

- core/src/main/java/org/apache/iceberg/util/SnapshotUtil.java
- spark/v3.0/spark/src/main/java/org/apache/iceberg/spark/source/SparkMicroBatchStream.java
- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/source/SparkMicroBatchStream.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/SparkMicroBatchStream.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/source/TestStructuredStreamingRead3.java
The util class `SnapshotUtil` is shared, so it needs to have fairly strict method contracts. This replaces `SnapshotUtil.firstSnapshotAfterTimestamp` with `oldestAncestorAfter`:
* The new implementation throws `IllegalStateException` if the correct ancestor cannot be determined
* The new name is clear that the snapshots considered are ancestors, not all snapshots
This also updates places that called `firstSnapshotAfterTimestamp` and attempts to have the same behavior by catching the `IllegalStateException` (cannot determine ancestor) and uses the oldest ancestor instead. However, in updating the Spark streaming code, I noticed a few bugs:
* `planFiles` will call `.snapshotId()` without checking the snapshot, which can be null if the timestamp is newer than the current, resulting in a …
> Core: Replace SnapshotUtil firstSnapshotAfterTimestamp

- spark/v3.0/spark/src/main/java/org/apache/iceberg/spark/Spark3Util.java
- spark/v3.0/spark/src/test/java/org/apache/iceberg/spark/source/TestFilteredScan.java
This is a followup for Spark 3.0 to backport the small changes needed to make `NOT_STARTS_WITH` work with Spark 3.0
Parent: https://github.com/apache/iceberg/pull/2062
> [SPARK] Add in NOT_STARTS_WITH support to Spark 3.0

- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/Spark3Util.java
- spark/v3.1/spark/src/test/java/org/apache/iceberg/spark/source/TestFilteredScan.java
This is a followup for Spark 3.0 to backport the small changes needed to make `NOT_STARTS_WITH` work with Spark 3.1
Parent: https://github.com/apache/iceberg/pull/2062
> [SPARK] Add in NOT_STARTS_WITH support to Spark 3.1

- spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestAddFilesProcedure.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/Spark3Util.java
When importing partitions into a table, we get all of the partitions using `Spark3Util#getPartitions`, which converts the catalyst value to a Scala value, on which we finally call `toString`.
However, if one of the partition columns is `null`, this will fail and throw when we try to call `toString` on `null`.
I've added 2 new test cases, in order to not mess with existing test cases.
However, if we'd prefer to cut down on the number of expensive tests, I can revert this to adding the 5th record (with `null`) into all DF and update the tests as needed.
Before this fix, these new tests fail with an NPE.
> [SPARK] Fix NPE when calling toString on partition column values in getPartitions (Spark 3.2)

- parquet/src/main/java/org/apache/iceberg/parquet/ApplyNameMapping.java
This makes a couple of modifications to #3723 to make it more consistent and simpler.
* Instead of creating a fake element type, add "element" to field names directly
* To support direct control of `fieldNames`, move name handling into `ApplyNameMapping`
* Remove unnecessary method, `makeListType`
* Apply similar changes to maps to avoid name mismatch bugs in the future
> Parquet: Simplify changes from #3723

- spark/v3.0/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestAddFilesProcedure.java
- spark/v3.0/spark/src/main/java/org/apache/iceberg/spark/Spark3Util.java
This is a backport of #3778 for Spark 3.0
Fixes an NPE when getting listing partitions for `add_files_procedure` if one of the partition columns has a value of `null`.
> [SPARK] Fix NPE for null partition cols in add_files_procedure - Backport of #3778 (Spark 3.0)

- spark/v3.1/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestAddFilesProcedure.java
- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/Spark3Util.java
This is a backport of https://github.com/apache/iceberg/pull/3778 for Spark 3.1.
> [SPARK] Fix NPE for null partition cols in add_files_procedure - Backport of #3778 (Spark 3.1)

- site/docs/spark-configuration.md
Adds documentation to the site for the catalog config key `cache.expiration-interval-ms` for Spark.
This has not been implemented for Flink yet, so I've not added it to the Flink documentation (working on that in a separate PR).
Here's a reference to the JavaDoc for this configuration value: https://github.com/apache/iceberg/blob/9c3e340cd67699c3d2499762d794ab1bc1ee7f45/core/src/main/java/org/apache/iceberg/CatalogProperties.java#L42-L52
> [SITE] Document cache.expiration-interval-ms in Spark Configuration

- spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRewriteDataFilesProcedure.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/procedures/RewriteDataFilesProcedure.java
- spark/v3.2/spark/src/main/scala/org/apache/spark/sql/execution/datasources/SparkExpressionConverter.scala
Some filters fails with exception mentioned in #3756.
Hence use the spark resolved expressions in rewrite_data_files procedure
Fixes #3756
> Spark: Fix UnresolvedException for some filters in rewrite_data_files procedure

- core/src/main/java/org/apache/iceberg/util/ThreadPools.java
This small PR sets the minimum size of the worker pool to be 2 threads. Many of the processes that use the pool are doing file I/O and are not necessarily CPU bound, like query planning, and often times people leave the number of Spark driver cores at the default of 1 core. This results in just one thread being used for query planning and other processes by default, which is a bit conservative.
> Core: Set the worker pool size to be at least 2 threads

- build.gradle
The `assertj` dependency is included in all sub-modules, by default.
Some submodules are declaring it, which isn't necessary. I've removed them.
> Remove unnecessary extra declarations of assertj in build file

- core/src/main/java/org/apache/iceberg/HistoryTable.java
- core/src/main/java/org/apache/iceberg/SnapshotsTable.java
- core/src/main/java/org/apache/iceberg/StaticTableScan.java
This PR fixes an issue when scanning the snapshots (and history) metadata tables. When the current snapshot for a table is not set, then no snapshots will be returned during the scan. A table can get in this state if it has snapshots, then a `REPLACE TABLE` operation is performed. In this case, the snapshots are still present but will not be returned because the current snapshot is not set. If some data is committed to the table, and the current snapshot is set to something, then the previous snapshots that were not returned will show up again.
Here is an example on how to reproduce with Spark SQL:
```
create table local.default.foobar (id int) using iceberg;  
insert into local.default.foobar values (1);  
replace table local.default.foobar (id int, data string) using iceberg;  
select * …
```
> Core: Fix metadata table scans when snapshot is null

- core/src/main/java/org/apache/iceberg/CachingCatalog.java
- core/src/test/java/org/apache/iceberg/hadoop/TestCachingCatalog.java
Uses caffeine's `RemovalListener` to expire metadata tables asynchronously, avoiding modifying cache entries during `compute` HashMap functions (which cause deadlocks).
For more details, check #3791
Fixes #3791
> Core: fix deadlock in CachingCatalog

- README.md
- site/docs/flink.md
> Docs: Update compatibility table

- dev/source-release.sh
A small fix for the `./dev/source-release.sh` script ( Found this when I release it into our own production).
> Build: Enable the -g option in source-release.sh

- spark/v3.1/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRewriteDataFilesProcedure.java
- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/procedures/RewriteDataFilesProcedure.java
- spark/v3.1/spark/src/main/scala/org/apache/spark/sql/execution/datasources/SparkExpressionConverter.scala
This PR is a backport of #3757 to spark-3.1
> Spark-3.1: Fix UnresolvedException for some filters in rewrite_data_files

- spark/v3.0/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRewriteDataFilesProcedure.java
- spark/v3.0/spark/src/main/java/org/apache/iceberg/spark/procedures/RewriteDataFilesProcedure.java
- spark/v3.0/spark/src/main/scala/org/apache/spark/sql/execution/datasources/SparkExpressionConverter.scala
This PR is a backport of #3757 to spark-3.0
> Spark-3.0: Fix UnresolvedException for some filters in rewrite_data_files

- site/docs/configuration.md
format version table properties is missing in the configuration docs.
> Docs: update about format version table properties

- site/docs/spark-structured-streaming.md
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/SparkMicroBatchStream.java
close https://github.com/apache/iceberg/issues/3699
> Spark: We should probably say why we cannot process the snapshot in SparkMicroBatchStream

- site/docs/spark-configuration.md
Add `stream-from-timestamp` in `spark-configuration.md`.
Reference: [Code](https://github.com/apache/iceberg/blob/master/spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/SparkReadOptions.java#L70-L71)
> Docs: Add stream-from-timestamp in spark-configuration.md

- site/docs/spark-queries.md
Some users in the slack are exploring incremental read in spark and we don't have document for the same. Hence this PR.
> Docs: update spark doc about incremental scan

- spark/v3.0/spark/src/main/java/org/apache/iceberg/spark/source/SparkTable.java
- spark/v3.0/spark/src/test/java/org/apache/iceberg/spark/sql/TestDeleteFrom.java
Fix UT case testDeleteFromTableAtSnapshot. This UT failed in spark version 3.0. I think this is because the [[SPARK-33623][SQL] Add canDeleteWhere to SupportsDelete](https://github.com/apache/spark/pull/30562) does not exist in 3.0.
> Spark 3.0: Fix delete from snapshot of table

- core/src/main/java/org/apache/iceberg/ManifestWriter.java
- core/src/test/java/org/apache/iceberg/TestRowDelta.java
We use the starting-sequence-number configuration when rewriting, then the data written in this rewrite will set the `status` to `ADDED` in the manifest entry, and set the `sequence_number` to the sequence number of the snapshot read before the rewrite. If this rewrite also triggers the `manifest merge` at the end, the sequence number of the new added data file's manifest entry will be lost.  
For example:   
We rewrite the snapshot with sequence number equals to `1` and enable `use-starting-sequence-number`, which triggers the rewriting of some data files and the merging of manifests. It is expected that the sequence number of the new manifest entries of the new rewritten data files should be `1`. When actually rewriting, because the manifest merge is triggered, the current logic sets …
> [Core][Rewrite] Fix merge manifests lost sequence number for added files when rewriting using staring sequence number

- api/src/main/java/org/apache/iceberg/PartitionSpec.java
- core/src/main/java/org/apache/iceberg/BaseUpdatePartitionSpec.java
- core/src/test/java/org/apache/iceberg/TestUpdatePartitionSpec.java
this would be convenient for the users to have various (can be same) transformations with the same target column name after deleting the original one
> Core: Allow deleting and adding the same column

- site/mkdocs.yml
Broken link of https://docs.dremio.com/data-formats/iceberg-enabling/
New link https://docs.dremio.com/data-formats/apache-iceberg/
> Docs: Fix broken link of Dremio with Iceberg

- rest_docs/rest-catalog-open-api.yaml
This is a follow up to the original PR, https://github.com/apache/iceberg/pull/3561, as the discussion there got too large.
We mostly handle _namespace_ related concerns here. Table related objects will come in a follow up PR.
I have followed up on comments and suggestions that were brought up on the other PR, as well as some conclusions that we've come to in the meeting.
The easiest way to view this document is by importing the YAML directly into editor.swagger.io
> Spec: Initial OpenAPI Spec for a Rest Catalog

- gradle/wrapper/gradle-wrapper.properties
- gradlew
7.3.2 does't fix log4j vulnerability completely. so should upgrade to 7.3.3
> Build: upgrade gradle to 7.3.3

- core/src/main/java/org/apache/iceberg/SerializableTable.java
- flink/v1.13/flink/src/test/java/org/apache/iceberg/flink/TestHelpers.java
- flink/v1.13/flink/src/test/java/org/apache/iceberg/flink/TestTableSerialization.java
The `SerializableTable`  cannot be kyro serializable because it will encounter the anonymous lambda registration issues. See the following stacktrace: 
```java
com.esotericsoftware.kryo.KryoException: java.lang.NullPointerException
Serialization trace:
hadoopConf (org.apache.iceberg.hadoop.HadoopFileIO)
io (org.apache.iceberg.SerializableTable)
at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:82)
at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:495)
at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:523)
at com.esotericsoftware.kryo.serializers.ObjectField.write(ObjectField.java:61)
at com.esotericsoftware.kryo.serializers.FieldSerializer.write(FieldSerializer.java:495)
at …
```
> Flink 1.13: Add SerializableTable test cases.

- core/src/main/java/org/apache/iceberg/deletes/BitmapPositionDeleteIndex.java
- core/src/main/java/org/apache/iceberg/deletes/Deletes.java
- core/src/main/java/org/apache/iceberg/deletes/PositionDeleteIndex.java
- core/src/test/java/org/apache/iceberg/deletes/TestPositionFilter.java
- data/src/main/java/org/apache/iceberg/data/DeleteFilter.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/data/vectorized/ColumnarBatchReader.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/data/TestSparkParquetReadMetadataColumns.java
This PR replaces `Set<Long>` with `Roaring64Bitmap` to store the deleted positions for filtering. Bitmap use significant less memory than a set, here is a [benchmark](https://github.com/apache/iceberg/pull/3287#discussion_r733910082). With that, we don't have to use streaming filter in case of large amount of positions, we can keep all deleted positions in memory.
cc @aokolnychyi @rdblue @RussellSpitzer @karuppayya  @szehon-ho
> Core: Replace Set with Bitmap to make delete filtering simpler and faster

- site/mkdocs.yml
As part of updating the copyright year in https://github.com/apache/iceberg/pull/3855, my grep-foo missed the mkdocs file.
cc @smallx thanks for catching this!
> Site - Update copyright year in mkdocs file to 2022

- flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/data/FlinkOrcWriters.java
Add annotation to skip build warnings.
```
[JavaInstantGetSecondsGetNano] instant.getNano() only accesses the underlying nanosecond adjustment from the whole second.
cv.nanos[rowId] = (instant.getNano() / 1_000) * 1_000;
^
(see https://errorprone.info/bugpattern/JavaInstantGetSecondsGetNano)
```
> Build: Add annotation to skip build warnings.

- build.gradle
- nessie/src/main/java/org/apache/iceberg/nessie/NessieCatalog.java
- nessie/src/main/java/org/apache/iceberg/nessie/NessieUtil.java
- nessie/src/test/java/org/apache/iceberg/nessie/BaseTestIceberg.java
- nessie/src/test/java/org/apache/iceberg/nessie/TestCustomNessieClient.java
Nessie defaults to use the HttpClientBuilder, but certain use cases
require a custom client builder implementation. This change allows
this by having a new configuration option.
> Allow using a custom NessieClientBuilder implementation

- api/src/main/java/org/apache/iceberg/expressions/Literals.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/Spark3Util.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/SparkTestBase.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/sql/TestSelect.java
adds the ability to assert binary arrays for "assertEquals"  and  adds  iceberg hexadecimal text parsing
solve cannot convert bytes to SQL literal
cc/ @aokolnychyi  @rdblue
> Spark: Generate Spark's SQL literal format for binary and update the toString representation of binary/fixed literals.

- spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestAddFilesProcedure.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/Spark3Util.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/SparkUtil.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/procedures/AddFilesProcedure.java
When getting files from Spark, we want to push down partition filters to Spark, so only the partitions that match the filters will be returned.
Basically, I am using this Spark API to prune partitions
```
FileIndex
def listFiles(
partitionFilters: Seq[Expression], dataFilters: Seq[Expression]): Seq[PartitionDirectory]
```
> Push down partition filter to Spark when Importing File Based Tables

- flink/v1.12/flink/src/test/java/org/apache/iceberg/flink/FlinkTestBase.java
- flink/v1.12/flink/src/test/java/org/apache/iceberg/flink/source/TestFlinkReaderDeletesBase.java
- flink/v1.13/flink/src/test/java/org/apache/iceberg/flink/FlinkTestBase.java
- flink/v1.13/flink/src/test/java/org/apache/iceberg/flink/source/TestFlinkReaderDeletesBase.java
- flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/FlinkTestBase.java
- flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/TestCatalogTableLoader.java
- flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/source/TestFlinkReaderDeletesBase.java
- hive-metastore/src/test/java/org/apache/iceberg/hive/HiveMetastoreTest.java
- hive-metastore/src/test/java/org/apache/iceberg/hive/TestHiveCatalog.java
- hive-metastore/src/test/java/org/apache/iceberg/hive/TestHiveMetastore.java
- mr/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerLocalScan.java
- mr/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerNoScan.java
- mr/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerTimezone.java
- mr/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerWithEngine.java
- mr/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerWithMultipleCatalogs.java
- mr/src/test/java/org/apache/iceberg/mr/hive/TestHiveShell.java
- spark/v2.4/spark/src/test/java/org/apache/iceberg/spark/SparkTestBase.java
- spark/v2.4/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkReaderDeletes.java
- spark/v3.0/spark/src/test/java/org/apache/iceberg/spark/SparkTestBase.java
- spark/v3.0/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkReaderDeletes.java
- spark/v3.1/spark/src/test/java/org/apache/iceberg/spark/SparkTestBase.java
- spark/v3.1/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkReaderDeletes.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/SparkTestBase.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/SparkTestBaseWithCatalog.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkReaderDeletes.java
Use `FileUtils.deleteQuietly` to delete the temp folders created in `TestHiveMetastore`, `SparkTestBaseWithCatalog` and `TestCatalogTableLoader`. Use JUnit `TemporaryFolder` in `TestHiveCatalog`.
Closes #3750
> Test: Make sure to delete temp folders

- api/src/main/java/org/apache/iceberg/catalog/Catalog.java
- hive-metastore/src/main/java/org/apache/iceberg/hive/HiveCatalog.java
- hive-metastore/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java
- hive-metastore/src/test/java/org/apache/iceberg/hive/HiveTableTest.java
This PR allows us to register existing tables in Iceberg HiveCatalog.
Right now, we can keep metadata and data files while dropping tables from Iceberg HiveCatalog. However, there is no way to register those tables back even though the metadata and data files can be still there. So, we need to extend HiveCatalog with another method that will accept a location to the valid metadata file and would register a table in HMS.
This will allow us to properly support external tables in Spark.
> API: Register existing tables in Iceberg HiveCatalog

- core/src/main/java/org/apache/iceberg/io/BaseTaskWriter.java
- core/src/main/java/org/apache/iceberg/io/RollingFileWriter.java
- flink/v1.12/flink/src/test/java/org/apache/iceberg/flink/sink/TestDeltaTaskWriter.java
- flink/v1.13/flink/src/test/java/org/apache/iceberg/flink/sink/TestDeltaTaskWriter.java
- flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/sink/TestDeltaTaskWriter.java
- parquet/src/main/java/org/apache/iceberg/parquet/ParquetWriter.java
This is an update to #3293 that implements the `FileAppender` contract more closely to avoid test failures.
This renames `writer` to `ensureWriterInitialized` and updates previous calls to `writer()` that would initialize the writer -- even if the appender was closed -- with null checks. `ensureWriterInitialized` is called when flushing a row group from the column write store to the file.
> Lazily initialize the underlying writer in ParquetWriter

- api/src/main/java/org/apache/iceberg/actions/DeleteOrphanFiles.java
- spark/v2.4/spark/src/main/java/org/apache/iceberg/spark/actions/BaseDeleteOrphanFilesSparkAction.java
- spark/v2.4/spark/src/test/java/org/apache/iceberg/spark/actions/TestRemoveOrphanFilesAction.java
- spark/v3.0/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRemoveOrphanFilesProcedure.java
- spark/v3.0/spark/src/main/java/org/apache/iceberg/spark/actions/BaseDeleteOrphanFilesSparkAction.java
- spark/v3.0/spark/src/main/java/org/apache/iceberg/spark/procedures/RemoveOrphanFilesProcedure.java
- spark/v3.0/spark/src/test/java/org/apache/iceberg/spark/actions/TestRemoveOrphanFilesAction.java
- spark/v3.1/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRemoveOrphanFilesProcedure.java
- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/actions/BaseDeleteOrphanFilesSparkAction.java
- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/procedures/RemoveOrphanFilesProcedure.java
- spark/v3.1/spark/src/test/java/org/apache/iceberg/spark/actions/TestRemoveOrphanFilesAction.java
- spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRemoveOrphanFilesProcedure.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/actions/BaseDeleteOrphanFilesSparkAction.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/procedures/RemoveOrphanFilesProcedure.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/actions/TestRemoveOrphanFilesAction.java
Allow parallelism in removing orphan files using Spark procedures and Spark Actions, like how it was implemented in expire snapshots, This change close #3582 
Since I need to change the `DeleteOrphanFiles` interface in api, ends up also updating the code for spark2.4/3.0/3.1/3.2 BaseDeleteOrphanFilesSparkAction as they are implement the same interface, also update the spark procedures to allow calling from spark SQL.
I update the tests for `TestRemoveOrphanFilesAction` and `TestRemoveOrphanFilesProcedure` in respective spark version. I did not touch any tests in  `TestRemoveOrphanFilesAction3` as it mostly cover different catalogs
```
$ ./gradlew -DsparkVersions=3.2 \
-DhiveVersions= -DflinkVersions= \
:iceberg-spark:iceberg-spark-3.2_2.12:check \ …
```
> Spark : Support parallelism in RemoveOrphanFiles

- api/src/main/java/org/apache/iceberg/PartitionSpec.java
- api/src/main/java/org/apache/iceberg/types/TypeUtil.java
- api/src/main/java/org/apache/iceberg/util/StructProjection.java
- core/src/main/java/org/apache/iceberg/TableProperties.java
- spark/v3.2/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/ProjectingInternalRow.scala
- spark/v3.2/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/analysis/RewriteDeleteFromTable.scala
- spark/v3.2/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/analysis/RewriteRowLevelCommand.scala
- spark/v3.2/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/planning/RewrittenRowLevelCommand.scala
- spark/v3.2/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/plans/logical/WriteDelta.scala
- spark/v3.2/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/util/RowDeltaUtils.scala
- spark/v3.2/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/util/WriteDeltaProjections.scala
- spark/v3.2/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/ExtendedDataSourceV2Strategy.scala
- spark/v3.2/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/ExtendedV2Writes.scala
- spark/v3.2/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/WriteDeltaExec.scala
- spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/SparkRowLevelOperationsTestBase.java
- spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestDelete.java
- spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMergeOnReadDelete.java
- spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestUpdate.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/Spark3Util.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/SparkDistributionAndOrderingUtil.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/SparkWriteConf.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/SparkWriteOptions.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/SparkBatchQueryScan.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/SparkPositionDeltaOperation.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/SparkPositionDeltaWrite.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/SparkPositionDeltaWriteBuilder.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/SparkRowLevelOperationBuilder.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/SparkScanBuilder.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/SparkTable.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/source/TestDataSourceOptions.java
This PR implements merge-on-read DELETE in Spark.
Resolves #3629.
> Spark: Implement merge-on-read DELETE

- site/docs/spark-ddl.md
Enrich the description of the syntax of `write distribution and ordering` based on alter table.
> Docs: Add `WRITE LOCALLY ORDERED BY` and `WRITE DISTRIBUTED BY` in spark-ddl.md

- dev/source-release.sh
In a previous PR, https://github.com/apache/iceberg/pull/3824, the default repo name was changed to `apache`.
However, this was originally kept as `origin` so we can run this in automation (GH action, on ASF infra - anywhere that clones the repository locally first). Additionally, all users are guaranteed to have `origin` locally.
The choice of `apache` is somewhat non-standard (all of the github docs etc use `upstream`). Though I know many committers / PMC that use `apache` to differentiate from forks or just to be more specific.
If we only do that from the release manager's laptop, we can keep it as `apache` as likely they have it set up that way.
In either case, I've added a check early on to ensure that the git remote exists, so that a tag and version file are not committed …
> Build: Fix source-release script to run anywhere automated and add validation that remote git repo exists

- python/src/iceberg/types.py
- python/tests/test_types.py
This PR is to solve having to do `isinstance` or `==` when checking types. 
```python
from iceberg.types import BooleanType, Boolean
x = BooleanType
isinstance(x, Boolean)  # True
```
No changes to tests. This also should not conflict with other PRs.
> Expanding primitive types to individual classes

- python_legacy/iceberg/api/expressions/expression_parser.py
- python_legacy/tests/api/expressions/test_str_to_expr.py
> [python legacy] Stripping quotes in convert_string_to_expr() when predicate value is a string type

- python_legacy/iceberg/api/types/conversions.py
- python_legacy/tests/api/test_conversions.py
See issue #3924 
@samredai As discussed in Slack, here is the PR fixing the conversion of boolean types.
> Python: fix wrong encoding for lower/upper bounds boolean value (#3924)

- site/docs/configuration.md
List the values supported by `write.parquet.compression-codec` in desc: `uncompressed, snappy, gzip, lzo, brotli, lz4, zstd`
> Doc: Add values supported by parquet\avro compression codec

- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/IcebergSpark.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSpark.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/sql/TestPartitionedWritesAsSelect.java
When writing to the partition table, we need to register the truncate transform function in Spark to specify it during sort.
issue: https://github.com/apache/iceberg/issues/3707
cc/ @rdblue @aokolnychyi
> Spark: Add register Truncate UDF

- flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/TestHelpers.java
- flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/source/TestProjectMetaColumn.java
Port https://github.com/apache/iceberg/commit/1778185d5d846dfc12182f5a6d9e181957c3e5ea to Flink 1.14 
as https://github.com/apache/iceberg/pull/3477#issuecomment-991188032
> Flink: Port TestProjectMetaColumn to Flink 1.14 to check whether should remove meta columns in source reader

- spark/v3.0/spark/src/main/java/org/apache/iceberg/spark/FileRewriteCoordinator.java
- spark/v3.0/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteDataFilesAction.java
- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/FileRewriteCoordinator.java
- spark/v3.1/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteDataFilesAction.java
This pr is to backport rewrite data files are eliminated by deletes to spark v3.0 and spark v3.1, see the pr #3724 for more detail.
cc @RussellSpitzer
> [Spark] Backport rewrite data files are eliminated by deletes to Spark v3.0 and Spark v3.1

- mr/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
- mr/src/main/java/org/apache/iceberg/mr/mapreduce/IcebergInputFormat.java
Skipping the IO config serialization (introduced [here](https://github.com/apache/iceberg/commit/da712eaf60744c933c08fe1cab7a00cdcb2f4829)), followed by injecting the config on the deserialization-side saves a lot of memory on the query coordinator (e.g. Tez AM), but this approach does not work for some of the metadata queries. 
When running standard queries, the tasks use the IO of the table object, which provides a way to inject the config via the `HadoopConfigurable` interface. However, some metadata table tasks, such as [DataFilesTable#ManifestReadTask](https://github.com/apache/iceberg/blob/master/core/src/main/java/org/apache/iceberg/DataFilesTable.java#L139) keep their own IO instance for reading, and they provide no API to replace/inject their IO instance.
We might want to tackle …
> Hive: Do not skip IO config serialization for metadata queries

- .github/workflows/jmh-bechmarks.yml
Given that we have multiple Spark project versions in the codebase and
that users might want to run a particular Benchmark from a specific
Spark version, we should make the Spark project version a parameter of
the JMH Benchmark Action.
Also running the Benchmarks is currently broken as can be seen in https://github.com/nastra/iceberg/actions/runs/1729448993.
Successful run here: https://github.com/nastra/iceberg/actions/runs/1729517779
> Parameterize spark project version for JHM Benchmarks

- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/SparkDistributionAndOrderingUtil.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/SparkWriteConf.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/TestSparkDistributionAndOrderingUtil.java
This PR changes the default distribution mode for copy-on-write DELETE. Previously, if the table was unpartitioned, unsorted and the write and delete distributions were not set, we did not request anything. It is a follow-up on the original PR.
> Spark 3.2: Revise distribution and ordering in copy-on-write DELETE

- spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestUpdate.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/SparkDistributionAndOrderingUtil.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/SparkWriteConf.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/SparkCopyOnWriteOperation.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/TestSparkDistributionAndOrderingUtil.java
This PR changes the distribution and ordering in copy-on-write UPDATEs to match the new logic in DELETEs.
> Spark 3.2: Revise distribution and ordering in copy-on-write UPDATE

- spark/v3.0/spark/src/main/java/org/apache/iceberg/spark/SparkCatalog.java
- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/SparkCatalog.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/SparkCatalog.java
This updates the time travel check in `SparkCatalog`. When loading a table from an Iceberg catalog results in a `NoSuchTableException`, the Spark catalog checks to see if the namespace is a valid table and then if the table name is a time travel name. If loading the namespace as a table fails, the original `NoSuchTableException` is thrown. But this only happened when `NoSuchTableException` was thrown by the second table load. If the Iceberg catalog instead threw `IllegalArgumentException` because the new identifier is invalid, that exception would propagate instead of the correct `NoSuchTableException`.
This updates the check so that if the namespace doesn't load as a table for any reason, the original failure is thrown.
> Spark: Fix SparkCatalog time travel check

- core/src/main/java/org/apache/iceberg/TableProperties.java
This PR removes the no longer used MERGE cardinality check property. After the refactoring, the check is always executed.
> Core: Deprecate the MERGE cardinality check property

- core/src/main/java/org/apache/iceberg/actions/BinPackStrategy.java
This PR fixes a log error for rewrite parameter max-file-size-bytes, when I set the target-file-size-bytes less than max-file-size-bytes, spark throwed a checkAgument exception "Cannot set max-file-size-bytes is greater than or equal to target-file-size-bytes, all files written will be larger than the threshold", it's puzzling, so I fix this error.
> Core: Fix the incorrectly log description in BinPackStrategy

- python/src/iceberg/io/base.py
- python/tests/io/test_base.py
**UPDATE**: This has been updated to only include the abstract base classes `FileIO`, `InputFile`, and `OutputFile`. The `S3FileIO` implementation can be opened in a follow-up PR.
---
This brings over the `FileIO` abstraction and includes an `S3FileIO` implementation. Implementing `FileIO` requires overriding the `__enter__()` and `__exit__()` methods where the `__enter__()` method sets a byte stream to `self.byte_stream`.
There's been a few discussions lately around file io and hopefully, this PR helps continue that. I think we should aim to maintain the file io abstraction for all file io operations (metadata files, manifest lists, manifest files, and data files) and allow the flexibility to plug in either an implementation that's packaged with the library or a custom implementation of …
> Add FileIO, InputFile, and OutputFile abstract base classes

- core/src/main/java/org/apache/iceberg/io/ResolvingFileIO.java
- Add no-arg constructor in `ResolvingFileIO` (maintaining consistency with `S3FileIO`, `HadoopFileIO`, `GCSFileIO` and `OSSFileIO`).
- Introduced static constant for `org.apache.iceberg.aws.s3.S3FileIO`
> Core: Add no-arg constructor in ResolvingFileIO

- parquet/src/main/java/org/apache/iceberg/parquet/ParquetUtil.java
- parquet/src/test/java/org/apache/iceberg/parquet/TestParquetDataWriter.java
A certain string in the input data (with a prefix of over 16 unparseable chars like high/low surrogates) triggered a NullPointerException in Parquet writer close:
```
at org.apache.iceberg.parquet.ParquetUtil.toBufferMap(ParquetUtil.java:267)
at org.apache.iceberg.parquet.ParquetUtil.footerMetrics(ParquetUtil.java:152)
at org.apache.iceberg.parquet.ParquetUtil.footerMetrics(ParquetUtil.java:85)
at org.apache.iceberg.parquet.ParquetWriter.metrics(ParquetWriter.java:151)
at org.apache.iceberg.io.DataWriter.close(DataWriter.java:78)
at org.apache.iceberg.io.BaseTaskWriter$BaseRollingWriter.closeCurrent(BaseTaskWriter.java:282)
at org.apache.iceberg.io.BaseTaskWriter$BaseRollingWriter.close(BaseTaskWriter.java:298)
at …
```
> NPE in Parquet Writer Metrics when data value max bound will overflow

- core/src/main/java/org/apache/iceberg/BaseUpdatePartitionSpec.java
- core/src/test/java/org/apache/iceberg/TestUpdatePartitionSpec.java
this PR is a followup of https://github.com/apache/iceberg/pull/3632#discussion_r776515101 . It rewrites the operation when deleting and adding the same partition col so that users will not encounter an error
specifically:
* when the user removes and adds the partition col with the same transformation and the same name, we ensure it is a no-op
* when the user remove and adds the partition col with the same transformation but DIFFERENT name, we just rewrite the remove and add as rename
We have this scenario that we need to change the partition column of a table with an API call, as said in the last PR, with the functionality in PR, we can just remove all "conflicted" column names without the burden to check whether the transformation is the same
> rewriting the operation when removing and adding the same partition col with the same transformation 

- core/src/main/java/org/apache/iceberg/DeleteFileIndex.java
- core/src/test/java/org/apache/iceberg/TableTestBase.java
- core/src/test/java/org/apache/iceberg/TestDeleteFileIndex.java
I found if the manifest only has existing files, the manifest file will be ignored. If we rewrite delete manifests (not implemented for now), this may happen.
> Core: Fix missing manifest that only has existing files

- aws/src/integration/java/org/apache/iceberg/aws/glue/TestGlueCatalogTable.java
- aws/src/main/java/org/apache/iceberg/aws/glue/IcebergToGlueConverter.java
- aws/src/test/java/org/apache/iceberg/aws/glue/TestIcebergToGlueConverter.java
some bugs fixed:
- if identity transform, duplicated column name and will fail
- use full column name, `y.z` instead of `z`
- convert null to "unknown" to avoid null pointer error
- improve dedupe logic
@jackye1995 @yyanyy
> AWS: fix Iceberg to Glue schema conversion

- core/src/main/java/org/apache/iceberg/TableProperties.java
- core/src/test/java/org/apache/iceberg/TestTableMetadata.java
- flink/v1.12/flink/src/test/java/org/apache/iceberg/flink/TestFlinkCatalogTable.java
- flink/v1.13/flink/src/test/java/org/apache/iceberg/flink/TestFlinkCatalogTable.java
- flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/TestFlinkCatalogTable.java
- hive-metastore/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java
- hive-metastore/src/test/java/org/apache/iceberg/hive/TestHiveCatalog.java
- mr/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerNoScan.java
- spark/v3.0/spark/src/test/java/org/apache/iceberg/spark/sql/TestCreateTable.java
#2123 pushes Iceberg table property values to HMS table properties. It'd be nice to add table uuid to HMS table properties as well. Uuid is critical to identify a table. This change is to support the application that wants to identify a table through its uuid by only access the HMS.
> Hive: Add table UUID to HMS table properties.

- aws/src/integration/java/org/apache/iceberg/aws/glue/TestGlueCatalogTable.java
- aws/src/main/java/org/apache/iceberg/aws/glue/IcebergToGlueConverter.java
- aws/src/test/java/org/apache/iceberg/aws/glue/TestIcebergToGlueConverter.java
based on #3887 
My organization wants to have Glue show old fields for Iceberg tables, so that people know what were the columns that were already used in the past and avoid adding the same name column.
@jackye1995 @yyanyy
> AWS: show old fields in Glue table

- aws/src/integration/java/org/apache/iceberg/aws/glue/TestGlueCatalogCommitFailure.java
- aws/src/main/java/org/apache/iceberg/aws/glue/GlueTableOperations.java
#3717 changed the exception in Glue integration test. Fix test name and behavior.
@jackye1995
> AWS: fix Glue catalog for unknown commit status

- site/docs/aws.md
Recently, Amazon EMR 6.5.0 [announced](https://aws.amazon.com/about-aws/whats-new/2022/01/amazon-emr-supports-apache-iceberg/) support of Apache Iceberg's Spark 3 Runtime.
This PR updates the docs.
> Docs: Add Amazon EMR announcement

- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/SparkWriteConf.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/TestSparkDistributionAndOrderingUtil.java
This PR changes the distribution and ordering for merge-on-read DELETE.
> Spark 3.2: Revise distribution and ordering for merge-on-read DELETE

- aws/src/integration/java/org/apache/iceberg/aws/s3/TestS3MultipartUpload.java
- aws/src/main/java/org/apache/iceberg/aws/AwsProperties.java
- aws/src/main/java/org/apache/iceberg/aws/s3/S3OutputStream.java
- aws/src/test/java/org/apache/iceberg/aws/s3/TestS3OutputStream.java
This PR adds capability to perform checksum validations on data uploads using S3 eTags. This should help in capturing hardware issues like corrupt disks that may affect the staged files generated while uploading data to S3.
> AWS: Support checksum validation with S3 eTags

- site/docs/aws.md
Update documentation to inform users of s3 checksum capability.
Tested with `mkdocs serve`.
> [AWS] Update documentation to inform users of s3 checksum capability.

- spark/v3.2/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/analysis/RewriteMergeIntoTable.scala
- spark/v3.2/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/plans/logical/NoStatsUnaryNode.scala
- spark/v3.2/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/ExtendedDataSourceV2Strategy.scala
- spark/v3.2/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/MergeRowsExec.scala
- spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMerge.java
This PR fixes the cardinality check for alternative join implementations.
The first issue is shuffle hash joins. Suppose our MERGE condition is `t.id = s.value`. If Spark chooses a shuffle hash join, then our records will be distributed by `id` but won't be ordered by `id` within the tasks. We only keep track of the last matched row while doing the cardinality check right now. If matched records are not co-located within tasks, the cardinality check will not behave correctly. We don't have this issue with sort merge joins as the order of produced records implicitly satisfies our needs.
Another issue is with broadcast nested loop joins when the target is broadcasted. In that case, if we have multiple source records that match the same target row but reside in different tasks, we won't be …
> Spark 3.2: Fix cardinality check for alternative join implementations

- dev/source-release.sh
Fix 2 issues found during release:
1. checksum uses absolute path, but should just use the relative path
2. gpg command order is wrong, causing the key configuration to be not respected
> Infra: fix release script signing and checksum commands

- rest_docs/rest-catalog-open-api.yaml
This adds two new routes to the REST catalog spec:
* `GET /v1/namespaces/{namespace}/tables/{table}` is used to load a table. This returns:
* Table-specific configuration for the catalog (e.g., a specific FileIO implementation for the table)
* The current table metadata
* `POST /v1/namespaces/{namespace}/tables/{table}` is used to commit updates a table
* The request body contains `requirements` and `updates` as in the [REST commit proposal](https://docs.google.com/document/d/1D0R3G0slssEhggH5XnIzMwsUIP-c385Qp2sjv5E7e6E/edit#heading=h.eo4x0coo8esy), but complete
* The response contains the updated table metadata
This PR includes the metadata JSON format expressed in OpenAPI to be able to return full `TableMetadata`.
Note that this updates the proposed change set slightly to account for …
> Spec: Add REST basics for TableOperations

- rest_docs/rest-catalog-open-api.yaml
I've been using various swagger & open-api CLI tools to validate the OpenAPI spec doc as we've been working on it.
I have yet to find one that I love, or that is considered "canonical", so I tend to use a handful of them as well as reference the spec. Some of the tools Ive been using include `widdershins` and others from https://openapi.tools/
For the `example` values in `schema` components, they are allowed to be expressed as a single string according to the spec (namely if they can't be properly expressed as JSON or YAML). However, some tools struggle to parse these properly and thus render the example as an explicit string.
Given that these examples can be expressed as JSON or YAML, I've updated the ones I've noticed giving trouble.
While these are technically allowed, the require care …
> SPEC - Convert string typed examples to JSON in REST API

- python_legacy/iceberg/api/types/type.py
- python_legacy/iceberg/api/types/type_util.py
- python_legacy/iceberg/api/types/types.py
MapType is missing `is_map_type()` method, so when calling it, it returns `False`.  That simply breaks the API.  I've checked and the other types are fine.  Map was the only one with such a problem.
> Python: MapType missing required methods and visit() not supporting MapType

- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/SparkReadConf.java
- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/SparkReadOptions.java
- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/source/SparkMicroBatchStream.java
- spark/v3.1/spark/src/test/java/org/apache/iceberg/spark/source/TestStructuredStreamingRead3.java
Backports https://github.com/apache/iceberg/pull/3517 to Spark 3.1 runtime.
> Spark 3.1: Add option to skip overwrites in streaming

- spark/v3.0/spark/src/main/java/org/apache/iceberg/spark/SparkReadConf.java
- spark/v3.0/spark/src/main/java/org/apache/iceberg/spark/SparkReadOptions.java
- spark/v3.0/spark/src/main/java/org/apache/iceberg/spark/source/SparkMicroBatchStream.java
- spark/v3.0/spark/src/test/java/org/apache/iceberg/spark/source/TestStructuredStreamingRead3.java
Backports https://github.com/apache/iceberg/pull/3517 to Spark 3.0 runtime.
> Spark 3.0: Add option to skip overwrites in streaming

- hive3/src/main/java/org/apache/iceberg/mr/hive/vector/HiveVectorizedReader.java
- hive3/src/main/java/org/apache/iceberg/mr/hive/vector/ParquetSchemaFieldNameVisitor.java
- mr/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergInputFormat.java
- mr/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
- mr/src/main/java/org/apache/iceberg/mr/mapreduce/IcebergInputFormat.java
- mr/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerWithEngine.java
Adding support or Parquet vectorization. Similarly to how this was done with ORC, we are reusing the already implemented Parquet vectorized read implementation of Hive. It is hooked into IcebergInputFormat to create the record reader from the split and fileScanTask information.
This change also reuses parts of the proposed solution in https://github.com/apache/iceberg/pull/3242 by @tprelle so that query plans that failed to get vectorized during Hive query compilation are correctly falling back to the non-vectorized read path.
> Hive: Parquet vectorization support for Hive 3

- site/docs/spark-procedures.md
This closes https://github.com/apache/iceberg/issues/4007
As of Iceberg 0.13.0, the Spark stored procedures `expire_snapshots` and `remove_orphan_files` have an added parameter, `max_concurrent_deletes`, which indicates the size of the thread pool that should be instantiated to remove the relevant files in parallel.
Without this parameter, no separate thread pool is instantiated and the files are deleted sequentially in the current thread. For a high volume of deletes, this can be slow. Moreover, we should document every public parameter to procedures.
> [Site] - Document max_concurrent_deletes parameter in spark stored procedures.

- spark/v3.2/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/RowLevelCommandScanRelationPushDown.scala
- spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMerge.java
This PR fixes predicate pushdown in row-level operations in Spark 3.2. Previously, we would not extract filters and MERGE conditions such as `t.id = s.id and t.dep IN ('hr')` would not be pushed down.
> Spark 3.2: Fix predicate pushdown in row-level operations

- rest_docs/rest-catalog-open-api.yaml
This and closes https://github.com/apache/iceberg/issues/4026
In some places in the OpenAPI spec for the REST catalog, we're using `response` type components where `schema` type components are expected and vice versa.
This passes many parsers (we're still on the hunt for a canonical parser), but I've been using a NodeJS / NPM module from https://openapi.tools called `openapi-spec-validator`. It can be installed, hopefully with an up to date nodejs, using `npm install -h openapi-spec-validator`.
The output is kind of cryptic, but once it gets to `OK` then it's `OK`.
This PR fixes any issues from that with the minimal change set possible (barring one schema name change to make things a bit more clear).
1. Renamed `StandardErrorWrapper`, the inner base schema element for …
> Spec: Fix REST response objects

- site/docs/how-to-verify-a-release.md
Adds `--check` option to `shasum` command for verifying checksum of a release. 
```
➜  my-release-verification git:(master) ✗ shasum -a 512 --check apache-iceberg-0.13.0.tar.gz.sha512
apache-iceberg-0.13.0.tar.gz: OK
```
> Docs: Add --check to verify checksum doc

- spark/v3.0/spark/src/main/java/org/apache/iceberg/spark/SparkCatalog.java
- spark/v3.0/spark/src/test/java/org/apache/iceberg/spark/sql/TestCreateTable.java
- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/SparkCatalog.java
- spark/v3.1/spark/src/test/java/org/apache/iceberg/spark/sql/TestCreateTable.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/SparkCatalog.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/sql/TestCreateTable.java
This is a functional regression issue in Iceberg 0.13.0. At least in Iceberg 0.12.x(I do not test every previous version), Iceberg allows creating table under the root namespace of hadoop catalog, but #3722 broke it.
Use Spark 3.2.0 and Iceberg 0.13.0, error occurs when trying to create table under root namespace of hadoop catalog.
```
java.sql.SQLException: Error operating EXECUTE_STATEMENT: java.lang.NegativeArraySizeException
at java.lang.reflect.Array.newArray(Native Method)
at java.lang.reflect.Array.newInstance(Array.java:75)
at java.util.Arrays.copyOf(Arrays.java:3212)
at java.util.Arrays.copyOf(Arrays.java:3181)
at org.apache.iceberg.spark.SparkCatalog.namespaceToIdentifier(SparkCatalog.java:570)
at org.apache.iceberg.spark.SparkCatalog.load(SparkCatalog.java:492)
at …
```
> Spark: Allow create table in hadoop catalog root namespace

- python/src/iceberg/types.py
- python/src/iceberg/utils/bin_packing.py
- python/tests/io/test_base.py
- python/tests/utils/test_bin_packing.py
- python/tox.ini
This adds `--line-length` to the black autoformatter and format checker commands in tox.ini
This may cause some open PRs to require rebasing (there's never a good time to change an auto-formatter) but alternatively we can keep this PR open and wait for a dip in open PRs to rebase this PR, run `tox -e format`, and commit the updates.
The first commit [fcddb35](https://github.com/apache/iceberg/pull/4025/commits/fcddb3545a1aa28184d8860a075207cb1a0f2fdc) is the actual change to the formatter, the second commit [66325f4](https://github.com/apache/iceberg/pull/4025/commits/66325f4d7e3a784fca08ae8b8930c7f74476395d) is the result of running `tox -e format` on the project.
> Set black line-length to 130 in tox settings

- api/src/main/java/org/apache/iceberg/SnapshotRef.java
- api/src/main/java/org/apache/iceberg/SnapshotRefType.java
- api/src/test/java/org/apache/iceberg/TestSnapshotRef.java
Co-authored-by: wangzeyu <1249369293@qq.com>
Co-authored-by: Jack Ye <yzhaoqin@amazon.com>
This is a smaller PR as part of breaking up the changes in https://github.com/apache/iceberg/pull/3883/files. This change includes the SnapshotRef entity in the Iceberg API.
Will include serializing/deserializing reference metadata, and reference/table API changes in separate PRs following this.
> Core: Add SnapshotRef entity to API

- python/tox.ini
During our tox run we call black with `--check` to validate that there are no formatting suggestions unaddressed. When that validation fails, the CI logs will show something like this:
```
would reformat src/iceberg/types.py
Oh no! 💥 💔 💥
1 file would be reformatted, 15 files would be left unchanged.
```
I find that it's helpful to show the line diff, as an example:
```
linters run-test: commands[2] | black --line-length 130 --check --diff setup.py src tests
--- src/iceberg/types.py	2022-02-03 15:58:58.471627 +0000
+++ src/iceberg/types.py	2022-02-03 15:59:03.477538 +0000
@@ -60,11 +60,11 @@
return self._is_primitive
class FixedType(Type):
def __init__(self, length: int):
-        super().__init__(f'fixed[{length}]', f"FixedType(length={length})", is_primitive=True)
+ …
```
> Add --diff to show the line diff when black fails

- .asf.yaml
This PR removes the publish directive from `.asf.yaml`. This should be merged before merging [PR #36](https://github.com/apache/iceberg-docs/pull/36) in apache/iceberg-docs which adds the publish directive there.
> Remove the publish directive from .asf.yaml

- spark/v3.2/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/analysis/RewriteDeleteFromTable.scala
- spark/v3.2/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/analysis/RewriteMergeIntoTable.scala
- spark/v3.2/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/analysis/RewriteUpdateTable.scala
As mentioned [here](https://github.com/apache/iceberg/pull/3984/files#r798156043), certain `RowLevelOperationTable` usages are a bit confusing. This PR attempts to rename some vars to avoid the ambiguity.
> Spark 3.2: Rename variables referring to RowLevelOperationTable

- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/SparkScanBuilder.java
This PR removes no longer used methods and variables in `SparkScanBuilder` in Spark 3.2.
> Spark 3.2: Remove unused methods and variables in SparkScanBuilder

- python_legacy/iceberg/hive/hive_tables.py
This is to enable kerberized HMS support.
> [python legacy] Support passing customized protocol for hms client

- core/src/main/java/org/apache/iceberg/io/BaseTaskWriter.java
- core/src/main/java/org/apache/iceberg/io/DataWriter.java
The DataWriter::add is deprecated in 0.13 and will be removed in 0.14.
BaseRollingWriter should stop using the deprecated add() method.
Moreover, if a subclass of BaseRollingWriter only overrides the write()
method, add() should honor that.
In this patch I did not remove all calls to `DataWriter::add` in tests. May update that as well?
> Core: BaseRollingWriter to use DataWriter::write instead of DataWriter::add

- api/src/main/java/org/apache/iceberg/SnapshotRef.java
- core/src/main/java/org/apache/iceberg/SnapshotRefParser.java
- core/src/main/java/org/apache/iceberg/util/JsonUtil.java
- core/src/test/java/org/apache/iceberg/TestSnapshotRefParser.java
This change adds serialization and parsing logic for SnapshotReferences. We do not yet call this in the Metadata serialization logic, that will be in a separate PR.
Co-authored-by: wangzeyu <1249369293@qq.com>
Co-authored-by: Jack Ye <yzhaoqin@amazon.com>
> Core: SnapshotRef parser and serialization logic

- rest_docs/rest-catalog-open-api.yaml
The current 200 response to create a namespace, is simply `{ "created": true }`. This doesn't provide much useful information.
Updating the spec to instead return the name of the namespace that was created, as well as any properties that were stored on the namespace (including any the server might have added).
Returning the namespace and actual properties means the caller doesn't have to immediately send a GET request to access this information.
The new 200 response will look like the following (in this situation we can assume `created_at` was added by the server).
`{ "namespace": ["accounting"], "properties": {"owner": "Hank", "created_at": "1452120468" }`
This still passes parsing according to a variety of openapi tools.
```bash
$ openapi-spec-validator …
```
> SPEC - Update the REST catalog's CreateNamespaceResponse to provide more useful info

- core/src/test/java/org/apache/iceberg/avro/TestAvroDataWriter.java
- data/src/test/java/org/apache/iceberg/data/orc/TestOrcDataWriter.java
- data/src/test/java/org/apache/iceberg/io/TestAppenderFactory.java
- data/src/test/java/org/apache/iceberg/io/TestFileWriterFactory.java
- data/src/test/java/org/apache/iceberg/io/TestGenericSortedPosDeleteWriter.java
- data/src/test/java/org/apache/iceberg/io/TestWriterMetrics.java
- parquet/src/test/java/org/apache/iceberg/parquet/TestParquetDataWriter.java
This is a follow-up change of #4048
I searched from IntelliJ and did not find any other usages of the deprecated `DataWriter::add` method.
> Tests: Replace DataWriter::add with DataWriter::write in tests

- api/src/test/java/org/apache/iceberg/types/TestConversions.java
- python_legacy/iceberg/api/types/conversions.py
- python_legacy/iceberg/api/types/type_util.py
- python_legacy/tests/api/test_conversions.py
python_legacy was missing support for Decimal conversion.  An error would be raised every time such a conversion happened:
```
File "/home/.local/lib/python3.8/site-packages/iceberg/api/types/conversions.py", line 93, in from_byte_buffer
[2022-01-25, 17:16:23 UTC] {custom_pod_launcher.py:53} INFO -     return Conversions.internal_from_byte_buffer(type_var.type_id, buffer_var)
[2022-01-25, 17:16:23 UTC] {custom_pod_launcher.py:53} INFO -   File "/home/.local/lib/python3.8/site-packages/iceberg/api/types/conversions.py", line 98, in internal_from_byte_buffer
[2022-01-25, 17:16:23 UTC] {custom_pod_launcher.py:53} INFO -     return Conversions.from_byte_buff_mapping.get(type_id)(type_id, buffer_var)
[2022-01-25, 17:16:23 UTC] {custom_pod_launcher.py:53} INFO - TypeError: 'NoneType' object is …
```
> Python: Add Decimal type conversion

- core/src/main/java/org/apache/iceberg/TableMetadata.java
- core/src/main/java/org/apache/iceberg/TableMetadataParser.java
- core/src/test/java/org/apache/iceberg/TestTableMetadata.java
To help unblock any development on TableMetadata Builder API changes, we can add the reference mapping structure to TableMetadata (and perform basic validation on this structure).
Co-authored-by: @hameizi 1249369293@qq.com
Co-authored-by: @jackye1995 yzhaoqin@amazon.com
Note: In this change we do not include deserializing the metadata. I can include that if it helps with any testing (we can't really do serialization until we conclude on an API), or if it provides more context to this change. For now left it off in favor of keeping the change small.
Let me know your thoughts!
@rdblue @jackye1995
> Core: Add reference structures to TableMetadata to unblock TableMetadata API changes

- flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkManifestUtil.java
- flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/IcebergFilesCommitter.java
- flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/ManifestOutputFileFactory.java
- flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkManifest.java
- flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/sink/TestIcebergFilesCommitter.java
- spark/v3.0/spark/src/main/java/org/apache/iceberg/spark/SparkCatalog.java
- spark/v3.0/spark/src/test/java/org/apache/iceberg/spark/sql/TestCreateTable.java
- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/SparkCatalog.java
- spark/v3.1/spark/src/test/java/org/apache/iceberg/spark/sql/TestCreateTable.java
- spark/v3.2/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/RowLevelCommandScanRelationPushDown.scala
- spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMerge.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/SparkCatalog.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/sql/TestCreateTable.java
Cherry-pick commits from milestone 0.13.1 https://github.com/apache/iceberg/milestone/17 onto the 0.13.x branch.
This includes these changes:
https://github.com/apache/iceberg/pull/3986
https://github.com/apache/iceberg/pull/4023
https://github.com/apache/iceberg/pull/4024
> 0.13.1 Cherry-Picks

- core/src/main/java/org/apache/iceberg/TableProperties.java
- core/src/main/java/org/apache/iceberg/avro/Avro.java
Addressing issue https://github.com/apache/iceberg/issues/3206
This change adds support for reading and writing ZSTD compressed Avro Data. ZSTD tends to optimize more for speed over GZIP (at the tradeoff of compression ratio). In this change we also allow for configurable ZSTD compression levels via table properties.
> Core: Add support for writing and reading ZSTD Avro Data

- docs/common/releases/how-to-verify-a-release.md
- docs/versioned/api/java-api.md
- docs/versioned/integrations/aws.md
- docs/versioned/integrations/jdbc.md
- docs/versioned/integrations/nessie.md
- docs/versioned/spark/spark-getting-started.md
Made core pr of this Docs PR
https://github.com/apache/iceberg-docs/pull/48/files
Basically our issue is that the current quick-start commands to do not work with the now default download method of spark "3.2" so I updated the references so they use the correct artifact.
> Docs: Update Release Artifacts in Quickstart Commands for Spark

- flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/FlinkConfigOptions.java
- flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/source/FlinkInputFormat.java
- flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/source/FlinkInputSplit.java
- flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/source/FlinkSource.java
- flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/source/FlinkSplitPlanner.java
- flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/source/ScanContext.java
- flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/source/TestFlinkScanSql.java
Closes https://github.com/apache/iceberg/issues/3816
> FlinkInputSplit extends LocatableInputSplit instread of InputSplit, get the location of all files in CombinedScanTask and replace DefaultInputSplitAssigner with LocatableInputSplitAssigner.
> Flink: FlinkInputSplit extends LocatableInputSplit instread of InputSplit

- docs/common/community/blogs.md
- docs/common/community/contribute.md
- docs/common/community/join.md
- docs/common/community/talks.md
- docs/versioned/community/blogs.md
- docs/versioned/community/contributing.md
- docs/versioned/community/talks.md
Currently, most of the details for contributing are on https://github.com/apache/iceberg/blob/master/CONTRIBUTING.md.
Since the Iceberg website should be the go-to for this information, and there is
enough unique content for contributing we can have a separate page for this on the site.
> Docs: Add separate contributing page for Iceberg website.

- core/src/main/java/org/apache/iceberg/MetricsConfig.java
- core/src/main/java/org/apache/iceberg/TableProperties.java
- data/src/test/java/org/apache/iceberg/io/TestWriterMetrics.java
- flink/v1.12/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkWriterMetrics.java
- flink/v1.13/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkWriterMetrics.java
- flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkWriterMetrics.java
- spark/v2.4/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkWriterMetrics.java
- spark/v3.0/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkWriterMetrics.java
- spark/v3.1/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkWriterMetrics.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkWriterMetrics.java
Giving a try to the suggestion in the last community sync to address very-wide-table.
This changes the default MetricsMode from "truncate(16)" to "none" if there are over 100 columns (should it be counts?).  This is overriden if the user explicitly sets a default, and of course if a user explicitly sets metrics on a particular column.
> Disable metrics for very wide tables to reduce metadata size

- core/src/main/java/org/apache/iceberg/io/BaseTaskWriter.java
- data/src/test/java/org/apache/iceberg/io/TestTaskEqualityDeltaWriter.java
- flink/v1.12/flink/src/test/java/org/apache/iceberg/flink/sink/TestDeltaTaskWriter.java
- flink/v1.13/flink/src/test/java/org/apache/iceberg/flink/sink/TestDeltaTaskWriter.java
- flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/sink/TestDeltaTaskWriter.java
Previous delete logic is write all delete data in eq-delete file although there is same key in pos-delete file.  This PR change this logic to just write the delete data what is not exist in pos-delete file in eq-delete file.  And the old logic will send several delete but one insert of one primary key in one snapshot when we want reperform the data by streaming read, in some scene will cause error (like aggregete count). 
the following is difference between old delete logic and the new. 
table schema: 
```
int key;  (primary key) 
string data;
``` 
**old logic:** 
tx1: 
> insert (1,'aa'); 
tx2: 
>delete (1,'aa');   -->eq-delete file add (1,'aa') 
> insert(1,'bb'); 
>delete (1,'bb');   -->eq-delete file add (1,'bb') pos-delete file add(1,filepath) 
>insert(1,'cc') 
result: 
eq-delete file …
> change delete logic

- docs/versioned/spark/spark-getting-started.md
The spark runtime jar link isn't rendered correctly in the hint on this page: https://iceberg.apache.org/docs/latest/getting-started/
This fixes that by pointing to the the Spark 3.2_2.12 jar. Another option is to just point this to `/releases`.
> Fix spark runtime jar link

- api/src/main/java/org/apache/iceberg/SnapshotRef.java
- core/src/main/java/org/apache/iceberg/MetadataUpdate.java
- core/src/main/java/org/apache/iceberg/SnapshotProducer.java
- core/src/main/java/org/apache/iceberg/TableMetadata.java
- nessie/src/main/java/org/apache/iceberg/nessie/NessieTableOperations.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSourceTablesBase.java
This updates the `TableMetadata.Builder` methods and replaces the previous `setCurrentSnapshot` with a branch-aware `setBranchSnapshot`.
I'm posting this for early feedback. This is the most straight-forward change, but it doesn't support modifying the ref settings like max age and it doesn't support creating/removing tags. We may want to change the builder API to be more generic and if so this is a step toward that API.
> Core: Replace setCurrentSnapshot with setBranchSnapshot in metadata builder

- core/src/main/java/org/apache/iceberg/BaseTransaction.java
- core/src/main/java/org/apache/iceberg/CherryPickOperation.java
- core/src/main/java/org/apache/iceberg/SetSnapshotOperation.java
- core/src/main/java/org/apache/iceberg/SnapshotManager.java
- core/src/test/java/org/apache/iceberg/TestSnapshotManager.java
- core/src/test/java/org/apache/iceberg/TestWapWorkflow.java
- spark/v3.0/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestCherrypickSnapshotProcedure.java
- spark/v3.1/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestCherrypickSnapshotProcedure.java
- spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestCherrypickSnapshotProcedure.java
This updates the implementation of `ManageSnapshots` to internally use a `Transaction`. Using `Transaction` as a base allows the API to make multiple changes in a single commit. For example, picking more than one snapshot into the current branch is now supported.
The previous implementation of `ManageSnapshots` supported setting the current snapshot, rolling back to a previous snapshot, and cherry picking a commit. Cherry picking is now handled by `CherryPickOperation` and the other operations that update the current snapshot are handled by `SetSnapshotOperation`. These are split because the set snapshot operation is much simpler and doesn't need to be mixed with cherry picking. Cherry picking is mostly unchanged.
The two new operations make a single change to the table state and are …
> Core: Update SnapshotManager to use a transaction

- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/procedures/BaseProcedure.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/procedures/ExpireSnapshotsProcedure.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/procedures/RemoveOrphanFilesProcedure.java
Previously executor services were left to be GC'd, instead now they are
shutdown immediately after the action completes.
> Spark: Close executor services after action completes in Procedures

- core/src/main/java/org/apache/iceberg/avro/AvroSchemaUtil.java
- core/src/main/java/org/apache/iceberg/avro/BuildAvroProjection.java
- core/src/main/java/org/apache/iceberg/avro/HasIds.java
- core/src/main/java/org/apache/iceberg/avro/MissingIds.java
- core/src/test/java/org/apache/iceberg/avro/TestAvroSchemaProjection.java
- core/src/test/java/org/apache/iceberg/avro/TestBuildAvroProjection.java
https://github.com/apache/iceberg/issues/4072
Purpose: Keeping the ID properties for list and map node when projecting
@RussellSpitzer
> Avro: Fix BuildAvroProjection list and map handling to preserve field IDs

- api/src/main/java/org/apache/iceberg/io/FileIOMetricsContext.java
- api/src/main/java/org/apache/iceberg/metrics/MetricsContext.java
- aws/src/main/java/org/apache/iceberg/aws/s3/BaseS3File.java
- aws/src/main/java/org/apache/iceberg/aws/s3/S3FileIO.java
- aws/src/main/java/org/apache/iceberg/aws/s3/S3InputFile.java
- aws/src/main/java/org/apache/iceberg/aws/s3/S3InputStream.java
- aws/src/main/java/org/apache/iceberg/aws/s3/S3OutputFile.java
- aws/src/main/java/org/apache/iceberg/aws/s3/S3OutputStream.java
- aws/src/test/java/org/apache/iceberg/aws/s3/TestS3OutputStream.java
- core/src/main/java/org/apache/iceberg/hadoop/HadoopMetricsContext.java
This PR adds a basic interface for reporting FileIO metrics and a shim implementation for reporting IO metrics via the Hadoop `FileSystem.Statistics` to be compatible with how Spark/Flink gather and report task metrics.
> Add MetricsContext to enable metrics tracking with initial S3FileIO implementation

- core/src/main/java/org/apache/iceberg/SnapshotProducer.java
- core/src/main/java/org/apache/iceberg/TableMetadata.java
While testing rollback_to_snaphot feature, we found that this is feature is failing in some cases.
In the setSetCurrentSnapshot method '[null](https://github.com/apache/iceberg/blob/apache-iceberg-0.13.0/core/src/main/java/org/apache/iceberg/TableMetadata.java#L924)' is being passed for timestamp which eventually causes the failure of the following [precondition check](https://github.com/apache/iceberg/blob/apache-iceberg-0.13.0/core/src/main/java/org/apache/iceberg/TableMetadata.java#L306).  The timeStamp should also be passed along with the Snapshot just like [here](https://github.com/apache/iceberg/blob/apache-iceberg-0.13.0/core/src/main/java/org/apache/iceberg/TableMetadata.java#L938 )
This PR fixes this bug in 0.13.x. I tested this with our internal tests and also by running the …
> Core: Call the replaceCurrentSnapshot with snapshotId for rollback operations

- spark/v3.0/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestDelete.java
- spark/v3.1/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestDelete.java
- spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestDelete.java
Tries to fix #4090 
(Copied from my comment there)
From the log, the expected exception seems still a validationException, just not from the distributed Spark delta-writer job as is expected but rather from the non-distributed metadata-only version.  Ref:
Expected: an instance of org.apache.spark.SparkException
but: <java.lang.IllegalArgumentException: Failed to cleanly delete data files matching: ref(name="id") == 1> is a java.lang.IllegalArgumentException
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
That's from here (the metadata-only version):
https://github.com/apache/iceberg/blob/master/spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/SparkTable.java#L271
Although most of the time it will hit the distributed delta delete, there is a chance here it …
> Fix random test failure of testDeleteWithSerializableIsolation

- core/src/main/java/org/apache/iceberg/TableProperties.java
- parquet/src/main/java/org/apache/iceberg/parquet/Parquet.java
- parquet/src/main/java/org/apache/iceberg/parquet/ParquetWriter.java
- parquet/src/test/java/org/apache/iceberg/parquet/TestParquet.java
- spark/v2.4/spark/src/test/java/org/apache/iceberg/spark/data/parquet/vectorized/TestParquetDictionaryEncodedVectorizedReads.java
- spark/v3.0/spark/src/test/java/org/apache/iceberg/spark/data/parquet/vectorized/TestParquetDictionaryEncodedVectorizedReads.java
- spark/v3.1/spark/src/test/java/org/apache/iceberg/spark/data/parquet/vectorized/TestParquetDictionaryEncodedVectorizedReads.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/data/parquet/vectorized/TestParquetDictionaryEncodedVectorizedReads.java
This is useufl when we want to use smaller row group size. In the past, we also found that tuning these configurations to smaller value is important lto avoid OOM problem when there are large records (like MBs). E.g., in the past, we have set the min/max check count default to 10/100 by default for the Flink streaming ingestion part. The performance impact is very insignificant. For streams with large records, we have even set the min/max to much smaller value like 1/5.
> Parquet: make row group check (min and max record count) configurable.

- core/src/main/java/org/apache/iceberg/TableMetadata.java
#4135 fixed a regression in 0.13.x by porting part of #4089, but accidentally added an unused method to `TableMetadata`. We remove it in this follow-up.
> Core: Remove unused method accidentally added to TableMetadata

- spark/v3.0/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestDelete.java
- spark/v3.0/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestUpdate.java
- spark/v3.1/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestDelete.java
- spark/v3.1/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestUpdate.java
[SPARK-33267](https://issues.apache.org/jira/browse/SPARK-33267) has been fixed in Spark 3.0.2/3.1.0.
> Spark: Enable test which was blocked by SPARK-33267

- api/src/test/java/org/apache/iceberg/transforms/TestBucketing.java
In PR https://github.com/apache/iceberg/pull/3815, I made a mistake and left out the fix for the unit test. `murmur3_32` should be replaced with `murmur3_32_fixed`.
> Test: Use murmur3_32_fixed in unit test

- spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestExpireSnapshotsProcedure.java
Adding a test to demonstrate how to age off delete files and eventually remove them by expire snapshots.
> Add unit test for ExpireSnapshot with DeleteFile

- flink/v1.12/build.gradle
- flink/v1.13/build.gradle
- flink/v1.14/build.gradle
- settings.gradle
As apache flink usually will release a version with two scala version, but we apache iceberg only support scala 2.12 now. So here I publish a PR to support configurable scala version for building flink iceberg module.
We can use the following command to build flink runtime modules for scala 2.12: 
```bash
./gradlew clean build -x test -DflinkVersions=1.12,1.13,1.14 \
-DscalaVersion=2.12 \
-DknownScalaVersions=2.12 \
-x javadoc -Pquick \
-DsparkVersions= -DhiveVersions=
```
Their packaged jar are looks like:
```
➜  iceberg git:(add-flink-scala-version) find  flink/ | grep jar | grep v1                                                                                                                             
flink//v1.12/flink/build/libs/iceberg-flink-1.12_2.11-0.13.0-SNAPSHOT-tests.jar …
```
> Flink: Support configurable Scala version.

- python_legacy/iceberg/hive/hive_tables.py
- python_legacy/tests/hive/test_hive_tables.py
According to https://github.com/gglanzani/hmsclient/blob/master/hmsclient/hmsclient.py#L42 the hms host and port is not used, thus not required, when `iprot` is presented. 
While the current iceberg `get_client()` implementation requires hms host and port to present. This diff is to make such requirement optional when `iprot` is presented in conf.
> [python legacy] skipping required hms host and port when iprot field is presented in conf

- docs/versioned/integrations/aws.md
Recently we upgraded AWS SDK version to `2.17.131` in https://github.com/apache/iceberg/pull/4153. This PR updates the site docs.
> Docs: Update AWS SDK version in site doc

- spark/v2.4/spark/src/jmh/java/org/apache/iceberg/spark/data/parquet/SparkParquetWritersFlatDataBenchmark.java
- spark/v3.0/spark/src/jmh/java/org/apache/iceberg/spark/data/parquet/SparkParquetWritersFlatDataBenchmark.java
- spark/v3.1/spark/src/jmh/java/org/apache/iceberg/spark/data/parquet/SparkParquetWritersFlatDataBenchmark.java
- spark/v3.2/spark/src/jmh/java/org/apache/iceberg/spark/data/parquet/SparkParquetWritersFlatDataBenchmark.java
This PR fixes a minor issue for a jmh test - `SparkParquetWritersFlatDataBenchmark`
The `dataFile` holds mocked outputs now cleaned at `Level.Trial` which will be executed after the set of benchmark iterations. Then, it cause errors like below.
```java
org.apache.iceberg.exceptions.AlreadyExistsException: File already exists: /Users/kentyao/iceberg/spark/v3.2/spark/build/tmp/jmh/parquet-flat-data-benchmark3385433263675547096.parquet
at org.apache.iceberg.Files$LocalOutputFile.create(Files.java:58)
at org.apache.iceberg.parquet.ParquetIO$ParquetOutputFile.create(ParquetIO.java:148)
```
In this PR, I set the TearDown level to Iteration to make the dataFile be deleted after each iteration.
> [Spark] Delete dataFile on iteration level in SparkParquetWritersFlatDataBenchmark

- api/src/main/java/org/apache/iceberg/catalog/Namespace.java
- core/src/main/java/org/apache/iceberg/catalog/TableIdentifierParser.java
- core/src/main/java/org/apache/iceberg/rest/RESTSerializers.java
- core/src/main/java/org/apache/iceberg/rest/requests/CreateNamespaceRequest.java
- core/src/main/java/org/apache/iceberg/rest/requests/UpdateNamespacePropertiesRequest.java
- core/src/main/java/org/apache/iceberg/rest/responses/CreateNamespaceResponse.java
- core/src/main/java/org/apache/iceberg/rest/responses/DropNamespaceResponse.java
- core/src/main/java/org/apache/iceberg/rest/responses/GetNamespaceResponse.java
- core/src/main/java/org/apache/iceberg/rest/responses/ListNamespacesResponse.java
- core/src/main/java/org/apache/iceberg/rest/responses/ListTablesResponse.java
- core/src/main/java/org/apache/iceberg/rest/responses/UpdateNamespacePropertiesResponse.java
- core/src/main/java/org/apache/iceberg/util/JsonUtil.java
- core/src/test/java/org/apache/iceberg/catalog/TestTableIdentifierParser.java
- core/src/test/java/org/apache/iceberg/rest/RequestResponseTestBase.java
- core/src/test/java/org/apache/iceberg/rest/requests/TestCreateNamespaceRequest.java
- core/src/test/java/org/apache/iceberg/rest/requests/TestUpdateNamespacePropertiesRequest.java
- core/src/test/java/org/apache/iceberg/rest/responses/TestCreateNamespaceResponse.java
- core/src/test/java/org/apache/iceberg/rest/responses/TestDropNamespaceResponse.java
- core/src/test/java/org/apache/iceberg/rest/responses/TestGetNamespaceResponse.java
- core/src/test/java/org/apache/iceberg/rest/responses/TestListNamespacesResponse.java
- core/src/test/java/org/apache/iceberg/rest/responses/TestListTablesResponse.java
- core/src/test/java/org/apache/iceberg/rest/responses/TestUpdateNamespacePropertiesResponse.java
This PR introduces some of the request and response objects from the REST catalog spec, as well as a set of Jackson based serializers & deserializers that can be used to read and write some of the components as JSON.
Opening this PR to get some initial request / responses that are already defined in the spec under review as well as helping provide some serializers for some components using Jackson, which are needed in the Trino project.
1. CreateNamespaceRequest / CreateNamespaceResponse
2. UpdateNamespacePropertiesRequest / UpdateNamespacePropertiesResponse
3. DropNamespaceResponse (request relies on only the route and has no request body)
4. GetNamespaceResponse (request has no body)
5. ListNamespacesResponse (request has no body, just the query parameter variables)
6. …
> REST Catalog - Initial request / response objects and Jackson-based SerDe module for some components

- spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestExpireSnapshotsProcedure.java
- spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRemoveOrphanFilesProcedure.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/data/TestHelpers.java
Simple test for validating remove orphans work with Delete Files, in particular that they do _not_ remove the delete files.
> Test: Add test for remove orphan files with delete files

- .github/workflows/jmh-bechmarks.yml
- spark/v2.4/spark/src/jmh/java/org/apache/iceberg/spark/data/parquet/SparkParquetWritersNestedDataBenchmark.java
- spark/v3.0/spark/src/jmh/java/org/apache/iceberg/spark/data/parquet/SparkParquetWritersNestedDataBenchmark.java
- spark/v3.1/spark/src/jmh/java/org/apache/iceberg/spark/data/parquet/SparkParquetWritersNestedDataBenchmark.java
- spark/v3.2/spark/src/jmh/java/org/apache/iceberg/spark/data/parquet/SparkParquetWritersNestedDataBenchmark.java
This PR fixs jmh Spark parquet benchmark, now the SparkParquetWritersFlatDataBenchmark throws the following exception:
```
org.apache.iceberg.exceptions.AlreadyExistsException: File already exists: /Users/zhongyujiang/projects/github/iceberg/spark/v3.2/spark/build/tmp/jmh/parquet-flat-data-benchmark6286636693589332554.parquet
at org.apache.iceberg.Files$LocalOutputFile.create(Files.java:58)
at org.apache.iceberg.parquet.ParquetIO$ParquetOutputFile.create(ParquetIO.java:148)
at org.apache.parquet.hadoop.ParquetFileWriter.<init>(ParquetFileWriter.java:329)
at org.apache.parquet.hadoop.ParquetFileWriter.<init>(ParquetFileWriter.java:305)
at org.apache.parquet.hadoop.ParquetFileWriter.<init>(ParquetFileWriter.java:284)
at org.apache.iceberg.parquet.ParquetWriter.ensureWriterInitialized(Parquet …
```
> Spark: Fix jmh Spark parquet benchmark

- core/src/main/java/org/apache/iceberg/TableProperties.java
This PR aligns the definition style of default Parquet page sizes to match what we have in all other properties.
> Core: Use consistent constant definition for Parquet page sizes

- api/src/main/java/org/apache/iceberg/actions/DeleteOrphanFiles.java
- api/src/main/java/org/apache/iceberg/actions/ExpireSnapshots.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/actions/BaseDeleteOrphanFilesSparkAction.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/actions/BaseDeleteReachableFilesSparkAction.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/actions/BaseExpireSnapshotsSparkAction.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/actions/BaseSparkAction.java
This PR fixes the name of the method that reads both data and delete files but claims to read only data files.
> Spark 3.2: Fix names of methods that read all content files in actions

- core/src/main/java/org/apache/iceberg/TableProperties.java
- spark/v2.4/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkTableUtilWithInMemoryCatalog.java
This PR enables vectorized Parquet reads by default. This feature has been available for quite some time and being used by multiple companies in prod. I do anticipate more bugs to be found when we enable this by default but I think there is sufficient confidence it will perform reasonably well in most cases.
> Parquet: Enable vectorized reads by default

- docs/common/format/spec.md
i noticed that the numeration in that section started with the wrong number, which is extra confusing because we refer back to "step 1" further down.
also as a first time reader seeing `<uuid>` when the previous section used `<random-uuid>` made me wonder if there is an important difference.
but looking at the code, it doesnt seem to be the case:
```
~/code/iceberg$ ag "UUID\." core/src/main/java/org/apache/iceberg/hadoop/HadoopTableOperations.java
150:    Path tempMetadataFile = metadataPath(UUID.randomUUID().toString() + fileExtension);
289:      Path tempVersionHintFile = metadataPath(UUID.randomUUID().toString() + "-version-hint.temp");
427:      Preconditions.checkState(newUUID.equals(currentMetadata.uuid()),
~/code/iceberg$ ag "UUID\." …
```
> Docs: fix numeration in Metastore Tables section

- api/src/main/java/org/apache/iceberg/Schema.java
- api/src/main/java/org/apache/iceberg/types/ReassignIds.java
- api/src/main/java/org/apache/iceberg/types/TypeUtil.java
- core/src/main/java/org/apache/iceberg/TableProperties.java
- core/src/main/java/org/apache/iceberg/types/FixupTypes.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/SparkConfParser.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/SparkSchemaUtil.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/SparkWriteConf.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/SparkWriteOptions.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/SparkTable.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/SparkWriteBuilder.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/SparkTestBase.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/source/TestDataFrameWriterV2.java
Some Spark tables support an option, `mergeSchema`, that will update the table schema on write if the incoming data has extra columns. This adds support for the `mergeSchema` option as well as an Iceberg alias, `merge-schema`.
In order to add this functionality, this PR adds a new table property, `write.spark.accept-any-schema`. This adds the Spark DSv2 capability `ACCEPT_ANY_SCHEMA` to the Spark table. This will bypass Spark's schema validation checks and use Iceberg's instead. As a result, this fixes #2456.
> Spark 3.2: Support mergeSchema option on write

- aws/src/main/java/org/apache/iceberg/aws/glue/GlueCatalog.java
- aws/src/main/java/org/apache/iceberg/aws/glue/GlueTableOperations.java
- core/src/main/java/org/apache/iceberg/util/LockManagers.java
Use Glue optimistic locking while updating table.
Retry logs in case of concurrent updates:
```
22/02/21 15:37:10 WARN Tasks: Retrying task after failure: Cannot commit my_catalog.db_iceberg.table because Glue detected concurrent update
org.apache.iceberg.exceptions.CommitFailedException: Cannot commit my_catalog.db_iceberg.table because Glue detected concurrent update
at org.apache.iceberg.aws.glue.GlueTableOperations.doCommit(GlueTableOperations.java:127)
at org.apache.iceberg.BaseMetastoreTableOperations.commit(BaseMetastoreTableOperations.java:127)
at org.apache.iceberg.BaseTransaction.lambda$commitSimpleTransaction$5(BaseTransaction.java:377)
at org.apache.iceberg.util.Tasks$Builder.runTaskWithRetry(Tasks.java:404)
at org.apache.iceberg.util.Tasks$Builder.runSingleThreaded(Tasks.java: …
```
> AWS: Use Glue optimistic locking while updating table

- core/src/main/java/org/apache/iceberg/GenericManifestFile.java
Split out GenericManifestFile::toString changes of #4142, as per https://github.com/apache/iceberg/pull/4142#discussion_r808414246 .  This changes adds to toString method some certain missed fields of GenericManifestFile.
> Core: Update GenericManifestFile toString

- api/src/main/java/org/apache/iceberg/exceptions/BadRequestException.java
- api/src/main/java/org/apache/iceberg/exceptions/ForbiddenException.java
- api/src/main/java/org/apache/iceberg/exceptions/NotAuthorizedException.java
- api/src/main/java/org/apache/iceberg/exceptions/RESTException.java
- api/src/main/java/org/apache/iceberg/exceptions/ServiceFailureException.java
- core/src/main/java/org/apache/iceberg/rest/ErrorHandlers.java
These are a set of error handlers, to be used with the `RESTClient` and its HTTP implementation, when an `ErrorResponse` is received.
This allows for individual routes to override behavior, based on their specification.
As the error handlers are just `Consumer<ErrorResponse>`, they can be chained together via `andThen`.
A base error handler is provided, which covers response codes we expect from any route. It should be last in the chain.
See also https://github.com/apache/iceberg/pull/4201, which is where `ErrorResponse` is defined.
This is being posted to unblock work on the testing harnesses and infrastructure for the REST catalog.
cc @rdblue
> CORE - Add main error handlers for use with REST catalog's HTTP client

- aws/src/integration/java/org/apache/iceberg/aws/TestAssumeRoleAwsClientFactory.java
- aws/src/main/java/org/apache/iceberg/aws/AssumeRoleAwsClientFactory.java
- aws/src/main/java/org/apache/iceberg/aws/AwsClientFactories.java
- aws/src/test/java/org/apache/iceberg/aws/s3/TestS3FileIO.java
- build.gradle
Currently one http client instance is shared among AWS clients. This change enables users to independently close AWS clients and their associated http client without affecting other clients.
> AWS: Use independent http client for AWS clients

- python/src/iceberg/io/base.py
- python/src/iceberg/io/pyarrow.py
- python/tests/io/test_base.py
- python/tests/io/test_pyarrow.py
- python/tox.ini
This PR adds the first FileIO implementation. It wraps the PyArrow [FileSystem](https://arrow.apache.org/docs/python/generated/pyarrow.fs.FileSystem.html#pyarrow.fs.FileSystem) class. The locations provided to `PyArrowInputFile` and `PyArrowOutputFile` are used to infer the correct filesystem by passing them to the [FileSystem.from_uri](https://arrow.apache.org/docs/python/generated/pyarrow.fs.FileSystem.html#pyarrow.fs.FileSystem.from_uri) method. The implementations of the `InputFile.open` and `OutputFile.create` methods both return a `pyarrow.lib.NativeFile` instance.
> PyArrowFileIO Implementation

- flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/TestFlinkTableSink.java
- flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/source/BoundedTableFactory.java
- flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/source/BoundedTestSource.java
This PR is trying to fix the flaky testHashDistributeMode unit test fundamentally.  The following are the explannation about the current fix.
1. https://github.com/apache/iceberg/pull/4117#issuecomment-1042701849
2. https://github.com/apache/iceberg/pull/4117#issuecomment-1042718844
3. https://github.com/apache/iceberg/issues/2575#issuecomment-1046845868
> Flink 1.14: Fix the flaky testHashDistributeMode by ingesting all rows in one checkpoint cycle.

- flink/v1.12/flink/src/test/java/org/apache/iceberg/flink/TestFlinkTableSink.java
- flink/v1.12/flink/src/test/java/org/apache/iceberg/flink/source/BoundedTableFactory.java
- flink/v1.12/flink/src/test/java/org/apache/iceberg/flink/source/BoundedTestSource.java
Port https://github.com/apache/iceberg/pull/4189 to flink 1.12.
Reference issue: https://github.com/apache/iceberg/issues/2575
> Flink 1.12: Fix flaky testHashDistributeMode by ingesting all rows in one checkpoint cycle.

- flink/v1.13/flink/src/test/java/org/apache/iceberg/flink/TestFlinkTableSink.java
- flink/v1.13/flink/src/test/java/org/apache/iceberg/flink/source/BoundedTableFactory.java
- flink/v1.13/flink/src/test/java/org/apache/iceberg/flink/source/BoundedTestSource.java
Port https://github.com/apache/iceberg/pull/4189 to flink 1.13. 
Reference issue: https://github.com/apache/iceberg/issues/2575
> Flink 1.13: Fix flaky testHashDistributeMode by ingesting all rows in one checkpoint cycle

- docs/versioned/flink/flink-getting-started.md
The default value of `monitor-interval` should be `10s` instead of `1s`.
> Docs: fix doc for flink streaming reading

- core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java
- core/src/main/java/org/apache/iceberg/jdbc/JdbcUtil.java
- core/src/test/java/org/apache/iceberg/jdbc/TestJdbcCatalog.java
This fixes a few issues with the JDBC catalog's namespace implementation:
* Uses a default "exists" property to allow creating a database without custom metadata
* Implements `loadNamespaceMetadata`
* Fixes incorrect `NoSuchNamespaceException` thrown in `dropNamespace` (return `false` instead)
* Fixes `dropNamespace` when the namespace exists because properties are set (will remove all properties)
* Allows an empty map or set of properties in `removeProperties` and `setProperties` as noops
* Moves private helper methods to the end of the JDBCCatalog class
* Update tests for behavior fixes and to use `loadNamespaceMetadata` rather than directly using the `fetchProperties` helper method
> Core: Update JDBC catalog namespaces

- core/src/main/java/org/apache/iceberg/rest/responses/RESTCatalogConfigResponse.java
- core/src/test/java/org/apache/iceberg/rest/responses/TestRESTCatalogConfigResponse.java
Defines the response class used to populate the server-provided configuration.
Per the spec, the catalog client will call the `/v1/config` endpoint to retrieve a set of `overrides` and `defaults`. The `default` configurations are there to allow clients to not have to provide _all_ details so that end user's don't have to specify values that are commonly used, and the `overrides` are there so that the server can require a certain value be used.
I've also started updating the REST catalog spec to be more detailed for this part (though I'll probably move that to another PR).
> CORE: REST Catalog - Response class for server provided configuration

- core/src/main/java/org/apache/iceberg/rest/responses/CreateNamespaceResponse.java
- core/src/main/java/org/apache/iceberg/rest/responses/GetNamespaceResponse.java
- core/src/main/java/org/apache/iceberg/rest/responses/ListNamespacesResponse.java
- core/src/main/java/org/apache/iceberg/rest/responses/ListTablesResponse.java
The builders can only be used outside of the `responses` package if the builders are public.
> Core: Make REST response builders public

- core/src/main/java/org/apache/iceberg/rest/responses/RESTCatalogConfigResponse.java
Right now, the `RESTCatalogConfigResponse#merge` function is used to merge the server-provided configuration with the initial client provided configuration.
However, if the data is parsed by Jackson and one of `overrides` or `defaults` is null (or wasn't in the original payload), this will hit an NPE.
Updating to avoid the NPE. Will add a unit test for this in my next PR (which makes use of this).
cc @rdblue
> Core: Avoid possible NPE in RESTCatalogConfigResponse#merge

- core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java
- core/src/main/java/org/apache/iceberg/jdbc/JdbcUtil.java
- core/src/test/java/org/apache/iceberg/catalog/CatalogTests.java
- core/src/test/java/org/apache/iceberg/jdbc/TestJdbcCatalog.java
This continues cleaning up the JDBC implementation after #4220 and adds namespace tests to validate the behavior of the JDBC catalog and other catalogs that support namespace properties.
* Creates a base set of catalog tests that check namespace behavior
* Consolidates JDBC exception handling by combining logic in `fetch`, `exists`, and `execute` helper methods
* Fixes namespace listing that needs to combine namespaces that exist from properties or tables
> Core: Clean up JDBC implementation, add catalog namespace tests

- flink/v1.12/build.gradle
- flink/v1.13/build.gradle
- flink/v1.14/build.gradle
- settings.gradle
Refer to the https://github.com/apache/iceberg/pull/4157#discussion_r811700041
> Flink: Remove the scala version suffix from artifact names.

- spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestExpireSnapshotsProcedure.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/actions/BaseExpireSnapshotsSparkAction.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/procedures/ExpireSnapshotsProcedure.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/actions/TestExpireSnapshotsAction.java
When we try to run expire_snapshots procedure on the iceberg table for the first time, it often makes the driver OOM due to a big list of files to delete, which requires to increase the driver memory a lot. The iceberg table in our case contained more than ~2M data files and ~70K snapshots before we executed the expire_snapshots procedure. 
We can allow the user to choose whether to use `stream_results` as a procedure option to avoid this case.
> enable stream-results option to avoid spark driver oom

- docs/versioned/integrations/aws.md
Recently we added Glue optimistic locking while updating table in https://github.com/apache/iceberg/pull/4166. This PR updates the site docs.
> Docs: Add Glue optimistic locking

- core/src/test/java/org/apache/iceberg/TestRemoveSnapshots.java
From this comment: https://github.com/apache/iceberg/pull/4182#issuecomment-1047472013
There are so far tests for expire-action and remove-orphans Spark Actions for V2 Delete Files, but not yet the Table API expire-snapshots.  This adds that test.
> Add test for Table::expireSnapshot API removing delete files

- build.gradle
- core/src/main/java/org/apache/iceberg/TableProperties.java
- docs/versioned/tables/configuration.md
- orc/src/main/java/org/apache/iceberg/orc/ORC.java
- orc/src/test/java/org/apache/iceberg/orc/TestTableProperties.java
closes https://github.com/apache/iceberg/issues/3272
> To be consistent with Parquet, it would be good to introduce write table properties for ORC too.
Also make sure that we have a configuration available for ORC separately.
Discussed here: #2935 (comment)
> ORC: Add configurable write properties

- docs/versioned/api/java-api-quickstart.md
Sample code declares a variable as `Catalog` instead of `HiveCatalog` but calls a method that is not in `Catalog`, only in `HiveCatalog`.
> Docs: Fix typo in Java API Quickstart

- common/src/main/java/org/apache/iceberg/common/DynConstructors.java
This adds the exceptions thrown while attempting to dynamically load a constructor as suppressed exceptions on the exception that is finally thrown. This should preserve causes that are currently unavailable because only the exception messages are used.
> Common: Add dynamic loading exceptions as suppressed exceptions

- hive-metastore/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java
- hive-metastore/src/test/java/org/apache/iceberg/hive/TestHiveCommits.java
After #3717 all HIve exceptions become CommitStateUnknownException.  That is because checkCommitStatus stops returning FAILURE mode and always either SUCCESS or UNKNOWN, and subsequent specific error-handling blocks [specific catch blocks](https://github.com/apache/iceberg/blob/master/hive-metastore/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java#L287) never get run.
For instance, doing a create table statement with invalid character in name:  
```CREATE TABLE `tbl` (id INT) USING ICEBERG```
Gets this kind of confusing and alarming error message for user:
```
org.apache.iceberg.exceptions.CommitStateUnknownException: `tbl` is not a valid object name
Cannot determine whether the commit was successful or not, the underlying data files may or may not be needed. Manual …
```
> Hive: Known exception should not become CommitStateUnknownException

- build.gradle
- core/src/main/java/org/apache/iceberg/rest/RESTUtil.java
- core/src/test/java/org/apache/iceberg/rest/TestRESTUtil.java
The REST Catalog uses the string value of a namespace in URLs.
Per the spec, the levels of a multi-level namespace are joined by the NULL byte character (`'\0'` or more correctly `'\u0000'`).
This adds a utility class which can:
1) Properly URL encode a `Namespace` for use as either a path or query parameter
2) Function for decoding the namespace string from a path variable into a Namespace
3) Some helpers for use with REST catalog configuration (function to get all config values that start with a specific prefix, and function to strip the trailing slash from a path if need be).
The items from (3) can likely be put into a shared `CatalogUtil` class as they occur in a few places, but to cause minimal disruption I'm declaring them separately. They can be merged together as a follow up.
This …
> Core - Add in RESTUtil class for encoding namespace as URL variable

- .github/workflows/flink-ci.yml
- .github/workflows/hive-ci.yml
- .github/workflows/java-ci.yml
- .github/workflows/python-ci.yml
- .github/workflows/python-legacy-ci.yml
- .github/workflows/spark-ci.yml
Right now, we use both `push` and `pull_request` event to trigger our github actions.
This causes us to duplicate our `paths-ignore` in every file.
Additionally, as we start to use more github action features, such as in https://github.com/apache/iceberg/pull/4207, it would be good to reduce the number of events that trigger workflows so that the `github` context has consistent fields. For example, `github.head_ref` is only defined for `pull_request` and not `push` or any other trigger.
Another quirk of using `push` is that it causes CI to run in forks etc when people push to their branch.
I've updated the CI workflows to only run on `pull_request`, which will retrigger every time it's pushed.
I also left `on: push` in, but only for the `'master'` branch, so that CI will run to completion …
> Infra - Trigger CI using on pull_request, saving push for master branch and tags (releases)

- .github/workflows/flink-ci.yml
- .github/workflows/hive-ci.yml
- .github/workflows/java-ci.yml
- .github/workflows/spark-ci.yml
Disables running CI workflows for any PR that is opened that only updates the `open-api` folder or the `format` folder.
The `docs` folder is already covered.
> Infra - Disable CI for anything in open-api or format folder

- .github/workflows/spark-ci.yml
- jmh.gradle
- settings.gradle
- spark/v2.4/build.gradle
- spark/v3.0/build.gradle
This PR is trying to address the comment from [here](https://github.com/apache/iceberg-docs/pull/27#discussion_r800297155). 
The current spark2.4, spark3.0 have the following unaligned module name for me (spark3.1 & spark3.2 are more clear).
```
iceberg-spark-runtime-0.13.1.jar
iceberg-spark3-runtime-0.13.1.jar
iceberg-spark-runtime-3.1_2.12-0.13.1.jar
iceberg-spark-runtime-3.2_2.12-0.13.1.jar
```
After applied this PR, the current spark runtime jar are named as:
```
./gradlew clean build -x test -DsparkVersions=2.4,3.0,3.1,3.2 -DscalaVersion=2.12 -DknownScalaVersions=2.12 -x javadoc -Pquick -DflinkVersions= -DhiveVersions=
➜  iceberg git:(align-spark-module-name) find spark | grep runtime | grep SNAPSHOT.jar
spark/v3.2/spark-runtime/build/libs/iceberg-spark-runtime-3.2_2.12-0.13.0-SNAPSHO …
```
> Build: Align the module name among spark2.4, spark3.0, spark3.1 and spark3.2

- .github/workflows/flink-ci.yml
- .github/workflows/hive-ci.yml
- .github/workflows/java-ci.yml
- .github/workflows/python-ci.yml
- .github/workflows/python-legacy-ci.yml
- .github/workflows/spark-ci.yml
We'd like to run CI to completion when we push to a release branch.
Release branches are of the form `0.x.y` right now, so matching on `0.**`
For release tags, they are normally `apache-iceberg-**`, so I've updated the CI suites to run on push to a tag of that format.
cc @rdblue @snazy @nastra
> Infra - Trigger CI when pushing to a release branch or tag

- core/src/main/java/org/apache/iceberg/TableMetadata.java
- core/src/main/java/org/apache/iceberg/TableMetadataParser.java
- core/src/test/java/org/apache/iceberg/TestTableMetadata.java
This updates TableMetadataParser to read and write the [refs map](https://iceberg.apache.org/spec/#snapshot-reference).
> Core: Implement table refs in TableMetadataParser

- core/src/main/java/org/apache/iceberg/BaseOverwriteFiles.java
- core/src/test/java/org/apache/iceberg/TestOverwriteWithValidation.java
This PR fixes the deleted data files validation for overwrites by filter in `OverwriteFiles`. Right now, we allow removal of data files in partitions we overwrite, which, I think violates the assumption.
Found by @szehon-ho in #4293.
> Core: Fix deleted data files validation in OverwriteFiles

- core/src/main/java/org/apache/iceberg/util/ThreadPools.java
- flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/FlinkConfigOptions.java
- flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/FlinkDynamicTableFactory.java
- flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/IcebergTableSink.java
- flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java
- flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/IcebergFilesCommitter.java
- flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/source/FlinkInputFormat.java
- flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/source/FlinkSource.java
- flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/source/FlinkSplitPlanner.java
- flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/source/ScanContext.java
- flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/source/StreamingMonitorFunction.java
- flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/sink/TestIcebergFilesCommitter.java
- flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/source/SplitHelpers.java
- flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/source/TestStreamingReaderOperator.java
> Use particular worker pool for flink jobs

- core/src/main/java/org/apache/iceberg/AllDataFilesTable.java
- core/src/main/java/org/apache/iceberg/BaseFilesTable.java
- core/src/main/java/org/apache/iceberg/DataFilesTable.java
- core/src/main/java/org/apache/iceberg/DeleteFilesTable.java
- core/src/main/java/org/apache/iceberg/MetadataTableType.java
- core/src/main/java/org/apache/iceberg/MetadataTableUtils.java
- core/src/test/java/org/apache/iceberg/TableTestBase.java
- core/src/test/java/org/apache/iceberg/TestMetadataTableScans.java
- core/src/test/java/org/apache/iceberg/hadoop/HadoopTableTestBase.java
- core/src/test/java/org/apache/iceberg/hadoop/TestTableSerialization.java
- spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMetadataTables.java
Closes #4139 
It was decided there to make it into a separate table.
This change refactors some of the DataFilesTable logic (like schema, partition pruning) into a base class and re-uses it for DeleteFilesTable.
> Add delete_files metadata table

- flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/FlinkTestBase.java
- flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/TestFlinkTableSink.java
- flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/TestIcebergConnector.java
- flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/source/ChangeLogTableTestBase.java
- flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/source/TestFlinkScanSql.java
- flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/source/TestStreamScanSql.java
The `blink` planner has been the default as of 1.14.
These calls to `useBlinkPlanner` are currently no-ops, but will become invalid as of Flink 1.15.
Removing them now from the Flink 1.14 code base to remove deprecation warnings, as well as to make migrating code to the upcoming Flink 1.15 release easier.
Additionally, I've removed calls to setting stream time characteristic as `EventTime`. `EventTime` is the default time characteristic, and functions should handle event time and processing time as needed. Given these are tests, it's essentially a no-op but we might want to ensure we adhere to this when we copy over for Flink 1.15.
> Flink - Remove deprecated calls to blink planner that has been removed

- core/src/main/java/org/apache/iceberg/hadoop/HadoopMetricsContext.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/TestHadoopMetricsContextSerialization.java
- Currently when we use any serializer other than JavaSerializer (for ex : KryoSerializer), we face an NPE due to statistics being null and not be re-initialized on de-serialization (since we broadcast FileIO and hence part of this we serialize it at driver & de serialize it in executor for spark) .
This PR attempts to address the issue reported below : 
Closes #4288
> Core : Fix NPE post HadoopMetricContext Deserialization

- spark/v3.2/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/analysis/RewriteMergeIntoTable.scala
Attribute exposes functions such as withNullability which can be used.
Incase of AttributeRef this is existing impl : [CodePointer](https://github.com/apache/spark/blob/master/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/namedExpressions.scala#L306-L312)
```
/**
* Returns a copy of this [[AttributeReference]] with changed nullability.
*/
override def withNullability(newNullability: Boolean): AttributeReference = {
if (nullable == newNullability) {
this
} else {
AttributeReference(name, dataType, newNullability, metadata)(exprId, qualifier)
}
}
```
As per my understanding, our intention was only to change nullablity we should use this rather than creating new AttributeRef obj always and losing exprId's / qualifers in the course 
Note : exprId's were used here to …
> Spark : use withNullability rather than creating new AttributeRef and losing ExprId, Qualifiers

- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/SparkCatalog.java
- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/SparkSessionCatalog.java
- spark/v3.1/spark/src/test/java/org/apache/iceberg/spark/sql/TestDropTable.java
In #3056, we have supported `PURGE` flag in `DROP TABLE` for Spark 3.2. This patch backports it to Spark 3.1.
> Spark 3.1: Support PURGE flag in DROP TABLE

- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/actions/BaseRewriteDataFilesSparkAction.java
This change simplifies the validation in `BaseRewriteDataFilesSparkAction`. 
The earlier validation was `!partialProgressEnabled || partialProgressEnabled && maxCommits > 0`. The right side of the OR condition is always evaluated when `partialProgressEnabled` is true. Hence, we need not to mention `partialProgressEnabled` explicitly on the right side of the OR condition.
> Spark: Simplify validation in BaseRewriteDataFilesSparkAction

- aws/src/main/java/org/apache/iceberg/aws/AwsProperties.java
- aws/src/main/java/org/apache/iceberg/aws/s3/BaseS3File.java
- aws/src/main/java/org/apache/iceberg/aws/s3/S3FileIO.java
- aws/src/main/java/org/apache/iceberg/aws/s3/S3OutputFile.java
- aws/src/main/java/org/apache/iceberg/aws/s3/S3OutputStream.java
- aws/src/test/java/org/apache/iceberg/aws/glue/TestGlueCatalog.java
- aws/src/test/java/org/apache/iceberg/aws/s3/TestS3FileIO.java
- aws/src/test/java/org/apache/iceberg/aws/s3/TestS3OutputStream.java
- core/src/main/java/org/apache/iceberg/util/PropertyUtil.java
This change adds [S3 Tags](https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-tagging.html) to the objects while writing using `S3FileIO`. Users can pass their custom tags as part of the catalog properties.
Spark SQL launch command:
```
sh spark-sql --conf spark.sql.catalog.my_catalog=org.apache.iceberg.spark.SparkCatalog \
--conf spark.sql.catalog.my_catalog.warehouse=s3://iceberg-warehouse/s3-tagging \
--conf spark.sql.catalog.my_catalog.catalog-impl=org.apache.iceberg.aws.glue.GlueCatalog \
--conf spark.sql.catalog.my_catalog.io-impl=org.apache.iceberg.aws.s3.S3FileIO \
--conf spark.sql.catalog.my_catalog.s3.write.tags.my_key=my_val \
--conf spark.sql.catalog.my_catalog.s3.write.tags.my_key2=my_val2
```
Tags added in S3:
```
aws s3api get-object-tagging --bucket …
```
> AWS: Add S3 Tagging

- docs/integrations/aws.md
This PR changes the doc to add details about [S3 tagging](https://github.com/apache/iceberg/pull/4259) feature.
----
cc: @jackye1995 @arminnajafi @singhpk234 @amogh-jahagirdar @xiaoxuandev @yyanyy
> Docs: Add S3 Tagging docs

- spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestConflictValidation.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/SparkWrite.java
This makes some minor cleanup and add one more test for #2925 
This is from comment https://github.com/apache/iceberg/pull/4293#discussion_r823035860 of splitting these changes from that pr into a separate one.
> Spark 3.2: Cleanup DataFrame overwritePartitions isolation level handling

- core/src/main/java/org/apache/iceberg/MetadataUpdate.java
- core/src/main/java/org/apache/iceberg/TableMetadata.java
This updates `TableMetadata` and `MetadataUpdate` so that changes can be reconstructed in `TableMetadata.Builder` from a list of `MetadataUpdate` instances that are produced by the builder.
This also fixes a few minor issues with the builder:
* `lastAssignedPartitionId` was not public
* Supports set changes that use `-1` to refer to the last added schema, spec, or sort order
* Updates snapshot history timestamp based on whether the snapshot was added, rather than the `setCurrentSnapshot` call
This is part of #4241.
> Core: Add MetadataUpdate.applyTo to re-apply changes

- .github/workflows/flink-ci.yml
Run flink travis CI for both scala 2.11 & 2.12
> Build: Test flink modules for both scala 2.11 and 2.12

- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/actions/BaseRewriteDataFilesSparkAction.java
This PR backports https://github.com/apache/iceberg/pull/4324 to Iceberg Spark 3.1 runtime.
> Spark 3.1: Simplify validation in BaseRewriteDataFilesSparkAction

- open-api/rest-catalog-open-api.yaml
This updates the REST spec to reflect the changes from #4241, which has a working implementation of the REST protocol using in-memory request/response message passing.
Major changes:
* Add assertions needed for transactions
* Document assertions
* Add `table-metadata` to load, update, and create table responses
> Spec: Update REST spec with changes needed for transactions

- core/src/main/java/org/apache/iceberg/ManifestFilterManager.java
- spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestDelete.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteDataFilesAction.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/data/TestHelpers.java
The presence of some V2 delete files lead to following error for a subsequent delete that tries to use metadata.
```
Failed to cleanly delete data files matching: ref(name="id") == 1
java.lang.IllegalArgumentException: Failed to cleanly delete data files matching: ref(name="id") == 1
at org.apache.iceberg.spark.source.SparkTable.deleteWhere(SparkTable.java:282)
at org.apache.spark.sql.execution.datasources.v2.DeleteFromTableExec.run(DeleteFromTableExec.scala:31)
at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.result$lzycompute(V2CommandExec.scala:43)
at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.result(V2CommandExec.scala:43)
at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.executeCollect(V2CommandExec.scala:49)
at …
```
> Core: ValidationException on metadata-only delete of certain delete files

- api/src/main/java/org/apache/iceberg/io/BulkDeletionFailureException.java
- api/src/main/java/org/apache/iceberg/io/SupportsBulkOperations.java
- aws/src/integration/java/org/apache/iceberg/aws/s3/TestS3FileIOIntegration.java
- aws/src/main/java/org/apache/iceberg/aws/AwsProperties.java
- aws/src/main/java/org/apache/iceberg/aws/s3/S3FileIO.java
- aws/src/test/java/org/apache/iceberg/aws/TestAwsProperties.java
- aws/src/test/java/org/apache/iceberg/aws/s3/TestS3FileIO.java
Starting a draft PR for performing batch deletion for S3 objects. Related issue: https://github.com/apache/iceberg/issues/4012
This can be useful for the expire snapshots and remove orphan files operations. In this PR we update the FileIO interface and add a S3 implementation to perform the batch removal. Leaving it in draft until I add some unit tests for the batch removal implementation for S3, wanted to get some initial feedback on the code.
In other PRs we can tackle updating the actions for expiring snapshots and removing orphan files. My thoughts there are we do have a separate batching mechanism within the action implementation (for an action a user would specify a batch size (defaulting to 1). Tasks looks like it is generic and for the parameter we could partition the given input …
> AWS: Add SupportBulkOperation interface. S3FileIO implementation will perform a batch deletion using RemoveObjects API

- core/src/main/java/org/apache/iceberg/TableMetadataParser.java
This change is a follow on to @rdblue change in https://github.com/apache/iceberg/pull/4260 . Since we have an existing SnapshotRefParser I think we can leverage that and reduce some of the implementation in TableMetadataParser.
Let me know your thoughts! @rdblue  @jackye1995
> Core: Use existing SnapshotRefParser when serializing ref information in TableMetadata Parser

- core/src/main/java/org/apache/iceberg/rest/requests/CreateTableRequest.java
- core/src/main/java/org/apache/iceberg/rest/requests/UpdateTableRequest.java
- core/src/main/java/org/apache/iceberg/rest/responses/DropTableResponse.java
- core/src/main/java/org/apache/iceberg/rest/responses/LoadTableResponse.java
This adds REST request and response classes for table operations.
* `CreateTableRequest` is used to create tables
* `UpdateTableRequest` is used to update tables by [applying a list of `MetadataUpdate` changes](https://github.com/apache/iceberg/pull/4320)
* `LoadTableResponse` is used for create, load, and update
* `DropTableResponse` is used for drop
`UpdateTableRequest` includes a set of assertions from the REST spec, with some additions that were needed to get [tests](https://github.com/apache/iceberg/pull/4319) working:
* `AssertTableDoesNotExist` is used for create table transactions
* `AssertTableUUID` checks that the table UUID has not changed from the base metadata (prevents errors from concurrent drop/create)
* `AssertLastAssignedFieldId` is used to check that no concurrent …
> Core: Add REST catalog table requests and responses

- flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/source/ScanContext.java
Fix missing copy metioned in #4329 by @stevenzwu .
> Flink: fix missing copy in ScanContext

- aws/src/main/java/org/apache/iceberg/aws/s3/S3FileIO.java
presently TestS3FileIOIntegration fails with NPE because of s3FileIo.Initialize not being called.
This happens because writeTags is never intialized if we don't call it's initialize and it always remains null so when we check if it's empty or not while initializing upload / mutlipart upload it faces NPE.
https://github.com/apache/iceberg/blob/c1adf2034280884d05afad4e67f09f2872c47d78/aws/src/main/java/org/apache/iceberg/aws/s3/S3FileIO.java#L70
https://github.com/apache/iceberg/blob/c1adf2034280884d05afad4e67f09f2872c47d78/aws/src/main/java/org/apache/iceberg/aws/s3/S3OutputStream.java#L263
Ideally we should initialize while declaration like we do metrics to avoid this scenario. 
Post this fix test passes
-----
cc: @jackye1995 @rajarshisarkar @arminnajafi @amogh-jahagirdar @xiaoxuandev …
> AWS : Address S3FileIOIntegrationTest failures

- format/spec.md
- parquet/src/main/java/org/apache/iceberg/parquet/ParquetWriter.java
When parquetWriter.java call close， it called the writeStore.close 
public void close() throws IOException {
if (!closed) {
this.closed = true;
flushRowGroup(true);
writeStore.close();                       ------ here close the writeStore
if (writer != null) {
writer.end(metadata);
}
}
}
But in checksize function when called the  flushRowGroup(false); 
private void flushRowGroup(boolean finished) {
try {
if (recordCount > 0) {
ensureWriterInitialized();
writer.startBlock(recordCount);
writeStore.flush();
flushPageStoreToWriter.invoke(writer);
writer.endBlock();
if (!finished) {
startRowGroup();                ---- here new another one, but the old not closed
}
}
} catch (IOException e) {
throw new UncheckedIOException("Failed to flush row group", e);
}
}
It doesn't close the writeStore …
> Parquet: parquet_writer.java should close the writeStore when flushRowGroup's finished is false

- core/src/main/java/org/apache/iceberg/LocationProviders.java
- core/src/test/java/org/apache/iceberg/TestLocationProvider.java
This detects when an object storage location is within a table's prefix and avoids adding the table and database names to file paths as context.
> Core: Skip context for object storage in table prefixes

- docs/spark/spark-queries.md
Using the SparkSessionCatalog to query metadata tables is possible in Spark 3.2.
> Docs: Update section on inspecting tables

- spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestConflictValidation.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/SparkWrite.java
https://github.com/apache/iceberg/pull/2925 adds isolation level support to the core Iceberg API ReplacePartitions, and also exposes it via Spark DataFrame.overwritePartitions() API.
This change is to extend isolation level support to the Spark DataFrame.overwrite(filter) API for symmetry. The underlying core Iceberg API (OverwriteFiles) already supported isolation level validation in this case, so the change is smaller.
One observation, DF.overwrite(filter) will be less aggressive than DF.overwritePartitions() in concurrent validation due to the two different API code paths.  OverwriteFiles checks exactly for the file that will be re-written, so it will not throw an exception if another file was deleted in the same partition. This is unlike ReplacePartitions API which throws exception if …
> Spark: Add isolation level support to DataFrame.overwrite(filter) API

- aws/src/main/java/org/apache/iceberg/aws/AwsProperties.java
- aws/src/main/java/org/apache/iceberg/aws/s3/BaseS3File.java
- aws/src/main/java/org/apache/iceberg/aws/s3/S3FileIO.java
- aws/src/main/java/org/apache/iceberg/aws/s3/S3OutputFile.java
- aws/src/main/java/org/apache/iceberg/aws/s3/S3OutputStream.java
- aws/src/test/java/org/apache/iceberg/aws/s3/TestS3FileIO.java
- aws/src/test/java/org/apache/iceberg/aws/s3/TestS3OutputStream.java
This change moves S3 `writeTags` to `AwsProperties`. This provides a cleaner solution as `AwsProperties` was designed to be the extension point for new configs without changing constructors.
Users can pass their custom tags as part of the catalog properties.
Spark SQL launch command:
```
sh spark-sql --conf spark.sql.catalog.my_catalog=org.apache.iceberg.spark.SparkCatalog \
--conf spark.sql.catalog.my_catalog.warehouse=s3://iceberg-warehouse/s3-tagging \
--conf spark.sql.catalog.my_catalog.catalog-impl=org.apache.iceberg.aws.glue.GlueCatalog \
--conf spark.sql.catalog.my_catalog.io-impl=org.apache.iceberg.aws.s3.S3FileIO \
--conf spark.sql.catalog.my_catalog.s3.write.tags.my_key=my_val \
--conf spark.sql.catalog.my_catalog.s3.write.tags.my_key2=my_val2
```
Tags added in S3:
```
aws s3api …
```
> AWS: Move S3 writeTags to AwsProperties

- aws/src/main/java/org/apache/iceberg/aws/AwsProperties.java
- aws/src/main/java/org/apache/iceberg/aws/s3/S3OutputStream.java
- aws/src/test/java/org/apache/iceberg/aws/s3/TestS3OutputStream.java
This is a minor follow-up to #4350 that removes an unnecessary `get` from S3 write tag config.
> AWS: Remove get from getter method.

- spark/v2.4/build.gradle
- spark/v2.4/spark-runtime/LICENSE
- spark/v2.4/spark-runtime/NOTICE
- spark/v3.0/build.gradle
- spark/v3.0/spark-runtime/LICENSE
- spark/v3.0/spark-runtime/NOTICE
- spark/v3.1/build.gradle
- spark/v3.1/spark-runtime/LICENSE
- spark/v3.1/spark-runtime/NOTICE
- spark/v3.2/build.gradle
- spark/v3.2/spark-runtime/LICENSE
- spark/v3.2/spark-runtime/NOTICE
This reverts commit eace97307cecf1e6a8cdd96cf78a5d0847ea1cb7.
while using the latest build from master branch with `iceberg-spark-runtime-3.0_2.12-0.14.0-SNAPSHOT.jar`.
**Basic select query from a table failed with below error.**
Caused by: java.lang.NoSuchMethodError: io.netty.buffer.PooledByteBufAllocatorL.allocate(J)Lio/netty/buffer/UnsafeDirectLittleEndian;
Once I revert this Change. Query was success for me.
> Revert "Spark: Exclude Netty from Spark runtime modules (#4110)"

- api/src/main/java/org/apache/iceberg/SortOrder.java
- api/src/main/java/org/apache/iceberg/UnboundSortOrder.java
- core/src/main/java/org/apache/iceberg/MetadataUpdate.java
- core/src/main/java/org/apache/iceberg/SortOrderParser.java
- core/src/main/java/org/apache/iceberg/TableMetadata.java
- core/src/main/java/org/apache/iceberg/rest/RESTSerializers.java
This is to support the REST catalog. Building a sort order currently requires a schema, which is not part of the serialization format. This adds an intermediate class, `UnboundSortOrder` that can be built without a schema and later bound to a schema.
> API: Add UnboundSortOrder that has no schema

- api/src/main/java/org/apache/iceberg/PartitionSpec.java
- api/src/main/java/org/apache/iceberg/SortOrder.java
- api/src/main/java/org/apache/iceberg/UnboundPartitionSpec.java
- core/src/main/java/org/apache/iceberg/MetadataUpdate.java
- core/src/main/java/org/apache/iceberg/PartitionSpecParser.java
- core/src/main/java/org/apache/iceberg/TableMetadata.java
- core/src/main/java/org/apache/iceberg/rest/RESTSerializers.java
Similar to #4360, this adds an unbound partition spec that can deserialize without a schema and bind to a schema to produce a normal `PartitionSpec`.
> API: Add UnboundPartitionSpec that has no schema

- aws/src/main/java/org/apache/iceberg/aws/AwsProperties.java
make the example in java doc of s3WriteTagPrefix engine agnostic.
earlier suggestion : https://github.com/apache/iceberg/pull/4334#discussion_r828195275
> AWS : make passing s3WriteTags javaDoc example engine agnostic

- open-api/rest-catalog-open-api.yaml
This is an alternative to #4337. Instead of using 200 for all cases where the table does not exist, it uses 204 if the namespace or table was removed (equivalent to dropped=true) and 404 if the namespace or table did not exist (equivalent to dropped=false).
> Core: Update DELETE routes to use 204 for success

- flink/v1.12/flink/src/main/java/org/apache/iceberg/flink/source/RowDataFileScanTaskReader.java
- flink/v1.13/flink/src/main/java/org/apache/iceberg/flink/source/RowDataFileScanTaskReader.java
- flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/source/RowDataFileScanTaskReader.java
```
Parquet.ReadBuilder builder = Parquet.read(inputFilesDecryptor.getInputFile(task))
.reuseContainers()
.split(task.start(), task.length())
.project(schema)
.createReaderFunc(fileSchema -> FlinkParquetReaders.buildReader(schema, fileSchema, idToConstant))
.filter(task.residual())
.caseSensitive(caseSensitive)
.reuseContainers()
```
call `reuseContainers` twice...
> Flink: remove redundant code

- core/src/main/java/org/apache/iceberg/rest/RESTSerializers.java
This adds the `ErrorResponse` to the `RESTSerializers`.
It uses the existing `ErrorResponseParser`, so that the `ErrorResponse` can be registered as serializable with the object mapper used with the REST Catalog.
cc @rdblue
> Core - Add ErrorResponse jackson serde to RESTSerializers

- gcp/src/main/java/org/apache/iceberg/gcp/gcs/BaseGCSFile.java
- gcp/src/main/java/org/apache/iceberg/gcp/gcs/GCSFileIO.java
- gcp/src/main/java/org/apache/iceberg/gcp/gcs/GCSInputFile.java
- gcp/src/main/java/org/apache/iceberg/gcp/gcs/GCSInputStream.java
- gcp/src/main/java/org/apache/iceberg/gcp/gcs/GCSOutputFile.java
- gcp/src/main/java/org/apache/iceberg/gcp/gcs/GCSOutputStream.java
- gcp/src/test/java/org/apache/iceberg/gcp/gcs/GCSInputStreamTest.java
- gcp/src/test/java/org/apache/iceberg/gcp/gcs/GCSOutputStreamTest.java
This PR adds metrics tracking for `GCSFileIO`. This would help reporting IO metrics via the Hadoop `FileSystem.Statistics`.
> GCP: Add metrics tracking for GCSFileIO

- core/src/main/java/org/apache/iceberg/ManifestFilterManager.java
- core/src/test/java/org/apache/iceberg/TestOverwriteWithValidation.java
This PR is a follow-up to #4304. In that PR, we updated the method that checks whether a manifest has an entry to be deleted. However, we did not update the method that actually does the manifest filtering. As a consequence, the test added in this PR would fail with a runtime exception as one delete file should be removed and one kept. In addition, we should not introduce any extra calls to `evaluator` as they are expensive.
Overall, the problem is that whenever we overwrite data by filter, we should not fail operations when it is not possible to remove delete files. Removal of delete files is optional and is an optimization we should perform if possible.
> Core: Make removal of delete files optional in manifest filtering

- docs/integrations/nessie.md
Order of arguments is wrong for java API example of Nessie catalog for `CatalogUtil.loadCatalog`
> Docs: Fix wrong ordering of arguments in Nessie catalog example

- docs/spark/spark-procedures.md
- spark/v3.0/spark/src/main/java/org/apache/iceberg/spark/procedures/RollbackToTimestampProcedure.java
- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/procedures/RollbackToTimestampProcedure.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/procedures/RollbackToTimestampProcedure.java
- Spark supports [microseconds precision](https://github.com/apache/spark/blob/master/sql/catalyst/src/main/scala/org/apache/spark/sql/types/TimestampType.scala#L26)  but in code we cast to milliseconds, so better to warn the users.
- Some code comment was wrong about spark precision. 
- Remove generic spark expressions for timestamp in expire_snapshots example (as it is not supported)
> Docs: Clarify timestamp in stored procedures

- aws/src/integration/java/org/apache/iceberg/aws/lakeformation/TestLakeFormationAwsClientFactory.java
- aws/src/main/java/org/apache/iceberg/aws/AssumeRoleAwsClientFactory.java
- aws/src/main/java/org/apache/iceberg/aws/AwsClientFactories.java
- aws/src/main/java/org/apache/iceberg/aws/AwsProperties.java
- aws/src/main/java/org/apache/iceberg/aws/glue/GlueCatalog.java
- aws/src/main/java/org/apache/iceberg/aws/lakeformation/LakeFormationAwsClientFactory.java
- build.gradle
[AWS LakeFormation](https://docs.aws.amazon.com/lake-formation/latest/dg/what-is-lake-formation.html) provides a central place where users can grant data/metadata security permissions such as access/update/delete databases, tables as well as columns and rows to other users. This change is focus on adding db and table level access control.
[Find more information on How to use LakeFormation Credential vending APIs](https://docs.aws.amazon.com/lake-formation/latest/dg/api-overview.html)
> AWS: Add LakeFormation credential support for GlueCatalog

- aws/src/integration/java/org/apache/iceberg/aws/AwsIntegTestUtil.java
- aws/src/integration/java/org/apache/iceberg/aws/s3/TestS3FileIOIntegration.java
- aws/src/main/java/org/apache/iceberg/aws/AssumeRoleAwsClientFactory.java
- aws/src/main/java/org/apache/iceberg/aws/AwsClientFactories.java
- aws/src/main/java/org/apache/iceberg/aws/AwsProperties.java
- aws/src/main/java/org/apache/iceberg/aws/lakeformation/LakeFormationAwsClientFactory.java
- aws/src/main/java/org/apache/iceberg/aws/s3/S3FileIO.java
- aws/src/main/java/org/apache/iceberg/aws/s3/S3InputFile.java
- aws/src/main/java/org/apache/iceberg/aws/s3/S3OutputFile.java
- aws/src/main/java/org/apache/iceberg/aws/s3/S3URI.java
- aws/src/test/java/org/apache/iceberg/aws/s3/TestS3URI.java
- build.gradle
This tries to add support of s3 access points 
ref : https://aws.amazon.com/s3/features/access-points/
```shell
spark-shell \
--conf spark.sql.catalog.test=org.apache.iceberg.spark.SparkCatalog \
--conf spark.sql.catalog.test.warehouse=s3://my-bucket \
--conf spark.sql.catalog.test.catalog-impl=org.apache.iceberg.aws.glue.GlueCatalog \
--conf spark.sql.catalog.test.io-impl=org.apache.iceberg.aws.s3.S3FileIO \
--conf spark.sql.catalog.test.s3.access-points.my-bucket=arn:aws:s3::123456789012:accesspoint:mfzwi23gnjvgw.mrap
```
The s3.access-points config provides a map of bucket to endpoint mapping for paths stored in Iceberg, so that the S3FileIO can use the access point to get the bucket instead when the mapping is configured.
---
cc: @jackye1995 @rajarshisarkar @arminnajafi …
> AWS: Add support for s3 access points

- data/src/main/java/org/apache/iceberg/data/DeleteFilter.java
- data/src/main/java/org/apache/iceberg/data/GenericDeleteFilter.java
- flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/source/RowDataFileScanTaskReader.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/BatchDataReader.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/RowDataReader.java
Limits the constructor arguments for DeleteFilters to just the parts of the FileScanTask actually used. This came up as a part of the Trino work to support merge-on-read tables and reusing DeleteFilter there.
> Core: Make DeleteFilter's constructor parameters more specific

- flink/v1.12/flink/src/main/java/org/apache/iceberg/flink/source/RowDataFileScanTaskReader.java
- flink/v1.13/flink/src/main/java/org/apache/iceberg/flink/source/RowDataFileScanTaskReader.java
- spark/v2.4/spark/src/main/java/org/apache/iceberg/spark/source/RowDataReader.java
- spark/v3.0/spark/src/main/java/org/apache/iceberg/spark/source/RowDataReader.java
- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/source/RowDataReader.java
I missed the older modules when doing this update https://github.com/apache/iceberg/pull/4381
@stevenzwu @danielcweeks
> Core: Update constructor parameters for older DeleteFilter implementations

- data/src/main/java/org/apache/iceberg/data/TableMigrationUtil.java
- Was reading this class `TableMigrationUtil` found this typo -> `Merics` -> `Metrics`
This PR attempts to fix this .
> Data : fix typo in TableMigrationUtil

- docs/spark/spark-procedures.md
Fix broken javadoc link for RewriteManifests in the docs. 
previous link: https://iceberg.apache.org/javadoc/0.13.1/org/apache/iceberg/actions/RewriteManifestsAction.html
new link: https://iceberg.apache.org/javadoc/0.13.1/org/apache/iceberg/actions/RewriteManifests.html
> Docs: Fix broken javadoc link for RewriteManifests

- open-api/rest-catalog-open-api.yaml
This cleans up some of the error response documentation in the REST protocol.
* Documents 500 and 504 specifically in the table commit route
* Adds `stack` to error responses for sending server-side stack traces (optional)
* Adds 419 to all routes to signal that authentication has timed out
* Adds 503 to all routes for a back-pressure signal
> Spec: Clean up error responses in REST protocol

- core/src/main/java/org/apache/iceberg/rest/HTTPClient.java
As a follow up to some comments on this PR here https://github.com/apache/iceberg/pull/4245#discussion_r835964263, the RESTCatalog's HTTPClient's builder should only expose the object mapper for testing.
Otherwise, the correct object mapper that knows how to handle all of the necessary request / response types should be used.
Also removing a method that is not used, `Builder#httpClient`.
cc @rdblue
> Core - Mark the object mapper in HTTPClient#Builder as visible for testing

- spark/v3.2/spark/src/jmh/java/org/apache/iceberg/spark/data/parquet/SparkParquetReadersFlatDataBenchmark.java
- spark/v3.2/spark/src/jmh/java/org/apache/iceberg/spark/data/parquet/SparkParquetReadersNestedDataBenchmark.java
- spark/v3.2/spark/src/jmh/java/org/apache/iceberg/spark/data/parquet/SparkParquetWritersFlatDataBenchmark.java
- spark/v3.2/spark/src/jmh/java/org/apache/iceberg/spark/data/parquet/SparkParquetWritersNestedDataBenchmark.java
- spark/v3.2/spark/src/jmh/java/org/apache/iceberg/spark/source/avro/AvroWritersBenchmark.java
- spark/v3.2/spark/src/jmh/java/org/apache/iceberg/spark/source/avro/IcebergSourceFlatAvroDataReadBenchmark.java
- spark/v3.2/spark/src/jmh/java/org/apache/iceberg/spark/source/avro/IcebergSourceNestedAvroDataReadBenchmark.java
- spark/v3.2/spark/src/jmh/java/org/apache/iceberg/spark/source/orc/IcebergSourceFlatORCDataReadBenchmark.java
- spark/v3.2/spark/src/jmh/java/org/apache/iceberg/spark/source/orc/IcebergSourceNestedListORCDataWriteBenchmark.java
- spark/v3.2/spark/src/jmh/java/org/apache/iceberg/spark/source/orc/IcebergSourceNestedORCDataReadBenchmark.java
- spark/v3.2/spark/src/jmh/java/org/apache/iceberg/spark/source/parquet/IcebergSourceFlatParquetDataFilterBenchmark.java
- spark/v3.2/spark/src/jmh/java/org/apache/iceberg/spark/source/parquet/IcebergSourceFlatParquetDataReadBenchmark.java
- spark/v3.2/spark/src/jmh/java/org/apache/iceberg/spark/source/parquet/IcebergSourceFlatParquetDataWriteBenchmark.java
- spark/v3.2/spark/src/jmh/java/org/apache/iceberg/spark/source/parquet/IcebergSourceNestedListParquetDataWriteBenchmark.java
- spark/v3.2/spark/src/jmh/java/org/apache/iceberg/spark/source/parquet/IcebergSourceNestedParquetDataFilterBenchmark.java
- spark/v3.2/spark/src/jmh/java/org/apache/iceberg/spark/source/parquet/IcebergSourceNestedParquetDataReadBenchmark.java
- spark/v3.2/spark/src/jmh/java/org/apache/iceberg/spark/source/parquet/IcebergSourceNestedParquetDataWriteBenchmark.java
- spark/v3.2/spark/src/jmh/java/org/apache/iceberg/spark/source/parquet/IcebergSourceParquetEqDeleteBenchmark.java
- spark/v3.2/spark/src/jmh/java/org/apache/iceberg/spark/source/parquet/IcebergSourceParquetMultiDeleteFileBenchmark.java
- spark/v3.2/spark/src/jmh/java/org/apache/iceberg/spark/source/parquet/IcebergSourceParquetPosDeleteBenchmark.java
- spark/v3.2/spark/src/jmh/java/org/apache/iceberg/spark/source/parquet/IcebergSourceParquetWithUnrelatedDeleteBenchmark.java
- spark/v3.2/spark/src/jmh/java/org/apache/iceberg/spark/source/parquet/ParquetWritersBenchmark.java
- spark/v3.2/spark/src/jmh/java/org/apache/iceberg/spark/source/parquet/vectorized/VectorizedReadDictionaryEncodedFlatParquetDataBenchmark.java
- spark/v3.2/spark/src/jmh/java/org/apache/iceberg/spark/source/parquet/vectorized/VectorizedReadFlatParquetDataBenchmark.java
As a followup to https://github.com/apache/iceberg/pull/4328, the Spark JMH benchmarks previously had invalid commands in their JavaDoc comments since we migrated to version specific Spark builds.
This updates all of the Spark 3.2 tests to include the `sparkVersions` system property, so that the tests are correct even when we move to Spark 3.3 or change the default spark version.
This also updates 4 tests that were missed in https://github.com/apache/iceberg/pull/4328
> Spark: Update Spark 3.2 JMH Benchmark javadoc instructions

- spark/v3.1/spark/src/jmh/java/org/apache/iceberg/spark/data/parquet/SparkParquetReadersFlatDataBenchmark.java
- spark/v3.1/spark/src/jmh/java/org/apache/iceberg/spark/data/parquet/SparkParquetReadersNestedDataBenchmark.java
- spark/v3.1/spark/src/jmh/java/org/apache/iceberg/spark/data/parquet/SparkParquetWritersFlatDataBenchmark.java
- spark/v3.1/spark/src/jmh/java/org/apache/iceberg/spark/data/parquet/SparkParquetWritersNestedDataBenchmark.java
- spark/v3.1/spark/src/jmh/java/org/apache/iceberg/spark/source/avro/AvroWritersBenchmark.java
- spark/v3.1/spark/src/jmh/java/org/apache/iceberg/spark/source/avro/IcebergSourceFlatAvroDataReadBenchmark.java
- spark/v3.1/spark/src/jmh/java/org/apache/iceberg/spark/source/avro/IcebergSourceNestedAvroDataReadBenchmark.java
- spark/v3.1/spark/src/jmh/java/org/apache/iceberg/spark/source/orc/IcebergSourceFlatORCDataReadBenchmark.java
- spark/v3.1/spark/src/jmh/java/org/apache/iceberg/spark/source/orc/IcebergSourceNestedListORCDataWriteBenchmark.java
- spark/v3.1/spark/src/jmh/java/org/apache/iceberg/spark/source/orc/IcebergSourceNestedORCDataReadBenchmark.java
- spark/v3.1/spark/src/jmh/java/org/apache/iceberg/spark/source/parquet/IcebergSourceFlatParquetDataFilterBenchmark.java
- spark/v3.1/spark/src/jmh/java/org/apache/iceberg/spark/source/parquet/IcebergSourceFlatParquetDataReadBenchmark.java
- spark/v3.1/spark/src/jmh/java/org/apache/iceberg/spark/source/parquet/IcebergSourceFlatParquetDataWriteBenchmark.java
- spark/v3.1/spark/src/jmh/java/org/apache/iceberg/spark/source/parquet/IcebergSourceNestedListParquetDataWriteBenchmark.java
- spark/v3.1/spark/src/jmh/java/org/apache/iceberg/spark/source/parquet/IcebergSourceNestedParquetDataFilterBenchmark.java
- spark/v3.1/spark/src/jmh/java/org/apache/iceberg/spark/source/parquet/IcebergSourceNestedParquetDataReadBenchmark.java
- spark/v3.1/spark/src/jmh/java/org/apache/iceberg/spark/source/parquet/IcebergSourceNestedParquetDataWriteBenchmark.java
- spark/v3.1/spark/src/jmh/java/org/apache/iceberg/spark/source/parquet/ParquetWritersBenchmark.java
- spark/v3.1/spark/src/jmh/java/org/apache/iceberg/spark/source/parquet/vectorized/VectorizedReadDictionaryEncodedFlatParquetDataBenchmark.java
- spark/v3.1/spark/src/jmh/java/org/apache/iceberg/spark/source/parquet/vectorized/VectorizedReadFlatParquetDataBenchmark.java
Similar to https://github.com/apache/iceberg/pull/4328, the Spark JMH benchmarks have invalid commands in their JavaDoc comment ever since we migrated to version specific Spark builds.
This updates all of the Spark 3.1 tests to use the correct project `iceberg-spark-3.1_2.12:jmh` as well as pass the system property `sparkVersions=3.1`, as it's not included in the default Spark versions in our gradle configuration.
cc @rdblue who reviewed the last one.
> Spark - Update commands for running Spark 3.1 JMH Benchmarks

- format/spec.md
This is somewhat pedantic.  Based on current wording:
`Each value must be less than or equal to all non-null, non-NaN values in the column for the file [2]`
Based on defined sorting statistics
`Sorting floating-point numbers should produce the following behavior: -NaN < -Infinity < -value < -0 < 0 < value < Infinity < NaN` -NaN could be a lower bound and NaN could be an upper bound.
This PR tries to clarify whether statistics can or can't used for lower and upper bounds (I think the first sentence quoted might have been intended to rule out NaN but it isn't clear, so I'm happy to reverse this language to state that +/- NaN are valid values for bounds if that is the case).
> [Spec] Clarify whether floating point lower and upper bounds can contain NaNs

- core/src/main/java/org/apache/iceberg/CachingCatalog.java
- core/src/test/java/org/apache/iceberg/hadoop/TestCachingCatalog.java
When there is a chain of catalogs with one catalog wrapped inside the other, then the missing catalog.invalidateTable
call can prevent a table from being invalidated. In case the wrapped catalog is a CachingCatalog, then this prevents the table to be removed from the cache. We need to call catalog.invalidateTable() so that the call can recurse to invoke invalidateTable on all the chained catalogs.
> Core: InvalidateTable in CachingCatalog should invoke InvalidateTable on the wrapped catalog too.

- core/src/main/java/org/apache/iceberg/AllManifestsTable.java
- core/src/main/java/org/apache/iceberg/ManifestsTable.java
- core/src/main/java/org/apache/iceberg/Partitioning.java
- core/src/test/java/org/apache/iceberg/TestMetadataTableScans.java
- core/src/test/java/org/apache/iceberg/TestPartitioning.java
This patch fixes two problems:
1. For V1 tables, we use a `VoidTransform` to replace the removed partition field. While the result type of `VoidTransform` same as the type of the field. For example, the result type of `Bucket(2, string_type_field)` is int, while is string for `VoidTransform(string_type_field)`. So we should use the original partition field type(int instead of string) to build the common partitioning type.
2. We should use the matched `PartitionSpec` to convert the `PartitionFiedlSummary` to human string, not the current table spec.
Closes #3374
> Fixes read metadata failed after dropped partition for V1 format

- build.gradle
- core/src/test/java/org/apache/iceberg/catalog/CatalogTests.java
- core/src/test/java/org/apache/iceberg/jdbc/TestJdbcCatalog.java
- core/src/test/java/org/apache/iceberg/rest/TestRESTCatalog.java
We are planning to add a `TestNessieCatalog` test that extends the
existing `CatalogTests` class. However, Nessie tests require
JUnit5 functionality to set up the Nessie server, therefore we need to
convert these catalog tests to JUnit5.
> Core: Make CatalogTests run with JUnit5

- core/src/main/java/org/apache/iceberg/rest/responses/ErrorResponse.java
- core/src/main/java/org/apache/iceberg/rest/responses/ErrorResponseParser.java
- core/src/test/java/org/apache/iceberg/rest/RESTCatalogAdapter.java
- core/src/test/java/org/apache/iceberg/rest/responses/TestErrorResponseParser.java
#4367 added a way to send stack traces in REST error responses. This updates the `ErrorResponse` implementation and test code to send stack traces.
> Core: Add stack trace to ErrorResponse

- core/src/main/java/org/apache/iceberg/io/ClusteredDataWriter.java
- core/src/main/java/org/apache/iceberg/io/ClusteredEqualityDeleteWriter.java
- core/src/main/java/org/apache/iceberg/io/ClusteredPositionDeleteWriter.java
- core/src/main/java/org/apache/iceberg/io/FanoutDataWriter.java
- data/src/test/java/org/apache/iceberg/io/TestPartitioningWriters.java
- data/src/test/java/org/apache/iceberg/io/TestPositionDeltaWriters.java
- flink/v1.12/flink/src/test/java/org/apache/iceberg/flink/actions/TestRewriteDataFilesAction.java
- flink/v1.12/flink/src/test/java/org/apache/iceberg/flink/sink/TestIcebergStreamWriter.java
- flink/v1.12/flink/src/test/java/org/apache/iceberg/flink/sink/TestTaskWriters.java
- flink/v1.13/flink/src/test/java/org/apache/iceberg/flink/actions/TestRewriteDataFilesAction.java
- flink/v1.13/flink/src/test/java/org/apache/iceberg/flink/sink/TestIcebergStreamWriter.java
- flink/v1.13/flink/src/test/java/org/apache/iceberg/flink/sink/TestTaskWriters.java
- spark/v2.4/spark/src/jmh/java/org/apache/iceberg/spark/source/WritersBenchmark.java
- spark/v2.4/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkDataWrite.java
- spark/v3.0/spark/src/jmh/java/org/apache/iceberg/spark/source/WritersBenchmark.java
- spark/v3.0/spark/src/main/java/org/apache/iceberg/spark/source/SparkWrite.java
- spark/v3.0/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkDataWrite.java
- spark/v3.1/spark/src/jmh/java/org/apache/iceberg/spark/source/WritersBenchmark.java
- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/source/SparkWrite.java
- spark/v3.1/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkDataWrite.java
- spark/v3.2/spark/src/jmh/java/org/apache/iceberg/spark/source/IcebergSourceDeleteBenchmark.java
- spark/v3.2/spark/src/jmh/java/org/apache/iceberg/spark/source/WritersBenchmark.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/SparkPositionDeltaWrite.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/SparkWrite.java
This PR consists of the following parts:
- Port ORC rolling writer  and unit test to `Spark 3.1 3.0 2.4` and `Flink 1.13 1.12`, refer: [#3784](https://github.com/apache/iceberg/pull/3784)
- Clear the `Formart`  that are no longer needed.
> Spark/Flink: ORC support estimated length for unclosed file.

- core/src/main/java/org/apache/iceberg/TableProperties.java
- docs/tables/configuration.md
- orc/src/main/java/org/apache/iceberg/orc/ORC.java
- orc/src/test/java/org/apache/iceberg/orc/TestTableProperties.java
This PR adds compression-codec and compression-strategy of ORC in `TableProperties`, @openinx @hililiwei would you help review this? Thanks!
> ORC: Add compression properties

- python/setup.cfg
- python/src/iceberg/expression/__init__.py
- python/src/iceberg/expression/literals.py
- python/src/iceberg/types.py
- python/tests/expression/__init__.py
- python/tests/expression/test_literals.py
- python/tox.ini
First step of closing https://github.com/apache/iceberg/issues/4250
This is my first iceberg python contribution, so there might be some naive mistake and please let me know so I can jump to fix, most of the code is refactoring from https://github.com/apache/iceberg/blob/master/python_legacy/iceberg/api/expressions/literals.py to our latest python module
Change highlights
- Refactor all static method to module level methods to be more pythonic
- Use [singledispath](https://docs.python.org/3/library/functools.html#functools.singledispatch) to dynamic overload the Literal factory from python primitive type and conversion between iceberg types
- Adopt the new TimestampType from types, 
- replace `TimestampType.with_timezone` with `TimestampTzType` 
- replace `TimestampType.without_timezone` …
> Python support on Literals

- python/src/iceberg/conversions.py
- python/tests/test_conversions.py
This adds functionality for converting a value to bytes and vice-versa augmented by the `PrimitiveType` subclass provided.
Functionally this is a direct port of [conversion.py](https://github.com/apache/iceberg/blob/master/python_legacy/iceberg/api/types/conversions.py) in the python legacy library. The main changes are:
1. I replaced the large dictionaries containing `<type>: <lambda function>` pairs with [@singledispatch](https://docs.python.org/3/library/functools.html#functools.singledispatch)
2. I removed the [TypeID](https://github.com/apache/iceberg/blob/master/python_legacy/iceberg/api/types/type.py#L24) enum and instead just used the types directly.
Overall this is more lines of source code but I'll summarize my reasonings for the above two changes:
1. I believe the intention …
> Python: Serialization/Deserialization for types and partition values (port of conversions.py from python_legacy)

- core/src/main/java/org/apache/iceberg/rest/HTTPClient.java
- core/src/main/java/org/apache/iceberg/rest/RESTMessage.java
- core/src/main/java/org/apache/iceberg/rest/RESTRequest.java
- core/src/main/java/org/apache/iceberg/rest/RESTResponse.java
- core/src/main/java/org/apache/iceberg/rest/requests/CreateNamespaceRequest.java
- core/src/main/java/org/apache/iceberg/rest/requests/CreateTableRequest.java
- core/src/main/java/org/apache/iceberg/rest/requests/UpdateNamespacePropertiesRequest.java
- core/src/main/java/org/apache/iceberg/rest/requests/UpdateTableRequest.java
- core/src/main/java/org/apache/iceberg/rest/responses/CreateNamespaceResponse.java
- core/src/main/java/org/apache/iceberg/rest/responses/ErrorResponse.java
- core/src/main/java/org/apache/iceberg/rest/responses/GetNamespaceResponse.java
- core/src/main/java/org/apache/iceberg/rest/responses/ListNamespacesResponse.java
- core/src/main/java/org/apache/iceberg/rest/responses/ListTablesResponse.java
- core/src/main/java/org/apache/iceberg/rest/responses/LoadTableResponse.java
- core/src/main/java/org/apache/iceberg/rest/responses/RESTCatalogConfigResponse.java
- core/src/main/java/org/apache/iceberg/rest/responses/UpdateNamespacePropertiesResponse.java
- core/src/test/java/org/apache/iceberg/rest/RESTCatalogAdapter.java
- core/src/test/java/org/apache/iceberg/rest/RequestResponseTestBase.java
- core/src/test/java/org/apache/iceberg/rest/TestHTTPClient.java
- core/src/test/java/org/apache/iceberg/rest/requests/TestCreateNamespaceRequest.java
- core/src/test/java/org/apache/iceberg/rest/requests/TestUpdateNamespacePropertiesRequest.java
- core/src/test/java/org/apache/iceberg/rest/responses/TestCreateNamespaceResponse.java
- core/src/test/java/org/apache/iceberg/rest/responses/TestGetNamespaceResponse.java
- core/src/test/java/org/apache/iceberg/rest/responses/TestListNamespacesResponse.java
- core/src/test/java/org/apache/iceberg/rest/responses/TestListTablesResponse.java
- core/src/test/java/org/apache/iceberg/rest/responses/TestRESTCatalogConfigResponse.java
- core/src/test/java/org/apache/iceberg/rest/responses/TestUpdateNamespacePropertiesResponse.java
Adds three empty interfaces, that are used for marking classes that correspond to REST requests / responses.
1) `RESTMessage` - This marks either a RESTRequest or a RESTResponse. The name is chosen to match many libraries, like Netty, where the `HTTPRequest` extends `HTTPMessage`.
2) `RESTRequest` - Specific empty subinterface for classes that correlate to REST catalog requests.
3) `RESTResponse` - Specific empty subinterface for classes that correlate to REST catalog resposnes.
Right now, these are empty but in the future we could add things like the `validate` method, or anything else that is needed. Eventually we could possibly even move these into the api module.
For now, this is in response to [a comment here](https://github.com/apache/iceberg/pull/4245#discussion_r832570043) so that …
> Core - Add marker interfaces for both RESTRequests and RESTResponses

- flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/data/FlinkParquetReaders.java
- flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/source/TestFlinkScan.java
In flink, only three predefined types of `ArrayData` are accepted by
`ArrayDataSerializer#copy`. It's not allowed to return customized type
of `ArrayData`, otherwise a `ClassCastException` will be thrown.
> Flink: fix parquet readers for array data

- aliyun/src/main/java/org/apache/iceberg/aliyun/oss/OSSInputStream.java
This PR is a follow-up of @rdblue's feedback: https://github.com/apache/iceberg/pull/4393#discussion_r838900710
Deprecating the constructor would maintain parity with the other InputStream classes like `GCSInputStream`, `EcsSeekableInputStream`, and `S3InputStream` which have a package private constructor.
cc: @rdblue
> Aliyun: Deprecate OSSInputStream public constructor

- .github/labeler.yml
- on raising a PR effecting DELL changes, the PR was not tagged with DELL label (looks like DELL folder was added recently), where as Aliyun / GCP tag got added.
- https://github.com/apache/iceberg/pull/4461
This change attempts to give PR labeler a way to tag DELL related changes with DELL tag.
---- 
cc @kbendick
> [BUILD] : Add DELL in PR labeler

- baseline.gradle
- build.gradle
This adds the three spotless tasks to the build:
```
spotlessApply - Applies code formatting steps to sourcecode in-place.
spotlessCheck - Checks that sourcecode satisfies formatting steps.
spotlessDiagnose
```
> Build: Update spotless version and add spotless tasks

- parquet/src/main/java/org/apache/iceberg/parquet/Parquet.java
- spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/SparkRowLevelOperationsTestBase.java
we faced concurrent modification issue in ORC when trying to modify existing hadoop conf from HadoopFileIO in ORC write builder.  ref : [Issue#4383](https://github.com/apache/iceberg/issues/4383), [PR#4384](https://github.com/apache/iceberg/pull/4384)
Looks like this code snippet was present in Parquet#write as well, based on discussion https://github.com/apache/iceberg/pull/3810#issuecomment-1061334692
As per my understanding, we should do the same changes as we did in the ORC, here in parquet. The issue we had in ORC (given that we expect our PR fixed it), could also happen in Parquet#write under same circumstances, added a test for the same
----
cc @openinx, @hililiwei , @rdblue
> Parquet: Avoid modifying existing conf of HadoopOutputFile rather create new one

- docs/tables/configuration.md
> Docs: fix format-version doc returns 404 not found

- aliyun/src/main/java/org/apache/iceberg/aliyun/oss/OSSFileIO.java
- dell/src/main/java/org/apache/iceberg/dell/ecs/EcsFileIO.java
- gcp/src/main/java/org/apache/iceberg/gcp/gcs/GCSFileIO.java
recently a change went in which showed / fixed thread safety concern with S3FileIO. This made me check other FileIO looks like this handling is missing here as well.
- https://github.com/apache/iceberg/pull/4454 
- As per my understanding the FileIO obj when serialized and sent to the executors (via broadcast) , it will be shared by all tasks within the executor, since the client is marked `transient` it will be re-initialized when it reaches executor and now the client initialization can be triggered by any of task threads hence raising the possibility of race condition.
This change attempts to fix all remaining FileIO's as well.
--- 
cc @jfz @rdblue
> Aliyun / GCP / DELL : make client initialization thread safe in all FileIOs

- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/SparkTable.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/actions/TestCreateActions.java
Unit tests was updated. Also tested manually in Spark SQL. The first table does not have identifier fields while the second table (same schema) has identifier fields.
Was following the pattern in #2330 for `location`. Thanks @flyrain 
Not sure is example `[userName,productId]` a good format? The comma is used to join multiple table properties in the shell.
> Spark: DESCRIBE TABLE EXTENDED shows identifier fields

- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/SparkScan.java
As per my understanding, presently we don't take `SplitScanTask`(which also implements FileScanTask),into consideration where we would _**not**_ be reading the complete file rather a subpart of the file. 
So in this case it's better to find number of records actually scanned by the task, rather than going to datafile this splitscanTask is based on and get's its complete record count. 
At present it seems like we are over-estimating the size by taking complete record count of the file associated with the SplitScanTask, where as we are just scanning the subset of data from this file.
---
cc @rdblue @aokolnychyi @RussellSpitzer @jackye1995  @wypoon
> Spark [3.2] : Improve stats estimation for spark scan

- core/src/main/java/org/apache/iceberg/rest/RESTCatalog.java
- core/src/main/java/org/apache/iceberg/rest/RESTUtil.java
- core/src/main/java/org/apache/iceberg/rest/ResourcePaths.java
- core/src/test/java/org/apache/iceberg/catalog/CatalogTests.java
- core/src/test/java/org/apache/iceberg/rest/RESTCatalogAdapter.java
- core/src/test/java/org/apache/iceberg/rest/TestRESTUtil.java
- core/src/test/java/org/apache/iceberg/rest/TestResourcePaths.java
This adds a helper class, `ResourcePaths` to construct resource paths in the REST catalog. This cleans up path construction to be based on REST resource and adds support for the `prefix` parameter in the REST spec.
This also adds tests for each resource and validates the multipart namespace (null byte) handling.
> Core: Add ResourcePaths helper for REST

- spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRemoveOrphanFilesProcedure.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/actions/BaseDeleteOrphanFilesSparkAction.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/actions/BaseDeleteReachableFilesSparkAction.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/actions/BaseExpireSnapshotsSparkAction.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/actions/BaseSparkAction.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/actions/TestDeleteReachableFilesAction.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/actions/TestRemoveOrphanFilesAction.java
This PR includes minor refactoring for a few actions to make them more consistent.
> Spark 3.2: Refactor certain actions

- python/src/iceberg/conversions.py
- python/src/iceberg/expression/literals.py
- python/src/iceberg/transforms.py
- python/src/iceberg/utils/datetime.py
- python/src/iceberg/utils/decimal.py
- python/tests/test_conversions.py
- python/tests/test_transforms.py
This fixes a couple of minor comments from #4416 and refactors to use common decimal and datetime util functions.
> Python: Refactor to use common decimal and datetime util

- spark/v3.2/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/parser/extensions/IcebergSparkSqlExtensionsParser.scala
- spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestCallStatementParser.java
- spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestExpireSnapshotsProcedure.java
This closes issue https://github.com/apache/iceberg/issues/4289
Currently, We ignore simple comments (those that start with `--`), as well as bracketed comments in our IcebergSqlExtensions ANTLR grammar.
However, we have a function `isIcebergCommand`, that checks if a command is an Iceberg command by checking if the string starts with specific phrases that match known Iceberg commands.
The sqlText has not yet been passed through the full ANTLR process, so we need to ignore comments manually, akin to ignoring new-lines in https://github.com/apache/iceberg/pull/2729
-------------------------------------------------
There might be a better way to handle this, but this does work for recognizing the Iceberg commands, while still allowing the antlr parser to remove comments, as it has special …
> Spark - Ignore SQL comments when testing if SQL command is an Iceberg specific command

- core/src/main/java/org/apache/iceberg/rest/RESTCatalog.java
- core/src/main/java/org/apache/iceberg/rest/ResourcePaths.java
- core/src/main/java/org/apache/iceberg/rest/requests/CreateTableRequest.java
- core/src/test/java/org/apache/iceberg/rest/RESTCatalogAdapter.java
- core/src/test/java/org/apache/iceberg/rest/TestResourcePaths.java
- open-api/rest-catalog-open-api.yaml
This fixes an outstanding item in `RESTCatalog`, which was to determine whether to create a separate route for create table transactions. This reuses the existing create table route with a flag to stage the create to begin the transaction. This includes both spec and code updates.
> Core: Add stage-create flag to REST create route

- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/source/TestStructuredStreamingRead3.java
This PR removes the redundant table refresh calls in `TestStructuredStreamingRead3`. The table instance after `commit` should always be up to date.
---
cc: @RussellSpitzer @rdblue
> Spark: Remove redundant table refresh calls in TestStructuredStreamingRead3

- core/src/main/java/org/apache/iceberg/util/JsonUtil.java
- core/src/test/java/org/apache/iceberg/rest/responses/TestErrorResponseParser.java
When testing the `ErrorResponse`, it came up that `JsonUtils#getStringListOrNull` fails when the node in question (element by name) is explicitly null.
Fixes the issue for both `getXCollectionOrNull` functions in `JsonUtils`.
> Core - Fix JsonUtils collection or null functions when an explicit null value is used

- python_legacy/iceberg/core/base_transaction.py
- python_legacy/tests/api/expressions/test_predicate_binding.py
- python_legacy/tests/api/test_conversions.py
fix: change invalid typo `commited` to `committed`
> chore: commenting invalid typo `commited` in base_transaction.py and fix invalid typos in test_cases

- core/src/main/java/org/apache/iceberg/AllDataFilesTable.java
- core/src/main/java/org/apache/iceberg/BaseAllMetadataTableScan.java
- core/src/main/java/org/apache/iceberg/BaseFilesTable.java
- core/src/main/java/org/apache/iceberg/BaseMetadataTableScan.java
- core/src/main/java/org/apache/iceberg/DataFilesTable.java
- core/src/main/java/org/apache/iceberg/DeleteFilesTable.java
- core/src/main/java/org/apache/iceberg/FilesTable.java
- core/src/test/java/org/apache/iceberg/TestMetadataTableFilters.java
- spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMetadataTables.java
This adopts all_data_files table on new base class added in #4139 , which will allow it predicate-push-down for partition predicates.
Change the base class  manifests() method slightly from List to Iterable, to support the original ParallelIterable of the AllDataFilesTable.
Inherit some WAP (staging snapshot) handling from BaseAllMetadataTableScan.
> Core: Predicate pushdown for all_data_files table

- build.gradle
- dell/src/main/java/org/apache/iceberg/dell/ecs/BaseEcsFile.java
- dell/src/main/java/org/apache/iceberg/dell/ecs/EcsAppendOutputStream.java
- dell/src/main/java/org/apache/iceberg/dell/ecs/EcsFileIO.java
- dell/src/main/java/org/apache/iceberg/dell/ecs/EcsInputFile.java
- dell/src/main/java/org/apache/iceberg/dell/ecs/EcsOutputFile.java
- dell/src/main/java/org/apache/iceberg/dell/ecs/EcsSeekableInputStream.java
- dell/src/test/java/org/apache/iceberg/dell/ecs/TestEcsAppendOutputStream.java
- dell/src/test/java/org/apache/iceberg/dell/ecs/TestEcsSeekableInputStream.java
This PR adds metrics tracking for `EcsFileIO`. This would help reporting IO metrics via the Hadoop `FileSystem.Statistics`.
---
cc: @danielcweeks @rdblue @kbendick
> Dell: Add metrics tracking for EcsFileIO

- flink/v1.13/flink/src/main/java/org/apache/iceberg/flink/data/FlinkParquetReaders.java
- flink/v1.13/flink/src/test/java/org/apache/iceberg/flink/TestHelpers.java
- flink/v1.13/flink/src/test/java/org/apache/iceberg/flink/source/TestFlinkScan.java
Apply fixing #4432 to Flink version 1.13
> Flink 1.13: Fix parquet readers for array data

- flink/v1.12/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java
- flink/v1.13/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java
- flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java
Just clear the deprecated `FlinkSink#build` among flink versions.
> Flink: Clear the deprecated FlinkSink#build.

- core/src/main/java/org/apache/iceberg/TableProperties.java
- hive-metastore/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java
- hive-metastore/src/test/java/org/apache/iceberg/hive/TestHiveCatalog.java
- mr/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerNoScan.java
cc @aokolnychyi @RussellSpitzer @raptond @karuppayya @szehon-ho @kbendick
> Hive: Expose Snapshot Stats in HMS.

- docs/spark/spark-queries.md
> spark: supplement spark-queries.md doc

- flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/source/FlinkSource.java
- flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/source/TestFlinkScanSql.java
The max parallelism of nodes in Flink stream graph will be set as global max parallelism if configured
we should respect it while inferring the source parallelism.
> Flink: inferred parallelism should respect global settings

- flink/v1.13/flink/src/test/java/org/apache/iceberg/flink/TestFlinkUpsert.java
- flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/TestFlinkUpsert.java
In Flink, only VALUES with literal tuples can be converted to a single
LogicalValues node. VALUES with other type of tuples will be converted
to a chain with multiple LogicalProject nodes, like following:
LogicalValues -> (# number or rows)LogicalProject -> LogicalUnion.
The `TO_DATE('xxxx-xx-xx')` expression is not a literal node, so the
VALUES used in upsert test cases will be converted in the latter way.
The order of tuples can not be guaranteed, which can lead to unstable
test results.
Changing `TO_DATE('xxxx-xx-xx')` to `DATE 'xxxx-xx-xx'` can make it a
literal node and ensure that the VALUES expression can be converted to a
single LogicalValues node.
fixes #4515
> Flink: fix out of order appends in upsert UT

- core/src/main/java/org/apache/iceberg/rest/HTTPClient.java
- core/src/main/java/org/apache/iceberg/rest/HTTPClientFactory.java
- core/src/main/java/org/apache/iceberg/rest/RESTCatalog.java
- core/src/main/java/org/apache/iceberg/rest/RESTCatalogProperties.java
- core/src/main/java/org/apache/iceberg/rest/RESTObjectMapper.java
- core/src/test/java/org/apache/iceberg/rest/RESTCatalogAdapter.java
- core/src/test/java/org/apache/iceberg/rest/TestHTTPClient.java
- core/src/test/java/org/apache/iceberg/rest/TestRESTCatalog.java
Adds the initial call to `/v1/config` and merges the server-side configuration with the client configuration.
Also adds in an object mapper specific to the RESTCatalog, so that the object mapper in `JsonUtils` doesn't need to be modified.
> Core - REST Catalog call /v1/config route

- core/src/main/java/org/apache/iceberg/PartitionsTable.java
- core/src/test/java/org/apache/iceberg/TestMetadataTableScans.java
- spark/v2.4/spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSourceTablesBase.java
- spark/v3.0/spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSourceTablesBase.java
- spark/v3.1/spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSourceTablesBase.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSourceTablesBase.java
As per #4292, PartitionsTable should call Partitioning.partitionType() to gather the partition struct in its schema. Also the result should show specId too, as the partition key might not be considered a unique key on its own without specId in V2 format. (E.g a partition column removed then re-added along with another column..)
This is just the initial change so that I can see what tests would need fixing and to check with community if the new schema is okay like this:
1. spec_id
2. partition
3. record_count
4. file_count
I think in other meta tables the spec_id precedes the partition key in the output, so I prepended the existing schema here with it. I'm not sure if this counts as a backward-incompatible change though. What do you think @aokolnychyi ?
> Adding specId for partitions metadata table

- .baseline/checkstyle/checkstyle.xml
`BanUnrelocatedGuavaClasses` requires that `Preconditions` are imported
from a relocated package, so allowing *static* imports for unrelocated
`Preconditions` is not useful.
> Remove allow static imports for unrelocated Preconditions

- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/SparkTable.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/actions/TestCreateActions.java
Currently Spark SQL does not show table `format-version` in `SHOW TBLPROPERTIES`, `DESCRIBE TABLE` or `SHOW CREATE TABLE`. This could be based on the fact that `format-version` is a reserved table property and it's not persisted as usual table properties.
Still users may find it useful to inspect the table `format-version` via Spark SQL. One way is to show it via `DESC TABLE EXTENDED`. Towards that, this pull requests has 3 small commits:
1. Add a one liner test which explains the intention and fails
2. Show `format-version` for command `DESC TABLE EXTENDED` by adding it to Spark table properties
3. (cosmetic) Replace some literals with constants defined in `TableProperties.java`
> Spark: `DESC TABLE EXTENDED` shows table format-version

- core/src/main/java/org/apache/iceberg/BaseFilesTable.java
- core/src/main/java/org/apache/iceberg/BaseMetadataTable.java
- core/src/main/java/org/apache/iceberg/PartitionsTable.java
- core/src/test/java/org/apache/iceberg/TestMetadataTableFilters.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/source/TestMetadataTablesWithPartitionEvolution.java
The change https://github.com/apache/iceberg/pull/2926 introduced partition predicate push down for the "files" metadata table.  However, it is incorrect in the case that the partition spec evolves and data written in both specs.  The projectionFilter is constructed by projecting the expression on the current table's partition spec, and evaluating the values against the manifest file.
Say for example, we have a table that had a former partition spec that is "data", and a new partition spec that is "id", with manifests written with both specs.
A query like "select * from my_table.files where files.partition.id=1" projects successfully against the current partition spec "id" to have a ManifestEvaluator looking for value 1.  It looks for this against all manifest-files, even those written …
> Core: Files table predicate filtering wrong for tables with evolved partition specs

- api/src/main/java/org/apache/iceberg/ManageSnapshots.java
- core/src/main/java/org/apache/iceberg/BaseTransaction.java
- core/src/main/java/org/apache/iceberg/MetadataUpdate.java
- core/src/main/java/org/apache/iceberg/SnapshotManager.java
- core/src/main/java/org/apache/iceberg/TableMetadata.java
- core/src/main/java/org/apache/iceberg/UpdateSnapshotReferencesOperation.java
- core/src/main/java/org/apache/iceberg/util/SnapshotUtil.java
- core/src/test/java/org/apache/iceberg/TestSnapshotManager.java
Part of breaking up https://github.com/apache/iceberg/pull/3883.
This adds the UpdateSnapshotRefs API. Will add an implementation once Table/TableMetadata API implementations are complete, since an implementation would depend on those changes.
Co-authored-by: @hameizi 1249369293@qq.com
Co-authored-by: @jackye1995 yzhaoqin@amazon.com
> API: Add snapshot reference create, replace, rename, and rename operations to ManageSnapshots API

- api/src/main/java/org/apache/iceberg/PartitionSpec.java
- core/src/main/java/org/apache/iceberg/BaseUpdatePartitionSpec.java
- core/src/main/java/org/apache/iceberg/TableMetadataParser.java
While reading code about partition spec, i find some usages of magic number 999 which should be `PARTITION_DATA_ID_START - 1` i think. Fix me if i misunderstand.
@rdblue would you help to review if you have time?
> Remove magic number usage for last assigned partition id

- flink/v1.13/flink/src/main/java/org/apache/iceberg/flink/source/FlinkSource.java
- flink/v1.13/flink/src/test/java/org/apache/iceberg/flink/source/TestFlinkScanSql.java
> Flink 1.13: Inferred parallelism should respect global settings

- core/src/main/java/org/apache/iceberg/rest/RESTCatalog.java
- core/src/main/java/org/apache/iceberg/rest/responses/ConfigResponse.java
- core/src/test/java/org/apache/iceberg/rest/RESTCatalogAdapter.java
- core/src/test/java/org/apache/iceberg/rest/TestRESTCatalog.java
- core/src/test/java/org/apache/iceberg/rest/responses/TestRESTCatalogConfigResponse.java
- open-api/rest-catalog-open-api.yaml
In the REST Catalog's `initialize` lifecycle, the server sends back some configuration overrides & fallback (default) values, which are merged with whatever the application provided.
This renames the class from `RESTCatalogConfigResponse` to `ConfigResponse`, as the class already is in the package `org.apache.iceberg.rest.responses` anyway.1
Also updates the spec and fixes a slightly incorrect example `ConfigResponse` object.
cc @rdblue
> Core - Rename REST Catalog server configuration class to ConfigResponse

- api/src/main/java/org/apache/iceberg/RewriteJobOrder.java
- api/src/main/java/org/apache/iceberg/actions/RewriteDataFiles.java
- core/src/main/java/org/apache/iceberg/actions/RewriteFileGroup.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/actions/BaseRewriteDataFilesSparkAction.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteDataFilesAction.java
This PR introduces ordering of `RewriteFileGroup`. This should be helpful in cases where we want to force the compaction order according to the size (in bytes) or number of files.
Introduce a new Spark option `rewrite.job-order = {"bytes-asc", "bytes-desc", "files-asc", "files-desc", "none"}`.
- `rewrite.job-order=bytes-asc`: rewrite the smallest job groups first.
- `rewrite.job-order=bytes-desc`: rewrite the largest job groups first.
- `rewrite.job-order=files-asc`: rewrite the job groups with the least files first.
- `rewrite.job-order=files-desc`: rewrite the job groups with the most files first.
- `rewrite.job-order=none`: rewrite job groups in the order they were planned (no specific ordering).
---
cc: @RussellSpitzer
> Spark: Add option to introduce ordering of RewriteFileGroup

- api/src/main/java/org/apache/iceberg/actions/RewriteDataFiles.java
- spark/v3.0/spark/src/main/java/org/apache/iceberg/spark/actions/BaseRewriteDataFilesSparkAction.java
- spark/v3.0/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteDataFilesAction.java
- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/actions/BaseRewriteDataFilesSparkAction.java
- spark/v3.1/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteDataFilesAction.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteDataFilesAction.java
This PR backports https://github.com/apache/iceberg/pull/4377 to Spark 3.1 and Spark 3.0. 
The PR also includes the changes discussed here: https://github.com/apache/iceberg/pull/4377#discussion_r851419052 
---
cc: @RussellSpitzer @aokolnychyi
> Spark 3.x: Add option to introduce ordering of RewriteFileGroup

- docs/emr/_index.md
- docs/integrations/aws.md
EMR docs have been recently updated from : 
- https://docs.aws.amazon.com/emr/latest/ReleaseGuide/emr-iceberg-create-cluster.html
to 
- https://docs.aws.amazon.com/emr/latest/ReleaseGuide/emr-iceberg-use-cluster.html
This PR attempts to update the doc links to the most recent one, present link redirects (since it's removed) to default landing page : https://docs.aws.amazon.com/emr/latest/ReleaseGuide/emr-release-components.html
cc @rajarshisarkar
> Docs : Update EMR docs links

- core/src/main/java/org/apache/iceberg/AllManifestsTable.java
- core/src/main/java/org/apache/iceberg/ManifestsTable.java
- core/src/main/java/org/apache/iceberg/Partitioning.java
- core/src/test/java/org/apache/iceberg/TestMetadataTableScans.java
This backs port #3411 to 0.13.x branch.
This patch fixes two problems:
1. For V1 tables, we use a `VoidTransform` to replace the removed partition field. While the result type of `VoidTransform` same as the type of the field. For example, the result type of `Bucket(2, string_type_field)` is int, while is string for `VoidTransform(string_type_field)`. So we should use the original partition field type(int instead of string) to build the common partitioning type.
2. We should use the matched `PartitionSpec` to convert the `PartitionFiedlSummary` to human string, not the current table spec.
> [0.13] Core: Fixes read metadata failed after dropped partition transform for V1 format

- parquet/src/main/java/org/apache/iceberg/parquet/ParquetMetricsRowGroupFilter.java
While running `./gradlew build -x test -x integrationTest` to build the iceberg project, I noticed that the private function `converterFor` from class `ParquetMetricsRowGroupFilter` was not used in the repo. This is why I wanted to remove it. Please feel free to let me know if that makes sense.
> Removed un-used function converterFor from class ParquetMetricsRowGroupFilter

- flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/FlinkCatalog.java
- flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/TestFlinkCatalogTable.java
Because we have iceberg table with primary key, and we want to alter table properties.
This PR supports `ALTER TABLE ... SET ...` and `ALTER TABLE ... RESET ...` to modify a table properties which has primary key.   #4562
> Flink: support modify table properties with primary key.

- nessie/src/main/java/org/apache/iceberg/nessie/NessieCatalog.java
- nessie/src/main/java/org/apache/iceberg/nessie/NessieIcebergClient.java
- nessie/src/main/java/org/apache/iceberg/nessie/NessieTableOperations.java
- nessie/src/main/java/org/apache/iceberg/nessie/NessieUtil.java
- nessie/src/test/java/org/apache/iceberg/nessie/TestBranchVisibility.java
- nessie/src/test/java/org/apache/iceberg/nessie/TestNessieTable.java
This adds a new `NessieIcebergClient` class that encapsulates some of
the features that have been used across the `NessieCatalog`.
It also slightly improves the error messages to include the reference or
the table name when something fails.
Note that the `testFailure()` method was updated, because we're now
always using the same `UpdateableReference` between `NessieCatalog` and
`NessieTableOperations`, so that it's higly unlikely that those two get
out-of-sync.
> Nessie: Extract Catalog client code to NessieClient for Trino Consumption

- bundled-guava/src/main/java/org/apache/iceberg/GuavaClasses.java
- nessie/src/main/java/org/apache/iceberg/nessie/NessieIcebergClient.java
- nessie/src/test/java/org/apache/iceberg/nessie/TestNessieTable.java
Note that this also reverts the test changes that were done in https://github.com/apache/iceberg/commit/9618147b6de8f8627052a205b86e45263394b0c2#diff-a92127e5d74e2be0c013d0eddf4c9d2af29a71f05e21d7289808271d4c97db78L326-R348
> Nessie: Use memoized Supplier to avoid unnecessary API calls

- aws/src/main/java/org/apache/iceberg/aws/dynamodb/DynamoDbCatalog.java
- aws/src/main/java/org/apache/iceberg/aws/glue/GlueCatalog.java
- aws/src/test/java/org/apache/iceberg/aws/glue/TestGlueCatalog.java
- core/src/main/java/org/apache/iceberg/CatalogUtil.java
- core/src/main/java/org/apache/iceberg/LocationProviders.java
- core/src/main/java/org/apache/iceberg/hadoop/HadoopCatalog.java
- core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java
- core/src/main/java/org/apache/iceberg/util/LocationUtil.java
- core/src/test/java/org/apache/iceberg/TestTables.java
- core/src/test/java/org/apache/iceberg/util/TestLocationUtil.java
- dell/src/main/java/org/apache/iceberg/dell/ecs/EcsCatalog.java
- hive-metastore/src/main/java/org/apache/iceberg/hive/HiveCatalog.java
- hive-metastore/src/test/java/org/apache/iceberg/hive/TestHiveCatalog.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/source/TestTables.java
Closes https://github.com/apache/iceberg/issues/4582
This change attempts to fix :
1. In `locationsFor` we don't sanitize the location (i.e strip the trailing slash), this attempts to do this stripping
2. The warehouse location for hiveCatalog is also missing this handling rest all catalogs such as Hadoop / Glue have these handling 
3. Had to refactor a bit, slash stripping logic was duplicated in all catalogs. 
Note : nessie Catalog also  doesn't have this handling, will do the same in next iteration of this pr if experts from nessie   suggests this is required (appologies I am new to nessie)
4. Fixes a minor typo.
cc @szehon-ho , @RussellSpitzer , @jackye1995 , @flyrain
> Core : Strip trailing slash from tableLocation in LocationProvider

- python/src/iceberg/files.py
This adds a `FileContentType` and `FileFormat` enum and also a `StructProtocol` that documents the requirements for objects to be compatible with accessors.
> Adding file related enums and StructProtocol

- spark/v3.1/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/parser/extensions/IcebergSparkSqlExtensionsParser.scala
- spark/v3.1/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestCallStatementParser.java
- spark/v3.1/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestExpireSnapshotsProcedure.java
This backports https://github.com/apache/iceberg/pull/4396 to Spark 3.1
Allow for procedures to have leading comments when checking if the command is Iceberg specific DDL.
This allows for systems that add leading comments to SQL statements for metadata purposes, such as dbt, to work if the command in question is an Iceberg Spark Procedure.
> Spark - Allow procedures to have leading comments - Backport to Spark 3.1

- spark/v3.0/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/parser/extensions/IcebergSparkSqlExtensionsParser.scala
- spark/v3.0/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestCallStatementParser.java
- spark/v3.0/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestExpireSnapshotsProcedure.java
This backports https://github.com/apache/iceberg/pull/4396 to Spark 3.0
Allow for procedures to have leading comments when checking if the command is Iceberg specific DDL.
This allows for systems that add leading comments to SQL statements for metadata purposes, such as dbt, to work if the command in question is an Iceberg Spark Procedure.
> Spark: Ignore SQL comments when testing if command is Iceberg DDL - Backport to Spark 3.0

- .baseline/checkstyle/checkstyle.xml
- api/src/test/java/org/apache/iceberg/types/TestReadabilityChecks.java
- core/src/test/java/org/apache/iceberg/TestSchemaUnionByFieldName.java
- core/src/test/java/org/apache/iceberg/jdbc/TestJdbcCatalog.java
- spark/v2.4/spark/src/test/java/org/apache/iceberg/spark/data/TestParquetAvroReader.java
- spark/v2.4/spark/src/test/java/org/apache/iceberg/spark/data/TestSparkDateTimes.java
- spark/v3.0/spark/src/test/java/org/apache/iceberg/spark/data/TestParquetAvroReader.java
- spark/v3.0/spark/src/test/java/org/apache/iceberg/spark/data/TestSparkDateTimes.java
- spark/v3.1/spark/src/test/java/org/apache/iceberg/spark/data/TestParquetAvroReader.java
- spark/v3.1/spark/src/test/java/org/apache/iceberg/spark/data/TestSparkDateTimes.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/data/TestParquetAvroReader.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/data/TestSparkDateTimes.java
in checkstyle.xml, `Logging with System.out and System.err are not allowed because it has no metadata and can't be configured at runtime. Please use an SLF4J logger instead`. so use SLF4J logger instead System.out and System.err. 
- Current strategy:  Removing System.out and System.err
cc: @RussellSpitzer @rdblue
> System Printing: Removing System.out and System.err

- core/src/test/java/org/apache/iceberg/TestManifestListVersions.java
- core/src/test/java/org/apache/iceberg/TestManifestWriterVersions.java
- core/src/test/java/org/apache/iceberg/TestScansAndSchemaEvolution.java
- core/src/test/java/org/apache/iceberg/avro/TestAvroDeleteWriters.java
- core/src/test/java/org/apache/iceberg/avro/TestGenericAvro.java
- core/src/test/java/org/apache/iceberg/io/InMemoryInputFile.java
- core/src/test/java/org/apache/iceberg/io/InMemoryOutputFile.java
Sometimes an actual file is needed, but sometimes it's not. In the case
where it isn't, we can use an in-memory `InputFile`, `OutputFile`
implementation.
Extracted from https://github.com/apache/iceberg/pull/4537
> Use memory-backed streams in tests

- core/src/main/java/org/apache/iceberg/MetadataUpdateParser.java
- core/src/main/java/org/apache/iceberg/rest/RESTSerializers.java
- core/src/test/java/org/apache/iceberg/TestMetadataUpdateParser.java
- open-api/rest-catalog-open-api.yaml
We need to be able to serialize and deserialize instances of `MetadataUpdate`.
Because `MetadataUpdate` is an interface that has multiple implementations, I've added a serializer / deserializer that handles `MetadataUpdate` and then reads or write the correct value based on the `action` field, as defined in the open-api spec.
I've only implemented  and tested`MetadataUpdate#UpgradeFormatVersion`, and have laid the foundation for the remaining classes which I will handle in a follow up PR.
> [CORE] - Add MetadataUpdateParser and Jackson SerDe with implementation covering UpgradeFormatVersion

- core/src/main/java/org/apache/iceberg/AllDataFilesTable.java
- core/src/main/java/org/apache/iceberg/AllEntriesTable.java
- core/src/main/java/org/apache/iceberg/AllManifestsTable.java
- core/src/main/java/org/apache/iceberg/BaseAllMetadataTableScan.java
- core/src/main/java/org/apache/iceberg/BaseFilesTable.java
- core/src/main/java/org/apache/iceberg/BaseMetadataTableScan.java
- core/src/main/java/org/apache/iceberg/BaseTableScan.java
- core/src/main/java/org/apache/iceberg/DataFilesTable.java
- core/src/main/java/org/apache/iceberg/DataTableScan.java
- core/src/main/java/org/apache/iceberg/DeleteFilesTable.java
- core/src/main/java/org/apache/iceberg/FilesTable.java
- core/src/main/java/org/apache/iceberg/HistoryTable.java
- core/src/main/java/org/apache/iceberg/IncrementalDataTableScan.java
- core/src/main/java/org/apache/iceberg/ManifestEntriesTable.java
- core/src/main/java/org/apache/iceberg/ManifestsTable.java
- core/src/main/java/org/apache/iceberg/PartitionsTable.java
- core/src/main/java/org/apache/iceberg/SnapshotsTable.java
- core/src/main/java/org/apache/iceberg/StaticDataTask.java
- core/src/main/java/org/apache/iceberg/StaticTableScan.java
This PR refactors metadata tables and scans. The project has evolved since the initial implementation was done and I think that metadata tables and scans can be cleaned up a little bit.
> Core: Refactor metadata tables and scans

- api/src/main/java/org/apache/iceberg/actions/DeleteOrphanFiles.java
- spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRemoveOrphanFilesProcedure.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/actions/BaseDeleteOrphanFilesSparkAction.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/actions/BaseSparkAction.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/procedures/RemoveOrphanFilesProcedure.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/actions/TestRemoveOrphanFilesAction.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/source/FilePathLastModifiedRecord.java
This allows the user to specify an existing table of actual files for the `DeleteOrphanFiles` action, skipping the directory listing.
This can be used in cases where a cloud storage provider-specific implementation might be more efficient than a recursive FileSystem listing (e.g. leveraging [S3 Inventory list](https://docs.aws.amazon.com/AmazonS3/latest/userguide/storage-inventory.html) for S3 to create a temp table).
> Spark 3.2: Add `compareWithFileList` param to DeleteOrphanFiles action

- .baseline/checkstyle/checkstyle.xml
Hi, this closes #4613.
running the checks on this simple example, :
```
public static void main(String[] args)  {
String str = null;
// not allowed
Objects.nonNull(str);
Objects.nonNull(Integer.valueOf(123));
Objects.requireNonNull(str);
Objects.requireNonNullElse(str, "123");
Objects.requireNonNullElseGet(str, () -> "1");
// allowed
Objects.isNull(str);
}
```
generates: `<error line="..." severity="error" message="Prefer using Preconditions.checkNotNull(Object, String)." source=...` for the 'not allowed' lines above.
> Style: Add checkstyle rule to prevent using Objects.requireNonNull

- python/src/iceberg/expressions/base.py
- python/tests/expressions/test_expressions_base.py
This adds a `BoundReference` class that takes a field and an accessor and allows you to evaluate a struct (a row object that abides by the `StructProtocol`) to retrieve the value at the referenced field's position.
For some more context, expressions are initially built with references (`x` in x = 1`) that are not bound to an actual field. The binding of the reference to the actual field `x` will return a `BoundReference` instance. The instance includes an `eval` method that uses the accessor to get the field at that position, given a row object.
> Add BoundReference class

- core/src/main/java/org/apache/iceberg/PartitionsTable.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/source/TestMetadataTablesWithPartitionEvolution.java
https://github.com/apache/iceberg/pull/4516 fixes the schema of the partitions table in the case of changed partition specs to use Partitioning.partitionType (a union of all previous partition specs), but the data is still wrong in some cases:
* The PartitionsMap is constructed with the table's current spec, which is used to generate hashcode of partition values.  This leads to colliding of some values which get lost. 
* Ref:  https://github.com/apache/iceberg/blob/apache-iceberg-0.13.1/core/src/main/java/org/apache/iceberg/PartitionsTable.java#L99.  
* Example:  p1=foo, p2=bar collides with p1=foo if PartitionMap is instantiated with current spec of {p1}, and other instance is lost.
* The partition values are just listed in order without any transformation, meaning they may in the wrong …
> Core: Fix Partitions table for evolved partition specs

- core/src/test/java/org/apache/iceberg/rest/RequestResponseTestBase.java
- core/src/test/java/org/apache/iceberg/rest/requests/TestCreateNamespaceRequest.java
- core/src/test/java/org/apache/iceberg/rest/responses/TestCreateNamespaceResponse.java
- core/src/test/java/org/apache/iceberg/rest/responses/TestGetNamespaceResponse.java
- core/src/test/java/org/apache/iceberg/rest/responses/TestListNamespacesResponse.java
- core/src/test/java/org/apache/iceberg/rest/responses/TestListTablesResponse.java
- core/src/test/java/org/apache/iceberg/rest/responses/TestRESTCatalogConfigResponse.java
There is now a global singleton object mapper for the `RESCatalog`, which already has the necessary serializers and deserializers registered.
The rest / response objects are all tested via the `RequestResponseTestBase` class, which currently repeats the object mapper instantiation and initialization logic that the `RESTObjectMapper` is ultimately responsible for.
We should be testing the rest objects using the correct object mapper (which should also reduce allocations during testing and other minor advantages).
cc @rdblue @danielcweeks
> Core - Use singleton RESTObjectMapper in REST RequestResponseTestBase class

- core/src/main/java/org/apache/iceberg/rest/responses/LoadTableResponse.java
The `LoadTableResponse` class has a `TableMetadata` field called `metadata`.
It's currently called `meta`. Using Jackson to infer the fields will result in incorrect results because the name is not correct / does not match the spec.
I am updating this as a hot fix, and am working on a comprehensive test suite for this class that I'll open after a few other earlier PRs come in. But this will make the REST objects match the spec now, so that anybody implementing it can work with the correct objects.
cc @rdblue @danielcweeks
> Core - Fix field name bug in LoadTableResponse object to match REST spec and properly deserialize

- core/src/main/java/org/apache/iceberg/TableMetadataParser.java
- core/src/main/java/org/apache/iceberg/rest/RESTSerializers.java
The REST catalog sends and receives `TableMetadata` objects as JSON.
There is an existing parser for `TableMetadata` that can convert metadata into JSON and also can parse JSON into `TableMetadata`.
Adds Jackson serializers to the `RESTSerializers` so that accessing tables via the REST catalog works.
There are existing tests for `TableMetadataParser`, and I intend to add further tests in a follow up PR around `LoadTableResponse`. This PR is intended so allow people to continue implementing REST catalogs and be able to work with TableMetadata, but more extensive coverage will come in a follow up.
> Core - Add serde for TableMetadata for REST catalog

- core/src/main/java/org/apache/iceberg/MetadataUpdateParser.java
- core/src/test/java/org/apache/iceberg/TestMetadataUpdateParser.java
This covers a few more parsers for MetadataUpdate:
-  AddSchema
- SetCurrentSchema
- SetDefaultPartitionSpec
Given that this one parser covers several classes, I am breaking this up into multiple PRs to make it easier to review.
> Core - Implement MetadataUpdateParser for AddSchema, SetCurrentSchema, and SetDefaultPartitionSpec

- python/README.md
It's expected that developers won't conveniently have python 3.7, 3.8 and 3.9 installed for tox to use for tests so I've added a recommendation to use pyenv to the python README. This is what I do locally and it works nicely. The content here is definitely more for the CONTRIBUTING.md file but I think it's ok here in the readme during the refactoring.
If anyone else feels there's a better local setup to recommend, let me know!
> Solution for InterpreterNotFound errors from tox

- core/src/main/java/org/apache/iceberg/hadoop/HiddenPathFilter.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/actions/BaseDeleteOrphanFilesSparkAction.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/actions/TestRemoveOrphanFilesAction.java
This is a rebase of #4307 and is by @ulmako. I'm just submitting this PR to test the rebase.
> Spark 3.2: Fix orphan file path filter when partitions use underscores

- core/src/test/java/org/apache/iceberg/rest/responses/TestConfigResponse.java
The class previously called `RESTCatalogConfigResponse` was renamed to `ConfigResponse` in https://github.com/apache/iceberg/pull/4554
However, the corresponding test class was not renamed.
> Core - Rename test class for ConfigResponse to match updated name.

- .asf.yaml
Noticed that @szehon-ho is listed in the ASF collaborators file.
Given that Szehon has become a committer, I don't believe it's necessary to have this entry in the asf.yaml file.
cc @RussellSpitzer @szehon-ho @aokolnychyi @rdblue
> Infra - Remove Szehon from collaborators list in asf.yaml as they are now a committer

- flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/FlinkTestBase.java
- flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/TestFlinkTableSource.java
When upgrading our Flink code for the upcoming Flink 1.15 release in https://github.com/apache/iceberg/pull/4553, it was discovered that there is a failing test: https://github.com/apache/iceberg/pull/4553#issuecomment-1107688576
Looking closer, the expected and actual results are the same, just in a different order.
Because we are not testing the ordering of records returned from the source here, using list comparison doesn't make sense and we can just use set comparison (with an initial size check) for any query that returns more than 1 record.
I have updated all queries in this test to use set comparison semantics as list comparison is inherently flakey.
I will port this over to Flink 1.15 in https://github.com/apache/iceberg/pull/4553 as that's where tests are failing (though we don't …
> Flink - Fix flakey, order-dependent FlinkTableSource tests for Flink 1.14

- spark/v3.0/spark/src/main/java/org/apache/iceberg/spark/source/SparkTable.java
- spark/v3.0/spark/src/test/java/org/apache/iceberg/spark/sql/TestDeleteFrom.java
- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/source/SparkTable.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/SparkTable.java
`SparkTables metadata only delete` should throw `ValidationException` instead of `IllegalArgumentException` based on @[szehon-ho](https://github.com/szehon-ho) comment.
> Only delete will throw ValidationException instead of IllegalArgumentException

- python/tox.ini
Since we recently removed `setup.py` and only include a `pyproject.toml` and `setup.cfg` file, pip versions less than 21.1 no longer work due to hitting this error:
```
ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: /Users/sam/iceberg/python
(A "pyproject.toml" file was found, but editable mode currently requires a setup.py based build.)
WARNING: You are using pip version 21.0; however, version 22.0.4 is available.
You should consider upgrading via the '/Users/sam/iceberg/python/.tox/py37/bin/python -m pip install --upgrade pip' command.
```
Some bugfixes for installing in editable mode were introduced in [pip 21.1](https://pip.pypa.io/en/stable/news/#v21-1) and depending on how you setup your virtual environment, you can end up with an older version. …
> Specify pip>=21.1 in tox dependencies

- core/src/main/java/org/apache/iceberg/SnapshotSummary.java
- core/src/test/java/org/apache/iceberg/TestSnapshotSummary.java
This adds more info for deletes in the snapshot summary.
In the case of V2 tables, users may have offline service to compact deletes.  For example, in our production, we analyze the snapshot summary from the commit event to determine whether to start major compaction or minor compaction. The detailed summary info about deletes can help us calculate better compaction timing and resource.
> Core: add the file count of specific deletes in the snapshot summary

- core/src/main/java/org/apache/iceberg/SnapshotProducer.java
> Core: Fix table corruption from OOM during commit cleanup in Spark

- core/src/main/java/org/apache/iceberg/actions/ConvertEqualityDeleteStrategy.java
After reading the [design doc](https://docs.google.com/document/d/1-EyKSfwd_W9iI5jrzAvomVw3w1mb_kayVNT7f2I-SUg) I think the `ConvertEqualityDeleteStrategy::options` should return `ConvertEqualityDeleteStrategy` instead of the `RewritePositionDeleteStrategy` type. I guess this was an omission unless I miss something.
> Core: Fix ConvertEqualityDeleteStrategy::options return type

- python/src/iceberg/schema.py
This adds a skeleton visitor for the `BuildPositionAccessors` visitor and the following `# TODO` in the struct component of the visitor:
```
```
The main reason for adding this now is to unblock the work on expressions visitors (for example PR #4679)
cc: @rdblue @emkornfield @dramaticlly @CircArgs @jun-he @dhruv-pratap
> Add a skeleton for the BuildPositionAccessors visitor

- flink/v1.13/flink/src/test/java/org/apache/iceberg/flink/FlinkTestBase.java
- flink/v1.13/flink/src/test/java/org/apache/iceberg/flink/TestFlinkTableSource.java
Backports https://github.com/apache/iceberg/pull/4635 to Flink 1.13 to make it easier to continue to backport any changes to this test suite in the future.
These tests weree failing in 1.15 due to their order dependent nature and it's just an implementation detail that they happened to work before this. We're not testing order on read here, so it doesn't matter.
cc @rdblue @yittg
> Flink 1.13: Backport fix for order dependent flink table source tests

- core/src/main/java/org/apache/iceberg/MetadataUpdateParser.java
- core/src/test/java/org/apache/iceberg/TestMetadataUpdateParser.java
Adds toJson / fromJson implementations for two more implementations of `MetadataUpdate`:
1. `AddPartitionSpec`
2. `AddSortOrder`
Following up on PR feedback from https://github.com/apache/iceberg/pull/4632, this PR also renames the `writeAs***` and `readAs***` by dorpping the `As` so that the functions read better. Also, the action constants have been made package-private so they can be shared with the tests.
I've also placed `AddPartitionSpec` into the switch statement based on its declaration order in the `MetadataUpdate` file. As it was skipped in the last PR, I moved it down so it's now moved back up.
> Core - Add MetadataUpdateParser implementation for AddPartitionSpec and AddSortOrder

- core/src/main/java/org/apache/iceberg/io/MultiBufferInputStream.java
This method returns both mutable and immutable collections or maps from different paths, I think it should `return ImmutableList.of();`
> Static Analysis: Mixed Mutability Return Type

- python/src/iceberg/expressions/base.py
This adds an `UnboundReference` class that has a `bind` method which returns a `BoundReference` class. Merging this relies on PR #4678 which adds the `Schema.accessor_for_field` method. For complete functionality, a subsequent PR needs to be opened that implements the `struct` method in the `BuildPositionAccessors` visitor (added in the other PR) that builds a map of field ID to schema position accessor (the same PR should probably include tests for `UnboundReference` and `BuildPositionAccessors`.
To summarize:
cc: @rdblue @emkornfield @dramaticlly @CircArgs @jun-he @dhruv-pratap
> Add UnboundReference class

- core/src/main/java/org/apache/iceberg/PartitionsTable.java
- core/src/test/java/org/apache/iceberg/TestMetadataTableScans.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/source/TestMetadataTablesWithPartitionEvolution.java
The Partitions metadata table filter pushdown logic is always using the current table's partition spec and not the original spec of the manifest file.  This would lead to errors if the table has data written to via different partition specs and a filter is applied to partitions table, like
```
Cannot find field 'data' in struct: struct<>
org.apache.iceberg.exceptions.ValidationException: Cannot find field 'data' in struct: struct<>
at app//org.apache.iceberg.exceptions.ValidationException.check(ValidationException.java:50)
at app//org.apache.iceberg.expressions.NamedReference.bind(NamedReference.java:46)
at app//org.apache.iceberg.expressions.NamedReference.bind(NamedReference.java:27)
at app//org.apache.iceberg.expressions.UnboundPredicate.bind(UnboundPredicate.java:106)
at …
```
> Core: Fix Partitions table filtering for evolved partition specs

- core/src/main/java/org/apache/iceberg/util/JsonUtil.java
Using `JsonUtils::getLongOrNull` in https://github.com/apache/iceberg/pull/4693, it seems that the functions `getIntOrNull` and `getLongOrNull` do not properly handle an explicit null.
As you can see in the `Preconditions` check, after getting the property, if the JsonNode of the nullable Integer or Long is explicitly `null`, the Precondition check will fail.
cc @rdblue @RussellSpitzer
> Core: Fix invalid null handling in JsonUtils::getIntOrNull ::getLongOrNull

- core/src/main/java/org/apache/iceberg/AllDeleteFilesTable.java
- core/src/main/java/org/apache/iceberg/AllFilesTable.java
- core/src/main/java/org/apache/iceberg/MetadataTableType.java
- core/src/main/java/org/apache/iceberg/MetadataTableUtils.java
- core/src/test/java/org/apache/iceberg/TestMetadataTableFilters.java
- spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMetadataTables.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/data/TestHelpers.java
This will be the final set of changes for https://github.com/apache/iceberg/issues/4139, adding the new metadata tables 'all_delete_files' and 'all_files' to include delete files.
This adds both in one change list as it's easier to write a unified test, although they can be split up if we prefer that.
> Core: Add all_delete_files and all_files tables

- flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/TestFlinkTableSource.java
Some tests in Flink's `TestFlinkTableSource` have been found to be order dependent.
As the order of results on read is not defined (without an order by clause), most of the tests were fixed in https://github.com/apache/iceberg/commit/c726b2222f491aac02f0f1910898b4a8dfda2b14
However, there is one test that has a `LIMIT 1` that then asserts on the row, which could be any of 3 possible rows.
As Flink happened to be returning the records in a stable manner prior to Flink 1.15, this test was passing. But in PR https://github.com/apache/iceberg/pull/4693, this test was discovered to occasionally fail, as `SELECT * .... LIMIT 1` on a table with 3 results has no guarantee of which record will be returned.
Failed execution output:
```
org.apache.iceberg.flink.TestFlinkTableSource > …
```
> Flink 1.15 - Fix flaky test that has implicit order dependency in TestFlinkTableSource

- api/src/main/java/org/apache/iceberg/PendingUpdate.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/SparkWrite.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/source/ManualSource.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkDataWrite.java
The issue here was pointed out by @stevenzwu when we were discussing the issue with incorrect aborts when non-runtime exceptions were thrown. He correctly noticed that the same sort of issue would appear if we threw a commit unknown exception and the Spark Writer aborted and deleted underlying data files.
Closes #4686
> Spark commit unknown handling

- core/src/main/java/org/apache/iceberg/PartitionsTable.java
- core/src/test/java/org/apache/iceberg/TestMetadataTableScans.java
- spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMetadataTables.java
Closes https://github.com/apache/iceberg/issues/4718
As per my understanding, we should use scan.tableSchema() rather than scan.schema() for transformSpec when planFiles() for partitions metaData table. 
Hence we faced :
> 22/05/06 16:12:25 ERROR SparkSQLDriver: Failed in [select file_count from spark_catalog.monitoring.test.partitions]
java.lang.IllegalArgumentException: Cannot find source column: partition.date
as present in reported ticket
Though in master we will get : 
>Cannot find source column: 1000
java.lang.NullPointerException: Cannot find source column: 1000
---
Testing Done : 
Added UT fails without the change
cc @szehon-ho @RussellSpitzer
> Core: Fix query failure when using projection on top of partitions metadata table

- core/src/main/java/org/apache/iceberg/rest/RESTSerializers.java
- core/src/main/java/org/apache/iceberg/rest/requests/UpdateRequirementParser.java
- core/src/main/java/org/apache/iceberg/rest/requests/UpdateTableRequest.java
- core/src/test/java/org/apache/iceberg/rest/requests/TestUpdateRequirementParser.java
- open-api/rest-catalog-open-api.yaml
We need a parser for `UpdateTableRequest.UpdateRequirement` class.
- Adds `UpdateRequirementParser`
- Adds json serializer / deserializer to the RESTSerializers class
- Adds tests for all of the individual implementations of `UpdateRequirement`, similar to `MetadataUpdate` tests.
Open questions:
- Some of the field names don't necessarily line up with the spec.
- I've noted them on the PR. I was initially going to change them, but they are intertwined with some other classes (namely `MetadataUpdate`) and would also possibly cause shadowing issues in some cases.
- The biggest source of confusion is `sortOrderId` vs `default-write-order-id`, though looking at the spec, the corresponding `MetadataUpdate` field is just called `order-id` so maybe it's not a concern.
EDIT:
For the naming, we've …
> Core - Add Parser for UpdateRequirement

- core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java
- core/src/main/java/org/apache/iceberg/rest/CatalogHandlers.java
- core/src/main/java/org/apache/iceberg/rest/RESTCatalog.java
- core/src/main/java/org/apache/iceberg/rest/requests/RenameTableRequest.java
- core/src/test/java/org/apache/iceberg/catalog/CatalogTests.java
- core/src/test/java/org/apache/iceberg/jdbc/TestJdbcCatalog.java
- core/src/test/java/org/apache/iceberg/rest/RESTCatalogAdapter.java
- core/src/test/java/org/apache/iceberg/rest/requests/TestRenameTableRequest.java
Adds `RenameTableRequest` as a request for the `RESTCatalog` and adds the call for `renameTable` to the `RESTCatalog`.
> Core: Add in RenameTableRequest for the RESTCatalog

- python/tox.ini
I have only Python 3.9 installed locally. And for fast turnaround
I'm not super interested to test everything against each version
locally. Therefore I would suggest to skip the missing interpreters.
Otherwise I have all the red lines with the errors that python 3.7 and 3.8
failed in the terminal all the time, which makes me uncomfortable.
Before:
```
______________________________________________________________________________________________ summary
_______________________________________________________________________________________________
ERROR:  py37: InterpreterNotFound: python3.7
ERROR:  py38: InterpreterNotFound: python3.8
py39: commands succeeded
linters: commands succeeded
```
After:
```
_________________________________________________________________________________________ …
```
> Python: Skip missing tox interpreters

- python/src/iceberg/transforms.py
- python/tox.ini
Mypy complaints about the config file:
```
No [mypy] section in config file
```
Also enabled some additional checks on unreachable code
> Python: Remove mypy error

- flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/data/FlinkParquetReaders.java
Migrate back to use ReusableArrayData for Flink 1.15
part of #4624
This change is already covered by the existing test: `TestFlinkScan#testCustomizedFlinkDataTypes`, for detail:
https://github.com/apache/iceberg/blob/f79da868f48c3364762eae25ee13f31d6f620eb7/flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/source/TestFlinkScan.java#L310-L321
> Flink 1.15: Migrate back to use ReusableArrayData

- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/actions/TestRemoveOrphanFilesAction.java
Follow up to PR #4307 refactoring the TestRemoceOrphanFilesAction class and replace `thread.sleep()` with calls to `waitUntilAfter()` method.
> Spark 3.2: Refactor TestRemoveOrphanFilesAction - remove Thread.sleep()

- spark/v3.0/spark/src/main/java/org/apache/iceberg/spark/procedures/RewriteManifestsProcedure.java
- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/procedures/RewriteManifestsProcedure.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/procedures/RewriteManifestsProcedure.java
use-caching in RewriteManifestsProcedure is always hardcoded to true and default value is also true. So, unable to disable.
> Spark: Fix unable to disable use-caching in RewriteManifestsProcedure

- api/src/main/java/org/apache/iceberg/expressions/ExpressionUtil.java
- api/src/main/java/org/apache/iceberg/expressions/Expressions.java
- api/src/test/java/org/apache/iceberg/expressions/TestExpressionUtil.java
- core/src/main/java/org/apache/iceberg/BaseAllMetadataTableScan.java
- core/src/main/java/org/apache/iceberg/BaseTableScan.java
This adds an expression sanitizer and sanitizes filters logged by table scans. This is to avoid leaking IDs and other sensitive information in logs.
Literals are sanitized using the following rules:
* Integers and longs are converted to `(N-digit-int)`, where `N` is the number of digits in the number
* Floats and doubles are converted to `(N-digit-float)`, where N is the number of digits before the decimal point
* Dates, times, and timestamps are converted to `(date)`, `(time)`, or `(timestamp)`
* All other types are hashed to produce `(hash-%08h)` from the string representation
The result for string literals matches the result after the literals are bound and converted.
> API: Add expression sanitizer, sanitize scan log messages

- open-api/rest-catalog-open-api.yaml
Small typo slipped into the REST OpenAPI spec, so it doesn't parse.
Just fixing `integer`.
I haven't added an openapi spec validator to our github actions because there doesn't seem to be a canonical one, and of the 6+ I've tried I get differing results amongst them.
But that will be prioritized given this as there are some that run fine.
After this change, we can use `openapi-spec-validator` as a starting point though I've found it misses some issues.
But I admittedly have gotten an `OK` response from `openapi-spec-validator` that gave errors elsewhere in other validators.  
The website editor.swagger.io seems to be the most correct in my experience.
> [SPEC] Fix typ in REST Catalog OpenAPI Spec

- flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/FlinkDynamicTableFactory.java
Get the `CatalogTable` directly instead of reflecting
It was originally part of #4246, but I take it out separately this time, because it has no correlation with #4246 and is easier to solve.
cc @kbendick
> Flink: Get the CatalogTable directly instead of reflecting

- core/src/main/java/org/apache/iceberg/BaseMetastoreTableOperations.java
- core/src/main/java/org/apache/iceberg/TableOperations.java
- core/src/main/java/org/apache/iceberg/hadoop/HadoopTableOperations.java
This is to address 2 issues:
- Just construct `Set` of  `removedPreviousMetadataFiles` After  `write.metadata.delete-after-commit.enabled = true`
- Delete the function of `deleteRemovedMetadataFiles `  in `BaseMetastoreTableOperations` and `HadoopTableOperations`,  and then implement it in interface of `TableOperations`
> Core: Optimize to delete the oldest metadata file after commit

- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/Spark3Util.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/SparkTableUtil.java
This logic removes the unnecessary reflection to load metadata tables in `SparkTableUtil` since we have separate modules for Spark versions.
> Spark 3.2: Avoid reflection to load metadata tables in SparkTableUtil

- python/src/iceberg/transforms.py
- python/tests/test_transforms.py
To split the PR https://github.com/apache/iceberg/pull/3450, open a new PR for void transform here.
> add VoidTransform

- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/SparkTableUtil.java
This PR cleans up and removes no longer used static vars in `SparkTableUtil`.
> Spark 3.2: Clean static vars in SparkTableUtil

- core/src/main/java/org/apache/iceberg/SnapshotSummary.java
This PR renames recently added and unreleased snapshot summary properties for equality and position delete files to match other recent public constants/methods.
Specifically, all other snapshot properties use full words for `equality` and `position`.
```
// SnapshotSummary
public static final String ADDED_POS_DELETES_PROP = "added-position-deletes";
public static final String REMOVED_POS_DELETES_PROP = "removed-position-deletes";
public static final String TOTAL_POS_DELETES_PROP = "total-position-deletes";
public static final String ADDED_EQ_DELETES_PROP = "added-equality-deletes";
// ConvertEqualityDeleteFiles
int convertedEqualityDeleteFilesCount();
int addedPositionDeleteFilesCount();
// FileWriterFactory
EqualityDeleteWriter<T> newEqualityDeleteWriter(...);
PositionDeleteWriter<T> …
```
> Core: Align snapshot summary property names for delete files

- .palantir/revapi.yml
Adds a blanket acceptance for all existing breaks that occurred prior to the introduction of the API / ABI compatibility guarantee checking tool, `revapi`, in https://github.com/apache/iceberg/pull/4638
cc @rdblue
> Core: Accept all API warnings in master

- docs/flink/flink-getting-started.md
We added support for Flink 1.15 and removed 1.12, the purpose of this PR is to update the docs..
The specific version number is no longer described, but refers the user to multi-engine-support page, meanwhile, I also raised https://github.com/apache/iceberg-docs/pull/79  to update it.
cc @kbendick
> Docs: Updated version description for Flink

- core/src/main/java/org/apache/iceberg/AllManifestsTable.java
- core/src/main/java/org/apache/iceberg/ManifestsTable.java
- spark/v2.4/spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSourceTablesBase.java
- spark/v3.0/spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSourceTablesBase.java
- spark/v3.1/spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSourceTablesBase.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSourceTablesBase.java
This PR adds content and delete file counts fields to `manifests` and `all_manifests` metadata tables.
Existing tests were adapted to cover the new functionality.
> Core: Add content and delete file counts to manifest tables

- api/src/main/java/org/apache/iceberg/catalog/SessionCatalog.java
- core/src/main/java/org/apache/iceberg/catalog/BaseSessionCatalog.java
This adds a `SessionCatalog` interface for engines that share catalog instances across sessions.
`SessionCatalog` is like `Catalog`, but passes a `SessionContext` object in each call. This session context can be used to carry identity and credentials, which are passed through to the catalog service. `SessionCatalog` does not extend `Catalog` to avoid bugs where context is accidentally not passed.
Because `SessionCatalog` does not implement `Catalog`, a base implementation class is also included in this PR that adapts `SessionCatalog` to `Catalog` using `withContext` and `asCatalog` methods. For example:
```java
boolean exists = sessionCatalog.withContext(sessionContext, (Catalog catalog) -> {
return catalog.tableExists(tableIdent);
});
```
This was originally part of #4575, but is not a …
> API: Add SessionCatalog interface and base class

- docs/tables/configuration.md
Update the doc for compression codec enum supported by Avro 
Based on：
https://github.com/apache/iceberg/blob/932ede696cbb07c266a15505a5d49083f624608e/core/src/main/java/org/apache/iceberg/avro/Avro.java#L74-L82
the codec should be：
- gzip(deflate with 9 level)
- zstd
- snappy
- uncompressed
> Docs: Update compression codec enum supported by Avro in configuration.md

- core/src/main/java/org/apache/iceberg/MergingSnapshotProducer.java
- core/src/test/java/org/apache/iceberg/TestV1ToV2RowDeltaDelete.java
This backports #4514 to the 0.13.x branch
> [0.13] Core: Fix delete file handling in upgraded tables with rewritten manifests (#4514)

- python/pylintrc
- python/src/iceberg/conversions.py
- python/src/iceberg/expressions/base.py
- python/src/iceberg/expressions/literals.py
- python/src/iceberg/io/pyarrow.py
- python/src/iceberg/schema.py
- python/src/iceberg/transforms.py
- python/src/iceberg/types.py
- python/tests/expressions/test_expressions_base.py
- python/tests/expressions/test_literals.py
- python/tests/test_conversions.py
- python/tests/test_schema.py
- python/tests/test_transforms.py
- python/tests/test_types.py
- python/tox.ini
Couple of things and checks:
- Moved the configuration from `tox.ini` to `pylintrc`.
- Checks for Pylint warnings
- Detects unused variables, so we can spend our brain cycles on more important stuff during reviews :)
- Checks reraising of exceptions, so you can also see the underlying exception.
- If you override a function, the argument names should stay the same
- Checks on using build-in keywords (input, type, etc)
> Python: Test for warning of PyLint

- format/spec.md
The generated field spec_id is added to data_file metadata table in https://github.com/apache/iceberg/pull/3015
As per https://github.com/apache/iceberg/pull/3015#discussion_r735838832 , this is a late follow up to mark the field id as reserved.
> Format: Add reserved field id to data_file

- python/setup.cfg
- python/spellcheck-dictionary.txt
- python/src/iceberg/schema.py
- python/src/iceberg/types.py
- python/tests/test_schema.py
- python/tests/test_types.py
Proposal to change the types into dataclasses.
This has several improvments:
- We can use the dataclasss field(repr=True) to include the fields in the representation, instead of building our own strings
- We can assign the types in the post_init when they are dynamic (List, Maps, Structs etc) , or just override them when they are static (Primitives)
- We don't have to implement any eq methods because they come for free
- The types are frozen, which is kind of nice since we re-use them
- The code is much more consise
- We can assign the min/max of the int/long/float as Final as of 3.8: https://peps.python.org/pep-0591/
My inspiration was the comment by Kyle:
https://github.com/apache/iceberg/pull/4742#discussion_r869494393
This would entail implementing eq, but why not use the generated …
> Change types into dataclasses

- core/src/main/java/org/apache/iceberg/rest/HTTPClient.java
- core/src/main/java/org/apache/iceberg/rest/RESTCatalog.java
- core/src/main/java/org/apache/iceberg/rest/RESTClient.java
- core/src/main/java/org/apache/iceberg/rest/RESTTableOperations.java
- core/src/main/java/org/apache/iceberg/rest/ResourcePaths.java
- core/src/test/java/org/apache/iceberg/rest/RESTCatalogAdapter.java
- core/src/test/java/org/apache/iceberg/rest/TestHTTPClient.java
- core/src/test/java/org/apache/iceberg/rest/TestRESTCatalog.java
This adds a parameter to `RESTClient` to pass headers when making a request. This was originally part of #4575, but we can get it in more easily on its own.
> Core: Add request headers to REST client

- python/src/iceberg/types.py
Tox tests for python 3.8 are failing, as the `StructType` is now a `dataclass`, but its parent class is not a dataclass and it has `init=False`.
To get around this, I've called `super().__init__()` in the post init method, as suggested here: https://stackoverflow.com/questions/66827839/super-classs-init-is-not-called-using-dataclass
It's also possible we want to just set an ignore on this.
cc @Fokko @samredai
> Python - Fix tox errors for not calling super __init__ on a dataclass

- aws/src/main/java/org/apache/iceberg/aws/glue/GlueCatalog.java
- core/src/main/java/org/apache/iceberg/BaseMetastoreCatalog.java
- core/src/main/java/org/apache/iceberg/hadoop/HadoopCatalog.java
- hive-metastore/src/main/java/org/apache/iceberg/hive/HiveCatalog.java
This PR addresses the nits of https://github.com/apache/iceberg/pull/4011:
- Use ImmutableMap for catalog properties.
- Correct indentation.
- Add loggers for table default and table override catalog properties.
---
cc: @rdblue @kbendick @SinghAsDev
> Catalog: Use ImmutableMap for catalog properties

- python_legacy/iceberg/core/data_table_scan.py
Based on analysis, `plan_files()` spent most of the time on doing copy and file reading which are both CPU bounded operations. However, current implementation is using thread pool instead of process pool which does not speed up the operation at all.
This diff proposes switch to process pool instead of thread pool.
Frame graph
Command
`py-spy record -o profile.svg -- python myprogram.py`
Code
```
from iceberg.hive import HiveTables
conf = {"hive.metastore.uris": 'xxxx', 'iceberg.scan.plan-in-worker-pool': True, 'iceberg.worker.num-threads': 4}
tables = HiveTables(conf)
table = tables.load('abc.xyz')
scan = table.new_scan()
files = scan.plan_files()
```
> [python legacy] use process pool instead of thread pool for files planning

- dev/stage-binaries.sh
Noticed we added support for Scala 2.13 with Spark 3.2 recently, but the release scripts have not been updated to reflect that. The nightly release workflow has been updated to publish Scala 2.13 artifacts: https://github.com/apache/iceberg/pull/4009
This came up as a result of this discussion: https://github.com/apache/iceberg/pull/4157#discussion_r809710633. There's probably more work to do, and I can covert this to an issue if somebody else wants to take over.
> Update release scripts to support publishing Spark 3.2 with Scala 2.13 support to Maven

- core/src/main/java/org/apache/iceberg/io/BaseTaskWriter.java
- data/src/test/java/org/apache/iceberg/io/TestTaskEqualityDeltaWriter.java
- flink/v1.12/flink/src/main/java/org/apache/iceberg/flink/sink/BaseDeltaTaskWriter.java
- flink/v1.12/flink/src/test/java/org/apache/iceberg/flink/sink/TestDeltaTaskWriter.java
- flink/v1.13/flink/src/main/java/org/apache/iceberg/flink/sink/BaseDeltaTaskWriter.java
- flink/v1.13/flink/src/main/java/org/apache/iceberg/flink/sink/RowDataTaskWriterFactory.java
- flink/v1.13/flink/src/test/java/org/apache/iceberg/flink/TestFlinkUpsert.java
- flink/v1.13/flink/src/test/java/org/apache/iceberg/flink/sink/TestDeltaTaskWriter.java
- flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/BaseDeltaTaskWriter.java
- flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/RowDataTaskWriterFactory.java
- flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/TestFlinkTableSink.java
- flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/TestFlinkUpsert.java
- flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/sink/TestDeltaTaskWriter.java
- flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/source/BoundedTableFactory.java
- flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/source/BoundedTestSource.java
This backports #4417 / #3834 (because #4364 depends on it) / #4364 / #4189 (because CI was failing without this test fix) to the 0.13.x branch
> [0.13] Flink upsert delete file metadata backports

- python/src/iceberg/types.py
If there is a doc, the rest gets ignored, which is kind of awkward.
Before:
```python
➜  python git:(master) ✗ python3
Python 3.9.12 (main, Mar 26 2022, 15:44:31)
[Clang 13.1.6 (clang-1316.0.21.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from iceberg.types import NestedField, LongType
>>> str(NestedField(
...     field_id=2,
...     name='bar',
...     field_type=LongType(),
...     is_optional=False
... ))
'2: bar: required long'
>>> str(NestedField(
...     field_id=2,
...     name='bar',
...     field_type=LongType(),
...     is_optional=False,
...     doc="Just a long"
... ))
' (Just a long)'
```
Now:
```python
➜  python git:(master) ✗ python3
Python 3.9.12 (main, Mar 26 2022, 15:44:31)
[Clang 13.1.6 (clang-1316.0.21.2)] on darwin
Type …
```
> Python: Fix the type_string of the NestedField

- aws/src/integration/java/org/apache/iceberg/aws/glue/TestGlueCatalogCommitFailure.java
- aws/src/main/java/org/apache/iceberg/aws/glue/GlueTableOperations.java
Handle certain glue exceptions as iceberg errors to be further processed as user errors instead of server internal errors
> AWS: handle certain glue exceptions as iceberg errors

- aws/src/main/java/org/apache/iceberg/aws/AwsClientFactories.java
- aws/src/main/java/org/apache/iceberg/aws/AwsProperties.java
AWS S3 path-style API requests are deprecated. However, there are many S3-compatible services like MinIO or Ceph are not able to use Virtual Hosted-Style because of legacy deployment or organization restriction.
Up until now, to config path-style access, we need to write custom `AwsClientFactory`. So it would be nice if Iceberg's `DefaultAwsClientFactory` support `s3.path-style-access` (`false` by default)
> AWS: support Path-Style Access

- data/src/main/java/org/apache/iceberg/data/IcebergGenerics.java
- data/src/test/java/org/apache/iceberg/data/TestLocalScan.java
- orc/src/main/java/org/apache/iceberg/orc/OrcValueReaders.java
This adds the project() method into IcebergGenerics so that it can forward the supplied Schema object into TableScan.
This change also fixes OrcValueReaders not being able to handle metadata columns in special cases.
cc: @pvary
> Add project method to IcebergGenerics to enable projections by Schema

- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/actions/BaseRewriteManifestsSparkAction.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteManifestsAction.java
This is an extension of https://github.com/apache/iceberg/pull/4687
Spark actions also manipulate the table obj, apart of SparkWrite and hence, the handling of CommitStateUnknown exception when encountered, should not delete the added files.
While actions such as RewriteDatafiles have this handling :
https://github.com/apache/iceberg/blob/566b2fe3f31f4a53f5a26aca1c4239085de4a994/core/src/main/java/org/apache/iceberg/actions/RewriteDataFilesCommitManager.java#L108-L120
found this missing in RewriteManifestSparkAction, hence added the same. 
----- 
Added a UT to demonstrate the E2E , without the change the UT fails with File Not found exception thus leading to table corruption 
---- 
cc @RussellSpitzer, @stevenzwu @flyrain @aokolnychyi
> Spark: Extend CommitStateUnknown exception handling in Spark Actions

- open-api/rest-catalog-open-api.yaml
This extends the OAuth2 tokens endpoint to explain its uses for REST catalogs.
> Spec: Add more context about OAuth2 to the REST spec

- core/src/main/java/org/apache/iceberg/rest/RESTSerializers.java
- core/src/main/java/org/apache/iceberg/rest/ResourcePaths.java
- core/src/main/java/org/apache/iceberg/rest/auth/OAuth2Properties.java
- core/src/main/java/org/apache/iceberg/rest/auth/OAuth2Util.java
- core/src/main/java/org/apache/iceberg/rest/responses/OAuthTokenResponse.java
- core/src/test/java/org/apache/iceberg/rest/RESTCatalogAdapter.java
- core/src/test/java/org/apache/iceberg/rest/RequestResponseTestBase.java
- core/src/test/java/org/apache/iceberg/rest/auth/TestOAuth2Util.java
- core/src/test/java/org/apache/iceberg/rest/responses/TestOAuthTokenResponse.java
This adds the OAuth2 classes needed by the REST catalog, from #4830.
This also fixes review feedback from that PR: add serialization tests, refactor into `rest.auth` module.
> Core: Add OAuth2 helpers for REST catalog

- core/src/main/java/org/apache/iceberg/MetadataUpdate.java
- core/src/main/java/org/apache/iceberg/MetadataUpdateParser.java
- core/src/main/java/org/apache/iceberg/SnapshotParser.java
- core/src/main/java/org/apache/iceberg/util/JsonUtil.java
- core/src/test/java/org/apache/iceberg/TestMetadataUpdateParser.java
- open-api/rest-catalog-open-api.yaml
Adds the remaining parsers for metadata update subclasses.
Opening this as a draft so I can compare and because some field renaming in a tangentially related PR: https://github.com/apache/iceberg/pull/4693
I'll probably move the field renaming over here if they don't get merged in over there before.
> [CORE] - Add remaining parsers for MetadataUpdate implementations

- core/src/main/java/org/apache/iceberg/rest/HTTPClient.java
- core/src/main/java/org/apache/iceberg/rest/HTTPClientFactory.java
- core/src/test/java/org/apache/iceberg/rest/TestHTTPClient.java
- core/src/test/java/org/apache/iceberg/rest/TestRESTCatalog.java
This removes the `Authorization` header code from `HTTPClient` because the REST catalog will handle its own headers independent of the client.
This is part #4830.
> Core: Remove Authorization header handling from HTTPClient

- api/src/main/java/org/apache/iceberg/catalog/SessionCatalog.java
> API: Update SessionCatalog context to use a credentials map

- core/src/main/java/org/apache/iceberg/rest/HTTPClientFactory.java
- core/src/main/java/org/apache/iceberg/rest/RESTClient.java
- core/src/main/java/org/apache/iceberg/rest/RESTSessionCatalog.java
- core/src/main/java/org/apache/iceberg/rest/RESTTableOperations.java
- core/src/test/java/org/apache/iceberg/rest/TestRESTCatalog.java
This is a minimal set of changes to refactor the `RESTCatalog` to a `RESTSessionCatalog`. The current `RESTCatalog` is removed to show changes between the session version and the original catalog implementation. A wrapper will be added in a follow-up commit.
> Core: Refactor REST catalog to RESTSessionCatalog

- core/src/main/java/org/apache/iceberg/TableMetadata.java
- nessie/src/main/java/org/apache/iceberg/nessie/NessieTableOperations.java
- nessie/src/test/java/org/apache/iceberg/nessie/TestBranchVisibility.java
This backports #4509 and the `metadataLocation` parts of #4320 to the 0.13.x branch
> [0.13] Nessie: Fix NPE while accessing refreshed table in nessie catalog (#4509)

- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/actions/BaseRewriteManifestsSparkAction.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteManifestsAction.java
This backports #4836 to the 0.13.x branch
> [0.13] Spark: Handle CommitStateUnknown exception in RewriteManifestSparkAction (#4836)

- core/src/main/java/org/apache/iceberg/BaseMetadataTable.java
- core/src/main/java/org/apache/iceberg/DataFilesTable.java
- core/src/main/java/org/apache/iceberg/PartitionsTable.java
- core/src/test/java/org/apache/iceberg/TestMetadataTableScans.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/source/TestMetadataTablesWithPartitionEvolution.java
Backport of #4520 to 0.13.x branch, which returns sometimes wrong results for Files metadata table queries with filters, for V2 tables with specific partition spec evolutions involving dropping fields, and IndexOutOfBoundException in other cases where partition spec has changed.
Adapted to old code in the branch.
This works, except some test case fails in querying dropped partition fields in V1 tables because of related but different issue #3411 .  So one option is to backport that one first for the test, though fix is orthogonal.
> [0.13] Core: Fix filter pushdown for metadata tables with evolved specs (#4520)

- docs/integrations/aws.md
Adds documentation for using s3 access-points : 
- Introduced in https://github.com/apache/iceberg/pull/4334
slack thread : https://apache-iceberg.slack.com/archives/C025PH0G1D4/p1645066803099319
----
cc @rdblue, @jackye1995, @rajarshisarkar, @anuragmantri
> Docs : add s3 access-point documentation

- spark/v2.4/spark/src/main/java/org/apache/iceberg/spark/actions/BaseRewriteManifestsSparkAction.java
- spark/v2.4/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteManifestsAction.java
- spark/v3.0/spark/src/main/java/org/apache/iceberg/spark/actions/BaseRewriteManifestsSparkAction.java
- spark/v3.0/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteManifestsAction.java
- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/actions/BaseRewriteManifestsSparkAction.java
- spark/v3.1/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteManifestsAction.java
This backports #4850 to the 0.13.x branch
> [0.13] Spark: Backport CommitStateUnknownException handling for RewriteManifestSparkAction (#4850)

- orc/src/main/java/org/apache/iceberg/data/orc/GenericOrcWriters.java
GenericOrcWriters TimestampWriters is intentionally using the getNano method, it can safely be suppressed to remove unnecessary warnings in build.
@jackye1995 @openinx  @singhpk234 @rajarshisarkar
> ORC: Suppress JavaLocalDateTimeGetNano warning in GenericOrcWriters

- aws/src/main/java/org/apache/iceberg/aws/dynamodb/DynamoDbLockManager.java
At present DDB get request uses eventually consistent reads by default unless specified to use strongly consistent read.
ref : https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HowItWorks.ReadConsistency.html
As per my understanding we should always read most up to date data with strong consistency as with eventually consistent read we can read stale data, when read in very short interval of write.
This PR attempts to make GET's of DDB strongly consistent, as by default GET's are eventually consistent.
---
Ran integration tests locally (passes)
```shell
./gradlew :iceberg-aws:integrationTest --tests "org.apache.iceberg.aws.dynamodb.TestDynamoDbLockManager"
```
----
cc @jackye1995 @rajarshisarkar @amogh-jahagirdar @arminnajafi  @xiaoxuandev @yyanyy
> AWS : Use strongly consistent read while acquiring lock via DDBLockManager

- core/src/main/java/org/apache/iceberg/CatalogUtil.java
- core/src/main/java/org/apache/iceberg/hadoop/HadoopTableOperations.java
- core/src/main/java/org/apache/iceberg/io/BaseTaskWriter.java
- mr/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergRecordWriter.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/SparkTableUtil.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/actions/BaseRewriteManifestsSparkAction.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/SparkPositionDeltaWrite.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/SparkWrite.java
This PR attempts to use MultiThreading where ever possible, Some scenarios where could be benefitial : 
1. droptTable currently deletes (mainfest-files, mainfest-list, previous meta-data) in single thread, As per my understanding using MultiThreading can be beneficial here.
2. Spark Writer aborts can also be sped up using MT, thus making it faster.
once FileIO's such as S3FileIO which supports bulkDeletes are integrated to these flows, these ops could be even more optimized :) !!!
cc @rdblue @ConeyLiu
> Core, Spark: Use MultiThreading in abort and clean-up

- spark/v3.2/spark-extensions/src/main/scala/org/apache/iceberg/spark/extensions/IcebergSparkSessionExtensions.scala
- spark/v3.2/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/analysis/AlignRowLevelCommandAssignments.scala
- spark/v3.2/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/analysis/AlignedRowLevelIcebergCommandCheck.scala
- spark/v3.2/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/expressions/AssignmentUtils.scala
- spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMerge.java
Prior to this a mixed-case insert statement would fail to be marked
as aligned after our alignement rule was applied. This would occur
because Spark is allowed to opperate without case sensitivity. Although
we would correctly align the fields, our check for alignment required
an exact match even with the system was set to be case-insensitive. Failing this
check would mean our RewriteToMerge analysis rule would never get applied.
> Spark: Fix Alignment of Merge Commands with Mixed Case

- spark/v3.2/spark-extensions/src/main/scala/org/apache/iceberg/spark/extensions/IcebergSparkSessionExtensions.scala
- spark/v3.2/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/analysis/AlignedRowLevelIcebergCommandCheck.scala
- spark/v3.2/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/expressions/AssignmentUtils.scala
- spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMerge.java
* Spark: Fix Alignment of Merge Commands with Mixed Case
Prior to this a mixed-case insert statement would fail to be marked
as aligned after our alignment rule was applied. This would then fail the
entire MERGE INTO command. The commands were correctly aligned but
our alignment check was always case sensitive.
> Spark: Fix Alignment of Merge Commands with Mixed Case (#4848)

- docs/spark/spark-ddl.md
This PR is close #4615
the syntax of spark sql
```
ALTER TABLE prod.db.sample SET TBLPROPERTIES (
'comment' = 'A table comment.'
)
```
> Docs: To set table comment using `SET TBLPROPERTIES`

- api/src/main/java/org/apache/iceberg/SortOrder.java
- core/src/main/java/org/apache/iceberg/rest/requests/CreateTableRequest.java
As I've been working on some serialization related tests for the REST catalog, it came to my attention that we should be storing the create table requests sort order and partition spec as `UnboundSortOrder` and `UnboundPartitionSpec`, respectively.
Generally speaking, we are moving towards using `Unbound` variants of all things whenever possible, and letting the binding to actual fields take place later in the process.
I am working on some PRs that add additional serialization tests in, but I wanted to get these changes in sooner so that anybody who might be implementing or testing agains the RESTCatalog would have these changes available to them.
> Core - Use unbound variants of SortOrder / PartitionSpec for REST Catalog's CreateTableRequest

- core/src/main/java/org/apache/iceberg/MetadataUpdate.java
- core/src/main/java/org/apache/iceberg/MetadataUpdateParser.java
- core/src/test/java/org/apache/iceberg/TestMetadataUpdateParser.java
- open-api/rest-catalog-open-api.yaml
This PR added the `RemoveSnapshotRef` to both MetadataUpdateParser and OpenAPI spec. 
Closes https://github.com/apache/iceberg/issues/4876
P.S Thanks @kbendick for beautifully documenting the change in the above issue :) !!!
Added UT for the same.
----- 
cc @rdblue @kbendick
> Core / OpenAPI: Add RemoveSnapshotRef to MetadataUpdateParser and OpenAPI spec

- flink/v1.13/flink/src/test/java/org/apache/iceberg/flink/TestChangeLogTable.java
- flink/v1.13/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkV2.java
- flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/TestChangeLogTable.java
- flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkV2.java
- gradle.properties
- spark/v3.0/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRewriteManifestsProcedure.java
- spark/v3.0/spark/src/main/java/org/apache/iceberg/spark/actions/BaseRewriteManifestsSparkAction.java
- spark/v3.0/spark/src/main/java/org/apache/iceberg/spark/source/SparkMicroBatchStream.java
- spark/v3.0/spark/src/test/java/org/apache/iceberg/spark/actions/TestExpireSnapshotsAction.java
- spark/v3.0/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteDataFilesAction.java
- spark/v3.0/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteManifestsAction.java
- spark/v3.0/spark/src/test/java/org/apache/iceberg/spark/source/TestDataFrameWrites.java
- spark/v3.0/spark/src/test/java/org/apache/iceberg/spark/source/TestDataSourceOptions.java
- spark/v3.0/spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSourceTablesBase.java
- spark/v3.0/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkDataFile.java
- spark/v3.0/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkDataWrite.java
- spark/v3.0/spark/src/test/java/org/apache/iceberg/spark/sql/TestRefreshTable.java
- spark/v3.1/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRewriteManifestsProcedure.java
- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/actions/BaseRewriteManifestsSparkAction.java
- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/source/SparkMicroBatchStream.java
- spark/v3.1/spark/src/test/java/org/apache/iceberg/spark/actions/TestExpireSnapshotsAction.java
- spark/v3.1/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteDataFilesAction.java
- spark/v3.1/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteManifestsAction.java
- spark/v3.1/spark/src/test/java/org/apache/iceberg/spark/source/TestDataFrameWrites.java
- spark/v3.1/spark/src/test/java/org/apache/iceberg/spark/source/TestDataSourceOptions.java
- spark/v3.1/spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSourceTablesBase.java
- spark/v3.1/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkDataFile.java
- spark/v3.1/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkDataWrite.java
- spark/v3.1/spark/src/test/java/org/apache/iceberg/spark/sql/TestRefreshTable.java
This backports https://github.com/apache/iceberg/pull/4873 to Spark 2.4, 3.0, and 3.1 as well as Flink 1.13 and 1.14.
The only usage of the deprecated functions that remains is the call to [`snapshot.allManifests()` in SnapshotParser at line 86](https://github.com/apache/iceberg/blob/128d5a161fda076118a7cab1d95ab5064400e08a/core/src/main/java/org/apache/iceberg/SnapshotParser.java#L80-L90), which we explicitly chose to leave in for now as there should be very few tables that do not already have the manifest list in them (and are storing manifests instead).
cc @rdblue @nastra @danielcweeks
> API: Pass FileIO into Snapshot methods that read metadata - Backport

- docs/starrocks/_index.md
This PR adds a link to the documentation for StarRocks querying for Iceberg tables.
> Docs: Add StarRocks to Documentation

- api/src/main/java/org/apache/iceberg/SnapshotRef.java
Cleanup SnapshotRef to avoid unnecessary boxing in equality check by comparing snapshotID via ==
> API: Cleanup SnapshotRef to avoid unnecessary boxing in equality check by comparing snapshotID via ==

- flink/v1.13/flink/src/test/java/org/apache/iceberg/flink/TestFlinkCatalogTable.java
- flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/TestFlinkCatalogTable.java
- flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/TestFlinkCatalogTable.java
In the original code, the path is directly written `'location'='/tmp/location'` , and hdfs will access the local port 9000.
However, in general, hadoop is not installed during local testing, which causes the connection port to fail and the test case to report an error. 
So, I modified the path to store it on disk `'location'='file:///tmp/location'` , which is more convenient for local testing.
> Flink: Modify Table Location Strings in Tests to Fix Local Test Failures

- .github/workflows/api-binary-compatibility.yml
The API / ABI compatibility checking tool, `revapi`, is supposed to run whenever we run `./gradlew build` or `./gradlew check`.
However, for some reason - likely due to caching, this is getting skipped as can be verified in this example PR: https://github.com/apache/iceberg/pull/4796
That PR shows that the output of `./gradlew -DflinkVersions=1.13,1.14,1.15 -DsparkVersions=2.4,3.0,3.1,3.2 -DhiveVersions=2,3 build -x test -x javadoc -x integrationTest`, which is run during `Java CI`, should run `revapi`. However, `revapi` is being skipped in that step per the log output.
For the moment, I'm adding an explicit `API Binary Compatibility` workflow to circumvent this issue.
cc @rdblue
> Infra - Add an explicit workflow for API binary compatibility checks

- core/src/main/java/org/apache/iceberg/CatalogProperties.java
- core/src/main/java/org/apache/iceberg/rest/RESTSessionCatalog.java
- core/src/main/java/org/apache/iceberg/rest/auth/OAuth2Properties.java
- core/src/main/java/org/apache/iceberg/rest/auth/OAuth2Util.java
This adds a timeout for REST catalog sessions. After the timeout is reached after a session is used, it will be removed and its token will no longer be refreshed using token exchange.
This also cleans up catalog options for token refresh:
* Renamed token expiration property to `token-expires-in-ms`
* `auth.default-refresh-enabled` should be set to enable token refresh when `token-expires-in-ms` is not present
The default refresh option is needed for long-running environments that need to refresh tokens because references are kept for a long time, like Flink jobs. The default is to not refresh for environments like Trino that should not continuously refresh tokens that are no longer referenced and used.
> Core: Add REST catalog session timeout

- open-api/rest-catalog-open-api.yaml
For Python, when we generate classes it is required to have the non-default variables first:
This is not allowed:
```python
class ListType(IcebergType, rest_catalog.ListType):
def __init__(
cls,
element_id: int,
element_required: bool = True,
element: IcebergType
):
```
It should be:
```python
class ListType(IcebergType, rest_catalog.ListType):
def __init__(
cls,
element_id: int,
element: IcebergType,
element_required: bool = True
):
```
It would be nice to have the type first (which is also more important), and then required/optional. Of course, we can just adjust this in the Python init method but would be nice to have this order the same in the open-api spec as well :)
> OpenAPI: Have the type before type_required

- core/src/main/java/org/apache/iceberg/BaseTableScan.java
- core/src/main/java/org/apache/iceberg/PartitionsTable.java
- core/src/test/java/org/apache/iceberg/TestMetadataTableScans.java
- spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMetadataTables.java
Backport #4720 for 0.13.2 release.
Regression where user cannot have projections on Partitions table.
> [0.13] Core: Fix query failure when using projection on top of partitions metadata table (#4720)

- spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestDelete.java
- spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMergeOnReadDelete.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/SparkPositionDeltaWrite.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkCatalog.java
Extend the handling for https://github.com/apache/iceberg/pull/4687 for SparkPositionDeltaWriter used in MOR.
Added an E2E UT as done in earlier PR.
---
cc @RussellSpitzer @aokolnychyi @flyrain
> Spark: Extend commit unknown exception handling to SparkPositionDeltaWrite

- open-api/rest-catalog-open-api.yaml
This is the case for the MapType and ListType, and makes sense for the StructType as well:
https://github.com/apache/iceberg/blob/29f294610a012a60f3c3452a2608e386df54e48b/open-api/rest-catalog-open-api.yaml#L937-L943
https://github.com/apache/iceberg/blob/29f294610a012a60f3c3452a2608e386df54e48b/open-api/rest-catalog-open-api.yaml#L955-L963
> OpenAPI: Make the type of the StructType required

- .github/workflows/flink-ci.yml
- .github/workflows/hive-ci.yml
- .github/workflows/java-ci.yml
- .github/workflows/jmh-bechmarks.yml
- .github/workflows/labeler.yml
- .github/workflows/license_check.yml
- .github/workflows/publish-snapshot.yml
- .github/workflows/python-ci.yml
- .github/workflows/python-legacy-ci.yml
- .github/workflows/spark-ci.yml
```
- use ubuntu-20.04 explicitly in anticipation of the next ubuntu release
- upgrade to actions/cache@v3
- upgrade to actions/checkout@v3
- upgrade to actions/labeler@v4
- upgrade to actions/setup-java@v3
- upgrade to actions/setup-python@v3
- upgrade to actions/upload-artifact@v3
```
this brings various improvements for each action, see changelogs:
https://github.com/actions/cache#v3
https://github.com/actions/checkout/#checkout-v3
https://github.com/actions/setup-java#v2-vs-v1
https://github.com/actions/setup-python#whats-new
https://github.com/actions/labeler/releases
https://github.com/actions/upload-artifact/releases
a common change across all actions is that they are now based on node16 LTS since node12 LTS is going EOL later this year.
we explicitly use the `ubuntu-20.04` runner, …
> Build: upgrade github actions

- parquet/src/main/java/org/apache/iceberg/data/parquet/BaseParquetReaders.java
String columns from Parquet files written by writers that don't use logical type annotations are converted into binary data. This can be reproduced with older versions of Hive or Impala.
> Parquet: Fix Iceberg's parquet reader returning binary data instead of string data

- docs/spark/spark-ddl.md
- docs/spark/spark-writes.md
Fix two issues in Spark documentation.
1. Typo in Spark DDL doc.
2. Examples for creating/replacing a table using `writeTo` need `using("iceberg")`.
> Docs: Fix a typo. Add using for writeTo when creating a table.

- open-api/rest-catalog-open-api.yaml
All the types match exactly one of the schemas:
```json
"string"
{"type": "struct", ...}
{"type": "list", ...}
{"type": "map", ...}
```
For more information:
https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/
The types are mutually exclusive (in the schema, technically an int can also be promoted to a long). The aforementioned types should map to exactly one type.
We could also add a discriminator if we bump the primitive type to an object as well. My suggestion would be to break down:
```json
"fixed[22]"
"string"
```
into
```json
{"type": "fixed", "size": 22}
{"type": "string"}
```
This would allow us to set:
```yaml
Type:
oneOf:
- $ref: '#/components/schemas/PrimitiveType'
- $ref: '#/components/schemas/StructType'
- $ref: '#/components/schemas/ListType'
- $ref: …
```
> OpenAPI: Move to oneOf for the types

- core/src/main/java/org/apache/iceberg/rest/CatalogHandlers.java
- core/src/test/java/org/apache/iceberg/catalog/CatalogTests.java
This PR makes a couple of minor changes to make the catalog tests a little bit more flexible. For example, it makes some list checks ignore element order.
> Minor adjustments to catalog tests for flexibility

- core/src/main/java/org/apache/iceberg/rest/CatalogHandlers.java
- core/src/test/java/org/apache/iceberg/catalog/CatalogTests.java
This PR adds a couple of options to the catalog tests so it is more flexible for different catalog implementations. The first option is to support testing against catalogs that manage the table location. The second option is to support testing against catalogs that do not support slashes in the namespace or table name.
> Add additional options for catalog test implementations

- api/src/main/java/org/apache/iceberg/io/CredentialSupplier.java
- aws/src/main/java/org/apache/iceberg/aws/s3/S3FileIO.java
This adds an interface, `CredentialSupplier`, for engines that don't use `FileIO` and need to get some credential from a table's `FileIO` to access files through some other object store library.
> API: Add CredentialSupplier to get credentials from FileIO

- python/src/iceberg/files.py
- python/src/iceberg/io/base.py
> Python: Remove typing extension imports

- python/.pre-commit-config.yaml
- python/CONTRIBUTING.md
More as an example, since nothing really changed in the lint tools.
Using pre-commit you can easily bump the integrations to the latest version using `pre-commit autoupdate`.
```bash
➜  python git:(master) pre-commit autoupdate
Updating https://github.com/pre-commit/pre-commit-hooks ... already up to date.
Updating https://github.com/ambv/black ... already up to date.
Updating https://github.com/pre-commit/mirrors-isort ... already up to date.
Updating https://github.com/pre-commit/mirrors-mypy ... updating v0.950 -> v0.960.
Updating https://github.com/hadialqattan/pycln ... updating v1.3.2 -> v1.3.3.
```
> Python: Bump pre-commit hooks

- aws/src/main/java/org/apache/iceberg/aws/AwsClientFactories.java
- aws/src/main/java/org/apache/iceberg/aws/s3/S3FileIO.java
- core/src/main/java/org/apache/iceberg/CatalogUtil.java
Using the context classloader to dynamically load FileIO will cause problems in systems like Trino where the context classloader comes from a different plugin (e.g. information schema or describe table).
The classloader that loaded the `CatalogUtil` should have be the same classloader as the FileIO.
> Use CatalogUtil classloader instead of context classloader for FileIO

- api/src/main/java/org/apache/iceberg/expressions/And.java
- api/src/main/java/org/apache/iceberg/expressions/BoundLiteralPredicate.java
- api/src/main/java/org/apache/iceberg/expressions/BoundReference.java
- api/src/main/java/org/apache/iceberg/expressions/BoundSetPredicate.java
- api/src/main/java/org/apache/iceberg/expressions/BoundTerm.java
- api/src/main/java/org/apache/iceberg/expressions/BoundTransform.java
- api/src/main/java/org/apache/iceberg/expressions/BoundUnaryPredicate.java
- api/src/main/java/org/apache/iceberg/expressions/Expression.java
- api/src/main/java/org/apache/iceberg/expressions/ExpressionUtil.java
- api/src/main/java/org/apache/iceberg/expressions/False.java
- api/src/main/java/org/apache/iceberg/expressions/Or.java
- api/src/main/java/org/apache/iceberg/expressions/True.java
- api/src/main/java/org/apache/iceberg/expressions/UnboundPredicate.java
- api/src/test/java/org/apache/iceberg/expressions/TestExpressionUtil.java
This adds `ExpressionUtil.equivalent` and `ExpressionUtil.selectsPartitions` to determine whether an expression will select whole files in a partition spec. This is needed to determine whether a filter is guaranteed to delete only whole files, or whether a row-level plan should be used. It is also needed to implement aggregate pushdown with non-trivial filters because filters must match whole files in order to use file metadata to satisfy a query.
> API: Add expression equivalence testing

- core/src/main/java/org/apache/iceberg/rest/RESTSessionCatalog.java
This PR adds a shutdown to the refresh token executor service when the REST catalog client is closed. Without shutting down the executor, refresh tasks continue to be scheduled (and fail because the REST client is closed).
> Shutdown refresh token executor service during REST catalog client close

- docs/spark/spark-procedures.md
> Docs: Fix broken link for `expiration properties`

- python/src/iceberg/conversions.py
Instead of construct `Struct` each time in conversion functions using `struct(c_type).unpack`, we can create struct one in module and use the cached structs to pack and unpack, getting performance gain.
> Improve binary pack/unpack performance using cached struct

- python/.pre-commit-config.yaml
- python/src/iceberg/catalog/base.py
- python/src/iceberg/schema.py
- python/src/iceberg/table/base.py
- python/src/iceberg/transforms.py
- python/src/iceberg/types.py
- python/src/iceberg/utils/schema_conversion.py
The pyupgrade plugin will check the syntax, and make sure that you're using the latest version. For example, instead of Union[str, int] we have the str | int notation in Python 3.8.
This hook will not change any behavior of the code, but will just make sure that we're all using the same syntax.
More information on:
https://github.com/asottile/pyupgrade
> Python: Add pyupgrade as a pre-commit hook

- format/spec.md
The [java function](https://github.com/apache/iceberg/blob/5009949ba4377ac5a8572ff7ae70e886c9e33bec/api/src/main/java/org/apache/iceberg/util/UnicodeUtil.java#L42) seems to take this approach.  The [python](https://github.com/apache/iceberg/blob/6e1dfe965f51e58b6c2dd654c3481cfc803df52a/python_legacy/iceberg/api/transforms/truncate.py#L201) implementation seems to this also but requires the write type passed in to work
> [Specification] Clarify truncate for Iceberg strings is based on code points

- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/SparkCatalog.java
Recently, it was reported in Slack general channel that [AWS S3 tagging](https://github.com/apache/iceberg/blob/master/docs/integrations/aws.md#s3-tags) present in master branch is not working for keys with upper case.
Reference: https://apache-iceberg.slack.com/archives/C025PH0G1D4/p1653879105452189
This is because we use `CaseInsensitiveStringMap` for options in `SparkCatalog`. This PR uses options as a `CaseSensitiveMap`.
With this change, the following Spark configurations:
```
sh spark-sql --conf spark.sql.catalog.my_catalog=org.apache.iceberg.spark.SparkCatalog \
--conf spark.sql.catalog.my_catalog.warehouse=s3://iceberg-dev/warehouse.case-sensitive \
--conf spark.sql.catalog.my_catalog.catalog-impl=org.apache.iceberg.aws.glue.GlueCatalog \
--conf …
```
> Spark: Use options as a CaseSensitiveMap

- format/puffin-spec.md
Add a specification for Puffin format, a container file format to store
indices and stats for Iceberg tables.
> Add Puffin, indices and stats file format specification

- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/SparkMicroBatchStream.java
- At present we iterate the iterator of addedFiles to find the no of added files in the snapshot, this info is already present in snapshot summary. We should use this rather than iterating the addedFiles iterator to determine files added.
Came across this while working on 
- https://github.com/apache/iceberg/pull/4479
--- 
cc @rdblue, @RussellSpitzer, @jackye1995, @kbendick
> Spark 3.2: Use SnapshotSummary to deduce latestOffset in Spark SS

- parquet/src/main/java/org/apache/iceberg/parquet/BasePageIterator.java
```
BasePageIterator.java:166: warning: [NonCanonicalType] The type `BasePageIterator.NullIntIterator` was referred to by the non-canonical name `PageIterator.NullIntIterator`. This may be misleading.
return new PageIterator.NullIntIterator();
^
(see https://errorprone.info/bugpattern/NonCanonicalType)
Did you mean 'return new NullIntIterator();'?
```
Fix  reference of non canonical subclass as noted in this warning
> Checkstyle: fix reference of non canonical subclass

- core/src/main/java/org/apache/iceberg/catalog/TableIdentifierParser.java
- core/src/main/java/org/apache/iceberg/rest/RESTSessionCatalog.java
- core/src/main/java/org/apache/iceberg/rest/RESTUtil.java
- core/src/test/java/org/apache/iceberg/rest/RESTCatalogAdapter.java
- core/src/test/java/org/apache/iceberg/rest/TestRESTUtil.java
- core/src/test/java/org/apache/iceberg/rest/TestResourcePaths.java
- core/src/test/java/org/apache/iceberg/rest/requests/TestCreateNamespaceRequest.java
- core/src/test/java/org/apache/iceberg/rest/responses/TestCreateNamespaceResponse.java
- core/src/test/java/org/apache/iceberg/rest/responses/TestGetNamespaceResponse.java
- core/src/test/java/org/apache/iceberg/rest/responses/TestListTablesResponse.java
- open-api/rest-catalog-open-api.yaml
The null byte character is not generally considered safe for use in REST paths even when url encoded due to various forms of null byte injection attacks.  This will cause problems with many frameworks that detect and reject requests using this character in the path.
The unit separator character (`0x1F`) is a safer and more meaningful alternative.
> Update REST namespace separator to use unit separator char

- api/src/main/java/org/apache/iceberg/util/CharSequenceSet.java
- core/src/main/java/org/apache/iceberg/mapping/MappedFields.java
- core/src/main/java/org/apache/iceberg/util/StructLikeSet.java
Observed some build warnings:
`warning: [ObjectsHashCodeUnnecessaryVarargs] java.util.Objects.hash(non-varargs) should be replaced with java.util.Objects.hashCode(value) to avoid unnecessary varargs array allocations.
return Objects.hash(fields);
^
(see https://github.com/palantir/gradle-baseline#baseline-error-prone-checks)
Did you mean 'return Objects.hashCode(fields)`
In some hashCode implementations we unnecessarily use Objects.hash which accepts variadic arguments. Under the hood, this will create an array and do Arrays.hash. However, in these cases since we're passing in a single object reference, hashCode suffices, and we can avoid ant unnecessary array allocations,
> Core, API: Replace unnecessary hash uses with hashCode

- .github/workflows/api-binary-compatibility.yml
The API Binary compatibility task `revapi`, was previously skipping or occasionally passing when it shouldn't be (and when it was _not_ passing for local gradle runs).
The issues were two:
1. The cache action was causing the action to be skipped.
2. The git checkout action checks out by default at a depth of 1, which is a detached head state. Therefore, the output of `git describe` or the first line of the output of `git tags` was not showing up. The action uses this tag to find the proper existing overrides and "old" version to pull from maven (currently iceberg-api:0.13.0) 
This removes the cache action, adds a step to output the `git describe` (so we can easily verify which tag is considered current, which corresponds to what's in `.palantir/revapi.yml`), and then runs the revapi task …
> Infra - Fix API compatibility Github Action

- flink/v1.13/flink/src/main/java/org/apache/iceberg/flink/source/StreamingMonitorFunction.java
- flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/source/StreamingMonitorFunction.java
- flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/source/StreamingMonitorFunction.java
Keep the expensive split planning outside the lock and only lock for emitting splits and update lastSnapshotId position.
> Flink: reduce the scope and duration of holding checkpoint lock.

- core/src/main/java/org/apache/iceberg/rest/RESTSessionCatalog.java
- core/src/main/java/org/apache/iceberg/util/EnvironmentUtil.java
- core/src/test/java/org/apache/iceberg/util/TestEnvironmentUtil.java
The REST catalog has support for access tokens that are used with Bearer authentication. To help protect these access tokens, some deployments may prefer to set them from environment variables. This adds support for resolving REST catalog configuration values using the JVM environment (`System.getenv()`). If a catalog config value is `env:SOME_VAR`, the value will be replaced with the value of the environment variable `SOME_VAR`. If the environment variable is missing, the value will be null.
> Core: Resolve environment variables in REST catalog config

- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/actions/TestRemoveOrphanFilesAction.java
We at Cloudera run Iceberg tests on Apache/master branch on a daily basis. 
Ever since #4711 was merged `org.apache.iceberg.spark.actions.TestRemoveOrphanFilesAction3.testOlderThanTimestamp` is failing in our internal builds with the following assertion error:
```bash
java.lang.AssertionError: Should delete only 2 files expected:<2> but was:<3>
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.failNotEquals(Assert.java:835)
at org.junit.Assert.assertEquals(Assert.java:647)
at org.apache.iceberg.spark.actions.TestRemoveOrphanFilesAction.testOlderThanTimestamp(TestRemoveOrphanFilesAction.java:433)
```
We identified the RC as the following:
The code execution on our VM is so fast that the millisecond precision used for selecting the candidate as an orphan file is simply not enough …
> Test: Fix flaky testOlderThanTimestamp in TestRemoveOrphanFilesAction3

- python/src/iceberg/expressions/base.py
- python/src/iceberg/expressions/literals.py
- python/src/iceberg/types.py
- python/src/iceberg/utils/singleton.py
- python/tests/expressions/test_expressions_base.py
- python/tests/test_types.py
Instead of having a specialized caching mechanism per class, we can generalize it as a singleton metaclass that we can reuse across different classes.
This moves the `Singleton` out of the `types.py` and implements it as a singleton.
Changing `Class(ABC)` to `Class(metaclass=ABCMeta)` is equivalent, but nicer since it more explicitly shows that we're setting a metaclass. From abc:
```python
class ABC(metaclass=ABCMeta):
"""Helper class that provides a standard way to create an ABC using
inheritance.
"""
__slots__ = ()
```
> Python: Extend the use of the singleton

- python/spellcheck-dictionary.txt
- python/src/iceberg/table/partitioning.py
- python/tests/table/test_partitioning.py
2nd step of complete the https://github.com/apache/iceberg/issues/3228
This change include the PartitionSpec but not include its builder part as I want to keep the changelist as small as possible. As suggested in https://github.com/apache/iceberg/issues/4631, the construction of PartitionSpec shall rely on its Builder class with proper checks and such logic shall not be duplicated in its dunder init methods.
```python
from iceberg.schema import Schema
from iceberg.transforms import bucket
from iceberg.types import BooleanType, IntegerType, NestedField, StringType
from iceberg.table.partitioning import PartitionSpec, PartitionField
table_schema = Schema(
NestedField(field_id=1, name="foo", field_type=StringType(), is_optional=False),
NestedField(field_id=2, name="bar", …
```
> Python: Add PartitionSpec

- core/src/main/java/org/apache/iceberg/jdbc/JdbcUtil.java
Issue reference:
https://github.com/apache/iceberg/issues/4952
> edit NAMESPACE_PROPERTY_KEY to not be a reserved SQL keyword

- parquet/src/main/java/org/apache/iceberg/parquet/PruneColumns.java
- parquet/src/test/java/org/apache/iceberg/parquet/TestPruneColumns.java
Fixes the following error when pruning columns. This is because the `LogicalTypeAnnotation` of `Struct` is null.
```
at org.apache.iceberg.parquet.PruneColumns.isStruct(PruneColumns.java:167)
at org.apache.iceberg.parquet.PruneColumns.message(PruneColumns.java:58)
at org.apache.iceberg.parquet.PruneColumns.message(PruneColumns.java:35)
at org.apache.iceberg.parquet.ParquetTypeVisitor.visit(ParquetTypeVisitor.java:37)
at org.apache.iceberg.parquet.ParquetSchemaUtil.pruneColumns(ParquetSchemaUtil.java:80)
```
> Parquet: Fixes NPE when pruning columns

- api/src/main/java/org/apache/iceberg/expressions/Binder.java
- core/src/main/java/org/apache/iceberg/TableProperties.java
- parquet/src/main/java/org/apache/iceberg/parquet/Parquet.java
- parquet/src/main/java/org/apache/iceberg/parquet/ParquetBloomRowGroupFilter.java
- parquet/src/main/java/org/apache/iceberg/parquet/ParquetUtil.java
- parquet/src/main/java/org/apache/iceberg/parquet/ReadConf.java
- parquet/src/test/java/org/apache/iceberg/parquet/TestBloomRowGroupFilter.java
Co-Authored-By: Xi Chen [jshmchenxi@163.com](mailto:jshmchenxi@163.com)
Co-Authored-By: Hao Lin [linhao@qiyi.com](mailto:linhao@qiyi.com)
Co-Authored-By: Huaxin Gao [huaxin_gao@apple.com](mailto:huaxin_gao@apple.com)
This is the read path of parquet row group bloom filter. The original PR is [here](https://github.com/apache/iceberg/pull/4831/)
> Support reading Parquet row group bloom filter

- LICENSE
I think we forgot to update the home page from the Parquet block.
> LICENSE: Fix copy paste: s/parquet/avro/

- core/src/test/java/org/apache/iceberg/io/InMemoryInputFile.java
- core/src/test/java/org/apache/iceberg/io/InMemoryOutputFile.java
- core/src/test/java/org/apache/iceberg/io/TestInMemoryInputFile.java
- core/src/test/java/org/apache/iceberg/io/TestInMemoryOutputFile.java
The in-memory `InputFile` and `OutputFile` implementations has an
undesirable property that returned streams allowed use after close.
Since most streams don't have such property, it should be disallowed
here too.
Extracted from https://github.com/apache/iceberg/pull/4537 per https://github.com/apache/iceberg/pull/4741#discussion_r895212259
> Verify no stream use after close in in-memory tests

- .github/workflows/flink-ci.yml
- .github/workflows/hive-ci.yml
- .github/workflows/java-ci.yml
- .github/workflows/spark-ci.yml
Presently on updating LICENSE / NOTICE we trigger complete engine suite, As per my understanding it should not be required, and hence like ignored running tests README / CONTRIBUTING .md we should avoid running it for them.
> INFRA: Avoid running engine tests on LICENSE and NOTICE update

- core/src/main/java/org/apache/iceberg/RemoveSnapshots.java
- core/src/main/java/org/apache/iceberg/TableMetadataParser.java
- core/src/main/java/org/apache/iceberg/TableProperties.java
- core/src/test/java/org/apache/iceberg/TestRemoveSnapshots.java
This PR contains the updated expire snapshots procedure for branching and tagging. Implements the algorithm outlined here https://github.com/apache/iceberg/blob/master/format/spec.md#snapshot-retention-policy.
> Core: Update Remove Snapshots procedure for branching and tagging

- aws/src/main/java/org/apache/iceberg/aws/AwsProperties.java
- aws/src/main/java/org/apache/iceberg/aws/glue/GlueCatalog.java
- aws/src/main/java/org/apache/iceberg/aws/glue/GlueTableOperations.java
- aws/src/main/java/org/apache/iceberg/aws/glue/IcebergToGlueConverter.java
- aws/src/test/java/org/apache/iceberg/aws/glue/TestIcebergToGlueConverter.java
- docs/integrations/aws.md
Add a configuration `awsProperties.glueCatalogSkipNameValidation()` which allows characters like `-` in glue catalog namespaces
Tested with unittests.
```
> Task :iceberg-aws:test
BUILD SUCCESSFUL in 9s
13 actionable tasks: 1 executed, 12 up-to-date
4:07:42 PM: Execution finished ':iceberg-aws:test --tests "org.apache.iceberg.aws.glue.TestIcebergToGlueConverter"'.
```
> AWS: add skip name validation config for glue namespace

- python/src/iceberg/expressions/base.py
- python/src/iceberg/expressions/literals.py
- python/src/iceberg/types.py
- python/src/iceberg/utils/singleton.py
- python/tests/expressions/test_expressions_base.py
Follow up PR of https://github.com/apache/iceberg/pull/5008
Metaclasses in Python don't mix very well, and when they cause conflicts then it breaks at initialization.
An example of metaclasses is the ABC, but also the Pydantic BaseModel. I tried to circumvent this by extending the Singleton from ABC but it is likely that we use different metaclasses in the future, and then it will bring us sadness and misery.
> Python: Don't use a metaclass for the Singleton

- core/src/main/java/org/apache/iceberg/hadoop/HadoopTableOperations.java
In HadoopTableOperations, we use getFileSystem method to get FileSystem, which internally calls  Util.getFs but it was missing in some methods.
Using getFileSystem at all places in HadoopFileSystem allows to overriding method.
> Core: In HadoopTableOperations, replace Util.getFs call with getFileSystem

- open-api/rest-catalog-open-api.yaml
Currently, the properties are optional, which doesn't really make sense.
Also, in the Java code it throws an exception:
https://github.com/apache/iceberg/blob/master/core/src/test/java/org/apache/iceberg/rest/requests/TestRenameTableRequest.java#L106-L121
Therefore I would suggest making those required in the spec as well
> Open-api: RenameTableRequest props are required

- python/py.typed
Otherwise, the type annotations won't be used by other libraries. And that would be a pity of course :)
For more info: https://blog.whtsky.me/tech/2021/dont-forget-py.typed-for-your-typed-python-package/
> Python: Add py.typed file for annotations

- core/src/main/java/org/apache/iceberg/PartitionData.java
Include requested and actual class name in the exception message thrown
when `PartitionData` detects type mismatch.
> Include actual class name in class mismatch exception

- core/src/main/java/org/apache/iceberg/rest/requests/RenameTableRequest.java
- core/src/main/java/org/apache/iceberg/rest/responses/LoadTableResponse.java
- core/src/main/java/org/apache/iceberg/rest/responses/OAuthTokenResponse.java
The `LoadTableResponse` class is missing a java doc.
This class is used in multiple places, as outlined in the OpenAPI spec. Refer to
1. The responses that [use the `LoadTableResult` schema](https://github.com/apache/iceberg/blob/a7f7c1a9b78dd596c6c9eda1f0b621950b09f6f5/open-api/rest-catalog-open-api.yaml#L1929-L1959)
2. The [schema definition for `LoadTableResult`](https://github.com/apache/iceberg/blob/a7f7c1a9b78dd596c6c9eda1f0b621950b09f6f5/open-api/rest-catalog-open-api.yaml#L1461-L1482), which is part of this class.
I also took this opportunity to fix a few error prone warnings in the REST request / responses.
> [CORE] Add Java Doc for LoadTableResponse and fix error prone warnings

- core/src/main/java/org/apache/iceberg/rest/requests/CreateTableRequest.java
- core/src/test/java/org/apache/iceberg/rest/requests/TestCreateTableRequest.java
This adds tests for the serialization / deserialization of `CreateTableRequest`.
This class is already being used quite a bit in other tests, specifically `CatalogTests` and `TestRESTCatalog`. It also relied pretty heavily on existing serializers inside of `RESTSerializers` for things like `Schema` etc, which simply call out to our existing parsers.
Thus, I kept the tests light in terms of combinations of schemas etc as this is a combination of several tested components.
> [CORE] Add SerDe tests for CreateTableRequest

- python/.pre-commit-config.yaml
```
➜  python git:(fd-bump-pre-commit) pre-commit autoupdate
Updating https://github.com/pre-commit/pre-commit-hooks ... updating v4.2.0 -> v4.3.0.
Updating https://github.com/ambv/black ... already up to date.
Updating https://github.com/pre-commit/mirrors-isort ... already up to date.
Updating https://github.com/pre-commit/mirrors-mypy ... updating v0.960 -> v0.961.
Updating https://github.com/hadialqattan/pycln ... already up to date.
Updating https://github.com/asottile/pyupgrade ... updating v2.32.1 -> v2.34.0.
➜  python git:(fd-bump-pre-commit) ✗ pre-commit run --all-files
trim trailing whitespace.................................................Passed
fix end of files.........................................................Passed
check docstring is …
```
> Python: Bump pre-commit versions

- aws/src/integration/java/org/apache/iceberg/aws/glue/GlueTestBase.java
- aws/src/integration/java/org/apache/iceberg/aws/glue/TestGlueCatalogTable.java
- aws/src/main/java/org/apache/iceberg/aws/glue/GlueCatalog.java
- aws/src/test/java/org/apache/iceberg/aws/glue/TestGlueCatalog.java
augment to: https://github.com/apache/iceberg/pull/5041
integration test passed
```
> Task :iceberg-aws:integrationTest
[Test worker] INFO org.apache.iceberg.aws.glue.GlueCatalog - Created namespace: dd-dd
[Test worker] INFO org.apache.iceberg.BaseMetastoreCatalog - Table properties set at catalog level through catalog properties: {}
[Test worker] INFO org.apache.iceberg.BaseMetastoreCatalog - Table properties enforced at catalog level through catalog properties: {}
[Test worker] INFO org.apache.iceberg.BaseMetastoreTableOperations - Successfully committed to table glue.dd-dd.cc-cc in 1992 ms
BUILD SUCCESSFUL in 21s
14 actionable tasks: 1 executed, 13 up-to-date
2:54:01 PM: Execution finished ':iceberg-aws:integrationTest --tests …
```
> AWS: add skip name validation to isValidIdentifier

- python/src/iceberg/expressions/base.py
- python/src/iceberg/schema.py
Instead of doing the caching ourselves, functools has a nice decorator that can do that for us. I also removed the type ignore to avoid having an accidental None.
> Python: Replace vars with cached_property decorator

- hive-metastore/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java
While acquiring hive-metastore lock on an Iceberg table, after every timeout, below [log line](https://github.com/apache/iceberg/blob/98dc9fe8724375e8b932e7e8afdb925c897b4695/hive-metastore/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java#L542) is printed, which doesn't have database and table name information. 
`org.apache.iceberg.hive.HiveTableOperations$WaitingForLockException: Waiting for lock.`
After exhausting all the re-try attempt, finally below [log line](https://github.com/apache/iceberg/blob/98dc9fe8724375e8b932e7e8afdb925c897b4695/hive-metastore/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java#L561) prints database and table name.
`Retrying task after failure: Timed out after 180133 ms waiting for lock on database.table`
Here we are adding the …
> Hive: Print db and table name while acquiring hive meta-store lock

- core/src/main/java/org/apache/iceberg/BaseUpdatePartitionSpec.java
- core/src/main/java/org/apache/iceberg/Partitioning.java
- core/src/test/java/org/apache/iceberg/ScanTestBase.java
- core/src/test/java/org/apache/iceberg/TestMetadataTableScans.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/source/TestMetadataTablesWithPartitionEvolution.java
First go at fixing #4661.
The proposed solution described at https://github.com/apache/iceberg/pull/3411#discussion_r823692312 seems very hardly feasible, so this would be a quick fix to just avoid `Invalid schema` errors thrown in any metadata query where the a partition col was reused.
> Core: Metadata table queries fail if a partition column was reused in V2

- arrow/src/main/java/org/apache/iceberg/arrow/vectorized/parquet/VectorizedDictionaryEncodedParquetValuesReader.java
- arrow/src/main/java/org/apache/iceberg/arrow/vectorized/parquet/VectorizedParquetDefinitionLevelReader.java
Currently `VectorizedParquetDefinitionLevelReader` only works with `HeapByteBuffer`. When using off heap byte buffer, it throws Exception
```
org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 5.0 failed 1 times, most recent failure: Lost task 0.0 in stage 5.0 (TID 5) (192.168.1.126 executor driver): java.lang.UnsupportedOperationException
at java.base/java.nio.ByteBuffer.array(ByteBuffer.java:1049)
at org.apache.iceberg.arrow.vectorized.parquet.VectorizedParquetDefinitionLevelReader$VarWidthReader.nextVal(VectorizedParquetDefinitionLevelReader.java:418)
at org.apache.iceberg.arrow.vectorized.parquet.VectorizedParquetDefinitionLevelReader$BaseReader.nextBatch(VectorizedParquetDefinitionLevelReader.java:247)
at …
```
> Make VectorizedParquetDefinitionLevelReader work with off heap byte buffer

- api/src/main/java/org/apache/iceberg/actions/ActionsProvider.java
- spark/v3.2/spark/src/jmh/java/org/apache/iceberg/spark/action/IcebergSortCompactionBenchmark.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/Spark3Util.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/actions/BaseRewriteDataFilesSparkAction.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/actions/SparkActions.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/actions/SparkBinPackStrategy.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/procedures/RewriteDataFilesProcedure.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteDataFilesAction.java
Allows e.g. `db.special-chars`.`table.special-chars` when calling the RewriteDataFiles action or procedure, e.g.:
```sql
CALL system.rewrite_data_files(table => '`db.with-special`.`table.with-special`')
```
Currently this causes an exception as the full identifier (`<catalog>.<database>.<table>`) is stringified without any quoting.
```
IllegalArgumentException: Cannot parse path or identifier: dev.db.with-special.table.with-special
```
> Spark 3.2: RewriteDataFiles - Escape special characters in table identifiers

- python/.pre-commit-config.yaml
- python/src/iceberg/table/partitioning.py
- python/src/iceberg/utils/bin_packing.py
- python/tests/table/test_partitioning.py
- python/tests/utils/test_bin_packing.py
It’s slower to call e.g. `dict()` than using the empty literal `{}`, because the name `dict` must be looked up in the global scope in case it has been rebound.
> Python: Add flake8-comprehensions

- docs/spark-writes.md
The link of hidden partition in `spark-writes.md` is an error.
Change link from `partitioning` to `icebergs-hidden-partitioning` .
> Docs: Fix link error of hidden partition

- .baseline/checkstyle/checkstyle.xml
- core/src/main/java/org/apache/iceberg/BaseIncrementalAppendScan.java
- spark/v3.0/spark/src/main/java/org/apache/iceberg/spark/procedures/AddFilesProcedure.java
- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/procedures/AddFilesProcedure.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/procedures/AddFilesProcedure.java
Closes #4618 
From the issue:
`Preconditions.checkArgument` only works with %s, as %d does not parse and returns a bad error message.
Created a multiline regex to prevent this.
The regex is as follows:
```regex
Preconditions\.checkArgument\([^;]+%d[^;]+\);
```
The logic behind it: Find the function call, then any characters (except `;`) until `%d`, and finally search until the function closes and a ';'.
* Used `[^;]*` instead of `.*`, because this is a multiline search and the dotall regex param (enabled by `matchAcrossLines` config) is aggressive and this is the best way to break its search.
Also, fixed %d usages that the Checkstyle rule found
> Checkstyle: Add checkstyle rule for %d in Preconditions.checkArgument

- arrow/src/main/java/org/apache/iceberg/arrow/vectorized/ArrowVectorAccessors.java
- arrow/src/main/java/org/apache/iceberg/arrow/vectorized/GenericArrowVectorAccessorFactory.java
- spark/v2.4/spark/src/main/java/org/apache/iceberg/spark/data/vectorized/ArrowVectorAccessorFactory.java
- spark/v3.0/spark/src/main/java/org/apache/iceberg/spark/data/vectorized/ArrowVectorAccessorFactory.java
- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/data/vectorized/ArrowVectorAccessorFactory.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/data/vectorized/ArrowVectorAccessorFactory.java
This PR changes the dictionary value accessors in the vectorized parquet reader so that the dictionary values are read from the underlying dictionary directly, rather than copying the values into a new buffer where relevant (this was already being done in the dictionary decimal accessor classes). The underlying parquet dictionary classes already load the values into a buffer, so copying them to a new buffer appears redundant in some cases.
This PR also makes a couple of changes to avoid binary buffer copies when building string values when possible.
In very limited testing, this shows a performance gain of over 20% in vectorized read performance in some scenarios, though more testing would be required to get more accurate metrics.
> Arrow: Avoid extra dictionary buffer copy

- python/poetry.lock
```
➜  python git:(master) poetry update
Updating dependencies
Resolving dependencies... (3.4s)
Writing lock file
Package operations: 0 installs, 4 updates, 0 removals
• Updating importlib-metadata (4.11.4 -> 4.12.0)
• Updating nodeenv (1.6.0 -> 1.7.0)
• Updating virtualenv (20.14.1 -> 20.15.0)
• Updating fastavro (1.5.1 -> 1.5.2)
```
> Python: Bump dependencies

- core/src/main/java/org/apache/iceberg/util/SortOrderUtil.java
- core/src/test/java/org/apache/iceberg/util/TestSortOrderUtil.java
This updates `SortOrderUtil.buildSortOrder` to produce a correct clustering when building a final sort order. This method creates a new sort order that clusters rows for a given partition spec and produces the ordering that was passed in for rows within the same partition.
Previously, this was done by checking whether the partition source fields were included in the sort order, and that the transform applied to the source data satisfied the partition field's sort order. This simple approach left a few cases where the clustering was not actually satisfied.
For example: when partitioning by `[ day(ts), category ]` and sorting by `[ ts, category ]`, the original order would be used because `ts` satisfies the order of `days(ts)` and `category` satisfies the order for `category`. However, this …
> Core: Fix partition clustering to produce table sort order

- core/src/main/java/org/apache/iceberg/RemoveSnapshots.java
- core/src/test/java/org/apache/iceberg/TestRemoveSnapshots.java
This fixes the expiration for snapshots that are ancestors of tags. Tag ancestors should not be considered "referenced" snapshots and should be cleaned up using the global table settings.
> Core: Fix tag ancestor snapshot handling

- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/SparkSessionCatalog.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/TestSparkSessionCatalog.java
To close https://github.com/apache/iceberg/issues/2488. Open a new PR since #3126 isn't active for a while.
All comments in #3126 are resolved. Please take a look. @RussellSpitzer @rdblue @kbendick @szehon-ho @karuppayya @aokolnychyi
> Spark: Validate HMS uri in SparkSessionCatalog

- core/src/main/java/org/apache/iceberg/MetadataColumns.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/TypeToSparkType.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/TestSparkSchemaUtil.java
Presently when doing schema conversion we were setting `metadata` for all the the columns, but we should add `____metadata_col` in metadata column which can be used by spark to check if the column is `metadata` col and drop it if required like, 
here : 
https://github.com/apache/spark/blob/master/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/plans/logical/v2Commands.scala#L221-L225
Note : `MetadataAttribute` extractor uses the above key in attribute meta data to find if the attribute is metadata attribute or not.
This PR includes : 
(i) Fix for above 
(ii) Fix an existing minor typo in `TestSparkSchemaUtil`
---- 
Added an UT for the same.
cc @rdblue @aokolnychyi @jackye1995 @RussellSpitzer
> Spark: Add `__metadata_col` metadata in metadata columns when doing Schema Conversion

- mr/src/main/java/org/apache/iceberg/mr/mapreduce/IcebergSplit.java
- mr/src/test/java/org/apache/iceberg/mr/TestIcebergInputFormats.java
`IcebergSplit.ANYWHERE` was a mutable and publicly accessible field, so
someone could modify it. The modification could also be accidental, if
someone modified the array returned from `IcebergSplit.locations()`.
> Encapsulate public mutable field in IcebergSplit

- api/src/main/java/org/apache/iceberg/Accessors.java
- api/src/test/java/org/apache/iceberg/TestAccessors.java
Positional accessors can be helpful to getting Row values
that are not primitive. Even though there does not appear
to be any use cases for this in the Iceberg codebase itself,
it seems logical to extends Accessors to support this to
allow external tools to use Accessors uniformly across all
column types.
* Update PositionAccessor to use appropriate javaClass in
get operations targeting composite values types (List, Map,
Struct).
* Generate individual positional accessors for Struct fields
to allow getting them as an Object. Previously, nested structs
could only be accessed field-by-field.
Note: Accessing Struct fields nested in Lists and Maps is
not supported.
/cc @nastra , @ajantha-bhat , @RussellSpitzer
> API: Support composite types in Accessors

- docs/_index.md
This brings over the change to this page in iceberg-docs from [this](https://github.com/apache/iceberg-docs/pull/94/files#diff-5d9ba8bc1a568741b44ccc852748ca739d71f89dc1ac05a9f8d3787a064a549d) PR. This file is pending removal from iceberg-docs and going forward will only be source controlled here in the iceberg repo.
> Docs: Add reference to Apache Impala documentation

- core/src/main/java/org/apache/iceberg/rest/requests/CreateTableRequest.java
The JavaDoc for `CreateTableRequest` appears to be copied over from the `CreateNamespaceRequest` class.
Updating it to reflect `CreateTableRequest` instead.
> Core - Update JavaDoc for CreateTableRequest

- python/src/iceberg/transforms.py
- python/tests/utils/test_singleton.py
We want to reuse VoidTransform since it doesn't carry any state
> Python: Make the VoidTransform a singleton

- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/SparkBatch.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/SparkScan.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/actions/TestExpireSnapshotsAction.java
A performance regression was introduced with the refactoring of the Spark batch classes. One problem that surfaced was that `BatchScanExec` does an equality check on the batch object. However with the refactoring, a new batch object was created for each call to `toBatch()` so the equality check returned false for the same scan instance (because the batch objects were different). The end result is that filters weren't being pushed down in some cases.
Creating only one batch object per scan partially fixed the performance problems, but other issues remained. So this PR makes the scan class implement the Batch interface as before the refactor, for now, until all of the issues can be addressed.
> Spark: fix regression from scan refactor

- core/src/main/java/org/apache/iceberg/rest/CatalogHandlers.java
- core/src/main/java/org/apache/iceberg/rest/responses/LoadTableResponse.java
- core/src/test/java/org/apache/iceberg/rest/responses/TestLoadTableResponse.java
- open-api/rest-catalog-open-api.yaml
This PR adds serde tests for `LoadTableResponse`.
It also removes `metadata-location` as a required field for `LoadTableResponse`, as `LoadTableResponse` is returned in response to a `CreateTableRequest` for staging a table for creation without committing it during a transaction. There is not yet necessarily a metadata location as the table has not been fully created.
To avoid making a number of things public, I'm reading in existing `TableMetadata` JSON files and testing `LoadTableResponse` with those (as `LoadTableResponse` is what's being tested, not `TableMetadata`).
> CORE - Load Table Response Test

- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/SparkCatalog.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/SparkSessionCatalog.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/IcebergSource.java
- spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/sql/TestSelect.java
Closes : 
1. https://github.com/apache/iceberg/issues/4365
2. https://github.com/apache/iceberg/issues/1405
3. https://github.com/apache/iceberg/issues/2618
---- 
1. Make SparkSession Catalog implement newly introduced Catalog methods
2. respect newly added data frame reader options via SupportsCatalogOptions
3. Adapt the timestamp precision returned by spark to iceberg requirements.
P.S This change would not have been possible without the awesome work done by @huaxingao in spark to [support AS OF grammar in spark](https://issues.apache.org/jira/browse/SPARK-37219) natively. 
---- 
Added new UT's 
----
cc @rdblue, @aokolnychyi , @RussellSpitzer , @jackye1995 , @huaxingao , @flyrain
> Spark 3.3: [FOLLOW UP] Support AS OF SPARK SQL syntax for TimeTravel E2E

- core/src/main/java/org/apache/iceberg/StreamingDelete.java
Make `StreamingDelete` a public class so that it can be used on packages outside of `org.apache.iceberg`.
This is useful for whenever users want to subclass the default implementation for monitoring or to add custom snapshot properties.
> StreamingDelete becomes public class

- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/SparkBatch.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/SparkScan.java
- spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/actions/TestExpireSnapshotsAction.java
This ports a change from the Spark v3.2 code to v3.3 that resolves a performance issue. See [this PR](https://github.com/apache/iceberg/pull/5143/files).
> Spark: Port performance fix for Spark 3.2 to 3.3

- format/spec.md
Clean up some rough language in the user-facing spec documentation.
> Format: Cleanup language in spec ORC type notes

- flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/RowDataConverter.java
private static RowData convert(Types.StructType struct, Record record) invoke private static Object convert(Type type, Object object), the latter has already use a switch case to handle STRUCT,LIST,MAP，so I just remove the unnecessary judgement  in the caller method.
> delete unnecessary switch case judgement

- aws/src/integration/java/org/apache/iceberg/aws/TestDefaultAwsClientFactory.java
- aws/src/main/java/org/apache/iceberg/aws/AssumeRoleAwsClientFactory.java
- aws/src/main/java/org/apache/iceberg/aws/AwsClientFactories.java
- aws/src/main/java/org/apache/iceberg/aws/AwsProperties.java
This makes testing DynamoDB integration easily with docker (https://hub.docker.com/r/amazon/dynamodb-local/).
> AWS: support overriding endpoint in DynamoDB

- core/src/main/java/org/apache/iceberg/BaseMetastoreTableOperations.java
- hive-metastore/src/main/java/org/apache/iceberg/hive/HiveCatalog.java
- hive-metastore/src/test/java/org/apache/iceberg/hive/HiveTableTest.java
Filesystem tables and metastore tables have different naming conventions for TableMetadata file as per spec.
So, when a filesystem table is registered to hive catalog (or any metastore based catalog), the register was successful but loading the table used to fail in `parseVersion` as it was expecting the naming convention of metastore table.
Fixed it by using metastore table naming convention while registering. 
Fixes #4794
> API: Support registering filesystem tables to metastore based catalogs

- core/src/main/java/org/apache/iceberg/AllManifestsTable.java
- core/src/test/java/org/apache/iceberg/TestMetadataTableScans.java
- spark/v2.4/spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSourceTablesBase.java
- spark/v3.0/spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSourceTablesBase.java
- spark/v3.1/spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSourceTablesBase.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSourceTablesBase.java
- spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSourceTablesBase.java
This is a pre-requisite for expire-snapshot performance improvement in : https://github.com/apache/iceberg/pull/4736
> Core: Add reference_snapshot_id column and filter to AllManifest table

- core/src/main/java/org/apache/iceberg/TableProperties.java
- docs/configuration.md
- parquet/src/main/java/org/apache/iceberg/parquet/Parquet.java
- parquet/src/main/java/org/apache/iceberg/parquet/ParquetWriter.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkReaderWithBloomFilter.java
- spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkReaderWithBloomFilter.java
Co-authored-by: Xi Chen <jshmchenxi@163.com>
Co-authored-by: Hao Lin <linhao1990@gmail.com>
Co-authored-by: Huaxin Gao <huaxin_gao@apple.com>
This is the write path of parquet row group bloom filter. The original PR is [here](https://github.com/apache/iceberg/pull/4831)
> Add Parquet Row Group Bloom Filter Support for write path

- parquet/src/main/java/org/apache/iceberg/parquet/ParquetUtil.java
We saw parquet files (don't have bloom filters) with `bloomFilterOffset = 0`  :(
This is a known [bug](https://issues.apache.org/jira/browse/PARQUET-1979). It was fixed before the bloom filter was released in parquet-mr 1.12.0, but I guess it's possible people may use the unofficial released parquet-mr (which has the bloom filter support but doesn't have the offset bug fix), so change the check to be `getBloomFilterOffset() <= 0` to be safe.
> Check getBloomFilterOffset() <= 0 for non bloom filter

- open-api/rest-catalog-open-api.yaml
Looking at the code, we expect this field:
https://github.com/apache/iceberg/blob/master/core/src/main/java/org/apache/iceberg/SortOrderParser.java#L154
And we always write it on the Java side.
@rdblue Can you confirm this? I saw that you recently did some work on this.
> Spec: Sort-order order-id is mandatory

- api/src/main/java/org/apache/iceberg/io/FileIO.java
- aws/src/main/java/org/apache/iceberg/aws/s3/S3FileIO.java
- aws/src/test/java/org/apache/iceberg/aws/s3/TestS3FileIO.java
- core/src/main/java/org/apache/iceberg/SortOrderParser.java
- core/src/main/java/org/apache/iceberg/hadoop/HadoopFileIO.java
- core/src/main/java/org/apache/iceberg/io/FileIOParser.java
- core/src/main/java/org/apache/iceberg/io/ResolvingFileIO.java
- core/src/main/java/org/apache/iceberg/util/JsonUtil.java
- gcp/src/main/java/org/apache/iceberg/gcp/gcs/GCSFileIO.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/TestFileIOSerialization.java
This adds a JSON parser to serialize FileIO instances to and from JSON. The format is an object with an `io-impl` and configuration `properties`. Deserialization uses `CatalogUtil` to re-create an instance from an environment Hadoop Configuration (optional), the IO impl class, and the configuration used to create the original `FileIO`.
> API: Add generic FileIO JSON serialization

- python_legacy/tox.ini
We got a new release on June 1st:
https://pypi.org/project/flake8-bugbear/22.7.1/
This introduced a new rule that actually broke the CI.
It is best to not do global lookups because of scoping and performance,
but I don't feel like rewriting the legacy code either.
> Python: Pin bugbear in Python legacy

- docs/flink-getting-started.md
- flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/FlinkConfParser.java
- flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/FlinkWriteConf.java
- flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/FlinkWriteOptions.java
- flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java
- flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/sink/RowDataTaskWriterFactory.java
- flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSink.java
- flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/sink/TestIcebergStreamWriter.java
Supports overwriting table configuration, such upsert \ overwirte\ file-format, when creating Flink sink.
> Flink: Support write options in FlinkSink builder

- spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/SparkTestBase.java
- spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/actions/TestCreateActions.java
Address https://github.com/apache/iceberg/pull/5094#discussion_r902008258
Spark was writing 3 level list rather than 2 level list which was expected in the [UT](https://github.com/apache/iceberg/blob/7e1ade80397a54c24db3634cb6015d539143e62d/spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/actions/TestCreateActions.java#L640-L703). 
On debugging this more found that, since the schema was passed via  `spark.read().schema(sparkSchema).json` and as of spark 3.3 spark will not respect the nullability in the schema passed via above by default (ref. [this](https://github.com/apache/iceberg/pull/5094)). 
Now since the nullability is not respected (will be considered nullable) by spark by default the Parquet writer despite `writeLegacyParquetFormat` being true, will write in Three level …
> Spark 3.3: Re-Enable TwoLevel Parquet List UT

- api/src/main/java/org/apache/iceberg/Accessors.java
- api/src/main/java/org/apache/iceberg/types/Comparators.java
- api/src/main/java/org/apache/iceberg/types/Type.java
- api/src/test/java/org/apache/iceberg/types/TestComparators.java
Previously TypeID.STRUCT, LIST and MAP exposed Void as their
java type. It seems reasonable to expose more specific java
types according to existing code patterns in Accessors and
Comparators and simplify their if/switch statements.
ManifestFileUtil has non-trivial logic around the value returned
from TypeID.javaClass() but it works only on PrimitiveType, so it
is not affected by this change.
BaseDataReader (for Spark) also has non-trivial logic for processing
TypeID.javaClass() in its convertConstant() method, but this change
appears to actually improve the processing of values in that case.
PartitionSpec appears to be unaffected by this change as it would
normally use TypeID.javaClass() only for primitive values. In any
case this change should not break its processing logic.
> API: Add java type to composite TypeID enums

- docs/flink-getting-started.md
Add flink and iceberg type compatibility.
Can you help review it? thanks !
@rdblue @openinx @kbendick 
Closes #4864
> Docs: add flink and iceberg type compatibility 

- core/src/main/java/org/apache/iceberg/ManifestFiles.java
- core/src/main/java/org/apache/iceberg/MetricsModes.java
- core/src/main/java/org/apache/iceberg/avro/Avro.java
- core/src/main/java/org/apache/iceberg/encryption/InputFilesDecryptor.java
- core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java
- core/src/main/java/org/apache/iceberg/rest/CatalogHandlers.java
- core/src/main/java/org/apache/iceberg/rest/RESTSessionCatalog.java
- core/src/main/java/org/apache/iceberg/util/Tasks.java
- core/src/main/java/org/apache/iceberg/util/ZOrderByteUtils.java
- data/src/test/java/org/apache/iceberg/data/TestReadProjection.java
The only warning that is left is this one from https://github.com/apache/iceberg/blob/2f8a09a8f81b27b8ba4025efaa328244ae0fc2a6/core/src/main/java/org/apache/iceberg/util/ZOrderByteUtils.java#L182-L183
which seems legit as we're doing a lossy cast that would fail compilation if I rewrite it (https://errorprone.info/bugpattern/NarrowingCompoundAssignment):
```
> Task :iceberg-core:compileJava
/home/nastra/Development/workspace/iceberg/core/src/main/java/org/apache/iceberg/util/ZOrderByteUtils.java:182: warning: [NarrowingCompoundAssignment] Compound assignments from int to byte hide lossy casts
interleavedBytes[interleaveByte] |=
^
(see https://errorprone.info/bugpattern/NarrowingCompoundAssignment)
Did you mean 'interleavedBytes[interleaveByte] = (byte) (interleavedBytes[interleaveByte] | …
```
> Core: Fix ErrorProne Warnings

- arrow/src/main/java/org/apache/iceberg/arrow/vectorized/GenericArrowVectorAccessorFactory.java
- arrow/src/main/java/org/apache/iceberg/arrow/vectorized/parquet/DecimalVectorUtil.java
- arrow/src/main/java/org/apache/iceberg/arrow/vectorized/parquet/VectorizedDictionaryEncodedParquetValuesReader.java
- arrow/src/main/java/org/apache/iceberg/arrow/vectorized/parquet/VectorizedParquetDefinitionLevelReader.java
- spark/v3.3/spark/src/jmh/java/org/apache/iceberg/spark/source/parquet/vectorized/VectorizedReadDictionaryEncodedFlatParquetDataBenchmark.java
- spark/v3.3/spark/src/jmh/java/org/apache/iceberg/spark/source/parquet/vectorized/VectorizedReadFlatParquetDataBenchmark.java
- spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/data/AvroDataTest.java
- spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/data/parquet/vectorized/TestParquetVectorizedReads.java
This PR fixes the vectorized reader for decimals that are fixed length binary and dictionary-encoded. Before these decimals would be downcast to 8 byte (long) precision. This only affects Parquet V2, as fixed length binary decimals aren't dictionary-encoded in Parquet V1. The Spark vectorized reader test for Parquet V2 was modified so this is now tested.
Also included is a minor refactor of the big endian padding to share some common logic and make it easier to enhance later.
In addition, the Spark benchmark test for the vectorized reader was enhanced to include both long encoded and fixed width binary encoded decimals.
> Arrow: Fix for dictionary encoded fixed length binary decimals

- core/src/main/java/org/apache/iceberg/ManifestGroup.java
This improves job planning performance by moving `ManifestFiles.read` setup into the `ParallelIterator` that is used to plan tasks. `ParallelIterator` accepts an `Iterable` of `CloseableIterable`. The outer iterable is iterated over to submit tasks that run in the worker pool. In `ManifestGroup`, the `Iterable` that was returned would call `ManifestFiles.read` to prepare the inner iterable, but the `ManifestReader` needs to read Avro file metadata and will open a stream. That initial file open was running in the consuming thread as tasks were submitted, instead of in the worker pool.
This updates `ManifestGroup` to use a custom `Iterable` that defers calling `ManifestFiles.read` until the inner iterable is used.
> Core: Defer reading Avro metadata until ManifestFile is read

- spark/v3.2/build.gradle
This will match the Antlr version in Spart 3.2.
> Spark: Update Antlr in Spark 3.2 extensions to 4.8

- mr/src/main/java/org/apache/iceberg/mr/hive/serde/objectinspector/IcebergRecordObjectInspector.java
- mr/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerWithEngine.java
- mr/src/test/java/org/apache/iceberg/mr/hive/serde/objectinspector/TestIcebergRecordObjectInspector.java
> Hive: Fix NPE when reading a struct field with null value

- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/SparkScanBuilder.java
- spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/sql/TestSelect.java
Currently iceberg throws Exception when using a filter on complex type:
```
org.apache.iceberg.spark.sql.TestSelect > testComplexTypeFilter[catalogName = testhadoop, implementation = org.apache.iceberg.spark.SparkCatalog, config = {type=hadoop}] FAILED
java.lang.IllegalArgumentException: Cannot create expression literal from org.apache.spark.sql.catalyst.expressions.GenericRowWithSchema: [3,v1]
at org.apache.iceberg.expressions.Literals.from(Literals.java:87)
at org.apache.iceberg.expressions.UnboundPredicate.<init>(UnboundPredicate.java:40)
at org.apache.iceberg.expressions.Expressions.equal(Expressions.java:175)
at org.apache.iceberg.spark.SparkFilters.handleEqual(SparkFilters.java:239)
at org.apache.iceberg.spark.SparkFilters.convert(SparkFilters.java:152)
at …
```
> Not push down complex filter

- core/src/main/java/org/apache/iceberg/actions/SortStrategy.java
- core/src/test/java/org/apache/iceberg/actions/TestSortStrategy.java
This is based on #4922, but adds a check for the unsorted order to make tests pass without modification.
Closes #4922.
> Core: Use table partitioning with manual sort order

- core/src/main/java/org/apache/iceberg/TableMetadata.java
- core/src/test/java/org/apache/iceberg/catalog/CatalogTests.java
This fixes a bug in the `TableMetadata` builder, where reverting to an older schema, spec, or sort order will correctly suppress the `AddSchema` change, but will still create a `SetSchema(-1)` change.
The fix is to detect when the new schema ID is an existing schema and suppress the `SetSchema` change as well.
> Core: Fix REST catalog when reverting DDL changes.

- core/src/main/java/org/apache/iceberg/MetricsConfig.java
- core/src/main/java/org/apache/iceberg/TableProperties.java
- core/src/test/java/org/apache/iceberg/TestMetricsModes.java
- data/src/test/java/org/apache/iceberg/io/TestWriterMetrics.java
#3959 updated `MetricsConfig` to stop writing metrics by default for tables with more than 32 columns. The intent was to avoid having too much metadata stored as stats in manifest files, but the implementation stopped writing metrics for all columns after a table reached 32 columns, which caused a large change in table performance after a table grows to 32+ columns.
This updates the logic so that the first 32 columns still have metrics, but no new metrics are stored for columns after that point unless the table has a global default set or columns are individually configured.
> Core: Update MetricsConfig to use a default for first 32 columns

- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/SparkScanBuilder.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/sql/TestSelect.java
This PR backports the changes in https://github.com/apache/iceberg/pull/5204 to Spark 3.2
> backport #5204 to Spark3.2

- .github/workflows/open-api.yml
- open-api/rest-catalog-open-api.yaml
While generating Python code from the open-api spec to bootstrap the Python rest catalog implementation I noticed that the URLs were constructed differently than expected.
For our service the warehouse uuid is encoded as part of the path:
```
https://api.iceberg.io/ws/v1/oss/warehouses/8bcb0838-50fc-472d-9ddb-8feb89ef5f1e/namespaces
```
However, the open-api spec states that the `/v1/` comes after the base path:
```
/v1/namespaces/{namespace}/properties:
```
This would lead to:
```
https://api.iceberg.io/ws/oss/warehouses/8bcb0838-50fc-472d-9ddb-8feb89ef5f1e/v1/namespaces
```
where the base path is part of the server's definition:
```yaml
servers:
- url: "{scheme}://{host}/{basePath}"
description: Server URL when the port can be inferred from the scheme
variables:
scheme:
description: The …
```
> Rest-catalog: Add flexibility to paths in rest catalog

- build.gradle
This adds a git properties file, generated using the https://github.com/n0mer/gradle-git-properties (many thanks to @nastra) for both the top level project.
The top level project file is needed so that the source tarball has a file that it can add to the tarball before releasing in `dev/source-release.sh`.
This is an alternative implementation to https://github.com/apache/iceberg/pull/5186
I've tested this, and we might want to remove some of the git property information but otherwise this generates the file `build/iceberg-build.properties` as described in the output comments below.
Note that [`build/**` is in the `.gitattributes` file as `export-ignore`](https://github.com/apache/iceberg/blob/b0937a4951a2d4a40b67eda484d49c4a4d32566e/.gitattributes#L26-L27), so this file won't be added to …
> Build - Add Git Build Properties File via Plugin

- build.gradle
- deploy.gradle
- dev/source-release.sh
- tasks.gradle
This ensures that `iceberg-build.properties` is added to Jars produced by the Gradle build, even when building from a source tarball with no `.git` directory.
This builds on the `generateGitProperties` task added in #5228 and updates the build:
* A new task, `buildInfo` ensures that `build/iceberg-build.properties` exists, either by copying it from the source root or by calling `generateGitProperties` (change in `tasks.gradle`)
* All Jars will now include `iceberg-build.properties` from the root `build` folder (change in `deploy.gradle`)
* The source release script will generate `iceberg-build.properties` and add it to the root folder for the release candidate tarball (changes in `source-release.sh`)
Note that this also changes how release tarballs are created. Previously, the …
> Build: Add iceberg-build.properties to Jars and release process

- python/.pre-commit-config.yaml
- python/pyiceberg/io/base.py
- python/pyiceberg/io/memory.py
- python/pyproject.toml
- python/tests/avro/test_decoder.py
- python/tests/conftest.py
- python/tests/io/test_io_base.py
- python/tests/test_schema.py
Mypy was so quiet, that I got a bit suspicious.
The path to the config file was incorrect, therefore it was not working.
I fixed all the violations, but also ran into some other issues:
It looks like that open() returns an incompatible type:
```
python/tests/conftest.py:833: error: Incompatible return value type (got "BufferedWriter", expected "OutputStream")
python/tests/conftest.py:833: note: Following member(s) of "BufferedWriter" have conflicts:
python/tests/conftest.py:833: note:     Expected:
python/tests/conftest.py:833: note:         def write(self, b: bytes) -> None
python/tests/conftest.py:833: note:     Got:
python/tests/conftest.py:833: note:         def write(self, Union[bytes, Union[bytearray, memoryview, array[Any], mmap, _CData, PickleBuffer]]) -> int
```
When fixing the …
> Python: Reenable mypy

- core/src/main/java/org/apache/iceberg/AllManifestsTable.java
Follow up from: https://github.com/apache/iceberg/pull/4847#discussion_r907751846, use Set.contains() to improve performance.
> Core: Improve in and not_in predicate eval for all_manifests.reference_snapshot_id

- python/pyiceberg/expressions/base.py
- python/tests/expressions/test_expressions_base.py
@samredai @rdblue 
Opening a draft PR introducing the `In` expression to get confirmation of the api. 
Is `def __init__(self, ref: 'UnboundReference', list: List[Literal]):` the correct signature?
I'll add the tests next and if this PR succeeds I will add the remaining boolean expressions
> remove operations from base expressions; add in expression

- core/src/main/java/org/apache/iceberg/TableMetadata.java
- core/src/main/java/org/apache/iceberg/rest/CatalogHandlers.java
- core/src/main/java/org/apache/iceberg/rest/RESTSessionCatalog.java
- core/src/test/java/org/apache/iceberg/catalog/CatalogTests.java
- core/src/test/java/org/apache/iceberg/rest/responses/TestLoadTableResponse.java
Currently in the REST catalog handler, during a CTAS, the files will be written and associated with the partition spec ID from the initial create request. When the commit occurs, an empty table metadata object is created and updates are applied to that. However, applying the updates will increment the partition spec ID, so the files will be associated with the empty spec ID, and thus partition pruning will not be available for these files.
This PR adds the ability to build on top of an empty TableMetadata so the initial IDs will match the initial files. It also moves `TableMetadata.newTableMetadata` to use the builder to instantiate a new instance so it can reuse functionality from the builder and to be consistent with `buildReplacement()`.
> REST: Create commit catalog handler fix

- spark/v3.3/spark-extensions/src/main/antlr/org.apache.spark.sql.catalyst.parser.extensions/IcebergSqlExtensions.g4
- spark/v3.3/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/parser/extensions/IcebergSparkSqlExtensionsParser.scala
- spark/v3.3/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/parser/extensions/IcebergSqlExtensionsAstBuilder.scala
- spark/v3.3/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRewriteDataFilesProcedure.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/ExtendedParser.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/Spark3Util.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/actions/BaseRewriteDataFilesSparkAction.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/actions/SparkZOrderStrategy.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/procedures/RewriteDataFilesProcedure.java
This is just a port of #4902 (from spark-3.2)
> Spark-3.3: Support Zorder option for rewrite_data_files stored procedure

- api/src/main/java/org/apache/iceberg/IcebergBuild.java
- api/src/test/java/org/apache/iceberg/TestIcebergBuild.java
- build.gradle
- tasks.gradle
This is based on `VersionProperties` from an old version of #5228 by @kbendick. This updates the class to use iceberg-build.properties in the root `build` folder, renames the class to `IcebergBuild`, and adds tests.
Co-authored-by: Kyle Bendickson <kyle@tabular.io>
> API: Add IcebergBuild info

- core/src/main/java/org/apache/iceberg/rest/HTTPClientFactory.java
- core/src/test/java/org/apache/iceberg/rest/TestHTTPClient.java
The HTTPClientFactory is used to build the HTTP Client that will be used by the REST Catalog.
This PR injects the following two headers into each request, for debugging purposes:
-   X-Client-Version  
-   X-Client-Git-Commit-Short
To test for these headers, `TestHTTPClient` was updated to use the `HTTPClientFactory`. The headers, with their expected values, are placed on each expected request, which is an assertion.
Notice that we don't have to add the headers onto the request that is sent, as they are default headers for each request.
This PR needs relies on work in #5237 and needs to be rebased once that is merged.
> Core - Add build information to all requests sent by HTTPClient as headers

- core/src/main/java/org/apache/iceberg/DeleteFileIndex.java
- core/src/main/java/org/apache/iceberg/actions/BaseRewriteDataFilesAction.java
- core/src/main/java/org/apache/iceberg/util/StructLikeMap.java
- core/src/main/java/org/apache/iceberg/util/StructLikeSet.java
- core/src/main/java/org/apache/iceberg/util/StructLikeWrapper.java
- data/src/main/java/org/apache/iceberg/data/DeleteFilter.java
- data/src/main/java/org/apache/iceberg/data/InternalRecordWrapper.java
This is an alternative implementation of #5242 and #5244. Rather than adding factory classes, this adds a `copyFor` method to `StructLikeWrapper` and `InternalRecordWrapper`. This is smaller than adding a factory and keeps the logic in one place (rather than duplicating it in a factory).
This updates cases where the wrappers are used to copy wrappers rather than create new ones. This avoids analyzing the type that the wrappers are created for and should speed up execution.
> Core: Fix wrapper performance for delete filters

- python/pyiceberg/expressions/base.py
- python/tests/expressions/test_expressions_base.py
- python/tests/test_types.py
This adds `BindVisitor` which is an implementation of `BooleanExpressionVisitor` for binding all references in an expression. As an example, here's binding an expression along the lines of `'a' in ('foo', 'bar', 'baz')`.
```py
from pyiceberg.expressions.base import BindVisitor, In, Reference, visit
from pyiceberg.expressions.literals import literal
from pyiceberg.schema import Schema
from pyiceberg.types import NestedField, StringType
schema = Schema(
NestedField(field_id=1, name="a", field_type=StringType(), required=True),
NestedField(field_id=2, name="b", field_type=StringType(), required=True),
NestedField(field_id=3, name="c", field_type=StringType(), required=False),
schema_id=1,
identifier_field_ids=[1],
)
bind_visitor = BindVisitor(schema=schema)
unbound_expression = …
```
> [Python] BindVisitor for binding a BooleanExpression to a Schema

- api/src/main/java/org/apache/iceberg/actions/ActionsProvider.java
- spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRewriteDataFilesProcedure.java
- spark/v3.2/spark/src/jmh/java/org/apache/iceberg/spark/action/IcebergSortCompactionBenchmark.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/SparkCachedTableCatalog.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/SparkTableCache.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/actions/BaseRewriteDataFilesSparkAction.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/actions/SparkActions.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/actions/SparkBinPackStrategy.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/actions/SparkSortStrategy.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/actions/SparkZOrderStrategy.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/procedures/RewriteDataFilesProcedure.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/IcebergSource.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/TestSparkCachedTableCatalog.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteDataFilesAction.java
- spark/v3.3/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRewriteDataFilesProcedure.java
- spark/v3.3/spark/src/jmh/java/org/apache/iceberg/spark/action/IcebergSortCompactionBenchmark.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/SparkCachedTableCatalog.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/SparkTableCache.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/actions/BaseRewriteDataFilesSparkAction.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/actions/SparkActions.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/actions/SparkBinPackStrategy.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/actions/SparkSortStrategy.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/actions/SparkZOrderStrategy.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/procedures/RewriteDataFilesProcedure.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/IcebergSource.java
- spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/TestSparkCachedTableCatalog.java
- spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteDataFilesAction.java
This PR adds a new internal Spark catalog capable of loading tables from a static table cache, which allows us to reliably load tables in actions without passing a fully quoted Spark identifier.
> Spark 3.3: Add Spark catalog for loading tables from cache

- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/procedures/RegisterTableProcedure.java
This PR renames output columns in `register_table` procedure for consistency with other procedures.
This procedure hasn't been released yet.
> Spark 3.3: Rename output columns in register_table procedure

- data/src/main/java/org/apache/iceberg/data/DeleteFilter.java
DeleteFilter initialize 'delete rows' multiple times  when call DeleteFilter#filter method multiple times,  This cause performance of MOR is very low in trino.
In my case, It spend 8 minutes when I query a table, after optimize it only spend 20 seconds.
> Make predicates of delete only initialize once

- core/src/main/java/org/apache/iceberg/MetadataTableUtils.java
- core/src/main/java/org/apache/iceberg/rest/RESTSessionCatalog.java
- core/src/test/java/org/apache/iceberg/catalog/CatalogTests.java
This fixes metadata table loading. Although the metadata table is correctly loaded, the `TableOperations` fails when it is first used because the path is based on the full table identifier (e.g. db.table.files) rather than the loaded table identifier (db.table). This fixes both the path and the table name.
> Core: Fix REST catalog metadata table loading.

- aws/src/main/java/org/apache/iceberg/aws/dynamodb/DynamoDbTableOperations.java
- aws/src/main/java/org/apache/iceberg/aws/glue/GlueTableOperations.java
- hive-metastore/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java
Any exception coming from the try-catch block will be swallowed and the user will only see the exception from the finally block.
Note that `cleanupMetadataAndUnlock()` is being called from a `finally` block.
It seems enough to just log the error but not throw an exception when
metadata cleanup failed.
> Don't throw from finally block

- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/procedures/RegisterTableProcedure.java
This is a change similar to #5253 but for Spark 3.2.
> Spark 3.2: Rename output columns in register_table procedure

- api/src/main/java/org/apache/iceberg/util/ExceptionUtil.java
The `runSafely` function gives an error prone warning for throwing from a finally block.
Originally, we fixed this via suppression in https://github.com/apache/iceberg/pull/5190, but I noticed this function was unused and so chose to deprecate it instead in https://github.com/apache/iceberg/pull/5205.
@rdblue wanted to keep the function, as it's tested and could be useful in the future.
So this PR:
- fixes the issue discovered in #5190 of throwing `failure` when it's null
- attempts to throw `failure` after adding `e` as a suppressed error when it's non-null
- adds the `@Finally` suppression to remove the error prone log from the build.
Warning that is logged on build:
```
iceberg/api/src/main/java/org/apache/iceberg/util/ExceptionUtil.java:124: warning: [Finally] If you return or throw …
```
> [API] Fix throwing null exception and add error prone suppression to runSafely functions

- aws/src/integration/java/org/apache/iceberg/aws/glue/TestGlueCatalogCommitFailure.java
- core/src/test/java/org/apache/iceberg/hadoop/TestHadoopCommits.java
- hive-metastore/src/test/java/org/apache/iceberg/hive/TestHiveCommitLocks.java
- hive-metastore/src/test/java/org/apache/iceberg/hive/TestHiveCommits.java
- versions.props
- upgrade junit5 to 5.8.2
- upgrade assertj to 3.23.1
- upgrade mockserver to 5.13.2
- upgrade mockito to 4.6.1
- org.mockito.Matchers class was removed
> Build: Upgrade test dependencies to latest version

- .github/workflows/api-binary-compatibility.yml
since https://github.com/apache/iceberg/pull/4851 a new workflow was added that did not use the upgraded versions
before:
```
~/code/iceberg$ rg --no-filename -o 'uses:.*$' .github | sort | uniq -c
9 uses: actions/cache@v3
17 uses: actions/checkout@v3
1 uses: actions/labeler@v4
1 uses: actions/setup-java@v1
12 uses: actions/setup-java@v3
2 uses: actions/setup-python@v3
1 uses: actions/upload-artifact@v2
9 uses: actions/upload-artifact@v3
```
after:
```
~/code/iceberg$ rg --no-filename -o 'uses:.*$' .github | sort | uniq -c
9 uses: actions/cache@v3
17 uses: actions/checkout@v3
1 uses: actions/labeler@v4
13 uses: actions/setup-java@v3
2 uses: actions/setup-python@v3
10 uses: actions/upload-artifact@v3
```
> Build: unify github action versions

- build.gradle
presently by default `gradle-git-properties` plugin add all the git properties as below : 
```
git.branch
git.build.host
git.build.user.email
git.build.user.name
git.build.version
git.closest.tag.commit.count
git.closest.tag.name
git.commit.id
git.commit.id.abbrev
git.commit.id.describe
git.commit.message.full
git.commit.message.short
git.commit.time
git.commit.user.email
git.commit.user.name
git.dirty
git.remote.origin.url
git.tags
git.total.commit.count
```
[[ref](https://github.com/n0mer/gradle-git-properties)]
This includes sensitive properties like `git.build.host` & `git.remote.origin.url`.
This changes avoid exposing all props, by only exposing the properties required by Iceberg Build Info.
----- 
Testing Done : 
Exsiting UT.
cc @rdblue @kbendick @nastra
> Build: Exclude unnecessary git properties from iceberg-build.properties

- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/SparkScanBuilder.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/SparkScanBuilder.java
This is a follow up to https://github.com/apache/iceberg/pull/5254. When filter conversion/bind expression fail, we will only log the error message instead of the whole stack trace.
> only log error message(not the stack trace) if filter conversion/bind expression fail

- dell/src/main/java/org/apache/iceberg/dell/DellClientFactory.java
- dell/src/main/java/org/apache/iceberg/dell/ecs/PropertiesSerDesUtil.java
1. Make `DellClientFactory` serializable
2. To avoid the NPE when reading the table/namespace object which doesn't have the version field.
> Dell: Fix bugs during documenting

- dev/stage-binaries.sh
Running `dev/stage-binaries.sh` for 0.14.0-rc1 initially failed because the Spark 3.2 project wasn't defined in `sparkVersions` when building the 2.13 binaries. This sets `sparkVersions` for the Scala 2.13 builds instead of relying on the default.
> Build: Fix Scala 2.13 builds in stage-binaries.sh

- dev/.rat-excludes
I hit this while verifying the 0.14.0-rc1 candidate.
It shouldn't fail the candidate since it is okay that the file doesn't have a license (it is generated metadata).
> Build: Add iceberg-build.properties to RAT excludes

- aws/src/main/java/org/apache/iceberg/aws/dynamodb/DynamoDbTableOperations.java
This resolves a bug that doesn't let the commit retry mechanism kick in. In the dynamo catalog, `checkMetadataLocation` can throw a CommitFailedException.  If this happens, it's caught in
```
} catch (RuntimeException persistFailure) {
```
and the commit state is repeatedly checked via `checkCommitStatus`. The only observable case is that checkCommitStatus fails and wraps the CommitFailedException into a CommitStateUnknownException. 
This PR catches explicit CommitFailedException (we know we didn't successfully commit) and bubbles it up to the more comprehensive retry logic that checks if the new commit touches partitions that have been recently modified. 
@jackye1995 would appreciate the review on this.
> AWS: Dynamo Catalog: Pass CommitFailedException up the stack without wrapping

- .baseline/copyright/copyright-header-java.txt
- baseline.gradle
- build.gradle
This PR is the first step towards automatic code formatting.
It configures Spotless to use the Google Java format and applies the copyright header automatically when running `./gradlew spotlessApply`.
Once this PR is merged, the next steps would be:
1. removing conflicting Checkstyle rules that are not in line with the Google format
2. formatting the entire code base via `./gradlew spotlessApply`
3. setting `enforceCheck` to `true` in https://github.com/apache/iceberg/blob/80318d8cfbeb0d96d0afc27c84bc3dbddde35344/baseline.gradle#L48
4. updating docs around the current Formatter usage and how to configure Eclipse/IntelliJ
> Build: Use Google Java Format for spotless

- aws/src/integration/java/org/apache/iceberg/aws/s3/TestS3FileIOIntegration.java
- aws/src/test/java/org/apache/iceberg/aws/s3/TestS3FileIO.java
Fix TestS3FileIO prefixDelete test and fix setup of S3 batch deletion tests. Sporadically the prefixDelete test fails with a 500 (see below). When debugging it looks appears as though for S3Mock there's some corruption of the file states when there's concurrent execution of deletes and lists. Still not entirely sure why this is, but serial execution of each of each of the "scale" prefix tests, leads to the test consistently passing. Though we really should be able to run these different scale tests in parallel without issue since the prefixes are isolated. The test fails during the validation step in the test where we list the prefix to validate the objects were deleted.
If this is truly a S3Mock issue (which debugging seems to point to), then for the prefix tests another way is just to …
> AWS: Reduce TestS3FileIO prefix test scale factors. Replace with S3FileIO integration tests.

- .baseline/checkstyle/checkstyle.xml
- api/src/test/java/org/apache/iceberg/expressions/TestExpressionBinding.java
- api/src/test/java/org/apache/iceberg/expressions/TestStringLiteralConversions.java
- api/src/test/java/org/apache/iceberg/transforms/TestResiduals.java
- api/src/test/java/org/apache/iceberg/types/TestTypeUtil.java
- arrow/src/test/java/org/apache/iceberg/arrow/vectorized/parquet/DecimalVectorUtilTest.java
- core/src/main/java/org/apache/iceberg/hadoop/HadoopMetricsContext.java
- data/src/test/java/org/apache/iceberg/data/avro/TestSingleMessageEncoding.java
- hive-metastore/src/test/java/org/apache/iceberg/hive/HiveTableTest.java
- pig/src/test/java/org/apache/iceberg/pig/SchemaUtilTest.java
- spark/v2.4/spark/src/test/java/org/apache/iceberg/examples/SchemaEvolutionTest.java
- spark/v2.4/spark/src/test/java/org/apache/iceberg/spark/source/TestSnapshotSelection.java
- spark/v3.0/spark/src/test/java/org/apache/iceberg/spark/source/TestSnapshotSelection.java
- spark/v3.1/spark/src/test/java/org/apache/iceberg/spark/source/TestSnapshotSelection.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/TestHadoopMetricsContextSerialization.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/source/TestSnapshotSelection.java
- spark/v3.3/spark/src/test/java/org/apache/iceberg/TestHadoopMetricsContextSerialization.java
- spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/source/TestSnapshotSelection.java
We should avoid usage of `@Test(expected = ...)` because it is not
always clear from where exactly an exception is thrown. We should rather
promote using `Assertions.assertThatThrownBy(...).isInstanceOf(...).hasMessage(...)`
as that makes sure that we are in fact getting the right exception with
the appropriate error message.
> Prevent usage of @Test(expected = ...) and change existing tests

- api/src/main/java/org/apache/iceberg/io/CloseableIterable.java
- api/src/test/java/org/apache/iceberg/io/TestCloseableIterable.java
While working on Scan reporting (#5268) I noticed that this entire chain https://github.com/apache/iceberg/blob/eff879daa492641ac8bc829e7c4625dcdfac05fa/core/src/main/java/org/apache/iceberg/ManifestGroup.java#L218-L237 would be evaluated twice.
It turns out we eventually use `CloseableIterable.concat` with those
`CloseableIterables` in
https://github.com/apache/iceberg/blob/eff879daa492641ac8bc829e7c4625dcdfac05fa/core/src/main/java/org/apache/iceberg/ManifestGroup.java#L198.
When `CloseableIterable.concat` would check for emptyness via
```
if (!iterables.hasNext()) {
return empty();
}
```
it would actually evaluate the first chain of Iterables twice.
> API: CloseableIterable.concat evaluates first item twice

- api/src/main/java/org/apache/iceberg/metrics/DefaultMetricsContext.java
- api/src/main/java/org/apache/iceberg/metrics/DefaultTimer.java
- api/src/main/java/org/apache/iceberg/metrics/IntCounter.java
- api/src/main/java/org/apache/iceberg/metrics/LongCounter.java
- api/src/main/java/org/apache/iceberg/metrics/MetricsContext.java
- api/src/main/java/org/apache/iceberg/metrics/Timer.java
- api/src/test/java/org/apache/iceberg/metrics/TestDefaultMetricsContext.java
- api/src/test/java/org/apache/iceberg/metrics/TestDefaultTimer.java
- bundled-guava/src/main/java/org/apache/iceberg/GuavaClasses.java
The idea here is that a `DefaultMetricsContext` can be used with native
Java Counters/Timers to measure things.
Additionally, this is introducing an API and a default implementation
for a Timer, which can be used to measure execution time.
> API: Introduce DefaultMetricsContext and Timer interface

- core/src/main/java/org/apache/iceberg/SchemaParser.java
- core/src/test/java/org/apache/iceberg/rest/responses/TestLoadTableResponse.java
- core/src/test/resources/TableMetadataV1MissingSchemaType.json
I got this when playing around with the rest API.
> Java: Catch NPE if the type isn't set

- open-api/rest-catalog-open-api.yaml
These fields are read/written by the Java reference implementation:
https://github.com/apache/iceberg/blob/master/core/src/main/java/org/apache/iceberg/SnapshotParser.java
And are part of the spec as well: https://iceberg.apache.org/spec/#snapshots
> Spec: Add sequence-number and parent-snapshot-id

- build.gradle
We don't use `release-base-` anymore for never released versions, so currently `./gradlew printVersion` shows `0.14.0-SNAPSHOT`. This will now correctly print the SNAPSHOT version:
```
$ ./gradlew printVersion
> Task :printVersion
0.15.0-SNAPSHOT
```
> Build: Use 'apache-iceberg-' tag prefix to figure out SNAPSHOT version

- .github/dependabot.yml
Avoid me having to bump the versions once a while: https://github.com/apache/iceberg/pull/5325
Dependabot is much better at this, and will also check for CVEs and such.
Maybe Python is nice to give this a try.
cc @nastra
> Python: Add dependabot for keeping the dependencies up to date

- spark/v3.0/spark/src/main/java/org/apache/iceberg/spark/Spark3Util.java
- spark/v3.0/spark/src/test/java/org/apache/iceberg/spark/sql/TestCreateTable.java
- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/Spark3Util.java
- spark/v3.1/spark/src/test/java/org/apache/iceberg/spark/sql/TestCreateTable.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/Spark3Util.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/sql/TestCreateTable.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/Spark3Util.java
- spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/sql/TestCreateTable.java
Transform is not supported for upper case, otherwise throw SQLException as follow:
```
java.sql.SQLException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.UnsupportedOperationException: Transform is not supported: HOURS(timestamp_)
at org.apache.iceberg.spark.Spark3Util.toPartitionSpec(Spark3Util.java:423)
at org.apache.iceberg.spark.SparkCatalog.createTable(SparkCatalog.java:156)
at org.apache.iceberg.spark.SparkCatalog.createTable(SparkCatalog.java:98)
at org.apache.iceberg.spark.SparkSessionCatalog.createTable(SparkSessionCatalog.java:139)
at org.apache.spark.sql.execution.datasources.v2.CreateTableExec.run(CreateTableExec.scala:41)
```
Since Spark side never check upper or lower case and SQL parse is ok,  we could ignore case for iceberg side.
> Ignore case for partition transform

- core/src/main/java/org/apache/iceberg/FindFiles.java
- core/src/main/java/org/apache/iceberg/util/DateTimeUtil.java
- core/src/test/java/org/apache/iceberg/util/TestDateTimeUtil.java
- flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/source/enumerator/TestContinuousSplitPlannerImpl.java
- flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/source/enumerator/TestContinuousSplitPlannerImplStartStrategy.java
- flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/source/enumerator/TestContinuousSplitPlannerImpl.java
- flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/source/enumerator/TestContinuousSplitPlannerImplStartStrategy.java
This should make it fairly clear that all timestamps are in UTC.
Additionally, this makes also sure that a timestamp string can be parsed
by `ZonedDateTime.parse(timestamp)`.
fixes #5321
> Core: Print DateTime strings always with +00:00 Zone offset

- api/src/main/java/org/apache/iceberg/metrics/IntCounter.java
- api/src/main/java/org/apache/iceberg/metrics/LongCounter.java
- api/src/main/java/org/apache/iceberg/metrics/MetricsContext.java
- api/src/test/java/org/apache/iceberg/metrics/TestDefaultMetricsContext.java
- flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/source/reader/ReaderMetricsContext.java
- flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/source/reader/ReaderMetricsContext.java
The rationale behind this change is that usually a Counter should always
be able to report the actual count it is counting. The reason
`count()` was made `Optional` initially is because in the case of Hadoop
we are reporting the count to Hadoop's file system statistics and don't
necessarily want to report the count in that case.
> API: Deprecate Counter#count() / Add Counter#value() 

- arrow/src/main/java/org/apache/iceberg/arrow/vectorized/VectorHolder.java
- arrow/src/main/java/org/apache/iceberg/arrow/vectorized/VectorizedArrowReader.java
- arrow/src/main/java/org/apache/iceberg/arrow/vectorized/VectorizedReaderBuilder.java
- spark/v2.4/spark/src/test/java/org/apache/iceberg/spark/data/TestSparkParquetReadMetadataColumns.java
- spark/v3.0/spark/src/test/java/org/apache/iceberg/spark/data/TestSparkParquetReadMetadataColumns.java
- spark/v3.1/spark/src/test/java/org/apache/iceberg/spark/data/TestSparkParquetReadMetadataColumns.java
- spark/v3.2/spark/src/jmh/java/org/apache/iceberg/spark/source/IcebergSourceBenchmark.java
- spark/v3.2/spark/src/jmh/java/org/apache/iceberg/spark/source/IcebergSourceDeleteBenchmark.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/data/vectorized/ColumnVectorBuilder.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/data/vectorized/ColumnarBatchReader.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/data/vectorized/DeletedColumnVector.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/data/vectorized/DeletedMetaColumnVector.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/data/vectorized/IcebergArrowColumnVector.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/data/TestSparkParquetReadMetadataColumns.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkReaderDeletes.java
- spark/v3.3/spark/src/jmh/java/org/apache/iceberg/spark/source/IcebergSourceBenchmark.java
- spark/v3.3/spark/src/jmh/java/org/apache/iceberg/spark/source/IcebergSourceDeleteBenchmark.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/data/vectorized/ColumnVectorBuilder.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/data/vectorized/ColumnarBatchReader.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/data/vectorized/DeletedColumnVector.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/data/vectorized/IcebergArrowColumnVector.java
- spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/data/TestSparkParquetReadMetadataColumns.java
- spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkReaderDeletes.java
The vectorized version of #4683.
cc @aokolnychyi @szehon-ho @RussellSpitzer @chenjunjiedada @stevenzwu @Reo-LEI @hameizi @singhpk234 @rajarshisarkar @kbendick @rdblue
Benchmarks for pos delete and eq delete
> Core: Support _deleted metadata column in vectorized read

- parquet/src/test/java/org/apache/iceberg/parquet/TestBloomRowGroupFilter.java
I saw bloom filter test `Assert.assertFalse("Should not read: ...", shouldRead)` failed with false positive.
This PR is to make the bloom filter test less flaky by taking consideration of fpp.
> Improve bloom filter test

- aws/src/test/java/org/apache/iceberg/aws/s3/TestS3OutputStream.java
current implementation only verifies mock invocation on an exception in catch block. This is flaky as the test won't verify if there are no failures, but we want to make sure the calls are made in the test.
> unit test should always verify mock invocation 

- aws/src/main/java/org/apache/iceberg/aws/AwsProperties.java
Noticed this error prone warning when checking my work for warnings.
This fixes  the malformed JavaDoc on the `GLUE_CATALOG_ENDPOINT` configuration constant.
```
> Task :iceberg-aws:compileJava
/Users/kylebendickson/repos/iceberg/aws/src/main/java/org/apache/iceberg/aws/AwsProperties.java:130: warning: [AlmostJavadoc] This comment contains Javadoc or HTML tags, but isn't started with a double asterisk (/**); is it meant to be Javadoc?
public static final String GLUE_CATALOG_ENDPOINT = "glue.endpoint";
^
(see https://errorprone.info/bugpattern/AlmostJavadoc)
Did you mean '/**'?
```
> AWS - Fix ErrorProne warning of malformed Javadoc

- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/BaseBatchReader.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/BaseReader.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/BaseRowReader.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/BatchDataReader.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/EqualityDeleteRowReader.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/RowDataReader.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/source/TestBaseReader.java
Cherry-picked from d7b1a874677b3dc58c20656d9b06c571fe0a475a. This is the same change as #5248 applying to the module Spark 3.2.
@aokolnychyi @szehon-ho  @RussellSpitzer
> Spark 3.2: Support different task types in readers

- nessie/src/test/java/org/apache/iceberg/nessie/BaseTestIceberg.java
- nessie/src/test/java/org/apache/iceberg/nessie/TestNessieCatalog.java
Nessie PR https://github.com/projectnessie/nessie/pull/4547 prevents the deletion of the default branch.
This PR updates the tests to re-assign the default branch instead of deleting it.
> Nessie: Do not delete default branch in tests

- api/src/main/java/org/apache/iceberg/AddedRowsScanTask.java
- api/src/main/java/org/apache/iceberg/DeletedDataFileScanTask.java
- api/src/main/java/org/apache/iceberg/DeletedRowsScanTask.java
- core/src/main/java/org/apache/iceberg/BaseAddedRowsScanTask.java
- core/src/main/java/org/apache/iceberg/BaseChangelogContentScanTask.java
- core/src/main/java/org/apache/iceberg/BaseContentScanTask.java
- core/src/main/java/org/apache/iceberg/BaseDeletedDataFileScanTask.java
- core/src/main/java/org/apache/iceberg/BaseDeletedRowsScanTask.java
- core/src/main/java/org/apache/iceberg/BaseFileScanTask.java
- core/src/main/java/org/apache/iceberg/FixedSizeSplitScanTaskIterator.java
- core/src/main/java/org/apache/iceberg/OffsetsAwareSplitScanTaskIterator.java
- core/src/main/java/org/apache/iceberg/SplitScanTaskIterator.java
- core/src/test/java/org/apache/iceberg/TestFixedSizeSplitScanTaskIterator.java
- core/src/test/java/org/apache/iceberg/TestOffsetsBasedSplitScanTaskIterator.java
This PR adds implementations for changelog tasks to be used in the changelog scan.
This PR currently relies on existing tests. More tests will come with the scan implementation.
> Core: Add base implementations for changelog tasks

- aws/src/integration/java/org/apache/iceberg/aws/s3/TestS3FileIOIntegration.java
Fix scale prefix in listPrefix test. In https://github.com/apache/iceberg/pull/5289 I made a change to fix some flaky tests and added some integration tests, but in the listPrefix integ test, the incorrect prefix is being used. For the prefix list integ test, all the objects are created under s3:://<test_bucket>/prefix-list-test/scale/. The test fails during S3 URI creation.  After fixing this, the test is passing.
> AWS: Fix S3FileIO#prefixList integration test

- spark/v3.3/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRemoveOrphanFilesProcedure.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/actions/DeleteOrphanFilesSparkAction.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/actions/SetAccumulator.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/procedures/RemoveOrphanFilesProcedure.java
- spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/actions/TestRemoveOrphanFilesAction.java
Copying over the changes from 3.2 to 3.3
https://github.com/apache/iceberg/issues/4346
> Spark 3.3: Add prefix mismatch mode for deleting orphan files

- python/pyiceberg/expressions/base.py
- python/pyiceberg/expressions/literals.py
- python/tests/expressions/test_expressions_base.py
This refactors unary and set expressions to use base classes. In addition, this updates binding to produce `AlwaysTrue()` or `AlwaysFalse()` values based on the bound type. For example, `IsNull(a)` when bound to a required field a will produce `AlwaysFalse()` because the value is required.
This also adds missing tests.
> Python: Refactor unary and set expressions

- .github/workflows/stale.yml
This closes issue https://github.com/apache/iceberg/issues/4948 
Adds a Github Action to mark issues as `stale` after the configured period of time (180 days), leaving the designated comment on those issues, and then closing them after 14 days if no activity occurs after that.
Issues can be marked as `not-stale` so that they will not be considered by the stale bot action. We'll need to create this label (whatever we wind up choosing).
Github Stale Action Docs / Configuration Options: https://github.com/actions/stale
Inspired By Airflow's usage of stale action: https://github.com/apache/airflow/blob/main/.github/workflows/stale.yml
cc @danielcweeks @Fokko
> Infra - Add a GH Action to Mark and Close Stale Issues

- docs/flink-getting-started.md
- flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/FlinkDynamicTableFactory.java
- flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/IcebergTableSink.java
- flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/TestFlinkUpsert.java
Support write options in the in-line insert SQL comments:
```sql
insert into talbeName  /*+ OPTIONS('upsert-enabled'='true')*/ 
select 
…………
```
For properties like upsert, it is not recommended to enable it in the table props. Configuring it in table props is a bit strange.
> Flink: Support write options in the in-line insert SQL comments

- aws/src/main/java/org/apache/iceberg/aws/s3/S3OutputStream.java
- aws/src/test/java/org/apache/iceberg/aws/s3/TestS3OutputStream.java
Presently whenever a failure is observed in any of the completableFutures in `uploadParts()`, it causes further completable futures fail with `FileNotFoundException`, when it tries to create a request for it using `RequestBody.fromFile(file)`, as all the stagings files deleted as part of `abortUpload` which is called on failure of first completableFuture.
https://github.com/apache/iceberg/blob/7a92bf5e31a995c61dc598d2a36f598d5c120756/aws/src/main/java/org/apache/iceberg/aws/s3/S3OutputStream.java#L306
I think this is what was also highlighted in @stevenzwu 's observation here (https://github.com/apache/iceberg/issues/4168#issuecomment-1123025380)
This change attempts : 
* To avoid unnecessary deletes being called for all staging files on every `completableFutures` which fail due to …
> AWS: Call abortUpload only once when any of the completable future fails

- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/BaseCatalog.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/SparkSessionCatalog.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/functions/IcebergVersionFunction.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/functions/SparkFunctions.java
- spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/TestFunctionCatalog.java
This PR stems from https://github.com/apache/iceberg/pull/5305 and covers just the `FunctionCatalog`
This allows users of `SparkCatalog` and `SparkSessionCatalog` to use functions (such as the `iceberg_version` function added here) without having to register it as a UDF.
The v2 functions also benefit from code generation and are significantly more efficient. For instance, this registers a logical plan of `project "0.15.0-SNAPSHOT" as value`).
All Iceberg functions that we register into the function catalog are accessible when used with an Iceberg spark catalog and:
1. No namespace is referenced - the storage partitioned joins implementation requires this.
e.g. `my_catalog.iceberg_version()`. 
2. The `system` namespace is referenced, to match called procedure syntax. 
** Note ** The …
> Spark - Add Spark FunctionCatalog

- python/pyiceberg/expressions/base.py
- python/tests/expressions/test_expressions_base.py
This makes some minor changes to the expression hierarchy, mostly making the classes only implement what they need to. For example, `Bound` and `Unbound` don't need to carry a bound type. A `Term` has an associated generic type instead. This also:
* Refactors And, Or, and Not to be data classes
* Adds a default for `case_sensitive` everywhere
> Python: Refactor expression hierarchy

- api/src/main/java/org/apache/iceberg/types/TypeUtil.java
- api/src/test/java/org/apache/iceberg/types/TestTypeUtil.java
Starting with schema:
```
{A: 1, B: 2, C:3}
```
And then a user drops C, resulting in:
```
{A: 1, B: 2} Highest Field ID = 3
```
Then do a mergeSchema with
```
{A, B, D}
```
This will end up assigning (highestId({A:1, B:2}) + 1) to D (3)
The table would then have schemas :
```
Schemas {
{A: 1, B: 2, C: 3}
{A: 1, B: 2}
{A: 1, B :2, D: 3}
}
```
> API: Assign the right field ids when merging schema, #5394

- python/pyiceberg/catalog/rest.py
- python/pyiceberg/exceptions.py
- python/tests/catalog/test_rest.py
Some small comments pending from: https://github.com/apache/iceberg/pull/5287
> Python: Follow up on REST comments

- aws/src/integration/java/org/apache/iceberg/aws/s3/TestS3FileIOIntegration.java
Right now, running s3 file io integration test multiple times will lead to failures in expectations of the testPrefixList. This is because the cleanup which happens in AfterClass only cleans up under s3://bucket/uuid-prefix where uuid prefix is the random uuid created on each run of the test class. The testPrefixList is creating objects in s3://bucket/prefix-list-test. We should actually put this in s3://bucket/uuid-prefix/prefix-list-test so that After class will properly clean this up, and we can run multiple runs of the integ test successfully.
Going forward, we will also want https://github.com/apache/iceberg/pull/4855 so that issues like this can be caught earlier on. I tested this by running the AWS integ tests multiple times on a pre-existing bucket I used for iceberg-aws …
> AWS: S3FileIo Integration test include UUID prefix in Prefix integration tests

- python/pyiceberg/catalog/base.py
- python/pyiceberg/catalog/rest.py
- python/pyiceberg/exceptions.py
- python/tests/catalog/test_base.py
- python/tests/catalog/test_rest.py
And be more specific in the NamespaceAlreadyExistsError
> Python: Cleanup catalog docstring

- python/pyiceberg/catalog/rest.py
- python/pyiceberg/exceptions.py
- python/tests/catalog/test_rest.py
The `/token` endpoint can return an OAuthErrorResponse as part of a HTTP400.
https://github.com/apache/iceberg/blob/master/open-api/rest-catalog-open-api.yaml#L1675-L1695
This has a different structure as the other error responses:
```json
{"error": "invalid_client", "error_description": "Credentials for key invalid_key do not match"}
```
Instead of:
```json
{
"error": {
"message": "Invalid client ID: abc",
"type": "BadCredentialsException",
"code": 401,
}
}
```
Therefore we check this and format the exception before throwing it
> Python: Handle OAuthErrorResponse properly

- .github/workflows/stale.yml
Now that the GH Action for marking issues as stale has been merged in https://github.com/apache/iceberg/pull/4949 and we've seen it work, we should upgrade it to the latest version to pick up some bug fixes.
Upgrades from v4 to v5.1.1 (the latest version found under releases https://github.com/actions/stale).
This will make it more efficient as it will not double check `stale` issues accidentally, and our limit of number of issues to consider in a run will be the value set (and not some fraction of it).
> Infra - Upgrade Stale GH Action to Latest 5.1.1

- api/src/main/java/org/apache/iceberg/io/CloseableIterable.java
- api/src/main/java/org/apache/iceberg/io/CloseableIterator.java
- api/src/main/java/org/apache/iceberg/metrics/IntCounter.java
- api/src/main/java/org/apache/iceberg/metrics/LoggingScanReporter.java
- api/src/main/java/org/apache/iceberg/metrics/LongCounter.java
- api/src/main/java/org/apache/iceberg/metrics/MetricsContext.java
- api/src/main/java/org/apache/iceberg/metrics/ScanReport.java
- api/src/main/java/org/apache/iceberg/metrics/ScanReporter.java
- api/src/test/java/org/apache/iceberg/io/TestCloseableIterable.java
- api/src/test/java/org/apache/iceberg/metrics/TestScanReport.java
- core/src/main/java/org/apache/iceberg/BaseTable.java
- core/src/main/java/org/apache/iceberg/BaseTableScan.java
- core/src/main/java/org/apache/iceberg/DataTableScan.java
- core/src/main/java/org/apache/iceberg/DeleteFileIndex.java
- core/src/main/java/org/apache/iceberg/ManifestGroup.java
- core/src/main/java/org/apache/iceberg/ManifestReader.java
- core/src/main/java/org/apache/iceberg/TableScanContext.java
- core/src/main/java/org/apache/iceberg/rest/RESTSessionCatalog.java
- core/src/test/java/org/apache/iceberg/TestTables.java
- data/src/test/java/org/apache/iceberg/TestScanPlanningAndReporting.java
The idea here is that we collect metrics during Table scans so that we
can better understand what exactly happens during a Table scan.
This is just an initial implementation that gathers/records a few metrics. The idea is to get early feedback on this approach.
* a `ScanReport` that contains all relevant metrics from a Scan
* a `ScanReporter` interface that can be used to collect and report different metrics during a Table scant. Engines can implement this API to customize how a `ScanReport` is being reported
* a `LoggingScanReporter` is introduced that logs a `ScanReport` to the log file. We can think about defaulting to that one or using a **no-op** scan reporter
* a new Catalog Property `scan-reporter-impl` is introduced, allowing a Catalog to specify which `ScanReporter` to use
* a …
> API/Core: Initial Table Scan Reporting support

- api/src/main/java/org/apache/iceberg/exceptions/CommitStateUnknownException.java
- hive-metastore/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java
- hive-metastore/src/test/java/org/apache/iceberg/hive/HiveMetastoreTest.java
- hive-metastore/src/test/java/org/apache/iceberg/hive/TestHiveCommitLocks.java
When using Hive Metastore catalog, it is possible that longer transactions can take longer than [transaction timeout](https://cwiki.apache.org/confluence/display/Hive/Configuration+Properties#ConfigurationProperties-hive.txn.timeout) of the Hive Metastore (hive.txn.timeout or metastore.txn.timeout in the newer versions). In those cases, concurrent transactions can overwrite each other leading to data corruption. This change fixes concurrent transactions overwriting commits by adding hive lock heartbeats.
> Hive: Fix concurrent transactions overwriting commits by adding hive lock heartbeats.

- hive-metastore/src/main/java/org/apache/iceberg/hive/HiveCatalog.java
- hive-metastore/src/test/java/org/apache/iceberg/hive/TestHiveCatalog.java
While testing locally with a Hive metastore with a Minio backend
```
spark-sql> create database nyc;
22/08/01 08:15:19 ERROR SparkSQLDriver: Failed in [create database nyc]
java.lang.IllegalArgumentException: java.net.URISyntaxException: Relative path in absolute URI: s3://warehousenyc
at org.apache.hadoop.fs.Path.initialize(Path.java:263)
at org.apache.hadoop.fs.Path.<init>(Path.java:161)
at org.apache.hadoop.fs.Path.<init>(Path.java:119)
at org.apache.iceberg.hive.HiveCatalog.convertToDatabase(HiveCatalog.java:510)
at org.apache.iceberg.hive.HiveCatalog.lambda$createNamespace$8(HiveCatalog.java:264)
at org.apache.iceberg.ClientPoolImpl.run(ClientPoolImpl.java:58)
at org.apache.iceberg.ClientPoolImpl.run(ClientPoolImpl.java:51)
at …
```
> Hive: Hadoop Path fails on s3 endpoint

- python/pyiceberg/catalog/rest.py
If it isn't caught, we still want to know what the error code was
> Python: Add http status code to RESTError

- python/pyiceberg/io/base.py
- python/pyiceberg/io/memory.py
- python/pyiceberg/serializers.py
- python/tests/avro/test_decoder.py
This way we can nicely use context managers:
```python
f = PyArrowInputFile(..).open()
f.read()
f.close()
```
turns into:
```python
with PyArrowInputFile('s3://').open() as f:
f.read()
```
This way we don't forget to close any files. This is very easy to do and was actually happening when reading the metadata.
> Python: Require `__enter__` and `__exit__` on `{Input,Output}Stream`

- .github/dependabot.yml
This will check the version of the Github Actions versions each week, so we don't have to do it by hand :)
> CI: Enable dependabot for Github Actions
