apache/iceberg

- .github/dependabot.yml
Even though dependabot isn't currently able to pick up the dependencies defined in `versions.props`, it can be at least used for Gradle plugin updates and any other dependencies that are defined in the default gradle files.
> CI: Enable dependabot for gradle

- aws/src/integration/java/org/apache/iceberg/aws/lakeformation/TestLakeFormationMetadataOperations.java
Cleans up a warning I see in the build for the AWS integ tests:
```
/Users/jahamogh/workplace/iceberg-jahamogh/iceberg/aws/src/integration/java/org/apache/iceberg/aws/lakeformation/TestLakeFormationMetadataOperations.java:244: warning: [LambdaMethodReference] Lambda should be a method reference
() -> updateProperties.commit());
```
^
> AWS: Cleanup warning about Lambda should be method reference

- core/src/main/java/org/apache/iceberg/AllEntriesTable.java
- core/src/main/java/org/apache/iceberg/BaseEntriesTable.java
- core/src/main/java/org/apache/iceberg/ManifestEntriesTable.java
- core/src/test/java/org/apache/iceberg/TestMetadataTableFilters.java
This implements partition filter pushdown for 'entries' and 'all_entries' table. This makes a base class for both and then re-uses the partition filter pushdown logic of 'files' table when doing planning.
> Core: Partition filter pushdown for entries table

- python/pyiceberg/catalog/rest.py
- python/tests/catalog/test_rest.py
Tables without a namespace are not allowed.
In the case when you provide an empty identifier, we want to catch
that right away before reaching out to the REST catalog.
> Python: Checks on REST catalog table/namespace identifiers

- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/actions/BaseSparkAction.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/actions/DeleteOrphanFilesSparkAction.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/actions/DeleteReachableFilesSparkAction.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/actions/ExpireSnapshotsSparkAction.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/actions/FileInfo.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/actions/ManifestFileBean.java
- spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/actions/TestExpireSnapshotsAction.java
This PR switches `BaseSparkAction` to use typed beans instead of generic `Row`. This allows us to avoid unreliable index-based access and enables having more typed operations. In a follow-up PR, I will consume these changes in other actions.
This change does not affect the performance as we were previously using `Row` that required converting values from the internal Spark representation anyway.
> Spark 3.3: Use typed beans in BaseSparkAction

- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/actions/BaseSparkAction.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/actions/DeleteOrphanFilesSparkAction.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/actions/DeleteReachableFilesSparkAction.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/actions/ExpireSnapshotsSparkAction.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/actions/FileInfo.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/actions/ManifestFileBean.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/actions/TestExpireSnapshotsAction.java
This is a cherry-pick of PR #5469 to Spark 3.2.
> Spark 3.2: Use typed beans in BaseSparkAction

- api/src/main/java/org/apache/iceberg/io/SupportsBulkOperations.java
- aws/src/integration/java/org/apache/iceberg/aws/s3/TestS3FileIOIntegration.java
- aws/src/main/java/org/apache/iceberg/aws/s3/S3FileIO.java
- aws/src/test/java/org/apache/iceberg/aws/s3/TestS3FileIO.java
Update the S3FileIO to lazily load batches and use the existing deletion threadpool for performing concurrent S3#RemoveObjects calls. 
This will be used in subsequent PRs for performing bulk deletes in procedures like removing orphan files, snapshot expiration and purging the data, manifests, old metadata files during table drop.
> AWS: Use executor service by default when performing batch deletion of files

- api/src/main/java/org/apache/iceberg/transforms/Truncate.java
- api/src/main/java/org/apache/iceberg/util/BinaryUtil.java
- api/src/main/java/org/apache/iceberg/util/TruncateUtil.java
- api/src/main/java/org/apache/iceberg/util/UnicodeUtil.java
- core/src/test/java/org/apache/iceberg/util/TestTruncateUtil.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/functions/SparkFunctions.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/functions/TruncateFunction.java
- spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/sql/TestSparkTruncateFunction.java
This is an offshoot of https://github.com/apache/iceberg/pull/5305 and partially closes https://github.com/apache/iceberg/issues/5349.
Adds a `system.truncate` function that can be used in Spark SQL, as well as can be used as a `FunctionCatalog` function that can be turned into a transform for storage partitioned joins.
This also breaks the definition of `Truncate` out into utility functions inside of `TruncateUtil`. Because different usages validate input at different times, all of the functions in `TruncateUtil` do not validate their input and instead assume that the input is validated by the calling code. This allows for the `Truncate` transforms to validate their width one time (on instantiation), and for the Spark `truncate` function to skip input validation for faster generated …
> Spark: Support truncate in FunctionCatalog

- spark/v3.1/spark/src/jmh/java/org/apache/iceberg/spark/source/IcebergSourceBenchmark.java
- spark/v3.1/spark/src/jmh/java/org/apache/iceberg/spark/source/IcebergSourceDeleteBenchmark.java
- spark/v3.1/spark/src/jmh/java/org/apache/iceberg/spark/source/parquet/IcebergSourceParquetDeleteBenchmark.java
- spark/v3.1/spark/src/jmh/java/org/apache/iceberg/spark/source/parquet/IcebergSourceParquetMultiDeleteFileBenchmark.java
- spark/v3.1/spark/src/jmh/java/org/apache/iceberg/spark/source/parquet/IcebergSourceParquetWithUnrelatedDeleteBenchmark.java
- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/data/vectorized/ColumnVectorWithFilter.java
- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/data/vectorized/ColumnarBatchReader.java
- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/data/vectorized/IcebergArrowColumnVector.java
- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/data/vectorized/VectorizedSparkParquetReaders.java
- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/source/BaseDataReader.java
- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/source/BatchDataReader.java
- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/source/SparkBatchScan.java
- spark/v3.1/spark/src/test/java/org/apache/iceberg/spark/data/TestSparkParquetReadMetadataColumns.java
- spark/v3.1/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkReaderDeletes.java
Split from https://github.com/apache/iceberg/pull/5479
There is a dependency between them. Otherwise, it will not compile properly.
> Spark 3.1:Port #3287  #4381 #3535 #4419 to Spark 3.1

- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/source/SparkMetadataColumn.java
- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/source/SparkTable.java
- spark/v3.1/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkCatalog.java
- spark/v3.1/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkMetadataColumns.java
Spark 3.1:Port #3373 to Spark 3.1
Split from #5479
> Spark 3.1:Port #3373 to Spark 3.1

- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/functions/SparkFunctions.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/functions/TruncateFunction.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/sql/TestSparkTruncateFunction.java
Backports #5431 to Spark 3.2, adding the `truncate` transform as a v2 Spark function.
> Spark 3.2: Support truncate in FunctionCatalog

- core/src/main/java/org/apache/iceberg/SetSnapshotOperation.java
- core/src/test/java/org/apache/iceberg/TestSnapshotManager.java
As discussed in #5507 SetSnapshotOperation currently doesn't commit the operation if the metadata is unchanged. Since this is used in a transaction, it can result in failure of committing the whole transaction as the `hasLastOpCommited` was not advanced.
I propose we commit such empty operations, as the overall transaction commit will result in a no-op anyway in these cases.
cc: @kbendick @amogh-jahagirdar
> SetSnapshotOperation should commit empty operations too

- aws/src/main/java/org/apache/iceberg/aws/AwsProperties.java
- aws/src/main/java/org/apache/iceberg/aws/s3/S3FileIO.java
Adding support for Initializing S3 client during the S3FileIO initialization. This is needed to deal with a scenario in which S3 files need to be deleted after table has been dropped when LakeFormation is enabled.
> AWS: Support preload S3 client mode for S3FileIO

- core/src/test/java/org/apache/iceberg/avro/TestAvroNameMapping.java
Using recursive type check to ensure every element in the map has desired type when casting
> Build: Resolve unchecked Map type cast in TestAvroNameMapping

- python/pyiceberg/serializers.py
- python/pyiceberg/typedef.py
- python/pyproject.toml
Noticed this while coding. Reduces visual noise
> Python: Remove unused `# type: ignore`

- core/src/main/java/org/apache/iceberg/util/JsonUtil.java
- core/src/test/java/org/apache/iceberg/TestMetadataUpdateParser.java
- core/src/test/java/org/apache/iceberg/TestSnapshotRefParser.java
- core/src/test/java/org/apache/iceberg/catalog/TestTableIdentifierParser.java
- core/src/test/java/org/apache/iceberg/rest/requests/TestRenameTableRequest.java
- core/src/test/java/org/apache/iceberg/rest/responses/TestOAuthTokenResponse.java
Sometimes one has to read the error message twice to figure out which
property name was affected, thus highlighting the property name in the
error message should make this clearer.
> Core: Put property names at the end in JsonUtil error messages 

- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/Spark3Util.java
- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/SparkConfParser.java
- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/SparkReadConf.java
- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/source/SparkBatchQueryScan.java
- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/source/SparkBatchScan.java
- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/source/SparkFilesScan.java
- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/source/SparkFilesScanBuilder.java
- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/source/SparkMergeScan.java
- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/source/SparkScanBuilder.java
Spark 3.1:Port #3505 to Spark 3.1
Split from #5479, after #5501
> Spark 3.1:Port #3505 to Spark 3.1

- flink/v1.13/flink/src/main/java/org/apache/iceberg/flink/data/FlinkOrcWriters.java
In the TimestampTz ORC writer, we are intentionally accessing _just_ the nanoseconds of the `Instant` method, and not trying to get the whole instant value in nanoseconds.
Additionally, we are storing the time in epoch millis, which is correct for timestamptz.
So we should suppress the warning `JavaInstantGetSecondsGetNanos` when storing the `cv.nanos` area.
This matches the code in Flink 1.14 exactly. https://github.com/apache/iceberg/blob/c965af5d489b4acdaef9267fd98fa845393f23bc/flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/data/FlinkOrcWriters.java#L144-L157
> Flink - Suppress Nanosecond Warning for TimestampTz ORC writer

- aws/src/main/java/org/apache/iceberg/aws/AwsClientFactories.java
- aws/src/main/java/org/apache/iceberg/aws/AwsProperties.java
- docs/aws.md
Compiled iceberg-spark-runtime-3.1 and tested on Glue 3.0. The job is able to read from a DEMO S3 bucket into an S3 bucket that lives in my account. The DEMO bucket is from this blog: https://aws.amazon.com/blogs/big-data/build-an-apache-iceberg-data-lake-using-amazon-athena-amazon-emr-and-aws-glue/
My Spark job used during the testing is listed below.
```
import com.amazonaws.services.glue.GlueContext
import org.apache.spark.SparkContext
import org.apache.spark.sql.SparkSession
object IcebergSparkSQL {
def main(sysArgs: Array[String]) {
val sparkContext: SparkContext = new SparkContext()
val spark: SparkSession = SparkSession.builder.
config("spark.sql.catalog.demo", "org.apache.iceberg.spark.SparkCatalog").
config("spark.sql.catalog.demo.warehouse", …
```
> Add s3.acceleration-enbled flag to AwsProperties

- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/actions/BaseSparkAction.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/actions/DeleteOrphanFilesSparkAction.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/actions/ExpireSnapshotsSparkAction.java
- spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/actions/TestRemoveOrphanFilesAction.java
This PR reduces the serialization in `DeleteOrphanFilesSparkAction`.
> Spark 3.3: Reduce serialization in DeleteOrphanFilesSparkAction

- python/tests/table/test_refs.py
It was showing as:
```python
SnapshotRef(
snapshot_id=3051729675574597004,
snapshot_ref_type=<SnapshotRefType.TAG: 'tag'>,
min_snapshots_to_keep=None,
max_snapshot_age_ms=None,
max_ref_age_ms=10000000
)
```
> Python: Implement proper `__repr__` for SnapshotRefType

- python/pyiceberg/table/snapshots.py
- python/tests/table/test_snapshots.py
It would look like:
```python
Snapshot(
snapshot_id=25,
parent_snapshot_id=19,
sequence_number=200,
timestamp_ms=1602638573590,
manifest_list='s3:/a/b/c.avro',
summary=Summary(
__root__={'operation': <Operation.APPEND: 'append'>, 'property': 'yes'}
),
schema_id=3
)
```
Which is not valid Python. I also moved the Snapshot in the test to a fixture.
> Python: Implement proper `__repr__` for Summary and Operation

- api/src/main/java/org/apache/iceberg/transforms/Bucket.java
- api/src/main/java/org/apache/iceberg/util/BucketHashUtil.java
- api/src/main/java/org/apache/iceberg/util/BucketUtil.java
- api/src/test/java/org/apache/iceberg/transforms/TestBucketing.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/functions/BucketFunction.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/functions/SparkFunctions.java
- spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/sql/TestSparkBucketFunction.java
Adds a `bucket` function that performs the Iceberg partition transformation to the Spark FunctionCatalog, for usage from SQL and for usage with storage partitioned joins.
This closes https://github.com/apache/iceberg/issues/5349
> Spark 3.3 - Support bucket in FunctionCatalog

- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/functions/BucketFunction.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/functions/SparkFunctions.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/sql/TestSparkBucketFunction.java
Backports the v2 `bucket` function for Spark's FunctionCatalog to Spark 3.2, which is needed for storage partitioned joins as well as calling the `bucket` transform on non-partition columns.
Backports #5513
> Spark 3.2: Support bucket in FunctionCatalog

- flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/source/IcebergSource.java
- flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/source/reader/IcebergSourceReader.java
- flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/source/reader/IcebergSourceReaderMetrics.java
- flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/source/reader/IcebergSourceSplitReader.java
- flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/source/reader/ReaderFunctionTestBase.java
- flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/source/reader/ReaderUtil.java
- flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/source/reader/TestIcebergSourceReader.java
- flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/source/reader/TestingMetricGroup.java
- flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/source/IcebergSource.java
- flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/source/reader/IcebergSourceReader.java
- flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/source/reader/IcebergSourceReaderMetrics.java
- flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/source/reader/IcebergSourceSplitReader.java
- flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/source/reader/ReaderFunctionTestBase.java
- flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/source/reader/ReaderUtil.java
- flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/source/reader/TestIcebergSourceReader.java
- flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/source/reader/TestingMetricGroup.java
can't register it in split reader as split reader can be re-created as previous fetcher exited. As a result, we will see registration failure later and metrics value will never be updated again. Hence we need to construct the metrics object/registration when reader (not split reader) is created.
Basically, IcebergSourceReader will become part of metric name and table k-v pair will become a tag. This is suggested by Mason Chen in the comment below so that it is more consistent as other Flink connector metrics. https://github.com/apache/iceberg/pull/5410#discussion_r946260023
> Flink: fix the bug where metrics are registered in split reader. Also updated reader metric group to be more consistent with Flink metrics style.

- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/actions/BaseSparkAction.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/actions/DeleteOrphanFilesSparkAction.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/actions/ExpireSnapshotsSparkAction.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/actions/TestRemoveOrphanFilesAction.java
This is a cherry-pick of #5495 to Spark 3.2.
> Spark 3.2: Reduce serialization in DeleteOrphanFilesSparkAction

- python/pyiceberg/utils/iceberg_base_model.py
A breaking change has been reverted:
https://github.com/pydantic/pydantic/releases/tag/v1.9.2
This means that it is now a str instead of a bool.
It defaults to shallow, which is fine for us.
```
tests/catalog/test_base.py::test_rename_table
/Users/fokkodriesprong/Desktop/iceberg/python/tests/catalog/test_base.py:117: DeprecationWarning: `copy_on_model_validation` should be a string: 'deep', 'shallow' or 'none'
self.__tables[to_identifier] = Table(
tests/catalog/test_hive.py::test_create_table
tests/catalog/test_hive.py::test_create_table
tests/catalog/test_hive.py::test_create_table
/Users/fokkodriesprong/Desktop/iceberg/python/pyiceberg/catalog/hive.py:308: DeprecationWarning: `copy_on_model_validation` should be a string: 'deep', 'shallow' or 'none'
metadata = TableMetadataV2( …
```
> Python: Remove copy_on_shallow

- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/functions/BucketFunction.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/functions/TruncateFunction.java
This PR aligns formatting in TruncateFunction and BucketFunction in Spark 3.2.
It backports https://github.com/apache/iceberg/pull/5573 to Spark 3.2
> Spark 3.2: Align formatting in bucket and truncate functions

- core/src/main/java/org/apache/iceberg/CatalogUtil.java
I don't want to memorize the full classpath to the RESTCatalog, but now I already do. Let's make it easier for others in the future.
> Core: Make a shorthand for the rest catalog

- api/src/main/java/org/apache/iceberg/metrics/DefaultMetricsContext.java
- api/src/main/java/org/apache/iceberg/metrics/FixedReservoirHistogram.java
- api/src/main/java/org/apache/iceberg/metrics/Histogram.java
- api/src/main/java/org/apache/iceberg/metrics/MetricsContext.java
- api/src/test/java/org/apache/iceberg/metrics/TestDefaultMetricsContext.java
- api/src/test/java/org/apache/iceberg/metrics/TestFixedReservoirHistogram.java
@rdblue here is the metrics PR. As we discussed, Flink Iceberg sink would need Gauge (e.g. last commit duration) and Histogram (e.g. file size distribution) metrics.
cc @danielcweeks @nastra for additional reviews
> API: add Histogram metric type

- .asf.yaml
A bold request to add me as a collaborator.
I would love to clean up the Python project: https://github.com/apache/iceberg/projects/7 To clean up the current state, and add the issues we want to include in the first Python release.
It also looks like the limit has been bumped to 20: https://cwiki.apache.org/confluence/display/INFRA/Git+-+.asf.yaml+features#Git.asf.yamlfeatures-AssigningexternalcollaboratorswiththetriageroleonGitHub
> Add Fokko as a collaborator

- python/pyiceberg/catalog/__init__.py
- python/pyiceberg/catalog/hive.py
- python/pyiceberg/catalog/rest.py
- python/pyiceberg/cli/console.py
- python/pyiceberg/cli/output.py
- python/tests/catalog/test_hive.py
- python/tests/catalog/test_rest.py
The recent refactor of how properties work caused the CLI to stop working with REST catalogs that use tokens. The token was being fetched from properties using `self.property`, but was set in the constructor's local properties map. The two maps were different objects because properties are passed to `__init__` using `**properties`.
The result was a 400 error (missing `Authorization` header). This also fixes the `_fetch_config` method's error handling. It was not parsing the error payload and so the cause message was ignored. This also updates text output to pretty print the stack trace when an exception causes the CLI to fail.
> Python: Fix CLI after properties refactor

- baseline.gradle
Follow-up to https://github.com/apache/iceberg/pull/5476 where the last violation was removed
the idea is to reduce review effort by enforcing this preference through a compile-time check instead of an ignorable warning
> Build: enforce LambdaMethodReference check at compile-time

- api/src/main/java/org/apache/iceberg/io/CredentialSupplier.java
- api/src/main/java/org/apache/iceberg/io/SupportsBulkOperations.java
- api/src/main/java/org/apache/iceberg/io/SupportsPrefixOperations.java
This PR extends `FileIO` in its optional interfaces. This way, we we can access all methods available in `FileIO` if we have a reference to the optional interface. Otherwise, we have to cast back.
> API: Extend FileIO in optional interfaces

- flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/source/enumerator/ContinuousSplitPlannerImpl.java
- flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/source/enumerator/ContinuousSplitPlannerImpl.java
When testing another PR, I noticed that there are some JavaDocs with malformed tags.
This file does not exist in Flink 1.13 and I didn't find this issue in other places.
> Flink - Fix Malformed Inline Tag in ContinuousSplitPlannerImpl JavaDoc

- .palantir/revapi.yml
- api/src/main/java/org/apache/iceberg/expressions/BoundReference.java
- api/src/main/java/org/apache/iceberg/expressions/ExpressionVisitors.java
- api/src/main/java/org/apache/iceberg/expressions/Expressions.java
- api/src/main/java/org/apache/iceberg/expressions/NamedReference.java
- api/src/main/java/org/apache/iceberg/expressions/Reference.java
- core/src/main/java/org/apache/iceberg/SingleValueParser.java
- core/src/main/java/org/apache/iceberg/expressions/ExpressionParser.java
- core/src/test/java/org/apache/iceberg/TestSingleValueParser.java
- core/src/test/java/org/apache/iceberg/expressions/TestExpressionParser.java
This adds a JSON parser for `Expression` based on @nastra's work in #5511, but with a few changes:
1. The format matches what was discussed in #4308
2. Adds a `CustomOrderExpressionVisitor` to visit expressions when converting to JSON
3. Transforms are supported if a schema is passed to `fromJson`
4. Both bound and unbound expressions can be passed to `toJson`. Using a bound expression ensures that the JSON representation for values matches expression's type
Closes #4308
Closes #5511
Co-authored-by: Eduard Tudenhoefner <etudenhoefner@gmail.com>
> Core: Add expression JSON parser

- core/src/main/java/org/apache/iceberg/MetadataUpdateParser.java
It was using `{}` instead of `%s` as a placeholder.
> Fix message pattern in checkArgument invocation

- core/src/main/java/org/apache/iceberg/MetadataTableType.java
- core/src/main/java/org/apache/iceberg/MetadataTableUtils.java
- core/src/main/java/org/apache/iceberg/RefsTable.java
- spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMetadataTables.java
This PR adds snapshot references metadata table to display branches and tags of a table.
```
spark-sql> DESCRIBE TABLE my_catalog.db_iceberg_poc.test_metatable.refs;
name                 	string
type                	string
snapshot_id         	bigint
max_reference_age_in_ms	bigint
min_snapshots_to_keep	int
max_snapshot_age_in_ms	bigint
scala> val df = spark.sql("SELECT * FROM my_catalog.db_iceberg_poc.test_metatable.refs");
df: org.apache.spark.sql.DataFrame = [reference: string, type: string ... 4 more fields]
scala> df.show()
+----+------+-------------------+-----------------------+---------------------+----------------------+
|name|  type|        snapshot_id|max_reference_age_in_ms|min_snapshots_to_keep|max_snapshot_age_in_ms| …
```
> Core: Add snapshot references metadata table

- api/src/main/java/org/apache/iceberg/BlobMetadata.java
- api/src/main/java/org/apache/iceberg/StatisticsFile.java
- core/src/main/java/org/apache/iceberg/GenericBlobMetadata.java
- core/src/main/java/org/apache/iceberg/GenericStatisticsFile.java
- core/src/main/java/org/apache/iceberg/MetadataUpdate.java
- core/src/main/java/org/apache/iceberg/MetadataUpdateParser.java
- core/src/main/java/org/apache/iceberg/StatisticsFileParser.java
- core/src/main/java/org/apache/iceberg/TableMetadata.java
- core/src/main/java/org/apache/iceberg/TableMetadataParser.java
- core/src/test/java/org/apache/iceberg/TestMetadataUpdateParser.java
- core/src/test/java/org/apache/iceberg/TestTableMetadata.java
- core/src/test/resources/TableMetadataStatisticsFiles.json
Extracted from https://github.com/apache/iceberg/pull/5021
https://github.com/apache/iceberg/pull/5021#discussion_r936925981
> Add table metadata changes for statistics information in table metadata

- aws/src/main/java/org/apache/iceberg/aws/AwsClientFactories.java
This method was incorrectly marked as public. Deprecating it is one of the follow-up items of the following PR:
https://github.com/apache/iceberg/pull/5555
> AWS: Deprecate AwsClientFactories.s3Configuration()

- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/SparkV2Filters.java
- spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/TestSparkV2Filters.java
This PR adds `SparkV2Filters` and `TestSparkV2Filters`. In next PR, I will make `SparkScanBuilder` implement `SupportsPushDownV2Filters` and add a test `TestV2FilteredScan`. 
Currently, Spark still uses V2 Filter in `SupportsRuntimeFiltering` and `SupportsDelete`. I have a PR to add `SupportsRuntimeV2Filtering` and will have a PR to add V2 Filter in `SupportsDelete`  in Spark. Before these support are released on Spark side, we can use `Filter.toV2` to convert V1 filter to V2 filter for now.
Spark V2 Filter format:
```
Predicate(String name, Expression[] children)
```
The Predicate could be
```
name: IS_NULL
children[0] is NamedReference
name: IS_NOT_NULL
children[0] is NamedReference
name: STARTS_WITH
children[0] is NamedReference
children[1] is LiteralValue
name: IN
children[0] is …
```
> Add SparkV2Filters

- api/src/main/java/org/apache/iceberg/TableScan.java
This PR deprecates old incremental append-only scans in favor of the new API.
> API: Deprecate old incremental append scans

- python/pyiceberg/typedef.py
- python/tests/test_typedef.py
One class a day, so we can enable mypy `--strict` one day.
> Python: Add annotations typedef

- api/src/main/java/org/apache/iceberg/types/TypeUtil.java
I believe this should be the other way around. Noticed this when working on the Python equivalent.
> Docs: Switch post- and pre- around

- aws/src/main/java/org/apache/iceberg/aws/AwsClientFactories.java
- aws/src/main/java/org/apache/iceberg/aws/AwsProperties.java
- docs/aws.md
Allow users to enable the dual stack feature
> AWS: Add s3.dualstack-enabled flag to AwsProperties

- python/pyiceberg/utils/datetime.py
This fixes some of the date/time transform methods introduced in #5462.
> Python: Fix date/time transforms

- .palantir/revapi.yml
- api/src/main/java/org/apache/iceberg/Table.java
- api/src/main/java/org/apache/iceberg/Transaction.java
- api/src/main/java/org/apache/iceberg/UpdateStatistics.java
- core/src/main/java/org/apache/iceberg/BaseMetadataTable.java
- core/src/main/java/org/apache/iceberg/BaseTransaction.java
- core/src/main/java/org/apache/iceberg/CommitCallbackTransaction.java
- core/src/main/java/org/apache/iceberg/SerializableTable.java
API for https://github.com/apache/iceberg/pull/4945
Implementation PR: https://github.com/apache/iceberg/pull/4741
Extracted from https://github.com/apache/iceberg/pull/4741 per https://github.com/apache/iceberg/pull/4741#discussion_r895213091
> Add API changes for statistics information in table metadata

- aws/src/main/java/org/apache/iceberg/aws/AssumeRoleAwsClientFactory.java
In [aws/src/main/java/org/apache/iceberg/aws/AssumeRoleAwsClientFactory.java, line 99](https://github.com/apache/iceberg/blob/6a1f351414227f5c09235a96ad579fab0e88733a/aws/src/main/java/org/apache/iceberg/aws/AssumeRoleAwsClientFactory.java#L99),
the `initialize` method use `AwsProperties.S3_ACCESS_POINTS_PREFIX` to update the `this.s3UseArnRegionEnabled` field:
```
this.s3UseArnRegionEnabled =
PropertyUtil.propertyAsBoolean(
properties,
AwsProperties.S3_ACCESS_POINTS_PREFIX,
AwsProperties.S3_USE_ARN_REGION_ENABLED_DEFAULT);
```
According to: https://aws.amazon.com/s3/features/access-points/, the `S3_ACCESS_POINTS_PREFIX` contains the name of the access point rather than `true/false` values. Initializing the feature in this way makes this feature `disabled` almost all the time.
Hence, it …
> AWS: fix the wrong flag used for s3UseArnRegionEnabled

- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/BaseReader.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/ChangelogRowReader.java
- spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/source/TestChangelogReader.java
@aokolnychyi @szehon-ho @anuragmantri @RussellSpitzer @karuppayya @kbendick @rdblue
> Spark: Add Changelog reader for copy-on-write

- aws/src/main/java/org/apache/iceberg/aws/s3/S3OutputStream.java
- aws/src/test/java/org/apache/iceberg/aws/s3/TestS3OutputStream.java
- core/src/main/java/org/apache/iceberg/io/BaseTaskWriter.java
- core/src/main/java/org/apache/iceberg/io/SortedPosDeleteWriter.java
This is an alternative fix for the Flink double close problem, #4168 and #5310.
The original solution modified `S3OutputStream` so that every call to `close` after a failure would re-throw the original exception. That violates the [contract for `close`](https://docs.oracle.com/javase/8/docs/api/java/io/Closeable.html#close--), which states:
> Closes this stream and releases any system resources associated with it. **If the stream is already closed then invoking this method has no effect.**
The original fix also did not address the underlying problem that the stream was closed twice and still emitting data files. This PR fixes double close cases in `BaseTaskWriter` by ensuring the writer that is closed is always set to null.
This PR also attempts to fix the problem of duplicate data in …
> Core: Fix exception handling in BaseTaskWriter

- aws/src/main/java/org/apache/iceberg/aws/dynamodb/DynamoDbCatalog.java
- aws/src/main/java/org/apache/iceberg/aws/glue/GlueCatalog.java
- core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java
- core/src/test/java/org/apache/iceberg/jdbc/TestJdbcCatalog.java
- hive-metastore/src/main/java/org/apache/iceberg/hive/HiveCatalog.java
- hive-metastore/src/test/java/org/apache/iceberg/hive/TestHiveCatalog.java
When the metadata file doesn't exist any more, drop table operation will fail. 
This PR aims to support deleting the table even if the table was corrupted.
> Support delete corrupted Iceberg table

- parquet/src/main/java/org/apache/iceberg/parquet/Parquet.java
- parquet/src/main/java/org/apache/iceberg/parquet/ParquetCodecFactory.java
This PR adds a workaround for memory issues encountered when reading Parquet files compressed with zstd. During some load testing on Spark, we encountered various OOM kills when reading from zstd compressed tables. One suggested solution was to set the environment variable `MALLOC_TRIM_THRESHOLD_` to something lower than default, like 8192. This helped in some cases but not all.
Upon further investigation, it appeared that buffers were accumulating...
Disabling the buffer pool resulted in finalizers accumulating instead...
The solution is the same being [proposed](https://github.com/apache/parquet-mr/pull/982) in parquet-mr. The current version of Parquet will leave the decompress stream [open](https://github.com/apache/parquet-mr/blob/6add62754b3d53e30376360f8d215da004fa8096/parquet-hadoo …
> Parquet: close zstd input stream early to avoid memory pressure

- docs/aws.md
AWS SDK version was bumped from 2.17.131 -> 2.17.257 via  https://github.com/apache/iceberg/pull/5612
This change attempts to reflect the same in doc.
cc @Fokko @jackye1995 @amogh-jahagirdar
> Docs: Update docs to reflect AWS SDK version presently being used 

- docs/spark-queries.md
In the pr of https://github.com/apache/iceberg/pull/4516, we added specId for partitions metadata table, but the document of query(https://iceberg.apache.org/docs/latest/spark-queries/#partitions ) hasn't been changed to adapt to that. 
What's more, the ResultSet structures are not the same between partitioned and not-partitioned tables.
query example:
```shell
0: jdbc:hive2://host:10000> create table p (id int, age int) using iceberg partitioned by (id);
0: jdbc:hive2://host:10000> create table np (id int, age int) using iceberg;
0: jdbc:hive2://host:10000> insert into p(id, age) values (1,1),(2,2),(3,3);
0: jdbc:hive2://host:10000> insert into np(id, age) values (1,1),(2,2),(3,3);
0: jdbc:hive2://host:10000> select * from spark_catalog.kunni_db.p.partitions; …
```
> Doc: Update doc to display the results of the table partitions query 

- api/src/main/java/org/apache/iceberg/exceptions/ServiceFailureException.java
- api/src/main/java/org/apache/iceberg/exceptions/ServiceUnavailableException.java
- core/src/main/java/org/apache/iceberg/rest/ErrorHandlers.java
This updates exception handling for the REST catalog where it deviates from the spec:
* Throws `CommitStateUnknownException` for 500 and 504 for table commits. This is needed to suppress file deletion when a commit may have succeeded
* Throws `ServiceUnavailableException` for 503 on all routes
* Updates `ServiceFailureException` for 500 on non-commit routes to extend `RESTException`
> Core: Add CommitStateUnknownException handling to REST

- core/src/main/java/org/apache/iceberg/deletes/DeleteCounter.java
- core/src/main/java/org/apache/iceberg/deletes/Deletes.java
- data/src/main/java/org/apache/iceberg/data/DeleteFilter.java
- data/src/test/java/org/apache/iceberg/data/DeleteReadTests.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/data/vectorized/ColumnarBatchReader.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/BaseReader.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/BatchDataReader.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/ChangelogRowReader.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/EqualityDeleteRowReader.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/RowDataReader.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/SparkScan.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/metrics/NumDeletes.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/metrics/NumSplits.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/metrics/TaskNumDeletes.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/metrics/TaskNumSplits.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/source/SparkSQLExecutionHelper.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkReaderDeletes.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/data/vectorized/ColumnarBatchReader.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/BaseReader.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/BatchDataReader.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/ChangelogRowReader.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/EqualityDeleteRowReader.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/RowDataReader.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/SparkScan.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/metrics/NumDeletes.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/metrics/NumSplits.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/metrics/TaskNumDeletes.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/metrics/TaskNumSplits.java
- spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/source/SparkSQLExecutionHelper.java
- spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkReaderDeletes.java
This is an extension of #4395.
Here we add a custom metric for the number of delete rows that have been applied in a scan of a format v2 table.
We introduce a counter in `BatchDataReader` and `RowDataReader`, that is incremented when a delete is applied. This counter is passed into `DeleteFilter`, and in the cases where we construct a `PositionDeleteIndex`, is passed into the implementation of the `PositionDeleteIndex`. In all the read paths, the counter is incremented whenever a delete is applied. When Spark calls `currentMetricsValues()` on a `PartitionReader`, which is a subclass of either `BatchDataReader` or `RowDataReader`, we get the current value of the counter and return that.
Tested manually by creating a format v2 table using each of Parquet, ORC, and Avro files, deleting and …
> Spark: Add custom metric for number of deletes applied by a SparkScan

- aws/src/main/java/org/apache/iceberg/aws/s3/S3InputStream.java
- aws/src/test/java/org/apache/iceberg/aws/s3/StaticClientFactory.java
- aws/src/test/java/org/apache/iceberg/aws/s3/TestS3FileIO.java
- build.gradle
- core/src/main/java/org/apache/iceberg/BaseMetastoreTableOperations.java
This is an alternative to #5688. Rather than making retries configurable, this stops retrying on `NotFoundException` in `BaseMetastoreTableOperations`. It also updates `S3FileIO` to throw `NotFoundException`.
> Core: Avoid useless metadata retries.

- baseline.gradle
These errorprone checks are just warnings by default:
https://github.com/palantir/gradle-baseline/blob/4.0.0/baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/Slf4jThrowable.java#L41
https://github.com/palantir/gradle-baseline/blob/4.0.0/baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/LoggerEnclosingClass.java#L41
https://github.com/palantir/gradle-baseline/blob/4.0.0/baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/PreferStaticLoggers.java#L43
Since the codebase has no violations we should increase the severity to
ERROR and enforce these conventions automatically going forward (i.e. at compile-time rather than through reviews).
> Build: Enforce logging conventions with errorprone

- nessie/src/main/java/org/apache/iceberg/nessie/NessieTableOperations.java
- nessie/src/test/java/org/apache/iceberg/nessie/TestNessieTable.java
Iceberg GC functionalities like `remove_orphan_files`, `expire_snapshots`, `drop_table` (with `purge=true`) are not aware of the Nessie's branches and tags. 
So, when a user accidentally calls these on Nessie-managed tables, these GC functionalities will clean up the files which are still referenced in other branches/tags. So, blocking all the Iceberg GC operations on Nessie-managed tables by default. 
Nessie will provide engine agnostic, reference-aware GC functionalities (which doesn't call these Iceberg GC functionalities internally) with CLI support for handling the GC of expired/unreferenced files of a Nessie managed table.
> Nessie: Prevent accidental deletion of files which are still referenced by other branches/tags

- docs/flink-getting-started.md
fix Hyperlink jump error in docs/flink/flink-getting-started.md #5714
> Docs: fix Hyperlink jump error in docs/flink-getting-started.md

- api/src/main/java/org/apache/iceberg/transforms/UnknownTransform.java
- baseline.gradle
Noticed this in the output, and decided to fix it right away:
```
/Users/fokkodriesprong/Desktop/iceberg/api/src/main/java/org/apache/iceberg/transforms/UnknownTransform.java:89: warning: [ObjectsHashCodeUnnecessaryVarargs] java.util.Objects.hash(non-varargs) should be
replaced with java.util.Objects.hashCode(value) to avoid unnecessary varargs array allocations.
return Objects.hash(transform);
^
```
> API: Use hashCode instead of hash

- python/pyiceberg/cli/console.py
- python/tests/cli/test_console.py
The three sub-level options within properties are a bit inconsistent with one-another. 
The Get Properties CLI at present expects a choice option `entity`. 
This is inconsistent with the way we have defined set and remove CLI option, where-in they have two sub-level commands for table and namespace which is much more cleaner IMO.
This PR makes the Get Properties CLI options consistent with Set and Remove CLI options and look like below.
> Python: Make Get Properties CLI options consistent with Set and Remove CLI options.

- versions.props
The Flink version is picked for each subproject in its respective build file.
Removing a specific Flink version from the global versions.props file as the version hint is unused - happened upon this when catching up on changes since I've been out for surgery =)
> Build - Remove unused global flink dependency from versions.props

- spark/v2.4/build.gradle
- versions.props
The `version.props` file provides version information to gradle for top-level dependencies.
All of the Spark projects have their dependencies declared in their own subprojects (from when we split the code base up by Spark version a while ago). But Spark 2.4 had one remaining dependency in `version.props` that _is_ still used: `spark-hive`.
Moved the Spark 2.4 version information to the Spark 2.4 subproject, to match the style used in Spark 3.0 subproject (and very similar to the others), and removed an entirely unused version declaration for `spark-avro` 2.4.3.
> Build - Move global Spark 2.4 dependency in version.props to Spark 2.4 subproject

- .github/workflows/open-api.yml
- .github/workflows/python-ci.yml
I noticed that we still have some jobs called `tox` when there is no tox involved. I also split out the Install and Validate step of the open-api checker to make it more clear what it is actually doing.
> CI: Fix names and jobs

- core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java
- core/src/test/java/org/apache/iceberg/jdbc/TestJdbcCatalog.java
The JdbcCatalog is overriding a specified location to the default location even if a specific location was set for the namespace.  This updates to only set the location if one is not already set.
> JdbcCatalog don't override namespace location if set

- spark/v3.2/build.gradle
- spark/v3.3/build.gradle
https://github.com/apache/iceberg/pull/4009 adds a dependency on `scala.collection.compat` which is bringing the `scala-library` dependencies and causing the runtime jars to be packaged with scala-library files. 
So far, two issues reported that scala files packaged with run time jar is conflicting with their environment scala files. 
Applicable only to spark-3.3 and spark-3.2 as PR#4009 is present only in these versions. This change also reduces the runtime jar size by 4MB!
Fixes #5732
> Spark: Fix runtime jars packaging scala library files

- flink/v1.13/build.gradle
- flink/v1.14/build.gradle
- flink/v1.15/build.gradle
- hive-runtime/build.gradle
- spark/v2.4/build.gradle
- spark/v3.0/build.gradle
- spark/v3.1/build.gradle
- spark/v3.2/build.gradle
- spark/v3.3/build.gradle
REST API catalog introduces a dependency on httpclient5 and it is included without proper relocation.
So, relocate httpclient5 dependency for runtime jars to avoid conflicts.
> Build: relocate httpclient5 dependency for runtime jars

- python/pyiceberg/catalog/rest.py
We pass in the version of the response that we expect for a certain version. If we change anything in the future in the spec, we can maintain backward compatibility until the version is being bumped.
> Python: Set the Iceberg Spec version

- .github/workflows/python-ci.yml
- python/CONTRIBUTING.md
- python/dev/docker-compose.yml
- python/dev/run-minio.sh
This PR adds a docker-compose.yml with the right configuration to run the s3 tests
> Python: Add docker-compose for s3 tests

- python/pyiceberg/table/metadata.py
I would like to remove the pre-validators because they are confusing.
Mostly because in the pre-validators the defaults and aliases aren't applied, do we have to check all the permutations of casing. Removing those requires setting defaults, and checking them afterward.
> Python: Remove the pre-validators

- python/pyiceberg/manifest.py
- python/tests/avro/test_reader.py
Found by processing fields in manifestentry with empty split_offsets field.
For pos_to_dict, check if values is None before processing as list or dict. Add two unit tests to verify.
Thanks to @fokko for the fix.
> Python: Handle optional fields in Avro conversion

- docs/flink-getting-started.md
- flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/FlinkCatalogFactory.java
- flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/FlinkCatalogFactory.java
Port https://github.com/apache/iceberg/pull/4622 to Flink 1.14&1.15 to set custom hadoop configuration during creating Iceberg catalog in Flink.
> Flink 1.14&1.15 backport: Set custom Hadoop configuration

- .baseline/checkstyle/checkstyle.xml
- api/src/main/java/org/apache/iceberg/metrics/ScanReport.java
- api/src/test/java/org/apache/iceberg/metrics/TestScanReport.java
- baseline.gradle
- build.gradle
- core/src/main/java/org/apache/iceberg/BaseTableScan.java
- core/src/main/java/org/apache/iceberg/DeleteFileIndex.java
- core/src/main/java/org/apache/iceberg/ManifestGroup.java
- core/src/main/java/org/apache/iceberg/ManifestReader.java
- core/src/main/java/org/apache/iceberg/metrics/CounterResultParser.java
- core/src/main/java/org/apache/iceberg/metrics/ScanMetricsResultParser.java
- core/src/main/java/org/apache/iceberg/metrics/ScanReportParser.java
- core/src/main/java/org/apache/iceberg/metrics/TimerResultParser.java
- core/src/test/java/org/apache/iceberg/metrics/TestCounterResultParser.java
- core/src/test/java/org/apache/iceberg/metrics/TestScanMetricsResultParser.java
- core/src/test/java/org/apache/iceberg/metrics/TestScanReportParser.java
- core/src/test/java/org/apache/iceberg/metrics/TestTimerResultParser.java
- versions.props
* Use true immutable objects that are type-safe, thread-safe, null-safe
* Get builder classes for free
This is relying on https://immutables.github.io/ (Apache License 2.0), which allows generating immutable objects and builders via annotation processing.
* Immutable objects are serialization ready (including JSON and its binary forms)
* Supports lazy, derived and optional attributes
* Immutable objects are constructed once, in a consistent state, and can be safely shared
* Will fail if mandatory attributes are missing
* Cannot be sneakily modified when passed to other code
* Immutable objects are naturally thread-safe and can therefore be safely shared among threads
* No excessive copying
* No excessive synchronization
* Object definitions are pleasant to write and read
* No boilerplate …
> API/Core: Make ScanReport and its related classes Immutable

- python/pyiceberg/expressions/base.py
Prefer to just use the first argument of the method. This makes it easier to read (less visual noise)
> Python: Remove duplicate dispatch types

- core/src/main/java/org/apache/iceberg/TableMetadataParser.java
- core/src/test/java/org/apache/iceberg/TestTableMetadata.java
`TableMetadataParser.toJson` now serializes table statistics. This
completes the read path from JSON.
Extracted from https://github.com/apache/iceberg/pull/4741 / https://github.com/apache/iceberg/pull/5794
> Core: Serialize statistics files in TableMetadata

- core/src/main/java/org/apache/iceberg/MetadataUpdateParser.java
- core/src/main/java/org/apache/iceberg/PartitionSpecParser.java
- core/src/main/java/org/apache/iceberg/SchemaParser.java
- core/src/main/java/org/apache/iceberg/SingleValueParser.java
- core/src/main/java/org/apache/iceberg/SnapshotParser.java
- core/src/main/java/org/apache/iceberg/SnapshotRefParser.java
- core/src/main/java/org/apache/iceberg/StatisticsFileParser.java
- core/src/main/java/org/apache/iceberg/catalog/TableIdentifierParser.java
- core/src/main/java/org/apache/iceberg/mapping/NameMappingParser.java
- core/src/main/java/org/apache/iceberg/puffin/FileMetadataParser.java
- core/src/main/java/org/apache/iceberg/rest/auth/OAuth2Util.java
- core/src/main/java/org/apache/iceberg/rest/requests/UpdateRequirementParser.java
While reviewing https://github.com/apache/iceberg/pull/5799 and the `StatisticsFileParser` I noticed that there are a bunch of places with duplicated code in the JSON Parsers. This PR aims at cleaning those up and reusing `JsonUtil.generate` where applicable
> Core: Reduce duplicated code in JSON Parsers

- .github/workflows/python-ci-docs.yml
The paths was invalid, but after fixing it, the Action did not run because it isn't part of the paths. I think it would be good to add this as well 👍
> Build: Add the path to the Action yaml

- python/pyproject.toml
Adds the tests to the source distribution so we can run them when validating a release.
> Python: Include the tests in source distribution

- aws/src/integration/java/org/apache/iceberg/aws/AwsIntegTestUtil.java
- aws/src/integration/java/org/apache/iceberg/aws/TestAssumeRoleAwsClientFactory.java
- aws/src/integration/java/org/apache/iceberg/aws/TestDefaultAwsClientFactory.java
- aws/src/integration/java/org/apache/iceberg/aws/dynamodb/TestDynamoDbCatalog.java
- aws/src/integration/java/org/apache/iceberg/aws/dynamodb/TestDynamoDbLockManager.java
- aws/src/integration/java/org/apache/iceberg/aws/glue/GlueTestBase.java
- aws/src/integration/java/org/apache/iceberg/aws/glue/TestGlueCatalogCommitFailure.java
- aws/src/integration/java/org/apache/iceberg/aws/glue/TestGlueCatalogLock.java
- aws/src/integration/java/org/apache/iceberg/aws/glue/TestGlueCatalogNamespace.java
- aws/src/integration/java/org/apache/iceberg/aws/glue/TestGlueCatalogTable.java
- aws/src/integration/java/org/apache/iceberg/aws/lakeformation/LakeFormationTestBase.java
- aws/src/integration/java/org/apache/iceberg/aws/lakeformation/TestLakeFormationAwsClientFactory.java
- aws/src/integration/java/org/apache/iceberg/aws/lakeformation/TestLakeFormationDataOperations.java
- aws/src/integration/java/org/apache/iceberg/aws/lakeformation/TestLakeFormationMetadataOperations.java
- aws/src/integration/java/org/apache/iceberg/aws/s3/S3TestUtil.java
- aws/src/integration/java/org/apache/iceberg/aws/s3/TestS3FileIOIntegration.java
- aws/src/integration/java/org/apache/iceberg/aws/s3/TestS3MultipartUpload.java
- baseline.gradle
- spark/v3.0/spark-runtime/src/integration/java/org/apache/iceberg/spark/SmokeTest.java
- spark/v3.1/spark-runtime/src/integration/java/org/apache/iceberg/spark/SmokeTest.java
- spark/v3.2/spark-runtime/src/integration/java/org/apache/iceberg/spark/SmokeTest.java
- spark/v3.3/spark-runtime/src/integration/java/org/apache/iceberg/spark/SmokeTest.java
This was unintentionally forgotten and usually spotless is able to infer
all java files from the source sets. However, the way we defined the
source sets doesn't seem working with spotless and so
we were defining relevant modules via `target`.
Additional details:
Spotless requires all source sets to be part of the current module being
evaluated, which isn't the case for the hive module:
```
> Spotless error! All target files must be within the project dir.
project dir: /home/nastra/Development/workspace/iceberg/hive3
target: /home/nastra/Development/workspace/iceberg/mr/src/test/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandlerTestUtils.java
```
And this is how the sourceSets are defined in `iceberg-hive3` which
cause issues:
```
project(':iceberg-hive3') {
// run the tests in …
```
> Build: Apply spotless on integration modules as well 

- python/pyproject.toml
- python/tests/test_version.py
Turned out that my regex isn't PEP440 compatible.
RCs are represented as 0.1.0rc1 and dev versions are with a dot: 0.1.0.dev1 And, they can be combined: 0.1.0rc1.dev1.
Instead of figuring out the regex myself, we can just use the one from packaging.
This package is already installed because it is also a dependency of pytest.
> Python: Test if version is PEP440 compliant

- python/pyproject.toml
This makes it easier for testing.
```
➜  python git:(fd-add-makefile-to-sdist) ✗ poetry build
Building pyiceberg (0.1.0.dev0)
- Building sdist
- Built pyiceberg-0.1.0.dev0.tar.gz
- Building wheel
- Built pyiceberg-0.1.0.dev0-py3-none-any.whl
➜  python git:(fd-add-makefile-to-sdist) ✗ cd dist
➜  dist git:(fd-add-makefile-to-sdist) ✗ tar -xf pyiceberg-0.1.0.dev0.tar.gz
➜  dist git:(fd-add-makefile-to-sdist) ✗ cd pyiceberg-0.1.0.dev0
➜  pyiceberg-0.1.0.dev0 git:(fd-add-makefile-to-sdist) ✗ find . | grep Makefile
./Makefile
➜  pyiceberg-0.1.0.dev0 git:(fd-add-makefile-to-sdist) ✗ head Makefile
```
> Python: Add the Makefile to the source distribution

- python/pyproject.toml
```
➜  python git:(master) ✗ poetry build
Building pyiceberg (0.1.0.dev0)
- Building sdist
- Built pyiceberg-0.1.0.dev0.tar.gz
- Building wheel
- Built pyiceberg-0.1.0.dev0-py3-none-any.whl
➜  python git:(master) ✗ cd dist
➜  dist git:(master) ✗ tar -xf pyiceberg-0.1.0.tar.gz
tar: Error opening archive: Failed to open 'pyiceberg-0.1.0.tar.gz'
➜  dist git:(master) ✗ tar -xf pyiceberg-0.1.0.dev0.tar.gz
➜  dist git:(master) ✗ cd pyiceberg-0.1.0.dev0
➜  pyiceberg-0.1.0.dev0 git:(master) ✗ ls -lah | grep -i notice
-rw-r--r--   1 fokkodriesprong  staff   251B Jun 14 21:52 NOTICE
```
> Python: Add NOTICE to source dist and wheel

- python/Makefile
- python/dev/check-license
- python/pyproject.toml
This adds a light version of the `check-license` script (without the exclusions), and a command in the makefile to easily run it
> Python: Add license checker to the source distribution

- python/pyproject.toml
This way we can just use the code as is when releasing, and we don't have to remove the modifier afterward.
> Python: Remove version modifier

- aws/src/main/java/org/apache/iceberg/aws/AwsProperties.java
- aws/src/test/java/org/apache/iceberg/aws/TestAwsProperties.java
- core/src/main/java/org/apache/iceberg/util/PropertyUtil.java
User can use `apache.socket-timeout-ms` and `apache.connection-timeout-ms` tags to configure the connection and socket timeout for the `ApacheHttpClient`.
Add unit test to check the if the correct HTTP client type is configured
> AWS: Add socket connection timeout for Apache Http Builder

- core/src/main/java/org/apache/iceberg/CatalogProperties.java
- core/src/main/java/org/apache/iceberg/ManifestFiles.java
- core/src/main/java/org/apache/iceberg/SystemProperties.java
- core/src/main/java/org/apache/iceberg/hadoop/HadoopFileIO.java
- core/src/main/java/org/apache/iceberg/io/ContentCache.java
- core/src/test/java/org/apache/iceberg/TestManifestCaching.java
- core/src/test/java/org/apache/iceberg/hadoop/TestManifestCaching.java
This is a draft PR for ManifestCache implementation.
The `ManifestCache` interface closely follow `com.github.benmanes.caffeine.cache.Cache` interface, with addition of specifying `maxContentLength()`. If stream length is longer than `maxContentLength()`, AvroIO will skip caching it to avoid memory pressure. An example of implementation, `CaffeineManifestCache`, can be seen in TestAvroFileSplit.java.
I will tidy this up and add documentations as we go. Looking forward for any feedback.
Closes #4508
> core: Provide mechanism to cache manifest file content

- api/src/main/java/org/apache/iceberg/UpdateStatistics.java
- core/src/main/java/org/apache/iceberg/BaseTable.java
- core/src/main/java/org/apache/iceberg/BaseTransaction.java
- core/src/main/java/org/apache/iceberg/SetStatistics.java
- core/src/test/java/org/apache/iceberg/TestSetStatistics.java
Implement `Transaction.updateStatistics` API.
Extracted from https://github.com/apache/iceberg/pull/4741 per https://github.com/apache/iceberg/pull/4741#discussion_r966200811. Probably not testable before that PR is merged.
> Support setting table statistics

- docs/spark-procedures.md
https://github.com/apache/iceberg/pull/4629 is already merged, but the the document hasn't been updated.
The execution output is inconsistent with the [documentation](https://iceberg.apache.org/docs/latest/spark-procedures/#output-4), which will lead to confuse, this pr will fix it.
```
CALL spark_catalog.system.expire_snapshots('test_table');
0       0       0       0       1
Time taken: 7.254 seconds, Fetched 1 row(s)
22/09/27 17:32:43 INFO SparkSQLCLIDriver: Time taken: 7.254 seconds, Fetched 1 row(s)
```
> Doc: Update  output of expire_snapshots procedure

- hive-metastore/src/test/java/org/apache/iceberg/hive/TestHiveMetastore.java
We have tried to run some Iceberg unit tests through test-jars in Spark.
Although Iceberg Spark v3.2 unit tests are okay to run, we got a lot errors on Hive metastore unit tests:
```
org.apache.thrift.ProcessFunction: Internal error processing lock
```
After setting hive.in.test as false in Iceberg `TestHiveMetastore.java`, the locking issue seems disappeared. 
The config seems to let Hive throw an exception when thrift version doesn't match under test.
Setting this to false to allow others to run Iceberg unit test through test-jars.
> Ensure the default value of hive.in.test to avoid overwriting

- api/src/main/java/org/apache/iceberg/metrics/DefaultMetricsContext.java
- api/src/main/java/org/apache/iceberg/metrics/MetricsContext.java
- api/src/main/java/org/apache/iceberg/transforms/Truncate.java
There are some deprecation comments added after 0.14.0 in the API folder where there is no indication when the particular functionality is going to be dropped. I marked them to be dropped in 2.0.0.
> API: Extended some deprecation comments in API folder

- core/src/main/java/org/apache/iceberg/deletes/EqualityDeleteWriter.java
- core/src/main/java/org/apache/iceberg/deletes/PositionDeleteWriter.java
- core/src/main/java/org/apache/iceberg/io/BaseTaskWriter.java
- core/src/main/java/org/apache/iceberg/io/SortedPosDeleteWriter.java
- core/src/test/java/org/apache/iceberg/avro/TestAvroDeleteWriters.java
- data/src/test/java/org/apache/iceberg/data/FileHelpers.java
- data/src/test/java/org/apache/iceberg/io/TestAppenderFactory.java
- data/src/test/java/org/apache/iceberg/io/TestFileWriterFactory.java
- flink/v1.13/flink/src/test/java/org/apache/iceberg/flink/SimpleDataUtil.java
- flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/SimpleDataUtil.java
- flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/SimpleDataUtil.java
- orc/src/test/java/org/apache/iceberg/orc/TestOrcDeleteWriters.java
- parquet/src/test/java/org/apache/iceberg/parquet/TestParquetDeleteWriters.java
- spark/v3.0/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteDataFilesAction.java
- spark/v3.1/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteDataFilesAction.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteDataFilesAction.java
- spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteDataFilesAction.java
There are some functions marked to be deprecated in 0.14. As we passed that release already and getting close to 1.0.0 this might be the time to drop them.
This patch takes care of the functions in EqualityDeleteWriter and PositionDeleteWriter classes in the core/ folder.
> Core: Deprecate functions in DeleteWriters

- aws/src/integration/java/org/apache/iceberg/aws/glue/TestGlueCatalogTable.java
- aws/src/main/java/org/apache/iceberg/aws/AwsProperties.java
- aws/src/main/java/org/apache/iceberg/aws/glue/GlueCatalog.java
- aws/src/main/java/org/apache/iceberg/aws/glue/GlueTableOperations.java
- aws/src/test/java/org/apache/iceberg/aws/glue/TestGlueCatalog.java
This change adds table level [S3 Tags](https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-tagging.html) to the objects while writing using `S3FileIO`. Users can pass these opt-in catalog properties to tag the objects in S3:
Spark SQL launch command:
```
sh spark-sql --conf spark.sql.catalog.my_catalog=org.apache.iceberg.spark.SparkCatalog \
--conf spark.sql.catalog.my_catalog.warehouse=s3://<bucket>/s3-tagging \
--conf spark.sql.catalog.my_catalog.catalog-impl=org.apache.iceberg.aws.glue.GlueCatalog \
--conf spark.sql.catalog.my_catalog.io-impl=org.apache.iceberg.aws.s3.S3FileIO \
--conf spark.sql.catalog.my_catalog.s3.write.table-name-tag-enabled=true \
--conf spark.sql.catalog.my_catalog.s3.write.namespace-name-tag-enabled=true
```
Tags added in S3:
```
aws s3api …
```
> AWS: Add table and namespace S3 tags

- core/src/main/java/org/apache/iceberg/hadoop/HadoopInputFile.java
- core/src/test/java/org/apache/iceberg/hadoop/HadoopFileIOTest.java
In case we call both exists() & getLength() we make a redundant call to `getFileStatus` as `fs.exists(path)` internally checks 
```java
/** Check if exists.
* @param f source file
*/
public boolean exists(Path f) throws IOException {
try {
return getFileStatus(f) != null;
} catch (FileNotFoundException e) {
return false;
}
}
```
So we could getFileStatus directly and cache it via lazyStat() in `stat` prop and in `getLength` & subsequent calls directly return it.
Note : This similar opt exists in S3InputFile as well as we cache the results in `getObjectMetadata` call https://github.com/apache/iceberg/blob/b9bbcfb0e4d8f2605d3c6fb2543cefdd5d09524d/aws/src/main/java/org/apache/iceberg/aws/s3/BaseS3File.java#L70
----
Existing UT's
> Core: Avoid extra getFileStatus call in HadoopInputFile

- build.gradle
- orc/src/main/java/org/apache/iceberg/orc/OrcFileAppender.java
- orc/src/test/java/org/apache/iceberg/orc/TestOrcDataWriter.java
Fixes ORCFileAppender such that it can retrieve the stripe offsets from the writer instead of having to reopen the file.
From ORC 1.7 we have a public API for getting stripe information from the writer. This avoids an additional IO to get stripe offsets
Added unit test to verify that the offsets are matching the offsets read from the file
> Orc: Closes #5777 - Obtain ORC stripe offsets from writer 

- flink/v1.13/flink/src/main/java/org/apache/iceberg/flink/sink/IcebergFilesCommitter.java
- flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/IcebergFilesCommitter.java
- flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/sink/IcebergFilesCommitter.java
…te. This would support Flink's allowNonRestoredState in case operator uid changed.
Otherwise, we can get exception like this.
```
java.util.NoSuchElementException
at java.base/java.util.ArrayList$Itr.next(ArrayList.java:1000)
at org.apache.iceberg.flink.sink.IcebergFilesCommitter.initializeState(IcebergFilesCommitter.java:175)
```
See more about `allowNonRestoredState` in Flink doc: https://nightlies.apache.org/flink/flink-docs-master/docs/ops/state/savepoints/#resuming-from-savepoints.
Without this fix, checkpoint/savepoint won't be usable if committer operator uid changed (with allowNonRestoredState enabled).
> Flink: add defensive check in IcebergFilesCommitter for restoring state

- spark/v3.3/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMetadataTables.java
I missed to add the snapshot references metadata table test in the Spark 3.3 module (in https://github.com/apache/iceberg/pull/4807). This PR backports the test.
---
cc: @jackye1995 @amogh-jahagirdar @singhpk234
> Spark 3.x: Backport snapshot references metadata table test

- spark/v3.2/build.gradle
- spark/v3.3/build.gradle
> [1.0.x] Spark: Exclude Scala library files from JAR (#5754)

- spark/v3.0/build.gradle
- spark/v3.1/build.gradle
- spark/v3.2/build.gradle
- spark/v3.3/build.gradle
While looking at https://github.com/apache/iceberg/issues/5791 I noticed that the Spark integration tests (`integrationTest` task) was never part of CI. On CI we're running the `check` task (which basically runs `test`) and this PR makes sure that `integrationTest` is part of the `check` task.
fixes #5791
> Build: Fix & Run spark integration tests on CI

- api/src/main/java/org/apache/iceberg/metrics/ScanReport.java
- core/src/main/java/org/apache/iceberg/DeleteFileIndex.java
- core/src/main/java/org/apache/iceberg/metrics/ScanMetricsResultParser.java
- core/src/test/java/org/apache/iceberg/TestScanPlanningAndReporting.java
- core/src/test/java/org/apache/iceberg/metrics/TestScanMetricsResultParser.java
- core/src/test/java/org/apache/iceberg/metrics/TestScanReportParser.java
This currently depends on https://github.com/apache/iceberg/pull/5788
> API,Core: Add scan planning metrics for scanned/skipped delete manifests

- docs/configuration.md
Vectorized read for parquet was enabled by default since [commit ec2f1ad7](https://github.com/apache/iceberg/commit/ec2f1ad76d2152d6aa08b185be4a2447319db642), this patch updates the doc accordingly.
> Doc: Update the default value of table property `read.parquet.vectorization.enabled`

- docs/configuration.md
Default values of 'Lock catalog properties' https://iceberg.apache.org/docs/latest/configuration/#lock-catalog-properties are inconsistent with context configurations, which may misleading users to fill in the wrong value.
This pull request is opened to fix it.
> Doc: Update default values of Lock catalog properties to avoid wrong way of filling.

- spark/v3.1/build.gradle
- spark/v3.2/build.gradle
https://lists.apache.org/list?dev@spark.apache.org:lte=1M:CVE-2022-33891
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-33891
> Spark: Bump Spark version for vulnerability

- .github/workflows/flink-ci.yml
- .github/workflows/hive-ci.yml
- .github/workflows/java-ci.yml
- .github/workflows/jmh-bechmarks.yml
- .github/workflows/spark-ci.yml
this avoids downloading the gradle distribution on every workflow run
also follows the recommended usage pattern for the github action:
https://github.com/actions/cache/blob/main/examples.md#java---gradle
the folder contents are deterministic:
```
chris@xanadu:~/code/iceberg$ tree -L 5 ~/.gradle/wrapper
/home/chris/.gradle/wrapper
└── dists
└── gradle-7.4-bin
└── c0gwcg53nkjbqw7r0h0umtfvt
├── gradle-7.4
│   ├── bin
│   ├── init.d
│   ├── lib
│   ├── LICENSE
│   ├── NOTICE
│   └── README
├── gradle-7.4-bin.zip
├── gradle-7.4-bin.zip.lck
└── gradle-7.4-bin.zip.ok
7 directories, 6 files
chris@xanadu:~/code/iceberg$ rm -rf ~/.gradle/wrapper
chris@xanadu:~/code/iceberg$ ./gradlew tasks >/dev/null; echo $?
0
chris@xanadu:~/code/iceberg$ tree -L 5 ~/.gradle/wrapper
/home/chris/.gradle/wrapper …
```
> Build: workflows cache gradle wrapper

- python/CONTRIBUTING.md
- python/pyiceberg/utils/deprecated.py
Since we're approaching the first version of the PyIceberg library, I think it would be good to formalize the code conventions a bit. Would love to hear what you think of this.
> Python: Add code conventions for Python

- core/src/main/java/org/apache/iceberg/GenericBlobMetadata.java
- core/src/main/java/org/apache/iceberg/ReachableFileUtil.java
- spark/v2.4/spark/src/main/java/org/apache/iceberg/spark/actions/BaseDeleteReachableFilesSparkAction.java
- spark/v2.4/spark/src/main/java/org/apache/iceberg/spark/actions/BaseSparkAction.java
- spark/v2.4/spark/src/test/java/org/apache/iceberg/spark/actions/TestRemoveOrphanFilesAction.java
- spark/v3.0/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRemoveOrphanFilesProcedure.java
- spark/v3.0/spark/src/main/java/org/apache/iceberg/spark/actions/BaseDeleteReachableFilesSparkAction.java
- spark/v3.0/spark/src/main/java/org/apache/iceberg/spark/actions/BaseSparkAction.java
- spark/v3.0/spark/src/test/java/org/apache/iceberg/spark/actions/TestRemoveOrphanFilesAction.java
- spark/v3.1/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRemoveOrphanFilesProcedure.java
- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/actions/BaseDeleteReachableFilesSparkAction.java
- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/actions/BaseSparkAction.java
- spark/v3.1/spark/src/test/java/org/apache/iceberg/spark/actions/TestRemoveOrphanFilesAction.java
- spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRemoveOrphanFilesProcedure.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/actions/BaseSparkAction.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/actions/TestRemoveOrphanFilesAction.java
- spark/v3.3/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRemoveOrphanFilesProcedure.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/actions/BaseSparkAction.java
- spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/actions/TestRemoveOrphanFilesAction.java
Do not delete table statistics files when running remove_orphan_files.
Extracted from https://github.com/apache/iceberg/pull/4741  and based on that PR, and also on https://github.com/apache/iceberg/pull/5794 and https://github.com/apache/iceberg/pull/5799.
> Retain table statistics during orphan files removal

- docs/spark-ddl.md
#3056 added support for `PURGE` flag to Spark.
However, the corresponding `DROP TABLE` doc is outdated.
This PR aims at documenting the updated behavior of the `DROP TABLE` DDL command.
Closes #5646
> [Docs] Update drop table behavior in spark-ddl docs

- spark/v3.3/spark/src/jmh/java/org/apache/iceberg/spark/data/parquet/SparkParquetReadersFlatDataBenchmark.java
- spark/v3.3/spark/src/jmh/java/org/apache/iceberg/spark/data/parquet/SparkParquetReadersNestedDataBenchmark.java
- spark/v3.3/spark/src/jmh/java/org/apache/iceberg/spark/data/parquet/SparkParquetWritersFlatDataBenchmark.java
- spark/v3.3/spark/src/jmh/java/org/apache/iceberg/spark/data/parquet/SparkParquetWritersNestedDataBenchmark.java
The `ParquetToSparkSchemaConverter` class in Spark3.3 expects `SQLConf.CASE_SENSITIVE` in the Configuration.
However, the above config is not specified while instantiating the `ReadBuilder` and `WriteBuilder` thereby resulting in the `IllegalArgumentException` exception.
Adding `spark.sql.caseSensitive=false` to ReadBuilder and WriteBuilder properties resolves the issue.
Closes #5634
> Spark 3.3: Fix failing jmh benchmarks under org.apache.iceberg.spark.data.parquet package

- api/src/main/java/org/apache/iceberg/PartitionSpec.java
- core/src/main/java/org/apache/iceberg/TableMetadataParser.java
- spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestAlterTablePartitionFields.java
- spark/v3.3/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestAlterTablePartitionFields.java
If a field is being deleted that used to be part of a partition spec, that will throw an error because it cannot resolve the field anymore. See the issue for more details.
Closes #5676
> Core: Only validate the current partition specs

- api/src/main/java/org/apache/iceberg/metrics/LoggingMetricsReporter.java
- api/src/main/java/org/apache/iceberg/metrics/MetricsReport.java
- api/src/main/java/org/apache/iceberg/metrics/MetricsReporter.java
- api/src/main/java/org/apache/iceberg/metrics/ScanReport.java
- core/src/main/java/org/apache/iceberg/BaseTable.java
- core/src/main/java/org/apache/iceberg/BaseTableScan.java
- core/src/main/java/org/apache/iceberg/TableScanContext.java
- core/src/main/java/org/apache/iceberg/metrics/ScanReportParser.java
- core/src/main/java/org/apache/iceberg/rest/RESTSerializers.java
- core/src/main/java/org/apache/iceberg/rest/RESTSessionCatalog.java
- core/src/main/java/org/apache/iceberg/rest/ResourcePaths.java
- core/src/main/java/org/apache/iceberg/rest/requests/ReportMetricsRequest.java
- core/src/main/java/org/apache/iceberg/rest/requests/ReportMetricsRequestParser.java
- core/src/test/java/org/apache/iceberg/TestScanPlanningAndReporting.java
- core/src/test/java/org/apache/iceberg/TestTables.java
- core/src/test/java/org/apache/iceberg/rest/RESTCatalogAdapter.java
- core/src/test/java/org/apache/iceberg/rest/requests/TestReportMetricsRequestParser.java
- open-api/rest-catalog-open-api.yaml
depends on https://github.com/apache/iceberg/pull/5427
> Core: Add RESTScanReporter to send scan report to REST endpoint

- .github/workflows/flink-ci.yml
- .github/workflows/hive-ci.yml
- .github/workflows/java-ci.yml
- .github/workflows/spark-ci.yml
Presently on updating ISSUE_TEMPLATE we trigger complete engine suite. Like Licence / Notice / readme we can also ignore running suite when we update the ISSUE_TEMPLATE.
> INFRA: Avoid running engine tests on ISSUE_TEMPLATE update

- docs/spark-ddl.md
#3056 added support for `PURGE` flag to Spark.
However, the corresponding `DROP TABLE` doc is outdated.
This PR aims at documenting the updated behavior of the `DROP TABLE` DDL command.
(cherry picked from commit fd7d20a97aef294d76f467c2419d5bc3f775165b)
Closes #5646
> [0.14][Docs] Update drop table behavior in spark-ddl docs

- spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestAlterTablePartitionFields.java
- spark/v3.3/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestAlterTablePartitionFields.java
Follow up of https://github.com/apache/iceberg/pull/5707
> Spark: Set the version explicitly

- spark/v3.1/build.gradle
- spark/v3.2/build.gradle
> [1.0.x] Spark: Bump Spark version for vulnerability (#5292)

- aliyun/src/main/java/org/apache/iceberg/aliyun/oss/OSSInputStream.java
- aliyun/src/main/java/org/apache/iceberg/aliyun/oss/OSSOutputStream.java
- api/src/main/java/org/apache/iceberg/metrics/MetricsContext.java
- api/src/main/java/org/apache/iceberg/metrics/ScanReport.java
- api/src/test/java/org/apache/iceberg/io/TestCloseableIterable.java
- aws/src/main/java/org/apache/iceberg/aws/s3/S3InputStream.java
- aws/src/main/java/org/apache/iceberg/aws/s3/S3OutputStream.java
- dell/src/main/java/org/apache/iceberg/dell/ecs/EcsAppendOutputStream.java
- dell/src/main/java/org/apache/iceberg/dell/ecs/EcsSeekableInputStream.java
- gcp/src/main/java/org/apache/iceberg/gcp/gcs/GCSInputStream.java
- gcp/src/main/java/org/apache/iceberg/gcp/gcs/GCSOutputStream.java
This is a follow-up from https://github.com/apache/iceberg/pull/5792#discussion_r984024379. `COUNT` is usually the unit that will be used in most places, so it makes sense to have `default org.apache.iceberg.metrics.Counter counter(String name)` that defaults to it
> API: Make COUNT default unit when creating a Counter

- core/src/main/java/org/apache/iceberg/deletes/PositionDeleteWriter.java
- core/src/main/java/org/apache/iceberg/io/SortedPosDeleteWriter.java
- core/src/test/java/org/apache/iceberg/avro/TestAvroDeleteWriters.java
- data/src/test/java/org/apache/iceberg/data/FileHelpers.java
- data/src/test/java/org/apache/iceberg/io/TestAppenderFactory.java
- data/src/test/java/org/apache/iceberg/io/TestFileWriterFactory.java
- flink/v1.13/flink/src/test/java/org/apache/iceberg/flink/SimpleDataUtil.java
- flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/SimpleDataUtil.java
- flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/SimpleDataUtil.java
- parquet/src/test/java/org/apache/iceberg/parquet/TestParquetDeleteWriters.java
This is a follow-up from #5771 to restore the old behavior where a `PositionDelete` was reused for a `PositionDeleteWriter`
> Core: Reuse PositionDelete

- spark/v3.3/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/analysis/RewriteMergeIntoTable.scala
- spark/v3.3/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/analysis/RewriteRowLevelIcebergCommand.scala
- spark/v3.3/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestCopyOnWriteMerge.java
- spark/v3.3/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMerge.java
This PR fixes the second part of #5739 and is an alternative to #5789. Instead of reporting a wrong output nullability for merged output attributes, this change fixes the schema used in lazy projections for row, row ID and metadata attributes.
> Spark 3.3: Fix nullability in merge-on-read projections

- spark/v3.2/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/analysis/RewriteMergeIntoTable.scala
- spark/v3.2/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/analysis/RewriteRowLevelCommand.scala
- spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestCopyOnWriteMerge.java
- spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMerge.java
This is a cherry-pick of #5880 to Spark 3.2.
> Spark 3.2: Fix nullability in merge-on-read projections

- .baseline/checkstyle/checkstyle.xml
- core/src/test/java/org/apache/iceberg/TableMetadataParserCodecTest.java
- core/src/test/java/org/apache/iceberg/TestMetricsModes.java
- core/src/test/java/org/apache/iceberg/TestSchemaUnionByFieldName.java
- data/src/test/java/org/apache/iceberg/data/TestMetricsRowGroupFilter.java
- orc/src/test/java/org/apache/iceberg/orc/TestBuildOrcProjection.java
- spark/v2.4/spark/src/test/java/org/apache/iceberg/spark/source/TestStructuredStreaming.java
- spark/v2.4/spark/src/test/java/org/apache/iceberg/spark/source/TestTimestampWithoutZone.java
- spark/v3.0/spark/src/test/java/org/apache/iceberg/spark/source/TestStructuredStreaming.java
- spark/v3.0/spark/src/test/java/org/apache/iceberg/spark/source/TestTimestampWithoutZone.java
- spark/v3.1/spark/src/test/java/org/apache/iceberg/spark/source/TestStructuredStreaming.java
- spark/v3.1/spark/src/test/java/org/apache/iceberg/spark/source/TestTimestampWithoutZone.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/source/TestStructuredStreaming.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/source/TestTimestampWithoutZone.java
- spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/source/TestStructuredStreaming.java
- spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/source/TestTimestampWithoutZone.java
While working on https://github.com/apache/iceberg/pull/5910 I noticed that there have been still a few places that use `ExpectedException`.
It is generally not good practice to use the `ExpectedException` rule, because it is difficult to determine in multi-line tests where exactly an exception is thrown, since the rule is very broad.
> Replace & Ban ExpectedException usage

- python/pyiceberg/expressions/base.py
- python/pyiceberg/schema.py
- python/tests/expressions/test_expressions_base.py
From:
```
➜  python git:(master) make test | grep -i "expressions/base.py"
pyiceberg/expressions/base.py                451     41    91%   68, 133, 137, 157, 183, 202, 204, 220, 228, 236, 245, 248, 258, 264, 275, 286, 314, 326, 350, 362, 370, 377, 385, 387, 392, 402, 419, 421, 438, 446, 452, 458, 464, 470, 476, 482, 498, 514, 530, 685, 776
```
To:
```
➜  python git:(fd-add-tests) make test | grep -i "expressions/base.py"
pyiceberg/expressions/base.py                446      0   100%
```
Cleans up the tests to also align them with the rest of the testcases.
> Python: Add expression tests

- api/src/main/java/org/apache/iceberg/expressions/ExpressionUtil.java
- api/src/test/java/org/apache/iceberg/expressions/TestExpressionUtil.java
Follows https://github.com/apache/iceberg/pull/4672
cc @ebyhr @alexjo2144 @electrum @dain
> Reduce 'Scanning table' log verbosity for long IN list

- core/src/main/java/org/apache/iceberg/ChangelogUtil.java
- core/src/main/java/org/apache/iceberg/MetadataColumns.java
- core/src/main/java/org/apache/iceberg/hadoop/Util.java
- spark/v3.3/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestChangelogBatchReads.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/SparkCatalog.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/ChangelogRowReader.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/SparkChangelogBatch.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/SparkChangelogScan.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/SparkChangelogTable.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/SparkInputPartition.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/SparkMicroBatchStream.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/SparkScan.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/SparkScanBuilder.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/SparkTable.java
- spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/actions/TestRemoveOrphanFilesAction3.java
- spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/source/TestPathIdentifier.java
This PR adds `SparkChangelogTable` for querying changelogs in Spark.
> Spark 3.3: Add SparkChangelogTable

- python/pyiceberg/table/partitioning.py
- python/tests/table/test_partitioning.py
We need to construct a StructType from the PartitionSpec for the manifest evaluators
> Python: Add partition_type to partition_spec

- api/src/main/java/org/apache/iceberg/ManifestFile.java
- core/src/main/java/org/apache/iceberg/DeleteFileIndex.java
- core/src/main/java/org/apache/iceberg/GenericManifestEntry.java
- core/src/main/java/org/apache/iceberg/InheritableMetadataFactory.java
- core/src/main/java/org/apache/iceberg/ManifestEntry.java
- core/src/main/java/org/apache/iceberg/ManifestFilterManager.java
- core/src/main/java/org/apache/iceberg/ManifestWriter.java
- core/src/main/java/org/apache/iceberg/V1Metadata.java
- core/src/main/java/org/apache/iceberg/V2Metadata.java
- core/src/test/java/org/apache/iceberg/TableTestBase.java
- core/src/test/java/org/apache/iceberg/TestManifestWriter.java
- core/src/test/java/org/apache/iceberg/TestManifestWriterVersions.java
- core/src/test/java/org/apache/iceberg/TestMergeAppend.java
- core/src/test/java/org/apache/iceberg/TestRewriteFiles.java
- core/src/test/java/org/apache/iceberg/TestRewriteManifests.java
- core/src/test/java/org/apache/iceberg/TestRowDelta.java
- core/src/test/java/org/apache/iceberg/TestSequenceNumberForV2Table.java
- core/src/test/java/org/apache/iceberg/TestV1ToV2RowDeltaDelete.java
- format/spec.md
This PR fixes the behavior of `sequence_number` in `ManifestEntry` to always represent the data sequence number.
> Core: Add dataSequenceNumber to ManifestEntry

- aws/src/main/java/org/apache/iceberg/aws/AwsProperties.java
- aws/src/test/java/org/apache/iceberg/aws/TestAwsProperties.java
User can use `http-client.urlconnection.socket-timeout-ms` and `http-client.urlconnection.connection-timeout-ms` tags to configure the connection and socket timeout for the `UrlConnectionHttpClient`.
Add unit test to check the timeout setting.
> AWS: Add socket connection timeout for UrlConnectionHttpClient

- python/pyiceberg/catalog/rest.py
- python/tests/catalog/test_rest.py
If an implementation of the rest catalog returns something different than we expect, we just propagate the ValidationError, which subclasses the ValueError. When using the CLI, it will tell you that the URI is not set, but actually it is, it is just invalid.
This will return the json to the user, and also tell what's wrong with the response. Hopefully users won't see this ever :)
> Python: Catch ValidationError on invalid REST response

- aws/src/main/java/org/apache/iceberg/aws/AssumeRoleAwsClientFactory.java
- aws/src/test/java/org/apache/iceberg/aws/TestAwsClientFactories.java
Fix the `NotSerializableException` when using `AssumeRoleAwsClientFactory` to configure the spark using `GlueCatalog`.
Compiled iceberg-spark-runtime-3.1 and tested on Glue 3.0.
The following Scala script triggered the exception before the fix and succeeded after the fix:
```
import org.apache.spark.SparkContext
import org.apache.spark.sql.SparkSession
import org.apache.iceberg.Table
import org.apache.iceberg.aws.glue.GlueCatalog
import org.apache.iceberg.catalog.Catalog
import org.apache.iceberg.aws.AssumeRoleAwsClientFactory
import org.apache.iceberg.catalog.TableIdentifier
import org.apache.iceberg.spark.actions.SparkActions
import scala.jdk.CollectionConverters._
object GlueApp {
def main(sysArgs: Array[String]) {
val sparkContext: SparkContext = new SparkContext()
val spark: …
```
> AWS: Fix NotSerializableException when using AssumeRoleAwsClientFactory in Spark

- api/src/main/java/org/apache/iceberg/ContentScanTask.java
- spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkScan.java
#5720 added `estimatedRowsCount` to `ScanTask` and provided an implementation in `ContentScanTask`.
For a `ScanTask` that scans the entire data file, we can do better for this estimate, and return the row count from the metadata.
I added a parameterized test, that fails without this fix, for the parquet and orc format (it passes for the avro format). Instead of returning a count of 10000 for the number of rows (we wrote 10000 rows), it returns 9998 for parquet and 9937 for orc. With the fix, the row count is 10000 for all 3 formats.
In case a file is bigger than the read split size, then there is no escaping underestimating the row count, because whenever the `scannedFileFraction` < 1.0, there is rounding down when multiplying the row count by the fraction and casting to long.
Note: This …
> API: Fix estimated row count in ContentScanTask

- core/src/main/java/org/apache/iceberg/FileCleanupStrategy.java
- core/src/main/java/org/apache/iceberg/IncrementalFileCleanup.java
- core/src/main/java/org/apache/iceberg/ReachableFileCleanup.java
- core/src/main/java/org/apache/iceberg/RemoveSnapshots.java
- core/src/test/java/org/apache/iceberg/TestRemoveSnapshots.java
Currently, Snapshot expiration has a limitation which prevents file cleanup from being performed if there are multiple branches and tags. That's because for reliable file cleanup in the presence of multiple references, a reachability analysis needs to be performed to determine which files can safely be removed. The existing incremental file cleanup cannot be performed in this case.
This PR introduces a FileCleanupStrategy which is a base strategy pattern that classes override with their own file cleanup logic. There are 2 strategy implementations
1.) IncrementalFileCleanup which is used in RemoveSnapshots procedure in the case there's only 1 reference. This is simply the existing file cleanup logic. 
2.) A new ReachableFileCleanup which performs a reachability analysis of reachable …
> Core: Expire Snapshots reachability analysis

- python/pyiceberg/avro/reader.py
This is only a cosmetic bug, because it would take the Type from the decorator. Also, removed the types from the decorator to reduce visual noise.
> Python: Fix annotation StringType ➜ BinaryType

- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/SparkBatch.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/SparkScan.java
This PR splits `SparkScan` (logical representation) and `SparkBatch` (physical representation) into multiple classes and implements proper equality in `SparkBatch` so that `BatchScanExec` would work as expected in Spark.
> Spark 3.3: Split SparkScan and SparkBatch

- core/src/main/java/org/apache/iceberg/SerializableTable.java
- core/src/test/java/org/apache/iceberg/hadoop/TestTableSerialization.java
Closes https://github.com/apache/iceberg/issues/5974
> Core/Spark: Fix kryo deserialization of `SerializableTable`

- flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/TestFlinkUpsert.java
- flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/TestFlinkUpsert.java
as what stevenzwu said in https://github.com/apache/iceberg/pull/5050 , the tables in TestFlinkUpsert was not partitioned by date, which would bring about  confusion, needed to be refactored.
> Flink: revise unit test of FlinkUpsert so the table is partitioned by date

- core/src/main/java/org/apache/iceberg/AllManifestsTable.java
- core/src/main/java/org/apache/iceberg/ReachableFileUtil.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/actions/BaseSparkAction.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/actions/ExpireSnapshotsSparkAction.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/actions/TestExpireSnapshotsAction.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/data/TestHelpers.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/actions/BaseSparkAction.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/actions/ExpireSnapshotsSparkAction.java
- spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/actions/TestExpireSnapshotsAction.java
- spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/data/TestHelpers.java
Expire snapshots can take a long time for large tables with millions of files and thousands of snapshots/manifests.
One cause is the calculation of files to be deleted.  The current algorithm is:
-  Find the reachability graph of all snapshots before expiration
-  Find reachability graph of all snapshots after expiration
-  Subtract the second from the first, these are files to delete
But this explores every retained snapshot twice.  Example: any periodic expire-snapshot job that expires 1 snapshot needs to explore all n-1 snapshots twice.
Proposal:
- Find reachability graph of all snapshots after expiration
- Find reachability graph of expired snapshots (if only a few expired, should be much smaller set)
- Subtract the first from the second, these are files to delete
Implementation: For …
> Spark: Improve performance of expire snapshot by not double-scanning retained Snapshots

- docs/hive.md
corrects the glue catalog class path name when using (Glue catalog with Hive engine).
> Docs: Fix incorrect glue catalog class name for Hive

- core/src/main/java/org/apache/iceberg/RemoveSnapshots.java
By default, `ExpireSnapshotsSparkAction` cleans the expired files but the log says not cleaning the files. 
`22/08/09 11:03:43 INFO RemoveSnapshots: Cleaning up manifest and data files disabled, leaving them in place`
So, this log is confusing the users. 
[ExpireSnapshotsSparkAction](https://github.com/apache/iceberg/blob/master/spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/actions/ExpireSnapshotsSparkAction.java#L155) calls some code that is common for non-distributed and distributed expire snapshot job.
So, update the common code to print the clean up logs only if the files are cleaned up.
> Core: Fix confusing log from RemoveSnapshots

- api/src/main/java/org/apache/iceberg/BatchScan.java
- api/src/main/java/org/apache/iceberg/BatchScanAdapter.java
- api/src/main/java/org/apache/iceberg/Scan.java
- api/src/main/java/org/apache/iceberg/Table.java
- api/src/main/java/org/apache/iceberg/TableScan.java
- core/src/test/java/org/apache/iceberg/TestBatchScans.java
This PR adds a new scan type called `BatchScan` that is supposed to gradually replace `TableScan`.
The primary motivation for adding the new interface:
- An ability to produce tasks that are don't inherit `FileScanTask`.
- An ability to deprecate `CombinedScanTask` and `DataTask` (currently extends `FileScanTask`) in the future.
There is an ongoing effort to add the `position_deletes` metadata table, which requires the scan to produce a new task type that must be treated by readers in a special way. If we make `DeleteFileScanTask` extend `FileScanTask`, existing readers may break as they would treat `DeleteFileScanTask` as a regular `FileScanTask`. It is pretty much the same situation we have today with `DataTask`, where readers do an explicit check if a task is `DataTask` and then handle …
> API: Add BatchScan to Table

- docs/spark-queries.md
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/IcebergSource.java
Was trying to follow this documentation to load a table from HadoopCatalog, and noticed this snippet does not work as is for me (Spark 3.2).
> Docs: Typo in loading table from DataFrameReader

- python/pyiceberg/catalog/__init__.py
- python/pyiceberg/catalog/rest.py
- python/pyiceberg/cli/console.py
- python/pyiceberg/exceptions.py
- python/tests/catalog/test_rest.py
401 also returns oauth token reponse
https://github.com/apache/iceberg/blob/master/open-api/rest-catalog-open-api.yaml#L170-L178
- This also removes the `BadCredentialsError` and replaces it with the `OAuthError`.
- Checks if there is a semicolon in the credential, and throws a nice error if not.
> Python: Cleanup inconsistency in OAuth responses

- aws/src/main/java/org/apache/iceberg/aws/AwsProperties.java
Proposing to fix exception message that contains an unnecessary format specifier string `%s`.
cc: @pvary
> AwsProperties prints format specifier in IllegalArgumentException message

- spark/v2.4/spark/src/jmh/java/org/apache/iceberg/spark/source/parquet/IcebergSourceFlatParquetDataWriteBenchmark.java
- spark/v3.0/spark/src/jmh/java/org/apache/iceberg/spark/source/parquet/IcebergSourceFlatParquetDataWriteBenchmark.java
- spark/v3.1/spark/src/jmh/java/org/apache/iceberg/spark/source/parquet/IcebergSourceFlatParquetDataWriteBenchmark.java
- spark/v3.2/spark/src/jmh/java/org/apache/iceberg/spark/source/parquet/IcebergSourceFlatParquetDataWriteBenchmark.java
- spark/v3.3/spark/src/jmh/java/org/apache/iceberg/spark/source/parquet/IcebergSourceFlatParquetDataWriteBenchmark.java
fix https://github.com/apache/iceberg/issues/5990
Spark 3.3 downloaded from https://www.apache.org/dyn/closer.lua/spark/spark-3.3.0/spark-3.3.0-bin-hadoop3.tgz
```
export SPARK_HOME="/Users/stevezhang/workspace/spark/spark-3.3.0-bin-hadoop3"
./gradlew -DsparkVersions=3.3 :iceberg-spark:iceberg-spark-3.3_2.12:jmh \
-PjmhIncludeRegex=IcebergSourceFlatParquetDataWriteBenchmark \
-PjmhOutputPath=benchmark/iceberg-source-flat-parquet-data-write-benchmark-result.txt
```
After my change, I am now seeing correct report generated
```
Iteration   1: 19.017 s/op
Iteration   2: 18.209 s/op
Iteration   3: 19.078 s/op
Iteration   4: 22.087 s/op
Iteration   5: 18.014 s/op
Result "org.apache.iceberg.spark.source.parquet.IcebergSourceFlatParquetDataWriteBenchmark.writeFileSource":
N = 5
mean =     19.281 …
```
> Spark: Fix DATE_ADD expression in IcebergSourceFlatParquetDataWriteBenchmark

- core/src/main/java/org/apache/iceberg/MergeAppend.java
- core/src/main/java/org/apache/iceberg/StreamingDelete.java
- core/src/test/java/org/apache/iceberg/TableTestBase.java
- core/src/test/java/org/apache/iceberg/TestDeleteFiles.java
- core/src/test/java/org/apache/iceberg/TestMergeAppend.java
- core/src/test/java/org/apache/iceberg/TestRemoveSnapshots.java
I realized as I was implementing some of the snapshot producing operations for branches, that one operation that could be handled in a straightforward manner was delete files. It also helps with writing some of the test cases for the implementation of branch operations because for some of those tests we want to delete files on a given branch. So separating out this PR.
cc: @rdblue @jackye1995 @namrathamyske
> Support performing merge appends and delete files on branches

- api/src/main/java/org/apache/iceberg/transforms/Transforms.java
This commit fixes typos in the Javadoc for month/day/hour transforms.
> Doc: Fix typos related to date transforms

- flink/v1.14/build.gradle
- flink/v1.14/flink-runtime/src/integration/java/org/apache/iceberg/flink/IcebergConnectorSmokeTest.java
- flink/v1.15/build.gradle
- flink/v1.15/flink-runtime/src/integration/java/org/apache/iceberg/flink/IcebergConnectorSmokeTest.java
#5410 added monitor metrics for Flink and the intention there was to include `org.apache.flink:flink-metrics-dropwizard` into the runtime jar. However, due to `exclude group: 'org.apache.flink'` for the entire `implementation` configuration, that dependency never made it into the jar. This can also be seen by looking at the latest [Flink Runtime Jar](https://repository.apache.org/content/groups/snapshots/org/apache/iceberg/iceberg-flink-runtime-1.15/0.15.0-SNAPSHOT/iceberg-flink-runtime-1.15-0.15.0-20221018.002238-86.jar) that is being published to the Snapshot repo.
When using that runtime jar, things will fail with a `NoClassDefFoundError` as can be seen below:
```
java.lang.NoClassDefFoundError: com/codahale/metrics/Reservoir
at …
```
> Flink: Fix NoClassDefFound with Flink runtime jar / Add integration test

- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/SparkScan.java
This PR removes redundant imports in Spark 3.2 to fix the build.
> Spark 3.2: Remove redundant imports in SparkScan

- core/src/test/java/org/apache/iceberg/util/TestSnapshotUtil.java
Fixed a random bug. Test case failed when the commit time was equal to the current system time. Introduce it in #6005 
Fix to use `snapshot time +1`
> Core: Fix TestSnapshotUtil time random disorder

- core/src/main/java/org/apache/iceberg/FileCleanupStrategy.java
- core/src/main/java/org/apache/iceberg/IncrementalFileCleanup.java
- core/src/main/java/org/apache/iceberg/ReachableFileCleanup.java
Follow up PR to https://github.com/apache/iceberg/pull/5669. 
1.) Parallelizing determining the reachable manifests given a set of snapshots
2.) Cleaning up issues in log messages https://github.com/apache/iceberg/pull/5669#discussion_r993986722 and  https://github.com/apache/iceberg/pull/5669#discussion_r993984959
> Core: Parallelize the determining of reachable manifests during file cleanup

- build.gradle
- core/src/main/java/org/apache/iceberg/TableProperties.java
- docs/configuration.md
- orc/src/main/java/org/apache/iceberg/orc/ORC.java
- orc/src/test/java/org/apache/iceberg/orc/TestBloomFilter.java
Issue link: https://github.com/apache/iceberg/issues/5218
Add `write.orc.bloom.filter.columns` and `write.orc.bloom.filter.fpp` options.
Enable these options in ORC class.
> Orc: Support row group bloom filters

- python_legacy/iceberg/core/filesystem/s3_filesystem.py
Importing s3_filesystem module will initialize boto client which will generate network IO, thus make this as lazy initialization.
I can't find similar thing in python module right now, please suggest if I should change other places for similar reasons.
> [python_legacy] BOTO_STS_CLIENT lazy initialization

- core/src/main/java/org/apache/iceberg/rest/RESTSessionCatalog.java
Metrics reporting via REST could temporarily fail for multiple reasons, such as Network hiccups or timeouts. That shouldn't interfere with scan planning overall.
> Core: Don't fail scan planning if REST metric reporting fails

- nessie/src/main/java/org/apache/iceberg/nessie/NessieTableOperations.java
- nessie/src/main/java/org/apache/iceberg/nessie/NessieUtil.java
- nessie/src/test/java/org/apache/iceberg/nessie/TestNessieUtil.java
The table metadata JSON can become quite big, actually too big, hitting HTTP limits. This change removes the previously introduced storage of Iceberg metadata in Nessie. We will come up with a better solution.
> Nessie: no longer push whole metadata JSON to Nessie

- core/src/main/java/org/apache/iceberg/rest/HTTPClient.java
- core/src/main/java/org/apache/iceberg/rest/HTTPClientFactory.java
- core/src/main/java/org/apache/iceberg/rest/RESTCatalog.java
- core/src/main/java/org/apache/iceberg/rest/RESTSessionCatalog.java
- core/src/test/java/org/apache/iceberg/rest/TestHTTPClient.java
- core/src/test/java/org/apache/iceberg/rest/TestRESTCatalog.java
I think we don't need to have `HTTPClientFactory` in order to init a `HTTPClient` as it requires to pass a map with the URI. We can rather just use the `HTTPClient.builder()` directly with the URI.
Additionally, this allows to pass the `HTTPClient` a custom `ObjectMapper` rather than always defaulting to `RESTObjectMapper.mapper()`
> Core: Deprecate HTTPClientFactory / Allow configuring ObjectMapper for HTTPClient

- hive-metastore/src/main/java/org/apache/iceberg/hive/HiveCatalog.java
- hive-metastore/src/test/java/org/apache/iceberg/hive/TestHiveCatalog.java
Currently Iceberg limits the Hive properties that can be configured onto a catalog to `uri -> hive.metastore.uris` and `warehouse -> hive.metastore.warehouse.dir`.
This limits the ability to configure the metastore client being set up. For example in a secure set up when using delegation tokens we need to configure different values for `hive.metastore.token.signature` for each metastore service.
We need a means for configuring each client differently on some properties and others are generic as derived from the classpath.
In this patch we allow any catalog properties that start with `hive.` to be passed on to the configuration used for creating the MetastoreClient.
Unit test was added to verify the above functionality and no regression failures.
> Closes #5988 - Allow configuration of Hive MetastoreClient using Catalog properties

- python/pyiceberg/expressions/__init__.py
- python/pyiceberg/expressions/visitors.py
- python/tests/expressions/test_expressions.py
- python/tests/expressions/test_visitors.py
- python/tests/test_schema.py
Move the expressions to `__init__.py` and the visitors to visitors.py
I also played around with a bound.py, but it is so intertwined with the unbound, that I think it makes more sense to have it into a single file.
> Python: Split expressions base

- docs/spark-ddl.md
This is just a rebased version of #4606 opened by @kyle-cx since the spark-ddl.md file has been moved up one directory.
> docs:Add an example of CTAS with PARTITIONED BY (rebased, fix #3854)

- core/src/main/java/org/apache/iceberg/TableProperties.java
- hive-metastore/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java
- hive-metastore/src/test/java/org/apache/iceberg/hive/TestHiveCatalog.java
When HiveCatalog is used for creating a table the table owner property is taken from a system property of the process running Iceberg. However, in some clients (e.g. Apache Impala) it's not the owner of the process who runs the create table operation and as a result not the desired owner gets written to HMS.
For instance, in Impala's case the owner of Catalogd (the process that makes the Iceberg API calls) was set as the table owner and not the user who ran the CREATE TABLE statement.
I changed HiveCatalog to accept an owner parameter from the clients. Note, other Catalog implementations aren't affected because the issue is related to HMS only.
> Core, Hive-metastore: Table owner can be incorrect in HMS

- .baseline/checkstyle/checkstyle.xml
- flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/source/enumerator/TestContinuousIcebergEnumerator.java
- flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/source/enumerator/TestContinuousIcebergEnumerator.java
- spark/v2.4/spark/src/test/java/org/apache/iceberg/spark/data/TestSparkParquetReader.java
- spark/v3.0/spark/src/test/java/org/apache/iceberg/spark/data/TestSparkParquetReader.java
- spark/v3.1/spark/src/test/java/org/apache/iceberg/spark/data/TestSparkParquetReader.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/data/TestSparkParquetReader.java
- spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/data/TestSparkParquetReader.java
Will be rebased once https://github.com/apache/iceberg/pull/6029 is merged.
Most of the time using Hamcrest Matchers is much more clunky and so we
should rather use AssertJ assertions as those are more fluent and more
flexible in their usage & readability.
> Replace and ban hamcrest usage

- api/src/main/java/org/apache/iceberg/expressions/ExpressionUtil.java
- api/src/test/java/org/apache/iceberg/expressions/TestExpressionUtil.java
This updates expression sanitization to produce relative date/time strings rather than generic `(date)` and `(timestamp)` literals.
For dates within the last 90 days, the sanitized values are shown in days relative to the current date: `(date-today)`, `(date-N-days-ago)`, and `(date-N-days-from-now)`. For timestamps, the sanitized values are shown relative to the current timestamp in hours or in days: `(timestamp-about-now)` within 5 minutes, `(timestamp-N-hours-ago)` within 3 days, and `(timestamp-N-days-from-now)` within 90 days.
Thanks to @kbendick for originally suggesting this.
> API: Update expression sanitization for relative dates and times

- python/pyiceberg/io/pyarrow.py
- python/tests/io/test_pyarrow.py
This is required for manually specifying datasets: https://arrow.apache.org/docs/python/dataset.html#manual-specification-of-the-dataset
From PyArrow:
The `dataset()` function allows easy creation of a Dataset viewing a directory, crawling all subdirectories for files, and partitioning information. However sometimes discovery is not required and the dataset’s files and partitions are already known (for example, when this information is stored in metadata). In this case, it is possible to create a Dataset explicitly without any automatic discovery or inference.
> Python: Visitor to convert Iceberg to PyArrow schema

- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/BaseBatchReader.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkReaderDeletes.java
This is a port of https://github.com/apache/iceberg/pull/6026 to spark/v3.2.
> Spark 3.2: Ensure rowStartPosInBatch in ColumnarBatchReader is set correctly

- docs/flink-getting-started.md
- flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/FlinkConfParser.java
- flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/FlinkWriteConf.java
- flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/FlinkWriteOptions.java
- flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java
- flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/sink/RowDataTaskWriterFactory.java
- flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/source/RowDataRewriter.java
- flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/sink/TestCompressionSettings.java
- flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/sink/TestDeltaTaskWriter.java
- flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/sink/TestTaskWriters.java
- flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/source/TestProjectMetaColumn.java
Based on my performance tests using `snappy` codec to write out files is 40% more performant that writing with gzip.
Since with Flink there is an additional compaction step which overwrites the original data files anyway, it would be useful to first write out the files with `snappy` and use the table codec only at the compaction time.
To provide this functionality additional `FlinkWriteOptions` are added to modify the table default settings for:
- compression-codec
- compression-level - For Parquet and Avro formats
- compression-strategy - For ORC formats
> Flink: Add Sink options to override the compression properties of the Table

- core/src/main/java/org/apache/iceberg/GenericManifestEntry.java
- core/src/main/java/org/apache/iceberg/InheritableMetadataFactory.java
- core/src/main/java/org/apache/iceberg/ManifestEntry.java
- core/src/main/java/org/apache/iceberg/ManifestWriter.java
- core/src/main/java/org/apache/iceberg/V1Metadata.java
- core/src/main/java/org/apache/iceberg/V2Metadata.java
- core/src/test/java/org/apache/iceberg/TableTestBase.java
- core/src/test/java/org/apache/iceberg/TestFastAppend.java
- core/src/test/java/org/apache/iceberg/TestManifestWriter.java
- core/src/test/java/org/apache/iceberg/TestManifestWriterVersions.java
- core/src/test/java/org/apache/iceberg/TestMergeAppend.java
- core/src/test/java/org/apache/iceberg/TestReplacePartitions.java
- core/src/test/java/org/apache/iceberg/TestRewriteFiles.java
- core/src/test/java/org/apache/iceberg/TestRowDelta.java
- core/src/test/java/org/apache/iceberg/TestSequenceNumberForV2Table.java
- core/src/test/java/org/apache/iceberg/TestV1ToV2RowDeltaDelete.java
- format/spec.md
- spark/v2.4/spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSourceTablesBase.java
- spark/v3.0/spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSourceTablesBase.java
- spark/v3.1/spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSourceTablesBase.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSourceTablesBase.java
- spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSourceTablesBase.java
This PR adds `file_sequence_number` to `ManifestEntry` to keep track of the sequence number at which a file was added.
> Core: Add file seq number to ManifestEntry

- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/source/BatchDataReader.java
- spark/v3.1/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkReaderDeletes.java
This is a port of https://github.com/apache/iceberg/pull/6026 to spark/v3.1.
This is not a direct port, as the 3.1 code base lags the 3.3 and 3.2 code base, but it is fairly straightforward.
> Spark 3.1: Ensure rowStartPosInBatch in ColumnarBatchReader is set correctly

- core/src/main/java/org/apache/iceberg/BaseTableScan.java
- core/src/main/java/org/apache/iceberg/metrics/ScanReport.java
- core/src/main/java/org/apache/iceberg/metrics/ScanReportParser.java
- core/src/test/java/org/apache/iceberg/metrics/TestScanReport.java
- core/src/test/java/org/apache/iceberg/metrics/TestScanReportParser.java
- core/src/test/java/org/apache/iceberg/rest/requests/TestReportMetricsRequestParser.java
- open-api/rest-catalog-open-api.yaml
The motivation behind this change is that the projected schema might get quite big and contain information such as doc comments, which make it quite hard to read/consume. This change makes sure that we only include the minimal set of information from a schema
(schemaId/fieldIds/fieldNames).
> Core: Replace projected Schema with schemaId/fieldIds/fieldNames in ScanReport

- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkReaderDeletes.java
In #6041, I ended up with a slightly different version of `TestSparkReaderDeletes` for v3.2 than in v3.3 because I created the PR before #6026 (the original PR, for v3.3) was merged and I then made some tweaks to `TestSparkReaderDeletes` for #6026. Here I align the version of `TestSparkReaderDeletes` in v3.2 with the version in v3.3. For future backports, it is easier when the 3.2 code base is the same as the 3.3 code base where there is no reason to be different.
> Spark 3.2: #6041 follow-up/cleanup

- build.gradle
- spark/v3.3/build.gradle
This PR update Spark to 3.3.1.
Spark 3.3.1 release notes:
https://spark.apache.org/releases/spark-release-3-3-1.html
> Build: Update Spark to 3.3.1

- python/pyiceberg/io/pyarrow.py
- python/tests/io/test_pyarrow.py
The Iceberg spec keeps timestamp in microsecond format so we should convert to a PyArrow type that doesn't lose precision.
The [Iceberg spec](https://iceberg.apache.org/docs/latest/schemas/) indicates timestamps "stored as microseconds."
I don't yet have any unit tests that validate this fix. I found the issue testing @Fokko's new code with my own internal table where I got the following error:
```
Traceback (most recent call last):
File "/read_test.py", line 47, in <module>
at = ds.to_table()
File "pyarrow/_dataset.pyx", line 331, in pyarrow._dataset.Dataset.to_table
File "pyarrow/_dataset.pyx", line 2577, in pyarrow._dataset.Scanner.to_table
File "pyarrow/error.pxi", line 144, in pyarrow.lib.pyarrow_internal_check_status
File "pyarrow/error.pxi", line 100, in pyarrow.lib.check_status …
```
> PyArrow should convert timestamps to microseconds.

- spark/v3.3/build.gradle
- spark/v3.3/spark-extensions/src/main/scala/org/apache/spark/sql/execution/dynamicpruning/RowLevelCommandDynamicPruning.scala
- spark/v3.3/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/SparkRowLevelOperationsTestBase.java
- spark/v3.3/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestCopyOnWriteDelete.java
- spark/v3.3/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestCopyOnWriteMerge.java
- spark/v3.3/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestCopyOnWriteUpdate.java
- spark/v3.3/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestDelete.java
- spark/v3.3/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMerge.java
- spark/v3.3/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestUpdate.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/SparkCopyOnWriteScan.java
This PR enables using a separate scan during file filtering in row-level copy-on-write operations. This means the runtime filter subquery will now be able to push down filters into row groups as well as prune columns. This should make the initial filtering phase more efficient.
> Spark 3.3: Use separate scan during file filtering in copy-on-write operations

- spark/v3.0/spark/src/main/java/org/apache/iceberg/spark/procedures/ExpireSnapshotsProcedure.java
- spark/v3.0/spark/src/main/java/org/apache/iceberg/spark/procedures/RemoveOrphanFilesProcedure.java
- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/procedures/ExpireSnapshotsProcedure.java
- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/procedures/RemoveOrphanFilesProcedure.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/procedures/ExpireSnapshotsProcedure.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/procedures/RemoveOrphanFilesProcedure.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/procedures/ExpireSnapshotsProcedure.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/procedures/RemoveOrphanFilesProcedure.java
max_concurrent_deletes is already validated for greater than 0 in the preconditions.
```
Preconditions.checkArgument(
maxConcurrentDeletes == null || maxConcurrentDeletes > 0,
"max_concurrent_deletes should have value > 0,  value: " + maxConcurrentDeletes);
```
> Spark: Remove redundant check for max_concurrent_deletes in spark actions

- .github/workflows/publish-snapshot.yml
Iceberg Spark-3.3 also supports scala-2.13 build. So, including this in the nightly build publish.
> Infra: Publish nightly build for Spark-3.3_2.13

- .github/ISSUE_TEMPLATE/iceberg_question.yml
Recently we have updated slack invite link in [iceberg-docs repo](https://github.com/apache/iceberg-docs/pull/169). It needs to be updated here also.
> Infra: Update slack invite link

- .github/ISSUE_TEMPLATE/iceberg_bug_report.yml
No option to select latest release while reporting issue. Hence, added.
> Infra: Add 1.0.0 in issue template dropdown

- spark/v3.2/build.gradle
- spark/v3.2/spark-extensions/src/main/scala/org/apache/spark/sql/execution/dynamicpruning/RowLevelCommandDynamicPruning.scala
- spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/SparkRowLevelOperationsTestBase.java
- spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestCopyOnWriteDelete.java
- spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestCopyOnWriteMerge.java
- spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestCopyOnWriteUpdate.java
- spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestDelete.java
- spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMerge.java
- spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestUpdate.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/SparkCopyOnWriteScan.java
This PR cherry-picks PR #6077 to Spark 3.2.
> Spark 3.2: Use separate scan during file filtering in copy-on-write ops

- spark/v3.3/build.gradle
This PR contains a change to relocate all Netty dependencies, including `netty-common`. Prior to this, we relocated only `netty-buffer` and `netty-common` libs were packaged in the runtime jar.
Below is the content of the runtime jar before this change.
> Spark 3.3: Relocate all Netty dependencies

- spark/v3.2/build.gradle
This PR is a cherry-pick of PR #6107 to Spark 3.2.
> Spark 3.2: Relocate all Netty classes

- spark/v3.0/spark/src/main/java/org/apache/iceberg/spark/procedures/ExpireSnapshotsProcedure.java
- spark/v3.0/spark/src/main/java/org/apache/iceberg/spark/procedures/RemoveOrphanFilesProcedure.java
- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/procedures/ExpireSnapshotsProcedure.java
- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/procedures/RemoveOrphanFilesProcedure.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/procedures/ExpireSnapshotsProcedure.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/procedures/RemoveOrphanFilesProcedure.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/procedures/ExpireSnapshotsProcedure.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/procedures/RemoveOrphanFilesProcedure.java
Removed the redundant space before `value`, and avoid the string concatenation by passing the `maxConcurrentDeletes` as an argument.
This is a follow-up, found after https://github.com/apache/iceberg/pull/6083.
> Spark: Optimize Preconditions.checkArgument in procedures

- README.md
While working on https://github.com/apache/iceberg/pull/6096, I learnt that `./gradlew spotlessApply` only works on default versions. I assumed that it works for all the folders. Which was not true.
Hence, updating the document for new users.
> Docs: Update spotless apply command for non-default versions

- core/src/main/java/org/apache/iceberg/util/JsonUtil.java
- core/src/test/java/org/apache/iceberg/metrics/TestScanReportParser.java
- core/src/test/java/org/apache/iceberg/puffin/TestFileMetadataParser.java
- core/src/test/java/org/apache/iceberg/util/TestJsonUtil.java
This aligns all collection methods to show the same error message and
behave the same with null/empty/invalid json values.
Additionally, this also adds the property name of the collection when
showing an error message.
This PR will be rebased once #6047 is in
> Core: Improve collection handling in JsonUtil 

- python/.pre-commit-config.yaml
- python/CONTRIBUTING.md
- python/pyiceberg/avro/codecs/__init__.py
- python/pyiceberg/avro/file.py
- python/pyiceberg/avro/reader.py
- python/pyiceberg/catalog/__init__.py
- python/pyiceberg/expressions/literals.py
- python/pyiceberg/utils/schema_conversion.py
Instead of using the runtime types that are available using the futures import (in Python 3.8):
```python
from __future__ import annotations
```
I prefer to use the types from Typing:
- I think `Optional[str]` is easier to read than `str | None`.
- Not all types are available, so we have to import from Types anyway (typevar, Callable, etc)
PyUpgrade was rewriting the [imports automatically](https://github.com/asottile/pyupgrade#pep-585-typing-rewrites), so we ended up with a mix, but I think it is better to stay consistent. I've disabled this on PyUpgrade.
> Python: Use Types from Typing

- python/pyiceberg/catalog/__init__.py
- python/pyiceberg/catalog/rest.py
- python/pyiceberg/io/fsspec.py
Small follow-up on https://github.com/apache/iceberg/pull/6019. This sets the token in the properties as well.
> Python: Add the REST token to the properties

- python/poetry.lock
- python/pyproject.toml
PR https://github.com/apache/iceberg/pull/6076 fails because the poetry update command also bumped the version of FastAvro.
I don't think this is wanted behavior, therefore I suggest pinning the versions, instead of providing a lower bound. Dependabot will take care of the bumping of the versions every week. In this PR I also helped dependabot by already bumping some versions.
> Python: Pin versions explicitly

- .github/workflows/python-ci-docs.yml
Github pages break every time we do a force push because it removes the `CNAME` file. This will fix it.
> Python: Fix Github pages

- core/src/main/java/org/apache/iceberg/BaseRewriteManifests.java
- core/src/main/java/org/apache/iceberg/FastAppend.java
- core/src/main/java/org/apache/iceberg/FileCleanupStrategy.java
- core/src/main/java/org/apache/iceberg/ManifestFiles.java
- core/src/main/java/org/apache/iceberg/ManifestReader.java
- core/src/main/java/org/apache/iceberg/MergingSnapshotProducer.java
This patch aims to reduce the time of Iceberg task planning. We notice the task plan could not benefit from ParallelIterator a lot when there are many manifest files to read. The problem is the ManifestReader needs to read the manifest file to get the PartitionSpec which is not needed for most cases (because the ManifestFile object has the PartitionSpec Id and the Table has the mapping from PartitionSpec Id to PartitionSpec). It needs to read all these manifest files in serial when the following code of ParallelIterator is initing. And this is very slow when the HDFS traffic is busy. 
https://github.com/apache/iceberg/blob/dbb8a404f6632a55acb36e949f0e7b84b643cede/core/src/main/java/org/apache/iceberg/util/ParallelIterable.java#L62 …
> Core: Avoid reading ManifestFile when create ManifestReader

- python/pyiceberg/expressions/visitors.py
@Fokko I'm playing with the new Manifest evaluator from #5845.
I had to make the included change to get that to work.  I know this is early days for this code but it's useful functionality even now.
> Struct fields should be provided to Schema constructor

- core/src/main/java/org/apache/iceberg/BaseMetastoreTableOperations.java
- core/src/main/java/org/apache/iceberg/rest/RESTTableOperations.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/actions/BaseTableCreationSparkAction.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/procedures/AddFilesProcedure.java
Followup for  https://github.com/apache/iceberg/issues/4582, handle custom metadata location trailing slash stripping.
related issue : https://github.com/aws-samples/dbt-glue/pull/108
> [Core | Spark] Strip trailing slash from custom metadatalocation

- api/src/main/java/org/apache/iceberg/util/BucketUtil.java
- api/src/test/java/org/apache/iceberg/transforms/TestBucketing.java
- format/spec.md
This commit changes the hashing of float/double for negative zero (-0.0) to produce the same hash as for positive zero (0.0). This is needed because positive/ negative zero are considered equal according to ==, but have distinct bit patterns according to
Double#doubleToLongBits. Therefore, using these bit patterns directly would violate the assumption "x = y implies bucket(x) = bucket(y)". With this commit, the bit pattern for negative zero is replaced with the bit pattern for positive zero before hashing, to ensure both produce the same hash.
Double negative zero has the bit pattern 0x8000000000000000, (which matches the bit pattern of Long.MIN_VALUE), whereas the bit pattern for positive zero is 0x0000000000000000.
> API: Hash floats -0.0 and 0.0 to the same bucket

- python/poetry.lock
- python/pyproject.toml
The mmh3 project is abandoned, and not being maintained.
This results in there being no wheels (compiled binaries) available for newer versions of Python (3.10 and 3.11). I've forked the repo and created a new release with the binaries for the latest versions of Python.
Solves #5901
> Python: Replace mmh3 with mmhash3

- api/src/main/java/org/apache/iceberg/expressions/Expressions.java
- api/src/test/java/org/apache/iceberg/expressions/TestAggregateBinding.java
Follow up [PR](https://github.com/apache/iceberg/pull/5961) to address a few comments:
- https://github.com/apache/iceberg/pull/5961#discussion_r1004975423
- https://github.com/apache/iceberg/pull/5961#discussion_r1005406682
- https://github.com/apache/iceberg/pull/5961#discussion_r1005408297
> Fix TestAggregateBinding

- python/pyiceberg/expressions/literals.py
- python/pyiceberg/utils/datetime.py
- python/tests/expressions/test_literals.py
- python/tests/test_transforms.py
* Renamed date_to_days to date_str_to_days
* Created new date_to_days to convert a Python date object to int days
* Contributes to workaround for #6120
> Python: Support creating a DateLiteral from a date (#6120)

- python/pyiceberg/expressions/visitors.py
@Fokko here's another runtime bug I'm seeing while playing with this new Manifest evaluator (#5845)
> Fix typo in `_ManifestEvalVisitor.visit_equal`

- python/pyiceberg/avro/reader.py
- python/pyiceberg/expressions/literals.py
- python/pyiceberg/io/pyarrow.py
- python/pyiceberg/types.py
- python/tests/test_types.py
* Replaces `.length` property with the pythonic `__len__` method on `FixedReader` and `FixedType` to enable use of `len()` built-in.
> Python: Use pythonic `len()` built-in instead of `length` property

- core/src/main/java/org/apache/iceberg/avro/BuildAvroProjection.java
- core/src/test/java/org/apache/iceberg/MetadataTableScanTestBase.java
- core/src/test/java/org/apache/iceberg/TestMetadataTableScans.java
- core/src/test/java/org/apache/iceberg/TestMetadataTableScansWithPartitionEvolution.java
As #4576 described, we got a `SchemaParseException ` when reading the metadata table. The root cause is that Avro does not support a name containing dot(.).  For example, `Identity(data.id)`. In this case, the partition field named with `data.id` is illegal for Avro, so we need to rewrite it to meet the Avro field name requirements.
> Fixes read metadata table failed due to illegal character

- core/src/main/java/org/apache/iceberg/rest/CatalogHandlers.java
- core/src/main/java/org/apache/iceberg/rest/HTTPClient.java
- core/src/main/java/org/apache/iceberg/rest/RESTClient.java
- core/src/main/java/org/apache/iceberg/rest/RESTSessionCatalog.java
- core/src/test/java/org/apache/iceberg/catalog/CatalogTests.java
- core/src/test/java/org/apache/iceberg/rest/RESTCatalogAdapter.java
- core/src/test/java/org/apache/iceberg/rest/TestHTTPClient.java
The motivation behind this change is that the REST server should know whether a `purge` was requested or not, rather than having the REST client throw an error.
> Core: Pass purgeRequested flag to REST server

- python_legacy/tox.ini
The CI is failing because a new version of mypy has been released yesterday: https://pypi.org/project/mypy/0.982/
> Python: Pin mypy in Python Legacy

- .github/workflows/api-binary-compatibility.yml
- .palantir/revapi.yml
- build.gradle
Update to the latest release and enable CI running for just the `revapi.yml` file change
> Build: Let revapi compare API compatibility against apache-iceberg-1.0.0

- core/src/main/java/org/apache/iceberg/TableProperties.java
I introduced this property in #5763, however, I learned since that its value doesn't follow the naming conventions for a table property. Fortunately the change hasn't been released yet so we can safely change this property before we release 1.1.0. and won't hurt backward compatibility.
> Core: Rename HMS_TABLE_OWNER to follow naming convention

- .github/workflows/python-ci.yml
The `setup-python@v4` action supports caching for poetry lock files as shown over here: https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#caching-packages
> Python: CI poetry cache

- core/src/main/java/org/apache/iceberg/rest/RESTSessionCatalog.java
- core/src/test/java/org/apache/iceberg/rest/TestRESTCatalog.java
This PR adds query params to the REST config route that are used to sync configuration between the REST client and service.
Right now, this sends the only client catalog property that needs to be in sync between the client and service, the warehouse location. Iceberg catalogs allow setting the warehouse location as standard catalog config on the client. This introduces a problem when using those catalog implementations behind the REST API because the service doesn't know what the client's warehouse location was set to.
To keep the client config in sync, this sends the properties to the config route, where the service can choose how to handle the client config. In the tests, the service overrides the client's warehouse config to ensure the two are in sync.
> Core: Sync client/server properties in REST catalog

- flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/FlinkWriteConf.java
- flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/FlinkWriteOptions.java
- flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java
- flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/RowDataTaskWriterFactory.java
- flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/source/RowDataRewriter.java
- flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/sink/TestCompressionSettings.java
- flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/sink/TestDeltaTaskWriter.java
- flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/sink/TestTaskWriters.java
- flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/source/TestProjectMetaColumn.java
Flink: Port #6049 to Flink 1.14 in order to add Sink options of compression properties.
These codes has been included in Flink 1.16 since #6092.
> Flink: Port #6049 to Flink 1.14 to add Sink options of compression properties

- python/pyiceberg/table/__init__.py
- python/tests/table/test_init.py
This adds an implementation of TableScan that is an alternative to the one in https://github.com/apache/iceberg/pull/6131. This doesn't implement plan_files, it is just to demonstrate a possible scan API:
```python
scan = table.scan(
row_filter=In("id", [5, 6, 7]),
selected_fields=("id", "data"),
snapshot_id=1234567890
)
```
> Python: Add initial TableScan implementation

- python/pyiceberg/catalog/__init__.py
- python/pyiceberg/catalog/hive.py
- python/pyiceberg/catalog/rest.py
- python/pyiceberg/io/__init__.py
- python/pyiceberg/table/__init__.py
- python/tests/catalog/test_base.py
- python/tests/catalog/test_rest.py
- python/tests/cli/test_console.py
- python/tests/table/test_init.py
Follow up on: https://github.com/apache/iceberg/pull/6161#discussion_r1018547445
Another option is to move it to the constructor of the Table and not store the properties.
> Python: Move FileIO initialization to the catalog

- python/pyiceberg/catalog/hive.py
I happened to notice this typo, which seems obviously wrong. The code isn't yet exercised anywhere so it's not a big deal but figured I might as well fix it.
> Fix typo in unused python iceberg paramter

- aws/src/integration/java/org/apache/iceberg/aws/lakeformation/LakeFormationTestBase.java
The glue catalog names set in the Lake Formation test are reversed.
> AWS: Fix catalog names in LakeFormationTestBase

- python/pyiceberg/expressions/literals.py
- python/tests/expressions/test_literals.py
Currently, we silently turn Literals into `None` if we can't convert them, instead I prefer to raise an exception. This can cause silent bugs like: `EqualTo(Reference("id"), StringLiteral("123a"))` will turn into a `IsNull` predicate since `123a` cannot be casted to a `Long` (assuming that the `id` column is a Long). 
This PR also:
- Adds support for casting a `StringLiteral` to a `LongLiteral`
- Also fixed the return types. The type checker couldn't work with it, so it was silently ignored. Now it works again by adding the annotations. The main `to` in the superclass returns a literal, therefore `AboveMax` and `BelowMin` also need to be literal. We can also turn this into a `Union[Literal, AboveMin, AboveMax]`.
~~Blocked on https://github.com/apache/iceberg/pull/6140~~
> Python: Make invalid Literal conversions explicit

- api/src/main/java/org/apache/iceberg/ContentScanTask.java
- api/src/main/java/org/apache/iceberg/FileScanTask.java
- api/src/main/java/org/apache/iceberg/PartitionScanTask.java
- api/src/main/java/org/apache/iceberg/util/StructProjection.java
- core/src/main/java/org/apache/iceberg/util/TableScanUtil.java
- core/src/test/java/org/apache/iceberg/MockFileScanTask.java
- core/src/test/java/org/apache/iceberg/util/TestTableScanUtil.java
This adds a new method: `TableScanUtil.planTaskGroups`, that allow Iceberg splits combining to only happen within partitions. This is a pre-requisite for Iceberg to start exposing table distribution and ordering spec to Spark in order to enable features such as storage-partitioned join.
A new interface `PartitionScanTask` is also introduced to represent scan tasks whose data come from a single partition.
> Core: Add a util method to combine tasks by partition

- spark/v3.3/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRewriteManifestsProcedure.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/SparkValueConverter.java
Solves https://github.com/apache/iceberg/issues/5104
Presently when `spark.sql.datetime.java8API.enabled` is set to true, 
- java.time.LocalDate is returned for Spark SQL DATE type
- java.time.Instant is returned for Spark SQL TIMESTAMP type
so always casting date type to java.sql.Date or timestamp to java.sql.Timestamp is not correct and can lead to class cast exception. This change attempts to use appropriate api's from DateTimeUtils class which take these scenarios into consideration and calls the relevant api's as per the object type.
```scala
/**
* Converts an Java object to days.
*
* @param obj Either an object of `java.sql.Date` or `java.time.LocalDate`.
* @return The number of days since 1970-01-01.
*/
def anyToDays(obj: Any): Int = obj match {
case d: Date => fromJavaDate(d)
case …
```
> Spark: Fix QueryFailure when running RewriteManifestProcedure on Date partitioned table

- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/actions/RewriteManifestsSparkAction.java
- spark/v3.3/spark/src/test/java/org/apache/iceberg/ValidationHelpers.java
- spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteManifestsAction.java
This PR preserves file seq numbers while rewriting manifests in Spark 3.3.
> Spark 3.3: Preserve file seq numbers while rewriting manifests

- docs/flink-getting-started.md
page link [write options](#Write options) under [UPSERT](https://iceberg.apache.org/docs/latest/flink/#upsert)  is wrong.
> Docs: fix link of `Write options` in Flink

- core/src/main/java/org/apache/iceberg/util/TableScanUtil.java
#2276 accidentally left an unused method `toTaskGroupStream` (which is replaced by `toTaskGroupIterable`). This removes it.
> Core: Remove unused toTaskGroupStream from TableScanUtil

- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/actions/RewriteManifestsSparkAction.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/ValidationHelpers.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteManifestsAction.java
This PR backports PR #6176 into 3.2.
> Spark 3.2: Preserve file seq numbers while rewriting manifests

- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/actions/BaseRewriteManifestsSparkAction.java
- spark/v3.1/spark/src/test/java/org/apache/iceberg/ValidationHelpers.java
- spark/v3.1/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteManifestsAction.java
This PR backports PR https://github.com/apache/iceberg/pull/6176 into 3.1.
> Spark 3.1: Preserve file seq numbers while rewriting manifests

- docs/flink-getting-started.md
- flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/FlinkCatalog.java
- flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/FlinkCatalogFactory.java
- flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/TestFlinkCatalogTablePartitions.java
- flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/FlinkCatalog.java
- flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/FlinkCatalogFactory.java
- flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/TestFlinkCatalogTablePartitions.java
- flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/FlinkCatalog.java
- flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/FlinkCatalogFactory.java
- flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/TestFlinkCatalogTablePartitions.java
As what https://github.com/apache/iceberg/pull/3543 has introduced, 'cache.expiration-interval-ms' option allows user to configure caching policy.
But this parameter has not been added in FlinkCatalog yet, This pr is aiming to do that.
> Flink: Add 'cache.expiration-interval-ms' option to FlinkCatalog

- core/src/main/java/org/apache/iceberg/MetadataUpdate.java
- core/src/main/java/org/apache/iceberg/TableMetadata.java
- core/src/main/java/org/apache/iceberg/rest/RESTSessionCatalog.java
This PR adds assigning the metadata UUID to the metadata change list for create table transactions when using the REST catalog. Currently the metadata UUID isn't being passed, which could lead to an inconsistent UUID when writing the data versus committing the metadata.
> REST: Assign metadata UUID on create transaction

- python/pyiceberg/expressions/literals.py
- python/pyiceberg/utils/datetime.py
- python/tests/expressions/test_literals.py
From https://github.com/apache/iceberg/pull/6141, for follow-up:
> Fix types returned by to when AboveMax/BelowMin are returned
Fixed
- Add tests for binding with invalid conversions
Added some tests to cover the last few uncovered lines:
```
poetry run coverage report -m --fail-under=90
Name                                       Stmts   Miss  Cover   Missing
------------------------------------------------------------------------
...
pyiceberg/expressions/literals.py            331      0   100%
```
- Update binding to rewrite expressions when AboveMax and BelowMin are returned
First thing after https://github.com/apache/iceberg/pull/6139 has been merged
- Check whether we need AboveMax/BelowMin for longs, since Python uses arbitrary precision numbers
Do you mean when you run Python on a …
> Python: Fix rough edges around literals

- python/pyiceberg/avro/reader.py
- python/pyiceberg/expressions/__init__.py
- python/pyiceberg/expressions/visitors.py
- python/pyiceberg/files.py
- python/pyiceberg/schema.py
- python/pyiceberg/typedef.py
- python/tests/expressions/test_evaluator.py
- python/tests/test_schema.py
Implement an expression evaluator in Python. This is needed for pruning data files based on the partition tuple in a manifest file.
This also makes a few of other changes:
* Moves `StructProtocol` to `typedef`
* Adds a `value_set` to `BoundSetPredicate` for faster in and not in evaluation
> Python: Add expression evaluator

- api/src/main/java/org/apache/iceberg/PartitionField.java
- api/src/main/java/org/apache/iceberg/PartitionSpec.java
- api/src/main/java/org/apache/iceberg/SortField.java
- api/src/main/java/org/apache/iceberg/UnboundPartitionSpec.java
- api/src/main/java/org/apache/iceberg/transforms/ProjectionUtil.java
- core/src/main/java/org/apache/iceberg/util/SortOrderUtil.java
Debugging some regression that we have at Trino, this PR seems to fix a part of it. 
It looks like we've deprecated this a bit too fast. Instead, when we read the PartitionSpec from the manifest, we should bind them to [maintain compatibility with 1.0.0](
https://github.com/apache/iceberg/blob/1.0.x/api/src/main/java/org/apache/iceberg/transforms/Transform.java#L42).
```
java.lang.UnsupportedOperationException: hash(value) is not supported on the base Bucket class
at org.apache.iceberg.transforms.Bucket.hash(Bucket.java:90)
at org.apache.iceberg.transforms.Bucket.apply(Bucket.java:99)
at org.apache.iceberg.transforms.Bucket.apply(Bucket.java:38)
at io.trino.plugin.iceberg.IcebergPageSink.applyTransform(IcebergPageSink.java:372)
at …
```
> API: Make the PartitionSpec less lazy

- spark/v3.1/spark/src/jmh/java/org/apache/iceberg/spark/source/WritersBenchmark.java
Saw this noise in the logs, and figured it would be nice to remove the noise
> Spark: Add missing override

- api/src/main/java/org/apache/iceberg/transforms/Transforms.java
I noticed this is the only transform that does a case-sensitive equal. Looks like this is a copy-paste error
> API: Ignore case when comparing truncate

- python/pyiceberg/avro/reader.py
- python/pyiceberg/catalog/rest.py
- python/pyiceberg/expressions/__init__.py
- python/pyiceberg/expressions/literals.py
- python/pyiceberg/expressions/visitors.py
- python/pyiceberg/io/fsspec.py
- python/pyiceberg/io/pyarrow.py
- python/pyiceberg/manifest.py
- python/pyiceberg/schema.py
- python/pyiceberg/table/metadata.py
- python/pyiceberg/table/partitioning.py
- python/pyiceberg/table/sorting.py
- python/pyiceberg/transforms.py
- python/pyiceberg/utils/bin_packing.py
- python/pyiceberg/utils/deprecated.py
- python/pyiceberg/utils/parsing.py
- python/pyiceberg/utils/schema_conversion.py
- python/pyiceberg/utils/singleton.py
- python/pyproject.toml
- python/tests/expressions/test_expressions.py
- python/tests/expressions/test_visitors.py
- python/tests/test_transforms.py
Mypy allows us to warn when a type is missing:
`List`, should be `List[str]`
This way we don't accidentally forget any type (which happens to me all the time :). I just ignored, added `Any` to most of the current violations, and also fixed some of them.
> Python: Disallow Any generics

- python/pyiceberg/expressions/__init__.py
- python/pyiceberg/expressions/literals.py
- python/pyiceberg/transforms.py
- python/tests/expressions/test_literals.py
- python/tests/test_transforms.py
- Adds projection for each of the transforms
- Removes the dataclasses from the expressions. I noticed that the IDE didn't like the way we were using the dataclasses in a hierarchical structure: 
It complaints about unexpected arguments. Also, noticed that mypy was struggling with it. I've removed the dataclasses and added the abstract classes. I've implemented the `__eq__` and `__repr__` where required. Also removed some inconsistencies along the way (`In` was expecting a tuple, and `BoundIn` a set).
More tests still to be added
> Python: Projection

- core/src/test/java/org/apache/iceberg/TestSortOrder.java
Adding a unit test to make sure a column that USED to be a part of a sort order but NO LONGER is, is allowed to be dropped.
> Allow dropping a column used by old SortOrders but not current SortOrder

- nessie/src/main/java/org/apache/iceberg/nessie/NessieIcebergClient.java
- nessie/src/main/java/org/apache/iceberg/nessie/NessieTableOperations.java
Move core logic from `NessieTableOperations#doCommit` to `NessieIcebergClient#commitTable` because Trino Nessie catalog integration (https://github.com/trinodb/trino/pull/11701) don't use Iceberg's `NessieTableOperation` directly. 
Hence to avoid code duplication, move common logic to `NessieIcebergClient`
> Nessie: Refactor NessieTableOperations#doCommit

- api/src/main/java/org/apache/iceberg/SortOrder.java
- api/src/main/java/org/apache/iceberg/UnboundSortOrder.java
- api/src/main/java/org/apache/iceberg/transforms/Identity.java
- api/src/main/java/org/apache/iceberg/transforms/Transforms.java
- api/src/test/java/org/apache/iceberg/transforms/TestIdentity.java
This caused some regression for the Iceberg 1.1.0 release:
```
2022-11-21T12:05:46.6549795Z [ERROR] io.trino.plugin.iceberg.TestIcebergSystemTables.testManifestsTable  Time elapsed: 0.701 s  <<< FAILURE!
2022-11-21T12:05:46.6550853Z java.lang.AssertionError:
2022-11-21T12:05:46.6551986Z [Rows for query [SELECT added_data_files_count, existing_rows_count, added_rows_count, deleted_data_files_count, deleted_rows_count, partitions FROM test_schema."test_table$manifests"]]
2022-11-21T12:05:46.6553075Z Expecting:
2022-11-21T12:05:46.6553593Z   <(2, 0, 3, 0, 0, [[false, false, 18148, 18149]]), (2, 0, 3, 0, 0, [[false, false, 18147, 18148]])>
2022-11-21T12:05:46.6553980Z to contain exactly in any order:
2022-11-21T12:05:46.6554557Z   <[(2, 0, 3, 0, 0, [[false, false, 2019-09-08, 2019-09-09]]), …
```
> API: Restore the type of the identity transform

- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/functions/SparkFunctions.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/functions/UnaryUnboundFunction.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/functions/YearsFunction.java
- spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/sql/TestSparkYearsFunction.java
This PR adds `years` transform function to Spark 3.3.
> Spark 3.3: Add years transform function

- flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/FlinkCatalogTestBase.java
- flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/FlinkTestBase.java
- flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/TestChangeLogTable.java
- flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/TestFlinkHiveCatalog.java
- flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/source/TestFlinkTableSource.java
FLINK-29677 add a check, so the currently used `Catalog` could not be dropped.
FLINK-29677 will land in Flink 1.16.1, and 1.17.0 and when we start to use it we need to update some of our tests.
This PR creates a method `pushCatalog` to store the current catalog, and `popCatalog` to restore this old catalog. This should be used to restore the original catalog before dropping the one used in the tests.
> Flink: Fix tests creating catalog after FLINK-29677

- api/src/main/java/org/apache/iceberg/transforms/Dates.java
- api/src/main/java/org/apache/iceberg/transforms/Timestamps.java
This should fix the ErrorProne warning
```
> Task :iceberg-api:compileJava
/home/nastra/Development/workspace/iceberg/api/src/main/java/org/apache/iceberg/transforms/Timestamps.java:69: warning: [ImmutableEnumChecker] enums should be immutable: 'Timestamps' has field 'apply' of type 'org.apache.iceberg.util.SerializableFunction<java.lang.Long,java.lang.Integer>', the declaration of type 'org.apache.iceberg.util.SerializableFunction<java.lang.Long,java.lang.Integer>' is not annotated with @com.google.errorprone.annotations.Immutable
private final SerializableFunction<Long, Integer> apply;
^
(see https://errorprone.info/bugpattern/ImmutableEnumChecker)
/home/nastra/Development/workspace/iceberg/api/src/main/java/org/apache/iceberg/transforms/Dates.java:66: warning: [ImmutableEnumChecker] …
```
> API: Fix ErrorProne warning around Immutable Enums

- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/functions/MonthsFunction.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/functions/SparkFunctions.java
- spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/sql/TestSparkMonthsFunction.java
This PR adds `months` transform function to Spark 3.3.
> Spark 3.3: Add months transform function

- python_legacy/tox.ini
Flake8 6.0.0 has been released, and this breaks the build.
> Python-legacy: Pin flake8

- open-api/rest-catalog-open-api.yaml
This is a minor clarification to the REST catalog spec. When a request is unauthenticated or unauthorized, the REST service must respond with a correct HTTP error code and must not return fake success responses. For example, if a request to load a table is unauthorized, the service cannot return fake table metadata to signal that the table exists but cannot be used.
> Spec: Clarify auth responses in the REST spec

- format/gcm-stream-spec.md
@rdblue @RussellSpitzer @jackye1995
> AES GCM Stream Spec

- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/actions/RewriteDataFilesSparkAction.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/actions/SparkBinPackStrategy.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/actions/SparkSortStrategy.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/actions/SparkZOrderStrategy.java
Currently, during Spark's rewrite data files procedure with bin pack strategy, `SparkSession` is cloned to disable AQE in each `rewriteFiles`. Since a cloned `SparkSession` has its own state, V2SessionCatalog is reloaded every time and a separate table cache is created. That means each file group has its own table cache and effectively disables the table cache.
This PR fixes it by cloning `SparkSession` when creating `SparkBinPackStrategy`.
> Spark: Fix a separate table cache being created for each rewriteFiles

- python/pyiceberg/avro/decoder.py
- python/pyiceberg/avro/file.py
This improves Avro scan performance when using PyArrowFileIO by about 10x by ensuring that scans are buffered and updating EOF handling. I was testing scan planning and found that S3 planning took about 130 seconds. Buffering the input stream and avoiding the `len(input_file)` call gets the planning time for the same query to 13 seconds.
The main problem was that the stream provided by PyArrow was not buffered, so nearly every read operation was causing another request to S3.
A second issue was that the call to get the file length was expensive, so this also updates the decoder to throw `EOFException` rather than checking file length. This improved the performance by about 1 second in my test.
> Python: Fix Avro scan performance in PyArrow

- docs/reliability.md
While reading the documentation, I found that there is a duplicate word in reliability.md, I submitted this pr to fix it, this is a small problem.
> Docs: Fix typo of reliability.md

- .github/ISSUE_TEMPLATE/iceberg_bug_report.yml
As 1.1.0 release is pushed to maven central, 
https://repo1.maven.org/maven2/org/apache/iceberg/iceberg-spark-runtime-3.3_2.13/1.1.0/
Also dependabots / renovate bots started raising version bump PR.  https://github.com/projectnessie/nessie/pull/5582
> Infra: Add 1.1.0 to issue template

- python/pyiceberg/expressions/literals.py
- python/pyiceberg/expressions/parser.py
- python/pyproject.toml
- python/tests/expressions/test_literals.py
- python/tests/expressions/test_parser.py
This adds a simple expression parser based on pyparsing.
> Python: Add boolean expression parser

- python/pyiceberg/expressions/__init__.py
- python/pyiceberg/expressions/literals.py
- python/tests/expressions/test_expressions.py
- python/tests/expressions/test_literals.py
When we have an expression `EqualTo('a', IntegerType.max + 1)`, that will result in an `AboveMax` literal. This means that the value cannot be in the values because it is out of bounds.
We can use this information in the optimizer to skip the files where this is the case.
Closes #6203
> Python: Skip in the case of AboveMax and BelowMin

- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/functions/DaysFunction.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/functions/SparkFunctions.java
- spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/sql/TestSparkDaysFunction.java
This PR adds `days` transform function to Spark 3.3.
> Spark 3.3: Add days transform function

- api/src/main/java/org/apache/iceberg/BaseScanTaskGroup.java
- api/src/main/java/org/apache/iceberg/EmptyStructLike.java
- api/src/main/java/org/apache/iceberg/ScanTaskGroup.java
- core/src/main/java/org/apache/iceberg/PartitionData.java
- core/src/main/java/org/apache/iceberg/util/TableScanUtil.java
This PR adds `groupingKey` to `ScanTaskGroup` so that we can later report it to query engines.
> API, Core: Add groupingKey to ScanTaskGroup

- build.gradle
We should merge this once 1.1.0 has been released
> Build: Let revapi compare against 1.1.0

- core/src/main/java/org/apache/iceberg/BaseMetastoreTableOperations.java
- core/src/test/java/org/apache/iceberg/catalog/CatalogTests.java
- docs/configuration.md
- docs/maintenance.md
The issue came up in a [slack discussion](https://apache-iceberg.slack.com/archives/C025PH0G1D4/p1668714478198079?thread_ts=1668645354.671479&cid=C025PH0G1D4) and also in https://github.com/apache/iceberg/issues/6105.
> Core: Add test + clarify behavior of write.metadata.delete-after-commit.enabled flag

- core/src/main/java/org/apache/iceberg/TableProperties.java
This table property was shipped with [1.1.0](https://github.com/apache/iceberg/blob/apache-iceberg-1.1.0/core/src/main/java/org/apache/iceberg/TableProperties.java#L363) and then removed by https://github.com/apache/iceberg/pull/6045 before we configured RevAPI to compare against 1.1.0 in #6275
CI is currently failing on `master` with:
```
* Just this break:
./gradlew :iceberg-core:revapiAcceptBreak --justification "{why this break is ok}" \
--code "java.field.removedWithConstant" \
--old "field org.apache.iceberg.TableProperties.HMS_TABLE_OWNER"
* All breaks in this project:
./gradlew :iceberg-core:revapiAcceptAllBreaks --justification "{why this break is ok}"
* All breaks in all projects:
./gradlew revapiAcceptAllBreaks --justification "{why this break is ok}" …
```
> Core: Re-add and deprecate HMS_TABLE_OWNER to TableProperties

- core/src/main/java/org/apache/iceberg/jdbc/JdbcUtil.java
Users are running into issues when hooking up the `JdbcCatalog` with `MySql` or other Databases, which actually impose lower limits than [sqlite](https://www.sqlite.org/limits.html) (which we use for testing the `JdbcCatalog`.
fixes #6236 
fixes #5027
fixes #6332
> Core: Use lower lengths for iceberg_namespace_properties / iceberg_tables in JdbcCatalog

- spark/v2.4/spark/src/main/java/org/apache/iceberg/spark/actions/BaseRewriteManifestsSparkAction.java
- spark/v2.4/spark/src/test/java/org/apache/iceberg/ValidationHelpers.java
- spark/v2.4/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteManifestsAction.java
I've ran into this while working on https://github.com/apache/iceberg/pull/6274. This backports https://github.com/apache/iceberg/pull/6193 to Spark 2.4
> Spark 2.4: Preserve file seq numbers while rewriting manifests

- python/pyiceberg/table/__init__.py
```python
➜  python git:(master) ✗ python3
Python 3.10.8 (main, Oct 13 2022, 09:48:40) [Clang 14.0.0 (clang-1400.0.29.102)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyiceberg.catalog import load_catalog
>>>
>>> catalog = load_catalog('local')
>>>
>>> table = catalog.load_table(('nyc', 'taxis'))
>>>
>>> table.scan().to_arrow()
/Users/fokkodriesprong/Desktop/iceberg/python/pyiceberg/table/__init__.py:340: UserWarning: Projection is currently done by name instead of column ID, this can lead to incorrect results in some cases.
```
> Python: Add warning on projection by name

- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/functions/HoursFunction.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/functions/SparkFunctions.java
- spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/sql/TestSparkHoursFunction.java
This PR adds `hours` transform function in Spark 3.3.
> Spark 3.3: Add hours transform function

- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/SparkBatch.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/SparkBatchQueryScan.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/SparkCopyOnWriteScan.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/SparkFilesScan.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/SparkScan.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/SparkScanBuilder.java
This PR allows using passing arbitrary scans in `SparkBatchQueryScan`. This change is needed to support tables that only implement the `BatchScan` interface. In addition, it migrates to `ScanTaskGroup` API, which is required for storage-partitioned joins.
> Spark 3.3: Consume arbitrary scans in SparkBatchQueryScan

- build.gradle
Default behavior is one compiler instance per "session", this change updates it to keep the compiler alive with the Gradle daemon. (This uses a new feature from Gradle 7.6.)
> Gradle build: keep Scala compiler alive

- python/pyiceberg/io/pyarrow.py
It turns out that we need to cast the literal to the right type:
```
ArrowNotImplementedError: Function 'greater_equal' has no kernel matching input types (timestamp[us, tz=+00:00], int64)
```
After casting the scalar, it works perfectly. One awkward thing to note is that we don't have to do this for the `isin` predicate. Where this is done for us. Please check the Jupyter notebook:
> Python: Fix PyArrow Type conversion

- api/src/main/java/org/apache/iceberg/types/Type.java
- api/src/main/java/org/apache/iceberg/types/TypeUtil.java
Deserialization of POJOs in Flink will call the default parameterless constructor to generate a new instance.
However, `Comparators` uses the `PrimitiveType` instance as the key of `Map`:
https://github.com/apache/iceberg/blob/master/api/src/main/java/org/apache/iceberg/types/Comparators.java#L33-L47
We need to override `equals` and `hashCode` methods for primitive types, otherwise, exception will occur after serializing `Schema`:
```
java.lang.UnsupportedOperationException: Cannot determine comparator for type: int
at org.apache.iceberg.types.Comparators.forType(Comparators.java:71)
at org.apache.iceberg.types.Comparators.internal(Comparators.java:77)
at org.apache.iceberg.types.Comparators.access$300(Comparators.java:31)
at org.apache.iceberg.types.Comparators$StructLikeComparator.lambda …
```
> API: Override `equals` and `hashCode` methods for primitive types

- core/src/main/java/org/apache/iceberg/io/SingleBufferInputStream.java
**What does this PR do?**
Changes the variable name `offset` to `off` in the `SingleBufferInputStream` function.
**Why are these changes needed?**
When running `./gradlew build` with `sourceCompatibility = '11'` and `targetCompatibility = '11'` instead of `1.8`, the build is blocked by a `ConsistentOverrides` error:
```
iceberg/core/src/main/java/org/apache/iceberg/io/SingleBufferInputStream.java:67: error: [ConsistentOverrides] Method overrides should have variable names consistent with the super-method when there are multiple parameters with the same type to avoid incorrectly binding values to variables.
public int read(byte[] bytes, int offset, int len) throws IOException {
^
(see https://github.com/palantir/gradle-baseline#baseline-error-prone-checks)
Did you mean 'public int …
```
> Change SingleBufferInputStream .read signature to match super-method.

- api/src/main/java/org/apache/iceberg/catalog/ViewCatalog.java
- api/src/main/java/org/apache/iceberg/exceptions/NoSuchViewException.java
- api/src/main/java/org/apache/iceberg/view/SQLViewRepresentation.java
- api/src/main/java/org/apache/iceberg/view/UpdateViewProperties.java
- api/src/main/java/org/apache/iceberg/view/View.java
- api/src/main/java/org/apache/iceberg/view/ViewBuilder.java
- api/src/main/java/org/apache/iceberg/view/ViewHistoryEntry.java
- api/src/main/java/org/apache/iceberg/view/ViewRepresentation.java
- api/src/main/java/org/apache/iceberg/view/ViewVersion.java
Co-authored-by: anjalinorwood@gmail.com
> API: Add view interfaces

- bundled-guava/src/main/java/org/apache/iceberg/GuavaClasses.java
- flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/source/IcebergSource.java
- flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/source/assigner/SimpleSplitAssigner.java
- flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/source/assigner/SplitAssigner.java
- flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/source/enumerator/ContinuousIcebergEnumerator.java
- flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/source/enumerator/ContinuousSplitPlannerImpl.java
- flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/source/enumerator/EnumerationHistory.java
- flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/source/enumerator/IcebergEnumeratorState.java
- flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/source/enumerator/IcebergEnumeratorStateSerializer.java
- flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/source/enumerator/StaticIcebergEnumerator.java
- flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/source/enumerator/ManualContinuousSplitPlanner.java
- flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/source/enumerator/TestContinuousIcebergEnumerator.java
- flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/source/enumerator/TestContinuousSplitPlannerImpl.java
- flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/source/enumerator/TestEnumerationHistory.java
- flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/source/enumerator/TestIcebergEnumeratorStateSerializer.java
there are two scenarios why throttling is desirable for streaming read.
1) large backlog. E.g., started the streaming job from earliest snapshot
2) intentionally delayed consumption. E.g., if we have a stream join job reading from two Iceberg tables. First table has more real-time data and second table has typically delayed data (e.g. 24 hours). It would be great to delay the consumption for the second table by 24 hours for event time alignment. This way, we can reduce the join window in Flink state. With delayed consumption, it doesn't make sense to discovery all 24 hours of splits and hold them in enumerator memory.
> Flink: support split discovery throttling for streaming read

- docs/spark-procedures.md
Some users are using Zorder with spark-3.1 and facing a confusing error message. Hence, updating the document.
Also thought about updating the code to throw the unsupported exception.  But maybe not required to modify the code as it is only the older versions.
> Docs: Update Zorder spark support versions.

- docs/spark-procedures.md
This PR removes backticks from the Spark procedure headings.
Official docs page: https://iceberg.apache.org/docs/latest/spark-procedures/#metadata-information where other headings don't have the backticks.
> Docs: Remove backticks from Spark procedure headings

- python/pyiceberg/cli/console.py
Realized there's type/incorrect description when attempt to set a properties on namespace or table level.
Before the change I saw this
```
$ pyiceberg properties --help
Usage: pyiceberg properties [OPTIONS] COMMAND [ARGS]...
Properties on tables/namespaces
Options:
--help  Show this message and exit.
Commands:
get     Fetch properties on tables/namespaces
remove  Removes properties on tables/namespaces
set     Removes properties on tables/namespaces
```
After it shall be 
```
Commands:
get     Fetch properties on tables/namespaces
remove  Sets a property on tables/namespaces
set     Removes a property on tables/namespaces
```
CC @Fokko
> [Python] Fix incorrect description when set a property

- core/src/main/java/org/apache/iceberg/rest/ErrorHandlers.java
- open-api/rest-catalog-open-api.yaml
This updates the commit error handler to throw `CommitStateUnknownException` for 502 responses. A 502 can be thrown from a load balancer when something goes wrong with the upstream service, after that service successfully commits.
> Core: Throw CommitStateUnknownException for 502 responses

- tasks.gradle
Since site/ folder was added to .gitignore the refreshJavadoc task started to fail. The reson is that as a last step it wanted to do a 'git add' on the Javadoc files under site/docs/javadoc/<VERSION> folder, however it couldn't due to site/ being added to gitignore. The Javadoc files anyway were generated successfully.
Not adding these files to git is on purpose as they are meant to be copied over to iceberg-docs repo and released from there. So this 'git add' step is removed from the task.
> Build: Fix ./gradlew refreshJavadoc

- flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/util/FlinkPackage.java
- flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/util/FlinkPackage.java
- flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/util/FlinkPackage.java
`./gradlew clean build -x test  -x integrationTest` used to be clean without compiler warning. 
#6206 has introduced one compiler warning. Hence, cleaned it up. 
```
/Users/ajantha/Documents/workspace/icebergWorkspace/iceberg/flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/util/FlinkPackage.java:29: warning: [MissingSummary] A summary fragment is required; consider using the value of the @return block as a summary fragment instead.
/** @return Flink version string like x.y.z */
^
(see https://google.github.io/styleguide/javaguide.html#s7.2-summary-fragment)
Did you mean '/** Returns flink version string like x.y.z.'?
```
Before:
After:
> Flink: Fix minor compiler warning

- api/src/main/java/org/apache/iceberg/PartitionSpec.java
- api/src/main/java/org/apache/iceberg/transforms/Transform.java
- api/src/main/java/org/apache/iceberg/transforms/VoidTransform.java
- core/src/main/java/org/apache/iceberg/DataFiles.java
- core/src/main/java/org/apache/iceberg/FileMetadata.java
- core/src/test/java/org/apache/iceberg/TestPartitionSpecInfo.java
- core/src/test/java/org/apache/iceberg/TestPartitioning.java
> Returns isUnpartitioned=true for VoidTransform on all fields

- python/poetry.lock
- python/pyiceberg/table/__init__.py
- python/pyproject.toml
After #6233, we can read Iceberg table to `pandas` DataFrame via Apache Arrow:
```python
table.scan().to_arrow().to_pandas()
```
Since Pandas is most popular python data analysis library, I'd like to add a shortcut to convert `TableScan` to `pd.DataFrame` directly.
```python
table.scan().to_pandas()
```
> Python: implement `to_pandas`

- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/actions/RewriteDataFilesSparkAction.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/actions/SparkBinPackStrategy.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/actions/SparkSortStrategy.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/actions/SparkZOrderStrategy.java
Back-port of https://github.com/apache/iceberg/pull/5392 to Spark 3.2
> Spark 3.2: Fix a separate table cache being created for each rewriteFiles

- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/actions/BaseRewriteDataFilesSparkAction.java
- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/actions/Spark3BinPackStrategy.java
- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/actions/Spark3SortStrategy.java
Back-port of https://github.com/apache/iceberg/pull/5392 to Spark 3.1
> Spark 3.1: Fix a separate table cache being created for each rewriteFiles

- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/data/SparkValueReaders.java
Was going through SparkValueReaders and saw some commented out code which can be removed.
> Spark: Cleanup commented out code in SparkValueReaders

- core/src/main/java/org/apache/iceberg/util/SnapshotUtil.java
- spark/v3.3/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestChangelogTable.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/SparkReadConf.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/SparkReadOptions.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/SparkScanBuilder.java
Per discussion in #6012, I create this PR to support time range query for changelog table. 
cc @aokolnychyi @RussellSpitzer @szehon-ho @rdblue
> Spark 3.3: Time range query of changelog tables

- spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestChangelogTable.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/SparkReadConf.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/SparkReadOptions.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/SparkScanBuilder.java
The Spark 3.2 version of #6350. cc @szehon-ho @RussellSpitzer @aokolnychyi
> Spark 3.2: Time range query of changelog tables

- docs/configuration.md
Docs: Update table snapshot retention property descriptions to explicitly mention that it is a default for all the table's branches.
> Docs: Update table snapshot retention property descriptions 

- docs/spark-ddl.md
add doc for this extension https://github.com/apache/iceberg/pull/2560
> Docs: add example of spark extension for identifier fields

- python/tests/cli/test_console.py
- python/tests/conftest.py
- python/tests/utils/test_config.py
This could be a way to alleviate this issue https://github.com/apache/iceberg/issues/6361. 
Alternative, you could mock `HOME` and `PYICEBERG_HOME` with an empty folder for all tests automatically.
> Python: Mock home and root folder when running `test_missing_uri`

- api/src/main/java/org/apache/iceberg/metrics/LoggingMetricsReporter.java
- core/src/main/java/org/apache/iceberg/CatalogProperties.java
- core/src/main/java/org/apache/iceberg/CatalogUtil.java
- core/src/main/java/org/apache/iceberg/rest/RESTSessionCatalog.java
- core/src/test/java/org/apache/iceberg/TestCatalogUtil.java
- core/src/test/java/org/apache/iceberg/rest/TestRESTCatalog.java
In certain cases it makes sense to make the used metrics reporter customizable, so that users have more control over it and how it's reporting
> Core: Allow configuring metrics reporter impl via Catalog property

- core/src/main/java/org/apache/iceberg/hadoop/HadoopStreams.java
- orc/src/main/java/org/apache/iceberg/orc/FileIOFSUtil.java
- orc/src/main/java/org/apache/iceberg/orc/ORC.java
- orc/src/main/java/org/apache/iceberg/orc/OrcFileAppender.java
- orc/src/test/java/org/apache/iceberg/orc/TestORCFileIOProxies.java
- orc/src/test/java/org/apache/iceberg/orc/TestOrcDataWriter.java
This adds support for FileIO with Apache ORC by wrapping InputFile and OutputFile into a consumable FileSystem objects.
In the absence of this ORC is not able to leverage the benefits of better FileIO such as S3FileIO compared to S3AFileSystem
New unit tests have been added to ensure the use of FileIO in ORC Readers and Writers
> Added FileIO Support for ORC Reader and Writers

- spark/v3.1/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRewriteManifestsProcedure.java
- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/SparkValueConverter.java
- spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRewriteManifestsProcedure.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/SparkValueConverter.java
Backport https://github.com/apache/iceberg/pull/5860 to spark 3.x
cc @aokolnychyi @rdblue @ajantha-bhat
> Spark[3.1 | 3.2]: Support Java 8 time API in SparkValueConverter 

- format/view-spec.md
`parent-version-id` is not mentioned in the spec but the example has the field. 
The latest API implementation also doesn't have it(https://github.com/apache/iceberg/pull/4925)
So, removing it from the examples.
> Docs: Remove parent-version-id from the view spec example

- format/spec.md
Background:
[Spec](https://github.com/apache/iceberg/blob/master/format/spec.md#table-statistics) has a snapshot id in two places, one in `StatisticsFile` and another in its `blob metadata`. 
To support the reuse of statistics files, we should have the referenced snapshot id in `StatisticsFile`, not the computed-from snapshot id. Hence, updated the spec. 
Note that PR https://github.com/apache/iceberg/pull/6090 is stuck because of confusion around stats file reuse.
> Docs: Update spec about statistics file snapshot id

- spark/v3.3/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRewriteDataFilesProcedure.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/procedures/RewriteDataFilesProcedure.java
For `RewriteDataFilesProcedure`, when the table has been created with a default sort order, there should be no need for the user to again specify the same sort order for the sort strategy during re-write. Currently, it fails with `Cannot set strategy sort order: unsorted` error for this scenario.
This particular scenario works with rewrite spark action now also and used to work with `RewriteDataFilesProcedure` too (In 0.13.0 release). 
But while introducing `Zorder` with re-write procedure, a strict check has been introduced which caused this particular scenario to fail.  This would have not happened if we had a test case to catch it. Fixed it now and added the test case.
> Spark-3.3: Use table sort order with sort strategy when user has not specified

- spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRewriteDataFilesProcedure.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/procedures/RewriteDataFilesProcedure.java
Backport of https://github.com/apache/iceberg/pull/6296
> Spark-3.2: Use table sort order with sort strategy when user has not specified

- core/src/main/java/org/apache/iceberg/SnapshotSummary.java
- core/src/test/java/org/apache/iceberg/TestFastAppend.java
- core/src/test/java/org/apache/iceberg/TestRowDelta.java
Previously, having an unpartitioned table would produce a `"partitions."` entry in the snapshot summary when the partition summary limit was configured
> Core: Don't produce partition summaries on unpartitioned table

- aws/src/main/java/org/apache/iceberg/aws/glue/GlueCatalog.java
- aws/src/test/java/org/apache/iceberg/aws/glue/TestGlueCatalog.java
`defaultWarehouseLocation` call to `glue.getDatabase` did not set catalog id while building a request.  
This results in `software.amazon.awssdk.services.glue.model.EntityNotFoundException: Database my_database not found.` error when table is being created in another AWS account.
More details are in https://github.com/apache/iceberg/issues/6215  
@singhpk234 
If you can take a look, it would be appreciated.  
I did not add any tests for it since I saw that similar tests for other methods do not exist.
> AWS: Use provided glue catalog id in defaultWarehouseLocation

- core/src/main/java/org/apache/iceberg/AllManifestsTable.java
We noticed throttling on `getLength` calls to S3 in the all manifests table. This avoids those unnecessary calls by no longer creating a fake `DataFile` or `FileScanTask`. Previously, the manifest list scan task wrapped a file scan task so that it could be read as a normal data file. However, since v2 the task has been converted to a `DataTask` to fill in inherited sequence numbers correctly. As a result, the wrapped `FileScanTask` is no longer needed.
Not creating the wrapped `FileScanTask` make it possible to avoid creating a `DataFile` (unless one is for some reason requested by calling `file()` on the task).
> Core: Refactor ManifestListReadTask to avoid extra S3 calls

- python/pyiceberg/expressions/literals.py
- python/tests/expressions/test_literals.py
I believe this resolves https://github.com/apache/iceberg/issues/6230. 
We could also check for nans in the `literal(.)` factory, but imo that doesn't add anything really.
> Python: Check for nans when creating literal

- flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/IcebergFilesCommitter.java
- flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/sink/IcebergFilesCommitter.java
- flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/sink/IcebergFilesCommitter.java
Add some logging to the `IcebergFilesCommitter`. Otherwise it is hard to follow what happens when multiple commits are in progress.
> Flink: Improve IcebergFilesCommitter logging

- aws/src/main/java/org/apache/iceberg/aws/dynamodb/DynamoDbCatalog.java
- core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java
- dell/src/main/java/org/apache/iceberg/dell/ecs/EcsCatalog.java
- nessie/src/main/java/org/apache/iceberg/nessie/NessieCatalog.java
While reviewing https://github.com/apache/iceberg/pull/6410 (which accesses the catalog properties via `properties()`), I've noticed that not every catalog exposes their properties. This PR aligns the affected catalog with how other catalogs expose their properties.
> Dynamo/Jdbc/Ecs/Nessie: Expose catalog properties

- python/pyiceberg/io/pyarrow.py
It causes to throw a cast exception:
```
---------------------------------------------------------------------------
ArrowNotImplementedError                  Traceback (most recent call last)
Input In [1], in <cell line: 7>()
3 cat = load_catalog('rest')
5 tbl = cat.load_table('fokko.uuid_partitioned')
----> 7 tbl.scan().to_arrow()
File ~/Desktop/iceberg/python/pyiceberg/table/__init__.py:386, in DataScan.to_arrow(self)
375 from pyarrow.dataset import dataset
377 ds = dataset(
378     source=locations,
379     filesystem=fs,
(...)
383     schema=schema_to_pyarrow(self.table.schema()),
384 )
--> 386 return ds.to_table(filter=pyarrow_filter, columns=columns)
File /opt/homebrew/lib/python3.9/site-packages/pyarrow/_dataset.pyx:304, in pyarrow._dataset.Dataset.to_table()
File …
```
> Python: Parse UUID as binary in PyArrow

- core/src/main/java/org/apache/iceberg/BaseTable.java
Delegate from one constructor to the other. This emphasizes the relation between them.
Follows https://github.com/apache/iceberg/pull/5268
> Have single 'working' constructor in BaseTable

- python/pyiceberg/avro/decoder.py
- python/pyiceberg/avro/reader.py
- python/tests/avro/test_decoder.py
This breaks partitioning:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[38], line 3
1 from pyiceberg.expressions import And, GreaterThanOrEqual, LessThan
----> 3 df = tbl.scan(row_filter=And(
4     GreaterThanOrEqual("tpep_pickup_datetime", "2021-04-01T00:00:00.000000+00:00"),
5     LessThan("tpep_pickup_datetime", "2021-05-01T00:00:00.000000+00:00")
6 )).to_arrow().to_pandas()
8 df
File /usr/local/lib/python3.9/site-packages/pyiceberg/table/__init__.py:350, in DataScan.to_arrow(self)
347     fs = self.table.io.get_fs(scheme)
349 locations = []
--> 350 for task in self.plan_files():
351     if isinstance(task, FileScanTask):
352         _, path = …
```
> Python: Read date as an int

- python/pyiceberg/avro/decoder.py
- python/pyiceberg/avro/reader.py
- python/pyiceberg/io/pyarrow.py
- python/pyiceberg/utils/schema_conversion.py
- python/tests/avro/test_decoder.py
- python/tests/avro/test_reader.py
Tested:
```
➜  python git:(fd-fix-uuid1925) ✗ python3
Python 3.10.9 (main, Dec 15 2022, 17:11:09) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyiceberg.catalog import load_catalog
>>>
>>> catalog = load_catalog('rest')
>>>
>>> tbl = catalog.load_table('fokko.uuid_partitioned')
>>>
>>> tbl.scan().to_arrow()
/Users/fokkodriesprong/Desktop/iceberg/python/pyiceberg/table/__init__.py:340: UserWarning: Projection is currently done by name instead of Field ID, this can lead to incorrect results in some cases.
warnings.warn(
pyarrow.Table
identifier: fixed_size_binary[16]
----
identifier: [[A61DC527E858449E9D22C77D90B53A41],[A61DC527E858449E9D22C77D90B53A40],...,[A61DC527E858449E9D22C77D90B53A31],[A61DC527E858449E9D …
```
> Python: Fix reading UUIDs

- python/pyiceberg/table/__init__.py
The import should be inline in the function to avoid pulling in PyArrow when we don't need it.
Tested this in a fresh docker container:
```
root@1252c09f932c:/vo# pip3 install -e ".[s3fs]"
Obtaining file:///vo
Installing build dependencies ... done
Checking if build backend supports build_editable ... done
Getting requirements to build editable ... done
Preparing editable metadata (pyproject.toml) ... done
Collecting mmhash3==3.0.1
Downloading mmhash3-3.0.1-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (38 kB)
Collecting pyyaml==6.0.0
Downloading PyYAML-6.0-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (731 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 731.1/731.1 KB 11.0 MB/s eta 0:00:00
Collecting rich==12.6.0
Downloading rich-12.6.0-py3-none-any.whl (237 kB) …
```
> Python: Fix PyArrow import

- api/src/main/java/org/apache/iceberg/types/Types.java
- core/src/main/java/org/apache/iceberg/Partitioning.java
- core/src/test/java/org/apache/iceberg/TestPartitioning.java
- spark/v3.3/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestAlterTablePartitionFields.java
- spark/v3.3/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestCopyOnWriteDelete.java
- spark/v3.3/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestCopyOnWriteMerge.java
- spark/v3.3/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestCopyOnWriteUpdate.java
- spark/v3.3/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestStoragePartitionedJoinsInRowLevelOperations.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/Spark3Util.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/SparkReadConf.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/SparkSQLProperties.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/SparkBatch.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/SparkBatchQueryScan.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/SparkChangelogScan.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/SparkCopyOnWriteScan.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/SparkInputPartition.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/SparkMicroBatchStream.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/SparkPartitioningAwareScan.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/SparkScan.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/SparkScanBuilder.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/SparkWrite.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/StructInternalRow.java
- spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/SparkTestBase.java
- spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/sql/TestStoragePartitionedJoins.java
This PR adds support for storage-partitioned joins in Spark 3.3.
> Spark 3.3: Support storage-partitioned joins

- python/pyiceberg/io/fsspec.py
Otherwise it will throw an error when it isn't installed:
```
│ /Users/fokkodriesprong/Desktop/iceberg/python/pyiceberg/io/fsspec.py:31 in <module>              │
│                                                                                                  │
│    28 from urllib.parse import urlparse                                                          │
│    29                                                                                            │
│    30 import requests                                                                            │
│ ❱  31 from adlfs import AzureBlobFileSystem                                                      │
│    32 from botocore import UNSIGNED                                                              │
│    33 from …
```
> Python: Move `adlfs` import inline

- .github/workflows/python-legacy-ci.yml
- python_legacy/setup.py
It looks like the latest version of `tox` clashes with `tox-travis`.
The tox version wasn't pinned in `tox-travis`, and it would just follow the latest version that's available.
This has been fixed in the repository:
https://github.com/tox-dev/tox-travis/commit/e11bacf107903375b5c42bda799e94f5dbe12978
I think it is good to add this constraint in our `setup.py` as well.
> Python-legacy: Fix CI

- python/pyiceberg/avro/file.py
- python/pyiceberg/avro/reader.py
- python/pyiceberg/avro/resolver.py
- python/pyiceberg/io/pyarrow.py
- python/pyiceberg/schema.py
- python/pyiceberg/typedef.py
- python/pyiceberg/types.py
- python/tests/avro/test_reader.py
- python/tests/avro/test_resolver.py
This refactors the Avro read path to use the newly introduced `SchemaWithPartnerVisitor`. The purpose of this is to make the resolver a little more standard and make it easy to inject types that implement `StructProtocol` for the readers to use. Since the readers are constructed in several places (that all create a new `ConstructReader`) this is refactor is needed.
I didn't quite get finished with this work. The next step is to remove `ConstructReader` and move all reader construction into `SchemaResolver`, then to pass a map of struct constructors into the resolver.
> Python: Refactor Avro read path to use a partner visitor

- parquet/src/main/java/org/apache/iceberg/parquet/ParquetDictionaryRowGroupFilter.java
- parquet/src/test/java/org/apache/iceberg/parquet/TestDictionaryRowGroupFilter.java
This PR fixs ParquetDictionaryRowGroupFilter evaluating `notNaN`. 
Because Parquet dictionaries cannot contain null values, ParquetDictionaryRowGroupFilter should check if there is null values in the column chunk when evaluting `notNaN` and return `true` if yes.
~~This also improves looking up `NaN` value in the dictionary set, in Java, both Double.NaN and Float.NaN are considered to be equal to themselves, so:~~
~~- the dict must contain values that are not `NaN` when its' size is greater than 1, can directly return `true` in this case;~~
~~- can use `Set#contains` to look up `NaN` directly instead of comparing elements in the collection one by one.~~
> Parquet: Fix ParquetDictionaryRowGroupFilter evaluating NaN.

- core/src/main/java/org/apache/iceberg/rest/CatalogHandlers.java
- core/src/test/java/org/apache/iceberg/catalog/CatalogTests.java
**Issue:**
As per documentation of [`SessionCataog.dropTable`](https://github.com/apache/iceberg/blob/2a3a297d134aeaaf2bc19bc75135bea89811228b/api/src/main/java/org/apache/iceberg/catalog/SessionCatalog.java#L180-L189) says 
> Drop a table, without requesting that files are immediately deleted.
But the [`RESTSessionCatalog#dropTable`](https://github.com/apache/iceberg/blob/67b5ca239ead5549122a5b10e8a372cd1c8dca81/core/src/main/java/org/apache/iceberg/rest/RESTSessionCatalog.java#L221-L232) API purges the table even if we are not setting `purgeRequested` to `true`.
The issue is happening because, While handling `DROP_TABLE` request in [`RESTCatalogAdapter`](https://github.com/apache/iceberg/blob/79bf0f69a2ccc723174c40a1678bc0dcdf32ae7f/core/src/test/java/org/apache/iceberg/rest/RESTCatalogA …
> Core: Fix drop table without purge for REST session catalog

- api/src/main/java/org/apache/iceberg/ChangelogOperation.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/ChangelogIterator.java
- spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/SparkTestBase.java
- spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/SparkTestHelperBase.java
- spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/TestChangelogIterator.java
Introduce an iterator to handle changelog rows within a task. It will be used by the changelog procedure #6012.
cc @aokolnychyi @RussellSpitzer @szehon-ho
> Spark 3.3: Introduce the changelog iterator

- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/Spark3Util.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/SparkScanBuilder.java
- spark/v3.3/spark/src/main/scala/org/apache/spark/sql/execution/datasources/SparkExpressionConverter.scala
- spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/SparkTestBase.java
- spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/sql/TestFilterPushDown.java
This PR enhances our filter pushdown logic in Spark 3.3 to discard filters that can be completely evaluated using partition metadata. That way, we can skip evaluating some predicates which we know are always true or false for rows produced by a scan.
This change leverages `ExpressionUtil$selectsPartitions()` that checks if an expression selects partitions by comparing its strict and inclusive projections.
> Spark 3.3: Discard filters that can be pushed down completely

- flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/DataGenerators.java
this is a follow-up to PR #6377
> Flink: add fixed field type for DataGenerators test util

- flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/sink/IcebergFilesCommitter.java
- flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/sink/TestIcebergFilesCommitter.java
Currently the Flink Iceberg commits are identifier by the `table` and the `JobID`. This could become problematic when there are multiple sinks for the same table for the same job.
Let's imagine the following sequence of events:
- Sink1 `notifyCheckpointComplete(99)` commits checkpoint the changes to the Iceberg table, and marks `99` as the latest checkpoint which was committed
- Sink1 `notifyCheckpointComplete(99)` commits checkpoint the changes to the Iceberg table, and marks `99` as the latest checkpoint which was committed
- New checkpoint is created with the id `100`
- Sink1 `notifyCheckpointComplete(100)` commits checkpoint the changes to the Iceberg table, and marks `100` as the latest checkpoint which was committed
- Job is cancelled
- Job is restarted
- Sink1 sees that the latest …
> Flink: Enable multiple flink sinks for the same table in the same job

- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/ChangelogIterator.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/SparkTestBase.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/SparkTestHelperBase.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/TestChangelogIterator.java
This is the Spark 3.2 version of #6344. cc @RussellSpitzer @szehon-ho
> Spark 3.2: Introduce a changelog iterator

- spark/v3.3/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/analysis/RewriteMergeIntoTable.scala
- spark/v3.3/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/RowLevelCommandScanRelationPushDown.scala
- spark/v3.3/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/SparkRowLevelOperationsTestBase.java
- spark/v3.3/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMerge.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/SparkCopyOnWriteOperation.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/SparkWrite.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/SparkWriteBuilder.java
This PR switches all merge-on-read and MERGE copy-on-write operations to use built-in Spark planning. This enables more optimizations for applicable row-level commands like discarding pushed down predicates.
> Spark 3.3: Use regular planning for applicable row-level operations

- core/src/main/java/org/apache/iceberg/actions/RewriteDataFilesCommitManager.java
In order to avoid timing out when writing large manifest files, we increase the timeout allowed for the commit phase of partial progress based on the number of commits left to perform.
Temporary Fix for performance issues in #6367
> Spark: Extend Timeout During Partial Progress Rewrites

- python/mkdocs/docs/verify-release.md
- python/tests/io/test_pyarrow.py
Running the tests in Docker makes sure that the tests aren't affected by the host system:
I had to remove a couple of tests since they don't work inside Docker. This is because by default you're root in docker, and chmod'ing certain directories doesn't work, because you can still read them as root.
> Python: Add Docker suggestion for testing

- python/.pre-commit-config.yaml
- python/README.md
The bug that would mess up the alerts in the docs has been fixed 🥳
> Python: Re-enable mdformat

- python/pyiceberg/catalog/__init__.py
When invoking pyiceberg cli, I get the following:
```shell
$ pyiceberg list
'type' object is not subscriptable
```
> Python: fix cast in console CLI

- python/.pre-commit-config.yaml
It is an issue in a downstream dependency and is currently being fixed in pylint: https://github.com/PyCQA/pylint/pull/8030 but we're still waiting for the release
Has been fixed in Astroid at: https://github.com/PyCQA/astroid/pull/1944
> Python: Add typing-extensions as a pylint dependency

- flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/SimpleDataUtil.java
- flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/SimpleDataUtil.java
- flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/SimpleDataUtil.java
some internal test code (not merged upstream) can use those two util methods
> Flink: make two test util methods public from SimpleDataUtil

- python/pyiceberg/avro/decoder.py
- python/tests/avro/test_decoder.py
When a binary field would be zero bytes, we would still read the stream, causing a EOFErrors:
```
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/Users/fokkodriesprong/Desktop/iceberg/python/pyiceberg/manifest.py", line 139, in read_manifest_entry
for record in reader:
File "/Users/fokkodriesprong/Desktop/iceberg/python/pyiceberg/avro/file.py", line 194, in __next__
return self.__next__()
File "/Users/fokkodriesprong/Desktop/iceberg/python/pyiceberg/avro/file.py", line 186, in __next__
return next(self.block)
File "/Users/fokkodriesprong/Desktop/iceberg/python/pyiceberg/avro/file.py", line 113, in __next__
return self.reader.read(self.block_decoder)
File "/Users/fokkodriesprong/Desktop/iceberg/python/pyiceberg/avro/reader.py", line 260, in read …
```
> Python: Fix reading 0-bytes binary

- core/src/test/java/org/apache/iceberg/io/InMemoryFileIO.java
- core/src/test/java/org/apache/iceberg/io/InMemoryOutputFile.java
- core/src/test/java/org/apache/iceberg/io/TestInMemoryFileIO.java
Add InMemoryFileIO alongside existing InMemoryOutputFile and InMemoryInputFile as a test helper class stitching the two together and maintaining an in-memory listing of files. Add a dedicated unittest for the new test helper.
> Add InMemoryFileIO as a test helper class

- core/src/test/java/org/apache/iceberg/TestCatalogUtil.java
Just while going through this testcase in core,  
felt odd to have an engine-specific naming in the core module as it is common for all the engines/APIs. Hence renamed.
> Core: Minor renaming to avoid engine specific naming in core

- api/src/main/java/org/apache/iceberg/view/SQLViewRepresentation.java
Minor fix for inline comments for fieldComments and fieldAliases, the comments for the two were reversed
> API: Fix comments in SQLViewRepresentation

- spark/v3.3/build.gradle
- spark/v3.3/spark/src/jmh/java/org/apache/iceberg/spark/source/parquet/vectorized/VectorizedReadDictionaryEncodedFlatParquetDataBenchmark.java
- spark/v3.3/spark/src/jmh/java/org/apache/iceberg/spark/source/parquet/vectorized/VectorizedReadFlatParquetDataBenchmark.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/data/vectorized/VectorizedSparkParquetReaders.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/BaseBatchReader.java
This PR adds logic to automatically set Arrow properties for read performance. Unless these properties are set, our read path can be up to 2x slower than built-in read path in Spark.
I verified this patch by removing all explicit settings and running benchmarks with and without setting properties.
Benchmark results without setting Arrow properties:
```
Benchmark                                                              Mode  Cnt  Score   Error  Units
VectorizedReadFlatParquetDataBenchmark.readLongsIcebergVectorized5k      ss    5  1.321 ± 0.029   s/op
VectorizedReadFlatParquetDataBenchmark.readLongsSparkVectorized5k        ss    5  1.064 ± 0.162   s/op
VectorizedReadFlatParquetDataBenchmark.readStringsIcebergVectorized5k    ss    5  2.187 ± 0.031   s/op …
```
> Spark 3.3: Automatically set Arrow properties for read performance

- aws/src/main/java/org/apache/iceberg/aws/s3/S3URI.java
- aws/src/test/java/org/apache/iceberg/aws/s3/TestS3URI.java
Enable users to run read-queries when specifying only S3 bucket name as its Iceberg table location.
Current S3URI ValidationChecker doesn't allow users to specify only bucket name such as `s3://bucket/` or `s3://bucket`.
However, we can specify an only bucket name when creating an Iceberg table. 
For example, if you run the following DDL with Spark, your table location is specified as `s3://bucket`
```
CREATE TABLE catalog.db.table(id int, data string)
USING iceberg
LOCATION 's3://bucket'
```
(If you don't specify `LOCATION`, Spark creates a table under `s3://<warehouse_path>/db.db/table/` by default.)
And you can also run `INSERT INTO` query for this. Through this operation, S3URI handles manifest list, files and metadata json in metadata directory. However, `SELECT` query needs to …
> AWS: Fix inconsistent behavior of naming S3 location between read and write operations by allowing only s3 bucket name

- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/SparkTable.java
- spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/SparkTestBase.java
- spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkTable.java
SPARK-40067 added Table#name() to the BatchScan node on SparkUI.
With this improvement in place, for all DSv2 tables, SparkUI shows
`BatchScan <Table#name>` instead of uninformative `BatchScan`.
In its current state, for iceberg table, SparkUI shows
`BatchScan <catalog_name>.<namespace>.<table>`.
This can be further improved by adding the data source name I.e. Iceberg to the table name thereby yielding the final result as
`BatchScan iceberg <catalog_name>.<namespace>.<table>`.
E.g. `BatchScan Iceberg spark_catalog.default.ui_test_parquet`
Note: SPARK-40067 is available from Spark3.4 and onwards. Since it is not a bug fix, we cannot backport the improvement to OSS Spark3.3. So if one is using Iceberg with OSS Spark3.3 then the improvement won't be visible and uninformative `BatchScan` …
> Spark: Add "Iceberg" prefix to SparkTable name string for better observability of Iceberg tables on SparkUI

- core/src/main/java/org/apache/iceberg/actions/RewriteDataFilesCommitManager.java
Implements the idea proposed in https://github.com/apache/iceberg/issues/6367
Existing UT's
cc @RussellSpitzer @flyrain
> Core: Create commit groups in commit service offer in RewriteDataFilesCommitManager

- format/view-spec.md
There is a running example in the view format doc. It works well to explain the view format. However, the example itself is not a valid JSON data (except the comments). That may confuse readers. This simply fixes that.
Validation commands to test this change:
```
sed -n '139,184p' format/view-spec.md | sed 's/=>.*//' | jq .
sed -n '190,264p' format/view-spec.md | sed 's/=>.*//' | jq .
```
> [Doc] Fix example view JSON format for view spec

- data/src/test/java/org/apache/iceberg/data/TestMetricsRowGroupFilter.java
- parquet/src/main/java/org/apache/iceberg/parquet/ParquetMetricsRowGroupFilter.java
- parquet/src/test/java/org/apache/iceberg/parquet/TestCDHParquetStatistics.java
Previously, the RowGroupFilter would skip any RowGroups whose min or max value was set as NaN because Parquet would report that those row groups "hasNonNull" as false. When the statistics are not empty and hasNonNull is false this actually indicates that the min and max are undefined, not that there are no non nulls.
Fixes #6516
> Parquet: Fixes Incorrect Skipping of RowGroups with NaNs

- api/src/main/java/org/apache/iceberg/view/ViewHistoryEntry.java
- core/src/main/java/org/apache/iceberg/view/ViewHistoryEntryParser.java
- core/src/test/java/org/apache/iceberg/view/TestViewHistoryEntryParser.java
Co-authored-by: John Zhuge <jzhuge@apache.org>
Separating this PR from https://github.com/apache/iceberg/pull/6559/files#diff-2a70d3056d3d0cca0da3ff4ddabc83c41c06af2296f281a5b37c5b54ead98915 for easier review from the community.
This PR contains the core implementation for view history entry and parsing/serializing logic for view history logs.
cc : @jzhuge @rdblue @jackye1995
> Core: View history entry core implementation

- docs/spark-queries.md
https://github.com/apache/iceberg/pull/5150/files introduced the ability to read from branches and tags in Spark, but the docs haven't been updated. This change updates the docs and examples for reading from branches and tags.
> Docs: Add information on how to read from branches and tags in Spark docs

- flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/HadoopCatalogResource.java
- flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/HadoopTableResource.java
- flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSink.java
- flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkV2.java
Refactor Flink Sink tests to use the HadoopCatalogResource.
This is a groundwork for adding encryption tests for Flink Sources and Sinks
> Flink: Refactor sink tests to use HadoopCatalogResource

- docs/spark-queries.md
one of my comments was not addressed in #6573. Hence, a follow-up PR.   #6573 adds two more spark read options in the data frame time travel syntax.
> Docs: Fix minor typo in time travel dataframe section

- flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/FlinkCatalog.java
- flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/FlinkSchemaUtil.java
- flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/data/StructRowData.java
- flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/source/DataTaskReader.java
- flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/source/FlinkInputFormat.java
- flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/source/IcebergSource.java
- flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/source/reader/MetaDataReaderFunction.java
- flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/DataGenerators.java
- flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/TestHelpers.java
- flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/data/TestStructRowData.java
- flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/source/TestFlinkMetaDataTable.java
- flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/source/TestMetadataTableReadableMetrics.java
- flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/FlinkCatalog.java
- flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/FlinkSchemaUtil.java
- flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/data/StructRowData.java
- flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/source/DataTaskReader.java
- flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/source/FlinkInputFormat.java
- flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/source/IcebergSource.java
- flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/source/reader/MetaDataReaderFunction.java
- flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/DataGenerators.java
- flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/TestHelpers.java
- flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/data/TestStructRowData.java
- flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/source/TestFlinkMetaDataTable.java
- flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/source/TestMetadataTableReadableMetrics.java
```
➜  iceberg git:(inspecting2) ✗ git diff --no-index  flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/ flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/
import org.apache.flink.table.api.constraints.UniqueConstraint;
import org.apache.flink.table.connector.ChangelogMode;
+import org.apache.flink.table.connector.ProviderContext;
import org.apache.flink.table.connector.sink.DataStreamSinkProvider;
import org.apache.flink.table.connector.sink.DynamicTableSink;
import org.apache.flink.table.connector.sink.abilities.SupportsOverwrite;
import org.apache.flink.table.connector.sink.abilities.SupportsPartitioning;
+import org.apache.flink.table.data.RowData;
import org.apache.flink.types.RowKind;
import org.apache.flink.util.Preconditions;
import …
```
> Flink: Port Support inspecting metadata table to Flink 1.14 & 1.15

- core/src/main/java/org/apache/iceberg/rest/HTTPClient.java
- core/src/main/java/org/apache/iceberg/rest/RESTClient.java
- core/src/test/java/org/apache/iceberg/rest/TestHTTPClient.java
For some context: In https://github.com/apache/iceberg/pull/6169#discussion_r1031590899 we're sending back a  `cache-control` header to indicate to the client whether something can be safely cached or not. 
However, our `HTTPClient` didn't have a way to retrieve the response headers from a given request, so a workaround in https://github.com/apache/iceberg/pull/6169 was done, where response headers are sent back as part of the actual response.
> Core: Support access to response headers from POST requests

- api/src/main/java/org/apache/iceberg/view/SQLViewRepresentation.java
The spec defines "sql" as the field in SQL view representation but at the API level it's called query. Renaming the API for consistency purposes and as discussed on https://github.com/apache/iceberg/pull/6612 concluded that sql is the best field name (rather than updating the spec to use query) since this will always be a SQL string and not some generic query string for SQL view representation
> API: Rename query to sql on SQLViewRepresentation API

- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/SparkCatalog.java
- spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/sql/TestSelect.java
Similar to the Trino PR I am trying to push https://github.com/trinodb/trino/pull/15646, support using reference name for the `VERSION AS OF` clause.
We have a related PR https://github.com/apache/iceberg/pull/5294 by @hililiwei that tries to directly add the reference info in table name, while we are consolidating that experience, I think we can first have this feature added in parallel.
@amogh-jahagirdar
> Spark 3.3: support version travel by reference name

- docs/spark-queries.md
Follow up to https://github.com/apache/iceberg/pull/6575/files, this change updates docs with examples of VERSION AS OF time travel for branches and tags, as well as some important notes.
Cc: @ajantha-bhat @nastra @jackye1995
> Docs: Update spark SQL examples for time travel to branches and tags

- aws/src/integration/java/org/apache/iceberg/aws/glue/TestGlueCatalogTable.java
- aws/src/main/java/org/apache/iceberg/aws/glue/GlueCatalog.java
- aws/src/test/java/org/apache/iceberg/aws/glue/TestGlueCatalog.java
Currently no matter in what situation warehouse path must be specified, but in many cases the user just want to initialize Glue catalog to read data, and don't want to pass in a warehouse path. This is to support that use case without user having to specify a dummy warehouse path to bypass the checks.
> AWS: make warehouse path optional for read only catalog use cases

- flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/source/AvroGenericRecordFileScanTaskReader.java
- flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/source/RowDataToAvroGenericRecordConverter.java
- flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/source/reader/AvroGenericRecordReaderFunction.java
- flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/source/reader/ListBatchRecords.java
- flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/source/reader/ListDataIteratorBatcher.java
- flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/DataGenerators.java
- flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/source/TestIcebergSourceBoundedGenericRecord.java
- flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/source/TestRowDataToAvroGenericRecordConverter.java
- flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/source/AvroGenericRecordFileScanTaskReader.java
- flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/source/RowDataToAvroGenericRecordConverter.java
- flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/source/reader/AvroGenericRecordReaderFunction.java
- flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/source/reader/ListBatchRecords.java
- flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/source/reader/ListDataIteratorBatcher.java
- flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/DataGenerators.java
- flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/source/TestIcebergSourceBoundedGenericRecord.java
- flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/source/TestRowDataToAvroGenericRecordConverter.java
- flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/source/TestRowDataToAvroGenericRecordConverter.java
I also piggybacked the fix of `TestRowDataToAvroGenericRecordConverter` package name (a mishap from PR #6584) in 1.16 module. should be under `test/.../flink/source` (not `test/.../flink/`)
>  Flink: backport PR #6584 to 1.14 and 1.15 for Avro GenericRecord in FLIP-27 source

- python/tests/cli/test_console.py
When running `make test` on mainline branch `test_missing_uri` unit test fails with:
```
empty_home_dir_path = '/private/var/folders/wz/yzqdwvrx0cj1j1h5c3g59rm40000gr/T/pytest-of-najarmin/pytest-22/home0'
def test_missing_uri(empty_home_dir_path: str) -> None:
with mock.patch.dict(os.environ, {"HOME": empty_home_dir_path, "PYICEBERG_HOME": empty_home_dir_path}):
runner = CliRunner()
result = runner.invoke(run, ["list"])
assert result.exit_code == 1
>           assert (
result.output
== "URI missing, please provide using --uri, the config or environment variable \nPYICEBERG_CATALOG__DEFAULT__URI\n"
)
E           AssertionError: assert 'You must specify a region.\n' == 'URI missing,...EFAULT__URI\n'
E             + You must specify a region.
E             - URI missing, please provide using …
```
> Python: Fix `test_missing_uri` unit test

- flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/source/IcebergSource.java
- flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/source/TestIcebergSourceBounded.java
- flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/source/IcebergSource.java
- flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/source/TestIcebergSourceBounded.java
- flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/source/IcebergSource.java
- flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/source/TestIcebergSourceBounded.java
This is to avoid double loading if table is already loaded before the builder. This is also the same pattern as the pre FLIP-27 FlinkSource#Builder.
> Flink: add table setter to FLIP-27 IcebergSource#Builder.

- baseline.gradle
- core/src/main/java/org/apache/iceberg/rest/auth/OAuth2Util.java
- hive-metastore/src/main/java/org/apache/iceberg/hive/HiveVersion.java
I have observed that the build [`./gradlew clean build -x test`] has some warnings. 
So it is an effort to keep the build green. 
Before:
After:
> Build: Fix minor error-prone warnings

- api/src/main/java/org/apache/iceberg/Transaction.java
- core/src/main/java/org/apache/iceberg/BaseTransaction.java
- core/src/main/java/org/apache/iceberg/CommitCallbackTransaction.java
- core/src/main/java/org/apache/iceberg/SnapshotManager.java
- core/src/test/java/org/apache/iceberg/TestSnapshotManager.java
Currently, SnapshotManager encapsulates its own BaseTransaction object and there is no way to expose it opposed to for example ExpireSnapshots that can be created through the Transaction API. As a result the operations in SnapshotManager can't run in the same transaction with the operations in e.g. BaseTransaction.
One real world use-case would be from Apache Impala where each transactional operation through the Iceberg API has to set some Catalog properties (CATALOG_SERVICE_ID, CATALOG_VERSION) in the same transaction. For explanation see this ticket:
https://issues.apache.org/jira/browse/IMPALA-11508
> API,Core: SnapshotManager to be created through Transaction

- core/src/main/java/org/apache/iceberg/BaseTransaction.java
Fix for https://github.com/apache/iceberg/issues/6632
The way intermediate snapshots in transactions are tracked is incorrect in the presence of branching.
Moving to draft as I read more of the code to make sure this handles different failure cases properly and will add tests if determined this is the right way to fix this issue.
> Core: Fix for deleting files when commiting transactions with multiple branches

- spark/v3.3/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/analysis/RewriteMergeIntoTable.scala
- spark/v3.3/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/RowLevelCommandScanRelationPushDown.scala
- spark/v3.3/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/SparkRowLevelOperationsTestBase.java
- spark/v3.3/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMerge.java
This PR fixes predicate pushdown for copy-on-write MERGE commands, which was broken after #6534. This change contains a test that would previously fail and lead to a data correctness issue.
> Spark 3.3: Fix predicate pushdown for copy-on-write MERGE commands

- aws/src/main/java/org/apache/iceberg/aws/glue/GlueCatalog.java
- aws/src/main/java/org/apache/iceberg/aws/glue/GlueTableOperations.java
Glue optimistic locking is automatically enabled if aws-java-sdk version is >= 2.17.131, however, users sometimes cannot check what version of aws-java-sdk is actually used in the runtime environment. Therefore I suppose it's good to add logging for users to understand whether the optimistic locking is actually enabled or not.
> AWS: Print logs whether Glue optimistic locking is used or not

- docs/aws.md
Now AWS Glue officially supports Apache Iceberg: https://docs.aws.amazon.com/glue/latest/dg/aws-glue-programming-etl-format-iceberg.html
> AWS, Docs: Add AWS Glue in Run Iceberg on AWS section

- python/pyiceberg/io/pyarrow.py
This is an interim solution for https://github.com/apache/iceberg/issues/6647. Parquet file k/v metadata is optional and not required to be written as per the Parquet spec https://github.com/apache/parquet-format/blob/master/src/main/thrift/parquet.thrift#L1022
The real fix will be to determine the Iceberg schema from the Parquet file (in this case we don't care about any external definitions, it'll be just from the parquet schema) https://github.com/apache/iceberg/issues/6505
If the real solution is ready for PR soon, we can just close this. But I was thinking in the interim it would be useful so that users know it's a known issue until we release the fix.
CC: @Fokko @JonasJ-ap @rdblue @samredai
> Python: Check if optional Parquet kv metadata is None before reading Iceberg Schema

- .palantir/revapi.yml
- api/src/main/java/org/apache/iceberg/ContentScanTask.java
- core/src/main/java/org/apache/iceberg/BaseMetadataTable.java
- core/src/main/java/org/apache/iceberg/BasePositionDeletesScanTask.java
- core/src/main/java/org/apache/iceberg/BaseScan.java
- core/src/main/java/org/apache/iceberg/BaseTableScan.java
- core/src/main/java/org/apache/iceberg/MetadataColumns.java
- core/src/main/java/org/apache/iceberg/MetadataTableUtils.java
- core/src/main/java/org/apache/iceberg/PositionDeletesScanTask.java
- core/src/main/java/org/apache/iceberg/PositionDeletesTable.java
- core/src/main/java/org/apache/iceberg/SerializableTable.java
- core/src/main/java/org/apache/iceberg/SnapshotScan.java
- core/src/main/java/org/apache/iceberg/SplitPositionDeletesScanTask.java
- core/src/test/java/org/apache/iceberg/MetadataTableScanTestBase.java
- core/src/test/java/org/apache/iceberg/TestMetadataTableScans.java
- core/src/test/java/org/apache/iceberg/TestMetadataTableScansWithPartitionEvolution.java
- core/src/test/java/org/apache/iceberg/TestSplitPlanning.java
- core/src/test/java/org/apache/iceberg/hadoop/TestStaticTable.java
- core/src/test/java/org/apache/iceberg/hadoop/TestTableSerialization.java
This breaks up the pr https://github.com/apache/iceberg/pull/4812 , and is just the part to add the table PositionDeletesTable.
It is now based on @aokolnychyi 's newly-added BatchScan interface (#5922), added for this purpose so the scan is free to not return FileScanTask.  It returns a custom ScanTask that scan DeleteFiles rather than DataFiles.
> Core: Add position deletes metadata table

- open-api/rest-catalog-open-api.yaml
Both types define some map of string to string as their `properties` property. The current spec would generate Java code like `private @Valid Object properties = { };` for these fields (using the common OpenAPI Generators), which leads to compile errors. I suspect, both are missing this:
```
additionalProperties:
type: string
```
> Fix OpenAPI types `CreateNamespaceRequest` + `GetNamespaceResponse`

- open-api/rest-catalog-open-api.yaml
This is a follow-up to https://github.com/apache/iceberg/pull/6663. 
According to https://github.com/apache/iceberg/blob/c07f2aabc0a1d02f068ecf1514d2479c0fbdd3b0/core/src/main/java/org/apache/iceberg/rest/responses/ConfigResponse.java#L46-L47 those need to be `Map<String, String>`
> Spec: Fix OpenAPI types for CatalogConfig (ConfigResponse)

- open-api/rest-catalog-open-api.yaml
The warehouse parameter was added to the REST config route, but was not documented in the spec.  This PR adds the relevant definitions.
> Update REST Spec to include warehouse param

- aws/src/integration/java/org/apache/iceberg/aws/dynamodb/TestDynamoDbCatalog.java
- aws/src/integration/java/org/apache/iceberg/aws/glue/TestGlueCatalogTable.java
- aws/src/main/java/org/apache/iceberg/aws/dynamodb/DynamoDbTableOperations.java
- aws/src/main/java/org/apache/iceberg/aws/glue/GlueTableOperations.java
- core/src/main/java/org/apache/iceberg/BaseMetastoreTableOperations.java
- core/src/main/java/org/apache/iceberg/jdbc/JdbcTableOperations.java
- core/src/test/java/org/apache/iceberg/jdbc/TestJdbcCatalog.java
- dell/src/main/java/org/apache/iceberg/dell/ecs/EcsTableOperations.java
- dell/src/test/java/org/apache/iceberg/dell/ecs/TestEcsCatalog.java
- hive-metastore/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java
- hive-metastore/src/test/java/org/apache/iceberg/hive/TestHiveCatalog.java
- nessie/src/main/java/org/apache/iceberg/nessie/NessieTableOperations.java
`HiveTableOperations` and `NessieTableOperations` were already handling this case, but other table operations are missing this case.
Follow up of https://github.com/apache/iceberg/pull/6512#discussion_r1065429572
> Core: Avoid creating new metadata file when `registerTable` API  is used

- spark/v3.2/build.gradle
- spark/v3.2/spark/src/jmh/java/org/apache/iceberg/spark/source/parquet/vectorized/VectorizedReadDictionaryEncodedFlatParquetDataBenchmark.java
- spark/v3.2/spark/src/jmh/java/org/apache/iceberg/spark/source/parquet/vectorized/VectorizedReadFlatParquetDataBenchmark.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/data/vectorized/VectorizedSparkParquetReaders.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/BaseBatchReader.java
Port of https://github.com/apache/iceberg/pull/6550 to Spark 3.2.
> Spark 3.2: Automatically set Arrow properties for read performance

- .palantir/revapi.yml
- core/src/main/java/org/apache/iceberg/SnapshotScan.java
#6365 moved `scanMetrics()` from `BaseTableScan` higher in the hierarchy to `SnapshotScan` and required RevAPI changes due to making method package-private instead of `protected` (meaning that classes in different packages wouldn't have access to that method anymore). This PR makes sure that we don't need the RevAPI changes and changes visibility back to `protected`.
/cc @szehon-ho @rdblue
> Core: Fix API breakages around scanMetrics()

- nessie/src/main/java/org/apache/iceberg/nessie/NessieCatalog.java
Nessie catalog supports namespace properties. Test cases can be found [here](https://github.com/apache/iceberg/blob/038091f6b65bf63d028af175dbbbc7285815d6be/nessie/src/test/java/org/apache/iceberg/nessie/TestNamespace.java#L111-L146).
But the  javadoc of `loadNamespaceMetadata` is incorrect (maybe not updated when Nessie supported namespace properties)
> Nessie: Update the outdated javadoc

- nessie/src/test/java/org/apache/iceberg/nessie/BaseTestIceberg.java
- nessie/src/test/java/org/apache/iceberg/nessie/TestNessieCatalog.java
- nessie/src/test/java/org/apache/iceberg/nessie/TestNessieTable.java
> Nessie: Avoid usage of deprecated APIs in test

- core/src/main/java/org/apache/iceberg/ManifestFilterManager.java
- core/src/test/java/org/apache/iceberg/TestDeleteFiles.java
- spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/sql/TestDeleteFrom.java
Fixes #6670 
When we determine the ResidualEvaluators for manifest entries in file we use a computeIfAbsent method using the file object's PartitionData as a key. The underlying issue here is that when being read using ManifestReader the PartitionData object is reused. This means once placed within the Map the value of the PartitionData changes every time a new entry is read. Because the original hashcode is correct, this isn't a problem until two values collide. Once they do the second key will end up retrieving the value of the first key, the underlying key retrieved will then also be equal because of the ManifestReader Container re-use. If the First Key was "always true" but the second key should be "false" the second key will return true and delete a file it should not.
To fix this we …
> Core: DeleteWithFilter fails on HashCode Collision

- python/tests/test_transforms.py
Because TestType contains test in the name, pytest tries to collect it and run tests on it. Setting `__test__ = False` tells PyTest to ignore it
> Python: Let pytest know that it shouldn't collect TestType

- core/src/main/java/org/apache/iceberg/rest/auth/OAuth2Util.java
The fields updated in the background during auth refresh should be marked as volatile.
> Mark updated auth fields volatile for refresh

- .github/workflows/open-api.yml
0.5.3 of openapi-spec-validator was recently released (https://pypi.org/project/openapi-spec-validator/#history) and it fails with the below error:
```
openapi-spec-validator open-api/rest-catalog-open-api.yaml
maximum recursion depth exceeded
```
> Pin openapi-spec-validator version

- core/src/main/java/org/apache/iceberg/BaseUpdatePartitionSpec.java
- core/src/test/java/org/apache/iceberg/TestTableUpdatePartitionSpec.java
BaseUpdatePartitionSpec::addField  is failing with “Cannot add duplicate partition field” for the re-added DATE type field.
existing.transform().equals(sourceTransform.second()) returns FALSE since the types are different: 
````
existing.transform() = {Dates@11599} “year”
sourceTransform.second() = {Years@11603} “year”
````
Test
````
Schema SCHEMA = new Schema(
required(1, "id", Types.IntegerType.get()),
required(2, "data", Types.StringType.get()),
optional(3, "year_field", Types.DateType.get()));
PartitionSpec SPEC = PartitionSpec.builderFor(SCHEMA).year("year_field").build();
table = create(SCHEMA, SPEC);
table.updateSpec()
.removeField(Expressions.year("year_field"))
.addField(Expressions.year("year_field"));
````
> API: Fix Transform backward compatibility in PartitionSpec

- .github/workflows/python-ci-docs.yml
- python/mkdocs/docs/how-to-release.md
Backport to 0.3.0
Currently everything that goes into master will directly be pushed to Github Pages. This was fine for a while, but now we have PRs that publish new functionality, but then it isn't available in the release for example: https://github.com/apache/iceberg/pull/6644
I think we should now publish by hand, and move to multi version docs once PyIceberg stabilizes a bit.
> Python: Publish the docs by hand

- spark/v3.3/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRewriteManifestsProcedure.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/actions/RewriteManifestsSparkAction.java
- spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteManifestsAction.java
Incase of no-op (when the manifests are already optimized),  rewrite manifest can still create one new file from the old file with the same contents.  Which is a waste of resources. Hence, handling the no-op scenario. 
Examples of no-op scenarios: 
a) have one manifest and user calls rewrite manifests. 
b) output of previous rewrite has created one smaller manifest (residual manifest after rewriting all the manifest to the target size) and user calls rewrite-manifests again. 
- Have four manifests of 5MB each and target size is 8MB. 
The first time calling rewrite will create three 8MB file and one 1MB file.  
If the rewrite is called again, no need to write just 1MB file into a new 1MB file.
> Spark-3.3: Handle no-op for  rewrite manifests procedure/action

- hive-metastore/src/main/java/org/apache/iceberg/hive/HiveLock.java
- hive-metastore/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java
- hive-metastore/src/main/java/org/apache/iceberg/hive/LockException.java
- hive-metastore/src/main/java/org/apache/iceberg/hive/MetastoreLock.java
- hive-metastore/src/test/java/org/apache/iceberg/hive/TestHiveCommitLocks.java
- hive-metastore/src/test/java/org/apache/iceberg/hive/TestHiveCommits.java
> Hive: Refactor commit lock mechanism from HiveTableOperations

- .github/workflows/open-api.yml
- aws/src/main/java/org/apache/iceberg/aws/AssumeRoleAwsClientFactory.java
- aws/src/main/java/org/apache/iceberg/aws/AwsClientFactories.java
- aws/src/main/java/org/apache/iceberg/aws/AwsProperties.java
- aws/src/main/java/org/apache/iceberg/aws/s3/signer/S3ObjectMapper.java
- aws/src/main/java/org/apache/iceberg/aws/s3/signer/S3SignRequest.java
- aws/src/main/java/org/apache/iceberg/aws/s3/signer/S3SignRequestParser.java
- aws/src/main/java/org/apache/iceberg/aws/s3/signer/S3SignResponse.java
- aws/src/main/java/org/apache/iceberg/aws/s3/signer/S3SignResponseParser.java
- aws/src/main/java/org/apache/iceberg/aws/s3/signer/S3V4RestSignerClient.java
- aws/src/main/resources/s3-signer-open-api.yaml
- aws/src/test/java/org/apache/iceberg/aws/TestAwsProperties.java
- aws/src/test/java/org/apache/iceberg/aws/s3/MinioContainer.java
- aws/src/test/java/org/apache/iceberg/aws/s3/signer/S3SignerServlet.java
- aws/src/test/java/org/apache/iceberg/aws/s3/signer/TestS3RestSigner.java
- aws/src/test/java/org/apache/iceberg/aws/s3/signer/TestS3SignRequestParser.java
- aws/src/test/java/org/apache/iceberg/aws/s3/signer/TestS3SignResponseParser.java
- build.gradle
- versions.props
This introduces an S3 REST signer client and defines a REST spec (`s3-signer-open-api.yml`) for a server implementation. Below is a high-level overview of the introduced changes:
* the main logic and functionality resides in the `S3V4RestSignerClient` class
* it uses the same **credential/token** exchange flow as we have in `RESTSessionCatalog` and also uses the same token refresh mechanism. In order to achieve that, a few refactorings have been done in `RESTSessionCatalog` / `OAuth2Util`.
* the default endpoint the signer connects to is `v1/aws/s3/sign` but can be customized.
* The server decides which headers to sign and can indicate to the `S3V4RestSignerClient` whether a response with signed headers can be cached by sending a `Cache-Control: private` header
* `AwsProperties` introduce …
> AWS,Core: Add S3 REST Signer client + REST Spec

- spark/v3.3/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/parser/extensions/IcebergSparkSqlExtensionsParser.scala
- spark/v3.3/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/parser/extensions/IcebergSqlExtensionsAstBuilder.scala
- spark/v3.3/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestCreateBranch.java
- spark/v3.3/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestReplaceBranch.java
@hililiwei @jackye1995 @flyrain  @yyanyy  When working on the drop branch implementation, I noticed that the "or" condition for replace branch wasn't placed right in https://github.com/apache/iceberg/pull/6638 . It should be within the startsWith("alter table") condition, but currently its outside. The Iceberg DDL will still work, but the check should be more specific to match the alter table condition to prevent any future spark sql syntax change from being bypassed in the `isIcebergCommand` check.
Just raising this PR separately since it's a bugfix (albeit for an unlikely case)
> Spark: Fix isIcebergCommand check and style issues from #6638

- spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRewriteManifestsProcedure.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/actions/RewriteManifestsSparkAction.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteManifestsAction.java
backport of https://github.com/apache/iceberg/pull/6695 (no conflicts)
> Spark-3.2: Handle no-op for rewrite manifests procedure/action

- spark/v3.1/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRewriteManifestsProcedure.java
- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/actions/BaseRewriteManifestsSparkAction.java
- spark/v3.1/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteManifestsAction.java
backport of https://github.com/apache/iceberg/pull/6695 (no conflicts)
> Spark-3.1: Handle no-op for rewrite manifests procedure/action

- spark/v2.4/spark/src/main/java/org/apache/iceberg/spark/actions/BaseRewriteManifestsSparkAction.java
- spark/v2.4/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteManifestsAction.java
backport of https://github.com/apache/iceberg/pull/6695
Note that spark-2.4 doesn't have call procedures. Hence, only two file changes. 
Also, Added a No-op testcase newly for the spark action itself as there is no procedure to cover that scenario.
> Spark-2.4: Handle no-op for rewrite manifests action

- core/src/main/java/org/apache/iceberg/hadoop/Util.java
- core/src/main/java/org/apache/iceberg/io/ResolvingFileIO.java
- flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/source/SourceUtil.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/SparkReadConf.java
Presently when determining the locality preference we check if the fileIO if it's Hadoop file IO and then only we perform subsequent checks to determine locality but we may also be using ResolvingFileIO which might be wrapping HadoopFileIO inside it and hence in that case, we might actually wanna proceed with inputFile creation and checking the scheme etc to determine locality enabled.
TODO
> Spark: Handle ResolvingFileIO while determining LocalityPreference

- snowflake/src/main/java/org/apache/iceberg/snowflake/JdbcSnowflakeClient.java
- snowflake/src/main/java/org/apache/iceberg/snowflake/SnowflakeCatalog.java
- snowflake/src/test/java/org/apache/iceberg/snowflake/JdbcSnowflakeClientTest.java
Currently the catalog is unable to handle databases or schema or table names (snowflake identifiers) with special characters. This limitation is due to sanitizing of the parameter for the like clause of SQL statements (which is not well supported by Snowflake JDBC's PreparedStatement) to determine if a database or schema exists (eg: SHOW DATABASES LIKE '%s' IN ACCOUNT). The alternative proposal is to list sub-namespace (eg: list schemas within a database (SHOW SCHEMAS/TABLES IN IDENTIFIER(?) LIMIT 1) or list tables within schema) and rely on the exception being thrown if the database/schema would not exist. This avoids using the like statement (while still being performant) and allows passing in the snowflake identifiers with special characters as quoted identifiers (more details at …
> Add support for special characters in snowflake identifiers for Snowflake Catalog

- core/src/main/java/org/apache/iceberg/rest/RESTSessionCatalog.java
When using OAuth with RESTCatalog, the catalog's auth session is returned by `newSession` if credentials are not provided.  This results in the main auth session being cached and eventually expired.
This PR removes the side-effect of returning the original auth from `newSession` and prevents it from being cached.
> Prevent RESTCatalog AuthSession from expiring

- python/tests/catalog/integration_test_glue.py
- python/tests/catalog/test_base.py
- python/tests/catalog/test_glue.py
- python/tests/cli/test_console.py
- python/tests/conftest.py
My isort seems to mess up the imports, and it is a good thing to avoid in general. Prefer fixtures over imports. Also because the test folder doesn't have the `__init__.py` files and therefore it isn't a package, this might introduce issues in some situations.
> Python: Avoid local imports in test

- spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRegisterTableProcedure.java
- spark/v3.3/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRegisterTableProcedure.java
PR #[5037](https://github.com/apache/iceberg/pull/5037) supports register tables for all (most of) the catalogs. 
There is no restriction in the register table procedure about catalog type. But the testcase has a restriction. 
Hence, update the testcase to test for all the catalogs.
> Spark: Update register table procedure test case for all the catalogs

- python/poetry.lock
- python/pyproject.toml
As discussed in #6620, this PR uses version ranges for some dependencies. This will unfix the versions for certain dependencies and allow users to use older versions when install PyIceberg to use as a library. The dependencies changed are:
- PyArrow from `11.0.0` to `8.0.0-11.0.0`. It is an optional dependency used either for FileIO, conversion from Iceberg to Arrow (schema, expression, table, etc.), or a dep for Pandas or DuckDB. Made sure current tests pass with every major version.
- Pandas from `1.5.3` to `1.4.4-1.5.3`. It is only used to read Iceberg tables out to Pandas, which is current done through PyArrow anyways. Tested 1.4.4. PyIceberg used 1.5.2 until recently
- DuckDB from `0.6.1` to `0.6.0-0.6.1`. Similar to Pandas, and PyIceberg used 0.6.0 until recently
- FsSpec, S3Fs, and …
> Python: Use Version Ranges for Various Dependencies

- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/SparkBatchQueryScan.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/SparkCopyOnWriteScan.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/SparkPartitioningAwareScan.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/SparkScan.java
While debugging storage-partitions joins, I realized our log messages in scans don't include table names. It makes hard to match log messages with tables if queries touch multiple tables. This PR slightly improves log messages in scans.
> Spark 3.3: Improve log messages in scans

- spark/v2.4/spark/src/main/java/org/apache/iceberg/spark/SparkReadConf.java
- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/SparkReadConf.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/SparkReadConf.java
Backports https://github.com/apache/iceberg/pull/6655 to Spark 2.4, 3.1, 3.2
> Spark: Backport handling ResolvingFileIO in determining locality - PR-6655

- core/src/main/java/org/apache/iceberg/TableMetadata.java
- core/src/test/java/org/apache/iceberg/TestTableMetadata.java
- delta-lake/src/integration/java/org/apache/iceberg/delta/TestSnapshotDeltaLakeTable.java
- snowflake/src/test/java/org/apache/iceberg/snowflake/SnowflakeCatalogTest.java
- spark/v2.4/spark/src/test/java/org/apache/iceberg/spark/actions/TestRemoveOrphanFilesAction.java
- spark/v3.1/spark/src/test/java/org/apache/iceberg/spark/actions/TestRemoveOrphanFilesAction.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/actions/TestRemoveOrphanFilesAction.java
- spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/actions/TestRemoveOrphanFilesAction.java
Previously we could end up in situations where we unintentionally we would create // in file paths which is an issue with non-POSIX FileIOs.
This is a partial fix for #6758
> Core: TableMetadata Always Strips Trailing Slash From Location

- api/src/main/java/org/apache/iceberg/view/ViewRepresentation.java
- build.gradle
- core/src/main/java/org/apache/iceberg/view/SQLViewRepresentationParser.java
- core/src/main/java/org/apache/iceberg/view/UnknownViewRepresentation.java
- core/src/main/java/org/apache/iceberg/view/ViewRepresentationParser.java
- core/src/test/java/org/apache/iceberg/view/TestSQLViewRepresentationParser.java
- core/src/test/java/org/apache/iceberg/view/TestViewRepresentationParser.java
- versions.props
View representation core implementation
Co-authored-by: John Zhuge <jzhuge@apache.org>
>  Core: View representation core implementation

- aws/src/main/java/org/apache/iceberg/aws/glue/IcebergToGlueConverter.java
Was going through GlueCatalog code and saw IcebergToGlueConverter.validateTableIdentifier is unused and since IcebergToGlueConverter is package private we should be good to remove it.
CC: @jackye1995 @singhpk234 @yyanyy
> AWS: Remove unused validateTableIdentifier method in IcebergToGlueConverter

- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/ChangelogRowReader.java
This PR removes redundant variables in `ChangelogRowReader`.
> Spark 3.3: Remove redundant vars in ChangelogRowReader

- spark/v3.3/spark-extensions/src/main/antlr/org.apache.spark.sql.catalyst.parser.extensions/IcebergSqlExtensions.g4
- spark/v3.3/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/parser/extensions/IcebergSparkSqlExtensionsParser.scala
- spark/v3.3/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/parser/extensions/IcebergSqlExtensionsAstBuilder.scala
- spark/v3.3/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/plans/logical/DropBranch.scala
- spark/v3.3/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/DropBranchExec.scala
- spark/v3.3/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/ExtendedDataSourceV2Strategy.scala
- spark/v3.3/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestBranchDDL.java
This is an implementation of DROP BRANCH Spark SQL
Co-authored-by: liliwei hililiwei@gmail.com
Co-authored-by: xuwei xuwei132@huawei.com
Co-authored-by: chidayong chidayong2@h-partners.com
CC: @jackye1995 @hililiwei @flyrain @singhpk234 @aokolnychyi
> Spark: DROP BRANCH SQL implementation

- flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/FlinkWriteConf.java
- flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/FlinkWriteOptions.java
- flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java
- flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/sink/IcebergFilesCommitter.java
- flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/SimpleDataUtil.java
- flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSink.java
- flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkBase.java
- flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkBranch.java
- flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkV2.java
- flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkV2Base.java
- flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkV2Branch.java
- flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/sink/TestIcebergFilesCommitter.java
This change adds support to write to branches in Flink Sink via a FlinkWriteOption "branch"
> Flink: Support writes to branches in FlinkSink

- python/pyiceberg/table/__init__.py
Since `TypeVar` S typining bound can be specified in the methods definition, TableScan should not be generic.
Previously using this syntax (see example below), was missleading `mypy` making it thinkg that everything after the `filter` was an `Any` type.
```python
df = (
table.scan()
.filter(EqualTo("uuid", "...."))
.select("rt", "cs1", "in")
.to_arrow()
)
```
Removing the `TableScan` generic, mypy succeds with the type inference
> Properly use TypeVar for bounding TableScan return

- api/src/main/java/org/apache/iceberg/view/SQLViewRepresentation.java
- build.gradle
- versions.props
Reverts to using stephenc findbugs dependency for Nullable based on @rdblue comment here: https://github.com/apache/iceberg/pull/6598/files#r1103888557
cc @danielcweeks since there is a differing view based off of https://github.com/apache/iceberg/pull/6598#discussion_r1096213570 . In the current PR, we're reverting back to using the stephenc dependency, because it appears the javax one from com.google.code.findbugs:jsr305 is banned. Let me know your thoughts on reverting this! 
To add a third option: It seems like the stephenc findbugs dependency has Nullable marked as deprecated, and based off https://stackoverflow.com/questions/19030954/cant-find-nullable-inside-javax-annotation spotbugs is the newer reccomended library to get the javax.annotation but this still just has a dependency …
> API: Revert to using stephenc findbugs dependency for Nullable

- core/src/main/java/org/apache/iceberg/util/TableScanUtil.java
- core/src/test/java/org/apache/iceberg/TestSplitPlanning.java
This PR refactors validation in `TableScanUtil` into a separate method as the same logic is currently used in 3 different methods. In addition, it switches to shorter messages to stay on one line with the new line limit.
> Core: Refactor validation in TableScanUtil

- data/src/test/java/org/apache/iceberg/data/GenericAppenderHelper.java
- flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/FlinkReadConf.java
- flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/FlinkReadOptions.java
- flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/source/FlinkSource.java
- flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/source/FlinkSplitPlanner.java
- flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/source/IcebergSource.java
- flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/source/ScanContext.java
- flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/source/StreamingMonitorFunction.java
- flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/source/TestFlinkScan.java
- flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/source/TestFlinkSource.java
- flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/source/TestStreamScanSql.java
- flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/source/TestStreamingMonitorFunction.java
Scan data using a specified tag or branch.
Add the following syntax
SQL:
```sql
* SELECT * FROM sample /*+ OPTIONS('tag'='t1')*/ ;
* SELECT * FROM sample /*+ OPTIONS('branch'='t1')*/ ;
```
API:
```java
public Builder tag(String tag) {
contextBuilder.useTag(tag);
return this;
}
public Builder branch(String branch) {
contextBuilder.useBranch(branch);
return this;
}
public Builder startTag(String startTag) {
contextBuilder.startTag(startTag);
return this;
}
public Builder endTag(String endTag) {
contextBuilder.endTag(endTag);
return this;
}
```
cc @amogh-jahagirdar
> Flink: Use Tag or Branch to scan data.

- spark/v3.3/spark-extensions/src/main/antlr/org.apache.spark.sql.catalyst.parser.extensions/IcebergSqlExtensions.g4
- spark/v3.3/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/parser/extensions/IcebergSparkSqlExtensionsParser.scala
- spark/v3.3/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/parser/extensions/IcebergSqlExtensionsAstBuilder.scala
- spark/v3.3/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/plans/logical/DropTag.scala
- spark/v3.3/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/DropTagExec.scala
- spark/v3.3/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/ExtendedDataSourceV2Strategy.scala
- spark/v3.3/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestBranchDDL.java
- spark/v3.3/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestTagDDL.java
Co-authored-by: Amogh Jahagirdar <jahamogh@amazon.com>
Co-authored-by: chidayong <247070443@qq.com>
> Spark 3.3: SQL Extensions for DROP TAG

- spark/v3.3/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestAddFilesProcedure.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/procedures/AddFilesProcedure.java
Close #6794 
This add `changed_partition_count` as results from Spark AddFilesProcedure. Before this change, spark only return `added_files_count` when adding external files to iceberg table using AddFilesProcedure. 
- For unpartitioned table, the `changed_partition_count` returned is 1
- For partitioned table, the `changed_partition_count` return number of partition updated (sourced from snapshot summary)
- If number of files being added is empty (either because of no valid parquet files or because of incorrectly configured partition filter), the `changed_partition_count` return is 0
This only impact the Spark 3.3 and only adds a new result in returned DF
CC @RussellSpitzer @szehon-ho
> Spark 3.3: Return partition stats for AddFiles procedure

- python/mkdocs/docs/configuration.md
- python/pyiceberg/io/__init__.py
- python/tests/catalog/test_glue.py
- python/tests/io/test_io.py
PyArrow is the most feature-complete FileIO, and it can be a bit confusing that we default to s3fs. I know that we're changing behavior here, but I think we should be still able to do this. If you only have S3FS installed, it will just fail over.
Resolves #6820
> Python: Set PyArrow as the default FileIO

- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/SparkTableUtil.java
- spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestAddFilesProcedure.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/SparkTableUtil.java
Fix for https://github.com/apache/iceberg/issues/6817
When two spark application runs end up with same manifest file name of format "stage-%d-task-%d-manifest" due to same stage/task planning, the add_file procedure ends up overwriting the manifest resulting in data loss
> Spark 3.2 : Backport PR #6818

- spark/v3.3/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRewriteDataFilesProcedure.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/SparkWriteConf.java
- spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/TestSparkDistributionAndOrderingUtil.java
- spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteManifestsAction.java
- spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSourceTablesBase.java
- spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/source/TestPartitionValues.java
- spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkDataWrite.java
This PR changes the default distribution modes in Spark 3.3.
- Default distribution mode for partitioned but unsorted tables in INSERT is HASH (instead of NONE).
- Default distribution mode for partitioned but unsorted tables in CoW MERGE is HASH (instead of NONE).
- Default distribution mode for partitioned and sorted tables in CoW MERGE is HASH (instead of RANGE).
- Default distribution mode for MoR MERGE is always HASH (instead of relying on write distribution).
Fixes #6679.
> Spark 3.3: Change default distribution modes

- python_legacy/iceberg/api/expressions/literals.py
- python_legacy/setup.py
- python_legacy/tests/api/expressions/test_string_literal_conversions.py
In case of `Boolean` binding column (`is_auth_action` column is `Boolean` type) following expression `Expressions.convert_string_to_expr("dt='2023-02-13' and is_auth_action=true")`, throwing below error -
```    file_scan_tasks = list(table.new_scan().filter(Expressions.convert_string_to_expr(partition)).plan_files())
File "/usr/local/lib/python3.7/dist-packages/iceberg/core/data_table_scan.py", line 72, in plan_files
return super(DataTableScan, self).plan_files()
File "/usr/local/lib/python3.7/dist-packages/iceberg/core/base_table_scan.py", line 164, in plan_files
return self.plan_files(ops, snapshot, row_filter)
File "/usr/local/lib/python3.7/dist-packages/iceberg/core/data_table_scan.py", line 74, in plan_files
matching_manifests = [manifest for manifest in snapshot.manifests
File …
```
> [Python Legacy] Convert string to boolean if the binding variable is Boolean

- spark/v3.1/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRewriteDataFilesProcedure.java
- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/procedures/RewriteDataFilesProcedure.java
- spark/v3.1/spark/src/test/java/org/apache/iceberg/spark/SparkCatalogConfig.java
- spark/v3.1/spark/src/test/java/org/apache/iceberg/spark/SparkTestBase.java
- spark/v3.1/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteDataFilesAction.java
- spark/v3.1/spark/src/test/java/org/apache/iceberg/spark/sql/TestRefreshTable.java
This backports #6801 to Spark 3.1
> Spark 3.1: Add rewritten bytes to rewrite data files procedure results

- spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRewriteDataFilesProcedure.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/procedures/RewriteDataFilesProcedure.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/SparkCatalogConfig.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/SparkTestHelperBase.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteDataFilesAction.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/sql/TestRefreshTable.java
This backports #6801 to Spark 3.2
> Spark 3.2: Add rewritten bytes to rewrite data files procedure results

- aws/src/main/java/org/apache/iceberg/aws/dynamodb/DynamoDbCatalog.java
While working on issue #6763 found that lastEvaluatedKey was not set for subsequent calls in listTables()
@jackye1995 FYI
> AWS: set lastEvaluatedKey for listTables in DynamoDb Catalog

- python/pyiceberg/catalog/__init__.py
- python/pyiceberg/cli/console.py
- python/pyiceberg/utils/config.py
If you set `default-catalog` it will default to that catalog.
```yaml
default-catalog: rest
catalog:
hive:
uri: thrift://127.0.0.1:9083
s3.endpoint: http://127.0.0.1:9000
s3.access-key-id: admin
s3.secret-access-key: password
rest:
uri: https://...
py-io-impl: pyiceberg.io.pyarrow.PyArrowFileIO
```
This will use the rest catalog as set using `default-catalog`.
> Python: Add `default-catalog` option to the config

- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/SparkSQLProperties.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/SparkWriteConf.java
- spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/TestSparkWriteConf.java
close #6741 
I will need to rebase the change once #6679 is merged but now we will have a new SQL config `spark.sql.iceberg.write.distribution-mode` to influence how spark can distribute its write for delete (which currently can only be achieved via SQL)
CC @aokolnychyi @szehon-ho @JunchengMa
> Spark 3.3: Add a new Spark SQLConf to influence the write distribution mode

- api/src/main/java/org/apache/iceberg/view/ViewRepresentation.java
Warning before fix:
```
../iceberg/api/src/main/java/org/apache/iceberg/view/SQLViewRepresentation.java:27: warning: (immutables:subtype) Should not inherit org.apache.iceberg.view.ViewRepresentation which is a value type itself. Avoid extending from another abstract value type. Better to share common abstract class or interface which are not carrying @Immutable annotation. If still extending from immutable abstract type be ready to face some incoherences in generated types.
public interface SQLViewRepresentation extends ViewRepresentation {
^
```
> Build: Fix compile warning with Immutables subtype

- spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRewriteDataFilesProcedure.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/SparkWriteConf.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/TestSparkDistributionAndOrderingUtil.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteManifestsAction.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSourceTablesBase.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/source/TestPartitionValues.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkDataWrite.java
This PR backports #6828 to Spark 3.2.
> Spark 3.2: Change default distribution modes

- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/SparkSQLProperties.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/SparkWriteConf.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/TestSparkWriteConf.java
backport of #6838 , this presume #6877 need to be merged first 
CC @aokolnychyi @amogh-jahagirdar @szehon-ho
> Spark 3.2: Add a new Spark SQLConf to influence the write distribution mode

- core/src/main/java/org/apache/iceberg/EnvironmentContext.java
- core/src/test/java/org/apache/iceberg/TestEnvironmentContext.java
Make Iceberg version in EnvironmentContext by default
> Core: Make Iceberg version in EnvironmentContext by default

- core/src/main/java/org/apache/iceberg/FileCleanupStrategy.java
- core/src/main/java/org/apache/iceberg/IncrementalFileCleanup.java
- core/src/main/java/org/apache/iceberg/ReachableFileCleanup.java
- core/src/main/java/org/apache/iceberg/TableMetadata.java
- core/src/test/java/org/apache/iceberg/TestRemoveSnapshots.java
Currently, Statistics files are safeguarded against orphan_files cleanup. But they are never cleaned up from table metadata and from the storage once the snapshots are expired/deleted.
Hence, this PR adds a change to handle the Statistics file cleanup during expire_snapshot.
Note that this is just for API level clean up (`table#expireSnapshots`) 
Clean-up from expired snapshots spark action/procedure will be built on top of it in a follow-up PR.
> Core: Handle statistics file clean up from expireSnapshots

- api/src/main/java/org/apache/iceberg/expressions/ExpressionUtil.java
- spark/v3.3/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestDelete.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/SparkReadConf.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/SparkUtil.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/actions/SparkZOrderStrategy.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/SparkScanBuilder.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/SparkTable.java
This PR avoids planning a scan to check whether a metadata-only DELETE is possible if the delete condition always matches entire partitions.
> Spark 3.3: Optimize metadata-only DELETEs

- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/SparkCachedTableCatalog.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/SparkCatalog.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/IcebergSource.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/SparkTable.java
- spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/source/TestSnapshotSelection.java
- spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/sql/TestSelect.java
In PR https://github.com/apache/iceberg/pull/5150 we introduced read from branch or tag. There is a bug where **we cannot read the snapshot specific schema changes** when doing 
`spark.read().option("branch", <branch_name>)`. The fix in this PR is applied similar to https://github.com/apache/iceberg/pull/3722
Still yet to add support for tag. If given a heads up for branch, will go ahead with tag 
cc  @jackieo168
@rdblue @jackye1995 @amogh-jahagirdar @wypoon Let me know what you think
> spark 3.3 read by snapshot ref schema

- aws/src/integration/java/org/apache/iceberg/aws/glue/GlueTestBase.java
- aws/src/integration/java/org/apache/iceberg/aws/glue/TestGlueCatalogTable.java
- aws/src/main/java/org/apache/iceberg/aws/AwsProperties.java
- docs/aws.md
Currently GLUE_CATALOG_SKIP_ARCHIVE_DEFAULT is set to false. This means every glue commit will archive older versions of table, which quickly hits the Glue limit (a max of 100k versions gets maintained) for streaming use cases. After discussing with users of Glue Catalog, came to the conclusion that it's better to change this default behavior.
CC: @jackye1995 @singhpk234
> AWS: Change GlueCatalog skip archive default to true

- spark/v3.3/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestWriteAborts.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/SparkCleanupUtil.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/SparkPositionDeltaWrite.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/SparkWrite.java
This PR improves our task and job abort handling in Spark 3.3.
- This change leverages bulk deletes whenever possible. 
- This change adds helpful log messages that indicate how many files were deleted and task context if any.
```
[Executor task launch worker for task 0.0 in stage 0.0 (TID 0)] ERROR org.apache.spark.sql.execution.datasources.v2.DataWritingSparkTask - Aborting commit for partition 0 (task 0, attempt 0, stage 0.0)
[Executor task launch worker for task 0.0 in stage 0.0 (TID 0)] INFO org.apache.iceberg.spark.source.SparkCleanupUtil - Deleted 2 file(s) (partition 0 (task 0, attempt 0, stage 0.0))
...
[Test worker] ERROR org.apache.spark.sql.execution.datasources.v2.AppendDataExec - Data source write support IcebergBatchWrite(table=testhive.default.table, format=PARQUET) is …
```
> Spark 3.3: Improve task and job abort handling

- api/src/main/java/org/apache/iceberg/types/Types.java
- api/src/test/java/org/apache/iceberg/types/TestTypes.java
Fix for [issue 6910](https://github.com/apache/iceberg/issues/6910), accepting space for types Fixed (Fixed[ 2 ]) and decimal.
(Unit test on Types class added)
> Fix Types from string, allow spaces

- open-api/rest-catalog-open-api.yaml
Change log:
1. Some snapshot id and time ms value in Rest Catalog OpenAPI def is int32 not int64. Correcting them.
> [Rest Catalog Spec] Correct snapshot id and time ms int format

- spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestWriteAborts.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/SparkCleanupUtil.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/SparkPositionDeltaWrite.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/SparkWrite.java
This PR backports PR #6876 to Spark 3.2.
> Spark 3.2: Improve task and job abort handling

- core/src/test/java/org/apache/iceberg/rest/TestRESTCatalog.java
Rest catalog test uses fixed port 8181, which can cause random test failures on CI.
Fix to use random available port for unit tests. 
Failure on oss https://github.com/apache/iceberg/actions/runs/4229402634/jobs/7345745908
> Core: use random port for rest catalog unit tests

- flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/sink/IcebergFilesCommitter.java
In https://github.com/apache/iceberg/pull/6660/files, I missed adding branch to the logs after a successful commit. This change is already included in the backport of #6660 to 1.14 and 1.15 https://github.com/apache/iceberg/pull/6949/files
@stevenzwu
> Flink: Add branch to successful commit logs

- flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/sink/BaseDeltaTaskWriter.java
- flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkV2.java
The equality delete writer is built with projected schema in upsert mode, but now it passes row data to it without projection and thus causes problems in case of the equality column is not the first column.
This change adds projection when deleting records in upsert mode.
> Flink: use projection when delete records in upsert mode

- core/src/test/java/org/apache/iceberg/rest/TestRESTCatalog.java
After reviewing #6895 it occurred to me that we don't need to manually figure out the port and construct the URL from it. We can directly use `httpServer.getURI()` in that case.
> Core: Use server URI from REST server instead of manually constructing it

- python/pyiceberg/io/pyarrow.py
- python/tests/io/test_pyarrow.py
Resolves #6945
I'm aware that I didn't add any tests to cover this. I think it would be nice to get the integration tests in: https://github.com/apache/iceberg/pull/6398 Or have write support in Python.
Tested this by running a scan that will filter out data (December 2021):
This fails on the current master:
> Python: Fix timezone concat issue

- spark/v3.3/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestAddFilesProcedure.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/SparkTableUtil.java
close #6888 
CC @szehon-ho @RussellSpitzer @abmo-x
> Spark 3.3: Skip duplicate check on deleted file path when import files

- flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/FlinkWriteConf.java
- flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/FlinkWriteOptions.java
- flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java
- flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/IcebergFilesCommitter.java
- flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/SimpleDataUtil.java
- flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSink.java
- flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkBase.java
- flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkBranch.java
- flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkV2.java
- flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkV2Base.java
- flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkV2Branch.java
- flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/sink/TestIcebergFilesCommitter.java
- flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/FlinkWriteConf.java
- flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/FlinkWriteOptions.java
- flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java
- flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/sink/IcebergFilesCommitter.java
- flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/SimpleDataUtil.java
- flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSink.java
- flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkBase.java
- flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkBranch.java
- flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkV2.java
- flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkV2Base.java
- flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkV2Branch.java
- flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/sink/TestIcebergFilesCommitter.java
Backport https://github.com/apache/iceberg/pull/6660/files
> Flink: Backport #6660 to Flink 1.14 and 1.15

- flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkV2.java
- flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkV2.java
this fix is by directly copying the test file from 1.16 to 1.14 and 1.15 folder.
we probably need to look into why CI build didn't catch it.
> Flink: fix compiling error from PR #6954

- spark/v3.1/spark-extensions/src/main/antlr/org.apache.spark.sql.catalyst.parser.extensions/IcebergSqlExtensions.g4
- spark/v3.1/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/parser/extensions/IcebergSparkSqlExtensionsParser.scala
- spark/v3.1/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/parser/extensions/IcebergSqlExtensionsAstBuilder.scala
- spark/v3.1/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/plans/logical/BranchOptions.scala
- spark/v3.1/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/plans/logical/CreateOrReplaceBranch.scala
- spark/v3.1/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/plans/logical/DropBranch.scala
- spark/v3.1/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/CreateOrReplaceBranchExec.scala
- spark/v3.1/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/DropBranchExec.scala
- spark/v3.1/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/ExtendedDataSourceV2Strategy.scala
- spark/v3.1/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestBranchDDL.java
- spark/v3.2/spark-extensions/src/main/antlr/org.apache.spark.sql.catalyst.parser.extensions/IcebergSqlExtensions.g4
- spark/v3.2/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/parser/extensions/IcebergSparkSqlExtensionsParser.scala
- spark/v3.2/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/parser/extensions/IcebergSqlExtensionsAstBuilder.scala
- spark/v3.2/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/plans/logical/BranchOptions.scala
- spark/v3.2/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/plans/logical/CreateOrReplaceBranch.scala
- spark/v3.2/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/plans/logical/DropBranch.scala
- spark/v3.2/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/CreateOrReplaceBranchExec.scala
- spark/v3.2/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/DropBranchExec.scala
- spark/v3.2/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/ExtendedDataSourceV2Strategy.scala
- spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestBranchDDL.java
Port Branch DDL to Spark 3.2&3.1, include Create\Replace\Drop, as part of https://github.com/apache/iceberg/issues/6896
cc @amogh-jahagirdar @jackye1995
> Spark 3.2&3.1: Port Branch DDL to Spark 3.2&3.1

- delta-lake/src/integration/java/org/apache/iceberg/delta/SparkDeltaLakeSnapshotTestBase.java
- delta-lake/src/integration/java/org/apache/iceberg/delta/TestSnapshotDeltaLakeTable.java
- delta-lake/src/main/java/org/apache/iceberg/delta/BaseSnapshotDeltaLakeTableAction.java
- delta-lake/src/test/java/org/apache/iceberg/delta/TestBaseSnapshotDeltaLakeTableAction.java
This PR fixes #6781 .
The automatic log clean whenever a new checkpoint is created and the manual data file clean by `VACUUM` sometimes lead to inconsistency between the first constructable delta lake version and the earliest delta lake version in the table. The inconsistency will cause file not found errors during the migration.
This PR fix the issue by forcing the snapshot delta lake action to start from the first constructable delta lake version instead of the earliest version.
Added Integration tests to mock the file clean scenario.
> Delta Migration: Handle delta lake's automatic log clean and VACUUM

- core/src/main/java/org/apache/iceberg/BaseOverwriteFiles.java
- core/src/main/java/org/apache/iceberg/BaseReplacePartitions.java
- core/src/main/java/org/apache/iceberg/BaseRewriteFiles.java
- core/src/main/java/org/apache/iceberg/util/SnapshotUtil.java
- core/src/test/java/org/apache/iceberg/TableTestBase.java
- core/src/test/java/org/apache/iceberg/TestDeleteFiles.java
- core/src/test/java/org/apache/iceberg/TestMergeAppend.java
- core/src/test/java/org/apache/iceberg/TestOverwrite.java
- core/src/test/java/org/apache/iceberg/TestOverwriteWithValidation.java
- core/src/test/java/org/apache/iceberg/TestReplacePartitions.java
- core/src/test/java/org/apache/iceberg/TestRewriteFiles.java
- core/src/test/java/org/apache/iceberg/TestRowDelta.java
follow up from https://github.com/apache/iceberg/pull/5234, to refactoring minor comments left in last PR. @rdblue @amogh-jahagirdar please take a look at this.
> Core, API: BaseReplacePartitions to branch test Refactoring

- aws/src/test/java/org/apache/iceberg/aws/s3/signer/TestS3RestSigner.java
This is mainly so that we don't conflict with other tests that might run in parallel
> AWS: Use random port for HTTP server

- api/src/main/java/org/apache/iceberg/expressions/ExpressionUtil.java
- api/src/test/java/org/apache/iceberg/expressions/TestExpressionUtil.java
Don't throw in sanitizeString because it will fail planFiles when reading with a string filter that matches any of the specific types like Date/Timestamp with parsing failure.
Closes #6911
> API:add try catch on ExpressionUtils.sanitizeString

- api/src/main/java/org/apache/iceberg/expressions/AggregateEvaluator.java
- api/src/main/java/org/apache/iceberg/expressions/ValueAggregate.java
- baseline.gradle
Just keeping the build green (`./gradlew build -x test -x javadoc -x integrationTest`)
Before
After
Note:
ignore the build time in the images. I was playing around with gradle --scan.
> Build: Fix minor errorprone warnings during compile

- build.gradle
- core/src/test/java/org/apache/iceberg/rest/TestRESTCatalog.java
- versions.props
This uses https://github.com/awaitility/awaitility instead of `Thread.sleep()` to fix some flakiness in TestRESTCatalog.
fixes #6988
> Core: Use Awaitility instead of Thread.sleep() for async testing

- docs/spark-procedures.md
Based on @szehon-ho suggestion in https://github.com/apache/iceberg/pull/6797#issuecomment-1430209452
- adds new `check_duplicate_files` in parameter 
- adds missing output section for both `added_files_count` and `check_duplicate_files`
- highlight the impact of tblprop `compatibility.snapshot-id-inheritance.enabled` and other caveats when using this procedure
CC @szehon-ho @RussellSpitzer
> Docs: Update documentation for Spark AddFiles procedure

- python/mkdocs/docs/api.md
- python/pyiceberg/utils/config.py
The .pyiceberg.yaml file located in the %USERPROFILE% folder on Windows could not be loaded previously. This pull request addresses the issue and enables successful loading of the file.
And fixes the issue #7001.
> Python: fix config loading on windows

- build.gradle
The main reasoning behind this change is to make people more aware of the API guarantees that the Iceberg project defined as part of https://github.com/apache/iceberg/blob/master/CONTRIBUTING.md#semantic-versioning.
Once RevAPI fails, we also point people to the API Deprecation rules via the `showDeprecationRulesOnRevApiFailure` task. 
Below is an example of the output that users would see (I've introduced an artificial API break so that RevAPI complains about it):
```
./gradlew revapi                                                                                                                                                                                                                                             1 ↵ ──(Fri,Mar03)─┘
> Task :iceberg-api:revapi FAILED
> Task …
```
> Build: Show API Deprecation rules on RevAPI failure

- flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/FlinkCatalog.java
- flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/FlinkEnvironmentContext.java
- flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/TableLoader.java
- flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/FlinkCatalog.java
- flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/FlinkEnvironmentContext.java
- flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/TableLoader.java
- flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/FlinkCatalog.java
- flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/FlinkEnvironmentContext.java
- flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/TableLoader.java
#6184 has add engine name and version  to `EnvironmentContext` in `FlinkCatalog` ,  but the FlinkCatalog works in the job manager not task manager, when `IcebergFilesCommiter` commit a snapshot, there is no engine name and version in the commit metrics report. So I add them again when table is loaded.
Please take a look this pr, thanks @nastra
> Flink: Set up EnvironmentContext for Flink(Both JM and TM)

- python/pyiceberg/io/fsspec.py
- python/pyiceberg/io/pyarrow.py
- python/tests/conftest.py
- python/tests/io/test_pyarrow.py
This allows us to read PyArrow tables using FsspecFileIO. For ADLS users this allows them to pull data from ADLS.
> Python: Wrap FsspecFileIO in PyArrowFileIO

- python/pyiceberg/catalog/__init__.py
- python/pyiceberg/catalog/dynamodb.py
- python/pyiceberg/catalog/glue.py
- python/pyiceberg/catalog/hive.py
- python/pyiceberg/catalog/rest.py
We need to pass in the metadata location when we recreate the file io for the table. We re-create the table because there can be new configuration, but we don't supply the location.
This can cause issues when you have both PyArrow and FSspec installed, you don't have the FileIO set explicitly in your config:
```yaml
catalog:
default:
...
py-io-impl: pyiceberg.io.fsspec.FsspecFileIO
```
When you fetch the metadata from ADLS using FSSpec, but then the re-created FileIO is PyArrow.
When we pass in the url, the schema gets taken into account and PyArrow won't be considered for ADLS.
> Python: Pass location when recreating the FileIO

- spark/v3.1/spark-extensions/src/main/antlr/org.apache.spark.sql.catalyst.parser.extensions/IcebergSqlExtensions.g4
- spark/v3.1/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestExpireSnapshotsProcedure.java
- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/procedures/ExpireSnapshotsProcedure.java
- spark/v3.2/spark-extensions/src/main/antlr/org.apache.spark.sql.catalyst.parser.extensions/IcebergSqlExtensions.g4
- spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestExpireSnapshotsProcedure.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/procedures/ExpireSnapshotsProcedure.java
- spark/v3.3/spark-extensions/src/main/antlr/org.apache.spark.sql.catalyst.parser.extensions/IcebergSqlExtensions.g4
- spark/v3.3/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestExpireSnapshotsProcedure.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/procedures/ExpireSnapshotsProcedure.java
Allow passing`snapshot_ids` to the `ExpireSnapshotsProcedure` so that we can expire arbitrary snapshots at will. This is particularly helpful when the audit of specific WAP snapshot is found to be wrong and we would like to retry staging a new snapshot with the same `wap_id`, we would be able to drop that snapshot and keep retrying using the same `wap_id`.
What we are trying to avoid is ever getting into a place where we might have multiple snapshots for a given `wap_id` that are not published.
> Expire snapshots procedure takes an array of snapshot IDs

- spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMetadataTables.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/SparkTable.java
fixes https://github.com/apache/iceberg/issues/6978
Spark-3.2 backport of https://github.com/apache/iceberg/pull/6980
> Spark-3.2: Bug Fix for Reading Metadata tables with Snapshot ID

- spark/v3.1/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMetadataTables.java
- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/source/SparkTable.java
- spark/v3.1/spark/src/test/java/org/apache/iceberg/spark/data/TestHelpers.java
fixes https://github.com/apache/iceberg/issues/6978
Spark-3.1 backport of https://github.com/apache/iceberg/pull/6980
> Spark-3.1: Bug Fix for Reading Metadata tables with Snapshot ID

- python/pyiceberg/io/__init__.py
- python/tests/io/test_io.py
When we pass in a warehouse identifier, we don't want to emit a warning. Also, the help message won't be helpful:
```
No preferred file implementation for scheme:
```
Since there is no scheme.
> Python: Don't warn on an identifier

- build.gradle
Fixes #7023 
related PRs: #7010 , #6982
> Build: Fix flaky checkstyle issue

- aws/src/main/java/org/apache/iceberg/aws/AwsProperties.java
- aws/src/main/java/org/apache/iceberg/aws/RESTSigV4Signer.java
- aws/src/test/java/org/apache/iceberg/aws/TestRESTSigV4Signer.java
- build.gradle
- core/src/main/java/org/apache/iceberg/rest/HTTPClient.java
- core/src/main/java/org/apache/iceberg/rest/RESTCatalog.java
- core/src/main/java/org/apache/iceberg/rest/RESTSessionCatalog.java
- core/src/test/java/org/apache/iceberg/rest/TestHTTPClient.java
This PR adds support for configuring the HTTPClient to allow for a request interceptor to be configured and an implementation in the AWS module for signing all requests with the SigV4 protocol.
> Add support for SigV4 request signing to REST Catalog requests

- hive-metastore/src/main/java/org/apache/iceberg/hive/HiveHadoopUtil.java
- hive-metastore/src/test/java/org/apache/iceberg/hive/TestHiveCatalog.java
In #6324, [HiveCatalog] was changed to use UGI current user as the default owner of Hive db&tbl.
The owner name was from `UserGroupInformation#getUserName`, was the full name of a kerberos principal, eg. "foo/dev@apache.org".
However, in Spark & Hive, owner name is set to `UserGroupInformation#getShortUserName`, eg. "foo".
We should change the owner name to the short user name.
Refs:
- https://issues.apache.org/jira/browse/SPARK-26929
- https://issues.apache.org/jira/browse/HIVE-3807
> Use UGI shortUserName as the default owner of Hive objects

- api/src/main/java/org/apache/iceberg/metrics/MetricsReporter.java
- core/src/main/java/org/apache/iceberg/BaseMetastoreCatalog.java
- core/src/main/java/org/apache/iceberg/CatalogUtil.java
- core/src/main/java/org/apache/iceberg/rest/RESTSessionCatalog.java
- core/src/test/java/org/apache/iceberg/TestCatalogUtil.java
A custom MetricsReporter implementation must have a no-arg constructor, but in some case , custom metrics reporter may need args , initialize method will be called after no-arg constructor,  then the reporter can get args through catalog properties
> Core: Add initialize method for MetricsReporter

- core/src/test/java/org/apache/iceberg/inmemory/InMemoryCatalog.java
- core/src/test/java/org/apache/iceberg/inmemory/TestInMemoryCatalog.java
Having an in-memory catalog might be useful in certain tests, so this is a revival of #4054 with some adjustments.
> Core: Add InMemoryCatalog

- core/src/main/java/org/apache/iceberg/ReachableFileUtil.java
- core/src/test/java/org/apache/iceberg/util/TestReachableFileUtil.java
After https://github.com/apache/iceberg/pull/6777 all trailing slashes to table locations are removed. This caused the issue below.
`ReachableFileUtil.versionHintLocation()` concatenates table location with "metadata" and does a hadoop path resolution. The path resolution fails if the first location is just S3 bucket name which is a valid table path. 
```
scala> new org.apache.hadoop.fs.Path("s3a://bucket1", "metadata");
java.lang.IllegalArgumentException: java.net.URISyntaxException: Relative path in absolute URI: s3a://idmsdatabucket1metadata
at org.apache.hadoop.fs.Path.initialize(Path.java:263)
at org.apache.hadoop.fs.Path.<init>(Path.java:161)
at org.apache.hadoop.fs.Path.<init>(Path.java:119)
... 47 elided
Caused by: java.net.URISyntaxException: Relative path in absolute URI: …
```
> Core: ReachableFileUtil.versionHintLocation() should not fail for table location with just bucket name

- core/src/main/java/org/apache/iceberg/rest/RESTSessionCatalog.java
When lazy snapshot loading is being used, the metadata from the response is modified to set a snapshot supplier. However, the metadata location is not set, and this has a secondary effect of not building a new metadata object. Thus the supplier is never set, and the full snapshot list is never retrieved.
This PR sets the metadata location, so a new metadata object is built with the snapshot supplier and the location set.
> REST: Set metadata location for lazy load snapshot

- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/procedures/CreateChangelogViewProcedure.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/procedures/ProcedureInput.java
This PR adds `ProcedureInput` to abstract away common logic for working with input to a procedure. Right now, our procedures have a lot of code to extract and parse arguments, which makes them unnecessary complicated. This PR adds a new utility class that will make our procedures simpler and will enable more code reuse.
> Spark 3.3: Add ProcedureInput to simplify procedures

- .palantir/revapi.yml
- api/src/main/java/org/apache/iceberg/actions/ExpireSnapshots.java
- core/src/main/java/org/apache/iceberg/ReachableFileUtil.java
- core/src/main/java/org/apache/iceberg/actions/BaseExpireSnapshotsActionResult.java
- spark/v3.3/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestExpireSnapshotsProcedure.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/actions/BaseSparkAction.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/actions/ExpireSnapshotsSparkAction.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/procedures/ExpireSnapshotsProcedure.java
This PR handles the spark action/procedure side of the statistics file clean-up for expire_snapshots. 
It is a follow-up based on the core functionality of https://github.com/apache/iceberg/pull/6090
> Spark-3.3: Handle statistics file clean up from expireSnapshots action/procedure

- core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java
- core/src/main/java/org/apache/iceberg/rest/RESTSessionCatalog.java
This adds `setFileIOBuilder(Function<Map<String, String>, FileIO)` to the `RESTSessionCatalog`. This allows another way to customize the `FileIO` instances used by the REST catalog. For example, Trino has custom `FileIO` implementations that manage resources differently than `S3FileIO`.
The function accepts a string map of config properties, which allows passing context from the catalog and table level for the IO, including `token` for remote S3 signing as well as the `s3.*` properties for access to S3.
> Core: Allow customizing FileIO in REST catalog

- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/actions/ExpireSnapshotsSparkAction.java
- spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/actions/TestExpireSnapshotsAction.java
This PR removes deprecated `expire()` method in `ExpireSnapshotsSparkAction`.
> Spark 3.3: Remove deprecated methods in ExpireSnapshotsSparkAction

- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/procedures/AddFilesProcedure.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/procedures/ProcedureInput.java
This PR migrates `AddFilesProcedure` to use `ProcedureInput`.
> Spark 3.3: Use ProcedureInput in AddFilesProcedure

- spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestExpireSnapshotsProcedure.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/actions/BaseSparkAction.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/actions/ExpireSnapshotsSparkAction.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/procedures/ExpireSnapshotsProcedure.java
> Spark-3.2: Handle statistics file clean up from expireSnapshots action/procedure

- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/actions/ExpireSnapshotsSparkAction.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/actions/TestExpireSnapshotsAction.java
This PR backports PR #7069 to Spark 3.2.
> Spark 3.2: Remove deprecated methods in ExpireSnapshotsSparkAction

- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/procedures/CreateChangelogViewProcedure.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/procedures/ProcedureInput.java
This PR backports PR #7038 to Spark 3.2.
> Spark 3.2: Add ProcedureInput to simplify procedures

- aws/src/main/java/org/apache/iceberg/aws/AwsProperties.java
- aws/src/test/java/org/apache/iceberg/aws/TestAwsProperties.java
After talking to @danielcweeks / @rdblue we concluded that it's probably better to have a `s3.remote-signing-enabled` flag rather than dynamic signer loading via `s3.signer-impl`.
This PR simplifies this and removes dynamic S3 signer loading.
> AWS: Simplify enabling S3 remote signing

- docs/flink-getting-started.md
The docs were still mentioning Flink 1.11, and was long overdue for an overhaul. Updated the links and also did some rewriting of the docs by removing `we`.
The Python quickstart became much simpler since the jars now ship with the package itself: https://pypi.org/project/apache-flink-libraries/1.16.1/
> Flink: Update the docs

- api/src/test/java/org/apache/iceberg/AssertHelpers.java
I believe we should point people for newly written code to use `Assertions#assertThatThrownBy(..)` as it provides a more fluent way of asserting exceptions
> API: Deprecate AssertHelpers

- api/src/main/java/org/apache/iceberg/catalog/SessionCatalog.java
- core/src/main/java/org/apache/iceberg/rest/RESTCatalog.java
- core/src/main/java/org/apache/iceberg/rest/RESTSessionCatalog.java
Trino needs to be able to create the `FileIO` instance with its own identity object.
> Core: Allow passing identity object through RESTSessionCatalog

- nessie/src/main/java/org/apache/iceberg/nessie/NessieCatalog.java
This fixes the same issue as https://github.com/apache/iceberg/pull/7049 by removing the compile-time dependency on Hadoop's `Configuration`.
> Nessie: Remove compile-time Hadoop dependency

- aws/src/main/java/org/apache/iceberg/aws/AwsProperties.java
- docs/aws.md
- python/dev/Dockerfile
Fixes https://github.com/apache/iceberg/issues/7118
> AWS: Use Apache HTTP client as default AWS HTTP client

- aliyun/src/test/java/org/apache/iceberg/aliyun/oss/TestOSSInputFile.java
- aliyun/src/test/java/org/apache/iceberg/aliyun/oss/TestOSSInputStream.java
- aliyun/src/test/java/org/apache/iceberg/aliyun/oss/TestOSSOutputFile.java
- aliyun/src/test/java/org/apache/iceberg/aliyun/oss/TestOSSURI.java
- SubTask of #7094 
Remove AssertHelpers in `iceberg-aliyun` module
> Aliyun: Remove AssertHelpers

- core/src/main/java/org/apache/iceberg/PartitionsTable.java
- core/src/test/java/org/apache/iceberg/TestMetadataTableScans.java
- spark/v2.4/spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSourceTablesBase.java
- spark/v3.1/spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSourceTablesBase.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSourceTablesBase.java
- spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSourceTablesBase.java
Changes:
- schema changes
- move spec_id (without changing field id) before the counters. Because It looks odd when we add new counters to have spec_id in between.
- add column docs for `record_count` and `file_count` to clarify that it is only data file counters.
- Rename internal fields `recordCount` to `dataRecordCount` and `fileCount` to `dataFileCount` for better clarity. 
This PR is a prerequisite for #6661
> Core: Minor refactoring of PartitionsTable

- .palantir/revapi.yml
- core/src/main/java/org/apache/iceberg/MergingSnapshotProducer.java
As part of branch write work, we deprecated the `validation` APIs in `MergingSnapshotProducer` in favor of new `validation` APIs which require explicit passing of the branch. This change removes those deprecated APIs for 1.3.0 and updates rev API.
cc: @rdblue @namrathamyske @jackye1995
> Core: Remove deprecated validation APIs in MergingSnapshotProducer

- aliyun/src/test/java/org/apache/iceberg/aliyun/oss/TestOSSInputStream.java
- data/src/test/java/org/apache/iceberg/data/TestGenericRecord.java
- data/src/test/java/org/apache/iceberg/data/TestLocalScan.java
- data/src/test/java/org/apache/iceberg/io/TestPartitioningWriters.java
Remove `AssertHelpers` in `iceberg-data` module
> data: Remove AssertHelpers Usage

- docs/spark-configuration.md
I noticed this one was missing.
> Docs: Add `rest` to the catalog configuration

- .palantir/revapi.yml
- api/src/main/java/org/apache/iceberg/view/ViewVersion.java
- core/src/main/java/org/apache/iceberg/view/ViewVersionParser.java
- core/src/test/java/org/apache/iceberg/view/TestViewVersionParser.java
View Version parser implementation
Co-authored-by: John Zhuge <jzhuge@apache.org>
CC @jzhuge @rdblue @nastra @danielcweeks @jackye1995  Let me know your thoughts!
> Core, API: View Version implementation

- flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/CatalogLoader.java
> Flink: fixed Cloneable not implemented on CatalogLoader

- api/src/main/java/org/apache/iceberg/actions/DeleteOrphanFiles.java
- api/src/main/java/org/apache/iceberg/actions/DeleteReachableFiles.java
- api/src/main/java/org/apache/iceberg/actions/MigrateTable.java
- api/src/main/java/org/apache/iceberg/actions/RewriteDataFiles.java
- api/src/main/java/org/apache/iceberg/actions/RewriteManifests.java
- api/src/main/java/org/apache/iceberg/actions/SnapshotTable.java
- core/src/main/java/org/apache/iceberg/actions/BaseDeleteOrphanFilesActionResult.java
- core/src/main/java/org/apache/iceberg/actions/BaseDeleteReachableFilesActionResult.java
- core/src/main/java/org/apache/iceberg/actions/BaseExpireSnapshotsActionResult.java
- core/src/main/java/org/apache/iceberg/actions/BaseFileGroupRewriteResult.java
- core/src/main/java/org/apache/iceberg/actions/BaseMigrateTableActionResult.java
- core/src/main/java/org/apache/iceberg/actions/BaseRewriteDataFilesFileGroupInfo.java
- core/src/main/java/org/apache/iceberg/actions/BaseRewriteDataFilesResult.java
- core/src/main/java/org/apache/iceberg/actions/BaseRewriteManifestsActionResult.java
- core/src/main/java/org/apache/iceberg/actions/BaseSnapshotTableActionResult.java
- core/src/main/java/org/apache/iceberg/actions/RewriteFileGroup.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/actions/DeleteOrphanFilesSparkAction.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/actions/DeleteReachableFilesSparkAction.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/actions/MigrateTableSparkAction.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/actions/RewriteDataFilesSparkAction.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/actions/RewriteManifestsSparkAction.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/actions/SnapshotTableSparkAction.java
Each action has a separate boilerplate code with the public constructor. Which is hard to maintain. Also, the addition of new fields requires deprecating older constructors and adding a new one. 
Recently two of the PRs (#6801, and #6091) also had to go through new constructors.   
Changes:
- deprecated the old action results. 
- Replaced the usage with immutables for the same.
This is a follow-up on https://github.com/apache/iceberg/pull/6091#discussion_r1129758863
Note: only spark-3.3 is using the new builders. Other versions are still using the newly deprecated builders.
Will be replaced in a single follow-up PR after the review.
> Core: Refactor actions results

- .github/ISSUE_TEMPLATE/iceberg_bug_report.yml
- python/dev/Dockerfile
- python/dev/docker-compose-integration.yml
- python/dev/docker-compose.yml
- python/mkdocs/docs/verify-release.md
This change focuses mainly to make sure docker file uses the most recent set-up as per 1.2.0 release
[1] AWS SDK changed to 2.20.18
[2] ~~url-connection-client is no longer required~~ (It's present in master only at the moment)
[3] minor refactoring 
Also updates iceberg_bug_report yml with recent version. 
cc @jackye1995 @Fokko
> Python: Update docker file

- api/src/main/java/org/apache/iceberg/util/CharSequenceSet.java
- api/src/test/java/org/apache/iceberg/util/TestCharSequenceSet.java
Found this while browsing the code, and checked that this method does not seem to be used in the project at present, luckily.
> API: Fix retainAll and removeAll in CharSequenceSet

- spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestChangelogTable.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/SparkChangelogTable.java
A Spark3.2 version of #7152  cc @aokolnychyi
> Spark 3.2: Support metadata column in the changelog table

- docs/flink-actions.md
- docs/flink-configuration.md
- docs/flink-ddl.md
- docs/flink-getting-started.md
- docs/flink-queries.md
- docs/flink-writes.md
Retypeset the Flink document,.
https://github.com/apache/iceberg/pull/7099
https://github.com/apache/iceberg-docs/pull/207
> Doc: Retypeset the Flink document

- flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/CatalogLoader.java
- flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/TableLoader.java
- flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/source/IcebergSource.java
- flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/source/enumerator/ContinuousSplitPlannerImpl.java
- flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/TestTableLoader.java
- flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/source/enumerator/TestContinuousSplitPlannerImpl.java
> Flink: Backport #6614 to Flink 1.14

- aws/src/test/java/org/apache/iceberg/aws/TestAwsClientFactories.java
- aws/src/test/java/org/apache/iceberg/aws/TestAwsProperties.java
- aws/src/test/java/org/apache/iceberg/aws/glue/TestGlueCatalog.java
- aws/src/test/java/org/apache/iceberg/aws/glue/TestGlueToIcebergConverter.java
- aws/src/test/java/org/apache/iceberg/aws/glue/TestIcebergToGlueConverter.java
- aws/src/test/java/org/apache/iceberg/aws/s3/TestS3FileIO.java
- aws/src/test/java/org/apache/iceberg/aws/s3/TestS3URI.java
Remove `AssertHelpers` in `iceberg-aws` module
> AWS: Remove deprecated AssertHelpers

- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/SparkSessionCatalog.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/TestSparkSessionCatalog.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/SparkSessionCatalog.java
- spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/TestSparkSessionCatalog.java
- spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkCatalog.java
- implement `loadFunction` in `SparkSessionCatalog` to support loading function from session catalog in Spark
- loading function in the following order:
1. load Iceberg built-in function in `BaseCatalog` (as it does now)
2. then try to load function from session catalog (e.g. registered permanent UDF in Hive MetaStore), if the session catalog is an instance of `FunctionCatalg`
> Spark: Support loading function as FunctionCatalog in SparkSessionCatalog

- aws/src/main/java/org/apache/iceberg/aws/s3/signer/S3V4RestSignerClient.java
- aws/src/test/java/org/apache/iceberg/aws/s3/signer/S3SignerServlet.java
- aws/src/test/java/org/apache/iceberg/aws/s3/signer/TestS3RestSigner.java
One of the main issues here was that we were previously scheduling a token for refresh on every single sign request. 
This PR caches the `AuthSession` based on the given token/credential to prevent this issue.
The existing `TestS3RestSigner` was slightly restructured and additional checks were added that immediately showed the original problem.
> AWS: Prevent token refresh scheduling on every sign request

- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/SparkTable.java
- spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkTable.java
Fixes #7239
This reverts commit fc501f33761ae35a48f257d6d973d835fccd6da7.
Based on https://github.com/apache/iceberg/issues/7239 Spark `SHOW CREATE TABLE` has a regression in 1.2 because we prefix `Iceberg` to the SparkTable name. Since `name()` is a public API, opting to revert the change to maintain the existing behavior. To get the Spark UI we desire, my recommendation is we look at leveraging another API.
@aokolnychyi @RussellSpitzer @sumeetgajjar @szehon-ho @jackye1995 @singhpk234
> Spark: Revert "Spark: Add "Iceberg" prefix to SparkTable name string for SparkUI (#5629)

- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/actions/RewriteManifestsSparkAction.java
This PR changes the Spark rewrite manifest action to broadcast a `Table` instead of a `FileIO`. This issue with `FileIO` is that it implements `Closeable`, so when Spark is removing the broadcast, it automatically calls `close()` on it. This happens in Spark's MemoryStore class [here](https://github.com/apache/spark/blob/309c65a353489b70bf5135a01d1f159328eaa3f3/core/src/main/scala/org/apache/spark/storage/memory/MemoryStore.scala#L397).
With `S3FileIO` and using the Apache HTTP client, that has the consequence of closing the connection pool, and can cause subsequent request failures if there is an attempt to use the FileIO object again. This currently only impacts the rewrite manifests procedure, as it is the only action that broadcasts a FileIO rather than a Table.
The …
> Spark: broadcast table instead of file IO in rewrite manifests

- aws/src/main/java/org/apache/iceberg/aws/s3/S3InputStream.java
- aws/src/main/java/org/apache/iceberg/aws/s3/S3OutputStream.java
This PR adds a check when closing an S3 input stream if the stream is at end-of-stream. If not, it calls `abort()` on the stream instead of `close()`. This avoids reading to the end of the stream when closing.
The Apache HTTP connection will always read the [entire stream](https://github.com/apache/httpcomponents-core/blob/2135596b1319910d56efb148566ecbbec0884638/httpcore/src/main/java/org/apache/http/impl/io/ContentLengthInputStream.java#L108) on close, which results in much more data being read than needed. The URL connection client does not behave this way.
Now that the Apache HTTP client is the default instead of URL connection client for AWS, this change should prevent a performance regression.
> AWS: abort S3 input stream on close if not EOS

- core/src/main/java/org/apache/iceberg/rest/RESTSessionCatalog.java
This PR fixes an issue in the REST catalog when loading metadata with refs only, where the current metadata location is being added as a previous location. The change in this PR prevents that, so the previous location list is retained as-is.
> REST: fix previous locations for refs-only load

- core/src/test/java/org/apache/iceberg/hadoop/HadoopFileIOTest.java
I've been able to reproduce this locally:
```
HadoopFileIOTest > testDeleteFiles() FAILED
at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
at org.apache.iceberg.hadoop.HadoopFileIOTest.testDeleteFiles(HadoopFileIOTest.java:130)
> Task :iceberg-aws:test
> Task :iceberg-core:test …
```
> Core: Fix flakiness in HadoopFileIOTest

- flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/sink/shuffle/DataStatisticsEvent.java
- flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/sink/shuffle/DataStatisticsOperator.java
- flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/sink/shuffle/TestDataStatisticsOperator.java
This PR is created as part of issue https://github.com/apache/iceberg/issues/6303 and project https://github.com/apache/iceberg/projects/27
In this PR, we implement the logic in DataStatisticsOperator to send local data statistics to the coordinator and receive aggregated data statistics from the coordinator.
> Flink: Data statistics operator sends local data statistics to coordinator and receive aggregated data statistics from coordinator for smart shuffling

- core/src/main/java/org/apache/iceberg/inmemory/InMemoryCatalog.java
- core/src/test/java/org/apache/iceberg/inmemory/TestInMemoryCatalog.java
In https://github.com/apache/iceberg/blob/0c2f5240146035029081a5a12ac4d71e64258602/core/src/test/java/org/apache/iceberg/inmemory/TestInMemoryCatalog.java#L41 we were specifying that this catalog requires a namespace to exist before creating a table. However, this was actually never checked in the code.
> Core: Require namespace when creating table using InMemoryCatalog

- core/src/main/java/org/apache/iceberg/BaseScan.java
- core/src/main/java/org/apache/iceberg/PartitionsTable.java
- core/src/test/java/org/apache/iceberg/MetadataTableScanTestBase.java
- core/src/test/java/org/apache/iceberg/TestMetadataTableScans.java
- core/src/test/java/org/apache/iceberg/TestMetadataTableScansWithPartitionEvolution.java
close #7189 
- Maintain original functionality of parallelizable manifest read
- hardcoded to avoid reading stats columns of data files in partition table
CC @szehon-ho
> Refactor PartitionsTable planning

- aws/src/integration/java/org/apache/iceberg/aws/glue/GlueTestBase.java
- aws/src/integration/java/org/apache/iceberg/aws/glue/TestGlueCatalogCommitFailure.java
- aws/src/main/java/org/apache/iceberg/aws/AwsClientFactories.java
- aws/src/main/java/org/apache/iceberg/aws/dynamodb/DynamoDbTableOperations.java
- aws/src/main/java/org/apache/iceberg/aws/glue/GlueTableOperations.java
- aws/src/main/java/org/apache/iceberg/aws/util/RetryDetector.java
- aws/src/test/java/org/apache/iceberg/aws/util/TestRetryDetector.java
This PR fixes the issue described by #7151 where a commit can succeed but Glue or Dynamo backed tables see a failure and delete the now-committed metadata.
> AWS: Check commit status after failed commit if AWS client performed retries

- baseline.gradle
- core/src/main/java/org/apache/iceberg/inmemory/InMemoryInputFile.java
Keeping the build clean [`./gradlew clean build -x test -x integrationTest`]
> Core: Fix errorprone warning

- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/SparkUtil.java
- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/actions/BaseRewriteManifestsSparkAction.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/SparkUtil.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/actions/RewriteManifestsSparkAction.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/SparkUtil.java
This PR applies the changes from https://github.com/apache/iceberg/pull/7263 to Spark v3.2 and v3.1 also. It marks the unused method `SparkUtil.serializableFileIO()` as deprecated, as using this to broadcast a FileIO can lead to unintended consequences, i.e. the underlying S3 client being closed during broadcast removal.
> Spark: apply rewrite manifest action fix to 3.1,3.2

- nessie/src/main/java/org/apache/iceberg/nessie/NessieCatalog.java
- nessie/src/main/java/org/apache/iceberg/nessie/NessieIcebergClient.java
- nessie/src/main/java/org/apache/iceberg/nessie/UpdateableReference.java
- nessie/src/test/java/org/apache/iceberg/nessie/TestMultipleClients.java
Consider the scenario,
a) client1 - java Nessie catalog client creates a table1
b) client2 - spark + iceberg+ Nessie creates a table2
c) client3 - another java Nessie catalog client creates a table3
where all the 3 clients are connected to the same Nessie server. 
Now for the first client (client1), list tables show only one table even though all 3 clients are connected to the same Nessie server. 
The reason is only the catalog APIs that involves table operations (like `loadTable()`, `commit()`, etc) refresh the `NessieIcebergClient`. The APIs like `listTables()`, `listNamespaces()` use the old state as it doesn't use table operations. 
Changes:
- Pass null for the reference hash in api request for immutable references. So that server will use the latest hash
Other scenarios can be two …
> Nessie: Use latest hash for catalog APIs

- nessie/src/test/java/org/apache/iceberg/nessie/BaseTestIceberg.java
- nessie/src/test/java/org/apache/iceberg/nessie/TestMultipleClients.java
https://github.com/apache/iceberg/pull/6789 was merged recently and the PR didn't rebase before merging as there was no conflict.
But there was another PR that got merged https://github.com/apache/iceberg/pull/7146 which enforces the namespace creation. Hence the new tests failed. 
Apologies for breaking the master build!
> Nessie: Fix testcase failures

- core/src/main/java/org/apache/iceberg/actions/BinPackStrategy.java
- core/src/main/java/org/apache/iceberg/actions/FileRewriter.java
- core/src/main/java/org/apache/iceberg/actions/RewriteStrategy.java
- core/src/main/java/org/apache/iceberg/actions/SizeBasedDataRewriter.java
- core/src/main/java/org/apache/iceberg/actions/SizeBasedFileRewriter.java
- core/src/main/java/org/apache/iceberg/actions/SortStrategy.java
- spark/v3.3/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRewriteDataFilesProcedure.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/actions/RewriteDataFilesSparkAction.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/actions/SparkBinPackDataRewriter.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/actions/SparkBinPackStrategy.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/actions/SparkShufflingDataRewriter.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/actions/SparkSizeBasedDataRewriter.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/actions/SparkSortDataRewriter.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/actions/SparkSortStrategy.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/actions/SparkZOrderDataRewriter.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/actions/SparkZOrderStrategy.java
- spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteDataFilesAction.java
- spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/actions/TestSparkFileRewriter.java
This PR refactors our compaction code so that it can be used for position delete file rewrites.
In particular, the following interfaces/classes have been added.
- `FileRewriter` - a generic API for rewriting content files
- `SizeBasedFileRewriter` - a common rewriter for content files primary based on file size
- `SizeBasedDataRewriter` - a common data rewriter
- `SparkSizeBasedDataRewriter` - a Spark data rewriter that stages tasks and uses a commit coordinator
- `SparkBinPackDataRewriter` - a Spark data rewriter that uses bin-packing
- `SparkSortDataRewriter` - a Spark data rewriter that shuffles and sorts data
- `SparkZOrderDataRewriter` - a Spark data rewriter that shuffles and zorders data
The new API has the same behavior as the existing rewrite strategies.
> Core, Spark 3.3: Add FileRewriter API

- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/SparkWriteConf.java
- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/SparkWriteOptions.java
- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/source/SparkWrite.java
- spark/v3.1/spark/src/test/java/org/apache/iceberg/spark/sql/TestPartitionedWrites.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/SparkWriteConf.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/SparkWriteOptions.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/SparkWrite.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/sql/TestPartitionedWrites.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/SparkWriteConf.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/SparkWriteOptions.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/SparkWrite.java
- spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/sql/PartitionedWritesTestBase.java
- spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/sql/TestPartitionedWritesToWapBranch.java
Allow passing `output-spec-id` to the Spark writer, so that we can customize which partition spec to write. This is useful for when a table has more than one active spec (e.g. daily and hourly partition spec).
Fixes https://github.com/apache/iceberg/issues/6932
> Spark - Accept an `output-spec-id` that allows writing to a desired partition spec

- orc/src/main/java/org/apache/iceberg/orc/OrcIterable.java
- orc/src/test/java/org/apache/iceberg/orc/TestOrcDataReader.java
- spark/v3.3/build.gradle
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/data/vectorized/VectorizedSparkOrcReaders.java
- spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/data/TestVectorizedOrcDataReader.java
Currently Iceberg does not support the use of the selected vector when reading ORC Files. This requires reads on ORC to be run in compatibility mode by not setting `orc.filter.use.selected` in the presence of filter processing that is triggered via `orc.sarg.to.filter`.
Filter processing was introduced as part of [ORC-744](https://issues.apache.org/jira/browse/ORC-744) where ORC has the ability to filter out records and indicate this status in partially filtered batches using the selected vector in VectorizedRowBatch.
This PR uses the selected vector to determine valid rows when applicable.
ORC can only operate in compatibility mode by not setting `orc.filter.use.selected`. Enabling this will further hasten the processing of rows by ignoring rows that are already filtered out in the …
> [ORC][Spark] - Support selected vector with ORC reader on the row and batch reader

- flink/v1.17/flink/src/main/java/org/apache/iceberg/flink/source/FlinkSplitPlanner.java
- flink/v1.17/flink/src/main/java/org/apache/iceberg/flink/source/enumerator/ContinuousSplitPlannerImpl.java
- flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/source/TestIcebergSourceContinuous.java
When consuming a table in `TABLE_SCAN_THEN_INCREMENTAL` mode and its snapshot history has expired, data can be lost. This is because `checkScanMode` returns incremental mode when the scan context is streaming. To address this issue, we have added a case to handle the `TABLE_SCAN_THEN_INCREMENTAL` mode.
> Flink: use correct scan mode when in TABLE_SCAN_THEN_INCREMENTAL mode

- docs/hive.md
I had the impression that the original sentence (`You will also need to set the following property in the Hive configuration: tez.mrreader.config.update.properties=hive.io.file.readcolumn.names,hive.io.file.readcolumn.ids.`) meant that this configuration was needed for the Tez engine on Hive 2.3.x only.
Besides, I thought that `Hive configuration` meant `hive-site.xml` rather than `tez-site.xml`.
Hence, I propose this change in wording to make it clearer.
> Docs: clarify Hive on Tez configuration

- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/SparkWriteConf.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/SparkWriteConf.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/SparkWriteConf.java
Rely only on `Table` to verify that `output-spec-id` is valid. This avoids having to keep the partition specs on 3.2 and 3.3 which are already present within the `Table`.
This is a follow-up to comment https://github.com/apache/iceberg/pull/7120#discussion_r1166312659 in the previous PR.
> Spark -Simplify checks of output-spec-id in SparkWriteConf

- core/src/main/java/org/apache/iceberg/MetadataUpdate.java
Looks like I caught a typo from @rdblue :)
> Fix SetDefaultPartitionSpec to use specId instead of schemaId

- core/src/main/java/org/apache/iceberg/LocationProviders.java
- spark/v3.3/spark/src/test/java/org/apache/iceberg/TestTableSerialization.java
ThreadLocal is not serializable, hence using this in serializing the ObjectStoreLocationProvider makes it non-serializable which is used in creating the Serializable instance of table fail (which is used by spark to broadcast this instance to the executor, while doing read / write). Since by default ObjectLocationProvider was disabled hence this couldn't be caught by serialization tests automatically. 
Thanks @nastra for reporting this issue via https://github.com/apache/iceberg/issues/7345.
This change makes the ThreadLocal obj static, as well as make table serialization test run with / without obj store enabled property. 
cc @rdblue @jackye1995 @nastra
> Core, Spark: Make ObjectStoreLocationProvider serializable

- core/src/test/java/org/apache/iceberg/util/TestParallelIterable.java
Fix flaky TestParallelIterable test 
Related issue: https://github.com/apache/iceberg/issues/7367
cc : @nastra @jackye1995 @rdblue
> Core: Fix flaky TestParallelIterable test

- data/src/test/java/org/apache/iceberg/data/GenericAppenderHelper.java
- flink/v1.17/flink/src/main/java/org/apache/iceberg/flink/FlinkSourceFilter.java
- flink/v1.17/flink/src/main/java/org/apache/iceberg/flink/source/FlinkInputFormat.java
- flink/v1.17/flink/src/main/java/org/apache/iceberg/flink/source/IcebergSource.java
- flink/v1.17/flink/src/main/java/org/apache/iceberg/flink/source/RowDataFileScanTaskReader.java
- flink/v1.17/flink/src/main/java/org/apache/iceberg/flink/source/RowDataRewriter.java
- flink/v1.17/flink/src/main/java/org/apache/iceberg/flink/source/reader/AvroGenericRecordReaderFunction.java
- flink/v1.17/flink/src/main/java/org/apache/iceberg/flink/source/reader/RowDataReaderFunction.java
- flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/source/TestFlinkInputFormat.java
- flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/source/TestFlinkScan.java
- flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/source/TestFlinkSource.java
- flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/source/TestIcebergSourceBounded.java
- flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/source/TestIcebergSourceBoundedGenericRecord.java
- flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/source/reader/ReaderUtil.java
- flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/source/reader/TestIcebergSourceReader.java
- flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/source/reader/TestRowDataReaderFunction.java
For Flink, we apply partition pruning, filtering based on metrics, and row-group skipping, but no row-level filtering.
See the issue for more details
Resolves #7022
@stevenzwu would you have time to take a peek at this one?
> Flink: Apply row level filtering

- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/SparkMicroBatchStream.java
- spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/source/TestStructuredStreamingRead3.java
Fixes https://github.com/apache/iceberg/issues/6388.
Based on the stack trace the following sequence of events seems plausible. 
1.) [The snapshot ID for current offset no longer exists (my hunch is due to expiration)](https://github.com/apache/iceberg/blob/master/spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/SparkMicroBatchStream.java#L210). So table.snapshot(currentOffset.snapshotId()) returns null.
2.) Then planning throws an unclear [NPE](https://github.com/apache/iceberg/blob/master/spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/SparkMicroBatchStream.java#L229) here when trying to get the operation associated with the snapshot. 
This is possible when resuming reading from a checkpoint where the snapshot associated with the checkpoint was expired.
> Spark: Surface better error message during streaming planning when checkpoint snapshot not found

- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/SparkMicroBatchStream.java
- spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/source/TestStructuredStreamingRead3.java
This PR backports #6480 to 3.3 as it is part of 3.4 after PR #7378.
> Spark 3.3: Surface better error message during streaming planning when checkpoint snapshot not found

- api/src/main/java/org/apache/iceberg/metrics/LoggingMetricsReporter.java
- core/src/main/java/org/apache/iceberg/SnapshotScan.java
- core/src/main/java/org/apache/iceberg/TableScanContext.java
- core/src/main/java/org/apache/iceberg/metrics/MetricsReporters.java
- core/src/test/java/org/apache/iceberg/TestScanPlanningAndReporting.java
- core/src/test/java/org/apache/iceberg/metrics/TestMetricsReporters.java
This introduces a `CompositeMetricsReporter` that allows registering multiple (simple) `MetricsReporter` instances that all get notified whenever a new `MetricsReport` is available.
This also switches from a collection of reporters to the `CompositeMetricsReporter` in `TableScanContext` to fix an issue where duplicate reporters were not handled (see https://github.com/apache/iceberg/pull/7337#discussion_r1165597698 for details).
> Core: Introduce CompositeMetricsReporter

- core/src/main/java/org/apache/iceberg/actions/BaseRewriteDataFilesAction.java
- flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/actions/TestRewriteDataFilesAction.java
When rewriting data files using Spark, the original starting sequence number is assigned to the rewritten files to avoid possible conflicts with newer eq-delete files. However, when rewriting data files using Flink, rewritten files are currently assigned a new sequence number. Consequently, conflicts between rewritten files and new eq-delete files cannot be ignored while checking conflicts in MergingSnapshotProducer.validateNoNewDeletesForDataFiles(). This creates an issue when continuously committing new eq-delete files to a table as we won't be able to rewrite files without conflicts.
This PR proposes to solve this problem by enabling Flink to use the starting sequence number by default when rewriting data files.
> Flink: Use starting sequence number by default when rewriting data files

- flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/sink/shuffle/DataStatistics.java
- flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/sink/shuffle/DataStatisticsEvent.java
- flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/sink/shuffle/DataStatisticsFactory.java
- flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/sink/shuffle/DataStatisticsOperator.java
- flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/sink/shuffle/DataStatisticsOrRecord.java
- flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/sink/shuffle/MapDataStatistics.java
- flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/sink/shuffle/MapDataStatisticsFactory.java
- flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/sink/shuffle/TestDataStatisticsOperator.java
Backport https://github.com/apache/iceberg/pull/6382 and https://github.com/apache/iceberg/pull/7269 to Flink 1.15
> Flink: Backport #6382 and #7269 to 1.15 for shuffle operator

- docs/delta-lake-conversion.md
- docs/delta-lake-migration.md
- docs/hive-migration.md
- docs/table-migration.md
Add documentation for the `iceberg-delta-lake` module created in #6449 and pointers to Hive/Spark table migration procedures specified in Spark Doc.
Closes #6770
> Doc: Add a page explaining migration from other table formats to iceberg

- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/SparkMicroBatchStream.java
As part of implementing `SupportsAdmissionControl` we now implement `Offset latestOffset(Offset startOffset, ReadLimit limit);` it faces the same problem as here https://github.com/apache/iceberg/pull/6480 , this change now throws an IllegalStateException instead of NPE and the ci for rate-limit pr had not run been rebased and re-run this couldn't be caught.
This pr attempts to fix the issue by having the similar handling. 
failing ut's pass now 
cc @jackye1995
> Spark: Fix failing SS UT

- mr/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergFilterFactory.java
- mr/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergFilterFactory.java
Fixes https://github.com/apache/iceberg/issues/7122
Handles issues when converting `SearchArguments` where tree and leaf arrays are not in sync.
The changes in PR make sure that whenever we access certain array indexes they are within bounds expected.
> MR: Fix IndexOutOfBounds by skip filter translation if there are no leaves

- aws/src/integration/java/org/apache/iceberg/aws/dynamodb/TestDynamoDbCatalog.java
- aws/src/main/java/org/apache/iceberg/aws/dynamodb/DynamoDbCatalog.java
- aws/src/test/java/org/apache/iceberg/aws/dynamodb/TestDynamoDbCatalog.java
Without getting the string value of the attribute, the formed the defaultWarehousePath is not in expected format.
cc @amogh-jahagirdar @jackye1995 @yyanyy
> AWS: Fix default warehouse path in Dynamodb catalog

- flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/source/RowDataFileScanTaskReader.java
- flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/source/RowDataRewriter.java
- flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/source/reader/AvroGenericRecordReaderFunction.java
- flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/source/reader/RowDataReaderFunction.java
- flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/source/reader/ReaderUtil.java
- flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/source/reader/TestIcebergSourceReader.java
- flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/source/reader/TestRowDataReaderFunction.java
seems that we have some divergencies from the backport effort. maintaining the versions in sync can make future backport easier when comparing git diff result.
Here are the remaining diffs after this sync. they are due to changes in 1.16 or 1.17.
git diff --no-index  flink/v1.16/flink/src/ flink/v1.17/flink/src
```
diff --git a/flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/actions/TestRewriteDataFilesAction.java b/flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/actions/TestRewriteDataFilesAction.java
index 07e5ca051..e59d7dacd 100644
--- a/flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/actions/TestRewriteDataFilesAction.java
+++ b/flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/actions/TestRewriteDataFilesAction.java
@@ -22,20 +22,15 @@ import static …
```
> Flink: sync 1.16 with 1.17 for backports missed or not ported identically

- flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/CatalogLoader.java
- flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/FlinkEnvironmentContext.java
- flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/TableLoader.java
- flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/sink/IcebergFilesCommitter.java
- flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/source/RowDataFileScanTaskReader.java
- flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/source/RowDataRewriter.java
- flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/source/reader/AvroGenericRecordReaderFunction.java
- flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/source/reader/RowDataReaderFunction.java
- flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/FlinkCatalogTestBase.java
- flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/FlinkTestBase.java
- flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/TestChangeLogTable.java
- flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/TestFlinkHiveCatalog.java
- flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/source/TestFlinkMergingMetrics.java
- flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/source/reader/ReaderUtil.java
- flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/source/reader/TestIcebergSourceReader.java
- flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/source/reader/TestRowDataReaderFunction.java
seems that we have some divergencies from the backport effort. maintaining the versions in sync can make future backport easier when comparing `git diff` result.
Here are the remaining diffs after this sync. they are due to changes in 1.15 or 1.17.
git diff --no-index  flink/v1.15/flink/src/ flink/v1.17/flink/src
```
diff --git a/flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/source/TestFlinkTableSource.java b/flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/source/TestFlinkTableSource.java
index 26201c7a5..d72f57dce 100644
--- a/flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/source/TestFlinkTableSource.java
+++ b/flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/source/TestFlinkTableSource.java
@@ -97,7 +97,7 @@ public class TestFlinkTableSource extends …
```
> Flink: sync 1.15 with 1.17 for backports missed or not ported identically

- format/view-spec.md
This cleans up and clarifies a few places in the view spec. It is formatted to be more like the table spec.
> Views: Clean up and clarify the view spec

- api/src/main/java/org/apache/iceberg/view/ViewVersion.java
- core/src/main/java/org/apache/iceberg/view/SQLViewRepresentationParser.java
- core/src/main/java/org/apache/iceberg/view/ViewRepresentationParser.java
- core/src/main/java/org/apache/iceberg/view/ViewVersionParser.java
- core/src/test/java/org/apache/iceberg/view/TestViewRepresentationParser.java
- core/src/test/java/org/apache/iceberg/view/TestViewVersionParser.java
This fixes the field name for view column descriptions and has a few other minor updates.
> Views: Fix SQL view representation field name

- core/src/main/java/org/apache/iceberg/TableProperties.java
- core/src/main/java/org/apache/iceberg/hadoop/ConfigProperties.java
- docs/configuration.md
- hive-metastore/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java
- hive-metastore/src/main/java/org/apache/iceberg/hive/MetastoreUtil.java
- hive-metastore/src/main/java/org/apache/iceberg/hive/NoLock.java
- hive-metastore/src/test/java/org/apache/iceberg/hive/TestHiveCommitLocks.java
- hive-metastore/src/test/java/org/apache/iceberg/hive/TestHiveCommits.java
HIVE-26882 gives us the possibility to atomically change the `metadata_location` using a single `alter_table` HMS call. The change is a new feature, so exception is needed from the Hive community to include it to new releases. OTOH I deliberately kept simple, so if someone uses their own Hive release they could backport the change easily.
If we start using this possibility we can avoid using HMS locks to ensure the atomicity of the `HiveTableOperations.commit`. This has the following benefits:
- Instead of 4 HMS calls (lock, getTable, alter_table, unlock) we can use only 2 calls (getTable, alter_table) which could help in commit performance.
- I have seen several complains when the locks were not removed correctly (#3336, #2301) and suggested solutions (#6370). Also did my share to fix …
> Hive: Use EnvironmentContext instead of Hive Locks to provide transactional commits after HIVE-26882

- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/source/SparkMicroBatchStream.java
- spark/v3.1/spark/src/test/java/org/apache/iceberg/spark/source/TestStructuredStreamingRead3.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/SparkMicroBatchStream.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/source/TestStructuredStreamingRead3.java
Backport #6480 to Spark 3.2 and Spark 3.1
CC: @aokolnychyi @RussellSpitzer @jackye1995
> Spark: Backport #6480 to Spark 3.2 and Spark 3.1

- .palantir/revapi.yml
- api/src/main/java/org/apache/iceberg/view/SQLViewRepresentation.java
- api/src/main/java/org/apache/iceberg/view/ViewVersion.java
- core/src/main/java/org/apache/iceberg/view/SQLViewRepresentationParser.java
- core/src/main/java/org/apache/iceberg/view/ViewVersionParser.java
- core/src/test/java/org/apache/iceberg/view/TestSQLViewRepresentationParser.java
- core/src/test/java/org/apache/iceberg/view/TestViewVersionParser.java
Follow up from https://github.com/apache/iceberg/pull/6559#discussion_r1161329781 . The conclusion was that it's better to make schema required and part of the ViewVersion since all representations should share the same schema.
> API, Core: Move schemaID from ViewRepresentation to ViewVersion and make it required

- spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/source/SparkPartitioningAwareScan.java
This PR simplifies `SparkPartitioningAwareScan` as SPARK-41398 is part of 3.4. We no longer have to ensure the same set of keys is reported back to Spark after runtime filtering. No new tests are needed as existing tests would fail without this logic.
> Spark 3.4: Relax constraints in SparkPartitioningAwareScan

- core/src/main/java/org/apache/iceberg/rest/RESTMetricsReporter.java
- core/src/main/java/org/apache/iceberg/rest/RESTSessionCatalog.java
depends on https://github.com/apache/iceberg/pull/7337
> Core: Extract REST metrics reporter into its own class

- spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestStoragePartitionedJoinsInRowLevelOperations.java
- spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/sql/TestStoragePartitionedJoins.java
This PR adds tests for SPJ when partition keys mismatch, which was not supported prior to 3.4. Now Iceberg supports SPJ in MERGE without limitations.
> Spark 3.4: Add tests for SPJ when partition keys mismatch

- .github/workflows/delta-conversion-ci.yml
- .github/workflows/hive-ci.yml
- .github/workflows/java-ci.yml
- .github/workflows/spark-ci.yml
- api/src/main/java/org/apache/iceberg/expressions/ExpressionUtil.java
- api/src/test/java/org/apache/iceberg/expressions/TestExpressionUtil.java
- build.gradle
- jmh.gradle
- mr/build.gradle
- spark/v3.3/build.gradle
- spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/source/TestMetadataTableReadableMetrics.java
- spark/v3.4/build.gradle
- spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/source/TestMetadataTableReadableMetrics.java
This change adds a CI to run iceberg with JDK 17, considering now most of the engines are adding support for jdk 17 for ex : trino, spark.
Fixes: https://github.com/apache/iceberg/issues/7290
cc @jackye1995
> Build: Run Iceberg with JDK 17

- python/pyiceberg/io/fsspec.py
Use fsspec implementation of LocalFileSysteminstead of pyarrow implementation
the io implementation [prefers ](https://github.com/apache/iceberg/blob/master/python/pyiceberg/io/__init__.py#L264)pyarrow and will [check if the ](https://github.com/apache/iceberg/blob/master/python/pyiceberg/io/__init__.py#L292-L301)pyarrow[ library exists](https://github.com/apache/iceberg/blob/master/python/pyiceberg/io/__init__.py#L292-L301). it then falls back to the fsspec implementation which [currently requires ](https://github.com/apache/iceberg/blob/master/python/pyiceberg/io/fsspec.py#L34)pyarrow[ as well](https://github.com/apache/iceberg/blob/master/python/pyiceberg/io/fsspec.py#L34)
from pyarrow.filesystem import LocalFileSystem
so it looks like theres current no way to use the fsspec io …
> Use fsspec implementation of LocalFileSystem

- core/src/main/java/org/apache/iceberg/ClientPoolImpl.java
- hive-metastore/src/main/java/org/apache/iceberg/hive/CachedClientPool.java
- hive-metastore/src/test/java/org/apache/iceberg/hive/TestCachedClientPool.java
Fixed a bug that could leak hive client connections.
Caffeine cache will not always call removelistener by default, so an extra scheduler is required to invoke removelistener.
See: https://github.com/google/guava/issues/3295.
> Hive: Clean up expired metastore clients

- core/src/main/java/org/apache/iceberg/BaseIncrementalChangelogScan.java
- core/src/main/java/org/apache/iceberg/BaseMetadataTableScan.java
- core/src/main/java/org/apache/iceberg/BaseTable.java
- core/src/main/java/org/apache/iceberg/PositionDeletesTable.java
- core/src/main/java/org/apache/iceberg/TableScanContext.java
- core/src/test/java/org/apache/iceberg/TestScanPlanningAndReporting.java
This is a shorter alternative to #5982
> Core: Make TableScanContext immutable

- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/SparkReadConf.java
- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/source/SparkMicroBatchStream.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/SparkReadConf.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/SparkMicroBatchStream.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/SparkReadConf.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/SparkMicroBatchStream.java
- spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/SparkReadConf.java
- spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/source/SparkMicroBatchStream.java
Address review feedback https://github.com/apache/iceberg/pull/7422#discussion_r1175813062 .
cc @aokolnychyi
> Spark: Refactor SparkReadConf use primitive type for confs with default values

- arrow/src/main/java/org/apache/iceberg/arrow/DictEncodedArrowConverter.java
- arrow/src/main/java/org/apache/iceberg/arrow/vectorized/ArrowReader.java
- arrow/src/main/java/org/apache/iceberg/arrow/vectorized/ArrowVectorAccessors.java
- arrow/src/main/java/org/apache/iceberg/arrow/vectorized/ColumnVector.java
- arrow/src/main/java/org/apache/iceberg/arrow/vectorized/ColumnarBatch.java
- arrow/src/main/java/org/apache/iceberg/arrow/vectorized/VectorHolder.java
- arrow/src/main/java/org/apache/iceberg/arrow/vectorized/VectorizedArrowReader.java
- arrow/src/test/java/org/apache/iceberg/arrow/vectorized/ArrowReaderTest.java
For testing we would like to check the Arrow Schema, but since dict-encoded Vectors all end up being of type `IntVector`, we essentially can't perform this check. That's why https://github.com/apache/iceberg/blob/master/arrow/src/test/java/org/apache/iceberg/arrow/vectorized/ArrowReaderTest.java#L207-L213 is currently ignored on `master`.
The goal of this PR is to convert dict-encoded vector to their correct vector types, so that a Schema check is possible. Note that this PR only affects code relevant for testing and not for production.
Note that this currently contains the commit from https://github.com/apache/iceberg/pull/3023, but will be rebased once #3023 is merged.
fixes #2484 
```
Benchmark                                                                 Mode  Cnt  Score   Error …
```
> Arrow: Convert dict encoded vectors to their expected Arrow vector types

- delta-lake/src/integration/java/org/apache/iceberg/delta/TestSnapshotDeltaLakeTable.java
- delta-lake/src/main/java/org/apache/iceberg/delta/BaseSnapshotDeltaLakeTableAction.java
Fixes #6769 
For each Iceberg transaction migrated, add `delta-version-xxx` and `delta-ts-xxxxx` tag to the snapshot. `delta-version-xxx` represents the logical delta lake version. `delta-ts-xxxxx` represents the commit time of the corresponding delta lake transaction
> Delta Migration: Add version and timestamp tags for each Delta Lake transaction when add to Iceberg transaction

- python/pyiceberg/conversions.py
mkdocs was generating a set of warnings for python/pyiceberg/conversions.py - from_bytes(...) function, per issue #7458 I have fixed this issue, following guidance from initial open. Let me know if there are any questions.
> Python: fix `mkdocs` warnings from `conversions.py`

- python/pyiceberg/conversions.py
- python/pyiceberg/expressions/visitors.py
Updated comments for visitor.py file to remove mkdocs WARNINGS, running in --strict mode for identification and resolution. Part of resolution set for issue #7458
> Python: fix `mkdocs` warnings from `visitors.py`

- spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/source/TestStructuredStreamingRead3.java
Post https://github.com/apache/iceberg/pull/7443). The UT of `testReadStreamOnIcebergTableWithMultipleSnapshots_WithNumberOfRows_1` SS started failing, it requires a certain number of files, and hence the same handling as [here](https://github.com/apache/iceberg/pull/7443/files#diff-bd2fb8a4edce59a36cbee408d65ad03b31e1b3431c4aaa180eb4db87755147e8R136) . Since the CI hasn't run post merging [PR](https://github.com/apache/iceberg/pull/7443/) this couldn't be caught. 
cc @jackye1995 @szehon-ho @wypoon
> Spark: Fix Failing SS ratelimit UT

- spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/sql/TestAlterTable.java
- spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/sql/TestCreateTable.java
- spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/sql/TestDeleteFrom.java
- spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/sql/TestDropTable.java
- spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/sql/TestNamespaceSQL.java
- spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/sql/TestSelect.java
- spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/sql/TestSparkBucketFunction.java
- spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/sql/TestSparkDaysFunction.java
- spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/sql/TestSparkHoursFunction.java
- spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/sql/TestSparkMonthsFunction.java
- spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/sql/TestSparkTruncateFunction.java
- spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/sql/TestSparkYearsFunction.java
- spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/sql/TestTimestampWithoutZone.java
- spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/sql/UnpartitionedWritesTestBase.java
Remove `AssertHelpers` in `iceberg-spark-sql` module.
> Spark: Remove Usage of deprecated AssertHelpers in spark-sql

- hive-metastore/src/main/java/org/apache/iceberg/hive/CachedClientPool.java
- hive-metastore/src/main/java/org/apache/iceberg/hive/HiveCatalog.java
- hive-metastore/src/test/java/org/apache/iceberg/hive/TestCachedClientPool.java
_Note:   As the term Hive-Catalog is overloaded across, I'll use "Iceberg-HiveCatalog" to refer to Iceberg's HiveCatalog class and "HMS Catalog" to refer to Hive specific concept._
https://issues.apache.org/jira/browse/HIVE-18685 added support for HMS catalogs, ie different namespaces for dbs/tables in the metastore.
However, the Iceberg-HiveCatalog uses a global cache of HMS connections based on Hive-Metastore-URI.  This prevents different Iceberg-HiveCatalogs existing in same JVM from talking to different HMS Catalogs on same HMS.  See issue:  https://github.com/apache/iceberg/pull/5378.  This is important for example in Spark, where user may try to configure different SparkCatalog pointing to separate catalog on same HMS.   
This change takes advantage of …
> Hive: Support connecting to multiple Hive-Catalog

- api/src/main/java/org/apache/iceberg/util/UUIDUtil.java
- api/src/test/java/org/apache/iceberg/util/RandomUtil.java
- arrow/src/main/java/org/apache/iceberg/arrow/vectorized/GenericArrowVectorAccessorFactory.java
- spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/data/SparkAvroWriter.java
- spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/data/SparkOrcReader.java
- spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/data/SparkOrcValueReaders.java
- spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/data/SparkOrcValueWriters.java
- spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/data/SparkOrcWriter.java
- spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/data/SparkParquetReaders.java
- spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/data/SparkParquetWriters.java
- spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/data/vectorized/ArrowVectorAccessorFactory.java
- spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/data/vectorized/VectorizedSparkOrcReaders.java
- spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/data/AvroDataTest.java
- spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/data/RandomData.java
- spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/data/TestSparkParquetWriter.java
fixes https://github.com/apache/iceberg/issues/4581
> Spark: Add read/write support for UUIDs

- hive-metastore/src/test/java/org/apache/iceberg/hive/HiveCreateReplaceTableTest.java
- hive-metastore/src/test/java/org/apache/iceberg/hive/HiveTableTest.java
- hive-metastore/src/test/java/org/apache/iceberg/hive/TestHiveCatalog.java
- hive-metastore/src/test/java/org/apache/iceberg/hive/TestHiveClientPool.java
- hive-metastore/src/test/java/org/apache/iceberg/hive/TestHiveCommitLocks.java
- hive-metastore/src/test/java/org/apache/iceberg/hive/TestHiveCommits.java
- hive-metastore/src/test/java/org/apache/iceberg/hive/TestHiveSchemaUtil.java
- mr/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergFilterFactory.java
- orc/src/test/java/org/apache/iceberg/orc/TestORCSchemaUtil.java
Remove AssertHelpers in `iceberg-hive-metastore` module
> Hive: Remove deprecated AssertHelpers

- flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/TestFlinkCatalogDatabase.java
- flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/TestFlinkCatalogFactory.java
- flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/TestFlinkCatalogTable.java
- flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/TestFlinkCatalogTablePartitions.java
- flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/TestFlinkSchemaUtil.java
- flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/TestIcebergConnector.java
- flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/data/TestRowDataProjection.java
- flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSink.java
- flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkV2.java
- flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkV2Base.java
- flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/source/TestFlinkScan.java
- flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/source/TestFlinkSourceConfig.java
- flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/source/TestFlinkTableSource.java
- flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/source/TestStreamScanSql.java
- flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/source/TestStreamingMonitorFunction.java
- flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/source/enumerator/TestContinuousSplitPlannerImpl.java
- flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/source/enumerator/TestContinuousSplitPlannerImplStartStrategy.java
Remove AssertHelpers in `iceberg-flink` module
> Flink: Remove deprecated AssertHelpers

- spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/TestFunctionCatalog.java
- spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/actions/TestDeleteReachableFilesAction.java
- spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/actions/TestExpireSnapshotsAction.java
- spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/actions/TestRemoveOrphanFilesAction.java
- spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteDataFilesAction.java
- spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteManifestsAction.java
- spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/data/parquet/vectorized/TestParquetVectorizedReads.java
- spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/source/TestDataFrameWriterV2.java
- spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/source/TestDataSourceOptions.java
- spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/source/TestForwardCompatibility.java
- spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSourceTablesBase.java
- spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/source/TestMetadataTablesWithPartitionEvolution.java
- spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/source/TestRequiredDistributionAndOrdering.java
- spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkDataWrite.java
- spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkMetadataColumns.java
- spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/source/TestStructuredStreamingRead3.java
- spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/source/TestTimestampWithoutZone.java
- spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/source/TestWriteMetricsConfig.java
Remove AssertHelpers in `iceberg-spark` module except `spark.sql` package, which will be resolved in next PR.
> Spark: Remove deprecated AssertHelpers

- docs/spark-configuration.md
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/SparkCatalog.java
- spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/SparkCatalog.java
I want to include new features we developed over last few releases to be reflected in javadoc of SparkCatalog as it's lacking at the moment
- catalog default/override in #4011
- rest catalog in #5570 
- catalog io-impl in #1618 
- catalog metrics-reporter-impl in #6404
CC @jackye1995 @Fokko @SinghAsDev @nastra
> Update documentation to reflect new catalog features

- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/data/SparkAvroWriter.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/data/SparkOrcReader.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/data/SparkOrcValueReaders.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/data/SparkOrcValueWriters.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/data/SparkOrcWriter.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/data/SparkParquetReaders.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/data/SparkParquetWriters.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/data/vectorized/ArrowVectorAccessorFactory.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/data/vectorized/VectorizedSparkOrcReaders.java
- spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/data/AvroDataTest.java
- spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/data/RandomData.java
- spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/data/TestSparkParquetWriter.java
- spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/data/SparkOrcValueWriters.java
This backports #7399 to Spark 3.3
> Spark 3.3: Add read and write support for UUIDs

- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/data/SparkAvroWriter.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/data/SparkOrcReader.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/data/SparkOrcValueReaders.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/data/SparkOrcValueWriters.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/data/SparkOrcWriter.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/data/SparkParquetReaders.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/data/SparkParquetWriters.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/data/vectorized/ArrowVectorAccessorFactory.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/data/vectorized/VectorizedSparkOrcReaders.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/data/AvroDataTest.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/data/RandomData.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/data/TestSparkParquetWriter.java
This backports #7399 to Spark 3.2
> Spark 3.2: Add read and write support for UUIDs

- api/src/main/java/org/apache/iceberg/catalog/Catalog.java
- api/src/main/java/org/apache/iceberg/catalog/ViewCatalog.java
`NotFoundException` is used for file-based operations and no catalog is throwing it for `listTables`.
Hence, updating it based on the current implementations.
> API: Update java doc for listTables and listViews

- core/src/main/java/org/apache/iceberg/PartitionsTable.java
- core/src/main/java/org/apache/iceberg/util/PartitionUtil.java
This code was added in https://github.com/apache/iceberg/pull/4560.
I now realize I could have used an existing util class for coercing (normalizing) partition data to the final type, instead of writing my own method.
> Core: Simplify Partitions table partition-coercion code

- core/src/main/java/org/apache/iceberg/CatalogProperties.java
- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/SparkCatalog.java
- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/SparkUtil.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/SparkCatalog.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/SparkCatalog.java
- spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/SparkCatalog.java
If this configuration is not set, and caching is enabled, the SparkCatalog uses a CachingCatalog with case sensitivity that matches the runtime configuration of `spark.sql.caseSensitive` in the SparkSession.
Motivation:
The `CachingCatalog` has a field that determines if the cache uses case sensitive `TableIdentifier` keys. By default, caching is enabled and the `SparkCatalog` wraps itself in a case sensitive `CachingCatalog`. There is no configuration to allow specifying the use of a case insensitive `CachingCatalog`.
In a customer SQL workload, we discovered that queries used inconsistent case for database and table names. A table is read using an upper case name and is updated using a lower case name. This is not incorrect as SQL is case insensitive for database, table and column …
> Core, Spark: Add configuration to control case sensitivity of CachingCatalog

- spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestDelete.java
- spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMerge.java
- spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestUpdate.java
- spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/source/SparkPositionDeltaWrite.java
- spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/source/SparkWrite.java
This PR enables AQE to handle skew in writes.
> Spark 3.4: Handle skew in writes

- format/view-spec.md
Spec: Update View spec to reflect that schema is defined at the version level  and is required
> Spec: Update View spec to reflect that schema is defined at the version level  and is required

- spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestDelete.java
- spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMerge.java
- spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestUpdate.java
This PR adds tests to verify AQE can coalesce small writing tasks.
> Spark 3.4: Tests for coalescing small writing tasks

- core/src/main/java/org/apache/iceberg/PartitionsTable.java
- core/src/test/java/org/apache/iceberg/MetadataTableScanTestBase.java
- core/src/test/java/org/apache/iceberg/TestMetadataTableScans.java
- core/src/test/java/org/apache/iceberg/TestMetadataTableScansWithPartitionEvolution.java
- spark/v3.1/spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSourceTablesBase.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSourceTablesBase.java
- spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSourceTablesBase.java
- spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSourceTablesBase.java
Currently [partitions metadata table](https://iceberg.apache.org/docs/latest/spark-queries/#partitions) only has the data file stats 
```
file_count
record_count
```
When the delete files are present, these stats are inaccurate (as we don't decrement these values). 
So, capture the delete file stats to give a rough idea about why these stats are inaccurate.
**Note that we are not applying the deletes to the data file and computing the effective result as it will be a very expensive operation. Users are suggested to execute rewrite_data_files periodically to apply the delete files to the data files.**
Delete file stats to be added:
```
pos_delete_file_count
pos_delete_record_count
eq_delete_file_count
eq_delete_record_count
```
Note:
- Docs will be updated in a follow-up PR, probably after …
> Core: Support delete file stats in partitions metadata table

- core/src/main/java/org/apache/iceberg/CatalogProperties.java
- spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/SparkCatalog.java
- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/SparkCatalog.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/SparkCatalog.java
- spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/SparkCatalog.java
Follow up to https://github.com/apache/iceberg/pull/7469.
To avoid breaking Spark users of Nessie, restore the former default behavior.
The case sensitivity of the CachingCatalog that wraps the SparkCatalog is still configurable, but it defaults to true.
> Make SparkCatalog use a case sensitive CachingCatalog by default.

- core/src/test/java/org/apache/iceberg/TableTestBase.java
When dropping ManifestEntry.sequenceNumber in #6274, a new assert was added to TableTestBase.validateManifests(). However, there was a same assert already. Dropping one of them.
> Core: Remove duplicate check for ManifestEntry.dataSequenceNumber()

- aws/src/integration/java/org/apache/iceberg/aws/s3/TestS3FileIOIntegration.java
- aws/src/integration/java/org/apache/iceberg/aws/s3/TestS3MultipartUpload.java
- aws/src/main/java/org/apache/iceberg/aws/s3/BaseS3File.java
- aws/src/main/java/org/apache/iceberg/aws/s3/S3FileIO.java
- aws/src/main/java/org/apache/iceberg/aws/s3/S3InputFile.java
- aws/src/main/java/org/apache/iceberg/aws/s3/S3InputStream.java
- aws/src/main/java/org/apache/iceberg/aws/s3/S3OutputFile.java
- aws/src/main/java/org/apache/iceberg/aws/s3/S3OutputStream.java
- aws/src/main/java/org/apache/iceberg/aws/s3/S3RequestUtil.java
- aws/src/test/java/org/apache/iceberg/aws/TestAwsClientFactories.java
- aws/src/test/java/org/apache/iceberg/aws/s3/TestS3OutputStream.java
- aws/src/test/java/org/apache/iceberg/aws/s3/TestS3RequestUtil.java
Subtask of https://github.com/apache/iceberg/issues/7515
This is a follow-up PR post my previous [PR](https://github.com/apache/iceberg/pull/7505) to add `S3FileIOProperties.java`.
This PR updates references to S3 related fields from AwsProperties within s3 package.
> Remove usages of S3 fields from AwsProperties within s3 package

- flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/TestFlinkCatalogDatabase.java
- flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/TestFlinkCatalogTable.java
- flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/TestFlinkCatalogDatabase.java
- flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/TestFlinkCatalogTable.java
- flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/TestFlinkCatalogDatabase.java
- flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/TestFlinkCatalogTable.java
replace `baseNamepace` with `baseNamespace`
> Flink: Fix Typo in Namespace

- api/src/main/java/org/apache/iceberg/RewriteFiles.java
- core/src/main/java/org/apache/iceberg/BaseRewriteFiles.java
- core/src/main/java/org/apache/iceberg/ManifestFilterManager.java
- core/src/main/java/org/apache/iceberg/MergingSnapshotProducer.java
- core/src/main/java/org/apache/iceberg/actions/BaseRewriteDataFilesAction.java
- core/src/main/java/org/apache/iceberg/actions/RewritePositionDeletesCommitManager.java
- core/src/test/java/org/apache/iceberg/TestRewriteFiles.java
This PR makes `RewriteFiles` more flexible and aligned with other APIs like `OverwriteFiles`. One valid use case is discussed in #7389, where we want to replace one set of delete files with another one. Instead of adding another overloaded method, we should make the interface flexible enough to support various combinations.
> API, Core: Make RewriteFiles flexible

- aws/src/main/java/org/apache/iceberg/aws/s3/S3FileIO.java
This PR adds a line that got removed by mistake when I rebased changes for my earlier [PR](https://github.com/apache/iceberg/pull/7534). 
Ran integ tests in TestS3FileIOIntegration, tests passed.
> AWS: Add missing line - assign param S3FileIOProperties inside constructor

- aws/src/main/java/org/apache/iceberg/aws/s3/S3FileIO.java
- core/src/main/java/org/apache/iceberg/io/ResolvingFileIO.java
When `S3FileIO` gets created through `ResolvingFileIO` then the creation stack
trace is being kept in `ResolvingFileIO`. `ResolvingFileIO` will then
close the underlying `S3FileIO` when `ResolvingFileIO#finalize()` gets
called. Therefore we don't want to issue a `WARN` in `S3FileIO` in case
`S3FileIO#finalize()` gets called before `ResolvingFileIO#finalize()`.
> Core, AWS: Add flag to control whether initialization stack trace should be created in S3FileIO

- aws/src/main/java/org/apache/iceberg/aws/AwsClientProperties.java
- aws/src/main/java/org/apache/iceberg/aws/AwsProperties.java
- aws/src/main/java/org/apache/iceberg/aws/HttpClientProperties.java
- aws/src/main/java/org/apache/iceberg/aws/s3/S3FileIOProperties.java
- aws/src/test/java/org/apache/iceberg/aws/AwsClientPropertiesTest.java
- aws/src/test/java/org/apache/iceberg/aws/HttpClientPropertiesTest.java
- aws/src/test/java/org/apache/iceberg/aws/s3/TestS3FileIOProperties.java
Subtask of #7516 
This PR creates separate class `HttpClientProperties`. Also, move all s3 related methods into `S3FileIOProperties` since we plan to deprecate `AwsProperties`. 
As part of #7156, when `S3FileIOAwsClientFactory` is added for creating S3 client, we will use methods from `S3FileIOProperties` and  `HttpClientProperties`.
Ran integ tests - `TestS3FileIOIntegration`, `TestS3MultipartUpload` and `TestDefaultAwsClientFactory`
> AWS: create HttpClientProperties, move s3 related methods into S3FileIOProperties

- core/src/main/java/org/apache/iceberg/PartitionsTable.java
- core/src/test/java/org/apache/iceberg/TestMetadataTableScans.java
- core/src/test/java/org/apache/iceberg/TestMetadataTableScansWithPartitionEvolution.java
Partitions Table schema checks only current spec to decide if partition column is returned or not. We should actually check historical specs to see if it was ever partitioned, similar to Files/Entries and other metadata tables.
Fixes #7533
> Core: Check for all specs in partitionsTable

- api/src/main/java/org/apache/iceberg/util/StructProjection.java
- flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/data/RowDataProjection.java
- flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/data/RowDataProjection.java
- flink/v1.17/flink/src/main/java/org/apache/iceberg/flink/data/RowDataProjection.java
Adjusted the same behavior in Flink RowDataProjection.
closes issue #7507
> API, Flink: StructProjection returns null projection object for null nested struct value

- core/src/test/java/org/apache/iceberg/catalog/CatalogTests.java
- core/src/test/java/org/apache/iceberg/catalog/TestTableIdentifierParser.java
Remove AssertHelpers in iceberg-core-catalog
> Core: Remove deprecated AssertHelpers usage in catalog

- flink/v1.17/flink/src/main/java/org/apache/iceberg/flink/data/RowDataProjection.java
- flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/DataGenerator.java
- flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/DataGenerators.java
- flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/data/TestRowDataProjection.java
Flink RowData implementation classes (like GenericRowData) all implement proper overrides for those methods. We also intend to use RowDataProjection as map key for MapDataStatistics from sink shuffling work. Hence this change is also required.
> Flink: add toString, equals, hashCode overrides for RowDataProjection.

- core/src/main/java/org/apache/iceberg/BaseEntriesTable.java
- core/src/test/java/org/apache/iceberg/TestEntriesMetadataTable.java
- core/src/test/java/org/apache/iceberg/TestMetadataTableScans.java
- spark/v3.1/spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSourceTablesBase.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSourceTablesBase.java
- spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSourceTablesBase.java
- spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSourceTablesBase.java
- spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/source/TestMetadataTableReadableMetrics.java
close #7364 
This enable query readable metrics on entry metadata table, similar to #5376 by @szehon-ho 
Given table schema like below
```schema
table {
1: id: optional int
2: data: optional string
}
```
we can query its per column min/max for each manifest entry
```sql
spark
.sql("select snapshot_id, readable_metrics.id.lower_bound, readable_metrics.data.upper_bound")
.show(false)
+-------------------+-----------+-----------+
|snapshot_id        |lower_bound|upper_bound|
+-------------------+-----------+-----------+
|8728349059432389037|1          |1          |
+-------------------+-----------+-----------+
```
> Implement ReadableMetrics for Entries table

- snowflake/src/main/java/org/apache/iceberg/snowflake/SnowflakeCatalog.java
- versions.props
This PR makes the JDBC application identifier unique for each catalog initialization and add another JDBC property to include the application identifier in the JDBC web request's user agent header.
Also updating to the latest version of snowflake's JDBC driver.
This PR is continued from https://github.com/apache/iceberg/pull/7176 due to a bad git rebase.
> Add unique JDBC application identifier and user agent header

- spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/data/vectorized/VectorizedSparkParquetReaders.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/data/TestHelpers.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/data/TestSparkParquetReadMetadataColumns.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/data/parquet/vectorized/TestParquetDictionaryEncodedVectorizedReads.java
- spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/data/parquet/vectorized/TestParquetVectorizedReads.java
- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/data/vectorized/VectorizedSparkParquetReaders.java
- spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/data/TestHelpers.java
- spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/data/TestSparkParquetReadMetadataColumns.java
- spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/data/parquet/vectorized/TestParquetDictionaryEncodedVectorizedReads.java
- spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/data/parquet/vectorized/TestParquetVectorizedReads.java
- spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/data/vectorized/VectorizedSparkParquetReaders.java
- spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/data/TestHelpers.java
- spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/data/TestSparkParquetReadMetadataColumns.java
- spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/data/parquet/vectorized/TestParquetDictionaryEncodedVectorizedReads.java
- spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/data/parquet/vectorized/TestParquetVectorizedReads.java
Remove deprecated VectorizedSparkParquetReaders#buildReader API for 1.3.0 release 
cc: @szehon-ho @aokolnychyi @nastra @singhpk234
> Spark: Remove deprecated VectorizedSparkParquetReaders#buildReader API for 1.3.0 release

- core/src/main/java/org/apache/iceberg/TableMetadata.java
- core/src/test/java/org/apache/iceberg/TestPartitioning.java
> Core: Allow deleting old partition spec columns in V1

- aws/src/integration/java/org/apache/iceberg/aws/s3/TestS3FileIOIntegration.java
- aws/src/main/java/org/apache/iceberg/aws/AwsClientProperties.java
- aws/src/main/java/org/apache/iceberg/aws/HttpClientProperties.java
- aws/src/main/java/org/apache/iceberg/aws/S3FileIOAwsClientFactories.java
- aws/src/main/java/org/apache/iceberg/aws/s3/DefaultS3FileIOAwsClientFactory.java
- aws/src/main/java/org/apache/iceberg/aws/s3/S3FileIO.java
- aws/src/main/java/org/apache/iceberg/aws/s3/S3FileIOAwsClientFactory.java
- aws/src/main/java/org/apache/iceberg/aws/s3/S3FileIOProperties.java
- aws/src/test/java/org/apache/iceberg/aws/TestS3FileIOAwsClientFactories.java
- aws/src/test/java/org/apache/iceberg/aws/s3/TestS3FileIOAwsClientFactory.java
This PR adds a new client factory class `S3FileIOAwsClientFactory` with catalog property `s3.client-factory-impl`. When `s3.client-factory-impl` is set to true, we instantiate `S3FileIOAwsClientFactory` class. If the property wasn't set, we fallback to `AwsClientFactory` factory classes.
> AWS: Add S3FileIOAwsClientFactory with s3.client-factory-impl catalog property for S3FileIO

- .gitignore
- jmh.gradle
- spark/v3.4/build.gradle
- spark/v3.4/spark-extensions/src/jmh/java/org/apache/iceberg/spark/MergeCardinalityCheckBenchmark.java
- spark/v3.4/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/analysis/RewriteMergeIntoTable.scala
- spark/v3.4/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/plans/logical/MergeRows.scala
- spark/v3.4/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/ExtendedDataSourceV2Strategy.scala
- spark/v3.4/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/MergeRowsExec.scala
This PR avoids an extra local sort to perform the cardinality check in MERGE. Instead, we can use a bitmap to check for matches within a partition as we rely on `MonotonicallyIncreasingID` expression that generates 64 bit longs. This change would be important when the size of a task is big and we may spill to disk. This is especially important for MERGE operations leveraging storage-partitioned joins or AQE. Such jobs tend to have larger tasks.
MoR used `_file` + `_pos` for the cardinality check. This PR migrates it to `MonotonicallyIncreasingID` to leverage the new mechanism. This also means we no longer copy the file name, which can be large and require quite a bit of memory.
> Spark 3.4: Avoid local sort for MERGE cardinality check

- core/src/main/java/org/apache/iceberg/util/StructLikeMap.java
- spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/actions/RewritePositionDeleteFilesSparkAction.java
- spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/actions/SparkActions.java
Fixup for #7389  
Ref:  https://github.com/apache/iceberg/pull/7389#pullrequestreview-1414025385
> Spark 3.4: Fixup for RewritePositionDeleteFilesSparkAction

- spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRewritePositionDeleteFilesProcedure.java
- spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/procedures/RewritePositionDeleteFilesProcedure.java
- spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/procedures/SparkProcedures.java
Adds a spark procedure: rewrite_position_delete_files for #7389
> Spark 3.4: Add RewritePositionDeleteFilesProcedure

- flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/FlinkReadConf.java
- flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/FlinkReadOptions.java
- flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/source/IcebergSource.java
- flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/source/ScanContext.java
- flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/source/enumerator/ContinuousIcebergEnumerator.java
- flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/source/enumerator/ManualContinuousSplitPlanner.java
- flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/source/enumerator/TestContinuousIcebergEnumerator.java
- flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/FlinkReadConf.java
- flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/FlinkReadOptions.java
- flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/source/IcebergSource.java
- flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/source/ScanContext.java
- flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/source/enumerator/ContinuousIcebergEnumerator.java
- flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/source/enumerator/ManualContinuousSplitPlanner.java
- flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/source/enumerator/TestContinuousIcebergEnumerator.java
> Flink: backport Add config for max allowed consecutive planning failures in IcebergSource before failing the job (#7571) to 1.16 and 1.15

- flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkManifestUtil.java
- flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java
- flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/sink/IcebergFilesCommitter.java
- flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/SimpleDataUtil.java
- flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSink.java
- flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkManifest.java
- flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/sink/TestIcebergFilesCommitter.java
We use a `SerializableTable` instance to create `IcebergStreamWriter`. The PartitionSpec of `SerializableTable` is fixed and will not change after the job started. While the PartitionSpec for `IcebergFilesCommitter` is refreshed with the table snapshot changing. This could fail the fink sink job when updating the partition spec in another job. Because we use the wrong partition spec to write those DataFiles/DeleteFiles to ManifestFile.
For example, we got the following error when updating the partition spec:
In this patch, we use the correct partition spec to write the staging manifest file.
> Flink: Fixes flink sink failed due to updating partition spec

- core/src/main/java/org/apache/iceberg/io/BasePositionDeltaWriter.java
- data/src/test/java/org/apache/iceberg/io/TestPositionDeltaWriters.java
This PR allows using a single data writer in `BasePositionDeltaWriter`.
> Core: Allow one data writer in BasePositionDeltaWriter

- spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/source/SparkPositionDeltaWrite.java
This PR contains minor cosmetic updates for `SparkPositionDeltaWrite`.
> Spark 3.4: Cosmetic updates for SparkPositionDeltaWrite

- spark/v3.4/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/CreateOrReplaceBranchExec.scala
- spark/v3.4/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/CreateOrReplaceTagExec.scala
- spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestBranchDDL.java
- spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestTagDDL.java
This fix help throw proper validation exception instead of NullPointerException when create branch or tag on iceberg table without any snapshot. 
```scala
Before
```scala
scala> val snapshotId = branchOptions.snapshotId.getOrElse(table.currentSnapshot().snapshotId())
at $anonfun$res38$1(<console>:47)
at scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.java:23)
at scala.Option.getOrElse(Option.scala:189)
... 51 elided
```
After
```scala
scala> val snapshotId: java.lang.Long = branchOptions.snapshotId
.orElse(Option(iceberg.table.currentSnapshot()).map(_.snapshotId()))
.map(java.lang.Long.valueOf)
.orNull
snapshotId: Long = null
```
CC @amogh-jahagirdar @zhangbutao
> Spark 3.4: Fix NPE when create branch and tag on table without snapshot

- spark/v3.4/spark-extensions/src/jmh/java/org/apache/iceberg/spark/UpdateProjectionBenchmark.java
- spark/v3.4/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/analysis/RewriteMergeIntoTable.scala
- spark/v3.4/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/analysis/RewriteRowLevelIcebergCommand.scala
- spark/v3.4/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/analysis/RewriteUpdateTable.scala
- spark/v3.4/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/plans/logical/UpdateRows.scala
- spark/v3.4/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/ExtendedDataSourceV2Strategy.scala
- spark/v3.4/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/MergeRowsExec.scala
- spark/v3.4/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/UpdateRowsExec.scala
- spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMerge.java
- spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/SparkDistributionAndOrderingUtil.java
- spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/TestSparkDistributionAndOrderingUtil.java
This PR contains a subset of changes from #7637 and is required for #7633.
> Spark 3.4: Split update into delete and insert for position deltas

- core/src/main/java/org/apache/iceberg/actions/RewriteFileGroup.java
- spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/actions/RewriteDataFilesSparkAction.java
- spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteDataFilesAction.java
some code style fixups to RewriteDeleteFileSparkAction that can be applied as well to RewriteDataFileSparkAction https://github.com/apache/iceberg/pull/7565#pullrequestreview-1427730581
Fixes #7625
> Spark-3.4: Harmonize RewriteDataFilesSparkAction

- spark/v3.2/spark-extensions/src/main/antlr/org.apache.spark.sql.catalyst.parser.extensions/IcebergSqlExtensions.g4
- spark/v3.2/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/parser/extensions/IcebergSparkSqlExtensionsParser.scala
- spark/v3.2/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/parser/extensions/IcebergSqlExtensionsAstBuilder.scala
- spark/v3.2/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/plans/logical/CreateOrReplaceTag.scala
- spark/v3.2/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/plans/logical/DropTag.scala
- spark/v3.2/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/plans/logical/TagOptions.scala
- spark/v3.2/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/CreateOrReplaceTagExec.scala
- spark/v3.2/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/DropTagExec.scala
- spark/v3.2/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/ExtendedDataSourceV2Strategy.scala
- spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestTagDDL.java
@hililiwei @amogh-jahagirdar @jackye1995 
If you can take a look, similar to spark 3.3 counterpart in #6637 and #6807
> Spark 3.2: backport Spark SQL extension on create/update/drop tags

- spark/v3.1/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/CreateOrReplaceBranchExec.scala
- spark/v3.1/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestBranchDDL.java
- spark/v3.2/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/CreateOrReplaceBranchExec.scala
- spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestBranchDDL.java
- spark/v3.3/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/CreateOrReplaceBranchExec.scala
- spark/v3.3/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/CreateOrReplaceTagExec.scala
- spark/v3.3/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestBranchDDL.java
- spark/v3.3/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestTagDDL.java
This backport fix to Spark 3.1/3.2/3.3 of #7652 
Also, I realized the `CreateOrReplaceTagExec` does not exists in spark 3.1 and spark 3.2, will track the backport in a separate issue
@amogh-jahagirdar
> Spark: Backport fix NPE when create branch and tag on table without snapshot

- api/src/main/java/org/apache/iceberg/RewriteFiles.java
- core/src/main/java/org/apache/iceberg/BaseRewriteFiles.java
- core/src/main/java/org/apache/iceberg/MergingSnapshotProducer.java
- core/src/main/java/org/apache/iceberg/actions/RewritePositionDeletesCommitManager.java
- core/src/main/java/org/apache/iceberg/actions/RewritePositionDeletesGroup.java
- spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewritePositionDeleteFilesAction.java
> Core: Compacted position delete files should use the max data sequence number of source files

- docs/spark-procedures.md
Follow-up for https://github.com/apache/iceberg/pull/7572 (still not merged)
> Docs: RewritePositionDeleteFiles procedure

- open-api/rest-catalog-open-api.yaml
The common _OpenAPI Tools_ generators do not properly recognize non-200 responses and generate the necessary objects for the non-200 response types. This change moves the schema definitions from `responses` to `schemas`.
Having code generated from the spec helps a lot, at least as a good start.
> OpenAPI responses should reference schemas

- build.gradle
Background: 
I tried to bump the Nessie version, which brought the latest Jackson 2.15.x dependency. 
With this, runtime uber jar building is failing as Jackson 2.15.x is [multi-version jar](https://github.com/FasterXML/jackson-core/issues/897) (packs classes of Java 19 also).
After debugging, found that the problem is in shadow jar plugin that Iceberg is using(which also looks fishy with [just one release](https://mvnrepository.com/artifact/gradle.plugin.com.github.jengelman.gradle.plugins/shadow)) and with the [standard shadow jar plugin](https://plugins.gradle.org/plugin/com.github.johnrengelman.shadow) the build can pass even with multi-version jars.
> Infra: Use the standard shadow plugin

- .gitignore
- jmh.gradle
- spark/v3.3/build.gradle
- spark/v3.3/spark-extensions/src/jmh/java/org/apache/iceberg/spark/MergeCardinalityCheckBenchmark.java
- spark/v3.3/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/analysis/RewriteMergeIntoTable.scala
- spark/v3.3/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/plans/logical/MergeRows.scala
- spark/v3.3/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/ExtendedDataSourceV2Strategy.scala
- spark/v3.3/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/MergeRowsExec.scala
This PR backports #7558 into Spark 3.3.
> Spark 3.3: Avoid local sort for MERGE cardinality check

- spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/actions/RewriteDataFilesSparkAction.java
- spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteDataFilesAction.java
Simple backport of https://github.com/apache/iceberg/pull/7630/files
> Spark 3.3: Harmonize RewriteDataFilesSparkAction

- core/src/main/java/org/apache/iceberg/BaseEntriesTable.java
- core/src/main/java/org/apache/iceberg/BaseFilesTable.java
- core/src/main/java/org/apache/iceberg/MetricsUtil.java
Some minor cleanup discussed:  https://github.com/apache/iceberg/pull/7539#discussion_r1192497611 ,
Try to make the readable_metrics code of BaseEntriesTable and BaseFilesTable align, by extracting common class and making code more similar.
> Core: Minor metadata table code harmonization for readable_metrics

- nessie/src/main/java/org/apache/iceberg/nessie/NessieTableOperations.java
- nessie/src/test/java/org/apache/iceberg/nessie/TestNessieTable.java
Avoid automatic cleanup of table metadata files during commit as it can be in use by other references.
> Nessie: Disable table metadata files cleanup during commits

- core/src/main/java/org/apache/iceberg/BaseFilesTable.java
```
/Users/fokkodriesprong/Desktop/iceberg/core/src/main/java/org/apache/iceberg/BaseFilesTable.java:188: warning: [InvalidBlockTag] @file is not a valid tag, but is a parameter
name. Use {@code %s} to refer to parameter names inline.
* @file content file metadata
```
> Core: Fix docstring

- core/src/main/java/org/apache/iceberg/deletes/PositionDelete.java
- core/src/main/java/org/apache/iceberg/deletes/PositionDeleteWriter.java
- core/src/main/java/org/apache/iceberg/deletes/SortingPositionOnlyDeleteWriter.java
- core/src/main/java/org/apache/iceberg/io/FanoutPositionOnlyDeleteWriter.java
- data/src/test/java/org/apache/iceberg/io/TestPartitioningWriters.java
- spark/v3.4/spark/src/jmh/java/org/apache/iceberg/spark/source/WritersBenchmark.java
This PR adds a position delete writer that can handle unordered position deletes. This writer should allow us to avoid a local sort for **_some_** MERGE operations. Specifically, consider MERGE operations where 90% of data are inserts and the table is partitioned but no sort order is defined. Right now, we always request a local sort to order deletes. However, that sort can be useless for inserts if no sort order is defined and fanout writer is enabled. Moreover, ordering inserts may lead to a spill, which is expensive for wide tables and large tasks.
> Core: Add writer for unordered position deletes

- python/Makefile
- python/dev/Dockerfile
- python/dev/entrypoint.sh
- python/dev/provision.py
- python/mkdocs/docs/contributing.md
This splits out running and building the integration tests that enables quick development iterations. I've also added ipython that will give a more meaningful error when something goes wrong with the provisioning of the tests.
> Python: Refactor integration tests

- open-api/rest-catalog-open-api.yaml
Motivation:
Encountering following error when parsing TableRequirement as defined by the existing rest catalog spec
```
Caused by: java.lang.IllegalArgumentException: Cannot parse update requirement. Missing field: type
at org.apache.iceberg.relocated.com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
at org.apache.iceberg.rest.requests.UpdateRequirementParser.fromJson(UpdateRequirementParser.java:159)
at org.apache.iceberg.rest.RESTSerializers$UpdateRequirementDeserializer.deserialize(RESTSerializers.java:95)
at org.apache.iceberg.rest.RESTSerializers$UpdateRequirementDeserializer.deserialize(RESTSerializers.java:90)
at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:359)
... 54 common frames …
```
> Spec: TableRequirement definition and parser mismatch

- data/src/test/java/org/apache/iceberg/data/parquet/TestParquetEncryptionWithWriteSupport.java
- parquet/src/main/java/org/apache/iceberg/parquet/Parquet.java
- parquet/src/main/java/org/apache/iceberg/parquet/ParquetWriter.java
- parquet/src/main/java/org/apache/iceberg/parquet/ReadConf.java
- parquet/src/test/java/org/apache/iceberg/parquet/TestParquetEncryption.java
- spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/data/parquet/vectorized/TestParquetDictionaryEncodedVectorizedReads.java
- spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/data/parquet/vectorized/TestParquetDictionaryFallbackToPlainEncodingVectorizedReads.java
- spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/data/parquet/vectorized/TestParquetVectorizedReads.java
> Parquet: Support parquet modular encryption

- core/src/main/java/org/apache/iceberg/BaseFile.java
- core/src/main/java/org/apache/iceberg/SerializableByteBufferMap.java
- core/src/test/java/org/apache/iceberg/TestManifestReaderStats.java
The BaseFile statistics maps are inconsistent.
Modifiable:
- lowerBounds
- upperBounds
Non-modifiable:
- columnSizes
- valueCounts
- nullValueCounts
- nanValueCounts
I think this is an oversight in #2343 when we wanted to make sure that it is possible to Serialize/Deserialize the stats, but accidentally made some of them modifiable at the same time.
> Core: Make all of the BaseFile stat maps immutable

- spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/SparkRowLevelOperationsTestBase.java
- spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestCopyOnWriteDelete.java
- spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestCopyOnWriteMerge.java
- spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestCopyOnWriteUpdate.java
- spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestDelete.java
- spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMerge.java
- spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMergeOnReadDelete.java
- spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMergeOnReadMerge.java
- spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMergeOnReadUpdate.java
- spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestUpdate.java
- spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/SparkWriteConf.java
- spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/SparkWriteRequirements.java
- spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/SparkWriteUtil.java
- spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/source/SparkPositionDeltaWrite.java
- spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/TestSparkDistributionAndOrderingUtil.java
This PR adds support for fanout writers in `SparkPositionDeltaWrite`.
> Spark 3.4: Support fanout writers in SparkPositionDeltaWrite

- core/src/test/java/org/apache/iceberg/rest/requests/TestCreateNamespaceRequest.java
- core/src/test/java/org/apache/iceberg/rest/requests/TestCreateTableRequest.java
- core/src/test/java/org/apache/iceberg/rest/requests/TestRenameTableRequest.java
- core/src/test/java/org/apache/iceberg/rest/requests/TestUpdateNamespacePropertiesRequest.java
- core/src/test/java/org/apache/iceberg/rest/requests/TestUpdateRequirementParser.java
Remove `AssertHelpers` in iceberg-core-request module.
> Core: Remove deprecated AssertHelpers

- .github/labeler.yml
Just realized there's no label correspond to openAPI spec change. I think introducing is would help filter out the spec change  and allow for easier subscription to such change
Appreciate reviews! @Fokko @haizhou-zhao @snazy @rdblue
> Build: Add openapi label

- parquet/src/main/java/org/apache/iceberg/parquet/Parquet.java
Right now, the Flink upsert job writes bloom filter for equality deletes when enabling bloom filter for equality columns. This is useless and should be avoided.
> Parquet: skip writing bloom filter for deletes

- docs/flink-getting-started.md
- flink/v1.16/build.gradle
- flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/util/TestFlinkPackage.java
- flink/v1.17/build.gradle
- flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/util/TestFlinkPackage.java
Bump flink version to `1.16.2` and `1.17.1` as they are the latest recommended version for `1.16` and `1.17`.
> Flink: Bump version to 1.16.2 and 1.17.1

- core/src/test/java/org/apache/iceberg/deletes/TestEqualityFilter.java
- core/src/test/java/org/apache/iceberg/deletes/TestPositionFilter.java
- core/src/test/java/org/apache/iceberg/expressions/TestExpressionParser.java
- core/src/test/java/org/apache/iceberg/rest/auth/TestOAuth2Util.java
This pull request is related to the issue "Move JUnit4 tests to JUnit5 https://github.com/apache/iceberg/issues/7160".
I switched the files in the deletes, expressions, auth packages from JUnit4 to JUnit5.
@nastra I fixed the commit with what you reviewed, but something went wrong with the GitHub push, so I clean up the files and resubmit the PR.
Based on your review, I removed unnecessary parts.
> Core: Switch tests to Junit5 in deletes,expressions,auth packages

- python/Makefile
- python/dev/Dockerfile
- python/dev/entrypoint.sh
- python/dev/provision.py
- python/mkdocs/docs/contributing.md
* Python: Refactor integration tests
This splits out running and building the integration tests that enables quick development iterations. I've also added ipython that will give a more meaningful error when something goes wrong with the provisioning of the tests.
* Simplify SQL
> Python: Refactor integration tests (#7698)

- core/src/main/java/org/apache/iceberg/MetadataUpdateParser.java
- core/src/test/java/org/apache/iceberg/TestMetadataUpdateParser.java
- open-api/rest-catalog-open-api.yaml
I noticed that this was required:
```
com.fasterxml.jackson.databind.JsonMappingException: Cannot parse missing int: last-column-id (through reference chain: org.apache.iceberg.rest.requests.UpdateTableRequest[&quot;updates&quot;]-&gt;java.util.ArrayList[0])
at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:402)
at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:373)
at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:375)
at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28 …
```
> Spec: Add missing `last-column-id`

- python/.pre-commit-config.yaml
This will make sure that our docstrings are properly formatted.
This is getting important since we also generate docs from the doc strings. This PR is about adding the framework, and then we can follow up in new PRs for each of the error codes.
> Python: Add support for pydocstyle

- core/src/test/java/org/apache/iceberg/hadoop/TestCachingCatalog.java
- core/src/test/java/org/apache/iceberg/hadoop/TestHadoopCatalog.java
- core/src/test/java/org/apache/iceberg/hadoop/TestHadoopCommits.java
- core/src/test/java/org/apache/iceberg/hadoop/TestHadoopTables.java
- core/src/test/java/org/apache/iceberg/hadoop/TestStaticTable.java
Remove `AssertHelpers` in iceberg-core-hadoop module.
> Core: Remove deprecated AssertHelpers in Hadoop

- python/.pre-commit-config.yaml
A new version has been released 9 hours ago, and broke the build:
https://pypi.org/project/mdformat_admon/1.0.2/
Let's pin the versions.
> Python: Pin `mkdocs-admon`

- core/src/test/java/org/apache/iceberg/catalog/CatalogTests.java
Some recently added catalog test assertions check that error messages exactly match an expected string. This PR changes that to be more permissive, so catalog services can append additional context if needed to the message without causing test failures.
> Tests: More permissive error message assertion in catalog tests

- core/src/test/java/org/apache/iceberg/catalog/CatalogTests.java
This is a follow-up to https://github.com/apache/iceberg/pull/7784, this PR updates one more assertion that was missed in that PR.
> Tests: Update catalog test assertion to be more permissive

- core/src/main/java/org/apache/iceberg/io/ClusteredWriter.java
- core/src/main/java/org/apache/iceberg/io/FanoutWriter.java
> Core: Deprecate `newOutputFile` from `{ClusteredWriter,FanoutWriter}`

- python/pyiceberg/manifest.py
Fix the `column_sizes`, `value_counts` and `data_file` field optionalities to conform to the specification at https://iceberg.apache.org/spec/#manifests
Without these changes the Avro files that I was generating couldn't be parsed by the iceberg rest catalog service.
> Python: Fix optionality of Manifest fields

- python/.pre-commit-config.yaml
- python/pyiceberg/avro/decoder.py
- python/pyiceberg/io/pyarrow.py
- python/pyiceberg/transforms.py
- python/pyiceberg/utils/config.py
> Fix D403 pydocstyle issues

- core/src/main/java/org/apache/iceberg/rest/RESTSerializers.java
- core/src/main/java/org/apache/iceberg/rest/ResourcePaths.java
- core/src/main/java/org/apache/iceberg/rest/requests/CommitTransactionRequest.java
- core/src/main/java/org/apache/iceberg/rest/requests/CommitTransactionRequestParser.java
- core/src/main/java/org/apache/iceberg/rest/requests/UpdateTableRequest.java
- core/src/test/java/org/apache/iceberg/rest/requests/TestCommitTransactionRequestParser.java
- open-api/rest-catalog-open-api.yaml
extracted from https://github.com/apache/iceberg/pull/7569
> Core: Add REST spec and request for committing changes against multiple tables

- python/.pre-commit-config.yaml
- python/pyiceberg/avro/decoder.py
- python/pyiceberg/avro/file.py
- python/pyiceberg/cli/console.py
- python/pyiceberg/partitioning.py
- python/pyiceberg/utils/datetime.py
- python/pyiceberg/utils/decimal.py
- python/pyiceberg/utils/schema_conversion.py
- python/tests/conftest.py
D414: Section has no content ('Returns')
D200: One-line docstring should fit on one line with quotes
> Python: Fix D414 and D200 docstring issues

- .github/workflows/recurring-jmh-benchmarks.yml
- .github/workflows/stale.yml
i got the following email today:
```
[XN137/iceberg] Run failed: Recurring JMH Benchmarks - master (b88951b)
```
it seems unintentional to me that these workflows also get scheduled on github repo forks...
especially assuming any substantial work on forks is done on branches other than `master`.
note the snapshot publish workflow gets scheduled but is then skipped immediately on forks already:
https://github.com/apache/iceberg/blob/8aefc6925fdd8501040dfaf7d8ee0cdfec60a92d/.github/workflows/publish-snapshot.yml#L28-L31
> Build: skip scheduled workflows on forks

- core/src/main/java/org/apache/iceberg/util/SnapshotUtil.java
- core/src/test/java/org/apache/iceberg/util/TestSnapshotUtil.java
Calling `hasNext()` on the any Iterator returned by the Iterable from `SnapshotUtil.ancestorsOf` throws a NullPointerException if it is called again after the prior call returned false. This only happens if the ancestor chain is broken by an expired snapshot, not if it reaches a snapshot with a null parentId.
This is because when `next.parentId()` returns null the iterator will return false without changing its state, but when the lookup function returns null, as it would when the snapshot's parent is expired, it sets the `next` variable to null as well. The first time this doesn't cause an issue as the next line null-checks it, but if `hasNext()` is called again it will attempt to call `next.parentId()` on the now-null next variable, throwing an NPE.
I considered fixing this by storing …
> Core: Fixed NPE in SnapshotUtil.ancestorsOf

- spark/v3.4/build.gradle
This PR updates the ANTLR version to match that in Spark 3.4. Currently, when Spark extensions are first loaded, you will see the following error message: `ANTLR Tool version 4.8 used for code generation does not match the current runtime version 4.9.3`.
> Spark: Update ANTLR to match Spark 3.4

- python/mkdocs/docs/configuration.md
- python/pyiceberg/catalog/glue.py
- python/tests/catalog/test_glue.py
This PR concerns issue https://github.com/apache/iceberg/issues/7777.
It makes it possible to pass AWS credentials directly through the Python API, when loading a Glue catalog. Additionally, the `profile_name` of the desired AWS profile can be selected. Currently, the default profile is used.
> Python: Make Glue catalog configurable

- docs/flink-ddl.md
- docs/flink-getting-started.md
1.Fix URL link in flink-getting-started.md
Before：
After：
2.Fix docs format in flink-ddl.md
Before：
After：
> Docs: Fix SQL formatting in Flink docs

- parquet/src/main/java/org/apache/iceberg/parquet/Parquet.java
- parquet/src/main/java/org/apache/iceberg/parquet/ParquetCodecFactory.java
This PR reverts https://github.com/apache/iceberg/pull/5681, which is no longer needed with the [upgrade](https://github.com/apache/iceberg/pull/7301) of Parquet to 1.13. This marks the now-unused codec factory class as deprecated.
Here is a heap leak analysis of one executor when running a large scan with a build of 1.2.1 (Parquet 1.12) and the workaround removed:
Here is the leak analysis with a build of this PR:
In the first example, the zstd buffer pool is accumulating memory. In the second example, there is no such accumulation.
> Parquet: Revert workaround for resource usage with zstd

- core/src/test/java/org/apache/iceberg/catalog/CatalogTests.java
- core/src/test/java/org/apache/iceberg/catalog/TestTableIdentifierParser.java
- core/src/test/java/org/apache/iceberg/encryption/TestCiphers.java
- core/src/test/java/org/apache/iceberg/inmemory/TestInMemoryFileIO.java
- core/src/test/java/org/apache/iceberg/inmemory/TestInMemoryInputFile.java
- core/src/test/java/org/apache/iceberg/inmemory/TestInMemoryOutputFile.java
- core/src/test/java/org/apache/iceberg/io/TestByteBufferInputStreams.java
- core/src/test/java/org/apache/iceberg/io/TestIOUtil.java
- core/src/test/java/org/apache/iceberg/io/TestMultiBufferInputStream.java
- core/src/test/java/org/apache/iceberg/io/TestResolvingIO.java
- core/src/test/java/org/apache/iceberg/io/TestSingleBufferInputStream.java
- core/src/test/java/org/apache/iceberg/view/TestSQLViewRepresentationParser.java
- core/src/test/java/org/apache/iceberg/view/TestViewHistoryEntryParser.java
- core/src/test/java/org/apache/iceberg/view/TestViewRepresentationParser.java
- core/src/test/java/org/apache/iceberg/view/TestViewVersionParser.java
This pull request is related to the issue "Move JUnit4 tests to JUnit5 https://github.com/apache/iceberg/issues/7160".
I switched the files in [catalog,encryption,inmemory,io,view] pakages to JUnit5.
> Core: Switch tests to Junit5 in catalog,encryption,inmemory,io,view

- nessie/src/main/java/org/apache/iceberg/nessie/NessieCatalog.java
- nessie/src/main/java/org/apache/iceberg/nessie/NessieUtil.java
- nessie/src/test/java/org/apache/iceberg/nessie/BaseTestIceberg.java
- nessie/src/test/java/org/apache/iceberg/nessie/TestCustomNessieClient.java
- nessie/src/test/java/org/apache/iceberg/nessie/TestNessieCatalog.java
- nessie/src/test/java/org/apache/iceberg/nessie/TestNessieIcebergClient.java
- The default version is v1 to avoid forcing users to change their URI in the existing jobs.
- "client-api-version" catalog property is added to specify the API version in-case the user wants to use v2.
> Nessie: Support ApiV2 for Nessie client

- build.gradle
Missed after the release step I guess. 
It is already covered in the docs.
https://iceberg.apache.org/how-to-release/#update-revapi
> Build: Let Rev API compare against 1.3.0

- core/src/main/java/org/apache/iceberg/view/ViewMetadata.java
- core/src/main/java/org/apache/iceberg/view/ViewMetadataParser.java
- core/src/main/java/org/apache/iceberg/view/ViewProperties.java
- core/src/test/java/org/apache/iceberg/view/TestViewMetadata.java
- core/src/test/java/org/apache/iceberg/view/TestViewMetadataParser.java
- core/src/test/resources/org/apache/iceberg/view/ValidViewMetadata.json
- core/src/test/resources/org/apache/iceberg/view/ViewMetadataInvalidCurrentSchema.json
- core/src/test/resources/org/apache/iceberg/view/ViewMetadataInvalidCurrentVersion.json
- core/src/test/resources/org/apache/iceberg/view/ViewMetadataLimitedVersions.json
- core/src/test/resources/org/apache/iceberg/view/ViewMetadataMissingCurrentSchema.json
- core/src/test/resources/org/apache/iceberg/view/ViewMetadataMissingCurrentVersion.json
- core/src/test/resources/org/apache/iceberg/view/ViewMetadataMissingLocation.json
This is a continuation PR of #6559 and I've addressed all remaining comments.
@stevenzwu @jackye1995 @rdblue since you guys were reviewing the original PR, I've added you here as well. Please take a look when you can.
> Core: View metadata implementation

- core/src/main/java/org/apache/iceberg/TableMetadata.java
- core/src/test/java/org/apache/iceberg/TestSnapshotLoading.java
- core/src/test/java/org/apache/iceberg/rest/TestRESTCatalog.java
I noticed that not all relevant snapshots are being retained with a V1 table and when using branches. I added a test that reproduces this issue and would fail with 
```
Snapshot for reference SnapshotRef{snapshotId=7532742534704478452, type=BRANCH, minSnapshotsToKeep=null, maxSnapshotAgeMs=null, maxRefAgeMs=null} does not exist in the existing snapshots list
java.lang.IllegalArgumentException: Snapshot for reference SnapshotRef{snapshotId=7532742534704478452, type=BRANCH, minSnapshotsToKeep=null, maxSnapshotAgeMs=null, maxRefAgeMs=null} does not exist in the existing snapshots list
at org.apache.iceberg.relocated.com.google.common.base.Preconditions.checkArgument(Preconditions.java:220)
at org.apache.iceberg.TableMetadata.validateRefs(TableMetadata.java:835)
at …
```
> Core: Include all reachable snapshots with v1 format and REF snapshot mode

- core/src/main/java/org/apache/iceberg/BaseTransaction.java
- core/src/main/java/org/apache/iceberg/catalog/TableCommit.java
- core/src/main/java/org/apache/iceberg/rest/CatalogHandlers.java
- core/src/main/java/org/apache/iceberg/rest/RESTCatalog.java
- core/src/main/java/org/apache/iceberg/rest/RESTSessionCatalog.java
- core/src/main/java/org/apache/iceberg/rest/requests/UpdateTableRequest.java
- core/src/test/java/org/apache/iceberg/rest/RESTCatalogAdapter.java
- core/src/test/java/org/apache/iceberg/rest/TestRESTCatalog.java
The main purpose of this PR is to extract the REST-specific changes out of https://github.com/apache/iceberg/pull/6948
> Core: Add REST API for committing changes against multiple tables
