apache/iceberg

core/src/main/java/org/apache/iceberg/rest/responses/ErrorResponseParser.java

This has been fixed by #5698 but then reverted by #5810

Core: Use JsonUtil.generate in ErrorResponseParser

---

.github/workflows/python-ci-docs.yml

I've renamed the directory structure as a PR suggestion, but forgot to update the path in Github 🤦🏻

Build: Fix CI paths

---

core/src/main/java/org/apache/iceberg/ManifestGroup.java
core/src/main/java/org/apache/iceberg/ManifestReader.java

Don't check row filter when deciding whether to copy data file with stats

---

build.gradle
core/src/main/java/org/apache/iceberg/rest/RESTUtil.java
core/src/test/java/org/apache/iceberg/rest/RESTCatalogAdapter.java
core/src/test/java/org/apache/iceberg/rest/RESTCatalogServlet.java
core/src/test/java/org/apache/iceberg/rest/TestRESTCatalog.java
core/src/test/java/org/apache/iceberg/rest/TestRESTUtil.java
versions.props

This PR provides a proxy implementation for a HttpServlet backed by a RESTCatalogAdaptor to expose the REST spec for any backend catalog implementation.

Add REST Servlet/Server Implementations

---

core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java
core/src/main/java/org/apache/iceberg/jdbc/JdbcTableOperations.java
core/src/main/java/org/apache/iceberg/jdbc/JdbcUtil.java
core/src/test/java/org/apache/iceberg/jdbc/TestJdbcCatalog.java

Core: Add strict-mode property to JDBC Catalog

---

python/mkdocs/docs/index.md

[Python][Docs] Very small formatting fix

---

api/src/main/java/org/apache/iceberg/metrics/ScanReport.java
core/src/main/java/org/apache/iceberg/DeleteFileIndex.java
core/src/main/java/org/apache/iceberg/metrics/ScanMetricsResultParser.java
core/src/test/java/org/apache/iceberg/TestScanPlanningAndReporting.java
core/src/test/java/org/apache/iceberg/metrics/TestScanMetricsResultParser.java
core/src/test/java/org/apache/iceberg/metrics/TestScanReportParser.java

Currently depends on #5780 / #5788 / #5792

API,Core: Add scan planning metrics for indexed/eq/pos delete files

---

docs/aws.md

This PR adds the doc for table and namespace S3 tags (refer: https://github.com/apache/iceberg/pull/4402)
---
cc: @jackye1995 @singhpk234 @amogh-jahagirdar

Docs: Add table and namespace S3 tags doc

---

python/pyproject.toml

In preparation of the next release

Python: Bump version to 0.2.0

---

api/src/main/java/org/apache/iceberg/expressions/ExpressionUtil.java
api/src/test/java/org/apache/iceberg/expressions/TestExpressionUtil.java

this was discovered while reviewing https://github.com/apache/iceberg/pull/5908

API: Handle negative/zero during num-digits calculation

---

api/src/main/java/org/apache/iceberg/DistributionMode.java
api/src/main/java/org/apache/iceberg/RewriteJobOrder.java
api/src/main/java/org/apache/iceberg/SnapshotRefType.java
api/src/main/java/org/apache/iceberg/SortDirection.java
api/src/main/java/org/apache/iceberg/actions/DeleteOrphanFiles.java
api/src/main/java/org/apache/iceberg/expressions/Expression.java
api/src/main/java/org/apache/iceberg/metrics/MetricsContext.java
core/src/main/java/org/apache/iceberg/IsolationLevel.java
core/src/main/java/org/apache/iceberg/MetadataUpdateParser.java
core/src/main/java/org/apache/iceberg/SnapshotRefParser.java
core/src/main/java/org/apache/iceberg/SortOrderParser.java
core/src/main/java/org/apache/iceberg/TableMetadataParser.java
core/src/main/java/org/apache/iceberg/expressions/ExpressionParser.java
core/src/main/java/org/apache/iceberg/metrics/TimerResultParser.java
core/src/main/java/org/apache/iceberg/rest/requests/ReportMetricsRequest.java
core/src/main/java/org/apache/iceberg/rest/requests/ReportMetricsRequestParser.java
core/src/test/java/org/apache/iceberg/TableMetadataParserCodecTest.java
core/src/test/java/org/apache/iceberg/TestSnapshotRefParser.java
core/src/test/java/org/apache/iceberg/TestSortOrderParser.java
core/src/test/java/org/apache/iceberg/expressions/TestExpressionParser.java
core/src/test/java/org/apache/iceberg/metrics/TestCounterResultParser.java
core/src/test/java/org/apache/iceberg/metrics/TestTimerResultParser.java
core/src/test/java/org/apache/iceberg/rest/requests/TestReportMetricsRequestParser.java
flink/v1.13/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSink.java
flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSink.java
flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSink.java
spark/v3.0/spark/src/main/java/org/apache/iceberg/spark/source/SparkMergeBuilder.java
spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/source/SparkMergeBuilder.java

This is a follow-up from https://github.com/apache/iceberg/pull/5407#discussion_r984999898

Core: Provide better error message on invalid enums

---

python/dev/RELEASE.md

Updated release instructions. Will port this into a shell script once we've settled on the process.

Python: Update release instructions

---

core/src/main/java/org/apache/iceberg/BaseSnapshot.java
core/src/main/java/org/apache/iceberg/SnapshotProducer.java
core/src/main/java/org/apache/iceberg/TableProperties.java
core/src/test/java/org/apache/iceberg/TestMetadataUpdateParser.java
core/src/test/java/org/apache/iceberg/TestSnapshotJson.java
core/src/test/java/org/apache/iceberg/TestTableMetadata.java

This depends on https://github.com/apache/iceberg/pull/5734

Core: Deprecate write.manifest-lists.enabled flag

---

python/pyiceberg/schema.py
python/pyiceberg/types.py
python/tests/test_schema.py

This is required if we want to implement `.select(*columns: str)`

Python: Ability to Prune Columns

---

api/src/main/java/org/apache/iceberg/PartitionSpec.java

Api: Optimize the code

---

core/src/main/java/org/apache/iceberg/util/SnapshotUtil.java
core/src/test/java/org/apache/iceberg/util/TestSnapshotUtil.java

Fix NPE for parent snapshot does not exist

Core: Fix NPE for parent snapshot does not exist

---

spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/SparkScan.java

This PR cherry-picks parts of PR #5720 to Spark 3.2 so that 3.3 and 3.2 don't diverge.

Spark 3.2: Use ScanTaskGroup methods when computing stats

---

spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestChangelogBatchReads.java
spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/SparkCatalog.java
spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/ChangelogRowReader.java
spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/SparkChangelogBatch.java
spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/SparkChangelogScan.java
spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/SparkChangelogTable.java
spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/SparkInputPartition.java
spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/SparkMicroBatchStream.java
spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/SparkScan.java
spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/SparkScanBuilder.java
spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/actions/TestRemoveOrphanFilesAction3.java
spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/source/TestPathIdentifier.java

This PR cherry-picks PR #5740 to Spark 3.2.

Spark 3.2: Add SparkChangelogTable

---

spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/SparkBatch.java
spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/SparkScan.java

This PR cherry-picks PR #5934 to Spark 3.2.

Spark 3.2: Split SparkScan and SparkBatch

---

python/pyiceberg/schema.py
python/tests/test_schema.py

So we can select a subset of the fields in a schema

Python: Implement select

---

.asf.yaml
.github/workflows/flink-ci.yml
.github/workflows/hive-ci.yml
.github/workflows/java-ci.yml
.github/workflows/spark-ci.yml

I got this email:
However, this looks to be inconsistent with the docs:
https://cwiki.apache.org/confluence/display/INFRA/Git+-+.asf.yaml+features
Since I got committer rights a while ago, I can be removed from the list.

Remove Fokko from the list of collaborators

---

spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/SparkBatchQueryScan.java
spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/SparkBatchQueryScan.java

Updating log in this class as per suggestion

SparkBatchQueryScan logs too much - #6106

---

flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/source/TestSourceUtil.java
flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/source/TestSourceUtil.java
flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/source/TestSourceUtil.java

just a little optimization. As shown in the submitted code, we can reuse configuration.

Flink: Optimize test code of TestSourceUtil

---

README.md

add Flink 1.16 and remove Spark 3.0

Docs: Update spotless apply command

---

core/src/main/java/org/apache/iceberg/ManifestReader.java
core/src/test/java/org/apache/iceberg/TestManifestReaderStats.java

This addresses [comments from #5815](https://github.com/apache/iceberg/pull/5815#discussion_r978094424)

Cache dropStats result for ManifestReader iterator

---

python/pyiceberg/catalog/hive.py
python/pyiceberg/catalog/rest.py
python/pyiceberg/cli/console.py
python/pyiceberg/cli/output.py
python/pyiceberg/io/fsspec.py
python/pyiceberg/io/pyarrow.py
python/pyiceberg/table/__init__.py
python/tests/cli/test_console.py

- Includes the session token when setting up a S3FS or PyArrow FileIO.
- Also moved the creation of the FileIO to the table

Python: Load the S3 Session token

---

core/src/main/java/org/apache/iceberg/Partitioning.java
core/src/test/java/org/apache/iceberg/TestPartitioning.java

This PR adds a method to `Partitioning` to build an intersection of all partition types. This intersection can be used as a clustering key for storage-partitioned joins.

Core: Method for building grouping key type

---

core/src/main/java/org/apache/iceberg/ManifestFiles.java
core/src/main/java/org/apache/iceberg/PartitionData.java
core/src/main/java/org/apache/iceberg/avro/AvroFileAppender.java
core/src/main/java/org/apache/iceberg/schema/UnionByNameVisitor.java

Core: Remove redundant initialization

Core: Remove redundant initialization

---

flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/util/TestFlinkPackage.java
flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/util/TestFlinkPackage.java
flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/util/TestFlinkPackage.java

Flink: Add unit test for FlinkPackage util class

---

python/.pre-commit-config.yaml
python/pyiceberg/catalog/__init__.py
python/pyiceberg/typedef.py
python/pyiceberg/utils/config.py
python/pyproject.toml
python/tests/avro/test_decoder.py

Python: Update mypy version

---

python/pyiceberg/expressions/__init__.py
python/pyiceberg/expressions/literals.py
python/pyiceberg/expressions/visitors.py
python/pyiceberg/typedef.py
python/tests/expressions/test_expressions.py

Small follow up on https://github.com/apache/iceberg/pull/6139/

Python: Follow up on types

---

python/pyiceberg/expressions/__init__.py
python/pyiceberg/expressions/visitors.py
python/tests/expressions/test_expressions.py

This fixes a couple that #6225 didn't catch.

Python: Minor fixes to expression types

---

.github/ISSUE_TEMPLATE/iceberg_question.yml

Follow up to https://github.com/apache/iceberg-docs/commit/59f1a607d318fff8c2423b2ab4e667dd24125767

Infra: Update slack invite link

---

python/pyiceberg/catalog/hive.py

- In #6034 , we put some variables shared by `hive` and `glue` in `catalog/__init__.py`. This PR updates `hive.py` to make it use those shared variables.
- As proposed in https://github.com/apache/iceberg/pull/5870#discussion_r990835173, we created `NoSuchIcebergTableError` in GLueCatalog to indicate the case when loaded table is not an iceberg table. This PR updates hive to also throw the this exception under the same case.

Python: Update HiveCatalog to share common variables with GlueCatalog

---

format/view-spec.md

some follow-up from https://github.com/apache/iceberg/pull/3188
Other than some comments to add detailed examples, I have handled all. Examples can be added in the follow-up PR.

Docs: Update the view spec

---

python/mkdocs/docs/index.md

We actually don't have support for changing tables. We have recently added support for planning scans

Python: Update feature matrix

---

python/dev/RELEASE.md
python/pyiceberg/__init__.py
python/pyproject.toml

This is required for the release

Python: Set version to 0.2.0

---

docs/flink-getting-started.md

Doc: Replace build with append in the Flink doc

---

docs/hive.md

Issue: https://github.com/apache/iceberg/issues/6249
This documentation contains the list of new features introduced in Hive 4.0.0-alpha-2.
The only exception is https://issues.apache.org/jira/browse/HIVE-26077. It seems it was already supported in alpha-1 so I just refreshed the related part of the documentation.

Docs: Update Iceberg Hive documentation

---

core/src/test/java/org/apache/iceberg/TestPartitionSpecInfo.java

Adding another unit test to make sure that columns used by an old but not currrent partition spec are allowed to be dropped.

Allow dropping a column used by an old but not currrent partition spec

---

spark/v3.3/spark/src/jmh/java/org/apache/iceberg/spark/data/parquet/SparkParquetReadersFlatDataBenchmark.java
spark/v3.3/spark/src/jmh/java/org/apache/iceberg/spark/data/parquet/SparkParquetReadersNestedDataBenchmark.java
spark/v3.3/spark/src/jmh/java/org/apache/iceberg/spark/data/parquet/SparkParquetWritersFlatDataBenchmark.java
spark/v3.3/spark/src/jmh/java/org/apache/iceberg/spark/data/parquet/SparkParquetWritersNestedDataBenchmark.java

[Here](https://github.com/nastra/iceberg/actions/runs/3647962993) is a benchmark run that failed previously but passes now

Fix Spark JMH Benchmarks

---

python/README.md

This solves https://github.com/apache/iceberg/issues/6383.

Python: Improve `readme.md` "Getting started" by mentioning required pip version

---

python/pyiceberg/io/pyarrow.py

Python: Add missing types

---

docs/spark-procedures.md

Add documentation for https://github.com/apache/iceberg/pull/4810
Official docs: https://iceberg.apache.org/docs/latest/spark-procedures/
Screenshot of the local running server:
---
cc: @RussellSpitzer

Docs: Add register table Spark procedure documentation

---

python/poetry.lock
python/pyproject.toml

This one was missing and was being pulled in transitively I presume

Python: Add pyparsing

---

.github/workflows/recurring-jmh-benchmarks.yml
build.gradle
gradle.properties
jmh.gradle

This runs the JMH Benchmarks every Sunday and also create a visual report for each benchmark and upload it after all benchmarks completed

Run weekly JMH Benchmarks & visualize results

---

python/pyiceberg/avro/decoder.py
python/pyiceberg/avro/reader.py
python/pyiceberg/avro/resolver.py
python/pyiceberg/schema.py
python/pyiceberg/utils/schema_conversion.py
python/tests/avro/test_decoder.py
python/tests/avro/test_reader.py

Python: Support for UUID

---

docs/spark-ddl.md

Example of correcting the document add/drop partition truncate

Doc:Example of correcting the document add/drop partition truncate

---

docs/aws.md

I copy pasted the example, but still had to select the catalog.

Docs: Select the right Spark catalog

---

format/spec.md

(use `pos` instead of `position`)

Minor clarification for spec

---

python/pyiceberg/__init__.py
python/pyproject.toml

Python: Bump version to 0.2.1

---

hive-metastore/src/test/java/org/apache/iceberg/hive/ScriptRunner.java

Hive-metastore: Merge identical catch branch

---

core/src/main/java/org/apache/iceberg/util/SnapshotUtil.java

Core: Java doc fix on method SnapshotUtil::oldestAncestorAfter

---

python/pyiceberg/typedef.py
python/tests/test_types.py
python/tests/utils/test_deprecated.py

Python: Add tests

---

python/pyiceberg/avro/file.py
python/pyiceberg/io/__init__.py
python/pyiceberg/io/fsspec.py
python/pyiceberg/io/pyarrow.py
python/tests/avro/test_reader.py
python/tests/io/test_pyarrow.py

I noticed that PyArrow is doing two calls to the Avro file, while one should be sufficient (150kb):
```
2022-12-27T08:45:32.822 [206 Partial Content] s3.GetObject minio:9000/warehouse/wh/nyc/taxis/metadata/00009-3dd7ff4a-a81f-4780-bee1-de9335490c20.metadata.json 172.18.0.3        1.142ms      ↑ 169 B ↓ 14 KiB
2022-12-27T08:45:32.913 [200 OK] s3.HeadObject 127.0.0.1:9000/warehouse/wh/nyc/taxis/metadata/snap-6682082212753545990-1-9f900c62-59ca-4ea1-ae75-e373d113b036.avro 172.18.0.1        867µs       ↑ 153 B ↓ 412 B
2022-12-27T08:45:32.925 [206 Partial Content] s3.GetObject 127.0.0.1:9000/warehouse/wh/nyc/taxis/metadata/snap-6682082212753545990-1-9f900c62-59ca-4ea1-ae75-e373d113b036.avro 172.18.0.1        1.626ms      ↑ 159 B ↓ 4.6 KiB
2022-12-27T08:45:32.973 [200 OK] s3.HeadObject …
```

Python: Use PyArrow buffer

---

aws/src/main/java/org/apache/iceberg/aws/glue/GlueTableOperations.java

Aws: Cosmetic change and simplify statusCode check in GlueTableOperations

Aws: Cosmetic change in GlueTableOperations

---

api/src/main/java/org/apache/iceberg/metrics/FixedReservoirHistogram.java
api/src/main/java/org/apache/iceberg/types/JavaHashes.java
core/src/jmh/java/org/apache/iceberg/util/ZOrderByteUtilsBenchmark.java
core/src/main/java/org/apache/iceberg/util/ParallelIterable.java
flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/sink/DeltaManifestsSerializer.java
flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/source/enumerator/IcebergEnumeratorStateSerializer.java
flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/sink/TestRowDataPartitionKey.java
flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/source/reader/ReaderUtil.java
flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/sink/DeltaManifestsSerializer.java
flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/source/enumerator/IcebergEnumeratorStateSerializer.java
flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/sink/TestRowDataPartitionKey.java
flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/source/reader/ReaderUtil.java
flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/sink/DeltaManifestsSerializer.java
flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/source/enumerator/IcebergEnumeratorStateSerializer.java
flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/sink/TestRowDataPartitionKey.java
flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/source/reader/ReaderUtil.java
parquet/src/main/java/org/apache/iceberg/parquet/ParquetValueReaders.java
spark/v2.4/spark/src/main/java/org/apache/iceberg/spark/data/SparkOrcWriter.java
spark/v2.4/spark/src/test/java/org/apache/iceberg/spark/data/TestSparkParquetReader.java
spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/data/SparkOrcWriter.java
spark/v3.1/spark/src/test/java/org/apache/iceberg/spark/data/TestSparkParquetReader.java
spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/data/SparkOrcWriter.java
spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/metrics/NumDeletes.java
spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/metrics/NumSplits.java
spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/data/TestSparkParquetReader.java
spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/data/SparkOrcWriter.java
spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/metrics/NumDeletes.java
spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/metrics/NumSplits.java
spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/data/TestSparkParquetReader.java

API, Core, Flink, Parquet, Spark: Use enhanced for loop

API, Core, Flink, Parquet, Spark: Use enhanced for loop

---

flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/source/enumerator/ContinuousSplitPlannerImpl.java
flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/source/enumerator/TestContinuousSplitPlannerImpl.java
flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/source/enumerator/TestContinuousSplitPlannerImplStartStrategy.java
flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/source/enumerator/ContinuousSplitPlannerImpl.java
flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/source/enumerator/TestContinuousSplitPlannerImpl.java
flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/source/enumerator/TestContinuousSplitPlannerImplStartStrategy.java
flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/source/enumerator/ContinuousSplitPlannerImpl.java
flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/source/enumerator/TestContinuousSplitPlannerImpl.java
flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/source/enumerator/TestContinuousSplitPlannerImplStartStrategy.java

address https://github.com/apache/iceberg/pull/6350#discussion_r1044901322

Flink: Change to oldestAncestorAfter

---

flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/SimpleDataUtil.java
flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkManifest.java
flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/sink/TestIcebergFilesCommitter.java
flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/sink/TestIcebergStreamWriter.java
flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/sink/TestTaskWriters.java

Backport #4699 for v1.14 Flink code, so we can have clean backport for the testing infra

Flink: Backport: Improve unit tests for sink

---

flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/HadoopCatalogResource.java
flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/HadoopTableResource.java
flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSink.java
flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkV2.java
flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/HadoopCatalogResource.java
flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/HadoopTableResource.java
flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSink.java
flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkV2.java

Flink: Backport: Flink: Refactor sink tests to use HadoopCatalogResource

---

core/src/main/java/org/apache/iceberg/io/OutputFileFactory.java
core/src/test/java/org/apache/iceberg/io/TestOutputFileFactory.java
spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/SparkPositionDeltaWrite.java
spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/SparkWrite.java
spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/SparkPositionDeltaWrite.java
spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/SparkWrite.java

This is a revival of https://github.com/apache/iceberg/pull/5214

Spark: Add the query ID to file names

---

python/.pre-commit-config.yaml

Python: Bump pylint

---

python/pyproject.toml

Same as https://github.com/apache/iceberg/pull/6704 but raising it against the main branch.

Python: Update pyproject.toml to include dev folder.

---

python/pyproject.toml

Python: Update pyproject.toml to include dev folder. 
Currently, some files which are required for during release validation such as 
1.) .rat-excludes
2.) scripts in the dev/ folder for running integration tests
are not included in the source release. This change updates the build target so that all the files in the dev folder are included in the source for being able to test during release validation.

Python: Update pyproject.toml to include dev folder. 

---

docs/configuration.md

Adds missing table props to configure update and merge write distribution mode. 
cc @jackye1995 @RussellSpitzer

Doc: Add update and merge distribution mode table props

---

flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/source/SourceUtil.java
flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/source/SourceUtil.java

Backports https://github.com/apache/iceberg/pull/6655 to Flink 1.14, 1.15

Flink: Backport handling ResolvingFileIO in determining locality - PR 6655

---

python/pyiceberg/io/pyarrow.py

This was not needed after all. The Pythondoc was outdated, see: https://github.com/apache/arrow/pull/33974
This removes the undertested code and additional logic from the path, which is great 🥳

Python: Remove the DNF conversion

---

spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/SparkCatalog.java
spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/SparkUtil.java
spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/SparkBatchQueryScan.java
spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/SparkCopyOnWriteScan.java
spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/SparkFileWriterFactory.java
spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/SparkMicroBatchStream.java
spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/SparkPositionDeltaWrite.java

This PR fixes auto formatting for some existing comments that look weird after applying Spotless.

Spark 3.3: Fix comment formatting

---

python/pyiceberg/table/__init__.py

In case PyArrow isn't installed, this will fail. Caught by @rdblue

Python: Inline the PyArrow import

---

python/tests/catalog/test_dynamodb.py

Changing the default FileIO from Arrow to Fsspec broke the DynamoDB tests.

Python: Fix the CI

---

data/src/main/java/org/apache/iceberg/data/IcebergGenerics.java

The IcebergGenerics class only has String ... method for select, should add Collection for select will be better!
closes #6833

Data: Add a select interface with collections for IcebergGenerics

---

python/pyiceberg/expressions/literals.py
python/tests/expressions/test_literals.py

This is the equivalent of the [Legacy Python PR ](https://github.com/apache/iceberg/pull/6843).

Python: Convert string to boolean if the binding variable is Boolean

---

docs/spark-queries.md

https://github.com/apache/iceberg/issues/6257

Docs: Document that partitions metadata table might show 'old' partitions

---

aws/src/main/java/org/apache/iceberg/aws/s3/signer/S3V4RestSignerClient.java

This should fix the following warning:
```
> Task :iceberg-aws:compileJava
/home/nastra/Development/workspace/iceberg/aws/src/main/java/org/apache/iceberg/aws/s3/signer/S3V4RestSignerClient.java:75: warning: (immutables:incompat) Avoid introduction of fields (except constants) in abstract value types
private static RESTClient httpClient;
^
```

AWS: Fix warning in S3V4RestSignerClient

---

python/mkdocs/docs/api.md

Add more pyiceberg doc

---

spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/ChangelogIterator.java
spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/TestChangelogIterator.java

cc @aokolnychyi @szehon-ho @RussellSpitzer

Spark 3.3: Handle Spark Row more generically

---

spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/ChangelogIterator.java
spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/TestChangelogIterator.java

Backport #6898 to Spark3.2. cc @aokolnychyi @RussellSpitzer

Spark 3.2: Minor updates to ChangelogIterator

---

spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestDelete.java
spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/SparkReadConf.java
spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/SparkUtil.java
spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/actions/SparkZOrderStrategy.java
spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/SparkTable.java

This PR is a cherry-pick of PR #6899.

Spark 3.2: Optimize DELETEs handled using metadata

---

flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkV2.java

not sure why CI build didn't catch the missing import issue.
The other issue with branch is a race condition with PR #6660

Flink: fix compiling error from PR #6753

---

flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/source/IcebergSource.java
flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/source/IcebergSource.java
flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/source/IcebergSource.java

Flink: fixed IcebergSource$Builder missing generics

---

.github/workflows/api-binary-compatibility.yml
.github/workflows/delta-conversion-ci.yml
.github/workflows/flink-ci.yml
.github/workflows/hive-ci.yml
.github/workflows/java-ci.yml
.github/workflows/jmh-benchmarks.yml
.github/workflows/labeler.yml
.github/workflows/license_check.yml
.github/workflows/open-api.yml
.github/workflows/publish-snapshot.yml
.github/workflows/python-ci-docs.yml
.github/workflows/python-ci.yml
.github/workflows/recurring-jmh-benchmarks.yml
.github/workflows/spark-ci.yml
.github/workflows/stale.yml

the new runner image became the new `ubuntu-latest` at the end of last year:
https://github.com/actions/runner-images#available-images
https://github.com/actions/runner-images/commit/9c544f47011f3fb7f13ab122927f15939d950b49

Build: upgrade workflows to ubuntu-22.04

---

gradle/wrapper/gradle-wrapper.properties
gradlew

see https://docs.gradle.org/8.0.2/release-notes.html

Build: Bump Gradle to 8.0.2

---

docs/spark-procedures.md

Add documentation for the new `snapshot_ids` parameter exposed on https://github.com/apache/iceberg/pull/6992

Document new expire_snapshots parameter: snapshot_ids

---

spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestCreateChangelogViewProcedure.java
spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/procedures/BaseProcedure.java
spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/procedures/CreateChangelogViewProcedure.java
spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/procedures/SparkProcedures.java

Spark 3.2: Add a procedure to create changelog view

---

.github/ISSUE_TEMPLATE/iceberg_question.yml

follow up of https://github.com/apache/iceberg-docs/pull/200

Update slack invite link

---

flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/CatalogLoader.java
flink/v1.14/flink/src/main/java/org/apache/iceberg/flink/FlinkCatalogFactory.java
flink/v1.14/flink/src/test/java/org/apache/iceberg/flink/TestCatalogLoader.java

Backport of https://github.com/apache/iceberg/pull/7044 to Flink 1.14

Flink 1.14: Add REST catalog shorthand

---

docs/nessie.md

Follow up on #7031 
latest pom link: https://repo1.maven.org/maven2/org/projectnessie/nessie-spark-extensions-3.3_2.12/0.51.1/nessie-spark-extensions-3.3_2.12-0.51.1.pom

Docs: Update nessie docs

---

core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java

In Trino, we create a separate `FileIO` per user, so we create many `JdbcCatalog` instances, and thus we need a way to share the JDBC client pool across all of these instances.

Core: Allow injecting client pool in JDBC catalog

---

dell/src/test/java/org/apache/iceberg/dell/ecs/TestEcsCatalog.java
dell/src/test/java/org/apache/iceberg/dell/ecs/TestEcsOutputFile.java
dell/src/test/java/org/apache/iceberg/dell/ecs/TestEcsTableOperations.java
dell/src/test/java/org/apache/iceberg/dell/ecs/TestEcsURI.java

Remove `AssertHelpers` in `iceberg-dell` module

dell: remove usage of AssertHelpers

---

mr/src/test/java/org/apache/iceberg/mr/TestCatalogs.java
mr/src/test/java/org/apache/iceberg/mr/TestIcebergInputFormats.java
mr/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerNoScan.java

Remove `AssertHelpers` in `iceberg-mr` module

MR: Remove deprecate AssertHelpers

---

docs/aws.md

Updated document regarding issue below
- https://github.com/apache/iceberg/issues/6636

Docs: update doc to read easier

---

flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/CatalogLoader.java
flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/TableLoader.java
flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/source/IcebergSource.java
flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/source/enumerator/ContinuousSplitPlannerImpl.java
flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/TestTableLoader.java
flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/source/enumerator/TestContinuousSplitPlannerImpl.java

Flink: Backport #6614 to Flink 1.15  

---

aws/src/main/java/org/apache/iceberg/aws/s3/signer/S3V4RestSignerClient.java

Signer instances can be fairly short-lived, meaning that the `AuthSession` cache doesn't get a chance to remove an `AuthSession` from the cache and thus call `AuthSession#stopRefreshing()`.

AWS: Make AuthSession cache static

---

docs/flink-configuration.md
flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/FlinkWriteConf.java
flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/FlinkWriteOptions.java
flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java
flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/TestFlinkTableSink.java

Co-authored-by: chidayong <247070443@qq.com>

Flink: Expose write-parallelism in SQL Hints

---

.palantir/revapi.yml
core/src/main/java/org/apache/iceberg/actions/BaseCommitService.java
core/src/main/java/org/apache/iceberg/actions/RewriteDataFilesCommitManager.java

This is needed for RewritePositionDeleteFiles implementation.

Core: Parameterize RewriteDataFile's CommitService

---

spark/v3.4/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/SetWriteDistributionAndOrderingExec.scala
spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestSetWriteDistributionAndOrdering.java

CP-ed commit https://github.com/apache/iceberg/commit/6504fd809199cbc88ef890cc2f5b42a2cf00e102

Cherry pick Order case sensitivity changes to 3.4

---

README.md

#7391 
It's just a simple change in my thinking.

Updated README.md to support Java 17

---

python/.pre-commit-config.yaml
python/pyiceberg/conversions.py
python/pyiceberg/expressions/__init__.py
python/pyiceberg/expressions/literals.py
python/pyiceberg/expressions/visitors.py
python/pyiceberg/schema.py
python/pyiceberg/typedef.py
python/pyiceberg/utils/decimal.py
python/tests/test_transforms.py
python/tests/utils/test_bin_packing.py

Removed some ignores and removed some list materialization

Python: Update pre-commit to the latest version

---

arrow/src/main/java/org/apache/iceberg/arrow/vectorized/ColumnVector.java
baseline.gradle
hive3/src/main/java/org/apache/hadoop/hive/ql/io/orc/OrcSplit.java

Arrow: Fix errorprone warnings

---

spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/ChangelogIterator.java
spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/ComputeUpdateIterator.java
spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/RemoveCarryoverIterator.java
spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/procedures/CreateChangelogViewProcedure.java
spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/TestChangelogIterator.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/ChangelogIterator.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/ComputeUpdateIterator.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/RemoveCarryoverIterator.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/procedures/CreateChangelogViewProcedure.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/TestChangelogIterator.java

Port #7388 to Spark3.2 and Spark3.4. cc @aokolnychyi @RussellSpitzer

Spark 3.2/3.4: Uniqueness validation when computing updates of changelogs

---

gradle/wrapper/gradle-wrapper.properties
gradlew

see https://docs.gradle.org/8.1.1/release-notes.html
Upgraded by running the following command twice and manually re-applying iceberg customizations:
./gradlew wrapper --gradle-version 8.1.1 --gradle-distribution-sha256-sum e111cb9948407e26351227dabce49822fb88c37ee72f1d1582a69c68af2e702

Build: Upgrade Gradle to 8.1.1

---

docs/branching-and-tagging.md

Improve readability on the page: https://iceberg.apache.org/docs/latest/branching/

Docs: Improve readability on page Branching and Tagging

---

format/view-spec.md

Update view spec with expectations on versions, representations, and dialects.

Views: Update spec with expectations on versions, representations, and dialects

---

spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/SparkScanBuilder.java
spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/source/TestDataSourceOptions.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/source/SparkScanBuilder.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/source/TestDataSourceOptions.java

Disable Agg push down for incremental scan for now. Will have a followup to enable Agg push down for incremental scan.

Disable Agg push down for incremental scan

---

baseline.gradle
spark/v3.4/build.gradle
spark/v3.4/spark-extensions/src/jmh/java/org/apache/iceberg/spark/MergeCardinalityCheckBenchmark.java

Caused by a recent change #7558

Spark-3.4: Fix errorprone warning

---

flink/v1.17/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkManifestUtil.java
flink/v1.17/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java
flink/v1.17/flink/src/main/java/org/apache/iceberg/flink/sink/IcebergFilesCommitter.java
flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/SimpleDataUtil.java
flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkManifest.java
flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/sink/TestIcebergFilesCommitter.java

This ports #7171 to Flink 1.17.

Flink: Port #7171 to flink 1.17

---

flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkManifestUtil.java
flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java
flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/sink/IcebergFilesCommitter.java
flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/SimpleDataUtil.java
flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkManifest.java
flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/sink/TestIcebergFilesCommitter.java

This ports #7171 to Flink 1.15.

Flink: Port #7171 to flink 1.15

---

spark/v3.3/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRewritePositionDeleteFilesProcedure.java
spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/procedures/RewritePositionDeleteFilesProcedure.java
spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/procedures/SparkProcedures.java

Spark 3.3: Backport RewritePositionDeleteFilesProcedure (#7572)

---

spark/v3.3/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestIcebergExpressions.java
spark/v3.3/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRequiredDistributionAndOrdering.java
spark/v3.3/spark/src/main/scala/org/apache/spark/sql/catalyst/expressions/TransformExpressions.scala

Spark 3.3: Fixes bucket on binary column

---

aws/src/test/java/org/apache/iceberg/aws/s3/signer/TestS3RestSigner.java

AWS: Fix Tests3RestSigner on OSX

---

api/src/test/java/org/apache/iceberg/TestHelpers.java
api/src/test/java/org/apache/iceberg/catalog/TestNamespace.java
api/src/test/java/org/apache/iceberg/catalog/TestTableIdentifier.java
api/src/test/java/org/apache/iceberg/events/TestListeners.java
api/src/test/java/org/apache/iceberg/expressions/TestAggregateBinding.java
api/src/test/java/org/apache/iceberg/expressions/TestAggregateEvaluator.java
api/src/test/java/org/apache/iceberg/expressions/TestEvaluator.java
api/src/test/java/org/apache/iceberg/expressions/TestExpressionBinding.java
api/src/test/java/org/apache/iceberg/expressions/TestExpressionHelpers.java
api/src/test/java/org/apache/iceberg/expressions/TestExpressionSerialization.java
api/src/test/java/org/apache/iceberg/expressions/TestExpressionUtil.java
api/src/test/java/org/apache/iceberg/expressions/TestInclusiveManifestEvaluator.java
api/src/test/java/org/apache/iceberg/expressions/TestInclusiveMetricsEvaluator.java
api/src/test/java/org/apache/iceberg/expressions/TestLiteralSerialization.java
api/src/test/java/org/apache/iceberg/expressions/TestMetricsEvaluatorsNaNHandling.java
api/src/test/java/org/apache/iceberg/expressions/TestMiscLiteralConversions.java
api/src/test/java/org/apache/iceberg/expressions/TestNumericLiteralConversions.java
api/src/test/java/org/apache/iceberg/expressions/TestPredicateBinding.java
api/src/test/java/org/apache/iceberg/expressions/TestStrictMetricsEvaluator.java
api/src/test/java/org/apache/iceberg/expressions/TestStringLiteralConversions.java
build.gradle

@nastra as suggested by you in #7666 , I would be closing that PR and would raise new PRs which are more review friendly.
This is the first PR for that. In total there are 60 files within the api tests and I would divide them between 3 PRs.

API: Switch tests to JUnit5

---

python/.pre-commit-config.yaml
python/pyiceberg/catalog/__init__.py
python/pyiceberg/catalog/dynamodb.py
python/pyiceberg/catalog/glue.py
python/pyiceberg/catalog/hive.py
python/pyiceberg/catalog/rest.py
python/pyiceberg/expressions/visitors.py
python/pyiceberg/io/pyarrow.py
python/pyiceberg/schema.py
python/pyiceberg/utils/deprecated.py

D202: No blank lines allowed after function docstring

Fix D202 pydocstring issues in pyiceberg

---

open-api/rest-catalog-open-api.py

Open-API: Update code

---

python/pyiceberg/expressions/__init__.py
python/pyiceberg/types.py
python/tests/expressions/test_expressions.py
python/tests/test_types.py

Python: Add pickle support

---

python/.pre-commit-config.yaml
python/pyiceberg/avro/decoder.py
python/pyiceberg/avro/file.py
python/pyiceberg/catalog/dynamodb.py
python/pyiceberg/conversions.py
python/pyiceberg/expressions/visitors.py
python/pyiceberg/io/__init__.py
python/pyiceberg/partitioning.py
python/pyiceberg/table/metadata.py
python/pyiceberg/table/snapshots.py
python/pyiceberg/transforms.py
python/pyiceberg/types.py
python/pyiceberg/utils/config.py
python/pyiceberg/utils/decimal.py
python/pyiceberg/utils/deprecated.py
python/pyiceberg/utils/schema_conversion.py
python/tests/conftest.py

Python: Fixes for D205 issues

---

docs/spark-configuration.md

followup PR of https://github.com/apache/iceberg/commit/893af4a19841ae23e18b1e2196df9176d9d90bc2
adding doc about org.apache.iceberg.spark.CommitMetadata

add doc about commitmetadata

---

python/.pre-commit-config.yaml
python/pyiceberg/avro/file.py
python/pyiceberg/avro/reader.py
python/pyiceberg/expressions/__init__.py
python/pyiceberg/expressions/literals.py
python/pyiceberg/io/__init__.py
python/pyiceberg/io/memory.py
python/pyiceberg/manifest.py
python/pyiceberg/partitioning.py
python/pyiceberg/schema.py
python/pyiceberg/table/__init__.py
python/pyiceberg/table/refs.py
python/pyiceberg/table/snapshots.py
python/pyiceberg/table/sorting.py
python/pyiceberg/transforms.py
python/pyiceberg/typedef.py
python/pyiceberg/types.py
python/pyiceberg/utils/bin_packing.py
python/tests/conftest.py

Also removes the check against D209 which doesn't actually have any issues

Python: Fixes for D105 issues

---

python/pyiceberg/manifest.py
python/pyiceberg/table/__init__.py

Sorry for making the CI unhappy

Python: Fix docstrings

---

docs/flink-queries.md

fixes https://github.com/apache/iceberg/issues/7907

Docs: Add missing ';' in Flink examples

---

core/src/test/java/org/apache/iceberg/jdbc/TestJdbcCatalog.java
core/src/test/java/org/apache/iceberg/jdbc/TestJdbcTableConcurrency.java
core/src/test/java/org/apache/iceberg/jdbc/TestJdbcUtil.java

This pull request is related to the issue "Move JUnit4 tests to JUnit5 #7160 ".

Core: Migrate jdbc package to JUnit5

---

docs/spark-procedures.md

Add docs for rewritten_bytes_count

---

build.gradle
spark/v3.4/build.gradle
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/data/TestSparkOrcReader.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/data/parquet/vectorized/TestParquetVectorizedReads.java

Just to make sure that the CI passes

Spark: Bump to 3.4.1

---

python/poetry.lock
python/pyproject.toml
python/tests/expressions/test_parser.py

It looks like the tokenizer changed to non-greedy.

Python: Update pyparsing tests

---

docs/aws.md

modified the link to hyperlink .

[doc](aws.md)Enhancement in some hyperlinks

---

aws/src/test/java/org/apache/iceberg/aws/TestAwsClientFactories.java
aws/src/test/java/org/apache/iceberg/aws/TestAwsProperties.java
aws/src/test/java/org/apache/iceberg/aws/TestHttpClientConfigurations.java
aws/src/test/java/org/apache/iceberg/aws/TestRESTSigV4Signer.java
aws/src/test/java/org/apache/iceberg/aws/dynamodb/TestDynamoDbCatalog.java
aws/src/test/java/org/apache/iceberg/aws/glue/TestGlueCatalog.java
aws/src/test/java/org/apache/iceberg/aws/glue/TestGlueToIcebergConverter.java
aws/src/test/java/org/apache/iceberg/aws/glue/TestIcebergToGlueConverter.java
aws/src/test/java/org/apache/iceberg/aws/s3/TestS3RequestUtil.java
aws/src/test/java/org/apache/iceberg/aws/s3/TestS3URI.java
aws/src/test/java/org/apache/iceberg/aws/s3/signer/TestS3SignRequestParser.java
aws/src/test/java/org/apache/iceberg/aws/s3/signer/TestS3SignResponseParser.java
aws/src/test/java/org/apache/iceberg/aws/util/TestRetryDetector.java

This pull request is related to the issue "Move JUnit4 tests to JUnit5 https://github.com/apache/iceberg/issues/7160".
I've switched the files in AWS pakage to JUnit5.

AWS: Switch tests to Junit5

---

python/pyiceberg/serializers.py
python/tests/conftest.py
python/tests/table/test_init.py

Python: Add gzip metadata support

---

flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/FlinkCatalog.java
flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/TestFlinkCatalogDatabase.java
flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/FlinkCatalog.java
flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/TestFlinkCatalogDatabase.java
flink/v1.17/flink/src/main/java/org/apache/iceberg/flink/FlinkCatalog.java
flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/TestFlinkCatalogDatabase.java

Flink: Remove the creation of default database in FlinkCatalog

---

spark/v3.1/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMigrateTableProcedure.java
spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/SparkTableUtil.java
spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMigrateTableProcedure.java
spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/SparkTableUtil.java
spark/v3.3/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMigrateTableProcedure.java
spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/SparkTableUtil.java

This is to port the changes  made in #7980 to different spark versions.

Spark: Port #7980 to other spark versions

---

spark/v3.3/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRewritePositionDeleteFiles.java
spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/SparkValueConverter.java
spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/actions/SparkBinPackPositionDeletesRewriter.java

Spark 3.3: Fix rewrite_position_deletes for certain partition types

---

flink/v1.15/build.gradle
flink/v1.16/build.gradle
flink/v1.17/build.gradle
spark/v3.1/build.gradle
spark/v3.2/build.gradle
spark/v3.3/build.gradle
spark/v3.4/build.gradle

Spark, Flink: Fix running integration tests with JDK17

---

core/src/main/java/org/apache/iceberg/inmemory/InMemoryCatalog.java

This makes `renameTable` thread-safe and aligns the implementation with `renameView` (https://github.com/apache/iceberg/pull/7880)

Core: Make InMemoryCatalog#renameTable thread-safe and simplify code

---

.github/ISSUE_TEMPLATE/iceberg_bug_report.yml
build.gradle

Build: Update revapi and github template version to 1.3.1

---

core/src/main/java/org/apache/iceberg/DeleteFileIndex.java
core/src/test/java/org/apache/iceberg/TestDeleteFileIndex.java

This PR adds a way to build `DeleteFileIndex` from a set of files, which would be later used by distributed planning.

Core: Ability to build DeleteFileIndex from files

---

python/dev/Dockerfile

Python: Add retry for downloading spark package

---

spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestFastForwardBranchProcedure.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/procedures/FastForwardBranchProcedure.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/procedures/SparkProcedures.java

Spark-3.4: Implement `fast_forward` procedure

---

spark/v3.4/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/RowLevelCommandScanRelationPushDown.scala

Fixes get an incorrect push down log for the following SQL:
```sql
update local.db.test_data set name = 'new-value' where id = 0 and upper(name) = 'NAME-0'
```
The logs:
```
[INFO ] 2023-08-07 15:59:59.557 [main] RowLevelCommandScanRelationPushDown -
Pushing operators to local.db.test_data
Pushed filters:
Filters that were not pushed: id = 0
Output: id#0L, name#1, salary#2, _file#5, _pos#6L
```

Spark 3.4: Correct push down log of RowLevelCommandScanRelationPushDown

---

spark/v3.4/spark-extensions/src/jmh/java/org/apache/iceberg/spark/PlanningBenchmark.java

This PR revises our recently added `PlanningBenchmark`:
- Fix generation of min/max boundaries for replicated delete files.
- Fix the benchmark with a sort key predicate.
- Switch to use `BatchScan` directly to test cases with and without column stats and simplify profiling.

Spark 3.4: Revise PlanningBenchmark

---

spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/actions/RewritePositionDeleteFilesSparkAction.java
spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewritePositionDeleteFilesAction.java

Backport of https://github.com/apache/iceberg/pull/7582

Spark 3.3: Add filter to Rewrite position deletes

---

core/src/main/java/org/apache/iceberg/io/ResolvingFileIO.java

In ResolvingFileIO, we use the `HashMap` + lock to keep the thread-safe. We could change to ConcurrentHashMap to simply do it.

Core: Replace HashMap with ConcurrentHashMap in ResolvingFileIO

---

.github/workflows/python-release.yml
python/mkdocs/docs/how-to-release.md

Adds a Github Actions for building the wheels, and also updates the instructions.

Python: Publish Wheels

---

.gitignore
python/pyiceberg/avro/decoder_fast.pyx

Noticed a few unused imports, and I have some Cython generated files that we shouldn't commit outside of the `.gitignore`.

Python: Update .gitignore and remove unused imports

---

spark/v3.3/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/RowLevelCommandScanRelationPushDown.scala

Spark 3.3: Correct push down log of RowLevelCommandScanRelationPushDown

---

python/pyiceberg/avro/file.py

Python: Close the file handler

---

aws/src/main/java/org/apache/iceberg/aws/glue/GlueCatalog.java

Fix issue #7841 
cc: @jackye1995

AWS: Add FileIO tracker/closer to Glue catalog

---

.github/workflows/python-release.yml
python/mkdocs/docs/how-to-release.md

The version was not correctly changed when building an RC. Adding some quotes fixed it. Also some small other issues that I ran into.
Before:
After:

Python: Fix Windows wheel build

---

.palantir/revapi.yml
api/src/main/java/org/apache/iceberg/IncrementalScan.java
core/src/main/java/org/apache/iceberg/BaseIncrementalScan.java
core/src/main/java/org/apache/iceberg/TableScanContext.java
core/src/test/java/org/apache/iceberg/TestBaseIncrementalAppendScan.java

Incremental to be able to specify a branch.

Core, API: Support incremental scanning with branch

---

spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/source/SparkPositionDeltaWrite.java

This is a #313 follow-up pr to address the minor code style issue.

Spark3.4: Fix minor code style issue

---

core/src/main/java/org/apache/iceberg/types/FixupTypes.java

Core: FixupTypes copied doc info.

---

python/mkdocs/docs/index.md

Python: Add note on pip

---

spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/TestSparkWriteConf.java

Address the comment https://github.com/apache/iceberg/pull/8438#discussion_r1317970253

Spark3.4: Fix the minor code style issue

---

python/build-module.py
python/pyiceberg/avro/decoder.py
python/pyiceberg/avro/file.py
python/tests/avro/test_decoder.py
python/tests/avro/test_reader.py

I think it would be good to include a pure Python fallback.
@rustyconover I'm seeing some weird errors here: https://github.com/pola-rs/polars/actions/runs/6109489610/job/16580630135?pr=10375

Python: Non-Cython fallback Avro parser

---

docs/spark-writes.md

Documentation about schemaMerge
See #8005

Schema Merge docs

---

hive-metastore/src/main/java/org/apache/iceberg/hive/MetastoreLock.java
hive-metastore/src/test/java/org/apache/iceberg/hive/TestHiveCommitLocks.java

HIVE: Fix the Hive version checking in MetastoreLock logical error

---

core/src/main/java/org/apache/iceberg/BaseDistributedDataScan.java

This PR adjusts `BaseDistributedDataScan` to pick local planning if heavy column stats must be serialized. In particular, we should default to local planning if column stats must be returned from the scan. We should also default to local planning if equality deletes are present since we need column stats to assign them.

Core: Default to local planning if column stats must be serialized

---

spark/v3.5/spark-extensions/src/jmh/java/org/apache/iceberg/spark/PlanningBenchmark.java

This PR adds local benchmarks for distributed planning.
```
Benchmark                                                                           Mode  Cnt   Score   Error  Units
PlanningBenchmark.distributedPlanningWithMinMaxFilter                                 ss    5   2.232 ± 0.135   s/op
PlanningBenchmark.localPlanningWithMinMaxFilter                                       ss    5   2.264 ± 0.077   s/op
PlanningBenchmark.distributedPlanningWithPartitionAndMinMaxFilter                     ss    5   0.502 ± 0.008   s/op
PlanningBenchmark.localPlanningWithPartitionAndMinMaxFilter                           ss    5   0.481 ± 0.019   s/op
PlanningBenchmark.distributedPlanningWithoutFilter                                    ss    5   3.364 ± 1.577   s/op …
```

Spark 3.5: Add distibuted planning benchmarks

---

spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkReaderDeletes.java

In addition to testing distributed planning for row-level operations, this PR also extends our hybrid tests that leverage both position and equality deletes to also cover distributed planning.

Spark 3.5: Add tests for distributed planning with deletes

---

spark/v3.4/spark/src/main/java/org/apache/iceberg/SparkDistributedDataScan.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/TestSparkDistributedDataScanReporting.java

This PR cherry-picks #8602 to Spark 3.4.

Spark 3.4: Fix metrics reporting in distributed planning

---

spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkReaderDeletes.java

This PR cherry-picks #8604 to Spark 3.4.

Spark 3.4: Add tests for distributed planning with deletes

---

aws/src/main/java/org/apache/iceberg/aws/s3/S3OutputStream.java

Currently, in S3FileIO, we use new FileOutputStream for initialization when creating the current staging file. This kind of initialization means that even when explicitly calling close() on these streams, they'll only be really closed when a garbage collection is done. Same applies for the input stream

AWS: Replace FileOutputStream/InputStream constructor with NIO Files APIs in S3OutputStream

---

dev/stage-binaries.sh

This PR fixes our staging script to include Spark 3.5.

Build: Fix staging script to include Spark 3.5

---

.github/labeler.yml

I noticed that this was missing

Labeler: Add Specification label

---

.github/ISSUE_TEMPLATE/iceberg_bug_report.yml

This PR adds 1.4.0 to our issue template.

Build: Add 1.4.0 to issue template

---

gradle/libs.versions.toml

Upgrade to Jetty 9.4.53.v20231009

---

core/src/main/java/org/apache/iceberg/BaseDistributedDataScan.java
core/src/main/java/org/apache/iceberg/BaseIncrementalChangelogScan.java
core/src/main/java/org/apache/iceberg/BaseOverwriteFiles.java
core/src/main/java/org/apache/iceberg/BaseRewriteFiles.java
core/src/main/java/org/apache/iceberg/FastAppend.java
core/src/main/java/org/apache/iceberg/ManifestFilterManager.java
core/src/main/java/org/apache/iceberg/MergingSnapshotProducer.java
core/src/main/java/org/apache/iceberg/PositionDeletesTable.java
core/src/main/java/org/apache/iceberg/ReachableFileUtil.java
core/src/main/java/org/apache/iceberg/SnapshotSummary.java
core/src/main/java/org/apache/iceberg/TableMetadata.java
core/src/main/java/org/apache/iceberg/actions/BaseCommitService.java
core/src/main/java/org/apache/iceberg/actions/RewritePositionDeletesGroup.java
core/src/main/java/org/apache/iceberg/io/DeleteWriteResult.java
core/src/main/java/org/apache/iceberg/util/PartitionUtil.java
core/src/main/java/org/apache/iceberg/view/ViewMetadata.java

Core: Replace `.size() > 0` with `!.isEmpty()`

---

build.gradle

Build: add gradle configuration to enforce reproducible build

---

aws/src/integration/java/org/apache/iceberg/aws/TestDefaultAwsClientFactory.java
aws/src/integration/java/org/apache/iceberg/aws/dynamodb/TestDynamoDbCatalog.java
aws/src/integration/java/org/apache/iceberg/aws/dynamodb/TestDynamoDbLockManager.java
aws/src/integration/java/org/apache/iceberg/aws/glue/TestGlueCatalogCommitFailure.java
aws/src/integration/java/org/apache/iceberg/aws/glue/TestGlueCatalogNamespace.java
aws/src/integration/java/org/apache/iceberg/aws/glue/TestGlueCatalogTable.java
aws/src/integration/java/org/apache/iceberg/aws/lakeformation/TestLakeFormationDataOperations.java
aws/src/integration/java/org/apache/iceberg/aws/lakeformation/TestLakeFormationMetadataOperations.java

Remove AssertHelpers usage as part of #7094

AWS: Remove AssertHelpers usage

---

spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/actions/RewriteManifestsSparkAction.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteManifestsAction.java

The action for rewriting manifests caches the manifest entry DF or does an extra shuffle in order to skip reading the actual manifest files twice. We did this assuming it would increase the performance. However, the caching seems to perform poorly for larger tables as it requires substantial cluster resources. In addition, doing a round-robin repartition is expensive as the entries must be written to disk. The extra write is actually more expensive than the extra read required for the range-based shuffle of manifest entries.
Therefore, this PR disables caching by default and removes the optional round-robin repartition step. Instead, we will read the manifests twice (this step is distributed and scales really well even for tables with huge metadata). I did some tests on a cluster and saw …

Spark 3.5: Don't cache or reuse manifest entries while rewriting metadata by default

---

spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/actions/RewriteManifestsSparkAction.java
spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteManifestsAction.java

This PR cherry-picks PR #8935 to Spark 3.3.

Spark 3.3: Don't cache or reuse manifest entries while rewriting metadata by default

---

spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/actions/RewriteManifestsSparkAction.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteManifestsAction.java

This PR cherry-picks PR #8935 to Spark 3.4.

Spark 3.4: Don't cache or reuse manifest entries while rewriting metadata by default

---

api/src/main/java/org/apache/iceberg/view/View.java
core/src/main/java/org/apache/iceberg/view/BaseView.java
core/src/test/java/org/apache/iceberg/view/ViewCatalogTests.java

similar to https://github.com/apache/iceberg/pull/8800, adding UUID to the `View` API

API, Core: Add uuid() to View

---

spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestChangelogTable.java
spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMerge.java
spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRequiredDistributionAndOrdering.java
spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestTagDDL.java
spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestUpdate.java

Remove usage of assert helpers as part of #7094

Spark 3.5:  Remove AssertHelpers usage

---

flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/TestFlinkCatalogFactory.java
flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/TestFlinkCatalogTable.java
flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/TestFlinkCatalogTablePartitions.java
flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/TestFlinkSchemaUtil.java
flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/TestIcebergConnector.java
flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSink.java
flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkV2.java
flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkV2Base.java
flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/source/TestFlinkScan.java
flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/source/TestFlinkSourceConfig.java
flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/source/TestFlinkTableSource.java
flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/source/TestStreamScanSql.java
flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/source/TestStreamingMonitorFunction.java
flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/source/enumerator/TestContinuousSplitPlannerImpl.java
flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/source/enumerator/TestContinuousSplitPlannerImplStartStrategy.java

Remove assert helpers as part of #7094

Flink v1.15 : Remove usage of AssertHelpers

---

flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/TestFlinkCatalogFactory.java
flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/TestFlinkCatalogTable.java
flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/TestFlinkCatalogTablePartitions.java
flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/TestFlinkSchemaUtil.java
flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/TestIcebergConnector.java
flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSink.java
flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkV2.java
flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkV2Base.java
flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/source/TestFlinkScan.java
flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/source/TestFlinkSourceConfig.java
flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/source/TestFlinkTableSource.java
flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/source/TestStreamScanSql.java
flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/source/TestStreamingMonitorFunction.java
flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/source/enumerator/TestContinuousSplitPlannerImpl.java
flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/source/enumerator/TestContinuousSplitPlannerImplStartStrategy.java

Remove assert helpers as part of #7094

FlinkV1.16 : Remove usage of AssertHelpers

---

spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestChangelogTable.java
spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMerge.java
spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRequiredDistributionAndOrdering.java
spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestTagDDL.java
spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestUpdate.java

Remove usage of AssertHelpers as part of #7094

Spark 3.4: Remove usage of AssertHelpers

---

spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/actions/RewriteManifestsSparkAction.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteManifestsAction.java

This PR migrates the action for rewriting manifests to use rolling writers. Right now, we collect all entries in a Spark partition into a list to determine the number of entries that must be written and then decide whether to split them into multiple manifest files or not. This process is slow as it forces Spark to materialize all records in a partition before we start writing. Moreover, it consumes quite a bit of memory as each Spark partition is loaded into memory.

Spark 3.5: Use rolling manifest writers when optimizing metadata

---

core/src/main/java/org/apache/iceberg/jdbc/JdbcTableOperations.java
core/src/main/java/org/apache/iceberg/jdbc/JdbcUtil.java

Fixes https://github.com/apache/iceberg/issues/8989

De-dup props in JdbcUtil

---

.github/ISSUE_TEMPLATE/iceberg_bug_report.yml

Adds 1.4.2 as latest release to issue template

Infra: Add 1.4.2 as latest release to issue template

---

core/src/main/java/org/apache/iceberg/BaseRewriteManifests.java
core/src/test/java/org/apache/iceberg/TableTestBase.java
core/src/test/java/org/apache/iceberg/TestRewriteManifests.java

This PR enables delete manifest replacement, basis for delete manifest compaction.

Core: Support replacing delete manifests

---

spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/actions/RewriteManifestsSparkAction.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteManifestsAction.java

This PR cherry-picks PR #8972 to Spark 3.4.

Spark 3.4: Use rolling manifest writers when optimizing metadata

---

docs/spark-queries.md

org.apache.spark.sql.DataFrameReader does not take parameters

Docs: Update spark-queries.md

---

azure/src/main/java/org/apache/iceberg/azure/AzureProperties.java
azure/src/test/java/org/apache/iceberg/azure/AzurePropertiesTest.java

The Azure Blob Storage client library, including the hadoop-azure stuff, allow using shared-key authentication, which is handy for testing purposes with Azurite. Unfortunately, `AzureProperties` does not play nicely here, because it does not support shared-keys. This change adds two new properties to allow shared-key authentication.

Azure: Allow shared-key auth for testing purposes

---

parquet/src/main/java/org/apache/iceberg/parquet/ParquetBloomRowGroupFilter.java

Add a log entry for bloom filter, so user can easily find out if bloom filter is being used in their applications.

Add log entry for bloom filter

---

spark/v3.3/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMetaColumnProjectionWithStageScan.java
spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/SparkStagedScan.java
spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/SparkStagedScanBuilder.java
spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMetaColumnProjectionWithStageScan.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/source/SparkStagedScan.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/source/SparkStagedScanBuilder.java

cherry pick #8872 to spark 3.3 3.4

Spark 3.4 3.3: Support metadata columns in staged scan (#8872)

---

open-api/requirements.txt

Open-API: Remove pydantic pin

---

core/src/main/java/org/apache/iceberg/SerializableTable.java

Core: lazily create locationProvider in SerializableTable

---

aws/src/main/java/org/apache/iceberg/aws/dynamodb/DynamoDbCatalog.java
aws/src/main/java/org/apache/iceberg/aws/glue/GlueCatalog.java
core/src/main/java/org/apache/iceberg/hadoop/HadoopCatalog.java
core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java
core/src/main/java/org/apache/iceberg/util/LocationUtil.java
dell/src/main/java/org/apache/iceberg/dell/ecs/EcsCatalog.java
spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/SparkRowLevelOperationsTestBase.java
spark/v3.3/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/SparkRowLevelOperationsTestBase.java

Use Strings to verify null and empty string

---

format/spec.md

Resolves parquet part of https://github.com/apache/iceberg/issues/9099
Resolves #9099

Spec: Clarify how column IDs are required for parquet files

---

spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRewriteManifestsProcedure.java

Influenced by patch: https://github.com/apache/iceberg/pull/6695, rewrite manifests op will not execute in testReplacePartitionField due to only one record in table. This will cause the function to not properly test for patch : https://github.com/apache/iceberg/pull/5691

Spark 3.5: Fix testReplacePartitionField for Rewrite Manifests

---

jmh.gradle

Noticed this while running some benchmarks

JMH: Improvements to `jmh.gradle`

---

baseline.gradle
build.gradle
deploy.gradle
settings.gradle
tasks.gradle

BOMs are pretty useful to align dependencies of a project. Their usage is optional though.
fixes https://github.com/apache/iceberg/issues/7371

Build: Add `iceberg-bom` artifact

---

flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/util/TestFlinkPackage.java
gradle/libs.versions.toml

Upgrades Flink Version from 1.18 to 1.18.1

Flink: Upgrade Flink version from 1.18 to 1.18.1

---

.github/ISSUE_TEMPLATE/iceberg_bug_report.yml

Update iceberg_bug_report.yml to 1.4.3

Update iceberg_bug_report.yml to 1.4.3

---

doap.rdf

As per https://iceberg.apache.org/releases/

Update ASF DOAP rdf file

---

.github/workflows/site-ci.yml
site/dev/deploy.sh

Update site-ci with github action credentials

Update site-ci with github action credentials

---

1.4.0/mkdocs.yml
1.4.1/mkdocs.yml
1.4.2/mkdocs.yml
1.4.3/mkdocs.yml

Add missing new docs to nav

---

dev/check-license

RAT 0.16.1 provides important performance improvement.

Build/Release: Upgrade to RAT 0.16.1

---

flink/v1.18/flink/src/main/java/org/apache/iceberg/flink/source/ScanContext.java
flink/v1.18/flink/src/main/java/org/apache/iceberg/flink/source/StreamingMonitorFunction.java
flink/v1.18/flink/src/main/java/org/apache/iceberg/flink/source/enumerator/ContinuousSplitPlannerImpl.java
flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/source/TestIcebergSourceContinuous.java
flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/source/TestStreamScanSql.java

With this change, we are now able to specify a branch when reading with the Flink Iceberg Source

Flink: Adds the ability to read from a branch on the Flink Iceberg Source

---

spark/v3.4/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/analysis/ResolveViews.scala
spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestViews.java

This backports #9587 to Spark 3.4

Spark 3.4: Rewrite identifier when using Subquery expressions in View

---

spark/v3.4/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/analysis/RewriteViewCommands.scala
spark/v3.4/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/plans/logical/views/ShowIcebergViews.scala
spark/v3.4/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/DescribeV2ViewExec.scala
spark/v3.4/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/ExtendedDataSourceV2Strategy.scala
spark/v3.4/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/ShowCreateV2ViewExec.scala
spark/v3.4/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/ShowV2ViewPropertiesExec.scala
spark/v3.4/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/ShowV2ViewsExec.scala
spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestViews.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/SparkCatalog.java

This backports #9513 to Spark 3.4

Spark 3.4: Add support for describing/showing views

---

spark/v3.4/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/analysis/ResolveViews.scala
spark/v3.4/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/analysis/RewriteViewCommands.scala
spark/v3.4/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/analysis/ViewUtil.scala
spark/v3.4/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/AlterV2ViewSetPropertiesExec.scala
spark/v3.4/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/AlterV2ViewUnsetPropertiesExec.scala
spark/v3.4/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/ExtendedDataSourceV2Strategy.scala
spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestViews.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/SparkCatalog.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/source/SparkView.java

This backports #9582 to Spark 3.4

Spark 3.4: Support altering view properties

---

spark/v3.4/build.gradle
spark/v3.4/spark-extensions/src/jmh/java/org/apache/iceberg/DeleteFileIndexBenchmark.java

This PR cherry-picks PR #9165 to Spark 3.4.

Spark 3.4: Rework DeleteFileIndexBenchmark

---

spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRewriteDataFilesProcedure.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/procedures/RewriteDataFilesProcedure.java
spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRewriteDataFilesProcedure.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/procedures/RewriteDataFilesProcedure.java

close #8582
CC @aokolnychyi @ConeyLiu @RussellSpitzer

Spark 3.4, 3.5: Use ProcedureInput for RewriteDataFiles

---

azure/src/test/java/org/apache/iceberg/azure/adlsv2/AzuriteContainer.java

To check if it works against the latest version of the Azure SDK: https://github.com/apache/iceberg/pull/9571

Bump Azurite container

---

spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/data/SparkParquetWriters.java

Backport of https://github.com/apache/iceberg/pull/9440

Spark 3.3: Move the Writer to a visitor

---

spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/data/SparkParquetWriters.java

Backport of https://github.com/apache/iceberg/pull/9440

Spark 3.4: Move the Writer to a visitor

---

core/src/main/java/org/apache/iceberg/TableMetadata.java
core/src/test/java/org/apache/iceberg/TestTableMetadata.java
spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMetadataTables.java

Core: Don't reset snapshotLog when replacing Table

---

core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java
core/src/main/java/org/apache/iceberg/jdbc/JdbcUtil.java
core/src/test/java/org/apache/iceberg/jdbc/TestJdbcCatalog.java
core/src/test/java/org/apache/iceberg/jdbc/TestJdbcViewCatalog.java

Core: Fix JDBC schema version when initialization is disabled

---

core/src/main/java/org/apache/iceberg/actions/BaseCommitService.java
spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/procedures/BaseProcedure.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/procedures/BaseProcedure.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/procedures/BaseProcedure.java

Build: Fix minor build warning related to link tag.

---

format/spec.md

Fix the main image on the spec.

Fix the main image on the spec.

---

core/src/test/java/org/apache/iceberg/catalog/CatalogTests.java

... so those can be re-used in concrete test classes

Core: Make constants in `CatalogTests` protected

---

site/mkdocs.yml
site/nav.yml

Don't merge this until #9930 and #9929 are both merged.

Update site to 1.5.0 docs

---

flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/util/TestFlinkPackage.java
flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/util/TestFlinkPackage.java
gradle/libs.versions.toml

https://flink.apache.org/posts/

Flink: Bump minor versions

---

site/docs/how-to-release.md
site/mkdocs.yml

- Resolve Nessie version for site docs
- Add release notes link to template

Docs: Update site docs

---

parquet/src/main/java/org/apache/iceberg/parquet/BasePageIterator.java

Add `initRepetitionLevelsReader()` to the BasePageIterator class to be on pair with `initDefinitionLevelsReader`. In the future we can support vectorized repetition level reader in VectorizedPageIterator.

Parquet: Refactor BasePageIterator to add initRepetitionLevelsReader

---

site/docs/blogs.md

Add 11 Blogs from Dremio Blog
Add 2 Blogs from my Substack
Fix a few blogs that were labeled 2022 when they should have 2023

Add 13 Dremio Blogs + Fix a few incorrect dates

---

core/src/test/java/org/apache/iceberg/TableTestBase.java
core/src/test/java/org/apache/iceberg/TestBase.java
core/src/test/java/org/apache/iceberg/TestRowDelta.java

Noticed this while working on https://github.com/apache/iceberg/pull/10007

Core: Use <?> as type parameter instead of raw type for SnapshotUpdate

---

site/docs/vendors.md

This PR simply adds Upsolver to the vendor list docs page.

Docs: Added Upsolver to vendor list

---

api/src/main/java/org/apache/iceberg/io/FileIO.java
aws/src/test/java/org/apache/iceberg/aws/s3/TestS3FileIO.java

[1.5.x] API: Fix default FileIO#newInputFile ManifestFile, DataFile and DeleteFile implementations

---

core/src/main/java/org/apache/iceberg/rest/ExponentialHttpRequestRetryStrategy.java
core/src/test/java/org/apache/iceberg/rest/TestExponentialHttpRequestRetryStrategy.java

[1.5.x] Core: Mark 502 and 504 failures as retryable to the exponential retry strategy

---

open-api/rest-catalog-open-api.yaml

fixes https://github.com/apache/iceberg/issues/10135

Fix open-api /rename/views success return code

---

spark/v3.5/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/optimizer/ReplaceStaticInvoke.scala
spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/SparkPlanUtil.java
spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestSystemFunctionPushDownInRowLevelOperations.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/functions/BaseScalarFunction.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/functions/BucketFunction.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/functions/DaysFunction.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/functions/HoursFunction.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/functions/IcebergVersionFunction.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/functions/MonthsFunction.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/functions/TruncateFunction.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/functions/YearsFunction.java

Cherry picks #9873 to the 1.5.x branch

(1.5.x cherry-pick) Spark 3.5: Fix system function pushdown in CoW row-level commands 

---

flink/v1.17/flink/src/main/java/org/apache/iceberg/flink/source/split/IcebergSourceSplit.java
flink/v1.17/flink/src/main/java/org/apache/iceberg/flink/source/split/IcebergSourceSplitSerializer.java
flink/v1.17/flink/src/main/java/org/apache/iceberg/flink/source/split/SerializerHelper.java
flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/source/SplitHelpers.java
flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/source/split/TestIcebergSourceSplitSerializer.java
flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/source/split/IcebergSourceSplit.java
flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/source/split/IcebergSourceSplitSerializer.java
flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/source/split/SerializerHelper.java
flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/source/SplitHelpers.java
flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/source/split/TestIcebergSourceSplitSerializer.java

Flink: port #9464 to v1.17 and v1.19
```
cp flink/v1.18/flink/src/main/java/org/apache/iceberg/flink/source/split/IcebergSourceSplit.java flink/v1.17/flink/src/main/java/org/apache/iceberg/flink/source/split/IcebergSourceSplit.java
cp flink/v1.18/flink/src/main/java/org/apache/iceberg/flink/source/split/IcebergSourceSplit.java flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/source/split/IcebergSourceSplit.java
cp flink/v1.18/flink/src/main/java/org/apache/iceberg/flink/source/split/IcebergSourceSplitSerializer.java  flink/v1.17/flink/src/main/java/org/apache/iceberg/flink/source/split/IcebergSourceSplitSerializer.java 
cp flink/v1.18/flink/src/main/java/org/apache/iceberg/flink/source/split/IcebergSourceSplitSerializer.java …
```

Flink: port #9464 to v1.17 and v1.19

---

site/docs/how-to-release.md

This will avoid having to clone everything locally.

Use `svn mv` when releasing the binaries

---

site/mkdocs.yml
site/nav.yml

To reviewers: Don't merge until #10215 and #10216 are in.

Update site to 1.5.1 docs

---

site/docs/releases.md

This change adds 1.5.1 release notes

Update 1.5.1 release notes

---

site/docs/how-to-release.md

Release: add instruction to update doap.rdf file as part of release process

---

docs/docs/hive.md

Docs: Update features for Hive 4.0

Docs: Update features for Hive 4.0

---

.github/ISSUE_TEMPLATE/iceberg_bug_report.yml

This change adds Iceberg 1.5.2 to the issue template.

Infra: Add Iceberg 1.5.2 to issue template

---

doap.rdf

This change updates the doap.rdf for the 1.5.2 release.

Update doap.rdf for 1.5.2 release

---

site/docs/hive-quickstart.md

Described as Hive 4.0.0

---

site/docs/vendors.md

Add up-to-date information amd remove ugly raw link.

Docs: Update vendor information for Cloudera

---

aws/src/main/java/org/apache/iceberg/aws/ApacheHttpClientConfigurations.java
aws/src/main/java/org/apache/iceberg/aws/HttpClientProperties.java
aws/src/main/java/org/apache/iceberg/aws/UrlConnectionHttpClientConfigurations.java
aws/src/test/java/org/apache/iceberg/aws/TestHttpClientConfigurations.java
docs/docs/aws.md

cc @RussellSpitzer @szehon-ho @aokolnychyi @akshayakp97 @nastra

Make proxy endpoint configurable for s3 Http clients

---

core/src/main/java/org/apache/iceberg/ClientPoolImpl.java
core/src/test/java/org/apache/iceberg/TestClientPoolImpl.java

cc @RussellSpitzer @aokolnychyi @szehon-ho @amogh-jahagirdar @nastra

Avoid adding a closed client to the pool

---

docs/mkdocs.yml

Fixes Apache Doris documentation link.

Update mkdocs.yml - Fixes Apache Doris documentation link

---

core/src/main/java/org/apache/iceberg/ManifestGroup.java

ManifestGroup#filterManifests(Predicate) is an unused package private API that we can remove since it's always true.

Core: Remove unused ManifestGroup#filterManifests(Predicate)

---

docs/mkdocs.yml

It's missing since 1.5.0
cc @bitsondatadev @nastra

Docs: add metrics-reporting back

---

flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/source/TestIcebergSourceFailover.java
flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/source/TestIcebergSourceFailoverWithWatermarkExtractor.java
flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/source/TestIcebergSourceFailover.java
flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/source/TestIcebergSourceFailoverWithWatermarkExtractor.java
flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/source/TestIcebergSourceFailover.java
flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/source/TestIcebergSourceFailoverWithWatermarkExtractor.java

This attempts to fix https://github.com/apache/iceberg/issues/10356
Also related: https://github.com/apache/iceberg/pull/10370

Flink 1.19: Fix flaky TestIcebergSourceFailover > testBoundedWithSavepoint

---

.github/workflows/site-ci.yml

cc @nastra @Fokko @bitsondatadev

docs: deploy on changes in `docs/`

---

spark/v3.4/spark-runtime/src/integration/java/org/apache/iceberg/spark/SmokeTest.java
spark/v3.5/spark-runtime/src/integration/java/org/apache/iceberg/spark/SmokeTest.java

remove static import from `SmokeTest`

remove static import from `SmokeTest`

---

.github/workflows/spark-ci.yml

Refactor to remove code duplication. Does not change test coverage nor configurations exercised on CI.

Build: Merge job definitions in spark-ci.yml

---

flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/sink/TestIcebergFilesCommitter.java
flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/sink/TestIcebergFilesCommitter.java
flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/sink/TestIcebergFilesCommitter.java

Flink: Fix the condition of formatVersion for skipping test cases

---

flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/source/TestStreamScanSql.java
flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/source/TestStreamScanSql.java
flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/source/TestStreamScanSql.java

Fix incorrect double-checked-locking around `TestStreamScanSql#tEnv`

---

core/src/main/java/org/apache/iceberg/rest/RESTSessionCatalog.java

Core: Handles potential NPE in `RESTSessionCatalog#newSessionCache`

---

gradle.properties

... and explicitly disable the Gradle configuration cache.

Enable the Gradle build cache

---

flink/v1.17/flink/src/main/java/org/apache/iceberg/flink/data/FlinkParquetReaders.java
flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/source/assigner/TestWatermarkBasedSplitAssigner.java
flink/v1.18/flink/src/main/java/org/apache/iceberg/flink/data/FlinkParquetReaders.java
flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/source/assigner/TestWatermarkBasedSplitAssigner.java
flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/data/FlinkParquetReaders.java

Backport of #10580 and resolve IDE warning/error wrt `floorMod`/`floorDiv`.

Flink: Fix `long` casting issues

---

build.gradle

Release notes: https://github.com/revapi/gradle-revapi/releases/tag/1.8.0
Special thanks to @nastra, @jbonofre  
more details: https://github.com/revapi/revapi/issues/296

Build: Use official revapi Gradle plugin

---

flink/v1.18/flink/src/main/java/org/apache/iceberg/flink/data/RowDataUtil.java
flink/v1.18/flink/src/main/java/org/apache/iceberg/flink/source/reader/RowDataRecordFactory.java
flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/TestHelpers.java
flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/data/RowDataUtil.java
flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/source/reader/RowDataRecordFactory.java
flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/TestHelpers.java

Clean backport with:
```
git diff 05923d6ab821a37108409236e03ef7dd5df62670^ 05923d6ab821a37108409236e03ef7dd5df62670 | sed "s/v1.17/v1.18/g" | git apply -3 -p1
git diff 05923d6ab821a37108409236e03ef7dd5df62670^ 05923d6ab821a37108409236e03ef7dd5df62670 | sed "s/v1.17/v1.19/g" | git apply -3 -p1
```

Flink: Backport #10565 to v1.18 and v1.19

---

site/docs/concepts/catalog.md

The link to the catalog properties was broken.

[DOCS] Fix link on Concepts page

---

format/spec.md

based on mailing list discussion: https://lists.apache.org/thread/7w4wyxsnv97trglpcobysy99qf9h2shn

Spec: Clarify which columns can be used for equality delete files.

---

api/src/main/java/org/apache/iceberg/StatisticsFile.java

See: https://github.com/apache/iceberg/pull/6267/files

API: Update StatisticsFile javadoc

---

site/docs/vendors.md

This PR adds Bodo to the list of vendors in the docs.

Docs: Add bodo to iceberg vendors

---

.asf.yaml

As discussed in another PR @findepi @Fokko @ajantha-bhat 😄

Add jbonofre as collaborator on the project

---

flink/v1.17/flink/src/main/java/org/apache/iceberg/flink/source/IcebergSource.java
flink/v1.17/flink/src/main/java/org/apache/iceberg/flink/source/reader/LimitableDataIterator.java
flink/v1.17/flink/src/main/java/org/apache/iceberg/flink/source/reader/RecordLimiter.java
flink/v1.17/flink/src/main/java/org/apache/iceberg/flink/source/reader/RowDataReaderFunction.java
flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/source/TestFlinkSourceConfig.java
flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/source/reader/TestLimitableDataIterator.java
flink/v1.18/flink/src/main/java/org/apache/iceberg/flink/source/IcebergSource.java
flink/v1.18/flink/src/main/java/org/apache/iceberg/flink/source/reader/LimitableDataIterator.java
flink/v1.18/flink/src/main/java/org/apache/iceberg/flink/source/reader/RecordLimiter.java
flink/v1.18/flink/src/main/java/org/apache/iceberg/flink/source/reader/RowDataReaderFunction.java
flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/source/TestFlinkSourceConfig.java
flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/source/reader/TestLimitableDataIterator.java

Flink: backport PR #10748 for limit pushdown

---

baseline.gradle
build.gradle
core/src/main/java/org/apache/iceberg/StaticDataTask.java
flink/v1.17/flink/src/main/java/org/apache/iceberg/flink/sink/shuffle/KeyAssignment.java
flink/v1.17/flink/src/main/java/org/apache/iceberg/flink/sink/shuffle/MapAssignment.java
flink/v1.18/flink/src/main/java/org/apache/iceberg/flink/sink/shuffle/KeyAssignment.java
flink/v1.18/flink/src/main/java/org/apache/iceberg/flink/sink/shuffle/MapAssignment.java
flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/sink/shuffle/KeyAssignment.java
flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/sink/shuffle/MapAssignment.java

Among other things, this pulls newest version of error-prone which adds
new useful checks.

Build: Update baseline gradle plugin to 5.58.0

---

flink/v1.17/flink/src/main/java/org/apache/iceberg/flink/sink/shuffle/AggregatedStatisticsTracker.java
flink/v1.17/flink/src/main/java/org/apache/iceberg/flink/sink/shuffle/CompletedStatistics.java
flink/v1.17/flink/src/main/java/org/apache/iceberg/flink/sink/shuffle/DataStatisticsCoordinator.java
flink/v1.17/flink/src/main/java/org/apache/iceberg/flink/sink/shuffle/RangePartitioner.java
flink/v1.17/flink/src/main/java/org/apache/iceberg/flink/sink/shuffle/SketchRangePartitioner.java
flink/v1.17/flink/src/main/java/org/apache/iceberg/flink/sink/shuffle/SketchUtil.java
flink/v1.17/flink/src/main/java/org/apache/iceberg/flink/sink/shuffle/SortKeyUtil.java
flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/sink/shuffle/TestRangePartitioner.java
flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/sink/shuffle/TestSketchRangePartitioner.java
flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/sink/shuffle/TestSketchUtil.java
flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/sink/shuffle/TestSortKeyUtil.java
flink/v1.18/flink/src/main/java/org/apache/iceberg/flink/sink/shuffle/AggregatedStatisticsTracker.java
flink/v1.18/flink/src/main/java/org/apache/iceberg/flink/sink/shuffle/CompletedStatistics.java
flink/v1.18/flink/src/main/java/org/apache/iceberg/flink/sink/shuffle/DataStatisticsCoordinator.java
flink/v1.18/flink/src/main/java/org/apache/iceberg/flink/sink/shuffle/RangePartitioner.java
flink/v1.18/flink/src/main/java/org/apache/iceberg/flink/sink/shuffle/SketchRangePartitioner.java
flink/v1.18/flink/src/main/java/org/apache/iceberg/flink/sink/shuffle/SketchUtil.java
flink/v1.18/flink/src/main/java/org/apache/iceberg/flink/sink/shuffle/SortKeyUtil.java
flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/sink/shuffle/TestRangePartitioner.java
flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/sink/shuffle/TestSketchRangePartitioner.java
flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/sink/shuffle/TestSketchUtil.java
flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/sink/shuffle/TestSortKeyUtil.java

Flink: backport PR #10823 for range partitioner fixup

---

baseline.gradle

fixes https://github.com/apache/iceberg/issues/10854

Build: Enable FormatStringAnnotation error-prone check

---

docs/docs/branching.md

Docs: Fix SQL in branching docs

---

aws/src/test/java/org/apache/iceberg/aws/s3/signer/S3SignerServlet.java
aws/src/test/java/org/apache/iceberg/aws/s3/signer/TestS3RestSigner.java

AWS: Fix flaky TestS3RestSigner

---

site/docs/blogs.md

Added a blog written by Cloudera in February 2023.

1 Cloudera blog in February 2023

---

core/src/test/java/org/apache/iceberg/util/TestParallelIterable.java

Cleanup related to https://github.com/apache/iceberg/pull/10857

Core: Remove unused throws declarations

---

flink/v1.20/build.gradle
flink/v1.20/flink/src/main/java/org/apache/iceberg/flink/maintenance/operator/JdbcLockFactory.java
flink/v1.20/flink/src/main/java/org/apache/iceberg/flink/maintenance/operator/MonitorSource.java
flink/v1.20/flink/src/main/java/org/apache/iceberg/flink/maintenance/operator/TableChange.java
flink/v1.20/flink/src/main/java/org/apache/iceberg/flink/maintenance/operator/TableMaintenanceMetrics.java
flink/v1.20/flink/src/main/java/org/apache/iceberg/flink/maintenance/operator/Trigger.java
flink/v1.20/flink/src/main/java/org/apache/iceberg/flink/maintenance/operator/TriggerEvaluator.java
flink/v1.20/flink/src/main/java/org/apache/iceberg/flink/maintenance/operator/TriggerLockFactory.java
flink/v1.20/flink/src/main/java/org/apache/iceberg/flink/maintenance/operator/TriggerManager.java
flink/v1.20/flink/src/test/java/org/apache/iceberg/flink/maintenance/operator/ConstantsForTests.java
flink/v1.20/flink/src/test/java/org/apache/iceberg/flink/maintenance/operator/MetricsReporterFactoryForTests.java
flink/v1.20/flink/src/test/java/org/apache/iceberg/flink/maintenance/operator/OperatorTestBase.java
flink/v1.20/flink/src/test/java/org/apache/iceberg/flink/maintenance/operator/TestJdbcLockFactory.java
flink/v1.20/flink/src/test/java/org/apache/iceberg/flink/maintenance/operator/TestLockFactoryBase.java
flink/v1.20/flink/src/test/java/org/apache/iceberg/flink/maintenance/operator/TestMonitorSource.java
flink/v1.20/flink/src/test/java/org/apache/iceberg/flink/maintenance/operator/TestTriggerManager.java
flink/v1.20/flink/src/test/resources/META-INF/services/org.apache.flink.metrics.reporter.MetricReporterFactory

Flink: Port #10484 to v1.20

---

flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/maintenance/operator/JdbcLockFactory.java
flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/maintenance/operator/TableChange.java
flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/maintenance/operator/TriggerEvaluator.java
flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/maintenance/operator/TestMonitorSource.java
flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/maintenance/operator/TestTriggerManager.java

Flink: Port #10992 to v1.19

---

docs/docs/spark-procedures.md

Docs: Fix wrong field name in CDC

---

spark/v3.5/spark-extensions/src/jmh/java/org/apache/iceberg/spark/PlanningBenchmark.java

This PR migrates `PlanningBenchmark` to use `FileGenerationUtil` instead of writing a number of real data files and then replicating them. The new approach is more reflective of the actual performance as the metadata for each file is no longer identical. Plus, it makes the initialization phase much quicker.

Spark 3.5: Use FileGenerationUtil in PlanningBenchmark

---

baseline.gradle

Enable a number of useful error-prone checks.

Build: Enable more error-prone checks

---

site/docs/blogs.md

This PR adds three blogs that I have written:
- Two are from my current company, Decodable.
- One is from my previous company, LakeFS/Treeverse. Note that the published date in the PR reflects the original publication, not the current 'last updated' shown on the article.

Add rmoff blogs

---

docs/docs/kafka-connect.md
docs/mkdocs.yml

This PR adds some initial docs on configuring the Iceberg sink for Kafka Connect.

Kafka Connect: Docs on configuring the sink

---

flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/maintenance/operator/JdbcLockFactory.java
flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/maintenance/operator/LockRemover.java
flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/maintenance/operator/TableMaintenanceMetrics.java
flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/maintenance/operator/TaskResult.java
flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/maintenance/operator/TriggerManager.java
flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/maintenance/operator/ManualSource.java
flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/maintenance/operator/TestLockRemover.java
flink/v1.20/flink/src/test/java/org/apache/iceberg/flink/maintenance/operator/TestLockRemover.java

Changed
```
config.set(CheckpointingOptions.CHECKPOINTING_INTERVAL, Duration.ofMillis(10));
```
to
```
env.enableCheckpointing(10);
```
as this means that the same code works for 1.19 and 1.20.
Otherwise a clean backport

Flink: Port #10484 to v1.19 (#11010)

---

docs/docs/spark-procedures.md

Docs: Fix missing options for remove_orphan_files procedure

---

1.4.0/docs/spark-procedures.md
1.4.1/docs/spark-procedures.md
1.4.2/docs/spark-procedures.md
1.4.3/docs/spark-procedures.md
1.5.0/docs/spark-procedures.md
1.5.1/docs/spark-procedures.md
1.5.2/docs/spark-procedures.md
1.6.0/docs/spark-procedures.md
1.6.1/docs/spark-procedures.md

Docs: Backport fixes for remove_orphan_files procedure

---

arrow/src/main/java/org/apache/iceberg/arrow/vectorized/parquet/VectorizedDictionaryEncodedParquetValuesReader.java
arrow/src/main/java/org/apache/iceberg/arrow/vectorized/parquet/VectorizedParquetDefinitionLevelReader.java

Remove unused vectorized Parquet readers.

Arrow: Remove dead code

---

spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/SparkScanBuilder.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/source/SparkScanBuilder.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/source/SparkScanBuilder.java

Fixing https://github.com/apache/iceberg/issues/11245

Remove unnecessary copying of FileScanTask

---

api/src/test/java/org/apache/iceberg/types/TestSerializableTypes.java

Trivial fix for the test.
Discovered by working on #11178

Small fix to TestSerializableTypes.java

---

flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkRangeDistributionBucketing.java
flink/v1.20/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkRangeDistributionBucketing.java

will come back to change the assertion logic later.

Flink: disable the flaky range distribution bucketing tests for now

---

spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestViews.java

Spark 3.4: Randomize view/function names in testing

---

core/src/main/java/org/apache/iceberg/SnapshotParser.java
core/src/test/java/org/apache/iceberg/TestSnapshotJson.java

Revert "Core: Snapshot `summary` map must have `operation` key"

---

site/docs/how-to-release.md

Docs: Fix format of verifying release candidate with Flink

---

gradle/wrapper/gradle-wrapper.properties
gradlew

Upgrade to Gradle 8.11.0

---

spark/v3.5/spark-extensions/src/jmh/java/org/apache/iceberg/spark/PlanningBenchmark.java

This PR adapts our `PlanningBenchmark` for DVs.
```
Benchmark                                                                          (type)  Mode  Cnt            Score              Error   Units
PlanningBenchmark.distributedPlanningWithMinMaxFilter                           partition    ss    5            1.415 ±            0.553    s/op
PlanningBenchmark.distributedPlanningWithMinMaxFilter                                file    ss    5            5.000 ±            1.021    s/op
PlanningBenchmark.distributedPlanningWithMinMaxFilter                                  dv    ss    5            2.312 ±            0.307    s/op
PlanningBenchmark.distributedPlanningWithoutFilter                              partition    ss    5            2.147 ±            1.272    s/op …
```

Spark 3.5: Adapt PlanningBenchmark for DVs

---

data/src/main/java/org/apache/iceberg/data/TableMigrationUtil.java
spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestAddFilesProcedure.java
spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMigrateTableProcedure.java
spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestSnapshotTableProcedure.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/SparkTableUtil.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/procedures/MigrateTableProcedure.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/procedures/SnapshotTableProcedure.java

This PR cherry picks https://github.com/apache/iceberg/pull/11157 for the 1.7.1 release.

1.7.1rc0 cherry pick PR #11157

---

spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestChangelogTable.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/source/SparkScanBuilder.java

This cherry picks https://github.com/apache/iceberg/pull/11564 for 1.7.1

1.7.1rc0 cherry pick PR #11564

---

core/src/main/java/org/apache/iceberg/TableMetadataParser.java

This PR applies https://github.com/apache/iceberg/pull/11621 to the 1.7.x branch in preparation for 1.7.1.

1.7.x apply PR #11220

---

core/src/main/java/org/apache/iceberg/rest/CatalogHandlers.java
core/src/main/java/org/apache/iceberg/rest/RESTSessionCatalog.java
core/src/test/java/org/apache/iceberg/rest/RESTCatalogAdapter.java
core/src/test/java/org/apache/iceberg/rest/TestRESTCatalog.java

REST: Use HEAD request to check table existence

---

doap.rdf

From the list of accepted values: https://projects.apache.org/validation.json

Add C++ to the list of languages in `doap.rdf`

---

kafka-connect/kafka-connect-runtime/docker/docker-compose.yml
site/docs/spark-quickstart.md

Also update the naming from `iceberg-rest-adapter-image` -> `iceberg-rest-fixtures` in the docs

REST: Use apache/iceberg-rest-fixture docker image

---

README.md

Add the new iceberg-cpp effort to the readme

Update README.md to add link to iceberg-cpp

---

.asf.yaml

@samredai has [agreed to be swapped out of the collaborator list](https://github.com/apache/iceberg/pull/11859#discussion_r1907239801). Thanks, Sam!

Infra: Add manuzhang to collaborators

---

site/overrides/home.html

Follow up on [Nhyi-streamlit](https://github.com/apache/iceberg/issues?q=is%3Apr+is%3Aopen+author%3ANhyi-streamlit) since they are currently on vacation :)

Put a CFP Banner on the Homepage

---

core/src/main/java/org/apache/iceberg/rest/HTTPClient.java
core/src/test/java/org/apache/iceberg/rest/TestHTTPClient.java

Relates to changes from PR https://github.com/apache/iceberg/pull/9195

Core, Rest: Read the max connection for rest client from properties

---

api/src/main/java/org/apache/iceberg/ScanTask.java

API: Fix parameter of ScanTask

---

NOTICE
aws-bundle/NOTICE
azure-bundle/NOTICE
bundled-guava/NOTICE
flink/v1.18/flink-runtime/NOTICE
flink/v1.19/flink-runtime/NOTICE
flink/v1.20/flink-runtime/NOTICE
gcp-bundle/NOTICE
kafka-connect/kafka-connect-runtime/NOTICE
open-api/NOTICE
spark/v3.3/spark-runtime/NOTICE
spark/v3.4/spark-runtime/NOTICE
spark/v3.5/spark-runtime/NOTICE

Update notice files copyright end year to 2025

Update notice files copyright end year to 2025

---

site/docs/vendors.md

Please let me know if you have any questions or any clarification you need. Thanks!

add RisingWave to the Vendors page

---

core/src/main/java/org/apache/iceberg/MetadataColumns.java
core/src/main/java/org/apache/iceberg/PositionDeletesTable.java
core/src/test/java/org/apache/iceberg/TestMetadataTableScans.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/source/DVIterator.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestPositionDeletesReader.java

Core, Spark: Include content offset/size in PositionDeletesTable

---

spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/actions/BaseTableCreationSparkAction.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/actions/BaseTableCreationSparkAction.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/actions/BaseTableCreationSparkAction.java

Spark: Fix typo in NoSuchTableException message

---

spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/data/vectorized/ColumnVectorBuilder.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/data/vectorized/ColumnarBatchReader.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/data/vectorized/ColumnarBatchUtil.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/data/vectorized/DeletedColumnVector.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/data/vectorized/IcebergArrowColumnVector.java

back-porting https://github.com/apache/iceberg/pull/11933/ to Spark 3.4

Spark 3.4: Refactor delete logic in batch reading

---

site/mkdocs.yml

Similar to https://github.com/apache/iceberg/pull/12175/ but agains the main branch

Bump the versions of `site/mkdocs.yml`

---

site/docs/spark-quickstart.md

The notebook is already opened by the docker-compose, no need to open again.
Signed-off-by: xxchan <xxchan22f@gmail.com>

Doc: update note about notebook in spark-quickstart

---

1.6.0/mkdocs.yml
1.6.1/mkdocs.yml
1.7.0/mkdocs.yml
1.7.1/mkdocs.yml

Closes #10378 
cc @jbonofre @Fokko

Docs: Fix links to Javadoc

---

format/spec.md

Typo I saw while working on something else

Spec: Typo - missing be

---

site/docs/releases.md
site/mkdocs.yml
site/nav.yml

Docs: Site update for 1.8.0 release

---

site/docs/terms.md

Fix link of catalog in terms.md

Docs: Fix link of catalog in terms.md

---

aws-bundle/LICENSE
aws-bundle/NOTICE
azure-bundle/LICENSE
azure-bundle/NOTICE
kafka-connect/kafka-connect-runtime/hive/LICENSE
kafka-connect/kafka-connect-runtime/main/LICENSE
open-api/LICENSE

Thanks @jbonofre for the ping :)

Bump versions in `{LICENSE,NOTICE}`

---

core/src/main/java/org/apache/iceberg/rest/HTTPRequest.java
core/src/test/java/org/apache/iceberg/rest/TestHTTPRequest.java

Core: Don't remove trailing slash from absolute paths

---

aws-bundle/LICENSE
azure-bundle/LICENSE
gcp-bundle/LICENSE
kafka-connect/kafka-connect-runtime/hive/LICENSE
kafka-connect/kafka-connect-runtime/main/LICENSE

[1.8.x] Fix versions in LICENSE/NOTICE

---

site/docs/vendors.md

Nothing much to add to the PR title I guess :)

Docs: Add Stackable to the Vendors page

---

format/view-spec.md

View Spec: Fix typo

---

site/docs/hive-quickstart.md

Fix grammar issues in descriptions about Hive environment in hive-quickstart.md

Fix grammar issues in descriptions about Hive environment in hive-quickstart.md

---

core/src/main/java/org/apache/iceberg/TableMetadataParser.java
core/src/main/java/org/apache/iceberg/view/ViewMetadataParser.java

Core: Print un-pretty metadata files without whitespace

---

docs/docs/spark-procedures.md

Docs: Fix link of ndv in spark-procedures.md

Docs: Fix link of ndv in spark-procedures.md

---

kafka-connect/kafka-connect-runtime/hive/LICENSE
kafka-connect/kafka-connect-runtime/main/LICENSE

Equivalent of https://github.com/apache/iceberg/pull/12364 for `1.7.x`

[1.7.x] Fix Kafka-connect `LICENSE` and `NOTICE`

---

core/src/main/java/org/apache/iceberg/TableMetadataParser.java
core/src/test/java/org/apache/iceberg/rest/responses/TestLoadTableResponseParser.java

See https://lists.apache.org/thread/gqqsnww6nqc50pddwn29blzghmb0m0h3
Closes #12310

Core: Write `null` for `current-snapshot-id` for V3+

---

api/src/main/java/org/apache/iceberg/variants/Variant.java
api/src/main/java/org/apache/iceberg/variants/VariantData.java

This implements `VariantData.toString`

API: Implement Variant#toString

---

site/docs/status.md

Updating the implementation status for Go implementation

docs: update go impl status

---

open-api/rest-catalog-open-api.yaml

https://lists.apache.org/thread/lxfbrv32wwn1tkvc37dmor2f8rbkrv2c
The Java client is updated as part of https://github.com/apache/iceberg/pull/12505
fixes https://github.com/apache/iceberg/issues/12502

OpenAPI: Handle NamespaceNotEmptyException when dropping a namespace

---

spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/source/DVIterator.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/source/PositionDeletesRowReader.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/source/TestPositionDeletesReader.java

this backports #11657 and #11808 to Spark 3.4

Spark 3.4: Read DVs when reading from .position_deletes table / Include content offset/size

---

spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteDataFilesAction.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteManifestsAction.java
spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/actions/TestSparkFileRewriter.java
spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteDataFilesAction.java

this backports #11825 to Spark 3.4

Spark 3.4: Rewrite data files with high delete ratio

---

site/docs/blogs.md

Added a new blog post: "How to Load Data into Apache Iceberg: A Step-by-Step Tutorial" by Estuary.

Added New Blog Post: Loading Data into Apache Iceberg

---

site/docs/multi-engine-support.md

Docs: Fix Latest Iceberg Support version of Hive

---

docs/docs/aws.md

Docs: Update link for User-Defined Tag Restrictions in AWS documentation

---

spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestAddFilesProcedure.java
spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMigrateTableProcedure.java
spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestSnapshotTableProcedure.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/SparkTableUtil.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/procedures/MigrateTableProcedure.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/procedures/SnapshotTableProcedure.java

Spark 3.4: Fix NotSerializableException when migrating Spark tables

---

flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/maintenance/api/TableMaintenance.java

backport https://github.com/apache/iceberg/pull/12773

Flink: backport fix rateLimit argument check in TableMaintenance to Flink 1.19

---

core/src/test/java/org/apache/iceberg/TestRewriteFiles.java

Was working on a separate fix for RewriteFiles, and noticed that RewriteFiles API isn't testing against V3 tables. This change updates to test against V3 tables, and uses helper functions to select the right delete file depending on the format version. I'm separating this out from my fix PR since that also needs to update some tests but for that PR, I wanted to put focus on the relevant changes instead of these additional changes.

Core: Update RewriteFiles tests to test against V3

---

.baseline/checkstyle/checkstyle.xml
core/src/test/java/org/apache/iceberg/catalog/CatalogTests.java
core/src/test/java/org/apache/iceberg/util/TestEnvironmentUtil.java

The goal of this PR is to implement the functionality described in issue #12817.

Core: Use assumeThat instead of assumeTrue

---

spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestAddFilesProcedure.java
spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/procedures/AddFilesProcedure.java

Spark3.4: BackPort Add Parallelism Parameter Validation to AddFilesProcedure.

---

site/mkdocs.yml
site/nav.yml

based on https://github.com/apache/iceberg/pull/12919

Docs: Site updates for 1.9.0

---

core/src/main/java/org/apache/iceberg/io/BaseTaskWriter.java
core/src/main/java/org/apache/iceberg/io/RollingFileWriter.java

Expanded the exception handling during writer cleanup to address scenarios where users may lack delete permissions, ensuring consistent behavior with [uncommitted file deletion handling](https://github.com/apache/iceberg/blob/main/core/src/main/java/org/apache/iceberg/BaseTransaction.java#L485).

Core: Broaden exception handling in writer clean up logic

---

docs/docs/aws.md

Incorrect property in CREATE CATALOG for Flink

Docs: Incorrect property in CREATE CATALOG for Flink

---

format/spec.md

This adds a summary of row lineage changes to the section on v3 changes.

Spec: Update v3 summary, add row lineage

---

site/docs/status.md

Many implementations support Azure Data Lake Storage so I've updated the status to reflect the current state

Update ADLS implementation status

---

open-api/rest-catalog-open-api.py
open-api/rest-catalog-open-api.yaml

This adds the encryption keys table that is part of v3, as well as actions to add and remove encryption keys.

REST spec: Add encryption keys

---

open-api/src/testFixtures/java/org/apache/iceberg/rest/RESTServerExtension.java

OpenAPI: Add retries when finding free port for REST server

---

core/src/test/java/org/apache/iceberg/catalog/CatalogTests.java
nessie/src/main/java/org/apache/iceberg/nessie/NessieIcebergClient.java
nessie/src/test/java/org/apache/iceberg/nessie/TestBranchVisibility.java
nessie/src/test/java/org/apache/iceberg/nessie/TestMultipleClients.java
nessie/src/test/java/org/apache/iceberg/nessie/TestNessieCatalog.java
nessie/src/test/java/org/apache/iceberg/nessie/TestNessieIcebergClient.java

This addresses issue  : https://github.com/apache/iceberg/issues/12875

Nessie: Throw a NoSuchNamespaceException when listing a non-existing namespace

---

core/src/test/java/org/apache/iceberg/catalog/CatalogTests.java

In my previous PR #12768  I changed hard coded table locations. But Looks like We missed these two location. This is small pr to fix these two.

CatalogTests: Fixing Table Location with baseTableLocation function

---

format/spec.md

This PR clarifies writer requirements to prevent orphan DVs as discussed on the dev list.

Spec: Clarify writer requirements to prevent orphan DVs

---

site/docs/status.md

Updating status.md with the changes in support after iceberg-go release v0.3.0

chore: Update status.md

---

.baseline/checkstyle/checkstyle.xml
core/src/test/java/org/apache/iceberg/rest/TestRESTCatalog.java

Move tests to assertJ - address feedback https://github.com/apache/iceberg/pull/12818#discussion_r2120167480
cc @nastra

Build, Core: Move assertions to AssertJ / Fix checkstyle rules

---

flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/sink/IcebergSink.java
flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkV2DistributionMode.java
flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/sink/TestIcebergSink.java
flink/v2.0/flink/src/main/java/org/apache/iceberg/flink/sink/IcebergSink.java
flink/v2.0/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkV2DistributionMode.java
flink/v2.0/flink/src/test/java/org/apache/iceberg/flink/sink/TestIcebergSink.java

Both back ports came out clean
cc: @stevenzwu @mxm @pvary @Guosmilesmile

Flink: Backport IcerbegSink RANGE distribution to Flink 1.19 and 2.0

---

azure/src/integration/java/org/apache/iceberg/azure/adlsv2/AzuriteContainer.java

This is the latest tag:
https://mcr.microsoft.com/v2/azure-storage/azurite/tags/list

Bump `AzuriteContainer` to 3.34.0

---

README.md

fix for  #13452 
Update README to include information about the issue and the possible workaround.
Solution discussed early in ICEBERG-13452 does not work so just documenting the workaround

Docs: Describe testcontainer failure workaround

---

docs/docs/spark-ddl.md

Fixes  #13538 
Fix the Spark Doc Bug about CREATE OR REPLACE VIEW

Fix Spark DDL Doc bug

---

.github/ISSUE_TEMPLATE/iceberg_bug_report.yml
doap.rdf

- Add 1.9.2 for bug report 
- updates the doap file

INFRA: Add 1.9.2 to latest

---

core/src/main/java/org/apache/iceberg/TableMetadata.java

Cherry-picked PR #13100 to main branch.

Core: backport PR #13100 from 1.9 to main branch that partially revert 12670 by sending single snapshot rather than in bulk 

---

docs/docs/flink-writes.md

This pr is aim to add doc for the dynamic sink.

Flink: Add doc for the dynamic sink

---

site/docs/vendors.md

Referring to #13511 - this adds in Databricks as a vendor.

Add Databricks to vendors.md

---

spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/source/SparkBatch.java
spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/source/SparkBatch.java
spark/v4.0/spark/src/main/java/org/apache/iceberg/spark/source/SparkBatch.java

Spark: Use ORC batch for orcBatchReadConf()

---

docs/docs/kafka-connect.md

- Link to the Apache Kafka docs
- Fix topic creation command
- Format JSON blocks
- Fix typo

Docs: Update the Kafka Connect readme

---

core/src/main/java/org/apache/iceberg/MetadataUpdateParser.java

Noticed this while checking some logic on PyIceberg

nit: Make style consistent

---

api/src/test/java/org/apache/iceberg/expressions/TestInclusiveMetricsEvaluator.java
flink/v2.0/flink/src/main/java/org/apache/iceberg/flink/maintenance/api/ZkLockFactory.java
flink/v2.0/flink/src/test/java/org/apache/iceberg/flink/maintenance/api/TestJdbcLockFactory.java
flink/v2.0/flink/src/test/java/org/apache/iceberg/flink/maintenance/api/TestLockFactoryBase.java
flink/v2.0/flink/src/test/java/org/apache/iceberg/flink/maintenance/api/TestZkLockFactory.java

The improvements include:
- Enhanced logging: Added lock type and lock path to error logs for better issue localization.
- Parameter validation: Ensured non-negative checks for parameters like sessionTimeoutMs, baseSleepTimeMs, and maxRetries.
- Resource management improvement: Ensured proper resource closure before throwing critical exceptions.
- Upgrade test cases: Replaced JUnit4 syntax with JUnit5 in TestZkLockFactory.
- Additional test case: Added testMultiTableLock to TestZkLockFactory to cover more scenarios.

Flink: Refactor ZkLockFactory to improve code readability and maintainability.

---

aws/src/main/java/org/apache/iceberg/aws/s3/S3InputStream.java
azure/src/main/java/org/apache/iceberg/azure/adlsv2/ADLSInputStream.java
azure/src/test/java/org/apache/iceberg/azure/adlsv2/TestADLSInputStream.java
build.gradle

A follow-up to https://github.com/apache/iceberg/pull/13899 with more fixes of the same issue.

AWS,Azure: Fix S3InputStream and ADLSInputStream connection leaks

---

core/src/main/java/org/apache/iceberg/IncrementalFileCleanup.java

By adding multi-threading when gathering manifests in IncrementalFileCleanup, tables with a high manifest count can be cleaned up faster. In some edge cases where tables have thousands or maybe even close to a million manifests, this operation can take a very long time to finish if it's single-threaded.

Core: Parallelize cleanFiles() in IncrementalFileCleanup

---

flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/maintenance/api/FlinkMaintenanceConfig.java
flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/maintenance/api/LockConfig.java
flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/maintenance/api/RewriteDataFilesConfig.java
flink/v1.20/flink/src/main/java/org/apache/iceberg/flink/maintenance/api/FlinkMaintenanceConfig.java
flink/v1.20/flink/src/main/java/org/apache/iceberg/flink/maintenance/api/LockConfig.java
flink/v1.20/flink/src/main/java/org/apache/iceberg/flink/maintenance/api/RewriteDataFilesConfig.java

Flink: Backport Improve ConfigOption Descriptions for Flink Table Maintenance Configs.

---

dev/source-release.sh

https://iceberg.apache.org/how-to-release/#how-to-verify-a-release

infra: add "how to verify a release" link to the release email template

---

aws/src/integration/java/org/apache/iceberg/aws/s3/TestS3OutputStream.java

Cleanup TestS3OutputStream integration tests by delegating file clean up to JUnit

---

site/docs/vendors.md

Adding Fivetran to the vendors.md file

Update vendors.md adding Fivetran

---

site/docs/multi-engine-support.md

Doc: Add Spark v4.0 to lifecycle status
