python/pyiceberg/utils/schema_conversion.py
@maxdebayser mentioned that he ran into something in Python 3.8: https://github.com/Fokko/incubator-iceberg/pull/377/files#r1221991790
I was unable to reproduce it on my end (if the `from __future__ import annotations` is imported, it _should_ work), but good to get rid of it anyway.
=> Python: Remove future annotations

python/pyiceberg/io/__init__.py
I was doing some final testing befor the release, and noticed that when you don't have PyArrow installed (only s3fs), and you try to describe a table, you'll get a warning:
```
root@0d64c149ba01:/vo# pyiceberg describe dbt_tabular.rides
/vo/pyiceberg/io/__init__.py:283: UserWarning: Could not initialize FileIO: pyiceberg.io.pyarrow.PyArrowFileIO
warnings.warn(f"Could not initialize FileIO: {io_impl}")
Table format version  1
Metadata location
s3://tabular-wh-us-east-1/6efbcaf4-21ae-499d-b340-3bc1a7003f52/f59f662e-878f-42e4-8b66-04b076c8ee23/metadata/00037-c9977e9d-64d7-45fc-a93a-7e10efdfecc9.gz.metadat…
Table UUID            f59f662e-878f-42e4-8b66-04b076c8ee23
Last Updated          1684818900590
Partition spec        []
Sort order            []
Current schema        Schema, id=13
├── 1: …
```
=> Python: Log to logging instead of warn

core/src/main/java/org/apache/iceberg/rest/RESTSerializers.java
We introduced an explicit JSON parser as part of #7750 for `UpdateTableRequest` so that we don't rely on JSON parsing via Reflection. However, registering it got lost during a rebase. This PR adds it back
=> Core: Register JSON Parser for UpdateTableRequest

core/src/main/java/org/apache/iceberg/PartitionsTable.java, core/src/test/java/org/apache/iceberg/MetadataTableScanTestBase.java, core/src/test/java/org/apache/iceberg/TestMetadataTableScans.java, core/src/test/java/org/apache/iceberg/TestMetadataTableScansWithPartitionEvolution.java, spark/v3.1/spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSourceTablesBase.java, spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSourceTablesBase.java, spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSourceTablesBase.java, spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSourceTablesBase.java
close #7560
add 2 column to partition metadata table
- `last_updated_at` with timestamp with timezone type (similar to `committed_at` in snapshot metadata table)
- `last_updated_snapshot_id` with long type  
In Partition metadata table, we moved from iterating over ContentFiles from ManifestReader to ManifestEntry instead, since entry contain both content file and snapshotId, which are valuable to provide last updated timestamp and snapshot information. We group by file for each partition boundary and get the highest snapshot commit timestamp so that we know when exactly is the partition last modified. 
This can be potentially useful for iceberg table ingested by streaming application such as flink, to understand which iceberg partition is "sealed" based on timestamp. However, the write …
=> Add last updated timestamp and snapshotId for partition table

orc/src/test/java/org/apache/iceberg/orc/TestOrcDataWriter.java
This PR aims to fix test failures due to the heterogeneous Hadoop exception types across multiple versions.
**HADOOP VERSION IN GRADLE**
Apache Iceberg builds with Apache Hadoop `2.7.3`
https://github.com/apache/iceberg/blob/6b23d2555d542b83396ce488e253813276d0c25d/versions.props#L4
**Apache Hadoop 2.7.3 Exception**
https://github.com/apache/hadoop/blob/baa91f7c6bc9cb92be5982de4719c1c8af91ccff/hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/FileSystem.java#L2660
```
throw new IOException("No FileSystem for scheme: " + scheme);
```
**Apache Hadoop 2.9.0+ Exception**
https://github.com/apache/hadoop/blame/1c15987ee38b96cf2ef4ff383f3f86e082c50fab/hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/FileSystem.java#L3575
```
throw new …
```
=> ORC: Fix to avoid test failure on Hadoop 2.7.3

flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/source/IcebergSource.java, flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/source/assigner/DefaultSplitAssigner.java, flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/source/assigner/OrderedSplitAssignerFactory.java, flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/source/reader/IcebergSourceReader.java, flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/source/reader/IcebergSourceSplitReader.java, flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/source/split/SerializableComparator.java, flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/source/split/SplitComparators.java, flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/source/SplitHelpers.java, flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/source/assigner/SplitAssignerTestBase.java, flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/source/assigner/TestDefaultSplitAssigner.java, flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/source/assigner/TestFileSequenceNumberBasedSplitAssigner.java, flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/source/enumerator/TestContinuousIcebergEnumerator.java, flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/source/reader/TestIcebergSourceReader.java, flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/source/IcebergSource.java, flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/source/assigner/DefaultSplitAssigner.java, flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/source/assigner/OrderedSplitAssignerFactory.java, flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/source/assigner/SimpleSplitAssignerFactory.java, flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/source/reader/IcebergSourceReader.java, flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/source/reader/IcebergSourceSplitReader.java, flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/source/split/SerializableComparator.java, flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/source/split/SplitComparators.java, flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/source/SplitHelpers.java, flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/source/assigner/SplitAssignerTestBase.java, flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/source/assigner/TestDefaultSplitAssigner.java, flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/source/assigner/TestFileSequenceNumberBasedSplitAssigner.java, flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/source/enumerator/TestContinuousIcebergEnumerator.java, flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/source/reader/TestIcebergSourceReader.java
Clean backport of #7661 to older Flink versions
=> Flink: Backport to 1.15 and 1.16: Add possibility of ordering the splits based on the file sequence number (#7661)

core/src/jmh/java/org/apache/iceberg/ManifestReadBenchmark.java, core/src/main/java/org/apache/iceberg/data/avro/DecoderResolver.java, core/src/test/java/org/apache/iceberg/data/avro/TestDecoderResolver.java
Closes #5652
This memory leak especially happens flink sink job which could lead there are many schema and decoders cached in memory and OOM in the end. Such as the following heap dumps:
Here are two problems at here:
1.  The guava map uses identity to compare the key when using the weak key. Here are the details: https://github.com/google/guava/blob/master/guava/src/com/google/common/collect/MapMaker.java#LL58C39-L58C39. 
2. Copied from #5652 
> The DecoderResolver holds a ThreadLocal variable of a two-layer map. The outer map has a weak key while the inner map has a strong one. As the inner map holds a reference to a Schema object, the outer map holding the same weak reference to the Schema object will not release the weak key. That leads to the OOM.
=> Core: Fixes OOM caused by Avro decoder caching

api/src/main/java/org/apache/iceberg/FileScanTask.java, core/src/main/java/org/apache/iceberg/BaseContentScanTask.java, core/src/main/java/org/apache/iceberg/BaseFileScanTask.java, core/src/main/java/org/apache/iceberg/ContentFileParser.java, core/src/main/java/org/apache/iceberg/DataFiles.java, core/src/main/java/org/apache/iceberg/FileScanTaskParser.java, core/src/main/java/org/apache/iceberg/GenericDataFile.java, core/src/main/java/org/apache/iceberg/util/JsonUtil.java, core/src/test/java/org/apache/iceberg/TableTestBase.java, core/src/test/java/org/apache/iceberg/TestContentFileParser.java, core/src/test/java/org/apache/iceberg/TestFileScanTaskParser.java, core/src/test/java/org/apache/iceberg/TestManifestWriterVersions.java, core/src/test/java/org/apache/iceberg/catalog/TestTableIdentifierParser.java, core/src/test/java/org/apache/iceberg/rest/responses/TestListTablesResponse.java, core/src/test/java/org/apache/iceberg/util/TestJsonUtil.java, format/spec.md
this closes issue #1698.
There are two motivations as described by issue #1698.
1) provide a more stable serialization (than Java serialization) for Flink checkpoint
2) can be used by REST catalog for scan planning or committing files
=>  core: add JSON parser for ContentFile and FileScanTask

flink/v1.17/flink/src/main/java/org/apache/iceberg/flink/sink/BaseDeltaTaskWriter.java, flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/SimpleDataUtil.java, flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/sink/TestDeltaTaskWriter.java
Flink data type could have some customized precision, such as `LocalZonedTimestampType(3)`. However, the precision could be lost after converting from  Flink type to Iceberg type back and forth. For example:
```
Flink LocalZonedTimestampType(3) -> Iceberg TimestampType
Iceberg TimestampType -> Flink LocalZonedTimestampType(6)
``` 
So when projecting on the row data to get the equality key, we should create the `RowDataProjection` based on the requested flink table schema
=> Flink: Key projection should be based on the requested Flink table schema

spark/v3.4/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/ExtendedDataSourceV2Strategy.scala, spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRewriteDataFilesProcedure.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/actions/SparkShufflingDataRewriter.java, spark/v3.4/spark/src/main/scala/org/apache/spark/sql/catalyst/plans/logical/OrderAwareCoalesce.scala, spark/v3.4/spark/src/main/scala/org/apache/spark/sql/execution/OrderAwareCoalesceExec.scala, spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteDataFilesAction.java, spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/actions/TestSparkFileRewriter.java
This PR adds a new compaction option called `shuffle-partitions-per-file` for shuffle-based file rewriters.
By default, our shuffling file rewriters assume each shuffle partition would become a separate output file. Attempting to generate large output files of 512 MB and more may strain the memory resources of the cluster as such rewrites would require lots of Spark memory. This parameter can be used to further divide up the data which will end up in a single file. For example, if the target file size is 2 GB, but the cluster can only handle shuffles of 512 MB, this parameter could be set to 4. Iceberg will use a custom coalesce operation to stitch these sorted partitions back together into a single sorted file.
=> Spark 3.4: Multiple shuffle partitions per file in compaction

docs/spark-writes.md
The new `TimestampNtz` Spark type (added in spark 3.4.0) is now [supported by Iceberg](https://github.com/apache/iceberg/pull/7553), this just updates the type conversion tables in the iceberg docs to reflect this.
=> Docs: add support for spark TimestampNtz type to docs

nessie/src/main/java/org/apache/iceberg/nessie/NessieIcebergClient.java, nessie/src/main/java/org/apache/iceberg/nessie/NessieTableOperations.java, nessie/src/main/java/org/apache/iceberg/nessie/NessieUtil.java
Move `NessieTableOperations#loadTableMetadata` -> `NessieUtil#updateTableMetadataWithNessieSpecificProperties `
This is needed for reusing the common code at Trino-Iceberg side for fixing the https://github.com/trinodb/trino/issues/17813
Tentative Trino side changes looks like https://github.com/ajantha-bhat/trino/commit/959445c807204e4c55b008d7b0963e97c8d726d6 once this PR changes are released.
=> Nessie: Minor Refactoring of NessieTableOperations

build.gradle, nessie/src/main/java/org/apache/iceberg/nessie/NessieIcebergClient.java, nessie/src/test/java/org/apache/iceberg/nessie/BaseTestIceberg.java, nessie/src/test/java/org/apache/iceberg/nessie/TestNessieCatalog.java, nessie/src/test/java/org/apache/iceberg/nessie/TestNessieTable.java
Nessie tests will only run against Java 11 or newer, because Nessie's storage implementation (server side thing) only works on Java 11. Nessie client libraries still work fine with Java 8.
=> Nessie: exercise tests against Nessie's new storage model

flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/sink/BaseDeltaTaskWriter.java, flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/SimpleDataUtil.java, flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/sink/TestDeltaTaskWriter.java, flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/sink/BaseDeltaTaskWriter.java, flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/SimpleDataUtil.java, flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/sink/TestDeltaTaskWriter.java
This ports #7836 to Flink 1.15/1.16.
=> Flink 1.15/1.16: Key projection should be based on the requested Flink table schema

open-api/rest-catalog-open-api.yaml
Change list:
1. Change success code of `tableExists` and `renameTable` from HTTP 200 to HTTP 204
Incentive:
According to [RFC spec](https://www.rfc-editor.org/rfc/rfc7231#section-6.3.1), if HTTP 200 is returned, then the response always have payload content. However, the 2 APIs above does not seem to have any return payload, for which cases, the correct success code should be 204.
=> [Rest Catalog Spec] Return 204 on no content response

core/src/main/java/org/apache/iceberg/TableMetadataParser.java
In the WIP for the Nessie Iceberg REST catalog server, there are a few places that currently require us to first serialize a `TableMetadata` to a `String` just to parse it right back into a `TableMetadata`, but this time with the right metadata-location.
First occurence is when we write the table metadata, where we have to first store the table metadata, get the metadata location, and then return the table metadata with the metadata location (and updates cleared). Second occurence is when we return a table metadata with "transient properties", which are used to pass the "expected Nessie commit" around.
This change makes the two `TableMetadataParser.fromJson()` taking a `JsonNode` public
=> Make `TableMetadataParser.fromJson` taking `JsonNode` public

spark/v3.1/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestIcebergExpressions.java, spark/v3.1/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestSetWriteDistributionAndOrdering.java, spark/v3.1/spark/src/main/scala/org/apache/spark/sql/catalyst/expressions/TransformExpressions.scala, spark/v3.1/spark/src/test/java/org/apache/iceberg/spark/SparkTestBase.java
This PR backports https://github.com/apache/iceberg/pull/7693 to Spark 3.1. Since `TestRequiredDistributionAndOrdering` is added after Spark 3.1, we put the `testDefaultSortOnBinaryBucketedColumn` in `TestSetWriteDistributionAndOrdering`.
=> Spark 3.1: Fixes bucket on binary column

spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestIcebergExpressions.java, spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRequiredDistributionAndOrdering.java, spark/v3.2/spark/src/main/scala/org/apache/spark/sql/catalyst/expressions/TransformExpressions.scala
This PR backports #7693 to Spark 3.2
=> Spark 3.2: Fixes bucket on binary column

core/src/main/java/org/apache/iceberg/DataFiles.java, data/src/main/java/org/apache/iceberg/data/TableMigrationUtil.java, spark/v3.1/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMigrateTableProcedure.java, spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMigrateTableProcedure.java, spark/v3.3/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMigrateTableProcedure.java, spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMigrateTableProcedure.java
This is https://github.com/apache/iceberg/issues/7612 reported by @gaborkaszab.
In this change, we fix the Spark migrate procedure to be able to handle a partition where a partition value contains '/'.
We do this by fixing `TableMigrationUtil.listPartition`. Instead of constructing a partition key (a String like `a=1/b=2`) from the `Map<String, String>` of partition column to partition value that is passed in, and then calling `DataFiles.fillFromPath` (via `DataFiles.Builder#withPartitionPath`) with the partition key String, where it is then split along '/' and the value recovered for each partition column (by further splitting along '='), we simply construct a List of the partition values and hand that off.
(We retain `DataFiles.fillFromPath` and `DataFiles.Builder#withPartitionPath` for …
=> Core, Spark: Fix migrate table in case of partitioned table with partition containing a special character

spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestCreateChangelogViewProcedure.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/ChangelogIterator.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/ComputeUpdateIterator.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/RemoveCarryoverIterator.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/RemoveNetCarryoverIterator.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/procedures/CreateChangelogViewProcedure.java, spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/TestChangelogIterator.java
A clean port of #7326 
cc @szehon-ho @RussellSpitzer @aokolnychyi
=> Spark 3.4: Output the net changes across snapshots for carryover rows in CDC

hive-metastore/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java, hive-metastore/src/test/java/org/apache/iceberg/hive/TestHiveCommits.java
We should set the `commitStatus` to `UNKNOWN` before throwing the `CommitStateUnknownException` for `LockException`. Otherwise the `commitStatus` is still `FAILURE` which could lead to the metadata being deleted in `cleanupMetadataAndUnlock`.
=> Hive: Set commit state as Unknown before throwing CommitStateUnknownException

build.gradle
Gradle 8.2 detects this task dependency issue, which means that the build is non-deterministic:
```
FAILURE: Build failed with an exception.
* What went wrong:
A problem was found with the configuration of task ':iceberg-data:revapiAnalyze' (type 'RevapiAnalyzeTask').
- Gradle detected a problem with the following location: '/home/nastra/Development/workspace/iceberg/common/build/libs/iceberg-common-1.4.0-SNAPSHOT.jar'.
Reason: Task ':iceberg-data:revapiAnalyze' uses this output of task ':iceberg-common:jar' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.
Possible solutions:
1. Declare task ':iceberg-common:jar' as an input of ':iceberg-data:revapiAnalyze'.
2. Declare an explicit …
```
=> Build: Fix revapi task dependency issue

core/src/main/java/org/apache/iceberg/BaseFileScanTask.java, core/src/main/java/org/apache/iceberg/FileScanTaskParser.java, core/src/test/java/org/apache/iceberg/TestFileScanTaskParser.java
Also added `schema()` override for BaseFileScanTask$SplitScanTask inner class.
=> Core: add missing start and length for FileScanTaskParser. 

spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/SparkV2Filters.java, spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/TestSparkV2Filters.java
This splits the changes for `NOT_EQ` from #7886
=> Spark 3.4: Support NOT_EQ for V2 filters

core/src/main/java/org/apache/iceberg/rest/CatalogHandlers.java, core/src/main/java/org/apache/iceberg/rest/RESTSerializers.java, core/src/main/java/org/apache/iceberg/rest/RESTSessionCatalog.java, core/src/main/java/org/apache/iceberg/rest/ResourcePaths.java, core/src/main/java/org/apache/iceberg/rest/requests/RegisterTableRequest.java, core/src/main/java/org/apache/iceberg/rest/requests/RegisterTableRequestParser.java, core/src/test/java/org/apache/iceberg/catalog/CatalogTests.java, core/src/test/java/org/apache/iceberg/jdbc/TestJdbcCatalog.java, core/src/test/java/org/apache/iceberg/rest/RESTCatalogAdapter.java, core/src/test/java/org/apache/iceberg/rest/TestResourcePaths.java, core/src/test/java/org/apache/iceberg/rest/requests/TestRegisterTableRequestParser.java, open-api/rest-catalog-open-api.py, open-api/rest-catalog-open-api.yaml
Core: Support `registerTable` with REST session catalog
=> Core: Support registerTable with REST session catalog

build.gradle, gradle/wrapper/gradle-wrapper.properties, gradlew
This reverts commit d2e570a57658a9e2dc20193120338183590a1651 and e62e0add11f5deab9cbd81c7fa122c8047e2f497.
https://github.com/apache/iceberg/pull/7992 introduced API-breaking changes, where I would have expected RevAPI to fail. However, all RevAPI checks passed. I think the best is probably to revert the Gradle version bump for now, so that we don't silently introduce API-breaking changes to the codebase.
=> Revert "Bump Gradle to 8.2 (#7955)"

.github/workflows/api-binary-compatibility.yml
This also probably explains why the PR checks on #7955 all passed, but RevAPI started to complain once #7955 got merged to `master`
=> Build: Run RevAPI on all configured projects

python/pyiceberg/catalog/glue.py, python/pyiceberg/catalog/hive.py, python/tests/catalog/integration_test_glue.py, python/tests/catalog/test_glue.py, python/tests/catalog/test_hive.py
=> Python: Add catalog name to identifiers of tables loaded by Glue and Hive Catalog

core/src/main/java/org/apache/iceberg/PartitionsTable.java, spark/v3.1/spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSourceTablesBase.java, spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSourceTablesBase.java, spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSourceTablesBase.java, spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSourceTablesBase.java
Good callout from @ajantha-bhat on iceberg spec where `timestamptz` supposed to store at microseconds precision but what we did here is essentially store `lastUpdatedMs` in PartitionsTable with microsecond * 1000, or second level precision. 
This patch try to 
-  rename the column name from `last_updated_ms` to `last_updated_at` to conform with what we had in SnapshotsTable
https://github.com/apache/iceberg/blob/master/core/src/main/java/org/apache/iceberg/SnapshotsTable.java#L99
However, this is does not mean we are conforming to the spec as we get such last updated timestamp from iceberg snapshot and it will provide millisecond precious instead of microsecond, so I believe this is best I can think of at the moment without change everything on snapshot.
CC @szehon-ho @rdblue
=> Rename last updated timestamp column in PartitionsTable

spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestExpireSnapshotsProcedure.java, spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMigrateTableProcedure.java, spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestPublishChangesProcedure.java, spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRewriteDataFilesProcedure.java, spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRollbackToSnapshotProcedure.java, spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRollbackToTimestampProcedure.java, spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestSetCurrentSnapshotProcedure.java, spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestSnapshotTableProcedure.java
Remove `AssertHelpers` in iceberg-spark module.
=> Spark 3.4: Remove deprecated AssertHelpers

python/pyiceberg/table/metadata.py, python/pyiceberg/utils/datetime.py, python/tests/utils/test_datetime.py
close #8025 
Use millisecond in TableMetadata in last-update-ms in construction.
=> Python: Let produce last-updated-ms field in metadata at microsecond level

python/pyiceberg/catalog/glue.py
pyiceberg creates 'Parameter' properties on glue catalog database entity and reads namespace properties from 'Parameters' except Location and Comment.
Previous logic ignores Location and Comment if there is no 'Parameters' property in glue database entity. But if glue database is created outside of pyiceberg (for example, create database from AWS web UI of aws cli), 'Parameters' property is not set.
So let load_namespace_properties fallback to empty dict when 'Parameters' property does not exist to load namespace properties consistently.
=> Python: let load_namespace_properties consistent where database is created outside of pyiceberg

spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestDelete.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/SparkTableUtil.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/source/SparkTable.java
=> [1.3.x] Spark 3.4: WAP branch not propagated when using DELETE without WHERE

spark/v3.3/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestDelete.java, spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/SparkTableUtil.java, spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/SparkTable.java
=> Spark-3.3: Backport -WAP branch not propagated when using DELETE with WHERE

spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/CommitMetadata.java, spark/v3.1/spark/src/test/java/org/apache/iceberg/spark/source/TestDataSourceOptions.java, spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/CommitMetadata.java, spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/source/TestDataSourceOptions.java, spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/CommitMetadata.java, spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/source/TestDataSourceOptions.java
This backports #7986 to earlier Spark versions
=> Spark 3.1, 3.2, 3.3: Backport removal of 'snapshot-property' prefix in CommitMetadata properties

spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMigrateTableProcedure.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/SparkTableUtil.java
To address #7929.
When a partitioned table is empty, create an empty append commit instead of throwing an exception.
=> Spark: Allow importing empty tables

core/src/main/java/org/apache/iceberg/rest/HTTPClient.java, core/src/test/java/org/apache/iceberg/catalog/CatalogTests.java
fixes #7821
Without the fix, tests would fail with
```
expected: struct<1: id: required int (unique ID 🤪), 2: data: required string>
but was: struct<1: id: required int (unique ID ?), 2: data: required string>
```
=> Core: Fix unicode handling in HTTPClient

spark/v3.1/spark/src/test/java/org/apache/iceberg/spark/data/TestHelpers.java, spark/v3.1/spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSourceTablesBase.java, spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestDelete.java, spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteDataFilesAction.java, spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/data/TestHelpers.java, spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSourceTablesBase.java, spark/v3.3/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestDelete.java, spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteDataFilesAction.java, spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewritePositionDeleteFilesAction.java, spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/data/TestHelpers.java, spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSourceTablesBase.java, spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestDelete.java, spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteDataFilesAction.java, spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewritePositionDeleteFilesAction.java, spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/data/TestHelpers.java, spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSourceTablesBase.java
- Retrieving data files of a table has been implemented multiple times so moved to `TestHelpers`.
- This is a follow-up PR based on our discussion in https://github.com/apache/iceberg/pull/7920
=> Spark: Consolidate duplicated test methods to TestHelpers

core/src/main/java/org/apache/iceberg/actions/BaseCommitService.java, core/src/test/java/org/apache/iceberg/actions/TestCommitService.java
We have met a very corner case that the rewrite job was aborted due to the timeout waiting. And some of the committed files are deleted meanwhile. The problem here is that the aborting thread (main thread) and the committerService thread could operate the `completedRewrites` concurrently. 
The following code could not run due to the concurrent call from the rewrite thread pool.
https://github.com/apache/iceberg/blob/51eaf6806361e6e0a5cd163071dce684ec05350b/core/src/main/java/org/apache/iceberg/actions/BaseCommitService.java#L133
And then those uncommit file groups will be committed by the committerService when all the rewrite jobs are finished. So when the main thread does the abort cleanings the committerService still could submit the commit request. However, the files that need to …
=> Core: Abort file groups should be under same lock as committerService

docs/flink-queries.md, docs/spark-queries.md
- Sync [PartitionsTable](https://github.com/hsiang-c/iceberg/blob/doc_partitions/core/src/main/java/org/apache/iceberg/PartitionsTable.java) implementation and document.
- This is a follow-up PR based on our discussion in https://github.com/apache/iceberg/pull/7920
=> Docs: Update Partitions table in Flink/Spark doc

core/src/main/java/org/apache/iceberg/TableMetadataParser.java, core/src/test/java/org/apache/iceberg/TestTableMetadata.java, core/src/test/resources/TableMetadataV2ValidMinimal.json
In the Java code, we expect:
- current-snapshot-id
- properties
- snapshots
to be there, but they are actually optional. Related https://github.com/apache/iceberg/pull/8049
Java still writes `-1` for the `current-snapshot-id` when there is no snapshot, but I think it is important to fix the readers first.
=> Core: Handle optional fields

spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRewritePositionDeleteFiles.java, spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRewritePositionDeleteFilesAction.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/SparkValueConverter.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/actions/SparkBinPackPositionDeletesRewriter.java
Fixes: https://github.com/apache/iceberg/issues/8045
This error is from the code that does 'removeDanglingDeletes'. 
In this code, for each partition of a group of delete files, I am trying to find 'live' data files so I can find which deletes no longer apply (dangling) and can clean up.
The issue is, I use the DeleteFile's partition values directly to query data_files table.  I thought it would work as the data_files table is using the transformed partition values, just as the DeleteFile partition values should have.
But the partition data of DeleteFile is not the same type as exposed in the Spark metadata table.
The fix is to convert into something that can be used for Spark query.
=> Spark 3.4: Fix rewrite_position_deletes for certain partition types

core/src/main/java/org/apache/iceberg/actions/BaseCommitService.java, core/src/test/java/org/apache/iceberg/actions/TestCommitService.java
=> [1.3.x] Core: Abort file groups should be under same lock as committerService 

gcp/src/main/java/org/apache/iceberg/gcp/gcs/GCSInputStream.java, gcp/src/test/java/org/apache/iceberg/gcp/gcs/GCSInputStreamTest.java
This PR fixes the conversion of a byte to an int when reading a single byte from GCSInputStream. Decoding integers in Parquet was throwing an exception because of this, in [this method](https://github.com/apache/parquet-mr/blob/1bdb3c6caf1bc45d66719ce6f77d25461216d697/parquet-common/src/main/java/org/apache/parquet/bytes/BytesUtils.java#L88).
=> GCP: fix single byte read in GCSInputStream

python/pyiceberg/avro/decoder.py, python/pyiceberg/avro/file.py, python/pyiceberg/avro/reader.py, python/pyiceberg/avro/resolver.py, python/pyiceberg/manifest.py, python/pyiceberg/typedef.py, python/tests/avro/test_file.py
Utilize __slots__ for various Avro classes.
Memoize the key/value reader functions in MapReader.
=> Python: Improve Avro read performance

python/pyiceberg/io/pyarrow.py, python/pyiceberg/table/__init__.py, python/pyiceberg/utils/concurrent.py
Relates to #8011 and #8015 
Tested on macOS, Ubuntu, and in AWS Lambda. 😄
=> Python: Support serverless environments

spark/v3.1/build.gradle
Spark 3.1: Relocate all Netty classes 
#6107
=> Spark 3.1: Relocate all Netty classes

spark/v3.4/build.gradle
Spark 3.4.1 uses Jackson 2.14.2 according to
https://github.com/apache/spark/blob/v3.4.1/pom.xml#L186-L187, so we should enforce the same version.
=> Spark 3.4: Force Jackson version to 2.14.2

spark/v3.1/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRemoveOrphanFilesProcedure.java, spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/actions/BaseDeleteOrphanFilesSparkAction.java, spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/actions/SetAccumulator.java, spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/procedures/RemoveOrphanFilesProcedure.java, spark/v3.1/spark/src/test/java/org/apache/iceberg/spark/actions/TestRemoveOrphanFilesAction.java
Back-port of https://github.com/apache/iceberg/pull/4652 to Spark 3.1
=> Spark 3.1: Add prefix mismatch mode for deleting orphan files

spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestAddFilesProcedure.java, spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/SparkTableUtil.java
close #8090
backport #6889 to spark 3.2
CC @szehon-ho @puchengy
=> Spark 3.2: Skip duplicate check on deleted file path when import files

spark/v3.3/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRewritePositionDeleteFiles.java, spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRewritePositionDeleteFiles.java
Follow up from comment https://github.com/apache/iceberg/pull/8059#discussion_r1263692477
=> Spark 3.3, 3.4: Migrate TestRewritePositionDeleteFiles to assertJ

spark/v3.4/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/parser/extensions/IcebergSqlExtensionsAstBuilder.scala, spark/v3.4/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/plans/logical/CreateOrReplaceBranch.scala, spark/v3.4/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/plans/logical/CreateOrReplaceTag.scala, spark/v3.4/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/CreateOrReplaceBranchExec.scala, spark/v3.4/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/CreateOrReplaceTagExec.scala, spark/v3.4/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/ExtendedDataSourceV2Strategy.scala, spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestBranchDDL.java, spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestTagDDL.java
Currently, executing `ALTER TABLE x CREATE OR REPLACE TAG xyz` will fail with `Tag does not exist: xyz`.
As a user I'd expect this to create the tag due to the `CREATE OR REPLACE` usage. The same issue happens with branches.
=> Spark 3.4: Create non-existing Tag/Branch when using CREATE OR REPLACE

spark/v3.1/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/parser/extensions/IcebergSqlExtensionsAstBuilder.scala, spark/v3.1/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/plans/logical/CreateOrReplaceBranch.scala, spark/v3.1/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/CreateOrReplaceBranchExec.scala, spark/v3.1/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/ExtendedDataSourceV2Strategy.scala, spark/v3.1/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestBranchDDL.java, spark/v3.2/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/parser/extensions/IcebergSqlExtensionsAstBuilder.scala, spark/v3.2/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/plans/logical/CreateOrReplaceBranch.scala, spark/v3.2/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/plans/logical/CreateOrReplaceTag.scala, spark/v3.2/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/CreateOrReplaceBranchExec.scala, spark/v3.2/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/CreateOrReplaceTagExec.scala, spark/v3.2/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/ExtendedDataSourceV2Strategy.scala, spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestBranchDDL.java, spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestTagDDL.java, spark/v3.3/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/parser/extensions/IcebergSqlExtensionsAstBuilder.scala, spark/v3.3/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/plans/logical/CreateOrReplaceBranch.scala, spark/v3.3/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/plans/logical/CreateOrReplaceTag.scala, spark/v3.3/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/CreateOrReplaceBranchExec.scala, spark/v3.3/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/CreateOrReplaceTagExec.scala, spark/v3.3/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/ExtendedDataSourceV2Strategy.scala, spark/v3.3/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestBranchDDL.java, spark/v3.3/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestTagDDL.java
This backports #8086. Worth mentioning that Spark 3.1 doesn't have SQL support for Tags, so I only backported the fix for Branches
=> Spark 3.1, 3.2, 3.3: Create non-existing Tag/Branch when using CREATE OR REPLACE

hive-metastore/src/test/java/org/apache/iceberg/hive/TestHiveMetastore.java
Tests would fail with the below error because the assertion check is wrong and I missed this during review of #8058 
```
expected: "Failed to delete /tmp/hive8945016726872271834"
but was: true
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at org.apache.iceberg.hive.TestHiveMetastore.lambda$static$0(TestHiveMetastore.java:115)
at java.lang.Thread.run(Thread.java:750)
```
=> Hive: Fix assertion

python/tests/utils/test_datetime.py
Running `test_datetime_to_millis` datetime test locally errors when system timezone is not UTC.
This is because [`datetime.timestamp()`](https://docs.python.org/3/library/datetime.html#datetime.datetime.timestamp) returns the POSIX timestamp using the system local timezone. My currently timezone Pacific time (PT) is 7 hours behind UTC. 
Run command:
```
make install
make test
```
Error message:
```
=================================================================================== FAILURES ====================================================================================
____________________________________________________________________________ test_datetime_to_millis ____________________________________________________________________________
def test_datetime_to_millis() -> None:
dt …
```
=> Python: Fix datetime test when run locally

python/pyiceberg/avro/writer.py
StructWriter was indicating it is a StructReader.
=> Python: fix StructWriter repr to indicate it is a writer

aliyun/src/test/java/org/apache/iceberg/aliyun/oss/mock/AliyunOSSMockLocalController.java, aliyun/src/test/java/org/apache/iceberg/aliyun/oss/mock/AliyunOSSMockLocalStore.java, aliyun/src/test/java/org/apache/iceberg/aliyun/oss/mock/AliyunOSSMockRule.java, api/src/test/java/org/apache/iceberg/TestHelpers.java, aws/src/integration/java/org/apache/iceberg/aws/s3/TestS3FileIOIntegration.java, aws/src/test/java/org/apache/iceberg/aws/s3/TestS3FileIO.java, aws/src/test/java/org/apache/iceberg/aws/s3/TestS3InputStream.java, core/src/jmh/java/org/apache/iceberg/ManifestReadBenchmark.java, dell/src/test/java/org/apache/iceberg/dell/mock/ecs/ObjectData.java, delta-lake/src/main/java/org/apache/iceberg/delta/BaseSnapshotDeltaLakeTableAction.java, gcp/src/test/java/org/apache/iceberg/gcp/gcs/GCSFileIOTest.java, gcp/src/test/java/org/apache/iceberg/gcp/gcs/GCSInputStreamTest.java, hive3/src/main/java/org/apache/iceberg/mr/hive/vector/CompatibilityHiveVectorUtils.java, hive3/src/main/java/org/apache/iceberg/mr/hive/vector/HiveVectorizedReader.java, nessie/src/test/java/org/apache/iceberg/nessie/TestNessieTable.java, parquet/src/main/java/org/apache/iceberg/parquet/ParquetAvro.java
The followed approach is to use native Java 8 code when the alternative was clear or replicate/borrow when not following iceberg-core approach..
Flink and Spark projects declare Apache Commons as direct dependency and therefore on those subprojects the dependency is not removed.
Closes #7658
=> Remove the direct dependency on Apache Commons. Issue - #7658

spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/source/SparkScanBuilder.java
The `ExpressionUtil.selectsPartitions` is aimed to determine whether the expression can be fully applied to the whole partitions. However, it is not necessary for an unpartitioned table. Especially for metadata tables which are always unpartitioned. For example, we get unexpected warnings for the following scan:
```
scala> spark.sql("select file_path, partition, record_count from iceberg.db.table.files where partition.partition_time = 2023012410").show()
23/07/24 14:20:47 WARN SparkScanBuilder: Failed to check if IsNotNull(partition.partition_time) can be pushed down: Cannot find field 'partition.partition_time' in struct: struct<>
23/07/24 14:20:47 WARN SparkScanBuilder: Failed to check if EqualTo(partition.partition_time,2023012410) can be pushed down: Cannot find field …
```
=> Spark: Evaluate ExpressionUtil.selectsPartitions for partitioned table only

python/mkdocs/docs/configuration.md, python/pyiceberg/io/__init__.py, python/pyiceberg/io/pyarrow.py, python/tests/io/test_pyarrow.py
=> Python: Add pyarrow hdfs support

spark/v3.3/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRewritePositionDeleteFiles.java, spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/actions/SparkBinPackPositionDeletesRewriter.java, spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRewritePositionDeleteFiles.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/actions/SparkBinPackPositionDeletesRewriter.java
Solve the "AnalysisException: No such struct field" mentioned in https://github.com/apache/iceberg/issues/8109.
=> Spark: fix rewrite_position_delete_files reports an error when the partition column contains "."

spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/SparkScanBuilder.java
=> Spark 3.3: Evaluate ExpressionUtil.selectsPartitions for partitioned table only

core/src/main/java/org/apache/iceberg/DeleteFileIndex.java, spark/v3.4/spark-extensions/src/jmh/java/org/apache/iceberg/spark/PlanningBenchmark.java
This PR improves and refactors `DeleteFileIndex`.
- Avoid the cost of repeated conversion of min/max boundaries that damages the index lookup performance.
- Use `dataSequenceNumber` from `ContentFile` instead of `ManifestEntry` to support distributed planning in the future.
This change relies on existing tests and adds a new benchmark.
Results prior to this change:
```
Benchmark                                                    Mode  Cnt  Score   Error  Units
PlanningBenchmark.localPlanningWithMinMaxFilter                ss    5  9.740 ± 2.333   s/op
PlanningBenchmark.localPlanningWithPartitionAndMinMaxFilter    ss    5  3.008 ± 0.044   s/op
PlanningBenchmark.localPlanningWithoutFilter                   ss    5  9.569 ± 1.309   s/op
```
Results after this change:
```
Benchmark …
```
=> Core: Optimize DeleteFileIndex

docs/branching-and-tagging.md
Tag name with `'` is an invalid identifier. This PR fixes it in the CREATE TAG example.
=> Docs: Fix tag name in CREATE TAG example

spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/SparkScanBuilder.java, spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/SparkScanBuilder.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/source/SparkScanBuilder.java
To fixe a casting issue while using CDC read.
```
cannot be cast to class org.apache.iceberg.spark.source.SparkScan (org.apache.iceberg.spark.source.SparkChangelogScan and org.apache.iceberg.spark.source.SparkScan are in unnamed module of loader 'app')
at org.apache.iceberg.spark.source.SparkScanBuilder.estimateStatistics(SparkScanBuilder.java:454)
at org.apache.spark.sql.execution.datasources.v2.DataSourceV2Relation.computeStats(DataSourceV2Relation.scala:85)
at org.apache.spark.sql.catalyst.plans.logical.statsEstimation.SizeInBytesOnlyStatsPlanVisitor$.default(SizeInBytesOnlyStatsPlanVisitor.scala:55)
at org.apache.spark.sql.catalyst.plans.logical.statsEstimation.SizeInBytesOnlyStatsPlanVisitor$.default(SizeInBytesOnlyStatsPlanVisitor.scala:27)
at …
```
=> Spark: Fix the ChangelogScan casting issue

api/src/main/java/org/apache/iceberg/expressions/ExpressionUtil.java, api/src/test/java/org/apache/iceberg/expressions/TestExpressionUtil.java, core/src/main/java/org/apache/iceberg/SnapshotScan.java
This implements sanitization for bound expressions and adds an option to bind an expression when sanitizing. The purpose is to get better sanitization for dates and timestamps, which may show up as longs when pushed down from Spark.
=> API: Implement bound expression sanitization

core/src/main/java/org/apache/iceberg/FastAppend.java, core/src/main/java/org/apache/iceberg/MergingSnapshotProducer.java, core/src/main/java/org/apache/iceberg/RollingManifestWriter.java, core/src/main/java/org/apache/iceberg/SnapshotProducer.java, core/src/test/java/org/apache/iceberg/TestManifestWriter.java
In our production env, we noticed the manifest files have a large random size, ranging from several KB to larger than 100 MB.  It seems the `MANIFEST_TARGET_SIZE_BYTES` has not worked during the commit phase.
In this PR, we avoid generating a manifest file larger than `MANIFEST_TARGET_SIZE_BYTES` for newly added content files and will generate multiple manifest files when the size is covered.
=> Core: Avoid generating a large ManifestFile when committing

core/src/main/java/org/apache/iceberg/TableProperties.java, core/src/main/java/org/apache/iceberg/util/TableScanUtil.java, core/src/test/java/org/apache/iceberg/util/TestTableScanUtil.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/SparkReadConf.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/source/SparkPartitioningAwareScan.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/source/SparkScan.java
This PR is an alternative to #7688 and what was initially envisioned by #7465.
=> Spark 3.4: Adaptive split size

api/src/main/java/org/apache/iceberg/ContentFile.java
This PR fixes our Javadoc for `ContentFile` on value counts to match the spec and implementation.
```
Map from column id to number of values in the column (including null and NaN values)
```
=> API: Fix ContentFile doc on value counts

api/src/main/java/org/apache/iceberg/ManageSnapshots.java, core/src/main/java/org/apache/iceberg/SnapshotManager.java, core/src/test/java/org/apache/iceberg/TestSnapshotManager.java, spark/v3.4/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/CreateOrReplaceBranchExec.scala, spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestBranchDDL.java
Currently, we only support creating branches with a given snapshot ID. However, there is no snapshot for an empty table. This PR achieves this by creating a newly empty snapshot for an empty table. And binding the branch to the new snapshot.
=> Spark: Supports creating a branch on an empty table

parquet/src/main/java/org/apache/iceberg/parquet/ParquetCodecFactory.java, parquet/src/main/java/org/apache/iceberg/parquet/ParquetWriter.java
Currently when Parquet caches codecs, it does so by name but does not include the level. The can cause a problem if the level changes between writes in the same process. For example, table A is set to zstd-9, and a new insert occurs. Parquet has now cached zstd as the zstd with level 9 config. In the same process, Table B is set to zstd-3 and a new insert occurs. Parquet will look up the codec in its cache by name only, and return the zstd codec with level 9 set. So table B will be written to using zstd-9 instead of zstd-3.
This PR adds a workaround to include the level when caching codecs during writes so the codec with the correct level will be returned. Ultimately this should be fixed in Parquet and a PR is planned for that, though this PR allows this fix to get in sooner rather than …
=> Parquet: Cache codecs by name and level

open-api/rest-catalog-open-api.py, open-api/rest-catalog-open-api.yaml
The `last-sequence-number` is a required field of [TableMetadata](https://github.com/apache/iceberg/blob/master/format/spec.md#table-metadata-fields) for V2.
=> Open-API: Add last-sequence-number to TableMetadata

core/src/main/java/org/apache/iceberg/SnapshotManager.java, core/src/test/java/org/apache/iceberg/TestSnapshotManager.java
This is a follow-up for #8072 to fix the problems of creating a branch which is already existed and add UT for it.
=> Core: Fails the branch creation on an empty table when the branch exists

python/dev/Dockerfile
Description: Update the integration tests to use Spark 3.4.1 and Iceberg 1.3.1.
Closes: https://github.com/apache/iceberg/issues/8200
Testing: 
```
$ make test-integration-rebuild 
$ make test-integration
```
=> Python: Update Iceberg and Spark versions in integration test

python/pyiceberg/catalog/glue.py, python/tests/catalog/test_glue.py
Fixes #8047 by using the right parameters in session initialization
=> Python: fix glue catalog when using aws credentials

spark/v3.1/spark-extensions/src/main/antlr/org.apache.spark.sql.catalyst.parser.extensions/IcebergSqlExtensions.g4, spark/v3.1/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/parser/extensions/IcebergSparkSqlExtensionsParser.scala, spark/v3.1/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/parser/extensions/IcebergSqlExtensionsAstBuilder.scala, spark/v3.1/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/plans/logical/CreateOrReplaceTag.scala, spark/v3.1/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/plans/logical/DropTag.scala, spark/v3.1/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/plans/logical/TagOptions.scala, spark/v3.1/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/CreateOrReplaceTagExec.scala, spark/v3.1/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/DropTagExec.scala, spark/v3.1/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/ExtendedDataSourceV2Strategy.scala, spark/v3.1/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestTagDDL.java
This is based on https://github.com/apache/iceberg/pull/7097, and back-ports bug fixes https://github.com/apache/iceberg/pull/7652 and https://github.com/apache/iceberg/pull/8086
=> Spark 3.1: Backport Tag DDL

python/pyiceberg/schema.py
I've noticed that the read support for UUIDType, initially introduced in PR #7523, was removed in PR #7873, likely due to a rebase issue.
This PR restores this functionality. However, if the deletion was purposeful, please let me know.
cc: @Fokko @maxdebayser 
Thank you for your time and review.
=> Python: Restore Inferring Iceberg UUIDType from parquet files

docs/flink-getting-started.md
I ran into this issue when testing Iceberg 1.1 release (with Flink 1.16) back in Nov 2022. But I forgot to update the doc. Dipankar Mazumdar asked me about the same jar loading issue. this can help other new users for just trying out Iceberg with Flink SQL.
=> Doc: update Flink get started instruction for 1.16+ due to regression of loading external jar

gcp/src/main/java/org/apache/iceberg/gcp/GCPProperties.java, gcp/src/main/java/org/apache/iceberg/gcp/gcs/GCSFileIO.java, gcp/src/main/java/org/apache/iceberg/gcp/gcs/GCSLocation.java, gcp/src/test/java/org/apache/iceberg/gcp/gcs/GCSFileIOTest.java, gcp/src/test/java/org/apache/iceberg/gcp/gcs/GCSLocationTest.java
This PR adds bulk and prefix operations to GCSFileIO, and has GCSFileIO implement the `SupportsBulkOperations` and `SupportsPrefixOperations` interfaces.
=> GCP: Add prefix and bulk operations to GCSFileIO

python/pyiceberg/expressions/visitors.py, python/pyiceberg/table/__init__.py
There are times when scanning a table that you want the empty files to be returned, this allows that to happen via an option to the scan.
=> Python: add support for returning empty files in scans if requested.

parquet/src/main/java/org/apache/iceberg/parquet/ParquetAvroValueReaders.java, spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/data/TestParquetAvroReader.java
During write, Int64 decimal data is written as `long` and `Int32` decimal data is written as `int`.
https://github.com/apache/iceberg/blob/b64446ce8eb139f06903691158d7acf93e18be88/parquet/src/main/java/org/apache/iceberg/parquet/ParquetAvroWriter.java#L158-L161
But during read, `Int32` data is read as `long` and `Int64` data is read as `int`. Hence the exception. 
Fixes: https://github.com/apache/iceberg/issues/8245
=> Parquet: Fix decimal data reading from ParquetAvroValueReaders

core/src/main/java/org/apache/iceberg/PositionDeletesTable.java, core/src/test/java/org/apache/iceberg/TestMetadataTableScans.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/actions/RewritePositionDeleteFilesSparkAction.java, spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewritePositionDeleteFilesAction.java
This adds support for filter in RewritePositionDeleteFiles.
Logic:  RewritePositionDeletesFiles is based on PositionDeletesTable (a metadata table representing position deletes).  Like all metadata table, it does partition predicate pushdown by transforming the partition spec into something that can evaluate the partition predicate on the metadata table (ie `my_table.position_deletes.partition.part_col` instead of `my_table.part_col`). 
But here the RewritePositionDeleteFiles action actually gets a filter on the original table, not the PositionDeletesTable metadata table.   So we short-circuit this partition-spec transformation in this case.
This is done by adding to the PositionDeletesTableScan a new method baseTableFilter() that takes filter based on the base table, not the …
=> Core, Spark 3.4: Add filter to Rewrite position deletes

api/src/main/java/org/apache/iceberg/PartitionSpec.java
Description: PartitionSpec uses deprecated calls to Transforms methods. These changes were made to resolve compatibility issues in Trino. Trino and Presto now use latest iceberg Transforms APIs and these calls can be updated as well if there no other concerns.
=> Api: Update deprecated calls to Transforms APIs

docs/branching-and-tagging.md, docs/spark-procedures.md
This PR adds docs for `fast_forward` procedure for https://github.com/apache/iceberg/pull/8081/ and update the `Audit Branch` example using the procedure.
=> Docs: Add `fast_forward` procedure

python/dev/Dockerfile, python/dev/provision.py, python/pyiceberg/conversions.py, python/pyiceberg/expressions/literals.py, python/pyiceberg/io/pyarrow.py, python/pyiceberg/transforms.py, python/tests/expressions/test_literals.py, python/tests/test_conversions.py, python/tests/test_integration.py, python/tests/test_schema.py, python/tests/test_transforms.py
Fixes: #8248 
This PR changes the value stored in UUID literal from `uuid` to `bytes` and add relevant integration tests for unpartitined uuid tables
=> Python: Change UUID representation to bytes and add integration tests

orc/src/main/java/org/apache/iceberg/orc/ExpressionToSearchArgument.java, orc/src/test/java/org/apache/iceberg/orc/TestExpressionToSearchArgument.java
ExpressionToSearchArgument should only convert those reference terms. Otherwise, we will get incorrect conversions or exceptions. For example, converting `equal(year("ts"), 10)`:
```java
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
at org.apache.iceberg.orc.ExpressionToSearchArgument.literal(ExpressionToSearchArgument.java:329)
at org.apache.iceberg.orc.ExpressionToSearchArgument.lambda$eq$13(ExpressionToSearchArgument.java:209)
at org.apache.iceberg.orc.ExpressionToSearchArgument.convert(ExpressionToSearchArgument.java:52)
at org.apache.iceberg.orc.TestExpressionToSearchArgument.testExpressionContainsNonReferenceTerm(TestExpressionToSearchArgument.java:492)
```
=> ORC: ExpressionToSearchArgument should only convert reference term

data/src/test/java/org/apache/iceberg/data/TestMetricsRowGroupFilter.java, parquet/src/main/java/org/apache/iceberg/parquet/ParquetBloomRowGroupFilter.java, parquet/src/main/java/org/apache/iceberg/parquet/ParquetDictionaryRowGroupFilter.java, parquet/src/main/java/org/apache/iceberg/parquet/ParquetMetricsRowGroupFilter.java, parquet/src/test/java/org/apache/iceberg/parquet/TestBloomRowGroupFilter.java, parquet/src/test/java/org/apache/iceberg/parquet/TestDictionaryRowGroupFilter.java
The parquet filter evaluator should not throw exceptions for those filters containing non-reference terms. For example, the filter evaluator apply on `year(ts) = 20` will throw `ValidationException`;
=> Parquet: Should not throw exception for filter contains non-reference term

core/src/main/java/org/apache/iceberg/io/ResolvingFileIO.java, core/src/test/java/org/apache/iceberg/io/TestResolvingIO.java
I noticed this issue while working on https://github.com/apache/iceberg/pull/7370 / https://github.com/apache/iceberg/pull/8032 and reproduced this in a small test.
Without this fix, the test fails with 
```
Cannot invoke "org.apache.hadoop.conf.Configuration.get(String, String)" because "conf" is null
java.lang.NullPointerException: Cannot invoke "org.apache.hadoop.conf.Configuration.get(String, String)" because "conf" is null
at org.apache.hadoop.fs.FileSystem.getDefaultUri(FileSystem.java:180)
at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:172)
at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:357)
at org.apache.hadoop.fs.Path.getFileSystem(Path.java:295)
at org.apache.iceberg.hadoop.Util.getFs(Util.java:56)
at org.apache.iceberg.hadoop.HadoopInputFile.fromLocation(HadoopIn …
```
=> Core: Re-apply Hadoop conf if it's null after Kryo ser/de in ResolvingFileIO

flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/source/IcebergSource.java, flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/source/enumerator/IcebergEnumeratorStateSerializer.java, flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/source/split/IcebergSourceSplit.java, flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/source/split/IcebergSourceSplitSerializer.java, flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/source/enumerator/TestIcebergEnumeratorStateSerializer.java, flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/source/split/TestIcebergSourceSplitSerializer.java, flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/source/IcebergSource.java, flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/source/enumerator/IcebergEnumeratorStateSerializer.java, flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/source/split/IcebergSourceSplit.java, flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/source/split/IcebergSourceSplitSerializer.java, flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/source/enumerator/TestIcebergEnumeratorStateSerializer.java, flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/source/split/TestIcebergSourceSplitSerializer.java
it is a clean back port. 
confirmed git diff
```
➜  iceberg git:(backport-7978) ✗ git diff --no-index  flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/source  flink/v1.17/flink/src/main/java/org/apache/iceberg/flink/source
➜  iceberg git:(backport-7978) ✗ git diff --no-index  flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/source  flink/v1.17/flink/src/main/java/org/apache/iceberg/flink/source
```
test folder has some diff related to assertj change, not related to this change
```
➜  iceberg git:(backport-7978) ✗ git diff --no-index  flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/source  flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/source
➜  iceberg git:(backport-7978) ✗ git diff --no-index …
```
=> Flink: backport PR #7978. switch to FileScanTaskParser for JSON serialization of IcebergSourceSplit

python/pyiceberg/avro/reader.py
Numerous reader classes are simply reading integers, they can all inherit from IntegerReader rather than having their own implementations of read() and skip().  Make this change.
=> Python: Simplify `Readers` using inheritance

core/src/main/java/org/apache/iceberg/DeleteFileIndex.java, core/src/main/java/org/apache/iceberg/metrics/ScanMetrics.java, core/src/main/java/org/apache/iceberg/metrics/ScanMetricsUtil.java
This PR avoids an extra copy of the passed iterable of delete files when creating an index from files.
=> Core: Use lazy iterable in DeleteFileIndex

core/src/main/java/org/apache/iceberg/DeleteFileIndex.java
This PR migrates `DeleteFileIndex` to use `HashMap` with precomputed values instead of `ConcurrentHashMap` populated on demand to avoid the extra cost of calling `computeIfAbsent` in `ConcurrentHashMap` for every single data file that must be planned.
=> Core: Use regular map for partition wrappers in DeleteFileIndex

aws/src/main/java/org/apache/iceberg/aws/s3/S3FileIO.java, gcp/src/main/java/org/apache/iceberg/gcp/gcs/GCSFileIO.java
This PR makes the `client()` methods in `S3FileIO` and `GCSFileIO` public, which allows more flexibility in using a file IO instance for storage operations that might not be defined in the interface.
=> AWS, GCP: Allow access to underlying storage client in FileIO

spark/v3.3/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestFastForwardBranchProcedure.java, spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/procedures/FastForwardBranchProcedure.java, spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/procedures/SparkProcedures.java
This is to backport the `fast_forward` procedure added in #8081
=> Spark-3.3 : Backport `fast_forward` procedure

spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/Spark3Util.java, spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/TestSpark3Util.java
Currently, the expression description expects all to be `NamedReference`. This fixes to add support for transform expression.
=> Spark 3.4: Fix Iceberg expression description

python/pyiceberg/catalog/rest.py, python/pyiceberg/serializers.py, python/pyiceberg/table/__init__.py, python/pyiceberg/table/metadata.py, python/tests/catalog/test_hive.py, python/tests/table/test_metadata.py, python/tests/table/test_sorting.py
(It should) closes #7982 
TableMetadataUtil has a `parse_raw` method where it receives a string that will be parsed by a pydantic model. This model will also return the correct TableMetadata version based on the field `format_version`. 
This is like a strategy method that is now handled with a pydantic model (before, there were a couple of if statements).
=> Python: Delegate serialization to pydantic

build.gradle
We removed `@Value.Immutable` usage from `iceberg-api` (by moving it to `iceberg-core`), so we can remove the dependency now
=> API: Remove Immutables dependency

spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/SparkCatalog.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/source/SparkTable.java, spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/sql/TestAlterTable.java
Unlike `sort-order`, I noticed it's still allowed to update the `identifier-fields` property through alter table when browsing related code. Although both `sort-order` and `identifier-fields` have been overwrote in `org.apache.iceberg.spark.source.SparkTable#properties` method, it wouldn't cause any correctness problems. I think it's better to throw an exception for `identifier-fields` as well.
=> Spark 3.4: disallow update identifier fields through alter table set tblproperties

spark/v3.1/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/CreateOrReplaceBranchExec.scala, spark/v3.1/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestBranchDDL.java, spark/v3.2/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/CreateOrReplaceBranchExec.scala, spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestBranchDDL.java, spark/v3.3/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/CreateOrReplaceBranchExec.scala, spark/v3.3/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestBranchDDL.java
Port #8072 to Spark 3.1/3.2/3.3
=> Spark 3.1, 3.2, 3.3: Supports create branch on empty table

spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/procedures/RewriteDataFilesProcedure.java, spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/procedures/RewriteDataFilesProcedure.java, spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/procedures/RewriteDataFilesProcedure.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/procedures/RewriteDataFilesProcedure.java
Noticed while doing #8289, rewrite_data_files exception when getting parse exception for the where clause, does not contain the spark parse exception, leaving user to have to do some guesswork.
=> Spark: Add cause to rewrite_data_files exception when parsing 'where'

spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/SparkReadConf.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/source/SparkScan.java
This PR is a follow-up change to #7714. The idea is to take into account the number of shuffle partitions while determining the cluster parallelism as discussed [earlier](https://github.com/apache/iceberg/pull/7714#discussion_r1275506085). I decided not to check the dynamic allocation config as the proposed approach should work reasonably well in all circumstances and is much easier.
=> Spark 3.4: Take into account number of shuffle partitions in parallelism

docs/spark-procedures.md, spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestSetCurrentSnapshotProcedure.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/procedures/SetCurrentSnapshotProcedure.java
`set_current_snapshot` procedure currently only supports setting snapshot with id. It's much more convenient for users to set snapshot with ref (e.g. use date as a tag for a daily job). This PR adds support for that.
=> Spark 3.4: Support setting current snapshot with ref

core/src/main/java/org/apache/iceberg/util/SnapshotUtil.java, spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestChangelogTable.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/source/SparkChangelogScan.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/source/SparkScanBuilder.java
Currently, when running `create_changelog_view` procedure and there are no snapshots between start time(exclusive) and end time(inclusive), the procedure will fail due to null checks on start snapshot and end snapshot. However, it's possible that there's no updates from upstream for a period of time and the procedure should not fail. This PR attempts to handle it by returning empty results when there are no snapshots between start time and end time.
=> Spark 3.4: Return empty changed rows when there are no snapshots between start time and end time

spark/v3.3/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRewritePositionDeleteFilesProcedure.java, spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/procedures/BaseProcedure.java, spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/procedures/RewritePositionDeleteFilesProcedure.java, spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRewritePositionDeleteFilesProcedure.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/procedures/BaseProcedure.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/procedures/RewritePositionDeleteFilesProcedure.java
This is similar to the 'where' procedure option of rewrite_data_files Spark procedure.
=> Spark 3.3, 3.4: Add where filter to rewrite_position_delete_files procedure

python/pyiceberg/catalog/__init__.py
* `load_catalog` API does not require the name of the catalog to be passed in as it can figure that out from ENV var or Config files.
Test code
```
from pyiceberg.catalog import load_catalog
catalog = load_catalog() # <- should load the default-catalog
catalog.list_namespaces()
```
Before PR
```
TypeError: load_catalog() missing 1 required positional argument: 'name'
```
After PR 
```
Above code should load the default catalog and not throw any error.
```
=> Python: Fix positional argument issue for load_catalog API

docs/spark-procedures.md
(unfiled) Noticed while running a `rewrite_data_files` job that there was an extra field in my output that's not present in the docs.
=> Add docs for failed_data_files_count

flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/sink/BucketPartitionKeySelector.java, flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/sink/BucketPartitioner.java, flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/sink/BucketPartitionerUtil.java, flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java, flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/HadoopCatalogExtension.java, flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/sink/TestBucketPartitionKeySelector.java, flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/sink/TestBucketPartitioner.java, flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/sink/TestBucketPartitionerFlinkIcebergSink.java, flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/sink/TestBucketPartitionerUtil.java, flink/v1.17/flink/src/main/java/org/apache/iceberg/flink/sink/BucketPartitionKeySelector.java, flink/v1.17/flink/src/main/java/org/apache/iceberg/flink/sink/BucketPartitioner.java, flink/v1.17/flink/src/main/java/org/apache/iceberg/flink/sink/BucketPartitionerUtil.java, flink/v1.17/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java, flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/HadoopCatalogExtension.java, flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/sink/TestBucketPartitionKeySelector.java, flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/sink/TestBucketPartitioner.java, flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/sink/TestBucketPartitionerFlinkIcebergSink.java, flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/sink/TestBucketPartitionerUtil.java
Backporting PR #7161 (Flink: Custom partitioner for bucket partitions) from 1.16 -> 1.15/1.17
The original PR was a 9-file change, ported to 1.15 and 1.17 so 18 affected files total on this one.
Verified contents (no difference/changes):
```
git diff --no-index  flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/ flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/
git diff --no-index  flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/ flink/v1.17/flink/src/main/java/org/apache/iceberg/flink/```
=> Flink: Backporting PR 7161 of custom partitioner for bucket partitions

aws/src/main/java/org/apache/iceberg/aws/s3/S3FileIOProperties.java, aws/src/main/java/org/apache/iceberg/aws/s3/S3OutputStream.java, aws/src/test/java/org/apache/iceberg/aws/s3/TestS3FileIOProperties.java
AWS: support config storage class for S3FileIO , to solve issue: https://github.com/apache/iceberg/issues/8153
=> AWS: support config storage class for S3FileIO

flink/v1.15/build.gradle, flink/v1.16/build.gradle, flink/v1.17/build.gradle, hive-runtime/build.gradle, spark/v3.1/build.gradle, spark/v3.2/build.gradle, spark/v3.3/build.gradle, spark/v3.4/build.gradle
This PR fixes the package names in the runtime builds so the Apache HTTP client is properly shaded. Currently the package name is actually the Maven coordinate for the Apache HTTP client, so it is not shaded. This results in a dependency conflict when running in some environments, like Azure Synapse Analytics.
This PR also updates the shading for `com.google` to be more specific to fix GCP support when using the runtimes. (This was already done for Spark 3.4.)
=> Fix shading of Apache HTTP and Google libraries in runtimes

aws/src/main/java/org/apache/iceberg/aws/s3/S3FileIO.java, dell/src/main/java/org/apache/iceberg/dell/ecs/EcsFileIO.java, gcp/src/main/java/org/apache/iceberg/gcp/gcs/GCSFileIO.java
The `FileIO` implementations currently attempt to initialize `HadoopMetricsContext` and log a stack trace if Hadoop is not on the classpath. The stack trace is not particularly useful and overly verbose to indicate this state, which can lead to confusion when viewing log output. This PR changes this to log the warning but without the stack trace.
This also moves the metrics initialization outside of the client supplier in `GCSFileIO`, consistent with the other FileIO implementations.
=> FileIO: Skip stack trace log for missing Hadoop

.github/workflows/python-ci.yml, python/Makefile
Poetry 1.6.0 broke our build: https://github.com/python-poetry/poetry/pull/8336
=> Python: Pin poetry to 1.5.1

core/src/main/java/org/apache/iceberg/BaseContentScanTask.java, core/src/main/java/org/apache/iceberg/BaseFile.java, core/src/main/java/org/apache/iceberg/BaseFileScanTask.java, core/src/main/java/org/apache/iceberg/OffsetsAwareSplitScanTaskIterator.java, core/src/main/java/org/apache/iceberg/util/ArrayUtil.java, core/src/test/java/org/apache/iceberg/util/TestArrayUtil.java, spark/v3.4/spark-extensions/src/jmh/java/org/apache/iceberg/spark/TaskGroupPlanningBenchmark.java
This PR optimizes how we handle offset splits during planning to reduce the amount of garbage and improve performance.
Results prior to this change:
```
Benchmark                                         Mode  Cnt  Score   Error  Units
TaskGroupPlanningBenchmark.planTaskGroups           ss   10  3.144 ± 0.064   s/op
TaskGroupPlanningBenchmark.planTaskGroups:·async    ss         NaN            ---
```
Results after this change:
```
Benchmark                                         Mode  Cnt  Score   Error  Units
TaskGroupPlanningBenchmark.planTaskGroups           ss   10  1.955 ± 0.027   s/op
TaskGroupPlanningBenchmark.planTaskGroups:·async    ss         NaN            ---
```
=> Core: Optimize offset splits handling

aws/src/main/java/org/apache/iceberg/aws/s3/signer/S3SignRequest.java, aws/src/main/java/org/apache/iceberg/aws/s3/signer/S3SignRequestParser.java, aws/src/main/resources/s3-signer-open-api.yaml, aws/src/test/java/org/apache/iceberg/aws/s3/signer/TestS3SignRequestParser.java
This change does the following:
1.) Updates the S3 Signer Spec to allow an optional string body in `S3SignRequest`
2.) Updates  `S3SignRequestParser` to support serialization and deserialization of the body.
Note: The body field will only be populated for requests which do not have the relevant information for signing in the URI itself (e..g DeleteObjectsRequest)
cc: @danielcweeks @nastra @jackye1995
=> AWS: Update S3 signer spec to allow an optional string body in S3SignRequest.

data/src/main/java/org/apache/iceberg/data/GenericReader.java, data/src/test/java/org/apache/iceberg/data/TestLocalScan.java
Problem:
Our application is using the following to read from the table
```
IcebergGenerics.ScanBuilder scanBuilder = IcebergGenerics.read(iceberg_table);
CloseableIterable<Record> records = scanBuilder.useSnapshot(snapshotId).build();
List<List<String>> output = new ArrayList<List<String>>();
for (Record record : records) {
```
however when I apply a case insensitive filter like
```
Expression filterExpr = ExpressionParser.fromJson(m_scanFilter);
scanBuilder = scanBuilder.where(filterExpr).caseInsensitive();
```
I get the below error despite setting the scan to caseInsensitive
```
2023-07-28 11:17:45.000208 EDT INFO: Scan of 'test.usethestats' using provided filter: '{"type":"eq","term":"V1","value":1}'
Records in test.usethestats :
Error processing the request: Cannot find field 'V1' in …
```
=> Java: Fix issue where the genericreader does not propagate case sensitivity

nessie/src/test/java/org/apache/iceberg/nessie/BaseTestIceberg.java, nessie/src/test/java/org/apache/iceberg/nessie/TestBranchVisibility.java, nessie/src/test/java/org/apache/iceberg/nessie/TestNessieIcebergClient.java
This commit modifies a few Nessie tests that were creating branches without explicitly specifying a target hash.
Nessie will soon forbid such situations, so we are proactively fixing all their occurrences.
=> Nessie: avoid creating branches without explicit hashes

core/src/main/java/org/apache/iceberg/DeleteFileIndex.java, spark/v3.4/spark-extensions/src/jmh/java/org/apache/iceberg/DeleteFileIndexBenchmark.java
This PR optimizes lookup performance in `DeleteFileIndex` when no useful bounds are present.
After this change:
```
Benchmark                                                                           Mode  Cnt           Score            Error   Units
DeleteFileIndexBenchmark.buildIndexAndLookup                                          ss   10           0.777 ±          0.761    s/op
DeleteFileIndexBenchmark.buildIndexAndLookup:·gc.alloc.rate                           ss   10        1147.705 ±        343.684  MB/sec
DeleteFileIndexBenchmark.buildIndexAndLookup:·gc.alloc.rate.norm                      ss   10  1453142312.800 ±     996440.801    B/op
DeleteFileIndexBenchmark.buildIndexAndLookup:·gc.count                                ss   10           6.000                   counts
``` …
=> Core: Optimize lookup in DeleteFileIndex without useful bounds

api/src/main/java/org/apache/iceberg/BaseScanTaskGroup.java, core/src/main/java/org/apache/iceberg/BaseCombinedScanTask.java, core/src/main/java/org/apache/iceberg/BaseFileScanTask.java
This PR optimizes computing user-facing state in data tasks to reduce the garbage and improve performance. 
It is related to the work in #8336.
=> Core: Optimize computing user-facing state in data task

core/src/main/java/org/apache/iceberg/DataTableScan.java
This PR ensures that data scans use a thread pool when there are more than 1 delete manifest, regardless of the number of data manifests
=> Core: Plan concurrently if there are multiple delete manifests

spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestChangelogTable.java, spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/SparkChangelogScan.java, spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/SparkScanBuilder.java, spark/v3.3/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestChangelogTable.java, spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/SparkChangelogScan.java, spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/SparkScanBuilder.java
Back-port of https://github.com/apache/iceberg/pull/8133 to `spark/v3.3` and `spark/v3.2`
=> Spark3.2, Spark3.3: Return empty changed rows when there are no snapshots between start time and end time

aws/src/main/java/org/apache/iceberg/aws/s3/signer/S3V4RestSignerClient.java, aws/src/test/java/org/apache/iceberg/aws/s3/signer/S3SignerServlet.java, aws/src/test/java/org/apache/iceberg/aws/s3/signer/TestS3RestSigner.java
Update S3V4RestSignerClient to send body for DeleteObjects (bulk delete) requests. Added a test which tests against a MinIO container.  Follow up to https://github.com/apache/iceberg/pull/8361
=> AWS: Update S3V4RestSignerClient to send body for DeleteObjects requests

python/pyiceberg/schema.py, python/tests/conftest.py, python/tests/io/test_pyarrow.py, python/tests/io/test_pyarrow_visitor.py, python/tests/test_schema.py
Fix #8386
Note: This pr only did validity checks when creating the Schema, not when it evolves, need to integrate with https://github.com/apache/iceberg/pull/8374.
=> Python: Check if identifier fields are valid

nessie/src/main/java/org/apache/iceberg/nessie/NessieTableOperations.java
`NessieTableOperations.doCommit()` wrongly assumes that _every_ exception thrown during a Nessie commit operation is a failure that requires the deletion of the newly written table-metadata. However, for exceptions like `j.l.InterruptedException` or HTTP timeout/error it is unclear whether the Nessie commit went through (or will go through), so deleting the table-metadata is wrong here.
This change updates the logic to only delete the table-metadata file if a `NessieReferenceConflictException` happened, when it is clear that the commit really failed.
=> Nessie: Fix possible table-metadata loss

docs/aws.md
Fixes: #8296 
In #7119, the default http client of AWS is switched from `url-connection` to `apache`. This PR update part of the doc to reflect the change.
cc: @singhpk234 @jackye1995 @stevenzwu 
Whenever you have a moment, could you kindly take a look at this PR? Thanks in advance!
=> Doc: Reflect Apache HttpClient as Default in AWS Integration Page

spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestDelete.java, spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMerge.java, spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestUpdate.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/source/SparkCopyOnWriteScan.java, spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/SparkTestBaseWithCatalog.java
Tests that cover concurrent modifications and row-level operations sporadically fail for me locally. The primary reason is that if table caching is disabled, the table would be eagerly refreshed in each scan. That means we can pick up concurrent changes even though they were done via another `Table` instance.
=> Spark 3.4: Clarify concurrent table modification error in copy-on-write operations

.asf.yaml
I need permissions to add partition stats related issues to project dashboard. https://github.com/apache/iceberg/projects/
Adding myself as collaborator since there is one empty slot and I would like to help other devs too.
cc: @flyrain, @Fokko, @nastra
=> Infra: Add `ajantha-bhat` as project collaborator

core/src/main/java/org/apache/iceberg/ManifestReader.java, core/src/test/java/org/apache/iceberg/TestScanPlanningAndReporting.java
This PR fixes skipped file counts in `ManifestReader` with deleted entries as discussed [here](https://github.com/apache/iceberg/pull/8123#discussion_r1275561171).
=> Core: Fix skipped file counts in ManifestReader with deleted entries

core/src/main/java/org/apache/iceberg/TableMetadata.java, core/src/test/java/org/apache/iceberg/catalog/CatalogTests.java
This fixes #8390, which was a problem from #8381. The REST catalog was failing standard catalog tests because it would reuse a sequence number when a concurrent commit that added a snapshot.
The fix is to allow a reused sequence number when the entire table state is replaced; that is, when the snapshot has no parent. That is the easiest fix because the replace table code does not currently rewrite snapshot metadata on retry. Rewriting snapshot metadata in that case isn't necessary because there is no previous data so reusing a sequence number is safe.
=> Core: Fix REST catalog tests with default v2 tables

docs/spark-structured-streaming.md
Promote usage of using `toTable(...)` instead of `.option("path", ...)` because I've found that the `.start()` might not inject the catalog functions when doing the query planning. If the catalog is missing, this causes issues when using partitioned tables, since the transforms are not available.
Details in https://github.com/apache/iceberg/issues/7226
=> Docs: Improve the Spark Structured Streaming jobs

core/src/main/java/org/apache/iceberg/MergingSnapshotProducer.java
Was going through the MergingSnapshotProducer code and noticed this typo
=> Core: Fix typo in startingSequenceNumber argument name

python/pyiceberg/catalog/__init__.py, python/pyiceberg/catalog/dynamodb.py, python/pyiceberg/catalog/glue.py, python/pyiceberg/catalog/hive.py, python/pyiceberg/catalog/noop.py, python/pyiceberg/catalog/rest.py, python/pyiceberg/catalog/sql.py, python/tests/catalog/test_base.py, python/tests/catalog/test_rest.py
Extend the API to allow registering tables, and implement it for the REST Catalog.
=> Python: Add register table

core/src/main/java/org/apache/iceberg/TableMetadata.java
This is a fix for table history when snapshots are lazily loaded (introduced by #6811).
When table metadata is returned with some snapshots suppressed, the next time table metadata is rebuilt results in losing history because the snapshot log is rewritten and removes any history that references unknown snapshots. The solution is to only clear history for unknown snapshots if there is a `RemoveSnapshot` change.
In addition, this PR adds a method to suppress snapshots that are not directly referenced by a ref for services that lazily load snapshots. This avoids the same history problem on the server side.
Closes #8096.
=> Core: Fix lazy snapshot loading history

.github/workflows/python-release.yml
Otherwise, the `sdist` version will be set to a non-RC when releasing an RC version:
Luckily this was caught before uploading.
=> Python: Set version prior `sdist` release

core/src/main/java/org/apache/iceberg/BaseSnapshot.java
I think this field got superseded by the one from [TableMetadata](https://github.com/apache/iceberg/blob/5bd7c649e4743a61eace5f52517db9b5b56ff8e6/core/src/main/java/org/apache/iceberg/TableMetadata.java#L51). Hence, this has no callers.
=> Core: Remove unused field from BaseSnapshot

nessie/src/main/java/org/apache/iceberg/nessie/NessieCatalog.java
Namespaces are not implicit anymore after Nessie 0.52.3 
https://projectnessie.org/blog/namespace-enforcement/
=> Nessie: Update NessieCatalog Javadoc about namespaces

api/src/main/java/org/apache/iceberg/exceptions/BadRequestException.java, api/src/main/java/org/apache/iceberg/exceptions/CleanableFailure.java, api/src/main/java/org/apache/iceberg/exceptions/ForbiddenException.java, api/src/main/java/org/apache/iceberg/exceptions/NoSuchIcebergTableException.java, api/src/main/java/org/apache/iceberg/exceptions/NoSuchNamespaceException.java, api/src/main/java/org/apache/iceberg/exceptions/NoSuchTableException.java, api/src/main/java/org/apache/iceberg/exceptions/NotAuthorizedException.java, api/src/main/java/org/apache/iceberg/exceptions/ServiceUnavailableException.java, api/src/main/java/org/apache/iceberg/exceptions/ValidationException.java, core/src/main/java/org/apache/iceberg/BaseTransaction.java, core/src/main/java/org/apache/iceberg/SnapshotProducer.java, core/src/main/java/org/apache/iceberg/TableOperations.java, core/src/main/java/org/apache/iceberg/rest/RESTTableOperations.java, core/src/test/java/org/apache/iceberg/catalog/CatalogTests.java, core/src/test/java/org/apache/iceberg/rest/TestRESTCatalog.java
Co-authored-by: Ryan Blue <blue@apache.org>
This is a continuation of https://github.com/apache/iceberg/pull/6399
Strict metadata cleanup will only trigger cleanups during commits when the commit fails with an exception which implements the marker interface CleanableFailure This will get used in SnapshotProducer and BaseTransaction and is useful for catalogs like the REST catalog where arbitrary HTTP client exceptions can be thrown (instead of the usual CommitStateUnknown exceptions).
=> API, Core: Add strict metadata cleanup to TableOperations

python/pyiceberg/utils/datetime.py
Change: Improved Readability and Alignment of Regex Patterns
In this change, I've updated the existing regular expressions where multiple \d characters appear sequentially. I've applied the {n} format to indicate a specific number of repetitions, making the patterns more readable. Furthermore, I've aligned these patterns consistently for better code clarity.
=> Python: Improved Readability and Alignment of Regex Patterns

python/pyiceberg/avro/decoder_basic.c, python/pyiceberg/avro/decoder_fast.pyx
Utilize libc.stdint for the definition of unsigned 64 bit integers.
Rename decoding/skip functions to not reference long.
Change the array.array type to use integers that are at least 64 bits in width.
Changes motiviated by differences in Windows builds
=> Python: Avro change to standardized integer types rather than relying on C compiler defined types

python/pyiceberg/io/pyarrow.py, python/tests/io/test_pyarrow.py
I have tested pyiceberg on our hdfs cluster, and this pr fixed some bugs.
Changed. 
1. Use optional parameters to create hdfs client, similar to  gcs's style.
2. Fix `PyArrowFileIO.parse_location` for hdfs path, which cannot be resolved by HadoopFileSystem.
Previous behavior：  parse_location("hdfs://127.0.0.1:9000/root/abc") ->  "hdfs", "127.0.0.1:9000/root/abc"
New behavior:       parse_location("hdfs://127.0.0.1:9000/root/abc") ->  "hdfs", "hdfs://127.0.0.1:9000/root/abc"
=> Python: Fix pyarrow hdfs support

python/dev/provision.py, python/tests/test_integration.py
Was going through the python codebase, noticed we didn't have any integ tests for use_ref so just added some simple integration tests which create a branch and tag, perform writes on a branch and then verifies the Python scan returns the expected records.
=> Python: Add integration tests for use_ref

python/pyproject.toml
Point to the Python-specific docs, instead of the general Java docs.
=> Python: Point to the Python docs

.github/workflows/python-release.yml, python/build-module.py, python/pyproject.toml, python/tests/conftest.py
This will run the Avro tests after building the wheel. Also refactored the `conftest.py` a bit so we can load the fixtures without pyarrow installed (this speeds up the tests quite a bit, since it will re-install it for every environment).
I've validated on my own fork: https://github.com/Fokko/incubator-iceberg/actions/runs/6133147394
=> Python: Add checks after building the wheels

.github/workflows/python-release.yml, python/pyproject.toml
We mark the test that don't have a specific marker (integration tests, s3, gcp, azure etc) with unmarked: https://github.com/apache/iceberg/blob/9ad9976551e8697d60ed7e0169ba0776ff1cffe5/python/tests/conftest.py#L96-L99
The marked was indeed missing, and I'm unsure why this works for the regular tests, but when validating the wheels we get an error: 
```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/tmp/tmp.Mofg6cKvZN/venv/lib/python3.8/site-packages/_pytest/main.py", line 271, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/tmp/tmp.Mofg6cKvZN/venv/lib/python3.8/site-packages/_pytest/main.py", line 324, in _main
INTERNALERROR>     config.hook.pytest_collection(session=session)
INTERNALERROR>   File …
```
=> Python: Add `unmarked` pytest marker

nessie/src/main/java/org/apache/iceberg/nessie/NessieIcebergClient.java
Small change covering the registration time commit message when the catalog is Nessie.
Fixes #8331
=> Nessie: Provide better commit message on table registation #8331

python/pyiceberg/io/pyarrow.py
It can be that certain build flags are turned off:
```
-DARROW_GCS=ON: Build Arrow with GCS support (requires the GCloud SDK for C++)
-DARROW_HDFS=ON: Arrow integration with libhdfs for accessing the Hadoop Filesystem
```
From: https://arrow.apache.org/docs/dev/developers/cpp/building.html#optional-components
This will cause an `ImportError` when importing `pyarrow.py`, while it can be that you don't want to use a missing FS. Therefore it is better to inline the imports
=> Python: Inline the Filesystem imports

python/pyiceberg/io/pyarrow.py, python/tests/io/test_pyarrow.py
https://github.com/apache/iceberg/pull/6010 didn't really fix it
Before:
```
python3 /tmp/benchmark.py
import: 0.175605 seconds
catalog: 0.060079 seconds
table: 0.245859 seconds
scan: 5.218688 seconds
Rows: 119890
```
After:
```
python3 /tmp/benchmark.py
import: 0.169811 seconds
catalog: 0.054512 seconds
table: 0.233786 seconds
scan: 2.165105 seconds
Rows: 119890
```
=> Python: Fix caching of FileSystem

.github/workflows/python-release.yml
We've moved from 20.04 to 22.04 but forgot to update the if-conditions below. This fixes it
=> Python: Change logic to use `startsWith`

arrow/src/main/java/org/apache/iceberg/arrow/vectorized/VectorHolder.java, arrow/src/main/java/org/apache/iceberg/arrow/vectorized/VectorizedArrowReader.java, arrow/src/main/java/org/apache/iceberg/arrow/vectorized/VectorizedReaderBuilder.java, core/src/main/java/org/apache/iceberg/MetadataColumns.java, spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/SparkPlanUtil.java, spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/SparkRowLevelOperationsTestBase.java, spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestDelete.java, spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMerge.java, spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestUpdate.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/data/vectorized/ColumnVectorBuilder.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/data/vectorized/ConstantColumnVector.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/source/SparkBatch.java, spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/source/TestParquetScan.java
Our merge-on-read queries can't benefit from vectorized reads because of `_partition` metadata column being projected for the write distribution. This PR adapts our Arrow and Spark 3.4 logic to support such structs.
=> Arrow, Spark 3.4: Support vectorized reads with struct constants

spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/source/SparkScanBuilder.java
close #8444
test sql:
```
CREATE TABLE wangzhen_test_iceberg_20230824_t3 (id bigint, name string)
USING iceberg;
INSERT INTO wangzhen_test_iceberg_20230824_t3 VALUES (4, 'd'),(5, 'e'),(6, 'f');
delete from wangzhen_test_iceberg_20230824_t3 where id = 5;
```
ui before:
after:
=> Spark 3.4: Set metricsReporter for CopyOnWriteScan/MergeOnReadScan/IncrementalAppendScan/ChangelogScan

LICENSE, core/src/main/java/org/apache/iceberg/rest/ExponentialHttpRequestRetryStrategy.java, core/src/main/java/org/apache/iceberg/rest/HTTPClient.java, core/src/test/java/org/apache/iceberg/rest/TestExponentialHttpRequestRetryStrategy.java, flink/v1.15/flink-runtime/LICENSE, flink/v1.16/flink-runtime/LICENSE, flink/v1.17/flink-runtime/LICENSE, hive-runtime/LICENSE, spark/v3.1/spark-runtime/LICENSE, spark/v3.2/spark-runtime/LICENSE, spark/v3.3/spark-runtime/LICENSE, spark/v3.4/spark-runtime/LICENSE
This adds a new retry strategy, allowing exponential backoff and also allows to adjust the number of retries for the `DefaultHttpRequestRetryStrategy`
=> Core: Default to exponential retry strategy in REST client

docs/branching-and-tagging.md, docs/spark-ddl.md, docs/spark-writes.md
* Fix `CREATE BRANCH` syntax in *Branching and Tagging* part and Spark DDL
* Fix broken link in *Writing to Branches* section in Spark Writes
There are several syntax descriptions that don't follow the current design in the doc.
The current doc shows the CREATE BRANCH in Branching and Tagging part like;
```sql
-- Create a branch "test-branch" which will be retained for 7 days along with the  latest 2 snapshots
ALTER TABLE prod.db.table CREATE BRANCH test-branch RETAIN 7 DAYS WITH RETENTION 2 SNAPSHOTS
```
If you run the query, the query fails with the following error;
```scala
scala> spark.sql("ALTER TABLE catalog.db.tbl CREATE BRANCH branch3 RETAIN 2 DAYS WITH RETENTION 3 SNAPSHOTS")
org.apache.spark.sql.catalyst.parser.extensions.IcebergParseException:
no viable alternative at input …
```
=> Docs: Fix CREATE BRANCH syntax and broken link in Writing to Branches section

spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/procedures/ExpireSnapshotsProcedure.java, spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/procedures/ExpireSnapshotsProcedure.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/procedures/ExpireSnapshotsProcedure.java
This just fixes a minor spacing issue in a warn log in ExpireSnapshotsProcedure, something I noticed when looking at logs.
currently the log line looks like "Thistable is currently using ...." instead of "This table is currently using"
=> Spark: Fix spacing in warn log in ExpireSnapshotsProcedure

spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRewriteDataFilesProcedure.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/procedures/RewriteDataFilesProcedure.java, spark/v3.4/spark/src/main/scala/org/apache/spark/sql/execution/datasources/SparkExpressionConverter.scala, spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteDataFilesAction.java
Inspired by #7886, try to push down v2 filters in where clause used by both rewriteDataFiles and rewritePositionDeleteFiles
- make sure the bucket transform works in the action
- Make sure the conversion works in the procedure
CC @RussellSpitzer @aokolnychyi @ConeyLiu @rdblue 
Expect following query to work after this change
```scala
spark.sql(
"""
CALL iceberg.system.rewrite_data_files(
table => 'foo.bar', 
where => 'iceberg.system.bucket(4, url) = 0')
"""
)
```
=> Spark 3.4: Push down system functions by V2 filters for rewriting DataFiles and PositionDeleteFiles

arrow/src/main/java/org/apache/iceberg/arrow/vectorized/VectorHolder.java, arrow/src/main/java/org/apache/iceberg/arrow/vectorized/VectorizedArrowReader.java
As a follow-up to #8466, this PR propagates correct field info while reading metadata columns.
=> Arrow: Propagate correct field info while reading metadata columns

core/src/main/java/org/apache/iceberg/BaseMetadataTable.java, core/src/main/java/org/apache/iceberg/PositionDeletesTable.java, spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/source/TestCompressionSettings.java
Address the comment https://github.com/apache/iceberg/pull/8313#discussion_r1295749631
=> Core, Spark 3.4:  Write properties of `PositionDeletesTable` should respect ones of `BaseTable`

spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestCompressionSettings.java
After https://github.com/apache/iceberg/pull/8428, `RewritePositionDeletesAction` can use the write properties to rewrite the data. So we should remove the workaround of the test case.
=> Spark 3.5: Fix the test case of `TestCompresssionSettings`

parquet/src/main/java/org/apache/iceberg/parquet/ParquetUtil.java, parquet/src/test/java/org/apache/iceberg/parquet/TestParquet.java
Trino Iceberg connector faced a silent correctness issue because of incorrect lower/upper bounds. 
The existing logic expects 2 state (null or non-empty), but there's another condition like: 
```java
@Override
public String toString() {
if (this.hasNonNullValue()) {
if (isNumNullsSet()) {
return String.format("min: %s, max: %s, num_nulls: %d", minAsString(), maxAsString(), this.getNumNulls());
} else {
return String.format("min: %s, max: %s, num_nulls not defined", minAsString(), maxAsString());
}
} else if (!this.isEmpty())
return String.format("num_nulls: %d, min/max not defined", this.getNumNulls());
else
return "no stats for this column";
}
```
https://github.com/apache/parquet-mr/blob/9b5a962df3007009a227ef421600197531f970a5/parquet-column/src/main/java/org/apache/parquet/column/stati …
=> Fix incorrect metrics in ParquetUtil

nessie/src/main/java/org/apache/iceberg/nessie/NessieCatalog.java, nessie/src/main/java/org/apache/iceberg/nessie/NessieTableOperations.java, nessie/src/main/java/org/apache/iceberg/nessie/NessieUtil.java, nessie/src/test/java/org/apache/iceberg/nessie/BaseTestIceberg.java, nessie/src/test/java/org/apache/iceberg/nessie/TestNessieTable.java
Introduce a new config property specific to Nessie to allow advanced users, who are aware of implications (see code comments), to use standard Iceberg GC tools in Nessie Catalogs.
The default behaviour is unchanged, that is Iceberg GC is disabled in Nessie Catalogs.
CC: @snazy @ajantha-bhat @nastra
=> Nessie: Permit Iceberg GC via explicit property overrides

spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/SparkValueConverter.java
=> Spark 3.5: Remove date logic with `anyToMicros`

spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMerge.java
This PR adds tests for WHEN NOT MATCHED BY SOURCE clauses, supported in Spark 3.5.
This resolves #8276. There are more tests in Spark itself, it is just a sanity check mostly.
=> Spark 3.5: Add tests for WHEN NOT MATCHED BY SOURCE clauses

build.gradle, flink/v1.15/build.gradle, flink/v1.16/build.gradle, flink/v1.17/build.gradle, hive3/build.gradle, mr/build.gradle, spark/v3.1/build.gradle, spark/v3.2/build.gradle, spark/v3.3/build.gradle, spark/v3.4/build.gradle, spark/v3.5/build.gradle
For some reason, Gradle has issues to detect the maven classifier properly in a consuming project from Gradle module metadata.
The issue has been reported in
https://youtrack.jetbrains.com/issue/IDEA-327421/IJ-fails-to-import-Gradle-project-with-dependency-with-classifier and in https://github.com/gradle/gradle/issues/15756.
https://youtrack.jetbrains.com/issue/IDEA-327421/IJ-fails-to-import-Gradle-project-with-dependency-with-classifier reported a workaround that ignores Gradle metadata when using Iceberg artifacts.
I talked to @snazy and https://github.com/projectnessie/nessie/blob/main/settings.gradle.kts#L46-L57 shows how he worked around the issue it when consuming the latest Iceberg snapshot release.
However, I don't think we want to go down that route, because every consumer of an …
=> Build: Fix Gradle issue for consuming projects with Maven classifier

spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRewriteDataFilesProcedure.java, spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRewritePositionDeleteFilesProcedure.java, spark/v3.4/spark/src/main/scala/org/apache/spark/sql/execution/datasources/SparkExpressionConverter.scala
For rewrite procedure, we should throw better exceptions when the filter condition can't be pushed down or can't convert to Iceberg. For example:
```scala
scala> spark.sql("call local.system.rewrite_data_files(table => 'db.test_rewrite', where => 'substr(data, 2) = \"fo\"')").show()
java.util.NoSuchElementException: None.get
at scala.None$.get(Option.scala:529)
at scala.None$.get(Option.scala:527)
at org.apache.spark.sql.execution.datasources.SparkExpressionConverter$.convertToIcebergExpression(SparkExpressionConverter.scala:38)
at org.apache.spark.sql.execution.datasources.SparkExpressionConverter.convertToIcebergExpression(SparkExpressionConverter.scala)
at org.apache.iceberg.spark.procedures.RewriteDataFilesProcedure.checkAndApplyFilter(RewriteDataFilesProcedure.java:137)
at …
```
=> Spark 3.4: Rewrite procedure throw better exception when filter expression cannot translate

core/src/main/java/org/apache/iceberg/TableOperations.java, core/src/main/java/org/apache/iceberg/rest/RESTTableOperations.java
This  change enables strict metadata cleanup by default for the 1.4.0 release (discussed in the 09/20 community sync).
=> Core: Enable strict metadata cleanup by default

python/pyiceberg/catalog/sql.py, python/tests/catalog/test_sql.py
As a follow-up to https://github.com/apache/iceberg/pull/8465 - this PR implements `register_table` for the SQL Catalog
=> Python: Register table functionality for SQL Catalog

core/src/main/java/org/apache/iceberg/MetricsUtil.java, core/src/main/java/org/apache/iceberg/deletes/PositionDeleteWriter.java, data/src/test/java/org/apache/iceberg/io/TestFileWriterFactory.java
This PR drops count metrics for the file and position columns in position delete files. This allows us to reduce the size of persisted delete metadata and to speed up distributed planning where the stats are serialized. Such stats are redundant as the spec does not permit null values in those columns and we have `recordCount` if the number of records must be known. 
We still keep counts for the data columns if deleted rows are persisted. We also keep column sizes for the file and position columns.
=> Core: Don't persist counts for paths and positions in position delete files

spark/v3.1/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRewriteDataFilesProcedure.java, spark/v3.1/spark/src/main/scala/org/apache/spark/sql/execution/datasources/SparkExpressionConverter.scala, spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRewriteDataFilesProcedure.java, spark/v3.2/spark/src/main/scala/org/apache/spark/sql/execution/datasources/SparkExpressionConverter.scala, spark/v3.3/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRewriteDataFilesProcedure.java, spark/v3.3/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRewritePositionDeleteFilesProcedure.java, spark/v3.3/spark/src/main/scala/org/apache/spark/sql/execution/datasources/SparkExpressionConverter.scala, spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRewriteDataFilesProcedure.java, spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRewritePositionDeleteFilesProcedure.java, spark/v3.5/spark/src/main/scala/org/apache/spark/sql/execution/datasources/SparkExpressionConverter.scala
This ports #8394 to Spark 3.5/3.3/3.2/3.1
Changes for Spark 3.5 is the same as #8394.
Changes for Spark 3.3/3.2/3.1 have slight differences since they use the Spark V1 filter.
=> Spark 3.1, 3.2, 3.3, 3.5: Throw better exception when filter expression cannot be translated in Rewrite procedure

format/spec.md
The Java implementation defines this field as `optional` [here](https://github.com/apache/iceberg/blob/master/api/src/main/java/org/apache/iceberg/ManifestFile.java#L51-L53). Same is done in Python [here](https://github.com/apache/iceberg/blob/master/python/pyiceberg/manifest.py#L275)
=> Spec: Mark added_snapshot_id as optional for V1

core/src/main/java/org/apache/iceberg/BaseTable.java, core/src/test/java/org/apache/iceberg/ScanPlanningAndReportingTestBase.java, core/src/test/java/org/apache/iceberg/TestCommitReporting.java, core/src/test/java/org/apache/iceberg/TestLocalScanPlanningAndReporting.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/SparkDistributedDataScan.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/TestSparkDistributedDataScanReporting.java
This PR fixes metrics reporting in distributed planning:
- `SparkDistributedDataScan` picks up the base reporter configured for the table.
- `SparkDistributedDataScan` correctly computes the number of skipped data and delete files.
=> Spark 3.5: Fix metrics reporting in distributed planning

core/src/main/java/org/apache/iceberg/TableMetadata.java, core/src/main/java/org/apache/iceberg/TableProperties.java, core/src/test/java/org/apache/iceberg/TestTableMetadata.java, flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/TestFlinkCatalogTable.java, flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/sink/TestCompressionSettings.java, flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/TestFlinkCatalogTable.java, flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/sink/TestCompressionSettings.java, flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/TestFlinkCatalogTable.java, flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/sink/TestCompressionSettings.java, hive-metastore/src/test/java/org/apache/iceberg/hive/TestHiveCatalog.java, mr/src/test/java/org/apache/iceberg/mr/TestCatalogs.java, mr/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerNoScan.java, spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/source/TestMetadataTableReadableMetrics.java, spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/source/TestMetadataTableReadableMetrics.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestMetadataTableReadableMetrics.java
This PR is an updated and rebased version of #8299.
=> Core: Default to zstd compression for Parquet in new tables

api/src/main/java/org/apache/iceberg/DeleteFiles.java, core/src/main/java/org/apache/iceberg/StreamingDelete.java, core/src/test/java/org/apache/iceberg/TestDeleteFiles.java
Currently there is no validation on delete files API for verifying that the file to be deleted actually exists prior to the commit. This can cause unexpected behavior, for example:
1.) Rewrite Data files compacts FILE_A + some delete files
2.) Concurrently a DeleteFiles call was done for FILE_A.
3.) Deletion gets retried after 1 completes. At the point it retries, FILE_A no longer exists due to the compaction so the deletion is a no-op.
From a user's perspective when they go and query the table after 3, they'll still see the contents of FILE_A, even though the wouldn't expect it since they received a successful delete of FILE_A.
This change currently adds a new validation API as opposed to changing the behavior to always do strict validation for purpose of backwards compatibility. I …
=> Core: Add a validation API to DeleteFiles which validates files exist prior to attempting to deletion.

python/.pre-commit-config.yaml
D106: Missing docstring in public nested class. No linter violations, just remove from the ignore list.
[#7776](https://github.com/apache/iceberg/issues/7776)
=> Python: Remove D106 Docstring Issue

python/pyiceberg/table/__init__.py, python/tests/table/test_init.py
This PR add `__repr__` method to the `Table` class.
=> Python: Add __repr__ method to Table class

python/pyiceberg/io/pyarrow.py, python/tests/io/test_pyarrow.py
The current pyarrow module creates FS from hdfs.host and hdfs.port in the catalog configuration.
```
catalog:
prod:
hdfs.host: xxxx
hdfs.port: xxx
```
However, when the real hdfs path has a anther netloc, it will throw Wrong FS execption. 
```
java.lang.IllegalArgumentException:
Wrong FS: hdfs://xxxx expected: hdfs://yyyy
```
This PR makes two changes:
1) Create FS from uri when netloc is not empty.
2) Cache FS by the key of <scheme, netloc>
=> Python: Create HadoopFileSystem from netloc

core/src/main/java/org/apache/iceberg/SchemaUpdate.java, core/src/test/java/org/apache/iceberg/TestSchemaUpdate.java
currently, users are not allowed to do the following operation which is valid use case when we want to change a column type and don't care about old data anymore
```java
// tableSchema as below
//        new Schema(
//            required(1, "id", Types.LongType.get()),
//            required(2, "data", Types.StringType.get()),
//            required(3, "data_1", Types.StringType.get()));
// id is deleted and added back with a different type and then we want to move this new column after an existing column "data"
new SchemaUpdate(schema, 3)
.allowIncompatibleChanges()
.deleteColumn("id")
.addRequiredColumn("id", Types.IntegerType.get())
.moveAfter("id", "data")
.apply();
```
(of course we can add/delete columns, commit and then move columns and commit again, but this workaround brings two …
=> Core: Move a column with the same name as a deleted column

spark/v3.1/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestAlterTablePartitionFields.java, spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/Spark3Util.java, spark/v3.1/spark/src/test/java/org/apache/iceberg/spark/sql/TestCreateTable.java, spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestAlterTablePartitionFields.java, spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/Spark3Util.java, spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/sql/TestCreateTable.java, spark/v3.3/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestAlterTablePartitionFields.java, spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/Spark3Util.java, spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/sql/TestCreateTable.java, spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestAlterTablePartitionFields.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/Spark3Util.java, spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/sql/TestCreateTable.java, spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestAlterTablePartitionFields.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/Spark3Util.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/sql/TestCreateTable.java
Given the spec for the time transform functions, this PR adds the singular (instead of plural) names of the transform functions.  
The spec specifies `year, month, hour, day`, but previously Spark only supported the plural version of these words (`years, months, etc`).
Hopefully this saves someone else a few cycles of debugging :)
=> Spark: Correct partition transform functions to match spec.md

open-api/requirements.txt
The new 2.4.0 release of Pydantic breaks the Python code generator.
=> Open-API: Make the CI happy

spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/SparkCatalog.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/SparkReadConf.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/SparkReadOptions.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/SparkSQLProperties.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/SparkUtil.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/SparkWriteConf.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/SparkWriteOptions.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/sql/TestTimestampWithoutZone.java
This PR removes legacy configs for timestamps without zone. Our 3.5 jar has never been released and 3.4 introduced the deprecation so it seems safe to remove it completely in 3.5.
=> Spark 3.5: Remove legacy configs for timestamps without zone

spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestCreateChangelogViewProcedure.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/procedures/CreateChangelogViewProcedure.java
The flag is deprecated for existing Spark version, and removed for the new Spark version(3.5)
=> Spark 3.5: Drop the `remove_carryovers` flag for CDC view creation

spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRequiredDistributionAndOrdering.java, spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestWriteAborts.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/SparkWriteConf.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/source/SparkPositionDeltaWrite.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/source/SparkWrite.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/TestSparkDistributionAndOrderingUtil.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestFilteredScan.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestPartitionValues.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestRequiredDistributionAndOrdering.java
This PR enables fanout writers for **_unsorted_** tables by default to speed up writes. This should be safe as we distribute the incoming records using the transforms for all operations in partitioned tables (unless configured otherwise). The ability to skip local sorts reduces the probability of expensive spills. This becomes critical given that we consider requesting larger advisory partition sizes.
=> Spark 3.5: Use fanout writers for unsorted tables by default

flink/v1.17/flink/src/main/java/org/apache/iceberg/flink/FlinkCatalog.java, flink/v1.17/flink/src/main/java/org/apache/iceberg/flink/FlinkSchemaUtil.java, flink/v1.17/flink/src/main/java/org/apache/iceberg/flink/FlinkTypeToType.java, flink/v1.17/flink/src/main/java/org/apache/iceberg/flink/util/FlinkAlterTableUtil.java, flink/v1.17/flink/src/main/java/org/apache/iceberg/flink/util/FlinkCompatibilityUtil.java, flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/TestFlinkCatalogTable.java
Resolves https://github.com/apache/iceberg/issues/7312
=> Flink 1.17: Support alter table column

core/src/main/java/org/apache/iceberg/TableProperties.java, spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestDelete.java, spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMerge.java, spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestUpdate.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/SparkCompressionUtil.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/SparkConfParser.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/SparkSQLProperties.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/SparkWriteConf.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/SparkWriteOptions.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/SparkWriteRequirements.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/SparkWriteUtil.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/source/SparkPositionDeltaWrite.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/source/SparkWrite.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/TestSparkCompressionUtil.java
This PR increases the default advisory partition size for writes and allows users to control it explicitly.
By default, we will try to write 128 MB data files and 32 MB position delete files. In the future, we may make this configurable but it should be a reasonable start, especially given that users can set this manually now.
=> Spark 3.5: Increase default advisory partition size for writes

.palantir/revapi.yml, core/src/main/java/org/apache/iceberg/TableProperties.java
This PR removes no longer used MERGE cardinality check table properties.
=> Core: Drop unused MERGE cardinality check table properties

spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/SparkWriteConf.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/TestSparkWriteConf.java
This PR adjusts the requested advisory partition size to be at least as big as the configured built-in Spark value. This is needed to avoid breaking pipelines where this property was configured big enough manually.
=> Spark 3.5: Requested advisory partition size must respect Spark config

core/src/main/java/org/apache/iceberg/actions/BinPackStrategy.java, core/src/main/java/org/apache/iceberg/actions/RewriteStrategy.java, core/src/main/java/org/apache/iceberg/actions/SortStrategy.java, docs/nessie.md, docs/spark-writes.md
Follow up for https://github.com/apache/iceberg/pull/8661
=> Docs: Remove spark-3.1 mention

spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/SparkV2Filters.java, spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/sql/TestFilterPushDown.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/SparkV2Filters.java, spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/sql/TestFilterPushDown.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/SparkV2Filters.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/sql/TestFilterPushDown.java
This PR fixes Decimal value conversion in V2 Spark filters that are being used by default now.
=> Spark: Fix Decimal value conversion in V2 filters

aws/src/main/java/org/apache/iceberg/aws/AwsClientFactories.java, aws/src/main/java/org/apache/iceberg/aws/AwsClientProperties.java, aws/src/main/java/org/apache/iceberg/aws/AwsProperties.java, aws/src/test/java/org/apache/iceberg/aws/AwsClientPropertiesTest.java
Fixes https://github.com/apache/iceberg/issues/8601
It replaces `DefaultCredentialsProvider.create()` with `DefaultCredentialsProvider.builder().build()` to avoid sharing the same credentials provider across multiple clients.
This PR changes 3 places calling `DefaultCredentialsProvider.create()`, and adds one test for `AwsCredentialsProvider.credentialsProvider`. The other two are deprecated so no tests were added for them.
=> AWS: avoid static global credentials provider which doesn't play well with lifecycle management

open-api/rest-catalog-open-api.yaml
Add a new namespaceExists API which are HEAD http call to namespace resource, it's similar to tableExists API already defined in open-api spec.
This is spec change only as I dont think we need to change any part of the code in rest package, since both [tableExists](https://github.com/apache/iceberg/blob/cf32bdead13815daf26c9feceebc6cd606a7bab8/api/src/main/java/org/apache/iceberg/catalog/SessionCatalog.java#L180-L187) and [namespaceExists](https://github.com/apache/iceberg/blob/cf32bdead13815daf26c9feceebc6cd606a7bab8/api/src/main/java/org/apache/iceberg/catalog/SessionCatalog.java#L356-L363) and defined as default method in SessionCatalog interface.
both `make lint && make generate` are happy
Can you guys take a look? @Fokko @nastra @rdblue
CC @haizhou-zhao
=> open-api: Add namespaceExist API

docs/spark-procedures.md
added missing docs for procedures `publish_changes`. 
As per today this is the only procedure missing from doc. 
Fixes #1601
=> Docs: Document publish_changes procedure

api/src/main/java/org/apache/iceberg/ManifestFile.java, core/src/test/java/org/apache/iceberg/TestManifestListVersions.java
When building the Manifest mappers for Python, @rdblue  noticed that the `added_data_files_count` should be `added_files_count` according to the spec. 
However, this field is written in Java as `added_data_files_count` to Avro by the Java implementation:  
https://github.com/apache/iceberg/blob/8104769f81ba79338fd3c94d5bd9267f22d31ed7/api/src/main/java/org/apache/iceberg/ManifestFile.java#L44-L49
Luckily this doesn't affect the reading/writing because it is position based.
However, it is confusing. I think we should resolve this. We could either do this by changing the Java impl, which probably works, but we could also change the spec. I know that this isn't something lightweight, but we could take it into consideration.
I think we should also update the references in the code to …
=> Spec: Inconsistency around files_count

format/spec.md
This reverts commit f7a7eb2c10cb4a9b6b3ea5bfdfc5d085be8b9c31.
This should stay required.
=> Revert "Spec: Mark added_snapshot_id as optional (#8600)"

build.gradle
This PR updates our base version in revapi checks after the 1.4.0 release.
=> Build: Let revapi compare against 1.4.0

spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/SerializableTableWithSize.java, spark/v3.2/spark/src/test/java/org/apache/iceberg/TestTableSerialization.java, spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/SerializableTableWithSize.java, spark/v3.3/spark/src/test/java/org/apache/iceberg/TestTableSerialization.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/source/SerializableTableWithSize.java, spark/v3.4/spark/src/test/java/org/apache/iceberg/TestTableSerialization.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/source/SerializableTableWithSize.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/TestTableSerialization.java
This PR implements `AutoCloseable` in `SerializableTableWithSize` to make sure resources used by copies of the table on executors are released correctly.
See `freeMemoryEntry` in `MemoryStore`.
```
def freeMemoryEntry[T <: MemoryEntry[_]](entry: T): Unit = {
entry match {
case SerializedMemoryEntry(buffer, _, _) => buffer.dispose()
case e: DeserializedMemoryEntry[_] => e.value.foreach {
case o: AutoCloseable =>
try {
o.close()
} catch {
case NonFatal(e) =>
logWarning("Fail to close a memory entry", e)
}
case _ =>
}
}
}
```
=> Spark: Clean up FileIO instances on executors

nessie/src/main/java/org/apache/iceberg/nessie/NessieCatalog.java
After https://github.com/apache/iceberg/pull/8607, 
`createNessieClientBuilder` is not used anymore in the code. So, it should be removed.
=> Nessie: Remove dead code in NessieCatalog

open-api/rest-catalog-open-api.yaml
OpenAPI schema fails code generation on row 1173:
```
- rest-catalog-open-api.yaml:1173:24 -> uniqueItems: unexpected field for type "object"
```
As far as I can tell `uniqueItems` is not valid for objects, so I assume this is a mistake.
=> API: Fix REST Catalog schema error: uniqueItems is not valid on type object

core/src/main/java/org/apache/iceberg/actions/BaseDeleteOrphanFiles.java, core/src/main/java/org/apache/iceberg/actions/BaseDeleteReachableFiles.java, core/src/main/java/org/apache/iceberg/actions/BaseExpireSnapshots.java, core/src/main/java/org/apache/iceberg/actions/BaseMigrateTable.java, core/src/main/java/org/apache/iceberg/actions/BaseRewriteDataFiles.java, core/src/main/java/org/apache/iceberg/actions/BaseRewriteManifests.java, core/src/main/java/org/apache/iceberg/actions/BaseRewritePositionalDeleteFiles.java, core/src/main/java/org/apache/iceberg/actions/BaseSnapshotTable.java, core/src/main/java/org/apache/iceberg/view/BaseViewHistoryEntry.java, core/src/main/java/org/apache/iceberg/view/BaseViewVersion.java, core/src/main/java/org/apache/iceberg/view/ViewMetadata.java
Now that https://github.com/immutables/immutables/pull/1474 has been fixed and was shipped as part of Immutables [2.10.0](https://github.com/immutables/immutables/releases), we can switch to using the visibility string to fix the below compiler warnings for consuming projects:
```
warning: unknown enum constant ImplementationVisibility.PACKAGE
reason: class file for org.immutables.value.Value$Style$ImplementationVisibility not found
warning: unknown enum constant ImplementationVisibility.PACKAGE
reason: class file for org.immutables.value.Value$Style$ImplementationVisibility not found
warning: unknown enum constant ImplementationVisibility.PACKAGE
reason: class file for org.immutables.value.Value$Style$ImplementationVisibility not found
warning: unknown enum constant …
```
=> Core: Use visibility string instead of enum for Immutable visibility

core/src/jmh/java/org/apache/iceberg/metrics/CountersBenchmark.java, flink/v1.17/flink/src/main/java/org/apache/iceberg/flink/sink/shuffle/DataStatisticsCoordinator.java
There were few warnings with `./gradlew clean build -x test -x integrationTest` . 
this change is to make build **green**.
=> Build: Fix minor compilation warnings

core/src/main/java/org/apache/iceberg/MetadataTableUtils.java, docs/spark-queries.md
added missing metadata tables  `all_delete_files` `all_entries` `entries` `position_deletes` 
Fixes #757
=> Docs: Document all metadata tables.

.github/dependabot.yml
Close #8764 
It seems it's not possible to set `open-pull-requests-limit` to unlimited value (default is 5, and 0 means disabling it).
In this change, I propose to open up to 50 PRs by dependabot
=> Build: increase open-pull-requests-limit to 50

open-api/rest-catalog-open-api.py, open-api/rest-catalog-open-api.yaml
Added a description based on feedback from https://github.com/apache/iceberg/commit/dd26f3630954e69c584faa06c9395f77d49337b1#r129277242
=> OpenAPI: Add description for AssignUUID

nessie/src/main/java/org/apache/iceberg/nessie/NessieIcebergClient.java, nessie/src/main/java/org/apache/iceberg/nessie/NessieTableOperations.java
`expectedContent` for put operation is not required for the latest Nessie versions.  Hence the constructor was deprecated from https://github.com/projectnessie/nessie/pull/6438. 
This PR updated the deprecated API usage with the alternative. 
Also introduces a simple interface for commit.
=> Nessie: Remove deprecated usage of Operation.Put.of()

.github/workflows/api-binary-compatibility.yml, .github/workflows/delta-conversion-ci.yml, .github/workflows/flink-ci.yml, .github/workflows/hive-ci.yml, .github/workflows/java-ci.yml, .github/workflows/open-api.yml, .github/workflows/spark-ci.yml, README.md, build.gradle, docs/flink-writes.md, docs/metrics-reporting.md
This PR rename resources using `master` to `main`. This PR should be merged only when the renaming has been done by Apache INRA.
=> Rename master branch to main

aws/src/integration/java/org/apache/iceberg/aws/glue/TestGlueCatalogCommitFailure.java, azure/src/test/java/org/apache/iceberg/azure/adlsv2/ADLSFileIOTest.java, gcp/src/test/java/org/apache/iceberg/gcp/gcs/GCSFileIOTest.java, hive-metastore/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java, snowflake/src/test/java/org/apache/iceberg/snowflake/JdbcSnowflakeClientTest.java, spark/v3.5/spark/src/jmh/java/org/apache/iceberg/spark/action/IcebergSortCompactionBenchmark.java
Fixing few xlint related warnings. 
examples:
> Note: /home/runner/work/iceberg/iceberg/nessie/src/main/java/org/apache/iceberg/nessie/NessieIcebergClient.java uses or overrides a deprecated API.
> 
> Note: Recompile with -Xlint:deprecation for details.
> Note: /Users/naveenkumar/Desktop/dremio_work/git/forked/iceberg/gcp/src/test/java/org/apache/iceberg/gcp/gcs/GCSFileIOTest.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Ref from one of the [build](https://github.com/apache/iceberg/actions/runs/6465826656/job/17552687522)
Before:
After:
=> Build: Fix compiler warnings

aliyun/src/test/java/org/apache/iceberg/aliyun/oss/mock/AliyunOSSMockLocalStore.java, api/src/main/java/org/apache/iceberg/expressions/ResidualEvaluator.java, aws/src/integration/java/org/apache/iceberg/aws/glue/TestGlueCatalogNamespace.java, data/src/test/java/org/apache/iceberg/data/TestMetricsRowGroupFilter.java, data/src/test/java/org/apache/iceberg/data/TestMetricsRowGroupFilterTypes.java, delta-lake/src/main/java/org/apache/iceberg/delta/BaseSnapshotDeltaLakeTableAction.java, flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java, flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java, flink/v1.17/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java, flink/v1.17/flink/src/main/java/org/apache/iceberg/flink/sink/shuffle/DataStatisticsCoordinator.java, hive3/src/main/java/org/apache/hadoop/hive/ql/io/orc/OrcSplit.java, mr/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergOutputCommitter.java, parquet/src/main/java/org/apache/iceberg/parquet/ParquetBloomRowGroupFilter.java
=> Flink, Aliyun, MR, Delta-lake, Hive3, Parquet, Data: replaced .size() > 0 with isEmpty()

spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/FileScanTaskSetManager.java, spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/actions/RewriteDataFilesSparkAction.java, spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/SparkBatch.java, spark/v3.2/spark/src/test/java/org/apache/iceberg/TestScanTaskSerialization.java, spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/actions/TestCreateActions.java, spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/ScanTaskSetManager.java, spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/actions/SparkBinPackPositionDeletesRewriter.java, spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/actions/SparkZOrderDataRewriter.java, spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/SparkBatch.java, spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/SparkPositionDeletesRewriteBuilder.java, spark/v3.3/spark/src/test/java/org/apache/iceberg/TestScanTaskSerialization.java, spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/actions/TestCreateActions.java, spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewritePositionDeleteFilesAction.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/ScanTaskSetManager.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/actions/SparkBinPackPositionDeletesRewriter.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/actions/SparkZOrderDataRewriter.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/source/SparkPositionDeletesRewriteBuilder.java, spark/v3.4/spark/src/test/java/org/apache/iceberg/TestScanTaskSerialization.java, spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/actions/TestCreateActions.java, spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewritePositionDeleteFilesAction.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/ScanTaskSetManager.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/actions/SparkBinPackPositionDeletesRewriter.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/actions/SparkZOrderDataRewriter.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/source/SparkPositionDeletesRewriteBuilder.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/TestScanTaskSerialization.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/actions/TestCreateActions.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewritePositionDeleteFilesAction.java
From issue #8810.
Replaced .`size() > 0` with `isEmpty()` where was possible inside spark module.
=> Spark: spark/*: replaced .size() > 0 with isEmpty()

flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/sink/shuffle/AggregatedStatistics.java, flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/sink/shuffle/AggregatedStatisticsTracker.java, flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/sink/shuffle/DataStatisticsCoordinator.java, flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/sink/shuffle/DataStatisticsCoordinatorProvider.java, flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/sink/shuffle/DataStatisticsOperator.java, flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/sink/shuffle/DataStatisticsOrRecord.java, flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/sink/shuffle/DataStatisticsUtil.java, flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/sink/shuffle/TestAggregatedStatistics.java, flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/sink/shuffle/TestAggregatedStatisticsTracker.java, flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/sink/shuffle/TestDataStatisticsCoordinator.java, flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/sink/shuffle/TestDataStatisticsCoordinatorProvider.java, flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/sink/shuffle/TestDataStatisticsOperator.java
it is a clean back port.
confirmed git diff
```
➜  git diff --no-index  flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/sink/shuffle  flink/v1.17/flink/src/main/java/org/apache/iceberg/flink/sink/shuffle
➜  git diff --no-index flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/sink/shuffle flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/sink/shuffle
```
=> Flink:backport PR to 1.16 #7360: Implement data statistics coordinator to aggregate data statistics from operator subtasks

flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/sink/shuffle/AggregatedStatistics.java, flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/sink/shuffle/AggregatedStatisticsTracker.java, flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/sink/shuffle/DataStatisticsCoordinator.java, flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/sink/shuffle/DataStatisticsCoordinatorProvider.java, flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/sink/shuffle/DataStatisticsOperator.java, flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/sink/shuffle/DataStatisticsOrRecord.java, flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/sink/shuffle/DataStatisticsUtil.java, flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/sink/shuffle/TestAggregatedStatistics.java, flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/sink/shuffle/TestAggregatedStatisticsTracker.java, flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/sink/shuffle/TestDataStatisticsCoordinator.java, flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/sink/shuffle/TestDataStatisticsCoordinatorProvider.java, flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/sink/shuffle/TestDataStatisticsOperator.java
it isn't a clean back port because OperatorCoordinator gets changed in Flink-runtime 1.16
=> Flink:backport PR to 1.15 #7360: Implement data statistics coordinator to aggregate data statistics from operator subtasks

docs/aws.md
It is easy to let these go out of sync. And people should just use the bundle :)
=> Docs: Remove AWS Version

core/src/main/java/org/apache/iceberg/BaseFile.java, core/src/main/java/org/apache/iceberg/util/ArrayUtil.java, core/src/test/java/org/apache/iceberg/TableTestBase.java, core/src/test/java/org/apache/iceberg/TestManifestReader.java
This PR fixes a critical bug in reading split offsets from manifests. A change in https://github.com/apache/iceberg/pull/8336 added caching of the offsets collection in `BaseFile` to avoid reallocation. However, the Avro reader will reuse the same BaseFile object when reading, thus only the offsets from the first entry are allocated, and then those are reused for all  other entries.
cc @aokolnychyi @RussellSpitzer @rdblue @danielcweeks This can result in corrupted metadata in cases the invalid offsets are read in then written back, e.g. when rewriting manifests.
=> Core: fix reading of split offsets in manifests

flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java, flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/sink/TestBucketPartitionerFlinkIcebergSink.java, flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java, flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/sink/TestBucketPartitionerFlinkIcebergSink.java, flink/v1.17/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java, flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/sink/TestBucketPartitionerFlinkIcebergSink.java
close issue #8847 
Flink: Disabling the usage of this custom partitioner by default bucketing columns with Hash distribution.
See details from this comment thread #7161
=> Flink: Reverting the default custom partitioner for bucket column

flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java, flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/sink/TestBucketPartitionerFlinkIcebergSink.java, flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java, flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/sink/TestBucketPartitionerFlinkIcebergSink.java, flink/v1.17/flink/src/main/java/org/apache/iceberg/flink/sink/FlinkSink.java, flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/sink/TestBucketPartitionerFlinkIcebergSink.java
=> [1.4.x] Flink: Reverting the default custom partitioner for bucket column (#8848)

core/src/main/java/org/apache/iceberg/BaseFile.java, core/src/test/java/org/apache/iceberg/TableTestBase.java, core/src/test/java/org/apache/iceberg/TestManifestReader.java
Follow up to https://github.com/apache/iceberg/pull/8834
This change ignores split offsets when the last split offset is past the file length. This is done as a defensive check to make sure that readers don't attempt to use corrupted split offset stemming from the issue described in #8834. Note: It is possible that split offsets were corrupted and then the last split offset was not past the file length. In that case, it's still acceptable to use the split offsets because it won't break reading logic since the split offsets would be guaranteed to be within the file boundaries.
=> Core: Ignore split offsets when the last split offset is past the file length

core/src/main/java/org/apache/iceberg/BaseFile.java, core/src/test/java/org/apache/iceberg/TableTestBase.java, core/src/test/java/org/apache/iceberg/TestManifestReader.java
Cherry pick #8860 onto the 1.4.x branch for 1.4.1 release
=> [1.4.x] Core: Ignore split offsets when the last split offset is past the file length

aws/src/main/java/org/apache/iceberg/aws/AwsClientFactories.java, aws/src/main/java/org/apache/iceberg/aws/AwsClientProperties.java, aws/src/main/java/org/apache/iceberg/aws/AwsProperties.java, aws/src/test/java/org/apache/iceberg/aws/AwsClientPropertiesTest.java
=> [1.4.x] AWS: avoid static global credentials provider which doesn't play well with lifecycle management (#8677)

open-api/rest-catalog-open-api.py, open-api/rest-catalog-open-api.yaml
I think we want to make `error` required, otherwise it would just be an empty document `{}`.
=> Open-API: Make error required

nessie/src/test/java/org/apache/iceberg/nessie/TestCustomNessieClient.java
extending the previous change #8607 .
Removing the use of deprecated [HttpClientBuilder](https://github.com/projectnessie/nessie/blob/5e028514f84e9dfd8ad54d5b591a9f3e083df146/api/client/src/main/java/org/projectnessie/client/http/HttpClientBuilder.java) and  [CONF_NESSIE_CLIENT_BUILDER_IMPL](https://github.com/projectnessie/nessie/blob/5e028514f84e9dfd8ad54d5b591a9f3e083df146/api/client/src/main/java/org/projectnessie/client/NessieConfigConstants.java#L258) .
=> Nessie: Adapt to Nessie 0.71.1 release

aws/src/main/java/org/apache/iceberg/aws/glue/GlueCatalog.java, aws/src/test/java/org/apache/iceberg/aws/glue/TestGlueCatalog.java
Currently the Glue catalog does not strip the trailing slash on default DB location this can lead to path issues as seen in the below issue.
Related to: https://github.com/tabular-io/iceberg-kafka-connect/issues/127
=> AWS: Glue catalog strip trailing slash on DB URI

flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/SimpleDataUtil.java, flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/source/TestIcebergSourceContinuous.java, flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/source/TestIcebergSourceFailover.java, flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/source/TestStreamingMonitorFunction.java
Continue from [here](https://github.com/apache/iceberg/pull/8852#issuecomment-1767711923) .
=> Flink 1.15: Use awaitility instead of Thread.sleep()

.github/workflows/jmh-benchmarks.yml
Closes #8665 
Update `.github/workflows/jmh-benchmarks.yml` to use environment file instead of deprecated `set-output` command. 
For more information, see: [https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
I found the workflow file that use `set-output` command through the following command:
```bash
$ find . -name '*.yml' -o -name '*.yaml' | xargs egrep '\bset-output\b'
```
**AS-IS**
```yaml
echo "::set-output name=matrix::[$matrix]"
echo "::set-output name=foundlabel::$(echo "[$matrix]" | jq 'if . | length > 0 then true else false end')"
```
**TO-BE**
```yaml
echo "matrix=[$matrix]" >> $GITHUB_OUTPUT
echo "foundlabel=$(echo …
```
=> Build: Replace deprecated command with environment file

README.md
latest javadoc can be found in https://iceberg.apache.org/javadoc/latest 
Can you help take a look @nastra @Fokko @amogh-jahagirdar
=> Doc: fix iceberg-javadoc link

spark/v3.4/build.gradle, spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/source/SparkSQLExecutionHelper.java
Continuing from [here](https://github.com/apache/iceberg/pull/8853/files)
=> Spark 3.4: Use Awaitility instead of Thread.sleep()

spark/v3.3/build.gradle, spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/source/SparkSQLExecutionHelper.java
Continuing from [here](https://github.com/apache/iceberg/pull/8853/files)
=> Spark 3.3: Use Awaitility instead of Thread.sleep()

spark/v3.2/build.gradle, spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/source/SparkSQLExecutionHelper.java
Continuing from [here](https://github.com/apache/iceberg/pull/8853/files)
=> Spark 3.2: Use Awaitility instead of Thread.sleep()

.github/workflows/delta-conversion-ci.yml, .github/workflows/flink-ci.yml, .github/workflows/hive-ci.yml, .github/workflows/java-ci.yml, .github/workflows/spark-ci.yml
On updating the issue templates we should not run the CI which tests code correctness this pr attempts to allow list the complete ISSUE_TEMPLATE folder so that when ever this is updated we don't waste the compute on running CI as it's effectively testing nothing. 
Sample PR : 
- https://github.com/apache/iceberg/pull/8889
cc @Fokko @nastra @ajantha-bhat
=> INFRA: Avoid Running engine and core CI on template update

dev/source-release.sh
I think we should remove the excluding weekends part of the wait period. With a patch release like we're doing now, I don't think we want to be constrained by this. In practice, I don't think many releases are being published over the weekend.
Apache states that a vote **should** be open for 72 hours. https://www.apache.org/foundation/voting.html#expressing-votes-1-0-1-and-fractions.
If we agree on it, I'll open up a PR on the docs site as well 👍
=> Update release template

.asf.yaml
This was done earlier before there was a `.asf.yaml` through an INFRA ticket, but I think it is good to also add it to the `yaml`.
=> INFRA: Disable merging explicitly

open-api/rest-catalog-open-api.py, open-api/rest-catalog-open-api.yaml
When generating a REST client using the current OpenAPI specification, the non-200 Iceberg error responses are defined as:
```
{
"message": "Malformed request",
"type": "BadRequestException",
"code": 400
}
```
However, the provided examples in the spec correctly enclose the error details within an error JSON node:
```
{
"error": {
"message": "Malformed request",
"type": "BadRequestException",
"code": 400
}
}
```
Iceberg error responses point to the `ErrorModel` as their schema, as seen [here](https://github.com/apache/iceberg/blob/main/open-api/rest-catalog-open-api.yaml#L1102-L1126). Following the current convention and returning the above-stated non-200 error structure to the client results in a precondition failure within the [ErrorResponseParser](https://github.com/apache/iceberg/blob/ …
=> Open-API: Error response in the spec don’t align with the expected model.

core/src/main/java/org/apache/iceberg/ManifestFilterManager.java
This change will make deletedPaths call 'add' function only if it not contains file path, thus avoiding the unnecessary cost caused by 'add' function calls
=> Core: Reduce unnecessary add operations in deletedPaths set

spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/source/SerializableTableWithSize.java, spark/v3.2/spark/src/test/java/org/apache/iceberg/TestTableSerialization.java, spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/SerializableTableWithSize.java, spark/v3.3/spark/src/test/java/org/apache/iceberg/TestTableSerialization.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/source/SerializableTableWithSize.java, spark/v3.4/spark/src/test/java/org/apache/iceberg/TestTableSerialization.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/source/SerializableTableWithSize.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/TestTableSerialization.java
This PR implements the same approach as in PR #8685 but for metadata tables.
=> Spark: Clean up FileIO instances on executors for metadata tables

core/src/main/java/org/apache/iceberg/BaseFile.java, core/src/test/java/org/apache/iceberg/util/TestTableScanUtil.java
Follow up from a miss in the fix done in https://github.com/apache/iceberg/pull/8860. There's an additional splitOffsetArray method which gets used here https://github.com/apache/iceberg/blob/aa891acf20040d15e7ca59dc503adb3c1e4325b8/core/src/main/java/org/apache/iceberg/BaseContentScanTask.java#L134 . We would want to surface null for this array in case we know the split offsets are corrupted and invalid (stemming from an issue in 1.4.0). The split offsets are invalid when the final offset is beyond the end of the file.
Alternatively, we can undo the optimization done here: https://github.com/apache/iceberg/pull/8336#discussion_r1296190234 and then the original fix in #8860 would be sufficient, and be simpler. Since the optimization seemed impactful and there was community interest in it, …
=> Core: Ignore split offsets array when split offset is past file length

core/src/main/java/org/apache/iceberg/BaseFile.java, core/src/test/java/org/apache/iceberg/util/TestTableScanUtil.java
=> [1.4.x] Core: Ignore split offsets array when split offset is past file length

aws/src/integration/java/org/apache/iceberg/aws/TestAssumeRoleAwsClientFactory.java, aws/src/integration/java/org/apache/iceberg/aws/glue/TestGlueCatalogLock.java, aws/src/integration/java/org/apache/iceberg/aws/lakeformation/LakeFormationTestBase.java, aws/src/integration/java/org/apache/iceberg/aws/lakeformation/TestLakeFormationAwsClientFactory.java, build.gradle, core/src/test/java/org/apache/iceberg/hadoop/TestHadoopCommits.java, core/src/test/java/org/apache/iceberg/jdbc/TestJdbcTableConcurrency.java, hive-metastore/src/test/java/org/apache/iceberg/hive/TestHiveTableConcurrency.java, spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/source/SparkSQLExecutionHelper.java, spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/source/SparkSQLExecutionHelper.java, spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/source/SparkSQLExecutionHelper.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/SparkSQLExecutionHelper.java
=> AWS, Core: Use Awaitility instead of Thread.sleep

core/src/main/java/org/apache/iceberg/util/LockManagers.java
This is a fix for an `NPE` problem that occurs when calling [InMemoryLockManager#release](https://github.com/apache/iceberg/blob/master/core/src/main/java/org/apache/iceberg/util/LockManagers.java#L240C2-L240C2) using Hadoop catalog, as described in this issue(#4550). The problem arises when `lockManager#release` is finally called after renaming metadata ([HadoopTableOperations#renameToFinal](https://github.com/apache/iceberg/blob/master/core/src/main/java/org/apache/iceberg/hadoop/HadoopTableOperations.java#L361C20-L361C20)).
The immediate cause of `NPE` is that the locked `entityId` has been removed from the [`HEARTBEATS`](https://github.com/apache/iceberg/blob/master/core/src/main/java/org/apache/iceberg/util/LockManagers.java#L168), but still exists in `LOCKS`. Some concurrent …
=> Core: fix `NullPointerException` when calling `InMemoryLockManager#release` using Hadoop catalog

api/src/main/java/org/apache/iceberg/Table.java, core/src/main/java/org/apache/iceberg/BaseMetadataTable.java, core/src/main/java/org/apache/iceberg/BaseTable.java, core/src/main/java/org/apache/iceberg/BaseTransaction.java, core/src/main/java/org/apache/iceberg/SerializableTable.java, core/src/test/java/org/apache/iceberg/catalog/CatalogTests.java
This change exposes the underlying table metadata UUID via the Table API for easier access (currently one has to go through multiple hops + casting to get these details, but since a table should always have a defined UUID it will make it easier for clients to just access it via an API)
=> API, Core: Add UUID API to Table

spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/actions/RewriteManifestsSparkAction.java, spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteManifestsAction.java
This PR cherry-picks PR #8935 to Spark 3.2.
=> Spark 3.2: Don't cache or reuse manifest entries while rewriting metadata by default

docs/spark-ddl.md
We have testcase in https://github.com/apache/iceberg/blob/b9a4478b0f8f5eeae553eb3900b08a7a08dbdb40/spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestSetWriteDistributionAndOrdering.java#L183
But it is not documented causing confusion to users.
Ref: https://github.com/apache/iceberg/issues/5071
=> Docs: Document UNORDERED for spark write

core/src/main/java/org/apache/iceberg/BaseRewriteManifests.java, core/src/main/java/org/apache/iceberg/SnapshotProducer.java, core/src/test/java/org/apache/iceberg/TestRewriteManifests.java, docs/configuration.md, docs/spark-procedures.md, spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/actions/RewriteManifestsSparkAction.java, spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteManifestsAction.java, spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/actions/RewriteManifestsSparkAction.java, spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteManifestsAction.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/actions/RewriteManifestsSparkAction.java, spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteManifestsAction.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/actions/RewriteManifestsSparkAction.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteManifestsAction.java
This PR avoids extra copies of manifests while optimizing metadata for V2 tables via Spark. Specifically, we have to rewrite all remotely produced manifests while committing again to assign explicit snapshot IDs in V1 tables unless the snapshot ID inheritance is enabled (false by default). In V2 tables, however, snapshot ID inheritance is always enabled. That's why it is safe to reuse the remotely produced manifests without an expensive rewrite on the driver as long as we have a V2 table. Before this change, we always relied on the table property to check if snapshot ID inheritance is enabled, which was added before the V2 spec.
=> Spark: Avoid extra copies of manifests while optimizing V2 tables

format/spec.md
Adding the spec changes for partition stats. 
Based on the discussed design:
https://docs.google.com/document/d/1vaufuD47kMijz97LxM67X8OX-W2Wq7nmlz3jRo8J5Qk/edit?usp=sharing
Fixes: #8451, #8452
=> Spec: Add partition stats spec

core/src/main/java/org/apache/iceberg/PartitionsTable.java, spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestDelete.java, spark/v3.3/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestDelete.java, spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestDelete.java, spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestDelete.java
close #8951 
This help fix the bug introduced in #7581 where partition table scan entries instead of files to have partition level stats aggregagted over files. In order to have correct stats, only live entries need to be scanned instead of all entries
=> Core: Scan only live entries for partitions table

core/src/main/java/org/apache/iceberg/SystemConfigs.java, core/src/main/java/org/apache/iceberg/deletes/BitmapPositionDeleteIndex.java, core/src/main/java/org/apache/iceberg/deletes/Deletes.java, core/src/main/java/org/apache/iceberg/util/ThreadPools.java, core/src/test/java/org/apache/iceberg/deletes/TestPositionFilter.java
This is a continuation of https://github.com/apache/iceberg/pull/6432 by @rbalamohan, as he is not working on it anymore.
I have squashed all his commits in that PR into one, rebased it on master, and made some minor changes.
=> Core: Use ParallelIterable in Deletes::toPositionIndex (6387)

site/docs/contribute.md
This PR removes outdated Python autoformatting command from the site doc, where tox was replaced by pre-commit by #4811.
=> Docs: Remove outdated python autoformating command from doc

spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/SparkDataFile.java
This PR makes `SparkDataFile` use constants in `DataFile` instead of hard-coded values.
=> Spark 3.5: Use DataFile constants in SparkDataFile

spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/actions/RewriteManifestsSparkAction.java, spark/v3.2/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteManifestsAction.java, spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/actions/RewriteManifestsSparkAction.java, spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteManifestsAction.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/actions/RewriteManifestsSparkAction.java, spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteManifestsAction.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/actions/RewriteManifestsSparkAction.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteManifestsAction.java
This PR fixes our actions for rewriting manifests to use the provided staging location only if the manifests are staged. If snapshot ID inheritance is enabled (true for all V2 tables), the manifests are committed directly without staging. In that case, the manifests must be written to the metadata folder and the staging location must be ignored.
=> Spark: Fix usage of staging location when optimizing metadata

core/src/main/java/org/apache/iceberg/StaticTableOperations.java, core/src/test/java/org/apache/iceberg/util/TestReachableFileUtil.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/actions/BaseSparkAction.java
If the table is already having table metadata object, no need to do an extra IO to read from the table metadata location. So, we need a constructor that accepts table metadata object directly.
=> Core: Add a constructor to StaticTableOperations

docs/flink-writes.md
Update the doc per the discussions in #5846
=> Docs: Add note that snapshot expiration and cleanup orphan files could corrupt Flink job state

format/spec.md
Helps #8657
In order for ORC types `timestamp` and `timestamp_instant` to be correctly converted to Iceberg `timestamp`, `timestamp_ns`, `timestamptz`, and `timestamptz_ns`, we need an ORC type attribute.
=> Spec: clarify ns timestamps for ORC deserialization

spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/actions/RewriteManifestsSparkAction.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteManifestsAction.java
This PR fixes our action for rewriting manifests for evolved unpartitioned V1 tables. There is no need to repartition by range and locally order manifest entries if the spec contains only void transforms. Such tables should be treated as unpartitioned.
=> Spark 3.5: Fix rewriting manifests for evolved unpartitioned V1 tables

api/src/main/java/org/apache/iceberg/ManifestFile.java
This PR fixes Javadoc for `ManifestFile` to be generic instead of being worded in terms of data files.
=> Docs: Fix Javadoc for ManifestFile

format/view-spec.md
When compared 244-249 lines to 175-177 lines,
column comment and view comment were missing. But this change was not reflected back in the new metadata file.
So, added back the comments, else we need to update the view metadata Json to reflect without comments.
=> Spec: Fix view example

spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/source/SparkPositionDeletesRewrite.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/source/SparkPositionDeltaWrite.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/source/SparkWrite.java
In Spark `BatchWrite.java`, `useCommitCoordinator` is default to true. This PR overrides `useCommitCoordinator` to false, so we can rewrite a task after it fails. Here is the [issue](https://github.com/apache/iceberg/issues/8904)
=> Override useCommitCoordinator to false

spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/source/SparkWrite.java
Followup PR for https://github.com/apache/iceberg/pull/9017: overriding `useCommitCoordinator` to false in `BaseStreamingWriter`
=> Override useCommitCoordinator to false in BaseStreamingWriter

spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/source/SparkPositionDeletesRewrite.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/source/SparkPositionDeltaWrite.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/source/SparkWrite.java
Override `useCommitCoordinator` to false in Spark 3.4
Here is the [PR](https://github.com/apache/iceberg/pull/9017) for Spark3.5
=> Override useCommitCoordinator to false in Spark3.4

api/src/main/java/org/apache/iceberg/util/CharSequenceWrapper.java
While profiling #8755, I noticed that `equals` in `CharSequenceWrapper` is quite slow. 
This PR contains 2 optimizations:
- Check if both wrapped objects are `String`. If so, call `equals()` on them. This comparison will be much more efficient because bytes will be compared directly.
- Return early if char sequences have different lengths.
=> API: Optimize equals in CharSequenceWrapper

.github/dependabot.yml
Since we're moving the site back into the main repository, it would be great to have Dependabot update `site/requirements.txt`
=> Add dependabot to automatically update the site

spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMetaColumnProjectionWithStageScan.java, spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMetaColumns.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/source/SparkStagedScan.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/source/SparkStagedScanBuilder.java
like in [query file meta column](https://docs.databricks.com/en/ingestion/file-metadata-column.html),
it is convenient to support the following 
```
spark.read \
.format("csv") \
.schema(schema) \
.load("dbfs:/tmp/*") \
.select("_metadata.file_name", "_metadata.file_size")
```
=> support read meta columns in staged scan

core/src/main/java/org/apache/iceberg/ContentFileParser.java, core/src/main/java/org/apache/iceberg/DataFiles.java, core/src/main/java/org/apache/iceberg/GenericDataFile.java, core/src/test/java/org/apache/iceberg/TestContentFileParser.java, core/src/test/java/org/apache/iceberg/TestManifestWriterVersions.java
This PR disallows setting equality field IDs for data to honor the spec.
```
Field ids used to determine row equality in equality delete files. Required when content=2 and should be null otherwise. Fields with ids listed in this column must be present in the delete file.
```
See [this](https://lists.apache.org/thread/cjjfxb53fpjbolr7y8dt9vt880fxp29x) dev list discussion.
=> Core: Disallow setting equality field IDs for data

core/src/main/java/org/apache/iceberg/actions/SizeBasedFileRewriter.java, core/src/test/java/org/apache/iceberg/actions/TestSizeBasedRewriter.java
This PR adjusts the split computation logic in file rewriters. The previous logic performed poorly in some cases.
Suppose we have 4 files, 145 MB each. This means we have 580 MB to compact. If the target file size is 512 MB, the rewriter will decide to produce 2 output files as the input is 13% larger than the target file size (we allow 10% overhead). If this happens, the previous logic will use 580 MB / 2 = 290 MB as the split size. That's why the compaction will produce 2 output files that are already poorly sized. Such files will be picked up again in the next round even if there is no new data, creating a never ending loop of useless compaction. 
This PR makes sure the split size is never less than the target output file.
=> Core: Fix split size calculations in file rewriters

api/src/main/java/org/apache/iceberg/util/CharSequenceMap.java, api/src/test/java/org/apache/iceberg/util/TestCharSequenceMap.java
This PR adds `CharSequenceMap`, a map implementation that uses arbitrary char sequences as keys. The implementation is similar to `CharSequenceSet`. This class will be used in writers, delete file index, Spark executor-level content file cache.
=> API: Add CharSequenceMap

gcp/src/main/java/org/apache/iceberg/gcp/GCPProperties.java, gcp/src/main/java/org/apache/iceberg/gcp/gcs/GCSFileIO.java, gcp/src/test/java/org/apache/iceberg/gcp/GCPPropertiesTest.java
Although there is no "official" Google Cloud Storage emulator available yet, there is [one available](https://github.com/oittaa/gcp-storage-emulator) that allows at least some basic testing. To use an emulator, the client needs to be configured to use no authentication, otherwise it will fallback to "automatic credential detection".
=> GCS: Allow no-auth for testing purposes

spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/SparkContentFile.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/SparkDeleteFile.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/actions/RewriteManifestsSparkAction.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteManifestsAction.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkDataFile.java
This PR extends our action for rewriting manifest to support deletes.
This fixes #6375.
=> Spark 3.5: Extend action for rewriting manifests to support deletes

spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/SparkRowLevelOperationsTestBase.java, spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestDelete.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/source/SparkTable.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/data/TestHelpers.java
Fix #7635 .
The Iceberg Spark integration has logic to surface to the Spark Optimizer whether a metadata delete (deleting a data file) should be performed or not (the alternative is row level deletes). When there are branches, this logic incorrectly reads the main branch's metadata and surfaces to the optimizer that metadata deletes are possible even though they are not possible on the actual branch being deleted.
This leads to expected failure at the time of the commit validation since there are residual rows in the file that don't match the deletion criteria. 
This fixes the problem by making sure the scan gets built correctly. Also this change also makes sure the metadata delete tests actually exercise branches. Previously the tests weren't exercising metadata deletes on branches …
=> Spark: Fix metadata delete condition check when there are branches

spark/v3.3/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/SparkRowLevelOperationsTestBase.java, spark/v3.3/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestDelete.java, spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/SparkTable.java, spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/data/TestHelpers.java, spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/SparkRowLevelOperationsTestBase.java, spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestDelete.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/source/SparkTable.java, spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/data/TestHelpers.java
This change backports #9102 to Spark 3.3 and 3.4
=> Spark 3.3, 3.4: Backport fix for metadata delete condition check for branches

core/src/main/java/org/apache/iceberg/deletes/BitmapPositionDeleteIndex.java
This PR removes synchronization from `BitmapPositionDeleteIndex` added in PR #8805.
We switched to `ParallelIterable` to parallelize reading of deletes in the original change. However, marking the `delete` method in `BitmapPositionDeleteIndex` synchronized was redundant because `ParallelIterable` outputs elements synchronously. That class internally uses a thread-safe queue to process the input iterables concurrently but does not require extra synchronization in consumers. In other words, there will be only one thread consuming from the iterable that will be populated by multiple threads internally.
I verified this manually and we also have `TestPositionFilter`.
=> Core: Remove synchronization from BitmapPositionDeleteIndex

data/src/main/java/org/apache/iceberg/data/DeleteFilter.java
This PR removes the outdated logic in `DeleteFilter` that determined whether we have to stream through position deletes or load them in memory. Instead, we should always rely on the bitmap-based approach like in vectorized reads.
=> Data: Always use delete index for position deletes

docs/flink-writes.md
Remove UNIQUE keyword as it is not supported in Flink.
=> Docs: Remove UNIQUE keyword as it is not supported in Flink

spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestFastForwardBranchProcedure.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/procedures/FastForwardBranchProcedure.java
Currently the output of the Spark fast forward procedure always outputs `currentSnapshot` before and after the fast forward operation. However, this is not correct in case the branch being fast forwarded is not main. This change updates the output to always output the before and after of the actual branch being fast forwarded.
=> Spark: Fix Fast forward procedure output for non-main branches

hive-metastore/src/main/java/org/apache/iceberg/hive/HiveCatalog.java, hive-metastore/src/main/java/org/apache/iceberg/hive/HiveOperationsBase.java, hive-metastore/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java
As part of issues #8698 , as discussed [here](https://github.com/apache/iceberg/pull/8907#issuecomment-1798279159) , All the common piece between table and view has been moved from `HiveTableOperations` to a new helper class.
=> Hive: Refactor HiveTableOperations with common code for View.

flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/source/TestIcebergSourceFailover.java, flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/source/TestStreamingMonitorFunction.java, flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/source/TestIcebergSourceFailover.java, flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/source/TestStreamingMonitorFunction.java
Fix backport differences for #8852 between the Flink versions
=> Flink: Proper backport for #8852

flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/source/FlinkSplitPlanner.java, flink/v1.15/flink/src/main/java/org/apache/iceberg/flink/source/ScanContext.java, flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/source/enumerator/TestContinuousSplitPlannerImpl.java, flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/source/FlinkSplitPlanner.java, flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/source/ScanContext.java, flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/source/enumerator/TestContinuousSplitPlannerImpl.java
Fixing missing backports on Flink v1.15 and v1.16 versions.
Should be merged without squashing the commits, so the commit structure does not change.
=> Flink missing backports

flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/MiniFlinkClusterExtension.java, flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/TestBase.java, flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/TestCatalogTableLoader.java, flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/MiniFlinkClusterExtension.java, flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/TestBase.java, flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/TestCatalogTableLoader.java
Backport gh-9078 to v1.16 and v1.15
=> Flink: Backport #9078 to v1.16 and v1.15

api/src/main/java/org/apache/iceberg/ManageSnapshots.java, core/src/main/java/org/apache/iceberg/SnapshotManager.java, core/src/main/java/org/apache/iceberg/UpdateSnapshotReferencesOperation.java, core/src/test/java/org/apache/iceberg/TestSnapshotManager.java
This change fixes some very confusing naming from my original implementation of the fastForward/replaceBranch APIs. 
Prior to this change, the APIs had the following naming:
```
fastForward(String name, String source)
replaceBranch(String name, String source)
```
"Name" is the branch that would be fast forwarded and source is the "destination" or target we would fast forward to. This doesn't really align with how most people would think when it comes to fast forward or replace operations (like Git). 
This change renames it to:
```
fastForward(String from, String to)
replaceBranch(String from, String to)
```
Note: This is just a rename of parameters and error messages. There is no change in behavior in the API.
=> API, Core: Fix naming in fastForwardBranch/replaceBranch APIs

api/src/main/java/org/apache/iceberg/PartitionKey.java, api/src/main/java/org/apache/iceberg/SortKey.java, api/src/main/java/org/apache/iceberg/SortOrderComparators.java, api/src/main/java/org/apache/iceberg/StructTransform.java, api/src/test/java/org/apache/iceberg/TestSortOrderComparators.java
see more context from dev ML thread: https://www.mail-archive.com/dev@iceberg.apache.org/msg04424.html
=> API: add StructTransform base class for PartitionKey and SortKey. add SortOrderComparators

core/src/main/java/org/apache/iceberg/DeleteFileIndex.java
This PR removes deprecated and no longer used code in `DeleteFileIndex`.
=> Core: Remove deprecated code in DeleteFileIndex

core/src/main/java/org/apache/iceberg/BaseTransaction.java, core/src/test/java/org/apache/iceberg/TableTestBase.java, core/src/test/java/org/apache/iceberg/TestRemoveSnapshots.java, core/src/test/java/org/apache/iceberg/TestSequenceNumberForV2Table.java
When a snapshot is expired as part of a transaction, the snapshot file(s) should be deleted when the transaction commits. A recent change (#6634) ensured that files are not deleted when they have also been committed as part of a transaction, but this breaks the simple case where no new files are committed. Fix this by not skipping deletion when the list of committed files is empty.
Closes #9182 
TESTING:
Extended a unit test to ensure that snapshot files are deleted. Ran the test without the fix on a branch where #6634 was reverted to show that this is a regression.
=> Core: Expired Snapshot files in a transaction should be deleted.

core/src/main/java/org/apache/iceberg/util/SnapshotUtil.java, core/src/test/java/org/apache/iceberg/util/TestSnapshotUtil.java, spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/source/TestSnapshotSelection.java, spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/source/TestSnapshotSelection.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestSnapshotSelection.java
When retrieving the schema for branch we should always return the table schema instead of the snapshot schema. This is because the table schema is the schema that will be used when the branch will be created. We should only return the schema of the snapshot when we have a tag.
Below is an example that shows the weird schema behavior when describing a table.
```
-- create a table with a single column and insert a value
spark-sql (default)> create table t (s string);
spark-sql (default)> insert into t values ('foo');
-- create a branch, the schema is the same as the original table
spark-sql (default)> alter table t create branch b1;
```
```
spark-sql (default)> describe default.t;
s                       string                      --> this schema comes from top-level table metadata …
```
=> Core: Schema for a branch should return table schema

aliyun/src/test/java/org/apache/iceberg/aliyun/TestAliyunClientFactories.java, aliyun/src/test/java/org/apache/iceberg/aliyun/TestUtility.java, aliyun/src/test/java/org/apache/iceberg/aliyun/oss/AliyunOSSExtension.java, aliyun/src/test/java/org/apache/iceberg/aliyun/oss/AliyunOSSTestBase.java, aliyun/src/test/java/org/apache/iceberg/aliyun/oss/OSSIntegrationExtension.java, aliyun/src/test/java/org/apache/iceberg/aliyun/oss/TestOSSFileIO.java, aliyun/src/test/java/org/apache/iceberg/aliyun/oss/TestOSSInputFile.java, aliyun/src/test/java/org/apache/iceberg/aliyun/oss/TestOSSInputStream.java, aliyun/src/test/java/org/apache/iceberg/aliyun/oss/TestOSSOutputFile.java, aliyun/src/test/java/org/apache/iceberg/aliyun/oss/TestOSSOutputStream.java, aliyun/src/test/java/org/apache/iceberg/aliyun/oss/TestOSSURI.java, aliyun/src/test/java/org/apache/iceberg/aliyun/oss/mock/AliyunOSSMockExtension.java, aliyun/src/test/java/org/apache/iceberg/aliyun/oss/mock/TestLocalAliyunOSS.java, build.gradle
Switch iceberg-aliyun's tests to Junit5
Fix: #9081 
@nastra Hi, I have changed all of the junit4 code to junit5 with AssertJ, but I have a question here: To fit the Extension class of Junit5, I changed most of the term 'Rule' to 'Extension', but there is a system env variable in `org/apache/iceberg/aliyun/TestUtility.java` called `ALIYUN_TEST_OSS_TEST_RULE_CLASS`.
I don't know where the CI system runs, and how the variable is set. So I'm not sure if I should change this.
=> Aliyun: Switch iceberg-aliyun's tests to Junit5

spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/SparkCatalog.java, spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/SparkTable.java, spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/sql/TestSelect.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/SparkCatalog.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/source/SparkTable.java, spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/sql/TestSelect.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/SparkCatalog.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/source/SparkTable.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/sql/TestSelect.java
In the context of https://github.com/apache/iceberg/pull/9131 we talked in the Iceberg sync about making sure that queries like `SELECT * from ns.table.branch_x VERSION AS OF ...` shouldn't be supported and should throw an error
=> Spark: Don't allow branch_ usage with VERSION AS OF

core/src/main/java/org/apache/iceberg/rest/ErrorHandlers.java, core/src/test/java/org/apache/iceberg/view/ViewCatalogTests.java
This came up in https://github.com/apache/iceberg/pull/7913#discussion_r1414686074
=> Core: Handle IAE in default error handler

core/src/main/java/org/apache/iceberg/BaseTransaction.java
This is a follow up to https://github.com/apache/iceberg/pull/9183. Null gets returned from `committedFiles` in 2 cases:
1.)  The snapshot ID list is empty (e.g. ExpireSnapshots in a transaction). This snapshot ID is the set of snapshots produced as a result of the transaction
2.).The set of committed files could not exactly be determined (e.g. missing any snapshot metadata).
In the first case, the logic should perform file deletion in case there were no new snapshots (e.g. ExpireSnapshots) which #9183 pointed out and addressed.
In the second case, we do want to signal to callers that it's a unique situation and file deletions should not be performed.
What this change does is return an empty set in case 1 and null in case 2 to prevent deleting files when we could not determine the full …
=> Core: Fix logic in BaseTransaction for determining set of committed files when there are no new snapshots

api/src/test/java/org/apache/iceberg/util/TestExceptionUtil.java, aws/src/test/java/org/apache/iceberg/aws/s3/signer/TestS3SignRequestParser.java, aws/src/test/java/org/apache/iceberg/aws/s3/signer/TestS3SignResponseParser.java, core/src/main/java/org/apache/iceberg/BaseRewriteManifests.java, core/src/test/java/org/apache/iceberg/ScanTestBase.java, core/src/test/java/org/apache/iceberg/TestContentFileParser.java, flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/source/enumerator/TestContinuousIcebergEnumerator.java, flink/v1.15/flink/src/test/java/org/apache/iceberg/flink/source/reader/TestIcebergSourceReader.java, flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/source/reader/TestIcebergSourceReader.java, flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/source/reader/TestIcebergSourceReader.java, hive-metastore/src/test/java/org/apache/iceberg/hive/TestHiveSchemaUtil.java
A simple task, wish it could be a good start for me:)
Closes #9207
=> Style: Replace Arrays.asList with Collections.singletonList

core/src/main/java/org/apache/iceberg/view/ViewProperties.java, core/src/test/java/org/apache/iceberg/view/TestViewMetadataParser.java, core/src/test/resources/org/apache/iceberg/view/ValidViewMetadata.json
We reference using "comment" as a property in the view spec, but it looks like we don't have a constant defined in the library. See https://github.com/trinodb/trino/pull/19818#discussion_r1408354022 for more details but I think "comment" should be defined in the Iceberg library as it is not engine specific.
=> Core: Add comment property to ViewProperties

api/src/test/java/org/apache/iceberg/TestHelpers.java, core/src/main/java/org/apache/iceberg/util/StructLikeMap.java, core/src/test/java/org/apache/iceberg/util/TestStructLikeMap.java
This PR fixes equality in `StructLikeMap`. See tests for use cases that previously failed.
=> Core: Fix equality in StructLikeMap

core/src/main/java/org/apache/iceberg/util/PartitionMap.java, core/src/main/java/org/apache/iceberg/util/PartitionSet.java, core/src/test/java/org/apache/iceberg/util/TestPartitionMap.java
This PR adds `PartitionMap`, a map that uses a pair of spec ID and partition tuple as keys. It is similar to `PartitionSet`.
The class will simplify places like `DeleteFileIndex` that uses the following code not related to the main logic.
```
private final Map<Integer, Types.StructType> partitionTypeById;
private final Map<Integer, ThreadLocal<StructLikeWrapper>> wrapperById;
private final Map<Pair<Integer, StructLikeWrapper>, DeleteFileGroup> deletesByPartition;
// use HashMap with precomputed values instead of thread-safe collections loaded on demand
// as the cache is being accessed for each data file and the lookup speed is critical
private Map<Integer, ThreadLocal<StructLikeWrapper>> wrappers(Map<Integer, PartitionSpec> specs) {
Map<Integer, ThreadLocal<StructLikeWrapper>> wrappers = …
```
=> Core: Add PartitionMap

docs/spark-queries.md
Writing to a branch or tag is supported in Spark using a table identifier with `branch_<branchname>` or `tag_<tagname>`. Reading from the branch or tag is supported using the same kind of identifier, in addition to the `VERSION AS OF` syntax, but this is not documented. For consistency, users may prefer to read and write using the same syntax. We should document that they can.
Note: When loading a table using identifiers with `snapshot_id_` and `at_timestamp_` was implemented, this was considered an implementation detail and we did not expose it publicly (i.e., document it). However, since the `branch_` and `tag_` identifiers are used for writes and documented, we should expose them for reads as well.
=> Docs: Document reading in Spark using branch and tag identifiers

spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRewriteManifestsProcedure.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/procedures/RewriteManifestsProcedure.java
As title. Current manifest rewrite in spark procedure only can be performed on manifests with current spec id. This PR allows user to specify rewrite on manifests with old spec ids.
=> [spark 3.5] Support specifying spec_id in RewriteManifestProcedure

core/src/test/java/org/apache/iceberg/FileGenerationUtil.java, spark/v3.5/build.gradle, spark/v3.5/spark-extensions/src/jmh/java/org/apache/iceberg/DeleteFileIndexBenchmark.java
This PR refactors `DeleteFileIndexBenchmark`:
- Add `FileGenerationUtil` to be used in metadata benchmarks.
- Use `FileGenerationUtil` to generate files to speed up the initialization phase of the delete file index benchmark. Prior to this change, we were adding a few real files and cloning them. There is no real benefit of doing 25 real inserts per each partition, it just takes time.
- Use `FileGenerationUtil` to generate random metrics to mimic realistic scenarios. Prior to this change, we cloned the metrics and used identical values for all cloned files. This compressed very well but is not realistic.
=> Spark 3.5: Rework DeleteFileIndexBenchmark

core/src/main/java/org/apache/iceberg/util/PartitionSet.java, core/src/test/java/org/apache/iceberg/util/TestPartitionMap.java, core/src/test/java/org/apache/iceberg/util/TestPartitionSet.java
This PR fixes usage of `null` partitions in `PartitionSet`. Previously, it was possible to store null partitions for unpartitioned specs but we could not retrieve them back. The set returned `false` that was wrong.
=> Core: Fix null partitions in PartitionSet

flink/v1.17/flink/src/main/java/org/apache/iceberg/flink/source/IcebergSource.java, flink/v1.17/flink/src/main/java/org/apache/iceberg/flink/source/enumerator/ContinuousSplitPlannerImpl.java
This is to fix a connection pool issue that prevents IcebergSource to startup in batch mode. The root cause is that the FileIO is closed when the tableLoader is closed via the try-with-resources statements. We need multiple copies of the user tableLoader parameter to retrieve the table name and do split planning and to close the loader after each use. The fix is to utilize clone the table loader to that it can be opened/closed by the batch split planning mechanism. This patch has been manually verified.
=> Flink: Fix IcebergSource tableloader lifecycle management in batch mode

core/src/main/java/org/apache/iceberg/rest/RESTSessionCatalog.java, core/src/main/java/org/apache/iceberg/view/BaseMetastoreViewCatalog.java, core/src/test/java/org/apache/iceberg/view/ViewCatalogTests.java
currently depends on https://github.com/apache/iceberg/pull/7913
=> Core: Improve view/table detection when replacing a table/view

core/src/main/java/org/apache/iceberg/rest/RESTSessionCatalog.java, core/src/test/java/org/apache/iceberg/rest/TestRESTCatalog.java
The purpose of caching auth session for tables is mainly so that we can stop refreshing the session when it isn't used anymore
=> Core: Add table session cache

.github/workflows/labeler.yml
This reverts commit 1b80537e821b7bf901a5b221fc3bfe53c8d87794.
V5 has some issues (breaking changes). We might have to adopt the config file as per new requirements.
To unblock the PRs. We can revert the fix and analyze later. 
More info: https://github.com/actions/labeler/issues/710
=> Revert "Build: Bump actions/labeler from 4 to 5 (#9264)"

mr/build.gradle, mr/src/test/java/org/apache/iceberg/mr/TestCatalogs.java, mr/src/test/java/org/apache/iceberg/mr/hive/HiveIcebergTestUtils.java, mr/src/test/java/org/apache/iceberg/mr/hive/TestDeserializer.java, mr/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergFilterFactory.java, mr/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergOutputCommitter.java, mr/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergSerDe.java, mr/src/test/java/org/apache/iceberg/mr/hive/serde/objectinspector/TestIcebergBinaryObjectInspector.java, mr/src/test/java/org/apache/iceberg/mr/hive/serde/objectinspector/TestIcebergDateObjectInspector.java, mr/src/test/java/org/apache/iceberg/mr/hive/serde/objectinspector/TestIcebergDecimalObjectInspector.java, mr/src/test/java/org/apache/iceberg/mr/hive/serde/objectinspector/TestIcebergFixedObjectInspector.java, mr/src/test/java/org/apache/iceberg/mr/hive/serde/objectinspector/TestIcebergObjectInspector.java, mr/src/test/java/org/apache/iceberg/mr/hive/serde/objectinspector/TestIcebergRecordObjectInspector.java, mr/src/test/java/org/apache/iceberg/mr/hive/serde/objectinspector/TestIcebergTimeObjectInspector.java, mr/src/test/java/org/apache/iceberg/mr/hive/serde/objectinspector/TestIcebergTimestampObjectInspector.java, mr/src/test/java/org/apache/iceberg/mr/hive/serde/objectinspector/TestIcebergTimestampWithZoneObjectInspector.java, mr/src/test/java/org/apache/iceberg/mr/hive/serde/objectinspector/TestIcebergUUIDObjectInspector.java
Closes #9083 
The goal here is to switch all imports to Junit5 and to use AssertJ-style assertions.
All test cases except the ones using parameterized tests have been migrated. Once https://github.com/apache/iceberg/pull/9161 gets merged, I will make the necessary changes to migrate Parameterized test as well.
=> Switch to junit5 for mr

nessie/src/main/java/org/apache/iceberg/nessie/NessieCatalog.java, nessie/src/main/java/org/apache/iceberg/nessie/NessieIcebergClient.java, nessie/src/main/java/org/apache/iceberg/nessie/NessieTableOperations.java, nessie/src/main/java/org/apache/iceberg/nessie/NessieUtil.java, nessie/src/main/java/org/apache/iceberg/nessie/NessieViewOperations.java, nessie/src/main/java/org/apache/iceberg/nessie/UpdateableReference.java, nessie/src/test/java/org/apache/iceberg/nessie/BaseTestIceberg.java, nessie/src/test/java/org/apache/iceberg/nessie/TestBranchVisibility.java, nessie/src/test/java/org/apache/iceberg/nessie/TestNessieTable.java, nessie/src/test/java/org/apache/iceberg/nessie/TestNessieView.java, nessie/src/test/java/org/apache/iceberg/nessie/TestNessieViewCatalog.java
- Extend `NessieCatalog` with `BaseMetastoreViewCatalog`.
- Move some common code to `NessieUtil` for reusing between tables and views.
- Generalize `ViewCatalogTests` to reuse for Nessie catalog.
Fixes: https://github.com/apache/iceberg/issues/8696
=> Nessie: Support views for NessieCatalog

data/src/main/java/org/apache/iceberg/data/GenericFileWriterFactory.java, data/src/test/java/org/apache/iceberg/data/FileHelpers.java, data/src/test/java/org/apache/iceberg/data/TestGenericFileWriterFactory.java, data/src/test/java/org/apache/iceberg/io/TestFileWriterFactory.java, flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/source/TestMetadataTableReadableMetrics.java, flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/source/TestMetadataTableReadableMetrics.java, flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/source/TestMetadataTableReadableMetrics.java
This PR adds `GenericFileWriterFactory`, similar to `FlinkFileWriterFactory` and `SparkFileWriterFactory`. This is a new API that should be used in favor of methods in `FileAppenderFactory` for creating data, equality and position delete writers. Spark, for instance, has migrated to `FileWriterFactory` a long time ago.
This PR migrates all tests to use this API for writing test files and adds a new test suite.
=> Data: Add GenericFileWriterFactory

api/src/main/java/org/apache/iceberg/AppendFiles.java, core/src/main/java/org/apache/iceberg/FastAppend.java, core/src/main/java/org/apache/iceberg/MergingSnapshotProducer.java, core/src/test/java/org/apache/iceberg/TestFastAppend.java, core/src/test/java/org/apache/iceberg/TestMergeAppend.java, core/src/test/java/org/apache/iceberg/TestTransaction.java, docs/spark-procedures.md, spark/v3.2/spark/src/main/java/org/apache/iceberg/spark/SparkTableUtil.java, spark/v3.3/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestAddFilesProcedure.java, spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/SparkTableUtil.java, spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/procedures/AddFilesProcedure.java, spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestAddFilesProcedure.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/SparkTableUtil.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/procedures/AddFilesProcedure.java, spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestAddFilesProcedure.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/SparkTableUtil.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/procedures/AddFilesProcedure.java
This PR extends the idea from #8928 to `FastAppend` and `MergeAppend`, which are used in data imports and migration.
=> Core, Spark: Avoid manifest copies when importing data to V2 tables

hive-metastore/src/test/java/org/apache/iceberg/hive/HiveCreateReplaceTableTest.java, hive-metastore/src/test/java/org/apache/iceberg/hive/HiveMetastoreExtension.java, hive-metastore/src/test/java/org/apache/iceberg/hive/HiveTableBaseTest.java, hive-metastore/src/test/java/org/apache/iceberg/hive/TestCachedClientPool.java, hive-metastore/src/test/java/org/apache/iceberg/hive/TestHiveCatalog.java, hive-metastore/src/test/java/org/apache/iceberg/hive/TestHiveCommitLocks.java
This is mainly required for https://github.com/apache/iceberg/pull/8918 so that the extension doesn't always create the database and gives the test more control over when to create the database
=> Hive: Make HiveMetastoreExtension configurable

docs/spark-procedures.md
Doc for new feature: https://github.com/apache/iceberg/pull/9242 and https://github.com/apache/iceberg/pull/9243.
=> Add doc for rewriting manifest with spec id

api/src/main/java/org/apache/iceberg/exceptions/RuntimeIOException.java
I'd like to open this proposal to restore `RuntimeIOException` for continued use and remove the deprecation.
This was originally marked deprecated when java introduced the `UncheckedIOException` which initially seemed like a more standard replacement, but there are a few issues.
1.  UncheckedIOException requires a `cause`, which is not present in a number of usages of RuntimeIOException.  This complicates the code or requires us to change the exception handling.  For example:
```java 
if (!file.getParentFile().isDirectory() && !file.getParentFile().mkdirs()) {
throw new RuntimeIOException(
"Failed to create the file's directory at %s.", file.getParentFile().getAbsolutePath());
}
```
becomes
```java
if (!file.getParentFile().isDirectory() && !file.getParentFile().mkdirs()) {
throw new …
```
=> Restore RuntimeIOException for use

core/src/test/java/org/apache/iceberg/TestRemoveSnapshots.java, spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/actions/TestExpireSnapshotsAction.java, spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/actions/TestRemoveOrphanFilesAction.java, spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/actions/TestExpireSnapshotsAction.java, spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/actions/TestRemoveOrphanFilesAction.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/actions/TestExpireSnapshotsAction.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/actions/TestRemoveOrphanFilesAction.java
This fixes #8824 and other places where `HashSet` can be modified concurrently.
As found in https://github.com/apache/iceberg/actions/runs/7191749083/job/19586958583?pr=9273
```
TestRemoveOrphanFilesAction3 > orphanedFileRemovedWithParallelTasks FAILED
java.lang.AssertionError: Should delete 4 files expected:<4> but was:<3>
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.failNotEquals(Assert.java:835)
at org.junit.Assert.assertEquals(Assert.java:647)
at org.apache.iceberg.spark.actions.TestRemoveOrphanFilesAction.orphanedFileRemovedWithParallelTasks(TestRemoveOrphanFilesAction.java:306)
```
The check of `deleteThreads` has passed. That means delete function is working but `deleteFiles` is not correctly modified since `HashSet` is not thread-safe.
```
Assert.assertEquals( …
```
=> Test: Fix flaky tests which concurrently modify HashSet

README.md
I've updated the ReadMe's Status paragraph to be more inline with the reality today and hopefully won't have to be kept up-to-date going forward. Please let me know if there are any inaccuracies in the text, or stylistic changes anyone would like to see. Thank you.
Closes #9127
=> Modernize the readme's Status paragraph

build.gradle, core/src/test/java/org/apache/iceberg/catalog/CatalogTests.java, hive-metastore/src/main/java/org/apache/iceberg/hive/HiveCatalog.java, hive-metastore/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java, hive-metastore/src/test/java/org/apache/iceberg/hive/TestHiveCatalog.java
Currently HiveTests are not using the Core catalog tests. Ideally unlike other catalog [Nessie](https://github.com/apache/iceberg/blob/main/nessie/src/test/java/org/apache/iceberg/nessie/TestNessieCatalog.java) , [JDBC](https://github.com/apache/iceberg/blob/main/nessie/src/test/java/org/apache/iceberg/nessie/TestNessieCatalog.java), Hive should also extent the core [CatalogTests](https://github.com/apache/iceberg/blob/main/core/src/test/java/org/apache/iceberg/catalog/CatalogTests.java). 
Depends upon feedback other duplicate tests will be removed and remaining will be moved to this new class.
=> Hive: Refactor TestHiveCatalog tests to use the core CatalogTests

api/src/main/java/org/apache/iceberg/view/SQLViewRepresentation.java, core/src/main/java/org/apache/iceberg/view/BaseSQLViewRepresentation.java
This moves `SQLViewRepresentation` from `core` to the `api` module mainly so that it's easier usable in the context of https://github.com/apache/iceberg/pull/9247/files#r1419759456
=> API, Core: Move SQLViewRepresentation to API

api/src/main/java/org/apache/iceberg/view/View.java, core/src/main/java/org/apache/iceberg/view/BaseView.java, core/src/test/java/org/apache/iceberg/view/ViewCatalogTests.java
This change adds a `ViewRepresentation sqlFor(String dialect)` API which will resolve a representation based on the give dialect. The current implementation just aims for an exact search with a fallback to the first added representation in case an exact match does not exist.  If no SQL dialect exists, null is returned.
The intention of this API is so that engine integrations don't have to implement this same logic. If an engine wants to use a different dialect than what this API returns then they can still implement that.
=> API, Core: Add sqlFor API to views to handle basic resolution of dialect

api/src/main/java/org/apache/iceberg/util/CharSequenceSet.java, api/src/test/java/org/apache/iceberg/util/TestCharSequenceSet.java
The `equals` and `hashCode` behaviors in `CharSequenceSet` contradict the `Set` API, which prohibits wrapping these sets into unmodifiable wrappers in `CharSequenceMap#keySet`.
```
/**
* Compares the specified object with this set for equality.  Returns
* {@code true} if the specified object is also a set, the two sets
* have the same size, and every member of the specified set is
* contained in this set (or equivalently, every member of this set is
* contained in the specified set).  This definition ensures that the
* equals method works properly across different implementations of the
* set interface.
*
* @param o object to be compared for equality with this set
* @return {@code true} if the specified object is equal to this set
*/
boolean equals(Object o);
/**
* Returns the hash code …
```
=> API: Fix equals and hashCode in CharSequenceSet

core/src/main/java/org/apache/iceberg/view/BaseView.java, core/src/test/java/org/apache/iceberg/view/ViewCatalogTests.java
This makes the dialect check case insensitive https://github.com/apache/iceberg/pull/9247/files . Was an oversight, after I refactored the code, the case insensitive change mistakenly became case sensitive. This change also adds a test to catch this case.
=> Core: Make sqlFor case insensitive for dialect check

core/src/main/java/org/apache/iceberg/BaseMetadataTable.java, core/src/test/java/org/apache/iceberg/TestMetadataTableScans.java
`BaseFileRewriteCoordinator`, `ScanTaskSetManager` calls `table.uuid()` of metadata table multiple times for setting and reading from cache. So, uuid has to be consistent on each call for a given table. 
This issue was discovered during https://github.com/apache/iceberg/pull/9298
=> Core: Fix Metadata table's UUID

flink/v1.16/build.gradle, flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/source/TestIcebergSourceWithWatermarkExtractor.java, flink/v1.17/build.gradle, flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/source/TestIcebergSourceWithWatermarkExtractor.java, flink/v1.18/build.gradle, flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/source/TestIcebergSourceWithWatermarkExtractor.java
Fix most of the flakiness in `TestIcebergSourceWithWatermarkExtractor`.
Still #9308 is needed for the full fix
=> Flink: Fix TestIcebergSourceWithWatermarkExtractor flakiness

api/src/main/java/org/apache/iceberg/util/CharSequenceMap.java, core/src/main/java/org/apache/iceberg/DeleteFileIndex.java, core/src/main/java/org/apache/iceberg/util/ArrayUtil.java, core/src/main/java/org/apache/iceberg/util/ContentFileUtil.java, core/src/test/java/org/apache/iceberg/DeleteFileIndexTestBase.java, core/src/test/java/org/apache/iceberg/util/TestArrayUtil.java, core/src/test/java/org/apache/iceberg/util/TestPartitionMap.java, data/src/test/java/org/apache/iceberg/data/TestDataFileIndexStatsFilters.java, spark/v3.5/spark-extensions/src/jmh/java/org/apache/iceberg/DeleteFileIndexBenchmark.java
This PR optimizes our `DeleteFileIndex` to look up deletes by path if they are targeting a single data file. This change is one in the set of properly supporting an optional 1-1 mapping for data files and position deletes. This PR relies on stored boundaries. If they are the same, it means the full path was persisted. In the future, we may optimize this part by persisting extra metadata.
This PR adds a few new tests and relies on other existing tests. It also comes with a benchmark that did not complete in 5 minutes before.
```
Benchmark                                           (oneToOneMapping)  Mode  Cnt            Score            Error   Units
DeleteFileIndexBenchmark.buildIndexAndLookup                     true    ss   10            9.670 ±          0.251    s/op …
```
=> Core: Look up targeted position deletes by path

flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/source/IcebergSource.java, flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/source/enumerator/ContinuousSplitPlannerImpl.java, flink/v1.18/flink/src/main/java/org/apache/iceberg/flink/source/IcebergSource.java, flink/v1.18/flink/src/main/java/org/apache/iceberg/flink/source/enumerator/ContinuousSplitPlannerImpl.java
```
cp -r flink/v1.17/flink/src/main/java/org/apache/iceberg/flink/source/ flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/source/
cp -r flink/v1.17/flink/src/main/java/org/apache/iceberg/flink/source/ flink/v1.18/flink/src/main/java/org/apache/iceberg/flink/source/
```
Clean port
=> Flink: port #9173 to v1.16 and v1.18

spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/sql/TestSelect.java, spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/sql/TestSelect.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/sql/TestSelect.java
Follow up to https://github.com/apache/iceberg/pull/9238. Add tests for reading using the `tag_` and `branch_` identifiers.
=> Spark: Add tests for select using tag and branch identifier

core/src/main/java/org/apache/iceberg/PartitionsTable.java, spark/v3.2/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestDelete.java, spark/v3.3/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestDelete.java, spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestDelete.java, spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestDelete.java
Backport of https://github.com/apache/iceberg/pull/8969
=> Core: Scan only live entries in partitions table (#8969)

core/src/main/java/org/apache/iceberg/hadoop/HadoopCatalog.java, core/src/test/java/org/apache/iceberg/hadoop/TestHadoopCatalog.java
Make HadoopFileIO as default for Hadoop Catalog to initialize HadoopFileIO catalog configs similar to [NessieCatalog](https://github.com/apache/iceberg/blob/main/nessie/src/main/java/org/apache/iceberg/nessie/NessieCatalog.java#L123)
=> Core: Use properties while initializing default HadoopFileIO for Hadoop catalog.

core/src/main/java/org/apache/iceberg/jdbc/JdbcUtil.java, core/src/test/java/org/apache/iceberg/jdbc/TestJdbcCatalog.java
* JDBC catalog fix namespaceExists check
(cherry picked from commit 11608e10245875ca2972c1dba1c92182c16ec887)
=> [1.4.x] JDBC Catalog: Fix namespaceExists check with special characters (#8340)

core/src/main/java/org/apache/iceberg/BaseTransaction.java, core/src/test/java/org/apache/iceberg/TableTestBase.java, core/src/test/java/org/apache/iceberg/TestRemoveSnapshots.java, core/src/test/java/org/apache/iceberg/TestSequenceNumberForV2Table.java
This is a clean cherry-pick of #9182 to 1.4.x
Closes #9182
cc @Fokko
=> [1.4.x] Core: Expired Snapshot files in a transaction should be deleted

spark/v3.5/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/parser/extensions/IcebergSparkSqlExtensionsParser.scala
Now that the MERGE functionality lives in upstream Spark, this class isn't required anymore.
=> Spark 3.5: Remove UnresolvedIcebergTable

core/src/main/java/org/apache/iceberg/MergingSnapshotProducer.java, core/src/test/java/org/apache/iceberg/TestTransaction.java
With retries with conflicting manifest merges. This makes the caching a bit more defensive so cached emptied when cleaning up a commit.
=> Core: Fix missing delete files from transaction

flink/v1.18/flink/src/main/java/org/apache/iceberg/flink/source/reader/IcebergSourceSplitReader.java, flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/source/TestIcebergSourceWithWatermarkExtractor.java
Based on the discussion with @mas-chen and @stevenzwu, there is no need to implement split level watermark alignment for Iceberg source, because the IcebergSourceSplitReader only reads splits sequentially. When waiting for watermark alignment the SourceOperator will stop processing and recycling the fetched batches. This exhausts the  {@link ArrayPoolDataIteratorBatcher#pool} and the `currentReader.next()` call will be blocked even without split-level watermark alignment. Based on this the `pauseOrResumeSplits` and the `wakeUp` are left empty.
=> Flink: Empty implementation for pauseOrResumeSplits to prevent UnsupportedOperationException

open-api/rest-catalog-open-api.yaml
Updates the Rest Catalog Open API Spec to address: https://github.com/apache/iceberg/issues/8869
Slack discussion thread where the agreement has been reached regarding the required Spec update: https://apache-iceberg.slack.com/archives/C03LG1D563F/p1698767745835999
=> Add Description on Using a Separate Authorization Server

docs/spark-procedures.md
The document example says the parameter of `set_current_snapshot` like `tag`. But the correct parameter is `ref`.
From the source, the parameter shows `ref`.
https://github.com/apache/iceberg/blob/2eea697297a4c724a950a4bdc9dd29822ea90d8c/spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/procedures/SetCurrentSnapshotProcedure.java#L50
=> Docs: Nit-fix the parameter of set_current_snapshot procedure in the example

spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/data/AvroDataTest.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/data/GenericsHelpers.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/data/ParameterizedAvroDataTest.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/data/TestHelpers.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/data/TestOrcWrite.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/data/TestParquetAvroReader.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/data/TestParquetAvroWriter.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/data/TestSparkAvroEnums.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/data/TestSparkAvroReader.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/data/TestSparkDateTimes.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/data/TestSparkOrcReadMetadataColumns.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/data/TestSparkOrcReader.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/data/TestSparkParquetReadMetadataColumns.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/data/TestSparkParquetReader.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/data/TestSparkParquetWriter.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/data/TestSparkRecordOrcReaderWriter.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/data/parquet/vectorized/TestParquetDictionaryEncodedVectorizedReads.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/data/parquet/vectorized/TestParquetDictionaryFallbackToPlainEncodingVectorizedReads.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/data/parquet/vectorized/TestParquetVectorizedReads.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestAvroScan.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestDataFrameWrites.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestParquetScan.java
Since migrating Spark 3.5v to Junit5 is a large task, I'm splitting my work into multiple easy-to-review PR's, split by directory. 
This PR contains the Junit5 migration for Spark 3.5v for the `spark/data` directory, and any files that inherit from this directory.
Issue: #9086
TODO:
=> Spark 3.5: Migrate tests to JUnit5 in data directory

data/src/test/java/org/apache/iceberg/RecordWrapperTest.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/CatalogTestBase.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestBaseReader.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestChangelogReader.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestDataFrameWriterV2.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestDataSourceOptions.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestForwardCompatibility.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSourceHadoopTables.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSourceHiveTables.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSourceTablesBase.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSpark.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestInternalRowWrapper.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestMetadataTableReadableMetrics.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestPathIdentifier.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestReadProjection.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkAggregates.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkCatalogCacheExpiration.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkDataFile.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkReadMetrics.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkReadProjection.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkStagedScan.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkTable.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestStreamingOffset.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestStructuredStreaming.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestWriteMetricsConfig.java
This PR contains the part of the files to migrate for Spark 3.5v in the source directory. The remaining files will be migrated in a seperate PR.
Related to PR : #9341 
Issue: #9086 
TODO:
=> Spark 3:5 Migrate tests to JUnit5 in source directory

.palantir/revapi.yml, core/src/main/java/org/apache/iceberg/avro/ApplyNameMapping.java, core/src/main/java/org/apache/iceberg/avro/AvroSchemaUtil.java, core/src/main/java/org/apache/iceberg/avro/ProjectionDatumReader.java, core/src/main/java/org/apache/iceberg/mapping/NameMapping.java
This separates the logic to apply a name mapping from the logic to prune columns in Avro. This is some cleanup since name mapping shouldn't be mixed with column pruning.
=> Core: Add ApplyNameMapping for Avro

spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/CatalogTestBase.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/TestBaseWithCatalog.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestDataFrameWriterV2.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestDataSourceOptions.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestMetadataTableReadableMetrics.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkCatalogCacheExpiration.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkReadMetrics.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkStagedScan.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkTable.java
After reviewing/merging https://github.com/apache/iceberg/pull/9342 I realized that parameterized base classes should not have a constructor but rather have their parameters set via `@Parameter`. All other setup code should go into a `@BeforeEach` method to properly initialize the test environment
=> Spark 3.5: Remove constructor from parameterized base class

core/src/main/java/org/apache/iceberg/deletes/SortingPositionOnlyDeleteWriter.java
This PR migrates `SortingPositionOnlyDeleteWriter` to use `CharSequenceMap` to simplify the code. The new solution is essentially the same in terms of functionality and performance.
**Before**
```
Benchmark                                                                            Mode  Cnt  Score   Error  Units
ParquetWritersBenchmark.writeUnpartitionedClusteredPositionDeleteWriter                ss    5  1.682 ± 0.242   s/op
ParquetWritersBenchmark.writeUnpartitionedFanoutPositionDeleteWriter                   ss    5  2.949 ± 0.092   s/op
ParquetWritersBenchmark.writeUnpartitionedFanoutPositionDeleteWriterShuffled           ss    5  3.428 ± 0.089   s/op
```
**After**
```
Benchmark                                                                            Mode  Cnt  Score   Error  Units …
```
=> Core: Use CharSequenceMap for writing unordered deletes

api/src/main/java/org/apache/iceberg/expressions/NamedReference.java, api/src/main/java/org/apache/iceberg/types/Types.java
During the snapshot commit process of MergingSnapshotProducer, Iceberg tries to merge the manifest files to increase the planning performance. During operations like overwrite, MergingSnapshotProducer finds the matching manifest files by deleteExpression and rewrites the manifests by filtering out the deleted manifest entries.
https://github.com/apache/iceberg/blob/main/core/src/main/java/org/apache/iceberg/ManifestFilterManager.java#L330
While finding the matching manifests by deleteExpression, we found that the Schema is created every time the expression needs to be bound. This has proven very expensive when there are large number of manifest files (~25,000 manifest files) for a super wide table (~35,000 columns).
https://github.com/apache/iceberg/blob/main/api/src/main/java/org/apache/i …
=> Core: Optimize manifest evaluation for super wide tables

core/src/main/java/org/apache/iceberg/BaseUpdatePartitionSpec.java
This change removes an unused `sourceTransform` parameter in a helper method in the implementation of `UpdatePartitionSpec`.
=> Core: Remove unused sourceTransform parameter in helper method

flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/CatalogTestBase.java, flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/FlinkCatalogTestBaseJU5.java, flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/TestFlinkCatalogDatabase.java, flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/TestFlinkCatalogTablePartitions.java, flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/source/TestMetadataTableReadableMetrics.java
Base class creation of FlinkCatalogTestBase for the migration to JUnit5 in regards to https://github.com/apache/iceberg/issues/9079
=> Flink: Create CatalogTestBase for migration to JUnit5

data/src/main/java/org/apache/iceberg/data/TableMigrationUtil.java, docs/spark-procedures.md, spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestAddFilesProcedure.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/SparkTableUtil.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/procedures/AddFilesProcedure.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/procedures/ProcedureInput.java
Currently, only one thread is used to list files when importing a Spark table in `add_files` procedure. It can be very slow for a table or a partition with many files. This PR adds an argument `listing_parallelism` to `add_files` procedure such that multiple threads can be used to list files.
=> Spark 3.5: Parallelize reading files in add_files procedure

spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/actions/TestCreateActions.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/actions/TestDeleteReachableFilesAction.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/actions/TestExpireSnapshotsAction.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/actions/TestRemoveOrphanFilesAction.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/actions/TestRemoveOrphanFilesAction3.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteDataFilesAction.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteManifestsAction.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewritePositionDeleteFilesAction.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/actions/TestSparkFileRewriter.java
This PR contains the tests in spark/actions directory, now migrated to JUnit5.
Related to PR : #9341
Issue: #9086
=> Spark 3.5: Migrate tests to JUnit5 in actions directory

core/src/main/java/org/apache/iceberg/PartitionsTable.java, spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSourceTablesBase.java, spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSourceTablesBase.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSourceTablesBase.java
The record counts for delete-file are calculated wrong in ParitionTable. For example, we got the following strange results.
=> Core, Spark: Correct the delete record count for PartitionTable

spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/source/SparkWrite.java
Fixes #9172 
Fixes #8953 
Leaving in draft as I figure out how to repro this in our tests just so we're really confident this is the issue and the right fix.
Currently the output file path in Spark Streaming has the following components (excluding the partition component):
1.) The Spark queryID as a "operation key"
2.) The task ID of the writing task
3.) The partitionID
4.) a suffix, used for delete files.
The Spark Streaming DSV2 writer SPI passes in the partitionID, taskID, and the epochID. Currently, we ignore the epochID when constructing the writer.
Prior to #6569 this was not an issue because we had a random UUID per file so files wouldn't clobber over each other. 
After #6569 we intentionally replaced the random UUID with a queryID so we can track which query wrote the file. …
=> Spark Streaming: Fix clobbering of files across streaming epochs

spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/SparkWrite.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/source/SparkWrite.java
This change backports #9255 to Spark 3.3 and 3.4 to fix the clobbering of files over multiple epochs by including the epoch ID in the output file. For context, query IDs and task IDs can be reused when resuming a spark streaming job but epochIDs are only increasing over time (and if they're reused due to replay the files produced will be idempotent)
=> Spark 3.3, 3.4: Backport #9255 - Fix clobbering of files across epochs

flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/source/reader/IcebergSourceSplitReader.java, flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/source/TestIcebergSourceWithWatermarkExtractor.java, flink/v1.17/flink/src/main/java/org/apache/iceberg/flink/source/reader/IcebergSourceSplitReader.java, flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/source/TestIcebergSourceWithWatermarkExtractor.java
Clean backport of #9308 to Flink 1.17
In 1.16, the `pauseOrResumeSplits` is not needed, but backported the other parts, so the code similar between the Flink versions.
=> Flink: Backport #9308 to v1.17 and the relevant parts to v1.16

api/src/main/java/org/apache/iceberg/UpdateSchema.java
This change fixes the Javadoc on UpdateSchema#updateColumnDoc; previously it was referring to rename and now the JavaDoc reflects the actual operation being performed
=> API: Fix Javadoc on UpdateSchema#updateColumnDoc

core/src/main/java/org/apache/iceberg/CatalogUtil.java, core/src/test/java/org/apache/iceberg/hadoop/TestCatalogUtilDropTable.java
This PR attempt to include puffin stats files as part of CatalogUtil table cleanup
CC @RussellSpitzer @findepi
=> Core: remove statistic files in CatalogUtil:dropTableData

flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/source/TestIcebergSourceWithWatermarkExtractor.java, flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/source/TestIcebergSourceWithWatermarkExtractor.java, flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/source/TestIcebergSourceWithWatermarkExtractor.java
I've seen the following flakiness several times. This PR fixes it by disabling Flink classloader check.
```
TestIcebergSourceWithWatermarkExtractor > testThrottling FAILED
java.lang.AssertionError: 
Expecting
<CompletableFuture[Failed with the following stack trace:
java.lang.IllegalStateException: Trying to access closed classloader. Please check if you store classloaders directly or indirectly in static fields. If the stacktrace suggests that the leak occurs in a third party library and cannot be fixed immediately, you can disable this check with the configuration 'classloader.check-leaked-classloader'.
at org.apache.flink.util.FlinkUserCodeClassLoaders$SafetyNetWrapperClassLoader.ensureInner(FlinkUserCodeClassLoaders.java:184)
at …
```
=> Flink: Disable classloader check in TestIcebergSourceWithWatermarkExtractor to fix flakiness

core/src/main/java/org/apache/iceberg/CatalogUtil.java, core/src/test/java/org/apache/iceberg/hadoop/TestCatalogUtilDropTable.java
follow up from https://github.com/apache/iceberg/pull/9305#issuecomment-1864264195
cc: @dramaticlly, @amogh-jahagirdar, @nastra, @RussellSpitzer
=> Core: Remove partition statistics files during purge table

nessie/src/main/java/org/apache/iceberg/nessie/NessieCatalog.java, nessie/src/test/java/org/apache/iceberg/nessie/TestNessieCatalog.java
Other catalogs does the same and for some file system double slash in a path creates the problem.
=> Nessie: Strip trailing slash for warehouse location

spark/v3.5/spark/src/test/java/org/apache/iceberg/TaskCheckHelper.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/TestDataFileSerialization.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/TestFileIOSerialization.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/TestHadoopMetricsContextSerialization.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/TestManifestFileSerialization.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/TestScanTaskSerialization.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/TestTableSerialization.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/ValidationHelpers.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/TestBase.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/TestBaseWithCatalog.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/TestChangelogIterator.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/TestFileRewriteCoordinator.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/TestFunctionCatalog.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/TestSpark3Util.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/TestSparkCachedTableCatalog.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/TestSparkCatalogOperations.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/TestSparkCompressionUtil.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/TestSparkDistributionAndOrderingUtil.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/TestSparkFilters.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/TestSparkSchemaUtil.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/TestSparkSessionCatalog.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/TestSparkTableUtil.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/TestSparkV2Filters.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/TestSparkValueConverter.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/TestSparkWriteConf.java
This PR migrates remaining tests in Spark3.5 to JUnit5. 
Issue: #9086
=> Spark 3.5: Remaining tests migrated to Junit5 

spark/v3.4/spark-extensions/src/main/scala/org/apache/iceberg/spark/extensions/IcebergSparkSessionExtensions.scala, spark/v3.4/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/analysis/ResolveViews.scala, spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestViews.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/SparkCatalog.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/source/SparkView.java, spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/SparkCatalogConfig.java, spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/SparkTestBaseWithCatalog.java, spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkCatalog.java
This backports https://github.com/apache/iceberg/pull/9340 to Spark 3.4
=> Spark 3.4: Add support for reading Iceberg views

parquet/src/main/java/org/apache/iceberg/parquet/ParquetConversions.java, parquet/src/main/java/org/apache/iceberg/parquet/ParquetDictionaryRowGroupFilter.java, spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSourceTablesBase.java, spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSourceTablesBase.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestIcebergSourceTablesBase.java
This fixes https://github.com/apache/iceberg/issues/8990
=> Parquet: Support reading INT96 column in row group filter

build.gradle, core/src/test/java/org/apache/iceberg/TestBase.java, core/src/test/java/org/apache/iceberg/TestCreateSnapshotEvent.java, core/src/test/java/org/apache/iceberg/TestManifestReader.java, data/src/test/java/org/apache/iceberg/io/TestGenericSortedPosDeleteWriter.java
This fixes https://github.com/apache/iceberg/issues/9073 and also converts a few old tests to the new Base class using the new way of parameterization
=> Core: Add JUnit5 version of TableTestBase

api/src/main/java/org/apache/iceberg/util/CharSequenceSet.java, api/src/main/java/org/apache/iceberg/util/CharSequenceWrapper.java, core/src/main/java/org/apache/iceberg/DeleteFileIndex.java, core/src/main/java/org/apache/iceberg/avro/AvroWithPartnerByStructureVisitor.java, core/src/main/java/org/apache/iceberg/deletes/SortingPositionOnlyDeleteWriter.java
`./gradlew clean build -x test` is reporting some warnings as seen below. 
After this PR, `./gradlew clean build -x test` is green.
=> API, Core: Fix errorprone warnings

.github/labeler.yml, core/src/main/java/org/apache/iceberg/avro/AvroSchemaUtil.java, core/src/main/java/org/apache/iceberg/avro/TypeToSchema.java, core/src/main/java/org/apache/iceberg/data/avro/DecoderResolver.java, kafka-connect/build.gradle, kafka-connect/kafka-connect-events/src/main/java/org/apache/iceberg/connect/events/AvroUtil.java, kafka-connect/kafka-connect-events/src/main/java/org/apache/iceberg/connect/events/CommitComplete.java, kafka-connect/kafka-connect-events/src/main/java/org/apache/iceberg/connect/events/CommitToTable.java, kafka-connect/kafka-connect-events/src/main/java/org/apache/iceberg/connect/events/DataComplete.java, kafka-connect/kafka-connect-events/src/main/java/org/apache/iceberg/connect/events/DataWritten.java, kafka-connect/kafka-connect-events/src/main/java/org/apache/iceberg/connect/events/Event.java, kafka-connect/kafka-connect-events/src/main/java/org/apache/iceberg/connect/events/Payload.java, kafka-connect/kafka-connect-events/src/main/java/org/apache/iceberg/connect/events/PayloadType.java, kafka-connect/kafka-connect-events/src/main/java/org/apache/iceberg/connect/events/StartCommit.java, kafka-connect/kafka-connect-events/src/main/java/org/apache/iceberg/connect/events/TableReference.java, kafka-connect/kafka-connect-events/src/main/java/org/apache/iceberg/connect/events/TopicPartitionOffset.java, kafka-connect/kafka-connect-events/src/test/java/org/apache/iceberg/connect/events/EventSerializationTest.java, kafka-connect/kafka-connect-events/src/test/java/org/apache/iceberg/connect/events/EventTestUtil.java, settings.gradle
We (Tabular) would like to submit our Iceberg Kafka Connect sink connector to the Iceberg project. Kafka Connect is a popular, efficient, and easy to use framework for reading from and writing to Kafka. This sink gives Iceberg users another option for landing data from Kafka into Iceberg tables. Having the backing of the Iceberg community will help it evolve and improve over time.
The sink codebase is on the larger side, so the thought was to break the submission into different PRs to make it easier to review. This initial PR includes the starting build setup and the project for the Avro event data structures.
The original repo can be found at https://github.com/tabular-io/iceberg-kafka-connect. Some design docs can be found in the `docs` directory, and that includes an explanation of …
=> Kafka Connect: Initial project setup and event data structures

spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/sql/PartitionedWritesTestBase.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/sql/TestAggregatePushDown.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/sql/TestAlterTable.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/sql/TestCreateTable.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/sql/TestCreateTableAsSelect.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/sql/TestDeleteFrom.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/sql/TestDropTable.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/sql/TestFilterPushDown.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/sql/TestNamespaceSQL.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/sql/TestPartitionedWrites.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/sql/TestPartitionedWritesAsSelect.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/sql/TestPartitionedWritesToBranch.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/sql/TestPartitionedWritesToWapBranch.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/sql/TestRefreshTable.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/sql/TestSelect.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/sql/TestSparkBucketFunction.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/sql/TestSparkDaysFunction.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/sql/TestSparkHoursFunction.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/sql/TestSparkMonthsFunction.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/sql/TestSparkTruncateFunction.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/sql/TestSparkYearsFunction.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/sql/TestStoragePartitionedJoins.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/sql/TestTimestampWithoutZone.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/sql/TestUnpartitionedWrites.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/sql/TestUnpartitionedWritesToBranch.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/sql/UnpartitionedWritesTestBase.java
This PR migrates the tests in spark/sql directory to JUnit5.
Issue: #9086
=> Spark 3.5: Migrate tests in SQL directory to JUnit5

flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/FlinkReadConf.java, flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/FlinkReadOptions.java, flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/source/IcebergSource.java, flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/source/ScanContext.java, flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/TestHelpers.java, flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/source/TestIcebergSourceSql.java, flink/v1.17/flink/src/main/java/org/apache/iceberg/flink/FlinkReadConf.java, flink/v1.17/flink/src/main/java/org/apache/iceberg/flink/FlinkReadOptions.java, flink/v1.17/flink/src/main/java/org/apache/iceberg/flink/source/IcebergSource.java, flink/v1.17/flink/src/main/java/org/apache/iceberg/flink/source/ScanContext.java, flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/TestHelpers.java, flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/source/TestIcebergSourceSql.java
Flink: Backports the Watermark Read Options to 1.17 and 1.16
The patch was cleanly applied to both 1.17 and 1.16
<b>source:</b>
``` git diff --no-index  flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/source  flink/v1.18/flink/src/main/java/org/apache/iceberg/flink/source```
brings some changes unrelated to this PR
```git diff --no-index  flink/v1.17/flink/src/main/java/org/apache/iceberg/flink/source  flink/v1.18/flink/src/main/java/org/apache/iceberg/flink/source```
came out clean
<b>test:</b>
``` git diff --no-index  flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/source  flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/source```
brings some changes on unrelated to this PR
```git diff --no-index  flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/source …
```
=> Backporting Flink: Watermark Read Options to 1.17 and 1.16

nessie/src/main/java/org/apache/iceberg/nessie/NessieIcebergClient.java
`table()` in `NessieIcebergClient` was renamed to `fetchContent()` with generic functionality while adding the view support for NessieCatalog. 
Nessie doesn't have to maintain compatibility as per https://iceberg.apache.org/contribute/#minor-version-deprecations-discretionary. 
But while bumping Iceberg version at Trino side (https://github.com/trinodb/trino/pull/20308), we concluded that it will be cleaner to have these table() and view() API.
=> Nessie: Add table() and view() API to NessieIcebergClient

data/src/test/java/org/apache/iceberg/data/DeleteReadTests.java, data/src/test/java/org/apache/iceberg/data/TestGenericReaderDeletes.java, flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/source/TestFlinkInputFormatReaderDeletes.java, flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/source/TestFlinkReaderDeletesBase.java, flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/source/TestIcebergSourceReaderDeletes.java, flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/source/TestFlinkInputFormatReaderDeletes.java, flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/source/TestFlinkReaderDeletesBase.java, flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/source/TestIcebergSourceReaderDeletes.java, flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/source/TestFlinkInputFormatReaderDeletes.java, flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/source/TestFlinkReaderDeletesBase.java, flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/source/TestIcebergSourceReaderDeletes.java, mr/src/test/java/org/apache/iceberg/mr/TestHelper.java, mr/src/test/java/org/apache/iceberg/mr/TestInputFormatReaderDeletes.java, spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkReaderDeletes.java, spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkReaderDeletes.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkReaderDeletes.java
This PR contains DeleteReadTests, its subclasses and all related helper files changed to JUnit5 migration.
Context: [PR comment](https://github.com/apache/iceberg/pull/9380#discussion_r1436255413)
`DeleteReadTests` is inherited by files in Flink, MR, and Data. Migrating `DeleteReadTests` to JUnit5 needs changes to all its subclasses. 
These subclasses also depend on `GenericAppenderHelper`, `TestTables` & `TestHelper`, which are in JUnit4. 
Solution:
To maintain compatibility between subclasses(now JUnit5), helper files and its dependents (still JUnit4), the helper files now use java.nio.file.Path instead `TemporaryFolder`
=> Spark, Flink: Migrate DeleteReadTests and its subclasses to JUnit5

spark/v3.5/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/analysis/ResolveViews.scala, spark/v3.5/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/plans/logical/views/ResolvedV2View.scala, spark/v3.5/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/ExtendedDataSourceV2Strategy.scala, spark/v3.5/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/RenameV2ViewExec.scala, spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestViews.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/SparkCatalog.java
This is based on https://github.com/apache/iceberg/pull/9340 and adds support for resolving and renaming views
=> Spark: Support renaming views

flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/TestHelpers.java, flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/source/TestFlinkInputFormat.java, flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/source/TestFlinkScan.java, flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/source/TestFlinkScanSql.java, flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/source/TestFlinkSource.java, flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/source/TestIcebergSourceBounded.java, flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/source/TestIcebergSourceBoundedSql.java
This ports the changes that were done for Flink 1.17 in https://github.com/apache/iceberg/pull/9185 and also fixes the current CI failures for Flink 1.18.
It's a clean port with one additional change around `TestHelpers`, where https://github.com/apache/iceberg/commit/22b95dc70eb46e82a0d51fd4cfb71ad4cbdf946a#diff-2ad5510e64472ce2b1c2983963ee09be1a59bdaedf5bdd443527154e8b632b8bR465 is being removed, since it's not required. That way `TestHelpers` is aligned  across Flink versions
=> Flink 1.18: Create JUnit5 version of TestFlinkScan

spark/v3.5/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/analysis/ResolveViews.scala, spark/v3.5/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/analysis/RewriteViewCommands.scala, spark/v3.5/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/parser/extensions/IcebergSparkSqlExtensionsParser.scala, spark/v3.5/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/plans/logical/views/DropIcebergView.scala, spark/v3.5/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/DropV2ViewExec.scala, spark/v3.5/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/ExtendedDataSourceV2Strategy.scala, spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestViews.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/SparkCatalog.java
This PR introduces DROP support for Iceberg views and requires a `pre-substitution` batch in 
`IcebergSparkSqlExtensionsParser` because `ResolveSessionCatalog` exits early in https://github.com/apache/spark/blob/branch-3.5/sql/core/src/main/scala/org/apache/spark/sql/catalyst/analysis/ResolveSessionCatalog.scala#L224-L229 for V2 commands
=> Spark: Support dropping views

flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/TestHelpers.java, flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/source/TestFlinkInputFormat.java, flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/source/TestFlinkScan.java, flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/source/TestFlinkScanSql.java, flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/source/TestFlinkSource.java, flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/source/TestIcebergSourceBounded.java, flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/source/TestIcebergSourceBoundedSql.java
This is a clean backport of the changes that were done for Flink 1.17 in https://github.com/apache/iceberg/pull/9185
=> Flink 1.16: Create JUnit5 version of TestFlinkScan

parquet/src/main/java/org/apache/iceberg/parquet/Parquet.java
Iceberg originally plugged in custom object models using Parquet's `ReadSupport` API, but that API wasn't able to handle filtering without reading the Parquet footer multiple times. Support has been carried forward, but there should be no need for it in 2.0.
=> Parquet: Deprecate readSupport and callInit in the read builder

api/src/main/java/org/apache/iceberg/types/TypeUtil.java, core/src/main/java/org/apache/iceberg/SystemConfigs.java, core/src/main/java/org/apache/iceberg/deletes/Deletes.java, core/src/main/java/org/apache/iceberg/deletes/EmptyPositionDeleteIndex.java, core/src/main/java/org/apache/iceberg/deletes/PositionDeleteIndex.java, core/src/main/java/org/apache/iceberg/deletes/PositionDeleteIndexUtil.java, core/src/main/java/org/apache/iceberg/util/ThreadPools.java, data/src/main/java/org/apache/iceberg/data/BaseDeleteLoader.java, data/src/main/java/org/apache/iceberg/data/DeleteFilter.java, data/src/main/java/org/apache/iceberg/data/DeleteLoader.java, spark/v3.5/build.gradle, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/SparkConfParser.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/SparkExecutorCache.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/SparkSQLProperties.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/source/BaseReader.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/source/SerializableTableWithSize.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/Employee.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/TestSparkExecutorCache.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/TestSparkWriteConf.java
This PR has code to parallelize reading of deletes and enable caching them on executors.
I also have a follow-up change to assign tasks for one partition to the same executor, similar to `KafkaRDD`. There is no way to express task affinity so we can only rely on task locality. The solution in `KafkaRDD` is simple to implement but won't work well if dynamic allocation is enabled (so it should be hidden under a flag).
More thoughts in [this](https://docs.google.com/document/d/1M4L6o-qnGRwGhbhkW8BnravoTwvCrJV8VvzVQDRJO5I) doc.
=> API, Core, Spark 3.5: Parallelize reading of deletes and cache them on executors

.github/workflows/stale.yml
We have so many issues that only latest ones are checked for staleness due to rate limit.
=> Check stale issues in ascending order

docs/java-api-quickstart.md
=> Docs: Fix typo in tag reading example

core/src/main/java/org/apache/iceberg/hadoop/HadoopTableOperations.java, core/src/test/java/org/apache/iceberg/hadoop/TestHadoopCommits.java
=> Core: Fix lock acquisition logic in HadoopTableOperations rename

site/mkdocs.yml
The community link works only on top-level site links. Link this to the static site for now, eventually we need to consider a site-wide variable solution but that's not important for now.
=> Fix community link

.baseline/eclipse/dynamic/dotfile.checkstyle, .github/ISSUE_TEMPLATE/iceberg_bug_report.yml, .github/ISSUE_TEMPLATE/iceberg_improvement.yml, .github/ISSUE_TEMPLATE/iceberg_question.yml, dev/.rat-excludes, dev/check-license
This PR does:
- upgrade to Apache RAT 0.16
- add `--scan-hidden-directories` option
- add ASF header where missing
- add new excluded file from RAT check
Closes #9494
=> Build: Upgrade to Apache RAT 0.16, scanning hidden directories and adding missing ASF header

spark/v3.4/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/analysis/ResolveViews.scala, spark/v3.4/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/analysis/RewriteViewCommands.scala, spark/v3.4/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/parser/extensions/IcebergSparkSqlExtensionsParser.scala, spark/v3.4/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/plans/logical/views/DropIcebergView.scala, spark/v3.4/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/plans/logical/views/ResolvedV2View.scala, spark/v3.4/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/DropV2ViewExec.scala, spark/v3.4/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/ExtendedDataSourceV2Strategy.scala, spark/v3.4/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/RenameV2ViewExec.scala, spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestViews.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/SparkCatalog.java
This backports https://github.com/apache/iceberg/pull/9421 to Spark 3.4
=> Spark 3.4: Support dropping views

docs/spark-writes.md, spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/sql/TestCreateTableAsSelect.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/sql/TestCreateTableAsSelect.java
=> Spark: Add distribution mode not respected for CTAS/RTAS before 3.5.0

gradle/libs.versions.toml
When running into this issue, the build used Flink 1.18.0. I've noticed that we were silently using Flink 1.18.1 because a new patch version was just released, which caused a [test to fail](https://github.com/apache/iceberg/actions/runs/7538529758/job/20520887186). This is because of how `strictly` and `prefer` (or even `require`) version definitions work.
According to https://docs.gradle.org/current/userguide/rich_versions.html Gradle would select a patch version as long as it matches the version range defined in `strictly`, which isn't necessarily what we want for those libraries.
I've changed them all to not use version ranges.
=> Build: Define strict version for Flink / Jackson / Hive2 / Tez 0.8

core/src/main/java/org/apache/iceberg/actions/RewriteDataFilesCommitManager.java, core/src/main/java/org/apache/iceberg/actions/RewritePositionDeletesCommitManager.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/actions/BaseSnapshotUpdateSparkAction.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/actions/RewriteDataFilesSparkAction.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/actions/RewritePositionDeleteFilesSparkAction.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteDataFilesAction.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewritePositionDeleteFilesAction.java
When working with `RewriteDataFiles`, I noticed that the snapshot properties cannot be set via `snapshotProperty(String, String)`.  This PR will fix that issue by propagating snapshot properties into `RewriteDataFilesCommitManager` or `RewritePositionDeletesCommitManager` and all the way down to `RewriteFiles`.
=> Spark: propagate snapshot properties for RewriteDataFiles and RewritePositionDeleteFiles

docs/spark-procedures.md, spark/v3.3/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestCreateChangelogViewProcedure.java, spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/procedures/CreateChangelogViewProcedure.java, spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestCreateChangelogViewProcedure.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/procedures/CreateChangelogViewProcedure.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/procedures/CreateChangelogViewProcedure.java
This is needed for 1.5.0 release as it removed the deprecated fields.
=> Spark: backport #8656 and update docs

spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkReaderDeletes.java, spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkReaderDeletes.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkReaderDeletes.java
=> Spark: Fix flaky TestSparkReaderDeletes tests due to metric not found

api/src/main/java/org/apache/iceberg/exceptions/NoSuchViewException.java
Similar to `NoSuchTableException`, this exception should also be marked as `CleanableFailure`
=> Core: Mark NoSuchViewException as CleanableFailure

docs/flink-writes.md, site/docs/docs/nightly/docs/flink-writes.md
fix #9527 
This pull request corrects the spelling of "gauge" in the following files:
- update docs/flink-writes.md
- update site/docs/docs/nightly/docs/flink-writes.md
=> Docs: Correct the spelling of "gauge"

.github/workflows/stale.yml
With the default value 30 of  `operations-per-run`, actually only 15 issues can be checked daily for staleness. 
```
Starting the stale action process...
Processing the batch of issues  #1  containing  100  issues...
[#41] Issue #41
[#44] Issue #44
[#76] Issue #76
[#81] Issue #81
[#96] Issue #96
[#116] Issue #116
[#118] Issue #118
[#127] Issue #127
[#128] Issue #128
[#168] Issue #168
[#189] Issue #189
[#193] Issue #193
[#257] Issue #257
[#274] Issue #274
[#345] Issue #345
Warning: No more operations left! Exiting...
Warning: If you think that not enough issues were processed you could try to increase the quantity related to the  operations-per-run (​[https://github.com/actions/stale#operations-per-run​)](https://github.com/actions/stale#operations-per-run%E2%80%8B))  option which is …
```
=> Infra: Increase operations-per-run in stale action to 100

gradle/libs.versions.toml
This needs to be reverted due to a NPE, which has been fixed by https://github.com/apache/httpcomponents-client/commit/9e3d79bedeee494d24bdb03cc598bae5184a3abf but hasn't been released yet.
This reverts commit 3112ec91617ef080604f47ac92c255b517458522.
```
Cannot invoke "org.apache.hc.client5.http.io.ManagedHttpClientConnection.isConsistent()" because "conn" is null
java.lang.NullPointerException: Cannot invoke "org.apache.hc.client5.http.io.ManagedHttpClientConnection.isConsistent()" because "conn" is null
at org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager.release(PoolingHttpClientConnectionManager.java:412)
at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.discardEndpoint(InternalExecRuntime.java:246)
at …
```
=> Revert "Build: Bump org.apache.httpcomponents.client5:httpclient5 (#9260)"

api/src/main/java/org/apache/iceberg/ManageSnapshots.java, core/src/main/java/org/apache/iceberg/UpdateSnapshotReferencesOperation.java, core/src/test/java/org/apache/iceberg/TestSnapshotManager.java, spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestFastForwardBranchProcedure.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/procedures/FastForwardBranchProcedure.java
Fixes #8849 
This change adds a `fastForwardOrCreate` API which will perform a fast forward of the `from` branch if it exists; otherwise `from` will be created and pointing towards what `to` references.
This change also integrates the API with the Spark fast forward procedure by default. Technically this is a behavior change but I think it is arguable that the  previous behavior was  a bug/incorrect behavior so we should change that.
Alternatives to this include:
1.) no new API, do a try/catch of fast forward and in case it fails attempt to do a creation. I think the issue there beyond being a little messy is that it forces clients/integrations to have to do that everywhere. 
2.) No new API, Change the `fastForward` API behavior to do a creation by default. I can see the merit because …
=> API, Core, Spark: Change behavior of fastForward/replace to create the from branch if it does not exist

baseline.gradle, data/src/main/java/org/apache/iceberg/data/BaseDeleteLoader.java
=> Build: Fix errorprone warning

spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRemoveOrphanFilesProcedure.java, spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/sql/TestDropTable.java, spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRemoveOrphanFilesProcedure.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/sql/TestDropTable.java
Since https://issues.apache.org/jira/browse/SPARK-43203 has been fixed in Spark 3.4.2 and 3.5.0, we can enable drop table with purge in tests now.
=> Spark 3.4, 3.5: Enable drop table with purge in tests

aws/src/integration/java/org/apache/iceberg/aws/s3/TestS3FileIOIntegration.java
This PR updates the existing test to check `S3FileIO` works even with the `CLIENT_FACTORY` is not set. This update ensures the two tests below work
- `testS3FileIOWithDefaultAwsClientFactoryImpl` - checks with `DefaultAwsClientFactory` 
- `testS3FileIOWithS3FileIOAwsClientFactoryImpl` - checks with `DefaultS3FileIOAwsClientFactory`
Currently the existing tests `testS3FileIOWithDefaultAwsClientFactoryImpl ` and `testS3FileIOWithS3FileIOAwsClientFactoryImpl` are duplicated.
=> AWS: Update S3FileIO test to run when CLIENT_FACTORY is not set

aws/src/integration/java/org/apache/iceberg/aws/glue/TestGlueCatalogNamespace.java, aws/src/integration/java/org/apache/iceberg/aws/glue/TestGlueCatalogTable.java, aws/src/main/java/org/apache/iceberg/aws/glue/GlueCatalog.java, aws/src/main/java/org/apache/iceberg/aws/glue/IcebergToGlueConverter.java, aws/src/test/java/org/apache/iceberg/aws/glue/TestIcebergToGlueConverter.java
Fixes https://github.com/apache/iceberg/issues/9462
=> AWS: Support setting description for Glue table

spark/v3.4/spark-extensions/src/main/scala/org/apache/iceberg/spark/extensions/IcebergSparkSessionExtensions.scala, spark/v3.4/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/analysis/CheckViews.scala, spark/v3.4/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/analysis/ResolveViews.scala, spark/v3.4/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/analysis/RewriteViewCommands.scala, spark/v3.4/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/plans/logical/views/CreateIcebergView.scala, spark/v3.4/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/CreateV2ViewExec.scala, spark/v3.4/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/ExtendedDataSourceV2Strategy.scala, spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestViews.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/SparkCatalog.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/source/SparkView.java
This is backporting #9423 to Spark 3.4. The error msg type `CREATE_VIEW_COLUMN_ARITY_MISMATCH` and `INVALID_TEMP_OBJ_REFERENCE` doesn't exist in Spark 3.4, so I backported the underlying error msg directly
=> Spark 3.4: Support creating views via SQL

spark/v3.3/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMerge.java, spark/v3.4/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/analysis/RewriteMergeIntoTable.scala, spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMerge.java, spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMerge.java
Fixes https://github.com/apache/iceberg/issues/9555
=>   Spark 3.4: Fix writing of default values in CoW for rows with NULL columns which are unmatched

.asf.yaml, site/dev/deploy.sh
This PR moves us to the updated documentation project to bring the Iceberg website and documentation back to the main repository. Related PRs: #8659, #8912, #8917, and #8919.
1. Revert [adding the ASF site publish indicator](https://github.com/apache/iceberg-docs/pull/36) from the apache/iceberg-docs repository. **This step must happen first!** https://github.com/apache/iceberg-docs/pull/308
1. Merge this PR:
1. Update the deploy script to [point to the `asf-site` branch](https://github.com/bitsondatadev/iceberg/blob/new-docs-switch/site/dev/deploy.sh#L23) instead of the default `gh-pages` branch.
1. Revert [removing the ASF site publish indicator](https://github.com/apache/iceberg/pull/4045) from the apache/iceberg repository to indicate ASF infra that this repository's `asf-site` branch …
=> New docs switch

spark/v3.5/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/analysis/RewriteViewCommands.scala, spark/v3.5/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/plans/logical/views/ShowIcebergViews.scala, spark/v3.5/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/DescribeV2ViewExec.scala, spark/v3.5/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/ExtendedDataSourceV2Strategy.scala, spark/v3.5/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/ShowCreateV2ViewExec.scala, spark/v3.5/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/ShowV2ViewPropertiesExec.scala, spark/v3.5/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/ShowV2ViewsExec.scala, spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestViews.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/SparkCatalog.java
This adds support for:
* `DESCRIBE <viewName>` / `DESCRIBE EXTENDED <viewName>`
* `SHOW VIEWS` / `SHOW VIEWS LIKE <pattern>`
* `SHOW TBLPROPERTIES <viewName>`
* `SHOW CREATE TABLE <viewName>`
=> Spark: Add support for describing/showing views

api/src/main/java/org/apache/iceberg/expressions/ValueAggregate.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/sql/TestAggregatePushDown.java
Currently, aggregation pushdowns on struct fields fail due to casting errors because in certain cases (e.g. optional field in struct) the accessor visitor construct a WrappedPositionAccessor when visiting the field. This WrappedPositionAccessor has an expectation that the element it's accessing is a `StructLike` but for aggregation pushdown this does not apply (the top level element is a Java type). 
Since there's always a single value I think we should be able to just read the evaluated value without actually performing any term evaluation.
=> API, Spark: Fix aggregation pushdown on struct fields

open-api/rest-catalog-open-api.py, open-api/rest-catalog-open-api.yaml
Table statistics were added in https://github.com/apache/iceberg/pull/5450 and it would be helpful to have them in the OpenAPI spec for REST catalog implementations that don't use the Java parsers from Iceberg.
=> Open-API: Add table updates for statistics

flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/CatalogTestBase.java, flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/TestFlinkCatalogDatabase.java, flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/TestFlinkCatalogTablePartitions.java, flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/source/TestMetadataTableReadableMetrics.java, flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/CatalogTestBase.java, flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/TestFlinkCatalogDatabase.java, flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/TestFlinkCatalogTablePartitions.java, flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/source/TestMetadataTableReadableMetrics.java
Both 1.17 and 1.16 patch came out clean
=> Flink: Backport #9364 to 1.16 and 1.17 for Create CatalogTestBase for migration to JUnit5

spark/v3.5/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/analysis/ResolveViews.scala, spark/v3.5/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/analysis/RewriteViewCommands.scala, spark/v3.5/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/analysis/ViewUtil.scala, spark/v3.5/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/AlterV2ViewSetPropertiesExec.scala, spark/v3.5/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/AlterV2ViewUnsetPropertiesExec.scala, spark/v3.5/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/ExtendedDataSourceV2Strategy.scala, spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestViews.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/SparkCatalog.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/source/SparkView.java
This adds support for the below `ALTER` cases as defined in https://spark.apache.org/docs/latest/sql-ref-syntax-ddl-alter-view.html:
* `ALTER VIEW <viewName> SET TBLPROPERTIES (...)`
* `ALTER VIEW <viewName> UNSET TBLPROPERTIES (...)`
=> Spark: Support altering view properties

spark/v3.5/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/analysis/CheckViews.scala, spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestViews.java
`ALTER VIEW <viewName> AS <query>` doesn't allow to preserve column aliases and column comment when the underlying query is changed, which can lead to unexpected behavior. For now it's better to use `CREATE OR REPLACE VIEW` as that is more explicit when the schema of the view is defined with column aliases/comments.
PS: Tests will pass once the `RewriteViewCommands` changes from #9582 are merged
=> Spark: Throw exception on `ALTER VIEW <viewName> AS <query>`

spark/v3.4/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/analysis/CheckViews.scala, spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestViews.java
This backports #9510 to Spark 3.4
=> Spark 3.4: Throw exception on `ALTER VIEW <viewName> AS <query>`

spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/actions/RewriteManifestsSparkAction.java, spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteManifestsAction.java
This PR cherry-picks #9015 to Spark 3.4.
=> Spark 3.4: Fix rewriting manifests for evolved unpartitioned V1 tables

spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMergeOnReadDelete.java, spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMergeOnReadMerge.java, spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMergeOnReadUpdate.java, spark/v3.4/spark/src/jmh/java/org/apache/iceberg/spark/source/WritersBenchmark.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/SparkWriteConf.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/SparkWriteOptions.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/source/SparkPositionDeletesRewrite.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/source/SparkPositionDeltaWrite.java, spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/TestSparkWriteConf.java, spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewritePositionDeleteFilesAction.java
This PR cherry-picks applicable parts of PR #9384 to Spark 3.4.
=> Spark 3.4: Support file and partition delete granularity

spark/v3.5/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/CreateV2ViewExec.scala, spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestViews.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/SparkCatalog.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/SupportsReplaceView.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/source/SparkView.java
Spark's `ViewCatalog` API doesn't have a `replace()` in 3.5 as it was only introduced later. Therefore we're bypassing Spark's `ViewCatalog` so that we can keep the view's history after executing a `CREATE OR REPLACE`
=> Spark: Bypass Spark's ViewCatalog API when replacing a view

spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/SparkContentFile.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/SparkDeleteFile.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/actions/RewriteManifestsSparkAction.java, spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteManifestsAction.java, spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkDataFile.java
This PR cherry-picks PR #9020 to Spark 3.4.
=> Spark 3.4: Extend action for rewriting manifests to support deletes

spark/v3.4/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/CreateV2ViewExec.scala, spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestViews.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/SparkCatalog.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/SupportsReplaceView.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/source/SparkView.java, spark/v3.5/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/CreateV2ViewExec.scala
This backports #9596 to Spark 3.4
=> Spark 3.4: Bypass Spark's ViewCatalog API when replacing a view

spark/v3.5/build.gradle, spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/ExtensionsTestBase.java, spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestAddFilesProcedure.java
Create `ExtensionTestBase` to migrate current tests in SparkExtension to JUnit 5 in regards to https://github.com/apache/iceberg/issues/9086.
For now, only one test `TestAddFilesProcedure` is updated with JUnit 5. Once the current migration works well, I will migrate other classes in the extension path.
=> Create ExtensionTestBase for migration to JUnit5

spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestViews.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/SparkCatalog.java
Running a `CREATE OR REPLACE VIEW` when the view doesn't exist fails currently, but should always work. This is because `.replace()` checks for view existence before creating the view, whereas `.createOrReplace()` creates it if it doesn't exist.
=> Spark: Fix CREATE OR REPLACE VIEW when view doesn't exist

spark/v3.4/build.gradle, spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestSparkExecutorCache.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/JavaUtils.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/SparkConfParser.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/SparkExecutorCache.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/SparkSQLProperties.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/source/BaseReader.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/source/SerializableTableWithSize.java, spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/Employee.java, spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/TestSparkExecutorCache.java, spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/TestSparkWriteConf.java
This PR cherry-picks applicable parts of PR #8755 and PR #9583 to Spark 3.4.
=> Spark 3.4: Read deletes in parallel and cache them on executors

arrow/src/main/java/org/apache/iceberg/arrow/vectorized/parquet/VectorizedPageIterator.java
I believe the BagePageReader class got its name due to a typo. Fortunately it is not a public class so we have the chance to fix it to BasePageReader.
=> Parquet, Arrow: Rename BagePageReader to BasePageReader in VectorizedPageIterator

open-api/rest-catalog-open-api.yaml
This PR add an optional header so that clients can provide information to the REST server related to which data access mechanisms they support.
=> Add REST spec for data access mechanisms

.palantir/revapi.yml, core/src/main/java/org/apache/iceberg/PartitionData.java, core/src/main/java/org/apache/iceberg/util/TableScanUtil.java, spark/v3.5/spark-extensions/src/jmh/java/org/apache/iceberg/spark/TaskGroupPlanningBenchmark.java
This PR fixes a substantial performance issue in combining tasks by partition for SPJ, which was caused by repetitive creation of `PartitionData`, which triggered expensive initialization.
**Before**
```
Benchmark                                                    Mode  Cnt   Score   Error  Units
TaskGroupPlanningBenchmark.planTaskGroups                      ss    5   2.879 ± 0.209   s/op
TaskGroupPlanningBenchmark.planTaskGroups:async                ss          NaN            ---
TaskGroupPlanningBenchmark.planTaskGroupsWithGrouping          ss    5  26.564 ± 0.410   s/op
TaskGroupPlanningBenchmark.planTaskGroupsWithGrouping:async    ss          NaN            ---
```
**After**
```
Benchmark                                                    Mode  Cnt  Score   Error  Units …
```
=> Core: Fix performance issue when combining tasks by partition

docs/docs/nessie.md
We should use the latest version available in the documentation and examples.
=> Docs: Update Nessie URI to API v2

spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestViews.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/SparkCatalog.java
This backports #9621 to Spark 3.4
=> Spark 3.4: Fix CREATE OR REPLACE VIEW when view doesn't exist

site/docs/catalog.md
The listing of catalog implementations is currently wrongly displayed as can be seen below
After the fix is applied, the listing looks as below
=> Docs: Fix listing of catalog implementations

flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/source/ScanContext.java, flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/source/StreamingMonitorFunction.java, flink/v1.16/flink/src/main/java/org/apache/iceberg/flink/source/enumerator/ContinuousSplitPlannerImpl.java, flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/source/TestIcebergSourceContinuous.java, flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/source/TestStreamScanSql.java, flink/v1.17/flink/src/main/java/org/apache/iceberg/flink/source/ScanContext.java, flink/v1.17/flink/src/main/java/org/apache/iceberg/flink/source/StreamingMonitorFunction.java, flink/v1.17/flink/src/main/java/org/apache/iceberg/flink/source/enumerator/ContinuousSplitPlannerImpl.java, flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/source/TestIcebergSourceContinuous.java, flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/source/TestStreamScanSql.java
1.17 came out clean
1.16 came out clean, after adding couple extra lines on `TestStreamScanSql`
=>  Flink: backport #9547 to 1.17 and 1.16 for Adds the ability to read from a branch on the Flink Iceberg Source

core/src/test/java/org/apache/iceberg/MockFileScanTask.java, spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMergeOnReadDelete.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/SparkReadConf.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/SparkSQLProperties.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/SparkUtil.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/source/SparkBatch.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/source/SparkInputPartition.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/source/SparkMicroBatchStream.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/source/SparkPlanningUtil.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkPlanningUtil.java
This PR adds an ability to enable executor cache locality. The new SQL property is off by default as it does not make sense in all cases and may introduce unnecessary task waits. When enabled and there are deletes, this logic will try to co-locate tasks for one partition to the same executors to increase the probability of the cache reuse.
=> Spark 3.5: Support executor cache locality

spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMergeOnReadDelete.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/SparkReadConf.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/SparkSQLProperties.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/SparkUtil.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/source/SparkBatch.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/source/SparkInputPartition.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/source/SparkMicroBatchStream.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/source/SparkPlanningUtil.java, spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkPlanningUtil.java
This PR cherry-picks PR #9563 to Spark 3.4.
=> Spark 3.4: Support executor cache locality

core/src/main/java/org/apache/iceberg/hadoop/HadoopCatalog.java, core/src/main/java/org/apache/iceberg/util/LocationUtil.java, core/src/test/java/org/apache/iceberg/util/TestLocationUtil.java
currently root paths like 'scheme://' get trimmed to 'scheme:' making them unusable.
=> Core: only trim slash when warehouse location is not root path

spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/data/SparkParquetWriters.java
This moves from the OriginalType to the LogicalTypeAnnotation to support nanosecond timestamps.
=> Spark: Move the Writer to a visitor

spark/v3.5/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/CreateV2ViewExec.scala, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/SparkCatalog.java
This is related to https://github.com/apache/iceberg/pull/9596#discussion_r1473189034. If the view is concurrently dropped during `CREATE OR REPLACE` we create the view in `CreateV2ViewExec`
=> Spark: Handle concurrently dropped view during CREATE OR REPLACE

spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/TestBaseWithCatalog.java
We do the same check in [`SparkTestBaseWithCatalog`](https://github.com/apache/iceberg/blob/1a9c3f78f5e2d0b831aadd4636eeb70975463e78/spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/SparkTestBaseWithCatalog.java#L90) to avoid a potential NPE when a catalog configuration doesn't have the `type` set
=> Spark: Avoid NPE when catalog config doesn't have "type" set

spark/v3.4/spark-extensions/src/main/scala/org/apache/spark/sql/execution/datasources/v2/CreateV2ViewExec.scala, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/SparkCatalog.java
this backports #9623 to Spark 3.4
=> Spark 3.4: Handle concurrently dropped view during CREATE OR REPLACE

docs/mkdocs.yml, site/docs/vendors.md
My last pull request wasn't merged before docs were switched, so submitting this one editing the correct files post-switch
Old PR: #9557 
FYI @bitsondatadev
=> Docs: Add/update Snowflake

open-api/rest-catalog-open-api.py, open-api/rest-catalog-open-api.yaml
As a follow up for https://github.com/apache/iceberg/pull/9564 I added the statistics files to the table metadata.
Then I noticed the partition statistics files were also missing, so I added them here instead of creating another PR, since the changes are somewhat related.
=> OpenAPI: Spec updates for statistics

site/mkdocs.yml
This commit should fix broken strike-through markup on https://iceberg.apache.org/spec/ page
Closes #9693
=> Docs: Fix broken strike-through markup

mr/src/test/java/org/apache/iceberg/mr/TestIcebergInputFormats.java, mr/src/test/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandlerTestUtils.java, mr/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerLocalScan.java, mr/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerNoScan.java, mr/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerTimezone.java, mr/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerWithEngine.java, mr/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerWithMultipleCatalogs.java, mr/src/test/java/org/apache/iceberg/mr/hive/TestTables.java
@nastra Could you please review this pr?
to  #9269
=> MR: Migrate parameterized tests to JUni5

core/src/main/java/org/apache/iceberg/view/ViewMetadata.java, core/src/main/java/org/apache/iceberg/view/ViewProperties.java, core/src/test/java/org/apache/iceberg/view/TestViewMetadata.java, core/src/test/java/org/apache/iceberg/view/ViewCatalogTests.java, nessie/src/test/java/org/apache/iceberg/nessie/BaseTestIceberg.java, spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestViews.java, spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestViews.java
The general idea behind this approach is to prevent a `CREATE OR REPLACE VIEW` stmt in Trino/Spark from accidentally dropping a view that was e.g. created in Spark/Trino. 
In Spark, the strictness flag could be disabled via `ALTER VIEW ... SET TBLPROPERTIES ('replace.strictness.enabled' = 'false')` or during a replace via `CREATE OR REPLACE VIEW ... TBLPROPERTIES ('replace.strictness.enabled' = 'false')`.
The PR still needs more tests, which will be added once we decide on the direction going forward
=> Core: Add property to prevent loss of view representation when replacing a view

core/src/main/java/org/apache/iceberg/inmemory/InMemoryFileIO.java, core/src/test/java/org/apache/iceberg/inmemory/TestInMemoryFileIO.java, core/src/test/java/org/apache/iceberg/rest/TestRESTCatalog.java
This PR addresses the issue with InMemoryFileIO not being resolved by the RESTCatalog Tests identified in #9604.
In the RESTCatalog tests are backed by the `InMemoryCatalog` which uses `InMemoryFileIO`. But the `ResolvingFileIO` can't resolve this FileIO, and if we pass in the FileIO into the `RESTCatalog` there will be two instances of the `InMemoryFileIO`. Therefore, this change will ensure that there is shared access to the files across all the instances of the `InMemoryFileIO`. 
For more information: #9604 
Running and setting a break point on this method:
* https://github.com/apache/iceberg/blob/50fb4004d299737fcbae6526e1743dd197c9242d/core/src/test/java/org/apache/iceberg/catalog/CatalogTests.java#L1386
`./gradlew build`
```
BUILD SUCCESSFUL in 49m 38s
452 actionable tasks: 216 …
```
=> Make InMemoryFileIO map shared access across instances

core/src/main/java/org/apache/iceberg/TableMetadata.java, core/src/test/java/org/apache/iceberg/rest/TestRESTCatalog.java
While using
```
TableMetadata.buildFrom(originalResponse.tableMetadata())
.suppressHistoricalSnapshots()
```
already suppresses historical snapshots correctly, we still end up with all snapshots when calling `build()`.
This is because `build()` exists early when there are no changes in https://github.com/apache/iceberg/blob/main/core/src/main/java/org/apache/iceberg/TableMetadata.java#L1391-L1393:
```
if (!hasChanges()) {
return base;
}
```
This then causes to return all snapshots from `base` metadata.
=> Core: Properly suppress historical snapshots when building TableMetadata with suppressHistoricalSnapshots()

core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java, core/src/main/java/org/apache/iceberg/jdbc/JdbcTableOperations.java, core/src/main/java/org/apache/iceberg/jdbc/JdbcUtil.java, core/src/main/java/org/apache/iceberg/jdbc/JdbcViewOperations.java, core/src/test/java/org/apache/iceberg/jdbc/TestJdbcCatalog.java, core/src/test/java/org/apache/iceberg/jdbc/TestJdbcUtil.java, core/src/test/java/org/apache/iceberg/jdbc/TestJdbcViewCatalog.java
This PR adds view support to the JDBC catalog:
- `JdbcCatalog` extends `BaseMetastoreViewCatalog`
- Introduce `JdbcViewOperations`
- Dedicated JDBC table to store views and associated namespaces
- `JdbcUtil` refactoring to deal with SQL statements common to table and view
- Introduce `TestJdbcViewCatalog` by extending `ViewCatalogTests`
Close #8697
=> Core: Add view support for JDBC catalog

aliyun/src/main/java/org/apache/iceberg/aliyun/AliyunClientFactories.java, aliyun/src/main/java/org/apache/iceberg/aliyun/AliyunProperties.java, aliyun/src/test/java/org/apache/iceberg/aliyun/TestAliyunClientFactories.java, aliyun/src/test/java/org/apache/iceberg/aliyun/oss/TestOSSFileIO.java
Currently the default DefaultAliyunClientFactory requires users to pass AccessKey pair to have access to OSS. However, in many cases organizations use Security Token Service (STS) to generate temporary access credentials to authorize a user to access the Object Storage Service (OSS) resources within a specific period of time. See https://www.alibabacloud.com/help/en/oss/developer-reference/use-temporary-access-credentials-provided-by-sts-to-access-oss for detail. It would be good to support passing a security token to create an OSS client by DefaultAliyunClientFactory.
=> Aliyun: Add security token to OSS client properties

api/src/main/java/org/apache/iceberg/encryption/EncryptingFileIO.java, api/src/main/java/org/apache/iceberg/io/FileIO.java, core/src/main/java/org/apache/iceberg/ManifestFiles.java, core/src/main/java/org/apache/iceberg/encryption/NativeEncryptionOutputFile.java, core/src/main/java/org/apache/iceberg/encryption/StandardEncryptionManager.java, core/src/main/java/org/apache/iceberg/io/ContentCache.java, core/src/test/java/org/apache/iceberg/hadoop/TestCatalogUtilDropTable.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/source/BaseReader.java
This adds `EncryptingFileIO` to handle metadata file encryption without breaking existing interfaces that pass `FileIO` without an `EncryptionManager`. It also updates `FileIO` to have methods for opening `ManifestFile`, `DataFile`, and `DeleteFile` directly to avoid needing to check whether a given `FileIO` supports encryption. The default implementation in `FileIO` fails if metadata files are encrypted.
=> API: Extend FileIO and add EncryptingFileIO.

flink/v1.18/flink/src/main/java/org/apache/iceberg/flink/source/enumerator/ContinuousIcebergEnumerator.java
`ContinuousIcebergEnumerator` ignore the enumeration history state when restore from checkpoint.
=> Flink 1.18: Fix continuous enumerator lost enumeration history state when restore from checkpoint.

flink/v1.18/flink/src/main/java/org/apache/iceberg/flink/FlinkReadConf.java
https://github.com/apache/iceberg/blob/66e957bd99ff8d11344efda4cb177c2d243eedaa/flink/v1.18/flink/src/main/java/org/apache/iceberg/flink/source/IcebergSource.java#L399-L404
In `IcebergSource`, we configure the plan parallelism into `readOptions` through the key `FlinkConfigOptions.TABLE_EXEC_ICEBERG_WORKER_POOL_SIZE`. 
However, since `FlinkReadConf.workerPoolSize()` does not parse the `readOptions` configuration based on this key, the parallelism configured through `IcebergSource.planParallelism` will not actually take effect.
=> Flink 1.18: Fix iceberg source plan parallelism not effective.

api/src/main/java/org/apache/iceberg/encryption/EncryptingFileIO.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/source/BaseReader.java
This implements @RussellSpitzer's suggestion to make `EncryptingFileIO.create` more defensive.
=> Core: Fix EncryptingFileIO factory method.

site/docs/multi-engine-support.md, site/docs/releases.md
The current list item layout on https://iceberg.apache.org/releases/ is wrongly intended, which is being fixed by this PR. Additionally, this adds Spark 3.5 to the supported engine page.
/cc @bitsondatadev @Fokko
=> Docs: Fix listings on Release page / Update Multi-engine support

aws/src/main/java/org/apache/iceberg/aws/dynamodb/DynamoDbCatalog.java, aws/src/main/java/org/apache/iceberg/aws/dynamodb/DynamoDbTableOperations.java
As discussed in the [community sync](https://youtu.be/uAQVGd5zV4I?si=cj0xpfprgvJIGYIm&t=1323), we want to reduce the scope of supported catalogs in Iceberg. There are currently many options, which creates confusion and makes it difficult to properly test and upgrade each one.
The `DynamoDBCatalog` specifically has seen little adoption. It provides similar functionality to other catalogs we already support better like the `GlueCatalog`. As we look to simplify our catalog selection, the DynamoDB catalog makes sense as one to deprecate. 
This PR marks the DynamoDB catalog as deprecated. It will be removed entirely in two releases, starting from Iceberg 1.6.0.
Please comment If you have any concerns or a hard dependency on this catalog.
=> Deprecate DynamoDB Catalog to Reduce Catalog Scope

spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestAddFilesProcedure.java, spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestAncestorsOfProcedure.java, spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestCallStatementParser.java, spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestChangelogTable.java, spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestCherrypickSnapshotProcedure.java, spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestCreateChangelogViewProcedure.java, spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestExpireSnapshotsProcedure.java, spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestFastForwardBranchProcedure.java, spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMigrateTableProcedure.java, spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestPublishChangesProcedure.java, spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRegisterTableProcedure.java, spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRemoveOrphanFilesProcedure.java, spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRewriteDataFilesProcedure.java, spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRewriteManifestsProcedure.java, spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRewritePositionDeleteFiles.java, spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRewritePositionDeleteFilesProcedure.java, spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRollbackToSnapshotProcedure.java, spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRollbackToTimestampProcedure.java, spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestSetCurrentSnapshotProcedure.java, spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestSnapshotTableProcedure.java, spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestWriteAborts.java
Migrate the following "Procedure" sub-classes in spark-extensions to JUnit 5 and AssertJ style along with https://github.com/apache/iceberg/pull/9613, and https://github.com/apache/iceberg/issues/9086.
TestAddFiles was included in https://github.com/apache/iceberg/pull/9613/, it's skipped in this PR.
=> Migrate Procedure sub-classes in spark-extensions to JUnit5 and AssertJ style

spark/v3.4/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/analysis/RewriteViewCommands.scala, spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestViews.java
This backports #9675 to Spark 3.4
=> Spark 3.4: Fail if temp functions are used in views

.github/dependabot.yml
Major version updates like https://github.com/apache/iceberg/pull/9799 and https://github.com/apache/iceberg/pull/9798 are usually breaking and can't be auto merged with dependabot. 
This PR proposes to ignore major version update to have fewer noise.
=> Build: Ignore major version update in dependabot

spark/v3.4/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/analysis/CheckViews.scala, spark/v3.4/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/analysis/RewriteViewCommands.scala, spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestViews.java, spark/v3.5/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/analysis/RewriteViewCommands.scala
This backports #9807 to Spark 3.4
=> Spark 3.4: Include catalog name in view errors

format/spec.md
This pr clarifies multi-arg transform behavior in relation to different Iceberg versions. It proposes to make the behavior default in V3 but enabled in V1/V2 with a new table config.  It also cleans up some of the affected tables and notes.
This is a follow up on: https://github.com/apache/iceberg/pull/8579 based on the email thread discussion : https://lists.apache.org/thread/9opgkrpqhzp3nl8hdohgnk1m1zxnxmq0.
=> Spec: Clarify multi-arg transform behavior for different versions

spark/v3.4/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/analysis/RewriteViewCommands.scala, spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestViews.java, spark/v3.5/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/analysis/RewriteViewCommands.scala, spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestViews.java
This uses the current namespace when executing `USE <namespace>` and then `SHOW VIEWS` (without specifying a namespace) 
This behavior is similar to what's being done for V1 `ShowViews` in https://github.com/apache/spark/blob/branch-3.5/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/analysis/ResolveCatalogs.scala#L43-L44
This reproduces the issue and shows that there's a different behavior for `SHOW TABLES` vs `SHOW VIEWS` when the current namespace is set:
```
spark-sql (default)> use iceberg1;
Time taken: 0.015 seconds
spark-sql (iceberg1)> show tables;
foo
foo2
Time taken: 0.044 seconds, Fetched 2 row(s)
spark-sql (iceberg1)> show views;
24/02/24 08:24:25 ERROR SparkSQLDriver: Failed in [show views]
org.apache.iceberg.exceptions.NoSuchNamespaceException: Invalid namespace: …
```
=> Spark 3.4, 3.5: Use current namespace for SHOW VIEWS cmd

spark/v3.5/build.gradle, spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestAlterTableSchema.java, spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMetaColumnProjectionWithStageScan.java, spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestMetadataTables.java, spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestStoragePartitionedJoinsInRowLevelOperations.java, spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestSystemFunctionPushDownDQL.java, spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestViews.java, spark/v3.5/spark-runtime/src/integration/java/org/apache/iceberg/spark/SmokeTest.java
Migrate the following "Read" and other sub-classes in spark-extensions to JUnit 5 and AssertJ style along with https://github.com/apache/iceberg/pull/9613, and https://github.com/apache/iceberg/issues/9086.
=> Migrate Read and other sub-classes in spark-extensions to JUnit5 and AssertJ style

api/src/main/java/org/apache/iceberg/SortOrder.java, api/src/main/java/org/apache/iceberg/SortOrderBuilder.java
This PR simply fix the typo in the comment for a series of `desc` methods in SortOrder and SortOrderBuilder, which should be `descending` rather than `ascending`.
=> API: Fix typo in method comment of SortOrder and SortOrderBuilder

spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestViews.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/SupportsFunctions.java, spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/TestFunctionCatalog.java
This backports #9814 to Spark 3.4
=> Spark 3.4: Improve error msg when function can't be loaded

open-api/rest-catalog-open-api.yaml
This PR simply updates to point to the correct doc url
=> OpenAPI: Point to latest doc in rest catalog

open-api/rest-catalog-open-api.py, open-api/rest-catalog-open-api.yaml
Dev List discussion thread around adding support for pagination in list namespaces, tables, and views: https://lists.apache.org/thread/lql05h02qtp8mgq74ovhb0ndd76ck4f3 
Credit to @emkornfield for creating this google doc for listing all cases which this change is based off: https://docs.google.com/document/d/1bbfoLssY1szCO_Hm3_93ZcN0UAMpf7kjmpwHQngqQJ0/edit
cc @jackye1995 @rdblue @danielcweeks
Ran `make install, make lint, and python3 rest-catalog-open-api.py` without issues.`
=> Add pagination to open api spec for listing of namespaces, tables, views

core/src/main/java/org/apache/iceberg/CatalogUtil.java, core/src/test/java/org/apache/iceberg/TestCatalogUtil.java
The current error message always says FileIO "missing no-arg constructor: " whenever a NoSuchMethod is thrown but we've seen several instances of the underlying exception being completely unrelated to the existence of a no arg constructor and actually a NSM exception being thrown from a dependent class. 
The biggest culprit of this is S3FileIO, for example if you have a bad AWS SDK you can see something like
#7396
```java
Exception in thread "main" java.lang.IllegalArgumentException: Cannot initialize FileIO, missing no-arg constructor: org.apache.iceberg.aws.s3.S3FileIO
Caused by: java.lang.NoSuchMethodException: Cannot find constructor for interface org.apache.iceberg.io.FileIO
Missing org.apache.iceberg.aws.s3.S3FileIO [java.lang.NoClassDefFoundError: …
```
=> Core: FileIO Reflection Error Message is Misleading

core/src/main/java/org/apache/iceberg/rest/RESTSessionCatalog.java
This is a fix for Spark table loading when a REST catalog does not support view extensions.
The problem is that Spark runs `ResolveViews` before `ResolveTables` in the substitution batch of rules. With view support in the REST catalog, table references will result in a `loadView` call to check if the unresolved identifier is a view. If the catalog service does not support views, then a 4XX exception is thrown but not caught and used to indicate the view does not exist.
This translates 4XX calls returned by the load view path to `NoSuchViewException` indicating that the service does not support views.
=> Core: Fix REST catalog handling when the service has no view support

site/docs/community.md
Remove calendar embed in favor calendar links.
=> Remove calendar embed in favor calendar links

flink/v1.18/flink/src/main/java/org/apache/iceberg/flink/FlinkCatalog.java, flink/v1.18/flink/src/main/java/org/apache/iceberg/flink/FlinkDynamicTableFactory.java, flink/v1.18/flink/src/main/java/org/apache/iceberg/flink/FlinkSchemaUtil.java, flink/v1.18/flink/src/main/java/org/apache/iceberg/flink/util/FlinkAlterTableUtil.java, flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/TestFlinkCatalogTable.java
If we use flinksql to create the iceberg table, even if I specify field comments, there are no field comments in the final iceberg table. #8511
In order to solve this problem, this PR parses field comments when creating tables and adding fields in flinksql, and finally adds them to iceberg field comments.
=> Flink: Supports specifying comment for iceberg fields in create table and addcolumn syntax using flinksql

format/gcm-stream-spec.md, format/puffin-spec.md, format/spec.md, format/view-spec.md
Continuation from #9843. We wanted to get the image fix on the spec. This PR fixes other updates needed under the `format/` markdown files.
=> Update specs from hugo to mkdocs format

core/src/test/java/org/apache/iceberg/MetadataTableScanTestBase.java, core/src/test/java/org/apache/iceberg/TestBase.java, core/src/test/java/org/apache/iceberg/TestBatchScans.java, core/src/test/java/org/apache/iceberg/TestEntriesMetadataTable.java, core/src/test/java/org/apache/iceberg/TestFindFiles.java, core/src/test/java/org/apache/iceberg/TestIncrementalDataTableScan.java, core/src/test/java/org/apache/iceberg/TestMetadataTableScans.java, core/src/test/java/org/apache/iceberg/TestMetadataTableScansWithPartitionEvolution.java
Migrate the following "Read" in iceberg-core to JUnit 5 and AssertJ style for https://github.com/apache/iceberg/issues/9085.
Read:
=> Migrate Read in Core to JUnit5

.github/workflows/spark-ci.yml, gradle/libs.versions.toml
I've seen [Spark CI failure due to no disk space](https://github.com/apache/iceberg/actions/runs/7946611346/job/21694529729?pr=9746) 
```
org.apache.iceberg.spark.extensions.TestCopyOnWriteMerge > testMergeWithConcurrentTableRefresh[catalogName = testhive, implementation = org.apache.iceberg.spark.SparkCatalog, config = {type=hive, default-namespace=default}, format = parquet, vectorized = true, distributionMode = none, branch = test] FAILED
java.lang.AssertionError: 
Expecting actual throwable to be an instance of:
java.lang.IllegalStateException
but was:
org.apache.spark.SparkException: Writing job aborted
at org.apache.spark.sql.errors.QueryExecutionErrors$.writingJobAbortedError(QueryExecutionErrors.scala:767)
at org.apache.spark.sql.execution.datasources.v2.V2TableWriteExec.writeWithV …
```
=> Build: Free disk space before running action in Spark CI

core/src/test/java/org/apache/iceberg/catalog/CatalogTests.java, hive-metastore/src/main/java/org/apache/iceberg/hive/HiveCatalog.java
For view catalogs we already test the same behavior in https://github.com/apache/iceberg/blob/main/core/src/test/java/org/apache/iceberg/view/ViewCatalogTests.java#L589-L611 but we haven't done so for table catalogs.
=> Core: Add test for renaming table to a non-existing namespace

spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/actions/RewriteDataFilesSparkAction.java, spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/actions/SparkBinPackDataRewriter.java, spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/actions/SparkShufflingDataRewriter.java, spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/actions/SparkSortDataRewriter.java, spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/actions/SparkZOrderDataRewriter.java, spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteDataFilesAction.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/actions/RewriteDataFilesSparkAction.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/actions/SparkBinPackDataRewriter.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/actions/SparkShufflingDataRewriter.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/actions/SparkZOrderDataRewriter.java, spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteDataFilesAction.java
=> Spark 3.4, 3.3 : support output-spec-id in rewrite (back port #9803)

docs/docs/flink-actions.md, docs/docs/flink-connector.md, docs/docs/flink-ddl.md, docs/docs/flink-queries.md, docs/docs/flink-writes.md, docs/docs/flink.md
1. Fix internal links
2. Remove period in title
3. Fix numbered list with code blocks
4. Add identifier fields as an approach for upsert mode
=> Docs: Enhance Flink pages

core/src/test/java/org/apache/iceberg/LocalTableOperations.java, core/src/test/java/org/apache/iceberg/TestSnapshot.java, core/src/test/java/org/apache/iceberg/TestSnapshotJson.java, core/src/test/java/org/apache/iceberg/TestSnapshotLoading.java, core/src/test/java/org/apache/iceberg/TestSnapshotManager.java, core/src/test/java/org/apache/iceberg/TestSnapshotRefParser.java, core/src/test/java/org/apache/iceberg/TestSnapshotSelection.java, core/src/test/java/org/apache/iceberg/TestSnapshotSummary.java, core/src/test/java/org/apache/iceberg/TestTableMetadata.java
Migrate the following "Read" in iceberg-core to JUnit 5 for https://github.com/apache/iceberg/issues/9085.
Snapshots:
The following classes are for Iceberg procedures:
=> Migrate Snapshot files in Core to JUnit5

data/src/test/java/org/apache/iceberg/TestGenericAppenderFactory.java, data/src/test/java/org/apache/iceberg/io/TestAppenderFactory.java, data/src/test/java/org/apache/iceberg/io/TestBaseTaskWriter.java, data/src/test/java/org/apache/iceberg/io/TestTaskEqualityDeltaWriter.java, flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkAppenderFactory.java, flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkAppenderFactory.java, flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkAppenderFactory.java, spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkAppenderFactory.java, spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkAppenderFactory.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkAppenderFactory.java
Issue #9085 
In this patch I planned to replace [TestBase](https://github.com/apache/iceberg/blob/main/core/src/test/java/org/apache/iceberg/TestBase.java) with [TableTestBase](https://github.com/apache/iceberg/blob/main/core/src/test/java/org/apache/iceberg/TableTestBase.java) for following base classes. 
1. TestBaseTaskWriter
2. TestAppenderFactory
3. TestTaskEqualityDeltaWriter
=> Data, Spark, Flink: Migrate TestAppenderFactory and subclasses to JUnit5

aws/src/main/java/org/apache/iceberg/aws/s3/signer/S3V4RestSignerClient.java, core/src/main/java/org/apache/iceberg/rest/RESTSessionCatalog.java, core/src/main/java/org/apache/iceberg/rest/auth/OAuth2Properties.java, core/src/main/java/org/apache/iceberg/rest/auth/OAuth2Util.java, core/src/test/java/org/apache/iceberg/rest/TestRESTCatalog.java
[Make the OAuth2 request audience
](https://github.com/apache/iceberg-python/issues/479)
=> Feature make oauth `audience` configurable

spark/v3.5/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/optimizer/ReplaceStaticInvoke.scala, spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/SparkPlanUtil.java, spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestSystemFunctionPushDownInRowLevelOperations.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/functions/BaseScalarFunction.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/functions/BucketFunction.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/functions/DaysFunction.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/functions/HoursFunction.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/functions/IcebergVersionFunction.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/functions/MonthsFunction.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/functions/TruncateFunction.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/functions/YearsFunction.java
This PR fixes the system function predicate pushdown in CoW MERGE operations and adds tests for other use cases. Prior to this PR, we did not cover `ReplaceData` and `Join` nodes that are participating in CoW operations. We also did not cover IN expressions.
See `GroupBasedRowLevelOperationScanPlanning` in Spark for more context.
=> Spark 3.5: Fix system function pushdown in CoW row-level commands

docs/docs/spark-configuration.md, docs/docs/spark-ddl.md, docs/docs/spark-getting-started.md, docs/docs/spark-procedures.md, docs/docs/spark-queries.md, docs/docs/spark-structured-streaming.md, docs/docs/spark-writes.md
1. Fix internal links
2. Move `Type Compatibility` section from spark-writes.md to spark-getting-started.md
=> Docs: Enhance Spark pages

core/src/test/java/org/apache/iceberg/TableMetadataParserCodecTest.java, core/src/test/java/org/apache/iceberg/TableMetadataParserTest.java, core/src/test/java/org/apache/iceberg/TestMetadataTableFilters.java, core/src/test/java/org/apache/iceberg/TestMetadataUpdateParser.java, core/src/test/java/org/apache/iceberg/TestTableMetadata.java, core/src/test/java/org/apache/iceberg/TestTableMetadataSerialization.java
Migrate the following "Read" in iceberg-core to JUnit 5 for https://github.com/apache/iceberg/issues/9085.
=> Migrate Metadata files in Core to JUnit5

core/src/test/java/org/apache/iceberg/TestFormatVersions.java, core/src/test/java/org/apache/iceberg/TestLocationProvider.java, core/src/test/java/org/apache/iceberg/TestManifestCaching.java, core/src/test/java/org/apache/iceberg/TestManifestCleanup.java, core/src/test/java/org/apache/iceberg/TestManifestEncryption.java, core/src/test/java/org/apache/iceberg/TestManifestListVersions.java, core/src/test/java/org/apache/iceberg/TestManifestReaderStats.java, core/src/test/java/org/apache/iceberg/TestManifestWriter.java, core/src/test/java/org/apache/iceberg/TestManifestWriterVersions.java
Migrate the following "Read" in iceberg-core to JUnit 5 and AssertJ style for https://github.com/apache/iceberg/issues/9085.
Additional classes:
=> Migrate Manifest, FormatVersion and LocationProvider files in Core to JUnit5

api/src/test/java/org/apache/iceberg/expressions/TestStrictMetricsEvaluator.java
All values (`5` and `6`) are not between the upper and lower bound of `[30, 79]`.
=> Fix `TestStrictMetricsEvaluator` assertion message

aws/src/test/java/org/apache/iceberg/aws/AwsClientPropertiesTest.java, aws/src/test/java/org/apache/iceberg/aws/HttpClientPropertiesTest.java, aws/src/test/java/org/apache/iceberg/aws/TestS3FileIOAwsClientFactories.java, aws/src/test/java/org/apache/iceberg/aws/s3/TestS3FileIOProperties.java, core/src/test/java/org/apache/iceberg/catalog/CatalogTests.java
We almost never want to use `.withFailMessage()` as that will override any enriched contextual information that AssertJ generally provides about actual/expected. It's better to use `.as()` to add some description to the check being done, which allows to still show contextual information about actual/expected if the assertion ever fails.
=> AWS, Core: Replace .withFailMessage() usage with .as()

core/src/test/java/org/apache/iceberg/TestCommitReporting.java, core/src/test/java/org/apache/iceberg/TestCreateTransaction.java, core/src/test/java/org/apache/iceberg/TestPartitionSpecInfo.java, core/src/test/java/org/apache/iceberg/TestPartitionSpecParser.java, core/src/test/java/org/apache/iceberg/TestPartitioning.java, core/src/test/java/org/apache/iceberg/TestReplaceTransaction.java, core/src/test/java/org/apache/iceberg/TestSetPartitionStatistics.java, core/src/test/java/org/apache/iceberg/TestSetStatistics.java, core/src/test/java/org/apache/iceberg/TestTransaction.java
Transactions
Partitions:
Statistics
Other
=> Migrate Transactions, Partitions and Statistics files in Core to JUnit5

docs/docs/daft.md, docs/mkdocs.yml
- Adds installation examples
- Adds code examples for getting up and running with Daft + PyIceberg
- Adds a type conversion matrix between Daft and PyIceberg
=> Docs: Add Daft into Iceberg documentation

core/src/test/java/org/apache/iceberg/TestDeleteFiles.java, core/src/test/java/org/apache/iceberg/TestFastAppend.java, core/src/test/java/org/apache/iceberg/TestMergeAppend.java, core/src/test/java/org/apache/iceberg/TestOverwrite.java, core/src/test/java/org/apache/iceberg/TestOverwriteWithValidation.java, core/src/test/java/org/apache/iceberg/TestRewriteFiles.java
=> Migrate Files, Append and Overwrite files in Core to JUnit5

.github/ISSUE_TEMPLATE/iceberg_proposal.yml, site/docs/contribute.md
This PR adds an issue template for Iceberg improvement proposals and adds docs to the site to cover the proposal process.
=> Add issue template and docs for iceberg proposals

core/src/test/java/org/apache/iceberg/TestReplacePartitions.java, core/src/test/java/org/apache/iceberg/TestScanDataFileColumns.java, core/src/test/java/org/apache/iceberg/TestScanSummary.java, core/src/test/java/org/apache/iceberg/TestScansAndSchemaEvolution.java, core/src/test/java/org/apache/iceberg/TestSchemaAndMappingUpdate.java, core/src/test/java/org/apache/iceberg/TestSchemaID.java, core/src/test/java/org/apache/iceberg/TestSchemaUpdate.java, core/src/test/java/org/apache/iceberg/TestTableUpdatePartitionSpec.java, core/src/test/java/org/apache/iceberg/TestTimestampPartitions.java, core/src/test/java/org/apache/iceberg/TestUpdatePartitionSpec.java
=> Migrate Scan, Schema and remaining Partition files in Core to JUnit5

core/src/test/java/org/apache/iceberg/TestBase.java, core/src/test/java/org/apache/iceberg/TestMetricsModes.java, core/src/test/java/org/apache/iceberg/TestMicroBatchBuilder.java, core/src/test/java/org/apache/iceberg/TestRemoveSnapshots.java, core/src/test/java/org/apache/iceberg/TestRewriteManifests.java, core/src/test/java/org/apache/iceberg/TestRowDelta.java, core/src/test/java/org/apache/iceberg/TestSchemaAndMappingUpdate.java, core/src/test/java/org/apache/iceberg/TestSchemaUpdate.java, core/src/test/java/org/apache/iceberg/TestSequenceNumberForV2Table.java, core/src/test/java/org/apache/iceberg/TestSingleValueParser.java, core/src/test/java/org/apache/iceberg/TestSortOrder.java, core/src/test/java/org/apache/iceberg/TestSortOrderParser.java, core/src/test/java/org/apache/iceberg/TestSplitPlanning.java, core/src/test/java/org/apache/iceberg/TestV1ToV2RowDeltaDelete.java, core/src/test/java/org/apache/iceberg/V2TableTestBase.java
Refactoring (related to https://github.com/apache/iceberg/pull/10014#discussion_r1534263933):
=> Migrate other files in Core to JUnit5

aws/src/main/java/org/apache/iceberg/aws/AwsClientFactories.java, aws/src/main/java/org/apache/iceberg/aws/s3/DefaultS3FileIOAwsClientFactory.java, aws/src/main/java/org/apache/iceberg/aws/s3/S3FileIOProperties.java, aws/src/test/java/org/apache/iceberg/aws/s3/TestS3FileIOProperties.java
This allows developers to monitor which version of Iceberg they have deployed to a cluster (for example, through the S3 Access Logs, which contain the user agent field).
=> Aws: Add Iceberg version to UserAgent in S3 requests

core/src/main/java/org/apache/iceberg/util/ZOrderByteUtils.java, core/src/test/java/org/apache/iceberg/util/TestZOrderByteUtil.java, spark/v3.3/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRewriteDataFilesProcedure.java, spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRewriteDataFilesProcedure.java, spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRewriteDataFilesProcedure.java
Fixes #10022
Currently we don't handle null binary values correctly when they are part of a zordered column. In terms of ordering they should just be a 0'd out buffer (simllar to strings).
=> Core, Spark: Fix handling of null binary values when sorting with zorder

hive-metastore/src/test/java/org/apache/iceberg/hive/HiveTableTest.java
Hive should not allow creating an iceberg table, if there is already another content available with same name.
@pvary / @szehon-ho  Please share your feedback for these tests.
=> Hive: Tests to do validation hive content and iceberg table with the same name

site/docs/blogs.md
=> Build: disable link-check for existing medium blog posts

spark/v3.4/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/analysis/CheckViews.scala, spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestViews.java
This backports https://github.com/apache/iceberg/pull/9834 to Spark 3.4
=> Spark 3.4: Fail on recursive cycle in view

.github/workflows/docs-check-links.yml
Hopefully this generates less requests, causing the CI to fail due to 429's
=> CI: Run Markdown links checker only when `{docs,site}/**` changes

core/src/test/java/org/apache/iceberg/FilterFilesTestBase.java, core/src/test/java/org/apache/iceberg/TestMetrics.java, core/src/test/java/org/apache/iceberg/TestWapWorkflow.java, core/src/test/java/org/apache/iceberg/actions/TestCommitService.java, core/src/test/java/org/apache/iceberg/actions/TestSizeBasedRewriter.java, core/src/test/java/org/apache/iceberg/avro/AvroTestHelpers.java, core/src/test/java/org/apache/iceberg/avro/TestNameMappingWithAvroSchema.java, core/src/test/java/org/apache/iceberg/encryption/TestGcmStreams.java, core/src/test/java/org/apache/iceberg/encryption/TestStandardKeyMetadataParser.java, core/src/test/java/org/apache/iceberg/io/TestOutputFileFactory.java, core/src/test/java/org/apache/iceberg/mapping/TestMappingUpdates.java, core/src/test/java/org/apache/iceberg/mapping/TestNameMapping.java, data/src/test/java/org/apache/iceberg/orc/TestOrcMetrics.java, data/src/test/java/org/apache/iceberg/parquet/TestParquetMetrics.java
=> Migrate WAP, Metrics and FilterFiles in Core to JUnit5

core/src/main/java/org/apache/iceberg/hadoop/HadoopStreams.java, core/src/test/java/org/apache/hadoop/fs/s3a/S3ABlockOutputStream.java, core/src/test/java/org/apache/iceberg/hadoop/HadoopStreamsTest.java, core/src/test/java/org/apache/iceberg/hadoop/TestHadoopStreams.java
This is fix for https://github.com/apache/iceberg/issues/9997
s3a putObject was interrupted due to flink pipeline failure _while_ the object was being uploaded. As this interrupt is not handled and thrown as an exception, the metadata writer assumes write was successful which results in table pointing to a metadata json file that doesn't exist.
This is the s3a code block which is called from stream close to putObject which is the root cause.
https://github.com/apache/hadoop/blob/0f51d2a4ec17bad754beb17048409811a151be53/hadoop-tools/hadoop-aws/src/main/java/org/apache/hadoop/fs/s3a/S3ABlockOutputStream.java#L636
``` 
try {
putObjectResult.get();
return size;
} catch (InterruptedException ie) {
LOG.warn("Interrupted object upload", ie);
Thread.currentThread().interrupt();
return 0;
} catch …
```
=> [core] fix #9997 - Handle s3a file upload interrupt which results in table metadata pointing to files that doesn't exist

spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/SparkCatalog.java, spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/sql/TestSelect.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/SparkCatalog.java, spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/sql/TestSelect.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/SparkCatalog.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/sql/TestSelect.java
fixes https://github.com/apache/iceberg/issues/10058 and applies the same as https://github.com/apache/iceberg/pull/9219 for `TIMESTAMP AS OF`
=> Spark: Don't allow branch_ usage with TIMESTAMP AS OF

site/docs/blogs.md, site/link-checker-config.json
fixes https://github.com/apache/iceberg/issues/10060
=> Build: Ignore link-checking for Blogs / https://search.maven.org/

core/src/test/java/org/apache/iceberg/util/TestTableScanUtil.java, data/src/test/java/org/apache/iceberg/io/TestPartitioningWriters.java, data/src/test/java/org/apache/iceberg/io/TestPositionDeltaWriters.java, data/src/test/java/org/apache/iceberg/io/TestRollingFileWriters.java, flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/sink/TestDeltaTaskWriter.java, flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/sink/TestIcebergFilesCommitter.java, flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/source/TestStreamingMonitorFunction.java, flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/source/TestStreamingReaderOperator.java, flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/sink/TestDeltaTaskWriter.java, flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/sink/TestIcebergFilesCommitter.java, flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/source/TestStreamingMonitorFunction.java, flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/source/TestStreamingReaderOperator.java, flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/sink/TestDeltaTaskWriter.java, flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/sink/TestIcebergFilesCommitter.java, flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/source/TestStreamingMonitorFunction.java, flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/source/TestStreamingReaderOperator.java
Migrate the following test classes to delete `TableTestBase`  for https://github.com/apache/iceberg/issues/9085.
This PR is for the migration of `TableTestBase` related classes in https://github.com/apache/iceberg/pull/10063.
Core:
`iceberg-flink` for the versions: v1.16, v.1.17, v1.18
=> Migrate TableTestBase related classes to JUnit5

api/src/main/java/org/apache/iceberg/io/FileIO.java, aws/src/test/java/org/apache/iceberg/aws/s3/TestS3FileIO.java
As part of adding encryption support, in https://github.com/apache/iceberg/pull/9592 we added some new FileIO APIs, namely 
```
newInputFile(ManifestFile)
newInputFile(DataFile)
newInputFile(DeleteFile)
```
The overriden implementaiton in EncryptedFileIO is correct but the default implementation in `FileIO` for these new APIs should pass in a length since it's always known from the Iceberg metadata. 
Without this, FileIO implementations which end up calling these default implementations (specifically referring to these new APIs)will make extra requests to the object store/file system to determine the length which we can avoid.
=> API: Fix default FileIO#newInputFile ManifestFile, DataFile and DeleteFile implementation to pass lengths

open-api/rest-catalog-open-api.py, open-api/rest-catalog-open-api.yaml
Details described on https://github.com/apache/iceberg/issues/9837
=> OpenAPI: Fix additionalProperties for SnapshotSummary

core/src/main/java/org/apache/iceberg/rest/RESTSerializers.java, core/src/main/java/org/apache/iceberg/rest/responses/ConfigResponseParser.java, core/src/main/java/org/apache/iceberg/util/JsonUtil.java, core/src/test/java/org/apache/iceberg/rest/responses/TestConfigResponse.java, core/src/test/java/org/apache/iceberg/rest/responses/TestConfigResponseParser.java, core/src/test/java/org/apache/iceberg/util/TestJsonUtil.java
This introduces an explicit JSON parser for `ConfigResponse` as a preparation step for the `capabilities` that are being introduced by https://github.com/apache/iceberg/pull/9940.
Currently, `ConfigResponse` is relying on reflection to properly do JSON <--> `ConfigResponse`.
Having an explicit JSON parser has the advantage that the underlying `capabilities` can be parsed in a way that gives us more flexiblity and allows to be fully forward/backward compatible when new capabilities are being added.
=> Core: Add explicit JSON parser for ConfigResponse

.baseline/checkstyle/checkstyle.xml, aws/src/integration/java/org/apache/iceberg/aws/TestAssumeRoleAwsClientFactory.java, aws/src/integration/java/org/apache/iceberg/aws/TestDefaultAwsClientFactory.java, aws/src/integration/java/org/apache/iceberg/aws/dynamodb/TestDynamoDbCatalog.java, aws/src/integration/java/org/apache/iceberg/aws/dynamodb/TestDynamoDbLockManager.java, aws/src/integration/java/org/apache/iceberg/aws/glue/GlueTestBase.java, aws/src/integration/java/org/apache/iceberg/aws/glue/TestGlueCatalogCommitFailure.java, aws/src/integration/java/org/apache/iceberg/aws/glue/TestGlueCatalogLock.java, aws/src/integration/java/org/apache/iceberg/aws/glue/TestGlueCatalogNamespace.java, aws/src/integration/java/org/apache/iceberg/aws/glue/TestGlueCatalogTable.java, aws/src/integration/java/org/apache/iceberg/aws/lakeformation/LakeFormationTestBase.java, aws/src/integration/java/org/apache/iceberg/aws/lakeformation/TestLakeFormationAwsClientFactory.java, aws/src/integration/java/org/apache/iceberg/aws/lakeformation/TestLakeFormationDataOperations.java, aws/src/integration/java/org/apache/iceberg/aws/lakeformation/TestLakeFormationMetadataOperations.java, aws/src/integration/java/org/apache/iceberg/aws/s3/TestS3FileIOIntegration.java, aws/src/integration/java/org/apache/iceberg/aws/s3/TestS3MultipartUpload.java, build.gradle
Migrate AWS integration tests to JUnit 5 for https://github.com/apache/iceberg/issues/9080
All tests in `iceberg-aws/test` already use JUnit5 and AssertJ.
The following integration tests need to be migrated.
`iceberg-aws/integration/java/org.apache.iceberg.aws/`:
* `S3TestUtil` (not a test file)
* `AwsIntegTestUtil` (not a test file)
=> Migrate AWS tests to JUnit5

format/spec.md
Fixes #5251
It seems unlikely we will address this discrepancy by dropping support for binary. I'd like to propose documenting the currently implemented behavior instead.
=> Docs: Document support for binary in truncate transform

docs/docs/spark-ddl.md
I propose following three modifications.
- Fix a broken bullet point display.
- Fix inconsistency between comment and SQL
> -- CREATE audit-branch at snapshot 1234, retain audit-branch for 31 days, and retain the latest 31 days. The latest 3
> snapshot snapshots, and 2 days worth of snapshots. 
> ALTER TABLE prod.db.sample CREATE BRANCH `audit-branch`
> AS OF VERSION 1234 RETAIN 30 DAYS 
> WITH SNAPSHOT RETENTION 3 SNAPSHOTS 2 DAYS
- A little clearer explanation of the respective options for DDLs.
I would be happy for you to review my proposal.
=> Docs: Fix On-screen display issues and minor expressions on Branching and Tagging DDL

site/overrides/partials/footer.html
Fixed the issue #10099 by using absolute links instead of relative links.
=> Docs: Fix links of `Get Started` and `Community` sections in footer

core/src/main/java/org/apache/iceberg/rest/HTTPClient.java, core/src/test/java/org/apache/iceberg/rest/TestHTTPClient.java
This PR includes code changes to extend the capability of the existing rest HTTPClient to allow setting a proxy server with basic username/password authentication. The requests made by the HTTPClient will be routed via the proxy server if the HTTPClient is configured with one. If the HTTPClient is not configured with a proxy we default to the current behavior.
=> Extend HTTPClient Builder to allow setting a proxy server

spark/v3.4/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/optimizer/ReplaceStaticInvoke.scala, spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/SparkPlanUtil.java, spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestSystemFunctionPushDownInRowLevelOperations.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/functions/BaseScalarFunction.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/functions/BucketFunction.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/functions/DaysFunction.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/functions/HoursFunction.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/functions/IcebergVersionFunction.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/functions/MonthsFunction.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/functions/TruncateFunction.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/functions/YearsFunction.java
This PR cherry-picks PR #9873 to Spark 3.4.
=> Spark 3.4: Fix system function pushdown in CoW row-level commands

api/src/main/java/org/apache/iceberg/FileFormat.java, core/src/main/java/org/apache/iceberg/BaseFile.java, core/src/main/java/org/apache/iceberg/CachingCatalog.java, core/src/main/java/org/apache/iceberg/GenericManifestEntry.java, core/src/main/java/org/apache/iceberg/GenericManifestFile.java, core/src/main/java/org/apache/iceberg/hadoop/HadoopTableOperations.java, kafka-connect/kafka-connect-events/src/main/java/org/apache/iceberg/connect/events/Event.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/SparkContentFile.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/SparkContentFile.java
reduce enum array allocation
cache enum .values() in a static variable
https://www.gamlor.info/wordpress/2017/08/javas-enum-values-hidden-allocations/
=> reduce enum array allocation

open-api/rest-catalog-open-api.yaml
=> Spec: required request bodies

docs/docs/spark-configuration.md, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/BaseCatalog.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/SparkCatalog.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/SparkSessionCatalog.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/TestSparkCatalogOperations.java
This PR adds a new catalog parameter `use-nullable-query-schema` to control whether to set all fields to null in CTAS and RTAS operations. 
Currently, when using CTAS and RTAS to create tables, the fields of new tables are always marked as optional, even if thier source fileds are marked as required in the original table. By utilizing the parameter `use-nullable-query-schema`, we can control whether to preserve the nullability of fields when creating a new table using CTAS or RTAS.
Set `use-nullable-query-schema` to `false` to preserve the nullability of fields:
```shell 
spark.sql.catalog.my_catalog= org.apache.iceberg.spark.SparkCatalog
spark.sql.catalog.my_catalog.use-nullable-query-schema=false
...
```
Releated Spark PR: [SPARK-43390](https://github.com/apache/spark/pull/41070)
Close …
=> Spark-3.5: Support CTAS and RTAS to preserve schema nullability.

flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/source/TestFlinkSource.java, flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/source/TestFlinkSource.java, flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/source/TestFlinkSource.java, spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/SparkTableUtil.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/SparkTableUtil.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/SparkTableUtil.java
`Boolean.getBoolean()` will look for a system property of the given name, whereas `Boolean.parseBoolean()` will parse the given string to a boolean.
=> Flink, Spark: Replace Boolean.getBoolean() with Boolean.parseBoolean()

spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/SparkSchemaUtil.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/SparkSchemaUtil.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/SparkSchemaUtil.java
Small refactoring of SparkSchemaUtil#schemaForTable, I noticed when doing #10133  we can just use the existing convert method
=> Spark: Simplify SparkSchemaUtil#schemaForTable

data/src/test/java/org/apache/iceberg/data/DataTest.java, data/src/test/java/org/apache/iceberg/data/avro/TestGenericData.java, data/src/test/java/org/apache/iceberg/data/orc/TestGenericData.java, data/src/test/java/org/apache/iceberg/data/parquet/TestGenericData.java, data/src/test/java/org/apache/iceberg/data/parquet/TestParquetEncryptionWithWriteSupport.java, flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/data/TestFlinkAvroReaderWriter.java, flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/data/TestFlinkOrcReaderWriter.java, flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/data/TestFlinkParquetReader.java, flink/v1.16/flink/src/test/java/org/apache/iceberg/flink/data/TestFlinkParquetWriter.java, flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/data/TestFlinkAvroReaderWriter.java, flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/data/TestFlinkOrcReaderWriter.java, flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/data/TestFlinkParquetReader.java, flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/data/TestFlinkParquetWriter.java, flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/AvroGenericRecordConverterBase.java, flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/TestDataFileSerialization.java, flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/TestFlinkCatalogFactory.java, flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/TestFlinkFilters.java, flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/TestFlinkSchemaUtil.java, flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/TestManifestFileSerialization.java, flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/TestRowDataWrapper.java, flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/TestTableSerialization.java, flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/data/TestFlinkAvroReaderWriter.java, flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/data/TestFlinkOrcReaderWriter.java, flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/data/TestFlinkParquetReader.java, flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/data/TestFlinkParquetWriter.java, flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/data/TestRowProjection.java, flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/data/TestStructRowData.java, flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/sink/TestAvroGenericRecordToRowDataMapper.java, flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/source/TestRowDataToAvroGenericRecordConverter.java, flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/util/TestFlinkPackage.java
Migrate the following classes in `iceberg-flink` and `iceberg-data` to JUnit 5 for https://github.com/apache/iceberg/issues/9087
`iceberg-flink` (v1.18) 
`DataTest` related classes in `iceberg-data`:
=> Migrate non TestBase related and Data classes in Flink

aws/src/main/java/org/apache/iceberg/aws/dynamodb/DynamoDbLockManager.java
With the new close method added to BaseLockManager, I noticed that DynamoDbLockManager was not reusing inherited `close` and, hence, not closing the underlying executor.
It's my first PR here, so let me know if I'm missing some guidelines. Thx.
=> AWS: close underlying executor for DynamoDb LockManager

api/src/main/java/org/apache/iceberg/actions/RewriteDataFiles.java, core/src/main/java/org/apache/iceberg/actions/BaseCommitService.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/actions/RewriteDataFilesSparkAction.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteDataFilesAction.java
When partial progress is enabled, `rewrite_data_files` Spark app can succeed without any "progress" (commits). This PR adds an option `partial-progress.max-failed-commits` and a RuntimeException will be thrown if the number of failed commits exceed it. The default value is `partital-progress.max-commits` to be consistent with current behavior.
=> Spark 3.5: Add max allowed failed commits to RewriteDataFiles when partial progress is enabled

core/src/main/java/org/apache/iceberg/jdbc/JdbcUtil.java, core/src/test/java/org/apache/iceberg/jdbc/TestJdbcCatalog.java, core/src/test/java/org/apache/iceberg/jdbc/TestJdbcUtil.java
This PR fixes table commit on the JDBC Catalog.
When upgrading JDBC Catalog SQL schema from `V0` to `V1`, the `iceberg_type` column is added with `NULL` value by default.
However, the SQL statement to update table (updating metadata location for instance) expects `iceberg_type` contains `TABLE`. It doesn't test if `iceberg_type` is `NULL`.
This PR updates the SQL statement to deal with `NULL` or `TABLE` for `iceberg_type`.
This closes #10046
=> Core: Fix JDBC Catalog table commit when migrating from schema V0 to V1

flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/AvroGenericRecordConverterBase.java, flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/TestDataFileSerialization.java, flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/TestFlinkCatalogFactory.java, flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/TestFlinkFilters.java, flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/TestFlinkSchemaUtil.java, flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/TestManifestFileSerialization.java, flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/TestRowDataWrapper.java, flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/TestTableSerialization.java, flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/sink/TestAvroGenericRecordToRowDataMapper.java, flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/source/TestRowDataToAvroGenericRecordConverter.java, flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/util/TestFlinkPackage.java
Backport the v1.18 changes in #10130 to v1.17 ~~and v1.16~~ (v1.16 was already removed, so skipped the migration for this version)
=> Backport Flink 1.18 JUnit5 migration to Flink 1.17

core/src/main/java/org/apache/iceberg/jdbc/JdbcUtil.java
=> Core: Fix namespace SQL statement using ESCAPE character that works with MySQL/PostgreSQL (#10167)

spark/v3.4/spark-extensions/src/main/scala/org/apache/spark/sql/catalyst/optimizer/ReplaceStaticInvoke.scala, spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/SparkPlanUtil.java, spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestSystemFunctionPushDownInRowLevelOperations.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/functions/BaseScalarFunction.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/functions/BucketFunction.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/functions/DaysFunction.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/functions/HoursFunction.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/functions/IcebergVersionFunction.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/functions/MonthsFunction.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/functions/TruncateFunction.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/functions/YearsFunction.java
=> (1.5.x Cherry-pick) Spark 3.4: Fix system function pushdown in CoW row-level commands (#10119)

flink/v1.18/flink/src/main/java/org/apache/iceberg/flink/source/split/IcebergSourceSplit.java, flink/v1.18/flink/src/main/java/org/apache/iceberg/flink/source/split/IcebergSourceSplitSerializer.java, flink/v1.18/flink/src/main/java/org/apache/iceberg/flink/source/split/SerializerHelper.java, flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/source/SplitHelpers.java, flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/source/split/TestIcebergSourceSplitSerializer.java
The changes in this PR is addressing the problem in #9410 which makes it problematic to consume from an Iceberg table which is getting regular upserts. 
The problem occurs [on this line](https://github.com/apache/flink/blob/master/flink-core/src/main/java/org/apache/flink/core/memory/DataOutputSerializer.java#L257) with Flink's DataOutputserializer object when the size of an object which is being serialized is above 65kb and that limit is easily exceeded for those tables which are having too many deleted files due to regular upserts.
=> Flink: Don't fail to serialize IcebergSourceSplit when there is too many delete files

core/src/test/java/org/apache/iceberg/catalog/CatalogTests.java
These assertions failed for me in a different context and the only info they would print is `0 != 1`. I've slightly updated the check so that when the assertion fails, you'll get more context:
```
[Table should have correct number of previous metadata locations] 
Expected size: 0 but was: 1 in:
[MetadataLogEntry{timestampMillis=1713510157942, file=path-to-metadata.json}]
```
=> Core: Improve size check in CatalogTests

aws/src/main/java/org/apache/iceberg/aws/s3/S3FileIOProperties.java, aws/src/test/java/org/apache/iceberg/aws/TestS3FileIOProperties.java, aws/src/test/java/org/apache/iceberg/aws/s3/TestS3FileIOProperties.java
This fixes an issue where the remote signing configuration is being overriden/ignored when the user-agent configuration is being applied. This is because calling `overrideConfiguration(Consumer<ClientOverrideConfiguration.Builder> overrideConfiguration)` creates a new `ClientOverrideConfiguration` and ignores any existing ones that might have been set previously. 
The `s3RemoteSigningEnabledWithUserAgent()` test reproduces the issue and fails without the fix being proposed here.
=> AWS: Make sure Signer + User Agent config are both applied

hive-metastore/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java, mr/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerNoScan.java, mr/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergWithHiveAutogatherEnable.java
Hive engine collects the stats by traversing the folder to count number of files and size when the table is created and hive.stats.autogather is turned on. The operation can be expensive for a large table while for iceberg table the stats is not needed to be stored on HMS. When the iceberg.hive.keep.stats is set to false, add table parameter "DO_NOT_UPDATE_STATS" so that Hive engine won't collect the stats.
=> Hive: turn off the stats gathering when iceberg.hive.keep.stats is false

site/docs/releases.md
@pvary had different random failures on the Release page in https://github.com/apache/iceberg/pull/10200, so I'd suggest that we completely skip checking links on this particular site
=> Docs: Don't check links on Release page

aws/src/integration/java/org/apache/iceberg/aws/glue/TestGlueCatalogTable.java
TestGlueCatalogTable#testCreateTable failed by the following assertion error:
```
org.opentest4j.AssertionFailedError: 
expected: 
["s3://iceberg-integ-684001615763-ap-northeast-3/writeDataLoc",
"s3://iceberg-integ-684001615763-ap-northeast-3/writeMetaDataLoc",
"s3://iceberg-integ-684001615763-ap-northeast-3/writeFolderStorageLoc"]
but was: 
["s3://iceberg-integ-684001615763-ap-northeast-3/writeFolderStorageLoc",
"s3://iceberg-integ-684001615763-ap-northeast-3/writeDataLoc",
"s3://iceberg-integ-684001615763-ap-northeast-3/writeMetaDataLoc"]
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAc …
```
=> AWS: Fix TestGlueCatalogTable#testCreateTable

format/spec.md
Jan raised a point on Slack of the semantic meaning of a field that can be written:
https://apache-iceberg.slack.com/archives/C03LG1D563F/p1695834739711569
There are two options:
- The field is not part of the schema, and is omitted from the file
- The field is part of the schema, but the value is not written (nullable)
My personal take on this is that we should use static schema when writing Avro files so that all the fields that are either optional or required are in the schema.
I'm well aware that this doesn't impose any issues if you dogfood the Iceberg Avro reader, where you can add required fields, for example, the `134: content` field in the manifest.
However, I think we should try to stick to the concept of writing strictly, read permissive where we try to encourage people to …
=> Spec: Clarify missing fields when writing

flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/source/IcebergSource.java, flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/SimpleDataUtil.java, flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/source/TestIcebergSourceFailover.java, flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/source/TestIcebergSourceFailoverWithWatermarkExtractor.java
On Bounded source state restore the splits are added again to the enumerator which causes data duplication downstream.
=> Flink: Fix bounded source state restore record duplication

core/src/main/java/org/apache/iceberg/rest/RESTSessionCatalog.java
The thread currently is always named "null-token-refresh" because `tokenRefreshExecutor()` is called before the catalog name is set.
=> REST: fix incorrect token refresh thread name

flink/v1.17/flink/src/main/java/org/apache/iceberg/flink/source/IcebergSource.java, flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/SimpleDataUtil.java, flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/source/TestIcebergSourceFailover.java, flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/source/TestIcebergSourceFailoverWithWatermarkExtractor.java, flink/v1.18/flink/src/main/java/org/apache/iceberg/flink/source/IcebergSource.java, flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/SimpleDataUtil.java, flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/source/TestIcebergSourceFailover.java, flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/source/TestIcebergSourceFailoverWithWatermarkExtractor.java
Clean backport with:
```
git diff df2a729b11bb5411ae46f8139eba2aa4beef84e3^ df2a729b11bb5411ae46f8139eba2aa4beef84e3 |sed "s/v1.19/v1.18/g" | g apply -3 -p1   
git diff df2a729b11bb5411ae46f8139eba2aa4beef84e3^ df2a729b11bb5411ae46f8139eba2aa4beef84e3 |sed "s/v1.19/v1.17/g" | g apply -3 -p1   
```
=> Flink: Backport #10208 to v1.18 and v1.17

flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/source/FlinkSource.java, flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/source/IcebergSource.java, flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/source/ScanContext.java, flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/source/TestFlinkInputFormat.java, flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/source/TestIcebergSourceBounded.java, flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/source/TestIcebergSourceContinuous.java, flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/source/TestScanContext.java, flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/source/TestStreamScanSql.java
Tried to hack around issues with setting `endSnapshotId` for a streaming job. It turns out the code is silently overwriting the values set in the context.
Since it doesn't make sense to set `end` for the streaming case, I propose to add validation to prevent these cases.
The `Preconditions` are copied from `StreamingMonitorFunction` used by the old FlinkSource implementation.
=> Flink: Prevent setting endTag/endSnapshotId for streaming source

flink/v1.17/flink/src/main/java/org/apache/iceberg/flink/source/FlinkSource.java, flink/v1.17/flink/src/main/java/org/apache/iceberg/flink/source/IcebergSource.java, flink/v1.17/flink/src/main/java/org/apache/iceberg/flink/source/ScanContext.java, flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/source/TestFlinkInputFormat.java, flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/source/TestIcebergSourceBounded.java, flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/source/TestIcebergSourceContinuous.java, flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/source/TestScanContext.java, flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/source/TestStreamScanSql.java, flink/v1.18/flink/src/main/java/org/apache/iceberg/flink/source/FlinkSource.java, flink/v1.18/flink/src/main/java/org/apache/iceberg/flink/source/IcebergSource.java, flink/v1.18/flink/src/main/java/org/apache/iceberg/flink/source/ScanContext.java, flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/source/TestFlinkInputFormat.java, flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/source/TestIcebergSourceBounded.java, flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/source/TestIcebergSourceContinuous.java, flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/source/TestScanContext.java, flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/source/TestStreamScanSql.java
Clean backport with:
```
git diff 646440abf6f1d6a5c06979b5939c33c5a410a7ba^ 646440abf6f1d6a5c06979b5939c33c5a410a7ba |sed "s/v1.19/v1.17/g" | g apply -3 -p1
git diff 646440abf6f1d6a5c06979b5939c33c5a410a7ba^ 646440abf6f1d6a5c06979b5939c33c5a410a7ba |sed "s/v1.19/v1.18/g" | g apply -3 -p1
```
=> Clean backport with:Flink: Backport #10207 to v1.18 and v1.17

core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java, core/src/main/java/org/apache/iceberg/jdbc/JdbcUtil.java, core/src/test/java/org/apache/iceberg/jdbc/TestJdbcCatalog.java
It would be helpful to disable the creation of the catalog tables used by the JdbcCatalog to maintain the principle of least privilege.  In my scenario, I would like to perform database migrations with a migration tool using a user with DDL privileges and use a separate user with only DML privileges for connecting the JdbcCatalog to the database.
=> Core: Add property to disable table initialization for JdbcCatalog

flink/v1.17/flink/src/main/java/org/apache/iceberg/flink/sink/BaseDeltaTaskWriter.java, flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkV2.java, flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/sink/BaseDeltaTaskWriter.java, flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkV2.java
Clean backport of #10200 to Flink v1.19 and v1.17
```
g d 1757577937d0e9c385ace059b8e8f7f1f75d5fc1^ 1757577937d0e9c385ace059b8e8f7f1f75d5fc1|sed "s/v1.18/v1.19/g" | g apply -3 -p1 
g d 1757577937d0e9c385ace059b8e8f7f1f75d5fc1^ 1757577937d0e9c385ace059b8e8f7f1f75d5fc1|sed "s/v1.18/v1.17/g" | g apply -3 -p1 
```
=> Flink: Backport #10200 to v1.19 and v1.17

.gitignore, docs/docs/flink-writes.md
The link to flink 1.16 unit test is broken after https://github.com/apache/iceberg/pull/10154. I remove it in this PR since 
1. I don't see an example of `write generic `DataStream<T>` to iceberg table` from the unit test as the doc stated
2. We don't trigger links check on source code changes so it will break next if we only update the link to latest version
The PR also adds `docs/site` to `.gitignore` file.
cc @nastra @pvary @rodmeneses @Fokko
=> Docs: Remove link to Flink unit test

format/spec.md
The documentation site does not show the rules as a list because some markdown readers need an empty line between a paragraph and a list.
The list on the docs site currently looks like this:
=> Fix struct evolution default value rule list

core/src/main/java/org/apache/iceberg/ClientPoolImpl.java, core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java, core/src/main/java/org/apache/iceberg/jdbc/JdbcClientPool.java, core/src/main/java/org/apache/iceberg/jdbc/JdbcUtil.java, core/src/test/java/org/apache/iceberg/TestClientPoolImpl.java, core/src/test/java/org/apache/iceberg/jdbc/TestJdbcCatalog.java
This change is an alternative to https://github.com/apache/iceberg/pull/7561 for retrying JDBC connections.
First, we currently retry SQLNonTransientExceptions which is a bug. Those are non-retryable by definition, we should retry SQLTransientExceptions.
Next, this change also enables configuring multiple retries since just retrying once may not increase the chance of success sufficiently.
Lastly, this change introduces the ability for a user to configure which SQL error codes they want to retry on on top of the standard retryable error codes. The reason is there's so many different databases out there each with their own status codes that Iceberg shouldn't define all those in the library. This approach allows a user to specify the ones they want to retry via a catalog property called …
=> Core: Retry connections in JDBC catalog with user configured error code list

spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/SparkConfParser.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/SparkReadConf.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/TestSparkWriteConf.java
This PR removes some conf parsing logic that predates the split of Spark 2 and Spark 3.
=> Spark 3.5: Remove obsolete conf parsing logic

spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/SparkConfParser.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/SparkReadConf.java
Add `EnumConfParser` to `SparkConfParser` to parse Enum type properties
=> Add EnumConfParser to SparkConfParser

spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/sql/TestAggregatePushDown.java, spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/sql/TestAggregatePushDown.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/sql/TestAggregatePushDown.java
Backport the tests from #9176 to Spark 3.3/Spark 3.4 to ensure we have coverage for those versions. This change also cleans up the original assertion (it's logically the same but in case of failures will surface more meaningful context)
=> Spark: Backport tests for struct aggregation pushdown to 3.3/3.4

spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/SparkConfParser.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/SparkReadConf.java
https://github.com/apache/iceberg/pull/10311 added an Enum conf parser in Spark3.5. This PR cherry picks the changes to spark 3.4
=> Spark3.4: Add support for enums in SparkConfParser

aws/src/integration/java/org/apache/iceberg/aws/glue/GlueTestBase.java, aws/src/integration/java/org/apache/iceberg/aws/glue/TestGlueCatalogTable.java, aws/src/main/java/org/apache/iceberg/aws/glue/GlueTableOperations.java
In AWS Glue Catalog, user can set arbitrary description to the table and its columns via Web UI or even from Amazon Athena. However, the descriptions will be removed after upgrading the table.
This patch is to keep the original table description when calling `UpdateTable` API. Keeping column description is hard and I think we can open a different PR to do this.
Manually tested. Also, added an integration test and it passed on my environment.
=> AWS: Retain Glue Catalog table description after updating Iceberg table

kafka-connect/kafka-connect/src/main/java/org/apache/iceberg/connect/data/IcebergWriterFactory.java, kafka-connect/kafka-connect/src/test/java/org/apache/iceberg/connect/data/IcebergWriterFactoryTest.java
Some catalogs like Inmemory, Hive, Nessie, REST catalog expects the namespace to be present before creating the table. Hence, the auto table creation feature will not work currently for these catalogs if the namespace is missing. 
Added a support to create the missing namespace and its parents while auto creating the table.
=> Kafka-connect: Handle namespace creation for auto table creation

spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRemoveOrphanFilesProcedure.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/procedures/RemoveOrphanFilesProcedure.java
This PR correct the setting of procedure parameter `equalAuthorities` for `RemoveOrphanFilesProcedure`. Previously it seems to be wrongly set.
=> Spark 3.5: Fix the setting of equalAuthorities in RemoveOrphanFilesProcedure

spark/v3.3/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRemoveOrphanFilesProcedure.java, spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/procedures/RemoveOrphanFilesProcedure.java, spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRemoveOrphanFilesProcedure.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/procedures/RemoveOrphanFilesProcedure.java
PR #10334 corrected the setting of procedure parameter `equalAuthorities` for `RemoveOrphanFilesProcedure` for Spark 3.5, this PR correct the same procedure parameter for Spark 3.4 and 3.3.
=> Spark 3.4, 3.3: Fix the setting of equalAuthorities in RemoveOrphanFilesProcedure

1.4.0/mkdocs.yml, 1.4.1/mkdocs.yml, 1.4.2/mkdocs.yml, 1.4.3/mkdocs.yml, 1.5.0/mkdocs.yml, 1.5.1/mkdocs.yml, 1.5.2/mkdocs.yml
"dev" refers to the documentation for the master branch of Apache Doris.
=> Docs: update Apache Doris  dead links

core/src/test/java/org/apache/iceberg/metrics/TestCommitMetricsResultParser.java, core/src/test/java/org/apache/iceberg/metrics/TestScanMetricsResultParser.java, spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestSystemFunctionPushDownInRowLevelOperations.java
This PR removes redundant output in tests.
=> Core, Spark 3.4: Remove redundant output in tests

core/src/main/java/org/apache/iceberg/deletes/BitmapPositionDeleteIndex.java
I was going through our delete file indexing logic, and noticed Roaring64BitMap#add(start, end) is deprecated in favor of addRange, so this change just addresses that.
=> Core: Replace deprecated Roaring64Bitmap#add call with addRange

spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/data/SparkParquetWriters.java, spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/source/TestDataFrameWriterV2Coercion.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/data/SparkParquetWriters.java, spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/source/TestDataFrameWriterV2Coercion.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/data/SparkParquetWriters.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestDataFrameWriterV2Coercion.java
Fixes #10225 
#9440 refactored the Spark Parquet writer to move to a visitor pattern. During this move, it [removed some code](https://github.com/apache/iceberg/blame/9f979a1ff187ebd69ef3b027d857ee697fd9c52c/spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/data/SparkParquetWriters.java#L204-L211) required for coercion from bytes/shorts to int. This PR adds back the coercion code along with unit tests validating the change.
Note that even without coercion code, the tests succeed in Spark 3.5 but not in 3.3 and 3.4. It succeeds in 3.5 due to https://github.com/apache/spark/pull/40734 which routes CTAS/RTAS through `AppendData`, in which case Spark adds its own projection to handle coercion [here](https://github.com/apache/spark/blob/1a454287c01eb2ddda3e11afcc8c4885abc095b2/sql/catalys …
=> Spark: Coerce shorts and bytes into ints in Parquet Writer

hive-metastore/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java, hive-metastore/src/test/java/org/apache/iceberg/hive/TestHiveCommits.java
Use base (instead of new) table metadata to create the lock object, so that concurrent commits use the same lock mechanism.
Fixes #10006
=> Hive: Use base table metadata to create HiveLock

spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/SparkConfParser.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/TestSparkWriteConf.java
This PR adds support for parsing camel case session configs and options. Our keys contain `-` but all built-in Spark configs follow the camel case style. Apart from the inconsistency, setting Iceberg SQL configs requires escaping the keys, which makes it confusing for the users.
The following statement throws an error and requires the user to manually deal with `-`.
```
SET spark.sql.iceberg.planning.preserve-data-grouping = false
```
After this change, users will be able to set SQL properties and options either using `-` or camel case.
```
SET spark.sql.iceberg.planning.preserveDataGrouping = false
SET `spark.sql.iceberg.planning.preserve-data-grouping` = false
```
We already have a precedent for this in `SparkWriteOptions`.
```
public static final String MERGE_SCHEMA = "merge-schema"; …
```
=> Spark 3.5: Support camel case session configs and options

api/src/main/java/org/apache/iceberg/PartitionSpec.java, api/src/test/java/org/apache/iceberg/TestPartitionPaths.java, core/src/test/java/org/apache/iceberg/TestLocationProvider.java
Field names can contain special characters that result in failure to produce valid paths using path based layout providers and possibly breaks usage of HadoopFileIO based FileSystem implementations.
This PR encodes the field name in addition to the preexisting encoding for the partition values.
Fixes #10279 
See also: #10283
cc. @dimas-b
=> Url encode field names for partition paths

spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestChangelogTable.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/source/SparkScanBuilder.java
Back-port of #10252 to Spark 3.4
cc @flyrain
=> Spark 3.4: Only traverse ancestors of current snapshot when building changelog scan

site/README.md, site/docs/how-to-release.md
=> Docs: Refer to the README.md in `site/` for the docs

.asf.yaml
It is _very_ easy to accidentally write to the `main` branch through the GitHub UI:
This happened to me just now 😭  https://github.com/apache/iceberg/commit/23eb5941cd599183be63676c9d1379ba102b1a97 While through the GitHub UI, the changes will probably be minor, I think it is good to avoid accidents and require explicit approval. After setting this, you'll get:
We have the required approval for [PyIceberg](https://github.com/apache/iceberg-python/blob/31c6c23d428a3237589ebada2b4cd64bf37b1aef/.asf.yaml#L37-L38), [iceberg-rust](https://github.com/apache/iceberg-rust/blob/1aa05e0e12f7152bb473101cfb06feeb76b7c66f/.asf.yaml#L41) and [iceberg-go](https://github.com/apache/iceberg-go/blob/60da61cc0368b889b74dbcc070f835a3cfb76914/.asf.yaml#L38).
=> Build: Require approving review

aws/src/main/java/org/apache/iceberg/aws/s3/signer/S3V4RestSignerClient.java, core/src/main/java/org/apache/iceberg/rest/RESTSessionCatalog.java, core/src/main/java/org/apache/iceberg/rest/auth/AuthConfig.java, core/src/main/java/org/apache/iceberg/rest/auth/OAuth2Util.java
Over time it became quite painful to add new parameters/functionality to `AuthSession` as can be seen with the recent changes from https://github.com/apache/iceberg/pull/8976 and from https://github.com/apache/iceberg/pull/9839.
Hence I'm proposing an `AuthConfig` class that carries all of the relevant configuration for an `AuthSession`.
=> Core: Introduce AuthConfig

core/src/test/java/org/apache/iceberg/TestPartitionSpecInfo.java, core/src/test/java/org/apache/iceberg/TestPartitionSpecParser.java
I've noticed that the `formatVersion` parameter wasn't properly initialized for this test class because the tests weren't annotated with `@TestTemplate`
=> Core: Use TestTemplate instead of Test annotation in TestPartitionSpecParser/Info

core/src/main/java/org/apache/iceberg/rest/RESTMetricsReporter.java, docs/docs/metrics-reporting.md
~~It looks from the [doc](https://iceberg.apache.org/docs/1.4.3/metrics-reporting/#restmetricsreporter) that `RESTMetricsReporter` is available for users. However, it's not a public class. This PR makes it public and add some javadocs. It also fixes its javadoc missing issue.~~
=> Docs: Point links in metrics-reporting.md to GitHub Java source

core/src/test/java/org/apache/iceberg/TestMetrics.java, orc/src/main/java/org/apache/iceberg/orc/OrcMetrics.java, parquet/src/main/java/org/apache/iceberg/parquet/ParquetUtil.java
Currently, the Iceberg Parquet and ORC writers will write out column sizes even when metrics are disabled. This should not be the case since column sizes are optional in the spec and we should respect the property for this case.
=> Core, Parquet, ORC: Don't write column sizes when metrics mode is None

flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/maintenance/operator/MonitorSource.java, flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/maintenance/operator/SingleThreadedIteratorSource.java, flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/maintenance/operator/TableChange.java, flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/maintenance/operator/CollectingSink.java, flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/maintenance/operator/FlinkSqlExtension.java, flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/maintenance/operator/FlinkStreamingTestUtils.java, flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/maintenance/operator/ManualSource.java, flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/maintenance/operator/OperatorTestBase.java, flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/maintenance/operator/TestMonitorSource.java
Implements a monitor source which emits TableChange events based on the new commits to the Iceberg table.
This will be used for Maintenance Task scheduling as described in the [design doc](https://docs.google.com/document/d/16g3vR18mVBy8jbFaLjf2JwAANuYOmIwr15yDDxovdnA). The Scheduling paragraph describes the require parameters of the TableChange object. Also the Monitor paragraph adds some more details.
Implements #10300
=> Flink: Maintenance - MonitorSource

open-api/rest-catalog-open-api.py, open-api/rest-catalog-open-api.yaml
Since we are using the [discriminator](https://swagger.io/docs/specification/data-models/inheritance-and-polymorphism/) field, the type property is inherited from TableRequirements. This PR removed redundant `type` properties in child classes.
=> Open-API: TableRequirements should use union of subclasses

core/src/main/java/org/apache/iceberg/BaseRewriteManifests.java, core/src/test/java/org/apache/iceberg/TestRewriteManifests.java
Users are assuming it is File not found error and it is better to have a message that clarifies that it is missing in metadata but not in the disk. 
https://apache-iceberg.slack.com/archives/C03LG1D563F/p1717453961622069
=> Core: Reword exception message in RewriteManifests 

.github/workflows/spark-ci.yml
GitHub allows to delete and re-publish a tag, so referencing 3rd party action by tag name should be discouraged.
=> Pin 3rd party CI action version

core/src/main/java/org/apache/iceberg/CatalogUtil.java
This PR simplifies the loadCatalog method call in Iceberg by removing the redundant CatalogUtil class qualifier. The change improves code readability.
=> Core: Simplify loadCatalog method call in Iceberg

mr/src/main/java/org/apache/iceberg/mr/Catalogs.java
This PR optimizes the retrieval of the schema string in Iceberg. Instead of calling `props.getProperty(InputFormatConfig.TABLE_SCHEMA)` twice, the method is now called once and the result is stored in the schemaString variable. This variable is then used for parsing the schema, reducing unnecessary method calls and improving code efficiency.
=> Mr: Optimize schema string retrieval in Iceberg

.github/workflows/java-ci.yml, .github/workflows/publish-snapshot.yml, README.md, settings.gradle
The meaning of the flag is to enable all modules. In particular, it does not enable all Scala versions for the build. The new name more directly conveys the intent.
=> Rename allVersions to allModules

aws/src/test/java/org/apache/iceberg/aws/TestAwsClientFactories.java
The test helper `assertThatThrownBy` had same name like `Assertions.assertThatThrownBy` but different API (not assertion builder). Rename to avoid confusion.
=> Rename test helper to deconflict with Assertions

spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/actions/RewriteManifestsSparkAction.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/actions/RewriteManifestsSparkAction.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/actions/RewriteManifestsSparkAction.java
This change uses bulk deletes when possible when cleaning up files as part of any failure or as part of the staging logic for v1 tables.
=> Spark: Use bulk deletes in rewrite manifests action

build.gradle
The JVM flags are set depending on Java version.  We should not be setting any flags that are not expected to be supported.
=> Remove redundant -XX:+IgnoreUnrecognizedVMOptions

format/spec.md
The list doesn't seem to work with a `-`, a `*` seems to do the trick (also used below).
=> spec: Fix formatting of Default values

docs/docs/flink-connector.md, docs/docs/flink-ddl.md, docs/docs/flink-queries.md, docs/docs/flink.md, site/mkdocs.yml
=> Docs: Add flinkVersion and flinkVersionMajor instead of hardcode

core/src/main/java/org/apache/iceberg/TableMetadata.java
This pr simplifies the newTableMetadata method call in Iceberg by removing the redundant TableMetadata class.
We can create `TableMetadata` object by using method 'org.apache.iceberg.TableMetadata#newTableMetadata(org.apache.iceberg.Schema, org.apache.iceberg.PartitionSpec, org.apache.iceberg.SortOrder, java.lang.String, java.util.Map<java.lang.String,java.lang.String>)' so that we can remove redundant code as follow： 
`int formatVersion =
PropertyUtil.propertyAsInt(
properties, TableProperties.FORMAT_VERSION, DEFAULT_TABLE_FORMAT_VERSION);`
=> Core：Simplify newTableMetadata method in TableMetadata class

.github/workflows/api-binary-compatibility.yml
a PR updating gradle (https://github.com/apache/iceberg/pull/10474) should not have green CI because of the revapi problem outlined here https://github.com/apache/iceberg/pull/10476#issuecomment-2160331173. run the revapi checks when CI workflows or build system configuration changes
=> Run revapi workflow on workflow/build system changes

api/src/main/java/org/apache/iceberg/expressions/ExpressionUtil.java, api/src/main/java/org/apache/iceberg/expressions/Projections.java, arrow/src/main/java/org/apache/iceberg/arrow/vectorized/GenericArrowVectorAccessorFactory.java, core/src/main/java/org/apache/iceberg/DeleteFileIndex.java, core/src/main/java/org/apache/iceberg/hadoop/HadoopStreams.java, flink/v1.17/flink/src/main/java/org/apache/iceberg/flink/sink/shuffle/MapRangePartitioner.java, flink/v1.17/flink/src/main/java/org/apache/iceberg/flink/source/enumerator/EnumerationHistory.java, flink/v1.18/flink/src/main/java/org/apache/iceberg/flink/sink/shuffle/MapRangePartitioner.java, flink/v1.18/flink/src/main/java/org/apache/iceberg/flink/source/enumerator/EnumerationHistory.java, flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/sink/shuffle/MapRangePartitioner.java, flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/source/enumerator/EnumerationHistory.java, parquet/src/main/java/org/apache/iceberg/parquet/ParquetAvro.java, parquet/src/main/java/org/apache/iceberg/parquet/ParquetValueReaders.java, parquet/src/main/java/org/apache/iceberg/parquet/ParquetValueWriters.java
Found by https://github.com/apache/iceberg/pull/10518
=> Remove some dead code, fill some javadocs

aliyun/src/main/java/org/apache/iceberg/aliyun/oss/OSSURI.java, api/src/main/java/org/apache/iceberg/catalog/TableIdentifier.java, aws/src/test/java/org/apache/iceberg/aws/s3/signer/S3SignerServlet.java, aws/src/test/java/org/apache/iceberg/aws/s3/signer/TestS3RestSigner.java, core/src/main/java/org/apache/iceberg/avro/AvroSchemaUtil.java, core/src/test/java/org/apache/iceberg/encryption/KeyStoreKmsClient.java, core/src/test/java/org/apache/iceberg/hadoop/TestStaticTable.java, data/src/test/java/org/apache/iceberg/io/TestBaseTaskWriter.java, dell/src/main/java/org/apache/iceberg/dell/ecs/EcsURI.java, flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/sink/TestIcebergStreamWriter.java, flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/sink/TestIcebergStreamWriter.java, flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/sink/TestIcebergStreamWriter.java, hive-metastore/src/main/java/org/apache/iceberg/hive/CachedClientPool.java, mr/src/main/java/org/apache/hadoop/hive/ql/exec/vector/VectorizedSupport.java, mr/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java, mr/src/main/java/org/apache/iceberg/mr/hive/serde/objectinspector/IcebergRecordObjectInspector.java, mr/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerNoScan.java, mr/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerWithEngine.java
Found by https://github.com/apache/iceberg/pull/10518
=> Fix lower/upper-case not to depend on JVM locale

.github/workflows/flink-ci.yml
Project supports building with 8, 11 and 17. In most CI scripts we run the jobs on all supported Java versions, let's do same here to ensure the build would work locally too.
=> Run Flink tests on Java 17 too

.github/workflows/hive-ci.yml, settings.gradle
Project supports building with 8, 11 and 17. In most CI scripts we run the jobs on all supported Java versions, let's do same here to ensure the build would work locally too.
Relates to: https://github.com/apache/iceberg/pull/10477
=> Run Hive3 tests on Java 11 and 17 too

core/src/main/java/org/apache/iceberg/FastAppend.java, core/src/main/java/org/apache/iceberg/MergingSnapshotProducer.java, core/src/test/java/org/apache/iceberg/TestBaseIncrementalAppendScan.java, core/src/test/java/org/apache/iceberg/TestFastAppend.java, core/src/test/java/org/apache/iceberg/TestMergeAppend.java, core/src/test/java/org/apache/iceberg/TestRewriteFiles.java, core/src/test/java/org/apache/iceberg/TestSnapshotSummary.java
One of the reasons for preventing duplicate files is that adding/deleting the same data/delete file X times will update snapshot summary stats for each file, resulting in unexpected stats.
I've added tests for all subclasses of `SnapshotUpdate` to see how stats behave with multiple files.
`TestSnapshotSummary#rewriteWithDuplicateFiles` shows e.g. how stats can be off when duplicates exist. In the below example, stats like `"total-data-files"="5"` / `"total-files-size"="50"` are far off:
```
{"added-data-files"="3", "added-files-size"="30", "added-records"="3", "changed-partition-count"="1", 
"deleted-data-files"="1", "deleted-duplicate-files"="2", "deleted-records"="1","removed-files-size"="10",
"total-data-files"="5", "total-delete-files"="0","total-equality-deletes"="0", …
```
=> Core: Prevent duplicate data/delete files

baseline.gradle
This makes it clear where new config option should be added (at the end, grouped semantically, etc.)
Extracted from https://github.com/apache/iceberg/pull/10518, per https://github.com/apache/iceberg/pull/10518#discussion_r1644271939
=> Sort error-prone configuration options

core/src/main/java/org/apache/iceberg/actions/BaseRewriteDataFilesAction.java, core/src/main/java/org/apache/iceberg/actions/RewriteDataFilesCommitManager.java, core/src/main/java/org/apache/iceberg/actions/RewritePositionDeletesCommitManager.java, spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteDataFilesAction.java, spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteDataFilesAction.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/actions/RewriteManifestsSparkAction.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/source/SparkPositionDeltaWrite.java, spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/source/SparkWrite.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/actions/TestRewriteDataFilesAction.java
Upstream callers of the transaction/snapshot producer APIs such as engines like Spark currently handle CommitStateUnknown exceptions to avoid cleaning up data files when it's unclear if the commit was successful or not. For example, see the rewrite data files procedure here: https://github.com/apache/iceberg/blob/main/core/src/main/java/org/apache/iceberg/actions/RewriteDataFilesCommitManager.java#L116
Currently, we only cleanup metadata files if strict cleanup is enabled (default true) and it's a cleanable failure. We should extend this to data file cleanups that upstream callers may do. To do that we can throw a commit state unknown exception in SnapshotProducer/BaseTransaction if strict cleanup is enabled and it's not a cleanable failure. Then engines won't go and cleanup data files.
=> Core, Spark: Spark writes/actions should only perform cleanup if failure is cleanable

site/docs/contribute.md
Java 17 is equally supported build-time JVM.
This syncs the wording between contribute.md and README.md.
=> Allow Java 17 in contribute.md

spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/actions/RewriteManifestsSparkAction.java, spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/SparkPositionDeltaWrite.java, spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/SparkWrite.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/actions/RewriteManifestsSparkAction.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/source/SparkPositionDeltaWrite.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/source/SparkWrite.java
Backport https://github.com/apache/iceberg/pull/10373 to Spark 3.3 and 3.4 to only perform eager cleanups in Spark writes when the failure is cleanable.
=> Spark: Backport #10373 to Spark 3.3 and 3.4

spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/source/SparkScanBuilder.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestDataSourceOptions.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/sql/TestAggregatePushDown.java
Enable Aggregate push down for incremental scan. Here is the original [PR](https://github.com/apache/iceberg/pull/7636)
=> Support Aggregate push down for incremental scan

core/src/main/java/org/apache/iceberg/BaseEntriesTable.java, core/src/test/java/org/apache/iceberg/MetadataTableScanTestBase.java, core/src/test/java/org/apache/iceberg/TestMetadataTableScans.java
Skip either data or delete manifest when reading entries table by filter on its `data_file.content`. Build a  new ManifestContentEvaluator in entries metadata table.
Can you take a look ? @szehon-ho @aokolnychyi
=> Core: pushdown data_file.content when filter manifests in entries table

spark/v3.3/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRemoveOrphanFilesProcedure.java, spark/v3.4/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRemoveOrphanFilesProcedure.java, spark/v3.5/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestRemoveOrphanFilesProcedure.java
This PR remove the useless code in test case `TestRemoveOrphanFilesProcedure.testConcurrentRemoveOrphanFiles()` for Spark 3.5, 3.4 and 3.3. The variable `metadataLocation` is declared and assigned a value, but not used anywhere.
=> Spark: Remove useless code in TestRemoveOrphanFilesProcedure

build.gradle, gradle/wrapper/gradle-wrapper.properties, gradlew
=> Build: Upgrade to gradle 8.8

spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/source/SparkScanBuilder.java, spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/source/TestDataSourceOptions.java, spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/sql/TestAggregatePushDown.java
This back-ports https://github.com/apache/iceberg/pull/10538/ to spark3.4
=> Spark3.4: Support Aggregate push down for incremental scan

aws-bundle/build.gradle, azure-bundle/build.gradle, build.gradle, flink/v1.17/build.gradle, flink/v1.18/build.gradle, flink/v1.19/build.gradle, gcp-bundle/build.gradle, hive-runtime/build.gradle, hive3-orc-bundle/build.gradle, spark/v3.3/build.gradle, spark/v3.4/build.gradle, spark/v3.5/build.gradle
The version of Jackson that comes with Parquet 1.14.1 carries JDK 21 specific code. this is not suported by the current version of the shadow plugin: https://github.com/johnrengelman/shadow/pull/876 There is a fork that actually fixes this.
=> Build: Move to `goooler` shadow plugin

core/src/main/java/org/apache/iceberg/DataTaskParser.java, core/src/main/java/org/apache/iceberg/FileScanTaskParser.java, core/src/main/java/org/apache/iceberg/ScanTaskParser.java, core/src/main/java/org/apache/iceberg/StaticDataTask.java, core/src/test/java/org/apache/iceberg/TestDataTaskParser.java, core/src/test/java/org/apache/iceberg/TestFileScanTaskParser.java, core/src/test/java/org/apache/iceberg/TestScanTaskParser.java, flink/v1.17/flink/src/main/java/org/apache/iceberg/flink/source/split/IcebergSourceSplit.java, flink/v1.18/flink/src/main/java/org/apache/iceberg/flink/source/split/IcebergSourceSplit.java, flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/source/split/IcebergSourceSplit.java
issue #9597 
Java implementation only adds serialization for `StaticDataTask`. Other task types should be added in a follow-up PR , which is ready in my fork. with the additional parsers, `TestFlinkMetaDataTable` can pass with FLIP-27 source using JSON serializers.
https://github.com/stevenzwu/iceberg/commit/59445b7342bd7c37294dfcaf002673af758e456d
=> Core: add a new task-type field to task JSON serialization. add data task JSON serialization implementation.

azure/src/main/java/org/apache/iceberg/azure/AzureProperties.java, azure/src/test/java/org/apache/iceberg/azure/AzurePropertiesTest.java
As `StorageSharedKeyCredential` is not serializable, shared key auth doesn't work with Spark.
=> Make AzureProperties w/ shared-key creds serializable

docs/mkdocs.yml
Add entry to the sidebar linking to the official BigQuery Iceberg tables support.
=> Docs: Add BigQuery docs url to sidebar

.github/workflows/java-ci.yml
This guarantees the build will succeed locally.
=> Run CI checks on all supported JDKs

.github/workflows/api-binary-compatibility.yml, .github/workflows/delta-conversion-ci.yml, .github/workflows/flink-ci.yml, .github/workflows/hive-ci.yml, .github/workflows/java-ci.yml, .github/workflows/open-api.yml, .github/workflows/spark-ci.yml
The CI scripts are meant to run on release maintenance branches such as 1.5.x. They were run for releases up to 1.0 because of the `0.*` pattern
This commit:
- includes `1.*` branches (but that's likely needs to be propagated to existing branches)
- includes `2.*` branches foreseeing imminent 2.0 release
- changes the `0.**` pattern to `0.*`. Multiple asterisks are needed to match branch names including `/` but release branche naming convention do not expect such branch names.
=> Fix CI script inclusion of release branches

core/src/main/java/org/apache/iceberg/util/ParallelIterable.java, core/src/test/java/org/apache/iceberg/util/TestParallelIterable.java
This patch is a part for fix #7843 , we will need to add `BlockingParallelIterable` to fix the whole problem.
=> Core: Fix ParallelIterable memory leak where queue continues to be populated even after iterator close 

flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/HadoopTableExtension.java, flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSink.java, flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkBranch.java, flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkV2.java, flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkV2Base.java, flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkV2Branch.java, flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/source/TestFlinkSourceSql.java, flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/source/TestIcebergSourceSql.java, flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/source/TestSqlBase.java, flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/source/reader/ReaderUtil.java, flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/source/reader/TestColumnStatsWatermarkExtractor.java, flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/HadoopTableExtension.java, flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSink.java, flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkBranch.java, flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkV2.java, flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkV2Base.java, flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/sink/TestFlinkIcebergSinkV2Branch.java, flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/source/TestFlinkSourceSql.java, flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/source/TestIcebergSourceSql.java, flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/source/TestSqlBase.java, flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/source/reader/ReaderUtil.java, flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/source/reader/TestColumnStatsWatermarkExtractor.java
Backport Flink 1.19 changes in https://github.com/apache/iceberg/pull/10358 to 1.17 and 1.18
Migrate the following classes in `iceberg-flink`  to JUnit 5 for https://github.com/apache/iceberg/issues/9087
`FlinkTestBase` inherited classes:
And newly created file for `HadoopTableResource` alternative:
=> Backport HadoopCatalog related classes in Flink

api/src/test/java/org/apache/iceberg/metrics/TestFixedReservoirHistogram.java, flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/data/FlinkParquetReaders.java, flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/source/assigner/TestWatermarkBasedSplitAssigner.java, orc/src/main/java/org/apache/iceberg/orc/ExpressionToSearchArgument.java
These locations popped up in IntelliJ, and the suggested fixes looked correct, so raising this PR.
=> Fix some `long` casting issues

core/src/main/java/org/apache/iceberg/rest/RESTSessionCatalog.java, core/src/test/java/org/apache/iceberg/rest/TestRESTCatalog.java
See #10256 for context.
As requested, this change disallows overriding the `credential` property in table sessions, by introducing an allow-list of auth-related properties that can be overridden in such situations.
Only the `token` property and properties used to exchange one token for another (`urn:ietf:params:oauth:token-type:*`) are now allowed.
=> REST: disallow overriding "credential" in table sessions

core/src/main/java/org/apache/iceberg/rest/auth/OAuth2Util.java, core/src/test/java/org/apache/iceberg/rest/RESTCatalogAdapter.java
The REST client wrongly assumes that the `issued_token_type` field is present in all OAuth responses, but that isn't true: e.g. in the `client_credentials` flow, this field is undefined. See RFC 6749, section 4.4.3:
https://datatracker.ietf.org/doc/html/rfc6749#section-4.4.3
This causes the client to crash when creating a tokens exchange request, since the issued token type becomes the request's subject token type, which is mandatory.
This has been verified against a Keycloak 24.0 server.
This change fixes this issue by assuming that the issued token type is an access token, if the response did not specify any token type.
This change also fixes `RESTCatalogAdapter`: it was incorrectly including the `issued_token_type` field in `client_credentials` responses, thus masking many test …
=> Core: Assume issued_token_type is access_token to fully comply with RFC 6749

core/src/main/java/org/apache/iceberg/rest/auth/OAuth2Util.java
=> Core: Handles possible heap data corruption of `OAuth2Util.AuthSession#headers`

core/src/main/java/org/apache/iceberg/TableMetadata.java, core/src/main/java/org/apache/iceberg/rest/CatalogHandlers.java, core/src/test/java/org/apache/iceberg/catalog/CatalogTests.java
This PR fix the problems of `Cannot downgrade v2 table to v1` when creating v1 table on REST Catalog.
Fix issue: #8756
=> Core: Fix create v1 table on REST Catalog

flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/source/SplitHelpers.java, flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/source/assigner/SplitAssignerTestBase.java, flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/source/assigner/TestDefaultSplitAssigner.java, flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/source/assigner/TestFileSequenceNumberBasedSplitAssigner.java, flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/source/assigner/TestWatermarkBasedSplitAssigner.java, flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/source/enumerator/TestContinuousIcebergEnumerator.java, flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/source/enumerator/TestContinuousSplitPlannerImpl.java, flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/source/enumerator/TestContinuousSplitPlannerImplStartStrategy.java, flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/source/enumerator/TestEnumerationHistory.java, flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/source/enumerator/TestIcebergEnumeratorStateSerializer.java, flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/source/reader/ReaderFunctionTestBase.java, flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/source/reader/ReaderUtil.java, flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/source/reader/TestArrayBatchRecords.java, flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/source/reader/TestArrayPoolDataIteratorBatcherRowData.java, flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/source/reader/TestIcebergSourceReader.java, flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/source/reader/TestRowDataReaderFunction.java, flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/source/split/TestIcebergSourceSplitSerializer.java
Migrate the following classes in `iceberg-flink`  to JUnit 5 for https://github.com/apache/iceberg/issues/9087
Curretly only including Flink 1.19.
=> Migrate source package in Flink

spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/source/SparkScanBuilder.java, spark/v3.5/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkMetadataColumns.java
support of 
`SELECT *, _partition from iceberg.foo.bar` when foo.bar table has over 1000 columns defined
=> Spark: support read of partition metadata column when table is over 1k

api/src/test/java/org/apache/iceberg/Parameter.java, build.gradle, flink/v1.17/build.gradle, flink/v1.18/build.gradle, flink/v1.19/build.gradle, spark/v3.3/build.gradle, spark/v3.4/build.gradle
Most modules have already been converted to JUnit5, except for Flink and Spark.
Defining the JUnit4 dependency only where necessary reduces the risk that new JUnit4-style tests are being added in the already converted modules.
=> Build: Define JUnit4 dependency only where necessary

aws-bundle/build.gradle, azure-bundle/build.gradle, gcp-bundle/build.gradle, hive3-orc-bundle/build.gradle
This excludes `slf4j-api` from being shadowed into `iceberg-aws-bundle`, `iceberg-azure-bundle`, `iceberg-gcp-bundle`, and `iceberg-hive3-orc-bundle`. This uses the same exclude pattern established by `iceberg-bundled-guava`. 
Fixes #10534
=> Build: don't include slf4j-api in bundled JARs

core/src/main/java/org/apache/iceberg/BaseMetastoreTableOperations.java
`write.metadata.previous-versions-max` is used to control previous version of metadata.json files on commit, default to 100. I believe we can tried to batch the deletion together if io supports it
For testing, it's already covered by testMetadataFileLocationsRemovalAfterCommit in CatalogTests.java
=> Core: use bulk delete when removing old metadata.json files

core/src/main/java/org/apache/iceberg/SerializableTable.java
required for [HIVE-27101](https://issues.apache.org/jira/browse/HIVE-27101): Support incremental materialized view rebuild when Iceberg source tables have insert operation only
=> Core: Expose table incremental scan for appends API  in SerializableTable

core/src/main/java/org/apache/iceberg/rest/RESTSessionCatalog.java, open-api/rest-catalog-open-api.py, open-api/rest-catalog-open-api.yaml
This PR implements "M1" of [this document](https://docs.google.com/document/d/1Xi5MRk8WdBWFC3N_eSmVcrLhk3yu5nJ9x_wC0ec6kVQ/), see #10537.
=> OpenAPI: Deprecate `oauth/tokens` endpoint

core/src/main/java/org/apache/iceberg/jdbc/JdbcCatalog.java, core/src/test/java/org/apache/iceberg/jdbc/TestJdbcCatalog.java
JdbcCatalog.listNamespaces returned unexpected namespaces because of `LIKE` with `%`. 
The updated `testListNamespace` test fails without this change:
```java
List<Namespace> nsp1 = catalog.listNamespaces(Namespace.of("db"));
assertThat(nsp1).hasSize(3);
Expected size: 3 but was: 4 in:
[db.ns1, db.ns2, db.ns3, db2.ns4]
java.lang.AssertionError: 
Expected size: 3 but was: 4 in:
[db.ns1, db.ns2, db.ns3, db2.ns4]
```
Fixes #10213
=> Core: Exclude unexpected namespaces JdbcCatalog.listNamespaces

core/src/main/java/org/apache/iceberg/util/PartitionSet.java, core/src/test/java/org/apache/iceberg/TestReplacePartitions.java
Partition values can be NULLs, or we can have NULLs because of the VOID transforms. If a conflict is found in such partitions we get a NullPointerException instead of a proper error message.
=> Core: Fix NPE during conflict handling of NULL partitions

spark/v3.3/spark/src/main/java/org/apache/iceberg/spark/source/SparkScanBuilder.java, spark/v3.3/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkMetadataColumns.java, spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/source/SparkScanBuilder.java, spark/v3.4/spark/src/test/java/org/apache/iceberg/spark/source/TestSparkMetadataColumns.java
Backport of pull request #10547 but looks like junit5 and assertJ is not there so keep the original unit test style. Also skip the vectorized read of ORC in Spark 3.3 unit tests
=> Spark 3.3/3.4: support read of partition metadata column when table is over 1k

open-api/rest-catalog-open-api.py, open-api/rest-catalog-open-api.yaml
Their property names are defined in https://github.com/apache/iceberg/blob/6e21bbf4c4cd2c8351a64636f91d05d00492dff2/core/src/main/java/org/apache/iceberg/TableMetadataParser.java#L111-L112 and have been wrong in the REST spec
=> OpenAPI: Fix property names for stats/partition stats

hive3/src/main/java/org/apache/iceberg/mr/hive/serde/objectinspector/IcebergTimestampObjectInspectorHive3.java
```
.../hive3/src/main/java/org/apache/iceberg/mr/hive/serde/objectinspector/IcebergTimestampObjectInspectorHive3.java:60: warning: [JavaLocalDateTimeGetNano] localDateTime.getNano() only accesss the nanos-of-second field. It's rare to only use getNano() without a nearby getSecond() call.
timestamp.setNanos(time.getNano());
^
(see https://errorprone.info/bugpattern/JavaLocalDateTimeGetNano)
```
=> Nit: fix/suppress false-positivie errorprone warning

format/spec.md
replaced with link to Java implementation and note for additional context.
See the discussion thread on dev mailing list.
https://lists.apache.org/thread/2ty27yx4q0zlqd5h71cyyhb5k47yf9bv
=> Spec: remove the JSON spec for content file and file scan task sections

site/docs/benchmarks.md, site/docs/concepts/catalog.md, site/docs/how-to-release.md
Some docs were referring to `master`, update them to refer to `main`.
=> Update references to main branch

spark/v3.3/spark-extensions/src/test/java/org/apache/iceberg/spark/extensions/TestCopyOnWriteMerge.java
=> Spark 3.3: Ignore flaky test taking up all device space

.github/workflows/stale.yml
Stale PR bot is finally working after #10706
https://github.com/apache/iceberg/actions/runs/9965906264/job/27537049317#step:2:1119
Based on above stats, it has only processed 23 PRs. As each issue/PR requires 3 operation (comment, label, fetch). 
Also, GH Iceberg repo has `14896` operation left during that time. Hence, increasing the operations limit a bit more. (it will just use 100 more operations)
=> Infra: Increase operation per limit for stale bot workflow

docs/docs/branching.md, docs/docs/spark-writes.md
Moved `Writing to branches` into SQL and data frame writes section and added examples of writing to branches with dataframes.
=> [Docs] Add examples for DataFrame branch writes

core/src/main/java/org/apache/iceberg/TableMetadata.java
This constructor should be made private. Note: If 1.6.0 release passes as is, this will have to go through a deprecation cycle rather than just making it private directly. 
Accidentally added a new public construcotr here https://github.com/apache/iceberg/commit/f236722f41a7fb35cffb80629f0516bb7b6c90b7#diff-c540a31e66b157a8f080433c82a29a070096d0e08c6578a0099153f1229bdb7aR913 when it should've been private.
=> Core: Make new TableMetadata.Builder constructor private

common/src/main/java/org/apache/iceberg/common/DynFields.java, common/src/main/java/org/apache/iceberg/common/DynMethods.java
The release 1.6.0 RC0 won't be promoted and in the meantime the deprecation was merged. The RC1 will be made of the main branch, so will include the deprecations, so the version in the deprecation message should be updated.
=> Update the version in deprecation messages

core/src/main/java/org/apache/iceberg/MergingSnapshotProducer.java, core/src/test/java/org/apache/iceberg/TestMergeAppend.java
Currently the `table.newAppend()` API expects users to provide Datafiles with the same PartitionSpec via `.appendFile()`. 
Failure to do so [raises](https://github.com/apache/iceberg/blob/1a4f23bc0e6cda520ca815f2a245f5f21bfbc24f/core/src/main/java/org/apache/iceberg/MergingSnapshotProducer.java#L258) a `ValidationException("Invalid data file, expected spec id: %d", dataSpec.specId())`. 
CMIIW but the Iceberg spec doesn't seem to impose any such restriction. 
The only related restriction I could find was in the [manifests section](https://iceberg.apache.org/spec/#manifests) which says: 
> A manifest stores files for a single partition spec. 
We can easily work around this by writing multiple manifests, one for each spec for which files are being appended. 
In the iceberg-kafka-connect …
=> Core: Support appending files with different specs

core/src/main/java/org/apache/iceberg/ManifestFiles.java
It was guarding `CONTENT_CACHES` access, but this field is a concurrent data structure (`Caffeine`) and does not need external synchronization.
=> Remove unnecessary class-level synchronized in ManifestFiles

api/src/main/java/org/apache/iceberg/Table.java, gradlew
This PR fix typos in the comment of interface methods in `Table`, and remove duplicate messages in the comment in `gradlew`
=> Api, Build: Fix typo in comments in `Table` and `gradlew`

core/src/main/java/org/apache/iceberg/util/ParallelIterable.java, core/src/test/java/org/apache/iceberg/util/TestParallelIterable.java
ParallelIterable schedules 2 * WORKER_THREAD_POOL_SIZE tasks for processing input iterables. This defaults to 2 * # CPU cores.  When one or some of the input iterables are considerable in size and the ParallelIterable consumer is not quick enough, this could result in unbounded allocation inside `ParallelIterator.queue`. This commit bounds the queue. When queue is full, the tasks yield and get removed from the executor. They are resumed when consumer catches up.
Follows https://github.com/apache/iceberg/pull/9402
Alternative to https://github.com/apache/iceberg/pull/7844
=> Core: Limit memory used by ParallelIterable

flink/v1.17/build.gradle, flink/v1.18/build.gradle, flink/v1.19/build.gradle
Now that https://github.com/apache/iceberg/issues/9087 is complete we can remove the JUnit4 dependency from Flink
=> Flink: Remove JUnit4 dependency

core/src/main/java/org/apache/iceberg/BaseEntriesTable.java, core/src/main/java/org/apache/iceberg/BaseFilesTable.java, core/src/test/java/org/apache/iceberg/TestMetadataTableScans.java
Spark queries of Metadata Tables will often try to check row count estimates repeatedly during planning phase, like picking a join strategy.
By default, this involves an extra call to read the manifest file header, as the default logic on the BaseContentScanTask is as follows:
```
static long estimateRowsCount(long length, ContentFile<?> file) {
long[] splitOffsets = splitOffsets(file);
long splitOffset = splitOffsets != null ? splitOffsets[0] : 0L;
double scannedFileFraction = ((double) length) / (file.fileSizeInBytes() - splitOffset);
return (long) (scannedFileFraction * file.recordCount());
}
```
However, we actually have this information in the metadata and can just return it directly without reading the file header.
This can save many calls on the Spark driver for planning (one call …
=> Core: Add estimateRowCount for Files and Entries Metadata Tables

.baseline/checkstyle/checkstyle.xml
This is a follow-up PR for the discussion at #10673 where @findepi pointed out these two things w.r.t. the checkstyle definition:
- We could use possessive quantifiers in the regexps for performance reasons.
- Some custom error messages do not really have a lot of added value, so we'd better remove them.
=> Update checkstyle definition

api/src/main/java/org/apache/iceberg/RewriteManifests.java
Fixes a small typo I noticed when reading the rewrite manifests API
=> API: Fix typo in RewriteManifestFiles java doc

.github/workflows/delta-conversion-ci.yml, .github/workflows/flink-ci.yml, .github/workflows/hive-ci.yml, .github/workflows/java-ci.yml, .github/workflows/spark-ci.yml, README.md, baseline.gradle, build.gradle, jmh.gradle, site/docs/contribute.md, spark/v3.3/build.gradle, spark/v3.4/build.gradle, spark/v3.5/build.gradle
This is currently the latest Java LTS version, so we should support
building with it.
=> Support building with Java 21

hive-metastore/src/main/java/org/apache/iceberg/hive/HiveCatalog.java
This PR fixes the following warning:
```
WARN S3FileIO: Unclosed S3FileIO instance created by:
org.apache.iceberg.aws.s3.S3FileIO.initialize(S3FileIO.java:359)
org.apache.iceberg.CatalogUtil.loadFileIO(CatalogUtil.java:350)
org.apache.iceberg.hive.HiveCatalog.initialize(HiveCatalog.java:111)
...
```
=> Hive: close the fileIO client when closing the hive catalog

site/docs/contribute.md
* make implementation match definition in interface
* clarify why adding a new interface method breaks compatibility.
=> Docs: Make compatibility example consistent.

mr/src/main/java/org/apache/iceberg/mr/mapreduce/IcebergInputFormat.java, mr/src/test/java/org/apache/iceberg/mr/TestIcebergInputFormats.java
Fix [10639](https://github.com/apache/iceberg/issues/10639)
All users use the same static thread pool in hiveserver2, the ugi in the thread is always the first user to use the thread.
I think each fetch task will new its own thread pool like [HIVE-28276](https://github.com/apache/hive/commit/45867be6cb5308566e4cf16c7b4cf8081085b58c)
=> mr：Fix issues 10639

core/src/main/java/org/apache/iceberg/util/ParallelIterable.java, core/src/test/java/org/apache/iceberg/util/TestParallelIterable.java
(backport #10691)
ParallelIterable schedules 2 * WORKER_THREAD_POOL_SIZE tasks for processing input iterables. This defaults to 2 * # CPU cores.  When one or some of the input iterables are considerable in size and the ParallelIterable consumer is not quick enough, this could result in unbounded allocation inside `ParallelIterator.queue`. This commit bounds the queue. When queue is full, the tasks yield and get removed from the executor. They are resumed when consumer catches up.
(cherry picked from commit 7831a8dfc3a2de546ca069f4fc1e7afd03777554)
=> Core: Limit ParallelIterable memory consumption by yielding in tasks

flink/v1.17/flink/src/main/java/org/apache/iceberg/flink/sink/shuffle/SortKeySerializer.java, flink/v1.17/flink/src/test/java/org/apache/iceberg/flink/sink/shuffle/TestSortKeySerializerSnapshot.java, flink/v1.18/flink/src/main/java/org/apache/iceberg/flink/sink/shuffle/SortKeySerializer.java, flink/v1.18/flink/src/test/java/org/apache/iceberg/flink/sink/shuffle/TestSortKeySerializerSnapshot.java, flink/v1.19/flink/src/main/java/org/apache/iceberg/flink/sink/shuffle/SortKeySerializer.java, flink/v1.19/flink/src/test/java/org/apache/iceberg/flink/sink/shuffle/TestSortKeySerializerSnapshot.java
also add unit tests for serializer snapshot.
=> Flink: improve snapshot compatibility check by comparing projected sort schema in SortKeySerializer

site/docs/releases.md
Use link url instead of descriptions
=> Docs: Use link addresses instead of descriptions in releases.md
